terrain_level_data {
  terrain_level: 300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1593531.38
      sim_grid_pos_y: 1235655
    }
    terrain_level_point {
      sim_grid_pos_x: 1592749.12
      sim_grid_pos_y: 1242043.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1592563.12
      sim_grid_pos_y: 1242015.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1593362.38
      sim_grid_pos_y: 1235607.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1593610.12
      sim_grid_pos_y: 1235602.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1592811.38
      sim_grid_pos_y: 1242125.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1592483.25
      sim_grid_pos_y: 1242076.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1593301.5
      sim_grid_pos_y: 1235515.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1593688.75
      sim_grid_pos_y: 1235550.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1592873.75
      sim_grid_pos_y: 1242207.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1592403.38
      sim_grid_pos_y: 1242136.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1593240.62
      sim_grid_pos_y: 1235424
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1593767.5
      sim_grid_pos_y: 1235497.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1592936
      sim_grid_pos_y: 1242289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1592323.5
      sim_grid_pos_y: 1242197.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1593179.75
      sim_grid_pos_y: 1235332.25
    }
  }
}
