terrain_level_data {
  terrain_level: 470
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3006217.5
      sim_grid_pos_y: 93666.8672
    }
    terrain_level_point {
      sim_grid_pos_x: 3006451.25
      sim_grid_pos_y: 94262.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 3008779.25
      sim_grid_pos_y: 98253.6719
    }
    terrain_level_point {
      sim_grid_pos_x: 3010700.5
      sim_grid_pos_y: 97020.9531
    }
    terrain_level_point {
      sim_grid_pos_x: 3007343
      sim_grid_pos_y: 91519.7891
    }
    terrain_level_point {
      sim_grid_pos_x: 3006463.5
      sim_grid_pos_y: 92021.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 3006110.25
      sim_grid_pos_y: 91488.3203
    }
    terrain_level_point {
      sim_grid_pos_x: 3005974
      sim_grid_pos_y: 91361.6328
    }
    terrain_level_point {
      sim_grid_pos_x: 3005757
      sim_grid_pos_y: 91240.5625
    }
    terrain_level_point {
      sim_grid_pos_x: 3005345.5
      sim_grid_pos_y: 91120.8
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 3005336.25
      sim_grid_pos_y: 91086.0469
    }
    terrain_level_point {
      sim_grid_pos_x: 3005310.25
      sim_grid_pos_y: 91113.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 3006188.75
      sim_grid_pos_y: 93677.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 3006423.5
      sim_grid_pos_y: 94276.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3008768.75
      sim_grid_pos_y: 98296.9
    }
    terrain_level_point {
      sim_grid_pos_x: 3010742.5
      sim_grid_pos_y: 97030.6094
    }
    terrain_level_point {
      sim_grid_pos_x: 3007353.75
      sim_grid_pos_y: 91478.2734
    }
    terrain_level_point {
      sim_grid_pos_x: 3006473.25
      sim_grid_pos_y: 91980.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 3006134
      sim_grid_pos_y: 91468.2734
    }
    terrain_level_point {
      sim_grid_pos_x: 3005992.25
      sim_grid_pos_y: 91336.5859
    }
    terrain_level_point {
      sim_grid_pos_x: 3005769
      sim_grid_pos_y: 91211.9922
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 3005326.75
      sim_grid_pos_y: 91051.2891
    }
    terrain_level_point {
      sim_grid_pos_x: 3005275.25
      sim_grid_pos_y: 91105.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 3006159.75
      sim_grid_pos_y: 93688.0781
    }
    terrain_level_point {
      sim_grid_pos_x: 3006395.75
      sim_grid_pos_y: 94289.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 3008758.5
      sim_grid_pos_y: 98340.1094
    }
    terrain_level_point {
      sim_grid_pos_x: 3010784.25
      sim_grid_pos_y: 97040.2422
    }
    terrain_level_point {
      sim_grid_pos_x: 3007364.5
      sim_grid_pos_y: 91436.7578
    }
    terrain_level_point {
      sim_grid_pos_x: 3006483
      sim_grid_pos_y: 91939.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 3006157.5
      sim_grid_pos_y: 91448.2422
    }
    terrain_level_point {
      sim_grid_pos_x: 3006010.5
      sim_grid_pos_y: 91311.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 3005781
      sim_grid_pos_y: 91183.4375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 3005317.5
      sim_grid_pos_y: 91016.5391
    }
    terrain_level_point {
      sim_grid_pos_x: 3.00524e+06
      sim_grid_pos_y: 91097.6562
    }
    terrain_level_point {
      sim_grid_pos_x: 3006131
      sim_grid_pos_y: 93698.6719
    }
    terrain_level_point {
      sim_grid_pos_x: 3006368
      sim_grid_pos_y: 94303.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 3008748
      sim_grid_pos_y: 98383.3281
    }
    terrain_level_point {
      sim_grid_pos_x: 3010826.25
      sim_grid_pos_y: 97049.9
    }
    terrain_level_point {
      sim_grid_pos_x: 3007375.25
      sim_grid_pos_y: 91395.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 3006492.75
      sim_grid_pos_y: 91898.9531
    }
    terrain_level_point {
      sim_grid_pos_x: 3006181.25
      sim_grid_pos_y: 91428.2
    }
    terrain_level_point {
      sim_grid_pos_x: 3006028.75
      sim_grid_pos_y: 91286.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 3005793
      sim_grid_pos_y: 91154.8828
    }
  }
}
