terrain_level_data {
  terrain_level: 780
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2277451
      sim_grid_pos_y: 1022523.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2277012.75
      sim_grid_pos_y: 1022097.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2276623.5
      sim_grid_pos_y: 1022582.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2276981.75
      sim_grid_pos_y: 1022956.69
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2.27701e+06
      sim_grid_pos_y: 1022051.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2276582.75
      sim_grid_pos_y: 1022584.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2276980.5
      sim_grid_pos_y: 1022999.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2277495.75
      sim_grid_pos_y: 1022523.94
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2277007.25
      sim_grid_pos_y: 1022005.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2276541.75
      sim_grid_pos_y: 1022585.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2276979
      sim_grid_pos_y: 1023042.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2277540.25
      sim_grid_pos_y: 1022524.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2277004.5
      sim_grid_pos_y: 1021960.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2276501
      sim_grid_pos_y: 1022587.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2276977.75
      sim_grid_pos_y: 1023086
    }
    terrain_level_point {
      sim_grid_pos_x: 2277585
      sim_grid_pos_y: 1022525.12
    }
  }
}
