terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 827736.125
      sim_grid_pos_y: 1894781.12
    }
    terrain_level_point {
      sim_grid_pos_x: 828552.812
      sim_grid_pos_y: 1894058
    }
    terrain_level_point {
      sim_grid_pos_x: 828535.375
      sim_grid_pos_y: 1893672.12
    }
    terrain_level_point {
      sim_grid_pos_x: 829528.812
      sim_grid_pos_y: 1893378.88
    }
    terrain_level_point {
      sim_grid_pos_x: 829493.875
      sim_grid_pos_y: 1896306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 829635
      sim_grid_pos_y: 1896534.75
    }
    terrain_level_point {
      sim_grid_pos_x: 829644.5
      sim_grid_pos_y: 1896766.62
    }
    terrain_level_point {
      sim_grid_pos_x: 830005.375
      sim_grid_pos_y: 1899519.38
    }
    terrain_level_point {
      sim_grid_pos_x: 830243.438
      sim_grid_pos_y: 1900096.88
    }
    terrain_level_point {
      sim_grid_pos_x: 830429.188
      sim_grid_pos_y: 1900248.5
    }
    terrain_level_point {
      sim_grid_pos_x: 830374.812
      sim_grid_pos_y: 1900365.62
    }
    terrain_level_point {
      sim_grid_pos_x: 830320
      sim_grid_pos_y: 1900643
    }
    terrain_level_point {
      sim_grid_pos_x: 829972.75
      sim_grid_pos_y: 1901303.38
    }
    terrain_level_point {
      sim_grid_pos_x: 829888.625
      sim_grid_pos_y: 1901754.75
    }
    terrain_level_point {
      sim_grid_pos_x: 829607.5
      sim_grid_pos_y: 1902616.88
    }
    terrain_level_point {
      sim_grid_pos_x: 829622.688
      sim_grid_pos_y: 1902839.25
    }
    terrain_level_point {
      sim_grid_pos_x: 829022.312
      sim_grid_pos_y: 1903032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 828784.5
      sim_grid_pos_y: 1901566.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 829617.312
      sim_grid_pos_y: 1896272
    }
    terrain_level_point {
      sim_grid_pos_x: 829756.625
      sim_grid_pos_y: 1896497.5
    }
    terrain_level_point {
      sim_grid_pos_x: 829767.188
      sim_grid_pos_y: 1896756.12
    }
    terrain_level_point {
      sim_grid_pos_x: 830125.25
      sim_grid_pos_y: 1899487.38
    }
    terrain_level_point {
      sim_grid_pos_x: 830345.312
      sim_grid_pos_y: 1900021.25
    }
    terrain_level_point {
      sim_grid_pos_x: 830581
      sim_grid_pos_y: 1900213.62
    }
    terrain_level_point {
      sim_grid_pos_x: 830492.625
      sim_grid_pos_y: 1900404
    }
    terrain_level_point {
      sim_grid_pos_x: 830437.25
      sim_grid_pos_y: 1900684.38
    }
    terrain_level_point {
      sim_grid_pos_x: 830090.312
      sim_grid_pos_y: 1901344.12
    }
    terrain_level_point {
      sim_grid_pos_x: 830008.125
      sim_grid_pos_y: 1901785.25
    }
    terrain_level_point {
      sim_grid_pos_x: 829731.875
      sim_grid_pos_y: 1902632.25
    }
    terrain_level_point {
      sim_grid_pos_x: 829752
      sim_grid_pos_y: 1902926.88
    }
    terrain_level_point {
      sim_grid_pos_x: 828923.812
      sim_grid_pos_y: 1903193.12
    }
    terrain_level_point {
      sim_grid_pos_x: 828663
      sim_grid_pos_y: 1901586.12
    }
    terrain_level_point {
      sim_grid_pos_x: 827604.312
      sim_grid_pos_y: 1894733.5
    }
    terrain_level_point {
      sim_grid_pos_x: 828427.25
      sim_grid_pos_y: 1894004.88
    }
    terrain_level_point {
      sim_grid_pos_x: 828408.125
      sim_grid_pos_y: 1893581.38
    }
    terrain_level_point {
      sim_grid_pos_x: 829653.812
      sim_grid_pos_y: 1893213.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 829740.75
      sim_grid_pos_y: 1896237.75
    }
    terrain_level_point {
      sim_grid_pos_x: 829878.188
      sim_grid_pos_y: 1896460.25
    }
    terrain_level_point {
      sim_grid_pos_x: 829889.875
      sim_grid_pos_y: 1896745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 830245.188
      sim_grid_pos_y: 1899455.38
    }
    terrain_level_point {
      sim_grid_pos_x: 830447.188
      sim_grid_pos_y: 1899945.62
    }
    terrain_level_point {
      sim_grid_pos_x: 830732.875
      sim_grid_pos_y: 1900178.75
    }
    terrain_level_point {
      sim_grid_pos_x: 830610.438
      sim_grid_pos_y: 1900442.38
    }
    terrain_level_point {
      sim_grid_pos_x: 830554.438
      sim_grid_pos_y: 1900725.88
    }
    terrain_level_point {
      sim_grid_pos_x: 830207.812
      sim_grid_pos_y: 1901385
    }
    terrain_level_point {
      sim_grid_pos_x: 830127.562
      sim_grid_pos_y: 1901815.75
    }
    terrain_level_point {
      sim_grid_pos_x: 829856.25
      sim_grid_pos_y: 1902647.75
    }
    terrain_level_point {
      sim_grid_pos_x: 829881.312
      sim_grid_pos_y: 1903014.62
    }
    terrain_level_point {
      sim_grid_pos_x: 828825.25
      sim_grid_pos_y: 1903354.12
    }
    terrain_level_point {
      sim_grid_pos_x: 828541.438
      sim_grid_pos_y: 1901605.38
    }
    terrain_level_point {
      sim_grid_pos_x: 827472.438
      sim_grid_pos_y: 1894686
    }
    terrain_level_point {
      sim_grid_pos_x: 828301.688
      sim_grid_pos_y: 1893951.75
    }
    terrain_level_point {
      sim_grid_pos_x: 828280.875
      sim_grid_pos_y: 1893490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 829778.812
      sim_grid_pos_y: 1893048.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 829864.188
      sim_grid_pos_y: 1896203.5
    }
    terrain_level_point {
      sim_grid_pos_x: 829999.812
      sim_grid_pos_y: 1896423
    }
    terrain_level_point {
      sim_grid_pos_x: 830012.625
      sim_grid_pos_y: 1896735.12
    }
    terrain_level_point {
      sim_grid_pos_x: 830365.062
      sim_grid_pos_y: 1899423.38
    }
    terrain_level_point {
      sim_grid_pos_x: 830549.125
      sim_grid_pos_y: 1.89987e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 830884.688
      sim_grid_pos_y: 1900143.88
    }
    terrain_level_point {
      sim_grid_pos_x: 830728.312
      sim_grid_pos_y: 1900480.75
    }
    terrain_level_point {
      sim_grid_pos_x: 830671.688
      sim_grid_pos_y: 1900767.25
    }
    terrain_level_point {
      sim_grid_pos_x: 830325.375
      sim_grid_pos_y: 1901425.75
    }
    terrain_level_point {
      sim_grid_pos_x: 830247.062
      sim_grid_pos_y: 1901846.12
    }
    terrain_level_point {
      sim_grid_pos_x: 829980.625
      sim_grid_pos_y: 1902663.12
    }
    terrain_level_point {
      sim_grid_pos_x: 830010.625
      sim_grid_pos_y: 1903102.25
    }
    terrain_level_point {
      sim_grid_pos_x: 828726.75
      sim_grid_pos_y: 1903515
    }
    terrain_level_point {
      sim_grid_pos_x: 828419.938
      sim_grid_pos_y: 1901624.62
    }
    terrain_level_point {
      sim_grid_pos_x: 827340.625
      sim_grid_pos_y: 1894638.38
    }
    terrain_level_point {
      sim_grid_pos_x: 828176.125
      sim_grid_pos_y: 1893898.5
    }
    terrain_level_point {
      sim_grid_pos_x: 828153.625
      sim_grid_pos_y: 1.8934e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 829903.875
      sim_grid_pos_y: 1892883.38
    }
  }
}
