terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 476721
      sim_grid_pos_y: 1999890.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476200.219
      sim_grid_pos_y: 1999973
    }
    terrain_level_point {
      sim_grid_pos_x: 475171.594
      sim_grid_pos_y: 2000557
    }
    terrain_level_point {
      sim_grid_pos_x: 474598.25
      sim_grid_pos_y: 2000715
    }
    terrain_level_point {
      sim_grid_pos_x: 474278.5
      sim_grid_pos_y: 2000735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 473718.656
      sim_grid_pos_y: 2000518.88
    }
    terrain_level_point {
      sim_grid_pos_x: 473454.562
      sim_grid_pos_y: 2000242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 473042.906
      sim_grid_pos_y: 1999499.88
    }
    terrain_level_point {
      sim_grid_pos_x: 473015.625
      sim_grid_pos_y: 1999023.38
    }
    terrain_level_point {
      sim_grid_pos_x: 473219.219
      sim_grid_pos_y: 1998836.38
    }
    terrain_level_point {
      sim_grid_pos_x: 473355
      sim_grid_pos_y: 1998730.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474040.719
      sim_grid_pos_y: 1998384.12
    }
    terrain_level_point {
      sim_grid_pos_x: 474186.5
      sim_grid_pos_y: 1998354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474294.562
      sim_grid_pos_y: 1.99838e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 474547.531
      sim_grid_pos_y: 1998618.88
    }
    terrain_level_point {
      sim_grid_pos_x: 474891.656
      sim_grid_pos_y: 1998718.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475439.688
      sim_grid_pos_y: 1998827.62
    }
    terrain_level_point {
      sim_grid_pos_x: 475612.031
      sim_grid_pos_y: 1998829.38
    }
    terrain_level_point {
      sim_grid_pos_x: 475972.438
      sim_grid_pos_y: 1998673.75
    }
    terrain_level_point {
      sim_grid_pos_x: 476187.156
      sim_grid_pos_y: 1998646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 476386.938
      sim_grid_pos_y: 1998682.5
    }
    terrain_level_point {
      sim_grid_pos_x: 476641.031
      sim_grid_pos_y: 1998828.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477038.219
      sim_grid_pos_y: 1999124.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477102.969
      sim_grid_pos_y: 1999246.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477122.125
      sim_grid_pos_y: 1999433.38
    }
    terrain_level_point {
      sim_grid_pos_x: 477111.062
      sim_grid_pos_y: 1999566.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477017.312
      sim_grid_pos_y: 1999729
    }
    terrain_level_point {
      sim_grid_pos_x: 476906.531
      sim_grid_pos_y: 1999820.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 474309.656
      sim_grid_pos_y: 1998351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 474563.25
      sim_grid_pos_y: 1998591.38
    }
    terrain_level_point {
      sim_grid_pos_x: 474898.938
      sim_grid_pos_y: 1998688.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475442.875
      sim_grid_pos_y: 1998796.88
    }
    terrain_level_point {
      sim_grid_pos_x: 475605.844
      sim_grid_pos_y: 1998798.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475964.219
      sim_grid_pos_y: 1998643.75
    }
    terrain_level_point {
      sim_grid_pos_x: 476187.969
      sim_grid_pos_y: 1998615.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476397.688
      sim_grid_pos_y: 1998653.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476657.938
      sim_grid_pos_y: 1998803.12
    }
    terrain_level_point {
      sim_grid_pos_x: 477062.156
      sim_grid_pos_y: 1999103.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477132.969
      sim_grid_pos_y: 1999237.62
    }
    terrain_level_point {
      sim_grid_pos_x: 477153
      sim_grid_pos_y: 1999433.12
    }
    terrain_level_point {
      sim_grid_pos_x: 477141.156
      sim_grid_pos_y: 1999575.62
    }
    terrain_level_point {
      sim_grid_pos_x: 477041.188
      sim_grid_pos_y: 1999749.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476922.156
      sim_grid_pos_y: 1999847.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476728.906
      sim_grid_pos_y: 1.99992e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 476210.562
      sim_grid_pos_y: 2000002.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475183.438
      sim_grid_pos_y: 2000585.62
    }
    terrain_level_point {
      sim_grid_pos_x: 474603.375
      sim_grid_pos_y: 2000745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474273.688
      sim_grid_pos_y: 2000766.62
    }
    terrain_level_point {
      sim_grid_pos_x: 473701.156
      sim_grid_pos_y: 2000545.12
    }
    terrain_level_point {
      sim_grid_pos_x: 473429.594
      sim_grid_pos_y: 2000261.12
    }
    terrain_level_point {
      sim_grid_pos_x: 473012.594
      sim_grid_pos_y: 1999508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 472984.062
      sim_grid_pos_y: 1999010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 473199.344
      sim_grid_pos_y: 1998812.88
    }
    terrain_level_point {
      sim_grid_pos_x: 473338.469
      sim_grid_pos_y: 1998704.62
    }
    terrain_level_point {
      sim_grid_pos_x: 474030.562
      sim_grid_pos_y: 1998354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474186.969
      sim_grid_pos_y: 1998323.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 474324.719
      sim_grid_pos_y: 1998323.88
    }
    terrain_level_point {
      sim_grid_pos_x: 474578.969
      sim_grid_pos_y: 1998563.88
    }
    terrain_level_point {
      sim_grid_pos_x: 474906.219
      sim_grid_pos_y: 1998658.88
    }
    terrain_level_point {
      sim_grid_pos_x: 475446.094
      sim_grid_pos_y: 1998766.12
    }
    terrain_level_point {
      sim_grid_pos_x: 475599.625
      sim_grid_pos_y: 1998767.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475956.031
      sim_grid_pos_y: 1998613.75
    }
    terrain_level_point {
      sim_grid_pos_x: 476188.781
      sim_grid_pos_y: 1998584.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476408.406
      sim_grid_pos_y: 1998623.88
    }
    terrain_level_point {
      sim_grid_pos_x: 476674.844
      sim_grid_pos_y: 1998777.38
    }
    terrain_level_point {
      sim_grid_pos_x: 477086.094
      sim_grid_pos_y: 1999083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477162.938
      sim_grid_pos_y: 1999228.5
    }
    terrain_level_point {
      sim_grid_pos_x: 477183.906
      sim_grid_pos_y: 1999432.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477171.219
      sim_grid_pos_y: 1999585
    }
    terrain_level_point {
      sim_grid_pos_x: 477065.094
      sim_grid_pos_y: 1999769.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476937.75
      sim_grid_pos_y: 1999874.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476736.781
      sim_grid_pos_y: 1999949.88
    }
    terrain_level_point {
      sim_grid_pos_x: 476220.906
      sim_grid_pos_y: 2000032
    }
    terrain_level_point {
      sim_grid_pos_x: 475195.312
      sim_grid_pos_y: 2000614.25
    }
    terrain_level_point {
      sim_grid_pos_x: 474608.469
      sim_grid_pos_y: 2000776
    }
    terrain_level_point {
      sim_grid_pos_x: 474268.906
      sim_grid_pos_y: 2000797.75
    }
    terrain_level_point {
      sim_grid_pos_x: 473683.656
      sim_grid_pos_y: 2000571.25
    }
    terrain_level_point {
      sim_grid_pos_x: 473404.625
      sim_grid_pos_y: 2000279.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472982.281
      sim_grid_pos_y: 1999517.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472952.531
      sim_grid_pos_y: 1998997.75
    }
    terrain_level_point {
      sim_grid_pos_x: 473179.469
      sim_grid_pos_y: 1998789.38
    }
    terrain_level_point {
      sim_grid_pos_x: 473321.938
      sim_grid_pos_y: 1998678.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474020.406
      sim_grid_pos_y: 1998325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474187.438
      sim_grid_pos_y: 1998291.88
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 480295.062
      sim_grid_pos_y: 2005138
    }
    terrain_level_point {
      sim_grid_pos_x: 480104.562
      sim_grid_pos_y: 2005502
    }
    terrain_level_point {
      sim_grid_pos_x: 479973.375
      sim_grid_pos_y: 2005474.62
    }
    terrain_level_point {
      sim_grid_pos_x: 479886.562
      sim_grid_pos_y: 2005503.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479835.281
      sim_grid_pos_y: 2005591.62
    }
    terrain_level_point {
      sim_grid_pos_x: 479878.938
      sim_grid_pos_y: 2005804.75
    }
    terrain_level_point {
      sim_grid_pos_x: 479977.219
      sim_grid_pos_y: 2006087
    }
    terrain_level_point {
      sim_grid_pos_x: 480008.812
      sim_grid_pos_y: 2006231.75
    }
    terrain_level_point {
      sim_grid_pos_x: 479813.281
      sim_grid_pos_y: 2006818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479612.344
      sim_grid_pos_y: 2007172.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479456.25
      sim_grid_pos_y: 2007514.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479541.25
      sim_grid_pos_y: 2007870.62
    }
    terrain_level_point {
      sim_grid_pos_x: 479492.438
      sim_grid_pos_y: 2008189.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479429.281
      sim_grid_pos_y: 2008283.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479616.5
      sim_grid_pos_y: 2008665
    }
    terrain_level_point {
      sim_grid_pos_x: 479521.906
      sim_grid_pos_y: 2008968.38
    }
    terrain_level_point {
      sim_grid_pos_x: 480039.062
      sim_grid_pos_y: 2009907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 480170.188
      sim_grid_pos_y: 2010098.62
    }
    terrain_level_point {
      sim_grid_pos_x: 480693.844
      sim_grid_pos_y: 2010245.62
    }
    terrain_level_point {
      sim_grid_pos_x: 480773.875
      sim_grid_pos_y: 2010371.12
    }
    terrain_level_point {
      sim_grid_pos_x: 480833.562
      sim_grid_pos_y: 2010915
    }
    terrain_level_point {
      sim_grid_pos_x: 480679.594
      sim_grid_pos_y: 2011161
    }
    terrain_level_point {
      sim_grid_pos_x: 481063.281
      sim_grid_pos_y: 2011478
    }
    terrain_level_point {
      sim_grid_pos_x: 481215.562
      sim_grid_pos_y: 2011446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 481361.719
      sim_grid_pos_y: 2011082.38
    }
    terrain_level_point {
      sim_grid_pos_x: 481686.156
      sim_grid_pos_y: 2011077.62
    }
    terrain_level_point {
      sim_grid_pos_x: 481929.969
      sim_grid_pos_y: 2011035
    }
    terrain_level_point {
      sim_grid_pos_x: 482195.875
      sim_grid_pos_y: 2011357.12
    }
    terrain_level_point {
      sim_grid_pos_x: 482552.688
      sim_grid_pos_y: 2011155.38
    }
    terrain_level_point {
      sim_grid_pos_x: 482886.594
      sim_grid_pos_y: 2011270.25
    }
    terrain_level_point {
      sim_grid_pos_x: 483635.438
      sim_grid_pos_y: 2011487
    }
    terrain_level_point {
      sim_grid_pos_x: 484388.188
      sim_grid_pos_y: 2012088
    }
    terrain_level_point {
      sim_grid_pos_x: 484911.219
      sim_grid_pos_y: 2011990.38
    }
    terrain_level_point {
      sim_grid_pos_x: 484900.156
      sim_grid_pos_y: 2010896
    }
    terrain_level_point {
      sim_grid_pos_x: 482968
      sim_grid_pos_y: 2008559.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 480289.938
      sim_grid_pos_y: 2005081.38
    }
    terrain_level_point {
      sim_grid_pos_x: 480088.094
      sim_grid_pos_y: 2005467.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479971.469
      sim_grid_pos_y: 2005442.75
    }
    terrain_level_point {
      sim_grid_pos_x: 479865.812
      sim_grid_pos_y: 2005478.38
    }
    terrain_level_point {
      sim_grid_pos_x: 479802.812
      sim_grid_pos_y: 2005586.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479849.219
      sim_grid_pos_y: 2005812.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479947.562
      sim_grid_pos_y: 2006095.38
    }
    terrain_level_point {
      sim_grid_pos_x: 479976.938
      sim_grid_pos_y: 2006230.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479785.031
      sim_grid_pos_y: 2006805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479584.938
      sim_grid_pos_y: 2007158.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479423.906
      sim_grid_pos_y: 2007511.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479509.938
      sim_grid_pos_y: 2007871.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479463.094
      sim_grid_pos_y: 2008177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 479393.844
      sim_grid_pos_y: 2008280.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479583.5
      sim_grid_pos_y: 2008667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479488.656
      sim_grid_pos_y: 2008971.75
    }
    terrain_level_point {
      sim_grid_pos_x: 480012.844
      sim_grid_pos_y: 2009923.62
    }
    terrain_level_point {
      sim_grid_pos_x: 480151.156
      sim_grid_pos_y: 2010125.25
    }
    terrain_level_point {
      sim_grid_pos_x: 480674.219
      sim_grid_pos_y: 2010272.12
    }
    terrain_level_point {
      sim_grid_pos_x: 480744.094
      sim_grid_pos_y: 2010381.62
    }
    terrain_level_point {
      sim_grid_pos_x: 480801.812
      sim_grid_pos_y: 2010907.62
    }
    terrain_level_point {
      sim_grid_pos_x: 480639.219
      sim_grid_pos_y: 2011167.5
    }
    terrain_level_point {
      sim_grid_pos_x: 481055.031
      sim_grid_pos_y: 2011511.12
    }
    terrain_level_point {
      sim_grid_pos_x: 481237.938
      sim_grid_pos_y: 2011473.62
    }
    terrain_level_point {
      sim_grid_pos_x: 481382.656
      sim_grid_pos_y: 2011112.75
    }
    terrain_level_point {
      sim_grid_pos_x: 481689.031
      sim_grid_pos_y: 2011108.38
    }
    terrain_level_point {
      sim_grid_pos_x: 481917.625
      sim_grid_pos_y: 2011068.38
    }
    terrain_level_point {
      sim_grid_pos_x: 482188.562
      sim_grid_pos_y: 2011396.5
    }
    terrain_level_point {
      sim_grid_pos_x: 482555.781
      sim_grid_pos_y: 2011188.88
    }
    terrain_level_point {
      sim_grid_pos_x: 482877.312
      sim_grid_pos_y: 2011299.5
    }
    terrain_level_point {
      sim_grid_pos_x: 483621
      sim_grid_pos_y: 2011514.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484379.969
      sim_grid_pos_y: 2012120.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484942.219
      sim_grid_pos_y: 2012015.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484930.812
      sim_grid_pos_y: 2010884.75
    }
    terrain_level_point {
      sim_grid_pos_x: 482992
      sim_grid_pos_y: 2008540.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 480284.781
      sim_grid_pos_y: 2005024.88
    }
    terrain_level_point {
      sim_grid_pos_x: 480071.625
      sim_grid_pos_y: 2005432.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479969.594
      sim_grid_pos_y: 2005410.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479845.062
      sim_grid_pos_y: 2005452.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479770.312
      sim_grid_pos_y: 2005580.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479819.5
      sim_grid_pos_y: 2005821
    }
    terrain_level_point {
      sim_grid_pos_x: 479917.906
      sim_grid_pos_y: 2006103.75
    }
    terrain_level_point {
      sim_grid_pos_x: 479945.094
      sim_grid_pos_y: 2006228.38
    }
    terrain_level_point {
      sim_grid_pos_x: 479756.812
      sim_grid_pos_y: 2006793.38
    }
    terrain_level_point {
      sim_grid_pos_x: 479557.531
      sim_grid_pos_y: 2007144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479391.531
      sim_grid_pos_y: 2007508
    }
    terrain_level_point {
      sim_grid_pos_x: 479478.625
      sim_grid_pos_y: 2007873.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479433.688
      sim_grid_pos_y: 2008166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479358.406
      sim_grid_pos_y: 2008278.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479550.5
      sim_grid_pos_y: 2.00867e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 479455.375
      sim_grid_pos_y: 2008975
    }
    terrain_level_point {
      sim_grid_pos_x: 479986.625
      sim_grid_pos_y: 2009939.75
    }
    terrain_level_point {
      sim_grid_pos_x: 480132.094
      sim_grid_pos_y: 2010151.75
    }
    terrain_level_point {
      sim_grid_pos_x: 480654.625
      sim_grid_pos_y: 2010298.5
    }
    terrain_level_point {
      sim_grid_pos_x: 480714.312
      sim_grid_pos_y: 2010392.12
    }
    terrain_level_point {
      sim_grid_pos_x: 480770.062
      sim_grid_pos_y: 2010900.38
    }
    terrain_level_point {
      sim_grid_pos_x: 480598.844
      sim_grid_pos_y: 2011174.12
    }
    terrain_level_point {
      sim_grid_pos_x: 481046.812
      sim_grid_pos_y: 2011544.25
    }
    terrain_level_point {
      sim_grid_pos_x: 481260.344
      sim_grid_pos_y: 2011500.38
    }
    terrain_level_point {
      sim_grid_pos_x: 481403.594
      sim_grid_pos_y: 2011143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 481691.938
      sim_grid_pos_y: 2011139
    }
    terrain_level_point {
      sim_grid_pos_x: 481905.312
      sim_grid_pos_y: 2011101.75
    }
    terrain_level_point {
      sim_grid_pos_x: 482181.25
      sim_grid_pos_y: 2011436
    }
    terrain_level_point {
      sim_grid_pos_x: 482558.875
      sim_grid_pos_y: 2011222.5
    }
    terrain_level_point {
      sim_grid_pos_x: 482868.031
      sim_grid_pos_y: 2011328.88
    }
    terrain_level_point {
      sim_grid_pos_x: 483606.594
      sim_grid_pos_y: 2011542.62
    }
    terrain_level_point {
      sim_grid_pos_x: 484371.781
      sim_grid_pos_y: 2012153.62
    }
    terrain_level_point {
      sim_grid_pos_x: 484973.25
      sim_grid_pos_y: 2012041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 484961.438
      sim_grid_pos_y: 2010873.62
    }
    terrain_level_point {
      sim_grid_pos_x: 483016.156
      sim_grid_pos_y: 2008521.38
    }
  }
}
