terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1326028.62
      sim_grid_pos_y: 1531261.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1324932.75
      sim_grid_pos_y: 1531171.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1324804
      sim_grid_pos_y: 1531342.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1324555.25
      sim_grid_pos_y: 1.53145e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1324432.25
      sim_grid_pos_y: 1531518.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1324394.88
      sim_grid_pos_y: 1532068.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1325501.38
      sim_grid_pos_y: 1532379.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326107.25
      sim_grid_pos_y: 1532320.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1324918.38
      sim_grid_pos_y: 1531139.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1324784.38
      sim_grid_pos_y: 1531317.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1324541.5
      sim_grid_pos_y: 1531422.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1324402.62
      sim_grid_pos_y: 1531500.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1324362.5
      sim_grid_pos_y: 1532091.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1325498.62
      sim_grid_pos_y: 1532411
    }
    terrain_level_point {
      sim_grid_pos_x: 1326140.12
      sim_grid_pos_y: 1532348.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1326057.38
      sim_grid_pos_y: 1531233.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1324904
      sim_grid_pos_y: 1531107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1324764.75
      sim_grid_pos_y: 1531292.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1324527.88
      sim_grid_pos_y: 1531394.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1324373.12
      sim_grid_pos_y: 1531481.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1324330.12
      sim_grid_pos_y: 1532114.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1325495.88
      sim_grid_pos_y: 1532442.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1326173
      sim_grid_pos_y: 1532376.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326086.12
      sim_grid_pos_y: 1531204.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1324889.62
      sim_grid_pos_y: 1531075.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1324745
      sim_grid_pos_y: 1531267.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1324514.25
      sim_grid_pos_y: 1531367.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1324343.5
      sim_grid_pos_y: 1531462.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1324297.75
      sim_grid_pos_y: 1532137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1325493
      sim_grid_pos_y: 1532473.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1326205.88
      sim_grid_pos_y: 1532404
    }
    terrain_level_point {
      sim_grid_pos_x: 1326114.88
      sim_grid_pos_y: 1531176.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1324875.25
      sim_grid_pos_y: 1531043.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1324725.38
      sim_grid_pos_y: 1531242.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1324500.62
      sim_grid_pos_y: 1531339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1324314
      sim_grid_pos_y: 1531444.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1324265.25
      sim_grid_pos_y: 1532160.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1325490.25
      sim_grid_pos_y: 1532504.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326238.75
      sim_grid_pos_y: 1532431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326143.62
      sim_grid_pos_y: 1531147.88
    }
  }
}
