terrain_level_data {
  terrain_level: 122
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2897468.75
      sim_grid_pos_y: 592390.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2896502.75
      sim_grid_pos_y: 594055.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2897379.5
      sim_grid_pos_y: 594313.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2898441.25
      sim_grid_pos_y: 594459.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2898578.75
      sim_grid_pos_y: 595453.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2899822
      sim_grid_pos_y: 597135.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2900598.75
      sim_grid_pos_y: 598504.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2901966
      sim_grid_pos_y: 597680.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2901823.5
      sim_grid_pos_y: 596591.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2901332.5
      sim_grid_pos_y: 595424.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2900548.75
      sim_grid_pos_y: 594689.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2900178.75
      sim_grid_pos_y: 594277.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2899322
      sim_grid_pos_y: 593966.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2899407
      sim_grid_pos_y: 593727.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2899593.75
      sim_grid_pos_y: 593483.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2898688
      sim_grid_pos_y: 592957.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2898223
      sim_grid_pos_y: 592605.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2897454
      sim_grid_pos_y: 592354.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2896456.5
      sim_grid_pos_y: 594073.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2897373
      sim_grid_pos_y: 594343.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2898414
      sim_grid_pos_y: 594487.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2898549.25
      sim_grid_pos_y: 595465.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2899796.25
      sim_grid_pos_y: 597152.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2900587.5
      sim_grid_pos_y: 598547.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2901999.25
      sim_grid_pos_y: 597696.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2901853.5
      sim_grid_pos_y: 596583.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2901358.25
      sim_grid_pos_y: 595406.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2900570.75
      sim_grid_pos_y: 594668.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2900196.5
      sim_grid_pos_y: 594251.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2899361.25
      sim_grid_pos_y: 593947.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2899434.25
      sim_grid_pos_y: 593742.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2899639.25
      sim_grid_pos_y: 593474.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2898705
      sim_grid_pos_y: 592932.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2898237
      sim_grid_pos_y: 592577.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2897439.5
      sim_grid_pos_y: 592318.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2896410.25
      sim_grid_pos_y: 594092.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2897366.5
      sim_grid_pos_y: 594373.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2898386.75
      sim_grid_pos_y: 594514.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2.89852e+06
      sim_grid_pos_y: 595477.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2899770.25
      sim_grid_pos_y: 597169.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2900576.25
      sim_grid_pos_y: 598590
    }
    terrain_level_point {
      sim_grid_pos_x: 2902032.25
      sim_grid_pos_y: 597712.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2901883.5
      sim_grid_pos_y: 596575
    }
    terrain_level_point {
      sim_grid_pos_x: 2901384
      sim_grid_pos_y: 595388.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2900592.75
      sim_grid_pos_y: 594646.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2900214.25
      sim_grid_pos_y: 594225.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2899400.5
      sim_grid_pos_y: 593929.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2899461.75
      sim_grid_pos_y: 593757.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2899685
      sim_grid_pos_y: 593465.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2898722
      sim_grid_pos_y: 592906.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2898251
      sim_grid_pos_y: 592549.562
    }
  }
}
