terrain_level_data {
  terrain_level: 650
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1550336.5
      sim_grid_pos_y: 1827342.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550411.5
      sim_grid_pos_y: 1827642.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550224
      sim_grid_pos_y: 1827842.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549780.25
      sim_grid_pos_y: 1827692.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549333.38
      sim_grid_pos_y: 1827442.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.54906e+06
      sim_grid_pos_y: 1827042.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548848.25
      sim_grid_pos_y: 1826367.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548592.38
      sim_grid_pos_y: 1826129.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548364.38
      sim_grid_pos_y: 1826111.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1547575.5
      sim_grid_pos_y: 1826426.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547406
      sim_grid_pos_y: 1826009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547246.25
      sim_grid_pos_y: 1826076
    }
    terrain_level_point {
      sim_grid_pos_x: 1547023.88
      sim_grid_pos_y: 1825921.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1547140.12
      sim_grid_pos_y: 1825739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1546910.88
      sim_grid_pos_y: 1825553.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1546603.62
      sim_grid_pos_y: 1824960.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546617.62
      sim_grid_pos_y: 1824813.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546229.5
      sim_grid_pos_y: 1824398.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1547253
      sim_grid_pos_y: 1824290.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1547457.25
      sim_grid_pos_y: 1824386.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548014.38
      sim_grid_pos_y: 1824884.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548555.5
      sim_grid_pos_y: 1825145.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549146
      sim_grid_pos_y: 1825144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549356.25
      sim_grid_pos_y: 1825220.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549396.38
      sim_grid_pos_y: 1825476.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549476.38
      sim_grid_pos_y: 1825784.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549529
      sim_grid_pos_y: 1826148.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549755.25
      sim_grid_pos_y: 1826537.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549895.88
      sim_grid_pos_y: 1826635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549953.62
      sim_grid_pos_y: 1826813.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1547474.38
      sim_grid_pos_y: 1824360.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1548031.62
      sim_grid_pos_y: 1824858.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548562.5
      sim_grid_pos_y: 1825115.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549151.38
      sim_grid_pos_y: 1825113.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549383.88
      sim_grid_pos_y: 1825198
    }
    terrain_level_point {
      sim_grid_pos_x: 1549426.5
      sim_grid_pos_y: 1825470.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549506.62
      sim_grid_pos_y: 1825778.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549558.62
      sim_grid_pos_y: 1826138
    }
    terrain_level_point {
      sim_grid_pos_x: 1549778.38
      sim_grid_pos_y: 1826516.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549922
      sim_grid_pos_y: 1826615.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549981.38
      sim_grid_pos_y: 1826799.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550364.88
      sim_grid_pos_y: 1827329.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550445.38
      sim_grid_pos_y: 1827651.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550232.88
      sim_grid_pos_y: 1827877.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549767.75
      sim_grid_pos_y: 1827720.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549312
      sim_grid_pos_y: 1827465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549032
      sim_grid_pos_y: 1827056
    }
    terrain_level_point {
      sim_grid_pos_x: 1548821.38
      sim_grid_pos_y: 1826384.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548579.25
      sim_grid_pos_y: 1826159.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548369.12
      sim_grid_pos_y: 1826142.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1547558.5
      sim_grid_pos_y: 1826466.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1547389.12
      sim_grid_pos_y: 1826049.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1547242.5
      sim_grid_pos_y: 1826110.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546982
      sim_grid_pos_y: 1.82593e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1547099.38
      sim_grid_pos_y: 1825746.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546886.5
      sim_grid_pos_y: 1825573.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546572.12
      sim_grid_pos_y: 1824966.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1546585.75
      sim_grid_pos_y: 1824824.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1546194
      sim_grid_pos_y: 1824405.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546207.38
      sim_grid_pos_y: 1824369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547258.38
      sim_grid_pos_y: 1824258.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1547491.5
      sim_grid_pos_y: 1824334.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1548048.88
      sim_grid_pos_y: 1824832.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548569.5
      sim_grid_pos_y: 1825084.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549156.75
      sim_grid_pos_y: 1825082.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549411.38
      sim_grid_pos_y: 1825175.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549456.62
      sim_grid_pos_y: 1825464
    }
    terrain_level_point {
      sim_grid_pos_x: 1549536.75
      sim_grid_pos_y: 1825772.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549588.12
      sim_grid_pos_y: 1826127.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549801.5
      sim_grid_pos_y: 1826495.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549948
      sim_grid_pos_y: 1826596.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550009.12
      sim_grid_pos_y: 1826785.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550393.25
      sim_grid_pos_y: 1827315.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550479.25
      sim_grid_pos_y: 1.82766e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1550241.75
      sim_grid_pos_y: 1827913.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549755.12
      sim_grid_pos_y: 1827748.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549290.75
      sim_grid_pos_y: 1827489
    }
    terrain_level_point {
      sim_grid_pos_x: 1549004
      sim_grid_pos_y: 1827069.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1548794.38
      sim_grid_pos_y: 1826401.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548566.12
      sim_grid_pos_y: 1826189.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548373.75
      sim_grid_pos_y: 1826173.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1547541.5
      sim_grid_pos_y: 1826506.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1547372.38
      sim_grid_pos_y: 1826090.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1547238.88
      sim_grid_pos_y: 1826145.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1546940.12
      sim_grid_pos_y: 1825938.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1547058.75
      sim_grid_pos_y: 1825752.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546862.12
      sim_grid_pos_y: 1825593.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546540.62
      sim_grid_pos_y: 1824972.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546553.75
      sim_grid_pos_y: 1824835.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546158.5
      sim_grid_pos_y: 1824412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546185.25
      sim_grid_pos_y: 1824340.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1547263.62
      sim_grid_pos_y: 1824227.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1547508.75
      sim_grid_pos_y: 1824308.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548066.25
      sim_grid_pos_y: 1824807
    }
    terrain_level_point {
      sim_grid_pos_x: 1548576.5
      sim_grid_pos_y: 1825053.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549162.12
      sim_grid_pos_y: 1825051.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549439
      sim_grid_pos_y: 1825152.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549486.88
      sim_grid_pos_y: 1825457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549567
      sim_grid_pos_y: 1825766.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549617.75
      sim_grid_pos_y: 1826117.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549824.75
      sim_grid_pos_y: 1826473.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549974.12
      sim_grid_pos_y: 1826577
    }
    terrain_level_point {
      sim_grid_pos_x: 1550036.88
      sim_grid_pos_y: 1826771.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550421.75
      sim_grid_pos_y: 1827302.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1550513.25
      sim_grid_pos_y: 1827668.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1550250.75
      sim_grid_pos_y: 1827948.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549742.62
      sim_grid_pos_y: 1827777.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549269.38
      sim_grid_pos_y: 1827512.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548976.12
      sim_grid_pos_y: 1827083.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548767.5
      sim_grid_pos_y: 1826418.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548553
      sim_grid_pos_y: 1826219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548378.5
      sim_grid_pos_y: 1826204.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1547524.5
      sim_grid_pos_y: 1826546.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547355.5
      sim_grid_pos_y: 1826130.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547235.12
      sim_grid_pos_y: 1826180.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546898.38
      sim_grid_pos_y: 1825946.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547018
      sim_grid_pos_y: 1825759.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546837.75
      sim_grid_pos_y: 1825613
    }
    terrain_level_point {
      sim_grid_pos_x: 1546509.12
      sim_grid_pos_y: 1824978.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546521.75
      sim_grid_pos_y: 1824846.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1546123.12
      sim_grid_pos_y: 1824419.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546163
      sim_grid_pos_y: 1824312.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1547269
      sim_grid_pos_y: 1824195.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1547525.88
      sim_grid_pos_y: 1824282.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548083.5
      sim_grid_pos_y: 1824781.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548583.5
      sim_grid_pos_y: 1825022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549167.5
      sim_grid_pos_y: 1825021
    }
    terrain_level_point {
      sim_grid_pos_x: 1549466.5
      sim_grid_pos_y: 1.82513e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1549517
      sim_grid_pos_y: 1825451.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1549597.12
      sim_grid_pos_y: 1825760.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549647.38
      sim_grid_pos_y: 1826107.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549847.88
      sim_grid_pos_y: 1826452.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550000.12
      sim_grid_pos_y: 1826557.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550064.75
      sim_grid_pos_y: 1826757.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550450.12
      sim_grid_pos_y: 1827289.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550547.12
      sim_grid_pos_y: 1827677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550259.62
      sim_grid_pos_y: 1827984.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549730.12
      sim_grid_pos_y: 1827805.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549248.12
      sim_grid_pos_y: 1827535.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548948.12
      sim_grid_pos_y: 1827096.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548740.62
      sim_grid_pos_y: 1826435.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548539.88
      sim_grid_pos_y: 1826249
    }
    terrain_level_point {
      sim_grid_pos_x: 1548383.12
      sim_grid_pos_y: 1826236.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1547507.62
      sim_grid_pos_y: 1826586.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547338.75
      sim_grid_pos_y: 1826170.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547231.38
      sim_grid_pos_y: 1826215.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1546856.5
      sim_grid_pos_y: 1825955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546977.38
      sim_grid_pos_y: 1825765.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546813.38
      sim_grid_pos_y: 1825632.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546477.75
      sim_grid_pos_y: 1824984.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1546489.88
      sim_grid_pos_y: 1824857.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546087.62
      sim_grid_pos_y: 1824426.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546140.88
      sim_grid_pos_y: 1824283.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547274.25
      sim_grid_pos_y: 1824164.25
    }
  }
}
