terrain_level_data {
  terrain_level: 230
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1863128.75
      sim_grid_pos_y: 1099577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863020.75
      sim_grid_pos_y: 1099335.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862727.75
      sim_grid_pos_y: 1099372.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862459.88
      sim_grid_pos_y: 1099796.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862462.5
      sim_grid_pos_y: 1.10018e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1862982.38
      sim_grid_pos_y: 1100791
    }
    terrain_level_point {
      sim_grid_pos_x: 1863379.88
      sim_grid_pos_y: 1101239
    }
    terrain_level_point {
      sim_grid_pos_x: 1863694.88
      sim_grid_pos_y: 1101874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863635.12
      sim_grid_pos_y: 1102281.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863779.5
      sim_grid_pos_y: 1102934.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863970.38
      sim_grid_pos_y: 1103078.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1864492.62
      sim_grid_pos_y: 1103022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1864133
      sim_grid_pos_y: 1102548.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863975.38
      sim_grid_pos_y: 1102510.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863886.25
      sim_grid_pos_y: 1102405
    }
    terrain_level_point {
      sim_grid_pos_x: 1863850.75
      sim_grid_pos_y: 1102160.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1864076.62
      sim_grid_pos_y: 1101977.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1864050.5
      sim_grid_pos_y: 1101714.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863902.25
      sim_grid_pos_y: 1101647.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863841.38
      sim_grid_pos_y: 1101407.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863564.12
      sim_grid_pos_y: 1100951.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863458.12
      sim_grid_pos_y: 1100664.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863262.12
      sim_grid_pos_y: 1100458.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863138.5
      sim_grid_pos_y: 1100356.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863023.38
      sim_grid_pos_y: 1.10019e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1863006.62
      sim_grid_pos_y: 1100062.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862969.62
      sim_grid_pos_y: 1099919.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863008.62
      sim_grid_pos_y: 1099692.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1863039.62
      sim_grid_pos_y: 1099301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862709.5
      sim_grid_pos_y: 1099344.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862429
      sim_grid_pos_y: 1099787.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862431.88
      sim_grid_pos_y: 1100191.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862959.12
      sim_grid_pos_y: 1100811.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863354.25
      sim_grid_pos_y: 1101256.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863663
      sim_grid_pos_y: 1101879.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863603.88
      sim_grid_pos_y: 1102283
    }
    terrain_level_point {
      sim_grid_pos_x: 1863751.88
      sim_grid_pos_y: 1102952.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863961.5
      sim_grid_pos_y: 1103110.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1864513.88
      sim_grid_pos_y: 1103051.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1864528
      sim_grid_pos_y: 1103018.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1864150.75
      sim_grid_pos_y: 1102521
    }
    terrain_level_point {
      sim_grid_pos_x: 1863992.38
      sim_grid_pos_y: 1102483.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863915.38
      sim_grid_pos_y: 1102391.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863883.75
      sim_grid_pos_y: 1102173.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1864108.88
      sim_grid_pos_y: 1101991.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1864079.38
      sim_grid_pos_y: 1101693.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863928.38
      sim_grid_pos_y: 1101625.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863870.12
      sim_grid_pos_y: 1101395
    }
    terrain_level_point {
      sim_grid_pos_x: 1863591.88
      sim_grid_pos_y: 1100937.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863484.75
      sim_grid_pos_y: 1100648.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863283.12
      sim_grid_pos_y: 1100435.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863161.25
      sim_grid_pos_y: 1100335.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863052.88
      sim_grid_pos_y: 1100178.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863036.88
      sim_grid_pos_y: 1100056.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863001
      sim_grid_pos_y: 1099918.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863037.25
      sim_grid_pos_y: 1099708.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863165.62
      sim_grid_pos_y: 1099585
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1863058.38
      sim_grid_pos_y: 1099268.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862691.25
      sim_grid_pos_y: 1099315.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862398.25
      sim_grid_pos_y: 1099779
    }
    terrain_level_point {
      sim_grid_pos_x: 1862401.12
      sim_grid_pos_y: 1100202.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862935.88
      sim_grid_pos_y: 1100831.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863328.5
      sim_grid_pos_y: 1101273.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863631.25
      sim_grid_pos_y: 1101884.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863572.62
      sim_grid_pos_y: 1102284.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863724.38
      sim_grid_pos_y: 1102970.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863952.75
      sim_grid_pos_y: 1103142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1864535
      sim_grid_pos_y: 1.10308e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1864563.38
      sim_grid_pos_y: 1103014.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1864168.62
      sim_grid_pos_y: 1102493.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1864009.38
      sim_grid_pos_y: 1102455.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863944.5
      sim_grid_pos_y: 1102378.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863916.62
      sim_grid_pos_y: 1102186.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1864141.12
      sim_grid_pos_y: 1102004.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1864108.25
      sim_grid_pos_y: 1101673
    }
    terrain_level_point {
      sim_grid_pos_x: 1863954.5
      sim_grid_pos_y: 1101603.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863898.75
      sim_grid_pos_y: 1101383
    }
    terrain_level_point {
      sim_grid_pos_x: 1863619.75
      sim_grid_pos_y: 1100924.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863511.38
      sim_grid_pos_y: 1100631.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863304.12
      sim_grid_pos_y: 1100413
    }
    terrain_level_point {
      sim_grid_pos_x: 1863184.12
      sim_grid_pos_y: 1100314.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863082.38
      sim_grid_pos_y: 1100167.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863067.12
      sim_grid_pos_y: 1100050.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863032.5
      sim_grid_pos_y: 1099917
    }
    terrain_level_point {
      sim_grid_pos_x: 1863065.75
      sim_grid_pos_y: 1099723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863202.5
      sim_grid_pos_y: 1099592.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1863077.12
      sim_grid_pos_y: 1099234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862673
      sim_grid_pos_y: 1099286.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862367.38
      sim_grid_pos_y: 1099770.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862370.5
      sim_grid_pos_y: 1100214.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862912.75
      sim_grid_pos_y: 1100851.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863302.75
      sim_grid_pos_y: 1101291
    }
    terrain_level_point {
      sim_grid_pos_x: 1863599.38
      sim_grid_pos_y: 1101889.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863541.38
      sim_grid_pos_y: 1102285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863696.75
      sim_grid_pos_y: 1102988.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863943.88
      sim_grid_pos_y: 1103174.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1864556.12
      sim_grid_pos_y: 1103108.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1864598.75
      sim_grid_pos_y: 1103009.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1864186.5
      sim_grid_pos_y: 1102466.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1864026.38
      sim_grid_pos_y: 1102428
    }
    terrain_level_point {
      sim_grid_pos_x: 1863973.75
      sim_grid_pos_y: 1102365.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863949.62
      sim_grid_pos_y: 1102199.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1864173.38
      sim_grid_pos_y: 1102018.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1864137
      sim_grid_pos_y: 1101652.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863980.75
      sim_grid_pos_y: 1101581.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863927.38
      sim_grid_pos_y: 1101371
    }
    terrain_level_point {
      sim_grid_pos_x: 1863647.62
      sim_grid_pos_y: 1100911
    }
    terrain_level_point {
      sim_grid_pos_x: 1863538
      sim_grid_pos_y: 1100615.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863325.12
      sim_grid_pos_y: 1100390.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863207
      sim_grid_pos_y: 1100293.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863111.88
      sim_grid_pos_y: 1100155.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863097.38
      sim_grid_pos_y: 1100044.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863063.88
      sim_grid_pos_y: 1099915.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863094.38
      sim_grid_pos_y: 1099738.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863239.38
      sim_grid_pos_y: 1099599.5
    }
  }
}
terrain_level_data {
  terrain_level: 240
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1862404.38
      sim_grid_pos_y: 1101382.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862596.62
      sim_grid_pos_y: 1101634.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862621.38
      sim_grid_pos_y: 1102009.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862668.88
      sim_grid_pos_y: 1102352.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862583.5
      sim_grid_pos_y: 1.10239e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1862637
      sim_grid_pos_y: 1102680.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862905.25
      sim_grid_pos_y: 1103135.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1863342.62
      sim_grid_pos_y: 1103300.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863766.38
      sim_grid_pos_y: 1103332.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863774.25
      sim_grid_pos_y: 1103602.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863490.5
      sim_grid_pos_y: 1104052.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863131.25
      sim_grid_pos_y: 1103977.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862843.5
      sim_grid_pos_y: 1103772.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862878.5
      sim_grid_pos_y: 1103677
    }
    terrain_level_point {
      sim_grid_pos_x: 1862824.25
      sim_grid_pos_y: 1103585.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862692.88
      sim_grid_pos_y: 1103496
    }
    terrain_level_point {
      sim_grid_pos_x: 1862613.25
      sim_grid_pos_y: 1103385.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862469.75
      sim_grid_pos_y: 1103269.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862407.5
      sim_grid_pos_y: 1103171.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862499.12
      sim_grid_pos_y: 1103102.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862513.62
      sim_grid_pos_y: 1103033.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862450.25
      sim_grid_pos_y: 1102924
    }
    terrain_level_point {
      sim_grid_pos_x: 1862084.62
      sim_grid_pos_y: 1102645.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862054.88
      sim_grid_pos_y: 1102316.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1861972.88
      sim_grid_pos_y: 1101979.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862029.38
      sim_grid_pos_y: 1101813.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862132.88
      sim_grid_pos_y: 1101440.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1862626.75
      sim_grid_pos_y: 1101623.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862652
      sim_grid_pos_y: 1102006.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862702.62
      sim_grid_pos_y: 1102371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862618.12
      sim_grid_pos_y: 1102408.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862666.38
      sim_grid_pos_y: 1102669.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862926.25
      sim_grid_pos_y: 1103110.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863349.38
      sim_grid_pos_y: 1103269.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1863796.38
      sim_grid_pos_y: 1103304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863805.25
      sim_grid_pos_y: 1103610.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863505.12
      sim_grid_pos_y: 1104087
    }
    terrain_level_point {
      sim_grid_pos_x: 1863118.62
      sim_grid_pos_y: 1104005.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862806.62
      sim_grid_pos_y: 1103784.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862844.62
      sim_grid_pos_y: 1103680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862801.25
      sim_grid_pos_y: 1103607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862671
      sim_grid_pos_y: 1103518.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862590.62
      sim_grid_pos_y: 1103406.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862446.38
      sim_grid_pos_y: 1103290.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862366.38
      sim_grid_pos_y: 1103163.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862471.5
      sim_grid_pos_y: 1103084.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862481.12
      sim_grid_pos_y: 1103039
    }
    terrain_level_point {
      sim_grid_pos_x: 1862426.75
      sim_grid_pos_y: 1102944.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862055.25
      sim_grid_pos_y: 1102662.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862024.5
      sim_grid_pos_y: 1102322
    }
    terrain_level_point {
      sim_grid_pos_x: 1861940.88
      sim_grid_pos_y: 1101977.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.862e+06
      sim_grid_pos_y: 1101804.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862108.25
      sim_grid_pos_y: 1101414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862417
      sim_grid_pos_y: 1101348.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1862656.75
      sim_grid_pos_y: 1101612.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862682.62
      sim_grid_pos_y: 1102003.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862736.25
      sim_grid_pos_y: 1.10239e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1862652.75
      sim_grid_pos_y: 1102426.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862695.62
      sim_grid_pos_y: 1102658.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862947.25
      sim_grid_pos_y: 1103085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863356.12
      sim_grid_pos_y: 1103239.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863826.38
      sim_grid_pos_y: 1103275.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1863836.25
      sim_grid_pos_y: 1103619.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863519.62
      sim_grid_pos_y: 1104121.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863106.12
      sim_grid_pos_y: 1104034.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862769.62
      sim_grid_pos_y: 1103795.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862810.62
      sim_grid_pos_y: 1103683.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862778.25
      sim_grid_pos_y: 1103629
    }
    terrain_level_point {
      sim_grid_pos_x: 1862649.25
      sim_grid_pos_y: 1103540.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1862568.12
      sim_grid_pos_y: 1103428.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862423.12
      sim_grid_pos_y: 1103311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862325.25
      sim_grid_pos_y: 1103156.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862443.75
      sim_grid_pos_y: 1103066.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862448.5
      sim_grid_pos_y: 1103044.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862403.12
      sim_grid_pos_y: 1102965.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862025.75
      sim_grid_pos_y: 1102678.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1861994
      sim_grid_pos_y: 1102327
    }
    terrain_level_point {
      sim_grid_pos_x: 1861908.88
      sim_grid_pos_y: 1101976.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1861970.5
      sim_grid_pos_y: 1101795.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862083.5
      sim_grid_pos_y: 1101388.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862429.62
      sim_grid_pos_y: 1101314.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1862686.88
      sim_grid_pos_y: 1101601
    }
    terrain_level_point {
      sim_grid_pos_x: 1862713.12
      sim_grid_pos_y: 1101999.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862769.88
      sim_grid_pos_y: 1102408.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862687.5
      sim_grid_pos_y: 1102445
    }
    terrain_level_point {
      sim_grid_pos_x: 1862724.88
      sim_grid_pos_y: 1102647.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862968.25
      sim_grid_pos_y: 1103060.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1863362.88
      sim_grid_pos_y: 1103209.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1863856.25
      sim_grid_pos_y: 1103247.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1863867.25
      sim_grid_pos_y: 1103627.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1863534.25
      sim_grid_pos_y: 1104156
    }
    terrain_level_point {
      sim_grid_pos_x: 1863093.5
      sim_grid_pos_y: 1104063.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862732.75
      sim_grid_pos_y: 1103807.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1862776.75
      sim_grid_pos_y: 1103686.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862755.38
      sim_grid_pos_y: 1103650.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862627.38
      sim_grid_pos_y: 1103563
    }
    terrain_level_point {
      sim_grid_pos_x: 1862545.62
      sim_grid_pos_y: 1103449.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1862399.88
      sim_grid_pos_y: 1103331.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1862284.12
      sim_grid_pos_y: 1103149
    }
    terrain_level_point {
      sim_grid_pos_x: 1862416
      sim_grid_pos_y: 1103049.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1862379.62
      sim_grid_pos_y: 1102986.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1861996.38
      sim_grid_pos_y: 1102694.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1861963.62
      sim_grid_pos_y: 1102332
    }
    terrain_level_point {
      sim_grid_pos_x: 1861876.88
      sim_grid_pos_y: 1101974.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1861941.12
      sim_grid_pos_y: 1101786.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1862058.88
      sim_grid_pos_y: 1101362.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1862442.25
      sim_grid_pos_y: 1101280.25
    }
  }
}
