terrain_level_data {
  terrain_level: 550
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1550476.5
      sim_grid_pos_y: 1596636.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1551099.5
      sim_grid_pos_y: 1597154.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550655.12
      sim_grid_pos_y: 1597338.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550540.38
      sim_grid_pos_y: 1597610.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550541
      sim_grid_pos_y: 1597767.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550642
      sim_grid_pos_y: 1598145.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550894.25
      sim_grid_pos_y: 1598033.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1551280.12
      sim_grid_pos_y: 1597976
    }
    terrain_level_point {
      sim_grid_pos_x: 1551575.25
      sim_grid_pos_y: 1598389.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1551538
      sim_grid_pos_y: 1599150.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1551075.75
      sim_grid_pos_y: 1599121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550524.12
      sim_grid_pos_y: 1599357.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550274
      sim_grid_pos_y: 1599407.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550196.88
      sim_grid_pos_y: 1599541.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550182.62
      sim_grid_pos_y: 1599767.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550014.88
      sim_grid_pos_y: 1599854.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549886.38
      sim_grid_pos_y: 1599822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549517.88
      sim_grid_pos_y: 1600009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549204.62
      sim_grid_pos_y: 1599956.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548792.12
      sim_grid_pos_y: 1599804.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548641.38
      sim_grid_pos_y: 1599926.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548442.38
      sim_grid_pos_y: 1599948.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1547860.38
      sim_grid_pos_y: 1599950.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547846
      sim_grid_pos_y: 1599834
    }
    terrain_level_point {
      sim_grid_pos_x: 1548147.88
      sim_grid_pos_y: 1599562.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548160.38
      sim_grid_pos_y: 1599300.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548155.12
      sim_grid_pos_y: 1599022.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548091.75
      sim_grid_pos_y: 1598854.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548340.75
      sim_grid_pos_y: 1598341
    }
    terrain_level_point {
      sim_grid_pos_x: 1548287.12
      sim_grid_pos_y: 1598149
    }
    terrain_level_point {
      sim_grid_pos_x: 1548156.88
      sim_grid_pos_y: 1597930.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548364.62
      sim_grid_pos_y: 1597924.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548788.25
      sim_grid_pos_y: 1597829.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548826.75
      sim_grid_pos_y: 1598022.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549096.38
      sim_grid_pos_y: 1597951.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549258.12
      sim_grid_pos_y: 1597805.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549346.38
      sim_grid_pos_y: 1597822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549508.75
      sim_grid_pos_y: 1597947.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549751.75
      sim_grid_pos_y: 1597715.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549905.38
      sim_grid_pos_y: 1597345
    }
    terrain_level_point {
      sim_grid_pos_x: 1550188
      sim_grid_pos_y: 1596911.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1551158.38
      sim_grid_pos_y: 1597163
    }
    terrain_level_point {
      sim_grid_pos_x: 1550678.62
      sim_grid_pos_y: 1597362.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550571.12
      sim_grid_pos_y: 1597616.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550571.75
      sim_grid_pos_y: 1597763
    }
    terrain_level_point {
      sim_grid_pos_x: 1550662.5
      sim_grid_pos_y: 1598102.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550885.62
      sim_grid_pos_y: 1598004
    }
    terrain_level_point {
      sim_grid_pos_x: 1551294.25
      sim_grid_pos_y: 1597942.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1551606.5
      sim_grid_pos_y: 1.59838e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1551567.12
      sim_grid_pos_y: 1599183.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1551081.12
      sim_grid_pos_y: 1599152.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550533.38
      sim_grid_pos_y: 1599387
    }
    terrain_level_point {
      sim_grid_pos_x: 1550293.62
      sim_grid_pos_y: 1599435
    }
    terrain_level_point {
      sim_grid_pos_x: 1550227.12
      sim_grid_pos_y: 1599550.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550212.25
      sim_grid_pos_y: 1599786.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550018.62
      sim_grid_pos_y: 1599887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.54989e+06
      sim_grid_pos_y: 1599854.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549522.75
      sim_grid_pos_y: 1600041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549196.62
      sim_grid_pos_y: 1599986.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548798
      sim_grid_pos_y: 1599839.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548653.62
      sim_grid_pos_y: 1599956.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548444.12
      sim_grid_pos_y: 1599979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547833.12
      sim_grid_pos_y: 1599981.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547813.5
      sim_grid_pos_y: 1599821.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548117.75
      sim_grid_pos_y: 1599548
    }
    terrain_level_point {
      sim_grid_pos_x: 1548129.62
      sim_grid_pos_y: 1599299.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548124.5
      sim_grid_pos_y: 1599028.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548058.38
      sim_grid_pos_y: 1598853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548308
      sim_grid_pos_y: 1598338.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548258.62
      sim_grid_pos_y: 1598161.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548103.75
      sim_grid_pos_y: 1597901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548360.75
      sim_grid_pos_y: 1597893.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548812.25
      sim_grid_pos_y: 1597793
    }
    terrain_level_point {
      sim_grid_pos_x: 1548850.5
      sim_grid_pos_y: 1597984.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549081.25
      sim_grid_pos_y: 1597923.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549248.88
      sim_grid_pos_y: 1597772.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549359.38
      sim_grid_pos_y: 1597793.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1549506.62
      sim_grid_pos_y: 1597907.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549725.88
      sim_grid_pos_y: 1597698
    }
    terrain_level_point {
      sim_grid_pos_x: 1549878.12
      sim_grid_pos_y: 1597330.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550164.25
      sim_grid_pos_y: 1596891.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550475.12
      sim_grid_pos_y: 1596595
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1551217.12
      sim_grid_pos_y: 1597171.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550702
      sim_grid_pos_y: 1597385.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1550602
      sim_grid_pos_y: 1597622.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1550602.5
      sim_grid_pos_y: 1597759
    }
    terrain_level_point {
      sim_grid_pos_x: 1550682.88
      sim_grid_pos_y: 1598059.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550876.88
      sim_grid_pos_y: 1597974.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1551308.38
      sim_grid_pos_y: 1597909.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1551637.75
      sim_grid_pos_y: 1598370.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1551596.38
      sim_grid_pos_y: 1599216
    }
    terrain_level_point {
      sim_grid_pos_x: 1551086.5
      sim_grid_pos_y: 1599183.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550542.5
      sim_grid_pos_y: 1599416.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550313.38
      sim_grid_pos_y: 1599462.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550257.25
      sim_grid_pos_y: 1599559.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1550241.88
      sim_grid_pos_y: 1599805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550022.5
      sim_grid_pos_y: 1599920.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549893.62
      sim_grid_pos_y: 1599887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549527.62
      sim_grid_pos_y: 1600073.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549188.75
      sim_grid_pos_y: 1600016
    }
    terrain_level_point {
      sim_grid_pos_x: 1548803.75
      sim_grid_pos_y: 1599874.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548666.12
      sim_grid_pos_y: 1599986
    }
    terrain_level_point {
      sim_grid_pos_x: 1548445.88
      sim_grid_pos_y: 1600010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1547805.88
      sim_grid_pos_y: 1600012.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1547781
      sim_grid_pos_y: 1599809.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548087.62
      sim_grid_pos_y: 1599533.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548098.88
      sim_grid_pos_y: 1599299.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548093.88
      sim_grid_pos_y: 1599034
    }
    terrain_level_point {
      sim_grid_pos_x: 1548024.88
      sim_grid_pos_y: 1598851.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548275.25
      sim_grid_pos_y: 1598335.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.54823e+06
      sim_grid_pos_y: 1598173.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1548050.62
      sim_grid_pos_y: 1597872.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1548356.88
      sim_grid_pos_y: 1597863
    }
    terrain_level_point {
      sim_grid_pos_x: 1548836.25
      sim_grid_pos_y: 1597756.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548874.25
      sim_grid_pos_y: 1597946.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549066.25
      sim_grid_pos_y: 1597896
    }
    terrain_level_point {
      sim_grid_pos_x: 1549239.5
      sim_grid_pos_y: 1597739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549372.38
      sim_grid_pos_y: 1597764.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1549504.5
      sim_grid_pos_y: 1597866.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.5497e+06
      sim_grid_pos_y: 1597680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549850.75
      sim_grid_pos_y: 1597316.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550140.38
      sim_grid_pos_y: 1596872.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550473.62
      sim_grid_pos_y: 1596553.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1551275.88
      sim_grid_pos_y: 1597180.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1550725.5
      sim_grid_pos_y: 1597409.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1550632.75
      sim_grid_pos_y: 1597628.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550633.25
      sim_grid_pos_y: 1597754.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550703.38
      sim_grid_pos_y: 1598017.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550868.25
      sim_grid_pos_y: 1597944.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1551322.38
      sim_grid_pos_y: 1597876.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1551668.88
      sim_grid_pos_y: 1598361.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1551625.5
      sim_grid_pos_y: 1599248.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1551091.88
      sim_grid_pos_y: 1599214.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550551.62
      sim_grid_pos_y: 1599446.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550333
      sim_grid_pos_y: 1599489.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1550287.5
      sim_grid_pos_y: 1599568.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1550271.38
      sim_grid_pos_y: 1599825.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1550026.25
      sim_grid_pos_y: 1599952.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549897.25
      sim_grid_pos_y: 1599920.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549532.5
      sim_grid_pos_y: 1600105.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549180.75
      sim_grid_pos_y: 1600045.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1548809.5
      sim_grid_pos_y: 1599909.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1548678.38
      sim_grid_pos_y: 1600015.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1548447.62
      sim_grid_pos_y: 1600041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1547778.75
      sim_grid_pos_y: 1600043.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1547748.5
      sim_grid_pos_y: 1599797.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548057.5
      sim_grid_pos_y: 1599519.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1548068.12
      sim_grid_pos_y: 1599299
    }
    terrain_level_point {
      sim_grid_pos_x: 1548063.25
      sim_grid_pos_y: 1599039.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1547991.5
      sim_grid_pos_y: 1598850.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548242.5
      sim_grid_pos_y: 1598332.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548201.5
      sim_grid_pos_y: 1598185.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1547997.38
      sim_grid_pos_y: 1597843.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1548353
      sim_grid_pos_y: 1597832.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1548860.25
      sim_grid_pos_y: 1597719.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1548898
      sim_grid_pos_y: 1597908.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1549051.25
      sim_grid_pos_y: 1597868.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549230.25
      sim_grid_pos_y: 1597706.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549385.25
      sim_grid_pos_y: 1597735.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1549502.38
      sim_grid_pos_y: 1597826.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1549674
      sim_grid_pos_y: 1597662.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1549823.5
      sim_grid_pos_y: 1597301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1550116.62
      sim_grid_pos_y: 1596852.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1550472.25
      sim_grid_pos_y: 1596512.62
    }
  }
}
