terrain_level_data {
  terrain_level: 12
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2145668.25
      sim_grid_pos_y: 844377.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2142395
      sim_grid_pos_y: 847315.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2142428.25
      sim_grid_pos_y: 849186.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2142035.5
      sim_grid_pos_y: 849588.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2140174.5
      sim_grid_pos_y: 849144.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2138394.25
      sim_grid_pos_y: 851454
    }
    terrain_level_point {
      sim_grid_pos_x: 2139927.75
      sim_grid_pos_y: 852602.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2140447.5
      sim_grid_pos_y: 855061.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2144897.75
      sim_grid_pos_y: 857630.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2148677.25
      sim_grid_pos_y: 854169.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2150789.5
      sim_grid_pos_y: 856574.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2156781.5
      sim_grid_pos_y: 851350.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2157031.5
      sim_grid_pos_y: 850710.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2158395.25
      sim_grid_pos_y: 850034.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2160418.25
      sim_grid_pos_y: 850040.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2160977.5
      sim_grid_pos_y: 850528.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2162360.25
      sim_grid_pos_y: 848779.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2163892.5
      sim_grid_pos_y: 849595.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2173352.5
      sim_grid_pos_y: 841490.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2180790.25
      sim_grid_pos_y: 823192.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2173981.75
      sim_grid_pos_y: 822206.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2167505.5
      sim_grid_pos_y: 814572.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2166708.5
      sim_grid_pos_y: 814830.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2159800.5
      sim_grid_pos_y: 821852.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2159633
      sim_grid_pos_y: 822840.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2.16143e+06
      sim_grid_pos_y: 826977.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2155235.25
      sim_grid_pos_y: 835870.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2167522.5
      sim_grid_pos_y: 814513.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2166680.75
      sim_grid_pos_y: 814785.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2159752.75
      sim_grid_pos_y: 821828.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2.15958e+06
      sim_grid_pos_y: 822846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2161371.75
      sim_grid_pos_y: 826971.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2155196.75
      sim_grid_pos_y: 835836
    }
    terrain_level_point {
      sim_grid_pos_x: 2145634.25
      sim_grid_pos_y: 844339.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2142343.5
      sim_grid_pos_y: 847293.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2142376.75
      sim_grid_pos_y: 849166.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2142019
      sim_grid_pos_y: 849532.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2140154.25
      sim_grid_pos_y: 849087.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2138322
      sim_grid_pos_y: 851463.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2139881.5
      sim_grid_pos_y: 852631.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2140402
      sim_grid_pos_y: 855094.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2144904.75
      sim_grid_pos_y: 857693.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2148673.25
      sim_grid_pos_y: 854242.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2150784.75
      sim_grid_pos_y: 856646.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2156824.5
      sim_grid_pos_y: 851380.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2157072.25
      sim_grid_pos_y: 850747.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2158407.25
      sim_grid_pos_y: 850085.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2160398.75
      sim_grid_pos_y: 850091.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2160984.25
      sim_grid_pos_y: 850602.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2162374
      sim_grid_pos_y: 848844.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2163899.25
      sim_grid_pos_y: 849657.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2173395.25
      sim_grid_pos_y: 841521.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2180862.5
      sim_grid_pos_y: 823151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2174008.25
      sim_grid_pos_y: 822158.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2167539.5
      sim_grid_pos_y: 814454.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2166653
      sim_grid_pos_y: 814740.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2159704.75
      sim_grid_pos_y: 821803.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2159526.75
      sim_grid_pos_y: 822853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2161313.25
      sim_grid_pos_y: 826965.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2155158
      sim_grid_pos_y: 835801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.1456e+06
      sim_grid_pos_y: 844301.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2142291.75
      sim_grid_pos_y: 847270.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2142325
      sim_grid_pos_y: 849145.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2142002.75
      sim_grid_pos_y: 849475.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2140133.75
      sim_grid_pos_y: 849029.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2138249.75
      sim_grid_pos_y: 851473.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2139835.25
      sim_grid_pos_y: 852661.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2140356.5
      sim_grid_pos_y: 855127.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2144911.5
      sim_grid_pos_y: 857756.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2148669.25
      sim_grid_pos_y: 854315.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2.15078e+06
      sim_grid_pos_y: 856719
    }
    terrain_level_point {
      sim_grid_pos_x: 2156867.75
      sim_grid_pos_y: 851411.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2157112.75
      sim_grid_pos_y: 850784.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2158419
      sim_grid_pos_y: 850137.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2160379.5
      sim_grid_pos_y: 850143.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2160991.25
      sim_grid_pos_y: 850676.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2162387.5
      sim_grid_pos_y: 848910.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2163906
      sim_grid_pos_y: 849719.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2173438
      sim_grid_pos_y: 841552.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2180934.75
      sim_grid_pos_y: 823110.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2174034.75
      sim_grid_pos_y: 822110.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2167556.25
      sim_grid_pos_y: 814394.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2166625.25
      sim_grid_pos_y: 814695.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2159657
      sim_grid_pos_y: 821779.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2159473.75
      sim_grid_pos_y: 822859.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2161254.75
      sim_grid_pos_y: 826960.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2155119.5
      sim_grid_pos_y: 835767.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2145565.75
      sim_grid_pos_y: 844263.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.14224e+06
      sim_grid_pos_y: 847248.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2142273.5
      sim_grid_pos_y: 849125.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2141986.25
      sim_grid_pos_y: 849419.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2140113.5
      sim_grid_pos_y: 848971.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2138177.25
      sim_grid_pos_y: 851483.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2139789.25
      sim_grid_pos_y: 852690.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2140311.25
      sim_grid_pos_y: 855160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2144918.5
      sim_grid_pos_y: 857819.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2148665.25
      sim_grid_pos_y: 854388.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2150775.25
      sim_grid_pos_y: 856791.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2156911
      sim_grid_pos_y: 851441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2157153.25
      sim_grid_pos_y: 850821.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2158431
      sim_grid_pos_y: 850188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2160360.25
      sim_grid_pos_y: 850194.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2160998
      sim_grid_pos_y: 850750.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2162401.25
      sim_grid_pos_y: 848975.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2163912.75
      sim_grid_pos_y: 849780.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2173480.75
      sim_grid_pos_y: 841583.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2181006.75
      sim_grid_pos_y: 823068.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2174061.25
      sim_grid_pos_y: 822062.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2167573.25
      sim_grid_pos_y: 814335.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2166597.5
      sim_grid_pos_y: 814650.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2159609.25
      sim_grid_pos_y: 821754.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2159420.75
      sim_grid_pos_y: 822866.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2161196.5
      sim_grid_pos_y: 826954.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2155080.75
      sim_grid_pos_y: 835733.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2145531.75
      sim_grid_pos_y: 844225
    }
    terrain_level_point {
      sim_grid_pos_x: 2142188.5
      sim_grid_pos_y: 847225.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2142221.75
      sim_grid_pos_y: 849104.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2.14197e+06
      sim_grid_pos_y: 849362.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2140093.25
      sim_grid_pos_y: 848914.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2138105
      sim_grid_pos_y: 851493.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2139743
      sim_grid_pos_y: 852720.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2140265.75
      sim_grid_pos_y: 855193.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2144925.5
      sim_grid_pos_y: 857882.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2148661.25
      sim_grid_pos_y: 854461.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2150770.25
      sim_grid_pos_y: 856863.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2156954
      sim_grid_pos_y: 851471.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2157193.75
      sim_grid_pos_y: 850859
    }
    terrain_level_point {
      sim_grid_pos_x: 2158443
      sim_grid_pos_y: 850239.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2160341
      sim_grid_pos_y: 850245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2161004.75
      sim_grid_pos_y: 850824.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2162415
      sim_grid_pos_y: 849041
    }
    terrain_level_point {
      sim_grid_pos_x: 2163919.75
      sim_grid_pos_y: 849842.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2173523.5
      sim_grid_pos_y: 841614.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2181079
      sim_grid_pos_y: 823027.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2174087.75
      sim_grid_pos_y: 822014.5
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2167626.5
      sim_grid_pos_y: 814473.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2169942.25
      sim_grid_pos_y: 817401.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2174082.75
      sim_grid_pos_y: 821971.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2177392
      sim_grid_pos_y: 822607.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2178885.5
      sim_grid_pos_y: 815696.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2177075.5
      sim_grid_pos_y: 814540
    }
    terrain_level_point {
      sim_grid_pos_x: 2178507.25
      sim_grid_pos_y: 814183.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2179275.75
      sim_grid_pos_y: 813504.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2179237.25
      sim_grid_pos_y: 812653.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2175426.25
      sim_grid_pos_y: 811538.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2173957.75
      sim_grid_pos_y: 811658.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2173256.25
      sim_grid_pos_y: 811061.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2171816.25
      sim_grid_pos_y: 810734
    }
    terrain_level_point {
      sim_grid_pos_x: 2170673.5
      sim_grid_pos_y: 810996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2170680.75
      sim_grid_pos_y: 811723.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2171816.25
      sim_grid_pos_y: 810702.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2170642.5
      sim_grid_pos_y: 810972.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2170649.75
      sim_grid_pos_y: 811710.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2167584.25
      sim_grid_pos_y: 814469.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2169918.75
      sim_grid_pos_y: 817421.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2174066.75
      sim_grid_pos_y: 821999.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2177415.75
      sim_grid_pos_y: 822643
    }
    terrain_level_point {
      sim_grid_pos_x: 2.17892e+06
      sim_grid_pos_y: 815682.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2177152.25
      sim_grid_pos_y: 814552.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2178522
      sim_grid_pos_y: 814211.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2179307.25
      sim_grid_pos_y: 813517.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2179267
      sim_grid_pos_y: 812629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2175429.5
      sim_grid_pos_y: 811507.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2173968
      sim_grid_pos_y: 811627.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2173270.5
      sim_grid_pos_y: 811033.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2171816.25
      sim_grid_pos_y: 810670.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2170611.5
      sim_grid_pos_y: 810947.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2170619
      sim_grid_pos_y: 811696.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2167542.25
      sim_grid_pos_y: 814466.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2169895.25
      sim_grid_pos_y: 817441.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2174051
      sim_grid_pos_y: 822028.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2177439.5
      sim_grid_pos_y: 822678.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2178954.75
      sim_grid_pos_y: 815668
    }
    terrain_level_point {
      sim_grid_pos_x: 2177229
      sim_grid_pos_y: 814565.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2178536.75
      sim_grid_pos_y: 814240
    }
    terrain_level_point {
      sim_grid_pos_x: 2179338.5
      sim_grid_pos_y: 813531.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2179296.5
      sim_grid_pos_y: 812606.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2175432.75
      sim_grid_pos_y: 811476.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2173978.25
      sim_grid_pos_y: 811595.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2173284.75
      sim_grid_pos_y: 811005.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2171816.25
      sim_grid_pos_y: 810639.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2170580.5
      sim_grid_pos_y: 810923.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2170588
      sim_grid_pos_y: 811683.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2167500.25
      sim_grid_pos_y: 814462.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2169871.75
      sim_grid_pos_y: 817461.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2174035
      sim_grid_pos_y: 822056.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2177463.25
      sim_grid_pos_y: 822714.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2178989.25
      sim_grid_pos_y: 815653.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2177306
      sim_grid_pos_y: 814577.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2178551.5
      sim_grid_pos_y: 814268
    }
    terrain_level_point {
      sim_grid_pos_x: 2.17937e+06
      sim_grid_pos_y: 813544.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2179326.25
      sim_grid_pos_y: 812583
    }
    terrain_level_point {
      sim_grid_pos_x: 2175435.75
      sim_grid_pos_y: 811445.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2173988.5
      sim_grid_pos_y: 811563.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2173299
      sim_grid_pos_y: 810976.812
    }
  }
}
