terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 484558.219
      sim_grid_pos_y: 2029554.88
    }
    terrain_level_point {
      sim_grid_pos_x: 486230.594
      sim_grid_pos_y: 2030709.38
    }
    terrain_level_point {
      sim_grid_pos_x: 484504
      sim_grid_pos_y: 2033218.12
    }
    terrain_level_point {
      sim_grid_pos_x: 483184.156
      sim_grid_pos_y: 2032337.38
    }
    terrain_level_point {
      sim_grid_pos_x: 483272.812
      sim_grid_pos_y: 2032269.88
    }
    terrain_level_point {
      sim_grid_pos_x: 483421.625
      sim_grid_pos_y: 2032218.5
    }
    terrain_level_point {
      sim_grid_pos_x: 483578.875
      sim_grid_pos_y: 2032221.5
    }
    terrain_level_point {
      sim_grid_pos_x: 483774.812
      sim_grid_pos_y: 2032334.25
    }
    terrain_level_point {
      sim_grid_pos_x: 483977.281
      sim_grid_pos_y: 2032373.12
    }
    terrain_level_point {
      sim_grid_pos_x: 484155.938
      sim_grid_pos_y: 2032319.12
    }
    terrain_level_point {
      sim_grid_pos_x: 484337.219
      sim_grid_pos_y: 2032209
    }
    terrain_level_point {
      sim_grid_pos_x: 484400.469
      sim_grid_pos_y: 2032034.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484436.125
      sim_grid_pos_y: 2031797
    }
    terrain_level_point {
      sim_grid_pos_x: 484386
      sim_grid_pos_y: 2031702.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484260.844
      sim_grid_pos_y: 2031585.62
    }
    terrain_level_point {
      sim_grid_pos_x: 484120.531
      sim_grid_pos_y: 2031537.25
    }
    terrain_level_point {
      sim_grid_pos_x: 483945.875
      sim_grid_pos_y: 2031530.62
    }
    terrain_level_point {
      sim_grid_pos_x: 483868.344
      sim_grid_pos_y: 2031541.88
    }
    terrain_level_point {
      sim_grid_pos_x: 483737.312
      sim_grid_pos_y: 2031567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 483677.188
      sim_grid_pos_y: 2031682.38
    }
    terrain_level_point {
      sim_grid_pos_x: 483564.625
      sim_grid_pos_y: 2031774.25
    }
    terrain_level_point {
      sim_grid_pos_x: 483428.562
      sim_grid_pos_y: 2031905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 483309.812
      sim_grid_pos_y: 2032037.5
    }
    terrain_level_point {
      sim_grid_pos_x: 483156.812
      sim_grid_pos_y: 2032325.12
    }
    terrain_level_point {
      sim_grid_pos_x: 482781.375
      sim_grid_pos_y: 2032057.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 486259.094
      sim_grid_pos_y: 2030704.12
    }
    terrain_level_point {
      sim_grid_pos_x: 484509.438
      sim_grid_pos_y: 2033246.38
    }
    terrain_level_point {
      sim_grid_pos_x: 483166.656
      sim_grid_pos_y: 2032350.25
    }
    terrain_level_point {
      sim_grid_pos_x: 483163.906
      sim_grid_pos_y: 2032355.38
    }
    terrain_level_point {
      sim_grid_pos_x: 482752.812
      sim_grid_pos_y: 2032062
    }
    terrain_level_point {
      sim_grid_pos_x: 484553.219
      sim_grid_pos_y: 2029526.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 486287.594
      sim_grid_pos_y: 2030698.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484514.875
      sim_grid_pos_y: 2033274.62
    }
    terrain_level_point {
      sim_grid_pos_x: 483174.125
      sim_grid_pos_y: 2032379.88
    }
    terrain_level_point {
      sim_grid_pos_x: 483171.031
      sim_grid_pos_y: 2032385.75
    }
    terrain_level_point {
      sim_grid_pos_x: 482724.25
      sim_grid_pos_y: 2032066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484548.219
      sim_grid_pos_y: 2029498.12
    }
  }
}
