terrain_level_data {
  terrain_level: 832
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2314083.5
      sim_grid_pos_y: 1036106
    }
    terrain_level_point {
      sim_grid_pos_x: 2313825
      sim_grid_pos_y: 1036131.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2313574.75
      sim_grid_pos_y: 1036240.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2313560.25
      sim_grid_pos_y: 1036510.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2313700.5
      sim_grid_pos_y: 1036719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2313881.5
      sim_grid_pos_y: 1036665.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2314198.5
      sim_grid_pos_y: 1036702.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2314251.75
      sim_grid_pos_y: 1036325.06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2314106.75
      sim_grid_pos_y: 1036052.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2313812
      sim_grid_pos_y: 1036081.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2313525.25
      sim_grid_pos_y: 1036205.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2313508
      sim_grid_pos_y: 1036524.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2313679
      sim_grid_pos_y: 1036779.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2313886
      sim_grid_pos_y: 1036717.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2314242.5
      sim_grid_pos_y: 1036758.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2314305.5
      sim_grid_pos_y: 1036310.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2.31413e+06
      sim_grid_pos_y: 1035998.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2313799
      sim_grid_pos_y: 1036031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2313475.75
      sim_grid_pos_y: 1036171.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2313456
      sim_grid_pos_y: 1036539.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2313657.5
      sim_grid_pos_y: 1036839.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2313890.5
      sim_grid_pos_y: 1036770.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2314286.25
      sim_grid_pos_y: 1036815.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2314359.25
      sim_grid_pos_y: 1036296.69
    }
  }
}
terrain_level_data {
  terrain_level: 810
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2314437.25
      sim_grid_pos_y: 1036685.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2314400.25
      sim_grid_pos_y: 1036892.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2314531.25
      sim_grid_pos_y: 1036986.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2314715.75
      sim_grid_pos_y: 1037002.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2314716.25
      sim_grid_pos_y: 1036838
    }
    terrain_level_point {
      sim_grid_pos_x: 2314632
      sim_grid_pos_y: 1036712
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2314395.5
      sim_grid_pos_y: 1036627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2314344
      sim_grid_pos_y: 1036915.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2314512.75
      sim_grid_pos_y: 1037036.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2314766.75
      sim_grid_pos_y: 1037058.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2314767.5
      sim_grid_pos_y: 1036822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2314662
      sim_grid_pos_y: 1036664.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2314353.75
      sim_grid_pos_y: 1036569.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2314288
      sim_grid_pos_y: 1036937.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2314494.25
      sim_grid_pos_y: 1037086.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2314818
      sim_grid_pos_y: 1037114.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2314818.75
      sim_grid_pos_y: 1036807
    }
    terrain_level_point {
      sim_grid_pos_x: 2314691.75
      sim_grid_pos_y: 1036616.81
    }
  }
}
terrain_level_data {
  terrain_level: 744
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2314047.25
      sim_grid_pos_y: 1037124.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2314274.75
      sim_grid_pos_y: 1037146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2314535.75
      sim_grid_pos_y: 1037317.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2314398.25
      sim_grid_pos_y: 1037529.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2314131.25
      sim_grid_pos_y: 1037552
    }
    terrain_level_point {
      sim_grid_pos_x: 2313932.75
      sim_grid_pos_y: 1037482.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2313914.25
      sim_grid_pos_y: 1037292
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2314292.25
      sim_grid_pos_y: 1037096.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2314606.5
      sim_grid_pos_y: 1037302.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2314427.75
      sim_grid_pos_y: 1037578.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2314124.75
      sim_grid_pos_y: 1037604
    }
    terrain_level_point {
      sim_grid_pos_x: 2313885
      sim_grid_pos_y: 1037519.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2313861.25
      sim_grid_pos_y: 1037276.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2314024.25
      sim_grid_pos_y: 1037070.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2314309.75
      sim_grid_pos_y: 1037046.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2314677.25
      sim_grid_pos_y: 1037287.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2314457
      sim_grid_pos_y: 1037627.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2314118
      sim_grid_pos_y: 1037656
    }
    terrain_level_point {
      sim_grid_pos_x: 2313837
      sim_grid_pos_y: 1037557.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2313808.25
      sim_grid_pos_y: 1037260.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2314001.5
      sim_grid_pos_y: 1037016.94
    }
  }
}
terrain_level_data {
  terrain_level: 832
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2313079.25
      sim_grid_pos_y: 1037595.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2313008.25
      sim_grid_pos_y: 1037687.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2313044.5
      sim_grid_pos_y: 1037841.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2313205.5
      sim_grid_pos_y: 1037854.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2313283.25
      sim_grid_pos_y: 1037780.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2313285.5
      sim_grid_pos_y: 1037623.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2313182.5
      sim_grid_pos_y: 1037572.19
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2313189
      sim_grid_pos_y: 1037518.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.31305e+06
      sim_grid_pos_y: 1037549.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2312952.75
      sim_grid_pos_y: 1037675.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2313003.25
      sim_grid_pos_y: 1037889.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2313224.25
      sim_grid_pos_y: 1037907.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2313334
      sim_grid_pos_y: 1037802.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2313337.25
      sim_grid_pos_y: 1037591.94
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2313195.25
      sim_grid_pos_y: 1037464.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2313020.75
      sim_grid_pos_y: 1037503.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2312897.25
      sim_grid_pos_y: 1037663.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2312962
      sim_grid_pos_y: 1037937.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2313243
      sim_grid_pos_y: 1037960.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2313385
      sim_grid_pos_y: 1037825
    }
    terrain_level_point {
      sim_grid_pos_x: 2313389
      sim_grid_pos_y: 1037560.38
    }
  }
}
terrain_level_data {
  terrain_level: 728
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2313237.25
      sim_grid_pos_y: 1037092.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2313229.5
      sim_grid_pos_y: 1037260.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2313504.5
      sim_grid_pos_y: 1037308.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2313552.25
      sim_grid_pos_y: 1037163.06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2313188.75
      sim_grid_pos_y: 1037028.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2313176.25
      sim_grid_pos_y: 1037302.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2313539.5
      sim_grid_pos_y: 1037367.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2313618.5
      sim_grid_pos_y: 1037125.44
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2313140.25
      sim_grid_pos_y: 1036965.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2313123
      sim_grid_pos_y: 1037345.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2313574.25
      sim_grid_pos_y: 1037425.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2313684.75
      sim_grid_pos_y: 1037087.81
    }
  }
}
