terrain_level_data {
  terrain_level: 300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3015667.75
      sim_grid_pos_y: 643347.125
    }
    terrain_level_point {
      sim_grid_pos_x: 3015342.75
      sim_grid_pos_y: 642890.625
    }
    terrain_level_point {
      sim_grid_pos_x: 3014316.5
      sim_grid_pos_y: 642291.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3014224.25
      sim_grid_pos_y: 642753.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3014650.5
      sim_grid_pos_y: 643906.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3014317.5
      sim_grid_pos_y: 645000.188
    }
    terrain_level_point {
      sim_grid_pos_x: 3015420.75
      sim_grid_pos_y: 645236.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3016164.5
      sim_grid_pos_y: 645591.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3016610.25
      sim_grid_pos_y: 644941.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3016316.25
      sim_grid_pos_y: 644366
    }
    terrain_level_point {
      sim_grid_pos_x: 3015704
      sim_grid_pos_y: 644358.625
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 3014171.75
      sim_grid_pos_y: 641970.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3014011.75
      sim_grid_pos_y: 642769.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3014434.25
      sim_grid_pos_y: 643912.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3014056.25
      sim_grid_pos_y: 645153.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3015354.25
      sim_grid_pos_y: 645432.312
    }
    terrain_level_point {
      sim_grid_pos_x: 3016234.5
      sim_grid_pos_y: 645852.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3016848.25
      sim_grid_pos_y: 644957.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3016442.5
      sim_grid_pos_y: 644162.438
    }
    terrain_level_point {
      sim_grid_pos_x: 3015901.75
      sim_grid_pos_y: 644155.938
    }
    terrain_level_point {
      sim_grid_pos_x: 3015870.5
      sim_grid_pos_y: 643278.312
    }
    terrain_level_point {
      sim_grid_pos_x: 3015484.25
      sim_grid_pos_y: 642735.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 3014027
      sim_grid_pos_y: 641648.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3013799.25
      sim_grid_pos_y: 642786.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3014218
      sim_grid_pos_y: 643919.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3013795
      sim_grid_pos_y: 645307.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3015287.75
      sim_grid_pos_y: 645627.812
    }
    terrain_level_point {
      sim_grid_pos_x: 3016304.25
      sim_grid_pos_y: 646112.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3017086.25
      sim_grid_pos_y: 644972.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3016568.75
      sim_grid_pos_y: 643958.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3016099.75
      sim_grid_pos_y: 643953.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3016073.25
      sim_grid_pos_y: 643209.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3015625.75
      sim_grid_pos_y: 642580.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 3013882.25
      sim_grid_pos_y: 641326.438
    }
    terrain_level_point {
      sim_grid_pos_x: 3013586.75
      sim_grid_pos_y: 642803.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3014001.75
      sim_grid_pos_y: 643925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3013533.75
      sim_grid_pos_y: 645461.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3015221.25
      sim_grid_pos_y: 645823.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3016374.25
      sim_grid_pos_y: 646373.125
    }
    terrain_level_point {
      sim_grid_pos_x: 3017324.5
      sim_grid_pos_y: 644988.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3016695
      sim_grid_pos_y: 643755.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3016297.75
      sim_grid_pos_y: 643750.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3016275.75
      sim_grid_pos_y: 643140.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3015767.25
      sim_grid_pos_y: 642426
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 3013737.5
      sim_grid_pos_y: 641004.625
    }
    terrain_level_point {
      sim_grid_pos_x: 3013374.5
      sim_grid_pos_y: 642819.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3013785.5
      sim_grid_pos_y: 643931.812
    }
    terrain_level_point {
      sim_grid_pos_x: 3013272.75
      sim_grid_pos_y: 645614.938
    }
    terrain_level_point {
      sim_grid_pos_x: 3015154.75
      sim_grid_pos_y: 646018.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3016444.25
      sim_grid_pos_y: 646633.625
    }
    terrain_level_point {
      sim_grid_pos_x: 3017562.5
      sim_grid_pos_y: 645003.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3016821.25
      sim_grid_pos_y: 643551.812
    }
    terrain_level_point {
      sim_grid_pos_x: 3016495.5
      sim_grid_pos_y: 643547.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3016478.5
      sim_grid_pos_y: 643071.938
    }
    terrain_level_point {
      sim_grid_pos_x: 3015908.75
      sim_grid_pos_y: 642271.125
    }
  }
}
