terrain_level_data {
  terrain_level: 341
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1530024
      sim_grid_pos_y: 1752885
    }
    terrain_level_point {
      sim_grid_pos_x: 1530046.75
      sim_grid_pos_y: 1753537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1530154.12
      sim_grid_pos_y: 1753544.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1530134.12
      sim_grid_pos_y: 1752873.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1530154
      sim_grid_pos_y: 1752850.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1530002.88
      sim_grid_pos_y: 1752866.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1530026.88
      sim_grid_pos_y: 1753557
    }
    terrain_level_point {
      sim_grid_pos_x: 1530175.25
      sim_grid_pos_y: 1753566.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1530173.88
      sim_grid_pos_y: 1752827.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1529981.75
      sim_grid_pos_y: 1752848.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1530007
      sim_grid_pos_y: 1753576.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1530196.5
      sim_grid_pos_y: 1753588.88
    }
  }
}
