terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 738819.75
      sim_grid_pos_y: 2024663.62
    }
    terrain_level_point {
      sim_grid_pos_x: 739082.5
      sim_grid_pos_y: 2024812.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738936.688
      sim_grid_pos_y: 2025004.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738598.188
      sim_grid_pos_y: 2025295.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738504.25
      sim_grid_pos_y: 2025789.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738193.062
      sim_grid_pos_y: 2026207.12
    }
    terrain_level_point {
      sim_grid_pos_x: 735946.875
      sim_grid_pos_y: 2027425.88
    }
    terrain_level_point {
      sim_grid_pos_x: 735942.5
      sim_grid_pos_y: 2026541.12
    }
    terrain_level_point {
      sim_grid_pos_x: 736047.25
      sim_grid_pos_y: 2026391.62
    }
    terrain_level_point {
      sim_grid_pos_x: 736290.938
      sim_grid_pos_y: 2026365.62
    }
    terrain_level_point {
      sim_grid_pos_x: 736883.125
      sim_grid_pos_y: 2026056.12
    }
    terrain_level_point {
      sim_grid_pos_x: 737038
      sim_grid_pos_y: 2025247.75
    }
    terrain_level_point {
      sim_grid_pos_x: 736725.625
      sim_grid_pos_y: 2024389.62
    }
    terrain_level_point {
      sim_grid_pos_x: 736970.125
      sim_grid_pos_y: 2023695.12
    }
    terrain_level_point {
      sim_grid_pos_x: 737560
      sim_grid_pos_y: 2022809.62
    }
    terrain_level_point {
      sim_grid_pos_x: 737914
      sim_grid_pos_y: 2022576
    }
    terrain_level_point {
      sim_grid_pos_x: 738306
      sim_grid_pos_y: 2022618.25
    }
    terrain_level_point {
      sim_grid_pos_x: 738367.562
      sim_grid_pos_y: 2022725.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738455.312
      sim_grid_pos_y: 2022985.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738707.75
      sim_grid_pos_y: 2022970.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738829.812
      sim_grid_pos_y: 2023156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738746.688
      sim_grid_pos_y: 2023372.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738501.875
      sim_grid_pos_y: 2023626.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738809
      sim_grid_pos_y: 2023986.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738500.188
      sim_grid_pos_y: 2024274.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 738324.875
      sim_grid_pos_y: 2022589.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738395.75
      sim_grid_pos_y: 2022713.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738476.938
      sim_grid_pos_y: 2022953.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738723.688
      sim_grid_pos_y: 2022939.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738864.188
      sim_grid_pos_y: 2023153.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738773.125
      sim_grid_pos_y: 2023388.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738543.375
      sim_grid_pos_y: 2023628.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738851.5
      sim_grid_pos_y: 2023989.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738542.312
      sim_grid_pos_y: 2024277.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738839.875
      sim_grid_pos_y: 2024639.62
    }
    terrain_level_point {
      sim_grid_pos_x: 739128.312
      sim_grid_pos_y: 2024803.25
    }
    terrain_level_point {
      sim_grid_pos_x: 738959.188
      sim_grid_pos_y: 2025025.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738626.375
      sim_grid_pos_y: 2025312
    }
    terrain_level_point {
      sim_grid_pos_x: 738533.125
      sim_grid_pos_y: 2025802.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738213.688
      sim_grid_pos_y: 2026230.88
    }
    terrain_level_point {
      sim_grid_pos_x: 735916.375
      sim_grid_pos_y: 2027477.38
    }
    terrain_level_point {
      sim_grid_pos_x: 735911.625
      sim_grid_pos_y: 2026531.5
    }
    terrain_level_point {
      sim_grid_pos_x: 736030.125
      sim_grid_pos_y: 2026362.5
    }
    terrain_level_point {
      sim_grid_pos_x: 736281.875
      sim_grid_pos_y: 2026335.75
    }
    terrain_level_point {
      sim_grid_pos_x: 736855.75
      sim_grid_pos_y: 2026035.75
    }
    terrain_level_point {
      sim_grid_pos_x: 737006.188
      sim_grid_pos_y: 2025250.38
    }
    terrain_level_point {
      sim_grid_pos_x: 736692.938
      sim_grid_pos_y: 2024389.88
    }
    terrain_level_point {
      sim_grid_pos_x: 736942.375
      sim_grid_pos_y: 2023681.38
    }
    terrain_level_point {
      sim_grid_pos_x: 737537.875
      sim_grid_pos_y: 2022787.5
    }
    terrain_level_point {
      sim_grid_pos_x: 737906.312
      sim_grid_pos_y: 2022544.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 738343.75
      sim_grid_pos_y: 2022560.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738423.938
      sim_grid_pos_y: 2022700.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738498.625
      sim_grid_pos_y: 2022921.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738739.625
      sim_grid_pos_y: 2022907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738898.625
      sim_grid_pos_y: 2023149.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738799.625
      sim_grid_pos_y: 2023405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738584.875
      sim_grid_pos_y: 2023629.25
    }
    terrain_level_point {
      sim_grid_pos_x: 738894
      sim_grid_pos_y: 2023991.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738584.438
      sim_grid_pos_y: 2024280.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738860.062
      sim_grid_pos_y: 2024615.75
    }
    terrain_level_point {
      sim_grid_pos_x: 739174.062
      sim_grid_pos_y: 2024793.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738981.75
      sim_grid_pos_y: 2025046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738654.625
      sim_grid_pos_y: 2025328.25
    }
    terrain_level_point {
      sim_grid_pos_x: 738562
      sim_grid_pos_y: 2025815
    }
    terrain_level_point {
      sim_grid_pos_x: 738234.312
      sim_grid_pos_y: 2026254.75
    }
    terrain_level_point {
      sim_grid_pos_x: 735885.875
      sim_grid_pos_y: 2027529
    }
    terrain_level_point {
      sim_grid_pos_x: 735880.875
      sim_grid_pos_y: 2026521.88
    }
    terrain_level_point {
      sim_grid_pos_x: 736012.938
      sim_grid_pos_y: 2026333.38
    }
    terrain_level_point {
      sim_grid_pos_x: 736272.812
      sim_grid_pos_y: 2026305.75
    }
    terrain_level_point {
      sim_grid_pos_x: 736828.312
      sim_grid_pos_y: 2026015.38
    }
    terrain_level_point {
      sim_grid_pos_x: 736974.375
      sim_grid_pos_y: 2025252.88
    }
    terrain_level_point {
      sim_grid_pos_x: 736660.312
      sim_grid_pos_y: 2.02439e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 736914.625
      sim_grid_pos_y: 2023667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 737515.75
      sim_grid_pos_y: 2022765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 737898.562
      sim_grid_pos_y: 2022512.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 738362.625
      sim_grid_pos_y: 2022531.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738452.125
      sim_grid_pos_y: 2022687.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738520.25
      sim_grid_pos_y: 2022889.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738755.625
      sim_grid_pos_y: 2022875.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738933
      sim_grid_pos_y: 2023145.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738826.062
      sim_grid_pos_y: 2023422.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738626.312
      sim_grid_pos_y: 2023630.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738936.5
      sim_grid_pos_y: 2023994.25
    }
    terrain_level_point {
      sim_grid_pos_x: 738626.562
      sim_grid_pos_y: 2024283.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738880.188
      sim_grid_pos_y: 2024591.75
    }
    terrain_level_point {
      sim_grid_pos_x: 739219.875
      sim_grid_pos_y: 2024784.5
    }
    terrain_level_point {
      sim_grid_pos_x: 739004.25
      sim_grid_pos_y: 2025068
    }
    terrain_level_point {
      sim_grid_pos_x: 738682.812
      sim_grid_pos_y: 2025344.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738590.875
      sim_grid_pos_y: 2025827.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738254.938
      sim_grid_pos_y: 2026278.5
    }
    terrain_level_point {
      sim_grid_pos_x: 735855.375
      sim_grid_pos_y: 2027580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 735850.062
      sim_grid_pos_y: 2026512.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735995.812
      sim_grid_pos_y: 2026304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 736263.75
      sim_grid_pos_y: 2026275.75
    }
    terrain_level_point {
      sim_grid_pos_x: 736800.938
      sim_grid_pos_y: 2025995
    }
    terrain_level_point {
      sim_grid_pos_x: 736942.625
      sim_grid_pos_y: 2025255.38
    }
    terrain_level_point {
      sim_grid_pos_x: 736627.625
      sim_grid_pos_y: 2024390.12
    }
    terrain_level_point {
      sim_grid_pos_x: 736886.875
      sim_grid_pos_y: 2023653.62
    }
    terrain_level_point {
      sim_grid_pos_x: 737493.625
      sim_grid_pos_y: 2022743
    }
    terrain_level_point {
      sim_grid_pos_x: 737890.875
      sim_grid_pos_y: 2022480.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 738381.562
      sim_grid_pos_y: 2022502.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738480.312
      sim_grid_pos_y: 2022675
    }
    terrain_level_point {
      sim_grid_pos_x: 738541.875
      sim_grid_pos_y: 2022857.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738771.562
      sim_grid_pos_y: 2022844
    }
    terrain_level_point {
      sim_grid_pos_x: 738967.375
      sim_grid_pos_y: 2023142.12
    }
    terrain_level_point {
      sim_grid_pos_x: 738852.562
      sim_grid_pos_y: 2023439.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738667.812
      sim_grid_pos_y: 2023631.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738979
      sim_grid_pos_y: 2023996.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738668.625
      sim_grid_pos_y: 2024285.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738900.312
      sim_grid_pos_y: 2024567.88
    }
    terrain_level_point {
      sim_grid_pos_x: 739265.625
      sim_grid_pos_y: 2024775
    }
    terrain_level_point {
      sim_grid_pos_x: 739026.75
      sim_grid_pos_y: 2025089.25
    }
    terrain_level_point {
      sim_grid_pos_x: 738711
      sim_grid_pos_y: 2025360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738619.812
      sim_grid_pos_y: 2025840.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738275.562
      sim_grid_pos_y: 2026302.38
    }
    terrain_level_point {
      sim_grid_pos_x: 735824.875
      sim_grid_pos_y: 2027632
    }
    terrain_level_point {
      sim_grid_pos_x: 735819.25
      sim_grid_pos_y: 2026502.62
    }
    terrain_level_point {
      sim_grid_pos_x: 735978.625
      sim_grid_pos_y: 2026275.12
    }
    terrain_level_point {
      sim_grid_pos_x: 736254.688
      sim_grid_pos_y: 2026245.88
    }
    terrain_level_point {
      sim_grid_pos_x: 736773.5
      sim_grid_pos_y: 2025974.62
    }
    terrain_level_point {
      sim_grid_pos_x: 736910.812
      sim_grid_pos_y: 2025258
    }
    terrain_level_point {
      sim_grid_pos_x: 736594.938
      sim_grid_pos_y: 2024390.38
    }
    terrain_level_point {
      sim_grid_pos_x: 736859.188
      sim_grid_pos_y: 2023639.75
    }
    terrain_level_point {
      sim_grid_pos_x: 737471.438
      sim_grid_pos_y: 2022720.75
    }
    terrain_level_point {
      sim_grid_pos_x: 737883.125
      sim_grid_pos_y: 2022448.88
    }
  }
}
