terrain_level_data {
  terrain_level: 380
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 781696.75
      sim_grid_pos_y: 2070895.25
    }
    terrain_level_point {
      sim_grid_pos_x: 781623
      sim_grid_pos_y: 2070827.25
    }
    terrain_level_point {
      sim_grid_pos_x: 781154.5
      sim_grid_pos_y: 2070793.88
    }
    terrain_level_point {
      sim_grid_pos_x: 781119.625
      sim_grid_pos_y: 2070082.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781239.25
      sim_grid_pos_y: 2069180.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781290.875
      sim_grid_pos_y: 2068986.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781477.688
      sim_grid_pos_y: 2068613.75
    }
    terrain_level_point {
      sim_grid_pos_x: 781610.438
      sim_grid_pos_y: 2068425.88
    }
    terrain_level_point {
      sim_grid_pos_x: 781956.312
      sim_grid_pos_y: 2068504.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782340.938
      sim_grid_pos_y: 2068696
    }
    terrain_level_point {
      sim_grid_pos_x: 782345.562
      sim_grid_pos_y: 2.07023e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 782629.812
      sim_grid_pos_y: 2070255.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782747.5
      sim_grid_pos_y: 2070777.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782524.062
      sim_grid_pos_y: 2070893.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782311.375
      sim_grid_pos_y: 2070984
    }
    terrain_level_point {
      sim_grid_pos_x: 781737.75
      sim_grid_pos_y: 2070975.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 781959.812
      sim_grid_pos_y: 2068494.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782351.188
      sim_grid_pos_y: 2068689.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782355.812
      sim_grid_pos_y: 2070220.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782638.188
      sim_grid_pos_y: 2070246.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782759.25
      sim_grid_pos_y: 2070783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782528.438
      sim_grid_pos_y: 2070903.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782313.375
      sim_grid_pos_y: 2070994.38
    }
    terrain_level_point {
      sim_grid_pos_x: 781731.438
      sim_grid_pos_y: 2070985.38
    }
    terrain_level_point {
      sim_grid_pos_x: 781688.438
      sim_grid_pos_y: 2070901.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781618.688
      sim_grid_pos_y: 2070837.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781144.688
      sim_grid_pos_y: 2070803.38
    }
    terrain_level_point {
      sim_grid_pos_x: 781109.312
      sim_grid_pos_y: 2070081.75
    }
    terrain_level_point {
      sim_grid_pos_x: 781229.188
      sim_grid_pos_y: 2069178.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781281.25
      sim_grid_pos_y: 2068982.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781468.875
      sim_grid_pos_y: 2068608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781606
      sim_grid_pos_y: 2068414.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 781963.25
      sim_grid_pos_y: 2068485.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782361.438
      sim_grid_pos_y: 2068683.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782366
      sim_grid_pos_y: 2070211.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782646.562
      sim_grid_pos_y: 2070236.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782771
      sim_grid_pos_y: 2070788.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782532.812
      sim_grid_pos_y: 2070912.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782315.375
      sim_grid_pos_y: 2071004.62
    }
    terrain_level_point {
      sim_grid_pos_x: 781725.125
      sim_grid_pos_y: 2070995.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781680.125
      sim_grid_pos_y: 2070907.88
    }
    terrain_level_point {
      sim_grid_pos_x: 781614.375
      sim_grid_pos_y: 2070847.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781134.875
      sim_grid_pos_y: 2070813
    }
    terrain_level_point {
      sim_grid_pos_x: 781099.062
      sim_grid_pos_y: 2070081.38
    }
    terrain_level_point {
      sim_grid_pos_x: 781219.125
      sim_grid_pos_y: 2069176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781271.625
      sim_grid_pos_y: 2068978.75
    }
    terrain_level_point {
      sim_grid_pos_x: 781460.062
      sim_grid_pos_y: 2068603.25
    }
    terrain_level_point {
      sim_grid_pos_x: 781601.562
      sim_grid_pos_y: 2068402.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 781966.75
      sim_grid_pos_y: 2068475.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782371.625
      sim_grid_pos_y: 2068676.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782376.25
      sim_grid_pos_y: 2070201.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782654.938
      sim_grid_pos_y: 2070227
    }
    terrain_level_point {
      sim_grid_pos_x: 782782.688
      sim_grid_pos_y: 2070794.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782537.188
      sim_grid_pos_y: 2070921.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782317.375
      sim_grid_pos_y: 2071014.88
    }
    terrain_level_point {
      sim_grid_pos_x: 781718.812
      sim_grid_pos_y: 2071005.62
    }
    terrain_level_point {
      sim_grid_pos_x: 781671.875
      sim_grid_pos_y: 2070914.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781610.062
      sim_grid_pos_y: 2070857.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781125.062
      sim_grid_pos_y: 2070822.62
    }
    terrain_level_point {
      sim_grid_pos_x: 781088.75
      sim_grid_pos_y: 2070080.88
    }
    terrain_level_point {
      sim_grid_pos_x: 781209.062
      sim_grid_pos_y: 2069174.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781262
      sim_grid_pos_y: 2068975.12
    }
    terrain_level_point {
      sim_grid_pos_x: 781451.25
      sim_grid_pos_y: 2068598
    }
    terrain_level_point {
      sim_grid_pos_x: 781597.188
      sim_grid_pos_y: 2068391.38
    }
  }
}
terrain_level_data {
  terrain_level: 400
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 782330.625
      sim_grid_pos_y: 2070225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782318.438
      sim_grid_pos_y: 2069123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782653.625
      sim_grid_pos_y: 2069110.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782658.188
      sim_grid_pos_y: 2070234.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 782678.812
      sim_grid_pos_y: 2070255.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782310.312
      sim_grid_pos_y: 2070245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782297.688
      sim_grid_pos_y: 2069103.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782674
      sim_grid_pos_y: 2069089.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 782699.375
      sim_grid_pos_y: 2070276.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782290.062
      sim_grid_pos_y: 2070265.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782277
      sim_grid_pos_y: 2069083.62
    }
    terrain_level_point {
      sim_grid_pos_x: 782694.438
      sim_grid_pos_y: 2069067.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 782720
      sim_grid_pos_y: 2070297.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782269.75
      sim_grid_pos_y: 2070285.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782256.25
      sim_grid_pos_y: 2069063.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782714.875
      sim_grid_pos_y: 2069046.5
    }
  }
}
