terrain_level_data {
  terrain_level: 112
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2626874
      sim_grid_pos_y: 383322.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2627319.5
      sim_grid_pos_y: 383350.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2627557.5
      sim_grid_pos_y: 383638.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2627457
      sim_grid_pos_y: 384191.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2627113.5
      sim_grid_pos_y: 384352.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2626758.75
      sim_grid_pos_y: 384310.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2626502
      sim_grid_pos_y: 383978.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2626575
      sim_grid_pos_y: 383543.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2627345
      sim_grid_pos_y: 383300.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2627612.25
      sim_grid_pos_y: 383624.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2627502.5
      sim_grid_pos_y: 384226.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2627122
      sim_grid_pos_y: 384404.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2626731.5
      sim_grid_pos_y: 384358.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2626447.75
      sim_grid_pos_y: 383991.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2626528
      sim_grid_pos_y: 383514.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2626858.5
      sim_grid_pos_y: 383270.219
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2627370.25
      sim_grid_pos_y: 383250.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2627667
      sim_grid_pos_y: 383610
    }
    terrain_level_point {
      sim_grid_pos_x: 2627548.25
      sim_grid_pos_y: 384262.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2627130.5
      sim_grid_pos_y: 384457.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2626704
      sim_grid_pos_y: 384407.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2626393.5
      sim_grid_pos_y: 384005.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2626480.75
      sim_grid_pos_y: 383485.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2626843
      sim_grid_pos_y: 383217.906
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2627395.75
      sim_grid_pos_y: 383200.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2627721.75
      sim_grid_pos_y: 383595.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2627594
      sim_grid_pos_y: 384297.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2627139
      sim_grid_pos_y: 384510.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2626676.5
      sim_grid_pos_y: 384455.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2626339.25
      sim_grid_pos_y: 384019.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2626433.75
      sim_grid_pos_y: 383456.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2626827.5
      sim_grid_pos_y: 383165.594
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2627421
      sim_grid_pos_y: 383151.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2627776.5
      sim_grid_pos_y: 383581.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2627639.75
      sim_grid_pos_y: 384332.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2627147.5
      sim_grid_pos_y: 384562.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2626649.25
      sim_grid_pos_y: 384503.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2626285
      sim_grid_pos_y: 384032.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2626386.5
      sim_grid_pos_y: 383427.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2626812.25
      sim_grid_pos_y: 383113.25
    }
  }
}
terrain_level_data {
  terrain_level: 109
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2.62784e+06
      sim_grid_pos_y: 384292.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2627813.75
      sim_grid_pos_y: 384480.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2628398
      sim_grid_pos_y: 384719.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2628511.5
      sim_grid_pos_y: 384342.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2628098.75
      sim_grid_pos_y: 384183.156
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2628097.75
      sim_grid_pos_y: 384127.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2627793.25
      sim_grid_pos_y: 384256.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2627757.25
      sim_grid_pos_y: 384513.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2628430.75
      sim_grid_pos_y: 384788.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2628574.5
      sim_grid_pos_y: 384312.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2628097
      sim_grid_pos_y: 384072.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2627746.75
      sim_grid_pos_y: 384220.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2627701
      sim_grid_pos_y: 384545.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2628463.75
      sim_grid_pos_y: 384857.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2628637.25
      sim_grid_pos_y: 384281.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2628096
      sim_grid_pos_y: 384017.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2.6277e+06
      sim_grid_pos_y: 384184.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2627644.75
      sim_grid_pos_y: 384577.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2628496.5
      sim_grid_pos_y: 384926
    }
    terrain_level_point {
      sim_grid_pos_x: 2.6287e+06
      sim_grid_pos_y: 384250.844
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2628095.25
      sim_grid_pos_y: 383961.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2627653.25
      sim_grid_pos_y: 384148.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2627588.25
      sim_grid_pos_y: 384610.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2628529.25
      sim_grid_pos_y: 384994.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2628762.75
      sim_grid_pos_y: 384220.156
    }
  }
}
