terrain_level_data {
  terrain_level: 120
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1873023.5
      sim_grid_pos_y: 1220100.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1872951.88
      sim_grid_pos_y: 1220280.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1873042.12
      sim_grid_pos_y: 1220460.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1873200.75
      sim_grid_pos_y: 1220555
    }
    terrain_level_point {
      sim_grid_pos_x: 1873332.25
      sim_grid_pos_y: 1220484.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1873423
      sim_grid_pos_y: 1220301.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1873364
      sim_grid_pos_y: 1220098.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1873200.5
      sim_grid_pos_y: 1220035.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1873201.5
      sim_grid_pos_y: 1219926.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1872945.12
      sim_grid_pos_y: 1220019.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1872839.62
      sim_grid_pos_y: 1220285.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1872964
      sim_grid_pos_y: 1220533.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1873198.25
      sim_grid_pos_y: 1220672.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1873409.62
      sim_grid_pos_y: 1220558.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1873532.62
      sim_grid_pos_y: 1220311
    }
    terrain_level_point {
      sim_grid_pos_x: 1873448.25
      sim_grid_pos_y: 1220021
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1873202.38
      sim_grid_pos_y: 1219816.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1872866.88
      sim_grid_pos_y: 1219938.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1872727.38
      sim_grid_pos_y: 1220290.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1872885.75
      sim_grid_pos_y: 1220606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1873195.75
      sim_grid_pos_y: 1220790.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1873487
      sim_grid_pos_y: 1220633.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1873642.25
      sim_grid_pos_y: 1220320.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1873532.5
      sim_grid_pos_y: 1219943.5
    }
  }
}
terrain_level_data {
  terrain_level: 58
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1869567.38
      sim_grid_pos_y: 1209378.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1870535.75
      sim_grid_pos_y: 1209292.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1870395.38
      sim_grid_pos_y: 1204366
    }
    terrain_level_point {
      sim_grid_pos_x: 1869326.88
      sim_grid_pos_y: 1204419.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1870445.12
      sim_grid_pos_y: 1204312.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1869273.12
      sim_grid_pos_y: 1204370.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1869518.75
      sim_grid_pos_y: 1209434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1870588.38
      sim_grid_pos_y: 1209339.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1870494.88
      sim_grid_pos_y: 1204258.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1869219.5
      sim_grid_pos_y: 1204322
    }
    terrain_level_point {
      sim_grid_pos_x: 1869470.12
      sim_grid_pos_y: 1.20949e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1870640.88
      sim_grid_pos_y: 1209386.12
    }
  }
}
