terrain_level_data {
  terrain_level: 1636
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1519936.75
      sim_grid_pos_y: 1609186.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1519896
      sim_grid_pos_y: 1609123.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1519911.75
      sim_grid_pos_y: 1609066.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520261.25
      sim_grid_pos_y: 1609166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520430.12
      sim_grid_pos_y: 1609326.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1520723.62
      sim_grid_pos_y: 1609258.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520869.25
      sim_grid_pos_y: 1609381.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1521066.75
      sim_grid_pos_y: 1609481.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1521349.25
      sim_grid_pos_y: 1609249.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521570.38
      sim_grid_pos_y: 1608959.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1521586.12
      sim_grid_pos_y: 1608827.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1521692.12
      sim_grid_pos_y: 1608858.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521668.5
      sim_grid_pos_y: 1609158.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1521245.62
      sim_grid_pos_y: 1609608.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1521388.75
      sim_grid_pos_y: 1609751
    }
    terrain_level_point {
      sim_grid_pos_x: 1521315.5
      sim_grid_pos_y: 1609869.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520943.62
      sim_grid_pos_y: 1609625
    }
    terrain_level_point {
      sim_grid_pos_x: 1520672.5
      sim_grid_pos_y: 1609639.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1520584.25
      sim_grid_pos_y: 1609754.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1520498.62
      sim_grid_pos_y: 1609706.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520504.12
      sim_grid_pos_y: 1609597.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1520335.25
      sim_grid_pos_y: 1609414.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1521735.62
      sim_grid_pos_y: 1608828.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1521708.25
      sim_grid_pos_y: 1609176.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1521302.75
      sim_grid_pos_y: 1609607.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1521440.75
      sim_grid_pos_y: 1609745
    }
    terrain_level_point {
      sim_grid_pos_x: 1521328.12
      sim_grid_pos_y: 1609926.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520932.38
      sim_grid_pos_y: 1609666.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520693.5
      sim_grid_pos_y: 1609679.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1520595
      sim_grid_pos_y: 1609807.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1520456.5
      sim_grid_pos_y: 1609729.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520462.38
      sim_grid_pos_y: 1609612.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1520309.38
      sim_grid_pos_y: 1609446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1519907.88
      sim_grid_pos_y: 1609216.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1519851.62
      sim_grid_pos_y: 1609130.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1519883.12
      sim_grid_pos_y: 1609015.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1520282.12
      sim_grid_pos_y: 1609129.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520442.38
      sim_grid_pos_y: 1609281.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520734.38
      sim_grid_pos_y: 1609213.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1520892.12
      sim_grid_pos_y: 1609346.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1521061.5
      sim_grid_pos_y: 1609433
    }
    terrain_level_point {
      sim_grid_pos_x: 1521319.5
      sim_grid_pos_y: 1609220.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1521531
      sim_grid_pos_y: 1608943.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1521551.25
      sim_grid_pos_y: 1608774.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1521779.12
      sim_grid_pos_y: 1608798.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1521748
      sim_grid_pos_y: 1609193.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1521359.88
      sim_grid_pos_y: 1609606.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1521492.75
      sim_grid_pos_y: 1609739
    }
    terrain_level_point {
      sim_grid_pos_x: 1521340.88
      sim_grid_pos_y: 1609984
    }
    terrain_level_point {
      sim_grid_pos_x: 1520921.12
      sim_grid_pos_y: 1609708.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1520714.5
      sim_grid_pos_y: 1609719.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520605.88
      sim_grid_pos_y: 1609860.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520414.25
      sim_grid_pos_y: 1609752.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1520420.5
      sim_grid_pos_y: 1609628
    }
    terrain_level_point {
      sim_grid_pos_x: 1520283.5
      sim_grid_pos_y: 1609479.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1519878.88
      sim_grid_pos_y: 1609247.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1519807.12
      sim_grid_pos_y: 1609137.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1519854.62
      sim_grid_pos_y: 1608964.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520303.12
      sim_grid_pos_y: 1609092.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1520454.62
      sim_grid_pos_y: 1609236.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1520745.12
      sim_grid_pos_y: 1609169.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1520914.88
      sim_grid_pos_y: 1609312.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521056.12
      sim_grid_pos_y: 1609384.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1521289.88
      sim_grid_pos_y: 1609192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1521491.62
      sim_grid_pos_y: 1608927.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1521516.25
      sim_grid_pos_y: 1608721
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1521822.62
      sim_grid_pos_y: 1608768.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1521787.75
      sim_grid_pos_y: 1609211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521417
      sim_grid_pos_y: 1609605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521544.75
      sim_grid_pos_y: 1609732.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1521353.5
      sim_grid_pos_y: 1610041.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1520909.88
      sim_grid_pos_y: 1.60975e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1520735.5
      sim_grid_pos_y: 1609759.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1520616.62
      sim_grid_pos_y: 1609913.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1520372
      sim_grid_pos_y: 1609776.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1520378.62
      sim_grid_pos_y: 1609643.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1520257.62
      sim_grid_pos_y: 1609511.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.51985e+06
      sim_grid_pos_y: 1609278.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1519762.75
      sim_grid_pos_y: 1609144.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1519826
      sim_grid_pos_y: 1608913.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1520324
      sim_grid_pos_y: 1609056.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1520466.75
      sim_grid_pos_y: 1609191.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1520755.88
      sim_grid_pos_y: 1609124.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1520937.75
      sim_grid_pos_y: 1609278.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1521050.75
      sim_grid_pos_y: 1609335.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1521260.12
      sim_grid_pos_y: 1609163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521452.25
      sim_grid_pos_y: 1608911.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1521481.25
      sim_grid_pos_y: 1608667.88
    }
  }
}
