terrain_level_data {
  terrain_level: 125
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 811396.688
      sim_grid_pos_y: 1943324.62
    }
    terrain_level_point {
      sim_grid_pos_x: 812524.375
      sim_grid_pos_y: 1943240.88
    }
    terrain_level_point {
      sim_grid_pos_x: 814029.062
      sim_grid_pos_y: 1942606.5
    }
    terrain_level_point {
      sim_grid_pos_x: 815126.062
      sim_grid_pos_y: 1941867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 815685
      sim_grid_pos_y: 1941177.38
    }
    terrain_level_point {
      sim_grid_pos_x: 816179.188
      sim_grid_pos_y: 1940300.62
    }
    terrain_level_point {
      sim_grid_pos_x: 816036.062
      sim_grid_pos_y: 1937087.25
    }
    terrain_level_point {
      sim_grid_pos_x: 815914.812
      sim_grid_pos_y: 1935380.25
    }
    terrain_level_point {
      sim_grid_pos_x: 808781.625
      sim_grid_pos_y: 1935618.38
    }
    terrain_level_point {
      sim_grid_pos_x: 808135.812
      sim_grid_pos_y: 1936746
    }
    terrain_level_point {
      sim_grid_pos_x: 802441.5
      sim_grid_pos_y: 1936926.38
    }
    terrain_level_point {
      sim_grid_pos_x: 802155.688
      sim_grid_pos_y: 1937587.25
    }
    terrain_level_point {
      sim_grid_pos_x: 801228.062
      sim_grid_pos_y: 1938535.62
    }
    terrain_level_point {
      sim_grid_pos_x: 801283.562
      sim_grid_pos_y: 1940969.38
    }
    terrain_level_point {
      sim_grid_pos_x: 802305.75
      sim_grid_pos_y: 1941901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 803076.188
      sim_grid_pos_y: 1942730.88
    }
    terrain_level_point {
      sim_grid_pos_x: 803621.188
      sim_grid_pos_y: 1943137.12
    }
    terrain_level_point {
      sim_grid_pos_x: 804301.5
      sim_grid_pos_y: 1943479
    }
    terrain_level_point {
      sim_grid_pos_x: 804849.375
      sim_grid_pos_y: 1943639.12
    }
    terrain_level_point {
      sim_grid_pos_x: 805380.688
      sim_grid_pos_y: 1943737.75
    }
    terrain_level_point {
      sim_grid_pos_x: 806124
      sim_grid_pos_y: 1.94373e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 815943.375
      sim_grid_pos_y: 1935348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 808763.5
      sim_grid_pos_y: 1935588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 808117.688
      sim_grid_pos_y: 1936715.75
    }
    terrain_level_point {
      sim_grid_pos_x: 802421
      sim_grid_pos_y: 1936896.25
    }
    terrain_level_point {
      sim_grid_pos_x: 802129.75
      sim_grid_pos_y: 1937569.88
    }
    terrain_level_point {
      sim_grid_pos_x: 801197.062
      sim_grid_pos_y: 1938523.38
    }
    terrain_level_point {
      sim_grid_pos_x: 801253.062
      sim_grid_pos_y: 1940983.25
    }
    terrain_level_point {
      sim_grid_pos_x: 802284.062
      sim_grid_pos_y: 1941923.62
    }
    terrain_level_point {
      sim_grid_pos_x: 803055.562
      sim_grid_pos_y: 1942753.88
    }
    terrain_level_point {
      sim_grid_pos_x: 803605
      sim_grid_pos_y: 1943163.38
    }
    terrain_level_point {
      sim_grid_pos_x: 804290.188
      sim_grid_pos_y: 1943507.75
    }
    terrain_level_point {
      sim_grid_pos_x: 804842.25
      sim_grid_pos_y: 1943669.12
    }
    terrain_level_point {
      sim_grid_pos_x: 805378
      sim_grid_pos_y: 1943768.5
    }
    terrain_level_point {
      sim_grid_pos_x: 806125.312
      sim_grid_pos_y: 1943760.75
    }
    terrain_level_point {
      sim_grid_pos_x: 811399
      sim_grid_pos_y: 1943355.25
    }
    terrain_level_point {
      sim_grid_pos_x: 811399
      sim_grid_pos_y: 1943355.25
    }
    terrain_level_point {
      sim_grid_pos_x: 812531.688
      sim_grid_pos_y: 1943271.12
    }
    terrain_level_point {
      sim_grid_pos_x: 814043.75
      sim_grid_pos_y: 1942633.62
    }
    terrain_level_point {
      sim_grid_pos_x: 815147.062
      sim_grid_pos_y: 1941890.25
    }
    terrain_level_point {
      sim_grid_pos_x: 815710.5
      sim_grid_pos_y: 1941194.75
    }
    terrain_level_point {
      sim_grid_pos_x: 816210.312
      sim_grid_pos_y: 1940308.12
    }
    terrain_level_point {
      sim_grid_pos_x: 816066.75
      sim_grid_pos_y: 1937085.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 815972
      sim_grid_pos_y: 1935316.75
    }
    terrain_level_point {
      sim_grid_pos_x: 808745.312
      sim_grid_pos_y: 1935558
    }
    terrain_level_point {
      sim_grid_pos_x: 808099.5
      sim_grid_pos_y: 1936685.62
    }
    terrain_level_point {
      sim_grid_pos_x: 802400.5
      sim_grid_pos_y: 1936866.12
    }
    terrain_level_point {
      sim_grid_pos_x: 802103.75
      sim_grid_pos_y: 1937552.38
    }
    terrain_level_point {
      sim_grid_pos_x: 801166
      sim_grid_pos_y: 1938511.12
    }
    terrain_level_point {
      sim_grid_pos_x: 801222.625
      sim_grid_pos_y: 1940997.12
    }
    terrain_level_point {
      sim_grid_pos_x: 802262.5
      sim_grid_pos_y: 1941945.62
    }
    terrain_level_point {
      sim_grid_pos_x: 803034.938
      sim_grid_pos_y: 1942776.88
    }
    terrain_level_point {
      sim_grid_pos_x: 803588.75
      sim_grid_pos_y: 1943189.62
    }
    terrain_level_point {
      sim_grid_pos_x: 804278.875
      sim_grid_pos_y: 1943536.5
    }
    terrain_level_point {
      sim_grid_pos_x: 804835.125
      sim_grid_pos_y: 1943699
    }
    terrain_level_point {
      sim_grid_pos_x: 805375.312
      sim_grid_pos_y: 1943799.25
    }
    terrain_level_point {
      sim_grid_pos_x: 806126.625
      sim_grid_pos_y: 1943791.5
    }
    terrain_level_point {
      sim_grid_pos_x: 811401.25
      sim_grid_pos_y: 1943385.88
    }
    terrain_level_point {
      sim_grid_pos_x: 811401.25
      sim_grid_pos_y: 1943385.88
    }
    terrain_level_point {
      sim_grid_pos_x: 812539
      sim_grid_pos_y: 1943301.38
    }
    terrain_level_point {
      sim_grid_pos_x: 814058.438
      sim_grid_pos_y: 1942660.88
    }
    terrain_level_point {
      sim_grid_pos_x: 815168.062
      sim_grid_pos_y: 1941913.12
    }
    terrain_level_point {
      sim_grid_pos_x: 815736
      sim_grid_pos_y: 1941212.12
    }
    terrain_level_point {
      sim_grid_pos_x: 816241.438
      sim_grid_pos_y: 1940315.5
    }
    terrain_level_point {
      sim_grid_pos_x: 816097.5
      sim_grid_pos_y: 1937083.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 816000.562
      sim_grid_pos_y: 1935285.12
    }
    terrain_level_point {
      sim_grid_pos_x: 808727.125
      sim_grid_pos_y: 1935527.88
    }
    terrain_level_point {
      sim_grid_pos_x: 808081.375
      sim_grid_pos_y: 1936655.38
    }
    terrain_level_point {
      sim_grid_pos_x: 802380.062
      sim_grid_pos_y: 1936836
    }
    terrain_level_point {
      sim_grid_pos_x: 802077.812
      sim_grid_pos_y: 1937535
    }
    terrain_level_point {
      sim_grid_pos_x: 801134.938
      sim_grid_pos_y: 1938498.88
    }
    terrain_level_point {
      sim_grid_pos_x: 801192.188
      sim_grid_pos_y: 1941010.88
    }
    terrain_level_point {
      sim_grid_pos_x: 802240.688
      sim_grid_pos_y: 1941967.38
    }
    terrain_level_point {
      sim_grid_pos_x: 803014.312
      sim_grid_pos_y: 1942799.88
    }
    terrain_level_point {
      sim_grid_pos_x: 803572.562
      sim_grid_pos_y: 1943215.88
    }
    terrain_level_point {
      sim_grid_pos_x: 804267.562
      sim_grid_pos_y: 1943565.25
    }
    terrain_level_point {
      sim_grid_pos_x: 804828
      sim_grid_pos_y: 1943729
    }
    terrain_level_point {
      sim_grid_pos_x: 805372.688
      sim_grid_pos_y: 1943830.12
    }
    terrain_level_point {
      sim_grid_pos_x: 806128
      sim_grid_pos_y: 1943822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 811403.5
      sim_grid_pos_y: 1943416.62
    }
    terrain_level_point {
      sim_grid_pos_x: 811403.5
      sim_grid_pos_y: 1943416.62
    }
    terrain_level_point {
      sim_grid_pos_x: 812546.312
      sim_grid_pos_y: 1943331.75
    }
    terrain_level_point {
      sim_grid_pos_x: 814073.188
      sim_grid_pos_y: 1942688
    }
    terrain_level_point {
      sim_grid_pos_x: 815189.062
      sim_grid_pos_y: 1941936.12
    }
    terrain_level_point {
      sim_grid_pos_x: 815761.562
      sim_grid_pos_y: 1941229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 816272.562
      sim_grid_pos_y: 1940322.88
    }
    terrain_level_point {
      sim_grid_pos_x: 816128.188
      sim_grid_pos_y: 1937082
    }
  }
}
