terrain_level_data {
  terrain_level: 94
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1216644.88
      sim_grid_pos_y: 1537895.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1216672.62
      sim_grid_pos_y: 1537378.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1216748.25
      sim_grid_pos_y: 1536781.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217933.12
      sim_grid_pos_y: 1535219.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1220533.75
      sim_grid_pos_y: 1532595.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1222925.12
      sim_grid_pos_y: 1532326.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1226110.12
      sim_grid_pos_y: 1531764.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1227008.25
      sim_grid_pos_y: 1536113.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1220933.25
      sim_grid_pos_y: 1539026.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217109.5
      sim_grid_pos_y: 1540401
    }
    terrain_level_point {
      sim_grid_pos_x: 1216596.75
      sim_grid_pos_y: 1539873
    }
    terrain_level_point {
      sim_grid_pos_x: 1216515.62
      sim_grid_pos_y: 1539119.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1216715.88
      sim_grid_pos_y: 1538510.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1216457.38
      sim_grid_pos_y: 1538469
    }
    terrain_level_point {
      sim_grid_pos_x: 1216314.5
      sim_grid_pos_y: 1538722.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1215810.5
      sim_grid_pos_y: 1538668.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1215718.75
      sim_grid_pos_y: 1538353.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1215913.12
      sim_grid_pos_y: 1537386.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1216488
      sim_grid_pos_y: 1537501.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216464.38
      sim_grid_pos_y: 1537906.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1227031.62
      sim_grid_pos_y: 1536125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1220941.12
      sim_grid_pos_y: 1539045.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1217104
      sim_grid_pos_y: 1540424.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1216577.12
      sim_grid_pos_y: 1539882.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1216494.75
      sim_grid_pos_y: 1539117
    }
    terrain_level_point {
      sim_grid_pos_x: 1216688.88
      sim_grid_pos_y: 1538526.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1216468.25
      sim_grid_pos_y: 1538491.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1216325.62
      sim_grid_pos_y: 1538744.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1215794.62
      sim_grid_pos_y: 1538687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1215697.75
      sim_grid_pos_y: 1538354.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1215897.12
      sim_grid_pos_y: 1537361.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1216509.5
      sim_grid_pos_y: 1537485.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1216486.25
      sim_grid_pos_y: 1537884.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1216625.38
      sim_grid_pos_y: 1537876.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1216652.12
      sim_grid_pos_y: 1537376.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216728.62
      sim_grid_pos_y: 1536773.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217917.62
      sim_grid_pos_y: 1535206.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1220524.25
      sim_grid_pos_y: 1532575.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1222922.25
      sim_grid_pos_y: 1532306.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1226126.12
      sim_grid_pos_y: 1531741.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1227054.88
      sim_grid_pos_y: 1536137
    }
    terrain_level_point {
      sim_grid_pos_x: 1220949
      sim_grid_pos_y: 1539064.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1217098.5
      sim_grid_pos_y: 1540448.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1216557.5
      sim_grid_pos_y: 1539891.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1216473.88
      sim_grid_pos_y: 1539114.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216661.88
      sim_grid_pos_y: 1538543.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1216479.12
      sim_grid_pos_y: 1538514
    }
    terrain_level_point {
      sim_grid_pos_x: 1216336.88
      sim_grid_pos_y: 1538766.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1215778.75
      sim_grid_pos_y: 1538706.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1215676.62
      sim_grid_pos_y: 1538355.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1215881
      sim_grid_pos_y: 1537337.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216531
      sim_grid_pos_y: 1537468.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1216508
      sim_grid_pos_y: 1537862.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1216605.88
      sim_grid_pos_y: 1537857
    }
    terrain_level_point {
      sim_grid_pos_x: 1216631.75
      sim_grid_pos_y: 1537374.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1216708.88
      sim_grid_pos_y: 1536765.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217902.12
      sim_grid_pos_y: 1535192.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1220514.75
      sim_grid_pos_y: 1532556.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1222919.12
      sim_grid_pos_y: 1532286.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1226142.25
      sim_grid_pos_y: 1531717.62
    }
  }
}
