terrain_level_data {
  terrain_level: 18
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2.1291e+06
      sim_grid_pos_y: 1673036.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2129955.25
      sim_grid_pos_y: 1670742.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2135032
      sim_grid_pos_y: 1670038.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2136838.25
      sim_grid_pos_y: 1671314
    }
    terrain_level_point {
      sim_grid_pos_x: 2138144.5
      sim_grid_pos_y: 1671864.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2138836.5
      sim_grid_pos_y: 1672382.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2138221.75
      sim_grid_pos_y: 1673377
    }
    terrain_level_point {
      sim_grid_pos_x: 2131331
      sim_grid_pos_y: 1672563.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2130263.75
      sim_grid_pos_y: 1673352.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2136888.5
      sim_grid_pos_y: 1671223.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2138195.75
      sim_grid_pos_y: 1671775
    }
    terrain_level_point {
      sim_grid_pos_x: 2138973
      sim_grid_pos_y: 1672356.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2138274.75
      sim_grid_pos_y: 1673486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2131359.25
      sim_grid_pos_y: 1.67267e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2130284.75
      sim_grid_pos_y: 1673464.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2128964.75
      sim_grid_pos_y: 1673105.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2129880.5
      sim_grid_pos_y: 1670649.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2135058
      sim_grid_pos_y: 1669931.25
    }
  }
}
