terrain_level_data {
  terrain_level: 190
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1734613.75
      sim_grid_pos_y: 1192772.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734619.5
      sim_grid_pos_y: 1193039.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1734752.38
      sim_grid_pos_y: 1193041.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1734757.88
      sim_grid_pos_y: 1192783.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1734508.88
      sim_grid_pos_y: 1192661.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734519.12
      sim_grid_pos_y: 1193141.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1734852.75
      sim_grid_pos_y: 1193145.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1734862.5
      sim_grid_pos_y: 1192688.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1734403.88
      sim_grid_pos_y: 1192550.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734418.75
      sim_grid_pos_y: 1193242.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1734953
      sim_grid_pos_y: 1193248.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734967
      sim_grid_pos_y: 1192593.88
    }
  }
}
terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1738065.12
      sim_grid_pos_y: 1200622.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1738097.62
      sim_grid_pos_y: 1200735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738196.38
      sim_grid_pos_y: 1200778
    }
    terrain_level_point {
      sim_grid_pos_x: 1738289.75
      sim_grid_pos_y: 1200749.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738343.38
      sim_grid_pos_y: 1200621.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738323.75
      sim_grid_pos_y: 1200492.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738199.12
      sim_grid_pos_y: 1200445.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1738091.25
      sim_grid_pos_y: 1200490.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1738197.25
      sim_grid_pos_y: 1200335.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738001.25
      sim_grid_pos_y: 1200416.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737959.75
      sim_grid_pos_y: 1200627.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738012.5
      sim_grid_pos_y: 1200810.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738190.25
      sim_grid_pos_y: 1200887
    }
    terrain_level_point {
      sim_grid_pos_x: 1738365.75
      sim_grid_pos_y: 1200833.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738449
      sim_grid_pos_y: 1200634.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738416
      sim_grid_pos_y: 1200417.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1738195.5
      sim_grid_pos_y: 1200225.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737911.38
      sim_grid_pos_y: 1200342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1737854.38
      sim_grid_pos_y: 1200631.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1737927.38
      sim_grid_pos_y: 1200885.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738184.12
      sim_grid_pos_y: 1200996
    }
    terrain_level_point {
      sim_grid_pos_x: 1738441.62
      sim_grid_pos_y: 1200918
    }
    terrain_level_point {
      sim_grid_pos_x: 1738554.75
      sim_grid_pos_y: 1200647.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738508.38
      sim_grid_pos_y: 1200342.62
    }
  }
}
terrain_level_data {
  terrain_level: 75
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1737511.88
      sim_grid_pos_y: 1201605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737505.38
      sim_grid_pos_y: 1201814.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1737751.62
      sim_grid_pos_y: 1201811.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737760.12
      sim_grid_pos_y: 1201589.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1737813.5
      sim_grid_pos_y: 1201534.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737462
      sim_grid_pos_y: 1201557.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737452.5
      sim_grid_pos_y: 1201865.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1737801
      sim_grid_pos_y: 1201862
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1737866.88
      sim_grid_pos_y: 1201479.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737412.25
      sim_grid_pos_y: 1201509.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737399.62
      sim_grid_pos_y: 1201917.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1737850.38
      sim_grid_pos_y: 1201912.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1737920.25
      sim_grid_pos_y: 1201424.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1737362.38
      sim_grid_pos_y: 1201461.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1737346.75
      sim_grid_pos_y: 1201969.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1737899.75
      sim_grid_pos_y: 1201963.5
    }
  }
}
terrain_level_data {
  terrain_level: 108
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1738626
      sim_grid_pos_y: 1200366.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738627.75
      sim_grid_pos_y: 1200593.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738846.75
      sim_grid_pos_y: 1200595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738845.38
      sim_grid_pos_y: 1200370.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1738522.62
      sim_grid_pos_y: 1200262.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1738526
      sim_grid_pos_y: 1200694.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738949.88
      sim_grid_pos_y: 1200699.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738947.25
      sim_grid_pos_y: 1200269.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1738419.25
      sim_grid_pos_y: 1200158.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738424.25
      sim_grid_pos_y: 1200795.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1739053
      sim_grid_pos_y: 1200803.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1739049.25
      sim_grid_pos_y: 1200168.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1738315.88
      sim_grid_pos_y: 1200054.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738322.62
      sim_grid_pos_y: 1200897.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1739156.12
      sim_grid_pos_y: 1200906.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1739151.12
      sim_grid_pos_y: 1200067.62
    }
  }
}
terrain_level_data {
  terrain_level: 100
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1737500.38
      sim_grid_pos_y: 1189888.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1737475.62
      sim_grid_pos_y: 1190033
    }
    terrain_level_point {
      sim_grid_pos_x: 1737481.38
      sim_grid_pos_y: 1190266
    }
    terrain_level_point {
      sim_grid_pos_x: 1737688.25
      sim_grid_pos_y: 1190270.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737722.88
      sim_grid_pos_y: 1190111.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1737727.12
      sim_grid_pos_y: 1189904.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1737457.75
      sim_grid_pos_y: 1189834.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737424.25
      sim_grid_pos_y: 1190029.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737459.88
      sim_grid_pos_y: 1190281.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737696.62
      sim_grid_pos_y: 1190285.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1737774
      sim_grid_pos_y: 1190117.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737779.5
      sim_grid_pos_y: 1189856.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1737415
      sim_grid_pos_y: 1189780.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1737372.88
      sim_grid_pos_y: 1190025.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737440.5
      sim_grid_pos_y: 1190311.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737703
      sim_grid_pos_y: 1190311.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737825.12
      sim_grid_pos_y: 1190123.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737831.75
      sim_grid_pos_y: 1189808.75
    }
  }
}
terrain_level_data {
  terrain_level: 46
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1743306
      sim_grid_pos_y: 1185983.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1742823
      sim_grid_pos_y: 1185585
    }
    terrain_level_point {
      sim_grid_pos_x: 1740697
      sim_grid_pos_y: 1188402.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1740166.75
      sim_grid_pos_y: 1188678.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1739543.5
      sim_grid_pos_y: 1189319.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738831.88
      sim_grid_pos_y: 1188224.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738185.88
      sim_grid_pos_y: 1188230.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738045.5
      sim_grid_pos_y: 1188523.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738142.5
      sim_grid_pos_y: 1188634.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73773e+06
      sim_grid_pos_y: 1190311.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737100.25
      sim_grid_pos_y: 1190452.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1736634.62
      sim_grid_pos_y: 1190271.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735876.38
      sim_grid_pos_y: 1190773.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735394.62
      sim_grid_pos_y: 1191071.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734859.5
      sim_grid_pos_y: 1190823
    }
    terrain_level_point {
      sim_grid_pos_x: 1734629.38
      sim_grid_pos_y: 1191234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735518.5
      sim_grid_pos_y: 1191543.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1736899.25
      sim_grid_pos_y: 1193769.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73895e+06
      sim_grid_pos_y: 1195644.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.74153e+06
      sim_grid_pos_y: 1191376.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1742954
      sim_grid_pos_y: 1188358.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1742805.62
      sim_grid_pos_y: 1185437.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1740629.12
      sim_grid_pos_y: 1188322.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1740104.75
      sim_grid_pos_y: 1188595.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1739559.5
      sim_grid_pos_y: 1189156.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738887.25
      sim_grid_pos_y: 1188121.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738121
      sim_grid_pos_y: 1188128.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737923.88
      sim_grid_pos_y: 1188539.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738030.25
      sim_grid_pos_y: 1188662
    }
    terrain_level_point {
      sim_grid_pos_x: 1737645.62
      sim_grid_pos_y: 1190225.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737108.25
      sim_grid_pos_y: 1190345.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1736622.25
      sim_grid_pos_y: 1190157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735821.25
      sim_grid_pos_y: 1190686.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735387.75
      sim_grid_pos_y: 1190955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1734816.38
      sim_grid_pos_y: 1190689.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734480.25
      sim_grid_pos_y: 1191291.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1735450.5
      sim_grid_pos_y: 1191628.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1736819.62
      sim_grid_pos_y: 1193836
    }
    terrain_level_point {
      sim_grid_pos_x: 1738973.12
      sim_grid_pos_y: 1195804.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1741620.5
      sim_grid_pos_y: 1191425.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1743053.25
      sim_grid_pos_y: 1188388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1743415.88
      sim_grid_pos_y: 1185941.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1742788.25
      sim_grid_pos_y: 1185290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1740561.25
      sim_grid_pos_y: 1188242.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1740042.75
      sim_grid_pos_y: 1188512
    }
    terrain_level_point {
      sim_grid_pos_x: 1739575.5
      sim_grid_pos_y: 1188992.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738942.5
      sim_grid_pos_y: 1188018.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738056.25
      sim_grid_pos_y: 1188026.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1737802.38
      sim_grid_pos_y: 1188556.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1737918
      sim_grid_pos_y: 1188689.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1737561.25
      sim_grid_pos_y: 1190139.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1737116.25
      sim_grid_pos_y: 1190239
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73661e+06
      sim_grid_pos_y: 1190042.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735765.75
      sim_grid_pos_y: 1190600.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1735380.75
      sim_grid_pos_y: 1190839
    }
    terrain_level_point {
      sim_grid_pos_x: 1734773.25
      sim_grid_pos_y: 1190556.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734331
      sim_grid_pos_y: 1191348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735382.5
      sim_grid_pos_y: 1191713.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73674e+06
      sim_grid_pos_y: 1193902.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738996.12
      sim_grid_pos_y: 1195964.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1741711
      sim_grid_pos_y: 1191473.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1743152.38
      sim_grid_pos_y: 1188418.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1743525.88
      sim_grid_pos_y: 1185898.88
    }
  }
}
