terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1097071.62
      sim_grid_pos_y: 1590563.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1096381.75
      sim_grid_pos_y: 1590583
    }
    terrain_level_point {
      sim_grid_pos_x: 1095696.25
      sim_grid_pos_y: 1590578
    }
    terrain_level_point {
      sim_grid_pos_x: 1094881.25
      sim_grid_pos_y: 1590565.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1094268
      sim_grid_pos_y: 1590462.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1093530.5
      sim_grid_pos_y: 1590256.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1092356.88
      sim_grid_pos_y: 1590001.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091820.62
      sim_grid_pos_y: 1589817.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1091290.38
      sim_grid_pos_y: 1589411.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1091069.25
      sim_grid_pos_y: 1589191
    }
    terrain_level_point {
      sim_grid_pos_x: 1090424.12
      sim_grid_pos_y: 1589197.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1090039.12
      sim_grid_pos_y: 1588988.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1089668.38
      sim_grid_pos_y: 1588911.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1089693.88
      sim_grid_pos_y: 1588583.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1090969.5
      sim_grid_pos_y: 1588683.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1091389
      sim_grid_pos_y: 1588677.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1091471.5
      sim_grid_pos_y: 1588637.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091494.38
      sim_grid_pos_y: 1588244.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091610.25
      sim_grid_pos_y: 1588162.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1092021.88
      sim_grid_pos_y: 1588179.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1092287.38
      sim_grid_pos_y: 1588046.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1092535.5
      sim_grid_pos_y: 1588051.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1095409.12
      sim_grid_pos_y: 1587640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1095917.88
      sim_grid_pos_y: 1588257.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1096622.75
      sim_grid_pos_y: 1588247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1096613.38
      sim_grid_pos_y: 1587832.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.09693e+06
      sim_grid_pos_y: 1587449.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1097075.25
      sim_grid_pos_y: 1587488.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1097264
      sim_grid_pos_y: 1587291.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1097541.38
      sim_grid_pos_y: 1587371.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098724.25
      sim_grid_pos_y: 1.58763e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1099034.12
      sim_grid_pos_y: 1587789.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1099064.12
      sim_grid_pos_y: 1588725.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098386
      sim_grid_pos_y: 1588748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098418.75
      sim_grid_pos_y: 1589004.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1098425.75
      sim_grid_pos_y: 1589630.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1098476
      sim_grid_pos_y: 1589629.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1098610.62
      sim_grid_pos_y: 1589914.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1098514.25
      sim_grid_pos_y: 1589957.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1097980.62
      sim_grid_pos_y: 1590291.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1097704.25
      sim_grid_pos_y: 1590442
    }
    terrain_level_point {
      sim_grid_pos_x: 1097429
      sim_grid_pos_y: 1590545
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1097571.62
      sim_grid_pos_y: 1587252.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098766.25
      sim_grid_pos_y: 1587513.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1099154.75
      sim_grid_pos_y: 1587713.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1099191
      sim_grid_pos_y: 1588844.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1098525.25
      sim_grid_pos_y: 1588867
    }
    terrain_level_point {
      sim_grid_pos_x: 1098541.75
      sim_grid_pos_y: 1588995.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098547.38
      sim_grid_pos_y: 1589505
    }
    terrain_level_point {
      sim_grid_pos_x: 1098553.25
      sim_grid_pos_y: 1589504.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098775.25
      sim_grid_pos_y: 1589974.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1098572.5
      sim_grid_pos_y: 1590066.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098042.75
      sim_grid_pos_y: 1590397.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1097755.5
      sim_grid_pos_y: 1590554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1097454.25
      sim_grid_pos_y: 1590666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1097076.5
      sim_grid_pos_y: 1590686.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1096383
      sim_grid_pos_y: 1590706
    }
    terrain_level_point {
      sim_grid_pos_x: 1095694.88
      sim_grid_pos_y: 1590701
    }
    terrain_level_point {
      sim_grid_pos_x: 1094870.12
      sim_grid_pos_y: 1590688.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1094241.25
      sim_grid_pos_y: 1590583.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1093500.88
      sim_grid_pos_y: 1590375.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1092323.75
      sim_grid_pos_y: 1590119.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1091761.75
      sim_grid_pos_y: 1589927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1091209.12
      sim_grid_pos_y: 1589504.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1091018.88
      sim_grid_pos_y: 1589314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1090393.5
      sim_grid_pos_y: 1589321.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1089996.38
      sim_grid_pos_y: 1589105.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1089537.38
      sim_grid_pos_y: 1589009.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1089580.75
      sim_grid_pos_y: 1588451.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1090973.5
      sim_grid_pos_y: 1588560.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1091353
      sim_grid_pos_y: 1588555
    }
    terrain_level_point {
      sim_grid_pos_x: 1091375
      sim_grid_pos_y: 1588177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1091573.5
      sim_grid_pos_y: 1588037.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1091995.12
      sim_grid_pos_y: 1588055.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1092259.5
      sim_grid_pos_y: 1587922.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1092528.12
      sim_grid_pos_y: 1587928.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1095460.12
      sim_grid_pos_y: 1587509.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1095975.12
      sim_grid_pos_y: 1588133.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1096497
      sim_grid_pos_y: 1588126.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1096489.38
      sim_grid_pos_y: 1587789.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1096885.5
      sim_grid_pos_y: 1.58731e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1097036.88
      sim_grid_pos_y: 1587350.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1097226.75
      sim_grid_pos_y: 1587152.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1097601.75
      sim_grid_pos_y: 1587133.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1098808.12
      sim_grid_pos_y: 1587396.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1099275.38
      sim_grid_pos_y: 1587636.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1099317.88
      sim_grid_pos_y: 1588963.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1098664.38
      sim_grid_pos_y: 1588985.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1098664.62
      sim_grid_pos_y: 1588987.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.09867e+06
      sim_grid_pos_y: 1589463.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.09894e+06
      sim_grid_pos_y: 1590035.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1098630.75
      sim_grid_pos_y: 1590175.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1098104.88
      sim_grid_pos_y: 1590503.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1097806.75
      sim_grid_pos_y: 1590666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1097479.62
      sim_grid_pos_y: 1590788.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1097081.5
      sim_grid_pos_y: 1590809.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1096384.38
      sim_grid_pos_y: 1590829.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1095693.38
      sim_grid_pos_y: 1590824
    }
    terrain_level_point {
      sim_grid_pos_x: 1094859
      sim_grid_pos_y: 1590811
    }
    terrain_level_point {
      sim_grid_pos_x: 1094214.38
      sim_grid_pos_y: 1590703.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1093471
      sim_grid_pos_y: 1590495
    }
    terrain_level_point {
      sim_grid_pos_x: 1092290.62
      sim_grid_pos_y: 1590238.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1091703
      sim_grid_pos_y: 1590037.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091128
      sim_grid_pos_y: 1589597.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1090968.5
      sim_grid_pos_y: 1589438.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1090362.75
      sim_grid_pos_y: 1589444.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1089953.5
      sim_grid_pos_y: 1589222.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1089406.25
      sim_grid_pos_y: 1589108.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1089467.62
      sim_grid_pos_y: 1588319
    }
    terrain_level_point {
      sim_grid_pos_x: 1090977.38
      sim_grid_pos_y: 1588437.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091236.88
      sim_grid_pos_y: 1588433.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1091255.62
      sim_grid_pos_y: 1588111.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1091536.88
      sim_grid_pos_y: 1587913
    }
    terrain_level_point {
      sim_grid_pos_x: 1091968.38
      sim_grid_pos_y: 1587931.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1092231.75
      sim_grid_pos_y: 1587798.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1092520.88
      sim_grid_pos_y: 1587805.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1095511.12
      sim_grid_pos_y: 1587377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1096032.5
      sim_grid_pos_y: 1.58801e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1096371.12
      sim_grid_pos_y: 1588004.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1096365.25
      sim_grid_pos_y: 1587746.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1096841
      sim_grid_pos_y: 1587170.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1096998.5
      sim_grid_pos_y: 1587213
    }
    terrain_level_point {
      sim_grid_pos_x: 1097189.5
      sim_grid_pos_y: 1587014.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1097632
      sim_grid_pos_y: 1587013.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098850.12
      sim_grid_pos_y: 1587279.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1099396.12
      sim_grid_pos_y: 1587560.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1099444.88
      sim_grid_pos_y: 1589082.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098789
      sim_grid_pos_y: 1589104.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1098792.62
      sim_grid_pos_y: 1589435.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1099104.62
      sim_grid_pos_y: 1590095.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1098689
      sim_grid_pos_y: 1590283.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098167
      sim_grid_pos_y: 1590610.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1097858
      sim_grid_pos_y: 1590778.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1097504.88
      sim_grid_pos_y: 1590910.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1097086.38
      sim_grid_pos_y: 1590932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1096385.62
      sim_grid_pos_y: 1590952.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1095692
      sim_grid_pos_y: 1590947.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1094847.75
      sim_grid_pos_y: 1590933.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1094187.5
      sim_grid_pos_y: 1590823.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1093441.5
      sim_grid_pos_y: 1590614.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1092257.5
      sim_grid_pos_y: 1590357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1091644.12
      sim_grid_pos_y: 1590147.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091046.75
      sim_grid_pos_y: 1589690.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1090918.12
      sim_grid_pos_y: 1589561.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1090332.12
      sim_grid_pos_y: 1589567.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1089910.75
      sim_grid_pos_y: 1589338.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1089275.25
      sim_grid_pos_y: 1589206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1089354.5
      sim_grid_pos_y: 1588186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1090981.38
      sim_grid_pos_y: 1588314.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091120.75
      sim_grid_pos_y: 1588312.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091136.25
      sim_grid_pos_y: 1588045.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1091500.12
      sim_grid_pos_y: 1587788.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1091941.62
      sim_grid_pos_y: 1587806.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1092203.88
      sim_grid_pos_y: 1587674.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1092513.5
      sim_grid_pos_y: 1587682.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1095562.12
      sim_grid_pos_y: 1587246
    }
    terrain_level_point {
      sim_grid_pos_x: 1096089.75
      sim_grid_pos_y: 1587886
    }
    terrain_level_point {
      sim_grid_pos_x: 1096245.38
      sim_grid_pos_y: 1587883.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1096241.25
      sim_grid_pos_y: 1587703.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1096796.5
      sim_grid_pos_y: 1587031.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1096960.12
      sim_grid_pos_y: 1587075.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1097152.12
      sim_grid_pos_y: 1586875.25
    }
  }
}
