terrain_level_data {
  terrain_level: 3586
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2354292.75
      sim_grid_pos_y: 1616353.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2362686.25
      sim_grid_pos_y: 1611053
    }
    terrain_level_point {
      sim_grid_pos_x: 2364047
      sim_grid_pos_y: 1.61186e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2364920.75
      sim_grid_pos_y: 1613027.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2364363.25
      sim_grid_pos_y: 1614086.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2364582.25
      sim_grid_pos_y: 1.61444e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2363873
      sim_grid_pos_y: 1615099.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2363091.25
      sim_grid_pos_y: 1614311.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360166
      sim_grid_pos_y: 1615194.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2359461
      sim_grid_pos_y: 1615930.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355360.75
      sim_grid_pos_y: 1617022.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354462.5
      sim_grid_pos_y: 1616653.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2364082
      sim_grid_pos_y: 1611821.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2364981.25
      sim_grid_pos_y: 1613022.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364422.25
      sim_grid_pos_y: 1614084.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2364648
      sim_grid_pos_y: 1614448.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2363871.5
      sim_grid_pos_y: 1615171.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2363076.5
      sim_grid_pos_y: 1614369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360193.75
      sim_grid_pos_y: 1.61524e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2359488
      sim_grid_pos_y: 1615976.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2355357.25
      sim_grid_pos_y: 1617076.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354426.5
      sim_grid_pos_y: 1616694.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354224
      sim_grid_pos_y: 1616336
    }
    terrain_level_point {
      sim_grid_pos_x: 2362685.5
      sim_grid_pos_y: 1610992.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2364116.75
      sim_grid_pos_y: 1611782.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2365041.75
      sim_grid_pos_y: 1613018.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2364481.25
      sim_grid_pos_y: 1614082.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2364713.75
      sim_grid_pos_y: 1614457.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.36387e+06
      sim_grid_pos_y: 1615242.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2363061.75
      sim_grid_pos_y: 1614427.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360221.5
      sim_grid_pos_y: 1615285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2359515.25
      sim_grid_pos_y: 1616022.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2355353.75
      sim_grid_pos_y: 1617130.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354390.75
      sim_grid_pos_y: 1616734.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354155.5
      sim_grid_pos_y: 1616318.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2362684.5
      sim_grid_pos_y: 1610932.75
    }
  }
}
