terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 437804.75
      sim_grid_pos_y: 2092803.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437819.406
      sim_grid_pos_y: 2093243.38
    }
    terrain_level_point {
      sim_grid_pos_x: 437876.188
      sim_grid_pos_y: 2093387.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437710.781
      sim_grid_pos_y: 2093552.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437684.812
      sim_grid_pos_y: 2093728
    }
    terrain_level_point {
      sim_grid_pos_x: 437860.125
      sim_grid_pos_y: 2093770.12
    }
    terrain_level_point {
      sim_grid_pos_x: 438051.938
      sim_grid_pos_y: 2093639.5
    }
    terrain_level_point {
      sim_grid_pos_x: 438180.75
      sim_grid_pos_y: 2093539.38
    }
    terrain_level_point {
      sim_grid_pos_x: 438517.594
      sim_grid_pos_y: 2093549.5
    }
    terrain_level_point {
      sim_grid_pos_x: 438812.156
      sim_grid_pos_y: 2093463.25
    }
    terrain_level_point {
      sim_grid_pos_x: 439564.688
      sim_grid_pos_y: 2093769
    }
    terrain_level_point {
      sim_grid_pos_x: 439867.844
      sim_grid_pos_y: 2093971.38
    }
    terrain_level_point {
      sim_grid_pos_x: 440558.844
      sim_grid_pos_y: 2094240.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440854.875
      sim_grid_pos_y: 2094051.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439415.719
      sim_grid_pos_y: 2093350.5
    }
    terrain_level_point {
      sim_grid_pos_x: 439423.844
      sim_grid_pos_y: 2093122.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438740.5
      sim_grid_pos_y: 2093121.75
    }
    terrain_level_point {
      sim_grid_pos_x: 438362.156
      sim_grid_pos_y: 2092770.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 438373.469
      sim_grid_pos_y: 2092739
    }
    terrain_level_point {
      sim_grid_pos_x: 437773
      sim_grid_pos_y: 2092774.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437788.844
      sim_grid_pos_y: 2093249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 437840.156
      sim_grid_pos_y: 2093379.62
    }
    terrain_level_point {
      sim_grid_pos_x: 437681.844
      sim_grid_pos_y: 2093537.62
    }
    terrain_level_point {
      sim_grid_pos_x: 437650.25
      sim_grid_pos_y: 2093751.38
    }
    terrain_level_point {
      sim_grid_pos_x: 437866.188
      sim_grid_pos_y: 2093803.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438070.031
      sim_grid_pos_y: 2093664.38
    }
    terrain_level_point {
      sim_grid_pos_x: 438190.875
      sim_grid_pos_y: 2093570.38
    }
    terrain_level_point {
      sim_grid_pos_x: 438521.562
      sim_grid_pos_y: 2093580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 438810.5
      sim_grid_pos_y: 2093495.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439550.25
      sim_grid_pos_y: 2093796.38
    }
    terrain_level_point {
      sim_grid_pos_x: 439853.562
      sim_grid_pos_y: 2093998.88
    }
    terrain_level_point {
      sim_grid_pos_x: 440562.219
      sim_grid_pos_y: 2094274.88
    }
    terrain_level_point {
      sim_grid_pos_x: 440886.594
      sim_grid_pos_y: 2094067.75
    }
    terrain_level_point {
      sim_grid_pos_x: 440884.531
      sim_grid_pos_y: 2094031.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439447.188
      sim_grid_pos_y: 2093331.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439455.719
      sim_grid_pos_y: 2093091.62
    }
    terrain_level_point {
      sim_grid_pos_x: 438752.594
      sim_grid_pos_y: 2093091
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 438384.75
      sim_grid_pos_y: 2092707.5
    }
    terrain_level_point {
      sim_grid_pos_x: 437741.281
      sim_grid_pos_y: 2092745.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437758.25
      sim_grid_pos_y: 2093256
    }
    terrain_level_point {
      sim_grid_pos_x: 437804.125
      sim_grid_pos_y: 2093372.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437652.906
      sim_grid_pos_y: 2093523.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437615.719
      sim_grid_pos_y: 2093774.62
    }
    terrain_level_point {
      sim_grid_pos_x: 437872.25
      sim_grid_pos_y: 2093836.38
    }
    terrain_level_point {
      sim_grid_pos_x: 438088.156
      sim_grid_pos_y: 2093689.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438201
      sim_grid_pos_y: 2093601.5
    }
    terrain_level_point {
      sim_grid_pos_x: 438525.5
      sim_grid_pos_y: 2093611.38
    }
    terrain_level_point {
      sim_grid_pos_x: 438808.875
      sim_grid_pos_y: 2093528.25
    }
    terrain_level_point {
      sim_grid_pos_x: 439535.75
      sim_grid_pos_y: 2093823.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439839.281
      sim_grid_pos_y: 2094026.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440565.594
      sim_grid_pos_y: 2094309.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440918.344
      sim_grid_pos_y: 2094084
    }
    terrain_level_point {
      sim_grid_pos_x: 440914.219
      sim_grid_pos_y: 2094012
    }
    terrain_level_point {
      sim_grid_pos_x: 439478.625
      sim_grid_pos_y: 2093312.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439487.594
      sim_grid_pos_y: 2093060.88
    }
    terrain_level_point {
      sim_grid_pos_x: 438764.688
      sim_grid_pos_y: 2093060.25
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 448254.844
      sim_grid_pos_y: 2094743.62
    }
    terrain_level_point {
      sim_grid_pos_x: 448338.531
      sim_grid_pos_y: 2094744.38
    }
    terrain_level_point {
      sim_grid_pos_x: 448980.281
      sim_grid_pos_y: 2094735.62
    }
    terrain_level_point {
      sim_grid_pos_x: 449322.531
      sim_grid_pos_y: 2094589.38
    }
    terrain_level_point {
      sim_grid_pos_x: 449411.219
      sim_grid_pos_y: 2094678
    }
    terrain_level_point {
      sim_grid_pos_x: 449257.094
      sim_grid_pos_y: 2095011.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449193.25
      sim_grid_pos_y: 2095219.38
    }
    terrain_level_point {
      sim_grid_pos_x: 448963.938
      sim_grid_pos_y: 2095477.38
    }
    terrain_level_point {
      sim_grid_pos_x: 448709.875
      sim_grid_pos_y: 2095246.62
    }
    terrain_level_point {
      sim_grid_pos_x: 448623.031
      sim_grid_pos_y: 2095185.75
    }
    terrain_level_point {
      sim_grid_pos_x: 448274.844
      sim_grid_pos_y: 2095186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 448272.75
      sim_grid_pos_y: 2094816.38
    }
  }
}
terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 443632.094
      sim_grid_pos_y: 2094580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 442595.406
      sim_grid_pos_y: 2094536.75
    }
    terrain_level_point {
      sim_grid_pos_x: 441337.156
      sim_grid_pos_y: 2094434.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441296.406
      sim_grid_pos_y: 2089673.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444797.375
      sim_grid_pos_y: 2088132.38
    }
    terrain_level_point {
      sim_grid_pos_x: 444889.656
      sim_grid_pos_y: 2088154.12
    }
    terrain_level_point {
      sim_grid_pos_x: 445398.312
      sim_grid_pos_y: 2089623.62
    }
    terrain_level_point {
      sim_grid_pos_x: 445390.906
      sim_grid_pos_y: 2089840.88
    }
    terrain_level_point {
      sim_grid_pos_x: 444868.281
      sim_grid_pos_y: 2090757.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444733
      sim_grid_pos_y: 2091611.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 444913.188
      sim_grid_pos_y: 2088128.12
    }
    terrain_level_point {
      sim_grid_pos_x: 445429.25
      sim_grid_pos_y: 2089619
    }
    terrain_level_point {
      sim_grid_pos_x: 445421.375
      sim_grid_pos_y: 2089849.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444897.781
      sim_grid_pos_y: 2090768.12
    }
    terrain_level_point {
      sim_grid_pos_x: 444762.875
      sim_grid_pos_y: 2091619
    }
    terrain_level_point {
      sim_grid_pos_x: 443653.156
      sim_grid_pos_y: 2094612.12
    }
    terrain_level_point {
      sim_grid_pos_x: 442593.5
      sim_grid_pos_y: 2094567.38
    }
    terrain_level_point {
      sim_grid_pos_x: 441306.625
      sim_grid_pos_y: 2094463.25
    }
    terrain_level_point {
      sim_grid_pos_x: 441265.469
      sim_grid_pos_y: 2089653.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444794.406
      sim_grid_pos_y: 2088100.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 444936.719
      sim_grid_pos_y: 2088102
    }
    terrain_level_point {
      sim_grid_pos_x: 445460.188
      sim_grid_pos_y: 2089614.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445451.844
      sim_grid_pos_y: 2089858.12
    }
    terrain_level_point {
      sim_grid_pos_x: 444927.281
      sim_grid_pos_y: 2090778.38
    }
    terrain_level_point {
      sim_grid_pos_x: 444792.781
      sim_grid_pos_y: 2091626.88
    }
    terrain_level_point {
      sim_grid_pos_x: 443674.219
      sim_grid_pos_y: 2094643.88
    }
    terrain_level_point {
      sim_grid_pos_x: 442591.625
      sim_grid_pos_y: 2094598.12
    }
    terrain_level_point {
      sim_grid_pos_x: 441276.125
      sim_grid_pos_y: 2094491.62
    }
    terrain_level_point {
      sim_grid_pos_x: 441234.531
      sim_grid_pos_y: 2089633.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444791.438
      sim_grid_pos_y: 2088067.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 444960.25
      sim_grid_pos_y: 2088076
    }
    terrain_level_point {
      sim_grid_pos_x: 445491.094
      sim_grid_pos_y: 2089609.62
    }
    terrain_level_point {
      sim_grid_pos_x: 445482.344
      sim_grid_pos_y: 2089866.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444956.781
      sim_grid_pos_y: 2090788.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444822.688
      sim_grid_pos_y: 2091634.75
    }
    terrain_level_point {
      sim_grid_pos_x: 443695.25
      sim_grid_pos_y: 2094675.5
    }
    terrain_level_point {
      sim_grid_pos_x: 442589.719
      sim_grid_pos_y: 2094628.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441245.594
      sim_grid_pos_y: 2.09452e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 441203.625
      sim_grid_pos_y: 2089613.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444788.438
      sim_grid_pos_y: 2088035.5
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 453144.656
      sim_grid_pos_y: 2096662.88
    }
    terrain_level_point {
      sim_grid_pos_x: 452964.375
      sim_grid_pos_y: 2096984.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452782.781
      sim_grid_pos_y: 2097363.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452463.781
      sim_grid_pos_y: 2098149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451885.031
      sim_grid_pos_y: 2100006.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452549.125
      sim_grid_pos_y: 2099521
    }
    terrain_level_point {
      sim_grid_pos_x: 452592.5
      sim_grid_pos_y: 2099299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452708.375
      sim_grid_pos_y: 2098776.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452921.969
      sim_grid_pos_y: 2098026
    }
    terrain_level_point {
      sim_grid_pos_x: 453149.938
      sim_grid_pos_y: 2097371.75
    }
    terrain_level_point {
      sim_grid_pos_x: 453286.469
      sim_grid_pos_y: 2096999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 453609.094
      sim_grid_pos_y: 2096944.75
    }
    terrain_level_point {
      sim_grid_pos_x: 453287.906
      sim_grid_pos_y: 2096566
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 453289.781
      sim_grid_pos_y: 2096552.38
    }
    terrain_level_point {
      sim_grid_pos_x: 453136.906
      sim_grid_pos_y: 2096655.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452955.281
      sim_grid_pos_y: 2096979.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452773.406
      sim_grid_pos_y: 2097359
    }
    terrain_level_point {
      sim_grid_pos_x: 452454.125
      sim_grid_pos_y: 2098146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 451873.031
      sim_grid_pos_y: 2100010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451885.094
      sim_grid_pos_y: 2100019
    }
    terrain_level_point {
      sim_grid_pos_x: 452558.438
      sim_grid_pos_y: 2099527
    }
    terrain_level_point {
      sim_grid_pos_x: 452602.5
      sim_grid_pos_y: 2099302
    }
    terrain_level_point {
      sim_grid_pos_x: 452718.312
      sim_grid_pos_y: 2098778.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452931.75
      sim_grid_pos_y: 2098029
    }
    terrain_level_point {
      sim_grid_pos_x: 453159.562
      sim_grid_pos_y: 2097375.5
    }
    terrain_level_point {
      sim_grid_pos_x: 453159.562
      sim_grid_pos_y: 2097375.5
    }
    terrain_level_point {
      sim_grid_pos_x: 453294.031
      sim_grid_pos_y: 2097008.38
    }
    terrain_level_point {
      sim_grid_pos_x: 453616.688
      sim_grid_pos_y: 2096953.88
    }
    terrain_level_point {
      sim_grid_pos_x: 453620.781
      sim_grid_pos_y: 2096942.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 453291.656
      sim_grid_pos_y: 2096538.75
    }
    terrain_level_point {
      sim_grid_pos_x: 453129.156
      sim_grid_pos_y: 2096648.62
    }
    terrain_level_point {
      sim_grid_pos_x: 452946.156
      sim_grid_pos_y: 2096974.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452764
      sim_grid_pos_y: 2097355
    }
    terrain_level_point {
      sim_grid_pos_x: 452444.469
      sim_grid_pos_y: 2098142.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451861.031
      sim_grid_pos_y: 2100014.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451885.156
      sim_grid_pos_y: 2100031.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452567.719
      sim_grid_pos_y: 2099532.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452612.5
      sim_grid_pos_y: 2099304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452728.25
      sim_grid_pos_y: 2098781.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452941.5
      sim_grid_pos_y: 2098032
    }
    terrain_level_point {
      sim_grid_pos_x: 453169.312
      sim_grid_pos_y: 2097378.5
    }
    terrain_level_point {
      sim_grid_pos_x: 453169.281
      sim_grid_pos_y: 2097378.5
    }
    terrain_level_point {
      sim_grid_pos_x: 453301.594
      sim_grid_pos_y: 2097017.5
    }
    terrain_level_point {
      sim_grid_pos_x: 453624.25
      sim_grid_pos_y: 2096963
    }
    terrain_level_point {
      sim_grid_pos_x: 453632.438
      sim_grid_pos_y: 2096940.62
    }
  }
}
