terrain_level_data {
  terrain_level: 4242
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2315832.25
      sim_grid_pos_y: 1618397.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2315916
      sim_grid_pos_y: 1618610.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2316255.5
      sim_grid_pos_y: 1618637
    }
    terrain_level_point {
      sim_grid_pos_x: 2316489.75
      sim_grid_pos_y: 1618588.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2316581.75
      sim_grid_pos_y: 1618430.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2316526.25
      sim_grid_pos_y: 1618314
    }
    terrain_level_point {
      sim_grid_pos_x: 2316415.5
      sim_grid_pos_y: 1618146.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2316242
      sim_grid_pos_y: 1618051.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2315951.5
      sim_grid_pos_y: 1618174.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2316245
      sim_grid_pos_y: 1617994.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2315914.75
      sim_grid_pos_y: 1618134.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315776
      sim_grid_pos_y: 1618393.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.31588e+06
      sim_grid_pos_y: 1618659.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2316258.75
      sim_grid_pos_y: 1618688.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316522.75
      sim_grid_pos_y: 1618634.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2316639.75
      sim_grid_pos_y: 1618432.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316570.75
      sim_grid_pos_y: 1618288.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316451.25
      sim_grid_pos_y: 1618108
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2316247.75
      sim_grid_pos_y: 1617937.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2315878.25
      sim_grid_pos_y: 1618094.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2315719.75
      sim_grid_pos_y: 1618390.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2315844
      sim_grid_pos_y: 1618708.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2316262
      sim_grid_pos_y: 1618740.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2316555.5
      sim_grid_pos_y: 1618679.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316697.5
      sim_grid_pos_y: 1618434.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2316615.5
      sim_grid_pos_y: 1618263.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2316487
      sim_grid_pos_y: 1618069.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2316250.75
      sim_grid_pos_y: 1617880.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315841.5
      sim_grid_pos_y: 1618054.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2315663.25
      sim_grid_pos_y: 1618387
    }
    terrain_level_point {
      sim_grid_pos_x: 2315808
      sim_grid_pos_y: 1618756.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2316265.25
      sim_grid_pos_y: 1618792
    }
    terrain_level_point {
      sim_grid_pos_x: 2316588.25
      sim_grid_pos_y: 1618725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2316755.5
      sim_grid_pos_y: 1618437.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2316660.25
      sim_grid_pos_y: 1618237.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2316522.75
      sim_grid_pos_y: 1618030.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2316253.5
      sim_grid_pos_y: 1617823.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315804.75
      sim_grid_pos_y: 1618014.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2315607
      sim_grid_pos_y: 1618383.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315772
      sim_grid_pos_y: 1618805.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2316268.5
      sim_grid_pos_y: 1618843.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316621.25
      sim_grid_pos_y: 1618770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2316813.5
      sim_grid_pos_y: 1618439.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2316705
      sim_grid_pos_y: 1618212.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316558.5
      sim_grid_pos_y: 1617991.5
    }
  }
}
terrain_level_data {
  terrain_level: 4268
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2315188.5
      sim_grid_pos_y: 1618306
    }
    terrain_level_point {
      sim_grid_pos_x: 2315283.5
      sim_grid_pos_y: 1618482.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2315366.5
      sim_grid_pos_y: 1618438.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315262
      sim_grid_pos_y: 1618287.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2315279.5
      sim_grid_pos_y: 1618241.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2315127.5
      sim_grid_pos_y: 1618279
    }
    terrain_level_point {
      sim_grid_pos_x: 2315266.75
      sim_grid_pos_y: 1618538.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2315426.5
      sim_grid_pos_y: 1618453.12
    }
  }
}
terrain_level_data {
  terrain_level: 4086
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2315518.5
      sim_grid_pos_y: 1619090.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315871
      sim_grid_pos_y: 1619090.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315879.25
      sim_grid_pos_y: 1619313.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2315519.25
      sim_grid_pos_y: 1619313.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2315920.5
      sim_grid_pos_y: 1619039.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2315932.5
      sim_grid_pos_y: 1619364.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2315468
      sim_grid_pos_y: 1619364.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2315467
      sim_grid_pos_y: 1619039.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2315969.75
      sim_grid_pos_y: 1618988.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2315985.75
      sim_grid_pos_y: 1619416
    }
    terrain_level_point {
      sim_grid_pos_x: 2315417
      sim_grid_pos_y: 1619415.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2315415.5
      sim_grid_pos_y: 1618988.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2316019.25
      sim_grid_pos_y: 1618936.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2316039
      sim_grid_pos_y: 1619467.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2315365.75
      sim_grid_pos_y: 1619467.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2315364.25
      sim_grid_pos_y: 1618936.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2316068.75
      sim_grid_pos_y: 1618885.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2316092.25
      sim_grid_pos_y: 1619518.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2315314.75
      sim_grid_pos_y: 1619518.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2315312.75
      sim_grid_pos_y: 1618885.62
    }
  }
}
terrain_level_data {
  terrain_level: 3877
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2319680.5
      sim_grid_pos_y: 1617485.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2319602
      sim_grid_pos_y: 1617630.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2319622.5
      sim_grid_pos_y: 1617692.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2319533
      sim_grid_pos_y: 1617862
    }
    terrain_level_point {
      sim_grid_pos_x: 2319832.25
      sim_grid_pos_y: 1618099.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2319968.5
      sim_grid_pos_y: 1618052.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2319974
      sim_grid_pos_y: 1617865.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2319871.5
      sim_grid_pos_y: 1617600.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2319661
      sim_grid_pos_y: 1617414.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2319546.5
      sim_grid_pos_y: 1617625.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2319567
      sim_grid_pos_y: 1617687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2319468
      sim_grid_pos_y: 1617875.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2319822.5
      sim_grid_pos_y: 1618156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2320018.75
      sim_grid_pos_y: 1618089.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2320025.5
      sim_grid_pos_y: 1617856.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2319913
      sim_grid_pos_y: 1617566
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2319641.5
      sim_grid_pos_y: 1617342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2319490.75
      sim_grid_pos_y: 1617620.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2319511.5
      sim_grid_pos_y: 1617683
    }
    terrain_level_point {
      sim_grid_pos_x: 2319402.75
      sim_grid_pos_y: 1617889.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2319812.5
      sim_grid_pos_y: 1618214.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2320069
      sim_grid_pos_y: 1618126.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2320077
      sim_grid_pos_y: 1617847.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2319954.5
      sim_grid_pos_y: 1617531.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2319622
      sim_grid_pos_y: 1617271.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2319435.25
      sim_grid_pos_y: 1617615.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2319456
      sim_grid_pos_y: 1617678.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2319337.5
      sim_grid_pos_y: 1617903.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2319802.5
      sim_grid_pos_y: 1618271.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2320119.25
      sim_grid_pos_y: 1618163.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2320128.5
      sim_grid_pos_y: 1617838.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2319996
      sim_grid_pos_y: 1617496.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2319602.25
      sim_grid_pos_y: 1617199.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2319379.5
      sim_grid_pos_y: 1617610.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2319400.5
      sim_grid_pos_y: 1617673.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2319272.5
      sim_grid_pos_y: 1617917
    }
    terrain_level_point {
      sim_grid_pos_x: 2319792.75
      sim_grid_pos_y: 1618329.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2320169.25
      sim_grid_pos_y: 1618200.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.32018e+06
      sim_grid_pos_y: 1617829.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2320037.5
      sim_grid_pos_y: 1617461.38
    }
  }
}
