terrain_level_data {
  terrain_level: 255
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1206082.62
      sim_grid_pos_y: 1674479.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1206081.25
      sim_grid_pos_y: 1673524.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206039.62
      sim_grid_pos_y: 1672476.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1205852.38
      sim_grid_pos_y: 1672251.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1205867.88
      sim_grid_pos_y: 1672167
    }
    terrain_level_point {
      sim_grid_pos_x: 1206093
      sim_grid_pos_y: 1672124.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206107.88
      sim_grid_pos_y: 1.67155e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1206057.12
      sim_grid_pos_y: 1671531.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206013.38
      sim_grid_pos_y: 1671346.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206027
      sim_grid_pos_y: 1671047
    }
    terrain_level_point {
      sim_grid_pos_x: 1206081.88
      sim_grid_pos_y: 1670912.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206045.25
      sim_grid_pos_y: 1669174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206081.5
      sim_grid_pos_y: 1669054.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1206449.5
      sim_grid_pos_y: 1668842.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206827.12
      sim_grid_pos_y: 1668142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206867.12
      sim_grid_pos_y: 1667959.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1206928.38
      sim_grid_pos_y: 1667833.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207008
      sim_grid_pos_y: 1667713.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207439.88
      sim_grid_pos_y: 1667445.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207573.38
      sim_grid_pos_y: 1667481.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207706.5
      sim_grid_pos_y: 1667604
    }
    terrain_level_point {
      sim_grid_pos_x: 1207819.62
      sim_grid_pos_y: 1668081.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207852.25
      sim_grid_pos_y: 1668363.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207673.25
      sim_grid_pos_y: 1668458.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207627.25
      sim_grid_pos_y: 1668785
    }
    terrain_level_point {
      sim_grid_pos_x: 1207261.88
      sim_grid_pos_y: 1668769.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207255.38
      sim_grid_pos_y: 1669097.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207507.88
      sim_grid_pos_y: 1669137
    }
    terrain_level_point {
      sim_grid_pos_x: 1207509.5
      sim_grid_pos_y: 1669585.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207907.12
      sim_grid_pos_y: 1669594.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1208134.62
      sim_grid_pos_y: 1669342.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208276.38
      sim_grid_pos_y: 1669289.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208844.25
      sim_grid_pos_y: 1669294.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209112
      sim_grid_pos_y: 1669367.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.20937e+06
      sim_grid_pos_y: 1669557.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209276
      sim_grid_pos_y: 1669636.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209277.25
      sim_grid_pos_y: 1669895.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209240.38
      sim_grid_pos_y: 1670020.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.20912e+06
      sim_grid_pos_y: 1670134.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209126.25
      sim_grid_pos_y: 1670194.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209326.75
      sim_grid_pos_y: 1670243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209297.12
      sim_grid_pos_y: 1670444.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209156.12
      sim_grid_pos_y: 1670412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209147
      sim_grid_pos_y: 1670349.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208866.75
      sim_grid_pos_y: 1670324.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208873.75
      sim_grid_pos_y: 1670368
    }
    terrain_level_point {
      sim_grid_pos_x: 1209083
      sim_grid_pos_y: 1670418.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1209322.75
      sim_grid_pos_y: 1670692.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209098.25
      sim_grid_pos_y: 1670896.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1208329.12
      sim_grid_pos_y: 1670870.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208235.88
      sim_grid_pos_y: 1671065.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207521
      sim_grid_pos_y: 1671318.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207420.62
      sim_grid_pos_y: 1671194.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207263.5
      sim_grid_pos_y: 1671185.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207265
      sim_grid_pos_y: 1671525.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207249.75
      sim_grid_pos_y: 1.67238e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1208330.88
      sim_grid_pos_y: 1672365.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208294
      sim_grid_pos_y: 1672646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208259.25
      sim_grid_pos_y: 1673485.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207900.12
      sim_grid_pos_y: 1674678.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207970.75
      sim_grid_pos_y: 1675104
    }
    terrain_level_point {
      sim_grid_pos_x: 1207498.62
      sim_grid_pos_y: 1675122.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207211.62
      sim_grid_pos_y: 1675147.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207178.5
      sim_grid_pos_y: 1675249.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207017.5
      sim_grid_pos_y: 1675334.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206944.38
      sim_grid_pos_y: 1675173.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206816.5
      sim_grid_pos_y: 1674956.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206737.5
      sim_grid_pos_y: 1674790.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206577.88
      sim_grid_pos_y: 1674779.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1206353.75
      sim_grid_pos_y: 1674807.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206261.38
      sim_grid_pos_y: 1674767.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206174.12
      sim_grid_pos_y: 1674602.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1207583.5
      sim_grid_pos_y: 1667462.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207725
      sim_grid_pos_y: 1667593.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207839.88
      sim_grid_pos_y: 1668078.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207874.25
      sim_grid_pos_y: 1668375.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207692.12
      sim_grid_pos_y: 1668472
    }
    terrain_level_point {
      sim_grid_pos_x: 1207645
      sim_grid_pos_y: 1668806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207282
      sim_grid_pos_y: 1668791.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207276.25
      sim_grid_pos_y: 1.66908e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1207528.38
      sim_grid_pos_y: 1669119.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207529.88
      sim_grid_pos_y: 1669565.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207898.25
      sim_grid_pos_y: 1669573.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208122.75
      sim_grid_pos_y: 1669325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208272.75
      sim_grid_pos_y: 1669268.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208847.12
      sim_grid_pos_y: 1669274.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209121.12
      sim_grid_pos_y: 1669348.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209403.12
      sim_grid_pos_y: 1669556.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209296.5
      sim_grid_pos_y: 1669646.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209297.75
      sim_grid_pos_y: 1669898.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209258.5
      sim_grid_pos_y: 1670032
    }
    terrain_level_point {
      sim_grid_pos_x: 1209141.5
      sim_grid_pos_y: 1670142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209145.12
      sim_grid_pos_y: 1670177.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209349.75
      sim_grid_pos_y: 1670227.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209314.12
      sim_grid_pos_y: 1670469.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209137.88
      sim_grid_pos_y: 1670429.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209129
      sim_grid_pos_y: 1670368.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208891.25
      sim_grid_pos_y: 1670347.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208891.75
      sim_grid_pos_y: 1670351.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209094.12
      sim_grid_pos_y: 1670400.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209351.5
      sim_grid_pos_y: 1670694.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209105.88
      sim_grid_pos_y: 1670917.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208341.88
      sim_grid_pos_y: 1670891.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208250.75
      sim_grid_pos_y: 1671082.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207514.25
      sim_grid_pos_y: 1671342.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207410.38
      sim_grid_pos_y: 1671214.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207284.12
      sim_grid_pos_y: 1671207.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207285.5
      sim_grid_pos_y: 1671526
    }
    terrain_level_point {
      sim_grid_pos_x: 1207270.62
      sim_grid_pos_y: 1672359.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208354.25
      sim_grid_pos_y: 1672344.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208314.5
      sim_grid_pos_y: 1672648.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208279.62
      sim_grid_pos_y: 1673488.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207921.12
      sim_grid_pos_y: 1674679.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207994.75
      sim_grid_pos_y: 1675123.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.2075e+06
      sim_grid_pos_y: 1675143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207226.88
      sim_grid_pos_y: 1675167.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207195.38
      sim_grid_pos_y: 1675263.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207007.88
      sim_grid_pos_y: 1675362.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206926.12
      sim_grid_pos_y: 1675182.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206798.38
      sim_grid_pos_y: 1674966.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206724.12
      sim_grid_pos_y: 1.67481e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1206578.5
      sim_grid_pos_y: 1674799.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206350.75
      sim_grid_pos_y: 1674828.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206246.62
      sim_grid_pos_y: 1674783.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206156.75
      sim_grid_pos_y: 1674613.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206062.12
      sim_grid_pos_y: 1674485.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206060.75
      sim_grid_pos_y: 1673524.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206019.38
      sim_grid_pos_y: 1672484.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1205830.5
      sim_grid_pos_y: 1672256.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1205850.25
      sim_grid_pos_y: 1672149.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206072.88
      sim_grid_pos_y: 1672107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206087
      sim_grid_pos_y: 1671564.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206039.75
      sim_grid_pos_y: 1671547.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1205992.75
      sim_grid_pos_y: 1671348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206006.62
      sim_grid_pos_y: 1671042.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206061.25
      sim_grid_pos_y: 1670908.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206024.62
      sim_grid_pos_y: 1669171.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206064.25
      sim_grid_pos_y: 1669040.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206434.25
      sim_grid_pos_y: 1668827.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206807.75
      sim_grid_pos_y: 1668135.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206847.62
      sim_grid_pos_y: 1667952.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206910.5
      sim_grid_pos_y: 1667823.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206993.38
      sim_grid_pos_y: 1667698
    }
    terrain_level_point {
      sim_grid_pos_x: 1207436.62
      sim_grid_pos_y: 1667423.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1207593.75
      sim_grid_pos_y: 1667444.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207743.5
      sim_grid_pos_y: 1667582.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207860.12
      sim_grid_pos_y: 1668074.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207896.25
      sim_grid_pos_y: 1668386.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207711
      sim_grid_pos_y: 1668485.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207662.62
      sim_grid_pos_y: 1668827.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207302
      sim_grid_pos_y: 1668812.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207297.12
      sim_grid_pos_y: 1669062.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207548.75
      sim_grid_pos_y: 1669101.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207550.38
      sim_grid_pos_y: 1669545.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207889.25
      sim_grid_pos_y: 1669553
    }
    terrain_level_point {
      sim_grid_pos_x: 1208110.88
      sim_grid_pos_y: 1669308
    }
    terrain_level_point {
      sim_grid_pos_x: 1208269.12
      sim_grid_pos_y: 1669248.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208849.88
      sim_grid_pos_y: 1669253.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209130.12
      sim_grid_pos_y: 1.66933e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1209436.25
      sim_grid_pos_y: 1669555.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209317.12
      sim_grid_pos_y: 1669655.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209318.25
      sim_grid_pos_y: 1669901.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209276.62
      sim_grid_pos_y: 1670043.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209162.88
      sim_grid_pos_y: 1670150.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1209164
      sim_grid_pos_y: 1670161.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209372.75
      sim_grid_pos_y: 1670212.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209331.25
      sim_grid_pos_y: 1670494.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209171.88
      sim_grid_pos_y: 1670457.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209380.12
      sim_grid_pos_y: 1670696.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209113.5
      sim_grid_pos_y: 1670937.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208354.5
      sim_grid_pos_y: 1670912.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208265.5
      sim_grid_pos_y: 1671098.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207507.38
      sim_grid_pos_y: 1671366.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207400.25
      sim_grid_pos_y: 1671234.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207304.75
      sim_grid_pos_y: 1671229.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207306
      sim_grid_pos_y: 1671526.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207291.5
      sim_grid_pos_y: 1672338.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1208377.75
      sim_grid_pos_y: 1672323.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208334.88
      sim_grid_pos_y: 1.67265e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1.2083e+06
      sim_grid_pos_y: 1673492.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207942.12
      sim_grid_pos_y: 1674680.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208018.88
      sim_grid_pos_y: 1675143.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207501.12
      sim_grid_pos_y: 1675163.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207242.25
      sim_grid_pos_y: 1675186.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207212.38
      sim_grid_pos_y: 1675278
    }
    terrain_level_point {
      sim_grid_pos_x: 1206998.12
      sim_grid_pos_y: 1675391
    }
    terrain_level_point {
      sim_grid_pos_x: 1206908
      sim_grid_pos_y: 1675192.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206780.25
      sim_grid_pos_y: 1674976
    }
    terrain_level_point {
      sim_grid_pos_x: 1206710.75
      sim_grid_pos_y: 1674829.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206579
      sim_grid_pos_y: 1674820.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206347.75
      sim_grid_pos_y: 1674849.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206231.88
      sim_grid_pos_y: 1674799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206139.38
      sim_grid_pos_y: 1674624.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206041.62
      sim_grid_pos_y: 1674492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206040.25
      sim_grid_pos_y: 1673525.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1205999.25
      sim_grid_pos_y: 1672492.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1205808.62
      sim_grid_pos_y: 1672262.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1205832.62
      sim_grid_pos_y: 1672131.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206052.88
      sim_grid_pos_y: 1672090.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206066.12
      sim_grid_pos_y: 1671578.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206022.38
      sim_grid_pos_y: 1671563
    }
    terrain_level_point {
      sim_grid_pos_x: 1205972.12
      sim_grid_pos_y: 1671350.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1205986.38
      sim_grid_pos_y: 1671038
    }
    terrain_level_point {
      sim_grid_pos_x: 1206040.75
      sim_grid_pos_y: 1670904.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206004.12
      sim_grid_pos_y: 1669168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206047
      sim_grid_pos_y: 1669026.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206419
      sim_grid_pos_y: 1668813
    }
    terrain_level_point {
      sim_grid_pos_x: 1206788.25
      sim_grid_pos_y: 1668128.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206828.12
      sim_grid_pos_y: 1667945.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206892.62
      sim_grid_pos_y: 1667813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206978.75
      sim_grid_pos_y: 1667683
    }
    terrain_level_point {
      sim_grid_pos_x: 1207433.38
      sim_grid_pos_y: 1667401.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1207603.88
      sim_grid_pos_y: 1667425.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207762
      sim_grid_pos_y: 1667571.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207880.38
      sim_grid_pos_y: 1668071
    }
    terrain_level_point {
      sim_grid_pos_x: 1207918.12
      sim_grid_pos_y: 1668398.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207729.75
      sim_grid_pos_y: 1668498.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207680.38
      sim_grid_pos_y: 1668848.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207322.12
      sim_grid_pos_y: 1668833.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207317.88
      sim_grid_pos_y: 1669045
    }
    terrain_level_point {
      sim_grid_pos_x: 1207569.25
      sim_grid_pos_y: 1669084.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207570.75
      sim_grid_pos_y: 1669525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207880.38
      sim_grid_pos_y: 1669532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208099
      sim_grid_pos_y: 1669290.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208265.38
      sim_grid_pos_y: 1669227.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208852.75
      sim_grid_pos_y: 1669233.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209139.25
      sim_grid_pos_y: 1669311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209469.38
      sim_grid_pos_y: 1669554.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209337.62
      sim_grid_pos_y: 1669665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209338.88
      sim_grid_pos_y: 1669904.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209294.75
      sim_grid_pos_y: 1670054.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209195.5
      sim_grid_pos_y: 1670147.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209395.75
      sim_grid_pos_y: 1670196.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209348.25
      sim_grid_pos_y: 1670519.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209228.88
      sim_grid_pos_y: 1670491.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209408.88
      sim_grid_pos_y: 1670697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209121.12
      sim_grid_pos_y: 1670958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208367.25
      sim_grid_pos_y: 1670933.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208280.38
      sim_grid_pos_y: 1671115.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207500.62
      sim_grid_pos_y: 1671390.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.20739e+06
      sim_grid_pos_y: 1671254.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207325.25
      sim_grid_pos_y: 1671251
    }
    terrain_level_point {
      sim_grid_pos_x: 1207326.5
      sim_grid_pos_y: 1671526.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207312.38
      sim_grid_pos_y: 1672317.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208401.12
      sim_grid_pos_y: 1672303
    }
    terrain_level_point {
      sim_grid_pos_x: 1208355.38
      sim_grid_pos_y: 1672651.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208320.38
      sim_grid_pos_y: 1673495.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207963.12
      sim_grid_pos_y: 1674682.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208042.88
      sim_grid_pos_y: 1675162.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207502.5
      sim_grid_pos_y: 1675184.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207257.5
      sim_grid_pos_y: 1675205.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207229.25
      sim_grid_pos_y: 1675292.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206988.5
      sim_grid_pos_y: 1675419.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206889.75
      sim_grid_pos_y: 1675201.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206762.12
      sim_grid_pos_y: 1674985.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206697.38
      sim_grid_pos_y: 1674849.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206579.62
      sim_grid_pos_y: 1674840.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206344.75
      sim_grid_pos_y: 1674870.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206217.12
      sim_grid_pos_y: 1674815.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206121.88
      sim_grid_pos_y: 1674635.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206021.12
      sim_grid_pos_y: 1674499.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206019.75
      sim_grid_pos_y: 1673525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1205979
      sim_grid_pos_y: 1672499.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1205786.62
      sim_grid_pos_y: 1672268.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1205815
      sim_grid_pos_y: 1672114.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206032.75
      sim_grid_pos_y: 1672073.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206045.25
      sim_grid_pos_y: 1671593
    }
    terrain_level_point {
      sim_grid_pos_x: 1206004.88
      sim_grid_pos_y: 1671578.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1205951.5
      sim_grid_pos_y: 1671352.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1205966
      sim_grid_pos_y: 1671033.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1206020.12
      sim_grid_pos_y: 1670901
    }
    terrain_level_point {
      sim_grid_pos_x: 1205983.5
      sim_grid_pos_y: 1669165.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206029.62
      sim_grid_pos_y: 1669013
    }
    terrain_level_point {
      sim_grid_pos_x: 1206403.62
      sim_grid_pos_y: 1668798.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1206768.88
      sim_grid_pos_y: 1668121
    }
    terrain_level_point {
      sim_grid_pos_x: 1206808.62
      sim_grid_pos_y: 1667938.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206874.88
      sim_grid_pos_y: 1667803
    }
    terrain_level_point {
      sim_grid_pos_x: 1206964.12
      sim_grid_pos_y: 1667667.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207430.12
      sim_grid_pos_y: 1667379.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1207614.12
      sim_grid_pos_y: 1667407.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207780.5
      sim_grid_pos_y: 1667560.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207900.5
      sim_grid_pos_y: 1668067.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207940.12
      sim_grid_pos_y: 1668409.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207748.62
      sim_grid_pos_y: 1668511.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207698.12
      sim_grid_pos_y: 1.66887e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1207342.25
      sim_grid_pos_y: 1668855.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207338.75
      sim_grid_pos_y: 1669027.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207589.62
      sim_grid_pos_y: 1669066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207591.25
      sim_grid_pos_y: 1669505.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207871.38
      sim_grid_pos_y: 1669511.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208087.12
      sim_grid_pos_y: 1669273.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208261.75
      sim_grid_pos_y: 1669207.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208855.62
      sim_grid_pos_y: 1669212.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209148.38
      sim_grid_pos_y: 1669292.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209502.62
      sim_grid_pos_y: 1669553.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209358.25
      sim_grid_pos_y: 1669674.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209359.38
      sim_grid_pos_y: 1669907
    }
    terrain_level_point {
      sim_grid_pos_x: 1209312.88
      sim_grid_pos_y: 1670065.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209237
      sim_grid_pos_y: 1670137
    }
    terrain_level_point {
      sim_grid_pos_x: 1209418.75
      sim_grid_pos_y: 1670181.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209365.38
      sim_grid_pos_y: 1670544
    }
    terrain_level_point {
      sim_grid_pos_x: 1209285.88
      sim_grid_pos_y: 1670525.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209437.5
      sim_grid_pos_y: 1670699.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209128.75
      sim_grid_pos_y: 1670979.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.20838e+06
      sim_grid_pos_y: 1670954.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208295.25
      sim_grid_pos_y: 1671131.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207493.88
      sim_grid_pos_y: 1671415
    }
    terrain_level_point {
      sim_grid_pos_x: 1207379.75
      sim_grid_pos_y: 1671274.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207345.88
      sim_grid_pos_y: 1671272.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207347
      sim_grid_pos_y: 1671526.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1207333.25
      sim_grid_pos_y: 1672296.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208424.5
      sim_grid_pos_y: 1672282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208375.75
      sim_grid_pos_y: 1672653.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208340.75
      sim_grid_pos_y: 1673499.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207984.12
      sim_grid_pos_y: 1674683.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208066.88
      sim_grid_pos_y: 1675182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207503.75
      sim_grid_pos_y: 1675204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1207272.75
      sim_grid_pos_y: 1675224.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207246.12
      sim_grid_pos_y: 1675306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206978.75
      sim_grid_pos_y: 1675447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206871.5
      sim_grid_pos_y: 1675211.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206744
      sim_grid_pos_y: 1674995.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206684
      sim_grid_pos_y: 1674868.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206580.25
      sim_grid_pos_y: 1674861.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206341.75
      sim_grid_pos_y: 1674891.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206202.38
      sim_grid_pos_y: 1674831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1206104.5
      sim_grid_pos_y: 1674646.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206000.62
      sim_grid_pos_y: 1674506.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1205999.25
      sim_grid_pos_y: 1673526
    }
    terrain_level_point {
      sim_grid_pos_x: 1205958.75
      sim_grid_pos_y: 1672507.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1205764.75
      sim_grid_pos_y: 1672274
    }
    terrain_level_point {
      sim_grid_pos_x: 1205797.38
      sim_grid_pos_y: 1672096.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1206012.75
      sim_grid_pos_y: 1672056.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1206024.38
      sim_grid_pos_y: 1671607.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1205987.5
      sim_grid_pos_y: 1671594.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1205930.88
      sim_grid_pos_y: 1671354.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1205945.75
      sim_grid_pos_y: 1671029.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1205999.5
      sim_grid_pos_y: 1670897.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1205963
      sim_grid_pos_y: 1669163
    }
    terrain_level_point {
      sim_grid_pos_x: 1206012.38
      sim_grid_pos_y: 1668999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206388.38
      sim_grid_pos_y: 1668783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1206749.5
      sim_grid_pos_y: 1668113.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206789.12
      sim_grid_pos_y: 1667932
    }
    terrain_level_point {
      sim_grid_pos_x: 1206857
      sim_grid_pos_y: 1667792.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1206949.5
      sim_grid_pos_y: 1667652.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207426.75
      sim_grid_pos_y: 1667357.38
    }
  }
}
terrain_level_data {
  terrain_level: 323
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1208300.88
      sim_grid_pos_y: 1671496.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208326.38
      sim_grid_pos_y: 1671785.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208304.75
      sim_grid_pos_y: 1672082.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1208220.25
      sim_grid_pos_y: 1672257.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1208119
      sim_grid_pos_y: 1672344.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207805.38
      sim_grid_pos_y: 1672371
    }
    terrain_level_point {
      sim_grid_pos_x: 1207541.88
      sim_grid_pos_y: 1672375.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1207538.12
      sim_grid_pos_y: 1671818.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207526.12
      sim_grid_pos_y: 1671598
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1208347
      sim_grid_pos_y: 1671785.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208324.88
      sim_grid_pos_y: 1672087.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208236.88
      sim_grid_pos_y: 1672270.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208127.38
      sim_grid_pos_y: 1672364.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207806.38
      sim_grid_pos_y: 1672391.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1207521.5
      sim_grid_pos_y: 1672396.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207517.62
      sim_grid_pos_y: 1671819.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1207504.62
      sim_grid_pos_y: 1671580.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208319.38
      sim_grid_pos_y: 1671473.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1208367.5
      sim_grid_pos_y: 1671784.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208345.12
      sim_grid_pos_y: 1672093.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208253.5
      sim_grid_pos_y: 1672282.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208135.62
      sim_grid_pos_y: 1672384
    }
    terrain_level_point {
      sim_grid_pos_x: 1207807.5
      sim_grid_pos_y: 1672412
    }
    terrain_level_point {
      sim_grid_pos_x: 1207501.12
      sim_grid_pos_y: 1672416.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1207497.12
      sim_grid_pos_y: 1671820.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1207483.12
      sim_grid_pos_y: 1671562.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1208338
      sim_grid_pos_y: 1.67145e+06
    }
  }
}
