terrain_level_data {
  terrain_level: 197
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1944205.75
      sim_grid_pos_y: 1165567.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1944157.38
      sim_grid_pos_y: 1165663.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1944205
      sim_grid_pos_y: 1165766.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1944307.12
      sim_grid_pos_y: 1165835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1944402.5
      sim_grid_pos_y: 1165794
    }
    terrain_level_point {
      sim_grid_pos_x: 1944459.5
      sim_grid_pos_y: 1165670.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1944414.25
      sim_grid_pos_y: 1165561.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1944319.62
      sim_grid_pos_y: 1165496
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1944322.62
      sim_grid_pos_y: 1165373.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944127.12
      sim_grid_pos_y: 1165495.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1944043.62
      sim_grid_pos_y: 1165661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1944123.88
      sim_grid_pos_y: 1165836
    }
    terrain_level_point {
      sim_grid_pos_x: 1944296.5
      sim_grid_pos_y: 1165951.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1944479.12
      sim_grid_pos_y: 1165872.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1944571.38
      sim_grid_pos_y: 1165673.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944497.38
      sim_grid_pos_y: 1165494.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1944325.62
      sim_grid_pos_y: 1165250.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1944048.38
      sim_grid_pos_y: 1165423.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1943929.88
      sim_grid_pos_y: 1165659.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944042.88
      sim_grid_pos_y: 1165905.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944285.88
      sim_grid_pos_y: 1166067.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1944555.75
      sim_grid_pos_y: 1165951.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944683.38
      sim_grid_pos_y: 1165675.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1944580.62
      sim_grid_pos_y: 1165427.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1944328.62
      sim_grid_pos_y: 1165127.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1943969.75
      sim_grid_pos_y: 1165352.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1943816
      sim_grid_pos_y: 1165657.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1943961.75
      sim_grid_pos_y: 1165974.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944275.38
      sim_grid_pos_y: 1166184.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1944632.38
      sim_grid_pos_y: 1166029.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1944795.38
      sim_grid_pos_y: 1165677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1944663.88
      sim_grid_pos_y: 1165360.88
    }
  }
}
terrain_level_data {
  terrain_level: 197
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1934772.88
      sim_grid_pos_y: 1160383.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1934747
      sim_grid_pos_y: 1160494.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934778.12
      sim_grid_pos_y: 1160623.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1934898.75
      sim_grid_pos_y: 1160657.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934986.88
      sim_grid_pos_y: 1160598.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1935031.75
      sim_grid_pos_y: 1160504.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934997.12
      sim_grid_pos_y: 1160387.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934891.38
      sim_grid_pos_y: 1160335
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1934893.5
      sim_grid_pos_y: 1160278.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934729
      sim_grid_pos_y: 1160346
    }
    terrain_level_point {
      sim_grid_pos_x: 1934694.25
      sim_grid_pos_y: 1160495
    }
    terrain_level_point {
      sim_grid_pos_x: 1934735.38
      sim_grid_pos_y: 1160664.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1934907.62
      sim_grid_pos_y: 1160713.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1935027.12
      sim_grid_pos_y: 1160633.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1935086.5
      sim_grid_pos_y: 1160509.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1935039.88
      sim_grid_pos_y: 1160351.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1934895.62
      sim_grid_pos_y: 1160222.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1934685
      sim_grid_pos_y: 1160308.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1934641.62
      sim_grid_pos_y: 1160495.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1934692.5
      sim_grid_pos_y: 1160705.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1934916.5
      sim_grid_pos_y: 1160769.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1935067.25
      sim_grid_pos_y: 1160668
    }
    terrain_level_point {
      sim_grid_pos_x: 1935141.25
      sim_grid_pos_y: 1160513.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1935082.75
      sim_grid_pos_y: 1160316
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1934897.75
      sim_grid_pos_y: 1160166.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1934641.12
      sim_grid_pos_y: 1160271.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1934588.88
      sim_grid_pos_y: 1160495.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1934649.75
      sim_grid_pos_y: 1160746.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934925.38
      sim_grid_pos_y: 1160825.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1935107.5
      sim_grid_pos_y: 1160702.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1935196
      sim_grid_pos_y: 1160517.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1935125.62
      sim_grid_pos_y: 1.16028e+06
    }
  }
}
terrain_level_data {
  terrain_level: 342
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1928714.88
      sim_grid_pos_y: 1161539.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1928558.5
      sim_grid_pos_y: 1161668.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1928654.75
      sim_grid_pos_y: 1161829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1928809.25
      sim_grid_pos_y: 1161849.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1928915.88
      sim_grid_pos_y: 1161738.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1928891
      sim_grid_pos_y: 1161573.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1928689.75
      sim_grid_pos_y: 1161440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1928438.75
      sim_grid_pos_y: 1161647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1928598.38
      sim_grid_pos_y: 1161915.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1928843.5
      sim_grid_pos_y: 1161947.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1929013.88
      sim_grid_pos_y: 1161769.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1928972.5
      sim_grid_pos_y: 1161495
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1928664.62
      sim_grid_pos_y: 1161341.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1928318.88
      sim_grid_pos_y: 1161626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1928542
      sim_grid_pos_y: 1162000.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1928877.88
      sim_grid_pos_y: 1162045.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1929111.88
      sim_grid_pos_y: 1161800.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1929054
      sim_grid_pos_y: 1161416.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1928639.38
      sim_grid_pos_y: 1161242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1928199
      sim_grid_pos_y: 1161605.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1928485.62
      sim_grid_pos_y: 1162086.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1928912.12
      sim_grid_pos_y: 1162142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1929209.75
      sim_grid_pos_y: 1161831.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1929135.62
      sim_grid_pos_y: 1161338.5
    }
  }
}
terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1929492.75
      sim_grid_pos_y: 1165622.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1929391.25
      sim_grid_pos_y: 1165829.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1929435.25
      sim_grid_pos_y: 1166079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1929737.62
      sim_grid_pos_y: 1166123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1929909.12
      sim_grid_pos_y: 1165856.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1929686.12
      sim_grid_pos_y: 1165582
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1929726.25
      sim_grid_pos_y: 1165468.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1929422.75
      sim_grid_pos_y: 1165532.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1929284.38
      sim_grid_pos_y: 1165814.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1929347.25
      sim_grid_pos_y: 1166170.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1929788.25
      sim_grid_pos_y: 1166233.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1930035.5
      sim_grid_pos_y: 1165849
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1929766.38
      sim_grid_pos_y: 1165355.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1929352.75
      sim_grid_pos_y: 1165442.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1929177.62
      sim_grid_pos_y: 1165798.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1929259.12
      sim_grid_pos_y: 1166261.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1929839
      sim_grid_pos_y: 1166344.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1930161.88
      sim_grid_pos_y: 1165841.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1929806.5
      sim_grid_pos_y: 1165242.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1929282.75
      sim_grid_pos_y: 1165352.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1929070.88
      sim_grid_pos_y: 1165783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1929171
      sim_grid_pos_y: 1166352.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1929889.62
      sim_grid_pos_y: 1166455.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1930288.25
      sim_grid_pos_y: 1165834.75
    }
  }
}
terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1930771.62
      sim_grid_pos_y: 1167732.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1930760.5
      sim_grid_pos_y: 1167923.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1930822.5
      sim_grid_pos_y: 1167999.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1930934.12
      sim_grid_pos_y: 1168024.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1931015
      sim_grid_pos_y: 1167989.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1931029.5
      sim_grid_pos_y: 1167819.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1930959.62
      sim_grid_pos_y: 1167723.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1.93101e+06
      sim_grid_pos_y: 1167618.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1930674.62
      sim_grid_pos_y: 1167635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1930655.75
      sim_grid_pos_y: 1167957.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1930765.62
      sim_grid_pos_y: 1168091.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1930944.25
      sim_grid_pos_y: 1168131.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1931112
      sim_grid_pos_y: 1168059.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1931134.88
      sim_grid_pos_y: 1167790.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1931060.25
      sim_grid_pos_y: 1167513
    }
    terrain_level_point {
      sim_grid_pos_x: 1930577.62
      sim_grid_pos_y: 1167537.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1930551.12
      sim_grid_pos_y: 1167991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1930708.75
      sim_grid_pos_y: 1168184.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1930954.25
      sim_grid_pos_y: 1168238.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1931208.88
      sim_grid_pos_y: 1168129.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1931240.38
      sim_grid_pos_y: 1167761
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1931110.62
      sim_grid_pos_y: 1167407.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1930480.62
      sim_grid_pos_y: 1167439.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1930446.38
      sim_grid_pos_y: 1168025.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1930651.75
      sim_grid_pos_y: 1168276.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1930964.38
      sim_grid_pos_y: 1168346
    }
    terrain_level_point {
      sim_grid_pos_x: 1931305.88
      sim_grid_pos_y: 1168198.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1931345.75
      sim_grid_pos_y: 1167731.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1931160.88
      sim_grid_pos_y: 1167302.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1930383.62
      sim_grid_pos_y: 1167341.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1930341.62
      sim_grid_pos_y: 1168059.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1930594.88
      sim_grid_pos_y: 1168368.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1930974.5
      sim_grid_pos_y: 1168453.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1931402.75
      sim_grid_pos_y: 1168268.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1931451.12
      sim_grid_pos_y: 1167702.38
    }
  }
}
terrain_level_data {
  terrain_level: 98
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1941684.25
      sim_grid_pos_y: 1156867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1941112.62
      sim_grid_pos_y: 1156742.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1940654.38
      sim_grid_pos_y: 1157661
    }
    terrain_level_point {
      sim_grid_pos_x: 1939883.38
      sim_grid_pos_y: 1158219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1939747.12
      sim_grid_pos_y: 1158661.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1939753.38
      sim_grid_pos_y: 1159611.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1940687.12
      sim_grid_pos_y: 1160199.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1938849.12
      sim_grid_pos_y: 1160771.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1937255.25
      sim_grid_pos_y: 1161444.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1934733.38
      sim_grid_pos_y: 1163369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1935171.38
      sim_grid_pos_y: 1163864
    }
    terrain_level_point {
      sim_grid_pos_x: 1935246.88
      sim_grid_pos_y: 1164836.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1935722.62
      sim_grid_pos_y: 1164917.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1937283
      sim_grid_pos_y: 1163959.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1938706.5
      sim_grid_pos_y: 1163613.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1941173.88
      sim_grid_pos_y: 1163663.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1943435.62
      sim_grid_pos_y: 1162422.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1947279.12
      sim_grid_pos_y: 1161252.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1947474.25
      sim_grid_pos_y: 1163517.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1950017.88
      sim_grid_pos_y: 1164576.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1963376.38
      sim_grid_pos_y: 1165584.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1963344.75
      sim_grid_pos_y: 1162928.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1950744.62
      sim_grid_pos_y: 1162274.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1950303.25
      sim_grid_pos_y: 1160209.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1950181
      sim_grid_pos_y: 1159190.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1948911.25
      sim_grid_pos_y: 1159022.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1943244.88
      sim_grid_pos_y: 1160654.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1943328.75
      sim_grid_pos_y: 1158886.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1941056.5
      sim_grid_pos_y: 1156625.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1940573.88
      sim_grid_pos_y: 1157592.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1939795.5
      sim_grid_pos_y: 1158156.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1939644.5
      sim_grid_pos_y: 1158646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1939651.25
      sim_grid_pos_y: 1159668.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1940444.25
      sim_grid_pos_y: 1160167.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1938813.88
      sim_grid_pos_y: 1160675.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1937203.38
      sim_grid_pos_y: 1161354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1934583.5
      sim_grid_pos_y: 1163354.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1935071.88
      sim_grid_pos_y: 1163906.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1935150.88
      sim_grid_pos_y: 1164923.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1935743.38
      sim_grid_pos_y: 1165024.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1937322.88
      sim_grid_pos_y: 1164055.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1938717.75
      sim_grid_pos_y: 1163716.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1941199.12
      sim_grid_pos_y: 1163766.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1943475.62
      sim_grid_pos_y: 1162517.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1947187.88
      sim_grid_pos_y: 1161387.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1947377.38
      sim_grid_pos_y: 1163588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1949993.75
      sim_grid_pos_y: 1164677.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1963480.25
      sim_grid_pos_y: 1165694.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1963446.12
      sim_grid_pos_y: 1162831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1950828.5
      sim_grid_pos_y: 1162176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1950404.5
      sim_grid_pos_y: 1160192.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1950273.38
      sim_grid_pos_y: 1159098.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1948903.5
      sim_grid_pos_y: 1158917.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1943354.12
      sim_grid_pos_y: 1160516.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1943433
      sim_grid_pos_y: 1158852.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1941741.12
      sim_grid_pos_y: 1156774.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1941000.38
      sim_grid_pos_y: 1156508
    }
    terrain_level_point {
      sim_grid_pos_x: 1940493.38
      sim_grid_pos_y: 1157524.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1939707.62
      sim_grid_pos_y: 1158093.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1939541.88
      sim_grid_pos_y: 1158631.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1939549.12
      sim_grid_pos_y: 1159725.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1940201.38
      sim_grid_pos_y: 1160136.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1938778.62
      sim_grid_pos_y: 1160579.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1937151.5
      sim_grid_pos_y: 1161265.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1934433.62
      sim_grid_pos_y: 1163340.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1934972.25
      sim_grid_pos_y: 1163948.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1935054.88
      sim_grid_pos_y: 1165011.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1935764.12
      sim_grid_pos_y: 1165132.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1937362.75
      sim_grid_pos_y: 1164151.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1938729
      sim_grid_pos_y: 1163819
    }
    terrain_level_point {
      sim_grid_pos_x: 1941224.5
      sim_grid_pos_y: 1163869.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1943515.62
      sim_grid_pos_y: 1162612.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1947096.62
      sim_grid_pos_y: 1161522.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1947280.62
      sim_grid_pos_y: 1163659
    }
    terrain_level_point {
      sim_grid_pos_x: 1949969.5
      sim_grid_pos_y: 1164778.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1963584.12
      sim_grid_pos_y: 1165805.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1963547.5
      sim_grid_pos_y: 1162734.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1950912.25
      sim_grid_pos_y: 1162078.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1950505.75
      sim_grid_pos_y: 1160175.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1950365.62
      sim_grid_pos_y: 1159007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1948895.62
      sim_grid_pos_y: 1158813.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1943463.25
      sim_grid_pos_y: 1160378.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1943537.25
      sim_grid_pos_y: 1158818.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1941798
      sim_grid_pos_y: 1156682.25
    }
  }
}
