terrain_level_data {
  terrain_level: 1088
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 243944.297
      sim_grid_pos_y: 3308896.5
    }
    terrain_level_point {
      sim_grid_pos_x: 243945.875
      sim_grid_pos_y: 3309387
    }
    terrain_level_point {
      sim_grid_pos_x: 243631.984
      sim_grid_pos_y: 3309373.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243931.859
      sim_grid_pos_y: 3310446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 243900.609
      sim_grid_pos_y: 3310986
    }
    terrain_level_point {
      sim_grid_pos_x: 243638.953
      sim_grid_pos_y: 3311003.25
    }
    terrain_level_point {
      sim_grid_pos_x: 243918.844
      sim_grid_pos_y: 3312047
    }
    terrain_level_point {
      sim_grid_pos_x: 243920.453
      sim_grid_pos_y: 3319352
    }
    terrain_level_point {
      sim_grid_pos_x: 243827.812
      sim_grid_pos_y: 3319381.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243950.734
      sim_grid_pos_y: 3319574.75
    }
    terrain_level_point {
      sim_grid_pos_x: 244073.391
      sim_grid_pos_y: 3321985.5
    }
    terrain_level_point {
      sim_grid_pos_x: 244506.75
      sim_grid_pos_y: 3321983
    }
    terrain_level_point {
      sim_grid_pos_x: 244992.578
      sim_grid_pos_y: 3319410.25
    }
    terrain_level_point {
      sim_grid_pos_x: 245270
      sim_grid_pos_y: 3.31941e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 245258.906
      sim_grid_pos_y: 3315153.75
    }
    terrain_level_point {
      sim_grid_pos_x: 245864.5
      sim_grid_pos_y: 3315159.5
    }
    terrain_level_point {
      sim_grid_pos_x: 246301.375
      sim_grid_pos_y: 3.31495e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 246693.734
      sim_grid_pos_y: 3314178.75
    }
    terrain_level_point {
      sim_grid_pos_x: 246767.297
      sim_grid_pos_y: 3313502.75
    }
    terrain_level_point {
      sim_grid_pos_x: 245938.344
      sim_grid_pos_y: 3311528
    }
    terrain_level_point {
      sim_grid_pos_x: 245915.219
      sim_grid_pos_y: 3310633.25
    }
    terrain_level_point {
      sim_grid_pos_x: 245650.75
      sim_grid_pos_y: 3309540.75
    }
    terrain_level_point {
      sim_grid_pos_x: 245542.391
      sim_grid_pos_y: 3308631.75
    }
    terrain_level_point {
      sim_grid_pos_x: 245235.516
      sim_grid_pos_y: 3308408.25
    }
    terrain_level_point {
      sim_grid_pos_x: 244636.281
      sim_grid_pos_y: 3308283.75
    }
    terrain_level_point {
      sim_grid_pos_x: 244373.953
      sim_grid_pos_y: 3308295
    }
    terrain_level_point {
      sim_grid_pos_x: 244210.125
      sim_grid_pos_y: 3308560.5
    }
    terrain_level_point {
      sim_grid_pos_x: 244207.281
      sim_grid_pos_y: 3308731.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 244677.234
      sim_grid_pos_y: 3307779.25
    }
    terrain_level_point {
      sim_grid_pos_x: 244086.297
      sim_grid_pos_y: 3307804.5
    }
    terrain_level_point {
      sim_grid_pos_x: 243710.094
      sim_grid_pos_y: 3308414.25
    }
    terrain_level_point {
      sim_grid_pos_x: 243709.5
      sim_grid_pos_y: 3308450.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243441.031
      sim_grid_pos_y: 3308619.25
    }
    terrain_level_point {
      sim_grid_pos_x: 243441.812
      sim_grid_pos_y: 3308863
    }
    terrain_level_point {
      sim_grid_pos_x: 242961.875
      sim_grid_pos_y: 3308842.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243425.484
      sim_grid_pos_y: 3310501
    }
    terrain_level_point {
      sim_grid_pos_x: 243424.734
      sim_grid_pos_y: 3310514
    }
    terrain_level_point {
      sim_grid_pos_x: 242995.188
      sim_grid_pos_y: 3310542.25
    }
    terrain_level_point {
      sim_grid_pos_x: 243416.484
      sim_grid_pos_y: 3312113.25
    }
    terrain_level_point {
      sim_grid_pos_x: 243417.984
      sim_grid_pos_y: 3318985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243054.344
      sim_grid_pos_y: 3319102.5
    }
    terrain_level_point {
      sim_grid_pos_x: 243455.734
      sim_grid_pos_y: 3319732.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243596.062
      sim_grid_pos_y: 3322490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 244923.594
      sim_grid_pos_y: 3322483
    }
    terrain_level_point {
      sim_grid_pos_x: 245409.047
      sim_grid_pos_y: 3319912.25
    }
    terrain_level_point {
      sim_grid_pos_x: 245773.688
      sim_grid_pos_y: 3319912
    }
    terrain_level_point {
      sim_grid_pos_x: 245762.625
      sim_grid_pos_y: 3315661
    }
    terrain_level_point {
      sim_grid_pos_x: 245976.469
      sim_grid_pos_y: 3315663
    }
    terrain_level_point {
      sim_grid_pos_x: 246672
      sim_grid_pos_y: 3315329.5
    }
    terrain_level_point {
      sim_grid_pos_x: 247183.203
      sim_grid_pos_y: 3314324.5
    }
    terrain_level_point {
      sim_grid_pos_x: 247280.781
      sim_grid_pos_y: 3313428
    }
    terrain_level_point {
      sim_grid_pos_x: 246438.125
      sim_grid_pos_y: 3311420.5
    }
    terrain_level_point {
      sim_grid_pos_x: 246416.047
      sim_grid_pos_y: 3310567
    }
    terrain_level_point {
      sim_grid_pos_x: 246146.062
      sim_grid_pos_y: 3309451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 246015.297
      sim_grid_pos_y: 3308354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 245443.734
      sim_grid_pos_y: 3307938.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 244718.203
      sim_grid_pos_y: 3307274.5
    }
    terrain_level_point {
      sim_grid_pos_x: 243798.641
      sim_grid_pos_y: 3307314
    }
    terrain_level_point {
      sim_grid_pos_x: 243307.547
      sim_grid_pos_y: 3.30811e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 242942.375
      sim_grid_pos_y: 3308339
    }
    terrain_level_point {
      sim_grid_pos_x: 242291.766
      sim_grid_pos_y: 3308311.5
    }
    terrain_level_point {
      sim_grid_pos_x: 242778.594
      sim_grid_pos_y: 3310053
    }
    terrain_level_point {
      sim_grid_pos_x: 242351.438
      sim_grid_pos_y: 3310081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 242914.109
      sim_grid_pos_y: 3312179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 242915.531
      sim_grid_pos_y: 3318619.5
    }
    terrain_level_point {
      sim_grid_pos_x: 242280.859
      sim_grid_pos_y: 3318823.25
    }
    terrain_level_point {
      sim_grid_pos_x: 242960.766
      sim_grid_pos_y: 3319890.75
    }
    terrain_level_point {
      sim_grid_pos_x: 243118.734
      sim_grid_pos_y: 3322995.75
    }
    terrain_level_point {
      sim_grid_pos_x: 245340.438
      sim_grid_pos_y: 3322983
    }
    terrain_level_point {
      sim_grid_pos_x: 245825.516
      sim_grid_pos_y: 3320414.25
    }
    terrain_level_point {
      sim_grid_pos_x: 246277.375
      sim_grid_pos_y: 3320413.75
    }
    terrain_level_point {
      sim_grid_pos_x: 246266.094
      sim_grid_pos_y: 3316081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 247042.625
      sim_grid_pos_y: 3315708.75
    }
    terrain_level_point {
      sim_grid_pos_x: 247672.688
      sim_grid_pos_y: 3314470.25
    }
    terrain_level_point {
      sim_grid_pos_x: 247794.266
      sim_grid_pos_y: 3313353.25
    }
    terrain_level_point {
      sim_grid_pos_x: 246937.891
      sim_grid_pos_y: 3311313.25
    }
    terrain_level_point {
      sim_grid_pos_x: 246916.875
      sim_grid_pos_y: 3310500.5
    }
    terrain_level_point {
      sim_grid_pos_x: 246641.375
      sim_grid_pos_y: 3309362.5
    }
    terrain_level_point {
      sim_grid_pos_x: 246488.203
      sim_grid_pos_y: 3308077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 245651.969
      sim_grid_pos_y: 3307468.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 244759.156
      sim_grid_pos_y: 3.30677e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 243510.984
      sim_grid_pos_y: 3306823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 242941.453
      sim_grid_pos_y: 3307746.5
    }
    terrain_level_point {
      sim_grid_pos_x: 242807.594
      sim_grid_pos_y: 3307830.5
    }
    terrain_level_point {
      sim_grid_pos_x: 241621.656
      sim_grid_pos_y: 3307780.5
    }
    terrain_level_point {
      sim_grid_pos_x: 242128.203
      sim_grid_pos_y: 3309592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 241707.688
      sim_grid_pos_y: 3309620.25
    }
    terrain_level_point {
      sim_grid_pos_x: 242411.75
      sim_grid_pos_y: 3312245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 242413.062
      sim_grid_pos_y: 3318253.25
    }
    terrain_level_point {
      sim_grid_pos_x: 241507.391
      sim_grid_pos_y: 3318544
    }
    terrain_level_point {
      sim_grid_pos_x: 242465.766
      sim_grid_pos_y: 3320048.75
    }
    terrain_level_point {
      sim_grid_pos_x: 242641.406
      sim_grid_pos_y: 3323501
    }
    terrain_level_point {
      sim_grid_pos_x: 245757.281
      sim_grid_pos_y: 3323483
    }
    terrain_level_point {
      sim_grid_pos_x: 246241.969
      sim_grid_pos_y: 3320916.25
    }
    terrain_level_point {
      sim_grid_pos_x: 246781.062
      sim_grid_pos_y: 3320915.75
    }
    terrain_level_point {
      sim_grid_pos_x: 246769.297
      sim_grid_pos_y: 3316397
    }
    terrain_level_point {
      sim_grid_pos_x: 247413.25
      sim_grid_pos_y: 3316088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 248162.156
      sim_grid_pos_y: 3314616.25
    }
    terrain_level_point {
      sim_grid_pos_x: 248307.734
      sim_grid_pos_y: 3313278.5
    }
    terrain_level_point {
      sim_grid_pos_x: 247437.656
      sim_grid_pos_y: 3311205.75
    }
    terrain_level_point {
      sim_grid_pos_x: 247417.719
      sim_grid_pos_y: 3310434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 247136.672
      sim_grid_pos_y: 3309273.25
    }
    terrain_level_point {
      sim_grid_pos_x: 246961.109
      sim_grid_pos_y: 3307800.5
    }
    terrain_level_point {
      sim_grid_pos_x: 245860.188
      sim_grid_pos_y: 3306998.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 244800.125
      sim_grid_pos_y: 3306265.25
    }
    terrain_level_point {
      sim_grid_pos_x: 243223.344
      sim_grid_pos_y: 3306333
    }
    terrain_level_point {
      sim_grid_pos_x: 242614.594
      sim_grid_pos_y: 3307319.5
    }
    terrain_level_point {
      sim_grid_pos_x: 240951.547
      sim_grid_pos_y: 3307249.25
    }
    terrain_level_point {
      sim_grid_pos_x: 241477.812
      sim_grid_pos_y: 3309131.75
    }
    terrain_level_point {
      sim_grid_pos_x: 241063.922
      sim_grid_pos_y: 3309159.25
    }
    terrain_level_point {
      sim_grid_pos_x: 241909.391
      sim_grid_pos_y: 3312312
    }
    terrain_level_point {
      sim_grid_pos_x: 241910.625
      sim_grid_pos_y: 3317886.75
    }
    terrain_level_point {
      sim_grid_pos_x: 240733.922
      sim_grid_pos_y: 3318264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 241970.766
      sim_grid_pos_y: 3320206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 242164.078
      sim_grid_pos_y: 3324006
    }
    terrain_level_point {
      sim_grid_pos_x: 246174.125
      sim_grid_pos_y: 3323983
    }
    terrain_level_point {
      sim_grid_pos_x: 246658.438
      sim_grid_pos_y: 3321418.25
    }
    terrain_level_point {
      sim_grid_pos_x: 247284.75
      sim_grid_pos_y: 3321417.75
    }
    terrain_level_point {
      sim_grid_pos_x: 247272.484
      sim_grid_pos_y: 3316713
    }
    terrain_level_point {
      sim_grid_pos_x: 247783.875
      sim_grid_pos_y: 3316467.75
    }
    terrain_level_point {
      sim_grid_pos_x: 248651.641
      sim_grid_pos_y: 3314762
    }
    terrain_level_point {
      sim_grid_pos_x: 248821.203
      sim_grid_pos_y: 3313203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 247937.422
      sim_grid_pos_y: 3311098.5
    }
    terrain_level_point {
      sim_grid_pos_x: 247918.547
      sim_grid_pos_y: 3310368
    }
    terrain_level_point {
      sim_grid_pos_x: 247631.984
      sim_grid_pos_y: 3309184.25
    }
    terrain_level_point {
      sim_grid_pos_x: 247434.016
      sim_grid_pos_y: 3307523.5
    }
    terrain_level_point {
      sim_grid_pos_x: 246068.422
      sim_grid_pos_y: 3306528.75
    }
  }
}
