terrain_level_data {
  terrain_level: 175
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1802076.88
      sim_grid_pos_y: 1006089.19
    }
    terrain_level_point {
      sim_grid_pos_x: 1801891
      sim_grid_pos_y: 1006402.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1801972.38
      sim_grid_pos_y: 1006634.19
    }
    terrain_level_point {
      sim_grid_pos_x: 1802254.38
      sim_grid_pos_y: 1006735.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1802460.88
      sim_grid_pos_y: 1006706.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1802597.62
      sim_grid_pos_y: 1006649.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1802630.62
      sim_grid_pos_y: 1006484.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1802512.75
      sim_grid_pos_y: 1006382.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1802373.25
      sim_grid_pos_y: 1006303.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1802238.5
      sim_grid_pos_y: 1006187.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1802048.75
      sim_grid_pos_y: 1005975.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1801800.88
      sim_grid_pos_y: 1006393.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1801907.88
      sim_grid_pos_y: 1006698.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1802245.62
      sim_grid_pos_y: 1006819.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1802482.62
      sim_grid_pos_y: 1006786.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1802669.5
      sim_grid_pos_y: 1006708.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1802720.38
      sim_grid_pos_y: 1006453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1802560.25
      sim_grid_pos_y: 1006314.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1802420.62
      sim_grid_pos_y: 1006235.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1802286.88
      sim_grid_pos_y: 1006121.19
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1802020.62
      sim_grid_pos_y: 1005862.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1801710.88
      sim_grid_pos_y: 1006384.19
    }
    terrain_level_point {
      sim_grid_pos_x: 1801843.38
      sim_grid_pos_y: 1006762.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1802237
      sim_grid_pos_y: 1006903.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1802504.38
      sim_grid_pos_y: 1006866.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1802741.38
      sim_grid_pos_y: 1006767.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1802810.12
      sim_grid_pos_y: 1006423.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1802607.88
      sim_grid_pos_y: 1006247.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1802468
      sim_grid_pos_y: 1006168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1802335.25
      sim_grid_pos_y: 1006054.62
    }
  }
}
