terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2886382
      sim_grid_pos_y: 2301583.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2883035
      sim_grid_pos_y: 2303161
    }
    terrain_level_point {
      sim_grid_pos_x: 2884341
      sim_grid_pos_y: 2306416.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2887895
      sim_grid_pos_y: 2304654
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2886396.25
      sim_grid_pos_y: 2301543
    }
    terrain_level_point {
      sim_grid_pos_x: 2882995.5
      sim_grid_pos_y: 2303145.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2884324.75
      sim_grid_pos_y: 2306458.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2887936
      sim_grid_pos_y: 2304668
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2886410.5
      sim_grid_pos_y: 2301502.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2882956.25
      sim_grid_pos_y: 2.30313e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2884308.5
      sim_grid_pos_y: 2306501
    }
    terrain_level_point {
      sim_grid_pos_x: 2887977.25
      sim_grid_pos_y: 2304681.75
    }
  }
}
