terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2504241.5
      sim_grid_pos_y: 266897.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2510519.5
      sim_grid_pos_y: 239956
    }
    terrain_level_point {
      sim_grid_pos_x: 2511606.75
      sim_grid_pos_y: 221741.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2500322
      sim_grid_pos_y: 221080.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2487807
      sim_grid_pos_y: 220316.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2480322.5
      sim_grid_pos_y: 208480.859
    }
    terrain_level_point {
      sim_grid_pos_x: 2475052
      sim_grid_pos_y: 204752.672
    }
    terrain_level_point {
      sim_grid_pos_x: 2464991.75
      sim_grid_pos_y: 213445.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2480733.5
      sim_grid_pos_y: 231216.609
    }
    terrain_level_point {
      sim_grid_pos_x: 2477815.75
      sim_grid_pos_y: 233315.578
    }
    terrain_level_point {
      sim_grid_pos_x: 2487631.75
      sim_grid_pos_y: 240284.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2481459.5
      sim_grid_pos_y: 249837.172
    }
  }
}
terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2487674.75
      sim_grid_pos_y: 240456
    }
    terrain_level_point {
      sim_grid_pos_x: 2481280.25
      sim_grid_pos_y: 249788
    }
    terrain_level_point {
      sim_grid_pos_x: 2475748.5
      sim_grid_pos_y: 246137
    }
    terrain_level_point {
      sim_grid_pos_x: 2473084.25
      sim_grid_pos_y: 250198.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2465256
      sim_grid_pos_y: 245225.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2463879.25
      sim_grid_pos_y: 243652.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2463191
      sim_grid_pos_y: 241546.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2467008.5
      sim_grid_pos_y: 241001.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2477950.5
      sim_grid_pos_y: 233522.234
    }
  }
}
terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2477626.25
      sim_grid_pos_y: 233757
    }
    terrain_level_point {
      sim_grid_pos_x: 2468998.75
      sim_grid_pos_y: 240145.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466309
      sim_grid_pos_y: 241214.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2463137.25
      sim_grid_pos_y: 241545.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2459013.75
      sim_grid_pos_y: 241102.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2454617.5
      sim_grid_pos_y: 241185.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2454551
      sim_grid_pos_y: 253812.578
    }
    terrain_level_point {
      sim_grid_pos_x: 2448935
      sim_grid_pos_y: 250179.297
    }
    terrain_level_point {
      sim_grid_pos_x: 2440240.25
      sim_grid_pos_y: 241765.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2441069.25
      sim_grid_pos_y: 233701.078
    }
    terrain_level_point {
      sim_grid_pos_x: 2447600.75
      sim_grid_pos_y: 233245.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2.45059e+06
      sim_grid_pos_y: 232257.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2463002.5
      sim_grid_pos_y: 227064.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2466928.5
      sim_grid_pos_y: 221635.094
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2469963
      sim_grid_pos_y: 220154.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2467064
      sim_grid_pos_y: 221847.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2464598
      sim_grid_pos_y: 225545.328
    }
    terrain_level_point {
      sim_grid_pos_x: 2462882.25
      sim_grid_pos_y: 227354.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2450631.75
      sim_grid_pos_y: 232311.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2447511.5
      sim_grid_pos_y: 233178.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2448176.75
      sim_grid_pos_y: 229341.672
    }
    terrain_level_point {
      sim_grid_pos_x: 2.44605e+06
      sim_grid_pos_y: 228780.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2445265
      sim_grid_pos_y: 224575.266
    }
    terrain_level_point {
      sim_grid_pos_x: 2446535
      sim_grid_pos_y: 222118.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2446693
      sim_grid_pos_y: 219566.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2446384
      sim_grid_pos_y: 216855.266
    }
    terrain_level_point {
      sim_grid_pos_x: 2453499
      sim_grid_pos_y: 214358.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2456758
      sim_grid_pos_y: 220910.734
    }
    terrain_level_point {
      sim_grid_pos_x: 2465016
      sim_grid_pos_y: 213443.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2468467.75
      sim_grid_pos_y: 217536.594
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2.44756e+06
      sim_grid_pos_y: 233330.109
    }
    terrain_level_point {
      sim_grid_pos_x: 2441597
      sim_grid_pos_y: 233639.578
    }
    terrain_level_point {
      sim_grid_pos_x: 2440958.25
      sim_grid_pos_y: 241626.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2433365
      sim_grid_pos_y: 234896.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2433318.75
      sim_grid_pos_y: 231188.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2435287.5
      sim_grid_pos_y: 230534.672
    }
    terrain_level_point {
      sim_grid_pos_x: 2437815.75
      sim_grid_pos_y: 228663.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2440333.75
      sim_grid_pos_y: 223367.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2441468.75
      sim_grid_pos_y: 223831
    }
    terrain_level_point {
      sim_grid_pos_x: 2440683.5
      sim_grid_pos_y: 226813.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2446114.5
      sim_grid_pos_y: 227815.797
    }
    terrain_level_point {
      sim_grid_pos_x: 2446242.5
      sim_grid_pos_y: 228905.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2448254.75
      sim_grid_pos_y: 229543.875
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2435012
      sim_grid_pos_y: 230016.766
    }
    terrain_level_point {
      sim_grid_pos_x: 2436195
      sim_grid_pos_y: 229297.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2437238.5
      sim_grid_pos_y: 228835.203
    }
    terrain_level_point {
      sim_grid_pos_x: 2438140.75
      sim_grid_pos_y: 228219.609
    }
    terrain_level_point {
      sim_grid_pos_x: 2441481.75
      sim_grid_pos_y: 223744.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2442998.75
      sim_grid_pos_y: 221867.547
    }
    terrain_level_point {
      sim_grid_pos_x: 2443366.5
      sim_grid_pos_y: 211751.359
    }
    terrain_level_point {
      sim_grid_pos_x: 2437392.75
      sim_grid_pos_y: 212160.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2437015.75
      sim_grid_pos_y: 215724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2431470.5
      sim_grid_pos_y: 219675.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2429361
      sim_grid_pos_y: 221773.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2426984
      sim_grid_pos_y: 221889.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2433232
      sim_grid_pos_y: 227554.594
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2443419.75
      sim_grid_pos_y: 211696.328
    }
    terrain_level_point {
      sim_grid_pos_x: 2437346.25
      sim_grid_pos_y: 212112.016
    }
    terrain_level_point {
      sim_grid_pos_x: 2436967.25
      sim_grid_pos_y: 215695.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2431437.25
      sim_grid_pos_y: 219636.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2429338.75
      sim_grid_pos_y: 221723.016
    }
    terrain_level_point {
      sim_grid_pos_x: 2426947.25
      sim_grid_pos_y: 221840.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2426924.25
      sim_grid_pos_y: 221904.797
    }
    terrain_level_point {
      sim_grid_pos_x: 2433193.75
      sim_grid_pos_y: 227588.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2434998.25
      sim_grid_pos_y: 230085.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2436218.75
      sim_grid_pos_y: 229343.391
    }
    terrain_level_point {
      sim_grid_pos_x: 2437263.5
      sim_grid_pos_y: 228880.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2438176.5
      sim_grid_pos_y: 228257.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2441522.25
      sim_grid_pos_y: 223775.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2443049.5
      sim_grid_pos_y: 221886.484
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2443473.25
      sim_grid_pos_y: 211641.297
    }
    terrain_level_point {
      sim_grid_pos_x: 2437299.75
      sim_grid_pos_y: 212063.797
    }
    terrain_level_point {
      sim_grid_pos_x: 2436918.5
      sim_grid_pos_y: 215667.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2431404.25
      sim_grid_pos_y: 219597.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2429316.5
      sim_grid_pos_y: 221672.766
    }
    terrain_level_point {
      sim_grid_pos_x: 2426910.5
      sim_grid_pos_y: 221790.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2426864.5
      sim_grid_pos_y: 221919.766
    }
    terrain_level_point {
      sim_grid_pos_x: 2433155.25
      sim_grid_pos_y: 227623.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2434984.5
      sim_grid_pos_y: 230153.547
    }
    terrain_level_point {
      sim_grid_pos_x: 2436242.5
      sim_grid_pos_y: 229388.953
    }
    terrain_level_point {
      sim_grid_pos_x: 2437288.5
      sim_grid_pos_y: 228925.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2438212.5
      sim_grid_pos_y: 228294.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2441562.5
      sim_grid_pos_y: 223807.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2.4431e+06
      sim_grid_pos_y: 221905.406
    }
  }
}
