terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 774278.688
      sim_grid_pos_y: 2238448
    }
    terrain_level_point {
      sim_grid_pos_x: 773700.688
      sim_grid_pos_y: 2239241.5
    }
    terrain_level_point {
      sim_grid_pos_x: 772797
      sim_grid_pos_y: 2240054.25
    }
    terrain_level_point {
      sim_grid_pos_x: 772652.938
      sim_grid_pos_y: 2240632
    }
    terrain_level_point {
      sim_grid_pos_x: 772764.875
      sim_grid_pos_y: 2241674.75
    }
    terrain_level_point {
      sim_grid_pos_x: 773990.938
      sim_grid_pos_y: 2242047.75
    }
    terrain_level_point {
      sim_grid_pos_x: 774492.188
      sim_grid_pos_y: 2242448.75
    }
    terrain_level_point {
      sim_grid_pos_x: 776972.438
      sim_grid_pos_y: 2245427
    }
    terrain_level_point {
      sim_grid_pos_x: 777289.5
      sim_grid_pos_y: 2245528.25
    }
    terrain_level_point {
      sim_grid_pos_x: 779538.25
      sim_grid_pos_y: 2248326.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782596.438
      sim_grid_pos_y: 2248386
    }
    terrain_level_point {
      sim_grid_pos_x: 782611.812
      sim_grid_pos_y: 2248336.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782217.688
      sim_grid_pos_y: 2248326.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782247.625
      sim_grid_pos_y: 2248089.5
    }
    terrain_level_point {
      sim_grid_pos_x: 780687.688
      sim_grid_pos_y: 2248046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780690.688
      sim_grid_pos_y: 2247839.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780132.125
      sim_grid_pos_y: 2247853
    }
    terrain_level_point {
      sim_grid_pos_x: 779657.75
      sim_grid_pos_y: 2245184
    }
    terrain_level_point {
      sim_grid_pos_x: 779419.75
      sim_grid_pos_y: 2244494
    }
    terrain_level_point {
      sim_grid_pos_x: 778461.562
      sim_grid_pos_y: 2243624.5
    }
    terrain_level_point {
      sim_grid_pos_x: 780192.125
      sim_grid_pos_y: 2241731.5
    }
    terrain_level_point {
      sim_grid_pos_x: 780277.875
      sim_grid_pos_y: 2241587.75
    }
    terrain_level_point {
      sim_grid_pos_x: 780392.562
      sim_grid_pos_y: 2240732.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779213
      sim_grid_pos_y: 2240091.5
    }
    terrain_level_point {
      sim_grid_pos_x: 779707.75
      sim_grid_pos_y: 2239143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782898.812
      sim_grid_pos_y: 2240558.75
    }
    terrain_level_point {
      sim_grid_pos_x: 783203.875
      sim_grid_pos_y: 2241673.25
    }
    terrain_level_point {
      sim_grid_pos_x: 786290.5
      sim_grid_pos_y: 2243659.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785184.188
      sim_grid_pos_y: 2246785
    }
    terrain_level_point {
      sim_grid_pos_x: 785261.5
      sim_grid_pos_y: 2246925
    }
    terrain_level_point {
      sim_grid_pos_x: 785150.125
      sim_grid_pos_y: 2.24722e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 785498.438
      sim_grid_pos_y: 2250741
    }
    terrain_level_point {
      sim_grid_pos_x: 786476.562
      sim_grid_pos_y: 2250580.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788374.25
      sim_grid_pos_y: 2244918.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788044.312
      sim_grid_pos_y: 2244676
    }
    terrain_level_point {
      sim_grid_pos_x: 788719.688
      sim_grid_pos_y: 2242780.25
    }
    terrain_level_point {
      sim_grid_pos_x: 788658.875
      sim_grid_pos_y: 2242604.25
    }
    terrain_level_point {
      sim_grid_pos_x: 789080
      sim_grid_pos_y: 2241571
    }
    terrain_level_point {
      sim_grid_pos_x: 787268.625
      sim_grid_pos_y: 2239650.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786340.938
      sim_grid_pos_y: 2238629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786182.5
      sim_grid_pos_y: 2238537.5
    }
    terrain_level_point {
      sim_grid_pos_x: 786007.688
      sim_grid_pos_y: 2238272.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785823.25
      sim_grid_pos_y: 2238192
    }
    terrain_level_point {
      sim_grid_pos_x: 785465.562
      sim_grid_pos_y: 2237691
    }
    terrain_level_point {
      sim_grid_pos_x: 785680.938
      sim_grid_pos_y: 2.23748e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 785430.188
      sim_grid_pos_y: 2237129.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782763.688
      sim_grid_pos_y: 2236054.25
    }
    terrain_level_point {
      sim_grid_pos_x: 781798
      sim_grid_pos_y: 2235631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 779850.125
      sim_grid_pos_y: 2234997
    }
    terrain_level_point {
      sim_grid_pos_x: 778530
      sim_grid_pos_y: 2234321.75
    }
    terrain_level_point {
      sim_grid_pos_x: 778276.688
      sim_grid_pos_y: 2234600.25
    }
    terrain_level_point {
      sim_grid_pos_x: 777528.375
      sim_grid_pos_y: 2234905
    }
    terrain_level_point {
      sim_grid_pos_x: 775489.875
      sim_grid_pos_y: 2237130.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 778523.062
      sim_grid_pos_y: 2234283.75
    }
    terrain_level_point {
      sim_grid_pos_x: 778258.625
      sim_grid_pos_y: 2234574.5
    }
    terrain_level_point {
      sim_grid_pos_x: 777510.375
      sim_grid_pos_y: 2234879
    }
    terrain_level_point {
      sim_grid_pos_x: 775467.188
      sim_grid_pos_y: 2237109.25
    }
    terrain_level_point {
      sim_grid_pos_x: 774254.875
      sim_grid_pos_y: 2238428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 773677.75
      sim_grid_pos_y: 2239221
    }
    terrain_level_point {
      sim_grid_pos_x: 772769.375
      sim_grid_pos_y: 2240037.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772621.75
      sim_grid_pos_y: 2240629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772736.438
      sim_grid_pos_y: 2241698.25
    }
    terrain_level_point {
      sim_grid_pos_x: 773976.375
      sim_grid_pos_y: 2242075.5
    }
    terrain_level_point {
      sim_grid_pos_x: 774470.625
      sim_grid_pos_y: 2242471
    }
    terrain_level_point {
      sim_grid_pos_x: 776954.5
      sim_grid_pos_y: 2245453.5
    }
    terrain_level_point {
      sim_grid_pos_x: 777271.312
      sim_grid_pos_y: 2245554.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779523.312
      sim_grid_pos_y: 2248357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782618.938
      sim_grid_pos_y: 2248417
    }
    terrain_level_point {
      sim_grid_pos_x: 782653.25
      sim_grid_pos_y: 2248306.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782252.438
      sim_grid_pos_y: 2248296.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782282.375
      sim_grid_pos_y: 2248059.5
    }
    terrain_level_point {
      sim_grid_pos_x: 780718.875
      sim_grid_pos_y: 2248016.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780721.938
      sim_grid_pos_y: 2247807.75
    }
    terrain_level_point {
      sim_grid_pos_x: 780157.812
      sim_grid_pos_y: 2247821.5
    }
    terrain_level_point {
      sim_grid_pos_x: 779687.562
      sim_grid_pos_y: 2245176.25
    }
    terrain_level_point {
      sim_grid_pos_x: 779446.25
      sim_grid_pos_y: 2244476.5
    }
    terrain_level_point {
      sim_grid_pos_x: 778505.125
      sim_grid_pos_y: 2243622.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780216.938
      sim_grid_pos_y: 2.24175e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 780307.5
      sim_grid_pos_y: 2241598
    }
    terrain_level_point {
      sim_grid_pos_x: 780425.875
      sim_grid_pos_y: 2240715.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779254.25
      sim_grid_pos_y: 2240079
    }
    terrain_level_point {
      sim_grid_pos_x: 779721.688
      sim_grid_pos_y: 2239183
    }
    terrain_level_point {
      sim_grid_pos_x: 782873
      sim_grid_pos_y: 2240581
    }
    terrain_level_point {
      sim_grid_pos_x: 783177.312
      sim_grid_pos_y: 2241692.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786253.375
      sim_grid_pos_y: 2243672
    }
    terrain_level_point {
      sim_grid_pos_x: 785150.625
      sim_grid_pos_y: 2246787.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785227.688
      sim_grid_pos_y: 2246927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 785118.812
      sim_grid_pos_y: 2247216
    }
    terrain_level_point {
      sim_grid_pos_x: 785471.062
      sim_grid_pos_y: 2250776.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786499.812
      sim_grid_pos_y: 2250608
    }
    terrain_level_point {
      sim_grid_pos_x: 788410.562
      sim_grid_pos_y: 2244907.25
    }
    terrain_level_point {
      sim_grid_pos_x: 788080.938
      sim_grid_pos_y: 2244664.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788752.312
      sim_grid_pos_y: 2242780.25
    }
    terrain_level_point {
      sim_grid_pos_x: 788691.75
      sim_grid_pos_y: 2242605
    }
    terrain_level_point {
      sim_grid_pos_x: 789115.938
      sim_grid_pos_y: 2241564.25
    }
    terrain_level_point {
      sim_grid_pos_x: 787291
      sim_grid_pos_y: 2239629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786360.5
      sim_grid_pos_y: 2238605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 786204.188
      sim_grid_pos_y: 2238514.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786028.375
      sim_grid_pos_y: 2238248.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785843.375
      sim_grid_pos_y: 2238167.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785505.875
      sim_grid_pos_y: 2237694.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785721.25
      sim_grid_pos_y: 2237483.5
    }
    terrain_level_point {
      sim_grid_pos_x: 785450
      sim_grid_pos_y: 2237104.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782775.688
      sim_grid_pos_y: 2236026
    }
    terrain_level_point {
      sim_grid_pos_x: 781808.938
      sim_grid_pos_y: 2235602.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779861.938
      sim_grid_pos_y: 2234968.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 778516.125
      sim_grid_pos_y: 2234245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 778240.562
      sim_grid_pos_y: 2234548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 777492.375
      sim_grid_pos_y: 2234853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 775444.562
      sim_grid_pos_y: 2237088.5
    }
    terrain_level_point {
      sim_grid_pos_x: 774231
      sim_grid_pos_y: 2238408.75
    }
    terrain_level_point {
      sim_grid_pos_x: 773654.75
      sim_grid_pos_y: 2239200.25
    }
    terrain_level_point {
      sim_grid_pos_x: 772741.875
      sim_grid_pos_y: 2240021.25
    }
    terrain_level_point {
      sim_grid_pos_x: 772590.625
      sim_grid_pos_y: 2240627.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772708.062
      sim_grid_pos_y: 2241721.75
    }
    terrain_level_point {
      sim_grid_pos_x: 773961.75
      sim_grid_pos_y: 2242103.25
    }
    terrain_level_point {
      sim_grid_pos_x: 774448.875
      sim_grid_pos_y: 2242493
    }
    terrain_level_point {
      sim_grid_pos_x: 776936.625
      sim_grid_pos_y: 2.24548e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 777253.125
      sim_grid_pos_y: 2245581.25
    }
    terrain_level_point {
      sim_grid_pos_x: 779508.312
      sim_grid_pos_y: 2248387.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782641.438
      sim_grid_pos_y: 2248448.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782694.75
      sim_grid_pos_y: 2248277.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782287.25
      sim_grid_pos_y: 2248266.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782317.188
      sim_grid_pos_y: 2248029.75
    }
    terrain_level_point {
      sim_grid_pos_x: 780750.062
      sim_grid_pos_y: 2247986.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780753.125
      sim_grid_pos_y: 2247776.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780183.438
      sim_grid_pos_y: 2247790.25
    }
    terrain_level_point {
      sim_grid_pos_x: 779717.438
      sim_grid_pos_y: 2245168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 779472.75
      sim_grid_pos_y: 2244459
    }
    terrain_level_point {
      sim_grid_pos_x: 778548.625
      sim_grid_pos_y: 2243620.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780241.75
      sim_grid_pos_y: 2241768.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780337.188
      sim_grid_pos_y: 2241608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 780459.188
      sim_grid_pos_y: 2240698.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779295.5
      sim_grid_pos_y: 2240066.25
    }
    terrain_level_point {
      sim_grid_pos_x: 779735.625
      sim_grid_pos_y: 2239222.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782847.188
      sim_grid_pos_y: 2240603.25
    }
    terrain_level_point {
      sim_grid_pos_x: 783150.75
      sim_grid_pos_y: 2241712.25
    }
    terrain_level_point {
      sim_grid_pos_x: 786216.25
      sim_grid_pos_y: 2243684.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785117
      sim_grid_pos_y: 2246790.5
    }
    terrain_level_point {
      sim_grid_pos_x: 785193.938
      sim_grid_pos_y: 2246929.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785087.5
      sim_grid_pos_y: 2247211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785443.688
      sim_grid_pos_y: 2250812.5
    }
    terrain_level_point {
      sim_grid_pos_x: 786523.125
      sim_grid_pos_y: 2250635.5
    }
    terrain_level_point {
      sim_grid_pos_x: 788446.812
      sim_grid_pos_y: 2244895.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788117.625
      sim_grid_pos_y: 2244653.5
    }
    terrain_level_point {
      sim_grid_pos_x: 788784.875
      sim_grid_pos_y: 2242780.5
    }
    terrain_level_point {
      sim_grid_pos_x: 788724.625
      sim_grid_pos_y: 2242606
    }
    terrain_level_point {
      sim_grid_pos_x: 789151.875
      sim_grid_pos_y: 2241557.5
    }
    terrain_level_point {
      sim_grid_pos_x: 787313.812
      sim_grid_pos_y: 2239609
    }
    terrain_level_point {
      sim_grid_pos_x: 786380.062
      sim_grid_pos_y: 2238581.25
    }
    terrain_level_point {
      sim_grid_pos_x: 786225.875
      sim_grid_pos_y: 2238491.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786049.062
      sim_grid_pos_y: 2238223.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785863.5
      sim_grid_pos_y: 2238142.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785546.188
      sim_grid_pos_y: 2237698.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785761.625
      sim_grid_pos_y: 2237487
    }
    terrain_level_point {
      sim_grid_pos_x: 785469.812
      sim_grid_pos_y: 2237079
    }
    terrain_level_point {
      sim_grid_pos_x: 782787.5
      sim_grid_pos_y: 2235997.5
    }
    terrain_level_point {
      sim_grid_pos_x: 781819.875
      sim_grid_pos_y: 2235574
    }
    terrain_level_point {
      sim_grid_pos_x: 779873.875
      sim_grid_pos_y: 2234940.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 778509.188
      sim_grid_pos_y: 2234207.5
    }
    terrain_level_point {
      sim_grid_pos_x: 778222.5
      sim_grid_pos_y: 2234522.75
    }
    terrain_level_point {
      sim_grid_pos_x: 777474.312
      sim_grid_pos_y: 2234827.25
    }
    terrain_level_point {
      sim_grid_pos_x: 775421.938
      sim_grid_pos_y: 2237067.75
    }
    terrain_level_point {
      sim_grid_pos_x: 774207.188
      sim_grid_pos_y: 2238389.25
    }
    terrain_level_point {
      sim_grid_pos_x: 773631.812
      sim_grid_pos_y: 2239179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 772714.25
      sim_grid_pos_y: 2240004.5
    }
    terrain_level_point {
      sim_grid_pos_x: 772559.438
      sim_grid_pos_y: 2240625.5
    }
    terrain_level_point {
      sim_grid_pos_x: 772679.625
      sim_grid_pos_y: 2241745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 773947.125
      sim_grid_pos_y: 2242131
    }
    terrain_level_point {
      sim_grid_pos_x: 774427.312
      sim_grid_pos_y: 2242515
    }
    terrain_level_point {
      sim_grid_pos_x: 776918.688
      sim_grid_pos_y: 2245506.75
    }
    terrain_level_point {
      sim_grid_pos_x: 777234.938
      sim_grid_pos_y: 2245607.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779493.375
      sim_grid_pos_y: 2248418.25
    }
    terrain_level_point {
      sim_grid_pos_x: 782663.875
      sim_grid_pos_y: 2248479.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782736.25
      sim_grid_pos_y: 2248247.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782322
      sim_grid_pos_y: 2248236.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782351.938
      sim_grid_pos_y: 2.248e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 780781.25
      sim_grid_pos_y: 2247956.5
    }
    terrain_level_point {
      sim_grid_pos_x: 780784.375
      sim_grid_pos_y: 2247744.75
    }
    terrain_level_point {
      sim_grid_pos_x: 780209.125
      sim_grid_pos_y: 2247758.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779747.312
      sim_grid_pos_y: 2245160.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779499.25
      sim_grid_pos_y: 2244441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 778592.188
      sim_grid_pos_y: 2243618.25
    }
    terrain_level_point {
      sim_grid_pos_x: 780266.562
      sim_grid_pos_y: 2241786.75
    }
    terrain_level_point {
      sim_grid_pos_x: 780366.812
      sim_grid_pos_y: 2241618.75
    }
    terrain_level_point {
      sim_grid_pos_x: 780492.5
      sim_grid_pos_y: 2240682
    }
    terrain_level_point {
      sim_grid_pos_x: 779336.75
      sim_grid_pos_y: 2240053.75
    }
    terrain_level_point {
      sim_grid_pos_x: 779749.5
      sim_grid_pos_y: 2239262.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782821.375
      sim_grid_pos_y: 2240625.25
    }
    terrain_level_point {
      sim_grid_pos_x: 783124.188
      sim_grid_pos_y: 2241731.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786179.125
      sim_grid_pos_y: 2243697.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785083.375
      sim_grid_pos_y: 2246793.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785160.125
      sim_grid_pos_y: 2246932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785056.188
      sim_grid_pos_y: 2247207.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785416.312
      sim_grid_pos_y: 2250848
    }
    terrain_level_point {
      sim_grid_pos_x: 786546.375
      sim_grid_pos_y: 2250662.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788483.125
      sim_grid_pos_y: 2244884.25
    }
    terrain_level_point {
      sim_grid_pos_x: 788154.25
      sim_grid_pos_y: 2244642.25
    }
    terrain_level_point {
      sim_grid_pos_x: 788817.5
      sim_grid_pos_y: 2242780.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788757.438
      sim_grid_pos_y: 2242607
    }
    terrain_level_point {
      sim_grid_pos_x: 789187.875
      sim_grid_pos_y: 2241550.75
    }
    terrain_level_point {
      sim_grid_pos_x: 787336.188
      sim_grid_pos_y: 2239588
    }
    terrain_level_point {
      sim_grid_pos_x: 786399.625
      sim_grid_pos_y: 2238557.25
    }
    terrain_level_point {
      sim_grid_pos_x: 786247.625
      sim_grid_pos_y: 2238468.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786069.688
      sim_grid_pos_y: 2238199.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785883.562
      sim_grid_pos_y: 2238117.5
    }
    terrain_level_point {
      sim_grid_pos_x: 785586.5
      sim_grid_pos_y: 2237701.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785801.938
      sim_grid_pos_y: 2237490.5
    }
    terrain_level_point {
      sim_grid_pos_x: 785489.625
      sim_grid_pos_y: 2237054
    }
    terrain_level_point {
      sim_grid_pos_x: 782799.5
      sim_grid_pos_y: 2235969.25
    }
    terrain_level_point {
      sim_grid_pos_x: 781830.875
      sim_grid_pos_y: 2235545
    }
    terrain_level_point {
      sim_grid_pos_x: 779885.625
      sim_grid_pos_y: 2234911.75
    }
  }
}
