terrain_level_data {
  terrain_level: 300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2239425.5
      sim_grid_pos_y: 1313718.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2239849.5
      sim_grid_pos_y: 1313173.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2240132.25
      sim_grid_pos_y: 1312195.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2239296.75
      sim_grid_pos_y: 1312211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2238355.25
      sim_grid_pos_y: 1313923.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2237873
      sim_grid_pos_y: 1314822.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2238031
      sim_grid_pos_y: 1315036.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2238206.5
      sim_grid_pos_y: 1315346.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2238232.75
      sim_grid_pos_y: 1315467.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2238292.25
      sim_grid_pos_y: 1315432.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2238251.5
      sim_grid_pos_y: 1315246.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2238226.5
      sim_grid_pos_y: 1315159.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2238358
      sim_grid_pos_y: 1315155.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.23847e+06
      sim_grid_pos_y: 1315138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2238890.25
      sim_grid_pos_y: 1314369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2239216.25
      sim_grid_pos_y: 1314022.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2239356.75
      sim_grid_pos_y: 1313875.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2240201
      sim_grid_pos_y: 1312142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2239266
      sim_grid_pos_y: 1312160.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2238310.25
      sim_grid_pos_y: 1313898.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2237812.5
      sim_grid_pos_y: 1314827.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2237988
      sim_grid_pos_y: 1315064.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2238158
      sim_grid_pos_y: 1315365.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2238197.75
      sim_grid_pos_y: 1315547
    }
    terrain_level_point {
      sim_grid_pos_x: 2238350.25
      sim_grid_pos_y: 1315457.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2238301.25
      sim_grid_pos_y: 1315234
    }
    terrain_level_point {
      sim_grid_pos_x: 2238294
      sim_grid_pos_y: 1315208.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2238362.5
      sim_grid_pos_y: 1315206.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2238502.75
      sim_grid_pos_y: 1315185.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2238932
      sim_grid_pos_y: 1314400.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2239253.5
      sim_grid_pos_y: 1314057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2239253.5
      sim_grid_pos_y: 1314057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.2394e+06
      sim_grid_pos_y: 1313904.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.23947e+06
      sim_grid_pos_y: 1313744.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2239896
      sim_grid_pos_y: 1313197.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2240269.5
      sim_grid_pos_y: 1.31209e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2239235.5
      sim_grid_pos_y: 1312110.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2238265.25
      sim_grid_pos_y: 1313874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2237752
      sim_grid_pos_y: 1314831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2237944.75
      sim_grid_pos_y: 1315092.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2238109.75
      sim_grid_pos_y: 1315383.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2238162.75
      sim_grid_pos_y: 1315626.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2238408.25
      sim_grid_pos_y: 1315483.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2238359
      sim_grid_pos_y: 1315257.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2238367.25
      sim_grid_pos_y: 1315257.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2238535.5
      sim_grid_pos_y: 1315232.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2238974
      sim_grid_pos_y: 1314430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2239290.5
      sim_grid_pos_y: 1314093.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2239443.5
      sim_grid_pos_y: 1313932.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2239514.25
      sim_grid_pos_y: 1313771.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2239942.5
      sim_grid_pos_y: 1313221.12
    }
  }
}
terrain_level_data {
  terrain_level: 360
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2237828.5
      sim_grid_pos_y: 1314955
    }
    terrain_level_point {
      sim_grid_pos_x: 2237616.5
      sim_grid_pos_y: 1315334.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2237595
      sim_grid_pos_y: 1315472.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2237407.25
      sim_grid_pos_y: 1315714.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2237218.25
      sim_grid_pos_y: 1315624.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2237251.75
      sim_grid_pos_y: 1315461.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2237282.5
      sim_grid_pos_y: 1315363.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2237350.5
      sim_grid_pos_y: 1315236.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2237380.25
      sim_grid_pos_y: 1315127.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2237430.75
      sim_grid_pos_y: 1315002
    }
    terrain_level_point {
      sim_grid_pos_x: 2237527.5
      sim_grid_pos_y: 1314854.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2237620.75
      sim_grid_pos_y: 1314768.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2237893
      sim_grid_pos_y: 1314944.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2237665.75
      sim_grid_pos_y: 1315351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2237643.5
      sim_grid_pos_y: 1315493.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2237422.5
      sim_grid_pos_y: 1315778.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.23716e+06
      sim_grid_pos_y: 1315653.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2237202.25
      sim_grid_pos_y: 1315448.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2237235
      sim_grid_pos_y: 1315344
    }
    terrain_level_point {
      sim_grid_pos_x: 2237302.5
      sim_grid_pos_y: 1315217.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2237331.5
      sim_grid_pos_y: 1315111.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2237385.25
      sim_grid_pos_y: 1314978.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2237488
      sim_grid_pos_y: 1314821
    }
    terrain_level_point {
      sim_grid_pos_x: 2237620.25
      sim_grid_pos_y: 1314699.5
    }
  }
}
