terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 614494.125
      sim_grid_pos_y: 2238198.75
    }
    terrain_level_point {
      sim_grid_pos_x: 615230.688
      sim_grid_pos_y: 2236253.5
    }
    terrain_level_point {
      sim_grid_pos_x: 615412.688
      sim_grid_pos_y: 2233588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 613379
      sim_grid_pos_y: 2233566.25
    }
    terrain_level_point {
      sim_grid_pos_x: 610892.5
      sim_grid_pos_y: 2232667.75
    }
    terrain_level_point {
      sim_grid_pos_x: 609916.25
      sim_grid_pos_y: 2234898.5
    }
    terrain_level_point {
      sim_grid_pos_x: 609590.125
      sim_grid_pos_y: 2235640.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607200.188
      sim_grid_pos_y: 2237892.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606531.875
      sim_grid_pos_y: 2238603.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603540.562
      sim_grid_pos_y: 2241062.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602801.188
      sim_grid_pos_y: 2241955.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601765.875
      sim_grid_pos_y: 2.24258e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 601479.688
      sim_grid_pos_y: 2242828.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601308.438
      sim_grid_pos_y: 2243115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601294.188
      sim_grid_pos_y: 2243431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601318.062
      sim_grid_pos_y: 2243656
    }
    terrain_level_point {
      sim_grid_pos_x: 601307.438
      sim_grid_pos_y: 2243827.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601239.75
      sim_grid_pos_y: 2244087.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601032
      sim_grid_pos_y: 2244399
    }
    terrain_level_point {
      sim_grid_pos_x: 602344.375
      sim_grid_pos_y: 2244878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603577.188
      sim_grid_pos_y: 2243943.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605085.062
      sim_grid_pos_y: 2242288.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607956.938
      sim_grid_pos_y: 2240688.25
    }
    terrain_level_point {
      sim_grid_pos_x: 610844.062
      sim_grid_pos_y: 2239898.25
    }
    terrain_level_point {
      sim_grid_pos_x: 612777.062
      sim_grid_pos_y: 2239149.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 610875.875
      sim_grid_pos_y: 2232629
    }
    terrain_level_point {
      sim_grid_pos_x: 609888.062
      sim_grid_pos_y: 2234886
    }
    terrain_level_point {
      sim_grid_pos_x: 609564.438
      sim_grid_pos_y: 2235622.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607178.438
      sim_grid_pos_y: 2237870.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606510.812
      sim_grid_pos_y: 2238581.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603518.75
      sim_grid_pos_y: 2241040.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602780.812
      sim_grid_pos_y: 2241932
    }
    terrain_level_point {
      sim_grid_pos_x: 601747.75
      sim_grid_pos_y: 2242555
    }
    terrain_level_point {
      sim_grid_pos_x: 601455.812
      sim_grid_pos_y: 2242808.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601278.062
      sim_grid_pos_y: 2243106.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601263.375
      sim_grid_pos_y: 2243432.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601287.188
      sim_grid_pos_y: 2243656.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601276.938
      sim_grid_pos_y: 2243823
    }
    terrain_level_point {
      sim_grid_pos_x: 601211.25
      sim_grid_pos_y: 2244074.75
    }
    terrain_level_point {
      sim_grid_pos_x: 600984.688
      sim_grid_pos_y: 2244414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602349.562
      sim_grid_pos_y: 2244913.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603598.062
      sim_grid_pos_y: 2243966.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605104.438
      sim_grid_pos_y: 2242313.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607968.688
      sim_grid_pos_y: 2240717
    }
    terrain_level_point {
      sim_grid_pos_x: 610853.75
      sim_grid_pos_y: 2239927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 612790.188
      sim_grid_pos_y: 2239177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 614518.938
      sim_grid_pos_y: 2238220.25
    }
    terrain_level_point {
      sim_grid_pos_x: 615261.062
      sim_grid_pos_y: 2236260.25
    }
    terrain_level_point {
      sim_grid_pos_x: 615445.562
      sim_grid_pos_y: 2233557.75
    }
    terrain_level_point {
      sim_grid_pos_x: 613384.5
      sim_grid_pos_y: 2233535.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 610859.25
      sim_grid_pos_y: 2232590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 609859.875
      sim_grid_pos_y: 2234873.75
    }
    terrain_level_point {
      sim_grid_pos_x: 609859.875
      sim_grid_pos_y: 2234873.75
    }
    terrain_level_point {
      sim_grid_pos_x: 609538.812
      sim_grid_pos_y: 2235604.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607156.688
      sim_grid_pos_y: 2237848.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606489.75
      sim_grid_pos_y: 2238558.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603496.938
      sim_grid_pos_y: 2241019
    }
    terrain_level_point {
      sim_grid_pos_x: 602760.438
      sim_grid_pos_y: 2241908.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601729.562
      sim_grid_pos_y: 2.24253e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 601431.875
      sim_grid_pos_y: 2242788.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601247.688
      sim_grid_pos_y: 2243097.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601232.562
      sim_grid_pos_y: 2243433.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601256.375
      sim_grid_pos_y: 2243657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601246.438
      sim_grid_pos_y: 2243818
    }
    terrain_level_point {
      sim_grid_pos_x: 601182.812
      sim_grid_pos_y: 2244062.25
    }
    terrain_level_point {
      sim_grid_pos_x: 600937.375
      sim_grid_pos_y: 2.24443e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 602354.812
      sim_grid_pos_y: 2244947.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603618.875
      sim_grid_pos_y: 2243989.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605123.75
      sim_grid_pos_y: 2242337.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607980.438
      sim_grid_pos_y: 2240745.75
    }
    terrain_level_point {
      sim_grid_pos_x: 610863.375
      sim_grid_pos_y: 2239956.75
    }
    terrain_level_point {
      sim_grid_pos_x: 612803.25
      sim_grid_pos_y: 2239205
    }
    terrain_level_point {
      sim_grid_pos_x: 614543.688
      sim_grid_pos_y: 2238241.75
    }
    terrain_level_point {
      sim_grid_pos_x: 615291.438
      sim_grid_pos_y: 2236266.75
    }
    terrain_level_point {
      sim_grid_pos_x: 615478.5
      sim_grid_pos_y: 2233527.5
    }
    terrain_level_point {
      sim_grid_pos_x: 613390.062
      sim_grid_pos_y: 2233505
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 610842.625
      sim_grid_pos_y: 2232551.5
    }
    terrain_level_point {
      sim_grid_pos_x: 609831.75
      sim_grid_pos_y: 2234861.25
    }
    terrain_level_point {
      sim_grid_pos_x: 609513.188
      sim_grid_pos_y: 2235586
    }
    terrain_level_point {
      sim_grid_pos_x: 607134.875
      sim_grid_pos_y: 2237827
    }
    terrain_level_point {
      sim_grid_pos_x: 606468.688
      sim_grid_pos_y: 2238536.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603475.125
      sim_grid_pos_y: 2240997
    }
    terrain_level_point {
      sim_grid_pos_x: 602740.125
      sim_grid_pos_y: 2241884.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601711.438
      sim_grid_pos_y: 2242505
    }
    terrain_level_point {
      sim_grid_pos_x: 601408
      sim_grid_pos_y: 2242768.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601217.312
      sim_grid_pos_y: 2243088.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601201.688
      sim_grid_pos_y: 2243434.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601225.5
      sim_grid_pos_y: 2243658
    }
    terrain_level_point {
      sim_grid_pos_x: 601215.938
      sim_grid_pos_y: 2243813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601154.375
      sim_grid_pos_y: 2244049.25
    }
    terrain_level_point {
      sim_grid_pos_x: 600890.125
      sim_grid_pos_y: 2244445.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602360
      sim_grid_pos_y: 2244982.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603639.688
      sim_grid_pos_y: 2244012
    }
    terrain_level_point {
      sim_grid_pos_x: 605143.125
      sim_grid_pos_y: 2242362
    }
    terrain_level_point {
      sim_grid_pos_x: 607992.125
      sim_grid_pos_y: 2240774.25
    }
    terrain_level_point {
      sim_grid_pos_x: 610873
      sim_grid_pos_y: 2239986
    }
    terrain_level_point {
      sim_grid_pos_x: 612816.312
      sim_grid_pos_y: 2239233
    }
    terrain_level_point {
      sim_grid_pos_x: 614568.438
      sim_grid_pos_y: 2238263.25
    }
    terrain_level_point {
      sim_grid_pos_x: 615321.812
      sim_grid_pos_y: 2236273.5
    }
    terrain_level_point {
      sim_grid_pos_x: 615511.375
      sim_grid_pos_y: 2233497
    }
    terrain_level_point {
      sim_grid_pos_x: 613395.625
      sim_grid_pos_y: 2233474.25
    }
  }
}
