terrain_level_data {
  terrain_level: 49
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 456053.344
      sim_grid_pos_y: 1471202.38
    }
    terrain_level_point {
      sim_grid_pos_x: 458917
      sim_grid_pos_y: 1473958.38
    }
    terrain_level_point {
      sim_grid_pos_x: 458118.594
      sim_grid_pos_y: 1478108.62
    }
    terrain_level_point {
      sim_grid_pos_x: 455947.25
      sim_grid_pos_y: 1476344.12
    }
    terrain_level_point {
      sim_grid_pos_x: 454936.656
      sim_grid_pos_y: 1475480.62
    }
    terrain_level_point {
      sim_grid_pos_x: 453844.188
      sim_grid_pos_y: 1.47556e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 452086.5
      sim_grid_pos_y: 1474521.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452253.969
      sim_grid_pos_y: 1474184.62
    }
    terrain_level_point {
      sim_grid_pos_x: 450888.25
      sim_grid_pos_y: 1473562.62
    }
    terrain_level_point {
      sim_grid_pos_x: 449218.156
      sim_grid_pos_y: 1472509.75
    }
    terrain_level_point {
      sim_grid_pos_x: 448968.812
      sim_grid_pos_y: 1472665
    }
    terrain_level_point {
      sim_grid_pos_x: 446677.625
      sim_grid_pos_y: 1470985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 448718.938
      sim_grid_pos_y: 1467706.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449731
      sim_grid_pos_y: 1468472.62
    }
    terrain_level_point {
      sim_grid_pos_x: 450458.188
      sim_grid_pos_y: 1467351.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 456118.375
      sim_grid_pos_y: 1471122.62
    }
    terrain_level_point {
      sim_grid_pos_x: 459028.188
      sim_grid_pos_y: 1473923.12
    }
    terrain_level_point {
      sim_grid_pos_x: 458186.906
      sim_grid_pos_y: 1478296.12
    }
    terrain_level_point {
      sim_grid_pos_x: 455881.594
      sim_grid_pos_y: 1476422.88
    }
    terrain_level_point {
      sim_grid_pos_x: 454902.062
      sim_grid_pos_y: 1475586
    }
    terrain_level_point {
      sim_grid_pos_x: 453819.625
      sim_grid_pos_y: 1475664.62
    }
    terrain_level_point {
      sim_grid_pos_x: 451952.25
      sim_grid_pos_y: 1474561.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452114.969
      sim_grid_pos_y: 1474234
    }
    terrain_level_point {
      sim_grid_pos_x: 450839.438
      sim_grid_pos_y: 1473653.12
    }
    terrain_level_point {
      sim_grid_pos_x: 449217.812
      sim_grid_pos_y: 1472630.75
    }
    terrain_level_point {
      sim_grid_pos_x: 448964.125
      sim_grid_pos_y: 1472788.62
    }
    terrain_level_point {
      sim_grid_pos_x: 446540.344
      sim_grid_pos_y: 1471012.38
    }
    terrain_level_point {
      sim_grid_pos_x: 448691.25
      sim_grid_pos_y: 1467556.62
    }
    terrain_level_point {
      sim_grid_pos_x: 449705
      sim_grid_pos_y: 1468324.38
    }
    terrain_level_point {
      sim_grid_pos_x: 450429.531
      sim_grid_pos_y: 1467207.25
    }
  }
}
