terrain_level_data {
  terrain_level: 4192
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2717645.25
      sim_grid_pos_y: 961894.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2717644.25
      sim_grid_pos_y: 962065.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2717823.75
      sim_grid_pos_y: 962063.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2717817.75
      sim_grid_pos_y: 961896.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2717614.5
      sim_grid_pos_y: 961863.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2717613.25
      sim_grid_pos_y: 962096.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2717855.5
      sim_grid_pos_y: 962094.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2717847.5
      sim_grid_pos_y: 961865.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2717584
      sim_grid_pos_y: 961832.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2717582.5
      sim_grid_pos_y: 962127.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2717887.5
      sim_grid_pos_y: 962124.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2717877.25
      sim_grid_pos_y: 961835.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2717553.5
      sim_grid_pos_y: 961801.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2717551.5
      sim_grid_pos_y: 962159.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2717919.25
      sim_grid_pos_y: 962155.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2717907
      sim_grid_pos_y: 961804.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2717522.75
      sim_grid_pos_y: 961770.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2717520.5
      sim_grid_pos_y: 962190.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2717951.25
      sim_grid_pos_y: 962185.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2717936.75
      sim_grid_pos_y: 961774.062
    }
  }
}
terrain_level_data {
  terrain_level: 4110
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2717387.75
      sim_grid_pos_y: 961961.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2717367.75
      sim_grid_pos_y: 962326.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2717084.75
      sim_grid_pos_y: 962329.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2717086.5
      sim_grid_pos_y: 961958.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2717420.25
      sim_grid_pos_y: 961931.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2717397
      sim_grid_pos_y: 962356.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2717053.75
      sim_grid_pos_y: 962360.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2717056
      sim_grid_pos_y: 961927.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2717452.75
      sim_grid_pos_y: 961901.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2717426
      sim_grid_pos_y: 962387.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2717022.75
      sim_grid_pos_y: 962392.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2717025.25
      sim_grid_pos_y: 961895.938
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2717485
      sim_grid_pos_y: 961870.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2717455.25
      sim_grid_pos_y: 962417.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2716992
      sim_grid_pos_y: 962423.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2716994.75
      sim_grid_pos_y: 961864.75
    }
  }
}
terrain_level_data {
  terrain_level: 4250
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2718139.75
      sim_grid_pos_y: 962123.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2718082.25
      sim_grid_pos_y: 962204.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718289
      sim_grid_pos_y: 962435.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2718263
      sim_grid_pos_y: 962647.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2718383.5
      sim_grid_pos_y: 962756.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2718544.25
      sim_grid_pos_y: 962670.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2718651.75
      sim_grid_pos_y: 962235.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2718403.75
      sim_grid_pos_y: 962251.938
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2718129.75
      sim_grid_pos_y: 962084.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2718043
      sim_grid_pos_y: 962206.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2718256.75
      sim_grid_pos_y: 962445.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2718230.5
      sim_grid_pos_y: 962659.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2718378.75
      sim_grid_pos_y: 962793.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2718570.75
      sim_grid_pos_y: 962691.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718691.75
      sim_grid_pos_y: 962202.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71841e+06
      sim_grid_pos_y: 962220.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2718119.75
      sim_grid_pos_y: 962045.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2718003.75
      sim_grid_pos_y: 962209.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2718224.5
      sim_grid_pos_y: 962455.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2718198
      sim_grid_pos_y: 962671.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2718374
      sim_grid_pos_y: 962830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2718597.25
      sim_grid_pos_y: 962712.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2718731.75
      sim_grid_pos_y: 962169.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2718416
      sim_grid_pos_y: 962189.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2718109.75
      sim_grid_pos_y: 962006.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2717964.25
      sim_grid_pos_y: 962211.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2718192.25
      sim_grid_pos_y: 962465.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718165.5
      sim_grid_pos_y: 962683.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2718369.5
      sim_grid_pos_y: 962868.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2718624
      sim_grid_pos_y: 962733.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2718771.75
      sim_grid_pos_y: 962135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2718422.25
      sim_grid_pos_y: 962158.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2718099.75
      sim_grid_pos_y: 961967.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2717925
      sim_grid_pos_y: 962213.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71816e+06
      sim_grid_pos_y: 962475.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2718133.25
      sim_grid_pos_y: 962695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2718364.75
      sim_grid_pos_y: 962905.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2718650.5
      sim_grid_pos_y: 962753.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2718811.75
      sim_grid_pos_y: 962102.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2718428.25
      sim_grid_pos_y: 962127.062
    }
  }
}
terrain_level_data {
  terrain_level: 4250
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2718226.25
      sim_grid_pos_y: 961118.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718238.25
      sim_grid_pos_y: 961367.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2718626.75
      sim_grid_pos_y: 961370
    }
    terrain_level_point {
      sim_grid_pos_x: 2718604.25
      sim_grid_pos_y: 961119.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2718194
      sim_grid_pos_y: 961087.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2718208.75
      sim_grid_pos_y: 961397.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718660.5
      sim_grid_pos_y: 961401
    }
    terrain_level_point {
      sim_grid_pos_x: 2718632.25
      sim_grid_pos_y: 961089.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2718161.75
      sim_grid_pos_y: 961057
    }
    terrain_level_point {
      sim_grid_pos_x: 2718179.5
      sim_grid_pos_y: 961428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2718694
      sim_grid_pos_y: 961432
    }
    terrain_level_point {
      sim_grid_pos_x: 2718660.5
      sim_grid_pos_y: 961058.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2718129.5
      sim_grid_pos_y: 961026.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2718150.25
      sim_grid_pos_y: 961458.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2718727.75
      sim_grid_pos_y: 961463
    }
    terrain_level_point {
      sim_grid_pos_x: 2718688.5
      sim_grid_pos_y: 961027.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2718097.25
      sim_grid_pos_y: 960995.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2718120.75
      sim_grid_pos_y: 961489.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2718761.5
      sim_grid_pos_y: 961494
    }
    terrain_level_point {
      sim_grid_pos_x: 2718716.5
      sim_grid_pos_y: 960997.125
    }
  }
}
