terrain_level_data {
  terrain_level: 25
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1501954.88
      sim_grid_pos_y: 1187116.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502198.5
      sim_grid_pos_y: 1187299.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502088.88
      sim_grid_pos_y: 1187353.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502119.88
      sim_grid_pos_y: 1187486.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1502258
      sim_grid_pos_y: 1187638.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502471
      sim_grid_pos_y: 1187541.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502622
      sim_grid_pos_y: 1187364.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1502844.62
      sim_grid_pos_y: 1186968.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1503225.5
      sim_grid_pos_y: 1186776.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1503662.62
      sim_grid_pos_y: 1186784.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1503924
      sim_grid_pos_y: 1186727.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1504263.12
      sim_grid_pos_y: 1.18689e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1504849.25
      sim_grid_pos_y: 1186898
    }
    terrain_level_point {
      sim_grid_pos_x: 1505406.12
      sim_grid_pos_y: 1185808.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1507095.62
      sim_grid_pos_y: 1183671.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1507601.75
      sim_grid_pos_y: 1182891.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507582.38
      sim_grid_pos_y: 1180575.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1505492.38
      sim_grid_pos_y: 1179650.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1505197.75
      sim_grid_pos_y: 1180169.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504808.38
      sim_grid_pos_y: 1181036.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1504406.88
      sim_grid_pos_y: 1181666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502988.12
      sim_grid_pos_y: 1182156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502798.12
      sim_grid_pos_y: 1182149
    }
    terrain_level_point {
      sim_grid_pos_x: 1502036.62
      sim_grid_pos_y: 1183162.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1505479.25
      sim_grid_pos_y: 1179611
    }
    terrain_level_point {
      sim_grid_pos_x: 1505170.38
      sim_grid_pos_y: 1180155.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1504781.25
      sim_grid_pos_y: 1181021.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1504386.62
      sim_grid_pos_y: 1181641.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502983.62
      sim_grid_pos_y: 1182125.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502783.25
      sim_grid_pos_y: 1182117.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1502006.12
      sim_grid_pos_y: 1183151.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1501923.75
      sim_grid_pos_y: 1187132.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.50214e+06
      sim_grid_pos_y: 1187294.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1502053.38
      sim_grid_pos_y: 1187337
    }
    terrain_level_point {
      sim_grid_pos_x: 1502091.75
      sim_grid_pos_y: 1187501.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502250.25
      sim_grid_pos_y: 1187676.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.50249e+06
      sim_grid_pos_y: 1187567
    }
    terrain_level_point {
      sim_grid_pos_x: 1502647.38
      sim_grid_pos_y: 1187382.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502866.75
      sim_grid_pos_y: 1186991.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1503232.5
      sim_grid_pos_y: 1186807
    }
    terrain_level_point {
      sim_grid_pos_x: 1503665.62
      sim_grid_pos_y: 1186815.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1503920.25
      sim_grid_pos_y: 1186759.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1504255.88
      sim_grid_pos_y: 1186920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504868
      sim_grid_pos_y: 1186929
    }
    terrain_level_point {
      sim_grid_pos_x: 1505432
      sim_grid_pos_y: 1185825
    }
    terrain_level_point {
      sim_grid_pos_x: 1507120.62
      sim_grid_pos_y: 1183689.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1507632.62
      sim_grid_pos_y: 1182900.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507613
      sim_grid_pos_y: 1180555.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1505466.25
      sim_grid_pos_y: 1179571.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1505142.88
      sim_grid_pos_y: 1180142
    }
    terrain_level_point {
      sim_grid_pos_x: 1504754.12
      sim_grid_pos_y: 1181006.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1504366.5
      sim_grid_pos_y: 1181615.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502979
      sim_grid_pos_y: 1182094.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502768.38
      sim_grid_pos_y: 1182086.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1501975.5
      sim_grid_pos_y: 1183141.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1501892.75
      sim_grid_pos_y: 1187147.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1502081.62
      sim_grid_pos_y: 1187288.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502018
      sim_grid_pos_y: 1187320.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1502063.62
      sim_grid_pos_y: 1187516.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1502242.5
      sim_grid_pos_y: 1187713.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502508.88
      sim_grid_pos_y: 1187592.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1502672.62
      sim_grid_pos_y: 1.1874e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1502889
      sim_grid_pos_y: 1187014.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1503239.62
      sim_grid_pos_y: 1186837.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503668.62
      sim_grid_pos_y: 1186845.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503916.5
      sim_grid_pos_y: 1186791.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504248.62
      sim_grid_pos_y: 1186951.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1504886.75
      sim_grid_pos_y: 1.18696e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1505458.12
      sim_grid_pos_y: 1185841.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507145.62
      sim_grid_pos_y: 1183707.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1507663.5
      sim_grid_pos_y: 1182909.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507643.62
      sim_grid_pos_y: 1180535.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1505453.25
      sim_grid_pos_y: 1179532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1505115.38
      sim_grid_pos_y: 1180128
    }
    terrain_level_point {
      sim_grid_pos_x: 1504727
      sim_grid_pos_y: 1180992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1504346.38
      sim_grid_pos_y: 1181590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1502974.5
      sim_grid_pos_y: 1182063.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502753.5
      sim_grid_pos_y: 1182054.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1501945
      sim_grid_pos_y: 1183130.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1501861.62
      sim_grid_pos_y: 1187162.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502023.12
      sim_grid_pos_y: 1187283.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1501982.5
      sim_grid_pos_y: 1187303.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1502035.5
      sim_grid_pos_y: 1187530.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502234.88
      sim_grid_pos_y: 1187750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502527.88
      sim_grid_pos_y: 1187617.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502698
      sim_grid_pos_y: 1187417.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502911.25
      sim_grid_pos_y: 1187037.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503246.62
      sim_grid_pos_y: 1186868.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503671.75
      sim_grid_pos_y: 1186876.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503912.75
      sim_grid_pos_y: 1186824
    }
    terrain_level_point {
      sim_grid_pos_x: 1504241.5
      sim_grid_pos_y: 1186982
    }
    terrain_level_point {
      sim_grid_pos_x: 1504905.38
      sim_grid_pos_y: 1186991.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1505484.12
      sim_grid_pos_y: 1185858.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1507170.62
      sim_grid_pos_y: 1183725.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507694.25
      sim_grid_pos_y: 1182918.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507674.25
      sim_grid_pos_y: 1180515.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1505440.25
      sim_grid_pos_y: 1179492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1505088
      sim_grid_pos_y: 1180114.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1504699.88
      sim_grid_pos_y: 1180977.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1504326.12
      sim_grid_pos_y: 1181564.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.50297e+06
      sim_grid_pos_y: 1182032.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502738.62
      sim_grid_pos_y: 1182023.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1501914.5
      sim_grid_pos_y: 1.18312e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1501830.62
      sim_grid_pos_y: 1187177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1501964.62
      sim_grid_pos_y: 1187278
    }
    terrain_level_point {
      sim_grid_pos_x: 1501947
      sim_grid_pos_y: 1187286.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502007.38
      sim_grid_pos_y: 1187545.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1502227.12
      sim_grid_pos_y: 1187788
    }
    terrain_level_point {
      sim_grid_pos_x: 1502546.88
      sim_grid_pos_y: 1187642.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1502723.38
      sim_grid_pos_y: 1187435.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1502933.5
      sim_grid_pos_y: 1187061.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1503253.62
      sim_grid_pos_y: 1186899.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503674.75
      sim_grid_pos_y: 1186907.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1503908.88
      sim_grid_pos_y: 1186856.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1504234.25
      sim_grid_pos_y: 1187012.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1504924.12
      sim_grid_pos_y: 1187022.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1505510.12
      sim_grid_pos_y: 1185875
    }
    terrain_level_point {
      sim_grid_pos_x: 1507195.62
      sim_grid_pos_y: 1183743.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507725.12
      sim_grid_pos_y: 1182927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507704.75
      sim_grid_pos_y: 1180495.38
    }
  }
}
