terrain_level_data {
  terrain_level: 1290
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1977107.38
      sim_grid_pos_y: 1631910.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1976944.12
      sim_grid_pos_y: 1632157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977262.12
      sim_grid_pos_y: 1632406.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1977418
      sim_grid_pos_y: 1632158.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1977095.5
      sim_grid_pos_y: 1631835.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976875.25
      sim_grid_pos_y: 1632168.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1977275.25
      sim_grid_pos_y: 1632482.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1977485.75
      sim_grid_pos_y: 1632147.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1977083.75
      sim_grid_pos_y: 1.63176e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1976806.5
      sim_grid_pos_y: 1632179.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1977288.38
      sim_grid_pos_y: 1632557.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1977553.5
      sim_grid_pos_y: 1632135.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1977071.88
      sim_grid_pos_y: 1631685
    }
    terrain_level_point {
      sim_grid_pos_x: 1976737.62
      sim_grid_pos_y: 1632191.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1977301.62
      sim_grid_pos_y: 1632633.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1977621.25
      sim_grid_pos_y: 1632124.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1.97706e+06
      sim_grid_pos_y: 1631609.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1976668.88
      sim_grid_pos_y: 1632202.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1977314.75
      sim_grid_pos_y: 1632708.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977689
      sim_grid_pos_y: 1632112.75
    }
  }
}
terrain_level_data {
  terrain_level: 1195
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1977883.75
      sim_grid_pos_y: 1633176.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1978238.62
      sim_grid_pos_y: 1633309
    }
    terrain_level_point {
      sim_grid_pos_x: 1978133.62
      sim_grid_pos_y: 1633684.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1978001.5
      sim_grid_pos_y: 1633662.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1977877.5
      sim_grid_pos_y: 1633861.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977887.88
      sim_grid_pos_y: 1634019
    }
    terrain_level_point {
      sim_grid_pos_x: 1977263
      sim_grid_pos_y: 1634503.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1977080.88
      sim_grid_pos_y: 1634100.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1977272.25
      sim_grid_pos_y: 1633885.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1977491.12
      sim_grid_pos_y: 1633878.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1978300.75
      sim_grid_pos_y: 1633277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1978170.62
      sim_grid_pos_y: 1633742.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1978026.88
      sim_grid_pos_y: 1633718.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1977929.62
      sim_grid_pos_y: 1633874.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1977940.75
      sim_grid_pos_y: 1634042.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1977243
      sim_grid_pos_y: 1634583.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977020.5
      sim_grid_pos_y: 1634091.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1977248.62
      sim_grid_pos_y: 1633834.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977460.62
      sim_grid_pos_y: 1633828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1977860.5
      sim_grid_pos_y: 1633113.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1978362.75
      sim_grid_pos_y: 1633245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1978207.62
      sim_grid_pos_y: 1633801.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1978052.12
      sim_grid_pos_y: 1633775
    }
    terrain_level_point {
      sim_grid_pos_x: 1977981.88
      sim_grid_pos_y: 1633887.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1977993.75
      sim_grid_pos_y: 1634066.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1977223.12
      sim_grid_pos_y: 1634663.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1976960.12
      sim_grid_pos_y: 1634082.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977225
      sim_grid_pos_y: 1633783.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.97743e+06
      sim_grid_pos_y: 1633777.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1977837.25
      sim_grid_pos_y: 1633050.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1978424.88
      sim_grid_pos_y: 1633214.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1978244.5
      sim_grid_pos_y: 1633859.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1978077.5
      sim_grid_pos_y: 1633831.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1978034.12
      sim_grid_pos_y: 1633900.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1978046.75
      sim_grid_pos_y: 1634090.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1977203.12
      sim_grid_pos_y: 1634744.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976899.62
      sim_grid_pos_y: 1634073.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1977201.38
      sim_grid_pos_y: 1633733.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1977399.5
      sim_grid_pos_y: 1633727.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977813.88
      sim_grid_pos_y: 1632986.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1978486.88
      sim_grid_pos_y: 1633182.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1978281.5
      sim_grid_pos_y: 1633917.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1978102.88
      sim_grid_pos_y: 1633887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1978086.38
      sim_grid_pos_y: 1633914
    }
    terrain_level_point {
      sim_grid_pos_x: 1978099.62
      sim_grid_pos_y: 1634114.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1977183.25
      sim_grid_pos_y: 1634824.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976839.25
      sim_grid_pos_y: 1634064.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1977177.75
      sim_grid_pos_y: 1633682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1977368.88
      sim_grid_pos_y: 1633677.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1977790.62
      sim_grid_pos_y: 1632923.5
    }
  }
}
terrain_level_data {
  terrain_level: 690
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1975255.5
      sim_grid_pos_y: 1627045
    }
    terrain_level_point {
      sim_grid_pos_x: 1975092.75
      sim_grid_pos_y: 1627186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1975268.75
      sim_grid_pos_y: 1627363.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1975406
      sim_grid_pos_y: 1627198.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1975261
      sim_grid_pos_y: 1626904.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1974942.75
      sim_grid_pos_y: 1627181.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1975275.5
      sim_grid_pos_y: 1627515.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1975544
      sim_grid_pos_y: 1627193.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1975266.62
      sim_grid_pos_y: 1626763.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1974792.75
      sim_grid_pos_y: 1627176.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1975282.25
      sim_grid_pos_y: 1627667.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1975682.12
      sim_grid_pos_y: 1627187.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1975272.25
      sim_grid_pos_y: 1626622.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1974642.88
      sim_grid_pos_y: 1627170.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1975289
      sim_grid_pos_y: 1.62782e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1975820.12
      sim_grid_pos_y: 1627182
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1975277.75
      sim_grid_pos_y: 1626481.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1974492.88
      sim_grid_pos_y: 1627165.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1975295.75
      sim_grid_pos_y: 1627972.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1975958.12
      sim_grid_pos_y: 1627176.38
    }
  }
}
terrain_level_data {
  terrain_level: 980
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1983676.12
      sim_grid_pos_y: 1633315.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1983630.62
      sim_grid_pos_y: 1633559.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1983772.5
      sim_grid_pos_y: 1633660.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1983896.12
      sim_grid_pos_y: 1633656.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1983978.25
      sim_grid_pos_y: 1633529.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1983997.25
      sim_grid_pos_y: 1633417.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1983921.5
      sim_grid_pos_y: 1633199.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1983951.25
      sim_grid_pos_y: 1633128.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1983630.62
      sim_grid_pos_y: 1633280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1983574.25
      sim_grid_pos_y: 1633582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1983756.88
      sim_grid_pos_y: 1633712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1983924.62
      sim_grid_pos_y: 1633706.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1984027
      sim_grid_pos_y: 1633548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.98405e+06
      sim_grid_pos_y: 1633413.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1983980.88
      sim_grid_pos_y: 1633057.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1983585
      sim_grid_pos_y: 1633245.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1983517.88
      sim_grid_pos_y: 1633605
    }
    terrain_level_point {
      sim_grid_pos_x: 1983741.25
      sim_grid_pos_y: 1633764.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1983953.12
      sim_grid_pos_y: 1633757.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1984075.75
      sim_grid_pos_y: 1633567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1984102.75
      sim_grid_pos_y: 1633409
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1984010.62
      sim_grid_pos_y: 1632986.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1983539.38
      sim_grid_pos_y: 1633210.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1983461.38
      sim_grid_pos_y: 1633627.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1983725.62
      sim_grid_pos_y: 1633816.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1983981.5
      sim_grid_pos_y: 1633807.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1984124.62
      sim_grid_pos_y: 1633586.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1984155.5
      sim_grid_pos_y: 1633404.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1984040.25
      sim_grid_pos_y: 1632915.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1983493.88
      sim_grid_pos_y: 1633175.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1983405
      sim_grid_pos_y: 1633650.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.98371e+06
      sim_grid_pos_y: 1633867.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.98401e+06
      sim_grid_pos_y: 1633857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1984173.38
      sim_grid_pos_y: 1633605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1984208.25
      sim_grid_pos_y: 1633400.25
    }
  }
}
terrain_level_data {
  terrain_level: 1350
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1976244.88
      sim_grid_pos_y: 1631453.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976144.75
      sim_grid_pos_y: 1631604
    }
    terrain_level_point {
      sim_grid_pos_x: 1976269.25
      sim_grid_pos_y: 1632369.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976729.12
      sim_grid_pos_y: 1632783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1976886.12
      sim_grid_pos_y: 1632669
    }
    terrain_level_point {
      sim_grid_pos_x: 1976584.75
      sim_grid_pos_y: 1632356.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1976421.88
      sim_grid_pos_y: 1632121.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1976544.75
      sim_grid_pos_y: 1631785.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976846.88
      sim_grid_pos_y: 1631732.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976867.88
      sim_grid_pos_y: 1631616.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976767.62
      sim_grid_pos_y: 1631478.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1976218.25
      sim_grid_pos_y: 1631400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1976090.88
      sim_grid_pos_y: 1631592.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976221.5
      sim_grid_pos_y: 1632395.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976725.75
      sim_grid_pos_y: 1632849.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976963.88
      sim_grid_pos_y: 1632675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1976624.62
      sim_grid_pos_y: 1632324.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976479.12
      sim_grid_pos_y: 1632114.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1976582.75
      sim_grid_pos_y: 1631830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1976891
      sim_grid_pos_y: 1631776.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1976922.25
      sim_grid_pos_y: 1631604
    }
    terrain_level_point {
      sim_grid_pos_x: 1976794.62
      sim_grid_pos_y: 1631428.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1976191.62
      sim_grid_pos_y: 1631348.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1976037.12
      sim_grid_pos_y: 1631580.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1976173.88
      sim_grid_pos_y: 1632421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976722.25
      sim_grid_pos_y: 1632915
    }
    terrain_level_point {
      sim_grid_pos_x: 1977041.75
      sim_grid_pos_y: 1632682.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1976664.38
      sim_grid_pos_y: 1632291.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976536.38
      sim_grid_pos_y: 1632106.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1976620.75
      sim_grid_pos_y: 1631876.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976935
      sim_grid_pos_y: 1631821.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976976.5
      sim_grid_pos_y: 1631591.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976821.62
      sim_grid_pos_y: 1631378.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1976165.12
      sim_grid_pos_y: 1631295.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1975983.25
      sim_grid_pos_y: 1631569.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976126.12
      sim_grid_pos_y: 1632447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976718.88
      sim_grid_pos_y: 1632980.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1977119.5
      sim_grid_pos_y: 1632689.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1976704.12
      sim_grid_pos_y: 1632258.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1976593.62
      sim_grid_pos_y: 1632099.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976658.75
      sim_grid_pos_y: 1631921.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976979.12
      sim_grid_pos_y: 1631865.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1977030.88
      sim_grid_pos_y: 1631579.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976848.75
      sim_grid_pos_y: 1631328.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1976138.5
      sim_grid_pos_y: 1631243
    }
    terrain_level_point {
      sim_grid_pos_x: 1975929.38
      sim_grid_pos_y: 1631557.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976078.38
      sim_grid_pos_y: 1632473.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1976715.5
      sim_grid_pos_y: 1633046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1977197.25
      sim_grid_pos_y: 1632696.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976743.88
      sim_grid_pos_y: 1632226.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1976651
      sim_grid_pos_y: 1632092.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1976696.75
      sim_grid_pos_y: 1631967
    }
    terrain_level_point {
      sim_grid_pos_x: 1977023.12
      sim_grid_pos_y: 1631909.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1977085.25
      sim_grid_pos_y: 1631566.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1976875.75
      sim_grid_pos_y: 1631278.12
    }
  }
}
