terrain_level_data {
  terrain_level: 175
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1354807.12
      sim_grid_pos_y: 1598508.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1354581.75
      sim_grid_pos_y: 1598891.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354344.62
      sim_grid_pos_y: 1599235.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1354303.5
      sim_grid_pos_y: 1599444.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1354572.5
      sim_grid_pos_y: 1599765.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355219.88
      sim_grid_pos_y: 1600458.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355232.25
      sim_grid_pos_y: 1600749.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355459
      sim_grid_pos_y: 1601153.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355406
      sim_grid_pos_y: 1601195.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355521.88
      sim_grid_pos_y: 1601464.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355638.5
      sim_grid_pos_y: 1601783.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355621
      sim_grid_pos_y: 1601892.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355712.62
      sim_grid_pos_y: 1601990.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1355810.75
      sim_grid_pos_y: 1601944.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355858.38
      sim_grid_pos_y: 1601766.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355951.88
      sim_grid_pos_y: 1601619.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355987.12
      sim_grid_pos_y: 1601346.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356191.88
      sim_grid_pos_y: 1601263.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356423.12
      sim_grid_pos_y: 1601094.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356419.38
      sim_grid_pos_y: 1600219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356325.12
      sim_grid_pos_y: 1600153
    }
    terrain_level_point {
      sim_grid_pos_x: 1356207.5
      sim_grid_pos_y: 1600166
    }
    terrain_level_point {
      sim_grid_pos_x: 1356263.75
      sim_grid_pos_y: 1599982.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356143.25
      sim_grid_pos_y: 1599787
    }
    terrain_level_point {
      sim_grid_pos_x: 1356235.5
      sim_grid_pos_y: 1599683.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1356210.88
      sim_grid_pos_y: 1599567.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355966.5
      sim_grid_pos_y: 1599540.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356023.25
      sim_grid_pos_y: 1599287
    }
    terrain_level_point {
      sim_grid_pos_x: 1356571.12
      sim_grid_pos_y: 1598979.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356532.88
      sim_grid_pos_y: 1598609.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356252.88
      sim_grid_pos_y: 1598263.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355837.5
      sim_grid_pos_y: 1598052.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355650.25
      sim_grid_pos_y: 1598008.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355329.75
      sim_grid_pos_y: 1597839
    }
    terrain_level_point {
      sim_grid_pos_x: 1355167.38
      sim_grid_pos_y: 1597914.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1355330.62
      sim_grid_pos_y: 1597804.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355146
      sim_grid_pos_y: 1597890.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1354780.62
      sim_grid_pos_y: 1598492.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1354555.75
      sim_grid_pos_y: 1598875.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354315.75
      sim_grid_pos_y: 1599223.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1354270.5
      sim_grid_pos_y: 1599452.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1354549.38
      sim_grid_pos_y: 1599785.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1355189.62
      sim_grid_pos_y: 1600471.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355201.75
      sim_grid_pos_y: 1600757.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1355419.25
      sim_grid_pos_y: 1601145.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355368.38
      sim_grid_pos_y: 1601186.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355493.38
      sim_grid_pos_y: 1601476.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355606.88
      sim_grid_pos_y: 1601786.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355588.38
      sim_grid_pos_y: 1601902.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355705.5
      sim_grid_pos_y: 1602028.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355836.75
      sim_grid_pos_y: 1601966
    }
    terrain_level_point {
      sim_grid_pos_x: 1355886.88
      sim_grid_pos_y: 1601779
    }
    terrain_level_point {
      sim_grid_pos_x: 1355981.5
      sim_grid_pos_y: 1601630.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356015.38
      sim_grid_pos_y: 1601368.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356207
      sim_grid_pos_y: 1601290.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356453.88
      sim_grid_pos_y: 1.60111e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1.35645e+06
      sim_grid_pos_y: 1600203.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356333.25
      sim_grid_pos_y: 1600121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1356250.62
      sim_grid_pos_y: 1600130.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356297.25
      sim_grid_pos_y: 1599978.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356181.38
      sim_grid_pos_y: 1599790.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356268.88
      sim_grid_pos_y: 1599692.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356236.38
      sim_grid_pos_y: 1599539.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356004
      sim_grid_pos_y: 1599513.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356050.25
      sim_grid_pos_y: 1599307
    }
    terrain_level_point {
      sim_grid_pos_x: 1356603.75
      sim_grid_pos_y: 1598996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356562.5
      sim_grid_pos_y: 1598597.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1356272.75
      sim_grid_pos_y: 1598239.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355848.12
      sim_grid_pos_y: 1598023.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355661.12
      sim_grid_pos_y: 1597979.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1355331.5
      sim_grid_pos_y: 1597770.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355124.5
      sim_grid_pos_y: 1597866.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354754.25
      sim_grid_pos_y: 1598476.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1354529.88
      sim_grid_pos_y: 1598858.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1354286.75
      sim_grid_pos_y: 1599211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354237.38
      sim_grid_pos_y: 1599461.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1354526.38
      sim_grid_pos_y: 1599806
    }
    terrain_level_point {
      sim_grid_pos_x: 1355159.38
      sim_grid_pos_y: 1600483.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355171.38
      sim_grid_pos_y: 1600766.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1355379.75
      sim_grid_pos_y: 1601138
    }
    terrain_level_point {
      sim_grid_pos_x: 1355330.88
      sim_grid_pos_y: 1601176.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1355464.75
      sim_grid_pos_y: 1601487.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355575.25
      sim_grid_pos_y: 1601789.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355555.62
      sim_grid_pos_y: 1601912.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355698.25
      sim_grid_pos_y: 1602065.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355862.75
      sim_grid_pos_y: 1601987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355915.38
      sim_grid_pos_y: 1601791.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356011.12
      sim_grid_pos_y: 1601641.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356043.62
      sim_grid_pos_y: 1601390.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1356222.12
      sim_grid_pos_y: 1601317.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356484.75
      sim_grid_pos_y: 1601125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356480.75
      sim_grid_pos_y: 1600187.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356341.5
      sim_grid_pos_y: 1600089.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356293.75
      sim_grid_pos_y: 1600094.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356330.75
      sim_grid_pos_y: 1599974.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356219.62
      sim_grid_pos_y: 1599793.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356302.25
      sim_grid_pos_y: 1599701.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356261.88
      sim_grid_pos_y: 1599511.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356041.5
      sim_grid_pos_y: 1599487
    }
    terrain_level_point {
      sim_grid_pos_x: 1356077.25
      sim_grid_pos_y: 1599327.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1356636.38
      sim_grid_pos_y: 1599013.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356592.12
      sim_grid_pos_y: 1598584.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1356292.5
      sim_grid_pos_y: 1598214.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1355858.75
      sim_grid_pos_y: 1597994.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355672
      sim_grid_pos_y: 1597950.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1355332.38
      sim_grid_pos_y: 1597736.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355103.12
      sim_grid_pos_y: 1597842.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354727.88
      sim_grid_pos_y: 1598461.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1354503.88
      sim_grid_pos_y: 1598842.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354257.88
      sim_grid_pos_y: 1599199.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354204.38
      sim_grid_pos_y: 1599469.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1354503.25
      sim_grid_pos_y: 1599826.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355129.12
      sim_grid_pos_y: 1600496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355141
      sim_grid_pos_y: 1600775.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.35534e+06
      sim_grid_pos_y: 1601130.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355293.25
      sim_grid_pos_y: 1601167.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355436.12
      sim_grid_pos_y: 1601499
    }
    terrain_level_point {
      sim_grid_pos_x: 1355543.62
      sim_grid_pos_y: 1601792.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355522.88
      sim_grid_pos_y: 1601922
    }
    terrain_level_point {
      sim_grid_pos_x: 1355691
      sim_grid_pos_y: 1602103.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355888.75
      sim_grid_pos_y: 1602009.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355943.75
      sim_grid_pos_y: 1601804.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1356040.75
      sim_grid_pos_y: 1601652
    }
    terrain_level_point {
      sim_grid_pos_x: 1356071.75
      sim_grid_pos_y: 1601411.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1356237.12
      sim_grid_pos_y: 1601344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356515.5
      sim_grid_pos_y: 1601141.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1356511.38
      sim_grid_pos_y: 1600171.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356349.75
      sim_grid_pos_y: 1600057.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356336.88
      sim_grid_pos_y: 1600058.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1356364.12
      sim_grid_pos_y: 1599969.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1356257.88
      sim_grid_pos_y: 1599797.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356335.5
      sim_grid_pos_y: 1599710.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356287.25
      sim_grid_pos_y: 1599483.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356079
      sim_grid_pos_y: 1599460.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356104.25
      sim_grid_pos_y: 1599347.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356669.12
      sim_grid_pos_y: 1599030.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356621.88
      sim_grid_pos_y: 1598572.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356312.25
      sim_grid_pos_y: 1598190.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355869.38
      sim_grid_pos_y: 1597965
    }
    terrain_level_point {
      sim_grid_pos_x: 1355682.88
      sim_grid_pos_y: 1597921.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1355333.25
      sim_grid_pos_y: 1597701.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355081.62
      sim_grid_pos_y: 1597818.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354701.5
      sim_grid_pos_y: 1598445.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354477.88
      sim_grid_pos_y: 1598825.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1354228.88
      sim_grid_pos_y: 1599187
    }
    terrain_level_point {
      sim_grid_pos_x: 1354171.38
      sim_grid_pos_y: 1599478.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1354480.25
      sim_grid_pos_y: 1599846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355098.88
      sim_grid_pos_y: 1600509.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355110.5
      sim_grid_pos_y: 1600783.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1355300.38
      sim_grid_pos_y: 1601122.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355255.75
      sim_grid_pos_y: 1601158
    }
    terrain_level_point {
      sim_grid_pos_x: 1355407.62
      sim_grid_pos_y: 1601510.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355512
      sim_grid_pos_y: 1601795.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1355490.12
      sim_grid_pos_y: 1601931.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1355683.88
      sim_grid_pos_y: 1602140.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355914.75
      sim_grid_pos_y: 1602031.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1355972.25
      sim_grid_pos_y: 1601816.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356070.38
      sim_grid_pos_y: 1601662.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.3561e+06
      sim_grid_pos_y: 1601433.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356252.25
      sim_grid_pos_y: 1601371.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356546.38
      sim_grid_pos_y: 1601156.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356542.12
      sim_grid_pos_y: 1600155.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356375.5
      sim_grid_pos_y: 1600038
    }
    terrain_level_point {
      sim_grid_pos_x: 1356397.62
      sim_grid_pos_y: 1599965.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356296.12
      sim_grid_pos_y: 1599800.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1356368.88
      sim_grid_pos_y: 1599719.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356312.75
      sim_grid_pos_y: 1599455.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356116.5
      sim_grid_pos_y: 1599433.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356131.38
      sim_grid_pos_y: 1599367.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356701.75
      sim_grid_pos_y: 1599047.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1356651.5
      sim_grid_pos_y: 1598560.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356332
      sim_grid_pos_y: 1598166
    }
    terrain_level_point {
      sim_grid_pos_x: 1355880.12
      sim_grid_pos_y: 1597936
    }
    terrain_level_point {
      sim_grid_pos_x: 1355693.75
      sim_grid_pos_y: 1597892
    }
  }
}
