terrain_level_data {
  terrain_level: 995
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1161221.5
      sim_grid_pos_y: 1584622.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1161376.12
      sim_grid_pos_y: 1584917.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161228.5
      sim_grid_pos_y: 1585029.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161203.88
      sim_grid_pos_y: 1585360.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1161119.5
      sim_grid_pos_y: 1585431.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1161166.62
      sim_grid_pos_y: 1585500.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1161506.62
      sim_grid_pos_y: 1585305.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161704.12
      sim_grid_pos_y: 1585120.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1161715
      sim_grid_pos_y: 1584862
    }
    terrain_level_point {
      sim_grid_pos_x: 1161841.5
      sim_grid_pos_y: 1584843
    }
    terrain_level_point {
      sim_grid_pos_x: 1161959.62
      sim_grid_pos_y: 1.58471e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1161725.75
      sim_grid_pos_y: 1584685
    }
    terrain_level_point {
      sim_grid_pos_x: 1161517.62
      sim_grid_pos_y: 1584678.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161328.75
      sim_grid_pos_y: 1584376.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1161286.88
      sim_grid_pos_y: 1584133
    }
    terrain_level_point {
      sim_grid_pos_x: 1161226.62
      sim_grid_pos_y: 1584033.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161132.38
      sim_grid_pos_y: 1584048.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1161134.38
      sim_grid_pos_y: 1584197
    }
    terrain_level_point {
      sim_grid_pos_x: 1161103.62
      sim_grid_pos_y: 1584387.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1161278.75
      sim_grid_pos_y: 1583921
    }
    terrain_level_point {
      sim_grid_pos_x: 1161028.75
      sim_grid_pos_y: 1583961.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161031.75
      sim_grid_pos_y: 1584189.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1160997.12
      sim_grid_pos_y: 1584403.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1161130.25
      sim_grid_pos_y: 1584669.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1161245.12
      sim_grid_pos_y: 1584888.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161129.75
      sim_grid_pos_y: 1584976.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1161104.88
      sim_grid_pos_y: 1585309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1160982.88
      sim_grid_pos_y: 1585411.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161135
      sim_grid_pos_y: 1585637.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161568.12
      sim_grid_pos_y: 1585388.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161804.88
      sim_grid_pos_y: 1585166.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1161813.88
      sim_grid_pos_y: 1584950.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161893.62
      sim_grid_pos_y: 1584938.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1162077.75
      sim_grid_pos_y: 1584731.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1162032.62
      sim_grid_pos_y: 1584614.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1161732.62
      sim_grid_pos_y: 1584582.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1161575.5
      sim_grid_pos_y: 1584578
    }
    terrain_level_point {
      sim_grid_pos_x: 1161426.38
      sim_grid_pos_y: 1584339.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1161384.62
      sim_grid_pos_y: 1584096.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1161330.75
      sim_grid_pos_y: 1583808.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1160925
      sim_grid_pos_y: 1583874
    }
    terrain_level_point {
      sim_grid_pos_x: 1160929.12
      sim_grid_pos_y: 1584182
    }
    terrain_level_point {
      sim_grid_pos_x: 1160890.62
      sim_grid_pos_y: 1584420.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1161039
      sim_grid_pos_y: 1584716.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161114.12
      sim_grid_pos_y: 1584859.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161030.88
      sim_grid_pos_y: 1584922.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161005.88
      sim_grid_pos_y: 1585258.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1160846.25
      sim_grid_pos_y: 1585392.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1161103.38
      sim_grid_pos_y: 1585773.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1161629.5
      sim_grid_pos_y: 1585471.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161905.62
      sim_grid_pos_y: 1585212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1161912.75
      sim_grid_pos_y: 1585039.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1161945.62
      sim_grid_pos_y: 1585034.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1162196
      sim_grid_pos_y: 1584752.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1162105.62
      sim_grid_pos_y: 1584519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161739.62
      sim_grid_pos_y: 1584480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161633.38
      sim_grid_pos_y: 1584477.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161524
      sim_grid_pos_y: 1584302.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1161482.38
      sim_grid_pos_y: 1584060.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1161382.75
      sim_grid_pos_y: 1583696.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1160821.38
      sim_grid_pos_y: 1583786.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1160826.5
      sim_grid_pos_y: 1584174.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1160784.12
      sim_grid_pos_y: 1584436.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1160947.75
      sim_grid_pos_y: 1584763
    }
    terrain_level_point {
      sim_grid_pos_x: 1160983.12
      sim_grid_pos_y: 1584830.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1160932
      sim_grid_pos_y: 1584869.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1160906.88
      sim_grid_pos_y: 1585208
    }
    terrain_level_point {
      sim_grid_pos_x: 1160709.62
      sim_grid_pos_y: 1585373.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1161071.75
      sim_grid_pos_y: 1585910.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1161690.88
      sim_grid_pos_y: 1585554.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1162006.25
      sim_grid_pos_y: 1585258.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1162012.25
      sim_grid_pos_y: 1585114
    }
    terrain_level_point {
      sim_grid_pos_x: 1162314.12
      sim_grid_pos_y: 1584773.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1162178.62
      sim_grid_pos_y: 1584424
    }
    terrain_level_point {
      sim_grid_pos_x: 1161746.5
      sim_grid_pos_y: 1584377.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161691.25
      sim_grid_pos_y: 1584376.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1161621.62
      sim_grid_pos_y: 1584264.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161580.12
      sim_grid_pos_y: 1584023.75
    }
  }
}
