terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2149340.5
      sim_grid_pos_y: 1691861.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2147220.25
      sim_grid_pos_y: 1689455
    }
    terrain_level_point {
      sim_grid_pos_x: 2149761.5
      sim_grid_pos_y: 1688166.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2151572
      sim_grid_pos_y: 1687453
    }
    terrain_level_point {
      sim_grid_pos_x: 2.15198e+06
      sim_grid_pos_y: 1687847.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2152112.25
      sim_grid_pos_y: 1687833
    }
    terrain_level_point {
      sim_grid_pos_x: 2149352.25
      sim_grid_pos_y: 1.69203e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2147055.75
      sim_grid_pos_y: 1689423.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2149719.5
      sim_grid_pos_y: 1688072.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2151596
      sim_grid_pos_y: 1687333.38
    }
  }
}
