terrain_level_data {
  terrain_level: 1572
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 788439.812
      sim_grid_pos_y: 1892084.62
    }
    terrain_level_point {
      sim_grid_pos_x: 787743.438
      sim_grid_pos_y: 1892864.12
    }
    terrain_level_point {
      sim_grid_pos_x: 787283.125
      sim_grid_pos_y: 1893262.5
    }
    terrain_level_point {
      sim_grid_pos_x: 786873.75
      sim_grid_pos_y: 1893571.5
    }
    terrain_level_point {
      sim_grid_pos_x: 786910.188
      sim_grid_pos_y: 1893746.62
    }
    terrain_level_point {
      sim_grid_pos_x: 786195.688
      sim_grid_pos_y: 1893771.38
    }
    terrain_level_point {
      sim_grid_pos_x: 785130.125
      sim_grid_pos_y: 1893868.75
    }
    terrain_level_point {
      sim_grid_pos_x: 785345.25
      sim_grid_pos_y: 1894417.62
    }
    terrain_level_point {
      sim_grid_pos_x: 785288.688
      sim_grid_pos_y: 1894697.12
    }
    terrain_level_point {
      sim_grid_pos_x: 784625.312
      sim_grid_pos_y: 1895226.75
    }
    terrain_level_point {
      sim_grid_pos_x: 784877.438
      sim_grid_pos_y: 1895319
    }
    terrain_level_point {
      sim_grid_pos_x: 785489.938
      sim_grid_pos_y: 1894847.88
    }
    terrain_level_point {
      sim_grid_pos_x: 785569.25
      sim_grid_pos_y: 1895068.62
    }
    terrain_level_point {
      sim_grid_pos_x: 786237.938
      sim_grid_pos_y: 1895089
    }
    terrain_level_point {
      sim_grid_pos_x: 786923.75
      sim_grid_pos_y: 1894987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 787644.375
      sim_grid_pos_y: 1894636.5
    }
    terrain_level_point {
      sim_grid_pos_x: 788521
      sim_grid_pos_y: 1894664.5
    }
    terrain_level_point {
      sim_grid_pos_x: 789177.312
      sim_grid_pos_y: 1894504.12
    }
    terrain_level_point {
      sim_grid_pos_x: 789334.938
      sim_grid_pos_y: 1893910.5
    }
    terrain_level_point {
      sim_grid_pos_x: 789620.312
      sim_grid_pos_y: 1893486
    }
    terrain_level_point {
      sim_grid_pos_x: 789907.438
      sim_grid_pos_y: 1892735.12
    }
    terrain_level_point {
      sim_grid_pos_x: 789369.75
      sim_grid_pos_y: 1891961.88
    }
    terrain_level_point {
      sim_grid_pos_x: 788924.188
      sim_grid_pos_y: 1891711
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 788915.375
      sim_grid_pos_y: 1891588.38
    }
    terrain_level_point {
      sim_grid_pos_x: 788369.688
      sim_grid_pos_y: 1892009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 787671.312
      sim_grid_pos_y: 1892790.88
    }
    terrain_level_point {
      sim_grid_pos_x: 787218.625
      sim_grid_pos_y: 1893182.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786760.125
      sim_grid_pos_y: 1893528.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786785.062
      sim_grid_pos_y: 1893648.38
    }
    terrain_level_point {
      sim_grid_pos_x: 786189.25
      sim_grid_pos_y: 1893669
    }
    terrain_level_point {
      sim_grid_pos_x: 784984.875
      sim_grid_pos_y: 1893779.12
    }
    terrain_level_point {
      sim_grid_pos_x: 785238.75
      sim_grid_pos_y: 1894426.88
    }
    terrain_level_point {
      sim_grid_pos_x: 785195.562
      sim_grid_pos_y: 1894640.25
    }
    terrain_level_point {
      sim_grid_pos_x: 784514.5
      sim_grid_pos_y: 1895184
    }
    terrain_level_point {
      sim_grid_pos_x: 784533.75
      sim_grid_pos_y: 1895302.38
    }
    terrain_level_point {
      sim_grid_pos_x: 784895.188
      sim_grid_pos_y: 1895434.62
    }
    terrain_level_point {
      sim_grid_pos_x: 785441
      sim_grid_pos_y: 1895014.88
    }
    terrain_level_point {
      sim_grid_pos_x: 785496.375
      sim_grid_pos_y: 1895169
    }
    terrain_level_point {
      sim_grid_pos_x: 786243.875
      sim_grid_pos_y: 1895191.75
    }
    terrain_level_point {
      sim_grid_pos_x: 786954.438
      sim_grid_pos_y: 1895086.88
    }
    terrain_level_point {
      sim_grid_pos_x: 787666.5
      sim_grid_pos_y: 1894739.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788531.75
      sim_grid_pos_y: 1894767.38
    }
    terrain_level_point {
      sim_grid_pos_x: 789260.812
      sim_grid_pos_y: 1894589.25
    }
    terrain_level_point {
      sim_grid_pos_x: 789429.625
      sim_grid_pos_y: 1893953.5
    }
    terrain_level_point {
      sim_grid_pos_x: 789711.938
      sim_grid_pos_y: 1893533.5
    }
    terrain_level_point {
      sim_grid_pos_x: 790022.562
      sim_grid_pos_y: 1892721.12
    }
    terrain_level_point {
      sim_grid_pos_x: 789440.5
      sim_grid_pos_y: 1891884
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 788906.5
      sim_grid_pos_y: 1891465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 788299.562
      sim_grid_pos_y: 1891933.88
    }
    terrain_level_point {
      sim_grid_pos_x: 787599.25
      sim_grid_pos_y: 1892717.75
    }
    terrain_level_point {
      sim_grid_pos_x: 787154.188
      sim_grid_pos_y: 1893102.88
    }
    terrain_level_point {
      sim_grid_pos_x: 786646.562
      sim_grid_pos_y: 1893486.12
    }
    terrain_level_point {
      sim_grid_pos_x: 786659.875
      sim_grid_pos_y: 1893550.12
    }
    terrain_level_point {
      sim_grid_pos_x: 786182.812
      sim_grid_pos_y: 1893566.62
    }
    terrain_level_point {
      sim_grid_pos_x: 784839.562
      sim_grid_pos_y: 1893689.38
    }
    terrain_level_point {
      sim_grid_pos_x: 785132.312
      sim_grid_pos_y: 1894436.12
    }
    terrain_level_point {
      sim_grid_pos_x: 785102.5
      sim_grid_pos_y: 1894583.38
    }
    terrain_level_point {
      sim_grid_pos_x: 784403.625
      sim_grid_pos_y: 1895141.38
    }
    terrain_level_point {
      sim_grid_pos_x: 784442.188
      sim_grid_pos_y: 1895378.12
    }
    terrain_level_point {
      sim_grid_pos_x: 784913
      sim_grid_pos_y: 1895550.38
    }
    terrain_level_point {
      sim_grid_pos_x: 785392.062
      sim_grid_pos_y: 1895181.88
    }
    terrain_level_point {
      sim_grid_pos_x: 785423.5
      sim_grid_pos_y: 1895269.38
    }
    terrain_level_point {
      sim_grid_pos_x: 786249.875
      sim_grid_pos_y: 1895294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 786985.062
      sim_grid_pos_y: 1895186
    }
    terrain_level_point {
      sim_grid_pos_x: 787688.562
      sim_grid_pos_y: 1894843.12
    }
    terrain_level_point {
      sim_grid_pos_x: 788542.438
      sim_grid_pos_y: 1894870.38
    }
    terrain_level_point {
      sim_grid_pos_x: 789344.25
      sim_grid_pos_y: 1894674.38
    }
    terrain_level_point {
      sim_grid_pos_x: 789524.312
      sim_grid_pos_y: 1893996.38
    }
    terrain_level_point {
      sim_grid_pos_x: 789803.5
      sim_grid_pos_y: 1893581
    }
    terrain_level_point {
      sim_grid_pos_x: 790137.688
      sim_grid_pos_y: 1892707.12
    }
    terrain_level_point {
      sim_grid_pos_x: 789511.25
      sim_grid_pos_y: 1891806.25
    }
  }
}
