terrain_level_data {
  terrain_level: 225
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2052437.62
      sim_grid_pos_y: 1240741.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052514
      sim_grid_pos_y: 1240811.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052669.75
      sim_grid_pos_y: 1240814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2052714
      sim_grid_pos_y: 1240736.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052717.88
      sim_grid_pos_y: 1240618.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052655.62
      sim_grid_pos_y: 1240537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2052508.38
      sim_grid_pos_y: 1240528
    }
    terrain_level_point {
      sim_grid_pos_x: 2052434.88
      sim_grid_pos_y: 1240598
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2052489.38
      sim_grid_pos_y: 1240475.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052383.12
      sim_grid_pos_y: 1240576.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052386.75
      sim_grid_pos_y: 1240764.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052493.62
      sim_grid_pos_y: 1240862.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052699.25
      sim_grid_pos_y: 1240866.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052764.88
      sim_grid_pos_y: 1240751
    }
    terrain_level_point {
      sim_grid_pos_x: 2052769.75
      sim_grid_pos_y: 1240601.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052682.12
      sim_grid_pos_y: 1240488.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2052470.25
      sim_grid_pos_y: 1240422.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2052331.5
      sim_grid_pos_y: 1240554.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052336
      sim_grid_pos_y: 1240787.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052473.25
      sim_grid_pos_y: 1240913.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052728.75
      sim_grid_pos_y: 1240918.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052815.62
      sim_grid_pos_y: 1240765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052821.5
      sim_grid_pos_y: 1240584.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052708.5
      sim_grid_pos_y: 1240438.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2052451.12
      sim_grid_pos_y: 1240370.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052279.88
      sim_grid_pos_y: 1240533.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052285.12
      sim_grid_pos_y: 1.24081e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2052452.88
      sim_grid_pos_y: 1240964
    }
    terrain_level_point {
      sim_grid_pos_x: 2052758.25
      sim_grid_pos_y: 1240970.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052866.5
      sim_grid_pos_y: 1240779.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052873.38
      sim_grid_pos_y: 1240568.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052735
      sim_grid_pos_y: 1240388.88
    }
  }
}
terrain_level_data {
  terrain_level: 250
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2045059.25
      sim_grid_pos_y: 1245960.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2045742
      sim_grid_pos_y: 1245838.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2046069.25
      sim_grid_pos_y: 1245874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046308.25
      sim_grid_pos_y: 1245577.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.04609e+06
      sim_grid_pos_y: 1245276
    }
    terrain_level_point {
      sim_grid_pos_x: 2045797.5
      sim_grid_pos_y: 1245293.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2045136.25
      sim_grid_pos_y: 1245614.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2046115
      sim_grid_pos_y: 1245223.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2045784.25
      sim_grid_pos_y: 1245243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2045091.62
      sim_grid_pos_y: 1245578.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2044992.5
      sim_grid_pos_y: 1246024.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2045743.75
      sim_grid_pos_y: 1245890.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046091.62
      sim_grid_pos_y: 1245928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046372.75
      sim_grid_pos_y: 1245579.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2.04614e+06
      sim_grid_pos_y: 1245170.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2045771
      sim_grid_pos_y: 1245192.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2045046.88
      sim_grid_pos_y: 1245543.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2044925.75
      sim_grid_pos_y: 1246088.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2045745.5
      sim_grid_pos_y: 1245942.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2046113.88
      sim_grid_pos_y: 1245982.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046437.25
      sim_grid_pos_y: 1245581
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2046165
      sim_grid_pos_y: 1245117.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2045757.88
      sim_grid_pos_y: 1245142.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2045002.25
      sim_grid_pos_y: 1245508.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2044859
      sim_grid_pos_y: 1246152.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2045747.25
      sim_grid_pos_y: 1245994
    }
    terrain_level_point {
      sim_grid_pos_x: 2046136.25
      sim_grid_pos_y: 1246036.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046501.62
      sim_grid_pos_y: 1245582.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2046290.12
      sim_grid_pos_y: 1244853
    }
    terrain_level_point {
      sim_grid_pos_x: 2045691.62
      sim_grid_pos_y: 1244889.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2044778.88
      sim_grid_pos_y: 1245331.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2044525.5
      sim_grid_pos_y: 1246472.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2045756
      sim_grid_pos_y: 1246252.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2046247.88
      sim_grid_pos_y: 1246306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046824
      sim_grid_pos_y: 1245591
    }
  }
}
terrain_level_data {
  terrain_level: 230
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2052772.5
      sim_grid_pos_y: 1240229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2052773.12
      sim_grid_pos_y: 1240419.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052874.25
      sim_grid_pos_y: 1240509
    }
    terrain_level_point {
      sim_grid_pos_x: 2053002.88
      sim_grid_pos_y: 1240508.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2053097.25
      sim_grid_pos_y: 1240444
    }
    terrain_level_point {
      sim_grid_pos_x: 2053091.12
      sim_grid_pos_y: 1240256.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052999.12
      sim_grid_pos_y: 1240156.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052863.38
      sim_grid_pos_y: 1240152.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2052845.25
      sim_grid_pos_y: 1240100.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052721.12
      sim_grid_pos_y: 1240205.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052721.88
      sim_grid_pos_y: 1240442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2052854.88
      sim_grid_pos_y: 1240560.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2053018.88
      sim_grid_pos_y: 1240560.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2053149.38
      sim_grid_pos_y: 1240470.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2053141.75
      sim_grid_pos_y: 1240235.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2053022.25
      sim_grid_pos_y: 1240105.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2052827
      sim_grid_pos_y: 1240048.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052669.88
      sim_grid_pos_y: 1240182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052670.75
      sim_grid_pos_y: 1240465.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052835.38
      sim_grid_pos_y: 1240611.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2053034.75
      sim_grid_pos_y: 1240611.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2053201.5
      sim_grid_pos_y: 1240496.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2053192.38
      sim_grid_pos_y: 1240214.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2053045.25
      sim_grid_pos_y: 1240055.25
    }
  }
}
terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2054564.12
      sim_grid_pos_y: 1242503.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2053972
      sim_grid_pos_y: 1241937.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2052846.75
      sim_grid_pos_y: 1242313.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2053626.12
      sim_grid_pos_y: 1242982.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2054105.62
      sim_grid_pos_y: 1243197.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2053985.12
      sim_grid_pos_y: 1241879.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052802.12
      sim_grid_pos_y: 1242274.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2052790.75
      sim_grid_pos_y: 1242333
    }
    terrain_level_point {
      sim_grid_pos_x: 2053598.38
      sim_grid_pos_y: 1243026.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2054124.38
      sim_grid_pos_y: 1243262.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2054630.5
      sim_grid_pos_y: 1242495.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2053998.12
      sim_grid_pos_y: 1241820.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052757.62
      sim_grid_pos_y: 1242235.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2052734.62
      sim_grid_pos_y: 1242352.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2053570.62
      sim_grid_pos_y: 1243070.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2054143.12
      sim_grid_pos_y: 1243327.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2054696.88
      sim_grid_pos_y: 1242488.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2054011.25
      sim_grid_pos_y: 1241762.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052713
      sim_grid_pos_y: 1242196
    }
    terrain_level_point {
      sim_grid_pos_x: 2052678.62
      sim_grid_pos_y: 1242371.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2053542.88
      sim_grid_pos_y: 1243113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2054161.88
      sim_grid_pos_y: 1243391.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2054763.25
      sim_grid_pos_y: 1242480.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2054024.25
      sim_grid_pos_y: 1241703.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052668.5
      sim_grid_pos_y: 1242156.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052622.62
      sim_grid_pos_y: 1242391.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2053515.12
      sim_grid_pos_y: 1243157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2054180.75
      sim_grid_pos_y: 1243456.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2054829.62
      sim_grid_pos_y: 1242473.5
    }
  }
}
terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2052820.75
      sim_grid_pos_y: 1.24228e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2053954.12
      sim_grid_pos_y: 1243103.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2052599
      sim_grid_pos_y: 1244643.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2051756.88
      sim_grid_pos_y: 1246082.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046174.62
      sim_grid_pos_y: 1250392.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2045757.5
      sim_grid_pos_y: 1249924.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2054029.75
      sim_grid_pos_y: 1243095.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2052640.75
      sim_grid_pos_y: 1244673.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2051796.12
      sim_grid_pos_y: 1246117
    }
    terrain_level_point {
      sim_grid_pos_x: 2046168.12
      sim_grid_pos_y: 1250462.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2045688.25
      sim_grid_pos_y: 1249923.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2052814
      sim_grid_pos_y: 1242211.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2054105.5
      sim_grid_pos_y: 1243086.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052682.5
      sim_grid_pos_y: 1244703.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2051835.25
      sim_grid_pos_y: 1246151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2046161.62
      sim_grid_pos_y: 1250532
    }
    terrain_level_point {
      sim_grid_pos_x: 2045619.12
      sim_grid_pos_y: 1249922.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2052807.25
      sim_grid_pos_y: 1242143.5
    }
  }
}
