terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2169260.75
      sim_grid_pos_y: 1715011.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2168094.25
      sim_grid_pos_y: 1716843.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2167899.75
      sim_grid_pos_y: 1717683.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2167397.25
      sim_grid_pos_y: 1717860.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2166444.5
      sim_grid_pos_y: 1717457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2165887.5
      sim_grid_pos_y: 1717150.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2165921.75
      sim_grid_pos_y: 1714665.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.16582e+06
      sim_grid_pos_y: 1714317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2166831
      sim_grid_pos_y: 1.71279e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2168634
      sim_grid_pos_y: 1714004.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2169432
      sim_grid_pos_y: 1714700.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2168652.75
      sim_grid_pos_y: 1713980.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2169471
      sim_grid_pos_y: 1714693.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2169287.25
      sim_grid_pos_y: 1715027
    }
    terrain_level_point {
      sim_grid_pos_x: 2168123
      sim_grid_pos_y: 1716855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2167926
      sim_grid_pos_y: 1717706.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2167396.25
      sim_grid_pos_y: 1717893.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2166431
      sim_grid_pos_y: 1717485.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2165856.5
      sim_grid_pos_y: 1717168.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2165891
      sim_grid_pos_y: 1714670.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2165786.5
      sim_grid_pos_y: 1714312.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2166822.5
      sim_grid_pos_y: 1712747.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2168671.5
      sim_grid_pos_y: 1713955.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.16951e+06
      sim_grid_pos_y: 1714686.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2169313.75
      sim_grid_pos_y: 1715042.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2168151.75
      sim_grid_pos_y: 1716867.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2167952
      sim_grid_pos_y: 1717729.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2167395.25
      sim_grid_pos_y: 1717926.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2166417.5
      sim_grid_pos_y: 1717513.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2165825.5
      sim_grid_pos_y: 1717186.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2165860.25
      sim_grid_pos_y: 1714674.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2165753
      sim_grid_pos_y: 1714307.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2166813.75
      sim_grid_pos_y: 1712704.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2168690.25
      sim_grid_pos_y: 1713931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2169548.75
      sim_grid_pos_y: 1714679.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.16934e+06
      sim_grid_pos_y: 1715058.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2168180.75
      sim_grid_pos_y: 1716879.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2167978.25
      sim_grid_pos_y: 1717753.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2167394.25
      sim_grid_pos_y: 1717959.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2166404.25
      sim_grid_pos_y: 1717540.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2165794.5
      sim_grid_pos_y: 1717204.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2165829.5
      sim_grid_pos_y: 1714678.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2165719.5
      sim_grid_pos_y: 1714302.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2166805.25
      sim_grid_pos_y: 1712661.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2168709
      sim_grid_pos_y: 1713907
    }
    terrain_level_point {
      sim_grid_pos_x: 2169587.75
      sim_grid_pos_y: 1714672.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2169366.5
      sim_grid_pos_y: 1715074.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2168209.5
      sim_grid_pos_y: 1716891.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2168004.25
      sim_grid_pos_y: 1717776.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2167393.5
      sim_grid_pos_y: 1717992.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2166390.75
      sim_grid_pos_y: 1717568.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2165763.5
      sim_grid_pos_y: 1717222.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2165798.5
      sim_grid_pos_y: 1714682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2165686
      sim_grid_pos_y: 1714297.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2166796.75
      sim_grid_pos_y: 1712618.62
    }
  }
}
