terrain_level_data {
  terrain_level: 4592
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2465881.5
      sim_grid_pos_y: 1876876.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466155.5
      sim_grid_pos_y: 1876841.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2466421.75
      sim_grid_pos_y: 1876404.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2466306
      sim_grid_pos_y: 1876023.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466026
      sim_grid_pos_y: 1875992
    }
    terrain_level_point {
      sim_grid_pos_x: 2466015.5
      sim_grid_pos_y: 1876191.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2465767.5
      sim_grid_pos_y: 1876643.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2465929.25
      sim_grid_pos_y: 1875878
    }
    terrain_level_point {
      sim_grid_pos_x: 2465914.25
      sim_grid_pos_y: 1876162.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2465652
      sim_grid_pos_y: 1876640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2465821.5
      sim_grid_pos_y: 1876987.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466217.5
      sim_grid_pos_y: 1876937.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466533.25
      sim_grid_pos_y: 1876418.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466384.5
      sim_grid_pos_y: 1875929
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2465832.75
      sim_grid_pos_y: 1875764
    }
    terrain_level_point {
      sim_grid_pos_x: 2465813.25
      sim_grid_pos_y: 1876133.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2465536.5
      sim_grid_pos_y: 1876638.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2465761.75
      sim_grid_pos_y: 1877098.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466279.25
      sim_grid_pos_y: 1877032.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2466644.75
      sim_grid_pos_y: 1876432.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466463
      sim_grid_pos_y: 1875834.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2465736
      sim_grid_pos_y: 1.87565e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2465712
      sim_grid_pos_y: 1876105
    }
    terrain_level_point {
      sim_grid_pos_x: 2465421
      sim_grid_pos_y: 1876635.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2465701.75
      sim_grid_pos_y: 1877209.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2466341.25
      sim_grid_pos_y: 1877128.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466756
      sim_grid_pos_y: 1876446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466541.5
      sim_grid_pos_y: 1875740.25
    }
  }
}
terrain_level_data {
  terrain_level: 4606
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2465578.75
      sim_grid_pos_y: 1877377.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2465912
      sim_grid_pos_y: 1876998.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.46572e+06
      sim_grid_pos_y: 1876804.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2465425
      sim_grid_pos_y: 1877240.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2465715.5
      sim_grid_pos_y: 1876756.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2465384.5
      sim_grid_pos_y: 1877245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2465581.5
      sim_grid_pos_y: 1877421.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2465954
      sim_grid_pos_y: 1876997
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2465711
      sim_grid_pos_y: 1876708.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2465344
      sim_grid_pos_y: 1877250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2465584
      sim_grid_pos_y: 1877464.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2465996
      sim_grid_pos_y: 1876995.75
    }
  }
}
terrain_level_data {
  terrain_level: 4648
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2464459
      sim_grid_pos_y: 1878343.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2464667.75
      sim_grid_pos_y: 1878261
    }
    terrain_level_point {
      sim_grid_pos_x: 2464893.25
      sim_grid_pos_y: 1878217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2464762.75
      sim_grid_pos_y: 1878464.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2464583.25
      sim_grid_pos_y: 1878610.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2464383.5
      sim_grid_pos_y: 1878531.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2464929.5
      sim_grid_pos_y: 1878214.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2464787
      sim_grid_pos_y: 1878484.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2464588.75
      sim_grid_pos_y: 1878646
    }
    terrain_level_point {
      sim_grid_pos_x: 2464343.5
      sim_grid_pos_y: 1878548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2464435.5
      sim_grid_pos_y: 1878320.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2464659
      sim_grid_pos_y: 1878231.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2464906.5
      sim_grid_pos_y: 1878183.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2464965.75
      sim_grid_pos_y: 1878212
    }
    terrain_level_point {
      sim_grid_pos_x: 2464811.25
      sim_grid_pos_y: 1878504
    }
    terrain_level_point {
      sim_grid_pos_x: 2464594
      sim_grid_pos_y: 1878681.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2464303.25
      sim_grid_pos_y: 1878565.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2464411.75
      sim_grid_pos_y: 1878296.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2464650.25
      sim_grid_pos_y: 1878201.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2464919.5
      sim_grid_pos_y: 1878149.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2465002
      sim_grid_pos_y: 1878209.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2464835.5
      sim_grid_pos_y: 1878523.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2464599.5
      sim_grid_pos_y: 1878716.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2464263.25
      sim_grid_pos_y: 1878582.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2464388.25
      sim_grid_pos_y: 1878272.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2464641.75
      sim_grid_pos_y: 1878172.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2464932.75
      sim_grid_pos_y: 1878115.88
    }
  }
}
terrain_level_data {
  terrain_level: 4468
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2464788.75
      sim_grid_pos_y: 1877483.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2464394.25
      sim_grid_pos_y: 1877821.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2464570.75
      sim_grid_pos_y: 1877929
    }
    terrain_level_point {
      sim_grid_pos_x: 2464847.75
      sim_grid_pos_y: 1877661.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2464803.5
      sim_grid_pos_y: 1877430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2464342.25
      sim_grid_pos_y: 1877825.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2464575
      sim_grid_pos_y: 1877967.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2464883
      sim_grid_pos_y: 1877669.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2464818.25
      sim_grid_pos_y: 1877377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.46429e+06
      sim_grid_pos_y: 1877829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2464579.25
      sim_grid_pos_y: 1878006.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2464918.5
      sim_grid_pos_y: 1877678.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2464833
      sim_grid_pos_y: 1877324.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2464237.75
      sim_grid_pos_y: 1877833.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2464583.5
      sim_grid_pos_y: 1878045
    }
    terrain_level_point {
      sim_grid_pos_x: 2464953.75
      sim_grid_pos_y: 1877687.12
    }
  }
}
terrain_level_data {
  terrain_level: 4700
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2462623.75
      sim_grid_pos_y: 1880919.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.46262e+06
      sim_grid_pos_y: 1881178.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2462821
      sim_grid_pos_y: 1881170.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2462826
      sim_grid_pos_y: 1880923.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2462573.25
      sim_grid_pos_y: 1880867.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2462567.75
      sim_grid_pos_y: 1881232.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2462871.5
      sim_grid_pos_y: 1881219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2462878.25
      sim_grid_pos_y: 1880873.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2462522.75
      sim_grid_pos_y: 1880814.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2462515.75
      sim_grid_pos_y: 1881286
    }
    terrain_level_point {
      sim_grid_pos_x: 2462921.75
      sim_grid_pos_y: 1881268.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2462930.5
      sim_grid_pos_y: 1880823.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2462472.5
      sim_grid_pos_y: 1880762.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2462463.75
      sim_grid_pos_y: 1881339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2462972
      sim_grid_pos_y: 1881317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2462982.75
      sim_grid_pos_y: 1880773.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2462422
      sim_grid_pos_y: 1880710.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2462411.5
      sim_grid_pos_y: 1881393
    }
    terrain_level_point {
      sim_grid_pos_x: 2463022.25
      sim_grid_pos_y: 1881367
    }
    terrain_level_point {
      sim_grid_pos_x: 2463035
      sim_grid_pos_y: 1880723.12
    }
  }
}
