terrain_level_data {
  terrain_level: 1669
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1754361.5
      sim_grid_pos_y: 1720801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1754786.25
      sim_grid_pos_y: 1720972.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1755112.5
      sim_grid_pos_y: 1721346.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1755296.38
      sim_grid_pos_y: 1721363.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1755176.75
      sim_grid_pos_y: 1720935.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1755194.5
      sim_grid_pos_y: 1720700.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1755447.62
      sim_grid_pos_y: 1720517.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1755934.62
      sim_grid_pos_y: 1720669.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1755958.12
      sim_grid_pos_y: 1720572.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1755240.75
      sim_grid_pos_y: 1720293
    }
    terrain_level_point {
      sim_grid_pos_x: 1754889.75
      sim_grid_pos_y: 1720070.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1754899.62
      sim_grid_pos_y: 1720469
    }
    terrain_level_point {
      sim_grid_pos_x: 1754797.75
      sim_grid_pos_y: 1720743
    }
    terrain_level_point {
      sim_grid_pos_x: 1754424.5
      sim_grid_pos_y: 1720633.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1754891.88
      sim_grid_pos_y: 1719986.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1754817
      sim_grid_pos_y: 1720029.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1754827.5
      sim_grid_pos_y: 1720457
    }
    terrain_level_point {
      sim_grid_pos_x: 1754753.75
      sim_grid_pos_y: 1720655.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1754380.62
      sim_grid_pos_y: 1720545.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1754269.75
      sim_grid_pos_y: 1720842.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1754743.5
      sim_grid_pos_y: 1721032.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1755077.25
      sim_grid_pos_y: 1721414.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1755393.5
      sim_grid_pos_y: 1721444.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1755249.25
      sim_grid_pos_y: 1720928
    }
    terrain_level_point {
      sim_grid_pos_x: 1755263.5
      sim_grid_pos_y: 1720738.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1755460.5
      sim_grid_pos_y: 1720596.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1755986.38
      sim_grid_pos_y: 1720760.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1756042.62
      sim_grid_pos_y: 1720528
    }
    terrain_level_point {
      sim_grid_pos_x: 1755273.38
      sim_grid_pos_y: 1720228.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1754894
      sim_grid_pos_y: 1719903
    }
    terrain_level_point {
      sim_grid_pos_x: 1754744.12
      sim_grid_pos_y: 1719987.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1754755.5
      sim_grid_pos_y: 1720444.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1754709.88
      sim_grid_pos_y: 1720567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1754336.88
      sim_grid_pos_y: 1720457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1754178
      sim_grid_pos_y: 1720882.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1754700.75
      sim_grid_pos_y: 1721093
    }
    terrain_level_point {
      sim_grid_pos_x: 1755042.12
      sim_grid_pos_y: 1721483.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1755490.75
      sim_grid_pos_y: 1721525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1755321.75
      sim_grid_pos_y: 1720920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1755332.62
      sim_grid_pos_y: 1720777.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1755473.5
      sim_grid_pos_y: 1720675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1756038.12
      sim_grid_pos_y: 1720852
    }
    terrain_level_point {
      sim_grid_pos_x: 1756127.12
      sim_grid_pos_y: 1720483.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1755305.75
      sim_grid_pos_y: 1720164.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1754896
      sim_grid_pos_y: 1719819.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1754671.25
      sim_grid_pos_y: 1719946.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1754683.38
      sim_grid_pos_y: 1720432.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1754665.88
      sim_grid_pos_y: 1720479.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1754293
      sim_grid_pos_y: 1.72037e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1754086.25
      sim_grid_pos_y: 1720922.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1754658
      sim_grid_pos_y: 1721153.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1755007
      sim_grid_pos_y: 1721552.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1755587.88
      sim_grid_pos_y: 1721606.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1755394.38
      sim_grid_pos_y: 1720913.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1755401.62
      sim_grid_pos_y: 1720816.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1755486.38
      sim_grid_pos_y: 1720755
    }
    terrain_level_point {
      sim_grid_pos_x: 1756089.88
      sim_grid_pos_y: 1720943.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1756211.62
      sim_grid_pos_y: 1720439.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1755338.38
      sim_grid_pos_y: 1.7201e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1754898.12
      sim_grid_pos_y: 1719735.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1754598.5
      sim_grid_pos_y: 1719905.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1754610.5
      sim_grid_pos_y: 1720388.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1754249.25
      sim_grid_pos_y: 1720282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753994.5
      sim_grid_pos_y: 1720963.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1754615.25
      sim_grid_pos_y: 1721213.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1754971.75
      sim_grid_pos_y: 1721621.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1755685.12
      sim_grid_pos_y: 1721687.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1755466.88
      sim_grid_pos_y: 1720906.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1755470.75
      sim_grid_pos_y: 1720854.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1755499.25
      sim_grid_pos_y: 1720834.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1756141.62
      sim_grid_pos_y: 1721034.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1756296.12
      sim_grid_pos_y: 1720395.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1755370.88
      sim_grid_pos_y: 1720035.62
    }
  }
}
