terrain_level_data {
  terrain_level: 190
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1524295.75
      sim_grid_pos_y: 2015269
    }
    terrain_level_point {
      sim_grid_pos_x: 1522951.75
      sim_grid_pos_y: 2016353
    }
    terrain_level_point {
      sim_grid_pos_x: 1521695.25
      sim_grid_pos_y: 2017550.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1520180.12
      sim_grid_pos_y: 2018762.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1519246.12
      sim_grid_pos_y: 2.01981e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1518452.38
      sim_grid_pos_y: 2020311.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1517709.5
      sim_grid_pos_y: 2019300.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1518281.25
      sim_grid_pos_y: 2018648.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1519292.88
      sim_grid_pos_y: 2017703.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1520382
      sim_grid_pos_y: 2016369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1519995.12
      sim_grid_pos_y: 2016326.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1519798.38
      sim_grid_pos_y: 2014242.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1521292.5
      sim_grid_pos_y: 2013508.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1522177.75
      sim_grid_pos_y: 2014446.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1523364.25
      sim_grid_pos_y: 2014419.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1525114
      sim_grid_pos_y: 2013029.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1525994.62
      sim_grid_pos_y: 2012206.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1527011.38
      sim_grid_pos_y: 2013171.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1525116.12
      sim_grid_pos_y: 2014569.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1527170.62
      sim_grid_pos_y: 2013181.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1525179.88
      sim_grid_pos_y: 2014650.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1524361.25
      sim_grid_pos_y: 2015347.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1523019.38
      sim_grid_pos_y: 2016430.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1521762.75
      sim_grid_pos_y: 2017627.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1520250.88
      sim_grid_pos_y: 2018837.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1519313.12
      sim_grid_pos_y: 2019889
    }
    terrain_level_point {
      sim_grid_pos_x: 1518426.38
      sim_grid_pos_y: 2020449.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1517578.12
      sim_grid_pos_y: 2019295.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1518207.5
      sim_grid_pos_y: 2018577.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1519217.88
      sim_grid_pos_y: 2017632.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1520183.38
      sim_grid_pos_y: 2016450.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1519900.88
      sim_grid_pos_y: 2016419.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1519689.62
      sim_grid_pos_y: 2014181.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1521315.12
      sim_grid_pos_y: 2013383
    }
    terrain_level_point {
      sim_grid_pos_x: 1522221
      sim_grid_pos_y: 2014342.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1523327.5
      sim_grid_pos_y: 2014317.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1525047
      sim_grid_pos_y: 2012952
    }
    terrain_level_point {
      sim_grid_pos_x: 1525995.12
      sim_grid_pos_y: 2012065.25
    }
  }
}
terrain_level_data {
  terrain_level: 40
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1517362.62
      sim_grid_pos_y: 2021634.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1516854.5
      sim_grid_pos_y: 2022088.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1516541
      sim_grid_pos_y: 2021751.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1516756.38
      sim_grid_pos_y: 2021428.62
    }
  }
}
