terrain_level_data {
  terrain_level: 3871
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2360687
      sim_grid_pos_y: 1601631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360459.5
      sim_grid_pos_y: 1601623.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360452.5
      sim_grid_pos_y: 1602004.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360678.75
      sim_grid_pos_y: 1601991.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2360429.5
      sim_grid_pos_y: 1601591.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2360421.25
      sim_grid_pos_y: 1602036.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360708.75
      sim_grid_pos_y: 1602021
    }
    terrain_level_point {
      sim_grid_pos_x: 2360718.5
      sim_grid_pos_y: 1601601.88
    }
  }
}
terrain_level_data {
  terrain_level: 3915
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2360340.75
      sim_grid_pos_y: 1602856.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2360311.5
      sim_grid_pos_y: 1603076.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360395.5
      sim_grid_pos_y: 1603422
    }
    terrain_level_point {
      sim_grid_pos_x: 2360903.25
      sim_grid_pos_y: 1603406.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360988.5
      sim_grid_pos_y: 1603478.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361031.25
      sim_grid_pos_y: 1603920.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361300.25
      sim_grid_pos_y: 1603824
    }
    terrain_level_point {
      sim_grid_pos_x: 2361209.75
      sim_grid_pos_y: 1603300.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360927.5
      sim_grid_pos_y: 1603207.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2360901.75
      sim_grid_pos_y: 1602992
    }
    terrain_level_point {
      sim_grid_pos_x: 2360651
      sim_grid_pos_y: 1602844.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2360664
      sim_grid_pos_y: 1602793
    }
    terrain_level_point {
      sim_grid_pos_x: 2360295.75
      sim_grid_pos_y: 1602806.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360259.5
      sim_grid_pos_y: 1603079.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2360355.5
      sim_grid_pos_y: 1603474.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360885.25
      sim_grid_pos_y: 1603458.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360939.5
      sim_grid_pos_y: 1603503.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360986.5
      sim_grid_pos_y: 1603990.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2361358.25
      sim_grid_pos_y: 1603857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2361255
      sim_grid_pos_y: 1603261.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360974.5
      sim_grid_pos_y: 1603168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2360949.5
      sim_grid_pos_y: 1602960.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2360677
      sim_grid_pos_y: 1602741.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360250.5
      sim_grid_pos_y: 1602756.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2360207.5
      sim_grid_pos_y: 1603081.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360315.5
      sim_grid_pos_y: 1603527
    }
    terrain_level_point {
      sim_grid_pos_x: 2360867.25
      sim_grid_pos_y: 1603510.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360890.5
      sim_grid_pos_y: 1603529.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2360942
      sim_grid_pos_y: 1604060.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2361416
      sim_grid_pos_y: 1603891.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2361300.25
      sim_grid_pos_y: 1603222.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361021.5
      sim_grid_pos_y: 1603130.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2360997.5
      sim_grid_pos_y: 1602929.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2360690.25
      sim_grid_pos_y: 1602689.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360205.5
      sim_grid_pos_y: 1602707.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2360155.25
      sim_grid_pos_y: 1603084.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2360275.5
      sim_grid_pos_y: 1603579.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360842.25
      sim_grid_pos_y: 1603562.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360897.25
      sim_grid_pos_y: 1604131.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2361474
      sim_grid_pos_y: 1603925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361345.5
      sim_grid_pos_y: 1603183.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361068.5
      sim_grid_pos_y: 1603091.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2361045.25
      sim_grid_pos_y: 1602897.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2360703.25
      sim_grid_pos_y: 1602637.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2360160.25
      sim_grid_pos_y: 1602657.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360103.25
      sim_grid_pos_y: 1603087.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360235.5
      sim_grid_pos_y: 1603632
    }
    terrain_level_point {
      sim_grid_pos_x: 2360795.75
      sim_grid_pos_y: 1603615
    }
    terrain_level_point {
      sim_grid_pos_x: 2360852.5
      sim_grid_pos_y: 1604201.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2361531.75
      sim_grid_pos_y: 1603959.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361390.75
      sim_grid_pos_y: 1603144.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2361115.5
      sim_grid_pos_y: 1603053.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2361093
      sim_grid_pos_y: 1602866.62
    }
  }
}
terrain_level_data {
  terrain_level: 3690
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2359585
      sim_grid_pos_y: 1601317.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359434.5
      sim_grid_pos_y: 1601668.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2359719.25
      sim_grid_pos_y: 1601827.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2359884.25
      sim_grid_pos_y: 1601515.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2359571.25
      sim_grid_pos_y: 1601271.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359395.25
      sim_grid_pos_y: 1601682.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2359731.75
      sim_grid_pos_y: 1601869.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2359924.5
      sim_grid_pos_y: 1601505.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2359557.5
      sim_grid_pos_y: 1601225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359356
      sim_grid_pos_y: 1601695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359744.25
      sim_grid_pos_y: 1601911.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2359964.75
      sim_grid_pos_y: 1601495.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2359543.75
      sim_grid_pos_y: 1601179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359316.75
      sim_grid_pos_y: 1601708.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2359756.75
      sim_grid_pos_y: 1601954.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2360005
      sim_grid_pos_y: 1601485
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2.35953e+06
      sim_grid_pos_y: 1601133.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359277.5
      sim_grid_pos_y: 1601722.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2359769
      sim_grid_pos_y: 1601996.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360045.25
      sim_grid_pos_y: 1601474.75
    }
  }
}
