terrain_level_data {
  terrain_level: 35
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 724886.438
      sim_grid_pos_y: 1533838.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724893.188
      sim_grid_pos_y: 1534757.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725121.25
      sim_grid_pos_y: 1538667
    }
    terrain_level_point {
      sim_grid_pos_x: 725086.562
      sim_grid_pos_y: 1539853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725988.312
      sim_grid_pos_y: 1540387.88
    }
    terrain_level_point {
      sim_grid_pos_x: 726489.562
      sim_grid_pos_y: 1540803.12
    }
    terrain_level_point {
      sim_grid_pos_x: 727713.938
      sim_grid_pos_y: 1540834.12
    }
    terrain_level_point {
      sim_grid_pos_x: 728093.5
      sim_grid_pos_y: 1540294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 728286
      sim_grid_pos_y: 1539787.38
    }
    terrain_level_point {
      sim_grid_pos_x: 728409.438
      sim_grid_pos_y: 1539108.75
    }
    terrain_level_point {
      sim_grid_pos_x: 728335.062
      sim_grid_pos_y: 1532301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 727731.375
      sim_grid_pos_y: 1532125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 727608.875
      sim_grid_pos_y: 1532129.12
    }
    terrain_level_point {
      sim_grid_pos_x: 727188
      sim_grid_pos_y: 1532519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726741.5
      sim_grid_pos_y: 1532595.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725864.625
      sim_grid_pos_y: 1533452.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725408.875
      sim_grid_pos_y: 1533748.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 727735.312
      sim_grid_pos_y: 1532094.62
    }
    terrain_level_point {
      sim_grid_pos_x: 727596.438
      sim_grid_pos_y: 1532098.75
    }
    terrain_level_point {
      sim_grid_pos_x: 727173.812
      sim_grid_pos_y: 1532490.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726726.875
      sim_grid_pos_y: 1532566.62
    }
    terrain_level_point {
      sim_grid_pos_x: 725845.312
      sim_grid_pos_y: 1533428
    }
    terrain_level_point {
      sim_grid_pos_x: 725397.438
      sim_grid_pos_y: 1533719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724855.5
      sim_grid_pos_y: 1533812.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724862.438
      sim_grid_pos_y: 1534758.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725090.5
      sim_grid_pos_y: 1538667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 725055.312
      sim_grid_pos_y: 1539870.5
    }
    terrain_level_point {
      sim_grid_pos_x: 725970.562
      sim_grid_pos_y: 1540413.12
    }
    terrain_level_point {
      sim_grid_pos_x: 726478.125
      sim_grid_pos_y: 1540833.62
    }
    terrain_level_point {
      sim_grid_pos_x: 727729.625
      sim_grid_pos_y: 1540865.25
    }
    terrain_level_point {
      sim_grid_pos_x: 728120.875
      sim_grid_pos_y: 1540309
    }
    terrain_level_point {
      sim_grid_pos_x: 728315.75
      sim_grid_pos_y: 1539795.62
    }
    terrain_level_point {
      sim_grid_pos_x: 728440.25
      sim_grid_pos_y: 1539111.38
    }
    terrain_level_point {
      sim_grid_pos_x: 728365.562
      sim_grid_pos_y: 1532278.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 727739.25
      sim_grid_pos_y: 1532063.75
    }
    terrain_level_point {
      sim_grid_pos_x: 727584
      sim_grid_pos_y: 1532068.25
    }
    terrain_level_point {
      sim_grid_pos_x: 727159.625
      sim_grid_pos_y: 1532461.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726712.25
      sim_grid_pos_y: 1532538
    }
    terrain_level_point {
      sim_grid_pos_x: 725826
      sim_grid_pos_y: 1533403.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725385.938
      sim_grid_pos_y: 1533690.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724824.562
      sim_grid_pos_y: 1533786.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724831.688
      sim_grid_pos_y: 1534759.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725059.688
      sim_grid_pos_y: 1538667.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725024
      sim_grid_pos_y: 1539887.62
    }
    terrain_level_point {
      sim_grid_pos_x: 725952.812
      sim_grid_pos_y: 1540438.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726466.688
      sim_grid_pos_y: 1540864.12
    }
    terrain_level_point {
      sim_grid_pos_x: 727745.312
      sim_grid_pos_y: 1540896.5
    }
    terrain_level_point {
      sim_grid_pos_x: 728148.25
      sim_grid_pos_y: 1540323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 728345.5
      sim_grid_pos_y: 1539804
    }
    terrain_level_point {
      sim_grid_pos_x: 728471
      sim_grid_pos_y: 1539114
    }
    terrain_level_point {
      sim_grid_pos_x: 728396.062
      sim_grid_pos_y: 1532255.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 727743.25
      sim_grid_pos_y: 1532032.88
    }
    terrain_level_point {
      sim_grid_pos_x: 727571.562
      sim_grid_pos_y: 1532037.88
    }
    terrain_level_point {
      sim_grid_pos_x: 727145.438
      sim_grid_pos_y: 1532432.88
    }
    terrain_level_point {
      sim_grid_pos_x: 726697.625
      sim_grid_pos_y: 1532509.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725806.625
      sim_grid_pos_y: 1533379.75
    }
    terrain_level_point {
      sim_grid_pos_x: 725374.5
      sim_grid_pos_y: 1533661
    }
    terrain_level_point {
      sim_grid_pos_x: 724793.562
      sim_grid_pos_y: 1533760.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724800.938
      sim_grid_pos_y: 1534760.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725028.875
      sim_grid_pos_y: 1538668.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724992.75
      sim_grid_pos_y: 1539904.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725935
      sim_grid_pos_y: 1540463.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726455.312
      sim_grid_pos_y: 1540894.62
    }
    terrain_level_point {
      sim_grid_pos_x: 727761
      sim_grid_pos_y: 1540927.62
    }
    terrain_level_point {
      sim_grid_pos_x: 728175.625
      sim_grid_pos_y: 1540338.12
    }
    terrain_level_point {
      sim_grid_pos_x: 728375.25
      sim_grid_pos_y: 1539812.25
    }
    terrain_level_point {
      sim_grid_pos_x: 728501.812
      sim_grid_pos_y: 1539116.62
    }
    terrain_level_point {
      sim_grid_pos_x: 728426.562
      sim_grid_pos_y: 1532232.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 727747.188
      sim_grid_pos_y: 1532002
    }
    terrain_level_point {
      sim_grid_pos_x: 727559.062
      sim_grid_pos_y: 1532007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 727131.188
      sim_grid_pos_y: 1532404.12
    }
    terrain_level_point {
      sim_grid_pos_x: 726683
      sim_grid_pos_y: 1532480.5
    }
    terrain_level_point {
      sim_grid_pos_x: 725787.312
      sim_grid_pos_y: 1533355.62
    }
    terrain_level_point {
      sim_grid_pos_x: 725363.062
      sim_grid_pos_y: 1533631.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724762.625
      sim_grid_pos_y: 1533734.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724770.188
      sim_grid_pos_y: 1534761.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724998.125
      sim_grid_pos_y: 1538668.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724961.438
      sim_grid_pos_y: 1539922.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725917.25
      sim_grid_pos_y: 1540488.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726443.875
      sim_grid_pos_y: 1540925
    }
    terrain_level_point {
      sim_grid_pos_x: 727776.688
      sim_grid_pos_y: 1540958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 728203.062
      sim_grid_pos_y: 1540352.62
    }
    terrain_level_point {
      sim_grid_pos_x: 728405.062
      sim_grid_pos_y: 1539820.5
    }
    terrain_level_point {
      sim_grid_pos_x: 728532.562
      sim_grid_pos_y: 1539119.12
    }
    terrain_level_point {
      sim_grid_pos_x: 728457.062
      sim_grid_pos_y: 1532209.25
    }
  }
}
