terrain_level_data {
  terrain_level: 300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2193464.5
      sim_grid_pos_y: 1019966.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2191447
      sim_grid_pos_y: 1024856.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2191388.5
      sim_grid_pos_y: 1025168
    }
    terrain_level_point {
      sim_grid_pos_x: 2190792
      sim_grid_pos_y: 1025306.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2190528.25
      sim_grid_pos_y: 1024909.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2190403
      sim_grid_pos_y: 1024190.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2190556.5
      sim_grid_pos_y: 1023664.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2191830.75
      sim_grid_pos_y: 1021147
    }
    terrain_level_point {
      sim_grid_pos_x: 2193273.25
      sim_grid_pos_y: 1019345.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2193762.25
      sim_grid_pos_y: 1019093.44
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2193917.5
      sim_grid_pos_y: 1019051.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2193589.25
      sim_grid_pos_y: 1020013.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2191575.5
      sim_grid_pos_y: 1024894.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2191503.5
      sim_grid_pos_y: 1025278.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2190732
      sim_grid_pos_y: 1025456.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2190401.75
      sim_grid_pos_y: 1024959.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2190266.5
      sim_grid_pos_y: 1024182.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2190432
      sim_grid_pos_y: 1023615.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2191718
      sim_grid_pos_y: 1021074.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2193187
      sim_grid_pos_y: 1019240.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2193781
      sim_grid_pos_y: 1018933.69
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2194072.75
      sim_grid_pos_y: 1019009.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2193714
      sim_grid_pos_y: 1020060.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2191704
      sim_grid_pos_y: 1024932.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2191618.25
      sim_grid_pos_y: 1025388.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2190672.25
      sim_grid_pos_y: 1025607.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2190275.25
      sim_grid_pos_y: 1025010.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2190129.75
      sim_grid_pos_y: 1024174.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2190307.5
      sim_grid_pos_y: 1023566.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2191605.5
      sim_grid_pos_y: 1021001.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2193100.5
      sim_grid_pos_y: 1019135
    }
    terrain_level_point {
      sim_grid_pos_x: 2.1938e+06
      sim_grid_pos_y: 1018774
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2194228
      sim_grid_pos_y: 1018966.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2193839
      sim_grid_pos_y: 1020107.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2191832.5
      sim_grid_pos_y: 1024970.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2191733.25
      sim_grid_pos_y: 1025498.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2190612.25
      sim_grid_pos_y: 1025758.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2190148.75
      sim_grid_pos_y: 1025060.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2189993.25
      sim_grid_pos_y: 1024167.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2190183
      sim_grid_pos_y: 1023517.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2191492.75
      sim_grid_pos_y: 1020929.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2193014.25
      sim_grid_pos_y: 1019029.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2193818.75
      sim_grid_pos_y: 1018614.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2194383
      sim_grid_pos_y: 1018924.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2193963.75
      sim_grid_pos_y: 1020154.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2191960.75
      sim_grid_pos_y: 1025008.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2191848.25
      sim_grid_pos_y: 1025608.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2190552.5
      sim_grid_pos_y: 1025908.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2190022.25
      sim_grid_pos_y: 1025111.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2189856.5
      sim_grid_pos_y: 1024159.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2190058.5
      sim_grid_pos_y: 1023467.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2.19138e+06
      sim_grid_pos_y: 1020856.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2192928
      sim_grid_pos_y: 1018924.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2193837.75
      sim_grid_pos_y: 1018454.5
    }
  }
}
