terrain_level_data {
  terrain_level: 975
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1525936.25
      sim_grid_pos_y: 1686205.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1524654
      sim_grid_pos_y: 1685682.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1524767.5
      sim_grid_pos_y: 1685372.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1524893.75
      sim_grid_pos_y: 1685321.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1524982.12
      sim_grid_pos_y: 1685090.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1525260.38
      sim_grid_pos_y: 1685221
    }
    terrain_level_point {
      sim_grid_pos_x: 1525718.25
      sim_grid_pos_y: 1685407.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1526253.62
      sim_grid_pos_y: 1685651
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1525268.5
      sim_grid_pos_y: 1685202.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1525726.38
      sim_grid_pos_y: 1685388.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1526282.62
      sim_grid_pos_y: 1685641.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1525945.12
      sim_grid_pos_y: 1686231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1524628
      sim_grid_pos_y: 1685693.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1524751.38
      sim_grid_pos_y: 1685356.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1524877.75
      sim_grid_pos_y: 1685305.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1524970.88
      sim_grid_pos_y: 1685062.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1525276.75
      sim_grid_pos_y: 1685183.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1525734.5
      sim_grid_pos_y: 1685369.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1526311.62
      sim_grid_pos_y: 1685632.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1525954
      sim_grid_pos_y: 1686257.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1524601.88
      sim_grid_pos_y: 1685705.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1524735.25
      sim_grid_pos_y: 1685341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1524861.88
      sim_grid_pos_y: 1685289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1524959.62
      sim_grid_pos_y: 1685034.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1525285
      sim_grid_pos_y: 1685164.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1525742.62
      sim_grid_pos_y: 1685351
    }
    terrain_level_point {
      sim_grid_pos_x: 1526340.5
      sim_grid_pos_y: 1685623
    }
    terrain_level_point {
      sim_grid_pos_x: 1525962.88
      sim_grid_pos_y: 1686283.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1524575.88
      sim_grid_pos_y: 1685716.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1524719.12
      sim_grid_pos_y: 1685325.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1524845.88
      sim_grid_pos_y: 1685274.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1524948.38
      sim_grid_pos_y: 1685007
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1525293.38
      sim_grid_pos_y: 1685145.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1525750.75
      sim_grid_pos_y: 1685332.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1526369.5
      sim_grid_pos_y: 1685613.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1525971.75
      sim_grid_pos_y: 1686308.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1524549.75
      sim_grid_pos_y: 1685728.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1524703
      sim_grid_pos_y: 1.68531e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1524829.88
      sim_grid_pos_y: 1685258.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1524937.12
      sim_grid_pos_y: 1684979.12
    }
  }
}
