terrain_level_data {
  terrain_level: 224
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2917778.5
      sim_grid_pos_y: 655075.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2916412.5
      sim_grid_pos_y: 656075
    }
    terrain_level_point {
      sim_grid_pos_x: 2915332.25
      sim_grid_pos_y: 655347.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2914394.75
      sim_grid_pos_y: 653851.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2914559
      sim_grid_pos_y: 652722
    }
    terrain_level_point {
      sim_grid_pos_x: 2914788.5
      sim_grid_pos_y: 652687.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2915212.75
      sim_grid_pos_y: 652490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2916493.75
      sim_grid_pos_y: 652957.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2916514.5
      sim_grid_pos_y: 652932.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2917819.5
      sim_grid_pos_y: 655083.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2916413.25
      sim_grid_pos_y: 656112.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2915309.5
      sim_grid_pos_y: 655369.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2914362.75
      sim_grid_pos_y: 653857.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2914532
      sim_grid_pos_y: 652694.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2914779.75
      sim_grid_pos_y: 652658.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2915211.25
      sim_grid_pos_y: 652457.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2916535
      sim_grid_pos_y: 652907.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2917860.5
      sim_grid_pos_y: 655091.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2916414
      sim_grid_pos_y: 656150.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2915287
      sim_grid_pos_y: 655391.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2914330.75
      sim_grid_pos_y: 653864.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2914504.75
      sim_grid_pos_y: 652667.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2914770.75
      sim_grid_pos_y: 652628.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2915209.75
      sim_grid_pos_y: 652424.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2916555.75
      sim_grid_pos_y: 652882
    }
    terrain_level_point {
      sim_grid_pos_x: 2917901.5
      sim_grid_pos_y: 655099.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2916414.75
      sim_grid_pos_y: 656187.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2915264.25
      sim_grid_pos_y: 655413.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2914298.75
      sim_grid_pos_y: 653871.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2914477.75
      sim_grid_pos_y: 652640.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2914761.75
      sim_grid_pos_y: 652598.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2915208.25
      sim_grid_pos_y: 652391
    }
  }
}
