terrain_level_data {
  terrain_level: 290
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2202199.25
      sim_grid_pos_y: 1037483.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2202257.25
      sim_grid_pos_y: 1037357.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2202427.25
      sim_grid_pos_y: 1037122.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2202383.5
      sim_grid_pos_y: 1036949.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2202395.75
      sim_grid_pos_y: 1036636.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2202343.25
      sim_grid_pos_y: 1036171.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2202131.75
      sim_grid_pos_y: 1036110.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2202202.25
      sim_grid_pos_y: 1035891.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2202337.25
      sim_grid_pos_y: 1035764.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2202388.25
      sim_grid_pos_y: 1035817.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202388.5
      sim_grid_pos_y: 1035922.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202601.5
      sim_grid_pos_y: 1036051.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202911
      sim_grid_pos_y: 1037067.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2204032.75
      sim_grid_pos_y: 1037324.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2203902.5
      sim_grid_pos_y: 1037746.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2203619.5
      sim_grid_pos_y: 1038262.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2203601.5
      sim_grid_pos_y: 1038363
    }
    terrain_level_point {
      sim_grid_pos_x: 2203651.75
      sim_grid_pos_y: 1038489.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2.20368e+06
      sim_grid_pos_y: 1038718.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2203549
      sim_grid_pos_y: 1038854.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2203243.75
      sim_grid_pos_y: 1038528.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2201377.25
      sim_grid_pos_y: 1041267.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2201305.5
      sim_grid_pos_y: 1040978.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200436.75
      sim_grid_pos_y: 1040541.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2200191
      sim_grid_pos_y: 1040349.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199419
      sim_grid_pos_y: 1039917.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2199461
      sim_grid_pos_y: 1039528.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2199558.25
      sim_grid_pos_y: 1039430.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199767.75
      sim_grid_pos_y: 1039539.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2200139.5
      sim_grid_pos_y: 1039841.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200229
      sim_grid_pos_y: 1039697.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2200635.5
      sim_grid_pos_y: 1039910.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2200752
      sim_grid_pos_y: 1039612.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2200947.25
      sim_grid_pos_y: 1039318.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2201160.25
      sim_grid_pos_y: 1038926
    }
    terrain_level_point {
      sim_grid_pos_x: 2201276.25
      sim_grid_pos_y: 1038766.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201450.25
      sim_grid_pos_y: 1038641
    }
    terrain_level_point {
      sim_grid_pos_x: 2201434.5
      sim_grid_pos_y: 1038601.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201497.25
      sim_grid_pos_y: 1038529.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201495.5
      sim_grid_pos_y: 1038440.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2201542.5
      sim_grid_pos_y: 1038381
    }
    terrain_level_point {
      sim_grid_pos_x: 2201594
      sim_grid_pos_y: 1038417
    }
    terrain_level_point {
      sim_grid_pos_x: 2.20171e+06
      sim_grid_pos_y: 1038412
    }
    terrain_level_point {
      sim_grid_pos_x: 2201886.75
      sim_grid_pos_y: 1038226.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2201948
      sim_grid_pos_y: 1037963.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2202011
      sim_grid_pos_y: 1037751.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2202055.5
      sim_grid_pos_y: 1037717.56
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2202419
      sim_grid_pos_y: 1035805.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2202419.25
      sim_grid_pos_y: 1035905.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2202627.5
      sim_grid_pos_y: 1036031.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2202935.25
      sim_grid_pos_y: 1037041.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2204072
      sim_grid_pos_y: 1037302
    }
    terrain_level_point {
      sim_grid_pos_x: 2203931
      sim_grid_pos_y: 1037758.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2203649
      sim_grid_pos_y: 1038272.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2203633.25
      sim_grid_pos_y: 1038359.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2203682
      sim_grid_pos_y: 1038482.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2203712.25
      sim_grid_pos_y: 1038728.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2203548.5
      sim_grid_pos_y: 1038898.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2203247.5
      sim_grid_pos_y: 1038577.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201391.25
      sim_grid_pos_y: 1041301.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2201352
      sim_grid_pos_y: 1041294.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2201279
      sim_grid_pos_y: 1040999.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2200420.25
      sim_grid_pos_y: 1040567.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200173.75
      sim_grid_pos_y: 1040374.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2199386
      sim_grid_pos_y: 1039934.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2199431.5
      sim_grid_pos_y: 1039514.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2199552.5
      sim_grid_pos_y: 1039392.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2199784.75
      sim_grid_pos_y: 1039513.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200131.75
      sim_grid_pos_y: 1039795.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2200217.75
      sim_grid_pos_y: 1039656.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2200619.5
      sim_grid_pos_y: 1039867.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2200724.5
      sim_grid_pos_y: 1039598.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2200920.75
      sim_grid_pos_y: 1039302.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2201134.25
      sim_grid_pos_y: 1038909.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2201254.25
      sim_grid_pos_y: 1038744.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201412.75
      sim_grid_pos_y: 1038630.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2201399
      sim_grid_pos_y: 1038595.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201466.25
      sim_grid_pos_y: 1038518.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2201464.5
      sim_grid_pos_y: 1038429.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2201536.5
      sim_grid_pos_y: 1038339.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2201603
      sim_grid_pos_y: 1038385.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201696.25
      sim_grid_pos_y: 1038381.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201858.75
      sim_grid_pos_y: 1038211
    }
    terrain_level_point {
      sim_grid_pos_x: 2201918.25
      sim_grid_pos_y: 1037955.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201984.25
      sim_grid_pos_y: 1037732.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202032.25
      sim_grid_pos_y: 1037696.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2202172
      sim_grid_pos_y: 1037468.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2202230.5
      sim_grid_pos_y: 1037341.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202393.75
      sim_grid_pos_y: 1037116.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2202352.75
      sim_grid_pos_y: 1036953.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2202365
      sim_grid_pos_y: 1036637.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2202315
      sim_grid_pos_y: 1036195.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2202092.75
      sim_grid_pos_y: 1036130.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2202175.5
      sim_grid_pos_y: 1035874.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2202338.5
      sim_grid_pos_y: 1035720.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2202449.75
      sim_grid_pos_y: 1035793
    }
    terrain_level_point {
      sim_grid_pos_x: 2.20245e+06
      sim_grid_pos_y: 1035888
    }
    terrain_level_point {
      sim_grid_pos_x: 2202653.5
      sim_grid_pos_y: 1036011.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2202959.5
      sim_grid_pos_y: 1037015.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2204111.25
      sim_grid_pos_y: 1037279.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2203959.5
      sim_grid_pos_y: 1037771
    }
    terrain_level_point {
      sim_grid_pos_x: 2203678.25
      sim_grid_pos_y: 1038283.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2203665
      sim_grid_pos_y: 1038356.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2203712
      sim_grid_pos_y: 1038474.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2203744.75
      sim_grid_pos_y: 1038739.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2203548.25
      sim_grid_pos_y: 1038943.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2203251.25
      sim_grid_pos_y: 1038626.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201405.5
      sim_grid_pos_y: 1041334.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2201327
      sim_grid_pos_y: 1041320.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2201252.5
      sim_grid_pos_y: 1041021
    }
    terrain_level_point {
      sim_grid_pos_x: 2200403.75
      sim_grid_pos_y: 1040593.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2200156.75
      sim_grid_pos_y: 1040400.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2199353.25
      sim_grid_pos_y: 1039951.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199402.25
      sim_grid_pos_y: 1039500.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2199546.5
      sim_grid_pos_y: 1039354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199801.75
      sim_grid_pos_y: 1039487.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2200124
      sim_grid_pos_y: 1039749.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2200206.75
      sim_grid_pos_y: 1039616
    }
    terrain_level_point {
      sim_grid_pos_x: 2200603.25
      sim_grid_pos_y: 1039824.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2200697
      sim_grid_pos_y: 1039583.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200894.5
      sim_grid_pos_y: 1039286.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2201108.25
      sim_grid_pos_y: 1038893.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2201232.25
      sim_grid_pos_y: 1038722.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201375.25
      sim_grid_pos_y: 1038619.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2201363.5
      sim_grid_pos_y: 1038589.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201435.25
      sim_grid_pos_y: 1038507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2201433.5
      sim_grid_pos_y: 1038419.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2201530.25
      sim_grid_pos_y: 1038297.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2201612.25
      sim_grid_pos_y: 1038354.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201682.5
      sim_grid_pos_y: 1038351.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2201830.75
      sim_grid_pos_y: 1038195.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201888.5
      sim_grid_pos_y: 1037947.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201957.75
      sim_grid_pos_y: 1037714.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2202009
      sim_grid_pos_y: 1037675.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2202145
      sim_grid_pos_y: 1037454.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2202204
      sim_grid_pos_y: 1037326.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2202360.5
      sim_grid_pos_y: 1.03711e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2202321.75
      sim_grid_pos_y: 1036956.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2202334.25
      sim_grid_pos_y: 1036638.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2202286.75
      sim_grid_pos_y: 1036219.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2202053.75
      sim_grid_pos_y: 1036151.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2202148.75
      sim_grid_pos_y: 1035857.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202339.5
      sim_grid_pos_y: 1035677.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2202480.5
      sim_grid_pos_y: 1035780.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202480.75
      sim_grid_pos_y: 1035870.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202679.5
      sim_grid_pos_y: 1035991
    }
    terrain_level_point {
      sim_grid_pos_x: 2202983.75
      sim_grid_pos_y: 1036989.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2204150.25
      sim_grid_pos_y: 1037256.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2203988
      sim_grid_pos_y: 1037783.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2203707.75
      sim_grid_pos_y: 1038293.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2203697
      sim_grid_pos_y: 1038353.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2203742
      sim_grid_pos_y: 1038466.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2203777
      sim_grid_pos_y: 1038750.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2203548
      sim_grid_pos_y: 1038988.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2203255
      sim_grid_pos_y: 1038675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201419.75
      sim_grid_pos_y: 1041368.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201302
      sim_grid_pos_y: 1041347.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2201226
      sim_grid_pos_y: 1041042.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2200387
      sim_grid_pos_y: 1040619.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2200139.5
      sim_grid_pos_y: 1040426.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199320.5
      sim_grid_pos_y: 1039968.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199372.75
      sim_grid_pos_y: 1039486.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2199540.5
      sim_grid_pos_y: 1039317
    }
    terrain_level_point {
      sim_grid_pos_x: 2199818.75
      sim_grid_pos_y: 1039461.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2200116.25
      sim_grid_pos_y: 1039703.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200195.75
      sim_grid_pos_y: 1039575.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2200587
      sim_grid_pos_y: 1039780.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2200669.5
      sim_grid_pos_y: 1039569.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2200868
      sim_grid_pos_y: 1039270.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201082
      sim_grid_pos_y: 1038876.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2201210.25
      sim_grid_pos_y: 1038700.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2201338
      sim_grid_pos_y: 1038608.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2201328
      sim_grid_pos_y: 1038583.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201404.25
      sim_grid_pos_y: 1038496.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2201402.5
      sim_grid_pos_y: 1038409.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2201524.25
      sim_grid_pos_y: 1038255.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2201621.25
      sim_grid_pos_y: 1038323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2201669
      sim_grid_pos_y: 1038321.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2201802.75
      sim_grid_pos_y: 1038180.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2201858.75
      sim_grid_pos_y: 1037939.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2201931
      sim_grid_pos_y: 1037695.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2201985.75
      sim_grid_pos_y: 1037654.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2202117.75
      sim_grid_pos_y: 1037439.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2202177.25
      sim_grid_pos_y: 1037310.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2202327.25
      sim_grid_pos_y: 1037103.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2202290.75
      sim_grid_pos_y: 1036959.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2202303.25
      sim_grid_pos_y: 1036639.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202258.5
      sim_grid_pos_y: 1036243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2202014.75
      sim_grid_pos_y: 1036172.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2202121.75
      sim_grid_pos_y: 1035840.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2202340.75
      sim_grid_pos_y: 1035634
    }
  }
}
