terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2250933.5
      sim_grid_pos_y: 776158.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2252771.75
      sim_grid_pos_y: 776977.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2254334.75
      sim_grid_pos_y: 777768.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2257081.25
      sim_grid_pos_y: 780342.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2257173
      sim_grid_pos_y: 781251.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2246248.5
      sim_grid_pos_y: 780381.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2246291.5
      sim_grid_pos_y: 777792.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2249129
      sim_grid_pos_y: 777718.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2252793.75
      sim_grid_pos_y: 776930.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2254364.5
      sim_grid_pos_y: 777726.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2257130.25
      sim_grid_pos_y: 780318.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2257230.25
      sim_grid_pos_y: 781307.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2246196.5
      sim_grid_pos_y: 780428.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2246241
      sim_grid_pos_y: 777742.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2249109.25
      sim_grid_pos_y: 777667.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2250924.75
      sim_grid_pos_y: 776098.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2252815.75
      sim_grid_pos_y: 776884.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2254394.25
      sim_grid_pos_y: 777683.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2257179.5
      sim_grid_pos_y: 780294.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2257287.25
      sim_grid_pos_y: 781363.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2246144.5
      sim_grid_pos_y: 780475.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2246190.5
      sim_grid_pos_y: 777692.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2249089.5
      sim_grid_pos_y: 777616.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2250915.75
      sim_grid_pos_y: 776038.625
    }
  }
}
