terrain_level_data {
  terrain_level: 403
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2138185.75
      sim_grid_pos_y: 1345002.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2139160.75
      sim_grid_pos_y: 1344031.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2139266.75
      sim_grid_pos_y: 1344134.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2138316.75
      sim_grid_pos_y: 1345088.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2139296
      sim_grid_pos_y: 1344134.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2138319.5
      sim_grid_pos_y: 1345114.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2138153.5
      sim_grid_pos_y: 1345005.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2139160.5
      sim_grid_pos_y: 1344003
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2139325
      sim_grid_pos_y: 1344134.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2138322
      sim_grid_pos_y: 1345140.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2138121
      sim_grid_pos_y: 1345009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2139160.25
      sim_grid_pos_y: 1343974.25
    }
  }
}
