terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 594188.125
      sim_grid_pos_y: 2218003.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593733.125
      sim_grid_pos_y: 2217614
    }
    terrain_level_point {
      sim_grid_pos_x: 591948.438
      sim_grid_pos_y: 2217133.75
    }
    terrain_level_point {
      sim_grid_pos_x: 591792.25
      sim_grid_pos_y: 2218163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 591124.312
      sim_grid_pos_y: 2219031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 590156.062
      sim_grid_pos_y: 2219579
    }
    terrain_level_point {
      sim_grid_pos_x: 588647.062
      sim_grid_pos_y: 2219654
    }
    terrain_level_point {
      sim_grid_pos_x: 587458.312
      sim_grid_pos_y: 2221225
    }
    terrain_level_point {
      sim_grid_pos_x: 587515.25
      sim_grid_pos_y: 2225064.25
    }
    terrain_level_point {
      sim_grid_pos_x: 586851.312
      sim_grid_pos_y: 2226331.5
    }
    terrain_level_point {
      sim_grid_pos_x: 587782.438
      sim_grid_pos_y: 2227548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 589389.312
      sim_grid_pos_y: 2227030.75
    }
    terrain_level_point {
      sim_grid_pos_x: 589709.562
      sim_grid_pos_y: 2226599.5
    }
    terrain_level_point {
      sim_grid_pos_x: 589746.438
      sim_grid_pos_y: 2227171
    }
    terrain_level_point {
      sim_grid_pos_x: 590457.125
      sim_grid_pos_y: 2228189
    }
    terrain_level_point {
      sim_grid_pos_x: 592253.75
      sim_grid_pos_y: 2227058.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592868.188
      sim_grid_pos_y: 2227248.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592964.062
      sim_grid_pos_y: 2225571.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592710.125
      sim_grid_pos_y: 2225205
    }
    terrain_level_point {
      sim_grid_pos_x: 593172.688
      sim_grid_pos_y: 2225003.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593491.5
      sim_grid_pos_y: 2224807.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593866.062
      sim_grid_pos_y: 2224306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593768.625
      sim_grid_pos_y: 2222579.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593296.062
      sim_grid_pos_y: 2222210.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593228.812
      sim_grid_pos_y: 2220655.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592602.312
      sim_grid_pos_y: 2220179.25
    }
    terrain_level_point {
      sim_grid_pos_x: 592549.062
      sim_grid_pos_y: 2219442
    }
    terrain_level_point {
      sim_grid_pos_x: 593692.562
      sim_grid_pos_y: 2219232.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593861.25
      sim_grid_pos_y: 2218444.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 591923.188
      sim_grid_pos_y: 2217095.25
    }
    terrain_level_point {
      sim_grid_pos_x: 591763
      sim_grid_pos_y: 2218151
    }
    terrain_level_point {
      sim_grid_pos_x: 591103.75
      sim_grid_pos_y: 2219007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 590147.25
      sim_grid_pos_y: 2219548.75
    }
    terrain_level_point {
      sim_grid_pos_x: 588631.188
      sim_grid_pos_y: 2219624
    }
    terrain_level_point {
      sim_grid_pos_x: 587427.438
      sim_grid_pos_y: 2221214.75
    }
    terrain_level_point {
      sim_grid_pos_x: 587484.375
      sim_grid_pos_y: 2225057
    }
    terrain_level_point {
      sim_grid_pos_x: 586814.938
      sim_grid_pos_y: 2226334.5
    }
    terrain_level_point {
      sim_grid_pos_x: 587771.188
      sim_grid_pos_y: 2227584.25
    }
    terrain_level_point {
      sim_grid_pos_x: 589408.125
      sim_grid_pos_y: 2227057
    }
    terrain_level_point {
      sim_grid_pos_x: 589684.25
      sim_grid_pos_y: 2226685.25
    }
    terrain_level_point {
      sim_grid_pos_x: 589716.312
      sim_grid_pos_y: 2227181.5
    }
    terrain_level_point {
      sim_grid_pos_x: 590448.688
      sim_grid_pos_y: 2228230.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592258.125
      sim_grid_pos_y: 2227092.5
    }
    terrain_level_point {
      sim_grid_pos_x: 592896.625
      sim_grid_pos_y: 2227289.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592995.375
      sim_grid_pos_y: 2225563
    }
    terrain_level_point {
      sim_grid_pos_x: 592756.75
      sim_grid_pos_y: 2225218.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593186.938
      sim_grid_pos_y: 2225031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593512.625
      sim_grid_pos_y: 2224830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593897.438
      sim_grid_pos_y: 2224316
    }
    terrain_level_point {
      sim_grid_pos_x: 593798.562
      sim_grid_pos_y: 2222563.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593326.188
      sim_grid_pos_y: 2222195
    }
    terrain_level_point {
      sim_grid_pos_x: 593258.875
      sim_grid_pos_y: 2.22064e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 592632
      sim_grid_pos_y: 2220163
    }
    terrain_level_point {
      sim_grid_pos_x: 592581.75
      sim_grid_pos_y: 2219467.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593718.312
      sim_grid_pos_y: 2219259.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593889.938
      sim_grid_pos_y: 2218457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 594229.875
      sim_grid_pos_y: 2217998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593747.875
      sim_grid_pos_y: 2217586.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 591897.938
      sim_grid_pos_y: 2217056.5
    }
    terrain_level_point {
      sim_grid_pos_x: 591733.812
      sim_grid_pos_y: 2218138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 591083.188
      sim_grid_pos_y: 2218984
    }
    terrain_level_point {
      sim_grid_pos_x: 590138.438
      sim_grid_pos_y: 2219518.25
    }
    terrain_level_point {
      sim_grid_pos_x: 588615.312
      sim_grid_pos_y: 2219594
    }
    terrain_level_point {
      sim_grid_pos_x: 587396.5
      sim_grid_pos_y: 2221204.75
    }
    terrain_level_point {
      sim_grid_pos_x: 587453.5
      sim_grid_pos_y: 2225049.5
    }
    terrain_level_point {
      sim_grid_pos_x: 586778.562
      sim_grid_pos_y: 2226337.75
    }
    terrain_level_point {
      sim_grid_pos_x: 587759.938
      sim_grid_pos_y: 2.22762e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 589426.938
      sim_grid_pos_y: 2227083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 589658.938
      sim_grid_pos_y: 2226770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 589686.188
      sim_grid_pos_y: 2227192
    }
    terrain_level_point {
      sim_grid_pos_x: 590440.25
      sim_grid_pos_y: 2228272.5
    }
    terrain_level_point {
      sim_grid_pos_x: 592262.562
      sim_grid_pos_y: 2227126
    }
    terrain_level_point {
      sim_grid_pos_x: 592925.125
      sim_grid_pos_y: 2227330.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593026.688
      sim_grid_pos_y: 2225554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 592803.312
      sim_grid_pos_y: 2225231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593201.188
      sim_grid_pos_y: 2225058.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593533.75
      sim_grid_pos_y: 2224853.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593928.75
      sim_grid_pos_y: 2224325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593828.5
      sim_grid_pos_y: 2222548
    }
    terrain_level_point {
      sim_grid_pos_x: 593356.312
      sim_grid_pos_y: 2222179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593289
      sim_grid_pos_y: 2220624.25
    }
    terrain_level_point {
      sim_grid_pos_x: 592661.688
      sim_grid_pos_y: 2220147
    }
    terrain_level_point {
      sim_grid_pos_x: 592614.375
      sim_grid_pos_y: 2219492.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593744.062
      sim_grid_pos_y: 2219285.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593918.625
      sim_grid_pos_y: 2218470.75
    }
    terrain_level_point {
      sim_grid_pos_x: 594271.688
      sim_grid_pos_y: 2217994
    }
    terrain_level_point {
      sim_grid_pos_x: 593762.562
      sim_grid_pos_y: 2217558.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 591872.688
      sim_grid_pos_y: 2217018
    }
    terrain_level_point {
      sim_grid_pos_x: 591704.562
      sim_grid_pos_y: 2218126
    }
    terrain_level_point {
      sim_grid_pos_x: 591062.625
      sim_grid_pos_y: 2218960.25
    }
    terrain_level_point {
      sim_grid_pos_x: 590129.625
      sim_grid_pos_y: 2219488
    }
    terrain_level_point {
      sim_grid_pos_x: 588599.438
      sim_grid_pos_y: 2219564
    }
    terrain_level_point {
      sim_grid_pos_x: 587365.625
      sim_grid_pos_y: 2221194.5
    }
    terrain_level_point {
      sim_grid_pos_x: 587422.688
      sim_grid_pos_y: 2225042.25
    }
    terrain_level_point {
      sim_grid_pos_x: 586742.25
      sim_grid_pos_y: 2226340.75
    }
    terrain_level_point {
      sim_grid_pos_x: 587748.75
      sim_grid_pos_y: 2227656
    }
    terrain_level_point {
      sim_grid_pos_x: 589445.75
      sim_grid_pos_y: 2227109.5
    }
    terrain_level_point {
      sim_grid_pos_x: 589633.688
      sim_grid_pos_y: 2226856.5
    }
    terrain_level_point {
      sim_grid_pos_x: 589656
      sim_grid_pos_y: 2227202.75
    }
    terrain_level_point {
      sim_grid_pos_x: 590431.812
      sim_grid_pos_y: 2228314
    }
    terrain_level_point {
      sim_grid_pos_x: 592267
      sim_grid_pos_y: 2227159.5
    }
    terrain_level_point {
      sim_grid_pos_x: 592953.562
      sim_grid_pos_y: 2227371.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593058
      sim_grid_pos_y: 2225545.25
    }
    terrain_level_point {
      sim_grid_pos_x: 592849.938
      sim_grid_pos_y: 2225244.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593215.438
      sim_grid_pos_y: 2225085.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593554.875
      sim_grid_pos_y: 2224877
    }
    terrain_level_point {
      sim_grid_pos_x: 593960.062
      sim_grid_pos_y: 2224334.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593858.438
      sim_grid_pos_y: 2222532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593386.438
      sim_grid_pos_y: 2222164
    }
    terrain_level_point {
      sim_grid_pos_x: 593319.125
      sim_grid_pos_y: 2220608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 592691.312
      sim_grid_pos_y: 2220131
    }
    terrain_level_point {
      sim_grid_pos_x: 592647.062
      sim_grid_pos_y: 2219517.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593769.875
      sim_grid_pos_y: 2219312.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593947.312
      sim_grid_pos_y: 2218483.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594313.438
      sim_grid_pos_y: 2217989.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593777.312
      sim_grid_pos_y: 2217530.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 591847.438
      sim_grid_pos_y: 2216979.25
    }
    terrain_level_point {
      sim_grid_pos_x: 591675.375
      sim_grid_pos_y: 2218113.5
    }
    terrain_level_point {
      sim_grid_pos_x: 591042
      sim_grid_pos_y: 2218936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 590120.812
      sim_grid_pos_y: 2219457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 588583.562
      sim_grid_pos_y: 2219534
    }
    terrain_level_point {
      sim_grid_pos_x: 587334.688
      sim_grid_pos_y: 2221184.5
    }
    terrain_level_point {
      sim_grid_pos_x: 587391.75
      sim_grid_pos_y: 2225035
    }
    terrain_level_point {
      sim_grid_pos_x: 586705.875
      sim_grid_pos_y: 2226344
    }
    terrain_level_point {
      sim_grid_pos_x: 587737.5
      sim_grid_pos_y: 2227692
    }
    terrain_level_point {
      sim_grid_pos_x: 589464.562
      sim_grid_pos_y: 2227135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 589608.375
      sim_grid_pos_y: 2226942.25
    }
    terrain_level_point {
      sim_grid_pos_x: 589625.875
      sim_grid_pos_y: 2227213.25
    }
    terrain_level_point {
      sim_grid_pos_x: 590423.375
      sim_grid_pos_y: 2228355.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592271.375
      sim_grid_pos_y: 2227193
    }
    terrain_level_point {
      sim_grid_pos_x: 592982.062
      sim_grid_pos_y: 2227412.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593089.312
      sim_grid_pos_y: 2225536.5
    }
    terrain_level_point {
      sim_grid_pos_x: 592896.5
      sim_grid_pos_y: 2225258
    }
    terrain_level_point {
      sim_grid_pos_x: 593229.75
      sim_grid_pos_y: 2225113.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593575.938
      sim_grid_pos_y: 2.2249e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 593991.438
      sim_grid_pos_y: 2224344.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593888.312
      sim_grid_pos_y: 2222516.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593416.562
      sim_grid_pos_y: 2222148.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593349.188
      sim_grid_pos_y: 2220592.75
    }
    terrain_level_point {
      sim_grid_pos_x: 592721
      sim_grid_pos_y: 2220115
    }
    terrain_level_point {
      sim_grid_pos_x: 592679.688
      sim_grid_pos_y: 2219543
    }
    terrain_level_point {
      sim_grid_pos_x: 593795.625
      sim_grid_pos_y: 2219339
    }
    terrain_level_point {
      sim_grid_pos_x: 593975.938
      sim_grid_pos_y: 2218496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594355.25
      sim_grid_pos_y: 2217984.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593792
      sim_grid_pos_y: 2217502.5
    }
  }
}
