terrain_level_data {
  terrain_level: 132
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2686877.5
      sim_grid_pos_y: 2248597.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2686450.75
      sim_grid_pos_y: 2247154.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2686347.25
      sim_grid_pos_y: 2245135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2687150.25
      sim_grid_pos_y: 2244837.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2687544
      sim_grid_pos_y: 2243685
    }
    terrain_level_point {
      sim_grid_pos_x: 2688232.75
      sim_grid_pos_y: 2243949.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2688331.75
      sim_grid_pos_y: 2249202.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2688263.75
      sim_grid_pos_y: 2249347
    }
    terrain_level_point {
      sim_grid_pos_x: 2687250.75
      sim_grid_pos_y: 2249196.5
    }
  }
}
