terrain_level_data {
  terrain_level: 50
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1924733.12
      sim_grid_pos_y: 63825.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 1924928.5
      sim_grid_pos_y: 63894.9062
    }
    terrain_level_point {
      sim_grid_pos_x: 1925286.88
      sim_grid_pos_y: 63959.2383
    }
    terrain_level_point {
      sim_grid_pos_x: 1925838.12
      sim_grid_pos_y: 63979.8828
    }
    terrain_level_point {
      sim_grid_pos_x: 1926864.75
      sim_grid_pos_y: 65759.6797
    }
    terrain_level_point {
      sim_grid_pos_x: 1926279.12
      sim_grid_pos_y: 66030.2109
    }
    terrain_level_point {
      sim_grid_pos_x: 1925965
      sim_grid_pos_y: 66038.3047
    }
    terrain_level_point {
      sim_grid_pos_x: 1924773.75
      sim_grid_pos_y: 65871.5312
    }
    terrain_level_point {
      sim_grid_pos_x: 1924156.75
      sim_grid_pos_y: 65660.9766
    }
    terrain_level_point {
      sim_grid_pos_x: 1921332.75
      sim_grid_pos_y: 65412.9
    }
    terrain_level_point {
      sim_grid_pos_x: 1920900.75
      sim_grid_pos_y: 65074.707
    }
    terrain_level_point {
      sim_grid_pos_x: 1921892.12
      sim_grid_pos_y: 64276.9062
    }
    terrain_level_point {
      sim_grid_pos_x: 1922325.12
      sim_grid_pos_y: 63989.2461
    }
    terrain_level_point {
      sim_grid_pos_x: 1922655.38
      sim_grid_pos_y: 63817.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 1923088
      sim_grid_pos_y: 63661.9102
    }
    terrain_level_point {
      sim_grid_pos_x: 1923508.5
      sim_grid_pos_y: 63558.6484
    }
    terrain_level_point {
      sim_grid_pos_x: 1923850.25
      sim_grid_pos_y: 63536.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1924175.5
      sim_grid_pos_y: 63636.0898
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1924184.88
      sim_grid_pos_y: 63606.8164
    }
    terrain_level_point {
      sim_grid_pos_x: 1924743.12
      sim_grid_pos_y: 63796.8555
    }
    terrain_level_point {
      sim_grid_pos_x: 1924936.5
      sim_grid_pos_y: 63865.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 1925290.12
      sim_grid_pos_y: 63928.5742
    }
    terrain_level_point {
      sim_grid_pos_x: 1925856.25
      sim_grid_pos_y: 63949.7852
    }
    terrain_level_point {
      sim_grid_pos_x: 1926908.25
      sim_grid_pos_y: 65773.4844
    }
    terrain_level_point {
      sim_grid_pos_x: 1926286.25
      sim_grid_pos_y: 66060.8
    }
    terrain_level_point {
      sim_grid_pos_x: 1925963.25
      sim_grid_pos_y: 66069.1172
    }
    terrain_level_point {
      sim_grid_pos_x: 1924766.62
      sim_grid_pos_y: 65901.5859
    }
    terrain_level_point {
      sim_grid_pos_x: 1924150.38
      sim_grid_pos_y: 65691.2891
    }
    terrain_level_point {
      sim_grid_pos_x: 1921320.88
      sim_grid_pos_y: 65442.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 1920851.25
      sim_grid_pos_y: 65075.0352
    }
    terrain_level_point {
      sim_grid_pos_x: 1921873.88
      sim_grid_pos_y: 64252.0664
    }
    terrain_level_point {
      sim_grid_pos_x: 1922309.5
      sim_grid_pos_y: 63962.7148
    }
    terrain_level_point {
      sim_grid_pos_x: 1922643
      sim_grid_pos_y: 63789.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 1923079.12
      sim_grid_pos_y: 63632.4141
    }
    terrain_level_point {
      sim_grid_pos_x: 1923503.88
      sim_grid_pos_y: 63528.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1923853.88
      sim_grid_pos_y: 63505.6953
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1924194.38
      sim_grid_pos_y: 63577.5352
    }
    terrain_level_point {
      sim_grid_pos_x: 1924753.25
      sim_grid_pos_y: 63767.7969
    }
    terrain_level_point {
      sim_grid_pos_x: 1924944.38
      sim_grid_pos_y: 63835.2461
    }
    terrain_level_point {
      sim_grid_pos_x: 1925293.62
      sim_grid_pos_y: 63897.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 1925874.38
      sim_grid_pos_y: 63919.6875
    }
    terrain_level_point {
      sim_grid_pos_x: 1926951.62
      sim_grid_pos_y: 65787.2891
    }
    terrain_level_point {
      sim_grid_pos_x: 1926293.38
      sim_grid_pos_y: 66091.3828
    }
    terrain_level_point {
      sim_grid_pos_x: 1925961.5
      sim_grid_pos_y: 66099.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 1924759.38
      sim_grid_pos_y: 65931.6484
    }
    terrain_level_point {
      sim_grid_pos_x: 1924143.88
      sim_grid_pos_y: 65721.5938
    }
    terrain_level_point {
      sim_grid_pos_x: 1921309.12
      sim_grid_pos_y: 65472.5742
    }
    terrain_level_point {
      sim_grid_pos_x: 1920801.88
      sim_grid_pos_y: 65075.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 1921855.75
      sim_grid_pos_y: 64227.2148
    }
    terrain_level_point {
      sim_grid_pos_x: 1922293.88
      sim_grid_pos_y: 63936.1875
    }
    terrain_level_point {
      sim_grid_pos_x: 1922630.62
      sim_grid_pos_y: 63760.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 1923070.12
      sim_grid_pos_y: 63602.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 1923499.12
      sim_grid_pos_y: 63497.6055
    }
    terrain_level_point {
      sim_grid_pos_x: 1923857.5
      sim_grid_pos_y: 63474.6367
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1924203.88
      sim_grid_pos_y: 63548.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 1924763.38
      sim_grid_pos_y: 63738.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 1924952.25
      sim_grid_pos_y: 63805.4141
    }
    terrain_level_point {
      sim_grid_pos_x: 1925296.88
      sim_grid_pos_y: 63867.2773
    }
    terrain_level_point {
      sim_grid_pos_x: 1925892.5
      sim_grid_pos_y: 63889.5859
    }
    terrain_level_point {
      sim_grid_pos_x: 1926995.12
      sim_grid_pos_y: 65801.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 1926300.5
      sim_grid_pos_y: 66121.9688
    }
    terrain_level_point {
      sim_grid_pos_x: 1925959.75
      sim_grid_pos_y: 66130.7422
    }
    terrain_level_point {
      sim_grid_pos_x: 1924752.25
      sim_grid_pos_y: 65961.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 1924137.5
      sim_grid_pos_y: 65751.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 1921297.38
      sim_grid_pos_y: 65502.4141
    }
    terrain_level_point {
      sim_grid_pos_x: 1920752.38
      sim_grid_pos_y: 65075.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 1921837.5
      sim_grid_pos_y: 64202.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1922278.25
      sim_grid_pos_y: 63909.6562
    }
    terrain_level_point {
      sim_grid_pos_x: 1922618.25
      sim_grid_pos_y: 63732.7461
    }
    terrain_level_point {
      sim_grid_pos_x: 1923061.25
      sim_grid_pos_y: 63573.4453
    }
    terrain_level_point {
      sim_grid_pos_x: 1923494.5
      sim_grid_pos_y: 63467.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 1923861.12
      sim_grid_pos_y: 63443.5859
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1924213.25
      sim_grid_pos_y: 63518.9961
    }
    terrain_level_point {
      sim_grid_pos_x: 1924773.38
      sim_grid_pos_y: 63709.6641
    }
    terrain_level_point {
      sim_grid_pos_x: 1924960.12
      sim_grid_pos_y: 63775.5742
    }
    terrain_level_point {
      sim_grid_pos_x: 1925300.12
      sim_grid_pos_y: 63836.6172
    }
    terrain_level_point {
      sim_grid_pos_x: 1925910.62
      sim_grid_pos_y: 63859.4844
    }
    terrain_level_point {
      sim_grid_pos_x: 1927038.62
      sim_grid_pos_y: 65814.8828
    }
    terrain_level_point {
      sim_grid_pos_x: 1926307.62
      sim_grid_pos_y: 66152.5547
    }
    terrain_level_point {
      sim_grid_pos_x: 1925958
      sim_grid_pos_y: 66161.5547
    }
    terrain_level_point {
      sim_grid_pos_x: 1924745.12
      sim_grid_pos_y: 65991.7578
    }
    terrain_level_point {
      sim_grid_pos_x: 1924131.12
      sim_grid_pos_y: 65782.2266
    }
    terrain_level_point {
      sim_grid_pos_x: 1921285.62
      sim_grid_pos_y: 65532.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 1920702.88
      sim_grid_pos_y: 65076.0352
    }
    terrain_level_point {
      sim_grid_pos_x: 1921819.38
      sim_grid_pos_y: 64177.5352
    }
    terrain_level_point {
      sim_grid_pos_x: 1922262.5
      sim_grid_pos_y: 63883.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1922606
      sim_grid_pos_y: 63704.5078
    }
    terrain_level_point {
      sim_grid_pos_x: 1923052.38
      sim_grid_pos_y: 63543.957
    }
    terrain_level_point {
      sim_grid_pos_x: 1923489.75
      sim_grid_pos_y: 63436.5664
    }
    terrain_level_point {
      sim_grid_pos_x: 1923864.88
      sim_grid_pos_y: 63412.5352
    }
  }
}
