terrain_level_data {
  terrain_level: 818
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2642292.5
      sim_grid_pos_y: 1364495
    }
    terrain_level_point {
      sim_grid_pos_x: 2647169
      sim_grid_pos_y: 1366213.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2646939.25
      sim_grid_pos_y: 1366725.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2644445.75
      sim_grid_pos_y: 1366186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2639354.25
      sim_grid_pos_y: 1364057.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2639669.75
      sim_grid_pos_y: 1363375
    }
    terrain_level_point {
      sim_grid_pos_x: 2641966.5
      sim_grid_pos_y: 1364262.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2642190.25
      sim_grid_pos_y: 1363909.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2642454.25
      sim_grid_pos_y: 1364123.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2641925
      sim_grid_pos_y: 1364136.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2642165.5
      sim_grid_pos_y: 1363757.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2642579.25
      sim_grid_pos_y: 1364093
    }
    terrain_level_point {
      sim_grid_pos_x: 2642430.5
      sim_grid_pos_y: 1364435
    }
    terrain_level_point {
      sim_grid_pos_x: 2647308
      sim_grid_pos_y: 1366153.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2646998.75
      sim_grid_pos_y: 1366843.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2644415
      sim_grid_pos_y: 1366285
    }
    terrain_level_point {
      sim_grid_pos_x: 2639216.5
      sim_grid_pos_y: 1364111
    }
    terrain_level_point {
      sim_grid_pos_x: 2639617
      sim_grid_pos_y: 1363244.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2641883.25
      sim_grid_pos_y: 1364010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2642140.5
      sim_grid_pos_y: 1363605.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2642704.25
      sim_grid_pos_y: 1364062.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2642568.5
      sim_grid_pos_y: 1364374.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2647447
      sim_grid_pos_y: 1366093.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2647058.5
      sim_grid_pos_y: 1366960.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2644384.25
      sim_grid_pos_y: 1366383.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2639078.75
      sim_grid_pos_y: 1364164.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2639564.25
      sim_grid_pos_y: 1363114.5
    }
  }
}
