terrain_level_data {
  terrain_level: 300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 481818.406
      sim_grid_pos_y: 1511015
    }
    terrain_level_point {
      sim_grid_pos_x: 482063.406
      sim_grid_pos_y: 1511318.12
    }
    terrain_level_point {
      sim_grid_pos_x: 482291.469
      sim_grid_pos_y: 1511390.25
    }
    terrain_level_point {
      sim_grid_pos_x: 482786.844
      sim_grid_pos_y: 1510471.12
    }
    terrain_level_point {
      sim_grid_pos_x: 482252.688
      sim_grid_pos_y: 1510167.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 482239.969
      sim_grid_pos_y: 1510124.75
    }
    terrain_level_point {
      sim_grid_pos_x: 481781.938
      sim_grid_pos_y: 1511018.75
    }
    terrain_level_point {
      sim_grid_pos_x: 482045.312
      sim_grid_pos_y: 1511344.62
    }
    terrain_level_point {
      sim_grid_pos_x: 482306.469
      sim_grid_pos_y: 1511427.25
    }
    terrain_level_point {
      sim_grid_pos_x: 482828.188
      sim_grid_pos_y: 1510459.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 482227.25
      sim_grid_pos_y: 1510082.12
    }
    terrain_level_point {
      sim_grid_pos_x: 481745.438
      sim_grid_pos_y: 1511022.5
    }
    terrain_level_point {
      sim_grid_pos_x: 482027.219
      sim_grid_pos_y: 1511371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 482321.469
      sim_grid_pos_y: 1511464.25
    }
    terrain_level_point {
      sim_grid_pos_x: 482869.531
      sim_grid_pos_y: 1510447.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 482214.531
      sim_grid_pos_y: 1510039.5
    }
    terrain_level_point {
      sim_grid_pos_x: 481708.938
      sim_grid_pos_y: 1511026.25
    }
    terrain_level_point {
      sim_grid_pos_x: 482009.125
      sim_grid_pos_y: 1511397.75
    }
    terrain_level_point {
      sim_grid_pos_x: 482336.469
      sim_grid_pos_y: 1511501.25
    }
    terrain_level_point {
      sim_grid_pos_x: 482910.844
      sim_grid_pos_y: 1510435.38
    }
  }
}
