terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1127168.62
      sim_grid_pos_y: 1441365.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1128180.5
      sim_grid_pos_y: 1441039.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131216.75
      sim_grid_pos_y: 1441054.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1131862.25
      sim_grid_pos_y: 1441324.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1132499.62
      sim_grid_pos_y: 1441760.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133623
      sim_grid_pos_y: 1441906.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133905
      sim_grid_pos_y: 1442678.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133935.88
      sim_grid_pos_y: 1446826.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134532.12
      sim_grid_pos_y: 1447487.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132319.25
      sim_grid_pos_y: 1451247.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1129418.75
      sim_grid_pos_y: 1451343.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1127985.5
      sim_grid_pos_y: 1451852.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1127565.88
      sim_grid_pos_y: 1449405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1127136.88
      sim_grid_pos_y: 1446113.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1131223
      sim_grid_pos_y: 1441024.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131877
      sim_grid_pos_y: 1441297.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132511
      sim_grid_pos_y: 1441731.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133645.38
      sim_grid_pos_y: 1441878
    }
    terrain_level_point {
      sim_grid_pos_x: 1133935.75
      sim_grid_pos_y: 1442673
    }
    terrain_level_point {
      sim_grid_pos_x: 1133966.5
      sim_grid_pos_y: 1446814.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.13457e+06
      sim_grid_pos_y: 1447483.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1132337.25
      sim_grid_pos_y: 1451277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1129424.62
      sim_grid_pos_y: 1451374.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1127961.38
      sim_grid_pos_y: 1451893.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1127535.5
      sim_grid_pos_y: 1449410.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1127106.12
      sim_grid_pos_y: 1446115.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1127138
      sim_grid_pos_y: 1441342.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1128175.75
      sim_grid_pos_y: 1441008.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1131229.12
      sim_grid_pos_y: 1440993.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1131891.75
      sim_grid_pos_y: 1441270.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1132522.25
      sim_grid_pos_y: 1441701.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133667.88
      sim_grid_pos_y: 1.44185e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1133966.5
      sim_grid_pos_y: 1442667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133997.25
      sim_grid_pos_y: 1446802.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134608
      sim_grid_pos_y: 1447479.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1132355.12
      sim_grid_pos_y: 1451307.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1129430.38
      sim_grid_pos_y: 1451404.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1127937.25
      sim_grid_pos_y: 1451934.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1127505.12
      sim_grid_pos_y: 1449414.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1127075.38
      sim_grid_pos_y: 1446117.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1127107.38
      sim_grid_pos_y: 1441320.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1128171
      sim_grid_pos_y: 1440977.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1131235.38
      sim_grid_pos_y: 1440962.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131906.5
      sim_grid_pos_y: 1441243
    }
    terrain_level_point {
      sim_grid_pos_x: 1132533.5
      sim_grid_pos_y: 1441672.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133690.38
      sim_grid_pos_y: 1441821.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133997.12
      sim_grid_pos_y: 1442661.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134027.88
      sim_grid_pos_y: 1446790.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134646
      sim_grid_pos_y: 1447475.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132373
      sim_grid_pos_y: 1451337.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1129436.12
      sim_grid_pos_y: 1451435.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1127913.12
      sim_grid_pos_y: 1451975.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1127474.62
      sim_grid_pos_y: 1449419.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1127044.62
      sim_grid_pos_y: 1446119.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1127076.75
      sim_grid_pos_y: 1441298
    }
    terrain_level_point {
      sim_grid_pos_x: 1128166.25
      sim_grid_pos_y: 1440946.88
    }
  }
}
