terrain_level_data {
  terrain_level: 6
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 133182.422
      sim_grid_pos_y: 3117538.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133461.406
      sim_grid_pos_y: 3116907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 133565.031
      sim_grid_pos_y: 3116277.75
    }
    terrain_level_point {
      sim_grid_pos_x: 133700.359
      sim_grid_pos_y: 3116265.5
    }
    terrain_level_point {
      sim_grid_pos_x: 134117.688
      sim_grid_pos_y: 3114200.25
    }
    terrain_level_point {
      sim_grid_pos_x: 134296.75
      sim_grid_pos_y: 3112360.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133730.859
      sim_grid_pos_y: 3111103.75
    }
    terrain_level_point {
      sim_grid_pos_x: 133788.344
      sim_grid_pos_y: 3.1107e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 128720.141
      sim_grid_pos_y: 3109374.5
    }
    terrain_level_point {
      sim_grid_pos_x: 128906.641
      sim_grid_pos_y: 3108505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 127902.703
      sim_grid_pos_y: 3108854
    }
    terrain_level_point {
      sim_grid_pos_x: 125595.258
      sim_grid_pos_y: 3110177
    }
    terrain_level_point {
      sim_grid_pos_x: 124747.922
      sim_grid_pos_y: 3110314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122326.359
      sim_grid_pos_y: 3110813.75
    }
    terrain_level_point {
      sim_grid_pos_x: 121643.016
      sim_grid_pos_y: 3111867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 121625.352
      sim_grid_pos_y: 3112296.75
    }
    terrain_level_point {
      sim_grid_pos_x: 121923.102
      sim_grid_pos_y: 3112555
    }
    terrain_level_point {
      sim_grid_pos_x: 123466.312
      sim_grid_pos_y: 3112999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122969.641
      sim_grid_pos_y: 3117235.5
    }
    terrain_level_point {
      sim_grid_pos_x: 123993.742
      sim_grid_pos_y: 3117355.25
    }
    terrain_level_point {
      sim_grid_pos_x: 124099.906
      sim_grid_pos_y: 3116468.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 128918.125
      sim_grid_pos_y: 3108447
    }
    terrain_level_point {
      sim_grid_pos_x: 127881.367
      sim_grid_pos_y: 3108807.25
    }
    terrain_level_point {
      sim_grid_pos_x: 125577.844
      sim_grid_pos_y: 3110128
    }
    terrain_level_point {
      sim_grid_pos_x: 124738.633
      sim_grid_pos_y: 3110264
    }
    terrain_level_point {
      sim_grid_pos_x: 122295.008
      sim_grid_pos_y: 3110767.75
    }
    terrain_level_point {
      sim_grid_pos_x: 121592.375
      sim_grid_pos_y: 3111851.5
    }
    terrain_level_point {
      sim_grid_pos_x: 121573.125
      sim_grid_pos_y: 3112319.25
    }
    terrain_level_point {
      sim_grid_pos_x: 121898.055
      sim_grid_pos_y: 3112601.25
    }
    terrain_level_point {
      sim_grid_pos_x: 123410.344
      sim_grid_pos_y: 3113036.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122912.75
      sim_grid_pos_y: 3117280.5
    }
    terrain_level_point {
      sim_grid_pos_x: 124038.562
      sim_grid_pos_y: 3117412
    }
    terrain_level_point {
      sim_grid_pos_x: 124144.727
      sim_grid_pos_y: 3116525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 133214
      sim_grid_pos_y: 3117593.5
    }
    terrain_level_point {
      sim_grid_pos_x: 133510.922
      sim_grid_pos_y: 3116922.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133609.172
      sim_grid_pos_y: 3116325.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133743.031
      sim_grid_pos_y: 3116313
    }
    terrain_level_point {
      sim_grid_pos_x: 134168.453
      sim_grid_pos_y: 3114207.75
    }
    terrain_level_point {
      sim_grid_pos_x: 134349.094
      sim_grid_pos_y: 3112351.75
    }
    terrain_level_point {
      sim_grid_pos_x: 133783.703
      sim_grid_pos_y: 3111096.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133845.547
      sim_grid_pos_y: 3110662
    }
    terrain_level_point {
      sim_grid_pos_x: 128780.539
      sim_grid_pos_y: 3109337.25
    }
    terrain_level_point {
      sim_grid_pos_x: 128963.047
      sim_grid_pos_y: 3108486.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 128929.625
      sim_grid_pos_y: 3108388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 127860.016
      sim_grid_pos_y: 3108760.25
    }
    terrain_level_point {
      sim_grid_pos_x: 125560.438
      sim_grid_pos_y: 3110078.75
    }
    terrain_level_point {
      sim_grid_pos_x: 124729.359
      sim_grid_pos_y: 3110213.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122263.664
      sim_grid_pos_y: 3110722
    }
    terrain_level_point {
      sim_grid_pos_x: 121541.727
      sim_grid_pos_y: 3111835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 121520.883
      sim_grid_pos_y: 3112341.75
    }
    terrain_level_point {
      sim_grid_pos_x: 121873.016
      sim_grid_pos_y: 3112647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 123354.359
      sim_grid_pos_y: 3113073.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122855.867
      sim_grid_pos_y: 3117325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 124083.398
      sim_grid_pos_y: 3117469
    }
    terrain_level_point {
      sim_grid_pos_x: 124189.547
      sim_grid_pos_y: 3116582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133245.594
      sim_grid_pos_y: 3117649
    }
    terrain_level_point {
      sim_grid_pos_x: 133560.453
      sim_grid_pos_y: 3116937
    }
    terrain_level_point {
      sim_grid_pos_x: 133653.312
      sim_grid_pos_y: 3116372.75
    }
    terrain_level_point {
      sim_grid_pos_x: 133785.719
      sim_grid_pos_y: 3116360.75
    }
    terrain_level_point {
      sim_grid_pos_x: 134219.219
      sim_grid_pos_y: 3114215.5
    }
    terrain_level_point {
      sim_grid_pos_x: 134401.438
      sim_grid_pos_y: 3112343
    }
    terrain_level_point {
      sim_grid_pos_x: 133836.547
      sim_grid_pos_y: 3111088.75
    }
    terrain_level_point {
      sim_grid_pos_x: 133902.734
      sim_grid_pos_y: 3110624
    }
    terrain_level_point {
      sim_grid_pos_x: 128840.945
      sim_grid_pos_y: 3109300.25
    }
    terrain_level_point {
      sim_grid_pos_x: 129019.453
      sim_grid_pos_y: 3108468.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 128941.117
      sim_grid_pos_y: 3108330.5
    }
    terrain_level_point {
      sim_grid_pos_x: 127838.68
      sim_grid_pos_y: 3108713.5
    }
    terrain_level_point {
      sim_grid_pos_x: 125542.992
      sim_grid_pos_y: 3110029.75
    }
    terrain_level_point {
      sim_grid_pos_x: 124720.062
      sim_grid_pos_y: 3110163.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122232.312
      sim_grid_pos_y: 3110676
    }
    terrain_level_point {
      sim_grid_pos_x: 121491.086
      sim_grid_pos_y: 3111819.25
    }
    terrain_level_point {
      sim_grid_pos_x: 121468.656
      sim_grid_pos_y: 3112364.5
    }
    terrain_level_point {
      sim_grid_pos_x: 121847.969
      sim_grid_pos_y: 3112693.5
    }
    terrain_level_point {
      sim_grid_pos_x: 123298.383
      sim_grid_pos_y: 3113111
    }
    terrain_level_point {
      sim_grid_pos_x: 122798.977
      sim_grid_pos_y: 3117370.5
    }
    terrain_level_point {
      sim_grid_pos_x: 124128.219
      sim_grid_pos_y: 3117525.75
    }
    terrain_level_point {
      sim_grid_pos_x: 124234.367
      sim_grid_pos_y: 3116639.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133277.156
      sim_grid_pos_y: 3117704.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133609.969
      sim_grid_pos_y: 3116951.75
    }
    terrain_level_point {
      sim_grid_pos_x: 133697.453
      sim_grid_pos_y: 3116420.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133828.391
      sim_grid_pos_y: 3116408.25
    }
    terrain_level_point {
      sim_grid_pos_x: 134269.984
      sim_grid_pos_y: 3114223
    }
    terrain_level_point {
      sim_grid_pos_x: 134453.781
      sim_grid_pos_y: 3112334.5
    }
    terrain_level_point {
      sim_grid_pos_x: 133889.391
      sim_grid_pos_y: 3111081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 133959.938
      sim_grid_pos_y: 3110586
    }
    terrain_level_point {
      sim_grid_pos_x: 128901.359
      sim_grid_pos_y: 3109263
    }
    terrain_level_point {
      sim_grid_pos_x: 129075.867
      sim_grid_pos_y: 3108449.5
    }
  }
}
