terrain_level_data {
  terrain_level: 12
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2016345.25
      sim_grid_pos_y: 55381.9648
    }
    terrain_level_point {
      sim_grid_pos_x: 2016186.62
      sim_grid_pos_y: 59346.543
    }
    terrain_level_point {
      sim_grid_pos_x: 2016552.75
      sim_grid_pos_y: 60588.1953
    }
    terrain_level_point {
      sim_grid_pos_x: 2016797.5
      sim_grid_pos_y: 60770.2578
    }
    terrain_level_point {
      sim_grid_pos_x: 2017809.5
      sim_grid_pos_y: 59919.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 2018337.5
      sim_grid_pos_y: 60314.0742
    }
    terrain_level_point {
      sim_grid_pos_x: 2021145
      sim_grid_pos_y: 60150.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2021156.12
      sim_grid_pos_y: 59701.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 2018844.75
      sim_grid_pos_y: 59554.2891
    }
    terrain_level_point {
      sim_grid_pos_x: 2018447.88
      sim_grid_pos_y: 58811.6172
    }
    terrain_level_point {
      sim_grid_pos_x: 2019155.38
      sim_grid_pos_y: 58844.5703
    }
    terrain_level_point {
      sim_grid_pos_x: 2020355.38
      sim_grid_pos_y: 58438.8516
    }
    terrain_level_point {
      sim_grid_pos_x: 2020221.75
      sim_grid_pos_y: 57794.2031
    }
    terrain_level_point {
      sim_grid_pos_x: 2020488.12
      sim_grid_pos_y: 56968.4414
    }
    terrain_level_point {
      sim_grid_pos_x: 2021758.12
      sim_grid_pos_y: 56974.7031
    }
    terrain_level_point {
      sim_grid_pos_x: 2022680.25
      sim_grid_pos_y: 57469.832
    }
    terrain_level_point {
      sim_grid_pos_x: 2025011.12
      sim_grid_pos_y: 56425.9
    }
    terrain_level_point {
      sim_grid_pos_x: 2024807.75
      sim_grid_pos_y: 55602.332
    }
    terrain_level_point {
      sim_grid_pos_x: 2025193.25
      sim_grid_pos_y: 55584.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 2024040.5
      sim_grid_pos_y: 54184.2539
    }
    terrain_level_point {
      sim_grid_pos_x: 2022837.62
      sim_grid_pos_y: 53646.3086
    }
    terrain_level_point {
      sim_grid_pos_x: 2022129.12
      sim_grid_pos_y: 53467.0156
    }
    terrain_level_point {
      sim_grid_pos_x: 2022253.75
      sim_grid_pos_y: 52630.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2021037.25
      sim_grid_pos_y: 52109.3828
    }
    terrain_level_point {
      sim_grid_pos_x: 2020842.38
      sim_grid_pos_y: 51805.4883
    }
    terrain_level_point {
      sim_grid_pos_x: 2020279.25
      sim_grid_pos_y: 51730.3633
    }
    terrain_level_point {
      sim_grid_pos_x: 2017848.12
      sim_grid_pos_y: 52617.6094
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2020273.62
      sim_grid_pos_y: 51677.8867
    }
    terrain_level_point {
      sim_grid_pos_x: 2017812.38
      sim_grid_pos_y: 52576.0938
    }
    terrain_level_point {
      sim_grid_pos_x: 2016294.5
      sim_grid_pos_y: 55367.9766
    }
    terrain_level_point {
      sim_grid_pos_x: 2016135
      sim_grid_pos_y: 59352.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 2016508.5
      sim_grid_pos_y: 60619.1172
    }
    terrain_level_point {
      sim_grid_pos_x: 2016799.5
      sim_grid_pos_y: 60835.5938
    }
    terrain_level_point {
      sim_grid_pos_x: 2017811.38
      sim_grid_pos_y: 59984.7656
    }
    terrain_level_point {
      sim_grid_pos_x: 2018321.88
      sim_grid_pos_y: 60366.3359
    }
    terrain_level_point {
      sim_grid_pos_x: 2021195
      sim_grid_pos_y: 60199.1875
    }
    terrain_level_point {
      sim_grid_pos_x: 2021208.62
      sim_grid_pos_y: 59653.9258
    }
    terrain_level_point {
      sim_grid_pos_x: 2018876.5
      sim_grid_pos_y: 59504.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 2018535.62
      sim_grid_pos_y: 58867.0156
    }
    terrain_level_point {
      sim_grid_pos_x: 2019162.75
      sim_grid_pos_y: 58896.2266
    }
    terrain_level_point {
      sim_grid_pos_x: 2020414.75
      sim_grid_pos_y: 58472.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2020274.75
      sim_grid_pos_y: 57797.0469
    }
    terrain_level_point {
      sim_grid_pos_x: 2020525.38
      sim_grid_pos_y: 57019.8867
    }
    terrain_level_point {
      sim_grid_pos_x: 2021745.12
      sim_grid_pos_y: 57025.8945
    }
    terrain_level_point {
      sim_grid_pos_x: 2022678.12
      sim_grid_pos_y: 57526.9258
    }
    terrain_level_point {
      sim_grid_pos_x: 2025071.12
      sim_grid_pos_y: 56455.1758
    }
    terrain_level_point {
      sim_grid_pos_x: 2024872.5
      sim_grid_pos_y: 55650.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 2025227.25
      sim_grid_pos_y: 55634.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2025253
      sim_grid_pos_y: 55576.8359
    }
    terrain_level_point {
      sim_grid_pos_x: 2024072.38
      sim_grid_pos_y: 54142.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2022854.5
      sim_grid_pos_y: 53597.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2022186.62
      sim_grid_pos_y: 53428.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2022310.38
      sim_grid_pos_y: 52598.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2021071.88
      sim_grid_pos_y: 52068.457
    }
    terrain_level_point {
      sim_grid_pos_x: 2020872.75
      sim_grid_pos_y: 51757.8164
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2020267.88
      sim_grid_pos_y: 51625.4062
    }
    terrain_level_point {
      sim_grid_pos_x: 2017776.62
      sim_grid_pos_y: 52534.5859
    }
    terrain_level_point {
      sim_grid_pos_x: 2016243.75
      sim_grid_pos_y: 55353.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 2016083.5
      sim_grid_pos_y: 59359.3359
    }
    terrain_level_point {
      sim_grid_pos_x: 2016464.12
      sim_grid_pos_y: 60650.0234
    }
    terrain_level_point {
      sim_grid_pos_x: 2016801.5
      sim_grid_pos_y: 60900.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 2017813.25
      sim_grid_pos_y: 60050.1641
    }
    terrain_level_point {
      sim_grid_pos_x: 2018306.12
      sim_grid_pos_y: 60418.6055
    }
    terrain_level_point {
      sim_grid_pos_x: 2021245.12
      sim_grid_pos_y: 60247.6172
    }
    terrain_level_point {
      sim_grid_pos_x: 2021261.12
      sim_grid_pos_y: 59605.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 2018908.25
      sim_grid_pos_y: 59455.6055
    }
    terrain_level_point {
      sim_grid_pos_x: 2018623.38
      sim_grid_pos_y: 58922.4258
    }
    terrain_level_point {
      sim_grid_pos_x: 2.01917e+06
      sim_grid_pos_y: 58947.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2020474.12
      sim_grid_pos_y: 58506.9062
    }
    terrain_level_point {
      sim_grid_pos_x: 2020327.62
      sim_grid_pos_y: 57799.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 2020562.62
      sim_grid_pos_y: 57071.3242
    }
    terrain_level_point {
      sim_grid_pos_x: 2021732.12
      sim_grid_pos_y: 57077.0938
    }
    terrain_level_point {
      sim_grid_pos_x: 2022676.12
      sim_grid_pos_y: 57584.0039
    }
    terrain_level_point {
      sim_grid_pos_x: 2025131.12
      sim_grid_pos_y: 56484.4648
    }
    terrain_level_point {
      sim_grid_pos_x: 2024937.25
      sim_grid_pos_y: 55699.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2025261.25
      sim_grid_pos_y: 55684.5156
    }
    terrain_level_point {
      sim_grid_pos_x: 2025312.75
      sim_grid_pos_y: 55568.7148
    }
    terrain_level_point {
      sim_grid_pos_x: 2024104.38
      sim_grid_pos_y: 54100.4961
    }
    terrain_level_point {
      sim_grid_pos_x: 2022871.38
      sim_grid_pos_y: 53549.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 2022244.25
      sim_grid_pos_y: 53390.3867
    }
    terrain_level_point {
      sim_grid_pos_x: 2022366.88
      sim_grid_pos_y: 52567.1367
    }
    terrain_level_point {
      sim_grid_pos_x: 2021106.5
      sim_grid_pos_y: 52027.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 2020903.12
      sim_grid_pos_y: 51710.1445
    }
  }
}
