terrain_level_data {
  terrain_level: 1680
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2581832.25
      sim_grid_pos_y: 1436902.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.58173e+06
      sim_grid_pos_y: 1437104.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2581742.75
      sim_grid_pos_y: 1437386.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581602.25
      sim_grid_pos_y: 1437425.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2581474.5
      sim_grid_pos_y: 1437330.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2581257.5
      sim_grid_pos_y: 1437301.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2581091.5
      sim_grid_pos_y: 1437178.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2581085
      sim_grid_pos_y: 1436772.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2581270.25
      sim_grid_pos_y: 1436620.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2581615
      sim_grid_pos_y: 1436640.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2581640.25
      sim_grid_pos_y: 1436590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581893
      sim_grid_pos_y: 1436895.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581781.75
      sim_grid_pos_y: 1437115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581795.75
      sim_grid_pos_y: 1437425.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581591.75
      sim_grid_pos_y: 1437481.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581454.75
      sim_grid_pos_y: 1437379.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2581237.75
      sim_grid_pos_y: 1437350.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2581040.5
      sim_grid_pos_y: 1437204.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581033.5
      sim_grid_pos_y: 1436748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2581253.25
      sim_grid_pos_y: 1436568
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2581665.5
      sim_grid_pos_y: 1436540.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2581954
      sim_grid_pos_y: 1436888.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2581833.75
      sim_grid_pos_y: 1437126.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2581849
      sim_grid_pos_y: 1437463.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581581.25
      sim_grid_pos_y: 1437537.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2581434.75
      sim_grid_pos_y: 1437428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581217.75
      sim_grid_pos_y: 1437399.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2580989.75
      sim_grid_pos_y: 1437230.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580981.75
      sim_grid_pos_y: 1436724.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2581236.25
      sim_grid_pos_y: 1436515.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2581690.75
      sim_grid_pos_y: 1436490.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2582015
      sim_grid_pos_y: 1436882.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2581885.5
      sim_grid_pos_y: 1437138
    }
    terrain_level_point {
      sim_grid_pos_x: 2581902
      sim_grid_pos_y: 1437502.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581570.75
      sim_grid_pos_y: 1437593.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2581414.75
      sim_grid_pos_y: 1437477.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581198
      sim_grid_pos_y: 1437448.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2580939
      sim_grid_pos_y: 1437257.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2580930.25
      sim_grid_pos_y: 1436700.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2581219
      sim_grid_pos_y: 1436463.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2581716
      sim_grid_pos_y: 1436440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2582075.75
      sim_grid_pos_y: 1436875.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581937.25
      sim_grid_pos_y: 1437149.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2581955
      sim_grid_pos_y: 1437540.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.58156e+06
      sim_grid_pos_y: 1.43765e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2581394.75
      sim_grid_pos_y: 1437526.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2581178.25
      sim_grid_pos_y: 1437497.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580888
      sim_grid_pos_y: 1437283.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2580878.5
      sim_grid_pos_y: 1436676.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581202
      sim_grid_pos_y: 1436411
    }
  }
}
terrain_level_data {
  terrain_level: 1716
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2580765.5
      sim_grid_pos_y: 1436565.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580771.25
      sim_grid_pos_y: 1436744
    }
    terrain_level_point {
      sim_grid_pos_x: 2580932.5
      sim_grid_pos_y: 1436730.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2580939.25
      sim_grid_pos_y: 1436562.12
    }
  }
}
terrain_level_data {
  terrain_level: 1340
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2582825.75
      sim_grid_pos_y: 1437361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2582336.75
      sim_grid_pos_y: 1438267.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2582851
      sim_grid_pos_y: 1438573.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2583327.75
      sim_grid_pos_y: 1437681.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2582806.75
      sim_grid_pos_y: 1437289
    }
    terrain_level_point {
      sim_grid_pos_x: 2582268.25
      sim_grid_pos_y: 1438286.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2582871
      sim_grid_pos_y: 1438645.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2583395.25
      sim_grid_pos_y: 1437663.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2582788
      sim_grid_pos_y: 1437216.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2582199.75
      sim_grid_pos_y: 1438305.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2582891
      sim_grid_pos_y: 1438716.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2583462.75
      sim_grid_pos_y: 1437645.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2582769
      sim_grid_pos_y: 1437143.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2582131.25
      sim_grid_pos_y: 1438324.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2582911
      sim_grid_pos_y: 1438788.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2583530.5
      sim_grid_pos_y: 1437627.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2.58275e+06
      sim_grid_pos_y: 1437070.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2582062.75
      sim_grid_pos_y: 1438343.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2582930.75
      sim_grid_pos_y: 1438859.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2583598
      sim_grid_pos_y: 1.43761e+06
    }
  }
}
terrain_level_data {
  terrain_level: 1170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2578902.75
      sim_grid_pos_y: 1437189.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.57889e+06
      sim_grid_pos_y: 1437557.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2579617.75
      sim_grid_pos_y: 1437553.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2579406.5
      sim_grid_pos_y: 1437188.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2579436
      sim_grid_pos_y: 1437137
    }
    terrain_level_point {
      sim_grid_pos_x: 2578853.25
      sim_grid_pos_y: 1437138.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2578837
      sim_grid_pos_y: 1437609.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2579706.25
      sim_grid_pos_y: 1437603.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2579465.5
      sim_grid_pos_y: 1437085.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2578803.75
      sim_grid_pos_y: 1437086.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2578784
      sim_grid_pos_y: 1437661.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2579794.75
      sim_grid_pos_y: 1437654.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2579495
      sim_grid_pos_y: 1437034.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2578754.25
      sim_grid_pos_y: 1437035.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2578730.75
      sim_grid_pos_y: 1437712.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2579883.5
      sim_grid_pos_y: 1437705.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2579524.5
      sim_grid_pos_y: 1436983.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2578704.5
      sim_grid_pos_y: 1436984.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2578677.75
      sim_grid_pos_y: 1437764.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2579972
      sim_grid_pos_y: 1437755.75
    }
  }
}
terrain_level_data {
  terrain_level: 1630
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2580629.75
      sim_grid_pos_y: 1436326.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2580543.75
      sim_grid_pos_y: 1436263.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580552.5
      sim_grid_pos_y: 1435997.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580599
      sim_grid_pos_y: 1435835.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2580746.75
      sim_grid_pos_y: 1435729.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580804.5
      sim_grid_pos_y: 1435862.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580727
      sim_grid_pos_y: 1436027.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2580743.25
      sim_grid_pos_y: 1436263
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2580860.75
      sim_grid_pos_y: 1435863.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580779.25
      sim_grid_pos_y: 1436037.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2580796.5
      sim_grid_pos_y: 1436291.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580626
      sim_grid_pos_y: 1436387.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580491.75
      sim_grid_pos_y: 1436289
    }
    terrain_level_point {
      sim_grid_pos_x: 2580501.25
      sim_grid_pos_y: 1435989.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580554.5
      sim_grid_pos_y: 1435804.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580768.25
      sim_grid_pos_y: 1435651
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2580917.25
      sim_grid_pos_y: 1435864.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2580831.25
      sim_grid_pos_y: 1436046.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580849.75
      sim_grid_pos_y: 1436320.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580622.25
      sim_grid_pos_y: 1436448.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580439.5
      sim_grid_pos_y: 1436314.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2580450.25
      sim_grid_pos_y: 1435981.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580510.25
      sim_grid_pos_y: 1435773.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.58079e+06
      sim_grid_pos_y: 1435572.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2580973.5
      sim_grid_pos_y: 1435865.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2580883.25
      sim_grid_pos_y: 1436056.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580903.25
      sim_grid_pos_y: 1436349.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580618.75
      sim_grid_pos_y: 1436509.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2580387.5
      sim_grid_pos_y: 1436339.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580399.25
      sim_grid_pos_y: 1435973.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580466
      sim_grid_pos_y: 1435741.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580811.75
      sim_grid_pos_y: 1435493.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2581029.75
      sim_grid_pos_y: 1435866
    }
    terrain_level_point {
      sim_grid_pos_x: 2580935.25
      sim_grid_pos_y: 1436066.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580956.5
      sim_grid_pos_y: 1436378.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2580615
      sim_grid_pos_y: 1436570.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2580335.5
      sim_grid_pos_y: 1436365
    }
    terrain_level_point {
      sim_grid_pos_x: 2580348.25
      sim_grid_pos_y: 1435965.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580421.5
      sim_grid_pos_y: 1435710.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580833.25
      sim_grid_pos_y: 1435415.12
    }
  }
}
terrain_level_data {
  terrain_level: 1495
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2580892.5
      sim_grid_pos_y: 1435153.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2580775
      sim_grid_pos_y: 1435276.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580732.25
      sim_grid_pos_y: 1435510.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2580901.5
      sim_grid_pos_y: 1435505.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2581011
      sim_grid_pos_y: 1435262.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2.58089e+06
      sim_grid_pos_y: 1435081.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2580727.25
      sim_grid_pos_y: 1435252.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2580670.5
      sim_grid_pos_y: 1435564
    }
    terrain_level_point {
      sim_grid_pos_x: 2580935
      sim_grid_pos_y: 1435555.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2581073
      sim_grid_pos_y: 1435249.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2580887.5
      sim_grid_pos_y: 1435009.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2580679.5
      sim_grid_pos_y: 1435228
    }
    terrain_level_point {
      sim_grid_pos_x: 2580608.5
      sim_grid_pos_y: 1435617.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2580968.75
      sim_grid_pos_y: 1435606
    }
    terrain_level_point {
      sim_grid_pos_x: 2581135
      sim_grid_pos_y: 1435236.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2580885.25
      sim_grid_pos_y: 1434938.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2580632
      sim_grid_pos_y: 1435203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2580546.75
      sim_grid_pos_y: 1435670.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2581002.25
      sim_grid_pos_y: 1435656.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2581196.75
      sim_grid_pos_y: 1435224
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2580882.75
      sim_grid_pos_y: 1434866.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2580584.25
      sim_grid_pos_y: 1435179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2580485
      sim_grid_pos_y: 1435723.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2581036
      sim_grid_pos_y: 1435706.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2581258.75
      sim_grid_pos_y: 1435211.25
    }
  }
}
