terrain_level_data {
  terrain_level: 398
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1596495.38
      sim_grid_pos_y: 1438862.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1596573.12
      sim_grid_pos_y: 1439379.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1596479.75
      sim_grid_pos_y: 1439753.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1596796.62
      sim_grid_pos_y: 1440094.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1597091.12
      sim_grid_pos_y: 1439722.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1596944.62
      sim_grid_pos_y: 1439197.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1596860.75
      sim_grid_pos_y: 1438863.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1596435.75
      sim_grid_pos_y: 1438811.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1596520.88
      sim_grid_pos_y: 1439377.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1596423.25
      sim_grid_pos_y: 1439768.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1596799.75
      sim_grid_pos_y: 1440173.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1597147.5
      sim_grid_pos_y: 1439734
    }
    terrain_level_point {
      sim_grid_pos_x: 1596994.25
      sim_grid_pos_y: 1439184.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1596900.75
      sim_grid_pos_y: 1438812.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1596376.25
      sim_grid_pos_y: 1438759.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1596468.75
      sim_grid_pos_y: 1439374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1596366.88
      sim_grid_pos_y: 1439782.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1596802.88
      sim_grid_pos_y: 1440252.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1597203.88
      sim_grid_pos_y: 1439745.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1597043.62
      sim_grid_pos_y: 1439170.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1596940.75
      sim_grid_pos_y: 1438761.12
    }
  }
}
