terrain_level_data {
  terrain_level: 472
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1507584.38
      sim_grid_pos_y: 1642236.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1507357.88
      sim_grid_pos_y: 1642184
    }
    terrain_level_point {
      sim_grid_pos_x: 1507059.12
      sim_grid_pos_y: 1642151.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1506834.5
      sim_grid_pos_y: 1642100.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1506570.62
      sim_grid_pos_y: 1642050.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1506344.5
      sim_grid_pos_y: 1642129.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1506156.5
      sim_grid_pos_y: 1642016
    }
    terrain_level_point {
      sim_grid_pos_x: 1506055.88
      sim_grid_pos_y: 1642077
    }
    terrain_level_point {
      sim_grid_pos_x: 1505861.25
      sim_grid_pos_y: 1641926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505741.5
      sim_grid_pos_y: 1641845.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1505576.75
      sim_grid_pos_y: 1641859
    }
    terrain_level_point {
      sim_grid_pos_x: 1505147.88
      sim_grid_pos_y: 1642256.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504949.88
      sim_grid_pos_y: 1642274.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1504919.62
      sim_grid_pos_y: 1641884.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1504544.75
      sim_grid_pos_y: 1641207.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1504577.5
      sim_grid_pos_y: 1640783.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1504935.62
      sim_grid_pos_y: 1640791.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505425
      sim_grid_pos_y: 1640676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505862.62
      sim_grid_pos_y: 1640531.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1506709.62
      sim_grid_pos_y: 1640750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1506986.12
      sim_grid_pos_y: 1640866.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1507723.88
      sim_grid_pos_y: 1640801.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1509663.12
      sim_grid_pos_y: 1641043.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1509721.62
      sim_grid_pos_y: 1642314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1509677.25
      sim_grid_pos_y: 1644557.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508505
      sim_grid_pos_y: 1644201.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.50848e+06
      sim_grid_pos_y: 1643681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1508686.62
      sim_grid_pos_y: 1643264.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508768.5
      sim_grid_pos_y: 1642998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1508638
      sim_grid_pos_y: 1642878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508664.25
      sim_grid_pos_y: 1642597.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508646.38
      sim_grid_pos_y: 1642495.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1508525
      sim_grid_pos_y: 1642449.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1508495.12
      sim_grid_pos_y: 1642362.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508215.75
      sim_grid_pos_y: 1642332.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1508165
      sim_grid_pos_y: 1642107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1508145.5
      sim_grid_pos_y: 1641984.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508005.25
      sim_grid_pos_y: 1642121.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1507923.88
      sim_grid_pos_y: 1642187.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1507744.75
      sim_grid_pos_y: 1642143.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1506742.38
      sim_grid_pos_y: 1640653.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1507002.38
      sim_grid_pos_y: 1640761.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1507725.75
      sim_grid_pos_y: 1640698.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1509761.62
      sim_grid_pos_y: 1640952.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1509824.25
      sim_grid_pos_y: 1642312.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1509777.12
      sim_grid_pos_y: 1644695
    }
    terrain_level_point {
      sim_grid_pos_x: 1508406.12
      sim_grid_pos_y: 1644278.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1508376.38
      sim_grid_pos_y: 1643660.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1508591.12
      sim_grid_pos_y: 1643226.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1508651.5
      sim_grid_pos_y: 1643030.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508531.25
      sim_grid_pos_y: 1642919.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508560.88
      sim_grid_pos_y: 1642601.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1508555.5
      sim_grid_pos_y: 1642570.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1508443.62
      sim_grid_pos_y: 1642528.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1508419.25
      sim_grid_pos_y: 1642457.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508131.88
      sim_grid_pos_y: 1642426.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508079.12
      sim_grid_pos_y: 1642192.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1508073.5
      sim_grid_pos_y: 1642198
    }
    terrain_level_point {
      sim_grid_pos_x: 1507949
      sim_grid_pos_y: 1642299
    }
    terrain_level_point {
      sim_grid_pos_x: 1507760.38
      sim_grid_pos_y: 1642253
    }
    terrain_level_point {
      sim_grid_pos_x: 1507600.62
      sim_grid_pos_y: 1642345.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1507340.75
      sim_grid_pos_y: 1642285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1507042.12
      sim_grid_pos_y: 1642252.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1506813.75
      sim_grid_pos_y: 1642200.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1506578.5
      sim_grid_pos_y: 1642156
    }
    terrain_level_point {
      sim_grid_pos_x: 1506332.88
      sim_grid_pos_y: 1642242.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1506156.62
      sim_grid_pos_y: 1642135.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1506048.88
      sim_grid_pos_y: 1642201.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1505801
      sim_grid_pos_y: 1642009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505713.88
      sim_grid_pos_y: 1641950.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505620.5
      sim_grid_pos_y: 1641958.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1505191.88
      sim_grid_pos_y: 1642355.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504855.62
      sim_grid_pos_y: 1642385.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1504819.12
      sim_grid_pos_y: 1641914.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504440.12
      sim_grid_pos_y: 1641230.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1504482.75
      sim_grid_pos_y: 1640679.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1504924.75
      sim_grid_pos_y: 1640688.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1505397
      sim_grid_pos_y: 1640577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1505859
      sim_grid_pos_y: 1640424.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1506775.12
      sim_grid_pos_y: 1640555.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1507018.62
      sim_grid_pos_y: 1640657.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507727.62
      sim_grid_pos_y: 1640595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.50986e+06
      sim_grid_pos_y: 1640861.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1509926.75
      sim_grid_pos_y: 1642311.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1509876.88
      sim_grid_pos_y: 1644832.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508307.12
      sim_grid_pos_y: 1644355.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1508272.62
      sim_grid_pos_y: 1643638.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508495.5
      sim_grid_pos_y: 1643188.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1508534.5
      sim_grid_pos_y: 1643061.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1508424.38
      sim_grid_pos_y: 1642960.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508454.12
      sim_grid_pos_y: 1642642.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1508362.25
      sim_grid_pos_y: 1642607.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508343.38
      sim_grid_pos_y: 1642552.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1508048
      sim_grid_pos_y: 1642520.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508015.62
      sim_grid_pos_y: 1642377
    }
    terrain_level_point {
      sim_grid_pos_x: 1507974
      sim_grid_pos_y: 1642410.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1507776
      sim_grid_pos_y: 1642362.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1507617
      sim_grid_pos_y: 1642454
    }
    terrain_level_point {
      sim_grid_pos_x: 1507323.62
      sim_grid_pos_y: 1642386.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507025.25
      sim_grid_pos_y: 1642354
    }
    terrain_level_point {
      sim_grid_pos_x: 1506792.5
      sim_grid_pos_y: 1642301.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1506586.5
      sim_grid_pos_y: 1642261.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1506321.25
      sim_grid_pos_y: 1642355.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1506156.62
      sim_grid_pos_y: 1642255.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1506041.75
      sim_grid_pos_y: 1642325.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1505741
      sim_grid_pos_y: 1642092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1505686.38
      sim_grid_pos_y: 1642055.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1505664.25
      sim_grid_pos_y: 1642057.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505236
      sim_grid_pos_y: 1642454.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504761.5
      sim_grid_pos_y: 1642497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1504718.62
      sim_grid_pos_y: 1641944.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1504335.62
      sim_grid_pos_y: 1641252.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1504388
      sim_grid_pos_y: 1640574.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504914
      sim_grid_pos_y: 1640585.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1505369.12
      sim_grid_pos_y: 1640479
    }
    terrain_level_point {
      sim_grid_pos_x: 1505855.5
      sim_grid_pos_y: 1640317.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1506808
      sim_grid_pos_y: 1640458.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507034.88
      sim_grid_pos_y: 1640553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1507729.62
      sim_grid_pos_y: 1640492.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1509958.5
      sim_grid_pos_y: 1.64077e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1510029.38
      sim_grid_pos_y: 1642310.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1509976.75
      sim_grid_pos_y: 1.64497e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1508208.25
      sim_grid_pos_y: 1644432.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1508169
      sim_grid_pos_y: 1643616.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.5084e+06
      sim_grid_pos_y: 1643150.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1508417.38
      sim_grid_pos_y: 1643093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508317.62
      sim_grid_pos_y: 1643001.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508344.75
      sim_grid_pos_y: 1642710.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508280.88
      sim_grid_pos_y: 1642686.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1508267.5
      sim_grid_pos_y: 1642647.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1507964.12
      sim_grid_pos_y: 1642614.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507940.12
      sim_grid_pos_y: 1642508
    }
    terrain_level_point {
      sim_grid_pos_x: 1507791.62
      sim_grid_pos_y: 1642471.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507633.25
      sim_grid_pos_y: 1642563
    }
    terrain_level_point {
      sim_grid_pos_x: 1507306.5
      sim_grid_pos_y: 1642487.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1507008.25
      sim_grid_pos_y: 1642455.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1506771.75
      sim_grid_pos_y: 1642401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1506594.38
      sim_grid_pos_y: 1642367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1506309.62
      sim_grid_pos_y: 1642467.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1506156.75
      sim_grid_pos_y: 1642375.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1506034.75
      sim_grid_pos_y: 1642449.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505684.5
      sim_grid_pos_y: 1642178.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.50528e+06
      sim_grid_pos_y: 1642553.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504667.25
      sim_grid_pos_y: 1642608.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1504618.12
      sim_grid_pos_y: 1641975.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1504231
      sim_grid_pos_y: 1641275.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1504293.25
      sim_grid_pos_y: 1640470.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1504903.25
      sim_grid_pos_y: 1640483.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1505341.12
      sim_grid_pos_y: 1640380.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1505851.88
      sim_grid_pos_y: 1640210.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1506840.75
      sim_grid_pos_y: 1640361.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1507051
      sim_grid_pos_y: 1640448.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1507731.5
      sim_grid_pos_y: 1640389.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1510056.88
      sim_grid_pos_y: 1640679
    }
    terrain_level_point {
      sim_grid_pos_x: 1510131.88
      sim_grid_pos_y: 1642308.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1510076.62
      sim_grid_pos_y: 1645107.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508109.25
      sim_grid_pos_y: 1644509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508065.25
      sim_grid_pos_y: 1643595.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1508298.75
      sim_grid_pos_y: 1643123.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508210.75
      sim_grid_pos_y: 1643042.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1508235.38
      sim_grid_pos_y: 1642778.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1508199.38
      sim_grid_pos_y: 1642765.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1508191.5
      sim_grid_pos_y: 1642742.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1507880.38
      sim_grid_pos_y: 1642708.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1507854.12
      sim_grid_pos_y: 1642592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1507807.25
      sim_grid_pos_y: 1642581
    }
    terrain_level_point {
      sim_grid_pos_x: 1507649.62
      sim_grid_pos_y: 1642672
    }
    terrain_level_point {
      sim_grid_pos_x: 1507289.38
      sim_grid_pos_y: 1642589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1506991.38
      sim_grid_pos_y: 1642556.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1506750.62
      sim_grid_pos_y: 1642502
    }
    terrain_level_point {
      sim_grid_pos_x: 1506602.38
      sim_grid_pos_y: 1642473.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1506298
      sim_grid_pos_y: 1642580.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1506156.88
      sim_grid_pos_y: 1642495.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1506027.75
      sim_grid_pos_y: 1642573.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1505690.5
      sim_grid_pos_y: 1642312.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1505324
      sim_grid_pos_y: 1642652.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1504573.12
      sim_grid_pos_y: 1.64272e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1504517.62
      sim_grid_pos_y: 1642005.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1504126.38
      sim_grid_pos_y: 1641298.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1504198.5
      sim_grid_pos_y: 1640365.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1504892.38
      sim_grid_pos_y: 1640380.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1505313.38
      sim_grid_pos_y: 1640281.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1505848.38
      sim_grid_pos_y: 1640104
    }
  }
}
