terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 447509
      sim_grid_pos_y: 2155218.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449505.031
      sim_grid_pos_y: 2155219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449261.781
      sim_grid_pos_y: 2152246.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449331.469
      sim_grid_pos_y: 2150794.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449650.25
      sim_grid_pos_y: 2150154.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449789.906
      sim_grid_pos_y: 2149656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449735.938
      sim_grid_pos_y: 2149308.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449550.031
      sim_grid_pos_y: 2149032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 448919.812
      sim_grid_pos_y: 2148573.25
    }
    terrain_level_point {
      sim_grid_pos_x: 447462
      sim_grid_pos_y: 2150740.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 448912.094
      sim_grid_pos_y: 2148529.5
    }
    terrain_level_point {
      sim_grid_pos_x: 447431.156
      sim_grid_pos_y: 2150731
    }
    terrain_level_point {
      sim_grid_pos_x: 447478.562
      sim_grid_pos_y: 2155249.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449538.406
      sim_grid_pos_y: 2.15525e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 449292.594
      sim_grid_pos_y: 2152245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449361.875
      sim_grid_pos_y: 2150802.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449679.094
      sim_grid_pos_y: 2150166
    }
    terrain_level_point {
      sim_grid_pos_x: 449821.344
      sim_grid_pos_y: 2149658.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449765.25
      sim_grid_pos_y: 2149297
    }
    terrain_level_point {
      sim_grid_pos_x: 449572.531
      sim_grid_pos_y: 2149010.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 448904.406
      sim_grid_pos_y: 2148486
    }
    terrain_level_point {
      sim_grid_pos_x: 447400.281
      sim_grid_pos_y: 2150721.75
    }
    terrain_level_point {
      sim_grid_pos_x: 447448.125
      sim_grid_pos_y: 2155280.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449571.781
      sim_grid_pos_y: 2155280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449323.406
      sim_grid_pos_y: 2152245.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449392.281
      sim_grid_pos_y: 2.15081e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 449707.938
      sim_grid_pos_y: 2150177
    }
    terrain_level_point {
      sim_grid_pos_x: 449852.75
      sim_grid_pos_y: 2149660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449794.625
      sim_grid_pos_y: 2149285.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449595.031
      sim_grid_pos_y: 2148989
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 448896.688
      sim_grid_pos_y: 2148442.25
    }
    terrain_level_point {
      sim_grid_pos_x: 447369.438
      sim_grid_pos_y: 2150712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 447417.688
      sim_grid_pos_y: 2155311
    }
    terrain_level_point {
      sim_grid_pos_x: 449605.156
      sim_grid_pos_y: 2155311.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449354.219
      sim_grid_pos_y: 2152244.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449422.719
      sim_grid_pos_y: 2150818
    }
    terrain_level_point {
      sim_grid_pos_x: 449736.75
      sim_grid_pos_y: 2150188.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449884.188
      sim_grid_pos_y: 2149662.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449823.938
      sim_grid_pos_y: 2149274.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449617.5
      sim_grid_pos_y: 2148967.25
    }
  }
}
