terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2360902.75
      sim_grid_pos_y: 2017183.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2361487
      sim_grid_pos_y: 2017576.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2362160.25
      sim_grid_pos_y: 2017620.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.36288e+06
      sim_grid_pos_y: 2017493.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2363823
      sim_grid_pos_y: 2017726.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2364363.5
      sim_grid_pos_y: 2018025.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364571.25
      sim_grid_pos_y: 2018263.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2364744
      sim_grid_pos_y: 2018606.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2364262.25
      sim_grid_pos_y: 2018536.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2364038.75
      sim_grid_pos_y: 2018290.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2363762.75
      sim_grid_pos_y: 2018226.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2363575.75
      sim_grid_pos_y: 2018577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2363376.5
      sim_grid_pos_y: 2018527.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2363622
      sim_grid_pos_y: 2018119
    }
    terrain_level_point {
      sim_grid_pos_x: 2363095.25
      sim_grid_pos_y: 2017975.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360176.25
      sim_grid_pos_y: 2018379.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2361521.25
      sim_grid_pos_y: 2017476.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2362154.5
      sim_grid_pos_y: 2017517.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2362883.5
      sim_grid_pos_y: 2017388.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2363860.75
      sim_grid_pos_y: 2017630.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2364428.75
      sim_grid_pos_y: 2017944.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364657
      sim_grid_pos_y: 2018205.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2364863.5
      sim_grid_pos_y: 2018616.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2364790.75
      sim_grid_pos_y: 2018717.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2364211
      sim_grid_pos_y: 2018632.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2363984.25
      sim_grid_pos_y: 2018382.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2363816.25
      sim_grid_pos_y: 2018343.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2363628.5
      sim_grid_pos_y: 2018696.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2363217.5
      sim_grid_pos_y: 2018592.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2363464.25
      sim_grid_pos_y: 2018182.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2363088.75
      sim_grid_pos_y: 2018080.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360126
      sim_grid_pos_y: 2018489.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360055
      sim_grid_pos_y: 2018381.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2360870.75
      sim_grid_pos_y: 2017038.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2361555.5
      sim_grid_pos_y: 2017375.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2362149
      sim_grid_pos_y: 2017414
    }
    terrain_level_point {
      sim_grid_pos_x: 2362887.25
      sim_grid_pos_y: 2017283.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2363898.5
      sim_grid_pos_y: 2017534.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2364494.25
      sim_grid_pos_y: 2017863.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364742.75
      sim_grid_pos_y: 2018147.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364983
      sim_grid_pos_y: 2018625.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2364837.5
      sim_grid_pos_y: 2018827.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2364159.75
      sim_grid_pos_y: 2018728.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.36393e+06
      sim_grid_pos_y: 2018475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2363869.75
      sim_grid_pos_y: 2018461.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2363681.25
      sim_grid_pos_y: 2018815.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2363058.5
      sim_grid_pos_y: 2018658.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2363306.5
      sim_grid_pos_y: 2018245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2363082
      sim_grid_pos_y: 2018184.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2360076
      sim_grid_pos_y: 2018600.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2359933.75
      sim_grid_pos_y: 2018383.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2360839
      sim_grid_pos_y: 2016893.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2361589.75
      sim_grid_pos_y: 2017275.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2362143.25
      sim_grid_pos_y: 2017310.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2362890.75
      sim_grid_pos_y: 2017179.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2363936.25
      sim_grid_pos_y: 2017437.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364559.5
      sim_grid_pos_y: 2017782.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2364828.5
      sim_grid_pos_y: 2018090.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2365102.75
      sim_grid_pos_y: 2018635.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2364884.25
      sim_grid_pos_y: 2018938
    }
    terrain_level_point {
      sim_grid_pos_x: 2364108.75
      sim_grid_pos_y: 2018825.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2363909.25
      sim_grid_pos_y: 2018605.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2363734
      sim_grid_pos_y: 2018935
    }
    terrain_level_point {
      sim_grid_pos_x: 2362899.5
      sim_grid_pos_y: 2018723.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2363148.75
      sim_grid_pos_y: 2018309.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2363075.25
      sim_grid_pos_y: 2018289.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360025.75
      sim_grid_pos_y: 2018710.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2359812.5
      sim_grid_pos_y: 2018385.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360807
      sim_grid_pos_y: 2016748.62
    }
  }
}
terrain_level_data {
  terrain_level: 225
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2361057
      sim_grid_pos_y: 2.02396e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2361029
      sim_grid_pos_y: 2024111.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361084.75
      sim_grid_pos_y: 2024195.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361202.5
      sim_grid_pos_y: 2024192.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361256.75
      sim_grid_pos_y: 2024119.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2361228
      sim_grid_pos_y: 2023962.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2361035.25
      sim_grid_pos_y: 2023943.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360974.75
      sim_grid_pos_y: 2024122.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361057.5
      sim_grid_pos_y: 2024247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2361228.75
      sim_grid_pos_y: 2024243.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361311.25
      sim_grid_pos_y: 2024132.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361263.75
      sim_grid_pos_y: 2023945
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2361027.25
      sim_grid_pos_y: 2023930.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2360920.75
      sim_grid_pos_y: 2024133.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361030.5
      sim_grid_pos_y: 2024299.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2361255
      sim_grid_pos_y: 2024293.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2361365.75
      sim_grid_pos_y: 2024145
    }
    terrain_level_point {
      sim_grid_pos_x: 2361290.25
      sim_grid_pos_y: 2023931
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2360982
      sim_grid_pos_y: 2023918.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360866.5
      sim_grid_pos_y: 2024144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361003.25
      sim_grid_pos_y: 2024351.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361281
      sim_grid_pos_y: 2024344.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2361420.25
      sim_grid_pos_y: 2024157.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2361377
      sim_grid_pos_y: 2023915.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2360977.5
      sim_grid_pos_y: 2023902.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2360812.5
      sim_grid_pos_y: 2024155.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2360976.25
      sim_grid_pos_y: 2024403.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2361307.25
      sim_grid_pos_y: 2024395
    }
    terrain_level_point {
      sim_grid_pos_x: 2361474.5
      sim_grid_pos_y: 2024170.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2361412.25
      sim_grid_pos_y: 2023900.38
    }
  }
}
terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2360432.25
      sim_grid_pos_y: 2015249.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2359919.75
      sim_grid_pos_y: 2015160.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2358435.25
      sim_grid_pos_y: 2023710.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359024.5
      sim_grid_pos_y: 2023682.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2359878
      sim_grid_pos_y: 2015100.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2358373.75
      sim_grid_pos_y: 2023764.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2359068.25
      sim_grid_pos_y: 2023731.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2360491.25
      sim_grid_pos_y: 2015207.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2359836.25
      sim_grid_pos_y: 2015041.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2358312.25
      sim_grid_pos_y: 2023819.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2359112
      sim_grid_pos_y: 2023780.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2360550.25
      sim_grid_pos_y: 2015165.88
    }
  }
}
