terrain_level_data {
  terrain_level: 100
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 519582.906
      sim_grid_pos_y: 1379346.25
    }
    terrain_level_point {
      sim_grid_pos_x: 518849.219
      sim_grid_pos_y: 1378270.88
    }
    terrain_level_point {
      sim_grid_pos_x: 518206.188
      sim_grid_pos_y: 1378085.75
    }
    terrain_level_point {
      sim_grid_pos_x: 517526.719
      sim_grid_pos_y: 1378417.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517651.688
      sim_grid_pos_y: 1378680.38
    }
    terrain_level_point {
      sim_grid_pos_x: 517547.594
      sim_grid_pos_y: 1379276.38
    }
    terrain_level_point {
      sim_grid_pos_x: 517960.25
      sim_grid_pos_y: 1379916.25
    }
    terrain_level_point {
      sim_grid_pos_x: 517956.156
      sim_grid_pos_y: 1380166.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517752.438
      sim_grid_pos_y: 1380387.5
    }
    terrain_level_point {
      sim_grid_pos_x: 517720.719
      sim_grid_pos_y: 1380568.25
    }
    terrain_level_point {
      sim_grid_pos_x: 517889
      sim_grid_pos_y: 1380930.5
    }
    terrain_level_point {
      sim_grid_pos_x: 518402.75
      sim_grid_pos_y: 1381190.5
    }
    terrain_level_point {
      sim_grid_pos_x: 519150.656
      sim_grid_pos_y: 1381338.12
    }
    terrain_level_point {
      sim_grid_pos_x: 519436.938
      sim_grid_pos_y: 1381447
    }
    terrain_level_point {
      sim_grid_pos_x: 519571.312
      sim_grid_pos_y: 1.38144e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 519980.438
      sim_grid_pos_y: 1381234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 520299
      sim_grid_pos_y: 1381018.25
    }
    terrain_level_point {
      sim_grid_pos_x: 520616.094
      sim_grid_pos_y: 1380980.12
    }
    terrain_level_point {
      sim_grid_pos_x: 520739.594
      sim_grid_pos_y: 1380733.12
    }
    terrain_level_point {
      sim_grid_pos_x: 520520.75
      sim_grid_pos_y: 1380469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 520385.031
      sim_grid_pos_y: 1380451.38
    }
    terrain_level_point {
      sim_grid_pos_x: 519948.906
      sim_grid_pos_y: 1380196.88
    }
    terrain_level_point {
      sim_grid_pos_x: 519844.812
      sim_grid_pos_y: 1380025.88
    }
    terrain_level_point {
      sim_grid_pos_x: 519880.469
      sim_grid_pos_y: 1379747.38
    }
    terrain_level_point {
      sim_grid_pos_x: 519705.375
      sim_grid_pos_y: 1379608.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 518203.312
      sim_grid_pos_y: 1378053
    }
    terrain_level_point {
      sim_grid_pos_x: 517485.875
      sim_grid_pos_y: 1378403.62
    }
    terrain_level_point {
      sim_grid_pos_x: 517619.719
      sim_grid_pos_y: 1378684.75
    }
    terrain_level_point {
      sim_grid_pos_x: 517515.219
      sim_grid_pos_y: 1379282.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517929.344
      sim_grid_pos_y: 1379925.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517925.594
      sim_grid_pos_y: 1380153.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517723.688
      sim_grid_pos_y: 1380373.25
    }
    terrain_level_point {
      sim_grid_pos_x: 517688.75
      sim_grid_pos_y: 1380572.5
    }
    terrain_level_point {
      sim_grid_pos_x: 517865.594
      sim_grid_pos_y: 1380953.12
    }
    terrain_level_point {
      sim_grid_pos_x: 518392.656
      sim_grid_pos_y: 1381219.88
    }
    terrain_level_point {
      sim_grid_pos_x: 519142.188
      sim_grid_pos_y: 1381367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 519432.062
      sim_grid_pos_y: 1381478
    }
    terrain_level_point {
      sim_grid_pos_x: 519579.344
      sim_grid_pos_y: 1381470.38
    }
    terrain_level_point {
      sim_grid_pos_x: 519996.062
      sim_grid_pos_y: 1381261.5
    }
    terrain_level_point {
      sim_grid_pos_x: 520310.094
      sim_grid_pos_y: 1381048
    }
    terrain_level_point {
      sim_grid_pos_x: 520636.219
      sim_grid_pos_y: 1381008.75
    }
    terrain_level_point {
      sim_grid_pos_x: 520776.062
      sim_grid_pos_y: 1380728.88
    }
    terrain_level_point {
      sim_grid_pos_x: 520536.719
      sim_grid_pos_y: 1380440.38
    }
    terrain_level_point {
      sim_grid_pos_x: 520395.188
      sim_grid_pos_y: 1380421.75
    }
    terrain_level_point {
      sim_grid_pos_x: 519971.125
      sim_grid_pos_y: 1380174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 519876.688
      sim_grid_pos_y: 1380019.12
    }
    terrain_level_point {
      sim_grid_pos_x: 519913.188
      sim_grid_pos_y: 1379734.12
    }
    terrain_level_point {
      sim_grid_pos_x: 519730.188
      sim_grid_pos_y: 1379588.62
    }
    terrain_level_point {
      sim_grid_pos_x: 519609.719
      sim_grid_pos_y: 1379331
    }
    terrain_level_point {
      sim_grid_pos_x: 518868.375
      sim_grid_pos_y: 1378244.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 518200.438
      sim_grid_pos_y: 1378020.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517445
      sim_grid_pos_y: 1378389.38
    }
    terrain_level_point {
      sim_grid_pos_x: 517587.719
      sim_grid_pos_y: 1378689.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517482.844
      sim_grid_pos_y: 1379289.5
    }
    terrain_level_point {
      sim_grid_pos_x: 517898.438
      sim_grid_pos_y: 1379934
    }
    terrain_level_point {
      sim_grid_pos_x: 517895.031
      sim_grid_pos_y: 1380141.62
    }
    terrain_level_point {
      sim_grid_pos_x: 517694.969
      sim_grid_pos_y: 1380359.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517656.781
      sim_grid_pos_y: 1380576.75
    }
    terrain_level_point {
      sim_grid_pos_x: 517842.188
      sim_grid_pos_y: 1380975.75
    }
    terrain_level_point {
      sim_grid_pos_x: 518382.531
      sim_grid_pos_y: 1381249.25
    }
    terrain_level_point {
      sim_grid_pos_x: 519133.656
      sim_grid_pos_y: 1381397.5
    }
    terrain_level_point {
      sim_grid_pos_x: 519427.188
      sim_grid_pos_y: 1381509
    }
    terrain_level_point {
      sim_grid_pos_x: 519587.344
      sim_grid_pos_y: 1381500.75
    }
    terrain_level_point {
      sim_grid_pos_x: 520011.656
      sim_grid_pos_y: 1381288
    }
    terrain_level_point {
      sim_grid_pos_x: 520321.188
      sim_grid_pos_y: 1381077.62
    }
    terrain_level_point {
      sim_grid_pos_x: 520656.312
      sim_grid_pos_y: 1381037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 520812.562
      sim_grid_pos_y: 1380724.75
    }
    terrain_level_point {
      sim_grid_pos_x: 520552.688
      sim_grid_pos_y: 1380411.5
    }
    terrain_level_point {
      sim_grid_pos_x: 520405.312
      sim_grid_pos_y: 1380392
    }
    terrain_level_point {
      sim_grid_pos_x: 519993.344
      sim_grid_pos_y: 1380151.62
    }
    terrain_level_point {
      sim_grid_pos_x: 519908.562
      sim_grid_pos_y: 1380012.25
    }
    terrain_level_point {
      sim_grid_pos_x: 519945.875
      sim_grid_pos_y: 1379720.88
    }
    terrain_level_point {
      sim_grid_pos_x: 519754.969
      sim_grid_pos_y: 1379569
    }
    terrain_level_point {
      sim_grid_pos_x: 519636.531
      sim_grid_pos_y: 1379315.62
    }
    terrain_level_point {
      sim_grid_pos_x: 518887.531
      sim_grid_pos_y: 1378218
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 518197.562
      sim_grid_pos_y: 1377987.25
    }
    terrain_level_point {
      sim_grid_pos_x: 517404.156
      sim_grid_pos_y: 1378375.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517555.75
      sim_grid_pos_y: 1378693.5
    }
    terrain_level_point {
      sim_grid_pos_x: 517450.469
      sim_grid_pos_y: 1379296
    }
    terrain_level_point {
      sim_grid_pos_x: 517867.531
      sim_grid_pos_y: 1379942.75
    }
    terrain_level_point {
      sim_grid_pos_x: 517864.469
      sim_grid_pos_y: 1380129.5
    }
    terrain_level_point {
      sim_grid_pos_x: 517666.219
      sim_grid_pos_y: 1380344.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517624.812
      sim_grid_pos_y: 1380580.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517818.781
      sim_grid_pos_y: 1380998.38
    }
    terrain_level_point {
      sim_grid_pos_x: 518372.438
      sim_grid_pos_y: 1381278.62
    }
    terrain_level_point {
      sim_grid_pos_x: 519125.156
      sim_grid_pos_y: 1381427.12
    }
    terrain_level_point {
      sim_grid_pos_x: 519422.312
      sim_grid_pos_y: 1381540.12
    }
    terrain_level_point {
      sim_grid_pos_x: 519595.375
      sim_grid_pos_y: 1381531.12
    }
    terrain_level_point {
      sim_grid_pos_x: 520027.25
      sim_grid_pos_y: 1381314.62
    }
    terrain_level_point {
      sim_grid_pos_x: 520332.312
      sim_grid_pos_y: 1381107.25
    }
    terrain_level_point {
      sim_grid_pos_x: 520676.438
      sim_grid_pos_y: 1381065.88
    }
    terrain_level_point {
      sim_grid_pos_x: 520849.031
      sim_grid_pos_y: 1380720.5
    }
    terrain_level_point {
      sim_grid_pos_x: 520568.688
      sim_grid_pos_y: 1380382.62
    }
    terrain_level_point {
      sim_grid_pos_x: 520415.469
      sim_grid_pos_y: 1380362.38
    }
    terrain_level_point {
      sim_grid_pos_x: 520015.562
      sim_grid_pos_y: 1380129
    }
    terrain_level_point {
      sim_grid_pos_x: 519940.438
      sim_grid_pos_y: 1380005.5
    }
    terrain_level_point {
      sim_grid_pos_x: 519978.594
      sim_grid_pos_y: 1379707.62
    }
    terrain_level_point {
      sim_grid_pos_x: 519779.781
      sim_grid_pos_y: 1379549.5
    }
    terrain_level_point {
      sim_grid_pos_x: 519663.344
      sim_grid_pos_y: 1379300.38
    }
    terrain_level_point {
      sim_grid_pos_x: 518906.719
      sim_grid_pos_y: 1378191.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 518194.719
      sim_grid_pos_y: 1377954.5
    }
    terrain_level_point {
      sim_grid_pos_x: 517363.281
      sim_grid_pos_y: 1378360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517523.75
      sim_grid_pos_y: 1378697.88
    }
    terrain_level_point {
      sim_grid_pos_x: 517418.125
      sim_grid_pos_y: 1379302.62
    }
    terrain_level_point {
      sim_grid_pos_x: 517836.625
      sim_grid_pos_y: 1379951.62
    }
    terrain_level_point {
      sim_grid_pos_x: 517833.906
      sim_grid_pos_y: 1380117.25
    }
    terrain_level_point {
      sim_grid_pos_x: 517637.469
      sim_grid_pos_y: 1380330.75
    }
    terrain_level_point {
      sim_grid_pos_x: 517592.844
      sim_grid_pos_y: 1380585.12
    }
    terrain_level_point {
      sim_grid_pos_x: 517795.375
      sim_grid_pos_y: 1381021
    }
    terrain_level_point {
      sim_grid_pos_x: 518362.312
      sim_grid_pos_y: 1381308
    }
    terrain_level_point {
      sim_grid_pos_x: 519116.594
      sim_grid_pos_y: 1381456.75
    }
    terrain_level_point {
      sim_grid_pos_x: 519417.438
      sim_grid_pos_y: 1381571.12
    }
    terrain_level_point {
      sim_grid_pos_x: 519603.406
      sim_grid_pos_y: 1381561.5
    }
    terrain_level_point {
      sim_grid_pos_x: 520042.875
      sim_grid_pos_y: 1381341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 520343.406
      sim_grid_pos_y: 1381136.88
    }
    terrain_level_point {
      sim_grid_pos_x: 520696.531
      sim_grid_pos_y: 1381094.38
    }
    terrain_level_point {
      sim_grid_pos_x: 520885.5
      sim_grid_pos_y: 1380716.38
    }
    terrain_level_point {
      sim_grid_pos_x: 520584.656
      sim_grid_pos_y: 1380353.62
    }
    terrain_level_point {
      sim_grid_pos_x: 520425.656
      sim_grid_pos_y: 1380332.62
    }
    terrain_level_point {
      sim_grid_pos_x: 520037.781
      sim_grid_pos_y: 1380106.38
    }
    terrain_level_point {
      sim_grid_pos_x: 519972.312
      sim_grid_pos_y: 1379998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 520011.312
      sim_grid_pos_y: 1379694.25
    }
    terrain_level_point {
      sim_grid_pos_x: 519804.562
      sim_grid_pos_y: 1379529.88
    }
    terrain_level_point {
      sim_grid_pos_x: 519690.156
      sim_grid_pos_y: 1379285.12
    }
    terrain_level_point {
      sim_grid_pos_x: 518925.875
      sim_grid_pos_y: 1378165
    }
  }
}
