terrain_level_data {
  terrain_level: 80
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1384051.88
      sim_grid_pos_y: 1159707
    }
    terrain_level_point {
      sim_grid_pos_x: 1383914.12
      sim_grid_pos_y: 1159482.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1383742.5
      sim_grid_pos_y: 1158963.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1383652.5
      sim_grid_pos_y: 1158813.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1383644.25
      sim_grid_pos_y: 1158635.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1383564.38
      sim_grid_pos_y: 1158527.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1383588.25
      sim_grid_pos_y: 1158395.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.38365e+06
      sim_grid_pos_y: 1158242.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1383717
      sim_grid_pos_y: 1158102.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383868.12
      sim_grid_pos_y: 1158145.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383998.12
      sim_grid_pos_y: 1158175.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384124.12
      sim_grid_pos_y: 1158068.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384094
      sim_grid_pos_y: 1157915.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384341.12
      sim_grid_pos_y: 1157965.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384430.25
      sim_grid_pos_y: 1158054.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384384.5
      sim_grid_pos_y: 1158219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384247
      sim_grid_pos_y: 1158407.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384096.75
      sim_grid_pos_y: 1158467.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1384061.25
      sim_grid_pos_y: 1159000.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384214.38
      sim_grid_pos_y: 1159329.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384520.5
      sim_grid_pos_y: 1159315.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1384647.25
      sim_grid_pos_y: 1159382.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384709.62
      sim_grid_pos_y: 1159530.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384851.38
      sim_grid_pos_y: 1159749.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1384644.12
      sim_grid_pos_y: 1159937.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1384574.75
      sim_grid_pos_y: 1160337.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384225.38
      sim_grid_pos_y: 1160471.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384088.38
      sim_grid_pos_y: 1160109.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1384361.5
      sim_grid_pos_y: 1157927.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1384476.12
      sim_grid_pos_y: 1158042.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384422
      sim_grid_pos_y: 1158237.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384273.12
      sim_grid_pos_y: 1158441.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384136
      sim_grid_pos_y: 1158496.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384102.88
      sim_grid_pos_y: 1158993.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1384239.88
      sim_grid_pos_y: 1159287.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384529.75
      sim_grid_pos_y: 1159273.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384679.38
      sim_grid_pos_y: 1159353.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384746
      sim_grid_pos_y: 1159511.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384904.75
      sim_grid_pos_y: 1159756.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1384682
      sim_grid_pos_y: 1159958
    }
    terrain_level_point {
      sim_grid_pos_x: 1384611.25
      sim_grid_pos_y: 1160367.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384201.62
      sim_grid_pos_y: 1160524.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384048
      sim_grid_pos_y: 1160119.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1384011.88
      sim_grid_pos_y: 1159720.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383876.62
      sim_grid_pos_y: 1159499.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1383705
      sim_grid_pos_y: 1158980.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383612
      sim_grid_pos_y: 1158826.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1383603.75
      sim_grid_pos_y: 1158650.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383521
      sim_grid_pos_y: 1158538
    }
    terrain_level_point {
      sim_grid_pos_x: 1383548.62
      sim_grid_pos_y: 1158384.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1383612.38
      sim_grid_pos_y: 1158225.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1383695
      sim_grid_pos_y: 1158054
    }
    terrain_level_point {
      sim_grid_pos_x: 1383878.25
      sim_grid_pos_y: 1158105.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1383987.38
      sim_grid_pos_y: 1158131.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1384079.25
      sim_grid_pos_y: 1158052.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384041.88
      sim_grid_pos_y: 1157863.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1384381.75
      sim_grid_pos_y: 1157889.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384522
      sim_grid_pos_y: 1158030.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384459.5
      sim_grid_pos_y: 1158255.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384299.25
      sim_grid_pos_y: 1158475.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384175.12
      sim_grid_pos_y: 1158524.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1384144.5
      sim_grid_pos_y: 1158985.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1384265.38
      sim_grid_pos_y: 1159245.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384539.12
      sim_grid_pos_y: 1159232.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1384711.5
      sim_grid_pos_y: 1159323.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384782.38
      sim_grid_pos_y: 1159492.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1384958.12
      sim_grid_pos_y: 1159763.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.38472e+06
      sim_grid_pos_y: 1159979
    }
    terrain_level_point {
      sim_grid_pos_x: 1384647.62
      sim_grid_pos_y: 1160397.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384177.88
      sim_grid_pos_y: 1160577.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384007.75
      sim_grid_pos_y: 1160128.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1383971.88
      sim_grid_pos_y: 1159733.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1383839.25
      sim_grid_pos_y: 1159517.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383667.5
      sim_grid_pos_y: 1158997.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1383571.5
      sim_grid_pos_y: 1158838.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1383563.38
      sim_grid_pos_y: 1158664.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1383477.5
      sim_grid_pos_y: 1158548.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1383509
      sim_grid_pos_y: 1158372.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383574.88
      sim_grid_pos_y: 1158209
    }
    terrain_level_point {
      sim_grid_pos_x: 1383672.88
      sim_grid_pos_y: 1158005.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1383888.62
      sim_grid_pos_y: 1158065.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383976.5
      sim_grid_pos_y: 1158086.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384034.38
      sim_grid_pos_y: 1158037
    }
    terrain_level_point {
      sim_grid_pos_x: 1383989.75
      sim_grid_pos_y: 1157811.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1384402
      sim_grid_pos_y: 1157851.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384567.88
      sim_grid_pos_y: 1158018.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384497.12
      sim_grid_pos_y: 1158273.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1384325.5
      sim_grid_pos_y: 1158509
    }
    terrain_level_point {
      sim_grid_pos_x: 1384214.38
      sim_grid_pos_y: 1158553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1384186
      sim_grid_pos_y: 1158977.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384291
      sim_grid_pos_y: 1159203
    }
    terrain_level_point {
      sim_grid_pos_x: 1384548.38
      sim_grid_pos_y: 1159190.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384743.62
      sim_grid_pos_y: 1159294.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1384818.75
      sim_grid_pos_y: 1159473.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1385011.5
      sim_grid_pos_y: 1159770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1384758
      sim_grid_pos_y: 1159999.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1384684.12
      sim_grid_pos_y: 1160427.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1384154.12
      sim_grid_pos_y: 1160630.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1383967.38
      sim_grid_pos_y: 1160137.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1383931.88
      sim_grid_pos_y: 1159746.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383801.75
      sim_grid_pos_y: 1159534.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.38363e+06
      sim_grid_pos_y: 1159014.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383531
      sim_grid_pos_y: 1158850.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383523
      sim_grid_pos_y: 1158679
    }
    terrain_level_point {
      sim_grid_pos_x: 1383434
      sim_grid_pos_y: 1158558.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383469.38
      sim_grid_pos_y: 1158361.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1383537.38
      sim_grid_pos_y: 1158192.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1383650.88
      sim_grid_pos_y: 1157956.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1383898.75
      sim_grid_pos_y: 1158026
    }
    terrain_level_point {
      sim_grid_pos_x: 1383965.75
      sim_grid_pos_y: 1158041.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1383989.5
      sim_grid_pos_y: 1158021.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1383937.62
      sim_grid_pos_y: 1157759.12
    }
  }
}
