terrain_level_data {
  terrain_level: 14
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2255329.25
      sim_grid_pos_y: 822081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2256581.5
      sim_grid_pos_y: 822096.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2257150.5
      sim_grid_pos_y: 822265.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2258177.75
      sim_grid_pos_y: 822351.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2257489.5
      sim_grid_pos_y: 822142.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2256932.5
      sim_grid_pos_y: 821544.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2256843
      sim_grid_pos_y: 820928.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2257120.5
      sim_grid_pos_y: 820925.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2257278
      sim_grid_pos_y: 820655.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2257337.5
      sim_grid_pos_y: 820319
    }
    terrain_level_point {
      sim_grid_pos_x: 2.25764e+06
      sim_grid_pos_y: 820379.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2257931.75
      sim_grid_pos_y: 821000.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2258465.5
      sim_grid_pos_y: 822219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2259174.5
      sim_grid_pos_y: 822066.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2259331.25
      sim_grid_pos_y: 820720.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2259409.75
      sim_grid_pos_y: 820326.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2259059
      sim_grid_pos_y: 819713.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2258648.5
      sim_grid_pos_y: 819642.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2258345
      sim_grid_pos_y: 819020.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2257356.25
      sim_grid_pos_y: 818836.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2257065
      sim_grid_pos_y: 818927.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2256784.5
      sim_grid_pos_y: 819078
    }
    terrain_level_point {
      sim_grid_pos_x: 2256321
      sim_grid_pos_y: 818998.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2255758.5
      sim_grid_pos_y: 818791.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2255630.75
      sim_grid_pos_y: 818858.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2255587.25
      sim_grid_pos_y: 818928.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2255562.5
      sim_grid_pos_y: 819106.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2255279.75
      sim_grid_pos_y: 819244
    }
    terrain_level_point {
      sim_grid_pos_x: 2255095.5
      sim_grid_pos_y: 819198.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2254977.5
      sim_grid_pos_y: 819265.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2254848.25
      sim_grid_pos_y: 819475.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2254550.5
      sim_grid_pos_y: 819601.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2254671
      sim_grid_pos_y: 819854.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2254960.75
      sim_grid_pos_y: 819888.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2254784
      sim_grid_pos_y: 820410.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2255030.25
      sim_grid_pos_y: 820945.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2255238
      sim_grid_pos_y: 821462.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2255756.5
      sim_grid_pos_y: 818757.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2255609
      sim_grid_pos_y: 818835.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2255557.75
      sim_grid_pos_y: 818917.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2255534.25
      sim_grid_pos_y: 819085.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2255276.25
      sim_grid_pos_y: 819211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2255090.75
      sim_grid_pos_y: 819165.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2254955.5
      sim_grid_pos_y: 819243.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2254827.25
      sim_grid_pos_y: 819450.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2254508.75
      sim_grid_pos_y: 819585.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2254650.5
      sim_grid_pos_y: 819883.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2254919.5
      sim_grid_pos_y: 819914.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2254750.75
      sim_grid_pos_y: 820412.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2255002
      sim_grid_pos_y: 820957.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2255208
      sim_grid_pos_y: 821470.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2255302.75
      sim_grid_pos_y: 822111.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2256576.75
      sim_grid_pos_y: 822127.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2257144.75
      sim_grid_pos_y: 822295.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2258202.75
      sim_grid_pos_y: 822384.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2258213.25
      sim_grid_pos_y: 822329.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2257506.5
      sim_grid_pos_y: 822115.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2256961.75
      sim_grid_pos_y: 821530.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2256878.5
      sim_grid_pos_y: 820958.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2257138.25
      sim_grid_pos_y: 820955.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2257307.25
      sim_grid_pos_y: 820665.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2257362.5
      sim_grid_pos_y: 820355.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2257618.75
      sim_grid_pos_y: 820406.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2257903.75
      sim_grid_pos_y: 821013.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2258447.5
      sim_grid_pos_y: 822254.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2259202.5
      sim_grid_pos_y: 822092.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2259361.75
      sim_grid_pos_y: 820725.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2259442.25
      sim_grid_pos_y: 820321.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2259078.5
      sim_grid_pos_y: 819685.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2258669.25
      sim_grid_pos_y: 819614.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2258365.75
      sim_grid_pos_y: 818993.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2257354.5
      sim_grid_pos_y: 818805.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2257053
      sim_grid_pos_y: 818899.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2256779.25
      sim_grid_pos_y: 819045.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2256328.75
      sim_grid_pos_y: 818968.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2255754.25
      sim_grid_pos_y: 818724.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2255587.5
      sim_grid_pos_y: 818812.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2255528.25
      sim_grid_pos_y: 818906.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2255506
      sim_grid_pos_y: 819065.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2255273
      sim_grid_pos_y: 819178.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2255086.25
      sim_grid_pos_y: 819132.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2254933.25
      sim_grid_pos_y: 819220.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2254806.25
      sim_grid_pos_y: 819426.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2254467.25
      sim_grid_pos_y: 819570
    }
    terrain_level_point {
      sim_grid_pos_x: 2.25463e+06
      sim_grid_pos_y: 819911.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2254878
      sim_grid_pos_y: 819940.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2254717.75
      sim_grid_pos_y: 820413.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2254973.75
      sim_grid_pos_y: 820969.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2255178.25
      sim_grid_pos_y: 821478.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2255276
      sim_grid_pos_y: 822142.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2256572.25
      sim_grid_pos_y: 822157.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2257139
      sim_grid_pos_y: 822326.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2258227.75
      sim_grid_pos_y: 822417.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2258248.5
      sim_grid_pos_y: 822308.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2257523.25
      sim_grid_pos_y: 822088.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2256990.75
      sim_grid_pos_y: 821516.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2256914
      sim_grid_pos_y: 820989.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2257156
      sim_grid_pos_y: 820986.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2257336.75
      sim_grid_pos_y: 820676.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2257387.25
      sim_grid_pos_y: 820391.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2257597.5
      sim_grid_pos_y: 820433.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2257875.75
      sim_grid_pos_y: 821026.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2258429.5
      sim_grid_pos_y: 822290.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2259230.5
      sim_grid_pos_y: 822117.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2259392
      sim_grid_pos_y: 820730
    }
    terrain_level_point {
      sim_grid_pos_x: 2259474.5
      sim_grid_pos_y: 820316
    }
    terrain_level_point {
      sim_grid_pos_x: 2259098
      sim_grid_pos_y: 819657.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2.25869e+06
      sim_grid_pos_y: 819587.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2258386.75
      sim_grid_pos_y: 818965.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2257352.5
      sim_grid_pos_y: 818773.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2257041
      sim_grid_pos_y: 818870.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2256774
      sim_grid_pos_y: 819013.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2256337
      sim_grid_pos_y: 818938.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2255752
      sim_grid_pos_y: 818690.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2255565.75
      sim_grid_pos_y: 818788.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2255498.5
      sim_grid_pos_y: 818896.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2255477.75
      sim_grid_pos_y: 819045
    }
    terrain_level_point {
      sim_grid_pos_x: 2255269.5
      sim_grid_pos_y: 819146.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2255081.75
      sim_grid_pos_y: 819100.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2254911.25
      sim_grid_pos_y: 819197.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2254785.25
      sim_grid_pos_y: 819401.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2254425.75
      sim_grid_pos_y: 819554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2254609.75
      sim_grid_pos_y: 819940.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2254836.75
      sim_grid_pos_y: 819966.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2254684.75
      sim_grid_pos_y: 820415.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2254945.5
      sim_grid_pos_y: 820981.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2255148.25
      sim_grid_pos_y: 821486.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2255249.5
      sim_grid_pos_y: 822172.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2256567.5
      sim_grid_pos_y: 822188.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2257133.25
      sim_grid_pos_y: 822356.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2258252.75
      sim_grid_pos_y: 822450.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2258284
      sim_grid_pos_y: 822287.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2257540.25
      sim_grid_pos_y: 822061.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2257019.75
      sim_grid_pos_y: 821502.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2256949.5
      sim_grid_pos_y: 821019.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2257173.75
      sim_grid_pos_y: 821017.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2257366
      sim_grid_pos_y: 820687.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2257412
      sim_grid_pos_y: 820427.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2257576.25
      sim_grid_pos_y: 820460.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2257847.75
      sim_grid_pos_y: 821039.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2258411.25
      sim_grid_pos_y: 822325.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2259258.5
      sim_grid_pos_y: 822143.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2259422.5
      sim_grid_pos_y: 820734.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2259507
      sim_grid_pos_y: 820310.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2259117.5
      sim_grid_pos_y: 819629.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2258710.75
      sim_grid_pos_y: 819559.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2258407.5
      sim_grid_pos_y: 818938.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2257350.75
      sim_grid_pos_y: 818741.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2257029
      sim_grid_pos_y: 818842.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2256768.75
      sim_grid_pos_y: 818981.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2256344.75
      sim_grid_pos_y: 818908.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2255749.75
      sim_grid_pos_y: 818657
    }
    terrain_level_point {
      sim_grid_pos_x: 2255544
      sim_grid_pos_y: 818765.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2255469
      sim_grid_pos_y: 818885.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2255449.5
      sim_grid_pos_y: 819024.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2255266
      sim_grid_pos_y: 819113.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2255077
      sim_grid_pos_y: 819067.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2254889.25
      sim_grid_pos_y: 819174.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2254764.25
      sim_grid_pos_y: 819377.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2254384
      sim_grid_pos_y: 819538.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2254589.25
      sim_grid_pos_y: 819968.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2254795.5
      sim_grid_pos_y: 819992.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2254651.75
      sim_grid_pos_y: 820417.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2254917.25
      sim_grid_pos_y: 820993.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2255118.5
      sim_grid_pos_y: 821494.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2255223
      sim_grid_pos_y: 822203
    }
    terrain_level_point {
      sim_grid_pos_x: 2256562.75
      sim_grid_pos_y: 822219.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2257127.5
      sim_grid_pos_y: 822386.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2258277.75
      sim_grid_pos_y: 822483.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2258319.5
      sim_grid_pos_y: 822265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2257557
      sim_grid_pos_y: 822034.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2257048.75
      sim_grid_pos_y: 821488.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2256985
      sim_grid_pos_y: 821049.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2257191.75
      sim_grid_pos_y: 821047.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2257395.25
      sim_grid_pos_y: 820698.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2257436.75
      sim_grid_pos_y: 820464.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2257555
      sim_grid_pos_y: 820487.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2257819.75
      sim_grid_pos_y: 821051.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2258393.25
      sim_grid_pos_y: 822360.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2259286.5
      sim_grid_pos_y: 822168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2259453
      sim_grid_pos_y: 820739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2259539.5
      sim_grid_pos_y: 820305.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2259137
      sim_grid_pos_y: 819601.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2258731.5
      sim_grid_pos_y: 819531.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2258428.25
      sim_grid_pos_y: 818910.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2257348.75
      sim_grid_pos_y: 818710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2257017.25
      sim_grid_pos_y: 818813.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2256763.5
      sim_grid_pos_y: 818949.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2256352.75
      sim_grid_pos_y: 818878.75
    }
  }
}
