terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 66988.0859
      sim_grid_pos_y: 2906956.75
    }
    terrain_level_point {
      sim_grid_pos_x: 69158.0078
      sim_grid_pos_y: 2904936.75
    }
    terrain_level_point {
      sim_grid_pos_x: 69179.2266
      sim_grid_pos_y: 2904026.25
    }
    terrain_level_point {
      sim_grid_pos_x: 70774.4766
      sim_grid_pos_y: 2903425
    }
    terrain_level_point {
      sim_grid_pos_x: 74303.2188
      sim_grid_pos_y: 2912024
    }
    terrain_level_point {
      sim_grid_pos_x: 74086.1172
      sim_grid_pos_y: 2912315.5
    }
    terrain_level_point {
      sim_grid_pos_x: 72505.3828
      sim_grid_pos_y: 2913202
    }
    terrain_level_point {
      sim_grid_pos_x: 72442.4766
      sim_grid_pos_y: 2913151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 71364.0547
      sim_grid_pos_y: 2910824.75
    }
    terrain_level_point {
      sim_grid_pos_x: 71484.4688
      sim_grid_pos_y: 2910731.75
    }
    terrain_level_point {
      sim_grid_pos_x: 71360.9297
      sim_grid_pos_y: 2910591.75
    }
    terrain_level_point {
      sim_grid_pos_x: 69205.9531
      sim_grid_pos_y: 2910491
    }
    terrain_level_point {
      sim_grid_pos_x: 68517.0391
      sim_grid_pos_y: 2909155.25
    }
    terrain_level_point {
      sim_grid_pos_x: 68668.0781
      sim_grid_pos_y: 2908984.25
    }
    terrain_level_point {
      sim_grid_pos_x: 68220.1719
      sim_grid_pos_y: 2908129.25
    }
    terrain_level_point {
      sim_grid_pos_x: 68116.4531
      sim_grid_pos_y: 2908154
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 74338.2812
      sim_grid_pos_y: 2912028.5
    }
    terrain_level_point {
      sim_grid_pos_x: 74106.875
      sim_grid_pos_y: 2912339
    }
    terrain_level_point {
      sim_grid_pos_x: 72502.3047
      sim_grid_pos_y: 2913239
    }
    terrain_level_point {
      sim_grid_pos_x: 72417.5938
      sim_grid_pos_y: 2913171
    }
    terrain_level_point {
      sim_grid_pos_x: 71325.8203
      sim_grid_pos_y: 2910815.5
    }
    terrain_level_point {
      sim_grid_pos_x: 71439.6875
      sim_grid_pos_y: 2910727.5
    }
    terrain_level_point {
      sim_grid_pos_x: 71346.4844
      sim_grid_pos_y: 2910622
    }
    terrain_level_point {
      sim_grid_pos_x: 69186.7656
      sim_grid_pos_y: 2910520.75
    }
    terrain_level_point {
      sim_grid_pos_x: 68480.0625
      sim_grid_pos_y: 2909150.5
    }
    terrain_level_point {
      sim_grid_pos_x: 68631.0156
      sim_grid_pos_y: 2908979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 68204.0312
      sim_grid_pos_y: 2908164.5
    }
    terrain_level_point {
      sim_grid_pos_x: 68106.2812
      sim_grid_pos_y: 2908188
    }
    terrain_level_point {
      sim_grid_pos_x: 66944.4766
      sim_grid_pos_y: 2906955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 69127.5703
      sim_grid_pos_y: 2904923
    }
    terrain_level_point {
      sim_grid_pos_x: 69148.9531
      sim_grid_pos_y: 2904005
    }
    terrain_level_point {
      sim_grid_pos_x: 70791.5938
      sim_grid_pos_y: 2903385.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 74373.3438
      sim_grid_pos_y: 2912033
    }
    terrain_level_point {
      sim_grid_pos_x: 74127.625
      sim_grid_pos_y: 2912362.75
    }
    terrain_level_point {
      sim_grid_pos_x: 72499.2266
      sim_grid_pos_y: 2913276
    }
    terrain_level_point {
      sim_grid_pos_x: 72392.7109
      sim_grid_pos_y: 2913190.5
    }
    terrain_level_point {
      sim_grid_pos_x: 71287.6
      sim_grid_pos_y: 2910806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 71394.9062
      sim_grid_pos_y: 2910723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 71332.0312
      sim_grid_pos_y: 2910652
    }
    terrain_level_point {
      sim_grid_pos_x: 69167.5703
      sim_grid_pos_y: 2910550.75
    }
    terrain_level_point {
      sim_grid_pos_x: 68443.0859
      sim_grid_pos_y: 2909146
    }
    terrain_level_point {
      sim_grid_pos_x: 68593.9375
      sim_grid_pos_y: 2908975.25
    }
    terrain_level_point {
      sim_grid_pos_x: 68187.9062
      sim_grid_pos_y: 2.9082e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 68096.1
      sim_grid_pos_y: 2908222
    }
    terrain_level_point {
      sim_grid_pos_x: 66900.8672
      sim_grid_pos_y: 2906953.75
    }
    terrain_level_point {
      sim_grid_pos_x: 69097.125
      sim_grid_pos_y: 2904909.25
    }
    terrain_level_point {
      sim_grid_pos_x: 69118.6953
      sim_grid_pos_y: 2903983.5
    }
    terrain_level_point {
      sim_grid_pos_x: 70808.7
      sim_grid_pos_y: 2903346.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 74408.4062
      sim_grid_pos_y: 2912037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 74148.3828
      sim_grid_pos_y: 2912386.25
    }
    terrain_level_point {
      sim_grid_pos_x: 72496.1406
      sim_grid_pos_y: 2913313
    }
    terrain_level_point {
      sim_grid_pos_x: 72367.8359
      sim_grid_pos_y: 2.91321e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 71249.375
      sim_grid_pos_y: 2910796.75
    }
    terrain_level_point {
      sim_grid_pos_x: 71350.1172
      sim_grid_pos_y: 2910719
    }
    terrain_level_point {
      sim_grid_pos_x: 71317.5859
      sim_grid_pos_y: 2910682.25
    }
    terrain_level_point {
      sim_grid_pos_x: 69148.3828
      sim_grid_pos_y: 2910580.75
    }
    terrain_level_point {
      sim_grid_pos_x: 68406.1
      sim_grid_pos_y: 2909141.5
    }
    terrain_level_point {
      sim_grid_pos_x: 68556.8672
      sim_grid_pos_y: 2908970.75
    }
    terrain_level_point {
      sim_grid_pos_x: 68171.75
      sim_grid_pos_y: 2908235.5
    }
    terrain_level_point {
      sim_grid_pos_x: 68085.9375
      sim_grid_pos_y: 2908256
    }
    terrain_level_point {
      sim_grid_pos_x: 66857.25
      sim_grid_pos_y: 2906952.5
    }
    terrain_level_point {
      sim_grid_pos_x: 69066.6719
      sim_grid_pos_y: 2904895.75
    }
    terrain_level_point {
      sim_grid_pos_x: 69088.4219
      sim_grid_pos_y: 2903962
    }
    terrain_level_point {
      sim_grid_pos_x: 70825.8125
      sim_grid_pos_y: 2903307
    }
  }
}
terrain_level_data {
  terrain_level: 14
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 70765.2578
      sim_grid_pos_y: 2903314
    }
    terrain_level_point {
      sim_grid_pos_x: 72010.6172
      sim_grid_pos_y: 2906208.5
    }
    terrain_level_point {
      sim_grid_pos_x: 74445.3828
      sim_grid_pos_y: 2905245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 73841.6875
      sim_grid_pos_y: 2903577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 72079.625
      sim_grid_pos_y: 2903185
    }
    terrain_level_point {
      sim_grid_pos_x: 72098.2734
      sim_grid_pos_y: 2903599.25
    }
    terrain_level_point {
      sim_grid_pos_x: 71040.6094
      sim_grid_pos_y: 2903308.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 72047.0938
      sim_grid_pos_y: 2903146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 72065.6328
      sim_grid_pos_y: 2903558.5
    }
    terrain_level_point {
      sim_grid_pos_x: 71044.4844
      sim_grid_pos_y: 2903278
    }
    terrain_level_point {
      sim_grid_pos_x: 70718.9062
      sim_grid_pos_y: 2903284
    }
    terrain_level_point {
      sim_grid_pos_x: 71994.1641
      sim_grid_pos_y: 2906248
    }
    terrain_level_point {
      sim_grid_pos_x: 74484.4766
      sim_grid_pos_y: 2905263
    }
    terrain_level_point {
      sim_grid_pos_x: 73864.8516
      sim_grid_pos_y: 2903551.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 72014.5547
      sim_grid_pos_y: 2903107.5
    }
    terrain_level_point {
      sim_grid_pos_x: 72033.0156
      sim_grid_pos_y: 2903517.5
    }
    terrain_level_point {
      sim_grid_pos_x: 71048.3516
      sim_grid_pos_y: 2903247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 70672.5469
      sim_grid_pos_y: 2903254
    }
    terrain_level_point {
      sim_grid_pos_x: 71977.7
      sim_grid_pos_y: 2906287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 74523.5625
      sim_grid_pos_y: 2905280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 73888.0312
      sim_grid_pos_y: 2903525
    }
  }
}
terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 75781.9
      sim_grid_pos_y: 2907610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 80611.8359
      sim_grid_pos_y: 2907696.5
    }
    terrain_level_point {
      sim_grid_pos_x: 80617.1172
      sim_grid_pos_y: 2906803.5
    }
    terrain_level_point {
      sim_grid_pos_x: 82290.0547
      sim_grid_pos_y: 2906622.5
    }
    terrain_level_point {
      sim_grid_pos_x: 82308.7109
      sim_grid_pos_y: 2905724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 80590.3906
      sim_grid_pos_y: 2905618
    }
    terrain_level_point {
      sim_grid_pos_x: 80707.8594
      sim_grid_pos_y: 2904676
    }
    terrain_level_point {
      sim_grid_pos_x: 81280.8359
      sim_grid_pos_y: 2902596.75
    }
    terrain_level_point {
      sim_grid_pos_x: 78386.8203
      sim_grid_pos_y: 2901292.5
    }
    terrain_level_point {
      sim_grid_pos_x: 77789.0625
      sim_grid_pos_y: 2902003.75
    }
    terrain_level_point {
      sim_grid_pos_x: 77392.8047
      sim_grid_pos_y: 2902901
    }
    terrain_level_point {
      sim_grid_pos_x: 77447.8438
      sim_grid_pos_y: 2903318.5
    }
    terrain_level_point {
      sim_grid_pos_x: 76702.9141
      sim_grid_pos_y: 2904203
    }
    terrain_level_point {
      sim_grid_pos_x: 75317.7891
      sim_grid_pos_y: 2904770.25
    }
    terrain_level_point {
      sim_grid_pos_x: 75535.8359
      sim_grid_pos_y: 2905111
    }
    terrain_level_point {
      sim_grid_pos_x: 75809.125
      sim_grid_pos_y: 2905152.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 78378.2422
      sim_grid_pos_y: 2901255
    }
    terrain_level_point {
      sim_grid_pos_x: 77762.6953
      sim_grid_pos_y: 2901987.25
    }
    terrain_level_point {
      sim_grid_pos_x: 77361.1875
      sim_grid_pos_y: 2902896.5
    }
    terrain_level_point {
      sim_grid_pos_x: 77415.5703
      sim_grid_pos_y: 2903309.25
    }
    terrain_level_point {
      sim_grid_pos_x: 76684.25
      sim_grid_pos_y: 2904177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 75272
      sim_grid_pos_y: 2904755.75
    }
    terrain_level_point {
      sim_grid_pos_x: 75517.4375
      sim_grid_pos_y: 2905139.25
    }
    terrain_level_point {
      sim_grid_pos_x: 75778.0625
      sim_grid_pos_y: 2905178.75
    }
    terrain_level_point {
      sim_grid_pos_x: 75750.8125
      sim_grid_pos_y: 2907640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 80642.4062
      sim_grid_pos_y: 2907728
    }
    terrain_level_point {
      sim_grid_pos_x: 80647.7
      sim_grid_pos_y: 2906831.25
    }
    terrain_level_point {
      sim_grid_pos_x: 82320.2422
      sim_grid_pos_y: 2906650.25
    }
    terrain_level_point {
      sim_grid_pos_x: 82340.0781
      sim_grid_pos_y: 2905695.25
    }
    terrain_level_point {
      sim_grid_pos_x: 80624.9609
      sim_grid_pos_y: 2905589.25
    }
    terrain_level_point {
      sim_grid_pos_x: 80738.1
      sim_grid_pos_y: 2904682
    }
    terrain_level_point {
      sim_grid_pos_x: 81317.4844
      sim_grid_pos_y: 2902579.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 78369.6641
      sim_grid_pos_y: 2901217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 77736.3359
      sim_grid_pos_y: 2901970.75
    }
    terrain_level_point {
      sim_grid_pos_x: 77329.5625
      sim_grid_pos_y: 2902892
    }
    terrain_level_point {
      sim_grid_pos_x: 77383.3047
      sim_grid_pos_y: 2903299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 76665.6
      sim_grid_pos_y: 2904151.75
    }
    terrain_level_point {
      sim_grid_pos_x: 75226.2266
      sim_grid_pos_y: 2904741.25
    }
    terrain_level_point {
      sim_grid_pos_x: 75499.0469
      sim_grid_pos_y: 2905167.5
    }
    terrain_level_point {
      sim_grid_pos_x: 75747.0156
      sim_grid_pos_y: 2905205.25
    }
    terrain_level_point {
      sim_grid_pos_x: 75719.7109
      sim_grid_pos_y: 2907670.75
    }
    terrain_level_point {
      sim_grid_pos_x: 80672.9844
      sim_grid_pos_y: 2907759.25
    }
    terrain_level_point {
      sim_grid_pos_x: 80678.3
      sim_grid_pos_y: 2906858.75
    }
    terrain_level_point {
      sim_grid_pos_x: 82350.4375
      sim_grid_pos_y: 2906678
    }
    terrain_level_point {
      sim_grid_pos_x: 82371.4453
      sim_grid_pos_y: 2905666.25
    }
    terrain_level_point {
      sim_grid_pos_x: 80659.5312
      sim_grid_pos_y: 2905560.75
    }
    terrain_level_point {
      sim_grid_pos_x: 80768.3438
      sim_grid_pos_y: 2904688
    }
    terrain_level_point {
      sim_grid_pos_x: 81354.1328
      sim_grid_pos_y: 2902562.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 78361.0938
      sim_grid_pos_y: 2901179.75
    }
    terrain_level_point {
      sim_grid_pos_x: 77709.9609
      sim_grid_pos_y: 2901954.25
    }
    terrain_level_point {
      sim_grid_pos_x: 77297.9453
      sim_grid_pos_y: 2902887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 77351.0312
      sim_grid_pos_y: 2903290.25
    }
    terrain_level_point {
      sim_grid_pos_x: 76646.9453
      sim_grid_pos_y: 2904126.25
    }
    terrain_level_point {
      sim_grid_pos_x: 75180.4375
      sim_grid_pos_y: 2904726.75
    }
    terrain_level_point {
      sim_grid_pos_x: 75480.6406
      sim_grid_pos_y: 2905196
    }
    terrain_level_point {
      sim_grid_pos_x: 75715.9609
      sim_grid_pos_y: 2905231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 75688.625
      sim_grid_pos_y: 2907701
    }
    terrain_level_point {
      sim_grid_pos_x: 80703.5547
      sim_grid_pos_y: 2907790.5
    }
    terrain_level_point {
      sim_grid_pos_x: 80708.8906
      sim_grid_pos_y: 2906886.5
    }
    terrain_level_point {
      sim_grid_pos_x: 82380.625
      sim_grid_pos_y: 2906705.5
    }
    terrain_level_point {
      sim_grid_pos_x: 82402.8047
      sim_grid_pos_y: 2905637.5
    }
    terrain_level_point {
      sim_grid_pos_x: 80694.1
      sim_grid_pos_y: 2905532
    }
    terrain_level_point {
      sim_grid_pos_x: 80798.5859
      sim_grid_pos_y: 2904694
    }
    terrain_level_point {
      sim_grid_pos_x: 81390.7812
      sim_grid_pos_y: 2902545
    }
  }
}
