terrain_level_data {
  terrain_level: 135
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2935597.25
      sim_grid_pos_y: 2340632.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935376
      sim_grid_pos_y: 2340750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935274.25
      sim_grid_pos_y: 2340944.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935291.75
      sim_grid_pos_y: 2341169.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935469.75
      sim_grid_pos_y: 2341214.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935704.5
      sim_grid_pos_y: 2341211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935941
      sim_grid_pos_y: 2341184.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935982.25
      sim_grid_pos_y: 2341114.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935909.5
      sim_grid_pos_y: 2341020.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935757.25
      sim_grid_pos_y: 2340988.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935632.25
      sim_grid_pos_y: 2340926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935665.75
      sim_grid_pos_y: 2340681.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2935601
      sim_grid_pos_y: 2340572.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935338
      sim_grid_pos_y: 2340713
    }
    terrain_level_point {
      sim_grid_pos_x: 2935222
      sim_grid_pos_y: 2340933.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935243.5
      sim_grid_pos_y: 2341210.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935463.75
      sim_grid_pos_y: 2341266
    }
    terrain_level_point {
      sim_grid_pos_x: 2935707.75
      sim_grid_pos_y: 2341263
    }
    terrain_level_point {
      sim_grid_pos_x: 2935972.25
      sim_grid_pos_y: 2341232.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936044
      sim_grid_pos_y: 2341110.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935938.5
      sim_grid_pos_y: 2340974.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935774.25
      sim_grid_pos_y: 2340939.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935688
      sim_grid_pos_y: 2340897
    }
    terrain_level_point {
      sim_grid_pos_x: 2935678.25
      sim_grid_pos_y: 2340680.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2935604.75
      sim_grid_pos_y: 2340512.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.9353e+06
      sim_grid_pos_y: 2340675.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935169.75
      sim_grid_pos_y: 2340923
    }
    terrain_level_point {
      sim_grid_pos_x: 2935195.25
      sim_grid_pos_y: 2341250.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935457.5
      sim_grid_pos_y: 2341317.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935711
      sim_grid_pos_y: 2341314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936003.5
      sim_grid_pos_y: 2341280.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936106
      sim_grid_pos_y: 2341106.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935967.5
      sim_grid_pos_y: 2340928.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935791.25
      sim_grid_pos_y: 2340891
    }
    terrain_level_point {
      sim_grid_pos_x: 2935743.75
      sim_grid_pos_y: 2340867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935707.25
      sim_grid_pos_y: 2340672.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2935608.75
      sim_grid_pos_y: 2340452.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935261.75
      sim_grid_pos_y: 2340637.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935117.5
      sim_grid_pos_y: 2340912.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935147
      sim_grid_pos_y: 2341291.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935451.5
      sim_grid_pos_y: 2341368.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935714.5
      sim_grid_pos_y: 2341365.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936034.75
      sim_grid_pos_y: 2341328.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936167.75
      sim_grid_pos_y: 2341102.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935996.25
      sim_grid_pos_y: 2340882
    }
    terrain_level_point {
      sim_grid_pos_x: 2935808.25
      sim_grid_pos_y: 2340842
    }
    terrain_level_point {
      sim_grid_pos_x: 2935799.5
      sim_grid_pos_y: 2340837.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935739.5
      sim_grid_pos_y: 2340668.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2935612.5
      sim_grid_pos_y: 2340392.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935223.75
      sim_grid_pos_y: 2340599.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935065.25
      sim_grid_pos_y: 2340901.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2935098.75
      sim_grid_pos_y: 2341332
    }
    terrain_level_point {
      sim_grid_pos_x: 2935445.5
      sim_grid_pos_y: 2341420.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935717.75
      sim_grid_pos_y: 2341416.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936066
      sim_grid_pos_y: 2341376.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936229.75
      sim_grid_pos_y: 2341098.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936025.25
      sim_grid_pos_y: 2340835.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935820.5
      sim_grid_pos_y: 2340813
    }
    terrain_level_point {
      sim_grid_pos_x: 2935765
      sim_grid_pos_y: 2340647.75
    }
  }
}
terrain_level_data {
  terrain_level: 75
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2935816.75
      sim_grid_pos_y: 2340723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935787.25
      sim_grid_pos_y: 2340581.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.93582e+06
      sim_grid_pos_y: 2340398.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936377
      sim_grid_pos_y: 2340670.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936344.75
      sim_grid_pos_y: 2340836.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936230.5
      sim_grid_pos_y: 2340894.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2936423.25
      sim_grid_pos_y: 2340647.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936381.25
      sim_grid_pos_y: 2340863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936232.25
      sim_grid_pos_y: 2340939.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935781
      sim_grid_pos_y: 2340752.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2935745.5
      sim_grid_pos_y: 2340582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2935789.25
      sim_grid_pos_y: 2340338.25
    }
  }
}
terrain_level_data {
  terrain_level: 140
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2936430.25
      sim_grid_pos_y: 2341594.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936446.75
      sim_grid_pos_y: 2341758
    }
    terrain_level_point {
      sim_grid_pos_x: 2936628.25
      sim_grid_pos_y: 2341772
    }
    terrain_level_point {
      sim_grid_pos_x: 2936829.75
      sim_grid_pos_y: 2341463.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2937013
      sim_grid_pos_y: 2341328.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936987.25
      sim_grid_pos_y: 2341159.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936838.25
      sim_grid_pos_y: 2341173.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936752
      sim_grid_pos_y: 2341172.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936622
      sim_grid_pos_y: 2341184.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936551.75
      sim_grid_pos_y: 2341286.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936632.25
      sim_grid_pos_y: 2341437.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936584
      sim_grid_pos_y: 2341584.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2937030.75
      sim_grid_pos_y: 2341104
    }
    terrain_level_point {
      sim_grid_pos_x: 2936836.25
      sim_grid_pos_y: 2341122.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.93675e+06
      sim_grid_pos_y: 2341121.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936593.25
      sim_grid_pos_y: 2341135.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936491.75
      sim_grid_pos_y: 2341283.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936576.5
      sim_grid_pos_y: 2341442.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936546
      sim_grid_pos_y: 2341536
    }
    terrain_level_point {
      sim_grid_pos_x: 2936374
      sim_grid_pos_y: 2341546.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.9364e+06
      sim_grid_pos_y: 2341805.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936654.5
      sim_grid_pos_y: 2341825.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936867.75
      sim_grid_pos_y: 2341499.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2937068.25
      sim_grid_pos_y: 2341351.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2937074
      sim_grid_pos_y: 2341048.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936834.25
      sim_grid_pos_y: 2341071.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936748
      sim_grid_pos_y: 2.34107e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2936564.75
      sim_grid_pos_y: 2341086.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936432
      sim_grid_pos_y: 2.34128e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2936521
      sim_grid_pos_y: 2341447.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936508
      sim_grid_pos_y: 2341487
    }
    terrain_level_point {
      sim_grid_pos_x: 2936317.75
      sim_grid_pos_y: 2341499
    }
    terrain_level_point {
      sim_grid_pos_x: 2936353.25
      sim_grid_pos_y: 2341853.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936680.75
      sim_grid_pos_y: 2341879
    }
    terrain_level_point {
      sim_grid_pos_x: 2936905.5
      sim_grid_pos_y: 2341535.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2937123.5
      sim_grid_pos_y: 2341374.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2937117.5
      sim_grid_pos_y: 2340992.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936832
      sim_grid_pos_y: 2.34102e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2936746.25
      sim_grid_pos_y: 2341018.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936536
      sim_grid_pos_y: 2341037.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936372
      sim_grid_pos_y: 2341276.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936458.5
      sim_grid_pos_y: 2341438.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936261.5
      sim_grid_pos_y: 2341451.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936306.5
      sim_grid_pos_y: 2341901.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936707.25
      sim_grid_pos_y: 2341932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936943.5
      sim_grid_pos_y: 2341571
    }
    terrain_level_point {
      sim_grid_pos_x: 2937179
      sim_grid_pos_y: 2341397.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2937160.75
      sim_grid_pos_y: 2340937
    }
    terrain_level_point {
      sim_grid_pos_x: 2.93683e+06
      sim_grid_pos_y: 2340968.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936744.25
      sim_grid_pos_y: 2340967.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936507.5
      sim_grid_pos_y: 2340989
    }
    terrain_level_point {
      sim_grid_pos_x: 2936312
      sim_grid_pos_y: 2341273.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936375.75
      sim_grid_pos_y: 2341392.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936205
      sim_grid_pos_y: 2341403.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936259.75
      sim_grid_pos_y: 2341949.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936733.5
      sim_grid_pos_y: 2341985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936981.25
      sim_grid_pos_y: 2341606.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2937234.25
      sim_grid_pos_y: 2341420.25
    }
  }
}
terrain_level_data {
  terrain_level: 118
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2936215.75
      sim_grid_pos_y: 2341212
    }
    terrain_level_point {
      sim_grid_pos_x: 2936177.25
      sim_grid_pos_y: 2341405
    }
    terrain_level_point {
      sim_grid_pos_x: 2936388
      sim_grid_pos_y: 2341421.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936388.25
      sim_grid_pos_y: 2341249
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2936175.75
      sim_grid_pos_y: 2341150.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2936115.75
      sim_grid_pos_y: 2341451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2936439
      sim_grid_pos_y: 2341477.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2936439.75
      sim_grid_pos_y: 2341207.75
    }
  }
}
