terrain_level_data {
  terrain_level: 332
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 983557.312
      sim_grid_pos_y: 2051457.62
    }
    terrain_level_point {
      sim_grid_pos_x: 983741.188
      sim_grid_pos_y: 2051563.75
    }
    terrain_level_point {
      sim_grid_pos_x: 983801.812
      sim_grid_pos_y: 2051736.88
    }
    terrain_level_point {
      sim_grid_pos_x: 983808.5
      sim_grid_pos_y: 2051977.25
    }
    terrain_level_point {
      sim_grid_pos_x: 983785.438
      sim_grid_pos_y: 2052168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983831.062
      sim_grid_pos_y: 2052459
    }
    terrain_level_point {
      sim_grid_pos_x: 983834.188
      sim_grid_pos_y: 2052575
    }
    terrain_level_point {
      sim_grid_pos_x: 984038.188
      sim_grid_pos_y: 2052602.75
    }
    terrain_level_point {
      sim_grid_pos_x: 984090.438
      sim_grid_pos_y: 2052448.38
    }
    terrain_level_point {
      sim_grid_pos_x: 984091.812
      sim_grid_pos_y: 2052303
    }
    terrain_level_point {
      sim_grid_pos_x: 984068.25
      sim_grid_pos_y: 2052257.38
    }
    terrain_level_point {
      sim_grid_pos_x: 984083
      sim_grid_pos_y: 2052179.38
    }
    terrain_level_point {
      sim_grid_pos_x: 984119.188
      sim_grid_pos_y: 2051962.88
    }
    terrain_level_point {
      sim_grid_pos_x: 984131.375
      sim_grid_pos_y: 2051806.5
    }
    terrain_level_point {
      sim_grid_pos_x: 984147.812
      sim_grid_pos_y: 2051743.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 983544
      sim_grid_pos_y: 2051417
    }
    terrain_level_point {
      sim_grid_pos_x: 983516.25
      sim_grid_pos_y: 2051469.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983715.938
      sim_grid_pos_y: 2051584.62
    }
    terrain_level_point {
      sim_grid_pos_x: 983771.188
      sim_grid_pos_y: 2051742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983777.688
      sim_grid_pos_y: 2051975.88
    }
    terrain_level_point {
      sim_grid_pos_x: 983754.375
      sim_grid_pos_y: 2052169
    }
    terrain_level_point {
      sim_grid_pos_x: 983800.375
      sim_grid_pos_y: 2052461.75
    }
    terrain_level_point {
      sim_grid_pos_x: 983804.125
      sim_grid_pos_y: 2052602
    }
    terrain_level_point {
      sim_grid_pos_x: 984059.188
      sim_grid_pos_y: 2052636.62
    }
    terrain_level_point {
      sim_grid_pos_x: 984121.125
      sim_grid_pos_y: 2052453.62
    }
    terrain_level_point {
      sim_grid_pos_x: 984122.625
      sim_grid_pos_y: 2052295.75
    }
    terrain_level_point {
      sim_grid_pos_x: 984100.438
      sim_grid_pos_y: 2052252.62
    }
    terrain_level_point {
      sim_grid_pos_x: 984113.25
      sim_grid_pos_y: 2052184.88
    }
    terrain_level_point {
      sim_grid_pos_x: 984149.75
      sim_grid_pos_y: 2051966.62
    }
    terrain_level_point {
      sim_grid_pos_x: 984161.812
      sim_grid_pos_y: 2051811.75
    }
    terrain_level_point {
      sim_grid_pos_x: 984184
      sim_grid_pos_y: 2051727
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 983530.688
      sim_grid_pos_y: 2051376.38
    }
    terrain_level_point {
      sim_grid_pos_x: 983475.125
      sim_grid_pos_y: 2051481.25
    }
    terrain_level_point {
      sim_grid_pos_x: 983690.688
      sim_grid_pos_y: 2051605.62
    }
    terrain_level_point {
      sim_grid_pos_x: 983740.562
      sim_grid_pos_y: 2051748.12
    }
    terrain_level_point {
      sim_grid_pos_x: 983746.938
      sim_grid_pos_y: 2051974.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983723.312
      sim_grid_pos_y: 2052169.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983769.688
      sim_grid_pos_y: 2052464.62
    }
    terrain_level_point {
      sim_grid_pos_x: 983774.125
      sim_grid_pos_y: 2052629
    }
    terrain_level_point {
      sim_grid_pos_x: 984080.188
      sim_grid_pos_y: 2052670.5
    }
    terrain_level_point {
      sim_grid_pos_x: 984151.875
      sim_grid_pos_y: 2052458.88
    }
    terrain_level_point {
      sim_grid_pos_x: 984153.438
      sim_grid_pos_y: 2052288.38
    }
    terrain_level_point {
      sim_grid_pos_x: 984132.625
      sim_grid_pos_y: 2052247.88
    }
    terrain_level_point {
      sim_grid_pos_x: 984143.562
      sim_grid_pos_y: 2052190.25
    }
    terrain_level_point {
      sim_grid_pos_x: 984180.312
      sim_grid_pos_y: 2051970.38
    }
    terrain_level_point {
      sim_grid_pos_x: 984192.312
      sim_grid_pos_y: 2051816.75
    }
    terrain_level_point {
      sim_grid_pos_x: 984220.125
      sim_grid_pos_y: 2051710.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 983517.438
      sim_grid_pos_y: 2051335.75
    }
    terrain_level_point {
      sim_grid_pos_x: 983434.062
      sim_grid_pos_y: 2051493.12
    }
    terrain_level_point {
      sim_grid_pos_x: 983665.438
      sim_grid_pos_y: 2051626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983709.938
      sim_grid_pos_y: 2051753.75
    }
    terrain_level_point {
      sim_grid_pos_x: 983716.062
      sim_grid_pos_y: 2051973
    }
    terrain_level_point {
      sim_grid_pos_x: 983692.312
      sim_grid_pos_y: 2052170.12
    }
    terrain_level_point {
      sim_grid_pos_x: 983739
      sim_grid_pos_y: 2052467.5
    }
    terrain_level_point {
      sim_grid_pos_x: 983744.062
      sim_grid_pos_y: 2052656
    }
    terrain_level_point {
      sim_grid_pos_x: 984101.188
      sim_grid_pos_y: 2052704.38
    }
    terrain_level_point {
      sim_grid_pos_x: 984182.562
      sim_grid_pos_y: 2052464
    }
    terrain_level_point {
      sim_grid_pos_x: 984184.312
      sim_grid_pos_y: 2052281
    }
    terrain_level_point {
      sim_grid_pos_x: 984164.812
      sim_grid_pos_y: 2052243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 984173.812
      sim_grid_pos_y: 2052195.62
    }
    terrain_level_point {
      sim_grid_pos_x: 984210.875
      sim_grid_pos_y: 2051974.12
    }
    terrain_level_point {
      sim_grid_pos_x: 984222.75
      sim_grid_pos_y: 2051822
    }
    terrain_level_point {
      sim_grid_pos_x: 984256.312
      sim_grid_pos_y: 2051693.75
    }
  }
}
