terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 317701.844
      sim_grid_pos_y: 1337986.75
    }
    terrain_level_point {
      sim_grid_pos_x: 318752.062
      sim_grid_pos_y: 1338279.88
    }
    terrain_level_point {
      sim_grid_pos_x: 319045.75
      sim_grid_pos_y: 1338453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 319569.281
      sim_grid_pos_y: 1338754.88
    }
    terrain_level_point {
      sim_grid_pos_x: 320233.344
      sim_grid_pos_y: 1338676.75
    }
    terrain_level_point {
      sim_grid_pos_x: 320481.406
      sim_grid_pos_y: 1338683.88
    }
    terrain_level_point {
      sim_grid_pos_x: 320509.031
      sim_grid_pos_y: 1338340.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322560.156
      sim_grid_pos_y: 1338403
    }
    terrain_level_point {
      sim_grid_pos_x: 322619
      sim_grid_pos_y: 1337279.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324912.312
      sim_grid_pos_y: 1337336.62
    }
    terrain_level_point {
      sim_grid_pos_x: 326135.219
      sim_grid_pos_y: 1336817.75
    }
    terrain_level_point {
      sim_grid_pos_x: 326517
      sim_grid_pos_y: 1336586.62
    }
    terrain_level_point {
      sim_grid_pos_x: 327541.062
      sim_grid_pos_y: 1336099.62
    }
    terrain_level_point {
      sim_grid_pos_x: 329584.531
      sim_grid_pos_y: 1336206.12
    }
    terrain_level_point {
      sim_grid_pos_x: 329829.812
      sim_grid_pos_y: 1336224.12
    }
    terrain_level_point {
      sim_grid_pos_x: 333303.062
      sim_grid_pos_y: 1336841.75
    }
    terrain_level_point {
      sim_grid_pos_x: 333292.469
      sim_grid_pos_y: 1336774.62
    }
    terrain_level_point {
      sim_grid_pos_x: 329867.312
      sim_grid_pos_y: 1336156.12
    }
    terrain_level_point {
      sim_grid_pos_x: 329154.812
      sim_grid_pos_y: 1336027.12
    }
    terrain_level_point {
      sim_grid_pos_x: 328522.344
      sim_grid_pos_y: 1335948.38
    }
    terrain_level_point {
      sim_grid_pos_x: 328095.656
      sim_grid_pos_y: 1335925.12
    }
    terrain_level_point {
      sim_grid_pos_x: 327400.875
      sim_grid_pos_y: 1336007.62
    }
    terrain_level_point {
      sim_grid_pos_x: 325918.062
      sim_grid_pos_y: 1336788.25
    }
    terrain_level_point {
      sim_grid_pos_x: 324903.562
      sim_grid_pos_y: 1337197
    }
    terrain_level_point {
      sim_grid_pos_x: 324654.25
      sim_grid_pos_y: 1337214.38
    }
    terrain_level_point {
      sim_grid_pos_x: 324583.188
      sim_grid_pos_y: 1335537.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322501.438
      sim_grid_pos_y: 1335553.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322508.812
      sim_grid_pos_y: 1335846.12
    }
    terrain_level_point {
      sim_grid_pos_x: 321221.344
      sim_grid_pos_y: 1335787.38
    }
    terrain_level_point {
      sim_grid_pos_x: 321232.156
      sim_grid_pos_y: 1334604.5
    }
    terrain_level_point {
      sim_grid_pos_x: 317180.844
      sim_grid_pos_y: 1334598.12
    }
    terrain_level_point {
      sim_grid_pos_x: 316350.969
      sim_grid_pos_y: 1335532.62
    }
    terrain_level_point {
      sim_grid_pos_x: 316494.125
      sim_grid_pos_y: 1335684.5
    }
    terrain_level_point {
      sim_grid_pos_x: 315690.875
      sim_grid_pos_y: 1336507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 315825.438
      sim_grid_pos_y: 1336671.25
    }
    terrain_level_point {
      sim_grid_pos_x: 315988.906
      sim_grid_pos_y: 1336518.38
    }
    terrain_level_point {
      sim_grid_pos_x: 316948.125
      sim_grid_pos_y: 1336160.62
    }
    terrain_level_point {
      sim_grid_pos_x: 317773.25
      sim_grid_pos_y: 1336953.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 317171.656
      sim_grid_pos_y: 1334577.62
    }
    terrain_level_point {
      sim_grid_pos_x: 316323.156
      sim_grid_pos_y: 1335533
    }
    terrain_level_point {
      sim_grid_pos_x: 316465.719
      sim_grid_pos_y: 1335684.25
    }
    terrain_level_point {
      sim_grid_pos_x: 315663.375
      sim_grid_pos_y: 1336506.12
    }
    terrain_level_point {
      sim_grid_pos_x: 315823.469
      sim_grid_pos_y: 1336701.12
    }
    terrain_level_point {
      sim_grid_pos_x: 315999.938
      sim_grid_pos_y: 1336536.12
    }
    terrain_level_point {
      sim_grid_pos_x: 316943.219
      sim_grid_pos_y: 1336184.38
    }
    terrain_level_point {
      sim_grid_pos_x: 317752.125
      sim_grid_pos_y: 1336961.62
    }
    terrain_level_point {
      sim_grid_pos_x: 317680.25
      sim_grid_pos_y: 1338002
    }
    terrain_level_point {
      sim_grid_pos_x: 318743.906
      sim_grid_pos_y: 1338299
    }
    terrain_level_point {
      sim_grid_pos_x: 319035.406
      sim_grid_pos_y: 1338471.38
    }
    terrain_level_point {
      sim_grid_pos_x: 319564.938
      sim_grid_pos_y: 1338776.12
    }
    terrain_level_point {
      sim_grid_pos_x: 320234.219
      sim_grid_pos_y: 1338697.38
    }
    terrain_level_point {
      sim_grid_pos_x: 320500.281
      sim_grid_pos_y: 1338705
    }
    terrain_level_point {
      sim_grid_pos_x: 320527.906
      sim_grid_pos_y: 1338361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 322579.594
      sim_grid_pos_y: 1338424.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322638.438
      sim_grid_pos_y: 1337300.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324916.25
      sim_grid_pos_y: 1337357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 326144.594
      sim_grid_pos_y: 1336836.12
    }
    terrain_level_point {
      sim_grid_pos_x: 326526.719
      sim_grid_pos_y: 1336604.62
    }
    terrain_level_point {
      sim_grid_pos_x: 327545.156
      sim_grid_pos_y: 1336120.38
    }
    terrain_level_point {
      sim_grid_pos_x: 329583.406
      sim_grid_pos_y: 1336226.62
    }
    terrain_level_point {
      sim_grid_pos_x: 329827.25
      sim_grid_pos_y: 1336244.5
    }
    terrain_level_point {
      sim_grid_pos_x: 333327.781
      sim_grid_pos_y: 1336867
    }
    terrain_level_point {
      sim_grid_pos_x: 333310.438
      sim_grid_pos_y: 1336757
    }
    terrain_level_point {
      sim_grid_pos_x: 329870.938
      sim_grid_pos_y: 1336136
    }
    terrain_level_point {
      sim_grid_pos_x: 329870.938
      sim_grid_pos_y: 1336136
    }
    terrain_level_point {
      sim_grid_pos_x: 329157.906
      sim_grid_pos_y: 1336006.88
    }
    terrain_level_point {
      sim_grid_pos_x: 328524.156
      sim_grid_pos_y: 1335928
    }
    terrain_level_point {
      sim_grid_pos_x: 328095
      sim_grid_pos_y: 1335904.5
    }
    terrain_level_point {
      sim_grid_pos_x: 327394.656
      sim_grid_pos_y: 1335987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 325909.469
      sim_grid_pos_y: 1336769.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324898.938
      sim_grid_pos_y: 1337176.88
    }
    terrain_level_point {
      sim_grid_pos_x: 324673.844
      sim_grid_pos_y: 1337192.38
    }
    terrain_level_point {
      sim_grid_pos_x: 324602.844
      sim_grid_pos_y: 1335516.88
    }
    terrain_level_point {
      sim_grid_pos_x: 322480.438
      sim_grid_pos_y: 1335533.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322487.75
      sim_grid_pos_y: 1335824.62
    }
    terrain_level_point {
      sim_grid_pos_x: 321242.031
      sim_grid_pos_y: 1335767.75
    }
    terrain_level_point {
      sim_grid_pos_x: 321252.844
      sim_grid_pos_y: 1334584
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 317162.438
      sim_grid_pos_y: 1334557.12
    }
    terrain_level_point {
      sim_grid_pos_x: 316295.375
      sim_grid_pos_y: 1335533.5
    }
    terrain_level_point {
      sim_grid_pos_x: 316437.312
      sim_grid_pos_y: 1335684
    }
    terrain_level_point {
      sim_grid_pos_x: 315635.875
      sim_grid_pos_y: 1336504.88
    }
    terrain_level_point {
      sim_grid_pos_x: 315821.5
      sim_grid_pos_y: 1336731
    }
    terrain_level_point {
      sim_grid_pos_x: 316010.906
      sim_grid_pos_y: 1336553.88
    }
    terrain_level_point {
      sim_grid_pos_x: 316938.312
      sim_grid_pos_y: 1336208.12
    }
    terrain_level_point {
      sim_grid_pos_x: 317731.031
      sim_grid_pos_y: 1336969.75
    }
    terrain_level_point {
      sim_grid_pos_x: 317658.625
      sim_grid_pos_y: 1338017.25
    }
    terrain_level_point {
      sim_grid_pos_x: 318735.812
      sim_grid_pos_y: 1338318
    }
    terrain_level_point {
      sim_grid_pos_x: 319025.094
      sim_grid_pos_y: 1338489.12
    }
    terrain_level_point {
      sim_grid_pos_x: 319560.594
      sim_grid_pos_y: 1338797.25
    }
    terrain_level_point {
      sim_grid_pos_x: 320235.188
      sim_grid_pos_y: 1338717.88
    }
    terrain_level_point {
      sim_grid_pos_x: 320519.156
      sim_grid_pos_y: 1338726
    }
    terrain_level_point {
      sim_grid_pos_x: 320546.781
      sim_grid_pos_y: 1338382.75
    }
    terrain_level_point {
      sim_grid_pos_x: 322599.031
      sim_grid_pos_y: 1338445.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322657.875
      sim_grid_pos_y: 1337321.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324920.156
      sim_grid_pos_y: 1337377.88
    }
    terrain_level_point {
      sim_grid_pos_x: 326153.969
      sim_grid_pos_y: 1336854.38
    }
    terrain_level_point {
      sim_grid_pos_x: 326536.5
      sim_grid_pos_y: 1336622.75
    }
    terrain_level_point {
      sim_grid_pos_x: 327549.281
      sim_grid_pos_y: 1336141.12
    }
    terrain_level_point {
      sim_grid_pos_x: 329581.781
      sim_grid_pos_y: 1336247.12
    }
    terrain_level_point {
      sim_grid_pos_x: 329824.656
      sim_grid_pos_y: 1336264.88
    }
    terrain_level_point {
      sim_grid_pos_x: 333352.531
      sim_grid_pos_y: 1336892.25
    }
    terrain_level_point {
      sim_grid_pos_x: 333328.438
      sim_grid_pos_y: 1336739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 329874.594
      sim_grid_pos_y: 1336115.88
    }
    terrain_level_point {
      sim_grid_pos_x: 329874.625
      sim_grid_pos_y: 1336115.88
    }
    terrain_level_point {
      sim_grid_pos_x: 329161
      sim_grid_pos_y: 1335986.62
    }
    terrain_level_point {
      sim_grid_pos_x: 328526
      sim_grid_pos_y: 1335907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 328094.344
      sim_grid_pos_y: 1335884
    }
    terrain_level_point {
      sim_grid_pos_x: 327388.469
      sim_grid_pos_y: 1335967.88
    }
    terrain_level_point {
      sim_grid_pos_x: 325900.812
      sim_grid_pos_y: 1336751
    }
    terrain_level_point {
      sim_grid_pos_x: 324894.25
      sim_grid_pos_y: 1337156.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324693.438
      sim_grid_pos_y: 1337170.5
    }
    terrain_level_point {
      sim_grid_pos_x: 324622.5
      sim_grid_pos_y: 1335496.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322459.406
      sim_grid_pos_y: 1335512.75
    }
    terrain_level_point {
      sim_grid_pos_x: 322466.688
      sim_grid_pos_y: 1335803.25
    }
    terrain_level_point {
      sim_grid_pos_x: 321262.719
      sim_grid_pos_y: 1335748.25
    }
    terrain_level_point {
      sim_grid_pos_x: 321273.562
      sim_grid_pos_y: 1334563.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 317153.25
      sim_grid_pos_y: 1334536.62
    }
    terrain_level_point {
      sim_grid_pos_x: 316267.594
      sim_grid_pos_y: 1335533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 316408.875
      sim_grid_pos_y: 1335683.75
    }
    terrain_level_point {
      sim_grid_pos_x: 315608.375
      sim_grid_pos_y: 1336503.75
    }
    terrain_level_point {
      sim_grid_pos_x: 315819.531
      sim_grid_pos_y: 1336761
    }
    terrain_level_point {
      sim_grid_pos_x: 316021.938
      sim_grid_pos_y: 1336571.62
    }
    terrain_level_point {
      sim_grid_pos_x: 316933.406
      sim_grid_pos_y: 1336231.88
    }
    terrain_level_point {
      sim_grid_pos_x: 317709.906
      sim_grid_pos_y: 1336977.88
    }
    terrain_level_point {
      sim_grid_pos_x: 317637.031
      sim_grid_pos_y: 1338032.5
    }
    terrain_level_point {
      sim_grid_pos_x: 318727.688
      sim_grid_pos_y: 1338337
    }
    terrain_level_point {
      sim_grid_pos_x: 319014.75
      sim_grid_pos_y: 1338506.88
    }
    terrain_level_point {
      sim_grid_pos_x: 319556.25
      sim_grid_pos_y: 1338818.38
    }
    terrain_level_point {
      sim_grid_pos_x: 320236.062
      sim_grid_pos_y: 1338738.38
    }
    terrain_level_point {
      sim_grid_pos_x: 320538.031
      sim_grid_pos_y: 1338747
    }
    terrain_level_point {
      sim_grid_pos_x: 320565.656
      sim_grid_pos_y: 1338403.88
    }
    terrain_level_point {
      sim_grid_pos_x: 322618.438
      sim_grid_pos_y: 1338466.38
    }
    terrain_level_point {
      sim_grid_pos_x: 322677.312
      sim_grid_pos_y: 1337342.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324924.094
      sim_grid_pos_y: 1337398.5
    }
    terrain_level_point {
      sim_grid_pos_x: 326163.312
      sim_grid_pos_y: 1336872.75
    }
    terrain_level_point {
      sim_grid_pos_x: 326546.188
      sim_grid_pos_y: 1336640.88
    }
    terrain_level_point {
      sim_grid_pos_x: 327553.406
      sim_grid_pos_y: 1336161.88
    }
    terrain_level_point {
      sim_grid_pos_x: 329580.656
      sim_grid_pos_y: 1336267.62
    }
    terrain_level_point {
      sim_grid_pos_x: 329822.125
      sim_grid_pos_y: 1336285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 333377.281
      sim_grid_pos_y: 1336917.38
    }
    terrain_level_point {
      sim_grid_pos_x: 333346.406
      sim_grid_pos_y: 1336721.88
    }
    terrain_level_point {
      sim_grid_pos_x: 329878.219
      sim_grid_pos_y: 1336095.62
    }
    terrain_level_point {
      sim_grid_pos_x: 329878.25
      sim_grid_pos_y: 1336095.62
    }
    terrain_level_point {
      sim_grid_pos_x: 329164.094
      sim_grid_pos_y: 1335966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 328527.812
      sim_grid_pos_y: 1335887.12
    }
    terrain_level_point {
      sim_grid_pos_x: 328093.688
      sim_grid_pos_y: 1335863.38
    }
    terrain_level_point {
      sim_grid_pos_x: 327382.281
      sim_grid_pos_y: 1335947.88
    }
    terrain_level_point {
      sim_grid_pos_x: 325892.188
      sim_grid_pos_y: 1336732.38
    }
    terrain_level_point {
      sim_grid_pos_x: 324889.625
      sim_grid_pos_y: 1337136.38
    }
    terrain_level_point {
      sim_grid_pos_x: 324713.031
      sim_grid_pos_y: 1337148.62
    }
    terrain_level_point {
      sim_grid_pos_x: 324642.156
      sim_grid_pos_y: 1335475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322438.375
      sim_grid_pos_y: 1335492.38
    }
    terrain_level_point {
      sim_grid_pos_x: 322445.656
      sim_grid_pos_y: 1335781.75
    }
    terrain_level_point {
      sim_grid_pos_x: 321283.406
      sim_grid_pos_y: 1335728.62
    }
    terrain_level_point {
      sim_grid_pos_x: 321294.25
      sim_grid_pos_y: 1334543
    }
  }
}
