terrain_level_data {
  terrain_level: 75
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 771816.375
      sim_grid_pos_y: 2251025.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772897
      sim_grid_pos_y: 2247655.5
    }
    terrain_level_point {
      sim_grid_pos_x: 773529.812
      sim_grid_pos_y: 2245467
    }
    terrain_level_point {
      sim_grid_pos_x: 774254.875
      sim_grid_pos_y: 2242879.25
    }
    terrain_level_point {
      sim_grid_pos_x: 771876.938
      sim_grid_pos_y: 2241762.75
    }
    terrain_level_point {
      sim_grid_pos_x: 768929.188
      sim_grid_pos_y: 2243191.5
    }
    terrain_level_point {
      sim_grid_pos_x: 767479.188
      sim_grid_pos_y: 2246494
    }
    terrain_level_point {
      sim_grid_pos_x: 768221.5
      sim_grid_pos_y: 2250442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 768162.188
      sim_grid_pos_y: 2251934.25
    }
    terrain_level_point {
      sim_grid_pos_x: 768180.125
      sim_grid_pos_y: 2253407.25
    }
    terrain_level_point {
      sim_grid_pos_x: 770589.125
      sim_grid_pos_y: 2253408.25
    }
    terrain_level_point {
      sim_grid_pos_x: 772432.125
      sim_grid_pos_y: 2253103.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 771876.25
      sim_grid_pos_y: 2241649
    }
    terrain_level_point {
      sim_grid_pos_x: 768850.5
      sim_grid_pos_y: 2243115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 767372.562
      sim_grid_pos_y: 2246482
    }
    terrain_level_point {
      sim_grid_pos_x: 768118.625
      sim_grid_pos_y: 2.25045e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 768059.625
      sim_grid_pos_y: 2251932.75
    }
    terrain_level_point {
      sim_grid_pos_x: 768078.875
      sim_grid_pos_y: 2253509.75
    }
    terrain_level_point {
      sim_grid_pos_x: 770597.562
      sim_grid_pos_y: 2253510.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772563.438
      sim_grid_pos_y: 2253185.25
    }
    terrain_level_point {
      sim_grid_pos_x: 771923.688
      sim_grid_pos_y: 2251027
    }
    terrain_level_point {
      sim_grid_pos_x: 772995.125
      sim_grid_pos_y: 2247685.25
    }
    terrain_level_point {
      sim_grid_pos_x: 773628.375
      sim_grid_pos_y: 2245495
    }
    terrain_level_point {
      sim_grid_pos_x: 774377
      sim_grid_pos_y: 2242823.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 771875.562
      sim_grid_pos_y: 2241535.5
    }
    terrain_level_point {
      sim_grid_pos_x: 768771.812
      sim_grid_pos_y: 2.24304e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 767265.938
      sim_grid_pos_y: 2246469.75
    }
    terrain_level_point {
      sim_grid_pos_x: 768015.688
      sim_grid_pos_y: 2250457.5
    }
    terrain_level_point {
      sim_grid_pos_x: 767957.125
      sim_grid_pos_y: 2251931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 767977.562
      sim_grid_pos_y: 2253612.25
    }
    terrain_level_point {
      sim_grid_pos_x: 770605.938
      sim_grid_pos_y: 2253613.25
    }
    terrain_level_point {
      sim_grid_pos_x: 772694.688
      sim_grid_pos_y: 2253267.5
    }
    terrain_level_point {
      sim_grid_pos_x: 772031
      sim_grid_pos_y: 2251028.25
    }
    terrain_level_point {
      sim_grid_pos_x: 773093.188
      sim_grid_pos_y: 2247715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 773727
      sim_grid_pos_y: 2245523.25
    }
    terrain_level_point {
      sim_grid_pos_x: 774499.188
      sim_grid_pos_y: 2242767.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 771874.875
      sim_grid_pos_y: 2241422
    }
    terrain_level_point {
      sim_grid_pos_x: 768693.125
      sim_grid_pos_y: 2242964.25
    }
    terrain_level_point {
      sim_grid_pos_x: 767159.312
      sim_grid_pos_y: 2246457.5
    }
    terrain_level_point {
      sim_grid_pos_x: 767912.812
      sim_grid_pos_y: 2250465.25
    }
    terrain_level_point {
      sim_grid_pos_x: 767854.562
      sim_grid_pos_y: 2.25193e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 767876.312
      sim_grid_pos_y: 2253714.75
    }
    terrain_level_point {
      sim_grid_pos_x: 770614.375
      sim_grid_pos_y: 2253715.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772826
      sim_grid_pos_y: 2253349.75
    }
    terrain_level_point {
      sim_grid_pos_x: 772138.25
      sim_grid_pos_y: 2251029.5
    }
    terrain_level_point {
      sim_grid_pos_x: 773191.25
      sim_grid_pos_y: 2247745
    }
    terrain_level_point {
      sim_grid_pos_x: 773825.625
      sim_grid_pos_y: 2245551.25
    }
    terrain_level_point {
      sim_grid_pos_x: 774621.312
      sim_grid_pos_y: 2242711.5
    }
  }
}
