terrain_level_data {
  terrain_level: 52
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1394853.62
      sim_grid_pos_y: 1410346.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1394874
      sim_grid_pos_y: 1408148.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1395259
      sim_grid_pos_y: 1407697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395302.62
      sim_grid_pos_y: 1407542.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395224
      sim_grid_pos_y: 1407312
    }
    terrain_level_point {
      sim_grid_pos_x: 1395424
      sim_grid_pos_y: 1407101.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395454.75
      sim_grid_pos_y: 1407022
    }
    terrain_level_point {
      sim_grid_pos_x: 1395382
      sim_grid_pos_y: 1406950.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1395292.25
      sim_grid_pos_y: 1406719.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1395226.25
      sim_grid_pos_y: 1406697.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1395471.5
      sim_grid_pos_y: 1406532.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395605.62
      sim_grid_pos_y: 1406532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396297.75
      sim_grid_pos_y: 1407053.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396638.62
      sim_grid_pos_y: 1407168.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396584.75
      sim_grid_pos_y: 1407775.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1396645.88
      sim_grid_pos_y: 1408034.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1396916
      sim_grid_pos_y: 1408530.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1396889.38
      sim_grid_pos_y: 1408710.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396706.25
      sim_grid_pos_y: 1408855.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396843
      sim_grid_pos_y: 1408969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1396871.75
      sim_grid_pos_y: 1409119.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1396584.12
      sim_grid_pos_y: 1409499.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1396739.38
      sim_grid_pos_y: 1409654.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1396663.75
      sim_grid_pos_y: 1409731.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396288.12
      sim_grid_pos_y: 1409572.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396071.12
      sim_grid_pos_y: 1409537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395972.38
      sim_grid_pos_y: 1409624
    }
    terrain_level_point {
      sim_grid_pos_x: 1395994.38
      sim_grid_pos_y: 1409781.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1395922.88
      sim_grid_pos_y: 1409954.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1395662.5
      sim_grid_pos_y: 1410104.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1396355.88
      sim_grid_pos_y: 1406943.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1396769.75
      sim_grid_pos_y: 1407083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396709.12
      sim_grid_pos_y: 1407766.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1396761.88
      sim_grid_pos_y: 1407990.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1397043.75
      sim_grid_pos_y: 1408508
    }
    terrain_level_point {
      sim_grid_pos_x: 1397004
      sim_grid_pos_y: 1408777
    }
    terrain_level_point {
      sim_grid_pos_x: 1396901.5
      sim_grid_pos_y: 1408858.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1396955.62
      sim_grid_pos_y: 1408903
    }
    terrain_level_point {
      sim_grid_pos_x: 1397002.88
      sim_grid_pos_y: 1409150.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396747
      sim_grid_pos_y: 1409488.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396912.88
      sim_grid_pos_y: 1409653.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1396692.88
      sim_grid_pos_y: 1409877
    }
    terrain_level_point {
      sim_grid_pos_x: 1396253.88
      sim_grid_pos_y: 1409692
    }
    terrain_level_point {
      sim_grid_pos_x: 1396108.5
      sim_grid_pos_y: 1409668.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1396103.5
      sim_grid_pos_y: 1409672.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1396120.88
      sim_grid_pos_y: 1409797.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1396020.62
      sim_grid_pos_y: 1410040.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395711.5
      sim_grid_pos_y: 1410218
    }
    terrain_level_point {
      sim_grid_pos_x: 1394729.12
      sim_grid_pos_y: 1410512.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1394751.5
      sim_grid_pos_y: 1408102.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1395147.88
      sim_grid_pos_y: 1407638.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1395173.88
      sim_grid_pos_y: 1407546.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395083.5
      sim_grid_pos_y: 1407281.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395305.12
      sim_grid_pos_y: 1407047.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395276.88
      sim_grid_pos_y: 1407020.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395198.62
      sim_grid_pos_y: 1406818
    }
    terrain_level_point {
      sim_grid_pos_x: 1395115
      sim_grid_pos_y: 1406790.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395093.75
      sim_grid_pos_y: 1406638.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1395433.75
      sim_grid_pos_y: 1406409.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1395646.5
      sim_grid_pos_y: 1406409
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1396414
      sim_grid_pos_y: 1406833.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1396900.88
      sim_grid_pos_y: 1406997.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1396833.38
      sim_grid_pos_y: 1407757.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396877.75
      sim_grid_pos_y: 1407945.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1397171.5
      sim_grid_pos_y: 1408485.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1397118.5
      sim_grid_pos_y: 1408843.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1397075.88
      sim_grid_pos_y: 1408877
    }
    terrain_level_point {
      sim_grid_pos_x: 1397134
      sim_grid_pos_y: 1409180.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396909.88
      sim_grid_pos_y: 1409476.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1397086.38
      sim_grid_pos_y: 1409653
    }
    terrain_level_point {
      sim_grid_pos_x: 1396722
      sim_grid_pos_y: 1410022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1396244
      sim_grid_pos_y: 1409821.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1396118.38
      sim_grid_pos_y: 1410125.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1395760.5
      sim_grid_pos_y: 1410331.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1394604.5
      sim_grid_pos_y: 1410678.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1394628.88
      sim_grid_pos_y: 1408056.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395036.75
      sim_grid_pos_y: 1407579
    }
    terrain_level_point {
      sim_grid_pos_x: 1395045
      sim_grid_pos_y: 1407549.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1394943.12
      sim_grid_pos_y: 1407250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1395149.75
      sim_grid_pos_y: 1407032.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395104.88
      sim_grid_pos_y: 1406916.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1395003.75
      sim_grid_pos_y: 1406883.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1394961.38
      sim_grid_pos_y: 1406579.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1395396
      sim_grid_pos_y: 1406287
    }
    terrain_level_point {
      sim_grid_pos_x: 1395687.5
      sim_grid_pos_y: 1406285.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1396472.25
      sim_grid_pos_y: 1406723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1397032
      sim_grid_pos_y: 1406912
    }
    terrain_level_point {
      sim_grid_pos_x: 1396957.75
      sim_grid_pos_y: 1407748.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396993.75
      sim_grid_pos_y: 1407901.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1397299.25
      sim_grid_pos_y: 1408462.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1397233.12
      sim_grid_pos_y: 1408909.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1397210.75
      sim_grid_pos_y: 1408927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1397265.12
      sim_grid_pos_y: 1409211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1397072.75
      sim_grid_pos_y: 1409465.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1397259.88
      sim_grid_pos_y: 1409652.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396751
      sim_grid_pos_y: 1410168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1396310.5
      sim_grid_pos_y: 1409982.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1396216.12
      sim_grid_pos_y: 1410211.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1395809.5
      sim_grid_pos_y: 1410445.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.39448e+06
      sim_grid_pos_y: 1410844
    }
    terrain_level_point {
      sim_grid_pos_x: 1394506.25
      sim_grid_pos_y: 1408010.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1394910.75
      sim_grid_pos_y: 1407537.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1394802.62
      sim_grid_pos_y: 1407219.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1394999.88
      sim_grid_pos_y: 1407012
    }
    terrain_level_point {
      sim_grid_pos_x: 1394892.5
      sim_grid_pos_y: 1406977
    }
    terrain_level_point {
      sim_grid_pos_x: 1394828.88
      sim_grid_pos_y: 1.40652e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1395358.25
      sim_grid_pos_y: 1406164.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1395728.38
      sim_grid_pos_y: 1406162.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1396530.38
      sim_grid_pos_y: 1406613
    }
    terrain_level_point {
      sim_grid_pos_x: 1397163.12
      sim_grid_pos_y: 1406826.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1397082
      sim_grid_pos_y: 1.40774e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1397109.75
      sim_grid_pos_y: 1407857.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1397427
      sim_grid_pos_y: 1408439.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1397347.62
      sim_grid_pos_y: 1408975.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1397345.5
      sim_grid_pos_y: 1408977.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1397396.25
      sim_grid_pos_y: 1409242.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1397235.62
      sim_grid_pos_y: 1409454.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1397433.25
      sim_grid_pos_y: 1409651.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1396780.12
      sim_grid_pos_y: 1410314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1396377
      sim_grid_pos_y: 1410144.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1396313.88
      sim_grid_pos_y: 1410297.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1395858.5
      sim_grid_pos_y: 1410559.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1394355.38
      sim_grid_pos_y: 1411009.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1394383.62
      sim_grid_pos_y: 1407964.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1394771.75
      sim_grid_pos_y: 1407510.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1394662.25
      sim_grid_pos_y: 1407189
    }
    terrain_level_point {
      sim_grid_pos_x: 1394780.5
      sim_grid_pos_y: 1407064.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1394696.38
      sim_grid_pos_y: 1406460.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1395320.5
      sim_grid_pos_y: 1406041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1395769.38
      sim_grid_pos_y: 1406039.38
    }
  }
}
