terrain_level_data {
  terrain_level: 600
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3279553
      sim_grid_pos_y: 2200212
    }
    terrain_level_point {
      sim_grid_pos_x: 3280539.75
      sim_grid_pos_y: 2199844.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3280292.5
      sim_grid_pos_y: 2198373.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3280352.5
      sim_grid_pos_y: 2198135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3280250.25
      sim_grid_pos_y: 2197593.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3282148.75
      sim_grid_pos_y: 2197288.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3283192.75
      sim_grid_pos_y: 2198259.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3283461.5
      sim_grid_pos_y: 2198574
    }
    terrain_level_point {
      sim_grid_pos_x: 3284187
      sim_grid_pos_y: 2206797.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3283621.5
      sim_grid_pos_y: 2207874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3283312
      sim_grid_pos_y: 2208314
    }
    terrain_level_point {
      sim_grid_pos_x: 3282556
      sim_grid_pos_y: 2208469
    }
    terrain_level_point {
      sim_grid_pos_x: 3282411
      sim_grid_pos_y: 2207567.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3280873
      sim_grid_pos_y: 2206242
    }
    terrain_level_point {
      sim_grid_pos_x: 3279640.75
      sim_grid_pos_y: 2206262.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3278986.25
      sim_grid_pos_y: 2205498.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3278743.75
      sim_grid_pos_y: 2202814.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3278684
      sim_grid_pos_y: 2202121.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3279832.75
      sim_grid_pos_y: 2201979.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 3283229.75
      sim_grid_pos_y: 2198223.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3283511.25
      sim_grid_pos_y: 2198553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3284239.25
      sim_grid_pos_y: 2206808
    }
    terrain_level_point {
      sim_grid_pos_x: 3283665.25
      sim_grid_pos_y: 2207901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3283342.25
      sim_grid_pos_y: 2208360.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3282514
      sim_grid_pos_y: 2.20853e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 3282363.25
      sim_grid_pos_y: 2207594
    }
    terrain_level_point {
      sim_grid_pos_x: 3280854.25
      sim_grid_pos_y: 2206293.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3279617.5
      sim_grid_pos_y: 2206314
    }
    terrain_level_point {
      sim_grid_pos_x: 3278936.75
      sim_grid_pos_y: 2205519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3278692.75
      sim_grid_pos_y: 2202818.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3278628.5
      sim_grid_pos_y: 2202076.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3279773.75
      sim_grid_pos_y: 2201935
    }
    terrain_level_point {
      sim_grid_pos_x: 3279495.75
      sim_grid_pos_y: 2200178.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3280482.25
      sim_grid_pos_y: 2199811.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3280240.25
      sim_grid_pos_y: 2198371.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3.2803e+06
      sim_grid_pos_y: 2198133.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3.28019e+06
      sim_grid_pos_y: 2197551
    }
    terrain_level_point {
      sim_grid_pos_x: 3282165.25
      sim_grid_pos_y: 2197233.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 3283266.75
      sim_grid_pos_y: 2198188
    }
    terrain_level_point {
      sim_grid_pos_x: 3283560.75
      sim_grid_pos_y: 2198532.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3284291.75
      sim_grid_pos_y: 2206818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3283709
      sim_grid_pos_y: 2207928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3283372.5
      sim_grid_pos_y: 2208406.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3282471.75
      sim_grid_pos_y: 2208591
    }
    terrain_level_point {
      sim_grid_pos_x: 3282315.75
      sim_grid_pos_y: 2207620.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3280835.75
      sim_grid_pos_y: 2206345
    }
    terrain_level_point {
      sim_grid_pos_x: 3279594.25
      sim_grid_pos_y: 2206365.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3278887
      sim_grid_pos_y: 2.20554e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 3278641.75
      sim_grid_pos_y: 2202823.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3278573.25
      sim_grid_pos_y: 2202031.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3279714.75
      sim_grid_pos_y: 2201890.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3279438.5
      sim_grid_pos_y: 2200145.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3280424.5
      sim_grid_pos_y: 2199778.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3280187.75
      sim_grid_pos_y: 2198369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3280247.75
      sim_grid_pos_y: 2198132.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3.28013e+06
      sim_grid_pos_y: 2197508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3282182
      sim_grid_pos_y: 2197179
    }
  }
}
