terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 117113.695
      sim_grid_pos_y: 3102720.75
    }
    terrain_level_point {
      sim_grid_pos_x: 117276.328
      sim_grid_pos_y: 3103715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118799.656
      sim_grid_pos_y: 3.10348e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 118672.75
      sim_grid_pos_y: 3102471.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117990.703
      sim_grid_pos_y: 3102156
    }
    terrain_level_point {
      sim_grid_pos_x: 117347.297
      sim_grid_pos_y: 3102196
    }
    terrain_level_point {
      sim_grid_pos_x: 117337.148
      sim_grid_pos_y: 3102297.5
    }
    terrain_level_point {
      sim_grid_pos_x: 117388.258
      sim_grid_pos_y: 3102598.75
    }
    terrain_level_point {
      sim_grid_pos_x: 117126.75
      sim_grid_pos_y: 3102609.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 117994.602
      sim_grid_pos_y: 3102135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117328.633
      sim_grid_pos_y: 3102176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 117316.469
      sim_grid_pos_y: 3102298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117364.148
      sim_grid_pos_y: 3102579.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117108.43
      sim_grid_pos_y: 3.10259e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 117093
      sim_grid_pos_y: 3102721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117259.367
      sim_grid_pos_y: 3103738.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118822.492
      sim_grid_pos_y: 3103497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118691.68
      sim_grid_pos_y: 3102457.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 117998.5
      sim_grid_pos_y: 3102114.5
    }
    terrain_level_point {
      sim_grid_pos_x: 117309.961
      sim_grid_pos_y: 3102157.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117295.789
      sim_grid_pos_y: 3102299
    }
    terrain_level_point {
      sim_grid_pos_x: 117340.047
      sim_grid_pos_y: 3102559.75
    }
    terrain_level_point {
      sim_grid_pos_x: 117090.102
      sim_grid_pos_y: 3102570.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117072.297
      sim_grid_pos_y: 3102721.75
    }
    terrain_level_point {
      sim_grid_pos_x: 117242.422
      sim_grid_pos_y: 3103762
    }
    terrain_level_point {
      sim_grid_pos_x: 118845.328
      sim_grid_pos_y: 3103514.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118710.602
      sim_grid_pos_y: 3102443.5
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 118752.758
      sim_grid_pos_y: 3102485
    }
    terrain_level_point {
      sim_grid_pos_x: 118828.172
      sim_grid_pos_y: 3103120.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118917.398
      sim_grid_pos_y: 3103113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 118939.492
      sim_grid_pos_y: 3103329.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118880.234
      sim_grid_pos_y: 3103337.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118890.117
      sim_grid_pos_y: 3103550.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117200.461
      sim_grid_pos_y: 3103796.5
    }
    terrain_level_point {
      sim_grid_pos_x: 117076.805
      sim_grid_pos_y: 3103178
    }
    terrain_level_point {
      sim_grid_pos_x: 116986.734
      sim_grid_pos_y: 3102674
    }
    terrain_level_point {
      sim_grid_pos_x: 116764
      sim_grid_pos_y: 3102878.25
    }
    terrain_level_point {
      sim_grid_pos_x: 116975.477
      sim_grid_pos_y: 3104067.5
    }
    terrain_level_point {
      sim_grid_pos_x: 119210.227
      sim_grid_pos_y: 3103780.5
    }
    terrain_level_point {
      sim_grid_pos_x: 119746.094
      sim_grid_pos_y: 3102922.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 118750.133
      sim_grid_pos_y: 3102461.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118730.992
      sim_grid_pos_y: 3102475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118810.117
      sim_grid_pos_y: 3103142.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118899.023
      sim_grid_pos_y: 3103135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 118917.062
      sim_grid_pos_y: 3103311.75
    }
    terrain_level_point {
      sim_grid_pos_x: 118858.883
      sim_grid_pos_y: 3103319.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118868.758
      sim_grid_pos_y: 3103532.75
    }
    terrain_level_point {
      sim_grid_pos_x: 117216.758
      sim_grid_pos_y: 3103773.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117096.992
      sim_grid_pos_y: 3103174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117004.789
      sim_grid_pos_y: 3102658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 116981.82
      sim_grid_pos_y: 3102650.75
    }
    terrain_level_point {
      sim_grid_pos_x: 116741.836
      sim_grid_pos_y: 3102870.75
    }
    terrain_level_point {
      sim_grid_pos_x: 116958.711
      sim_grid_pos_y: 3104090.25
    }
    terrain_level_point {
      sim_grid_pos_x: 119222.469
      sim_grid_pos_y: 3103799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 119776.031
      sim_grid_pos_y: 3102913.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 118747.5
      sim_grid_pos_y: 3102438
    }
    terrain_level_point {
      sim_grid_pos_x: 118709.227
      sim_grid_pos_y: 3102466.25
    }
    terrain_level_point {
      sim_grid_pos_x: 118792.07
      sim_grid_pos_y: 3103164
    }
    terrain_level_point {
      sim_grid_pos_x: 118880.648
      sim_grid_pos_y: 3103157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118894.633
      sim_grid_pos_y: 3103294
    }
    terrain_level_point {
      sim_grid_pos_x: 118837.523
      sim_grid_pos_y: 3103301.5
    }
    terrain_level_point {
      sim_grid_pos_x: 118847.406
      sim_grid_pos_y: 3103515
    }
    terrain_level_point {
      sim_grid_pos_x: 117233.047
      sim_grid_pos_y: 3103750.25
    }
    terrain_level_point {
      sim_grid_pos_x: 117117.148
      sim_grid_pos_y: 3103170.5
    }
    terrain_level_point {
      sim_grid_pos_x: 117022.836
      sim_grid_pos_y: 3102643
    }
    terrain_level_point {
      sim_grid_pos_x: 116976.898
      sim_grid_pos_y: 3102627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 116719.68
      sim_grid_pos_y: 3102863.25
    }
    terrain_level_point {
      sim_grid_pos_x: 116941.953
      sim_grid_pos_y: 3104113
    }
    terrain_level_point {
      sim_grid_pos_x: 119234.711
      sim_grid_pos_y: 3103818.75
    }
    terrain_level_point {
      sim_grid_pos_x: 119805.961
      sim_grid_pos_y: 3102904
    }
  }
}
