terrain_level_data {
  terrain_level: 1660
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1568199.5
      sim_grid_pos_y: 989213.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1568309.75
      sim_grid_pos_y: 989381.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1568488.38
      sim_grid_pos_y: 989385.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1568588.5
      sim_grid_pos_y: 989223.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1568486.75
      sim_grid_pos_y: 989069.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1568337.62
      sim_grid_pos_y: 989068.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1568294.12
      sim_grid_pos_y: 988965.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1568069.25
      sim_grid_pos_y: 989201.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1568253.5
      sim_grid_pos_y: 989483.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1568544.75
      sim_grid_pos_y: 989489.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1568710.25
      sim_grid_pos_y: 989221.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1568542.25
      sim_grid_pos_y: 988967.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1568250.75
      sim_grid_pos_y: 988862.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1567939
      sim_grid_pos_y: 989189.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1568197.25
      sim_grid_pos_y: 989584.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1568601.25
      sim_grid_pos_y: 989593.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1568831.88
      sim_grid_pos_y: 989219.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1568597.75
      sim_grid_pos_y: 988865.938
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1568207.25
      sim_grid_pos_y: 988759.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1567808.75
      sim_grid_pos_y: 989177.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1568141
      sim_grid_pos_y: 989685.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1568657.62
      sim_grid_pos_y: 989696.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1568953.62
      sim_grid_pos_y: 989217.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1568653.25
      sim_grid_pos_y: 988764
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1568163.75
      sim_grid_pos_y: 988656.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1567678.5
      sim_grid_pos_y: 989165.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1568084.75
      sim_grid_pos_y: 989787
    }
    terrain_level_point {
      sim_grid_pos_x: 1568714
      sim_grid_pos_y: 989800.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1569075.25
      sim_grid_pos_y: 989216
    }
    terrain_level_point {
      sim_grid_pos_x: 1568708.62
      sim_grid_pos_y: 988662.062
    }
  }
}
