terrain_level_data {
  terrain_level: 1520
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1295439.25
      sim_grid_pos_y: 132443.781
    }
    terrain_level_point {
      sim_grid_pos_x: 1295563.62
      sim_grid_pos_y: 132582.469
    }
    terrain_level_point {
      sim_grid_pos_x: 1295770.88
      sim_grid_pos_y: 132655.016
    }
    terrain_level_point {
      sim_grid_pos_x: 1296001.25
      sim_grid_pos_y: 132664.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1296061.88
      sim_grid_pos_y: 132598.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1296155.5
      sim_grid_pos_y: 132471.266
    }
    terrain_level_point {
      sim_grid_pos_x: 1296082.25
      sim_grid_pos_y: 132356.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1295868
      sim_grid_pos_y: 132286.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1295867.5
      sim_grid_pos_y: 132253.484
    }
    terrain_level_point {
      sim_grid_pos_x: 1295386.12
      sim_grid_pos_y: 132430.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1295546
      sim_grid_pos_y: 132608.891
    }
    terrain_level_point {
      sim_grid_pos_x: 1295765.12
      sim_grid_pos_y: 132685.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1296014.25
      sim_grid_pos_y: 132695.672
    }
    terrain_level_point {
      sim_grid_pos_x: 1296085.62
      sim_grid_pos_y: 132617.703
    }
    terrain_level_point {
      sim_grid_pos_x: 1296192.88
      sim_grid_pos_y: 132472.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1296102.25
      sim_grid_pos_y: 132331.031
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1295866.88
      sim_grid_pos_y: 132220.906
    }
    terrain_level_point {
      sim_grid_pos_x: 1295333
      sim_grid_pos_y: 132417.344
    }
    terrain_level_point {
      sim_grid_pos_x: 1295528.38
      sim_grid_pos_y: 132635.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1295759.25
      sim_grid_pos_y: 132716.109
    }
    terrain_level_point {
      sim_grid_pos_x: 1296027.25
      sim_grid_pos_y: 132726.984
    }
    terrain_level_point {
      sim_grid_pos_x: 1296109.38
      sim_grid_pos_y: 132637.281
    }
    terrain_level_point {
      sim_grid_pos_x: 1296230.12
      sim_grid_pos_y: 132473.734
    }
    terrain_level_point {
      sim_grid_pos_x: 1296122.25
      sim_grid_pos_y: 132305.25
    }
  }
}
terrain_level_data {
  terrain_level: 1470
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1296092.25
      sim_grid_pos_y: 131893.141
    }
    terrain_level_point {
      sim_grid_pos_x: 1295824.5
      sim_grid_pos_y: 132086.203
    }
    terrain_level_point {
      sim_grid_pos_x: 1295947.75
      sim_grid_pos_y: 132299.656
    }
    terrain_level_point {
      sim_grid_pos_x: 1296117.25
      sim_grid_pos_y: 132190.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1296196.75
      sim_grid_pos_y: 132009.453
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1296096.62
      sim_grid_pos_y: 131852.031
    }
    terrain_level_point {
      sim_grid_pos_x: 1295784
      sim_grid_pos_y: 132077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295937.25
      sim_grid_pos_y: 132343.031
    }
    terrain_level_point {
      sim_grid_pos_x: 1296141.62
      sim_grid_pos_y: 132211.016
    }
    terrain_level_point {
      sim_grid_pos_x: 1296232.88
      sim_grid_pos_y: 132003.672
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1296101
      sim_grid_pos_y: 131810.922
    }
    terrain_level_point {
      sim_grid_pos_x: 1295743.38
      sim_grid_pos_y: 132068.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1295926.75
      sim_grid_pos_y: 132386.422
    }
    terrain_level_point {
      sim_grid_pos_x: 1296166.12
      sim_grid_pos_y: 132231.844
    }
    terrain_level_point {
      sim_grid_pos_x: 1296269
      sim_grid_pos_y: 131997.891
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1296105.5
      sim_grid_pos_y: 131769.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1295702.88
      sim_grid_pos_y: 132060.109
    }
    terrain_level_point {
      sim_grid_pos_x: 1295916.25
      sim_grid_pos_y: 132429.797
    }
    terrain_level_point {
      sim_grid_pos_x: 1296190.5
      sim_grid_pos_y: 132252.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1296305.12
      sim_grid_pos_y: 131992.094
    }
  }
}
