terrain_level_data {
  terrain_level: 690
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1537224.62
      sim_grid_pos_y: 1881847
    }
    terrain_level_point {
      sim_grid_pos_x: 1537011.38
      sim_grid_pos_y: 1881765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1536432.75
      sim_grid_pos_y: 1881291
    }
    terrain_level_point {
      sim_grid_pos_x: 1536321.25
      sim_grid_pos_y: 1881183
    }
    terrain_level_point {
      sim_grid_pos_x: 1536248.62
      sim_grid_pos_y: 1881066.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536187
      sim_grid_pos_y: 1880913.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536163.5
      sim_grid_pos_y: 1880801.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536232
      sim_grid_pos_y: 1880353.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1536249.75
      sim_grid_pos_y: 1879974.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536554.25
      sim_grid_pos_y: 1880353.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1536659.75
      sim_grid_pos_y: 1880463
    }
    terrain_level_point {
      sim_grid_pos_x: 1536830.5
      sim_grid_pos_y: 1880612.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1536997.12
      sim_grid_pos_y: 1880707.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1537161.62
      sim_grid_pos_y: 1880775.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1537358
      sim_grid_pos_y: 1880795.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1538524.38
      sim_grid_pos_y: 1880864.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1538576.12
      sim_grid_pos_y: 1881083.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1538583.12
      sim_grid_pos_y: 1881248.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1538530.75
      sim_grid_pos_y: 1881405.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1538408.75
      sim_grid_pos_y: 1881534.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1538103.25
      sim_grid_pos_y: 1881723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1537739
      sim_grid_pos_y: 1881908.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1537564.12
      sim_grid_pos_y: 1881964.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537398.62
      sim_grid_pos_y: 1881921.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1536577.38
      sim_grid_pos_y: 1880333
    }
    terrain_level_point {
      sim_grid_pos_x: 1536681
      sim_grid_pos_y: 1880440.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1536848.38
      sim_grid_pos_y: 1880587.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1537010.62
      sim_grid_pos_y: 1880679.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537169.25
      sim_grid_pos_y: 1880745.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1537360.62
      sim_grid_pos_y: 1880764.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1538549
      sim_grid_pos_y: 1880835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1538606.75
      sim_grid_pos_y: 1881079.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538614.12
      sim_grid_pos_y: 1881253
    }
    terrain_level_point {
      sim_grid_pos_x: 1538557.75
      sim_grid_pos_y: 1881421.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538428.38
      sim_grid_pos_y: 1881558.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1538118.38
      sim_grid_pos_y: 1881750.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1537750.75
      sim_grid_pos_y: 1881936.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1537565
      sim_grid_pos_y: 1881996.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537388.62
      sim_grid_pos_y: 1881950.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1537213
      sim_grid_pos_y: 1881875.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536995.75
      sim_grid_pos_y: 1881792.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1536412.25
      sim_grid_pos_y: 1881314
    }
    terrain_level_point {
      sim_grid_pos_x: 1536297.12
      sim_grid_pos_y: 1881202.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536221.12
      sim_grid_pos_y: 1881080.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536157.5
      sim_grid_pos_y: 1880922.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536132.25
      sim_grid_pos_y: 1880802.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1536201.38
      sim_grid_pos_y: 1880350.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.53622e+06
      sim_grid_pos_y: 1879951.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536260.38
      sim_grid_pos_y: 1879938.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1536600.5
      sim_grid_pos_y: 1880312.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1536702.25
      sim_grid_pos_y: 1880418.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536866.38
      sim_grid_pos_y: 1880562
    }
    terrain_level_point {
      sim_grid_pos_x: 1537024.12
      sim_grid_pos_y: 1880652.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1537176.75
      sim_grid_pos_y: 1880715.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1537363
      sim_grid_pos_y: 1880734.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1538573.75
      sim_grid_pos_y: 1880805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1538637.38
      sim_grid_pos_y: 1881075.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1538645.12
      sim_grid_pos_y: 1881257.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538584.75
      sim_grid_pos_y: 1881437.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1538448
      sim_grid_pos_y: 1881582.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538133.38
      sim_grid_pos_y: 1881776.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537762.5
      sim_grid_pos_y: 1881965.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1537566
      sim_grid_pos_y: 1882029
    }
    terrain_level_point {
      sim_grid_pos_x: 1537378.62
      sim_grid_pos_y: 1.88198e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1537201.38
      sim_grid_pos_y: 1881904
    }
    terrain_level_point {
      sim_grid_pos_x: 1536980.12
      sim_grid_pos_y: 1881819.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536391.75
      sim_grid_pos_y: 1881337
    }
    terrain_level_point {
      sim_grid_pos_x: 1536273
      sim_grid_pos_y: 1881221.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1536193.62
      sim_grid_pos_y: 1881094.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536127.88
      sim_grid_pos_y: 1880931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536101
      sim_grid_pos_y: 1880803.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1536170.75
      sim_grid_pos_y: 1880347.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536190.25
      sim_grid_pos_y: 1879928.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1536271.12
      sim_grid_pos_y: 1879902.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1536623.62
      sim_grid_pos_y: 1880292.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1536723.5
      sim_grid_pos_y: 1880396.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536884.38
      sim_grid_pos_y: 1880536.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537037.75
      sim_grid_pos_y: 1880624.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1537184.38
      sim_grid_pos_y: 1880685
    }
    terrain_level_point {
      sim_grid_pos_x: 1537365.38
      sim_grid_pos_y: 1880703.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1538598.38
      sim_grid_pos_y: 1880776.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1538668
      sim_grid_pos_y: 1881071
    }
    terrain_level_point {
      sim_grid_pos_x: 1538676
      sim_grid_pos_y: 1881261.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1538611.75
      sim_grid_pos_y: 1881453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1538467.5
      sim_grid_pos_y: 1881606.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538148.5
      sim_grid_pos_y: 1881803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1537774.38
      sim_grid_pos_y: 1881993.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1537566.88
      sim_grid_pos_y: 1882061
    }
    terrain_level_point {
      sim_grid_pos_x: 1537368.62
      sim_grid_pos_y: 1882009.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.53719e+06
      sim_grid_pos_y: 1881932.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536964.38
      sim_grid_pos_y: 1881846.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536371.25
      sim_grid_pos_y: 1881359.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1536248.88
      sim_grid_pos_y: 1881241.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1536166
      sim_grid_pos_y: 1881108.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536098.38
      sim_grid_pos_y: 1880940.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536069.75
      sim_grid_pos_y: 1880804.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.53614e+06
      sim_grid_pos_y: 1880344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536160.5
      sim_grid_pos_y: 1879906.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1536281.75
      sim_grid_pos_y: 1879866.62
    }
  }
}
