terrain_level_data {
  terrain_level: 40
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 347980
      sim_grid_pos_y: 1741722.25
    }
    terrain_level_point {
      sim_grid_pos_x: 349848.781
      sim_grid_pos_y: 1741665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 349960
      sim_grid_pos_y: 1741781
    }
    terrain_level_point {
      sim_grid_pos_x: 351756.969
      sim_grid_pos_y: 1741797.5
    }
    terrain_level_point {
      sim_grid_pos_x: 351765.25
      sim_grid_pos_y: 1741052.75
    }
    terrain_level_point {
      sim_grid_pos_x: 351878.188
      sim_grid_pos_y: 1740688.5
    }
    terrain_level_point {
      sim_grid_pos_x: 352523.781
      sim_grid_pos_y: 1740563.38
    }
    terrain_level_point {
      sim_grid_pos_x: 353228.156
      sim_grid_pos_y: 1740799
    }
    terrain_level_point {
      sim_grid_pos_x: 354534.594
      sim_grid_pos_y: 1745176.38
    }
    terrain_level_point {
      sim_grid_pos_x: 353367.531
      sim_grid_pos_y: 1744656.38
    }
    terrain_level_point {
      sim_grid_pos_x: 352841.75
      sim_grid_pos_y: 1744691.12
    }
    terrain_level_point {
      sim_grid_pos_x: 352200.938
      sim_grid_pos_y: 1744553.38
    }
    terrain_level_point {
      sim_grid_pos_x: 352346.094
      sim_grid_pos_y: 1744298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 352171.375
      sim_grid_pos_y: 1744135.38
    }
    terrain_level_point {
      sim_grid_pos_x: 351864.719
      sim_grid_pos_y: 1744140.12
    }
    terrain_level_point {
      sim_grid_pos_x: 351275.344
      sim_grid_pos_y: 1743753.38
    }
    terrain_level_point {
      sim_grid_pos_x: 351255.344
      sim_grid_pos_y: 1743199.12
    }
    terrain_level_point {
      sim_grid_pos_x: 350265.938
      sim_grid_pos_y: 1743166.38
    }
    terrain_level_point {
      sim_grid_pos_x: 350262.719
      sim_grid_pos_y: 1742814.62
    }
    terrain_level_point {
      sim_grid_pos_x: 349227.219
      sim_grid_pos_y: 1742842.88
    }
    terrain_level_point {
      sim_grid_pos_x: 349279.875
      sim_grid_pos_y: 1743109.88
    }
    terrain_level_point {
      sim_grid_pos_x: 349124.062
      sim_grid_pos_y: 1743319.12
    }
    terrain_level_point {
      sim_grid_pos_x: 348836.5
      sim_grid_pos_y: 1743445.75
    }
    terrain_level_point {
      sim_grid_pos_x: 348117.281
      sim_grid_pos_y: 1743479.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 353253.062
      sim_grid_pos_y: 1740774.88
    }
    terrain_level_point {
      sim_grid_pos_x: 354569.719
      sim_grid_pos_y: 1745186.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354540.094
      sim_grid_pos_y: 1745212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353361.969
      sim_grid_pos_y: 1744687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 352839.5
      sim_grid_pos_y: 1744722.12
    }
    terrain_level_point {
      sim_grid_pos_x: 352153.469
      sim_grid_pos_y: 1744574.62
    }
    terrain_level_point {
      sim_grid_pos_x: 352307.312
      sim_grid_pos_y: 1744304.12
    }
    terrain_level_point {
      sim_grid_pos_x: 352159.438
      sim_grid_pos_y: 1744166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 351855.75
      sim_grid_pos_y: 1744171
    }
    terrain_level_point {
      sim_grid_pos_x: 351245.156
      sim_grid_pos_y: 1743770.38
    }
    terrain_level_point {
      sim_grid_pos_x: 351225.656
      sim_grid_pos_y: 1743229
    }
    terrain_level_point {
      sim_grid_pos_x: 350235.469
      sim_grid_pos_y: 1743196.12
    }
    terrain_level_point {
      sim_grid_pos_x: 350232.25
      sim_grid_pos_y: 1742846.25
    }
    terrain_level_point {
      sim_grid_pos_x: 349264.469
      sim_grid_pos_y: 1742872.62
    }
    terrain_level_point {
      sim_grid_pos_x: 349312.688
      sim_grid_pos_y: 1743117.25
    }
    terrain_level_point {
      sim_grid_pos_x: 349143.875
      sim_grid_pos_y: 1743344
    }
    terrain_level_point {
      sim_grid_pos_x: 348843.688
      sim_grid_pos_y: 1743476.12
    }
    terrain_level_point {
      sim_grid_pos_x: 348088.938
      sim_grid_pos_y: 1743511.62
    }
    terrain_level_point {
      sim_grid_pos_x: 347946.812
      sim_grid_pos_y: 1741692.5
    }
    terrain_level_point {
      sim_grid_pos_x: 349861.5
      sim_grid_pos_y: 1741634.12
    }
    terrain_level_point {
      sim_grid_pos_x: 349973.219
      sim_grid_pos_y: 1741750.38
    }
    terrain_level_point {
      sim_grid_pos_x: 351726.562
      sim_grid_pos_y: 1741766.5
    }
    terrain_level_point {
      sim_grid_pos_x: 351734.531
      sim_grid_pos_y: 1741047.88
    }
    terrain_level_point {
      sim_grid_pos_x: 351854.25
      sim_grid_pos_y: 1740661.75
    }
    terrain_level_point {
      sim_grid_pos_x: 352525.875
      sim_grid_pos_y: 1740531.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 353277.969
      sim_grid_pos_y: 1740750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354604.812
      sim_grid_pos_y: 1745196.62
    }
    terrain_level_point {
      sim_grid_pos_x: 354545.562
      sim_grid_pos_y: 1745248.62
    }
    terrain_level_point {
      sim_grid_pos_x: 353356.375
      sim_grid_pos_y: 1744718.75
    }
    terrain_level_point {
      sim_grid_pos_x: 352837.219
      sim_grid_pos_y: 1744753
    }
    terrain_level_point {
      sim_grid_pos_x: 352105.969
      sim_grid_pos_y: 1744595.88
    }
    terrain_level_point {
      sim_grid_pos_x: 352268.562
      sim_grid_pos_y: 1744310.12
    }
    terrain_level_point {
      sim_grid_pos_x: 352147.531
      sim_grid_pos_y: 1744197.25
    }
    terrain_level_point {
      sim_grid_pos_x: 351846.781
      sim_grid_pos_y: 1744201.88
    }
    terrain_level_point {
      sim_grid_pos_x: 351215
      sim_grid_pos_y: 1743787.38
    }
    terrain_level_point {
      sim_grid_pos_x: 351195.938
      sim_grid_pos_y: 1743258.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350204.969
      sim_grid_pos_y: 1743225.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350201.781
      sim_grid_pos_y: 1742877.88
    }
    terrain_level_point {
      sim_grid_pos_x: 349301.688
      sim_grid_pos_y: 1742902.38
    }
    terrain_level_point {
      sim_grid_pos_x: 349345.5
      sim_grid_pos_y: 1743124.75
    }
    terrain_level_point {
      sim_grid_pos_x: 349163.688
      sim_grid_pos_y: 1743368.88
    }
    terrain_level_point {
      sim_grid_pos_x: 348850.812
      sim_grid_pos_y: 1743506.62
    }
    terrain_level_point {
      sim_grid_pos_x: 348060.594
      sim_grid_pos_y: 1743543.75
    }
    terrain_level_point {
      sim_grid_pos_x: 347913.656
      sim_grid_pos_y: 1741662.75
    }
    terrain_level_point {
      sim_grid_pos_x: 349874.219
      sim_grid_pos_y: 1741603
    }
    terrain_level_point {
      sim_grid_pos_x: 349986.438
      sim_grid_pos_y: 1741719.75
    }
    terrain_level_point {
      sim_grid_pos_x: 351696.156
      sim_grid_pos_y: 1741735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 351703.812
      sim_grid_pos_y: 1741043
    }
    terrain_level_point {
      sim_grid_pos_x: 351830.312
      sim_grid_pos_y: 1740635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 352527.969
      sim_grid_pos_y: 1740499.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 353302.875
      sim_grid_pos_y: 1740726.62
    }
    terrain_level_point {
      sim_grid_pos_x: 354639.938
      sim_grid_pos_y: 1745206.62
    }
    terrain_level_point {
      sim_grid_pos_x: 354551.062
      sim_grid_pos_y: 1745284.75
    }
    terrain_level_point {
      sim_grid_pos_x: 353350.812
      sim_grid_pos_y: 1.74475e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 352834.969
      sim_grid_pos_y: 1744784
    }
    terrain_level_point {
      sim_grid_pos_x: 352058.5
      sim_grid_pos_y: 1744617.12
    }
    terrain_level_point {
      sim_grid_pos_x: 352229.812
      sim_grid_pos_y: 1744316
    }
    terrain_level_point {
      sim_grid_pos_x: 352135.625
      sim_grid_pos_y: 1744228.12
    }
    terrain_level_point {
      sim_grid_pos_x: 351837.812
      sim_grid_pos_y: 1744232.88
    }
    terrain_level_point {
      sim_grid_pos_x: 351184.812
      sim_grid_pos_y: 1743804.25
    }
    terrain_level_point {
      sim_grid_pos_x: 351166.25
      sim_grid_pos_y: 1743288.5
    }
    terrain_level_point {
      sim_grid_pos_x: 350174.5
      sim_grid_pos_y: 1743255.62
    }
    terrain_level_point {
      sim_grid_pos_x: 350171.312
      sim_grid_pos_y: 1742909.5
    }
    terrain_level_point {
      sim_grid_pos_x: 349338.875
      sim_grid_pos_y: 1742932.12
    }
    terrain_level_point {
      sim_grid_pos_x: 349378.312
      sim_grid_pos_y: 1743132.12
    }
    terrain_level_point {
      sim_grid_pos_x: 349183.531
      sim_grid_pos_y: 1743393.75
    }
    terrain_level_point {
      sim_grid_pos_x: 348858
      sim_grid_pos_y: 1743537.12
    }
    terrain_level_point {
      sim_grid_pos_x: 348032.25
      sim_grid_pos_y: 1743575.88
    }
    terrain_level_point {
      sim_grid_pos_x: 347880.469
      sim_grid_pos_y: 1741633
    }
    terrain_level_point {
      sim_grid_pos_x: 349886.906
      sim_grid_pos_y: 1741571.88
    }
    terrain_level_point {
      sim_grid_pos_x: 349999.656
      sim_grid_pos_y: 1741689.12
    }
    terrain_level_point {
      sim_grid_pos_x: 351665.719
      sim_grid_pos_y: 1741704.38
    }
    terrain_level_point {
      sim_grid_pos_x: 351673.125
      sim_grid_pos_y: 1741038.25
    }
    terrain_level_point {
      sim_grid_pos_x: 351806.406
      sim_grid_pos_y: 1740608.38
    }
    terrain_level_point {
      sim_grid_pos_x: 352530.031
      sim_grid_pos_y: 1740468.12
    }
  }
}
terrain_level_data {
  terrain_level: 150
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 349694.344
      sim_grid_pos_y: 1743434.12
    }
    terrain_level_point {
      sim_grid_pos_x: 349855.188
      sim_grid_pos_y: 1744551.75
    }
    terrain_level_point {
      sim_grid_pos_x: 349623.438
      sim_grid_pos_y: 1745151.38
    }
    terrain_level_point {
      sim_grid_pos_x: 349049.281
      sim_grid_pos_y: 1745287
    }
    terrain_level_point {
      sim_grid_pos_x: 348347.562
      sim_grid_pos_y: 1744440.38
    }
    terrain_level_point {
      sim_grid_pos_x: 348163.094
      sim_grid_pos_y: 1743751.62
    }
    terrain_level_point {
      sim_grid_pos_x: 348653.125
      sim_grid_pos_y: 1743647.12
    }
    terrain_level_point {
      sim_grid_pos_x: 349007.656
      sim_grid_pos_y: 1743764.88
    }
    terrain_level_point {
      sim_grid_pos_x: 349131.438
      sim_grid_pos_y: 1743385.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 349721.281
      sim_grid_pos_y: 1743405.62
    }
    terrain_level_point {
      sim_grid_pos_x: 349886.781
      sim_grid_pos_y: 1744555.38
    }
    terrain_level_point {
      sim_grid_pos_x: 349646.281
      sim_grid_pos_y: 1745177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 349037.781
      sim_grid_pos_y: 1745321.38
    }
    terrain_level_point {
      sim_grid_pos_x: 348319.594
      sim_grid_pos_y: 1744454.88
    }
    terrain_level_point {
      sim_grid_pos_x: 348125
      sim_grid_pos_y: 1743728.25
    }
    terrain_level_point {
      sim_grid_pos_x: 348654.906
      sim_grid_pos_y: 1743615.38
    }
    terrain_level_point {
      sim_grid_pos_x: 348988
      sim_grid_pos_y: 1743726
    }
    terrain_level_point {
      sim_grid_pos_x: 349109.75
      sim_grid_pos_y: 1743353.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 349748.25
      sim_grid_pos_y: 1743377
    }
    terrain_level_point {
      sim_grid_pos_x: 349918.375
      sim_grid_pos_y: 1744558.88
    }
    terrain_level_point {
      sim_grid_pos_x: 349669.125
      sim_grid_pos_y: 1745203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 349026.281
      sim_grid_pos_y: 1745355.62
    }
    terrain_level_point {
      sim_grid_pos_x: 348291.625
      sim_grid_pos_y: 1744469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 348086.906
      sim_grid_pos_y: 1743705
    }
    terrain_level_point {
      sim_grid_pos_x: 348656.656
      sim_grid_pos_y: 1743583.5
    }
    terrain_level_point {
      sim_grid_pos_x: 348968.375
      sim_grid_pos_y: 1743687
    }
    terrain_level_point {
      sim_grid_pos_x: 349088.094
      sim_grid_pos_y: 1743320.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 349775.219
      sim_grid_pos_y: 1743348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 349949.969
      sim_grid_pos_y: 1744562.5
    }
    terrain_level_point {
      sim_grid_pos_x: 349691.969
      sim_grid_pos_y: 1.74523e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 349014.781
      sim_grid_pos_y: 1.74539e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 348263.656
      sim_grid_pos_y: 1744483.75
    }
    terrain_level_point {
      sim_grid_pos_x: 348048.812
      sim_grid_pos_y: 1743681.62
    }
    terrain_level_point {
      sim_grid_pos_x: 348658.406
      sim_grid_pos_y: 1743551.75
    }
    terrain_level_point {
      sim_grid_pos_x: 348948.719
      sim_grid_pos_y: 1743648.12
    }
    terrain_level_point {
      sim_grid_pos_x: 349066.406
      sim_grid_pos_y: 1743287.62
    }
  }
}
