terrain_level_data {
  terrain_level: 145
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1675569.88
      sim_grid_pos_y: 960894.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1675422.25
      sim_grid_pos_y: 961466.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1675372
      sim_grid_pos_y: 961762.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1.6754e+06
      sim_grid_pos_y: 961977.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1675731.88
      sim_grid_pos_y: 962008.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1676169.88
      sim_grid_pos_y: 961898
    }
    terrain_level_point {
      sim_grid_pos_x: 1676474.38
      sim_grid_pos_y: 961662.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1676664.5
      sim_grid_pos_y: 961471.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1676774.38
      sim_grid_pos_y: 961124.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1676755.38
      sim_grid_pos_y: 960967.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1676704.88
      sim_grid_pos_y: 960798.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1676546.38
      sim_grid_pos_y: 960783.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1.6763e+06
      sim_grid_pos_y: 960765.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1676101
      sim_grid_pos_y: 960773.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1676301
      sim_grid_pos_y: 960704.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1676092.88
      sim_grid_pos_y: 960711.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1675519.62
      sim_grid_pos_y: 960843.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1675362
      sim_grid_pos_y: 961453.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1675309.75
      sim_grid_pos_y: 961761.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1675345.25
      sim_grid_pos_y: 962034.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1675736.75
      sim_grid_pos_y: 962070.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1676197.38
      sim_grid_pos_y: 961954.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1676515.12
      sim_grid_pos_y: 961708.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1676718.62
      sim_grid_pos_y: 961504.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1676837.12
      sim_grid_pos_y: 961130.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1676815.88
      sim_grid_pos_y: 960954.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1676751.88
      sim_grid_pos_y: 960741.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1676551.5
      sim_grid_pos_y: 960722.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1676302.12
      sim_grid_pos_y: 960642.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1676084.88
      sim_grid_pos_y: 960650.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1675469.5
      sim_grid_pos_y: 960791.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1675301.75
      sim_grid_pos_y: 961440.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1675247.62
      sim_grid_pos_y: 961760.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1675290.62
      sim_grid_pos_y: 962091.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1675741.5
      sim_grid_pos_y: 962132.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1676224.88
      sim_grid_pos_y: 962011
    }
    terrain_level_point {
      sim_grid_pos_x: 1676555.88
      sim_grid_pos_y: 961754.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1676772.75
      sim_grid_pos_y: 961537.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1676899.75
      sim_grid_pos_y: 961136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1676876.25
      sim_grid_pos_y: 960942.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1676799
      sim_grid_pos_y: 960683.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1676556.5
      sim_grid_pos_y: 960660.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1676303.12
      sim_grid_pos_y: 960581.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1676076.75
      sim_grid_pos_y: 960589.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1675419.25
      sim_grid_pos_y: 960739.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1675241.5
      sim_grid_pos_y: 961427.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1675185.38
      sim_grid_pos_y: 961759
    }
    terrain_level_point {
      sim_grid_pos_x: 1675236
      sim_grid_pos_y: 962147.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1675746.38
      sim_grid_pos_y: 962195
    }
    terrain_level_point {
      sim_grid_pos_x: 1676252.38
      sim_grid_pos_y: 962067.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1676596.62
      sim_grid_pos_y: 961800.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1676826.88
      sim_grid_pos_y: 961570.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1676962.38
      sim_grid_pos_y: 961142.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1676936.75
      sim_grid_pos_y: 960929.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1676846
      sim_grid_pos_y: 960626.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1676561.62
      sim_grid_pos_y: 960599.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1676304.12
      sim_grid_pos_y: 960519.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1676068.62
      sim_grid_pos_y: 960528.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1675369.12
      sim_grid_pos_y: 960688.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1675181.38
      sim_grid_pos_y: 961414.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1675123.12
      sim_grid_pos_y: 961757.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1675181.38
      sim_grid_pos_y: 962204.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1675751.12
      sim_grid_pos_y: 962257.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1676279.88
      sim_grid_pos_y: 962124
    }
    terrain_level_point {
      sim_grid_pos_x: 1676637.38
      sim_grid_pos_y: 961847.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1676881
      sim_grid_pos_y: 961603
    }
    terrain_level_point {
      sim_grid_pos_x: 1677025.12
      sim_grid_pos_y: 961147.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1676997.12
      sim_grid_pos_y: 960916.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1676893.12
      sim_grid_pos_y: 960569
    }
    terrain_level_point {
      sim_grid_pos_x: 1676566.75
      sim_grid_pos_y: 960538.125
    }
  }
}
