terrain_level_data {
  terrain_level: 205
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2198921.25
      sim_grid_pos_y: 1113678.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199037.75
      sim_grid_pos_y: 1113845.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2199246
      sim_grid_pos_y: 1113846.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2199306.5
      sim_grid_pos_y: 1113654.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199259
      sim_grid_pos_y: 1113492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199081
      sim_grid_pos_y: 1113526.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2199295
      sim_grid_pos_y: 1113433.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199056.5
      sim_grid_pos_y: 1113479.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2198854
      sim_grid_pos_y: 1113671.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199011
      sim_grid_pos_y: 1113897
    }
    terrain_level_point {
      sim_grid_pos_x: 2199283.5
      sim_grid_pos_y: 1113898.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.19936e+06
      sim_grid_pos_y: 1113655.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2199331.25
      sim_grid_pos_y: 1113374.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2199032.25
      sim_grid_pos_y: 1113431.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2198786.75
      sim_grid_pos_y: 1113665
    }
    terrain_level_point {
      sim_grid_pos_x: 2198984
      sim_grid_pos_y: 1113948.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199321
      sim_grid_pos_y: 1113949.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199413.75
      sim_grid_pos_y: 1113655.75
    }
  }
}
terrain_level_data {
  terrain_level: 225
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2199544
      sim_grid_pos_y: 1113528.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2199474
      sim_grid_pos_y: 1113651.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199539.5
      sim_grid_pos_y: 1.11379e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199711.75
      sim_grid_pos_y: 1113778.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199779.5
      sim_grid_pos_y: 1113682.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2199693.5
      sim_grid_pos_y: 1113517.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2199723.25
      sim_grid_pos_y: 1113464.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199513
      sim_grid_pos_y: 1113479.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199416.5
      sim_grid_pos_y: 1113649.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2199508
      sim_grid_pos_y: 1113843.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2199739.75
      sim_grid_pos_y: 1113828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199839.25
      sim_grid_pos_y: 1113686.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2199753.25
      sim_grid_pos_y: 1113410.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199482
      sim_grid_pos_y: 1113430.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199358.75
      sim_grid_pos_y: 1113647.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2199476.5
      sim_grid_pos_y: 1113896.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2199767.5
      sim_grid_pos_y: 1113877.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199899.25
      sim_grid_pos_y: 1113690.5
    }
  }
}
terrain_level_data {
  terrain_level: 120
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2197780.75
      sim_grid_pos_y: 1112408.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2198680.5
      sim_grid_pos_y: 1112617.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2198730.25
      sim_grid_pos_y: 1113926.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2198815.25
      sim_grid_pos_y: 1116180.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2198379.25
      sim_grid_pos_y: 1116729
    }
    terrain_level_point {
      sim_grid_pos_x: 2.19708e+06
      sim_grid_pos_y: 1118885.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2195895.5
      sim_grid_pos_y: 1119525.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.19548e+06
      sim_grid_pos_y: 1118960.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2196178.5
      sim_grid_pos_y: 1116533
    }
    terrain_level_point {
      sim_grid_pos_x: 2197366.75
      sim_grid_pos_y: 1112874
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2198730.25
      sim_grid_pos_y: 1112576.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2198781.5
      sim_grid_pos_y: 1113924.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2198781.5
      sim_grid_pos_y: 1113924.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2198867.25
      sim_grid_pos_y: 1116197.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2198421.5
      sim_grid_pos_y: 1116758.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2197116.75
      sim_grid_pos_y: 1118924.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2195880.5
      sim_grid_pos_y: 1119591.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2195423.75
      sim_grid_pos_y: 1118970.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2196129.5
      sim_grid_pos_y: 1116518
    }
    terrain_level_point {
      sim_grid_pos_x: 2197321.25
      sim_grid_pos_y: 1112848
    }
    terrain_level_point {
      sim_grid_pos_x: 2197762.75
      sim_grid_pos_y: 1112351.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2.19878e+06
      sim_grid_pos_y: 1112535.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2198832.75
      sim_grid_pos_y: 1113922.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2198832.75
      sim_grid_pos_y: 1113922.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2198919.25
      sim_grid_pos_y: 1116214.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2198463.5
      sim_grid_pos_y: 1116787.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2197153.25
      sim_grid_pos_y: 1118962.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2195865.75
      sim_grid_pos_y: 1119657.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2195367.5
      sim_grid_pos_y: 1118980.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2196080.5
      sim_grid_pos_y: 1116503
    }
    terrain_level_point {
      sim_grid_pos_x: 2197275.75
      sim_grid_pos_y: 1112821.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2197744.75
      sim_grid_pos_y: 1112294.88
    }
  }
}
