terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1139029.88
      sim_grid_pos_y: 1355151.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1137117.12
      sim_grid_pos_y: 1355140.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136186.38
      sim_grid_pos_y: 1355045
    }
    terrain_level_point {
      sim_grid_pos_x: 1135760.12
      sim_grid_pos_y: 1355160.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135352.5
      sim_grid_pos_y: 1355713.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135053.38
      sim_grid_pos_y: 1355755.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134480.12
      sim_grid_pos_y: 1356213.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134263
      sim_grid_pos_y: 1356307.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134048.75
      sim_grid_pos_y: 1356254.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133323.62
      sim_grid_pos_y: 1357444.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132798.62
      sim_grid_pos_y: 1358031.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132520.25
      sim_grid_pos_y: 1358041.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132042.12
      sim_grid_pos_y: 1357888.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1131474.25
      sim_grid_pos_y: 1356215.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1131562.88
      sim_grid_pos_y: 1354381.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1131216.75
      sim_grid_pos_y: 1348614
    }
    terrain_level_point {
      sim_grid_pos_x: 1131648
      sim_grid_pos_y: 1348500.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131898.5
      sim_grid_pos_y: 1348658
    }
    terrain_level_point {
      sim_grid_pos_x: 1132532
      sim_grid_pos_y: 1349341.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133237.5
      sim_grid_pos_y: 1347842.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133623
      sim_grid_pos_y: 1347391.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134762.5
      sim_grid_pos_y: 1347150.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135531.12
      sim_grid_pos_y: 1347218.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135797.75
      sim_grid_pos_y: 1347264
    }
    terrain_level_point {
      sim_grid_pos_x: 1135949
      sim_grid_pos_y: 1347431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136496.25
      sim_grid_pos_y: 1347763
    }
    terrain_level_point {
      sim_grid_pos_x: 1136816.38
      sim_grid_pos_y: 1347803
    }
    terrain_level_point {
      sim_grid_pos_x: 1137198
      sim_grid_pos_y: 1347716.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1137474.5
      sim_grid_pos_y: 1347316
    }
    terrain_level_point {
      sim_grid_pos_x: 1137977.62
      sim_grid_pos_y: 1347252.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1138394.62
      sim_grid_pos_y: 1350431.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1138858.88
      sim_grid_pos_y: 1352911.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1139075.25
      sim_grid_pos_y: 1354208.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1135535
      sim_grid_pos_y: 1347187.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135813.38
      sim_grid_pos_y: 1347235.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135968.88
      sim_grid_pos_y: 1347407.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136506.5
      sim_grid_pos_y: 1347733.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136814.75
      sim_grid_pos_y: 1347771.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1137179.5
      sim_grid_pos_y: 1347689.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1137457
      sim_grid_pos_y: 1347287.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1138004.12
      sim_grid_pos_y: 1347217.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1138425
      sim_grid_pos_y: 1350426.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1138889.12
      sim_grid_pos_y: 1352906.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1139106.12
      sim_grid_pos_y: 1354206.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1139059.12
      sim_grid_pos_y: 1355182.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1137115.5
      sim_grid_pos_y: 1355171.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136188.88
      sim_grid_pos_y: 1355076.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135778.5
      sim_grid_pos_y: 1355187.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135369.62
      sim_grid_pos_y: 1355742.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135066
      sim_grid_pos_y: 1355785.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134496
      sim_grid_pos_y: 1356240.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134265.75
      sim_grid_pos_y: 1356339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134063.25
      sim_grid_pos_y: 1356289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133348.5
      sim_grid_pos_y: 1357463.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132812.75
      sim_grid_pos_y: 1358061.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1132515.88
      sim_grid_pos_y: 1358072.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132018
      sim_grid_pos_y: 1357913
    }
    terrain_level_point {
      sim_grid_pos_x: 1131443.25
      sim_grid_pos_y: 1.35622e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1131532.12
      sim_grid_pos_y: 1354381.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131184.5
      sim_grid_pos_y: 1348590.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131653.12
      sim_grid_pos_y: 1348467
    }
    terrain_level_point {
      sim_grid_pos_x: 1131918.25
      sim_grid_pos_y: 1348634.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132523.62
      sim_grid_pos_y: 1349286.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133211.5
      sim_grid_pos_y: 1347825.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133606.38
      sim_grid_pos_y: 1347363.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134760.62
      sim_grid_pos_y: 1347119.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1135539
      sim_grid_pos_y: 1347157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135829.12
      sim_grid_pos_y: 1347206.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135988.62
      sim_grid_pos_y: 1347383.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136516.88
      sim_grid_pos_y: 1347703.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136813.25
      sim_grid_pos_y: 1347740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1137161
      sim_grid_pos_y: 1347662
    }
    terrain_level_point {
      sim_grid_pos_x: 1137439.38
      sim_grid_pos_y: 1347258.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1138030.75
      sim_grid_pos_y: 1347183.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1138455.38
      sim_grid_pos_y: 1350421.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1138919.5
      sim_grid_pos_y: 1352901
    }
    terrain_level_point {
      sim_grid_pos_x: 1139137
      sim_grid_pos_y: 1354204.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1139088.5
      sim_grid_pos_y: 1355213.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1137113.75
      sim_grid_pos_y: 1355201.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136191.5
      sim_grid_pos_y: 1355107.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135796.88
      sim_grid_pos_y: 1355214.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135386.75
      sim_grid_pos_y: 1355770.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135078.62
      sim_grid_pos_y: 1355814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134512
      sim_grid_pos_y: 1356266.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134268.38
      sim_grid_pos_y: 1356371.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134077.88
      sim_grid_pos_y: 1356325.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133373.25
      sim_grid_pos_y: 1357481.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1132827
      sim_grid_pos_y: 1358091.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1132511.62
      sim_grid_pos_y: 1358103.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1131993.88
      sim_grid_pos_y: 1357937.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1131412.25
      sim_grid_pos_y: 1356224.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1131501.25
      sim_grid_pos_y: 1354382
    }
    terrain_level_point {
      sim_grid_pos_x: 1131152.25
      sim_grid_pos_y: 1348567.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1131658.25
      sim_grid_pos_y: 1348433.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131938.12
      sim_grid_pos_y: 1348610.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1132515.12
      sim_grid_pos_y: 1349232.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133185.38
      sim_grid_pos_y: 1347809.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133589.75
      sim_grid_pos_y: 1347335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134758.75
      sim_grid_pos_y: 1347088.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1135542.88
      sim_grid_pos_y: 1347126.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135844.75
      sim_grid_pos_y: 1347178.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136008.5
      sim_grid_pos_y: 1347359.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136527.25
      sim_grid_pos_y: 1347674
    }
    terrain_level_point {
      sim_grid_pos_x: 1136811.75
      sim_grid_pos_y: 1347709.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1137142.5
      sim_grid_pos_y: 1347634.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1137421.88
      sim_grid_pos_y: 1347229.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1138057.25
      sim_grid_pos_y: 1347149
    }
    terrain_level_point {
      sim_grid_pos_x: 1138485.75
      sim_grid_pos_y: 1350416.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138949.75
      sim_grid_pos_y: 1352895.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1139167.88
      sim_grid_pos_y: 1354202.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1139117.75
      sim_grid_pos_y: 1355244.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1137112.12
      sim_grid_pos_y: 1355232.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136194
      sim_grid_pos_y: 1355138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135815.25
      sim_grid_pos_y: 1355241.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135403.75
      sim_grid_pos_y: 1355799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135091.25
      sim_grid_pos_y: 1355843.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134528
      sim_grid_pos_y: 1356293.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134271.12
      sim_grid_pos_y: 1356404.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134092.38
      sim_grid_pos_y: 1356360.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133398
      sim_grid_pos_y: 1.3575e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1132841.12
      sim_grid_pos_y: 1358122.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132507.38
      sim_grid_pos_y: 1358134.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1131969.75
      sim_grid_pos_y: 1357962.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131381.25
      sim_grid_pos_y: 1356228.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1131470.5
      sim_grid_pos_y: 1354382
    }
    terrain_level_point {
      sim_grid_pos_x: 1.13112e+06
      sim_grid_pos_y: 1348544.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131663.25
      sim_grid_pos_y: 1348400.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1131957.88
      sim_grid_pos_y: 1348586.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132506.75
      sim_grid_pos_y: 1349178.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133159.25
      sim_grid_pos_y: 1347792.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133573.12
      sim_grid_pos_y: 1347307.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134756.88
      sim_grid_pos_y: 1347057.75
    }
  }
}
