terrain_level_data {
  terrain_level: 158
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1495041.5
      sim_grid_pos_y: 1412259.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494709.25
      sim_grid_pos_y: 1411851.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494059.25
      sim_grid_pos_y: 1410878.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1493474.75
      sim_grid_pos_y: 1410183
    }
    terrain_level_point {
      sim_grid_pos_x: 1493211.62
      sim_grid_pos_y: 1410249.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1493370.88
      sim_grid_pos_y: 1410903
    }
    terrain_level_point {
      sim_grid_pos_x: 1494113.62
      sim_grid_pos_y: 1411824.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1494348.75
      sim_grid_pos_y: 1411877.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1494699
      sim_grid_pos_y: 1412292.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1494890.38
      sim_grid_pos_y: 1412378
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1493485.88
      sim_grid_pos_y: 1410148.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1493174.5
      sim_grid_pos_y: 1410227
    }
    terrain_level_point {
      sim_grid_pos_x: 1493342.62
      sim_grid_pos_y: 1410917
    }
    terrain_level_point {
      sim_grid_pos_x: 1494096.5
      sim_grid_pos_y: 1411852
    }
    terrain_level_point {
      sim_grid_pos_x: 1494332
      sim_grid_pos_y: 1411905.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.49468e+06
      sim_grid_pos_y: 1412317.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494894.75
      sim_grid_pos_y: 1412413.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1495085.12
      sim_grid_pos_y: 1412264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1494734.12
      sim_grid_pos_y: 1411833.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1494083.88
      sim_grid_pos_y: 1410860.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1493497
      sim_grid_pos_y: 1410114
    }
    terrain_level_point {
      sim_grid_pos_x: 1493137.38
      sim_grid_pos_y: 1410204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1493314.38
      sim_grid_pos_y: 1410931
    }
    terrain_level_point {
      sim_grid_pos_x: 1494079.25
      sim_grid_pos_y: 1411879.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1494315.12
      sim_grid_pos_y: 1411932.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494661.12
      sim_grid_pos_y: 1412343.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1494899.12
      sim_grid_pos_y: 1412449.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1495128.75
      sim_grid_pos_y: 1412269.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1494758.88
      sim_grid_pos_y: 1411815.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1494108.5
      sim_grid_pos_y: 1410841.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1493508.25
      sim_grid_pos_y: 1410079.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1493100.25
      sim_grid_pos_y: 1410182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1493286.12
      sim_grid_pos_y: 1410944.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494062
      sim_grid_pos_y: 1411907.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1494298.25
      sim_grid_pos_y: 1411960.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1494642.12
      sim_grid_pos_y: 1412368.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1494903.5
      sim_grid_pos_y: 1412485
    }
    terrain_level_point {
      sim_grid_pos_x: 1495172.38
      sim_grid_pos_y: 1412274.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1494783.62
      sim_grid_pos_y: 1411797
    }
    terrain_level_point {
      sim_grid_pos_x: 1494133.12
      sim_grid_pos_y: 1410823.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1493519.38
      sim_grid_pos_y: 1410044.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1493063.25
      sim_grid_pos_y: 1410159.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1493257.88
      sim_grid_pos_y: 1410958.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494044.75
      sim_grid_pos_y: 1411934.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1494281.38
      sim_grid_pos_y: 1411988.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1494623.12
      sim_grid_pos_y: 1412393.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1494907.88
      sim_grid_pos_y: 1412520.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1495216
      sim_grid_pos_y: 1412279.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1494808.38
      sim_grid_pos_y: 1411778.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1494157.75
      sim_grid_pos_y: 1410804.88
    }
  }
}
