terrain_level_data {
  terrain_level: 190
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2757906.75
      sim_grid_pos_y: 2266984
    }
    terrain_level_point {
      sim_grid_pos_x: 2757904.25
      sim_grid_pos_y: 2267110.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2757962
      sim_grid_pos_y: 2267173.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758071.75
      sim_grid_pos_y: 2267198
    }
    terrain_level_point {
      sim_grid_pos_x: 2758175.25
      sim_grid_pos_y: 2267166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758199.75
      sim_grid_pos_y: 2267034.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758161.5
      sim_grid_pos_y: 2.26693e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2758013.25
      sim_grid_pos_y: 2266924.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2757988.25
      sim_grid_pos_y: 2266821.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2757805.5
      sim_grid_pos_y: 2266923
    }
    terrain_level_point {
      sim_grid_pos_x: 2757801
      sim_grid_pos_y: 2267149.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2757908.25
      sim_grid_pos_y: 2267266.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758076
      sim_grid_pos_y: 2267304
    }
    terrain_level_point {
      sim_grid_pos_x: 2758264.75
      sim_grid_pos_y: 2267246
    }
    terrain_level_point {
      sim_grid_pos_x: 2758305.75
      sim_grid_pos_y: 2267025.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758234
      sim_grid_pos_y: 2.26683e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2757963.5
      sim_grid_pos_y: 2266717.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2757704
      sim_grid_pos_y: 2266862
    }
    terrain_level_point {
      sim_grid_pos_x: 2757697.5
      sim_grid_pos_y: 2267188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2757854.5
      sim_grid_pos_y: 2267359.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.75808e+06
      sim_grid_pos_y: 2.26741e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2758354.25
      sim_grid_pos_y: 2267325.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758411.5
      sim_grid_pos_y: 2267016.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758306.5
      sim_grid_pos_y: 2.26673e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2757938.5
      sim_grid_pos_y: 2266614.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2757602.75
      sim_grid_pos_y: 2266801.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2757594.25
      sim_grid_pos_y: 2267227.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2757800.5
      sim_grid_pos_y: 2267452.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758084.25
      sim_grid_pos_y: 2267516
    }
    terrain_level_point {
      sim_grid_pos_x: 2758443.75
      sim_grid_pos_y: 2267405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758517.5
      sim_grid_pos_y: 2267007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758379
      sim_grid_pos_y: 2.26663e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2757913.75
      sim_grid_pos_y: 2266510.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2757501.5
      sim_grid_pos_y: 2266740.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2757491
      sim_grid_pos_y: 2267266.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2757746.75
      sim_grid_pos_y: 2267545.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758088.25
      sim_grid_pos_y: 2267622
    }
    terrain_level_point {
      sim_grid_pos_x: 2758533
      sim_grid_pos_y: 2267485.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758623.5
      sim_grid_pos_y: 2266998.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758451.5
      sim_grid_pos_y: 2.26653e+06
    }
  }
}
terrain_level_data {
  terrain_level: 150
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2758622
      sim_grid_pos_y: 2266615.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758573.75
      sim_grid_pos_y: 2266759.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758644.5
      sim_grid_pos_y: 2266837
    }
    terrain_level_point {
      sim_grid_pos_x: 2758828.75
      sim_grid_pos_y: 2266832.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758894
      sim_grid_pos_y: 2266695
    }
    terrain_level_point {
      sim_grid_pos_x: 2758936.5
      sim_grid_pos_y: 2266427.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758761.75
      sim_grid_pos_y: 2266392
    }
    terrain_level_point {
      sim_grid_pos_x: 2758662.75
      sim_grid_pos_y: 2266417
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2758760.5
      sim_grid_pos_y: 2266339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758619
      sim_grid_pos_y: 2266375.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758572.5
      sim_grid_pos_y: 2266602
    }
    terrain_level_point {
      sim_grid_pos_x: 2758515.5
      sim_grid_pos_y: 2266771.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758622.25
      sim_grid_pos_y: 2266889
    }
    terrain_level_point {
      sim_grid_pos_x: 2758861.75
      sim_grid_pos_y: 2266882.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758943.5
      sim_grid_pos_y: 2266710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758994.75
      sim_grid_pos_y: 2266386.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2758759.25
      sim_grid_pos_y: 2266287
    }
    terrain_level_point {
      sim_grid_pos_x: 2758575.25
      sim_grid_pos_y: 2266333.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2758523
      sim_grid_pos_y: 2266588.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758457.5
      sim_grid_pos_y: 2266783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758600.25
      sim_grid_pos_y: 2266940.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2758894.5
      sim_grid_pos_y: 2266933.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2758993
      sim_grid_pos_y: 2266725.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2759053.25
      sim_grid_pos_y: 2266346.25
    }
  }
}
terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2754008.5
      sim_grid_pos_y: 2262719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753407.25
      sim_grid_pos_y: 2266600.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2750308
      sim_grid_pos_y: 2265615.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2749547.5
      sim_grid_pos_y: 2266669.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2757403.75
      sim_grid_pos_y: 2.27141e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2757626.5
      sim_grid_pos_y: 2270510.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754608.75
      sim_grid_pos_y: 2265700.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2755439.25
      sim_grid_pos_y: 2265324.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2755181
      sim_grid_pos_y: 2265063.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.75444e+06
      sim_grid_pos_y: 2265434.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753982.75
      sim_grid_pos_y: 2264649
    }
    terrain_level_point {
      sim_grid_pos_x: 2753986.5
      sim_grid_pos_y: 2263826.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754551.75
      sim_grid_pos_y: 2263765.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754255.5
      sim_grid_pos_y: 2262799
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2753925.5
      sim_grid_pos_y: 2262585
    }
    terrain_level_point {
      sim_grid_pos_x: 2753324.25
      sim_grid_pos_y: 2266466.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2750268.25
      sim_grid_pos_y: 2265495.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2749399.25
      sim_grid_pos_y: 2266699.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2757469.75
      sim_grid_pos_y: 2271569.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2757736.5
      sim_grid_pos_y: 2270493
    }
    terrain_level_point {
      sim_grid_pos_x: 2754758
      sim_grid_pos_y: 2265745.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2755615.75
      sim_grid_pos_y: 2265357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2755201.5
      sim_grid_pos_y: 2264939
    }
    terrain_level_point {
      sim_grid_pos_x: 2.75448e+06
      sim_grid_pos_y: 2265299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2754085.5
      sim_grid_pos_y: 2264621.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754088.5
      sim_grid_pos_y: 2263918.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754686
      sim_grid_pos_y: 2263854.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754337.75
      sim_grid_pos_y: 2262718
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2753842.75
      sim_grid_pos_y: 2262450.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753241.25
      sim_grid_pos_y: 2266332.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2750228.5
      sim_grid_pos_y: 2265375
    }
    terrain_level_point {
      sim_grid_pos_x: 2749251
      sim_grid_pos_y: 2266729.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2757536
      sim_grid_pos_y: 2271729.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2757846.5
      sim_grid_pos_y: 2270475.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754907.25
      sim_grid_pos_y: 2265790.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2755792.25
      sim_grid_pos_y: 2.26539e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2755222.25
      sim_grid_pos_y: 2264814
    }
    terrain_level_point {
      sim_grid_pos_x: 2754520.25
      sim_grid_pos_y: 2265165
    }
    terrain_level_point {
      sim_grid_pos_x: 2754188
      sim_grid_pos_y: 2264594.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754190.75
      sim_grid_pos_y: 2264010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754820.5
      sim_grid_pos_y: 2263942.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2754420.25
      sim_grid_pos_y: 2262636.75
    }
  }
}
