terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 46711.6914
      sim_grid_pos_y: 2746862
    }
    terrain_level_point {
      sim_grid_pos_x: 47712.5859
      sim_grid_pos_y: 2744137.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46450.9
      sim_grid_pos_y: 2742842.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47205.0977
      sim_grid_pos_y: 2740967.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47997.8242
      sim_grid_pos_y: 2741769.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47669.7891
      sim_grid_pos_y: 2742430.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48537.3711
      sim_grid_pos_y: 2743267
    }
    terrain_level_point {
      sim_grid_pos_x: 48627.7109
      sim_grid_pos_y: 2743223.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49235.5938
      sim_grid_pos_y: 2741513.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46926.6484
      sim_grid_pos_y: 2739112
    }
    terrain_level_point {
      sim_grid_pos_x: 46891.8633
      sim_grid_pos_y: 2739221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46503.4961
      sim_grid_pos_y: 2739568.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45950.2617
      sim_grid_pos_y: 2738827
    }
    terrain_level_point {
      sim_grid_pos_x: 45575.0352
      sim_grid_pos_y: 2738482.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44920.2305
      sim_grid_pos_y: 2738074.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44802.3086
      sim_grid_pos_y: 2737895.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44690.5
      sim_grid_pos_y: 2737490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44616.6641
      sim_grid_pos_y: 2736222.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44913.457
      sim_grid_pos_y: 2736174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45089.1836
      sim_grid_pos_y: 2737701.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45246.4688
      sim_grid_pos_y: 2737889
    }
    terrain_level_point {
      sim_grid_pos_x: 46225.0977
      sim_grid_pos_y: 2738455
    }
    terrain_level_point {
      sim_grid_pos_x: 46387.1914
      sim_grid_pos_y: 2738392
    }
    terrain_level_point {
      sim_grid_pos_x: 46009.5469
      sim_grid_pos_y: 2737680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46093.5742
      sim_grid_pos_y: 2737631
    }
    terrain_level_point {
      sim_grid_pos_x: 45474.5312
      sim_grid_pos_y: 2735204.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45282.0352
      sim_grid_pos_y: 2733807.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44994.9414
      sim_grid_pos_y: 2733827
    }
    terrain_level_point {
      sim_grid_pos_x: 45045.457
      sim_grid_pos_y: 2734260.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44565.2422
      sim_grid_pos_y: 2734184
    }
    terrain_level_point {
      sim_grid_pos_x: 44450.7422
      sim_grid_pos_y: 2735130.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44491.1484
      sim_grid_pos_y: 2735609
    }
    terrain_level_point {
      sim_grid_pos_x: 44455.4375
      sim_grid_pos_y: 2736155.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44470.543
      sim_grid_pos_y: 2736316.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44525.4219
      sim_grid_pos_y: 2736554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44583.2266
      sim_grid_pos_y: 2737576.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44599.1289
      sim_grid_pos_y: 2738143.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45596.4844
      sim_grid_pos_y: 2738659
    }
    terrain_level_point {
      sim_grid_pos_x: 45687.2617
      sim_grid_pos_y: 2739013.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46065.0977
      sim_grid_pos_y: 2739486
    }
    terrain_level_point {
      sim_grid_pos_x: 46036.8047
      sim_grid_pos_y: 2739644.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45902.2461
      sim_grid_pos_y: 2739575.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45651.9492
      sim_grid_pos_y: 2739645.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45538.9492
      sim_grid_pos_y: 2739876
    }
    terrain_level_point {
      sim_grid_pos_x: 45685.5
      sim_grid_pos_y: 2740119.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45644.7109
      sim_grid_pos_y: 2740352.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45802.6484
      sim_grid_pos_y: 2740590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46356.8242
      sim_grid_pos_y: 2740419.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46477.8125
      sim_grid_pos_y: 2739825
    }
    terrain_level_point {
      sim_grid_pos_x: 46722.0117
      sim_grid_pos_y: 2.73997e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 46885.1289
      sim_grid_pos_y: 2.74046e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 47069.8
      sim_grid_pos_y: 2740712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46129.7539
      sim_grid_pos_y: 2743053.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45737.2578
      sim_grid_pos_y: 2745148.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46028.3359
      sim_grid_pos_y: 2745594.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45891.0312
      sim_grid_pos_y: 2746084.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46313.168
      sim_grid_pos_y: 2746213.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46503.2734
      sim_grid_pos_y: 2746822.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 45299.7305
      sim_grid_pos_y: 2733786
    }
    terrain_level_point {
      sim_grid_pos_x: 44972.082
      sim_grid_pos_y: 2733808
    }
    terrain_level_point {
      sim_grid_pos_x: 45021.9609
      sim_grid_pos_y: 2734236
    }
    terrain_level_point {
      sim_grid_pos_x: 44547.4414
      sim_grid_pos_y: 2734160.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44430.1328
      sim_grid_pos_y: 2735130.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44470.5898
      sim_grid_pos_y: 2735609.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44434.8711
      sim_grid_pos_y: 2736155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44450.25
      sim_grid_pos_y: 2.73632e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 44505.0508
      sim_grid_pos_y: 2736557.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44562.7227
      sim_grid_pos_y: 2737577
    }
    terrain_level_point {
      sim_grid_pos_x: 44578.9727
      sim_grid_pos_y: 2738156.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45578.9102
      sim_grid_pos_y: 2738673
    }
    terrain_level_point {
      sim_grid_pos_x: 45668.4922
      sim_grid_pos_y: 2739023
    }
    terrain_level_point {
      sim_grid_pos_x: 46043.2812
      sim_grid_pos_y: 2739491.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46021.4805
      sim_grid_pos_y: 2739614
    }
    terrain_level_point {
      sim_grid_pos_x: 45904.4805
      sim_grid_pos_y: 2739553.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45637.582
      sim_grid_pos_y: 2739628
    }
    terrain_level_point {
      sim_grid_pos_x: 45515.6328
      sim_grid_pos_y: 2739877
    }
    terrain_level_point {
      sim_grid_pos_x: 45663.9805
      sim_grid_pos_y: 2740123.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45623.1
      sim_grid_pos_y: 2740357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45794.0625
      sim_grid_pos_y: 2740614.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46374.4922
      sim_grid_pos_y: 2740435.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46492.1523
      sim_grid_pos_y: 2739857.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46704.9727
      sim_grid_pos_y: 2739983.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46866.6914
      sim_grid_pos_y: 2740469.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47046.5195
      sim_grid_pos_y: 2740715.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46109.9727
      sim_grid_pos_y: 2743047.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45715.5898
      sim_grid_pos_y: 2745152.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46006.0898
      sim_grid_pos_y: 2745597.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45865.8906
      sim_grid_pos_y: 2746098.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46296.832
      sim_grid_pos_y: 2746230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46487.3711
      sim_grid_pos_y: 2746840.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46724.9531
      sim_grid_pos_y: 2746885.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47736.2812
      sim_grid_pos_y: 2744132.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46474.9102
      sim_grid_pos_y: 2742837.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47212.4609
      sim_grid_pos_y: 2741004
    }
    terrain_level_point {
      sim_grid_pos_x: 47972.9414
      sim_grid_pos_y: 2741773.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47644.75
      sim_grid_pos_y: 2742435
    }
    terrain_level_point {
      sim_grid_pos_x: 48533.4297
      sim_grid_pos_y: 2743291.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48644.2109
      sim_grid_pos_y: 2743238.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49259.1602
      sim_grid_pos_y: 2741508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46917.5195
      sim_grid_pos_y: 2739073
    }
    terrain_level_point {
      sim_grid_pos_x: 46874
      sim_grid_pos_y: 2739210.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46506.5508
      sim_grid_pos_y: 2739538
    }
    terrain_level_point {
      sim_grid_pos_x: 45965.5508
      sim_grid_pos_y: 2738813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45587.5
      sim_grid_pos_y: 2738466
    }
    terrain_level_point {
      sim_grid_pos_x: 44934.9023
      sim_grid_pos_y: 2738059.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44821.2109
      sim_grid_pos_y: 2737886.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44710.8516
      sim_grid_pos_y: 2737487.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44638.2109
      sim_grid_pos_y: 2736239.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44895.5508
      sim_grid_pos_y: 2736198
    }
    terrain_level_point {
      sim_grid_pos_x: 45069.5117
      sim_grid_pos_y: 2737710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45233.0898
      sim_grid_pos_y: 2737904.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46223.3516
      sim_grid_pos_y: 2738477.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46416.1
      sim_grid_pos_y: 2738402.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46036.8828
      sim_grid_pos_y: 2737688
    }
    terrain_level_point {
      sim_grid_pos_x: 46117.25
      sim_grid_pos_y: 2737640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45494.6797
      sim_grid_pos_y: 2735200.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 45317.4297
      sim_grid_pos_y: 2733764.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44949.2227
      sim_grid_pos_y: 2733789
    }
    terrain_level_point {
      sim_grid_pos_x: 44998.4727
      sim_grid_pos_y: 2734211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44529.6406
      sim_grid_pos_y: 2734137
    }
    terrain_level_point {
      sim_grid_pos_x: 44409.5234
      sim_grid_pos_y: 2735129.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44450.0312
      sim_grid_pos_y: 2735609.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44414.3
      sim_grid_pos_y: 2736156
    }
    terrain_level_point {
      sim_grid_pos_x: 44429.9609
      sim_grid_pos_y: 2736323.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44484.6719
      sim_grid_pos_y: 2.73656e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 44542.2617
      sim_grid_pos_y: 2737578.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44558.8125
      sim_grid_pos_y: 2738169
    }
    terrain_level_point {
      sim_grid_pos_x: 45561.3203
      sim_grid_pos_y: 2738686.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45649.7227
      sim_grid_pos_y: 2739032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46021.4609
      sim_grid_pos_y: 2739497
    }
    terrain_level_point {
      sim_grid_pos_x: 46006.1602
      sim_grid_pos_y: 2739583
    }
    terrain_level_point {
      sim_grid_pos_x: 45906.7227
      sim_grid_pos_y: 2739531.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45623.2227
      sim_grid_pos_y: 2739610.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45492.3125
      sim_grid_pos_y: 2739878
    }
    terrain_level_point {
      sim_grid_pos_x: 45642.4609
      sim_grid_pos_y: 2740127.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45601.4922
      sim_grid_pos_y: 2740361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45785.4609
      sim_grid_pos_y: 2740638.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46392.1523
      sim_grid_pos_y: 2740451.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46506.4922
      sim_grid_pos_y: 2739889.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46687.9219
      sim_grid_pos_y: 2739997.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46848.2422
      sim_grid_pos_y: 2740479
    }
    terrain_level_point {
      sim_grid_pos_x: 47023.2617
      sim_grid_pos_y: 2740718.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46090.1914
      sim_grid_pos_y: 2743041.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45693.9219
      sim_grid_pos_y: 2745157
    }
    terrain_level_point {
      sim_grid_pos_x: 45983.8398
      sim_grid_pos_y: 2745601
    }
    terrain_level_point {
      sim_grid_pos_x: 45840.7422
      sim_grid_pos_y: 2746112.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46280.4805
      sim_grid_pos_y: 2746246.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46471.4609
      sim_grid_pos_y: 2746858.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46738.2109
      sim_grid_pos_y: 2746908.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47759.9805
      sim_grid_pos_y: 2744127.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46498.9219
      sim_grid_pos_y: 2742833
    }
    terrain_level_point {
      sim_grid_pos_x: 47219.832
      sim_grid_pos_y: 2741040.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47948.0625
      sim_grid_pos_y: 2741777.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47619.7031
      sim_grid_pos_y: 2742439.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48529.5
      sim_grid_pos_y: 2743316.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48660.7227
      sim_grid_pos_y: 2743253
    }
    terrain_level_point {
      sim_grid_pos_x: 49282.7227
      sim_grid_pos_y: 2741503.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46908.3906
      sim_grid_pos_y: 2739033.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46856.1602
      sim_grid_pos_y: 2739198.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46509.6
      sim_grid_pos_y: 2739507.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45980.832
      sim_grid_pos_y: 2738799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45599.9727
      sim_grid_pos_y: 2738449.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44949.5508
      sim_grid_pos_y: 2738044.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44840.1328
      sim_grid_pos_y: 2737878
    }
    terrain_level_point {
      sim_grid_pos_x: 44731.1914
      sim_grid_pos_y: 2737484
    }
    terrain_level_point {
      sim_grid_pos_x: 44659.7617
      sim_grid_pos_y: 2736257
    }
    terrain_level_point {
      sim_grid_pos_x: 44877.6328
      sim_grid_pos_y: 2736221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45049.8516
      sim_grid_pos_y: 2737718.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45219.7109
      sim_grid_pos_y: 2737920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46221.6133
      sim_grid_pos_y: 2738500.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46445.0195
      sim_grid_pos_y: 2738413.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46064.2031
      sim_grid_pos_y: 2737695.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46140.9297
      sim_grid_pos_y: 2737650.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45514.8516
      sim_grid_pos_y: 2735196.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 45335.1406
      sim_grid_pos_y: 2733742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44926.3633
      sim_grid_pos_y: 2.73377e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 44974.9727
      sim_grid_pos_y: 2734187
    }
    terrain_level_point {
      sim_grid_pos_x: 44511.8398
      sim_grid_pos_y: 2734113.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44388.9102
      sim_grid_pos_y: 2735129.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44429.4727
      sim_grid_pos_y: 2735609.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44393.7422
      sim_grid_pos_y: 2736156.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44409.6797
      sim_grid_pos_y: 2736326.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44464.3
      sim_grid_pos_y: 2736563
    }
    terrain_level_point {
      sim_grid_pos_x: 44521.7617
      sim_grid_pos_y: 2737579.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44538.6602
      sim_grid_pos_y: 2738181.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45543.7422
      sim_grid_pos_y: 2738700.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45630.9531
      sim_grid_pos_y: 2739041.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45999.6523
      sim_grid_pos_y: 2739502.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45990.8516
      sim_grid_pos_y: 2739552
    }
    terrain_level_point {
      sim_grid_pos_x: 45908.9609
      sim_grid_pos_y: 2.73951e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 45608.8516
      sim_grid_pos_y: 2739593.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45468.9805
      sim_grid_pos_y: 2739879
    }
    terrain_level_point {
      sim_grid_pos_x: 45620.9531
      sim_grid_pos_y: 2740131.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45579.8828
      sim_grid_pos_y: 2740366.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45776.8711
      sim_grid_pos_y: 2740662.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46409.8203
      sim_grid_pos_y: 2740467.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46520.8203
      sim_grid_pos_y: 2739922
    }
    terrain_level_point {
      sim_grid_pos_x: 46670.8828
      sim_grid_pos_y: 2740011.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46829.8
      sim_grid_pos_y: 2740488.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46999.9922
      sim_grid_pos_y: 2740721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46070.4023
      sim_grid_pos_y: 2743036
    }
    terrain_level_point {
      sim_grid_pos_x: 45672.25
      sim_grid_pos_y: 2745161.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45961.5898
      sim_grid_pos_y: 2745604.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45815.6
      sim_grid_pos_y: 2746126
    }
    terrain_level_point {
      sim_grid_pos_x: 46264.1406
      sim_grid_pos_y: 2746263
    }
    terrain_level_point {
      sim_grid_pos_x: 46455.5625
      sim_grid_pos_y: 2746876.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46751.4727
      sim_grid_pos_y: 2746932
    }
    terrain_level_point {
      sim_grid_pos_x: 47783.6914
      sim_grid_pos_y: 2744122.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46522.9297
      sim_grid_pos_y: 2742828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47227.2031
      sim_grid_pos_y: 2741077.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47923.2031
      sim_grid_pos_y: 2741781.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47594.6602
      sim_grid_pos_y: 2742443.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48525.5625
      sim_grid_pos_y: 2743341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48677.2227
      sim_grid_pos_y: 2743267.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49306.293
      sim_grid_pos_y: 2741498.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46899.2617
      sim_grid_pos_y: 2738994.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46838.3
      sim_grid_pos_y: 2739187.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46512.6602
      sim_grid_pos_y: 2739477.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45996.1211
      sim_grid_pos_y: 2738785.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45612.4297
      sim_grid_pos_y: 2738433.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44964.2227
      sim_grid_pos_y: 2738029.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44859.0312
      sim_grid_pos_y: 2737869.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44751.543
      sim_grid_pos_y: 2737480.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44681.3
      sim_grid_pos_y: 2736274.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44859.7227
      sim_grid_pos_y: 2736245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45030.1797
      sim_grid_pos_y: 2737727.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45206.332
      sim_grid_pos_y: 2737936.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46219.8711
      sim_grid_pos_y: 2738523.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46473.9297
      sim_grid_pos_y: 2738424.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46091.5195
      sim_grid_pos_y: 2737703.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46164.6211
      sim_grid_pos_y: 2737660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45535
      sim_grid_pos_y: 2735192.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 45352.8398
      sim_grid_pos_y: 2733720.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44903.5
      sim_grid_pos_y: 2733751
    }
    terrain_level_point {
      sim_grid_pos_x: 44951.4727
      sim_grid_pos_y: 2734162.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44494.043
      sim_grid_pos_y: 2734089.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44368.3
      sim_grid_pos_y: 2735129
    }
    terrain_level_point {
      sim_grid_pos_x: 44408.9102
      sim_grid_pos_y: 2735609.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44373.1719
      sim_grid_pos_y: 2736156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44389.3906
      sim_grid_pos_y: 2736329.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44443.9297
      sim_grid_pos_y: 2736566
    }
    terrain_level_point {
      sim_grid_pos_x: 44501.2734
      sim_grid_pos_y: 2.73758e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 44518.5
      sim_grid_pos_y: 2738194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45526.1523
      sim_grid_pos_y: 2738714.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45612.1797
      sim_grid_pos_y: 2739051
    }
    terrain_level_point {
      sim_grid_pos_x: 45977.832
      sim_grid_pos_y: 2739508
    }
    terrain_level_point {
      sim_grid_pos_x: 45975.5195
      sim_grid_pos_y: 2739521
    }
    terrain_level_point {
      sim_grid_pos_x: 45911.2031
      sim_grid_pos_y: 2739488
    }
    terrain_level_point {
      sim_grid_pos_x: 45594.4805
      sim_grid_pos_y: 2739576
    }
    terrain_level_point {
      sim_grid_pos_x: 45445.6602
      sim_grid_pos_y: 2.73988e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 45599.4297
      sim_grid_pos_y: 2740135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45558.2695
      sim_grid_pos_y: 2740370.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45768.2812
      sim_grid_pos_y: 2740686.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46427.4922
      sim_grid_pos_y: 2740483.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46535.1523
      sim_grid_pos_y: 2739954.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46653.8398
      sim_grid_pos_y: 2740025
    }
    terrain_level_point {
      sim_grid_pos_x: 46811.3633
      sim_grid_pos_y: 2740498
    }
    terrain_level_point {
      sim_grid_pos_x: 46976.7227
      sim_grid_pos_y: 2740724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46050.6211
      sim_grid_pos_y: 2743030.25
    }
    terrain_level_point {
      sim_grid_pos_x: 45650.582
      sim_grid_pos_y: 2745165.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45939.3398
      sim_grid_pos_y: 2745607.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45790.4609
      sim_grid_pos_y: 2746139.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46247.793
      sim_grid_pos_y: 2746279.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46439.6602
      sim_grid_pos_y: 2746894
    }
    terrain_level_point {
      sim_grid_pos_x: 46764.7305
      sim_grid_pos_y: 2746955.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47807.3906
      sim_grid_pos_y: 2744117.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46546.9414
      sim_grid_pos_y: 2742823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47234.5703
      sim_grid_pos_y: 2741113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47898.3125
      sim_grid_pos_y: 2741785.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47569.6133
      sim_grid_pos_y: 2742448
    }
    terrain_level_point {
      sim_grid_pos_x: 48521.6211
      sim_grid_pos_y: 2743365.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48693.7227
      sim_grid_pos_y: 2743282.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49329.8594
      sim_grid_pos_y: 2741493.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46890.1211
      sim_grid_pos_y: 2738955.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46820.4609
      sim_grid_pos_y: 2739175.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46515.7109
      sim_grid_pos_y: 2739447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 46011.4023
      sim_grid_pos_y: 2738772
    }
    terrain_level_point {
      sim_grid_pos_x: 45624.8906
      sim_grid_pos_y: 2738416.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44978.8906
      sim_grid_pos_y: 2738014.5
    }
    terrain_level_point {
      sim_grid_pos_x: 44877.9414
      sim_grid_pos_y: 2737861
    }
    terrain_level_point {
      sim_grid_pos_x: 44771.8828
      sim_grid_pos_y: 2737477.25
    }
    terrain_level_point {
      sim_grid_pos_x: 44702.8516
      sim_grid_pos_y: 2736291.75
    }
    terrain_level_point {
      sim_grid_pos_x: 44841.8
      sim_grid_pos_y: 2736269
    }
    terrain_level_point {
      sim_grid_pos_x: 45010.5195
      sim_grid_pos_y: 2737735.75
    }
    terrain_level_point {
      sim_grid_pos_x: 45192.9531
      sim_grid_pos_y: 2737952.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46218.1328
      sim_grid_pos_y: 2738545.75
    }
    terrain_level_point {
      sim_grid_pos_x: 46502.8516
      sim_grid_pos_y: 2738435
    }
    terrain_level_point {
      sim_grid_pos_x: 46118.8398
      sim_grid_pos_y: 2737711.25
    }
    terrain_level_point {
      sim_grid_pos_x: 46188.3
      sim_grid_pos_y: 2737670.5
    }
    terrain_level_point {
      sim_grid_pos_x: 45555.1406
      sim_grid_pos_y: 2735188.5
    }
  }
}
