terrain_level_data {
  terrain_level: 354
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 998991.312
      sim_grid_pos_y: 1936653.88
    }
    terrain_level_point {
      sim_grid_pos_x: 998492.188
      sim_grid_pos_y: 1935998.25
    }
    terrain_level_point {
      sim_grid_pos_x: 999459.75
      sim_grid_pos_y: 1935206.62
    }
    terrain_level_point {
      sim_grid_pos_x: 998765.875
      sim_grid_pos_y: 1934040.38
    }
    terrain_level_point {
      sim_grid_pos_x: 998963.875
      sim_grid_pos_y: 1931681.25
    }
    terrain_level_point {
      sim_grid_pos_x: 998776.062
      sim_grid_pos_y: 1930322.5
    }
    terrain_level_point {
      sim_grid_pos_x: 998758.875
      sim_grid_pos_y: 1928963.12
    }
    terrain_level_point {
      sim_grid_pos_x: 997677.188
      sim_grid_pos_y: 1927459.62
    }
    terrain_level_point {
      sim_grid_pos_x: 997074.688
      sim_grid_pos_y: 1925531.25
    }
    terrain_level_point {
      sim_grid_pos_x: 997143.938
      sim_grid_pos_y: 1924847.38
    }
    terrain_level_point {
      sim_grid_pos_x: 998861.375
      sim_grid_pos_y: 1923743.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1001570.38
      sim_grid_pos_y: 1924910.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1001782.75
      sim_grid_pos_y: 1925853.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1001727.19
      sim_grid_pos_y: 1928955.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1002000.12
      sim_grid_pos_y: 1930527.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1001221.69
      sim_grid_pos_y: 1930828.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1001318.25
      sim_grid_pos_y: 1933995.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1001374.62
      sim_grid_pos_y: 1934661.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1001872.69
      sim_grid_pos_y: 1934670.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1001878.88
      sim_grid_pos_y: 1935043.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1001535
      sim_grid_pos_y: 1935397.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1001297.12
      sim_grid_pos_y: 1936102.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1000909.75
      sim_grid_pos_y: 1936694
    }
    terrain_level_point {
      sim_grid_pos_x: 1000381.12
      sim_grid_pos_y: 1936314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1000064.75
      sim_grid_pos_y: 1935846.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1001658.94
      sim_grid_pos_y: 1924836.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1001885.5
      sim_grid_pos_y: 1925843
    }
    terrain_level_point {
      sim_grid_pos_x: 1001829.88
      sim_grid_pos_y: 1928947.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1002115.5
      sim_grid_pos_y: 1930592.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1001326.38
      sim_grid_pos_y: 1930897.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1001420.69
      sim_grid_pos_y: 1.93399e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1001469
      sim_grid_pos_y: 1934560.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1001973.56
      sim_grid_pos_y: 1934569.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1001982.12
      sim_grid_pos_y: 1935084.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1001624.75
      sim_grid_pos_y: 1935452.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1001390.06
      sim_grid_pos_y: 1936147.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1000936.88
      sim_grid_pos_y: 1936839.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1000306.44
      sim_grid_pos_y: 1936386.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1000040.19
      sim_grid_pos_y: 1935993
    }
    terrain_level_point {
      sim_grid_pos_x: 998971.438
      sim_grid_pos_y: 1936797.12
    }
    terrain_level_point {
      sim_grid_pos_x: 998350.625
      sim_grid_pos_y: 1935981.62
    }
    terrain_level_point {
      sim_grid_pos_x: 999326.5
      sim_grid_pos_y: 1935183.25
    }
    terrain_level_point {
      sim_grid_pos_x: 998660.938
      sim_grid_pos_y: 1934064.62
    }
    terrain_level_point {
      sim_grid_pos_x: 998860.75
      sim_grid_pos_y: 1931684
    }
    terrain_level_point {
      sim_grid_pos_x: 998673.625
      sim_grid_pos_y: 1930330.25
    }
    terrain_level_point {
      sim_grid_pos_x: 998656.75
      sim_grid_pos_y: 1928996.75
    }
    terrain_level_point {
      sim_grid_pos_x: 997584.312
      sim_grid_pos_y: 1927506
    }
    terrain_level_point {
      sim_grid_pos_x: 996970.625
      sim_grid_pos_y: 1925541.88
    }
    terrain_level_point {
      sim_grid_pos_x: 997046.875
      sim_grid_pos_y: 1924787.88
    }
    terrain_level_point {
      sim_grid_pos_x: 998851.812
      sim_grid_pos_y: 1923627.38
    }
  }
}
