terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 105415.75
      sim_grid_pos_y: 3356449.75
    }
    terrain_level_point {
      sim_grid_pos_x: 104110.383
      sim_grid_pos_y: 3355035
    }
    terrain_level_point {
      sim_grid_pos_x: 105359.828
      sim_grid_pos_y: 3353592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 106701.359
      sim_grid_pos_y: 3355607.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 106744.125
      sim_grid_pos_y: 3355616.25
    }
    terrain_level_point {
      sim_grid_pos_x: 105410.82
      sim_grid_pos_y: 3356489.75
    }
    terrain_level_point {
      sim_grid_pos_x: 104069.125
      sim_grid_pos_y: 3355035.5
    }
    terrain_level_point {
      sim_grid_pos_x: 105363.039
      sim_grid_pos_y: 3353541.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 106786.906
      sim_grid_pos_y: 3355625
    }
    terrain_level_point {
      sim_grid_pos_x: 105405.891
      sim_grid_pos_y: 3356529.75
    }
    terrain_level_point {
      sim_grid_pos_x: 104027.867
      sim_grid_pos_y: 3355036.25
    }
    terrain_level_point {
      sim_grid_pos_x: 105366.25
      sim_grid_pos_y: 3353491
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 104258.852
      sim_grid_pos_y: 3355378.75
    }
    terrain_level_point {
      sim_grid_pos_x: 105404.406
      sim_grid_pos_y: 3356621.75
    }
    terrain_level_point {
      sim_grid_pos_x: 106708.25
      sim_grid_pos_y: 3355761.75
    }
    terrain_level_point {
      sim_grid_pos_x: 106877.102
      sim_grid_pos_y: 3356014
    }
    terrain_level_point {
      sim_grid_pos_x: 108582.086
      sim_grid_pos_y: 3355932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 108569.594
      sim_grid_pos_y: 3356453.5
    }
    terrain_level_point {
      sim_grid_pos_x: 106869.07
      sim_grid_pos_y: 3356337.25
    }
    terrain_level_point {
      sim_grid_pos_x: 105388.57
      sim_grid_pos_y: 3357406
    }
    terrain_level_point {
      sim_grid_pos_x: 103561.273
      sim_grid_pos_y: 3355806.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 105407.68
      sim_grid_pos_y: 3356595
    }
    terrain_level_point {
      sim_grid_pos_x: 106713.961
      sim_grid_pos_y: 3355733.5
    }
    terrain_level_point {
      sim_grid_pos_x: 106887.688
      sim_grid_pos_y: 3355993
    }
    terrain_level_point {
      sim_grid_pos_x: 108603.117
      sim_grid_pos_y: 3355910.5
    }
    terrain_level_point {
      sim_grid_pos_x: 108589.586
      sim_grid_pos_y: 3356475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 106875.055
      sim_grid_pos_y: 3356358.25
    }
    terrain_level_point {
      sim_grid_pos_x: 105387.336
      sim_grid_pos_y: 3357432.25
    }
    terrain_level_point {
      sim_grid_pos_x: 103526.805
      sim_grid_pos_y: 3355803.25
    }
    terrain_level_point {
      sim_grid_pos_x: 104262.508
      sim_grid_pos_y: 3355352.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 105410.938
      sim_grid_pos_y: 3356568.25
    }
    terrain_level_point {
      sim_grid_pos_x: 106719.664
      sim_grid_pos_y: 3355705.25
    }
    terrain_level_point {
      sim_grid_pos_x: 106898.281
      sim_grid_pos_y: 3355972
    }
    terrain_level_point {
      sim_grid_pos_x: 108624.141
      sim_grid_pos_y: 3355889
    }
    terrain_level_point {
      sim_grid_pos_x: 108609.57
      sim_grid_pos_y: 3356497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 106881.047
      sim_grid_pos_y: 3356379.25
    }
    terrain_level_point {
      sim_grid_pos_x: 105386.109
      sim_grid_pos_y: 3357458.5
    }
    terrain_level_point {
      sim_grid_pos_x: 103492.336
      sim_grid_pos_y: 3355800.5
    }
    terrain_level_point {
      sim_grid_pos_x: 104266.156
      sim_grid_pos_y: 3355326.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 105414.195
      sim_grid_pos_y: 3356541.75
    }
    terrain_level_point {
      sim_grid_pos_x: 106725.375
      sim_grid_pos_y: 3355676.75
    }
    terrain_level_point {
      sim_grid_pos_x: 106908.875
      sim_grid_pos_y: 3355951
    }
    terrain_level_point {
      sim_grid_pos_x: 108645.164
      sim_grid_pos_y: 3355867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 108629.555
      sim_grid_pos_y: 3356519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 106887.055
      sim_grid_pos_y: 3356400.25
    }
    terrain_level_point {
      sim_grid_pos_x: 105384.875
      sim_grid_pos_y: 3357484.5
    }
    terrain_level_point {
      sim_grid_pos_x: 103457.859
      sim_grid_pos_y: 3355797.5
    }
    terrain_level_point {
      sim_grid_pos_x: 104269.82
      sim_grid_pos_y: 3.3553e+06
    }
  }
}
