terrain_level_data {
  terrain_level: 370
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2076238.75
      sim_grid_pos_y: 1341808.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076276.88
      sim_grid_pos_y: 1342037.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076036.75
      sim_grid_pos_y: 1342539.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2075950.12
      sim_grid_pos_y: 1342627.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2075928
      sim_grid_pos_y: 1343049.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2075986.25
      sim_grid_pos_y: 1343670.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076086.38
      sim_grid_pos_y: 1343994.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2075838.38
      sim_grid_pos_y: 1344360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2075851.75
      sim_grid_pos_y: 1344867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076078.88
      sim_grid_pos_y: 1345072.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076494.75
      sim_grid_pos_y: 1345527.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076805.12
      sim_grid_pos_y: 1345771.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2077415.12
      sim_grid_pos_y: 1345743
    }
    terrain_level_point {
      sim_grid_pos_x: 2077674.75
      sim_grid_pos_y: 1345529.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2078209.38
      sim_grid_pos_y: 1344897.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2078386.88
      sim_grid_pos_y: 1344588.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2077853.62
      sim_grid_pos_y: 1341731.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2077489.75
      sim_grid_pos_y: 1340180.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2077230.62
      sim_grid_pos_y: 1340211.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2077221.75
      sim_grid_pos_y: 1340418.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076524.38
      sim_grid_pos_y: 1341019.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076282.62
      sim_grid_pos_y: 1340995
    }
    terrain_level_point {
      sim_grid_pos_x: 2076222.75
      sim_grid_pos_y: 1341047.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2076260.12
      sim_grid_pos_y: 1341107.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2076352
      sim_grid_pos_y: 1341167.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076331.62
      sim_grid_pos_y: 1341359.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2076222.75
      sim_grid_pos_y: 1341637.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2077521.38
      sim_grid_pos_y: 1340135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2077191.12
      sim_grid_pos_y: 1340175
    }
    terrain_level_point {
      sim_grid_pos_x: 2077181.62
      sim_grid_pos_y: 1340399
    }
    terrain_level_point {
      sim_grid_pos_x: 2076511
      sim_grid_pos_y: 1340976.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2076269
      sim_grid_pos_y: 1340952.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076169.62
      sim_grid_pos_y: 1.34104e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2076230.12
      sim_grid_pos_y: 1341137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076308.62
      sim_grid_pos_y: 1341188.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2076291.5
      sim_grid_pos_y: 1.34135e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2076181
      sim_grid_pos_y: 1341631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076198.12
      sim_grid_pos_y: 1341813.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2076234.25
      sim_grid_pos_y: 1342031.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076002.75
      sim_grid_pos_y: 1342515.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.07591e+06
      sim_grid_pos_y: 1342610.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2075887
      sim_grid_pos_y: 1343050.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2075945.75
      sim_grid_pos_y: 1343678.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076041.38
      sim_grid_pos_y: 1343987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2075797
      sim_grid_pos_y: 1344348.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2075811.25
      sim_grid_pos_y: 1344885.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.07605e+06
      sim_grid_pos_y: 1345101.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076466.75
      sim_grid_pos_y: 1345557.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076791.88
      sim_grid_pos_y: 1345813
    }
    terrain_level_point {
      sim_grid_pos_x: 2077430.62
      sim_grid_pos_y: 1345783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2077703.62
      sim_grid_pos_y: 1345559.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2078243.12
      sim_grid_pos_y: 1344921.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.07843e+06
      sim_grid_pos_y: 1344595.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2077893.75
      sim_grid_pos_y: 1341722.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2077552.88
      sim_grid_pos_y: 1340090.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2077151.62
      sim_grid_pos_y: 1340138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2077141.38
      sim_grid_pos_y: 1340379.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076497.62
      sim_grid_pos_y: 1340934.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076255.38
      sim_grid_pos_y: 1340909.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2076116.38
      sim_grid_pos_y: 1341032.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2076200.12
      sim_grid_pos_y: 1341166.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2076265.25
      sim_grid_pos_y: 1341208.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2076251.25
      sim_grid_pos_y: 1341340.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2076139.25
      sim_grid_pos_y: 1341625.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076157.38
      sim_grid_pos_y: 1341819
    }
    terrain_level_point {
      sim_grid_pos_x: 2076191.75
      sim_grid_pos_y: 1342025.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2075968.62
      sim_grid_pos_y: 1342491.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2075869.88
      sim_grid_pos_y: 1342592.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2075845.88
      sim_grid_pos_y: 1343051.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2075905.38
      sim_grid_pos_y: 1343686.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2075996.38
      sim_grid_pos_y: 1343981.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2075755.62
      sim_grid_pos_y: 1344336.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2075770.75
      sim_grid_pos_y: 1344904.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076021
      sim_grid_pos_y: 1345130.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2076438.88
      sim_grid_pos_y: 1345587.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2076778.5
      sim_grid_pos_y: 1345854.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2077446.12
      sim_grid_pos_y: 1345823.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2077732.62
      sim_grid_pos_y: 1345588.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2078276.88
      sim_grid_pos_y: 1344945
    }
    terrain_level_point {
      sim_grid_pos_x: 2078473.12
      sim_grid_pos_y: 1344603.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2077934
      sim_grid_pos_y: 1341714.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2077584.38
      sim_grid_pos_y: 1340045.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2077112.12
      sim_grid_pos_y: 1340101.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2077101.12
      sim_grid_pos_y: 1.34036e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2076484.12
      sim_grid_pos_y: 1340891.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2076241.62
      sim_grid_pos_y: 1340867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076063.25
      sim_grid_pos_y: 1341024.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076170.25
      sim_grid_pos_y: 1341196.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2076221.75
      sim_grid_pos_y: 1341229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076211
      sim_grid_pos_y: 1341330.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2076097.62
      sim_grid_pos_y: 1341619.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2076116.62
      sim_grid_pos_y: 1341824.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076149.12
      sim_grid_pos_y: 1342019.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2075934.62
      sim_grid_pos_y: 1342468
    }
    terrain_level_point {
      sim_grid_pos_x: 2075829.75
      sim_grid_pos_y: 1342575
    }
    terrain_level_point {
      sim_grid_pos_x: 2075804.75
      sim_grid_pos_y: 1343052.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2075864.88
      sim_grid_pos_y: 1343694.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2075951.38
      sim_grid_pos_y: 1343974.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2075714.38
      sim_grid_pos_y: 1344324.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2075730.12
      sim_grid_pos_y: 1344923.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2075992.12
      sim_grid_pos_y: 1345159.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2076410.88
      sim_grid_pos_y: 1345617.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2076765.12
      sim_grid_pos_y: 1345896.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2077461.62
      sim_grid_pos_y: 1345864
    }
    terrain_level_point {
      sim_grid_pos_x: 2077761.5
      sim_grid_pos_y: 1345617.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2078310.62
      sim_grid_pos_y: 1344968.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2078516.25
      sim_grid_pos_y: 1344610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2077974.12
      sim_grid_pos_y: 1341705.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2077616
      sim_grid_pos_y: 1340000.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2077072.62
      sim_grid_pos_y: 1340065.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2077060.88
      sim_grid_pos_y: 1340340.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076470.75
      sim_grid_pos_y: 1340849.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2076228
      sim_grid_pos_y: 1340824.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.07601e+06
      sim_grid_pos_y: 1341016.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076140.25
      sim_grid_pos_y: 1341225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076178.38
      sim_grid_pos_y: 1341250.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2076170.88
      sim_grid_pos_y: 1341320.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076055.88
      sim_grid_pos_y: 1341613.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2076076
      sim_grid_pos_y: 1341829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2076106.5
      sim_grid_pos_y: 1342013.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2075900.5
      sim_grid_pos_y: 1342444.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2075789.62
      sim_grid_pos_y: 1342557.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2075763.62
      sim_grid_pos_y: 1343053.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2075824.5
      sim_grid_pos_y: 1343702.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2075906.38
      sim_grid_pos_y: 1343967.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2075673
      sim_grid_pos_y: 1344312.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2075689.62
      sim_grid_pos_y: 1344941.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2075963.12
      sim_grid_pos_y: 1345188.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2076382.88
      sim_grid_pos_y: 1345648
    }
    terrain_level_point {
      sim_grid_pos_x: 2076751.75
      sim_grid_pos_y: 1345938.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2077477.12
      sim_grid_pos_y: 1345904.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2077790.38
      sim_grid_pos_y: 1345647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2078344.25
      sim_grid_pos_y: 1344992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2078559.25
      sim_grid_pos_y: 1344617.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2078014.25
      sim_grid_pos_y: 1341697.25
    }
  }
}
