terrain_level_data {
  terrain_level: 14
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 476156.406
      sim_grid_pos_y: 2105383
    }
    terrain_level_point {
      sim_grid_pos_x: 476338.969
      sim_grid_pos_y: 2108072.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479154.031
      sim_grid_pos_y: 2107738.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479148.531
      sim_grid_pos_y: 2107137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 480533.594
      sim_grid_pos_y: 2107754.75
    }
    terrain_level_point {
      sim_grid_pos_x: 480821.875
      sim_grid_pos_y: 2109866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 480496.375
      sim_grid_pos_y: 2110410.75
    }
    terrain_level_point {
      sim_grid_pos_x: 480615.094
      sim_grid_pos_y: 2110997
    }
    terrain_level_point {
      sim_grid_pos_x: 476070
      sim_grid_pos_y: 2111545.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475745.562
      sim_grid_pos_y: 2112230.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475339.844
      sim_grid_pos_y: 2112307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475042
      sim_grid_pos_y: 2113809.25
    }
    terrain_level_point {
      sim_grid_pos_x: 474378.5
      sim_grid_pos_y: 2113307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 472787.906
      sim_grid_pos_y: 2112217.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471495.281
      sim_grid_pos_y: 2112427
    }
    terrain_level_point {
      sim_grid_pos_x: 471011.719
      sim_grid_pos_y: 2113810.25
    }
    terrain_level_point {
      sim_grid_pos_x: 469767.094
      sim_grid_pos_y: 2113137.75
    }
    terrain_level_point {
      sim_grid_pos_x: 470266.25
      sim_grid_pos_y: 2111521.75
    }
    terrain_level_point {
      sim_grid_pos_x: 468041.312
      sim_grid_pos_y: 2110403.75
    }
    terrain_level_point {
      sim_grid_pos_x: 467899.594
      sim_grid_pos_y: 2108608
    }
    terrain_level_point {
      sim_grid_pos_x: 469907.844
      sim_grid_pos_y: 2108419
    }
    terrain_level_point {
      sim_grid_pos_x: 470328.031
      sim_grid_pos_y: 2108634.75
    }
    terrain_level_point {
      sim_grid_pos_x: 473396.125
      sim_grid_pos_y: 2108245
    }
    terrain_level_point {
      sim_grid_pos_x: 474379.625
      sim_grid_pos_y: 2105250.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 476252.656
      sim_grid_pos_y: 2105287.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476433.938
      sim_grid_pos_y: 2107958
    }
    terrain_level_point {
      sim_grid_pos_x: 479050.656
      sim_grid_pos_y: 2107647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479044.562
      sim_grid_pos_y: 2106978.75
    }
    terrain_level_point {
      sim_grid_pos_x: 480627.438
      sim_grid_pos_y: 2107684.5
    }
    terrain_level_point {
      sim_grid_pos_x: 480928.312
      sim_grid_pos_y: 2109888.25
    }
    terrain_level_point {
      sim_grid_pos_x: 480604.719
      sim_grid_pos_y: 2110429.25
    }
    terrain_level_point {
      sim_grid_pos_x: 480737.594
      sim_grid_pos_y: 2111085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 476138.438
      sim_grid_pos_y: 2111640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475815.906
      sim_grid_pos_y: 2112321.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475426.969
      sim_grid_pos_y: 2112395.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475110.719
      sim_grid_pos_y: 2113989.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474318.625
      sim_grid_pos_y: 2113391
    }
    terrain_level_point {
      sim_grid_pos_x: 472763.812
      sim_grid_pos_y: 2112325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471571.906
      sim_grid_pos_y: 2112518.25
    }
    terrain_level_point {
      sim_grid_pos_x: 471068.781
      sim_grid_pos_y: 2113957.5
    }
    terrain_level_point {
      sim_grid_pos_x: 469644.281
      sim_grid_pos_y: 2113188
    }
    terrain_level_point {
      sim_grid_pos_x: 470142.688
      sim_grid_pos_y: 2111574.25
    }
    terrain_level_point {
      sim_grid_pos_x: 467943.656
      sim_grid_pos_y: 2110469.5
    }
    terrain_level_point {
      sim_grid_pos_x: 467789.438
      sim_grid_pos_y: 2108515.5
    }
    terrain_level_point {
      sim_grid_pos_x: 469928.031
      sim_grid_pos_y: 2108314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 470346.625
      sim_grid_pos_y: 2108529
    }
    terrain_level_point {
      sim_grid_pos_x: 473318.938
      sim_grid_pos_y: 2108151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474307.25
      sim_grid_pos_y: 2105142.5
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 469642.125
      sim_grid_pos_y: 2103227
    }
    terrain_level_point {
      sim_grid_pos_x: 466049.969
      sim_grid_pos_y: 2104226.75
    }
    terrain_level_point {
      sim_grid_pos_x: 466538.25
      sim_grid_pos_y: 2.1054e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 468057.656
      sim_grid_pos_y: 2106034.25
    }
    terrain_level_point {
      sim_grid_pos_x: 469409.75
      sim_grid_pos_y: 2104887.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 469765.375
      sim_grid_pos_y: 2103086.5
    }
    terrain_level_point {
      sim_grid_pos_x: 465910.75
      sim_grid_pos_y: 2104159
    }
    terrain_level_point {
      sim_grid_pos_x: 466459.812
      sim_grid_pos_y: 2105478.25
    }
    terrain_level_point {
      sim_grid_pos_x: 468076.094
      sim_grid_pos_y: 2106153.25
    }
    terrain_level_point {
      sim_grid_pos_x: 469505.875
      sim_grid_pos_y: 2104940.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 469888.594
      sim_grid_pos_y: 2102945.75
    }
    terrain_level_point {
      sim_grid_pos_x: 465771.531
      sim_grid_pos_y: 2104091.25
    }
    terrain_level_point {
      sim_grid_pos_x: 466381.344
      sim_grid_pos_y: 2105556.75
    }
    terrain_level_point {
      sim_grid_pos_x: 468094.531
      sim_grid_pos_y: 2106272
    }
    terrain_level_point {
      sim_grid_pos_x: 469601.969
      sim_grid_pos_y: 2104993.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 470011.812
      sim_grid_pos_y: 2102805
    }
    terrain_level_point {
      sim_grid_pos_x: 465632.312
      sim_grid_pos_y: 2104023.75
    }
    terrain_level_point {
      sim_grid_pos_x: 466302.906
      sim_grid_pos_y: 2105635
    }
    terrain_level_point {
      sim_grid_pos_x: 468112.969
      sim_grid_pos_y: 2106390.75
    }
    terrain_level_point {
      sim_grid_pos_x: 469698.094
      sim_grid_pos_y: 2105046.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 470135.031
      sim_grid_pos_y: 2102664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 465493.094
      sim_grid_pos_y: 2103956
    }
    terrain_level_point {
      sim_grid_pos_x: 466224.469
      sim_grid_pos_y: 2105713.5
    }
    terrain_level_point {
      sim_grid_pos_x: 468131.406
      sim_grid_pos_y: 2106509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 469794.219
      sim_grid_pos_y: 2105099
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 457752.594
      sim_grid_pos_y: 2117996.25
    }
    terrain_level_point {
      sim_grid_pos_x: 462209.344
      sim_grid_pos_y: 2119102
    }
    terrain_level_point {
      sim_grid_pos_x: 465686.938
      sim_grid_pos_y: 2120069.75
    }
    terrain_level_point {
      sim_grid_pos_x: 468712.219
      sim_grid_pos_y: 2120624.75
    }
    terrain_level_point {
      sim_grid_pos_x: 466795.188
      sim_grid_pos_y: 2118923.5
    }
    terrain_level_point {
      sim_grid_pos_x: 462517.75
      sim_grid_pos_y: 2117121.75
    }
    terrain_level_point {
      sim_grid_pos_x: 460421.844
      sim_grid_pos_y: 2117159.5
    }
    terrain_level_point {
      sim_grid_pos_x: 458268
      sim_grid_pos_y: 2116831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 457355.812
      sim_grid_pos_y: 2117207.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 458248.938
      sim_grid_pos_y: 2116673
    }
    terrain_level_point {
      sim_grid_pos_x: 457143.938
      sim_grid_pos_y: 2117128
    }
    terrain_level_point {
      sim_grid_pos_x: 457646.969
      sim_grid_pos_y: 2118128.5
    }
    terrain_level_point {
      sim_grid_pos_x: 462170.125
      sim_grid_pos_y: 2119250.75
    }
    terrain_level_point {
      sim_grid_pos_x: 465652.375
      sim_grid_pos_y: 2120219.75
    }
    terrain_level_point {
      sim_grid_pos_x: 468799.312
      sim_grid_pos_y: 2120797
    }
    terrain_level_point {
      sim_grid_pos_x: 468901.625
      sim_grid_pos_y: 2120587.25
    }
    terrain_level_point {
      sim_grid_pos_x: 466878.281
      sim_grid_pos_y: 2118791.75
    }
    terrain_level_point {
      sim_grid_pos_x: 462547.469
      sim_grid_pos_y: 2116967.25
    }
    terrain_level_point {
      sim_grid_pos_x: 460432.094
      sim_grid_pos_y: 2117005.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 458229.844
      sim_grid_pos_y: 2116514.5
    }
    terrain_level_point {
      sim_grid_pos_x: 456932.031
      sim_grid_pos_y: 2117049
    }
    terrain_level_point {
      sim_grid_pos_x: 457541.312
      sim_grid_pos_y: 2118260.75
    }
    terrain_level_point {
      sim_grid_pos_x: 462130.969
      sim_grid_pos_y: 2119399.5
    }
    terrain_level_point {
      sim_grid_pos_x: 465617.812
      sim_grid_pos_y: 2120369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 468886.375
      sim_grid_pos_y: 2120969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 469091
      sim_grid_pos_y: 2120549.75
    }
    terrain_level_point {
      sim_grid_pos_x: 466961.375
      sim_grid_pos_y: 2118659.75
    }
    terrain_level_point {
      sim_grid_pos_x: 462577.219
      sim_grid_pos_y: 2116813
    }
    terrain_level_point {
      sim_grid_pos_x: 460442.375
      sim_grid_pos_y: 2116851.5
    }
  }
}
