terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1883001.62
      sim_grid_pos_y: 1199593.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1883639.62
      sim_grid_pos_y: 1199353.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1884243.88
      sim_grid_pos_y: 1199319.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1884755.38
      sim_grid_pos_y: 1199238.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1885182.75
      sim_grid_pos_y: 1199143.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1885561.88
      sim_grid_pos_y: 1198928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1886084.62
      sim_grid_pos_y: 1198572.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1886445.75
      sim_grid_pos_y: 1198379.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1885865.38
      sim_grid_pos_y: 1197668.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1885498.75
      sim_grid_pos_y: 1197859
    }
    terrain_level_point {
      sim_grid_pos_x: 1885119
      sim_grid_pos_y: 1197986.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1884767.12
      sim_grid_pos_y: 1198013.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1883922.88
      sim_grid_pos_y: 1198028.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1883707.12
      sim_grid_pos_y: 1198067.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1883467.38
      sim_grid_pos_y: 1198160.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1883081.75
      sim_grid_pos_y: 1198388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1882173
      sim_grid_pos_y: 1199058.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1882082
      sim_grid_pos_y: 1199080.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1881716.62
      sim_grid_pos_y: 1199354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1880624.88
      sim_grid_pos_y: 1200185.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1880883.88
      sim_grid_pos_y: 1200480.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1881152
      sim_grid_pos_y: 1200608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1881384.38
      sim_grid_pos_y: 1200599.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1881653
      sim_grid_pos_y: 1200395.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1882114
      sim_grid_pos_y: 1199883
    }
    terrain_level_point {
      sim_grid_pos_x: 1882251.5
      sim_grid_pos_y: 1199741.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1882446
      sim_grid_pos_y: 1199666.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1885892.12
      sim_grid_pos_y: 1197539.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1885458.5
      sim_grid_pos_y: 1197764.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1885098.38
      sim_grid_pos_y: 1197885.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1884762.25
      sim_grid_pos_y: 1197911.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1883912.88
      sim_grid_pos_y: 1197925.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1883679.12
      sim_grid_pos_y: 1197968
    }
    terrain_level_point {
      sim_grid_pos_x: 1883422.38
      sim_grid_pos_y: 1198068.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1883025.12
      sim_grid_pos_y: 1198303.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1882128.88
      sim_grid_pos_y: 1198963.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1882037.5
      sim_grid_pos_y: 1198985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1881654.75
      sim_grid_pos_y: 1199273
    }
    terrain_level_point {
      sim_grid_pos_x: 1880475.25
      sim_grid_pos_y: 1200170.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1880820.75
      sim_grid_pos_y: 1200563.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1881130.5
      sim_grid_pos_y: 1200711.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1881420.62
      sim_grid_pos_y: 1200701
    }
    terrain_level_point {
      sim_grid_pos_x: 1881722.75
      sim_grid_pos_y: 1200471.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1882188.75
      sim_grid_pos_y: 1199953.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1882309.38
      sim_grid_pos_y: 1199829.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1882471.62
      sim_grid_pos_y: 1199766.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1883026.62
      sim_grid_pos_y: 1199693.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1883661
      sim_grid_pos_y: 1199455.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1884254.88
      sim_grid_pos_y: 1199421.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1884774.5
      sim_grid_pos_y: 1199339.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.88522e+06
      sim_grid_pos_y: 1199240.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1885616.12
      sim_grid_pos_y: 1199015.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1886137.75
      sim_grid_pos_y: 1198660.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1886604
      sim_grid_pos_y: 1198411.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1885929.5
      sim_grid_pos_y: 1197358
    }
    terrain_level_point {
      sim_grid_pos_x: 1885402.25
      sim_grid_pos_y: 1197631.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1885069.5
      sim_grid_pos_y: 1197743.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1884755.62
      sim_grid_pos_y: 1197768
    }
    terrain_level_point {
      sim_grid_pos_x: 1883898.75
      sim_grid_pos_y: 1197782.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1883639.88
      sim_grid_pos_y: 1197829.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1883359.38
      sim_grid_pos_y: 1197938.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1882945.75
      sim_grid_pos_y: 1198183.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1882067.38
      sim_grid_pos_y: 1198831
    }
    terrain_level_point {
      sim_grid_pos_x: 1881975.25
      sim_grid_pos_y: 1198853
    }
    terrain_level_point {
      sim_grid_pos_x: 1881568.38
      sim_grid_pos_y: 1199158.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1880265.62
      sim_grid_pos_y: 1200149.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1880732.38
      sim_grid_pos_y: 1200680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1881100.5
      sim_grid_pos_y: 1200856.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1881471.38
      sim_grid_pos_y: 1200842.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1881820.38
      sim_grid_pos_y: 1200577.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1882293.88
      sim_grid_pos_y: 1200051
    }
    terrain_level_point {
      sim_grid_pos_x: 1882390.38
      sim_grid_pos_y: 1199951.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1882507.5
      sim_grid_pos_y: 1199906.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1883061.62
      sim_grid_pos_y: 1199833.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1883691
      sim_grid_pos_y: 1199597.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1884270.12
      sim_grid_pos_y: 1199564.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1884801.25
      sim_grid_pos_y: 1199480.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1885272.12
      sim_grid_pos_y: 1199376.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1885692.12
      sim_grid_pos_y: 1199137.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1886212.12
      sim_grid_pos_y: 1198783.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1886825.5
      sim_grid_pos_y: 1198455.62
    }
  }
}
