terrain_level_data {
  terrain_level: 75
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1854492.12
      sim_grid_pos_y: 1164695
    }
    terrain_level_point {
      sim_grid_pos_x: 1855409.25
      sim_grid_pos_y: 1166394
    }
    terrain_level_point {
      sim_grid_pos_x: 1855986
      sim_grid_pos_y: 1166775
    }
    terrain_level_point {
      sim_grid_pos_x: 1856456
      sim_grid_pos_y: 1167277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1857298.38
      sim_grid_pos_y: 1166568.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1857014.75
      sim_grid_pos_y: 1165811.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1856712.12
      sim_grid_pos_y: 1165202.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1856377.62
      sim_grid_pos_y: 1164431.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1856008.38
      sim_grid_pos_y: 1163804.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1856019.25
      sim_grid_pos_y: 1163762.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1854450.88
      sim_grid_pos_y: 1164683.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1855385.88
      sim_grid_pos_y: 1166415.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1855966
      sim_grid_pos_y: 1166798.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1856453.38
      sim_grid_pos_y: 1167319.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857334.88
      sim_grid_pos_y: 1166578
    }
    terrain_level_point {
      sim_grid_pos_x: 1857043
      sim_grid_pos_y: 1165799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1856740.12
      sim_grid_pos_y: 1165189.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1856405
      sim_grid_pos_y: 1164417.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1856030.12
      sim_grid_pos_y: 1163720.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1854409.75
      sim_grid_pos_y: 1164672
    }
    terrain_level_point {
      sim_grid_pos_x: 1855362.5
      sim_grid_pos_y: 1166436.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1855946
      sim_grid_pos_y: 1166822.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1856450.88
      sim_grid_pos_y: 1167362
    }
    terrain_level_point {
      sim_grid_pos_x: 1857371.25
      sim_grid_pos_y: 1166587.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1857071.25
      sim_grid_pos_y: 1165787.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1856768
      sim_grid_pos_y: 1165176.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1856432.5
      sim_grid_pos_y: 1164403.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1856041.12
      sim_grid_pos_y: 1163678.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1854368.62
      sim_grid_pos_y: 1164660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1855339.12
      sim_grid_pos_y: 1166458.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1855926
      sim_grid_pos_y: 1166846
    }
    terrain_level_point {
      sim_grid_pos_x: 1856448.38
      sim_grid_pos_y: 1167404.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1857407.75
      sim_grid_pos_y: 1166597.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1857099.5
      sim_grid_pos_y: 1165774.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1856795.88
      sim_grid_pos_y: 1165163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.85646e+06
      sim_grid_pos_y: 1164389.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1856052
      sim_grid_pos_y: 1163636.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1854327.5
      sim_grid_pos_y: 1164649
    }
    terrain_level_point {
      sim_grid_pos_x: 1855315.75
      sim_grid_pos_y: 1166479.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1855906
      sim_grid_pos_y: 1166869.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1856445.88
      sim_grid_pos_y: 1167446.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1857444.12
      sim_grid_pos_y: 1166606.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857127.75
      sim_grid_pos_y: 1165762.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1856823.75
      sim_grid_pos_y: 1165150.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1856487.5
      sim_grid_pos_y: 1164375.5
    }
  }
}
