terrain_level_data {
  terrain_level: 1005
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1738803.25
      sim_grid_pos_y: 1406386
    }
    terrain_level_point {
      sim_grid_pos_x: 1738871.5
      sim_grid_pos_y: 1406478.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73902e+06
      sim_grid_pos_y: 1406565.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1739118.12
      sim_grid_pos_y: 1406519.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1739212.62
      sim_grid_pos_y: 1406383.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1739154.38
      sim_grid_pos_y: 1406195.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1739003.12
      sim_grid_pos_y: 1406115.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738835
      sim_grid_pos_y: 1406195.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1739004.25
      sim_grid_pos_y: 1406058.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738788.88
      sim_grid_pos_y: 1406160.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1738749
      sim_grid_pos_y: 1406399
    }
    terrain_level_point {
      sim_grid_pos_x: 1738836.5
      sim_grid_pos_y: 1406517
    }
    terrain_level_point {
      sim_grid_pos_x: 1739017.25
      sim_grid_pos_y: 1406623.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1739152.38
      sim_grid_pos_y: 1406560.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1739269
      sim_grid_pos_y: 1406391.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1739197
      sim_grid_pos_y: 1406160.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1739005.5
      sim_grid_pos_y: 1406000.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738742.75
      sim_grid_pos_y: 1406125.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738694.88
      sim_grid_pos_y: 1406412
    }
    terrain_level_point {
      sim_grid_pos_x: 1738801.5
      sim_grid_pos_y: 1406556
    }
    terrain_level_point {
      sim_grid_pos_x: 1739014.62
      sim_grid_pos_y: 1406681.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1739186.62
      sim_grid_pos_y: 1406600.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1739325.38
      sim_grid_pos_y: 1406400.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1739239.75
      sim_grid_pos_y: 1406124.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1739006.75
      sim_grid_pos_y: 1405943.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738696.62
      sim_grid_pos_y: 1406091
    }
    terrain_level_point {
      sim_grid_pos_x: 1738640.75
      sim_grid_pos_y: 1406425
    }
    terrain_level_point {
      sim_grid_pos_x: 1738766.5
      sim_grid_pos_y: 1406594.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1739011.88
      sim_grid_pos_y: 1406739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1739220.88
      sim_grid_pos_y: 1406641.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1739381.75
      sim_grid_pos_y: 1406409.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1739282.38
      sim_grid_pos_y: 1406089.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1739008
      sim_grid_pos_y: 1405886.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738650.38
      sim_grid_pos_y: 1406056.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1738586.62
      sim_grid_pos_y: 1406438
    }
    terrain_level_point {
      sim_grid_pos_x: 1738731.5
      sim_grid_pos_y: 1406633.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1739009.12
      sim_grid_pos_y: 1406797.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1739255.12
      sim_grid_pos_y: 1406681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1739438.12
      sim_grid_pos_y: 1406417.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1739325.12
      sim_grid_pos_y: 1406054
    }
  }
}
terrain_level_data {
  terrain_level: 895
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1738563.12
      sim_grid_pos_y: 1406715.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738664.62
      sim_grid_pos_y: 1406899.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1738492.5
      sim_grid_pos_y: 1407055.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738458.62
      sim_grid_pos_y: 1407317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738272.88
      sim_grid_pos_y: 1407186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738297.5
      sim_grid_pos_y: 1406683
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1738595.38
      sim_grid_pos_y: 1406667.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1738729
      sim_grid_pos_y: 1406910.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1738541
      sim_grid_pos_y: 1407081
    }
    terrain_level_point {
      sim_grid_pos_x: 1738498.5
      sim_grid_pos_y: 1407408.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738220.25
      sim_grid_pos_y: 1407211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738249
      sim_grid_pos_y: 1406625.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1738627.62
      sim_grid_pos_y: 1406619.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738793.5
      sim_grid_pos_y: 1406920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1738589.38
      sim_grid_pos_y: 1407106.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1738538.38
      sim_grid_pos_y: 1407499.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738167.75
      sim_grid_pos_y: 1407237.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1738200.5
      sim_grid_pos_y: 1406567.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1738659.75
      sim_grid_pos_y: 1406572.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1738857.88
      sim_grid_pos_y: 1406931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738637.75
      sim_grid_pos_y: 1407131.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1738578.25
      sim_grid_pos_y: 1407591
    }
    terrain_level_point {
      sim_grid_pos_x: 1738115.12
      sim_grid_pos_y: 1407262.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1738151.88
      sim_grid_pos_y: 1406510.38
    }
  }
}
