terrain_level_data {
  terrain_level: 403
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1540239.25
      sim_grid_pos_y: 1733227.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1540686
      sim_grid_pos_y: 1733373.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1541192.38
      sim_grid_pos_y: 1733526.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1541501
      sim_grid_pos_y: 1733567.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1541973.5
      sim_grid_pos_y: 1733539
    }
    terrain_level_point {
      sim_grid_pos_x: 1543110.88
      sim_grid_pos_y: 1733278
    }
    terrain_level_point {
      sim_grid_pos_x: 1543492.62
      sim_grid_pos_y: 1733022.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1543462.5
      sim_grid_pos_y: 1732969.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1541186.12
      sim_grid_pos_y: 1732474
    }
    terrain_level_point {
      sim_grid_pos_x: 1540893.38
      sim_grid_pos_y: 1732595.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1540612.88
      sim_grid_pos_y: 1732587.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1541183.25
      sim_grid_pos_y: 1732441.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1540887.62
      sim_grid_pos_y: 1732564.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1540595.5
      sim_grid_pos_y: 1732556.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1540193.5
      sim_grid_pos_y: 1733244.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1540676.75
      sim_grid_pos_y: 1733402.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1541185.88
      sim_grid_pos_y: 1733556.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1541499.88
      sim_grid_pos_y: 1733598.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1541977.88
      sim_grid_pos_y: 1733569.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1543123.25
      sim_grid_pos_y: 1733306.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1543533.62
      sim_grid_pos_y: 1733031.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1543482.38
      sim_grid_pos_y: 1732942.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1541180.38
      sim_grid_pos_y: 1732409.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1540882
      sim_grid_pos_y: 1732534
    }
    terrain_level_point {
      sim_grid_pos_x: 1540578.12
      sim_grid_pos_y: 1732524.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1540147.62
      sim_grid_pos_y: 1733262.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1540667.5
      sim_grid_pos_y: 1733431.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1541179.25
      sim_grid_pos_y: 1733587
    }
    terrain_level_point {
      sim_grid_pos_x: 1541498.75
      sim_grid_pos_y: 1733629.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1541982.38
      sim_grid_pos_y: 1733600.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1543135.75
      sim_grid_pos_y: 1733335.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1543574.5
      sim_grid_pos_y: 1733041.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1543502.25
      sim_grid_pos_y: 1732915.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1541177.38
      sim_grid_pos_y: 1732377.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1540876.25
      sim_grid_pos_y: 1732503
    }
    terrain_level_point {
      sim_grid_pos_x: 1540560.88
      sim_grid_pos_y: 1732493.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1540101.88
      sim_grid_pos_y: 1733279.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1540658.25
      sim_grid_pos_y: 1733461.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1541172.75
      sim_grid_pos_y: 1733617.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1541497.62
      sim_grid_pos_y: 1733660.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1541986.75
      sim_grid_pos_y: 1733630.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1543148.12
      sim_grid_pos_y: 1733364.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1543615.5
      sim_grid_pos_y: 1733051
    }
    terrain_level_point {
      sim_grid_pos_x: 1543522.12
      sim_grid_pos_y: 1732888.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1541174.5
      sim_grid_pos_y: 1732345.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1540870.62
      sim_grid_pos_y: 1732472.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1540543.5
      sim_grid_pos_y: 1732462.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1540056.12
      sim_grid_pos_y: 1733297.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1540649.12
      sim_grid_pos_y: 1733490.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1541166.25
      sim_grid_pos_y: 1733647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1541496.62
      sim_grid_pos_y: 1733691.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1541991.12
      sim_grid_pos_y: 1733661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1543160.5
      sim_grid_pos_y: 1733392.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1543656.5
      sim_grid_pos_y: 1733060.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1543542
      sim_grid_pos_y: 1732861.12
    }
  }
}
