terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3126504.5
      sim_grid_pos_y: 2528534.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3.13149e+06
      sim_grid_pos_y: 2527672.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3131088.75
      sim_grid_pos_y: 2528518.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3129947.25
      sim_grid_pos_y: 2529955.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3126727.25
      sim_grid_pos_y: 2531186
    }
    terrain_level_point {
      sim_grid_pos_x: 3.12648e+06
      sim_grid_pos_y: 2531179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3126314.5
      sim_grid_pos_y: 2531131
    }
    terrain_level_point {
      sim_grid_pos_x: 3126027
      sim_grid_pos_y: 2530926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3125389.75
      sim_grid_pos_y: 2531592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3125150.5
      sim_grid_pos_y: 2531907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3124838.5
      sim_grid_pos_y: 2532077.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3124537
      sim_grid_pos_y: 2532168.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3124297.25
      sim_grid_pos_y: 2532174.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123901
      sim_grid_pos_y: 2531778.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3.12336e+06
      sim_grid_pos_y: 2530911.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123163.5
      sim_grid_pos_y: 2530624.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3121316.25
      sim_grid_pos_y: 2529873.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3121785.25
      sim_grid_pos_y: 2529373
    }
    terrain_level_point {
      sim_grid_pos_x: 3121975.75
      sim_grid_pos_y: 2529292.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3122441.25
      sim_grid_pos_y: 2528694
    }
    terrain_level_point {
      sim_grid_pos_x: 3122992.75
      sim_grid_pos_y: 2528886.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3123464.75
      sim_grid_pos_y: 2528995
    }
    terrain_level_point {
      sim_grid_pos_x: 3123782
      sim_grid_pos_y: 2529000.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3126074.5
      sim_grid_pos_y: 2528627.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 3131525.75
      sim_grid_pos_y: 2527668.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3131115
      sim_grid_pos_y: 2528534.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3129966
      sim_grid_pos_y: 2529981.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3126732.5
      sim_grid_pos_y: 2531217
    }
    terrain_level_point {
      sim_grid_pos_x: 3126475.25
      sim_grid_pos_y: 2531210.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3126300.75
      sim_grid_pos_y: 2531159
    }
    terrain_level_point {
      sim_grid_pos_x: 3126030.75
      sim_grid_pos_y: 2530967
    }
    terrain_level_point {
      sim_grid_pos_x: 3125413.25
      sim_grid_pos_y: 2531612.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3125171
      sim_grid_pos_y: 2531931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3124850.25
      sim_grid_pos_y: 2532105.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3124542
      sim_grid_pos_y: 2532199.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3124284.75
      sim_grid_pos_y: 2532205.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123876.75
      sim_grid_pos_y: 2531798
    }
    terrain_level_point {
      sim_grid_pos_x: 3123334
      sim_grid_pos_y: 2530928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3123143.25
      sim_grid_pos_y: 2530649.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3121263.25
      sim_grid_pos_y: 2529885.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3121767.25
      sim_grid_pos_y: 2529347.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3121956.25
      sim_grid_pos_y: 2529267.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3122430.5
      sim_grid_pos_y: 2528657.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123001.25
      sim_grid_pos_y: 2528857
    }
    terrain_level_point {
      sim_grid_pos_x: 3123468.5
      sim_grid_pos_y: 2528964.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3123779.75
      sim_grid_pos_y: 2528969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3126068.75
      sim_grid_pos_y: 2528597
    }
    terrain_level_point {
      sim_grid_pos_x: 3126498.75
      sim_grid_pos_y: 2528504.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3131503.25
      sim_grid_pos_y: 2527638.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 3131561.5
      sim_grid_pos_y: 2527664.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3131141.5
      sim_grid_pos_y: 2528551.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3129984.75
      sim_grid_pos_y: 2530007
    }
    terrain_level_point {
      sim_grid_pos_x: 3126737.75
      sim_grid_pos_y: 2531247.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3126470.5
      sim_grid_pos_y: 2531240.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3126287.25
      sim_grid_pos_y: 2531187
    }
    terrain_level_point {
      sim_grid_pos_x: 3126034.5
      sim_grid_pos_y: 2531007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3125436.75
      sim_grid_pos_y: 2531632.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3125191.5
      sim_grid_pos_y: 2531955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3124862.25
      sim_grid_pos_y: 2532134.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3124547
      sim_grid_pos_y: 2.53223e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 3124272.5
      sim_grid_pos_y: 2532236.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123852.5
      sim_grid_pos_y: 2531817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3123308.5
      sim_grid_pos_y: 2530945.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3123123.25
      sim_grid_pos_y: 2530674.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3121210.25
      sim_grid_pos_y: 2529897
    }
    terrain_level_point {
      sim_grid_pos_x: 3121749.25
      sim_grid_pos_y: 2529321.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3121937
      sim_grid_pos_y: 2529242
    }
    terrain_level_point {
      sim_grid_pos_x: 3122419.75
      sim_grid_pos_y: 2528621.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3.12301e+06
      sim_grid_pos_y: 2528827.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3123472.25
      sim_grid_pos_y: 2528933.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3123777.5
      sim_grid_pos_y: 2528938.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3126063
      sim_grid_pos_y: 2528566.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3126492.75
      sim_grid_pos_y: 2528474.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3131516.25
      sim_grid_pos_y: 2527605.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 3131597.5
      sim_grid_pos_y: 2527661
    }
    terrain_level_point {
      sim_grid_pos_x: 3131167.75
      sim_grid_pos_y: 2528567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3130003.75
      sim_grid_pos_y: 2530032.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3126743.25
      sim_grid_pos_y: 2531278.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3126465.75
      sim_grid_pos_y: 2531271.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3126273.5
      sim_grid_pos_y: 2531215
    }
    terrain_level_point {
      sim_grid_pos_x: 3126038.5
      sim_grid_pos_y: 2531048
    }
    terrain_level_point {
      sim_grid_pos_x: 3.12546e+06
      sim_grid_pos_y: 2531652.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3125212
      sim_grid_pos_y: 2531979
    }
    terrain_level_point {
      sim_grid_pos_x: 3124874.25
      sim_grid_pos_y: 2532162.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3124552
      sim_grid_pos_y: 2532260.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3.12426e+06
      sim_grid_pos_y: 2532267.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123828.25
      sim_grid_pos_y: 2531836.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3123282.75
      sim_grid_pos_y: 2530962.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3123103
      sim_grid_pos_y: 2530699.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3121157
      sim_grid_pos_y: 2529908.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3121731.5
      sim_grid_pos_y: 2529295.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3121917.5
      sim_grid_pos_y: 2529216.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3122409.25
      sim_grid_pos_y: 2528585
    }
    terrain_level_point {
      sim_grid_pos_x: 3123018.5
      sim_grid_pos_y: 2528797.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3123476
      sim_grid_pos_y: 2528903
    }
    terrain_level_point {
      sim_grid_pos_x: 3123775.25
      sim_grid_pos_y: 2528908
    }
    terrain_level_point {
      sim_grid_pos_x: 3126057.25
      sim_grid_pos_y: 2528536.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3126487
      sim_grid_pos_y: 2528444.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3131529.5
      sim_grid_pos_y: 2527571.75
    }
  }
}
