terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 715160.938
      sim_grid_pos_y: 1556650.88
    }
    terrain_level_point {
      sim_grid_pos_x: 717162.188
      sim_grid_pos_y: 1558046
    }
    terrain_level_point {
      sim_grid_pos_x: 715661.75
      sim_grid_pos_y: 1560799.38
    }
    terrain_level_point {
      sim_grid_pos_x: 713334.875
      sim_grid_pos_y: 1559195.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 717202.375
      sim_grid_pos_y: 1558036.62
    }
    terrain_level_point {
      sim_grid_pos_x: 715672.438
      sim_grid_pos_y: 1560844
    }
    terrain_level_point {
      sim_grid_pos_x: 713291.625
      sim_grid_pos_y: 1559202.75
    }
    terrain_level_point {
      sim_grid_pos_x: 715153.625
      sim_grid_pos_y: 1556608.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 717242.562
      sim_grid_pos_y: 1558027.12
    }
    terrain_level_point {
      sim_grid_pos_x: 715683.062
      sim_grid_pos_y: 1560888.75
    }
    terrain_level_point {
      sim_grid_pos_x: 713248.375
      sim_grid_pos_y: 1559210.25
    }
    terrain_level_point {
      sim_grid_pos_x: 715146.375
      sim_grid_pos_y: 1556565.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 717282.812
      sim_grid_pos_y: 1558017.62
    }
    terrain_level_point {
      sim_grid_pos_x: 715693.75
      sim_grid_pos_y: 1560933.5
    }
    terrain_level_point {
      sim_grid_pos_x: 713205.062
      sim_grid_pos_y: 1559217.75
    }
    terrain_level_point {
      sim_grid_pos_x: 715139.062
      sim_grid_pos_y: 1556523.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 717323
      sim_grid_pos_y: 1558008.12
    }
    terrain_level_point {
      sim_grid_pos_x: 715704.375
      sim_grid_pos_y: 1560978.12
    }
    terrain_level_point {
      sim_grid_pos_x: 713161.812
      sim_grid_pos_y: 1559225.25
    }
    terrain_level_point {
      sim_grid_pos_x: 715131.75
      sim_grid_pos_y: 1556480.5
    }
  }
}
