terrain_level_data {
  terrain_level: 85
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2.06808e+06
      sim_grid_pos_y: 129357.133
    }
    terrain_level_point {
      sim_grid_pos_x: 2071355.75
      sim_grid_pos_y: 130141.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2078450.62
      sim_grid_pos_y: 132666.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2078471.62
      sim_grid_pos_y: 136394.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2074571.62
      sim_grid_pos_y: 135547.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2072356.12
      sim_grid_pos_y: 134663.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2071605.62
      sim_grid_pos_y: 133761.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2071141.5
      sim_grid_pos_y: 133689.641
    }
    terrain_level_point {
      sim_grid_pos_x: 2069424.38
      sim_grid_pos_y: 134878.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2068792.5
      sim_grid_pos_y: 134378.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2068552.12
      sim_grid_pos_y: 133880.234
    }
    terrain_level_point {
      sim_grid_pos_x: 2.06767e+06
      sim_grid_pos_y: 133658.922
    }
    terrain_level_point {
      sim_grid_pos_x: 2067275.62
      sim_grid_pos_y: 132443.672
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2071370.25
      sim_grid_pos_y: 130092.43
    }
    terrain_level_point {
      sim_grid_pos_x: 2078501.75
      sim_grid_pos_y: 132629.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2078523.25
      sim_grid_pos_y: 136458.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2074556.62
      sim_grid_pos_y: 135596.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2072325.12
      sim_grid_pos_y: 134705.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2071578.62
      sim_grid_pos_y: 133809.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2071153.88
      sim_grid_pos_y: 133743.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2069422.38
      sim_grid_pos_y: 134942.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2068751.38
      sim_grid_pos_y: 134411.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2068516.5
      sim_grid_pos_y: 133924.109
    }
    terrain_level_point {
      sim_grid_pos_x: 2.06763e+06
      sim_grid_pos_y: 133701.734
    }
    terrain_level_point {
      sim_grid_pos_x: 2067222.25
      sim_grid_pos_y: 132445.234
    }
    terrain_level_point {
      sim_grid_pos_x: 2068043.12
      sim_grid_pos_y: 129295.57
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2071384.88
      sim_grid_pos_y: 130043.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2078552.75
      sim_grid_pos_y: 132593.578
    }
    terrain_level_point {
      sim_grid_pos_x: 2078574.88
      sim_grid_pos_y: 136522.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2074541.5
      sim_grid_pos_y: 135645.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2072294
      sim_grid_pos_y: 134748.609
    }
    terrain_level_point {
      sim_grid_pos_x: 2071551.62
      sim_grid_pos_y: 133856.766
    }
    terrain_level_point {
      sim_grid_pos_x: 2071166.25
      sim_grid_pos_y: 133797.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2069420.38
      sim_grid_pos_y: 135006.484
    }
    terrain_level_point {
      sim_grid_pos_x: 2068710.38
      sim_grid_pos_y: 134444.016
    }
    terrain_level_point {
      sim_grid_pos_x: 2068480.75
      sim_grid_pos_y: 133968
    }
    terrain_level_point {
      sim_grid_pos_x: 2.06759e+06
      sim_grid_pos_y: 133744.547
    }
    terrain_level_point {
      sim_grid_pos_x: 2067168.88
      sim_grid_pos_y: 132446.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2068006.12
      sim_grid_pos_y: 129234.008
    }
  }
}
