terrain_level_data {
  terrain_level: 240
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1605020.12
      sim_grid_pos_y: 1377785.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605043.38
      sim_grid_pos_y: 1377973.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1605373.5
      sim_grid_pos_y: 1377845.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605677.38
      sim_grid_pos_y: 1377730.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1606034.38
      sim_grid_pos_y: 1377764.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1606148.5
      sim_grid_pos_y: 1377575.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605953.5
      sim_grid_pos_y: 1377364.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605686.12
      sim_grid_pos_y: 1377352.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605493.75
      sim_grid_pos_y: 1377369.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605303.75
      sim_grid_pos_y: 1377449
    }
    terrain_level_point {
      sim_grid_pos_x: 1605244
      sim_grid_pos_y: 1377646.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1605684.88
      sim_grid_pos_y: 1377301.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1605481.25
      sim_grid_pos_y: 1377319.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1605261.75
      sim_grid_pos_y: 1377411
    }
    terrain_level_point {
      sim_grid_pos_x: 1605200.5
      sim_grid_pos_y: 1377613.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1604965.12
      sim_grid_pos_y: 1377759.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1605000.75
      sim_grid_pos_y: 1378044.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1605391.5
      sim_grid_pos_y: 1377893.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605684.38
      sim_grid_pos_y: 1377783
    }
    terrain_level_point {
      sim_grid_pos_x: 1606061.62
      sim_grid_pos_y: 1377818.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1606212.25
      sim_grid_pos_y: 1377569.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605976.88
      sim_grid_pos_y: 1377314.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1605683.75
      sim_grid_pos_y: 1377249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1605468.88
      sim_grid_pos_y: 1377269.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1605219.62
      sim_grid_pos_y: 1377372.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605157
      sim_grid_pos_y: 1377580.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1604910.25
      sim_grid_pos_y: 1377733.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1604958
      sim_grid_pos_y: 1378116.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1605409.62
      sim_grid_pos_y: 1377941.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605691.38
      sim_grid_pos_y: 1377835.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1606088.88
      sim_grid_pos_y: 1377872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1606276.12
      sim_grid_pos_y: 1377563
    }
    terrain_level_point {
      sim_grid_pos_x: 1606000.25
      sim_grid_pos_y: 1377263.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1605682.5
      sim_grid_pos_y: 1377198.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1605456.38
      sim_grid_pos_y: 1377218.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605177.62
      sim_grid_pos_y: 1377334.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605113.62
      sim_grid_pos_y: 1377546.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604855.25
      sim_grid_pos_y: 1377707.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1604915.25
      sim_grid_pos_y: 1378187.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1605428.12
      sim_grid_pos_y: 1377989.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1605698.38
      sim_grid_pos_y: 1377887.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1606116.12
      sim_grid_pos_y: 1377926.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.60634e+06
      sim_grid_pos_y: 1377556.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1606023.62
      sim_grid_pos_y: 1377213.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1605681.38
      sim_grid_pos_y: 1377147
    }
    terrain_level_point {
      sim_grid_pos_x: 1605443.88
      sim_grid_pos_y: 1377168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1605135.5
      sim_grid_pos_y: 1377296.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1605070.12
      sim_grid_pos_y: 1377513.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1604800.38
      sim_grid_pos_y: 1377681
    }
    terrain_level_point {
      sim_grid_pos_x: 1604872.5
      sim_grid_pos_y: 1378259.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1605447.25
      sim_grid_pos_y: 1378036.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1605705.38
      sim_grid_pos_y: 1377939.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1606143.25
      sim_grid_pos_y: 1377980.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1606403.75
      sim_grid_pos_y: 1377550.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1606047
      sim_grid_pos_y: 1377163.25
    }
  }
}
terrain_level_data {
  terrain_level: 240
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1604815.25
      sim_grid_pos_y: 1377690.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1604914.12
      sim_grid_pos_y: 1377819.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1604864.75
      sim_grid_pos_y: 1377952.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604766.88
      sim_grid_pos_y: 1378061.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1604599
      sim_grid_pos_y: 1378058.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1604462.5
      sim_grid_pos_y: 1377880.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1604548.88
      sim_grid_pos_y: 1377695.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1604685
      sim_grid_pos_y: 1377635.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1604847.62
      sim_grid_pos_y: 1377648.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1604972
      sim_grid_pos_y: 1377810.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1604909.5
      sim_grid_pos_y: 1377979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604789.38
      sim_grid_pos_y: 1378112.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604573.38
      sim_grid_pos_y: 1378109.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604402.88
      sim_grid_pos_y: 1377887.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1604510.5
      sim_grid_pos_y: 1377656.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1604684.62
      sim_grid_pos_y: 1.37758e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1604880.12
      sim_grid_pos_y: 1377606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1605029.88
      sim_grid_pos_y: 1377801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604954.12
      sim_grid_pos_y: 1378006.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604811.88
      sim_grid_pos_y: 1378164.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1604547.75
      sim_grid_pos_y: 1378160.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1604343.25
      sim_grid_pos_y: 1377893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1604472.25
      sim_grid_pos_y: 1377616.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1604684.12
      sim_grid_pos_y: 1377524.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1604912.5
      sim_grid_pos_y: 1377564.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1605087.75
      sim_grid_pos_y: 1377793
    }
    terrain_level_point {
      sim_grid_pos_x: 1604998.75
      sim_grid_pos_y: 1378033.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604834.38
      sim_grid_pos_y: 1378216
    }
    terrain_level_point {
      sim_grid_pos_x: 1604522.25
      sim_grid_pos_y: 1378211.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1604283.75
      sim_grid_pos_y: 1.3779e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1604434
      sim_grid_pos_y: 1377577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1604683.75
      sim_grid_pos_y: 1377468.5
    }
  }
}
