terrain_level_data {
  terrain_level: 230
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3004581.75
      sim_grid_pos_y: 240457.281
    }
    terrain_level_point {
      sim_grid_pos_x: 3003698
      sim_grid_pos_y: 240971.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3003587.5
      sim_grid_pos_y: 241723.266
    }
    terrain_level_point {
      sim_grid_pos_x: 3004486.25
      sim_grid_pos_y: 241913.812
    }
    terrain_level_point {
      sim_grid_pos_x: 3004929
      sim_grid_pos_y: 241375.141
    }
    terrain_level_point {
      sim_grid_pos_x: 3005122.25
      sim_grid_pos_y: 240721.328
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 3004575.25
      sim_grid_pos_y: 240283.031
    }
    terrain_level_point {
      sim_grid_pos_x: 3003556.75
      sim_grid_pos_y: 240875.844
    }
    terrain_level_point {
      sim_grid_pos_x: 3003414.25
      sim_grid_pos_y: 241843.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3004545.75
      sim_grid_pos_y: 242083.641
    }
    terrain_level_point {
      sim_grid_pos_x: 3005067.75
      sim_grid_pos_y: 241448.672
    }
    terrain_level_point {
      sim_grid_pos_x: 3005306.5
      sim_grid_pos_y: 240640.219
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 3004569
      sim_grid_pos_y: 240108.781
    }
    terrain_level_point {
      sim_grid_pos_x: 3003415.25
      sim_grid_pos_y: 240780.172
    }
    terrain_level_point {
      sim_grid_pos_x: 3003241.25
      sim_grid_pos_y: 241964.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3004605.25
      sim_grid_pos_y: 242253.453
    }
    terrain_level_point {
      sim_grid_pos_x: 3005206.25
      sim_grid_pos_y: 241522.203
    }
    terrain_level_point {
      sim_grid_pos_x: 3005491
      sim_grid_pos_y: 240559.094
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 3004562.5
      sim_grid_pos_y: 239934.531
    }
    terrain_level_point {
      sim_grid_pos_x: 3003274
      sim_grid_pos_y: 240684.516
    }
    terrain_level_point {
      sim_grid_pos_x: 3003068
      sim_grid_pos_y: 242084.734
    }
    terrain_level_point {
      sim_grid_pos_x: 3004664.75
      sim_grid_pos_y: 242423.281
    }
    terrain_level_point {
      sim_grid_pos_x: 3005345
      sim_grid_pos_y: 241595.734
    }
    terrain_level_point {
      sim_grid_pos_x: 3005675.25
      sim_grid_pos_y: 240477.984
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 3004556.25
      sim_grid_pos_y: 239760.281
    }
    terrain_level_point {
      sim_grid_pos_x: 3003132.5
      sim_grid_pos_y: 240588.859
    }
    terrain_level_point {
      sim_grid_pos_x: 3002894.75
      sim_grid_pos_y: 242205.234
    }
    terrain_level_point {
      sim_grid_pos_x: 3004724.25
      sim_grid_pos_y: 242593.094
    }
    terrain_level_point {
      sim_grid_pos_x: 3005483.5
      sim_grid_pos_y: 241669.266
    }
    terrain_level_point {
      sim_grid_pos_x: 3005859.5
      sim_grid_pos_y: 240396.875
    }
  }
}
