terrain_level_data {
  terrain_level: 774
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2576469.25
      sim_grid_pos_y: 466155.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2576309.5
      sim_grid_pos_y: 466363.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2576321.5
      sim_grid_pos_y: 466777.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2576605.5
      sim_grid_pos_y: 466990.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2576937.25
      sim_grid_pos_y: 466864.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2577092.25
      sim_grid_pos_y: 466544.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2576988
      sim_grid_pos_y: 466175.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2576811
      sim_grid_pos_y: 465958.844
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2576818.25
      sim_grid_pos_y: 465919.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2576448.5
      sim_grid_pos_y: 466131.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2576278.25
      sim_grid_pos_y: 466353.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2576291.25
      sim_grid_pos_y: 466792.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2576600.75
      sim_grid_pos_y: 467025.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2576959.75
      sim_grid_pos_y: 466888.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2577125
      sim_grid_pos_y: 466547.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2577016
      sim_grid_pos_y: 466160.938
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2576825.5
      sim_grid_pos_y: 465879.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2576428
      sim_grid_pos_y: 466108.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2576247.25
      sim_grid_pos_y: 466343.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2576260.75
      sim_grid_pos_y: 466808.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2576595.75
      sim_grid_pos_y: 467060.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2576982
      sim_grid_pos_y: 466912.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2577157.75
      sim_grid_pos_y: 466550.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2577043.75
      sim_grid_pos_y: 466146.406
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2576832.75
      sim_grid_pos_y: 465839.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2576407.25
      sim_grid_pos_y: 466084.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2576216.25
      sim_grid_pos_y: 466333.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2576230.5
      sim_grid_pos_y: 466824.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2576591
      sim_grid_pos_y: 467095.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2577004.5
      sim_grid_pos_y: 466937.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2577190.5
      sim_grid_pos_y: 466553.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2577071.75
      sim_grid_pos_y: 466131.906
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2.57684e+06
      sim_grid_pos_y: 465800.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2576386.5
      sim_grid_pos_y: 466061
    }
    terrain_level_point {
      sim_grid_pos_x: 2576185.25
      sim_grid_pos_y: 466323.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2576200.25
      sim_grid_pos_y: 466839.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2576586
      sim_grid_pos_y: 467129.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2577026.75
      sim_grid_pos_y: 466961.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2577223.5
      sim_grid_pos_y: 466556.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2577099.5
      sim_grid_pos_y: 466117.375
    }
  }
}
