terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1308510.5
      sim_grid_pos_y: 1461555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1308414
      sim_grid_pos_y: 1461397.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308373.62
      sim_grid_pos_y: 1460986.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308115.5
      sim_grid_pos_y: 1460572.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1307563.12
      sim_grid_pos_y: 1460130.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1307268.62
      sim_grid_pos_y: 1460298.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1306591.38
      sim_grid_pos_y: 1460521.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1305923.25
      sim_grid_pos_y: 1460884.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1305319.88
      sim_grid_pos_y: 1461544.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1305642.75
      sim_grid_pos_y: 1461845.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1307850.88
      sim_grid_pos_y: 1462785.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308369.88
      sim_grid_pos_y: 1462378.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1309028.75
      sim_grid_pos_y: 1462052.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.30864e+06
      sim_grid_pos_y: 1461647.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1307576.62
      sim_grid_pos_y: 1459957.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1307209.88
      sim_grid_pos_y: 1460167
    }
    terrain_level_point {
      sim_grid_pos_x: 1306534.12
      sim_grid_pos_y: 1460389.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1305833.62
      sim_grid_pos_y: 1460770.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1305117.88
      sim_grid_pos_y: 1461552.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1305563.38
      sim_grid_pos_y: 1461967.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1307872.62
      sim_grid_pos_y: 1462951
    }
    terrain_level_point {
      sim_grid_pos_x: 1308446.75
      sim_grid_pos_y: 1462500.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1309267.88
      sim_grid_pos_y: 1462093.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1308734.12
      sim_grid_pos_y: 1461537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1308617.62
      sim_grid_pos_y: 1461455.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308553.62
      sim_grid_pos_y: 1461350.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1308513.25
      sim_grid_pos_y: 1460939.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1308224.38
      sim_grid_pos_y: 1460476
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1307590.12
      sim_grid_pos_y: 1459784
    }
    terrain_level_point {
      sim_grid_pos_x: 1307151.25
      sim_grid_pos_y: 1460035.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1306477
      sim_grid_pos_y: 1460256.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1305744
      sim_grid_pos_y: 1460655.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1304916
      sim_grid_pos_y: 1461560.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1305483.88
      sim_grid_pos_y: 1462089.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307894.5
      sim_grid_pos_y: 1463116.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1308523.75
      sim_grid_pos_y: 1462622.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1309507
      sim_grid_pos_y: 1462135.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308828.12
      sim_grid_pos_y: 1461428.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1308724.62
      sim_grid_pos_y: 1461355.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1308693.25
      sim_grid_pos_y: 1461304
    }
    terrain_level_point {
      sim_grid_pos_x: 1308652.75
      sim_grid_pos_y: 1460891.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308333.12
      sim_grid_pos_y: 1460379.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1307603.5
      sim_grid_pos_y: 1459610.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307092.62
      sim_grid_pos_y: 1459903.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1306419.88
      sim_grid_pos_y: 1460124.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1305654.25
      sim_grid_pos_y: 1460541
    }
    terrain_level_point {
      sim_grid_pos_x: 1304714.12
      sim_grid_pos_y: 1461568.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1305404.38
      sim_grid_pos_y: 1462212.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1307916.38
      sim_grid_pos_y: 1463281.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308600.75
      sim_grid_pos_y: 1462744.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1309746.12
      sim_grid_pos_y: 1462177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1308922.25
      sim_grid_pos_y: 1461319.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1308832.75
      sim_grid_pos_y: 1461256
    }
    terrain_level_point {
      sim_grid_pos_x: 1308792.38
      sim_grid_pos_y: 1460844.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1308442
      sim_grid_pos_y: 1460282.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1307617
      sim_grid_pos_y: 1459437.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1307033.88
      sim_grid_pos_y: 1459771.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1306362.62
      sim_grid_pos_y: 1459992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1305564.62
      sim_grid_pos_y: 1460426.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1304512.25
      sim_grid_pos_y: 1461576.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1305325
      sim_grid_pos_y: 1462334.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1307938.25
      sim_grid_pos_y: 1463446.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1308677.75
      sim_grid_pos_y: 1462866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1309985.25
      sim_grid_pos_y: 1462219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1309016.38
      sim_grid_pos_y: 1.46121e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1308969.12
      sim_grid_pos_y: 1461176.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308931.88
      sim_grid_pos_y: 1460796.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1308550.88
      sim_grid_pos_y: 1460185.88
    }
  }
}
