terrain_level_data {
  terrain_level: 955
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1484723.62
      sim_grid_pos_y: 1916111.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1484115.12
      sim_grid_pos_y: 1915796.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1483789
      sim_grid_pos_y: 1915647.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1483519.62
      sim_grid_pos_y: 1915550.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1483206.5
      sim_grid_pos_y: 1915438.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1482415.88
      sim_grid_pos_y: 1915170.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481925.62
      sim_grid_pos_y: 1915000.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481518
      sim_grid_pos_y: 1914871.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481372.38
      sim_grid_pos_y: 1914831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481295
      sim_grid_pos_y: 1914816.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481216.12
      sim_grid_pos_y: 1914814.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1480992.12
      sim_grid_pos_y: 1914853.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1480938.25
      sim_grid_pos_y: 1914689.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1480838
      sim_grid_pos_y: 1914574.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1481024.88
      sim_grid_pos_y: 1914500.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1481415.5
      sim_grid_pos_y: 1914367
    }
    terrain_level_point {
      sim_grid_pos_x: 1481450.88
      sim_grid_pos_y: 1914296.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481670.5
      sim_grid_pos_y: 1914140.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481776.62
      sim_grid_pos_y: 1914082.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481863.5
      sim_grid_pos_y: 1914045.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1481908.12
      sim_grid_pos_y: 1914034.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1482069.38
      sim_grid_pos_y: 1914023.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1482229.25
      sim_grid_pos_y: 1914034.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1482851
      sim_grid_pos_y: 1914284
    }
    terrain_level_point {
      sim_grid_pos_x: 1483377.5
      sim_grid_pos_y: 1.91468e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1483768.88
      sim_grid_pos_y: 1915017.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1484225
      sim_grid_pos_y: 1915459.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1484662
      sim_grid_pos_y: 1915866.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1484823.75
      sim_grid_pos_y: 1916012.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1482252.38
      sim_grid_pos_y: 1913933.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1482901.75
      sim_grid_pos_y: 1914193.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1483441.88
      sim_grid_pos_y: 1914600.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1483838.12
      sim_grid_pos_y: 1914942
    }
    terrain_level_point {
      sim_grid_pos_x: 1484295.5
      sim_grid_pos_y: 1915384.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1484731.38
      sim_grid_pos_y: 1915790.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1484973
      sim_grid_pos_y: 1916008.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1484742.62
      sim_grid_pos_y: 1916236.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1484070.12
      sim_grid_pos_y: 1915888.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1483750.38
      sim_grid_pos_y: 1915742.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1483485
      sim_grid_pos_y: 1915647.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1483485
      sim_grid_pos_y: 1915647.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1483172.88
      sim_grid_pos_y: 1915535.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1482382.75
      sim_grid_pos_y: 1915267.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481893.38
      sim_grid_pos_y: 1915098
    }
    terrain_level_point {
      sim_grid_pos_x: 1481489
      sim_grid_pos_y: 1914969.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1481348.88
      sim_grid_pos_y: 1914931.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481283.62
      sim_grid_pos_y: 1914918.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481223.75
      sim_grid_pos_y: 1914916.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1480922.5
      sim_grid_pos_y: 1914970.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1480847.38
      sim_grid_pos_y: 1914741.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1480665.5
      sim_grid_pos_y: 1914532.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1480989.38
      sim_grid_pos_y: 1914404.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481342.5
      sim_grid_pos_y: 1914283.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481370.62
      sim_grid_pos_y: 1914227.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481616.12
      sim_grid_pos_y: 1914053
    }
    terrain_level_point {
      sim_grid_pos_x: 1481731.88
      sim_grid_pos_y: 1913990.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481830.88
      sim_grid_pos_y: 1913947.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481892.5
      sim_grid_pos_y: 1913932.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1482069.38
      sim_grid_pos_y: 1913920.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1482275.5
      sim_grid_pos_y: 1913832
    }
    terrain_level_point {
      sim_grid_pos_x: 1482952.5
      sim_grid_pos_y: 1914103.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1483506.25
      sim_grid_pos_y: 1914520.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1483907.25
      sim_grid_pos_y: 1914866.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1484366.12
      sim_grid_pos_y: 1915310.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1484800.62
      sim_grid_pos_y: 1915715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1485122.25
      sim_grid_pos_y: 1916005.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1484761.75
      sim_grid_pos_y: 1916361.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1484025.25
      sim_grid_pos_y: 1915980.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1483711.75
      sim_grid_pos_y: 1915837.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1483450.38
      sim_grid_pos_y: 1915744
    }
    terrain_level_point {
      sim_grid_pos_x: 1483450.38
      sim_grid_pos_y: 1915743.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1483138.75
      sim_grid_pos_y: 1915632
    }
    terrain_level_point {
      sim_grid_pos_x: 1482349.5
      sim_grid_pos_y: 1915364.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481861
      sim_grid_pos_y: 1915195.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1481459.75
      sim_grid_pos_y: 1915068.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481325.62
      sim_grid_pos_y: 1915031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1481272.25
      sim_grid_pos_y: 1915020.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1481231.25
      sim_grid_pos_y: 1915019.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1480852.88
      sim_grid_pos_y: 1915086.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1480756.38
      sim_grid_pos_y: 1914793.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1480492.88
      sim_grid_pos_y: 1914491
    }
    terrain_level_point {
      sim_grid_pos_x: 1480953.88
      sim_grid_pos_y: 1914308.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481269.62
      sim_grid_pos_y: 1914200.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1481290.38
      sim_grid_pos_y: 1914158.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481561.88
      sim_grid_pos_y: 1913965.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1481687
      sim_grid_pos_y: 1913898
    }
    terrain_level_point {
      sim_grid_pos_x: 1481798.38
      sim_grid_pos_y: 1913850.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481876.75
      sim_grid_pos_y: 1913831.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1482069.38
      sim_grid_pos_y: 1913818
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1482298.62
      sim_grid_pos_y: 1913730.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1483003.38
      sim_grid_pos_y: 1914013.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1483570.62
      sim_grid_pos_y: 1914440.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1483976.5
      sim_grid_pos_y: 1914790.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1484436.62
      sim_grid_pos_y: 1915236
    }
    terrain_level_point {
      sim_grid_pos_x: 1.48487e+06
      sim_grid_pos_y: 1915639.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1485271.5
      sim_grid_pos_y: 1916002.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1484780.75
      sim_grid_pos_y: 1916487.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1483980.5
      sim_grid_pos_y: 1916073.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1483673.12
      sim_grid_pos_y: 1915932.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1483415.75
      sim_grid_pos_y: 1915840.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1483415.62
      sim_grid_pos_y: 1915840.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1483105
      sim_grid_pos_y: 1915728.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1482316.25
      sim_grid_pos_y: 1915461.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481828.75
      sim_grid_pos_y: 1915292.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481430.88
      sim_grid_pos_y: 1915166.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481302.12
      sim_grid_pos_y: 1915131.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1481260.75
      sim_grid_pos_y: 1915123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481238.88
      sim_grid_pos_y: 1915122.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1480783.25
      sim_grid_pos_y: 1915203.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1480665.5
      sim_grid_pos_y: 1914844.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1480320.38
      sim_grid_pos_y: 1914449
    }
    terrain_level_point {
      sim_grid_pos_x: 1480918.38
      sim_grid_pos_y: 1914212.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481196.62
      sim_grid_pos_y: 1914116.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1481210.12
      sim_grid_pos_y: 1914089.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1481507.62
      sim_grid_pos_y: 1913878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481642.25
      sim_grid_pos_y: 1913805.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1481765.75
      sim_grid_pos_y: 1913752.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481861.12
      sim_grid_pos_y: 1913729.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1482069.38
      sim_grid_pos_y: 1913715.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1482321.75
      sim_grid_pos_y: 1913629.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1483054.12
      sim_grid_pos_y: 1913923.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1483635
      sim_grid_pos_y: 1914360.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1484045.75
      sim_grid_pos_y: 1914714.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1484507.5
      sim_grid_pos_y: 1915161.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1484939
      sim_grid_pos_y: 1915563.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1485420.75
      sim_grid_pos_y: 1915998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1484799.88
      sim_grid_pos_y: 1916612.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1483935.75
      sim_grid_pos_y: 1916165.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1483634.38
      sim_grid_pos_y: 1916027.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1483381.12
      sim_grid_pos_y: 1915937
    }
    terrain_level_point {
      sim_grid_pos_x: 1483381
      sim_grid_pos_y: 1915936.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1483071.75
      sim_grid_pos_y: 1915825.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1482283
      sim_grid_pos_y: 1915558.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1481796.5
      sim_grid_pos_y: 1.91539e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1481401.75
      sim_grid_pos_y: 1915264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1481278.62
      sim_grid_pos_y: 1915231
    }
    terrain_level_point {
      sim_grid_pos_x: 1481249.5
      sim_grid_pos_y: 1915225.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481246.38
      sim_grid_pos_y: 1915225.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1480713.62
      sim_grid_pos_y: 1915319.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1480574.5
      sim_grid_pos_y: 1914896.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1480147.75
      sim_grid_pos_y: 1914407.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1480882.88
      sim_grid_pos_y: 1914116
    }
    terrain_level_point {
      sim_grid_pos_x: 1481123.75
      sim_grid_pos_y: 1914033.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481129.88
      sim_grid_pos_y: 1914021.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1481453.25
      sim_grid_pos_y: 1913791.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1481597.5
      sim_grid_pos_y: 1913713.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1481733.25
      sim_grid_pos_y: 1913654.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1481845.5
      sim_grid_pos_y: 1913627.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1482069.38
      sim_grid_pos_y: 1913612.5
    }
  }
}
