terrain_level_data {
  terrain_level: 5260
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2459904
      sim_grid_pos_y: 1759424.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2460172.5
      sim_grid_pos_y: 1759487.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2460516.75
      sim_grid_pos_y: 1759769.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2460531.5
      sim_grid_pos_y: 1759969.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2460322.75
      sim_grid_pos_y: 1759880.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2460023.25
      sim_grid_pos_y: 1759642.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2460186.5
      sim_grid_pos_y: 1759459.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2460546.5
      sim_grid_pos_y: 1759754.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2460565.75
      sim_grid_pos_y: 1760017.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2460307
      sim_grid_pos_y: 1759907
    }
    terrain_level_point {
      sim_grid_pos_x: 2459999.25
      sim_grid_pos_y: 1759662.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2459867.5
      sim_grid_pos_y: 1759421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2459891.75
      sim_grid_pos_y: 1759389.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2460200.5
      sim_grid_pos_y: 1759430.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2460576.25
      sim_grid_pos_y: 1759738.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2460600.25
      sim_grid_pos_y: 1760065.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2460291
      sim_grid_pos_y: 1759933.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2459975.25
      sim_grid_pos_y: 1759682.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2459831
      sim_grid_pos_y: 1759418.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2459879.25
      sim_grid_pos_y: 1759355.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2460214.5
      sim_grid_pos_y: 1759402.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2460606
      sim_grid_pos_y: 1759723.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2460634.5
      sim_grid_pos_y: 1760113.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2460275.25
      sim_grid_pos_y: 1759960.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2459951.25
      sim_grid_pos_y: 1759703
    }
    terrain_level_point {
      sim_grid_pos_x: 2459794.5
      sim_grid_pos_y: 1759416
    }
    terrain_level_point {
      sim_grid_pos_x: 2459867
      sim_grid_pos_y: 1759320.75
    }
  }
}
