terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1296650.38
      sim_grid_pos_y: 1564943.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1297990.62
      sim_grid_pos_y: 1565447.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1298875.12
      sim_grid_pos_y: 1565658.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1302333.75
      sim_grid_pos_y: 1566079.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1301920.75
      sim_grid_pos_y: 1567822.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1302484.88
      sim_grid_pos_y: 1568626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1300053
      sim_grid_pos_y: 1568517.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1295423.5
      sim_grid_pos_y: 1568600.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1293560.75
      sim_grid_pos_y: 1568954.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1291796
      sim_grid_pos_y: 1568667.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1290279.62
      sim_grid_pos_y: 1568461.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1290198.38
      sim_grid_pos_y: 1568006.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1289823.12
      sim_grid_pos_y: 1567208.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.29002e+06
      sim_grid_pos_y: 1566666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1289605.25
      sim_grid_pos_y: 1565554.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1291313.5
      sim_grid_pos_y: 1564586.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1293368.88
      sim_grid_pos_y: 1564835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1294711.38
      sim_grid_pos_y: 1564719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295857.75
      sim_grid_pos_y: 1564749.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1293369.75
      sim_grid_pos_y: 1564783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1294709.88
      sim_grid_pos_y: 1564668.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1295864.62
      sim_grid_pos_y: 1564698.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1296665.5
      sim_grid_pos_y: 1564894.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1298005.75
      sim_grid_pos_y: 1565398.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1298884.25
      sim_grid_pos_y: 1565608.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1302396.88
      sim_grid_pos_y: 1566035.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1301976
      sim_grid_pos_y: 1567812.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1302545.12
      sim_grid_pos_y: 1568623.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1302514.5
      sim_grid_pos_y: 1568679.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1300052.25
      sim_grid_pos_y: 1568568.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1295428.88
      sim_grid_pos_y: 1568651.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1293561.5
      sim_grid_pos_y: 1569006.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1291788.5
      sim_grid_pos_y: 1568718.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1290235.75
      sim_grid_pos_y: 1568506.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1290149.12
      sim_grid_pos_y: 1568022.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1289767.62
      sim_grid_pos_y: 1567210.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1289965.38
      sim_grid_pos_y: 1566667.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1289542
      sim_grid_pos_y: 1565531.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1291302.88
      sim_grid_pos_y: 1564534
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1293370.62
      sim_grid_pos_y: 1564732.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1294708.25
      sim_grid_pos_y: 1564616.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1295871.5
      sim_grid_pos_y: 1564647
    }
    terrain_level_point {
      sim_grid_pos_x: 1296680.75
      sim_grid_pos_y: 1564845.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1298020.62
      sim_grid_pos_y: 1565349.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1298893.25
      sim_grid_pos_y: 1565557.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.30246e+06
      sim_grid_pos_y: 1565991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1302031.12
      sim_grid_pos_y: 1567801.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1302605.5
      sim_grid_pos_y: 1568619.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1302544
      sim_grid_pos_y: 1568731.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1300051.62
      sim_grid_pos_y: 1568619.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1295434.12
      sim_grid_pos_y: 1568702.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1293562.12
      sim_grid_pos_y: 1569059
    }
    terrain_level_point {
      sim_grid_pos_x: 1291780.88
      sim_grid_pos_y: 1568768.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1290191.88
      sim_grid_pos_y: 1568552.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1290099.88
      sim_grid_pos_y: 1568038
    }
    terrain_level_point {
      sim_grid_pos_x: 1289712.25
      sim_grid_pos_y: 1567213.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1289910.75
      sim_grid_pos_y: 1566667.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1289478.62
      sim_grid_pos_y: 1565508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1291292.25
      sim_grid_pos_y: 1564481
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1293371.5
      sim_grid_pos_y: 1564680.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1294706.75
      sim_grid_pos_y: 1564565.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295878.25
      sim_grid_pos_y: 1564595.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1296695.88
      sim_grid_pos_y: 1564796.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1298035.75
      sim_grid_pos_y: 1.5653e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1298902.38
      sim_grid_pos_y: 1565507.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1302523
      sim_grid_pos_y: 1565947.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1302086.38
      sim_grid_pos_y: 1567791
    }
    terrain_level_point {
      sim_grid_pos_x: 1302665.75
      sim_grid_pos_y: 1568616.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1302573.62
      sim_grid_pos_y: 1568784.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1300050.88
      sim_grid_pos_y: 1568671
    }
    terrain_level_point {
      sim_grid_pos_x: 1295439.38
      sim_grid_pos_y: 1568753.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1293562.88
      sim_grid_pos_y: 1569111
    }
    terrain_level_point {
      sim_grid_pos_x: 1291773.38
      sim_grid_pos_y: 1568819.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1290148
      sim_grid_pos_y: 1568598.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1290050.5
      sim_grid_pos_y: 1568053.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1289656.75
      sim_grid_pos_y: 1567215.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1289856.12
      sim_grid_pos_y: 1566667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1289415.38
      sim_grid_pos_y: 1565485.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1291281.75
      sim_grid_pos_y: 1564428.12
    }
  }
}
