terrain_level_data {
  terrain_level: 210
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2140979
      sim_grid_pos_y: 1005811.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2140950.25
      sim_grid_pos_y: 1005942.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2141052
      sim_grid_pos_y: 1006015.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2141155.75
      sim_grid_pos_y: 1006041.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2141276.75
      sim_grid_pos_y: 1005982.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2141297.25
      sim_grid_pos_y: 1005853.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2141243.75
      sim_grid_pos_y: 1005747.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2141022
      sim_grid_pos_y: 1005744.81
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2140994.25
      sim_grid_pos_y: 1005693.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2140931
      sim_grid_pos_y: 1005791.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2140893
      sim_grid_pos_y: 1005964.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.14103e+06
      sim_grid_pos_y: 1006062.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2141161.25
      sim_grid_pos_y: 1006095.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2141323.25
      sim_grid_pos_y: 1006017.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2141350.5
      sim_grid_pos_y: 1005845.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2141275.5
      sim_grid_pos_y: 1005696.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2140966.25
      sim_grid_pos_y: 1005641.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2140882.75
      sim_grid_pos_y: 1005771.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2140835.5
      sim_grid_pos_y: 1005986.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2141008.25
      sim_grid_pos_y: 1006110.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2141167
      sim_grid_pos_y: 1006149.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2141369.5
      sim_grid_pos_y: 1006052
    }
    terrain_level_point {
      sim_grid_pos_x: 2141403.75
      sim_grid_pos_y: 1005837.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2141307.25
      sim_grid_pos_y: 1005645.19
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2140938.5
      sim_grid_pos_y: 1005590.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2140834.75
      sim_grid_pos_y: 1005751.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2140778.25
      sim_grid_pos_y: 1006007.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2140986.25
      sim_grid_pos_y: 1006157.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2141172.5
      sim_grid_pos_y: 1006203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2141416
      sim_grid_pos_y: 1006086.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2141457
      sim_grid_pos_y: 1005828.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2141339
      sim_grid_pos_y: 1005594.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2140910.75
      sim_grid_pos_y: 1005538.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2140786.75
      sim_grid_pos_y: 1005731.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2140721
      sim_grid_pos_y: 1006029.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2140964.25
      sim_grid_pos_y: 1006205
    }
    terrain_level_point {
      sim_grid_pos_x: 2141178.25
      sim_grid_pos_y: 1006258
    }
    terrain_level_point {
      sim_grid_pos_x: 2141462.5
      sim_grid_pos_y: 1006121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.14151e+06
      sim_grid_pos_y: 1005820.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2141371
      sim_grid_pos_y: 1005543.31
    }
  }
}
terrain_level_data {
  terrain_level: 295
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2144111
      sim_grid_pos_y: 1010574.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2.14408e+06
      sim_grid_pos_y: 1010740.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2144132
      sim_grid_pos_y: 1010934.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2144259.25
      sim_grid_pos_y: 1010922.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2144373.5
      sim_grid_pos_y: 1010808.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2144372.75
      sim_grid_pos_y: 1010596.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2144233.75
      sim_grid_pos_y: 1010482.06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2144235
      sim_grid_pos_y: 1010416.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2144064.25
      sim_grid_pos_y: 1010545.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2144027.5
      sim_grid_pos_y: 1010742.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2144093.75
      sim_grid_pos_y: 1010990.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2144282.25
      sim_grid_pos_y: 1010971.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2144425
      sim_grid_pos_y: 1010829.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2144424
      sim_grid_pos_y: 1010572.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2144236.25
      sim_grid_pos_y: 1010351.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2144017.5
      sim_grid_pos_y: 1010517
    }
    terrain_level_point {
      sim_grid_pos_x: 2143975
      sim_grid_pos_y: 1010744.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2144055.5
      sim_grid_pos_y: 1011045.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2144305.5
      sim_grid_pos_y: 1011020.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2144476.25
      sim_grid_pos_y: 1010851.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2144475.25
      sim_grid_pos_y: 1010547.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2144237.5
      sim_grid_pos_y: 1010286.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2143971
      sim_grid_pos_y: 1010488.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2143922.5
      sim_grid_pos_y: 1010746.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2144017.25
      sim_grid_pos_y: 1011100.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2144328.75
      sim_grid_pos_y: 1011069.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2144527.5
      sim_grid_pos_y: 1010872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2144526.25
      sim_grid_pos_y: 1010523.56
    }
  }
}
terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2.14676e+06
      sim_grid_pos_y: 1016379.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2146745.5
      sim_grid_pos_y: 1016490.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2146831.5
      sim_grid_pos_y: 1016606.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2146952
      sim_grid_pos_y: 1016659.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2147078.5
      sim_grid_pos_y: 1016599.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2147145.75
      sim_grid_pos_y: 1016463.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2147071.75
      sim_grid_pos_y: 1016323.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2146938.75
      sim_grid_pos_y: 1016292.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2146820.5
      sim_grid_pos_y: 1016312.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2146940.25
      sim_grid_pos_y: 1016240.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2146794.25
      sim_grid_pos_y: 1016264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2146711.25
      sim_grid_pos_y: 1016357.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2146692
      sim_grid_pos_y: 1016503.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2146798.25
      sim_grid_pos_y: 1016648.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2146952.75
      sim_grid_pos_y: 1016716.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2147116.5
      sim_grid_pos_y: 1016638.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2147203.25
      sim_grid_pos_y: 1016463
    }
    terrain_level_point {
      sim_grid_pos_x: 2147106.25
      sim_grid_pos_y: 1016278.81
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2146942
      sim_grid_pos_y: 1016188.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2146768.25
      sim_grid_pos_y: 1016217.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2146662.5
      sim_grid_pos_y: 1016334.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2146638.5
      sim_grid_pos_y: 1016517.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2146765.25
      sim_grid_pos_y: 1016689.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2146953.75
      sim_grid_pos_y: 1016772.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2147154.5
      sim_grid_pos_y: 1016676.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2147261
      sim_grid_pos_y: 1016462.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2147140.5
      sim_grid_pos_y: 1016234.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2146943.5
      sim_grid_pos_y: 1016135.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2146742
      sim_grid_pos_y: 1016169.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2146613.75
      sim_grid_pos_y: 1016312.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2146585
      sim_grid_pos_y: 1016531.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2146732
      sim_grid_pos_y: 1016730.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2146954.5
      sim_grid_pos_y: 1016828.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2147192.75
      sim_grid_pos_y: 1016715.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2147318.5
      sim_grid_pos_y: 1016461.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2147175
      sim_grid_pos_y: 1016189.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2146945.25
      sim_grid_pos_y: 1016083.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2146716
      sim_grid_pos_y: 1016121.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2146565
      sim_grid_pos_y: 1.01629e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2146531.5
      sim_grid_pos_y: 1016545.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2146699
      sim_grid_pos_y: 1016772.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2146955.5
      sim_grid_pos_y: 1016885.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2147230.75
      sim_grid_pos_y: 1016754
    }
    terrain_level_point {
      sim_grid_pos_x: 2147376
      sim_grid_pos_y: 1016460.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2147209.5
      sim_grid_pos_y: 1016144.81
    }
  }
}
terrain_level_data {
  terrain_level: 57
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2135942.5
      sim_grid_pos_y: 1006629.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2135437.25
      sim_grid_pos_y: 1007027.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2136699.5
      sim_grid_pos_y: 1008480.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2138438.25
      sim_grid_pos_y: 1009329.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2138627
      sim_grid_pos_y: 1008800.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2135943
      sim_grid_pos_y: 1006563.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2135363.25
      sim_grid_pos_y: 1007020.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2136667.75
      sim_grid_pos_y: 1008522.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2138467.25
      sim_grid_pos_y: 1009400.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2138687.5
      sim_grid_pos_y: 1008783.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2135943.25
      sim_grid_pos_y: 1006498.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2135289.25
      sim_grid_pos_y: 1007013.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2136635.75
      sim_grid_pos_y: 1008563.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2138496.25
      sim_grid_pos_y: 1009471.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2138748
      sim_grid_pos_y: 1008766.5
    }
  }
}
