terrain_level_data {
  terrain_level: 406
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1358845.88
      sim_grid_pos_y: 1450477
    }
    terrain_level_point {
      sim_grid_pos_x: 1358682.88
      sim_grid_pos_y: 1451048.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1358748.12
      sim_grid_pos_y: 1451302.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1358942.62
      sim_grid_pos_y: 1451251.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.35918e+06
      sim_grid_pos_y: 1450947.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359394.38
      sim_grid_pos_y: 1450892.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359350.25
      sim_grid_pos_y: 1450623.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1359309.62
      sim_grid_pos_y: 1450430.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1359823.38
      sim_grid_pos_y: 1450176.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1360040.88
      sim_grid_pos_y: 1450158.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359982.75
      sim_grid_pos_y: 1449984.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359782.25
      sim_grid_pos_y: 1450013
    }
    terrain_level_point {
      sim_grid_pos_x: 1359199.38
      sim_grid_pos_y: 1450241.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1360003.75
      sim_grid_pos_y: 1449950.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359774.5
      sim_grid_pos_y: 1449983.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359185.12
      sim_grid_pos_y: 1450214.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1358819.38
      sim_grid_pos_y: 1450457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1358651
      sim_grid_pos_y: 1451048.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1358726.12
      sim_grid_pos_y: 1451340.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1358960.38
      sim_grid_pos_y: 1451279
    }
    terrain_level_point {
      sim_grid_pos_x: 1359197.75
      sim_grid_pos_y: 1450974.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1359429.25
      sim_grid_pos_y: 1450915.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359380.5
      sim_grid_pos_y: 1450617.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359344.62
      sim_grid_pos_y: 1450447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1359831.75
      sim_grid_pos_y: 1450207
    }
    terrain_level_point {
      sim_grid_pos_x: 1360082.5
      sim_grid_pos_y: 1450185.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1360024.75
      sim_grid_pos_y: 1449916.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359766.62
      sim_grid_pos_y: 1449953.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359170.88
      sim_grid_pos_y: 1450187
    }
    terrain_level_point {
      sim_grid_pos_x: 1358793
      sim_grid_pos_y: 1450438.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1358619.12
      sim_grid_pos_y: 1451048
    }
    terrain_level_point {
      sim_grid_pos_x: 1358704
      sim_grid_pos_y: 1451377.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1358978.25
      sim_grid_pos_y: 1451306.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359215.5
      sim_grid_pos_y: 1451001.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1359464.25
      sim_grid_pos_y: 1450938.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1359410.75
      sim_grid_pos_y: 1450612.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1359379.62
      sim_grid_pos_y: 1450464.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1359840.25
      sim_grid_pos_y: 1450237.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1360124.12
      sim_grid_pos_y: 1450212.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1360045.75
      sim_grid_pos_y: 1449882.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359758.75
      sim_grid_pos_y: 1449923.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359156.5
      sim_grid_pos_y: 1450159.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1358766.5
      sim_grid_pos_y: 1450419
    }
    terrain_level_point {
      sim_grid_pos_x: 1358587.25
      sim_grid_pos_y: 1451047.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1358681.88
      sim_grid_pos_y: 1451415.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1358996.12
      sim_grid_pos_y: 1451333.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1359233.25
      sim_grid_pos_y: 1451028.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1359499.12
      sim_grid_pos_y: 1450961.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1359441
      sim_grid_pos_y: 1450606.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1359414.62
      sim_grid_pos_y: 1450481.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1359848.62
      sim_grid_pos_y: 1450267.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1360165.75
      sim_grid_pos_y: 1.45024e+06
    }
  }
}
