terrain_level_data {
  terrain_level: 4450
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2923749.25
      sim_grid_pos_y: 1932829.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2917835
      sim_grid_pos_y: 1923052.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2919357.75
      sim_grid_pos_y: 1922162.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2925282.75
      sim_grid_pos_y: 1932031.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2925426.75
      sim_grid_pos_y: 1932072.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2923711.25
      sim_grid_pos_y: 1932965.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2917693.5
      sim_grid_pos_y: 1923016.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2919393.5
      sim_grid_pos_y: 1922022.5
    }
  }
}
