terrain_level_data {
  terrain_level: 505
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1800415
      sim_grid_pos_y: 1840490.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1800118.25
      sim_grid_pos_y: 1840492
    }
    terrain_level_point {
      sim_grid_pos_x: 1799983.75
      sim_grid_pos_y: 1840451.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1799848.5
      sim_grid_pos_y: 1840140.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1800109.12
      sim_grid_pos_y: 1840033.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1800175.38
      sim_grid_pos_y: 1839619.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1800346.12
      sim_grid_pos_y: 1839414.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1800578.62
      sim_grid_pos_y: 1839417.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1800402.88
      sim_grid_pos_y: 1839599.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1800326.38
      sim_grid_pos_y: 1839744.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1800480.25
      sim_grid_pos_y: 1840075.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1800590.62
      sim_grid_pos_y: 1840339.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1800568.38
      sim_grid_pos_y: 1840488.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1800599.38
      sim_grid_pos_y: 1839387
    }
    terrain_level_point {
      sim_grid_pos_x: 1800614.88
      sim_grid_pos_y: 1839424.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1800428
      sim_grid_pos_y: 1839618
    }
    terrain_level_point {
      sim_grid_pos_x: 1800360.62
      sim_grid_pos_y: 1839745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1800508.38
      sim_grid_pos_y: 1840063.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1800622.38
      sim_grid_pos_y: 1840336
    }
    terrain_level_point {
      sim_grid_pos_x: 1800594.88
      sim_grid_pos_y: 1840519
    }
    terrain_level_point {
      sim_grid_pos_x: 1800415.25
      sim_grid_pos_y: 1840521.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1800113.88
      sim_grid_pos_y: 1840522.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1799961.25
      sim_grid_pos_y: 1840476.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1799807.75
      sim_grid_pos_y: 1840123.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1800081.5
      sim_grid_pos_y: 1840011.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1800146.38
      sim_grid_pos_y: 1839606
    }
    terrain_level_point {
      sim_grid_pos_x: 1800331.88
      sim_grid_pos_y: 1839383.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1.80062e+06
      sim_grid_pos_y: 1839356.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1800651
      sim_grid_pos_y: 1839431.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1800453.12
      sim_grid_pos_y: 1839636.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1800395
      sim_grid_pos_y: 1839746.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1800536.5
      sim_grid_pos_y: 1840050.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1800654
      sim_grid_pos_y: 1840332
    }
    terrain_level_point {
      sim_grid_pos_x: 1800621.38
      sim_grid_pos_y: 1840549.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1800415.5
      sim_grid_pos_y: 1840552
    }
    terrain_level_point {
      sim_grid_pos_x: 1800109.38
      sim_grid_pos_y: 1840553.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1799938.75
      sim_grid_pos_y: 1840502.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1799767
      sim_grid_pos_y: 1840107.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1800053.88
      sim_grid_pos_y: 1839989.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1800117.25
      sim_grid_pos_y: 1839592.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1800317.62
      sim_grid_pos_y: 1839352.25
    }
  }
}
terrain_level_data {
  terrain_level: 130
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1800014
      sim_grid_pos_y: 1841935.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.7999e+06
      sim_grid_pos_y: 1841782.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1800109.62
      sim_grid_pos_y: 1841559.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1800267.88
      sim_grid_pos_y: 1841718.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1800313.12
      sim_grid_pos_y: 1841720.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1800009
      sim_grid_pos_y: 1841980.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1799859.88
      sim_grid_pos_y: 1841780.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1800109
      sim_grid_pos_y: 1841514.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1800358.25
      sim_grid_pos_y: 1841722.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1800004
      sim_grid_pos_y: 1842024.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1799819.88
      sim_grid_pos_y: 1841778.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1800108.38
      sim_grid_pos_y: 1841470.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1800403.38
      sim_grid_pos_y: 1841724.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1799999
      sim_grid_pos_y: 1842069.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1799779.75
      sim_grid_pos_y: 1841776.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1800107.75
      sim_grid_pos_y: 1841426.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1800448.62
      sim_grid_pos_y: 1841726
    }
    terrain_level_point {
      sim_grid_pos_x: 1799994.12
      sim_grid_pos_y: 1842114.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1799739.75
      sim_grid_pos_y: 1841774
    }
    terrain_level_point {
      sim_grid_pos_x: 1800107.12
      sim_grid_pos_y: 1841382
    }
  }
}
