terrain_level_data {
  terrain_level: 340
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1.89242e+06
      sim_grid_pos_y: 1649623.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892229.38
      sim_grid_pos_y: 1649847.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892155
      sim_grid_pos_y: 1650168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1892371.5
      sim_grid_pos_y: 1650280.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1892607
      sim_grid_pos_y: 1650219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1892755.5
      sim_grid_pos_y: 1649950.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1892807.62
      sim_grid_pos_y: 1649669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1892599.12
      sim_grid_pos_y: 1649587.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1892603
      sim_grid_pos_y: 1649545.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892398
      sim_grid_pos_y: 1649585.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892191.62
      sim_grid_pos_y: 1649828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892107.88
      sim_grid_pos_y: 1650190.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1892366.5
      sim_grid_pos_y: 1650324.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1892634.38
      sim_grid_pos_y: 1650254.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892794.5
      sim_grid_pos_y: 1649964.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1892854.25
      sim_grid_pos_y: 1649643.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1892606.88
      sim_grid_pos_y: 1649502.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1892376
      sim_grid_pos_y: 1649548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892154
      sim_grid_pos_y: 1649809.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892060.75
      sim_grid_pos_y: 1650212.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1892361.62
      sim_grid_pos_y: 1650367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892661.75
      sim_grid_pos_y: 1.65029e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1892833.62
      sim_grid_pos_y: 1649978.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892900.75
      sim_grid_pos_y: 1649618
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1892610.62
      sim_grid_pos_y: 1649460.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1892354.12
      sim_grid_pos_y: 1649510.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1892116.25
      sim_grid_pos_y: 1649790.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1892013.62
      sim_grid_pos_y: 1650234
    }
    terrain_level_point {
      sim_grid_pos_x: 1892356.75
      sim_grid_pos_y: 1650411.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1892689.12
      sim_grid_pos_y: 1650325.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1892872.75
      sim_grid_pos_y: 1649992.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892947.25
      sim_grid_pos_y: 1649592.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1892614.5
      sim_grid_pos_y: 1649417.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1892332.12
      sim_grid_pos_y: 1649473.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1892078.5
      sim_grid_pos_y: 1649771.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1891966.5
      sim_grid_pos_y: 1650255.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892351.88
      sim_grid_pos_y: 1650455
    }
    terrain_level_point {
      sim_grid_pos_x: 1892716.38
      sim_grid_pos_y: 1650360.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1892911.88
      sim_grid_pos_y: 1650006.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1892993.75
      sim_grid_pos_y: 1649566.5
    }
  }
}
