terrain_level_data {
  terrain_level: 300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1464693.75
      sim_grid_pos_y: 1537747
    }
    terrain_level_point {
      sim_grid_pos_x: 1464809.62
      sim_grid_pos_y: 1537905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464835.25
      sim_grid_pos_y: 1538024.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464851.5
      sim_grid_pos_y: 1538232.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.46487e+06
      sim_grid_pos_y: 1538343
    }
    terrain_level_point {
      sim_grid_pos_x: 1464905.12
      sim_grid_pos_y: 1538435.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465054.75
      sim_grid_pos_y: 1538609.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1465133.62
      sim_grid_pos_y: 1538893.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465275.75
      sim_grid_pos_y: 1539209.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465348.12
      sim_grid_pos_y: 1539260.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465383.38
      sim_grid_pos_y: 1540070.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465841.25
      sim_grid_pos_y: 1540030.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466238.75
      sim_grid_pos_y: 1539842.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466187.25
      sim_grid_pos_y: 1539711.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466285.75
      sim_grid_pos_y: 1539478.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466315.62
      sim_grid_pos_y: 1539354
    }
    terrain_level_point {
      sim_grid_pos_x: 1466284.25
      sim_grid_pos_y: 1539352.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466246.88
      sim_grid_pos_y: 1539165.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466181.5
      sim_grid_pos_y: 1539115
    }
    terrain_level_point {
      sim_grid_pos_x: 1466182.62
      sim_grid_pos_y: 1539089.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466392.25
      sim_grid_pos_y: 1539034.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466602.88
      sim_grid_pos_y: 1538901.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466420.75
      sim_grid_pos_y: 1538490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466327.5
      sim_grid_pos_y: 1538408.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466353.75
      sim_grid_pos_y: 1537993.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466617.12
      sim_grid_pos_y: 1537998.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466719.5
      sim_grid_pos_y: 1537926
    }
    terrain_level_point {
      sim_grid_pos_x: 1466721.88
      sim_grid_pos_y: 1537536
    }
    terrain_level_point {
      sim_grid_pos_x: 1466626.88
      sim_grid_pos_y: 1537403.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466499.25
      sim_grid_pos_y: 1537335.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466186.5
      sim_grid_pos_y: 1537260.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466073.12
      sim_grid_pos_y: 1537124
    }
    terrain_level_point {
      sim_grid_pos_x: 1466135.38
      sim_grid_pos_y: 1537023.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466113.5
      sim_grid_pos_y: 1536933.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466054.62
      sim_grid_pos_y: 1536883.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1465809.88
      sim_grid_pos_y: 1537072.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465483.38
      sim_grid_pos_y: 1536984.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465531.5
      sim_grid_pos_y: 1536590.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465501.25
      sim_grid_pos_y: 1536476
    }
    terrain_level_point {
      sim_grid_pos_x: 1465403
      sim_grid_pos_y: 1536483.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1465400.25
      sim_grid_pos_y: 1536272.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465441.25
      sim_grid_pos_y: 1536106
    }
    terrain_level_point {
      sim_grid_pos_x: 1465505.88
      sim_grid_pos_y: 1535734.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464863.62
      sim_grid_pos_y: 1535738.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464103.62
      sim_grid_pos_y: 1536134
    }
    terrain_level_point {
      sim_grid_pos_x: 1463776.38
      sim_grid_pos_y: 1536691.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1465664.5
      sim_grid_pos_y: 1535599.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464830.62
      sim_grid_pos_y: 1535605.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464008.12
      sim_grid_pos_y: 1536033.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1463613
      sim_grid_pos_y: 1536706.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464589.38
      sim_grid_pos_y: 1537830.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464685.38
      sim_grid_pos_y: 1537961.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464703
      sim_grid_pos_y: 1538044
    }
    terrain_level_point {
      sim_grid_pos_x: 1464719
      sim_grid_pos_y: 1538248.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464740.75
      sim_grid_pos_y: 1538378
    }
    terrain_level_point {
      sim_grid_pos_x: 1464788.75
      sim_grid_pos_y: 1538504.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464934.38
      sim_grid_pos_y: 1538674.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465008
      sim_grid_pos_y: 1538938.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1465169.12
      sim_grid_pos_y: 1539297.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465217.88
      sim_grid_pos_y: 1539331.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1465256.38
      sim_grid_pos_y: 1540214.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465876.75
      sim_grid_pos_y: 1540161.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466408.38
      sim_grid_pos_y: 1539909.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466331.25
      sim_grid_pos_y: 1539713.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466412.75
      sim_grid_pos_y: 1.53952e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1466483.38
      sim_grid_pos_y: 1539226.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466394.38
      sim_grid_pos_y: 1539223.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466384.5
      sim_grid_pos_y: 1539174.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466446
      sim_grid_pos_y: 1539157.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466771.5
      sim_grid_pos_y: 1538953.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466530.75
      sim_grid_pos_y: 1538410.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466464.62
      sim_grid_pos_y: 1538351.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466478.75
      sim_grid_pos_y: 1538129.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466658.38
      sim_grid_pos_y: 1538132.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466852.38
      sim_grid_pos_y: 1537995.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466855.5
      sim_grid_pos_y: 1537493.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466717
      sim_grid_pos_y: 1537300.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466546.88
      sim_grid_pos_y: 1537209.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466260.62
      sim_grid_pos_y: 1537141.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466236.88
      sim_grid_pos_y: 1537112.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466278
      sim_grid_pos_y: 1537045.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466232.88
      sim_grid_pos_y: 1536859.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466058.5
      sim_grid_pos_y: 1536711.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1465780.62
      sim_grid_pos_y: 1536926.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465629.75
      sim_grid_pos_y: 1536886.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465667
      sim_grid_pos_y: 1536581.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1465601.75
      sim_grid_pos_y: 1536334.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1465534.38
      sim_grid_pos_y: 1536339.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465533.75
      sim_grid_pos_y: 1536287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1465571.75
      sim_grid_pos_y: 1536133.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1465823.25
      sim_grid_pos_y: 1535465.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464797.62
      sim_grid_pos_y: 1535472
    }
    terrain_level_point {
      sim_grid_pos_x: 1463912.5
      sim_grid_pos_y: 1535933
    }
    terrain_level_point {
      sim_grid_pos_x: 1463449.5
      sim_grid_pos_y: 1536721.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464485.12
      sim_grid_pos_y: 1537913.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464561
      sim_grid_pos_y: 1538017.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464570.88
      sim_grid_pos_y: 1538063.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464586.62
      sim_grid_pos_y: 1538264.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1464611.38
      sim_grid_pos_y: 1538413
    }
    terrain_level_point {
      sim_grid_pos_x: 1464672.5
      sim_grid_pos_y: 1538574
    }
    terrain_level_point {
      sim_grid_pos_x: 1464813.88
      sim_grid_pos_y: 1538738.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464882.25
      sim_grid_pos_y: 1538984.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465062.62
      sim_grid_pos_y: 1539385.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465087.5
      sim_grid_pos_y: 1539402.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1465129.25
      sim_grid_pos_y: 1540359.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1465912.12
      sim_grid_pos_y: 1540292.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466577.88
      sim_grid_pos_y: 1539976.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466475.12
      sim_grid_pos_y: 1539715
    }
    terrain_level_point {
      sim_grid_pos_x: 1466539.75
      sim_grid_pos_y: 1539561.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466626.25
      sim_grid_pos_y: 1539202
    }
    terrain_level_point {
      sim_grid_pos_x: 1.46694e+06
      sim_grid_pos_y: 1539004.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466640.88
      sim_grid_pos_y: 1538329.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466601.75
      sim_grid_pos_y: 1538295
    }
    terrain_level_point {
      sim_grid_pos_x: 1466603.62
      sim_grid_pos_y: 1538264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466699.62
      sim_grid_pos_y: 1538266.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466985.25
      sim_grid_pos_y: 1538064.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466989
      sim_grid_pos_y: 1537450.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466807.12
      sim_grid_pos_y: 1537197.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466594.62
      sim_grid_pos_y: 1537084.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466414
      sim_grid_pos_y: 1537040.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466352.12
      sim_grid_pos_y: 1536786.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466062.5
      sim_grid_pos_y: 1536540.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1465779.5
      sim_grid_pos_y: 1536759.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465802.38
      sim_grid_pos_y: 1536572.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465702.25
      sim_grid_pos_y: 1536193
    }
    terrain_level_point {
      sim_grid_pos_x: 1465694.12
      sim_grid_pos_y: 1536193.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1465702.25
      sim_grid_pos_y: 1536160.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1465981.88
      sim_grid_pos_y: 1535331.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464764.5
      sim_grid_pos_y: 1535339
    }
    terrain_level_point {
      sim_grid_pos_x: 1463817
      sim_grid_pos_y: 1535832.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1463286.12
      sim_grid_pos_y: 1536737
    }
    terrain_level_point {
      sim_grid_pos_x: 1464380.75
      sim_grid_pos_y: 1537996.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464436.62
      sim_grid_pos_y: 1538072.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464438.75
      sim_grid_pos_y: 1538082.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464454.12
      sim_grid_pos_y: 1538280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464482.12
      sim_grid_pos_y: 1538447.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464556.12
      sim_grid_pos_y: 1538643.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464693.5
      sim_grid_pos_y: 1538802.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464756.62
      sim_grid_pos_y: 1539029.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1464956
      sim_grid_pos_y: 1539473.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464957.25
      sim_grid_pos_y: 1539474
    }
    terrain_level_point {
      sim_grid_pos_x: 1465002.12
      sim_grid_pos_y: 1540504.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465947.5
      sim_grid_pos_y: 1540422.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466747.5
      sim_grid_pos_y: 1540043.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466619
      sim_grid_pos_y: 1539716.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466666.75
      sim_grid_pos_y: 1539603.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466743.12
      sim_grid_pos_y: 1539286
    }
    terrain_level_point {
      sim_grid_pos_x: 1467108.62
      sim_grid_pos_y: 1539056.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466799.75
      sim_grid_pos_y: 1538359
    }
    terrain_level_point {
      sim_grid_pos_x: 1467118.12
      sim_grid_pos_y: 1538133.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1467122.5
      sim_grid_pos_y: 1537408.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466897.38
      sim_grid_pos_y: 1537094.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466642.38
      sim_grid_pos_y: 1536958.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466524.25
      sim_grid_pos_y: 1536930.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1466471.38
      sim_grid_pos_y: 1536712.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466066.38
      sim_grid_pos_y: 1536368.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1465917
      sim_grid_pos_y: 1536484.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1465835.12
      sim_grid_pos_y: 1536174.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1466140.5
      sim_grid_pos_y: 1535197
    }
    terrain_level_point {
      sim_grid_pos_x: 1464731.5
      sim_grid_pos_y: 1535205.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463721.38
      sim_grid_pos_y: 1535732
    }
    terrain_level_point {
      sim_grid_pos_x: 1463122.62
      sim_grid_pos_y: 1536752.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464276.5
      sim_grid_pos_y: 1538079.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464308.12
      sim_grid_pos_y: 1538122.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464321.75
      sim_grid_pos_y: 1538297
    }
    terrain_level_point {
      sim_grid_pos_x: 1464352.88
      sim_grid_pos_y: 1538482.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464439.75
      sim_grid_pos_y: 1538712.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464573
      sim_grid_pos_y: 1538867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464630.88
      sim_grid_pos_y: 1539075
    }
    terrain_level_point {
      sim_grid_pos_x: 1464825.25
      sim_grid_pos_y: 1539507.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464875
      sim_grid_pos_y: 1540649
    }
    terrain_level_point {
      sim_grid_pos_x: 1465982.88
      sim_grid_pos_y: 1540553.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466917.12
      sim_grid_pos_y: 1540110.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1466763
      sim_grid_pos_y: 1539718.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1466793.88
      sim_grid_pos_y: 1539645.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.46686e+06
      sim_grid_pos_y: 1.53937e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1467277.12
      sim_grid_pos_y: 1539107.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466965.75
      sim_grid_pos_y: 1538404.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1467251
      sim_grid_pos_y: 1538203.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1467256.12
      sim_grid_pos_y: 1537365.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1466987.5
      sim_grid_pos_y: 1536992
    }
    terrain_level_point {
      sim_grid_pos_x: 1466690.12
      sim_grid_pos_y: 1536832.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1466634.5
      sim_grid_pos_y: 1536819.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1466590.75
      sim_grid_pos_y: 1536639.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1466070.25
      sim_grid_pos_y: 1536197.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1465994.5
      sim_grid_pos_y: 1536255.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1465971.5
      sim_grid_pos_y: 1536168.5
    }
  }
}
