terrain_level_data {
  terrain_level: 14
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 484789.438
      sim_grid_pos_y: 2014661.12
    }
    terrain_level_point {
      sim_grid_pos_x: 484006.5
      sim_grid_pos_y: 2015815
    }
    terrain_level_point {
      sim_grid_pos_x: 484908.531
      sim_grid_pos_y: 2018213.88
    }
    terrain_level_point {
      sim_grid_pos_x: 486567.938
      sim_grid_pos_y: 2021945.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487916.406
      sim_grid_pos_y: 2021922.25
    }
    terrain_level_point {
      sim_grid_pos_x: 487935.531
      sim_grid_pos_y: 2021218.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487062.75
      sim_grid_pos_y: 2018458.62
    }
    terrain_level_point {
      sim_grid_pos_x: 486634.656
      sim_grid_pos_y: 2017106.12
    }
    terrain_level_point {
      sim_grid_pos_x: 486386.906
      sim_grid_pos_y: 2016764.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485834.5
      sim_grid_pos_y: 2016208.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485436.344
      sim_grid_pos_y: 2016285
    }
    terrain_level_point {
      sim_grid_pos_x: 485199.531
      sim_grid_pos_y: 2015589.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485116.781
      sim_grid_pos_y: 2015617.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484990.906
      sim_grid_pos_y: 2015204
    }
    terrain_level_point {
      sim_grid_pos_x: 484954.75
      sim_grid_pos_y: 2015092.12
    }
    terrain_level_point {
      sim_grid_pos_x: 484986.688
      sim_grid_pos_y: 2014924.25
    }
    terrain_level_point {
      sim_grid_pos_x: 484975
      sim_grid_pos_y: 2014751.25
    }
    terrain_level_point {
      sim_grid_pos_x: 484925.938
      sim_grid_pos_y: 2014598.25
    }
    terrain_level_point {
      sim_grid_pos_x: 484783.719
      sim_grid_pos_y: 2014387
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 484796.406
      sim_grid_pos_y: 2014350.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484752.5
      sim_grid_pos_y: 2014364.62
    }
    terrain_level_point {
      sim_grid_pos_x: 484758.469
      sim_grid_pos_y: 2014652
    }
    terrain_level_point {
      sim_grid_pos_x: 483972.125
      sim_grid_pos_y: 2015810.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484880.062
      sim_grid_pos_y: 2018225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486548.125
      sim_grid_pos_y: 2021976.62
    }
    terrain_level_point {
      sim_grid_pos_x: 487946.375
      sim_grid_pos_y: 2021952.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487966.406
      sim_grid_pos_y: 2021214.12
    }
    terrain_level_point {
      sim_grid_pos_x: 487092.094
      sim_grid_pos_y: 2018449.38
    }
    terrain_level_point {
      sim_grid_pos_x: 487092.062
      sim_grid_pos_y: 2018449.38
    }
    terrain_level_point {
      sim_grid_pos_x: 486662.469
      sim_grid_pos_y: 2017092.12
    }
    terrain_level_point {
      sim_grid_pos_x: 486410.406
      sim_grid_pos_y: 2016744.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485844.781
      sim_grid_pos_y: 2016175
    }
    terrain_level_point {
      sim_grid_pos_x: 485456.844
      sim_grid_pos_y: 2016249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485218.719
      sim_grid_pos_y: 2015550.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485136.969
      sim_grid_pos_y: 2015578.38
    }
    terrain_level_point {
      sim_grid_pos_x: 485020.281
      sim_grid_pos_y: 2015194.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484986.469
      sim_grid_pos_y: 2015090.12
    }
    terrain_level_point {
      sim_grid_pos_x: 485017.625
      sim_grid_pos_y: 2014926.12
    }
    terrain_level_point {
      sim_grid_pos_x: 485005.438
      sim_grid_pos_y: 2014745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 484953.906
      sim_grid_pos_y: 2014584.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 484809.062
      sim_grid_pos_y: 2014314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 484721.281
      sim_grid_pos_y: 2014342.25
    }
    terrain_level_point {
      sim_grid_pos_x: 484727.531
      sim_grid_pos_y: 2014642.75
    }
    terrain_level_point {
      sim_grid_pos_x: 483937.719
      sim_grid_pos_y: 2015806.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484851.594
      sim_grid_pos_y: 2018237.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486528.281
      sim_grid_pos_y: 2022007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487976.312
      sim_grid_pos_y: 2021982.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487997.281
      sim_grid_pos_y: 2021209.88
    }
    terrain_level_point {
      sim_grid_pos_x: 487121.406
      sim_grid_pos_y: 2.01844e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 487121.406
      sim_grid_pos_y: 2.01844e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 486690.281
      sim_grid_pos_y: 2017078.12
    }
    terrain_level_point {
      sim_grid_pos_x: 486433.938
      sim_grid_pos_y: 2016724.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485855.062
      sim_grid_pos_y: 2016141.62
    }
    terrain_level_point {
      sim_grid_pos_x: 485477.312
      sim_grid_pos_y: 2016214.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485237.938
      sim_grid_pos_y: 2015511.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485157.125
      sim_grid_pos_y: 2015539
    }
    terrain_level_point {
      sim_grid_pos_x: 485049.625
      sim_grid_pos_y: 2015185.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485018.125
      sim_grid_pos_y: 2015088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485048.594
      sim_grid_pos_y: 2014928
    }
    terrain_level_point {
      sim_grid_pos_x: 485035.875
      sim_grid_pos_y: 2014739.62
    }
    terrain_level_point {
      sim_grid_pos_x: 484981.844
      sim_grid_pos_y: 2014571.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 484821.719
      sim_grid_pos_y: 2014278.25
    }
    terrain_level_point {
      sim_grid_pos_x: 484690.031
      sim_grid_pos_y: 2014319.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484696.562
      sim_grid_pos_y: 2014633.62
    }
    terrain_level_point {
      sim_grid_pos_x: 483903.312
      sim_grid_pos_y: 2015802.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484823.125
      sim_grid_pos_y: 2018248.88
    }
    terrain_level_point {
      sim_grid_pos_x: 486508.469
      sim_grid_pos_y: 2022038.88
    }
    terrain_level_point {
      sim_grid_pos_x: 488006.25
      sim_grid_pos_y: 2022013
    }
    terrain_level_point {
      sim_grid_pos_x: 488028.188
      sim_grid_pos_y: 2021205.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487150.719
      sim_grid_pos_y: 2018430.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487150.719
      sim_grid_pos_y: 2018430.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486718.125
      sim_grid_pos_y: 2017064.12
    }
    terrain_level_point {
      sim_grid_pos_x: 486457.438
      sim_grid_pos_y: 2016704.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485865.344
      sim_grid_pos_y: 2016108.38
    }
    terrain_level_point {
      sim_grid_pos_x: 485497.781
      sim_grid_pos_y: 2016179.12
    }
    terrain_level_point {
      sim_grid_pos_x: 485257.125
      sim_grid_pos_y: 2015472.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485177.312
      sim_grid_pos_y: 2015499.62
    }
    terrain_level_point {
      sim_grid_pos_x: 485078.969
      sim_grid_pos_y: 2015176.38
    }
    terrain_level_point {
      sim_grid_pos_x: 485049.812
      sim_grid_pos_y: 2015086.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485079.531
      sim_grid_pos_y: 2014929.88
    }
    terrain_level_point {
      sim_grid_pos_x: 485066.312
      sim_grid_pos_y: 2014733.88
    }
    terrain_level_point {
      sim_grid_pos_x: 485009.812
      sim_grid_pos_y: 2014557.62
    }
  }
}
