terrain_level_data {
  terrain_level: 4654
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1497945.5
      sim_grid_pos_y: 1690970.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1497731.5
      sim_grid_pos_y: 1691228.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1497452.12
      sim_grid_pos_y: 1691399.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1497428.88
      sim_grid_pos_y: 1691588.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1497656.25
      sim_grid_pos_y: 1691730.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1497982.75
      sim_grid_pos_y: 1691563.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1498201.5
      sim_grid_pos_y: 1691401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1498348.88
      sim_grid_pos_y: 1691257.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1498189
      sim_grid_pos_y: 1691036.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1497901.38
      sim_grid_pos_y: 1690830.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1497649.75
      sim_grid_pos_y: 1691134.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1497337.25
      sim_grid_pos_y: 1691325.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1497297.12
      sim_grid_pos_y: 1691651.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1497650.25
      sim_grid_pos_y: 1691872
    }
    terrain_level_point {
      sim_grid_pos_x: 1498047.75
      sim_grid_pos_y: 1691668
    }
    terrain_level_point {
      sim_grid_pos_x: 1498281.38
      sim_grid_pos_y: 1691495.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1498510.75
      sim_grid_pos_y: 1691271.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1498263.25
      sim_grid_pos_y: 1690929.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1497872
      sim_grid_pos_y: 1690737.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1497595.38
      sim_grid_pos_y: 1691071.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1497260.62
      sim_grid_pos_y: 1691276.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1497209.38
      sim_grid_pos_y: 1691693.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1497646.38
      sim_grid_pos_y: 1691966.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1498091.25
      sim_grid_pos_y: 1691738
    }
    terrain_level_point {
      sim_grid_pos_x: 1498334.75
      sim_grid_pos_y: 1691558
    }
    terrain_level_point {
      sim_grid_pos_x: 1498618.75
      sim_grid_pos_y: 1691280.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1498312.75
      sim_grid_pos_y: 1690857.88
    }
  }
}
