terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1155327.88
      sim_grid_pos_y: 1389328.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154213.25
      sim_grid_pos_y: 1392470.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1155169
      sim_grid_pos_y: 1392803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1155916.12
      sim_grid_pos_y: 1393059
    }
    terrain_level_point {
      sim_grid_pos_x: 1155376.62
      sim_grid_pos_y: 1393687.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1155398.75
      sim_grid_pos_y: 1393503
    }
    terrain_level_point {
      sim_grid_pos_x: 1155334
      sim_grid_pos_y: 1393136.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1154251.38
      sim_grid_pos_y: 1392744.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1154118.62
      sim_grid_pos_y: 1392690.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154054.12
      sim_grid_pos_y: 1392608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153998.62
      sim_grid_pos_y: 1392470.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154009.62
      sim_grid_pos_y: 1392333.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154284.62
      sim_grid_pos_y: 1391604.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154823.88
      sim_grid_pos_y: 1390351
    }
    terrain_level_point {
      sim_grid_pos_x: 1155267
      sim_grid_pos_y: 1389330.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1154239.5
      sim_grid_pos_y: 1392457.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155175.75
      sim_grid_pos_y: 1392784.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1155951.38
      sim_grid_pos_y: 1393049.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1155382.25
      sim_grid_pos_y: 1393712
    }
    terrain_level_point {
      sim_grid_pos_x: 1155354.38
      sim_grid_pos_y: 1393699.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1155378
      sim_grid_pos_y: 1393503.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1155315.88
      sim_grid_pos_y: 1393151.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1154244
      sim_grid_pos_y: 1392764
    }
    terrain_level_point {
      sim_grid_pos_x: 1154105.88
      sim_grid_pos_y: 1392707
    }
    terrain_level_point {
      sim_grid_pos_x: 1154036.12
      sim_grid_pos_y: 1392619
    }
    terrain_level_point {
      sim_grid_pos_x: 1153977.75
      sim_grid_pos_y: 1392473.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1153989.38
      sim_grid_pos_y: 1392329
    }
    terrain_level_point {
      sim_grid_pos_x: 1154265.62
      sim_grid_pos_y: 1391596.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1154805.12
      sim_grid_pos_y: 1390342.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155253.38
      sim_grid_pos_y: 1389310.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1155357.25
      sim_grid_pos_y: 1389306.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1154265.75
      sim_grid_pos_y: 1392445.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1155182.25
      sim_grid_pos_y: 1392764.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155986.62
      sim_grid_pos_y: 1393039.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155387.88
      sim_grid_pos_y: 1393736.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155332.25
      sim_grid_pos_y: 1393712.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1155357.25
      sim_grid_pos_y: 1393504.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1155297.75
      sim_grid_pos_y: 1393166.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1154236.62
      sim_grid_pos_y: 1392783.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154093.12
      sim_grid_pos_y: 1392724
    }
    terrain_level_point {
      sim_grid_pos_x: 1154018.25
      sim_grid_pos_y: 1392629.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1153957
      sim_grid_pos_y: 1392476.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1153969.12
      sim_grid_pos_y: 1392324.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1154246.5
      sim_grid_pos_y: 1391589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154786.25
      sim_grid_pos_y: 1390334.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1155239.75
      sim_grid_pos_y: 1389290.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1155386.62
      sim_grid_pos_y: 1389285.25
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1155570.5
      sim_grid_pos_y: 1393897.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1156013.5
      sim_grid_pos_y: 1393408.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1156038.38
      sim_grid_pos_y: 1393478.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1156405
      sim_grid_pos_y: 1393602
    }
    terrain_level_point {
      sim_grid_pos_x: 1156486.75
      sim_grid_pos_y: 1393564.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1156743.75
      sim_grid_pos_y: 1393682.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1156821.88
      sim_grid_pos_y: 1393552.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1158904.5
      sim_grid_pos_y: 1387622.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1157429.12
      sim_grid_pos_y: 1387045.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1157196.75
      sim_grid_pos_y: 1387588
    }
    terrain_level_point {
      sim_grid_pos_x: 1156558.38
      sim_grid_pos_y: 1388241.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1156400.12
      sim_grid_pos_y: 1388078.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1157047.12
      sim_grid_pos_y: 1387411.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1157199.12
      sim_grid_pos_y: 1386973.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1156993
      sim_grid_pos_y: 1386619.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1157008
      sim_grid_pos_y: 1384849.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1157397.62
      sim_grid_pos_y: 1384738.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1157562.38
      sim_grid_pos_y: 1386497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1158132.88
      sim_grid_pos_y: 1386664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1159133.5
      sim_grid_pos_y: 1387322.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1159352
      sim_grid_pos_y: 1387736.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1158444.62
      sim_grid_pos_y: 1390564.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1159267.75
      sim_grid_pos_y: 1390835.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1159239.38
      sim_grid_pos_y: 1391462.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1158739.5
      sim_grid_pos_y: 1392069.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1157625.75
      sim_grid_pos_y: 1392516.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1157097.12
      sim_grid_pos_y: 1394017.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1156241.25
      sim_grid_pos_y: 1394139.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1156009.25
      sim_grid_pos_y: 1394862.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154189.88
      sim_grid_pos_y: 1396157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1151911
      sim_grid_pos_y: 1396586.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1151946.88
      sim_grid_pos_y: 1396095.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1152752.38
      sim_grid_pos_y: 1396098.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1153208.75
      sim_grid_pos_y: 1395952
    }
    terrain_level_point {
      sim_grid_pos_x: 1.15364e+06
      sim_grid_pos_y: 1395611.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1153757.88
      sim_grid_pos_y: 1395605.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1153931.38
      sim_grid_pos_y: 1395765.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154204.5
      sim_grid_pos_y: 1395620.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1154231.62
      sim_grid_pos_y: 1395439
    }
    terrain_level_point {
      sim_grid_pos_x: 1154417.25
      sim_grid_pos_y: 1395171.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1154791.75
      sim_grid_pos_y: 1395054.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155403.12
      sim_grid_pos_y: 1394709.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1155528.5
      sim_grid_pos_y: 1394324.38
    }
  }
}
terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1154452.25
      sim_grid_pos_y: 1392334
    }
    terrain_level_point {
      sim_grid_pos_x: 1155199.62
      sim_grid_pos_y: 1390073.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1155466
      sim_grid_pos_y: 1389180.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1156346
      sim_grid_pos_y: 1388180.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1156511.12
      sim_grid_pos_y: 1388360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1157223.88
      sim_grid_pos_y: 1387659.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1157468.88
      sim_grid_pos_y: 1387157
    }
    terrain_level_point {
      sim_grid_pos_x: 1158773.12
      sim_grid_pos_y: 1387623.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1156829.12
      sim_grid_pos_y: 1393146.88
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1155173.88
      sim_grid_pos_y: 1393659.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1155296.38
      sim_grid_pos_y: 1393179.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1153838.88
      sim_grid_pos_y: 1392647.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154802.38
      sim_grid_pos_y: 1390270.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155019.75
      sim_grid_pos_y: 1389613.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154894.12
      sim_grid_pos_y: 1389586.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1154775.12
      sim_grid_pos_y: 1389968
    }
    terrain_level_point {
      sim_grid_pos_x: 1154591.75
      sim_grid_pos_y: 1389913.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154494.38
      sim_grid_pos_y: 1390135.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1154349.5
      sim_grid_pos_y: 1390160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1154165.12
      sim_grid_pos_y: 1390641
    }
    terrain_level_point {
      sim_grid_pos_x: 1154026.62
      sim_grid_pos_y: 1390696
    }
    terrain_level_point {
      sim_grid_pos_x: 1153909.38
      sim_grid_pos_y: 1390977.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1154045.75
      sim_grid_pos_y: 1391100.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1153856.62
      sim_grid_pos_y: 1391563.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1153598.5
      sim_grid_pos_y: 1391975.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153314
      sim_grid_pos_y: 1392022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1153446.88
      sim_grid_pos_y: 1392434.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1153358.12
      sim_grid_pos_y: 1392776.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153349.5
      sim_grid_pos_y: 1393035.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1153537
      sim_grid_pos_y: 1393276.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153702.25
      sim_grid_pos_y: 1393177
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1.15488e+06
      sim_grid_pos_y: 1389562.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1154761.62
      sim_grid_pos_y: 1389942.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154580.25
      sim_grid_pos_y: 1389888.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.15448e+06
      sim_grid_pos_y: 1390117.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1154334.62
      sim_grid_pos_y: 1390142
    }
    terrain_level_point {
      sim_grid_pos_x: 1154149.25
      sim_grid_pos_y: 1390625.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1154011.12
      sim_grid_pos_y: 1390680.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153884.88
      sim_grid_pos_y: 1390982.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1154021.25
      sim_grid_pos_y: 1391106
    }
    terrain_level_point {
      sim_grid_pos_x: 1153838.25
      sim_grid_pos_y: 1391553.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1153586
      sim_grid_pos_y: 1391956.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153287.12
      sim_grid_pos_y: 1392006.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153425.5
      sim_grid_pos_y: 1392435.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153337.75
      sim_grid_pos_y: 1392773.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153328.75
      sim_grid_pos_y: 1393042
    }
    terrain_level_point {
      sim_grid_pos_x: 1153532
      sim_grid_pos_y: 1393303
    }
    terrain_level_point {
      sim_grid_pos_x: 1153704.75
      sim_grid_pos_y: 1393199.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1155188.38
      sim_grid_pos_y: 1393686
    }
    terrain_level_point {
      sim_grid_pos_x: 1155320.75
      sim_grid_pos_y: 1393166.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1153865.88
      sim_grid_pos_y: 1392635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154821.75
      sim_grid_pos_y: 1390277.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1155046.38
      sim_grid_pos_y: 1389597.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1154866
      sim_grid_pos_y: 1389538.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1154748.12
      sim_grid_pos_y: 1389917
    }
    terrain_level_point {
      sim_grid_pos_x: 1154568.75
      sim_grid_pos_y: 1389863.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1154465.62
      sim_grid_pos_y: 1390099.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1154319.62
      sim_grid_pos_y: 1390123.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1154133.25
      sim_grid_pos_y: 1390609.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153995.5
      sim_grid_pos_y: 1390664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1153860.38
      sim_grid_pos_y: 1390988.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1153996.88
      sim_grid_pos_y: 1391111.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.15382e+06
      sim_grid_pos_y: 1391544.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153573.5
      sim_grid_pos_y: 1391937.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1153260.38
      sim_grid_pos_y: 1391990.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153404.12
      sim_grid_pos_y: 1392436.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1153317.25
      sim_grid_pos_y: 1392770.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1153308
      sim_grid_pos_y: 1393048.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1153527
      sim_grid_pos_y: 1.39333e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1153707.25
      sim_grid_pos_y: 1393221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1155202.88
      sim_grid_pos_y: 1393712.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1155345.25
      sim_grid_pos_y: 1393153.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1153892.88
      sim_grid_pos_y: 1392623.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1154841
      sim_grid_pos_y: 1390285
    }
    terrain_level_point {
      sim_grid_pos_x: 1155073.12
      sim_grid_pos_y: 1389582.38
    }
  }
}
