terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 472821.406
      sim_grid_pos_y: 2006174.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472680.781
      sim_grid_pos_y: 2006520.25
    }
    terrain_level_point {
      sim_grid_pos_x: 472579.188
      sim_grid_pos_y: 2007036.88
    }
    terrain_level_point {
      sim_grid_pos_x: 472179.688
      sim_grid_pos_y: 2008152.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471952.625
      sim_grid_pos_y: 2008511
    }
    terrain_level_point {
      sim_grid_pos_x: 471615.531
      sim_grid_pos_y: 2008620.38
    }
    terrain_level_point {
      sim_grid_pos_x: 471499.188
      sim_grid_pos_y: 2008915.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471741.688
      sim_grid_pos_y: 2009167.88
    }
    terrain_level_point {
      sim_grid_pos_x: 471844.062
      sim_grid_pos_y: 2009401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471751.562
      sim_grid_pos_y: 2009613.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471480.969
      sim_grid_pos_y: 2009865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471321.375
      sim_grid_pos_y: 2010241.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471078.969
      sim_grid_pos_y: 2010632.12
    }
    terrain_level_point {
      sim_grid_pos_x: 470838.375
      sim_grid_pos_y: 2010672.88
    }
    terrain_level_point {
      sim_grid_pos_x: 470834.844
      sim_grid_pos_y: 2010788.75
    }
    terrain_level_point {
      sim_grid_pos_x: 470987.375
      sim_grid_pos_y: 2010987.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471004.562
      sim_grid_pos_y: 2011089.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471166.219
      sim_grid_pos_y: 2011122.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471414.938
      sim_grid_pos_y: 2011053.88
    }
    terrain_level_point {
      sim_grid_pos_x: 471724.438
      sim_grid_pos_y: 2011189
    }
    terrain_level_point {
      sim_grid_pos_x: 471863
      sim_grid_pos_y: 2011423.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471758.906
      sim_grid_pos_y: 2011766.88
    }
    terrain_level_point {
      sim_grid_pos_x: 471659.625
      sim_grid_pos_y: 2012337.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472038.875
      sim_grid_pos_y: 2013740.12
    }
    terrain_level_point {
      sim_grid_pos_x: 472354.938
      sim_grid_pos_y: 2014092.38
    }
    terrain_level_point {
      sim_grid_pos_x: 472757.375
      sim_grid_pos_y: 2014174.75
    }
    terrain_level_point {
      sim_grid_pos_x: 472880.812
      sim_grid_pos_y: 2014065.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472891.75
      sim_grid_pos_y: 2013669.88
    }
    terrain_level_point {
      sim_grid_pos_x: 472776.688
      sim_grid_pos_y: 2013653.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472659.031
      sim_grid_pos_y: 2013351.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472791.75
      sim_grid_pos_y: 2012682.88
    }
    terrain_level_point {
      sim_grid_pos_x: 473615.656
      sim_grid_pos_y: 2011826.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474325.5
      sim_grid_pos_y: 2009487
    }
    terrain_level_point {
      sim_grid_pos_x: 475250.906
      sim_grid_pos_y: 2009823.38
    }
    terrain_level_point {
      sim_grid_pos_x: 475835.688
      sim_grid_pos_y: 2009785.5
    }
    terrain_level_point {
      sim_grid_pos_x: 476012.5
      sim_grid_pos_y: 2011822.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476208.219
      sim_grid_pos_y: 2012157.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476136.031
      sim_grid_pos_y: 2012222.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476876.469
      sim_grid_pos_y: 2013427.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477555.531
      sim_grid_pos_y: 2013197.5
    }
    terrain_level_point {
      sim_grid_pos_x: 477350.25
      sim_grid_pos_y: 2012684.88
    }
    terrain_level_point {
      sim_grid_pos_x: 476967.094
      sim_grid_pos_y: 2012022.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476917.562
      sim_grid_pos_y: 2010773.38
    }
    terrain_level_point {
      sim_grid_pos_x: 477096.375
      sim_grid_pos_y: 2010549.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477306.031
      sim_grid_pos_y: 2010473.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477319.875
      sim_grid_pos_y: 2010242.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477044.094
      sim_grid_pos_y: 2010139.38
    }
    terrain_level_point {
      sim_grid_pos_x: 477040.594
      sim_grid_pos_y: 2009342.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476240.625
      sim_grid_pos_y: 2008078.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476860
      sim_grid_pos_y: 2007304.38
    }
    terrain_level_point {
      sim_grid_pos_x: 477312.656
      sim_grid_pos_y: 2007082.12
    }
    terrain_level_point {
      sim_grid_pos_x: 477627.875
      sim_grid_pos_y: 2006613.5
    }
    terrain_level_point {
      sim_grid_pos_x: 477808.25
      sim_grid_pos_y: 2006185.38
    }
    terrain_level_point {
      sim_grid_pos_x: 478719.594
      sim_grid_pos_y: 2005674.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479109.156
      sim_grid_pos_y: 2005582.62
    }
    terrain_level_point {
      sim_grid_pos_x: 478799.188
      sim_grid_pos_y: 2005151
    }
    terrain_level_point {
      sim_grid_pos_x: 477382.062
      sim_grid_pos_y: 2006069.25
    }
    terrain_level_point {
      sim_grid_pos_x: 473971.812
      sim_grid_pos_y: 2006005
    }
    terrain_level_point {
      sim_grid_pos_x: 473899.312
      sim_grid_pos_y: 2006211.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 478807.062
      sim_grid_pos_y: 2005109.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477373.219
      sim_grid_pos_y: 2006038.38
    }
    terrain_level_point {
      sim_grid_pos_x: 473950.156
      sim_grid_pos_y: 2005973.88
    }
    terrain_level_point {
      sim_grid_pos_x: 473877.781
      sim_grid_pos_y: 2006179.88
    }
    terrain_level_point {
      sim_grid_pos_x: 472801
      sim_grid_pos_y: 2006143.12
    }
    terrain_level_point {
      sim_grid_pos_x: 472651.156
      sim_grid_pos_y: 2006511.38
    }
    terrain_level_point {
      sim_grid_pos_x: 472549.469
      sim_grid_pos_y: 2007028.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472151.875
      sim_grid_pos_y: 2008139.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471932.562
      sim_grid_pos_y: 2008485.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471592.25
      sim_grid_pos_y: 2008595.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471463.344
      sim_grid_pos_y: 2008922.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471715.719
      sim_grid_pos_y: 2009185.25
    }
    terrain_level_point {
      sim_grid_pos_x: 471810.5
      sim_grid_pos_y: 2009401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471725.938
      sim_grid_pos_y: 2009595.38
    }
    terrain_level_point {
      sim_grid_pos_x: 471455.219
      sim_grid_pos_y: 2009847.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471294
      sim_grid_pos_y: 2010227.38
    }
    terrain_level_point {
      sim_grid_pos_x: 471060.156
      sim_grid_pos_y: 2010604.12
    }
    terrain_level_point {
      sim_grid_pos_x: 470808.406
      sim_grid_pos_y: 2010646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 470803.75
      sim_grid_pos_y: 2010798.75
    }
    terrain_level_point {
      sim_grid_pos_x: 470958.312
      sim_grid_pos_y: 2011000.38
    }
    terrain_level_point {
      sim_grid_pos_x: 470977.75
      sim_grid_pos_y: 2011115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471167.312
      sim_grid_pos_y: 2011153.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471412.594
      sim_grid_pos_y: 2011086.38
    }
    terrain_level_point {
      sim_grid_pos_x: 471703.031
      sim_grid_pos_y: 2011213.25
    }
    terrain_level_point {
      sim_grid_pos_x: 471829.625
      sim_grid_pos_y: 2011427.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471728.938
      sim_grid_pos_y: 2011759.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471628.156
      sim_grid_pos_y: 2012338.88
    }
    terrain_level_point {
      sim_grid_pos_x: 472011.094
      sim_grid_pos_y: 2013755.25
    }
    terrain_level_point {
      sim_grid_pos_x: 472338.812
      sim_grid_pos_y: 2014120.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472766.25
      sim_grid_pos_y: 2014208
    }
    terrain_level_point {
      sim_grid_pos_x: 472911.219
      sim_grid_pos_y: 2014079.75
    }
    terrain_level_point {
      sim_grid_pos_x: 472923.25
      sim_grid_pos_y: 2013643.25
    }
    terrain_level_point {
      sim_grid_pos_x: 472798.844
      sim_grid_pos_y: 2013625.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472690.938
      sim_grid_pos_y: 2013348.88
    }
    terrain_level_point {
      sim_grid_pos_x: 472820.188
      sim_grid_pos_y: 2012697.62
    }
    terrain_level_point {
      sim_grid_pos_x: 473642.969
      sim_grid_pos_y: 2011842.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474345.5
      sim_grid_pos_y: 2009527
    }
    terrain_level_point {
      sim_grid_pos_x: 475246.438
      sim_grid_pos_y: 2009854.38
    }
    terrain_level_point {
      sim_grid_pos_x: 475807.656
      sim_grid_pos_y: 2009818.12
    }
    terrain_level_point {
      sim_grid_pos_x: 475982.438
      sim_grid_pos_y: 2011832.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476169
      sim_grid_pos_y: 2012151.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476096.375
      sim_grid_pos_y: 2012216.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476863.094
      sim_grid_pos_y: 2013464.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477596.156
      sim_grid_pos_y: 2013216.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477377.969
      sim_grid_pos_y: 2012671.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476997.5
      sim_grid_pos_y: 2012013.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476948.719
      sim_grid_pos_y: 2010783.62
    }
    terrain_level_point {
      sim_grid_pos_x: 477115
      sim_grid_pos_y: 2010575.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477335.5
      sim_grid_pos_y: 2010495.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477351.938
      sim_grid_pos_y: 2010222.12
    }
    terrain_level_point {
      sim_grid_pos_x: 477074.75
      sim_grid_pos_y: 2010118
    }
    terrain_level_point {
      sim_grid_pos_x: 477071.312
      sim_grid_pos_y: 2009333.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476278.344
      sim_grid_pos_y: 2008080.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476879.719
      sim_grid_pos_y: 2007328.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477333.594
      sim_grid_pos_y: 2007106.12
    }
    terrain_level_point {
      sim_grid_pos_x: 477655.062
      sim_grid_pos_y: 2006628.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477832.5
      sim_grid_pos_y: 2006207
    }
    terrain_level_point {
      sim_grid_pos_x: 478730.844
      sim_grid_pos_y: 2005703.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479160.938
      sim_grid_pos_y: 2005602.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 478814.969
      sim_grid_pos_y: 2005067.5
    }
    terrain_level_point {
      sim_grid_pos_x: 477364.375
      sim_grid_pos_y: 2006007.38
    }
    terrain_level_point {
      sim_grid_pos_x: 473928.5
      sim_grid_pos_y: 2005942.62
    }
    terrain_level_point {
      sim_grid_pos_x: 473856.25
      sim_grid_pos_y: 2006148.38
    }
    terrain_level_point {
      sim_grid_pos_x: 472780.594
      sim_grid_pos_y: 2006111.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472621.562
      sim_grid_pos_y: 2006502.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472519.719
      sim_grid_pos_y: 2007020.5
    }
    terrain_level_point {
      sim_grid_pos_x: 472124.062
      sim_grid_pos_y: 2008125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471912.531
      sim_grid_pos_y: 2008459.25
    }
    terrain_level_point {
      sim_grid_pos_x: 471568.938
      sim_grid_pos_y: 2008570.88
    }
    terrain_level_point {
      sim_grid_pos_x: 471427.5
      sim_grid_pos_y: 2008929.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471689.75
      sim_grid_pos_y: 2009202.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471776.938
      sim_grid_pos_y: 2009401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471700.281
      sim_grid_pos_y: 2009577.25
    }
    terrain_level_point {
      sim_grid_pos_x: 471429.469
      sim_grid_pos_y: 2009829.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471266.594
      sim_grid_pos_y: 2010213.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471041.344
      sim_grid_pos_y: 2010576.12
    }
    terrain_level_point {
      sim_grid_pos_x: 470778.438
      sim_grid_pos_y: 2010620.62
    }
    terrain_level_point {
      sim_grid_pos_x: 470772.688
      sim_grid_pos_y: 2010808.75
    }
    terrain_level_point {
      sim_grid_pos_x: 470929.25
      sim_grid_pos_y: 2011013
    }
    terrain_level_point {
      sim_grid_pos_x: 470950.938
      sim_grid_pos_y: 2011141.75
    }
    terrain_level_point {
      sim_grid_pos_x: 471168.438
      sim_grid_pos_y: 2011185.38
    }
    terrain_level_point {
      sim_grid_pos_x: 471410.25
      sim_grid_pos_y: 2011119
    }
    terrain_level_point {
      sim_grid_pos_x: 471681.625
      sim_grid_pos_y: 2011237.5
    }
    terrain_level_point {
      sim_grid_pos_x: 471796.281
      sim_grid_pos_y: 2011431.12
    }
    terrain_level_point {
      sim_grid_pos_x: 471698.969
      sim_grid_pos_y: 2011752.62
    }
    terrain_level_point {
      sim_grid_pos_x: 471596.688
      sim_grid_pos_y: 2012340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 471983.312
      sim_grid_pos_y: 2013770.25
    }
    terrain_level_point {
      sim_grid_pos_x: 472322.719
      sim_grid_pos_y: 2014148.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472775.125
      sim_grid_pos_y: 2014241.12
    }
    terrain_level_point {
      sim_grid_pos_x: 472941.594
      sim_grid_pos_y: 2014093.88
    }
    terrain_level_point {
      sim_grid_pos_x: 472954.75
      sim_grid_pos_y: 2013616.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472820.969
      sim_grid_pos_y: 2013597.62
    }
    terrain_level_point {
      sim_grid_pos_x: 472722.844
      sim_grid_pos_y: 2013346
    }
    terrain_level_point {
      sim_grid_pos_x: 472848.594
      sim_grid_pos_y: 2012712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 473670.25
      sim_grid_pos_y: 2011858.5
    }
    terrain_level_point {
      sim_grid_pos_x: 474365.531
      sim_grid_pos_y: 2009567
    }
    terrain_level_point {
      sim_grid_pos_x: 475242
      sim_grid_pos_y: 2009885.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475779.594
      sim_grid_pos_y: 2009850.75
    }
    terrain_level_point {
      sim_grid_pos_x: 475952.406
      sim_grid_pos_y: 2011841.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476129.75
      sim_grid_pos_y: 2012145.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476056.719
      sim_grid_pos_y: 2012210.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476849.75
      sim_grid_pos_y: 2013501.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477636.781
      sim_grid_pos_y: 2013235
    }
    terrain_level_point {
      sim_grid_pos_x: 477405.719
      sim_grid_pos_y: 2012657.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477027.938
      sim_grid_pos_y: 2012004.62
    }
    terrain_level_point {
      sim_grid_pos_x: 476979.938
      sim_grid_pos_y: 2010793.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477133.625
      sim_grid_pos_y: 2010601.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477365
      sim_grid_pos_y: 2010517.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477384
      sim_grid_pos_y: 2010201.25
    }
    terrain_level_point {
      sim_grid_pos_x: 477105.406
      sim_grid_pos_y: 2010096.75
    }
    terrain_level_point {
      sim_grid_pos_x: 477102.031
      sim_grid_pos_y: 2009324.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476316.062
      sim_grid_pos_y: 2008082.38
    }
    terrain_level_point {
      sim_grid_pos_x: 476899.438
      sim_grid_pos_y: 2007353.5
    }
    terrain_level_point {
      sim_grid_pos_x: 477354.531
      sim_grid_pos_y: 2007130.12
    }
    terrain_level_point {
      sim_grid_pos_x: 477682.25
      sim_grid_pos_y: 2006642.88
    }
    terrain_level_point {
      sim_grid_pos_x: 477856.75
      sim_grid_pos_y: 2006228.62
    }
    terrain_level_point {
      sim_grid_pos_x: 478742.125
      sim_grid_pos_y: 2005732.38
    }
    terrain_level_point {
      sim_grid_pos_x: 479212.75
      sim_grid_pos_y: 2005621.5
    }
  }
}
