terrain_level_data {
  terrain_level: 389
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1431698
      sim_grid_pos_y: 1638328.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1431160.75
      sim_grid_pos_y: 1638638.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.4308e+06
      sim_grid_pos_y: 1638676.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430814.75
      sim_grid_pos_y: 1638915
    }
    terrain_level_point {
      sim_grid_pos_x: 1430609.62
      sim_grid_pos_y: 1639156.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430400.12
      sim_grid_pos_y: 1639290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430277.62
      sim_grid_pos_y: 1639575.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430081.25
      sim_grid_pos_y: 1639673.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429965.38
      sim_grid_pos_y: 1639464.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429986.12
      sim_grid_pos_y: 1639289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429995.75
      sim_grid_pos_y: 1639096
    }
    terrain_level_point {
      sim_grid_pos_x: 1429900.25
      sim_grid_pos_y: 1639125.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429662.25
      sim_grid_pos_y: 1639073.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429221.12
      sim_grid_pos_y: 1639230.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1429054.38
      sim_grid_pos_y: 1639356
    }
    terrain_level_point {
      sim_grid_pos_x: 1429122.25
      sim_grid_pos_y: 1639454.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429153.25
      sim_grid_pos_y: 1639619.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429172
      sim_grid_pos_y: 1639877
    }
    terrain_level_point {
      sim_grid_pos_x: 1429113.88
      sim_grid_pos_y: 1639983.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1428914.88
      sim_grid_pos_y: 1639940.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1428813.38
      sim_grid_pos_y: 1640074.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428695.12
      sim_grid_pos_y: 1640001.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1428275.12
      sim_grid_pos_y: 1640526.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1427473
      sim_grid_pos_y: 1640105.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1427390.62
      sim_grid_pos_y: 1640064.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1427548.75
      sim_grid_pos_y: 1639870.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1427826.75
      sim_grid_pos_y: 1639333.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1428662.38
      sim_grid_pos_y: 1638682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1428977
      sim_grid_pos_y: 1638496.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1429466.38
      sim_grid_pos_y: 1638238.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429942.25
      sim_grid_pos_y: 1638015.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430094.5
      sim_grid_pos_y: 1637961.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430733.25
      sim_grid_pos_y: 1637960.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.43106e+06
      sim_grid_pos_y: 1637965
    }
    terrain_level_point {
      sim_grid_pos_x: 1431191.5
      sim_grid_pos_y: 1637967
    }
    terrain_level_point {
      sim_grid_pos_x: 1431519.25
      sim_grid_pos_y: 1637942.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1431788
      sim_grid_pos_y: 1637947.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1432000.25
      sim_grid_pos_y: 1638258.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1431838.75
      sim_grid_pos_y: 1638286.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1431804.5
      sim_grid_pos_y: 1637917.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1432052.62
      sim_grid_pos_y: 1638281
    }
    terrain_level_point {
      sim_grid_pos_x: 1431845.75
      sim_grid_pos_y: 1638316.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431710.25
      sim_grid_pos_y: 1638357
    }
    terrain_level_point {
      sim_grid_pos_x: 1431170.5
      sim_grid_pos_y: 1638668.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430832.5
      sim_grid_pos_y: 1638704.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430846.25
      sim_grid_pos_y: 1638925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430630.12
      sim_grid_pos_y: 1639179.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430424.62
      sim_grid_pos_y: 1639311.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430301.38
      sim_grid_pos_y: 1639597.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1430068.62
      sim_grid_pos_y: 1639713.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1429933.62
      sim_grid_pos_y: 1639471.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429955.5
      sim_grid_pos_y: 1639287.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429962.88
      sim_grid_pos_y: 1639138.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429901.5
      sim_grid_pos_y: 1639156.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429664.25
      sim_grid_pos_y: 1639105.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429235.88
      sim_grid_pos_y: 1639258.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429096.5
      sim_grid_pos_y: 1639362.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429151.25
      sim_grid_pos_y: 1639442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429183.75
      sim_grid_pos_y: 1639615.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429203.38
      sim_grid_pos_y: 1639883.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1429129.88
      sim_grid_pos_y: 1640018.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1428927.62
      sim_grid_pos_y: 1639974.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1428821
      sim_grid_pos_y: 1640115.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428702.12
      sim_grid_pos_y: 1640041.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1428283.25
      sim_grid_pos_y: 1640565.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1427458.88
      sim_grid_pos_y: 1640132.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1427342.38
      sim_grid_pos_y: 1640075.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1427522.88
      sim_grid_pos_y: 1639853.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1427802.5
      sim_grid_pos_y: 1639313.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1428645
      sim_grid_pos_y: 1638657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1428962
      sim_grid_pos_y: 1638469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429452.62
      sim_grid_pos_y: 1638210.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429930.62
      sim_grid_pos_y: 1637986.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430089.25
      sim_grid_pos_y: 1637930.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430733.38
      sim_grid_pos_y: 1637929.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1431060.5
      sim_grid_pos_y: 1637934.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1431190.5
      sim_grid_pos_y: 1637936.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1431518.38
      sim_grid_pos_y: 1637911.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1431820.88
      sim_grid_pos_y: 1637886.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1432105
      sim_grid_pos_y: 1638303.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1431852.75
      sim_grid_pos_y: 1638346.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431722.5
      sim_grid_pos_y: 1638385.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431180.25
      sim_grid_pos_y: 1638698.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430865
      sim_grid_pos_y: 1638731.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430877.62
      sim_grid_pos_y: 1638936
    }
    terrain_level_point {
      sim_grid_pos_x: 1430650.5
      sim_grid_pos_y: 1639203.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430449.12
      sim_grid_pos_y: 1639332.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430325.25
      sim_grid_pos_y: 1639620.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430056.12
      sim_grid_pos_y: 1639754.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429902
      sim_grid_pos_y: 1639477.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429924.75
      sim_grid_pos_y: 1639284.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.42993e+06
      sim_grid_pos_y: 1639180.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429902.88
      sim_grid_pos_y: 1639188.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429666.38
      sim_grid_pos_y: 1639137.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429250.62
      sim_grid_pos_y: 1639285.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429138.5
      sim_grid_pos_y: 1639369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1429180.25
      sim_grid_pos_y: 1639430.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429214.38
      sim_grid_pos_y: 1639611.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429234.62
      sim_grid_pos_y: 1639890.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429145.88
      sim_grid_pos_y: 1640053.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1428940.25
      sim_grid_pos_y: 1640008.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428828.62
      sim_grid_pos_y: 1640156.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428709
      sim_grid_pos_y: 1640082.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1428291.5
      sim_grid_pos_y: 1640604.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427445
      sim_grid_pos_y: 1640159.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1427294.12
      sim_grid_pos_y: 1640085.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427497
      sim_grid_pos_y: 1639836.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1427778.38
      sim_grid_pos_y: 1639293.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1428627.62
      sim_grid_pos_y: 1638631.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428947
      sim_grid_pos_y: 1638442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429439
      sim_grid_pos_y: 1638183.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1429918.88
      sim_grid_pos_y: 1637958.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430083.88
      sim_grid_pos_y: 1637900.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430733.62
      sim_grid_pos_y: 1637899.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1431060.88
      sim_grid_pos_y: 1637903.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1431189.75
      sim_grid_pos_y: 1637905.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1431517.5
      sim_grid_pos_y: 1637880.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1431837.38
      sim_grid_pos_y: 1637856.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432157.38
      sim_grid_pos_y: 1638325.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431859.75
      sim_grid_pos_y: 1638376.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431734.62
      sim_grid_pos_y: 1638413.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1431189.88
      sim_grid_pos_y: 1638728.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430897.5
      sim_grid_pos_y: 1638759.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430909.12
      sim_grid_pos_y: 1638946.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430671
      sim_grid_pos_y: 1639226.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1430473.75
      sim_grid_pos_y: 1639353
    }
    terrain_level_point {
      sim_grid_pos_x: 1430349
      sim_grid_pos_y: 1639642.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1430043.5
      sim_grid_pos_y: 1639795
    }
    terrain_level_point {
      sim_grid_pos_x: 1429870.25
      sim_grid_pos_y: 1639483.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429894.12
      sim_grid_pos_y: 1639282.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429897.25
      sim_grid_pos_y: 1639218.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429668.38
      sim_grid_pos_y: 1639169.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1429265.38
      sim_grid_pos_y: 1639313
    }
    terrain_level_point {
      sim_grid_pos_x: 1429180.62
      sim_grid_pos_y: 1639376.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429209.38
      sim_grid_pos_y: 1639418.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429244.88
      sim_grid_pos_y: 1639607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429266
      sim_grid_pos_y: 1639897.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429161.75
      sim_grid_pos_y: 1640088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1428953
      sim_grid_pos_y: 1640043
    }
    terrain_level_point {
      sim_grid_pos_x: 1428836.12
      sim_grid_pos_y: 1640197.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428716
      sim_grid_pos_y: 1640122.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428299.62
      sim_grid_pos_y: 1640643.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427431.38
      sim_grid_pos_y: 1640187.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1427245.75
      sim_grid_pos_y: 1640096.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1427471.25
      sim_grid_pos_y: 1639819.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427754.12
      sim_grid_pos_y: 1639273.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1428610.25
      sim_grid_pos_y: 1638606.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1428932
      sim_grid_pos_y: 1638415.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1429425.25
      sim_grid_pos_y: 1638155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1429907.25
      sim_grid_pos_y: 1637929.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430078.62
      sim_grid_pos_y: 1637869.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430733.75
      sim_grid_pos_y: 1637868.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431061.38
      sim_grid_pos_y: 1637872.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431188.62
      sim_grid_pos_y: 1637874.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431516.75
      sim_grid_pos_y: 1637850.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1431853.88
      sim_grid_pos_y: 1637826
    }
    terrain_level_point {
      sim_grid_pos_x: 1432209.75
      sim_grid_pos_y: 1638347.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431866.75
      sim_grid_pos_y: 1638406.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431746.88
      sim_grid_pos_y: 1638442.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431199.62
      sim_grid_pos_y: 1638758.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430930.12
      sim_grid_pos_y: 1638786.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430940.62
      sim_grid_pos_y: 1638956.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430691.5
      sim_grid_pos_y: 1639250.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430498.25
      sim_grid_pos_y: 1639373.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1430372.88
      sim_grid_pos_y: 1639665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430030.88
      sim_grid_pos_y: 1639835.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429838.5
      sim_grid_pos_y: 1639489.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429863.5
      sim_grid_pos_y: 1639279.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429865.25
      sim_grid_pos_y: 1639243.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429670.5
      sim_grid_pos_y: 1639201.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.42928e+06
      sim_grid_pos_y: 1639340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429222.62
      sim_grid_pos_y: 1639383.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429238.38
      sim_grid_pos_y: 1639406.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1429275.5
      sim_grid_pos_y: 1639603.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429297.38
      sim_grid_pos_y: 1639904.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429177.75
      sim_grid_pos_y: 1640123.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1428965.75
      sim_grid_pos_y: 1640077.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1428843.75
      sim_grid_pos_y: 1640238.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428722.88
      sim_grid_pos_y: 1640163.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1428307.75
      sim_grid_pos_y: 1640682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427417.25
      sim_grid_pos_y: 1640214.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427197.5
      sim_grid_pos_y: 1640106.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427445.38
      sim_grid_pos_y: 1639802.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1427729.88
      sim_grid_pos_y: 1639253
    }
    terrain_level_point {
      sim_grid_pos_x: 1428592.88
      sim_grid_pos_y: 1638580.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1428916.88
      sim_grid_pos_y: 1638388.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429411.5
      sim_grid_pos_y: 1638128.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429895.5
      sim_grid_pos_y: 1637901.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430073.38
      sim_grid_pos_y: 1637838.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430734
      sim_grid_pos_y: 1637837.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431061.75
      sim_grid_pos_y: 1637842
    }
    terrain_level_point {
      sim_grid_pos_x: 1431187.88
      sim_grid_pos_y: 1637843.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1431515.88
      sim_grid_pos_y: 1637819.38
    }
  }
}
