terrain_level_data {
  terrain_level: 1735
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2447593.25
      sim_grid_pos_y: 1382576.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2447760.5
      sim_grid_pos_y: 1382634.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2447566
      sim_grid_pos_y: 1382918.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447716.75
      sim_grid_pos_y: 1383163.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2447794.25
      sim_grid_pos_y: 1383163.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447807
      sim_grid_pos_y: 1383353.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2447924.75
      sim_grid_pos_y: 1383428.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2448037
      sim_grid_pos_y: 1383288
    }
    terrain_level_point {
      sim_grid_pos_x: 2448027.75
      sim_grid_pos_y: 1383219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2448031
      sim_grid_pos_y: 1383099.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2448148.75
      sim_grid_pos_y: 1383007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2448459
      sim_grid_pos_y: 1382984
    }
    terrain_level_point {
      sim_grid_pos_x: 2448583.75
      sim_grid_pos_y: 1382848.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2448607
      sim_grid_pos_y: 1382667.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2448027.25
      sim_grid_pos_y: 1382558.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2447695.75
      sim_grid_pos_y: 1382446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2447379.25
      sim_grid_pos_y: 1382420.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447275.25
      sim_grid_pos_y: 1382269.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447126.75
      sim_grid_pos_y: 1382241.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2446889.75
      sim_grid_pos_y: 1382415
    }
    terrain_level_point {
      sim_grid_pos_x: 2446976.25
      sim_grid_pos_y: 1382652.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447170.25
      sim_grid_pos_y: 1382777
    }
    terrain_level_point {
      sim_grid_pos_x: 2447369.75
      sim_grid_pos_y: 1382616.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2447114.5
      sim_grid_pos_y: 1382187.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2446828.5
      sim_grid_pos_y: 1382396.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2446934
      sim_grid_pos_y: 1382686
    }
    terrain_level_point {
      sim_grid_pos_x: 2447173.5
      sim_grid_pos_y: 1.38284e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2447391.5
      sim_grid_pos_y: 1382664.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447589
      sim_grid_pos_y: 1382628.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447680.25
      sim_grid_pos_y: 1382660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2447504.75
      sim_grid_pos_y: 1382916.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447688.25
      sim_grid_pos_y: 1383215
    }
    terrain_level_point {
      sim_grid_pos_x: 2447746.25
      sim_grid_pos_y: 1383214.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2447757.75
      sim_grid_pos_y: 1383382.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447936
      sim_grid_pos_y: 1383497
    }
    terrain_level_point {
      sim_grid_pos_x: 2448090.75
      sim_grid_pos_y: 1383302.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2448079
      sim_grid_pos_y: 1383216.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2448081.5
      sim_grid_pos_y: 1383125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448168
      sim_grid_pos_y: 1383057.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448483
      sim_grid_pos_y: 1383033.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2448632.5
      sim_grid_pos_y: 1382871.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448664
      sim_grid_pos_y: 1382625.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2448040.25
      sim_grid_pos_y: 1382508.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447706.25
      sim_grid_pos_y: 1382395.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447407.75
      sim_grid_pos_y: 1382371.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2447305.5
      sim_grid_pos_y: 1382222.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2447102
      sim_grid_pos_y: 1382133
    }
    terrain_level_point {
      sim_grid_pos_x: 2446767
      sim_grid_pos_y: 1382377.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2446891.75
      sim_grid_pos_y: 1382719.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447177
      sim_grid_pos_y: 1382903.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2447413.5
      sim_grid_pos_y: 1382712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2447585
      sim_grid_pos_y: 1382681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.4476e+06
      sim_grid_pos_y: 1382687
    }
    terrain_level_point {
      sim_grid_pos_x: 2447443.75
      sim_grid_pos_y: 1382915.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447659.5
      sim_grid_pos_y: 1383266.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2447698.5
      sim_grid_pos_y: 1383266.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447708.25
      sim_grid_pos_y: 1383412.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2447947.25
      sim_grid_pos_y: 1383565.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2448144.5
      sim_grid_pos_y: 1383317.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2448130.5
      sim_grid_pos_y: 1383214
    }
    terrain_level_point {
      sim_grid_pos_x: 2448132.25
      sim_grid_pos_y: 1383150.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2448187.5
      sim_grid_pos_y: 1383107.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448507
      sim_grid_pos_y: 1383083.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2448681.25
      sim_grid_pos_y: 1382894
    }
    terrain_level_point {
      sim_grid_pos_x: 2448721
      sim_grid_pos_y: 1382584.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2448053.25
      sim_grid_pos_y: 1382458.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2447716.5
      sim_grid_pos_y: 1382345.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447436.25
      sim_grid_pos_y: 1382322.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2447335.75
      sim_grid_pos_y: 1382176.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2447089.5
      sim_grid_pos_y: 1382078.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2446705.75
      sim_grid_pos_y: 1382359
    }
    terrain_level_point {
      sim_grid_pos_x: 2446849.5
      sim_grid_pos_y: 1382753.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2447180.25
      sim_grid_pos_y: 1382966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447435.5
      sim_grid_pos_y: 1382760.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2447494.75
      sim_grid_pos_y: 1.38275e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2447382.75
      sim_grid_pos_y: 1382913.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447631
      sim_grid_pos_y: 1383317.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2447650.5
      sim_grid_pos_y: 1383317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2447658.75
      sim_grid_pos_y: 1383441.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447958.5
      sim_grid_pos_y: 1383633.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2448198.25
      sim_grid_pos_y: 1383332.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448181.75
      sim_grid_pos_y: 1383211.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2448182.75
      sim_grid_pos_y: 1383176.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2448207
      sim_grid_pos_y: 1383157.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2448531
      sim_grid_pos_y: 1383132.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.44873e+06
      sim_grid_pos_y: 1382916.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2448778
      sim_grid_pos_y: 1382542.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2448066.25
      sim_grid_pos_y: 1382409
    }
    terrain_level_point {
      sim_grid_pos_x: 2447727
      sim_grid_pos_y: 1382294.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2447464.5
      sim_grid_pos_y: 1382273.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2447366
      sim_grid_pos_y: 1382129.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2447077.25
      sim_grid_pos_y: 1382024.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2446644.25
      sim_grid_pos_y: 1382340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2446807.25
      sim_grid_pos_y: 1382787.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447183.75
      sim_grid_pos_y: 1383029.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447324
      sim_grid_pos_y: 1382916.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447602.5
      sim_grid_pos_y: 1383369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447602.5
      sim_grid_pos_y: 1383369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447609.5
      sim_grid_pos_y: 1383470.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2447969.75
      sim_grid_pos_y: 1383701.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2448252
      sim_grid_pos_y: 1383347.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2448233.25
      sim_grid_pos_y: 1383208.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448233.25
      sim_grid_pos_y: 1383206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2448555
      sim_grid_pos_y: 1383182.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448778.75
      sim_grid_pos_y: 1382939.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2448835
      sim_grid_pos_y: 1382501.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2448079.25
      sim_grid_pos_y: 1382359.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2447737.25
      sim_grid_pos_y: 1382244.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2447493
      sim_grid_pos_y: 1382224.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2447396.25
      sim_grid_pos_y: 1382083.25
    }
  }
}
