terrain_level_data {
  terrain_level: 860
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1912616.5
      sim_grid_pos_y: 454970.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1912502
      sim_grid_pos_y: 454953.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1912287.75
      sim_grid_pos_y: 454977.594
    }
    terrain_level_point {
      sim_grid_pos_x: 1912195.25
      sim_grid_pos_y: 455131.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1912308
      sim_grid_pos_y: 455288.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1912366.88
      sim_grid_pos_y: 455439.406
    }
    terrain_level_point {
      sim_grid_pos_x: 1912549.12
      sim_grid_pos_y: 455353.594
    }
    terrain_level_point {
      sim_grid_pos_x: 1912605.25
      sim_grid_pos_y: 455121.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1912792.12
      sim_grid_pos_y: 455124.906
    }
    terrain_level_point {
      sim_grid_pos_x: 1912921.62
      sim_grid_pos_y: 455037.656
    }
    terrain_level_point {
      sim_grid_pos_x: 1912847.75
      sim_grid_pos_y: 454962
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1912502.5
      sim_grid_pos_y: 454922.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1912269.25
      sim_grid_pos_y: 454948.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1912158.5
      sim_grid_pos_y: 455132.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1912280.75
      sim_grid_pos_y: 455302.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1912350.12
      sim_grid_pos_y: 455481.281
    }
    terrain_level_point {
      sim_grid_pos_x: 1912575.62
      sim_grid_pos_y: 455375.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1912629.38
      sim_grid_pos_y: 455152.406
    }
    terrain_level_point {
      sim_grid_pos_x: 1912801.25
      sim_grid_pos_y: 455155.844
    }
    terrain_level_point {
      sim_grid_pos_x: 1912969.38
      sim_grid_pos_y: 455042.594
    }
    terrain_level_point {
      sim_grid_pos_x: 1912860.38
      sim_grid_pos_y: 454930.781
    }
    terrain_level_point {
      sim_grid_pos_x: 1912618.25
      sim_grid_pos_y: 454939.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1912503
      sim_grid_pos_y: 454891.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1912250.75
      sim_grid_pos_y: 454919.906
    }
    terrain_level_point {
      sim_grid_pos_x: 1912121.75
      sim_grid_pos_y: 455134.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1912253.5
      sim_grid_pos_y: 455317.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1912333.38
      sim_grid_pos_y: 455523.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1912602
      sim_grid_pos_y: 455396.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1912653.5
      sim_grid_pos_y: 455183.656
    }
    terrain_level_point {
      sim_grid_pos_x: 1912810.38
      sim_grid_pos_y: 455186.781
    }
    terrain_level_point {
      sim_grid_pos_x: 1913017.12
      sim_grid_pos_y: 455047.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1912872.88
      sim_grid_pos_y: 454899.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1.91262e+06
      sim_grid_pos_y: 454908.531
    }
  }
}
