terrain_level_data {
  terrain_level: 8
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1.92333e+06
      sim_grid_pos_y: 1677398.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1922267
      sim_grid_pos_y: 1678027
    }
    terrain_level_point {
      sim_grid_pos_x: 1921246.75
      sim_grid_pos_y: 1678832.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1920032.88
      sim_grid_pos_y: 1679940.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1918381.5
      sim_grid_pos_y: 1682180.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1916885.25
      sim_grid_pos_y: 1683985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915038.38
      sim_grid_pos_y: 1685677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914819.38
      sim_grid_pos_y: 1684978
    }
    terrain_level_point {
      sim_grid_pos_x: 1917964.5
      sim_grid_pos_y: 1681023.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1919359.5
      sim_grid_pos_y: 1679376.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1922848.75
      sim_grid_pos_y: 1677096.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1923527
      sim_grid_pos_y: 1677401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1922325
      sim_grid_pos_y: 1678111.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1921313.25
      sim_grid_pos_y: 1678910.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1920109.38
      sim_grid_pos_y: 1680009.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1918462.25
      sim_grid_pos_y: 1682243.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1916959.75
      sim_grid_pos_y: 1684056.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914988.75
      sim_grid_pos_y: 1685862.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914705.25
      sim_grid_pos_y: 1684956.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1917885.25
      sim_grid_pos_y: 1680958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1919290.88
      sim_grid_pos_y: 1679298.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1922847.62
      sim_grid_pos_y: 1676974.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1923723.88
      sim_grid_pos_y: 1677404.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1922383.12
      sim_grid_pos_y: 1678196.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1921379.5
      sim_grid_pos_y: 1678988.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1920186
      sim_grid_pos_y: 1680078.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1918543.12
      sim_grid_pos_y: 1682307
    }
    terrain_level_point {
      sim_grid_pos_x: 1917034.12
      sim_grid_pos_y: 1684127.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914939
      sim_grid_pos_y: 1686046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1914591.25
      sim_grid_pos_y: 1684935.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1917806
      sim_grid_pos_y: 1680893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1919222.38
      sim_grid_pos_y: 1679221
    }
    terrain_level_point {
      sim_grid_pos_x: 1922846.62
      sim_grid_pos_y: 1676852.88
    }
  }
}
terrain_level_data {
  terrain_level: 110
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1914797.62
      sim_grid_pos_y: 1673535.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914891.38
      sim_grid_pos_y: 1673831.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914991.62
      sim_grid_pos_y: 1673843.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915080.88
      sim_grid_pos_y: 1673981.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915191
      sim_grid_pos_y: 1673916
    }
    terrain_level_point {
      sim_grid_pos_x: 1915292.25
      sim_grid_pos_y: 1673983.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1915398.88
      sim_grid_pos_y: 1673894.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915535.38
      sim_grid_pos_y: 1673941.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915651.25
      sim_grid_pos_y: 1673675.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915675.12
      sim_grid_pos_y: 1673504.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1915438.88
      sim_grid_pos_y: 1673408.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915296.5
      sim_grid_pos_y: 1673587.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1915055.75
      sim_grid_pos_y: 1673631
    }
    terrain_level_point {
      sim_grid_pos_x: 1914842.12
      sim_grid_pos_y: 1673366.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1914803.12
      sim_grid_pos_y: 1673121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914652.5
      sim_grid_pos_y: 1673101.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914636.62
      sim_grid_pos_y: 1673208.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1914609.12
      sim_grid_pos_y: 1673044.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1914583.62
      sim_grid_pos_y: 1673217.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1914749.88
      sim_grid_pos_y: 1673554.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1914852.5
      sim_grid_pos_y: 1673878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914961.62
      sim_grid_pos_y: 1673891.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915064.75
      sim_grid_pos_y: 1674051.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915189.5
      sim_grid_pos_y: 1673976.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915295.75
      sim_grid_pos_y: 1674047.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915409.5
      sim_grid_pos_y: 1673952.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915563.38
      sim_grid_pos_y: 1674005.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915701
      sim_grid_pos_y: 1673689.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915731.38
      sim_grid_pos_y: 1673471.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915422.62
      sim_grid_pos_y: 1673346.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915268.38
      sim_grid_pos_y: 1673540.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1915076.5
      sim_grid_pos_y: 1673575.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914890.62
      sim_grid_pos_y: 1673344.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1914847.62
      sim_grid_pos_y: 1673075.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1914565.75
      sim_grid_pos_y: 1672986.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1914530.5
      sim_grid_pos_y: 1673225.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914702.25
      sim_grid_pos_y: 1673573.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1914813.5
      sim_grid_pos_y: 1673925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1914931.62
      sim_grid_pos_y: 1673939.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915025.5
      sim_grid_pos_y: 1674086.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915188
      sim_grid_pos_y: 1674037.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915299.25
      sim_grid_pos_y: 1674111.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915420.12
      sim_grid_pos_y: 1674010.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915591.38
      sim_grid_pos_y: 1674069.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915750.88
      sim_grid_pos_y: 1673704
    }
    terrain_level_point {
      sim_grid_pos_x: 1915787.75
      sim_grid_pos_y: 1673439.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1915406.38
      sim_grid_pos_y: 1673285
    }
    terrain_level_point {
      sim_grid_pos_x: 1915240.38
      sim_grid_pos_y: 1673493.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1915097.38
      sim_grid_pos_y: 1673519.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1914939.12
      sim_grid_pos_y: 1673323.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1914892.25
      sim_grid_pos_y: 1673029.25
    }
  }
}
terrain_level_data {
  terrain_level: 16
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1915855.5
      sim_grid_pos_y: 1674174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1919291.75
      sim_grid_pos_y: 1673166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1921995.12
      sim_grid_pos_y: 1673125.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1925467.75
      sim_grid_pos_y: 1672484.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1927952.62
      sim_grid_pos_y: 1672328
    }
    terrain_level_point {
      sim_grid_pos_x: 1928445.88
      sim_grid_pos_y: 1672924.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1919655.25
      sim_grid_pos_y: 1678474.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1919847
      sim_grid_pos_y: 1679195.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1919083.75
      sim_grid_pos_y: 1679637.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1918313.75
      sim_grid_pos_y: 1679591.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916133.12
      sim_grid_pos_y: 1680727.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915588.38
      sim_grid_pos_y: 1679880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916590.12
      sim_grid_pos_y: 1678588.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1917727.88
      sim_grid_pos_y: 1677555.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1919658.5
      sim_grid_pos_y: 1675046
    }
    terrain_level_point {
      sim_grid_pos_x: 1914985.5
      sim_grid_pos_y: 1674575.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915360.62
      sim_grid_pos_y: 1674143
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1928599.25
      sim_grid_pos_y: 1672948.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1919773.75
      sim_grid_pos_y: 1678521.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1919966.25
      sim_grid_pos_y: 1679245.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1919108.5
      sim_grid_pos_y: 1679742
    }
    terrain_level_point {
      sim_grid_pos_x: 1918336
      sim_grid_pos_y: 1679695.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1916097.5
      sim_grid_pos_y: 1680862.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915463
      sim_grid_pos_y: 1679875
    }
    terrain_level_point {
      sim_grid_pos_x: 1916514.62
      sim_grid_pos_y: 1678518.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1917652.12
      sim_grid_pos_y: 1677485.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1919464.88
      sim_grid_pos_y: 1675129.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914913.12
      sim_grid_pos_y: 1674671.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914867.12
      sim_grid_pos_y: 1674555.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915316.38
      sim_grid_pos_y: 1674037.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1915843.88
      sim_grid_pos_y: 1674070.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1919276.38
      sim_grid_pos_y: 1673064
    }
    terrain_level_point {
      sim_grid_pos_x: 1921985
      sim_grid_pos_y: 1673022.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1925455.25
      sim_grid_pos_y: 1672382.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1927998.38
      sim_grid_pos_y: 1672222.38
    }
  }
}
