terrain_level_data {
  terrain_level: 270
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1430129.88
      sim_grid_pos_y: 2071783.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430370.75
      sim_grid_pos_y: 2072212.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1431031.38
      sim_grid_pos_y: 2071917.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431647.62
      sim_grid_pos_y: 2071638.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1431831.88
      sim_grid_pos_y: 2071473.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431683.88
      sim_grid_pos_y: 2071107.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430592.38
      sim_grid_pos_y: 2071656.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430465.88
      sim_grid_pos_y: 2071579.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1431699.88
      sim_grid_pos_y: 2071065
    }
    terrain_level_point {
      sim_grid_pos_x: 1430593.75
      sim_grid_pos_y: 2071621
    }
    terrain_level_point {
      sim_grid_pos_x: 1430465.88
      sim_grid_pos_y: 2071543.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430088.5
      sim_grid_pos_y: 2071772.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430357.75
      sim_grid_pos_y: 2072251.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431044
      sim_grid_pos_y: 2071945.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431664.62
      sim_grid_pos_y: 2071664.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1431868.5
      sim_grid_pos_y: 2071481.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1431715.88
      sim_grid_pos_y: 2071022.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430595.12
      sim_grid_pos_y: 2071585.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430465.75
      sim_grid_pos_y: 2071507.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430047.12
      sim_grid_pos_y: 2071761.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430344.62
      sim_grid_pos_y: 2072291.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1431056.62
      sim_grid_pos_y: 2071973.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431681.62
      sim_grid_pos_y: 2071690.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1431905.12
      sim_grid_pos_y: 2071490.5
    }
  }
}
terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1430394.88
      sim_grid_pos_y: 2071229.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430386
      sim_grid_pos_y: 2071351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429942.5
      sim_grid_pos_y: 2071371.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429760.75
      sim_grid_pos_y: 2071065
    }
    terrain_level_point {
      sim_grid_pos_x: 1429672.38
      sim_grid_pos_y: 2070653.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429578.88
      sim_grid_pos_y: 2070114.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1429540.12
      sim_grid_pos_y: 2069715
    }
    terrain_level_point {
      sim_grid_pos_x: 1430159.38
      sim_grid_pos_y: 2069422.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430533.88
      sim_grid_pos_y: 2069412.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430586.62
      sim_grid_pos_y: 2069650.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430682
      sim_grid_pos_y: 2069791
    }
    terrain_level_point {
      sim_grid_pos_x: 1431205
      sim_grid_pos_y: 2069774.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432210.62
      sim_grid_pos_y: 2070101.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1432447.62
      sim_grid_pos_y: 2070454.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432450.5
      sim_grid_pos_y: 2071237.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1432014.25
      sim_grid_pos_y: 2071432.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1431825.12
      sim_grid_pos_y: 2071075.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431571.62
      sim_grid_pos_y: 2071174.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1431000.75
      sim_grid_pos_y: 2071405.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1430615.38
      sim_grid_pos_y: 2069638.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430698
      sim_grid_pos_y: 2069759.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1431209.38
      sim_grid_pos_y: 2069743.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1432230.25
      sim_grid_pos_y: 2070075.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1432478.25
      sim_grid_pos_y: 2070445
    }
    terrain_level_point {
      sim_grid_pos_x: 1432481.25
      sim_grid_pos_y: 2071257.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1432000.5
      sim_grid_pos_y: 2071472.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431810.75
      sim_grid_pos_y: 2071114.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431582.88
      sim_grid_pos_y: 2071203.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1431002.38
      sim_grid_pos_y: 2071437.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430422.75
      sim_grid_pos_y: 2071269.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430414.75
      sim_grid_pos_y: 2071381.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429925.38
      sim_grid_pos_y: 2071403
    }
    terrain_level_point {
      sim_grid_pos_x: 1429731.75
      sim_grid_pos_y: 2071076.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429642.12
      sim_grid_pos_y: 2070659.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1429548.38
      sim_grid_pos_y: 2070119
    }
    terrain_level_point {
      sim_grid_pos_x: 1429507.38
      sim_grid_pos_y: 2069696.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1430152.12
      sim_grid_pos_y: 2069391.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1430558.38
      sim_grid_pos_y: 2069380.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1430644.25
      sim_grid_pos_y: 2069625.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430713.88
      sim_grid_pos_y: 2069728.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1431213.88
      sim_grid_pos_y: 2069712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1432249.75
      sim_grid_pos_y: 2070049.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1432509
      sim_grid_pos_y: 2070435.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1432512.12
      sim_grid_pos_y: 2071277.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431986.88
      sim_grid_pos_y: 2071512.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1431796.38
      sim_grid_pos_y: 2071153
    }
    terrain_level_point {
      sim_grid_pos_x: 1431594.5
      sim_grid_pos_y: 2071231.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1431004
      sim_grid_pos_y: 2071470.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1430450.75
      sim_grid_pos_y: 2071309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1430443.38
      sim_grid_pos_y: 2071411
    }
    terrain_level_point {
      sim_grid_pos_x: 1429908.38
      sim_grid_pos_y: 2071434.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1429702.75
      sim_grid_pos_y: 2071087.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1429612
      sim_grid_pos_y: 2070665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1429517.75
      sim_grid_pos_y: 2070123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1429474.62
      sim_grid_pos_y: 2069677.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1430144.75
      sim_grid_pos_y: 2069361.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1430582.88
      sim_grid_pos_y: 2069349.5
    }
  }
}
