terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 357124.969
      sim_grid_pos_y: 2042579.25
    }
    terrain_level_point {
      sim_grid_pos_x: 356921.438
      sim_grid_pos_y: 2042373.75
    }
    terrain_level_point {
      sim_grid_pos_x: 356972.156
      sim_grid_pos_y: 2042235.62
    }
    terrain_level_point {
      sim_grid_pos_x: 357649.875
      sim_grid_pos_y: 2041743
    }
    terrain_level_point {
      sim_grid_pos_x: 360428.281
      sim_grid_pos_y: 2036392.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365010.656
      sim_grid_pos_y: 2038146.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363878.469
      sim_grid_pos_y: 2039442.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363103.219
      sim_grid_pos_y: 2038774.38
    }
    terrain_level_point {
      sim_grid_pos_x: 362916.688
      sim_grid_pos_y: 2038989.88
    }
    terrain_level_point {
      sim_grid_pos_x: 362571.812
      sim_grid_pos_y: 2038709.75
    }
    terrain_level_point {
      sim_grid_pos_x: 362055.688
      sim_grid_pos_y: 2039254.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363159.094
      sim_grid_pos_y: 2040177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363104.844
      sim_grid_pos_y: 2040250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364141.969
      sim_grid_pos_y: 2040989.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364021.719
      sim_grid_pos_y: 2041149.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363835.844
      sim_grid_pos_y: 2040993.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363543.594
      sim_grid_pos_y: 2041392.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363743
      sim_grid_pos_y: 2041545.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363245.219
      sim_grid_pos_y: 2042161.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363116.531
      sim_grid_pos_y: 2041968.38
    }
    terrain_level_point {
      sim_grid_pos_x: 361718.719
      sim_grid_pos_y: 2040878.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360315.906
      sim_grid_pos_y: 2042581.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360596.875
      sim_grid_pos_y: 2042802.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360672.719
      sim_grid_pos_y: 2042740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363486.719
      sim_grid_pos_y: 2044993.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363391.375
      sim_grid_pos_y: 2045053.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363661.625
      sim_grid_pos_y: 2045241.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363915.625
      sim_grid_pos_y: 2045011.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364583.188
      sim_grid_pos_y: 2044641.12
    }
    terrain_level_point {
      sim_grid_pos_x: 365274.719
      sim_grid_pos_y: 2045233.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365372.188
      sim_grid_pos_y: 2045178.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365577.719
      sim_grid_pos_y: 2045360.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365624.406
      sim_grid_pos_y: 2045531.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367068.219
      sim_grid_pos_y: 2046751.5
    }
    terrain_level_point {
      sim_grid_pos_x: 367292.938
      sim_grid_pos_y: 2046506
    }
    terrain_level_point {
      sim_grid_pos_x: 367793.188
      sim_grid_pos_y: 2046911.25
    }
    terrain_level_point {
      sim_grid_pos_x: 367180.688
      sim_grid_pos_y: 2047398.25
    }
    terrain_level_point {
      sim_grid_pos_x: 366731.906
      sim_grid_pos_y: 2047253.88
    }
    terrain_level_point {
      sim_grid_pos_x: 366442.125
      sim_grid_pos_y: 2047250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 366372.562
      sim_grid_pos_y: 2047345.62
    }
    terrain_level_point {
      sim_grid_pos_x: 366066.281
      sim_grid_pos_y: 2047202.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365480.625
      sim_grid_pos_y: 2047534.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364855.062
      sim_grid_pos_y: 2047631.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364765.969
      sim_grid_pos_y: 2047328.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364937.5
      sim_grid_pos_y: 2046981.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364834.719
      sim_grid_pos_y: 2046485.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364764.75
      sim_grid_pos_y: 2046264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364408.688
      sim_grid_pos_y: 2045959.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364111.875
      sim_grid_pos_y: 2045698.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363544.344
      sim_grid_pos_y: 2045494.62
    }
    terrain_level_point {
      sim_grid_pos_x: 362677.281
      sim_grid_pos_y: 2045426.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362467.688
      sim_grid_pos_y: 2045253.5
    }
    terrain_level_point {
      sim_grid_pos_x: 362175.062
      sim_grid_pos_y: 2045215.25
    }
    terrain_level_point {
      sim_grid_pos_x: 361943.375
      sim_grid_pos_y: 2045436.5
    }
    terrain_level_point {
      sim_grid_pos_x: 361730.156
      sim_grid_pos_y: 2045359.75
    }
    terrain_level_point {
      sim_grid_pos_x: 361455.844
      sim_grid_pos_y: 2045189
    }
    terrain_level_point {
      sim_grid_pos_x: 361119.656
      sim_grid_pos_y: 2045033.88
    }
    terrain_level_point {
      sim_grid_pos_x: 360983.312
      sim_grid_pos_y: 2044793.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360760.75
      sim_grid_pos_y: 2044613.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360742.031
      sim_grid_pos_y: 2044566
    }
    terrain_level_point {
      sim_grid_pos_x: 359842.5
      sim_grid_pos_y: 2044114.12
    }
    terrain_level_point {
      sim_grid_pos_x: 357378.312
      sim_grid_pos_y: 2042633.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 365062.812
      sim_grid_pos_y: 2038133.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363881.531
      sim_grid_pos_y: 2039485.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363106.406
      sim_grid_pos_y: 2038817.75
    }
    terrain_level_point {
      sim_grid_pos_x: 362920.438
      sim_grid_pos_y: 2039032.62
    }
    terrain_level_point {
      sim_grid_pos_x: 362574.531
      sim_grid_pos_y: 2038751.62
    }
    terrain_level_point {
      sim_grid_pos_x: 362100.5
      sim_grid_pos_y: 2039251.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363201.094
      sim_grid_pos_y: 2040172.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363148.219
      sim_grid_pos_y: 2040243.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364185.562
      sim_grid_pos_y: 2040983
    }
    terrain_level_point {
      sim_grid_pos_x: 364026.781
      sim_grid_pos_y: 2041193.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363841.25
      sim_grid_pos_y: 2041038
    }
    terrain_level_point {
      sim_grid_pos_x: 363586.156
      sim_grid_pos_y: 2041386.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363786.75
      sim_grid_pos_y: 2041540.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363242.812
      sim_grid_pos_y: 2042213.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363093.688
      sim_grid_pos_y: 2041989.62
    }
    terrain_level_point {
      sim_grid_pos_x: 361723.406
      sim_grid_pos_y: 2040921.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360359.625
      sim_grid_pos_y: 2042576.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360596.531
      sim_grid_pos_y: 2042763
    }
    terrain_level_point {
      sim_grid_pos_x: 360672.531
      sim_grid_pos_y: 2042701.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363539.688
      sim_grid_pos_y: 2044996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363447.062
      sim_grid_pos_y: 2045054.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363659.094
      sim_grid_pos_y: 2045202.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363897.625
      sim_grid_pos_y: 2044986.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364586.938
      sim_grid_pos_y: 2044603.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365278.344
      sim_grid_pos_y: 2045195.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365376.188
      sim_grid_pos_y: 2045140.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365605
      sim_grid_pos_y: 2045343.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365651.562
      sim_grid_pos_y: 2045514.38
    }
    terrain_level_point {
      sim_grid_pos_x: 367065.469
      sim_grid_pos_y: 2046709
    }
    terrain_level_point {
      sim_grid_pos_x: 367289.781
      sim_grid_pos_y: 2046463.88
    }
    terrain_level_point {
      sim_grid_pos_x: 367842.312
      sim_grid_pos_y: 2046911.5
    }
    terrain_level_point {
      sim_grid_pos_x: 367186.938
      sim_grid_pos_y: 2047432.62
    }
    terrain_level_point {
      sim_grid_pos_x: 366726.906
      sim_grid_pos_y: 2047284.5
    }
    terrain_level_point {
      sim_grid_pos_x: 366457.625
      sim_grid_pos_y: 2047281.5
    }
    terrain_level_point {
      sim_grid_pos_x: 366382.438
      sim_grid_pos_y: 2047384.12
    }
    terrain_level_point {
      sim_grid_pos_x: 366067.625
      sim_grid_pos_y: 2047237.12
    }
    terrain_level_point {
      sim_grid_pos_x: 365490.906
      sim_grid_pos_y: 2047564
    }
    terrain_level_point {
      sim_grid_pos_x: 364833.156
      sim_grid_pos_y: 2047666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364733.094
      sim_grid_pos_y: 2047325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364905.219
      sim_grid_pos_y: 2046977.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364804.906
      sim_grid_pos_y: 2046493
    }
    terrain_level_point {
      sim_grid_pos_x: 364738.062
      sim_grid_pos_y: 2046282.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364388.531
      sim_grid_pos_y: 2045982.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364095.938
      sim_grid_pos_y: 2045725.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363537.812
      sim_grid_pos_y: 2045525
    }
    terrain_level_point {
      sim_grid_pos_x: 362665.219
      sim_grid_pos_y: 2045456.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362454.938
      sim_grid_pos_y: 2045282.88
    }
    terrain_level_point {
      sim_grid_pos_x: 362185.656
      sim_grid_pos_y: 2045247.62
    }
    terrain_level_point {
      sim_grid_pos_x: 361950.875
      sim_grid_pos_y: 2045471.88
    }
    terrain_level_point {
      sim_grid_pos_x: 361716.688
      sim_grid_pos_y: 2045387.62
    }
    terrain_level_point {
      sim_grid_pos_x: 361441.281
      sim_grid_pos_y: 2045216.12
    }
    terrain_level_point {
      sim_grid_pos_x: 361097.781
      sim_grid_pos_y: 2045057.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360959.438
      sim_grid_pos_y: 2044813.88
    }
    terrain_level_point {
      sim_grid_pos_x: 360735.094
      sim_grid_pos_y: 2044632.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360717.688
      sim_grid_pos_y: 2044588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 359827.656
      sim_grid_pos_y: 2044141.12
    }
    terrain_level_point {
      sim_grid_pos_x: 357366.906
      sim_grid_pos_y: 2042662.12
    }
    terrain_level_point {
      sim_grid_pos_x: 357109.594
      sim_grid_pos_y: 2042607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 356885.812
      sim_grid_pos_y: 2042381.5
    }
    terrain_level_point {
      sim_grid_pos_x: 356946.531
      sim_grid_pos_y: 2042216.25
    }
    terrain_level_point {
      sim_grid_pos_x: 357625.906
      sim_grid_pos_y: 2041722.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360413.625
      sim_grid_pos_y: 2036353.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 365115
      sim_grid_pos_y: 2038120.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363884.594
      sim_grid_pos_y: 2039528.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363109.562
      sim_grid_pos_y: 2038861
    }
    terrain_level_point {
      sim_grid_pos_x: 362924.188
      sim_grid_pos_y: 2039075.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362577.25
      sim_grid_pos_y: 2038793.38
    }
    terrain_level_point {
      sim_grid_pos_x: 362145.344
      sim_grid_pos_y: 2039249.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363243.062
      sim_grid_pos_y: 2040167.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363191.625
      sim_grid_pos_y: 2040236.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364229.125
      sim_grid_pos_y: 2040976.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364031.812
      sim_grid_pos_y: 2041238.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363846.656
      sim_grid_pos_y: 2041082.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363628.75
      sim_grid_pos_y: 2041380.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363830.5
      sim_grid_pos_y: 2041535.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363240.406
      sim_grid_pos_y: 2042265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363070.844
      sim_grid_pos_y: 2042010.75
    }
    terrain_level_point {
      sim_grid_pos_x: 361728.125
      sim_grid_pos_y: 2040964
    }
    terrain_level_point {
      sim_grid_pos_x: 360403.375
      sim_grid_pos_y: 2042572
    }
    terrain_level_point {
      sim_grid_pos_x: 360596.188
      sim_grid_pos_y: 2042723.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360672.375
      sim_grid_pos_y: 2042661.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363592.656
      sim_grid_pos_y: 2044999.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363502.75
      sim_grid_pos_y: 2045056
    }
    terrain_level_point {
      sim_grid_pos_x: 363656.594
      sim_grid_pos_y: 2045163.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363879.594
      sim_grid_pos_y: 2044961.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364590.719
      sim_grid_pos_y: 2044566.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365282
      sim_grid_pos_y: 2045158.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365380.188
      sim_grid_pos_y: 2045103.12
    }
    terrain_level_point {
      sim_grid_pos_x: 365632.25
      sim_grid_pos_y: 2045326.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365678.719
      sim_grid_pos_y: 2045497
    }
    terrain_level_point {
      sim_grid_pos_x: 367062.75
      sim_grid_pos_y: 2046666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 367286.625
      sim_grid_pos_y: 2046421.75
    }
    terrain_level_point {
      sim_grid_pos_x: 367891.469
      sim_grid_pos_y: 2046911.75
    }
    terrain_level_point {
      sim_grid_pos_x: 367193.188
      sim_grid_pos_y: 2047466.88
    }
    terrain_level_point {
      sim_grid_pos_x: 366721.875
      sim_grid_pos_y: 2047315.25
    }
    terrain_level_point {
      sim_grid_pos_x: 366473.094
      sim_grid_pos_y: 2047312.38
    }
    terrain_level_point {
      sim_grid_pos_x: 366392.344
      sim_grid_pos_y: 2047422.75
    }
    terrain_level_point {
      sim_grid_pos_x: 366068.969
      sim_grid_pos_y: 2047271.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365501.188
      sim_grid_pos_y: 2047593.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364811.25
      sim_grid_pos_y: 2047701
    }
    terrain_level_point {
      sim_grid_pos_x: 364700.188
      sim_grid_pos_y: 2047322.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364872.969
      sim_grid_pos_y: 2046973.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364775.094
      sim_grid_pos_y: 2046500.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364711.406
      sim_grid_pos_y: 2.0463e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 364368.375
      sim_grid_pos_y: 2046006
    }
    terrain_level_point {
      sim_grid_pos_x: 364080.062
      sim_grid_pos_y: 2045752.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363531.312
      sim_grid_pos_y: 2045555.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362653.125
      sim_grid_pos_y: 2045486.12
    }
    terrain_level_point {
      sim_grid_pos_x: 362442.156
      sim_grid_pos_y: 2045312.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362196.25
      sim_grid_pos_y: 2.04528e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 361958.344
      sim_grid_pos_y: 2045507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 361703.188
      sim_grid_pos_y: 2045415.38
    }
    terrain_level_point {
      sim_grid_pos_x: 361426.625
      sim_grid_pos_y: 2045243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 361075.906
      sim_grid_pos_y: 2045081.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360935.562
      sim_grid_pos_y: 2044834.12
    }
    terrain_level_point {
      sim_grid_pos_x: 360709.406
      sim_grid_pos_y: 2044651.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360693.375
      sim_grid_pos_y: 2044610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 359812.812
      sim_grid_pos_y: 2044168
    }
    terrain_level_point {
      sim_grid_pos_x: 357355.438
      sim_grid_pos_y: 2042691.12
    }
    terrain_level_point {
      sim_grid_pos_x: 357094.188
      sim_grid_pos_y: 2042635.62
    }
    terrain_level_point {
      sim_grid_pos_x: 356850.188
      sim_grid_pos_y: 2042389.25
    }
    terrain_level_point {
      sim_grid_pos_x: 356920.875
      sim_grid_pos_y: 2042196.88
    }
    terrain_level_point {
      sim_grid_pos_x: 357601.969
      sim_grid_pos_y: 2041701.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360399
      sim_grid_pos_y: 2036315.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 365167.156
      sim_grid_pos_y: 2038107.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363887.656
      sim_grid_pos_y: 2039571.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363112.75
      sim_grid_pos_y: 2038904.38
    }
    terrain_level_point {
      sim_grid_pos_x: 362927.938
      sim_grid_pos_y: 2039118
    }
    terrain_level_point {
      sim_grid_pos_x: 362579.969
      sim_grid_pos_y: 2038835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362190.188
      sim_grid_pos_y: 2039246.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363285.062
      sim_grid_pos_y: 2040162.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363235
      sim_grid_pos_y: 2.04023e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 364272.719
      sim_grid_pos_y: 2040969.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364036.875
      sim_grid_pos_y: 2041282.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363852.062
      sim_grid_pos_y: 2041127.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363671.312
      sim_grid_pos_y: 2041374.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363874.219
      sim_grid_pos_y: 2.04153e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 363238
      sim_grid_pos_y: 2042317.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363047.969
      sim_grid_pos_y: 2042032
    }
    terrain_level_point {
      sim_grid_pos_x: 361732.812
      sim_grid_pos_y: 2041006.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360447.125
      sim_grid_pos_y: 2042567.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360595.875
      sim_grid_pos_y: 2042684.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360672.219
      sim_grid_pos_y: 2042622.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363645.656
      sim_grid_pos_y: 2045002.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363558.469
      sim_grid_pos_y: 2045057.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363654.094
      sim_grid_pos_y: 2045123.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363861.562
      sim_grid_pos_y: 2044936
    }
    terrain_level_point {
      sim_grid_pos_x: 364594.5
      sim_grid_pos_y: 2044529.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365285.625
      sim_grid_pos_y: 2045121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 365384.156
      sim_grid_pos_y: 2045065.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365659.531
      sim_grid_pos_y: 2045309.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365705.875
      sim_grid_pos_y: 2045479.75
    }
    terrain_level_point {
      sim_grid_pos_x: 367060
      sim_grid_pos_y: 2046623.75
    }
    terrain_level_point {
      sim_grid_pos_x: 367283.5
      sim_grid_pos_y: 2046379.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367940.594
      sim_grid_pos_y: 2046912
    }
    terrain_level_point {
      sim_grid_pos_x: 367199.438
      sim_grid_pos_y: 2047501.25
    }
    terrain_level_point {
      sim_grid_pos_x: 366716.875
      sim_grid_pos_y: 2047346
    }
    terrain_level_point {
      sim_grid_pos_x: 366488.562
      sim_grid_pos_y: 2047343.38
    }
    terrain_level_point {
      sim_grid_pos_x: 366402.219
      sim_grid_pos_y: 2047461.25
    }
    terrain_level_point {
      sim_grid_pos_x: 366070.375
      sim_grid_pos_y: 2047306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365511.469
      sim_grid_pos_y: 2047623.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364789.312
      sim_grid_pos_y: 2047735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364667.281
      sim_grid_pos_y: 2047319.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364840.688
      sim_grid_pos_y: 2046969.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364745.312
      sim_grid_pos_y: 2046508.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364684.75
      sim_grid_pos_y: 2046317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364348.219
      sim_grid_pos_y: 2046029.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364064.125
      sim_grid_pos_y: 2045779.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363524.781
      sim_grid_pos_y: 2045585.62
    }
    terrain_level_point {
      sim_grid_pos_x: 362641.031
      sim_grid_pos_y: 2045516
    }
    terrain_level_point {
      sim_grid_pos_x: 362429.406
      sim_grid_pos_y: 2045341.62
    }
    terrain_level_point {
      sim_grid_pos_x: 362206.875
      sim_grid_pos_y: 2045312.38
    }
    terrain_level_point {
      sim_grid_pos_x: 361965.844
      sim_grid_pos_y: 2045542.62
    }
    terrain_level_point {
      sim_grid_pos_x: 361689.719
      sim_grid_pos_y: 2045443.25
    }
    terrain_level_point {
      sim_grid_pos_x: 361412
      sim_grid_pos_y: 2045270.38
    }
    terrain_level_point {
      sim_grid_pos_x: 361054.031
      sim_grid_pos_y: 2045105.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360911.688
      sim_grid_pos_y: 2044854.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360683.75
      sim_grid_pos_y: 2044670.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360669.031
      sim_grid_pos_y: 2044632.62
    }
    terrain_level_point {
      sim_grid_pos_x: 359797.969
      sim_grid_pos_y: 2044195
    }
    terrain_level_point {
      sim_grid_pos_x: 357344.031
      sim_grid_pos_y: 2042720.25
    }
    terrain_level_point {
      sim_grid_pos_x: 357078.812
      sim_grid_pos_y: 2042663.75
    }
    terrain_level_point {
      sim_grid_pos_x: 356814.594
      sim_grid_pos_y: 2042397
    }
    terrain_level_point {
      sim_grid_pos_x: 356895.219
      sim_grid_pos_y: 2042177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 357578.031
      sim_grid_pos_y: 2041681.12
    }
    terrain_level_point {
      sim_grid_pos_x: 360384.344
      sim_grid_pos_y: 2036276.62
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 360650.344
      sim_grid_pos_y: 2042560.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363629.688
      sim_grid_pos_y: 2044990.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363584.781
      sim_grid_pos_y: 2045037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363699.375
      sim_grid_pos_y: 2045130.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363919.219
      sim_grid_pos_y: 2044870.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364599.344
      sim_grid_pos_y: 2044526.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365269.562
      sim_grid_pos_y: 2045116.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365321.5
      sim_grid_pos_y: 2045114.38
    }
    terrain_level_point {
      sim_grid_pos_x: 366429.688
      sim_grid_pos_y: 2046140.5
    }
    terrain_level_point {
      sim_grid_pos_x: 366522.938
      sim_grid_pos_y: 2046165.25
    }
    terrain_level_point {
      sim_grid_pos_x: 367055.656
      sim_grid_pos_y: 2046647.5
    }
    terrain_level_point {
      sim_grid_pos_x: 367267.625
      sim_grid_pos_y: 2046412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 367838.5
      sim_grid_pos_y: 2046891
    }
    terrain_level_point {
      sim_grid_pos_x: 371722.594
      sim_grid_pos_y: 2043907.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371501.5
      sim_grid_pos_y: 2043414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371667.219
      sim_grid_pos_y: 2042834.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371650.594
      sim_grid_pos_y: 2042532.88
    }
    terrain_level_point {
      sim_grid_pos_x: 371406.906
      sim_grid_pos_y: 2042393.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371301.906
      sim_grid_pos_y: 2042173
    }
    terrain_level_point {
      sim_grid_pos_x: 371376
      sim_grid_pos_y: 2042034.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371480.625
      sim_grid_pos_y: 2041996.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371570.344
      sim_grid_pos_y: 2041993.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371633.344
      sim_grid_pos_y: 2041853.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371284.094
      sim_grid_pos_y: 2041533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 370928.594
      sim_grid_pos_y: 2041529.38
    }
    terrain_level_point {
      sim_grid_pos_x: 370479.344
      sim_grid_pos_y: 2041221.88
    }
    terrain_level_point {
      sim_grid_pos_x: 369975.688
      sim_grid_pos_y: 2041202.5
    }
    terrain_level_point {
      sim_grid_pos_x: 369839.094
      sim_grid_pos_y: 2040907.38
    }
    terrain_level_point {
      sim_grid_pos_x: 369651.062
      sim_grid_pos_y: 2040782.75
    }
    terrain_level_point {
      sim_grid_pos_x: 369408.031
      sim_grid_pos_y: 2040808.88
    }
    terrain_level_point {
      sim_grid_pos_x: 369305.312
      sim_grid_pos_y: 2040718.62
    }
    terrain_level_point {
      sim_grid_pos_x: 368830.25
      sim_grid_pos_y: 2040947.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368680.094
      sim_grid_pos_y: 2040956.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368533.125
      sim_grid_pos_y: 2040833.38
    }
    terrain_level_point {
      sim_grid_pos_x: 368568.125
      sim_grid_pos_y: 2040674
    }
    terrain_level_point {
      sim_grid_pos_x: 368722.875
      sim_grid_pos_y: 2040532.12
    }
    terrain_level_point {
      sim_grid_pos_x: 368771.375
      sim_grid_pos_y: 2040311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 368583.469
      sim_grid_pos_y: 2040060.75
    }
    terrain_level_point {
      sim_grid_pos_x: 368446.469
      sim_grid_pos_y: 2040032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368365.094
      sim_grid_pos_y: 2039857.5
    }
    terrain_level_point {
      sim_grid_pos_x: 368149.688
      sim_grid_pos_y: 2039868.5
    }
    terrain_level_point {
      sim_grid_pos_x: 367946.188
      sim_grid_pos_y: 2039563.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368100.438
      sim_grid_pos_y: 2039344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 368521.188
      sim_grid_pos_y: 2039240.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368548.5
      sim_grid_pos_y: 2038469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 367913.875
      sim_grid_pos_y: 2038414.38
    }
    terrain_level_point {
      sim_grid_pos_x: 367878.219
      sim_grid_pos_y: 2038354
    }
    terrain_level_point {
      sim_grid_pos_x: 366381.562
      sim_grid_pos_y: 2038908.12
    }
    terrain_level_point {
      sim_grid_pos_x: 365886.031
      sim_grid_pos_y: 2038708
    }
    terrain_level_point {
      sim_grid_pos_x: 365645.625
      sim_grid_pos_y: 2039116.5
    }
    terrain_level_point {
      sim_grid_pos_x: 364995.375
      sim_grid_pos_y: 2038599.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364897.062
      sim_grid_pos_y: 2038611.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364817.75
      sim_grid_pos_y: 2038577.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364727.719
      sim_grid_pos_y: 2038653.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364553.969
      sim_grid_pos_y: 2038507.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364397.906
      sim_grid_pos_y: 2038699.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364554.344
      sim_grid_pos_y: 2038806.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363895.531
      sim_grid_pos_y: 2039584.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363294.125
      sim_grid_pos_y: 2039046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363058.469
      sim_grid_pos_y: 2038931
    }
    terrain_level_point {
      sim_grid_pos_x: 362913.75
      sim_grid_pos_y: 2039092.75
    }
    terrain_level_point {
      sim_grid_pos_x: 362611.719
      sim_grid_pos_y: 2038858.62
    }
    terrain_level_point {
      sim_grid_pos_x: 362333.344
      sim_grid_pos_y: 2039192.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363295.281
      sim_grid_pos_y: 2039959
    }
    terrain_level_point {
      sim_grid_pos_x: 363257.594
      sim_grid_pos_y: 2040015.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363405.562
      sim_grid_pos_y: 2040131.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363285.25
      sim_grid_pos_y: 2040269.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363414.906
      sim_grid_pos_y: 2040380.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363485.344
      sim_grid_pos_y: 2040346
    }
    terrain_level_point {
      sim_grid_pos_x: 364279.531
      sim_grid_pos_y: 2040996.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364058.125
      sim_grid_pos_y: 2041261.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363897.094
      sim_grid_pos_y: 2041119
    }
    terrain_level_point {
      sim_grid_pos_x: 363773.969
      sim_grid_pos_y: 2041211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363662.656
      sim_grid_pos_y: 2041372.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363832.5
      sim_grid_pos_y: 2041523.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363751.5
      sim_grid_pos_y: 2041653.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363233.312
      sim_grid_pos_y: 2042268.75
    }
    terrain_level_point {
      sim_grid_pos_x: 361730.375
      sim_grid_pos_y: 2040956.88
    }
    terrain_level_point {
      sim_grid_pos_x: 361410.625
      sim_grid_pos_y: 2041368.25
    }
    terrain_level_point {
      sim_grid_pos_x: 361464.094
      sim_grid_pos_y: 2041439.88
    }
    terrain_level_point {
      sim_grid_pos_x: 361040.844
      sim_grid_pos_y: 2041991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360972.281
      sim_grid_pos_y: 2041931.12
    }
    terrain_level_point {
      sim_grid_pos_x: 360810.375
      sim_grid_pos_y: 2042075.88
    }
    terrain_level_point {
      sim_grid_pos_x: 360838.875
      sim_grid_pos_y: 2042331
    }
    terrain_level_point {
      sim_grid_pos_x: 360612
      sim_grid_pos_y: 2042343.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360445.062
      sim_grid_pos_y: 2042540.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360567.656
      sim_grid_pos_y: 2042643.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 367887.188
      sim_grid_pos_y: 2038328.75
    }
    terrain_level_point {
      sim_grid_pos_x: 366381.875
      sim_grid_pos_y: 2038886.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365877.344
      sim_grid_pos_y: 2038682.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365639.906
      sim_grid_pos_y: 2039085.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365001.438
      sim_grid_pos_y: 2038578
    }
    terrain_level_point {
      sim_grid_pos_x: 364900.062
      sim_grid_pos_y: 2038590.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364814.125
      sim_grid_pos_y: 2038553.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364727.625
      sim_grid_pos_y: 2038627
    }
    terrain_level_point {
      sim_grid_pos_x: 364551.219
      sim_grid_pos_y: 2038478.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364367.938
      sim_grid_pos_y: 2038703.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364524
      sim_grid_pos_y: 2038810.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363893.469
      sim_grid_pos_y: 2039554.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363305.688
      sim_grid_pos_y: 2039029
    }
    terrain_level_point {
      sim_grid_pos_x: 363053.531
      sim_grid_pos_y: 2038905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 362911.188
      sim_grid_pos_y: 2039064.88
    }
    terrain_level_point {
      sim_grid_pos_x: 362608.656
      sim_grid_pos_y: 2038830.25
    }
    terrain_level_point {
      sim_grid_pos_x: 362304.188
      sim_grid_pos_y: 2039195.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363267.719
      sim_grid_pos_y: 2039963.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363229.969
      sim_grid_pos_y: 2040019.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363375.906
      sim_grid_pos_y: 2040134
    }
    terrain_level_point {
      sim_grid_pos_x: 363256.25
      sim_grid_pos_y: 2040271.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363411.844
      sim_grid_pos_y: 2040405.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363482.562
      sim_grid_pos_y: 2040370.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364250.5
      sim_grid_pos_y: 2040998.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364055.875
      sim_grid_pos_y: 2041231.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363898.125
      sim_grid_pos_y: 2041092.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363759
      sim_grid_pos_y: 2041197.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363635.469
      sim_grid_pos_y: 2041375.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363805.969
      sim_grid_pos_y: 2041527.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363734.875
      sim_grid_pos_y: 2041641.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363231.062
      sim_grid_pos_y: 2042239.5
    }
    terrain_level_point {
      sim_grid_pos_x: 361727.5
      sim_grid_pos_y: 2040927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 361384.875
      sim_grid_pos_y: 2041368
    }
    terrain_level_point {
      sim_grid_pos_x: 361438.375
      sim_grid_pos_y: 2041439.75
    }
    terrain_level_point {
      sim_grid_pos_x: 361037.906
      sim_grid_pos_y: 2041961.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360972.156
      sim_grid_pos_y: 2041903.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360788.844
      sim_grid_pos_y: 2042067.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360816.094
      sim_grid_pos_y: 2042311.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360602.094
      sim_grid_pos_y: 2042323.88
    }
    terrain_level_point {
      sim_grid_pos_x: 360416.125
      sim_grid_pos_y: 2042542.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360568.875
      sim_grid_pos_y: 2042671.62
    }
    terrain_level_point {
      sim_grid_pos_x: 360651.781
      sim_grid_pos_y: 2042588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363599.5
      sim_grid_pos_y: 2044992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363554.594
      sim_grid_pos_y: 2045039.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363702.031
      sim_grid_pos_y: 2045159.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363932.219
      sim_grid_pos_y: 2044886.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364596.219
      sim_grid_pos_y: 2044551.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365262.188
      sim_grid_pos_y: 2045137.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365313.844
      sim_grid_pos_y: 2045135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 366419.531
      sim_grid_pos_y: 2046159.12
    }
    terrain_level_point {
      sim_grid_pos_x: 366512.875
      sim_grid_pos_y: 2046183.75
    }
    terrain_level_point {
      sim_grid_pos_x: 367057.125
      sim_grid_pos_y: 2046676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 367269.594
      sim_grid_pos_y: 2046440.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367837.906
      sim_grid_pos_y: 2046917.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371747.938
      sim_grid_pos_y: 2043913.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371523.281
      sim_grid_pos_y: 2043413
    }
    terrain_level_point {
      sim_grid_pos_x: 371687.875
      sim_grid_pos_y: 2042836.88
    }
    terrain_level_point {
      sim_grid_pos_x: 371670.469
      sim_grid_pos_y: 2042520.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371422.625
      sim_grid_pos_y: 2042378.88
    }
    terrain_level_point {
      sim_grid_pos_x: 371324.875
      sim_grid_pos_y: 2042173.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371390.375
      sim_grid_pos_y: 2042051.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371484.594
      sim_grid_pos_y: 2042017
    }
    terrain_level_point {
      sim_grid_pos_x: 371583.844
      sim_grid_pos_y: 2042013.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371658.156
      sim_grid_pos_y: 2041848
    }
    terrain_level_point {
      sim_grid_pos_x: 371292.156
      sim_grid_pos_y: 2041513.5
    }
    terrain_level_point {
      sim_grid_pos_x: 370935.062
      sim_grid_pos_y: 2041509
    }
    terrain_level_point {
      sim_grid_pos_x: 370486.031
      sim_grid_pos_y: 2041201.62
    }
    terrain_level_point {
      sim_grid_pos_x: 369989.031
      sim_grid_pos_y: 2041182.5
    }
    terrain_level_point {
      sim_grid_pos_x: 369855.281
      sim_grid_pos_y: 2040893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 369656.219
      sim_grid_pos_y: 2040761.62
    }
    terrain_level_point {
      sim_grid_pos_x: 369414.781
      sim_grid_pos_y: 2040787.5
    }
    terrain_level_point {
      sim_grid_pos_x: 369308.656
      sim_grid_pos_y: 2040694.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368824.938
      sim_grid_pos_y: 2040927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 368687
      sim_grid_pos_y: 2040935.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368555.844
      sim_grid_pos_y: 2040825.75
    }
    terrain_level_point {
      sim_grid_pos_x: 368586.781
      sim_grid_pos_y: 2040684.75
    }
    terrain_level_point {
      sim_grid_pos_x: 368741.531
      sim_grid_pos_y: 2040542.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368793.438
      sim_grid_pos_y: 2040306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368595.219
      sim_grid_pos_y: 2040042.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368460.688
      sim_grid_pos_y: 2040014.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368377.875
      sim_grid_pos_y: 2039836.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368160.25
      sim_grid_pos_y: 2039847.38
    }
    terrain_level_point {
      sim_grid_pos_x: 367971.062
      sim_grid_pos_y: 2039563.5
    }
    terrain_level_point {
      sim_grid_pos_x: 368112.781
      sim_grid_pos_y: 2039362.62
    }
    terrain_level_point {
      sim_grid_pos_x: 368541.125
      sim_grid_pos_y: 2039257.12
    }
    terrain_level_point {
      sim_grid_pos_x: 368569.656
      sim_grid_pos_y: 2038450.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367926.156
      sim_grid_pos_y: 2038394.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 367896.125
      sim_grid_pos_y: 2038303.62
    }
    terrain_level_point {
      sim_grid_pos_x: 366382.219
      sim_grid_pos_y: 2038864.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365868.625
      sim_grid_pos_y: 2038656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365634.219
      sim_grid_pos_y: 2039055
    }
    terrain_level_point {
      sim_grid_pos_x: 365007.5
      sim_grid_pos_y: 2038556.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364903.062
      sim_grid_pos_y: 2038569.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364810.5
      sim_grid_pos_y: 2038529.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364727.562
      sim_grid_pos_y: 2038600.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364548.469
      sim_grid_pos_y: 2038449.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364337.969
      sim_grid_pos_y: 2038708
    }
    terrain_level_point {
      sim_grid_pos_x: 364493.688
      sim_grid_pos_y: 2038814.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363891.469
      sim_grid_pos_y: 2039525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363317.25
      sim_grid_pos_y: 2039011.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363048.594
      sim_grid_pos_y: 2038880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 362908.656
      sim_grid_pos_y: 2039036.88
    }
    terrain_level_point {
      sim_grid_pos_x: 362605.562
      sim_grid_pos_y: 2038801.88
    }
    terrain_level_point {
      sim_grid_pos_x: 362275
      sim_grid_pos_y: 2039198.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363240.188
      sim_grid_pos_y: 2039967.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363202.344
      sim_grid_pos_y: 2040024
    }
    terrain_level_point {
      sim_grid_pos_x: 363346.281
      sim_grid_pos_y: 2040136.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363227.219
      sim_grid_pos_y: 2040273.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363408.75
      sim_grid_pos_y: 2040429.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363479.812
      sim_grid_pos_y: 2040394.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364221.469
      sim_grid_pos_y: 2041001.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364053.656
      sim_grid_pos_y: 2041202.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363899.125
      sim_grid_pos_y: 2041066.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363744.031
      sim_grid_pos_y: 2041183
    }
    terrain_level_point {
      sim_grid_pos_x: 363608.25
      sim_grid_pos_y: 2041378.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363779.438
      sim_grid_pos_y: 2041531.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363718.219
      sim_grid_pos_y: 2041629.5
    }
    terrain_level_point {
      sim_grid_pos_x: 363228.844
      sim_grid_pos_y: 2042210.38
    }
    terrain_level_point {
      sim_grid_pos_x: 361724.625
      sim_grid_pos_y: 2040897.5
    }
    terrain_level_point {
      sim_grid_pos_x: 361359.094
      sim_grid_pos_y: 2041367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 361412.688
      sim_grid_pos_y: 2041439.62
    }
    terrain_level_point {
      sim_grid_pos_x: 361035
      sim_grid_pos_y: 2041931.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360972.031
      sim_grid_pos_y: 2041876.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360767.281
      sim_grid_pos_y: 2042059.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360793.312
      sim_grid_pos_y: 2042292.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360592.156
      sim_grid_pos_y: 2042303.88
    }
    terrain_level_point {
      sim_grid_pos_x: 360387.188
      sim_grid_pos_y: 2042545.12
    }
    terrain_level_point {
      sim_grid_pos_x: 360570.125
      sim_grid_pos_y: 2042699.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360653.219
      sim_grid_pos_y: 2042615.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363569.344
      sim_grid_pos_y: 2044994.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363524.406
      sim_grid_pos_y: 2045041
    }
    terrain_level_point {
      sim_grid_pos_x: 363704.688
      sim_grid_pos_y: 2045188
    }
    terrain_level_point {
      sim_grid_pos_x: 363945.156
      sim_grid_pos_y: 2044903.12
    }
    terrain_level_point {
      sim_grid_pos_x: 364593.094
      sim_grid_pos_y: 2044575.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365254.812
      sim_grid_pos_y: 2045158.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365306.156
      sim_grid_pos_y: 2045156
    }
    terrain_level_point {
      sim_grid_pos_x: 366409.344
      sim_grid_pos_y: 2046177.62
    }
    terrain_level_point {
      sim_grid_pos_x: 366502.781
      sim_grid_pos_y: 2046202.25
    }
    terrain_level_point {
      sim_grid_pos_x: 367058.594
      sim_grid_pos_y: 2046705.5
    }
    terrain_level_point {
      sim_grid_pos_x: 367271.594
      sim_grid_pos_y: 2046469.12
    }
    terrain_level_point {
      sim_grid_pos_x: 367837.344
      sim_grid_pos_y: 2046943.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371773.281
      sim_grid_pos_y: 2043920.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371545.062
      sim_grid_pos_y: 2043411.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371708.562
      sim_grid_pos_y: 2042839.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371690.312
      sim_grid_pos_y: 2042508.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371438.375
      sim_grid_pos_y: 2042364.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371347.844
      sim_grid_pos_y: 2042174.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371404.75
      sim_grid_pos_y: 2042067.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371488.562
      sim_grid_pos_y: 2042037.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371597.312
      sim_grid_pos_y: 2042033.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371682.938
      sim_grid_pos_y: 2041842.88
    }
    terrain_level_point {
      sim_grid_pos_x: 371300.219
      sim_grid_pos_y: 2041493.12
    }
    terrain_level_point {
      sim_grid_pos_x: 370941.531
      sim_grid_pos_y: 2041488.5
    }
    terrain_level_point {
      sim_grid_pos_x: 370492.719
      sim_grid_pos_y: 2041181.38
    }
    terrain_level_point {
      sim_grid_pos_x: 370002.375
      sim_grid_pos_y: 2041162.5
    }
    terrain_level_point {
      sim_grid_pos_x: 369871.438
      sim_grid_pos_y: 2040879.62
    }
    terrain_level_point {
      sim_grid_pos_x: 369661.375
      sim_grid_pos_y: 2040740.38
    }
    terrain_level_point {
      sim_grid_pos_x: 369421.531
      sim_grid_pos_y: 2040766.12
    }
    terrain_level_point {
      sim_grid_pos_x: 369312
      sim_grid_pos_y: 2040669.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368819.656
      sim_grid_pos_y: 2040906.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368693.875
      sim_grid_pos_y: 2040914.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368578.531
      sim_grid_pos_y: 2040818
    }
    terrain_level_point {
      sim_grid_pos_x: 368605.406
      sim_grid_pos_y: 2040695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 368760.156
      sim_grid_pos_y: 2040553.5
    }
    terrain_level_point {
      sim_grid_pos_x: 368815.469
      sim_grid_pos_y: 2040301.5
    }
    terrain_level_point {
      sim_grid_pos_x: 368606.969
      sim_grid_pos_y: 2040023.75
    }
    terrain_level_point {
      sim_grid_pos_x: 368474.938
      sim_grid_pos_y: 2039996.25
    }
    terrain_level_point {
      sim_grid_pos_x: 368390.625
      sim_grid_pos_y: 2039815.12
    }
    terrain_level_point {
      sim_grid_pos_x: 368170.875
      sim_grid_pos_y: 2039826.38
    }
    terrain_level_point {
      sim_grid_pos_x: 367995.906
      sim_grid_pos_y: 2039563.88
    }
    terrain_level_point {
      sim_grid_pos_x: 368125.125
      sim_grid_pos_y: 2039380.75
    }
    terrain_level_point {
      sim_grid_pos_x: 368561.094
      sim_grid_pos_y: 2039273.38
    }
    terrain_level_point {
      sim_grid_pos_x: 368590.844
      sim_grid_pos_y: 2038431.88
    }
    terrain_level_point {
      sim_grid_pos_x: 367938.469
      sim_grid_pos_y: 2038375.25
    }
  }
}
