terrain_level_data {
  terrain_level: 135
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2914793
      sim_grid_pos_y: 531847.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2921079.5
      sim_grid_pos_y: 534813.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2921010.25
      sim_grid_pos_y: 535525.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2922047.75
      sim_grid_pos_y: 536013.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2921961.25
      sim_grid_pos_y: 536147
    }
    terrain_level_point {
      sim_grid_pos_x: 2922670.25
      sim_grid_pos_y: 536555.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2922420.25
      sim_grid_pos_y: 537010.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2921630.75
      sim_grid_pos_y: 536875.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2921489.5
      sim_grid_pos_y: 537333.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2920758.25
      sim_grid_pos_y: 537469.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2919242
      sim_grid_pos_y: 537256.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2917914.75
      sim_grid_pos_y: 536958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2915009.25
      sim_grid_pos_y: 534208.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2914118.75
      sim_grid_pos_y: 533531.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2913625.25
      sim_grid_pos_y: 533388.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2913739.25
      sim_grid_pos_y: 533214.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2912789
      sim_grid_pos_y: 532821.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2913860.75
      sim_grid_pos_y: 532013.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2914380.5
      sim_grid_pos_y: 531790.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2914822.5
      sim_grid_pos_y: 531748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2921188.5
      sim_grid_pos_y: 534751.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2921119.25
      sim_grid_pos_y: 535463.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2922197.5
      sim_grid_pos_y: 535971.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2922106
      sim_grid_pos_y: 536112.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2922808.75
      sim_grid_pos_y: 536517.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2922474.75
      sim_grid_pos_y: 537123.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2921702.25
      sim_grid_pos_y: 536991.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2921569.25
      sim_grid_pos_y: 537423.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2920760.5
      sim_grid_pos_y: 537573.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2919223.5
      sim_grid_pos_y: 537357.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2917864.75
      sim_grid_pos_y: 537052.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2914942.75
      sim_grid_pos_y: 534286.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2914072
      sim_grid_pos_y: 533624.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2913463.5
      sim_grid_pos_y: 533448.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2913585.75
      sim_grid_pos_y: 533261.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2912695
      sim_grid_pos_y: 532893.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2912679.75
      sim_grid_pos_y: 532775
    }
    terrain_level_point {
      sim_grid_pos_x: 2913809
      sim_grid_pos_y: 531923.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2914366.5
      sim_grid_pos_y: 531685
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2914852
      sim_grid_pos_y: 531649.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2921297.5
      sim_grid_pos_y: 534689.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2921228.25
      sim_grid_pos_y: 535401.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2922347.5
      sim_grid_pos_y: 535928.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2922251
      sim_grid_pos_y: 536077.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2922947
      sim_grid_pos_y: 536478.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2922529.5
      sim_grid_pos_y: 537237
    }
    terrain_level_point {
      sim_grid_pos_x: 2921773.75
      sim_grid_pos_y: 537107.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2921649
      sim_grid_pos_y: 537512.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2920762.75
      sim_grid_pos_y: 537677.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2919205
      sim_grid_pos_y: 537458.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2917814.75
      sim_grid_pos_y: 537146.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2914876.25
      sim_grid_pos_y: 534365.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2914025
      sim_grid_pos_y: 533717.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2913301.75
      sim_grid_pos_y: 533508.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2913432
      sim_grid_pos_y: 533309.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2912600.75
      sim_grid_pos_y: 532965
    }
    terrain_level_point {
      sim_grid_pos_x: 2912570.5
      sim_grid_pos_y: 532728.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2913757.25
      sim_grid_pos_y: 531834.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2914352.25
      sim_grid_pos_y: 531579.5
    }
  }
}
