terrain_level_data {
  terrain_level: 4025
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2466704.75
      sim_grid_pos_y: 1854808.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466678
      sim_grid_pos_y: 1855227.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466963
      sim_grid_pos_y: 1855473
    }
    terrain_level_point {
      sim_grid_pos_x: 2467368
      sim_grid_pos_y: 1855323
    }
    terrain_level_point {
      sim_grid_pos_x: 2467594.5
      sim_grid_pos_y: 1855372.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2467745.25
      sim_grid_pos_y: 1855194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2467471.5
      sim_grid_pos_y: 1854858.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2467406.5
      sim_grid_pos_y: 1854586.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2467078.5
      sim_grid_pos_y: 1854399
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2467058.25
      sim_grid_pos_y: 1854269.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2466604.75
      sim_grid_pos_y: 1854766
    }
    terrain_level_point {
      sim_grid_pos_x: 2466572.5
      sim_grid_pos_y: 1855271.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2466942
      sim_grid_pos_y: 1855590.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2467375.5
      sim_grid_pos_y: 1855429.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2467633
      sim_grid_pos_y: 1855486
    }
    terrain_level_point {
      sim_grid_pos_x: 2467878.5
      sim_grid_pos_y: 1855195.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2467565.75
      sim_grid_pos_y: 1854811.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2467496
      sim_grid_pos_y: 1854519.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2467037.75
      sim_grid_pos_y: 1854139.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2466504.75
      sim_grid_pos_y: 1854723.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466466.75
      sim_grid_pos_y: 1855316.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2466920.75
      sim_grid_pos_y: 1855707.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2467382.75
      sim_grid_pos_y: 1855536.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2467671.25
      sim_grid_pos_y: 1855599.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2468011.75
      sim_grid_pos_y: 1855196.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.46766e+06
      sim_grid_pos_y: 1854764.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2467585.25
      sim_grid_pos_y: 1854452.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2467017.5
      sim_grid_pos_y: 1854009.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2466404.75
      sim_grid_pos_y: 1854681
    }
    terrain_level_point {
      sim_grid_pos_x: 2466361.25
      sim_grid_pos_y: 1855360.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466899.75
      sim_grid_pos_y: 1855824.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2467390.25
      sim_grid_pos_y: 1855642.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2467709.75
      sim_grid_pos_y: 1855712.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2468145
      sim_grid_pos_y: 1855197.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2467754.25
      sim_grid_pos_y: 1854718.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2467674.75
      sim_grid_pos_y: 1854385.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2466997
      sim_grid_pos_y: 1853879.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2466304.75
      sim_grid_pos_y: 1854638.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2466255.75
      sim_grid_pos_y: 1855404.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2466878.5
      sim_grid_pos_y: 1855941.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2467397.75
      sim_grid_pos_y: 1855749.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2467748.25
      sim_grid_pos_y: 1855826.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2468278
      sim_grid_pos_y: 1855199.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2467848.5
      sim_grid_pos_y: 1854671.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2467764
      sim_grid_pos_y: 1854318.88
    }
  }
}
terrain_level_data {
  terrain_level: 4075
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2476259
      sim_grid_pos_y: 1855390.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2476782.5
      sim_grid_pos_y: 1855458.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2476408
      sim_grid_pos_y: 1855781.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2476252
      sim_grid_pos_y: 1856133.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2475933.25
      sim_grid_pos_y: 1856304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2475777
      sim_grid_pos_y: 1856773
    }
    terrain_level_point {
      sim_grid_pos_x: 2475380.5
      sim_grid_pos_y: 1857040.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2475262.25
      sim_grid_pos_y: 1857463.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2474977.75
      sim_grid_pos_y: 1857648.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2474963.5
      sim_grid_pos_y: 1858136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2474496.25
      sim_grid_pos_y: 1858512.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2474262.75
      sim_grid_pos_y: 1858376.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2474547.75
      sim_grid_pos_y: 1857729.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2475469.5
      sim_grid_pos_y: 1856373.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2476861.75
      sim_grid_pos_y: 1855365.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2476899.75
      sim_grid_pos_y: 1855492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2476492.5
      sim_grid_pos_y: 1855844
    }
    terrain_level_point {
      sim_grid_pos_x: 2476331.5
      sim_grid_pos_y: 1856207
    }
    terrain_level_point {
      sim_grid_pos_x: 2476017.5
      sim_grid_pos_y: 1856375.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2475863.25
      sim_grid_pos_y: 1856838.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2475469.25
      sim_grid_pos_y: 1857104.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2475350.5
      sim_grid_pos_y: 1857528.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2475078.5
      sim_grid_pos_y: 1857705.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2475064.5
      sim_grid_pos_y: 1858186.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2474505.5
      sim_grid_pos_y: 1858636.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2474132
      sim_grid_pos_y: 1858418.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2474457.75
      sim_grid_pos_y: 1857679.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2475387
      sim_grid_pos_y: 1856312.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2476215.25
      sim_grid_pos_y: 1855281
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2476940.75
      sim_grid_pos_y: 1855272.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2477017
      sim_grid_pos_y: 1855527
    }
    terrain_level_point {
      sim_grid_pos_x: 2476576.75
      sim_grid_pos_y: 1855906.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2476410.75
      sim_grid_pos_y: 1856280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2476102
      sim_grid_pos_y: 1856446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2475949.5
      sim_grid_pos_y: 1856904
    }
    terrain_level_point {
      sim_grid_pos_x: 2475557.75
      sim_grid_pos_y: 1857168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2475439
      sim_grid_pos_y: 1857593
    }
    terrain_level_point {
      sim_grid_pos_x: 2475179.5
      sim_grid_pos_y: 1857762
    }
    terrain_level_point {
      sim_grid_pos_x: 2475165.75
      sim_grid_pos_y: 1858236.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2474515
      sim_grid_pos_y: 1858760.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2474001.25
      sim_grid_pos_y: 1858461.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2474367.75
      sim_grid_pos_y: 1857629.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2475304.5
      sim_grid_pos_y: 1856251.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2476171.25
      sim_grid_pos_y: 1855171.88
    }
  }
}
terrain_level_data {
  terrain_level: 4200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2471027
      sim_grid_pos_y: 1860607.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2470250.5
      sim_grid_pos_y: 1860324.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2469744.75
      sim_grid_pos_y: 1860803.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2469361.25
      sim_grid_pos_y: 1862008
    }
    terrain_level_point {
      sim_grid_pos_x: 2469637
      sim_grid_pos_y: 1862460.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2469719.25
      sim_grid_pos_y: 1862901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2469812
      sim_grid_pos_y: 1863055.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2470372.5
      sim_grid_pos_y: 1862407
    }
    terrain_level_point {
      sim_grid_pos_x: 2470315
      sim_grid_pos_y: 1861641.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2470226
      sim_grid_pos_y: 1860206.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2469655
      sim_grid_pos_y: 1860747.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2469249.25
      sim_grid_pos_y: 1862021.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2469539.5
      sim_grid_pos_y: 1862498
    }
    terrain_level_point {
      sim_grid_pos_x: 2469622
      sim_grid_pos_y: 1862938.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2469797.25
      sim_grid_pos_y: 1.86323e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2470477.75
      sim_grid_pos_y: 1862441.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.47042e+06
      sim_grid_pos_y: 1861669.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2471186.5
      sim_grid_pos_y: 1860556.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2470201.5
      sim_grid_pos_y: 1860088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2469565.5
      sim_grid_pos_y: 1860691.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2469137.5
      sim_grid_pos_y: 1862034.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2469442.25
      sim_grid_pos_y: 1862535.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2469524.5
      sim_grid_pos_y: 1862975.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2469782.25
      sim_grid_pos_y: 1863404.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2470583.25
      sim_grid_pos_y: 1862476.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2470525
      sim_grid_pos_y: 1861698.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2471346
      sim_grid_pos_y: 1860505.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2470177
      sim_grid_pos_y: 1859970.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2469475.75
      sim_grid_pos_y: 1860635
    }
    terrain_level_point {
      sim_grid_pos_x: 2469025.5
      sim_grid_pos_y: 1862048.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2469345
      sim_grid_pos_y: 1862572.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2469427.25
      sim_grid_pos_y: 1863012.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2469767.5
      sim_grid_pos_y: 1863578.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2470688.75
      sim_grid_pos_y: 1862511.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2470629.75
      sim_grid_pos_y: 1861726.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2471505.5
      sim_grid_pos_y: 1860454.25
    }
  }
}
terrain_level_data {
  terrain_level: 4025
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2473653.75
      sim_grid_pos_y: 1859018.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2473740.5
      sim_grid_pos_y: 1858888.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2474742
      sim_grid_pos_y: 1858892.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2477349.25
      sim_grid_pos_y: 1855484.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2477979.75
      sim_grid_pos_y: 1856127.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2472133.25
      sim_grid_pos_y: 1863979.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2471595.75
      sim_grid_pos_y: 1863771.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2471625
      sim_grid_pos_y: 1863402.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2472525.5
      sim_grid_pos_y: 1861997.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2473143
      sim_grid_pos_y: 1861423.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2473824.5
      sim_grid_pos_y: 1859861.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2478114.5
      sim_grid_pos_y: 1856118.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2472169
      sim_grid_pos_y: 1864102.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2471487.5
      sim_grid_pos_y: 1863839.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2471524.75
      sim_grid_pos_y: 1863368.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2472446.25
      sim_grid_pos_y: 1861931.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2473057.75
      sim_grid_pos_y: 1861362.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2473717.75
      sim_grid_pos_y: 1859850.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2473544.75
      sim_grid_pos_y: 1858997.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2473685.75
      sim_grid_pos_y: 1858786
    }
    terrain_level_point {
      sim_grid_pos_x: 2474691.5
      sim_grid_pos_y: 1858789.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2477339.75
      sim_grid_pos_y: 1855328
    }
  }
}
