terrain_level_data {
  terrain_level: 355
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1545485.5
      sim_grid_pos_y: 1298822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1545507.88
      sim_grid_pos_y: 1299071.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1545636.5
      sim_grid_pos_y: 1.29926e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1545801.62
      sim_grid_pos_y: 1299147.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545928.88
      sim_grid_pos_y: 1299242.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546054
      sim_grid_pos_y: 1299233.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546178.12
      sim_grid_pos_y: 1299458.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1546279.38
      sim_grid_pos_y: 1299492.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546399.88
      sim_grid_pos_y: 1299452
    }
    terrain_level_point {
      sim_grid_pos_x: 1546429.5
      sim_grid_pos_y: 1299312.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546393.12
      sim_grid_pos_y: 1299169
    }
    terrain_level_point {
      sim_grid_pos_x: 1546193.75
      sim_grid_pos_y: 1299016.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546221.25
      sim_grid_pos_y: 1298792.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546114.88
      sim_grid_pos_y: 1298701.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546098
      sim_grid_pos_y: 1298477.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1545842.5
      sim_grid_pos_y: 1298425.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545607.5
      sim_grid_pos_y: 1298524.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1545837.12
      sim_grid_pos_y: 1298372
    }
    terrain_level_point {
      sim_grid_pos_x: 1545568.12
      sim_grid_pos_y: 1298485.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1545433.38
      sim_grid_pos_y: 1298814.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545458
      sim_grid_pos_y: 1299089.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1545623
      sim_grid_pos_y: 1299331.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1545800.38
      sim_grid_pos_y: 1299210.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545913.5
      sim_grid_pos_y: 1299294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1546024.88
      sim_grid_pos_y: 1299287
    }
    terrain_level_point {
      sim_grid_pos_x: 1546142.88
      sim_grid_pos_y: 1299500.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1546279.38
      sim_grid_pos_y: 1299547
    }
    terrain_level_point {
      sim_grid_pos_x: 1546444
      sim_grid_pos_y: 1299491.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546482.12
      sim_grid_pos_y: 1299311.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546438.38
      sim_grid_pos_y: 1299139.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546248.25
      sim_grid_pos_y: 1298993.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1546275.5
      sim_grid_pos_y: 1298771.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546164.38
      sim_grid_pos_y: 1298676.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546146.12
      sim_grid_pos_y: 1298434.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1545831.88
      sim_grid_pos_y: 1298318.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1545528.62
      sim_grid_pos_y: 1298446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1545381.12
      sim_grid_pos_y: 1298806.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1545408.12
      sim_grid_pos_y: 1299107
    }
    terrain_level_point {
      sim_grid_pos_x: 1545609.5
      sim_grid_pos_y: 1299402.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1545799
      sim_grid_pos_y: 1299273.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1545898
      sim_grid_pos_y: 1299347
    }
    terrain_level_point {
      sim_grid_pos_x: 1545995.75
      sim_grid_pos_y: 1299340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546107.62
      sim_grid_pos_y: 1299543
    }
    terrain_level_point {
      sim_grid_pos_x: 1546279.38
      sim_grid_pos_y: 1299601.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546488
      sim_grid_pos_y: 1299530.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546534.75
      sim_grid_pos_y: 1299310.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546483.75
      sim_grid_pos_y: 1299109.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546302.62
      sim_grid_pos_y: 1298971
    }
    terrain_level_point {
      sim_grid_pos_x: 1546329.75
      sim_grid_pos_y: 1298750.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546213.88
      sim_grid_pos_y: 1298651.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1546194.38
      sim_grid_pos_y: 1298392
    }
  }
}
terrain_level_data {
  terrain_level: 354
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1546503.12
      sim_grid_pos_y: 1299205
    }
    terrain_level_point {
      sim_grid_pos_x: 1546500.38
      sim_grid_pos_y: 1299527.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546715.25
      sim_grid_pos_y: 1299522.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1546720.75
      sim_grid_pos_y: 1299202.75
    }
  }
}
terrain_level_data {
  terrain_level: 280
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1545639
      sim_grid_pos_y: 1299558.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1545545.88
      sim_grid_pos_y: 1300212.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545909.25
      sim_grid_pos_y: 1300232
    }
    terrain_level_point {
      sim_grid_pos_x: 1545893.25
      sim_grid_pos_y: 1299788.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1545964.75
      sim_grid_pos_y: 1299564.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1545594.62
      sim_grid_pos_y: 1299506.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1545487.12
      sim_grid_pos_y: 1300260.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1545962.5
      sim_grid_pos_y: 1300286.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1545944.88
      sim_grid_pos_y: 1299795.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546034.62
      sim_grid_pos_y: 1299514
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1545550.25
      sim_grid_pos_y: 1299454.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1545428.5
      sim_grid_pos_y: 1300308.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1546015.75
      sim_grid_pos_y: 1300340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545996.38
      sim_grid_pos_y: 1299802.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1546104.38
      sim_grid_pos_y: 1299463.88
    }
  }
}
terrain_level_data {
  terrain_level: 240
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1545199.75
      sim_grid_pos_y: 1302347.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1545104
      sim_grid_pos_y: 1302619.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1545367.5
      sim_grid_pos_y: 1302816.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545422
      sim_grid_pos_y: 1302810.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1545547.88
      sim_grid_pos_y: 1302416.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1545166.25
      sim_grid_pos_y: 1302288.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1545043.12
      sim_grid_pos_y: 1302638.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545352.75
      sim_grid_pos_y: 1302869.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545460.62
      sim_grid_pos_y: 1302858.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1545614.12
      sim_grid_pos_y: 1302377.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1545132.62
      sim_grid_pos_y: 1302229.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1544982.25
      sim_grid_pos_y: 1302656.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1545338.12
      sim_grid_pos_y: 1302922.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1545499.25
      sim_grid_pos_y: 1302906.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1545680.38
      sim_grid_pos_y: 1302338.75
    }
  }
}
terrain_level_data {
  terrain_level: 328
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1545713
      sim_grid_pos_y: 1298097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1545598.5
      sim_grid_pos_y: 1298245.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1545794.5
      sim_grid_pos_y: 1298394
    }
    terrain_level_point {
      sim_grid_pos_x: 1545884.88
      sim_grid_pos_y: 1298255.75
    }
  }
}
