terrain_level_data {
  terrain_level: 92
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2294439
      sim_grid_pos_y: 846526.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2294317.25
      sim_grid_pos_y: 846553
    }
    terrain_level_point {
      sim_grid_pos_x: 2294276
      sim_grid_pos_y: 846715.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2294321.5
      sim_grid_pos_y: 846859.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2294243
      sim_grid_pos_y: 847005.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2294299.25
      sim_grid_pos_y: 847188.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2294449
      sim_grid_pos_y: 847230.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2294442.75
      sim_grid_pos_y: 847066.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2294435
      sim_grid_pos_y: 846865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2294451.5
      sim_grid_pos_y: 846652.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2294529.75
      sim_grid_pos_y: 846402.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2294233.5
      sim_grid_pos_y: 846466.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2294169.5
      sim_grid_pos_y: 846718.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2294210.75
      sim_grid_pos_y: 846849.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2294132.5
      sim_grid_pos_y: 846995
    }
    terrain_level_point {
      sim_grid_pos_x: 2294217.75
      sim_grid_pos_y: 847271.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2294556.75
      sim_grid_pos_y: 847368.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2294545.25
      sim_grid_pos_y: 847063
    }
    terrain_level_point {
      sim_grid_pos_x: 2294545.25
      sim_grid_pos_y: 847063
    }
    terrain_level_point {
      sim_grid_pos_x: 2294537.75
      sim_grid_pos_y: 846867.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2294554.5
      sim_grid_pos_y: 846651.375
    }
  }
}
terrain_level_data {
  terrain_level: 50
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2291458
      sim_grid_pos_y: 840508.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2291401.25
      sim_grid_pos_y: 840618.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2291449.25
      sim_grid_pos_y: 840737.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2291547.25
      sim_grid_pos_y: 840772.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2291657.25
      sim_grid_pos_y: 840740.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29171e+06
      sim_grid_pos_y: 840615.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2291682.75
      sim_grid_pos_y: 840511.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2291572.25
      sim_grid_pos_y: 840467
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2291573.25
      sim_grid_pos_y: 840412
    }
    terrain_level_point {
      sim_grid_pos_x: 2291421.75
      sim_grid_pos_y: 840467.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2291345
      sim_grid_pos_y: 840615.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2291410.25
      sim_grid_pos_y: 840777.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2291545.5
      sim_grid_pos_y: 840826.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2291695.25
      sim_grid_pos_y: 840783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2291763.75
      sim_grid_pos_y: 840619.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2291725.75
      sim_grid_pos_y: 840474
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2291574
      sim_grid_pos_y: 840357.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2291385.25
      sim_grid_pos_y: 840426.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2291288.75
      sim_grid_pos_y: 840613.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2291371.25
      sim_grid_pos_y: 840818.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2291543.75
      sim_grid_pos_y: 840880.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2291733
      sim_grid_pos_y: 840825.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2291817.75
      sim_grid_pos_y: 840623
    }
    terrain_level_point {
      sim_grid_pos_x: 2291768.75
      sim_grid_pos_y: 840436.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2291575
      sim_grid_pos_y: 840302.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2291349
      sim_grid_pos_y: 840385.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2291232.25
      sim_grid_pos_y: 840610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2291332.25
      sim_grid_pos_y: 840858.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2291542
      sim_grid_pos_y: 840934.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2291770.75
      sim_grid_pos_y: 840868.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2291871.75
      sim_grid_pos_y: 840626.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2291812
      sim_grid_pos_y: 840398.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2291576
      sim_grid_pos_y: 840247.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2291312.5
      sim_grid_pos_y: 840343.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2291176
      sim_grid_pos_y: 840607.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2291293.25
      sim_grid_pos_y: 840898.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2291540.25
      sim_grid_pos_y: 840988.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2291808.75
      sim_grid_pos_y: 840910.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2291925.75
      sim_grid_pos_y: 840630.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2291855
      sim_grid_pos_y: 840360.5
    }
  }
}
terrain_level_data {
  terrain_level: 95
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2292192.75
      sim_grid_pos_y: 841979
    }
    terrain_level_point {
      sim_grid_pos_x: 2292168.75
      sim_grid_pos_y: 842093.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2292174.25
      sim_grid_pos_y: 842211.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2292271.75
      sim_grid_pos_y: 842262.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2292383
      sim_grid_pos_y: 842234.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2292406.25
      sim_grid_pos_y: 842098.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2292359
      sim_grid_pos_y: 841974.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2292274.25
      sim_grid_pos_y: 841944.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2292272.5
      sim_grid_pos_y: 841890
    }
    terrain_level_point {
      sim_grid_pos_x: 2292148.25
      sim_grid_pos_y: 841942.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2292117.25
      sim_grid_pos_y: 842089.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2292124.25
      sim_grid_pos_y: 842243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2292265.25
      sim_grid_pos_y: 842316.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2292427.75
      sim_grid_pos_y: 842275.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2292459.25
      sim_grid_pos_y: 842093.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2292398.25
      sim_grid_pos_y: 841933.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2292270.75
      sim_grid_pos_y: 841835.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2292103.5
      sim_grid_pos_y: 841905.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2292065.5
      sim_grid_pos_y: 842085.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2292074.5
      sim_grid_pos_y: 842275.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2292258.75
      sim_grid_pos_y: 842371.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2292472.75
      sim_grid_pos_y: 842317.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2292512
      sim_grid_pos_y: 842088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2292437.75
      sim_grid_pos_y: 841893.125
    }
  }
}
terrain_level_data {
  terrain_level: 42
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2299128.5
      sim_grid_pos_y: 842998.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2295722
      sim_grid_pos_y: 839758.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2293913.25
      sim_grid_pos_y: 838139.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2291952.75
      sim_grid_pos_y: 836830.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2291138
      sim_grid_pos_y: 837555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2291823.5
      sim_grid_pos_y: 838220.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2291162.25
      sim_grid_pos_y: 838828.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2292076
      sim_grid_pos_y: 839600.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2294269.25
      sim_grid_pos_y: 841799.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2294354.5
      sim_grid_pos_y: 842510.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2292147
      sim_grid_pos_y: 842896.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2292214.5
      sim_grid_pos_y: 843422.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2292503.25
      sim_grid_pos_y: 843389.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2292449.25
      sim_grid_pos_y: 842970.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2294713.25
      sim_grid_pos_y: 842743.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2295854.5
      sim_grid_pos_y: 849661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2295598.5
      sim_grid_pos_y: 849901.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29574e+06
      sim_grid_pos_y: 850790.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2295889.75
      sim_grid_pos_y: 851380.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2296348.25
      sim_grid_pos_y: 851450.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296168.5
      sim_grid_pos_y: 849719.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2295589.25
      sim_grid_pos_y: 846233.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2295001
      sim_grid_pos_y: 842731.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2295553
      sim_grid_pos_y: 842755.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2296652
      sim_grid_pos_y: 843906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296351.75
      sim_grid_pos_y: 844631.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2296777
      sim_grid_pos_y: 844994.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2298148
      sim_grid_pos_y: 844331.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2291943.75
      sim_grid_pos_y: 836700.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2290987.5
      sim_grid_pos_y: 837552.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2291674.25
      sim_grid_pos_y: 838218.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2291007.25
      sim_grid_pos_y: 838831.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2292006.5
      sim_grid_pos_y: 839676.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2294171.5
      sim_grid_pos_y: 841846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2294241
      sim_grid_pos_y: 842426.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2292032.75
      sim_grid_pos_y: 842812.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2292125.75
      sim_grid_pos_y: 843535.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2292618.25
      sim_grid_pos_y: 843480
    }
    terrain_level_point {
      sim_grid_pos_x: 2292564.25
      sim_grid_pos_y: 843061.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2294627.75
      sim_grid_pos_y: 842854.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2295744.5
      sim_grid_pos_y: 849623.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2295488.5
      sim_grid_pos_y: 849863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2295639.5
      sim_grid_pos_y: 850811
    }
    terrain_level_point {
      sim_grid_pos_x: 2295807
      sim_grid_pos_y: 851472.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2296463.75
      sim_grid_pos_y: 851571.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296270.25
      sim_grid_pos_y: 849705.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2295690.25
      sim_grid_pos_y: 846216.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2295123
      sim_grid_pos_y: 842839.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2295507.25
      sim_grid_pos_y: 842856.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296531.75
      sim_grid_pos_y: 843929.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296228.75
      sim_grid_pos_y: 844660.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2296761.25
      sim_grid_pos_y: 845116.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2298215.75
      sim_grid_pos_y: 844412.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2299264.5
      sim_grid_pos_y: 842986.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2295791.5
      sim_grid_pos_y: 839682.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2293976.25
      sim_grid_pos_y: 838058.625
    }
  }
}
terrain_level_data {
  terrain_level: 33
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2293309.25
      sim_grid_pos_y: 843624.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2293196.5
      sim_grid_pos_y: 842922.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2294045.5
      sim_grid_pos_y: 842795.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2294179.5
      sim_grid_pos_y: 843508
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2294300.25
      sim_grid_pos_y: 843595.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2293223.75
      sim_grid_pos_y: 843739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2293079
      sim_grid_pos_y: 842836.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2294128
      sim_grid_pos_y: 842679.688
    }
  }
}
