terrain_level_data {
  terrain_level: 88
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2000801.25
      sim_grid_pos_y: 148227.734
    }
    terrain_level_point {
      sim_grid_pos_x: 2001094.12
      sim_grid_pos_y: 148187.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2001418.5
      sim_grid_pos_y: 148317.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2001426.25
      sim_grid_pos_y: 148745.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2001351.25
      sim_grid_pos_y: 149077.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2000778.12
      sim_grid_pos_y: 149025.156
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2001469.25
      sim_grid_pos_y: 148282.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2001477.62
      sim_grid_pos_y: 148750.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2001391.38
      sim_grid_pos_y: 149132.297
    }
    terrain_level_point {
      sim_grid_pos_x: 2000725.5
      sim_grid_pos_y: 149071.859
    }
    terrain_level_point {
      sim_grid_pos_x: 2000751.25
      sim_grid_pos_y: 148182.828
    }
    terrain_level_point {
      sim_grid_pos_x: 2001100.62
      sim_grid_pos_y: 148135.156
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2001519.88
      sim_grid_pos_y: 148247.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2001529
      sim_grid_pos_y: 148756.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2001431.38
      sim_grid_pos_y: 149187.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2000672.88
      sim_grid_pos_y: 149118.547
    }
    terrain_level_point {
      sim_grid_pos_x: 2000701.25
      sim_grid_pos_y: 148137.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2001107.12
      sim_grid_pos_y: 148082.531
    }
  }
}
