terrain_level_data {
  terrain_level: 125
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2010299.75
      sim_grid_pos_y: 1247344.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2010710.88
      sim_grid_pos_y: 1247989.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2011216
      sim_grid_pos_y: 1248483.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2012726
      sim_grid_pos_y: 1248688.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2013488
      sim_grid_pos_y: 1248165.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2010631.5
      sim_grid_pos_y: 1244028
    }
    terrain_level_point {
      sim_grid_pos_x: 2010613.88
      sim_grid_pos_y: 1244156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2010258.75
      sim_grid_pos_y: 1246071.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2010111.38
      sim_grid_pos_y: 1246943.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2010644.75
      sim_grid_pos_y: 1243993.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2010603.88
      sim_grid_pos_y: 1244003
    }
    terrain_level_point {
      sim_grid_pos_x: 2010583.5
      sim_grid_pos_y: 1244152
    }
    terrain_level_point {
      sim_grid_pos_x: 2010228.5
      sim_grid_pos_y: 1246066
    }
    terrain_level_point {
      sim_grid_pos_x: 2010079.38
      sim_grid_pos_y: 1246947.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2010272.75
      sim_grid_pos_y: 1247359.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2010686.88
      sim_grid_pos_y: 1248008.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2011201.75
      sim_grid_pos_y: 1248512.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2012733.62
      sim_grid_pos_y: 1248720.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2013530.75
      sim_grid_pos_y: 1248173.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2010658.12
      sim_grid_pos_y: 1243958.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2010576.25
      sim_grid_pos_y: 1243977.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2010553.12
      sim_grid_pos_y: 1244147
    }
    terrain_level_point {
      sim_grid_pos_x: 2010198.25
      sim_grid_pos_y: 1246060.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2010047.5
      sim_grid_pos_y: 1246952.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2010245.75
      sim_grid_pos_y: 1247374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2010662.75
      sim_grid_pos_y: 1248028.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2011187.5
      sim_grid_pos_y: 1248541.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2012741.25
      sim_grid_pos_y: 1248752.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2013573.62
      sim_grid_pos_y: 1248181.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2010671.5
      sim_grid_pos_y: 1243923.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2010548.5
      sim_grid_pos_y: 1243952.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2010522.75
      sim_grid_pos_y: 1244142
    }
    terrain_level_point {
      sim_grid_pos_x: 2010167.88
      sim_grid_pos_y: 1246055.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2010015.5
      sim_grid_pos_y: 1246956.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2010218.75
      sim_grid_pos_y: 1247389.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2010638.75
      sim_grid_pos_y: 1248047.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2011173.25
      sim_grid_pos_y: 1248571
    }
    terrain_level_point {
      sim_grid_pos_x: 2012748.88
      sim_grid_pos_y: 1248784.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2013616.5
      sim_grid_pos_y: 1248189.62
    }
  }
}
