terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3348405
      sim_grid_pos_y: 2757564.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3349042.25
      sim_grid_pos_y: 2758092.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3350283.5
      sim_grid_pos_y: 2753995.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3351424.25
      sim_grid_pos_y: 2753232.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3351162.25
      sim_grid_pos_y: 2752923
    }
    terrain_level_point {
      sim_grid_pos_x: 3350089.75
      sim_grid_pos_y: 2752465
    }
    terrain_level_point {
      sim_grid_pos_x: 3348763.5
      sim_grid_pos_y: 2748355.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348467.5
      sim_grid_pos_y: 2746337.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3346625.25
      sim_grid_pos_y: 2744487.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3343514.5
      sim_grid_pos_y: 2747121.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3344190.5
      sim_grid_pos_y: 2747410.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3344672.75
      sim_grid_pos_y: 2747833
    }
    terrain_level_point {
      sim_grid_pos_x: 3345416.5
      sim_grid_pos_y: 2748685
    }
    terrain_level_point {
      sim_grid_pos_x: 3346056.75
      sim_grid_pos_y: 2749473
    }
    terrain_level_point {
      sim_grid_pos_x: 3346816.5
      sim_grid_pos_y: 2750645.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3347532.25
      sim_grid_pos_y: 2751941.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3348081
      sim_grid_pos_y: 2753200.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3348544.25
      sim_grid_pos_y: 2754801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348431.75
      sim_grid_pos_y: 2756425.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 3346627
      sim_grid_pos_y: 2744445.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3343456.75
      sim_grid_pos_y: 2.74713e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 3344174
      sim_grid_pos_y: 2747436.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3344651
      sim_grid_pos_y: 2747854.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3345393
      sim_grid_pos_y: 2748704.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3346031.75
      sim_grid_pos_y: 2749491
    }
    terrain_level_point {
      sim_grid_pos_x: 3346790.25
      sim_grid_pos_y: 2750661.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3347504.75
      sim_grid_pos_y: 2751955
    }
    terrain_level_point {
      sim_grid_pos_x: 3348052
      sim_grid_pos_y: 2753210.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348513.25
      sim_grid_pos_y: 2754805
    }
    terrain_level_point {
      sim_grid_pos_x: 3348401
      sim_grid_pos_y: 2756424
    }
    terrain_level_point {
      sim_grid_pos_x: 3348373.75
      sim_grid_pos_y: 2757578.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3349058.25
      sim_grid_pos_y: 2758146
    }
    terrain_level_point {
      sim_grid_pos_x: 3350309.75
      sim_grid_pos_y: 2754015.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3.35147e+06
      sim_grid_pos_y: 2753239.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3351181
      sim_grid_pos_y: 2752897.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3350114.75
      sim_grid_pos_y: 2752442.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3348793.5
      sim_grid_pos_y: 2748348.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348496.5
      sim_grid_pos_y: 2746323
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 3346628.75
      sim_grid_pos_y: 2744403.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3343398.75
      sim_grid_pos_y: 2747138.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3344157.5
      sim_grid_pos_y: 2747463
    }
    terrain_level_point {
      sim_grid_pos_x: 3344629
      sim_grid_pos_y: 2747876.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3345369.5
      sim_grid_pos_y: 2748724.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3346007
      sim_grid_pos_y: 2749509.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3346763.75
      sim_grid_pos_y: 2750677.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3347477
      sim_grid_pos_y: 2751968.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3348023
      sim_grid_pos_y: 2753221.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3348482.25
      sim_grid_pos_y: 2754808.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3348370.25
      sim_grid_pos_y: 2756422.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348342.75
      sim_grid_pos_y: 2757593
    }
    terrain_level_point {
      sim_grid_pos_x: 3349074.25
      sim_grid_pos_y: 2758199.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3350336
      sim_grid_pos_y: 2754034.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3351515.75
      sim_grid_pos_y: 2753245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3351199.75
      sim_grid_pos_y: 2752872.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3350139.75
      sim_grid_pos_y: 2752419.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3348823.5
      sim_grid_pos_y: 2748341.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348525.25
      sim_grid_pos_y: 2746308.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 3346630.5
      sim_grid_pos_y: 2744362
    }
    terrain_level_point {
      sim_grid_pos_x: 3343341
      sim_grid_pos_y: 2747147.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3344140.75
      sim_grid_pos_y: 2747489.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3344607.25
      sim_grid_pos_y: 2747898.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3345345.75
      sim_grid_pos_y: 2748744.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3345982
      sim_grid_pos_y: 2749527.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3346737.25
      sim_grid_pos_y: 2750693.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3347449.5
      sim_grid_pos_y: 2751982.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3347994
      sim_grid_pos_y: 2753231.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348451
      sim_grid_pos_y: 2754811.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3348339.5
      sim_grid_pos_y: 2756421.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3348311.75
      sim_grid_pos_y: 2757607
    }
    terrain_level_point {
      sim_grid_pos_x: 3349090.25
      sim_grid_pos_y: 2758252.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3350362.25
      sim_grid_pos_y: 2754054
    }
    terrain_level_point {
      sim_grid_pos_x: 3351561.5
      sim_grid_pos_y: 2753252
    }
    terrain_level_point {
      sim_grid_pos_x: 3351218.5
      sim_grid_pos_y: 2752846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3350164.75
      sim_grid_pos_y: 2752396.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348853.5
      sim_grid_pos_y: 2748334.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3348554.25
      sim_grid_pos_y: 2746294
    }
  }
}
