terrain_level_data {
  terrain_level: 370
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1459847.5
      sim_grid_pos_y: 1526652.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460692.88
      sim_grid_pos_y: 1525812
    }
    terrain_level_point {
      sim_grid_pos_x: 1460993.5
      sim_grid_pos_y: 1525714.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461308.5
      sim_grid_pos_y: 1525930.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461254.62
      sim_grid_pos_y: 1526073.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461354.62
      sim_grid_pos_y: 1526184
    }
    terrain_level_point {
      sim_grid_pos_x: 1460934.5
      sim_grid_pos_y: 1526854.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460804.75
      sim_grid_pos_y: 1527036.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460661.62
      sim_grid_pos_y: 1527163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1459818.5
      sim_grid_pos_y: 1527820.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1459323
      sim_grid_pos_y: 1527882
    }
    terrain_level_point {
      sim_grid_pos_x: 1459346.25
      sim_grid_pos_y: 1527361.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1461345.75
      sim_grid_pos_y: 1525918.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.46129e+06
      sim_grid_pos_y: 1526066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461393
      sim_grid_pos_y: 1526180.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460960.12
      sim_grid_pos_y: 1526871.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1460827.75
      sim_grid_pos_y: 1527056.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460681.25
      sim_grid_pos_y: 1527187.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1459830.75
      sim_grid_pos_y: 1.52785e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1459290.75
      sim_grid_pos_y: 1527917
    }
    terrain_level_point {
      sim_grid_pos_x: 1459315.88
      sim_grid_pos_y: 1527351
    }
    terrain_level_point {
      sim_grid_pos_x: 1459823.88
      sim_grid_pos_y: 1526632.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460676.38
      sim_grid_pos_y: 1525784.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460998.5
      sim_grid_pos_y: 1525681
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1461383
      sim_grid_pos_y: 1525906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461325.38
      sim_grid_pos_y: 1.52606e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1461431.5
      sim_grid_pos_y: 1526177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460985.75
      sim_grid_pos_y: 1526888.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460850.88
      sim_grid_pos_y: 1527077.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460701
      sim_grid_pos_y: 1527210.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1459843
      sim_grid_pos_y: 1527879.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1459258.38
      sim_grid_pos_y: 1527952
    }
    terrain_level_point {
      sim_grid_pos_x: 1459285.5
      sim_grid_pos_y: 1527340.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1459800.38
      sim_grid_pos_y: 1526613
    }
    terrain_level_point {
      sim_grid_pos_x: 1460659.88
      sim_grid_pos_y: 1525757.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461003.38
      sim_grid_pos_y: 1525647.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1461420.38
      sim_grid_pos_y: 1525895
    }
    terrain_level_point {
      sim_grid_pos_x: 1461360.75
      sim_grid_pos_y: 1526053.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461469.88
      sim_grid_pos_y: 1526173.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461011.25
      sim_grid_pos_y: 1526905.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460873.88
      sim_grid_pos_y: 1527098.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460720.62
      sim_grid_pos_y: 1527234.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1459855.12
      sim_grid_pos_y: 1527909
    }
    terrain_level_point {
      sim_grid_pos_x: 1459226
      sim_grid_pos_y: 1527987
    }
    terrain_level_point {
      sim_grid_pos_x: 1459255.25
      sim_grid_pos_y: 1527330.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1459776.75
      sim_grid_pos_y: 1526593
    }
    terrain_level_point {
      sim_grid_pos_x: 1460643.38
      sim_grid_pos_y: 1525730.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461008.25
      sim_grid_pos_y: 1525613.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1461457.62
      sim_grid_pos_y: 1525883.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461396.25
      sim_grid_pos_y: 1526046.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461508.25
      sim_grid_pos_y: 1526170.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461036.88
      sim_grid_pos_y: 1526922.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1460896.88
      sim_grid_pos_y: 1527119
    }
    terrain_level_point {
      sim_grid_pos_x: 1460740.38
      sim_grid_pos_y: 1527258.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1459867.38
      sim_grid_pos_y: 1527938.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1459193.62
      sim_grid_pos_y: 1528022
    }
    terrain_level_point {
      sim_grid_pos_x: 1459224.88
      sim_grid_pos_y: 1527319.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1459753.12
      sim_grid_pos_y: 1526573.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460627
      sim_grid_pos_y: 1525703.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461013.25
      sim_grid_pos_y: 1525579.38
    }
  }
}
