terrain_level_data {
  terrain_level: 740
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2971172
      sim_grid_pos_y: 895342.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2970896.25
      sim_grid_pos_y: 895403.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2970531
      sim_grid_pos_y: 894469.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2970795.75
      sim_grid_pos_y: 894183
    }
    terrain_level_point {
      sim_grid_pos_x: 2971180.75
      sim_grid_pos_y: 893995.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2971663.25
      sim_grid_pos_y: 894059.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2971782.75
      sim_grid_pos_y: 894259.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2971479.75
      sim_grid_pos_y: 894377.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2971692.5
      sim_grid_pos_y: 895153
    }
    terrain_level_point {
      sim_grid_pos_x: 2971561.25
      sim_grid_pos_y: 895535.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2971682
      sim_grid_pos_y: 894031.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2971827.75
      sim_grid_pos_y: 894275.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2971516.75
      sim_grid_pos_y: 894396.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2971724.5
      sim_grid_pos_y: 895154
    }
    terrain_level_point {
      sim_grid_pos_x: 2971579
      sim_grid_pos_y: 895578.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2971168
      sim_grid_pos_y: 895374.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2970877.25
      sim_grid_pos_y: 895438.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2970495.25
      sim_grid_pos_y: 894463.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2970777
      sim_grid_pos_y: 894157.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2971175.75
      sim_grid_pos_y: 893964.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2971700.75
      sim_grid_pos_y: 894002.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2971873
      sim_grid_pos_y: 894290.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2971553.75
      sim_grid_pos_y: 894414.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2971756.75
      sim_grid_pos_y: 895155
    }
    terrain_level_point {
      sim_grid_pos_x: 2971596.75
      sim_grid_pos_y: 895621.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2971164.25
      sim_grid_pos_y: 895407.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2970858
      sim_grid_pos_y: 895474.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2970459.75
      sim_grid_pos_y: 894456.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2970758.25
      sim_grid_pos_y: 894132.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2971170.5
      sim_grid_pos_y: 893932.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2971719.5
      sim_grid_pos_y: 893974.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2971918
      sim_grid_pos_y: 894306.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2971590.75
      sim_grid_pos_y: 894433.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2971789
      sim_grid_pos_y: 895156
    }
    terrain_level_point {
      sim_grid_pos_x: 2971614.5
      sim_grid_pos_y: 895664.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2971160.25
      sim_grid_pos_y: 895439.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2970839
      sim_grid_pos_y: 895510.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2970424
      sim_grid_pos_y: 894449.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2970739.75
      sim_grid_pos_y: 894107.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2971165.5
      sim_grid_pos_y: 893900.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2971738.25
      sim_grid_pos_y: 893945.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2971963
      sim_grid_pos_y: 894321.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2971627.75
      sim_grid_pos_y: 894451.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2971821.25
      sim_grid_pos_y: 895157.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2971632.25
      sim_grid_pos_y: 895707.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2971156.25
      sim_grid_pos_y: 895471.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2.97082e+06
      sim_grid_pos_y: 895546
    }
    terrain_level_point {
      sim_grid_pos_x: 2970388.5
      sim_grid_pos_y: 894442.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2970721
      sim_grid_pos_y: 894082.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2971160.25
      sim_grid_pos_y: 893869.062
    }
  }
}
terrain_level_data {
  terrain_level: 777
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2972064.5
      sim_grid_pos_y: 894551.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2971838.75
      sim_grid_pos_y: 894462.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2971902
      sim_grid_pos_y: 894262.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2972166
      sim_grid_pos_y: 894387.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2972195.25
      sim_grid_pos_y: 894379.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2972073
      sim_grid_pos_y: 894577.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2971813.5
      sim_grid_pos_y: 894474.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2971889.5
      sim_grid_pos_y: 894233.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2972224.75
      sim_grid_pos_y: 894370.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2972081.5
      sim_grid_pos_y: 894602.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2971788
      sim_grid_pos_y: 894486.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2971877
      sim_grid_pos_y: 894205
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2972254.25
      sim_grid_pos_y: 894361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2972089.75
      sim_grid_pos_y: 894628.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2971762.75
      sim_grid_pos_y: 894498.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2971864.5
      sim_grid_pos_y: 894176.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2972283.75
      sim_grid_pos_y: 894353.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2972098.25
      sim_grid_pos_y: 894653.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2971737.5
      sim_grid_pos_y: 894510.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2971852
      sim_grid_pos_y: 894147.75
    }
  }
}
