terrain_level_data {
  terrain_level: 104
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 868427.562
      sim_grid_pos_y: 1563281.25
    }
    terrain_level_point {
      sim_grid_pos_x: 868290.688
      sim_grid_pos_y: 1563847
    }
    terrain_level_point {
      sim_grid_pos_x: 868555.688
      sim_grid_pos_y: 1563978.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868761.25
      sim_grid_pos_y: 1564074.88
    }
    terrain_level_point {
      sim_grid_pos_x: 869051.312
      sim_grid_pos_y: 1564311.5
    }
    terrain_level_point {
      sim_grid_pos_x: 869743.312
      sim_grid_pos_y: 1564493
    }
    terrain_level_point {
      sim_grid_pos_x: 871026.375
      sim_grid_pos_y: 1565536
    }
    terrain_level_point {
      sim_grid_pos_x: 871107.812
      sim_grid_pos_y: 1565918.25
    }
    terrain_level_point {
      sim_grid_pos_x: 870911.875
      sim_grid_pos_y: 1566325
    }
    terrain_level_point {
      sim_grid_pos_x: 870587.812
      sim_grid_pos_y: 1566517.75
    }
    terrain_level_point {
      sim_grid_pos_x: 870203.5
      sim_grid_pos_y: 1566579
    }
    terrain_level_point {
      sim_grid_pos_x: 870174.938
      sim_grid_pos_y: 1567015.25
    }
    terrain_level_point {
      sim_grid_pos_x: 869671.75
      sim_grid_pos_y: 1567763.38
    }
    terrain_level_point {
      sim_grid_pos_x: 869244.812
      sim_grid_pos_y: 1567805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 869171.688
      sim_grid_pos_y: 1.5679e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 868634.688
      sim_grid_pos_y: 1568070.38
    }
    terrain_level_point {
      sim_grid_pos_x: 868389.625
      sim_grid_pos_y: 1568007.38
    }
    terrain_level_point {
      sim_grid_pos_x: 867710.688
      sim_grid_pos_y: 1568292.75
    }
    terrain_level_point {
      sim_grid_pos_x: 867501.312
      sim_grid_pos_y: 1568253.5
    }
    terrain_level_point {
      sim_grid_pos_x: 867148.438
      sim_grid_pos_y: 1568042.75
    }
    terrain_level_point {
      sim_grid_pos_x: 866887.438
      sim_grid_pos_y: 1568151.75
    }
    terrain_level_point {
      sim_grid_pos_x: 866522
      sim_grid_pos_y: 1567612.12
    }
    terrain_level_point {
      sim_grid_pos_x: 867017.125
      sim_grid_pos_y: 1565779.12
    }
    terrain_level_point {
      sim_grid_pos_x: 866769.188
      sim_grid_pos_y: 1565594.12
    }
    terrain_level_point {
      sim_grid_pos_x: 866628.312
      sim_grid_pos_y: 1565448.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866837.812
      sim_grid_pos_y: 1564407.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866727.875
      sim_grid_pos_y: 1564283.12
    }
    terrain_level_point {
      sim_grid_pos_x: 865833.438
      sim_grid_pos_y: 1564088
    }
    terrain_level_point {
      sim_grid_pos_x: 865274.188
      sim_grid_pos_y: 1564377.75
    }
    terrain_level_point {
      sim_grid_pos_x: 865256.188
      sim_grid_pos_y: 1.56383e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 864794.875
      sim_grid_pos_y: 1563535.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864216.062
      sim_grid_pos_y: 1563028.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864148.938
      sim_grid_pos_y: 1562810.88
    }
    terrain_level_point {
      sim_grid_pos_x: 864785.938
      sim_grid_pos_y: 1562782.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864496.625
      sim_grid_pos_y: 1561811.88
    }
    terrain_level_point {
      sim_grid_pos_x: 864411.688
      sim_grid_pos_y: 1561589
    }
    terrain_level_point {
      sim_grid_pos_x: 864302.938
      sim_grid_pos_y: 1561416.38
    }
    terrain_level_point {
      sim_grid_pos_x: 864221.375
      sim_grid_pos_y: 1561022.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864184.562
      sim_grid_pos_y: 1560800.25
    }
    terrain_level_point {
      sim_grid_pos_x: 864409.125
      sim_grid_pos_y: 1560753.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864635.812
      sim_grid_pos_y: 1560646.38
    }
    terrain_level_point {
      sim_grid_pos_x: 865122
      sim_grid_pos_y: 1560955.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865357.562
      sim_grid_pos_y: 1560679.12
    }
    terrain_level_point {
      sim_grid_pos_x: 865525.875
      sim_grid_pos_y: 1560700.62
    }
    terrain_level_point {
      sim_grid_pos_x: 865628.188
      sim_grid_pos_y: 1560916.75
    }
    terrain_level_point {
      sim_grid_pos_x: 865679.312
      sim_grid_pos_y: 1561024.75
    }
    terrain_level_point {
      sim_grid_pos_x: 865754.25
      sim_grid_pos_y: 1561086.62
    }
    terrain_level_point {
      sim_grid_pos_x: 865777.312
      sim_grid_pos_y: 1561368.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866237.438
      sim_grid_pos_y: 1561074.12
    }
    terrain_level_point {
      sim_grid_pos_x: 867343.812
      sim_grid_pos_y: 1563065.38
    }
    terrain_level_point {
      sim_grid_pos_x: 867506.25
      sim_grid_pos_y: 1563011.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867625.125
      sim_grid_pos_y: 1563067.12
    }
    terrain_level_point {
      sim_grid_pos_x: 867856.188
      sim_grid_pos_y: 1.56297e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 868013.312
      sim_grid_pos_y: 1562978.62
    }
    terrain_level_point {
      sim_grid_pos_x: 868393.25
      sim_grid_pos_y: 1563157.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 865115.938
      sim_grid_pos_y: 1560915.62
    }
    terrain_level_point {
      sim_grid_pos_x: 865344.875
      sim_grid_pos_y: 1560646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 865546.5
      sim_grid_pos_y: 1560672.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865656
      sim_grid_pos_y: 1560903.5
    }
    terrain_level_point {
      sim_grid_pos_x: 865704.188
      sim_grid_pos_y: 1561005.38
    }
    terrain_level_point {
      sim_grid_pos_x: 865783.875
      sim_grid_pos_y: 1561071.12
    }
    terrain_level_point {
      sim_grid_pos_x: 865803.812
      sim_grid_pos_y: 1561314.88
    }
    terrain_level_point {
      sim_grid_pos_x: 866248.438
      sim_grid_pos_y: 1561030.5
    }
    terrain_level_point {
      sim_grid_pos_x: 867358.312
      sim_grid_pos_y: 1563028.12
    }
    terrain_level_point {
      sim_grid_pos_x: 867508.188
      sim_grid_pos_y: 1562978.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867625.75
      sim_grid_pos_y: 1563033.5
    }
    terrain_level_point {
      sim_grid_pos_x: 867850.812
      sim_grid_pos_y: 1562938.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868020.938
      sim_grid_pos_y: 1562948.25
    }
    terrain_level_point {
      sim_grid_pos_x: 868419.125
      sim_grid_pos_y: 1563135.5
    }
    terrain_level_point {
      sim_grid_pos_x: 868459.375
      sim_grid_pos_y: 1563280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 868326.312
      sim_grid_pos_y: 1563830.38
    }
    terrain_level_point {
      sim_grid_pos_x: 868568.938
      sim_grid_pos_y: 1563951.12
    }
    terrain_level_point {
      sim_grid_pos_x: 868777.75
      sim_grid_pos_y: 1564048.62
    }
    terrain_level_point {
      sim_grid_pos_x: 869065.625
      sim_grid_pos_y: 1564283.38
    }
    terrain_level_point {
      sim_grid_pos_x: 869757.562
      sim_grid_pos_y: 1564465
    }
    terrain_level_point {
      sim_grid_pos_x: 871054.188
      sim_grid_pos_y: 1565519
    }
    terrain_level_point {
      sim_grid_pos_x: 871140.125
      sim_grid_pos_y: 1565922.12
    }
    terrain_level_point {
      sim_grid_pos_x: 870935.625
      sim_grid_pos_y: 1566346.62
    }
    terrain_level_point {
      sim_grid_pos_x: 870598.438
      sim_grid_pos_y: 1566547.25
    }
    terrain_level_point {
      sim_grid_pos_x: 870232.625
      sim_grid_pos_y: 1566605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 870205.125
      sim_grid_pos_y: 1567025.5
    }
    terrain_level_point {
      sim_grid_pos_x: 869689.188
      sim_grid_pos_y: 1567792.5
    }
    terrain_level_point {
      sim_grid_pos_x: 869261
      sim_grid_pos_y: 1567835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 869190.125
      sim_grid_pos_y: 1567926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 868635.562
      sim_grid_pos_y: 1568102.38
    }
    terrain_level_point {
      sim_grid_pos_x: 868392
      sim_grid_pos_y: 1568039.75
    }
    terrain_level_point {
      sim_grid_pos_x: 867714.125
      sim_grid_pos_y: 1568324.62
    }
    terrain_level_point {
      sim_grid_pos_x: 867490.25
      sim_grid_pos_y: 1568282.75
    }
    terrain_level_point {
      sim_grid_pos_x: 867146
      sim_grid_pos_y: 1568077
    }
    terrain_level_point {
      sim_grid_pos_x: 866876.062
      sim_grid_pos_y: 1568189.75
    }
    terrain_level_point {
      sim_grid_pos_x: 866488.625
      sim_grid_pos_y: 1567617.75
    }
    terrain_level_point {
      sim_grid_pos_x: 866982
      sim_grid_pos_y: 1565791.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866748.812
      sim_grid_pos_y: 1565617.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866595
      sim_grid_pos_y: 1565458.12
    }
    terrain_level_point {
      sim_grid_pos_x: 866804.625
      sim_grid_pos_y: 1564416.25
    }
    terrain_level_point {
      sim_grid_pos_x: 866711.5
      sim_grid_pos_y: 1564311
    }
    terrain_level_point {
      sim_grid_pos_x: 865837.688
      sim_grid_pos_y: 1564120.5
    }
    terrain_level_point {
      sim_grid_pos_x: 865245.062
      sim_grid_pos_y: 1564427.5
    }
    terrain_level_point {
      sim_grid_pos_x: 865226
      sim_grid_pos_y: 1563847.25
    }
    terrain_level_point {
      sim_grid_pos_x: 864776.375
      sim_grid_pos_y: 1563559.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864189.25
      sim_grid_pos_y: 1563046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 864107.812
      sim_grid_pos_y: 1562781.88
    }
    terrain_level_point {
      sim_grid_pos_x: 864745.188
      sim_grid_pos_y: 1562753.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864467.5
      sim_grid_pos_y: 1561821.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864384
      sim_grid_pos_y: 1561602.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864273.938
      sim_grid_pos_y: 1561428.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864191.188
      sim_grid_pos_y: 1561027.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864149.375
      sim_grid_pos_y: 1560776.25
    }
    terrain_level_point {
      sim_grid_pos_x: 864399.312
      sim_grid_pos_y: 1560723.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864638.062
      sim_grid_pos_y: 1560611.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 865109.875
      sim_grid_pos_y: 1560875.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865332.25
      sim_grid_pos_y: 1560613.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865567.125
      sim_grid_pos_y: 1560643.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865683.75
      sim_grid_pos_y: 1560890.38
    }
    terrain_level_point {
      sim_grid_pos_x: 865729.062
      sim_grid_pos_y: 1560986
    }
    terrain_level_point {
      sim_grid_pos_x: 865813.438
      sim_grid_pos_y: 1561055.75
    }
    terrain_level_point {
      sim_grid_pos_x: 865830.312
      sim_grid_pos_y: 1561261.5
    }
    terrain_level_point {
      sim_grid_pos_x: 866259.438
      sim_grid_pos_y: 1560987
    }
    terrain_level_point {
      sim_grid_pos_x: 867372.875
      sim_grid_pos_y: 1562991
    }
    terrain_level_point {
      sim_grid_pos_x: 867510.125
      sim_grid_pos_y: 1562945.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867626.375
      sim_grid_pos_y: 1562999.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867845.438
      sim_grid_pos_y: 1562907.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868028.625
      sim_grid_pos_y: 1562917.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868445
      sim_grid_pos_y: 1563113.62
    }
    terrain_level_point {
      sim_grid_pos_x: 868491.125
      sim_grid_pos_y: 1563280.12
    }
    terrain_level_point {
      sim_grid_pos_x: 868362
      sim_grid_pos_y: 1563813.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868582.438
      sim_grid_pos_y: 1563923.5
    }
    terrain_level_point {
      sim_grid_pos_x: 868794.188
      sim_grid_pos_y: 1564022.38
    }
    terrain_level_point {
      sim_grid_pos_x: 869079.875
      sim_grid_pos_y: 1564255.38
    }
    terrain_level_point {
      sim_grid_pos_x: 869771.812
      sim_grid_pos_y: 1564436.88
    }
    terrain_level_point {
      sim_grid_pos_x: 871082
      sim_grid_pos_y: 1565502
    }
    terrain_level_point {
      sim_grid_pos_x: 871172.375
      sim_grid_pos_y: 1565926
    }
    terrain_level_point {
      sim_grid_pos_x: 870959.312
      sim_grid_pos_y: 1566368.38
    }
    terrain_level_point {
      sim_grid_pos_x: 870609.125
      sim_grid_pos_y: 1566576.62
    }
    terrain_level_point {
      sim_grid_pos_x: 870261.688
      sim_grid_pos_y: 1566632
    }
    terrain_level_point {
      sim_grid_pos_x: 870235.25
      sim_grid_pos_y: 1567035.75
    }
    terrain_level_point {
      sim_grid_pos_x: 869706.625
      sim_grid_pos_y: 1567821.75
    }
    terrain_level_point {
      sim_grid_pos_x: 869277.188
      sim_grid_pos_y: 1567864.5
    }
    terrain_level_point {
      sim_grid_pos_x: 869208.5
      sim_grid_pos_y: 1567952.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868636.438
      sim_grid_pos_y: 1568134.38
    }
    terrain_level_point {
      sim_grid_pos_x: 868394.375
      sim_grid_pos_y: 1568072.12
    }
    terrain_level_point {
      sim_grid_pos_x: 867717.562
      sim_grid_pos_y: 1568356.5
    }
    terrain_level_point {
      sim_grid_pos_x: 867479.188
      sim_grid_pos_y: 1568311.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867143.562
      sim_grid_pos_y: 1568111.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866864.688
      sim_grid_pos_y: 1568227.88
    }
    terrain_level_point {
      sim_grid_pos_x: 866455.25
      sim_grid_pos_y: 1567623.38
    }
    terrain_level_point {
      sim_grid_pos_x: 866946.875
      sim_grid_pos_y: 1565803.5
    }
    terrain_level_point {
      sim_grid_pos_x: 866728.375
      sim_grid_pos_y: 1565640.5
    }
    terrain_level_point {
      sim_grid_pos_x: 866561.625
      sim_grid_pos_y: 1565467.88
    }
    terrain_level_point {
      sim_grid_pos_x: 866771.438
      sim_grid_pos_y: 1564425.12
    }
    terrain_level_point {
      sim_grid_pos_x: 866695.188
      sim_grid_pos_y: 1564338.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865842
      sim_grid_pos_y: 1564152.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865215.938
      sim_grid_pos_y: 1564477.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865195.75
      sim_grid_pos_y: 1563864.38
    }
    terrain_level_point {
      sim_grid_pos_x: 864757.875
      sim_grid_pos_y: 1563584.5
    }
    terrain_level_point {
      sim_grid_pos_x: 864162.438
      sim_grid_pos_y: 1563063.62
    }
    terrain_level_point {
      sim_grid_pos_x: 864066.688
      sim_grid_pos_y: 1562752.88
    }
    terrain_level_point {
      sim_grid_pos_x: 864704.5
      sim_grid_pos_y: 1562724.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864438.375
      sim_grid_pos_y: 1561831.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864356.375
      sim_grid_pos_y: 1561616.62
    }
    terrain_level_point {
      sim_grid_pos_x: 864244.938
      sim_grid_pos_y: 1561439.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864160.938
      sim_grid_pos_y: 1561033.38
    }
    terrain_level_point {
      sim_grid_pos_x: 864114.188
      sim_grid_pos_y: 1560752.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864389.438
      sim_grid_pos_y: 1560694.38
    }
    terrain_level_point {
      sim_grid_pos_x: 864640.312
      sim_grid_pos_y: 1560576.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 865103.812
      sim_grid_pos_y: 1560834.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865319.625
      sim_grid_pos_y: 1560581.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865587.688
      sim_grid_pos_y: 1560615.5
    }
    terrain_level_point {
      sim_grid_pos_x: 865711.562
      sim_grid_pos_y: 1560877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865753.938
      sim_grid_pos_y: 1560966.62
    }
    terrain_level_point {
      sim_grid_pos_x: 865843.062
      sim_grid_pos_y: 1561040.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865856.812
      sim_grid_pos_y: 1561208
    }
    terrain_level_point {
      sim_grid_pos_x: 866270.438
      sim_grid_pos_y: 1560943.38
    }
    terrain_level_point {
      sim_grid_pos_x: 867387.438
      sim_grid_pos_y: 1562953.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867512.062
      sim_grid_pos_y: 1562912.88
    }
    terrain_level_point {
      sim_grid_pos_x: 867627
      sim_grid_pos_y: 1562966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 867840.062
      sim_grid_pos_y: 1562876.75
    }
    terrain_level_point {
      sim_grid_pos_x: 868036.312
      sim_grid_pos_y: 1562887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 868470.875
      sim_grid_pos_y: 1563091.88
    }
    terrain_level_point {
      sim_grid_pos_x: 868522.875
      sim_grid_pos_y: 1563279.62
    }
    terrain_level_point {
      sim_grid_pos_x: 868397.688
      sim_grid_pos_y: 1563797.25
    }
    terrain_level_point {
      sim_grid_pos_x: 868595.562
      sim_grid_pos_y: 1563895.62
    }
    terrain_level_point {
      sim_grid_pos_x: 868810.688
      sim_grid_pos_y: 1563996.12
    }
    terrain_level_point {
      sim_grid_pos_x: 869094.125
      sim_grid_pos_y: 1564227.25
    }
    terrain_level_point {
      sim_grid_pos_x: 869786
      sim_grid_pos_y: 1564408.88
    }
    terrain_level_point {
      sim_grid_pos_x: 871109.875
      sim_grid_pos_y: 1565485
    }
    terrain_level_point {
      sim_grid_pos_x: 871204.625
      sim_grid_pos_y: 1565929.88
    }
    terrain_level_point {
      sim_grid_pos_x: 870983
      sim_grid_pos_y: 1.56639e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 870619.812
      sim_grid_pos_y: 1566606.12
    }
    terrain_level_point {
      sim_grid_pos_x: 870290.75
      sim_grid_pos_y: 1566658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 870265.375
      sim_grid_pos_y: 1567046.12
    }
    terrain_level_point {
      sim_grid_pos_x: 869724.062
      sim_grid_pos_y: 1567850.88
    }
    terrain_level_point {
      sim_grid_pos_x: 869293.375
      sim_grid_pos_y: 1567893.75
    }
    terrain_level_point {
      sim_grid_pos_x: 869226.938
      sim_grid_pos_y: 1567979.38
    }
    terrain_level_point {
      sim_grid_pos_x: 868637.375
      sim_grid_pos_y: 1568166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 868396.75
      sim_grid_pos_y: 1568104.5
    }
    terrain_level_point {
      sim_grid_pos_x: 867720.938
      sim_grid_pos_y: 1568388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 867468.125
      sim_grid_pos_y: 1568341.12
    }
    terrain_level_point {
      sim_grid_pos_x: 867141.062
      sim_grid_pos_y: 1568145.75
    }
    terrain_level_point {
      sim_grid_pos_x: 866853.375
      sim_grid_pos_y: 1568266
    }
    terrain_level_point {
      sim_grid_pos_x: 866421.875
      sim_grid_pos_y: 1567628.88
    }
    terrain_level_point {
      sim_grid_pos_x: 866911.688
      sim_grid_pos_y: 1565815.62
    }
    terrain_level_point {
      sim_grid_pos_x: 866708
      sim_grid_pos_y: 1565663.62
    }
    terrain_level_point {
      sim_grid_pos_x: 866528.312
      sim_grid_pos_y: 1565477.62
    }
    terrain_level_point {
      sim_grid_pos_x: 866738.312
      sim_grid_pos_y: 1564434.12
    }
    terrain_level_point {
      sim_grid_pos_x: 866678.75
      sim_grid_pos_y: 1564366.88
    }
    terrain_level_point {
      sim_grid_pos_x: 865846.312
      sim_grid_pos_y: 1564185.25
    }
    terrain_level_point {
      sim_grid_pos_x: 865186.812
      sim_grid_pos_y: 1564527
    }
    terrain_level_point {
      sim_grid_pos_x: 865165.562
      sim_grid_pos_y: 1563881.62
    }
    terrain_level_point {
      sim_grid_pos_x: 864739.312
      sim_grid_pos_y: 1563609.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864135.625
      sim_grid_pos_y: 1563081
    }
    terrain_level_point {
      sim_grid_pos_x: 864025.562
      sim_grid_pos_y: 1562723.88
    }
    terrain_level_point {
      sim_grid_pos_x: 864663.75
      sim_grid_pos_y: 1562695.75
    }
    terrain_level_point {
      sim_grid_pos_x: 864409.25
      sim_grid_pos_y: 1561841.62
    }
    terrain_level_point {
      sim_grid_pos_x: 864328.688
      sim_grid_pos_y: 1561630.38
    }
    terrain_level_point {
      sim_grid_pos_x: 864215.938
      sim_grid_pos_y: 1561451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 864130.688
      sim_grid_pos_y: 1561039
    }
    terrain_level_point {
      sim_grid_pos_x: 864079
      sim_grid_pos_y: 1560728.12
    }
    terrain_level_point {
      sim_grid_pos_x: 864379.625
      sim_grid_pos_y: 1560665
    }
    terrain_level_point {
      sim_grid_pos_x: 864642.5
      sim_grid_pos_y: 1560541.25
    }
  }
}
