terrain_level_data {
  terrain_level: 670
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1877662.62
      sim_grid_pos_y: 29907.1172
    }
    terrain_level_point {
      sim_grid_pos_x: 1877647
      sim_grid_pos_y: 30020.8984
    }
    terrain_level_point {
      sim_grid_pos_x: 1877723
      sim_grid_pos_y: 30116.9492
    }
    terrain_level_point {
      sim_grid_pos_x: 1877912.5
      sim_grid_pos_y: 30191.6094
    }
    terrain_level_point {
      sim_grid_pos_x: 1878076.25
      sim_grid_pos_y: 30089.3555
    }
    terrain_level_point {
      sim_grid_pos_x: 1878009.12
      sim_grid_pos_y: 29944.623
    }
    terrain_level_point {
      sim_grid_pos_x: 1877855.38
      sim_grid_pos_y: 29825.1191
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1.87786e+06
      sim_grid_pos_y: 29789.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 1877634.5
      sim_grid_pos_y: 29885.6445
    }
    terrain_level_point {
      sim_grid_pos_x: 1877614.75
      sim_grid_pos_y: 30029.7031
    }
    terrain_level_point {
      sim_grid_pos_x: 1877704
      sim_grid_pos_y: 30142.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 1877915.75
      sim_grid_pos_y: 30225.9043
    }
    terrain_level_point {
      sim_grid_pos_x: 1878115.62
      sim_grid_pos_y: 30101.0547
    }
    terrain_level_point {
      sim_grid_pos_x: 1878033.88
      sim_grid_pos_y: 29924.9141
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1877864.62
      sim_grid_pos_y: 29754.3535
    }
    terrain_level_point {
      sim_grid_pos_x: 1877606.38
      sim_grid_pos_y: 29864.1738
    }
    terrain_level_point {
      sim_grid_pos_x: 1877582.5
      sim_grid_pos_y: 30038.5039
    }
    terrain_level_point {
      sim_grid_pos_x: 1877685
      sim_grid_pos_y: 30168.1035
    }
    terrain_level_point {
      sim_grid_pos_x: 1877918.88
      sim_grid_pos_y: 30260.1934
    }
    terrain_level_point {
      sim_grid_pos_x: 1878155
      sim_grid_pos_y: 30112.7539
    }
    terrain_level_point {
      sim_grid_pos_x: 1878058.62
      sim_grid_pos_y: 29905.2031
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1877869.25
      sim_grid_pos_y: 29718.9648
    }
    terrain_level_point {
      sim_grid_pos_x: 1877578.38
      sim_grid_pos_y: 29842.6934
    }
    terrain_level_point {
      sim_grid_pos_x: 1877550.25
      sim_grid_pos_y: 30047.3047
    }
    terrain_level_point {
      sim_grid_pos_x: 1877666
      sim_grid_pos_y: 30193.6836
    }
    terrain_level_point {
      sim_grid_pos_x: 1877922
      sim_grid_pos_y: 30294.4941
    }
    terrain_level_point {
      sim_grid_pos_x: 1878194.38
      sim_grid_pos_y: 30124.4434
    }
    terrain_level_point {
      sim_grid_pos_x: 1878083.38
      sim_grid_pos_y: 29885.4941
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1877873.75
      sim_grid_pos_y: 29683.584
    }
    terrain_level_point {
      sim_grid_pos_x: 1877550.25
      sim_grid_pos_y: 29821.2246
    }
    terrain_level_point {
      sim_grid_pos_x: 1877518
      sim_grid_pos_y: 30056.1035
    }
    terrain_level_point {
      sim_grid_pos_x: 1877647
      sim_grid_pos_y: 30219.2637
    }
    terrain_level_point {
      sim_grid_pos_x: 1877925.12
      sim_grid_pos_y: 30328.7949
    }
    terrain_level_point {
      sim_grid_pos_x: 1878233.62
      sim_grid_pos_y: 30136.1445
    }
    terrain_level_point {
      sim_grid_pos_x: 1878108.12
      sim_grid_pos_y: 29865.7832
    }
  }
}
