terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 578722.812
      sim_grid_pos_y: 2234172.75
    }
    terrain_level_point {
      sim_grid_pos_x: 581766.375
      sim_grid_pos_y: 2237493.75
    }
    terrain_level_point {
      sim_grid_pos_x: 581729.688
      sim_grid_pos_y: 2237669.5
    }
    terrain_level_point {
      sim_grid_pos_x: 582754.312
      sim_grid_pos_y: 2238812.5
    }
    terrain_level_point {
      sim_grid_pos_x: 582314.062
      sim_grid_pos_y: 2239517.75
    }
    terrain_level_point {
      sim_grid_pos_x: 581670.5
      sim_grid_pos_y: 2240313.25
    }
    terrain_level_point {
      sim_grid_pos_x: 579126.438
      sim_grid_pos_y: 2238722.75
    }
    terrain_level_point {
      sim_grid_pos_x: 579645.625
      sim_grid_pos_y: 2237394.5
    }
    terrain_level_point {
      sim_grid_pos_x: 577828.938
      sim_grid_pos_y: 2236689.75
    }
    terrain_level_point {
      sim_grid_pos_x: 577490.812
      sim_grid_pos_y: 2236348.25
    }
    terrain_level_point {
      sim_grid_pos_x: 578494.312
      sim_grid_pos_y: 2234026.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 578742.75
      sim_grid_pos_y: 2234149
    }
    terrain_level_point {
      sim_grid_pos_x: 581799.688
      sim_grid_pos_y: 2237484.5
    }
    terrain_level_point {
      sim_grid_pos_x: 581763
      sim_grid_pos_y: 2237660.75
    }
    terrain_level_point {
      sim_grid_pos_x: 582792.688
      sim_grid_pos_y: 2238809
    }
    terrain_level_point {
      sim_grid_pos_x: 582339.188
      sim_grid_pos_y: 2239535.5
    }
    terrain_level_point {
      sim_grid_pos_x: 581677.312
      sim_grid_pos_y: 2240353.75
    }
    terrain_level_point {
      sim_grid_pos_x: 579088.5
      sim_grid_pos_y: 2238735.25
    }
    terrain_level_point {
      sim_grid_pos_x: 579605.75
      sim_grid_pos_y: 2237412
    }
    terrain_level_point {
      sim_grid_pos_x: 577811.688
      sim_grid_pos_y: 2236716.25
    }
    terrain_level_point {
      sim_grid_pos_x: 577454.312
      sim_grid_pos_y: 2236355.25
    }
    terrain_level_point {
      sim_grid_pos_x: 578480.438
      sim_grid_pos_y: 2233981.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 578762.75
      sim_grid_pos_y: 2234125.25
    }
    terrain_level_point {
      sim_grid_pos_x: 581833
      sim_grid_pos_y: 2237475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 581796.25
      sim_grid_pos_y: 2237651.75
    }
    terrain_level_point {
      sim_grid_pos_x: 582831
      sim_grid_pos_y: 2238805.75
    }
    terrain_level_point {
      sim_grid_pos_x: 582364.25
      sim_grid_pos_y: 2239553.5
    }
    terrain_level_point {
      sim_grid_pos_x: 581684.062
      sim_grid_pos_y: 2240394.25
    }
    terrain_level_point {
      sim_grid_pos_x: 579050.562
      sim_grid_pos_y: 2238747.75
    }
    terrain_level_point {
      sim_grid_pos_x: 579565.875
      sim_grid_pos_y: 2237429.5
    }
    terrain_level_point {
      sim_grid_pos_x: 577794.438
      sim_grid_pos_y: 2236742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 577417.875
      sim_grid_pos_y: 2236362
    }
    terrain_level_point {
      sim_grid_pos_x: 578466.562
      sim_grid_pos_y: 2233935.75
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 574438.875
      sim_grid_pos_y: 2236363.5
    }
    terrain_level_point {
      sim_grid_pos_x: 570416.188
      sim_grid_pos_y: 2234824.25
    }
    terrain_level_point {
      sim_grid_pos_x: 569607.25
      sim_grid_pos_y: 2235068.25
    }
    terrain_level_point {
      sim_grid_pos_x: 568746.625
      sim_grid_pos_y: 2236177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 568163.688
      sim_grid_pos_y: 2236059
    }
    terrain_level_point {
      sim_grid_pos_x: 568143.25
      sim_grid_pos_y: 2237043
    }
    terrain_level_point {
      sim_grid_pos_x: 569557.812
      sim_grid_pos_y: 2236975.25
    }
    terrain_level_point {
      sim_grid_pos_x: 570178.562
      sim_grid_pos_y: 2235494.25
    }
    terrain_level_point {
      sim_grid_pos_x: 572759.25
      sim_grid_pos_y: 2236591.25
    }
    terrain_level_point {
      sim_grid_pos_x: 573320.875
      sim_grid_pos_y: 2237206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573998.875
      sim_grid_pos_y: 2237500.25
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 557400.75
      sim_grid_pos_y: 2234635.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556310.312
      sim_grid_pos_y: 2233518
    }
    terrain_level_point {
      sim_grid_pos_x: 556401.562
      sim_grid_pos_y: 2232902.5
    }
    terrain_level_point {
      sim_grid_pos_x: 557375.5
      sim_grid_pos_y: 2231593.5
    }
    terrain_level_point {
      sim_grid_pos_x: 557038.562
      sim_grid_pos_y: 2231150.5
    }
    terrain_level_point {
      sim_grid_pos_x: 558448.125
      sim_grid_pos_y: 2229896.5
    }
    terrain_level_point {
      sim_grid_pos_x: 559477.5
      sim_grid_pos_y: 2230938.5
    }
    terrain_level_point {
      sim_grid_pos_x: 560422.812
      sim_grid_pos_y: 2231294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 563058
      sim_grid_pos_y: 2231198.25
    }
    terrain_level_point {
      sim_grid_pos_x: 563179.625
      sim_grid_pos_y: 2234875.25
    }
    terrain_level_point {
      sim_grid_pos_x: 562223.25
      sim_grid_pos_y: 2234879.25
    }
    terrain_level_point {
      sim_grid_pos_x: 562093.438
      sim_grid_pos_y: 2234520.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 559494.625
      sim_grid_pos_y: 2230912.25
    }
    terrain_level_point {
      sim_grid_pos_x: 560427.875
      sim_grid_pos_y: 2231263.5
    }
    terrain_level_point {
      sim_grid_pos_x: 563087.688
      sim_grid_pos_y: 2231166.5
    }
    terrain_level_point {
      sim_grid_pos_x: 563211.375
      sim_grid_pos_y: 2234905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 562201.688
      sim_grid_pos_y: 2234910.25
    }
    terrain_level_point {
      sim_grid_pos_x: 562072.062
      sim_grid_pos_y: 2234552
    }
    terrain_level_point {
      sim_grid_pos_x: 557388.125
      sim_grid_pos_y: 2234666.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556277.625
      sim_grid_pos_y: 2233528.5
    }
    terrain_level_point {
      sim_grid_pos_x: 556372.25
      sim_grid_pos_y: 2232890.5
    }
    terrain_level_point {
      sim_grid_pos_x: 557337
      sim_grid_pos_y: 2231593.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556996.875
      sim_grid_pos_y: 2231146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 558449.438
      sim_grid_pos_y: 2229854
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 559511.812
      sim_grid_pos_y: 2230885.75
    }
    terrain_level_point {
      sim_grid_pos_x: 560432.938
      sim_grid_pos_y: 2231232.5
    }
    terrain_level_point {
      sim_grid_pos_x: 563117.438
      sim_grid_pos_y: 2231134.5
    }
    terrain_level_point {
      sim_grid_pos_x: 563243.188
      sim_grid_pos_y: 2234936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 562180.125
      sim_grid_pos_y: 2234941
    }
    terrain_level_point {
      sim_grid_pos_x: 562050.688
      sim_grid_pos_y: 2234583.25
    }
    terrain_level_point {
      sim_grid_pos_x: 557375.438
      sim_grid_pos_y: 2234697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556245
      sim_grid_pos_y: 2233539
    }
    terrain_level_point {
      sim_grid_pos_x: 556343
      sim_grid_pos_y: 2232878.25
    }
    terrain_level_point {
      sim_grid_pos_x: 557298.5
      sim_grid_pos_y: 2231594
    }
    terrain_level_point {
      sim_grid_pos_x: 556955.125
      sim_grid_pos_y: 2231142.25
    }
    terrain_level_point {
      sim_grid_pos_x: 558450.812
      sim_grid_pos_y: 2229811.75
    }
  }
}
