terrain_level_data {
  terrain_level: 35
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 602450.625
      sim_grid_pos_y: 2235926.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604971.625
      sim_grid_pos_y: 2236847.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607710.812
      sim_grid_pos_y: 2234510.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606007.75
      sim_grid_pos_y: 2234454.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605982.5
      sim_grid_pos_y: 2233867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605468.375
      sim_grid_pos_y: 2233825.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605478.25
      sim_grid_pos_y: 2233330.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605307.188
      sim_grid_pos_y: 2233326.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605332.688
      sim_grid_pos_y: 2232646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605453.312
      sim_grid_pos_y: 2232468.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605436.875
      sim_grid_pos_y: 2232172.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605314.875
      sim_grid_pos_y: 2231904.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605046.625
      sim_grid_pos_y: 2231899.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603694.562
      sim_grid_pos_y: 2232182.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 605043.688
      sim_grid_pos_y: 2231868.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603670.938
      sim_grid_pos_y: 2232156.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602412
      sim_grid_pos_y: 2235945.25
    }
    terrain_level_point {
      sim_grid_pos_x: 604977.938
      sim_grid_pos_y: 2236882.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607746.812
      sim_grid_pos_y: 2234520.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607732.875
      sim_grid_pos_y: 2234480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606037.25
      sim_grid_pos_y: 2234425
    }
    terrain_level_point {
      sim_grid_pos_x: 606012.062
      sim_grid_pos_y: 2233839
    }
    terrain_level_point {
      sim_grid_pos_x: 605499.688
      sim_grid_pos_y: 2233797.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605509.625
      sim_grid_pos_y: 2233300.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605339.062
      sim_grid_pos_y: 2233296.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605363.125
      sim_grid_pos_y: 2232656.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605484.625
      sim_grid_pos_y: 2232476.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605467.25
      sim_grid_pos_y: 2232164.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605334.812
      sim_grid_pos_y: 2231874.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 605040.812
      sim_grid_pos_y: 2231837.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603647.312
      sim_grid_pos_y: 2232129.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602373.438
      sim_grid_pos_y: 2235964
    }
    terrain_level_point {
      sim_grid_pos_x: 604984.25
      sim_grid_pos_y: 2236917.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607782.812
      sim_grid_pos_y: 2234529.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607754.938
      sim_grid_pos_y: 2234450.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606066.75
      sim_grid_pos_y: 2234395.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606041.625
      sim_grid_pos_y: 2233810.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605531
      sim_grid_pos_y: 2233769
    }
    terrain_level_point {
      sim_grid_pos_x: 605541
      sim_grid_pos_y: 2233270.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605371
      sim_grid_pos_y: 2233266.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605393.5
      sim_grid_pos_y: 2232666.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605515.875
      sim_grid_pos_y: 2232485.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605497.625
      sim_grid_pos_y: 2232157.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605354.75
      sim_grid_pos_y: 2231843.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 605037.938
      sim_grid_pos_y: 2231807
    }
    terrain_level_point {
      sim_grid_pos_x: 603623.688
      sim_grid_pos_y: 2232103.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602334.812
      sim_grid_pos_y: 2235982.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604990.562
      sim_grid_pos_y: 2236952.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607818.812
      sim_grid_pos_y: 2234539.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607777
      sim_grid_pos_y: 2234420.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606096.25
      sim_grid_pos_y: 2234365.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606071.188
      sim_grid_pos_y: 2233782.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605562.375
      sim_grid_pos_y: 2233740.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605572.375
      sim_grid_pos_y: 2233240.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605402.875
      sim_grid_pos_y: 2233236.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605423.875
      sim_grid_pos_y: 2232676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605547.188
      sim_grid_pos_y: 2232494
    }
    terrain_level_point {
      sim_grid_pos_x: 605528.062
      sim_grid_pos_y: 2232149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605374.688
      sim_grid_pos_y: 2231813.5
    }
  }
}
