terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 54597.8867
      sim_grid_pos_y: 3082364
    }
    terrain_level_point {
      sim_grid_pos_x: 54829.8164
      sim_grid_pos_y: 3082751.25
    }
    terrain_level_point {
      sim_grid_pos_x: 56814.293
      sim_grid_pos_y: 3083730.5
    }
    terrain_level_point {
      sim_grid_pos_x: 57668.0703
      sim_grid_pos_y: 3083231.75
    }
    terrain_level_point {
      sim_grid_pos_x: 58441.7773
      sim_grid_pos_y: 3083202
    }
    terrain_level_point {
      sim_grid_pos_x: 58349.9023
      sim_grid_pos_y: 3081139.75
    }
    terrain_level_point {
      sim_grid_pos_x: 57131.9297
      sim_grid_pos_y: 3080951.5
    }
    terrain_level_point {
      sim_grid_pos_x: 56716.1484
      sim_grid_pos_y: 3081099.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 57128.9297
      sim_grid_pos_y: 3080919.75
    }
    terrain_level_point {
      sim_grid_pos_x: 56702.9805
      sim_grid_pos_y: 3081071.75
    }
    terrain_level_point {
      sim_grid_pos_x: 54555.6797
      sim_grid_pos_y: 3082353.25
    }
    terrain_level_point {
      sim_grid_pos_x: 54808.0898
      sim_grid_pos_y: 3082774.75
    }
    terrain_level_point {
      sim_grid_pos_x: 56815.5195
      sim_grid_pos_y: 3083765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 57676.9492
      sim_grid_pos_y: 3083262.25
    }
    terrain_level_point {
      sim_grid_pos_x: 58473.8789
      sim_grid_pos_y: 3083231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 58379.5117
      sim_grid_pos_y: 3081113
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 57125.9297
      sim_grid_pos_y: 3080888.25
    }
    terrain_level_point {
      sim_grid_pos_x: 56689.8
      sim_grid_pos_y: 3081043.75
    }
    terrain_level_point {
      sim_grid_pos_x: 54513.4609
      sim_grid_pos_y: 3082342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 54786.3516
      sim_grid_pos_y: 3082798.25
    }
    terrain_level_point {
      sim_grid_pos_x: 56816.7422
      sim_grid_pos_y: 3083800.25
    }
    terrain_level_point {
      sim_grid_pos_x: 57685.8203
      sim_grid_pos_y: 3083292.75
    }
    terrain_level_point {
      sim_grid_pos_x: 58505.9922
      sim_grid_pos_y: 3083261
    }
    terrain_level_point {
      sim_grid_pos_x: 58409.1094
      sim_grid_pos_y: 3081086.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 57122.9297
      sim_grid_pos_y: 3080856.75
    }
    terrain_level_point {
      sim_grid_pos_x: 56676.6289
      sim_grid_pos_y: 3081015.75
    }
    terrain_level_point {
      sim_grid_pos_x: 54471.25
      sim_grid_pos_y: 3082332
    }
    terrain_level_point {
      sim_grid_pos_x: 54764.6211
      sim_grid_pos_y: 3082822
    }
    terrain_level_point {
      sim_grid_pos_x: 56817.9727
      sim_grid_pos_y: 3083835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 57694.7
      sim_grid_pos_y: 3083323.25
    }
    terrain_level_point {
      sim_grid_pos_x: 58538.0898
      sim_grid_pos_y: 3083290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 58438.7227
      sim_grid_pos_y: 3.08106e+06
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 58285.0156
      sim_grid_pos_y: 3080562.75
    }
    terrain_level_point {
      sim_grid_pos_x: 57305.793
      sim_grid_pos_y: 3080403
    }
    terrain_level_point {
      sim_grid_pos_x: 57333.8906
      sim_grid_pos_y: 3080238.5
    }
    terrain_level_point {
      sim_grid_pos_x: 58434.5078
      sim_grid_pos_y: 3079107
    }
    terrain_level_point {
      sim_grid_pos_x: 58791.1406
      sim_grid_pos_y: 3078016.75
    }
    terrain_level_point {
      sim_grid_pos_x: 60089.6094
      sim_grid_pos_y: 3078272
    }
    terrain_level_point {
      sim_grid_pos_x: 59933.6523
      sim_grid_pos_y: 3079032.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 60125.9688
      sim_grid_pos_y: 3078247.75
    }
    terrain_level_point {
      sim_grid_pos_x: 59961.8
      sim_grid_pos_y: 3079048.25
    }
    terrain_level_point {
      sim_grid_pos_x: 58294.9219
      sim_grid_pos_y: 3080595.5
    }
    terrain_level_point {
      sim_grid_pos_x: 57270.2617
      sim_grid_pos_y: 3080428.5
    }
    terrain_level_point {
      sim_grid_pos_x: 57305.1797
      sim_grid_pos_y: 3080223.75
    }
    terrain_level_point {
      sim_grid_pos_x: 58407.5
      sim_grid_pos_y: 3079090.5
    }
    terrain_level_point {
      sim_grid_pos_x: 58770.3711
      sim_grid_pos_y: 3077981.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 60162.332
      sim_grid_pos_y: 3078223.5
    }
    terrain_level_point {
      sim_grid_pos_x: 59989.9492
      sim_grid_pos_y: 3079064
    }
    terrain_level_point {
      sim_grid_pos_x: 58304.8203
      sim_grid_pos_y: 3080628.25
    }
    terrain_level_point {
      sim_grid_pos_x: 57234.7227
      sim_grid_pos_y: 3080453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 57276.4727
      sim_grid_pos_y: 3080209.25
    }
    terrain_level_point {
      sim_grid_pos_x: 58380.4609
      sim_grid_pos_y: 3079074.25
    }
    terrain_level_point {
      sim_grid_pos_x: 58749.6
      sim_grid_pos_y: 3077945.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 60198.6914
      sim_grid_pos_y: 3078199.25
    }
    terrain_level_point {
      sim_grid_pos_x: 60018.1
      sim_grid_pos_y: 3079079.75
    }
    terrain_level_point {
      sim_grid_pos_x: 58314.7227
      sim_grid_pos_y: 3080661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 57199.1914
      sim_grid_pos_y: 3080479.25
    }
    terrain_level_point {
      sim_grid_pos_x: 57247.7617
      sim_grid_pos_y: 3080194.75
    }
    terrain_level_point {
      sim_grid_pos_x: 58353.4609
      sim_grid_pos_y: 3079057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 58728.8203
      sim_grid_pos_y: 3077910.5
    }
  }
}
