terrain_level_data {
  terrain_level: 249
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1316479.38
      sim_grid_pos_y: 1716349
    }
    terrain_level_point {
      sim_grid_pos_x: 1316690.62
      sim_grid_pos_y: 1716430.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1317274.88
      sim_grid_pos_y: 1716785.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1317766.25
      sim_grid_pos_y: 1717430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1318217.88
      sim_grid_pos_y: 1718307.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1317842.88
      sim_grid_pos_y: 1718389.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1317037.88
      sim_grid_pos_y: 1718192
    }
    terrain_level_point {
      sim_grid_pos_x: 1316932.75
      sim_grid_pos_y: 1718347.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1316803.5
      sim_grid_pos_y: 1.71827e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1316671.38
      sim_grid_pos_y: 1718335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1316446
      sim_grid_pos_y: 1718262.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1316350.75
      sim_grid_pos_y: 1718425.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1316443.62
      sim_grid_pos_y: 1718799.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1316271.38
      sim_grid_pos_y: 1718819
    }
    terrain_level_point {
      sim_grid_pos_x: 1316032.12
      sim_grid_pos_y: 1718625.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315841
      sim_grid_pos_y: 1718768.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315681.62
      sim_grid_pos_y: 1718755.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315606
      sim_grid_pos_y: 1718666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1315678.12
      sim_grid_pos_y: 1718485.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1315688.75
      sim_grid_pos_y: 1718361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315596.38
      sim_grid_pos_y: 1718293.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315491.12
      sim_grid_pos_y: 1718357.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315360.38
      sim_grid_pos_y: 1718514.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315300.75
      sim_grid_pos_y: 1718336.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315235.12
      sim_grid_pos_y: 1718340.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315083.88
      sim_grid_pos_y: 1718485
    }
    terrain_level_point {
      sim_grid_pos_x: 1314931.75
      sim_grid_pos_y: 1718738.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314243.38
      sim_grid_pos_y: 1718090.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1313624.62
      sim_grid_pos_y: 1717658.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1313379
      sim_grid_pos_y: 1717473.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1313866.12
      sim_grid_pos_y: 1717421.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1313892.88
      sim_grid_pos_y: 1717282.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1313792.88
      sim_grid_pos_y: 1717120.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1314290.38
      sim_grid_pos_y: 1716533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1314391.38
      sim_grid_pos_y: 1716528.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1314522.62
      sim_grid_pos_y: 1716598.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1314467.12
      sim_grid_pos_y: 1716877.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1314587.88
      sim_grid_pos_y: 1716932
    }
    terrain_level_point {
      sim_grid_pos_x: 1314616.5
      sim_grid_pos_y: 1716958.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314752.62
      sim_grid_pos_y: 1716930.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1314810.38
      sim_grid_pos_y: 1716827.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315134.38
      sim_grid_pos_y: 1716904.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315161.62
      sim_grid_pos_y: 1716990.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1315046.62
      sim_grid_pos_y: 1717093.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315094.5
      sim_grid_pos_y: 1717236.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315208.62
      sim_grid_pos_y: 1717266.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315513.62
      sim_grid_pos_y: 1.71704e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1315555.5
      sim_grid_pos_y: 1716790.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315993.38
      sim_grid_pos_y: 1716518.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1316183.12
      sim_grid_pos_y: 1716521.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1316740.62
      sim_grid_pos_y: 1716328.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1317351.62
      sim_grid_pos_y: 1716700.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1317862
      sim_grid_pos_y: 1717369.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1318385.38
      sim_grid_pos_y: 1718386.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1317841.38
      sim_grid_pos_y: 1718505
    }
    terrain_level_point {
      sim_grid_pos_x: 1317087.25
      sim_grid_pos_y: 1718320.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1316966.38
      sim_grid_pos_y: 1718498.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1316798.5
      sim_grid_pos_y: 1718398.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316680.38
      sim_grid_pos_y: 1718456.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316497.62
      sim_grid_pos_y: 1718397.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316471.25
      sim_grid_pos_y: 1718442.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316584
      sim_grid_pos_y: 1718896.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1316237.25
      sim_grid_pos_y: 1718936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1316029.5
      sim_grid_pos_y: 1718768.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315874.38
      sim_grid_pos_y: 1718884.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315625.75
      sim_grid_pos_y: 1718864.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315476.12
      sim_grid_pos_y: 1718687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315567.12
      sim_grid_pos_y: 1718459.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315568.62
      sim_grid_pos_y: 1718442
    }
    terrain_level_point {
      sim_grid_pos_x: 1315565.62
      sim_grid_pos_y: 1718443.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1315404.62
      sim_grid_pos_y: 1718637.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315274.5
      sim_grid_pos_y: 1718612.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315235.38
      sim_grid_pos_y: 1718496.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315172.75
      sim_grid_pos_y: 1718556.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1314956.38
      sim_grid_pos_y: 1718916.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1314172
      sim_grid_pos_y: 1718177.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1313558.5
      sim_grid_pos_y: 1717749.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1313249.88
      sim_grid_pos_y: 1717517.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1313290.62
      sim_grid_pos_y: 1717369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1313771.12
      sim_grid_pos_y: 1717317.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1313773.75
      sim_grid_pos_y: 1717304.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1313653.75
      sim_grid_pos_y: 1717110.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1314235.88
      sim_grid_pos_y: 1716423.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314416.62
      sim_grid_pos_y: 1716414.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1314649.62
      sim_grid_pos_y: 1716537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314595.25
      sim_grid_pos_y: 1716811.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314650.25
      sim_grid_pos_y: 1716836.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314679.5
      sim_grid_pos_y: 1716830.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314753.62
      sim_grid_pos_y: 1716698
    }
    terrain_level_point {
      sim_grid_pos_x: 1315222.5
      sim_grid_pos_y: 1716809.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315291.25
      sim_grid_pos_y: 1717025.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315177.12
      sim_grid_pos_y: 1717127.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1315182.12
      sim_grid_pos_y: 1717142.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315184.75
      sim_grid_pos_y: 1717143.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1315409.88
      sim_grid_pos_y: 1716976.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315452.75
      sim_grid_pos_y: 1716721.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315962
      sim_grid_pos_y: 1716405
    }
    terrain_level_point {
      sim_grid_pos_x: 1316153.5
      sim_grid_pos_y: 1716407.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316469.5
      sim_grid_pos_y: 1716224.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1316790.62
      sim_grid_pos_y: 1716227.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1317428.5
      sim_grid_pos_y: 1716615.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1317957.75
      sim_grid_pos_y: 1717309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1318552.88
      sim_grid_pos_y: 1718465.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1317839.88
      sim_grid_pos_y: 1718620.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1317136.62
      sim_grid_pos_y: 1718448.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.317e+06
      sim_grid_pos_y: 1718649.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316793.5
      sim_grid_pos_y: 1718526.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1316689.38
      sim_grid_pos_y: 1718578.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316615.25
      sim_grid_pos_y: 1718554.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316724.38
      sim_grid_pos_y: 1718993.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1316203.25
      sim_grid_pos_y: 1719053.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316026.88
      sim_grid_pos_y: 1718911.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1315907.75
      sim_grid_pos_y: 1719000.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.31557e+06
      sim_grid_pos_y: 1718972.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315378.75
      sim_grid_pos_y: 1718747.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315208.88
      sim_grid_pos_y: 1718715.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1314981
      sim_grid_pos_y: 1719094.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314100.75
      sim_grid_pos_y: 1718265.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1313492.25
      sim_grid_pos_y: 1717841
    }
    terrain_level_point {
      sim_grid_pos_x: 1313120.75
      sim_grid_pos_y: 1717561.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1313202.25
      sim_grid_pos_y: 1717265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1313591.5
      sim_grid_pos_y: 1717223.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1313514.75
      sim_grid_pos_y: 1717099.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1314181.38
      sim_grid_pos_y: 1716313.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1314441.88
      sim_grid_pos_y: 1716300.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1314776.62
      sim_grid_pos_y: 1716477.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1314755.62
      sim_grid_pos_y: 1716582.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315310.75
      sim_grid_pos_y: 1716714.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315329.5
      sim_grid_pos_y: 1716774
    }
    terrain_level_point {
      sim_grid_pos_x: 1315349.88
      sim_grid_pos_y: 1716652.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315930.5
      sim_grid_pos_y: 1716291.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1316124
      sim_grid_pos_y: 1716294.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1316459.62
      sim_grid_pos_y: 1716099.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1316840.62
      sim_grid_pos_y: 1716125.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1317505.25
      sim_grid_pos_y: 1716529.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1318053.38
      sim_grid_pos_y: 1717249
    }
    terrain_level_point {
      sim_grid_pos_x: 1318720.38
      sim_grid_pos_y: 1718544.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1317838.38
      sim_grid_pos_y: 1718736.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1317185.88
      sim_grid_pos_y: 1718576.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1317033.62
      sim_grid_pos_y: 1718801.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316788.5
      sim_grid_pos_y: 1718655
    }
    terrain_level_point {
      sim_grid_pos_x: 1.31676e+06
      sim_grid_pos_y: 1718669.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1316864.88
      sim_grid_pos_y: 1719091.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1316169.12
      sim_grid_pos_y: 1719171.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316024.25
      sim_grid_pos_y: 1719054.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315941.12
      sim_grid_pos_y: 1719116.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315514.12
      sim_grid_pos_y: 1719081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315318.62
      sim_grid_pos_y: 1718850.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315265.12
      sim_grid_pos_y: 1718840.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315005.62
      sim_grid_pos_y: 1719272.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1314029.38
      sim_grid_pos_y: 1718353.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1313426.12
      sim_grid_pos_y: 1717932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1312991.75
      sim_grid_pos_y: 1717605.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1313113.88
      sim_grid_pos_y: 1717161.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1313401.38
      sim_grid_pos_y: 1717130.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1313375.62
      sim_grid_pos_y: 1717089.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314126.88
      sim_grid_pos_y: 1716203.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1314467.12
      sim_grid_pos_y: 1716185.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1314903.62
      sim_grid_pos_y: 1716417
    }
    terrain_level_point {
      sim_grid_pos_x: 1314887.5
      sim_grid_pos_y: 1716498
    }
    terrain_level_point {
      sim_grid_pos_x: 1315247.25
      sim_grid_pos_y: 1716583.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315899.12
      sim_grid_pos_y: 1716178.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316094.38
      sim_grid_pos_y: 1716181.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316449.75
      sim_grid_pos_y: 1715974.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1316890.62
      sim_grid_pos_y: 1716024.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1317582
      sim_grid_pos_y: 1716444.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1318149.12
      sim_grid_pos_y: 1717188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1318887.88
      sim_grid_pos_y: 1718623.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1317836.88
      sim_grid_pos_y: 1718852.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1317235.25
      sim_grid_pos_y: 1718704.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1317067.25
      sim_grid_pos_y: 1718952.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1316925.62
      sim_grid_pos_y: 1718868.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1317005.25
      sim_grid_pos_y: 1719188.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1316135
      sim_grid_pos_y: 1719288.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1316021.5
      sim_grid_pos_y: 1719197.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315974.5
      sim_grid_pos_y: 1719232.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1315458.25
      sim_grid_pos_y: 1719189.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1315299.5
      sim_grid_pos_y: 1719002.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1315030.25
      sim_grid_pos_y: 1719451
    }
    terrain_level_point {
      sim_grid_pos_x: 1313958.12
      sim_grid_pos_y: 1718441.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1313359.88
      sim_grid_pos_y: 1718023.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1312862.62
      sim_grid_pos_y: 1717649.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1313025.5
      sim_grid_pos_y: 1717058
    }
    terrain_level_point {
      sim_grid_pos_x: 1313277.62
      sim_grid_pos_y: 1717030.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1314072.38
      sim_grid_pos_y: 1716093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314492.38
      sim_grid_pos_y: 1716071.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315030.5
      sim_grid_pos_y: 1716356.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1315019.25
      sim_grid_pos_y: 1716413.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315227.62
      sim_grid_pos_y: 1716463.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1315867.75
      sim_grid_pos_y: 1716065.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1316064.75
      sim_grid_pos_y: 1716068.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1316439.88
      sim_grid_pos_y: 1715850.25
    }
  }
}
