terrain_level_data {
  terrain_level: 125
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1599886.88
      sim_grid_pos_y: 1976371.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1599836
      sim_grid_pos_y: 1976289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1599955.38
      sim_grid_pos_y: 1976184.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1600066.62
      sim_grid_pos_y: 1976121.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1600136.38
      sim_grid_pos_y: 1976016.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1600151.12
      sim_grid_pos_y: 1975919.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1600309.75
      sim_grid_pos_y: 1975904.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1600498.75
      sim_grid_pos_y: 1975985
    }
    terrain_level_point {
      sim_grid_pos_x: 1600910.88
      sim_grid_pos_y: 1976695.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1600872.62
      sim_grid_pos_y: 1976813
    }
    terrain_level_point {
      sim_grid_pos_x: 1600731.62
      sim_grid_pos_y: 1976918
    }
    terrain_level_point {
      sim_grid_pos_x: 1600639.25
      sim_grid_pos_y: 1976919.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1600603.12
      sim_grid_pos_y: 1977212
    }
    terrain_level_point {
      sim_grid_pos_x: 1.60048e+06
      sim_grid_pos_y: 1977207.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1599962.75
      sim_grid_pos_y: 1976880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1599872
      sim_grid_pos_y: 1976828.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1599785.5
      sim_grid_pos_y: 1976792.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1599829.38
      sim_grid_pos_y: 1976707.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1599822.62
      sim_grid_pos_y: 1976609
    }
    terrain_level_point {
      sim_grid_pos_x: 1599792.88
      sim_grid_pos_y: 1976601.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599779
      sim_grid_pos_y: 1976422.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1599882.12
      sim_grid_pos_y: 1976424.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1600513.12
      sim_grid_pos_y: 1975968.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1600933.25
      sim_grid_pos_y: 1976693.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1600890.12
      sim_grid_pos_y: 1976825.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1600738.62
      sim_grid_pos_y: 1976938.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1600657.38
      sim_grid_pos_y: 1976939.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1600621.12
      sim_grid_pos_y: 1977233.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1600473.75
      sim_grid_pos_y: 1977227.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599952.25
      sim_grid_pos_y: 1976898.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1599863
      sim_grid_pos_y: 1976846.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1599757
      sim_grid_pos_y: 1976803.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1599808.5
      sim_grid_pos_y: 1976703.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1599803.25
      sim_grid_pos_y: 1976625.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1599773.5
      sim_grid_pos_y: 1976618
    }
    terrain_level_point {
      sim_grid_pos_x: 1599756.88
      sim_grid_pos_y: 1976401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599863.38
      sim_grid_pos_y: 1976403.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1599865.88
      sim_grid_pos_y: 1976376.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1599809.38
      sim_grid_pos_y: 1976286
    }
    terrain_level_point {
      sim_grid_pos_x: 1599943.38
      sim_grid_pos_y: 1976167.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1600052.25
      sim_grid_pos_y: 1976105.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1600116.75
      sim_grid_pos_y: 1976009
    }
    terrain_level_point {
      sim_grid_pos_x: 1600133.25
      sim_grid_pos_y: 1975900.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1600313
      sim_grid_pos_y: 1975883.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1600527.38
      sim_grid_pos_y: 1975952.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1600955.62
      sim_grid_pos_y: 1976691
    }
    terrain_level_point {
      sim_grid_pos_x: 1600907.5
      sim_grid_pos_y: 1976838
    }
    terrain_level_point {
      sim_grid_pos_x: 1600745.5
      sim_grid_pos_y: 1976958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1600675.62
      sim_grid_pos_y: 1.97696e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1600639.25
      sim_grid_pos_y: 1977254.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1600467.5
      sim_grid_pos_y: 1977248
    }
    terrain_level_point {
      sim_grid_pos_x: 1599941.62
      sim_grid_pos_y: 1976915.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599853.88
      sim_grid_pos_y: 1976865.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1599728.5
      sim_grid_pos_y: 1976813.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599787.62
      sim_grid_pos_y: 1976699.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1599783.75
      sim_grid_pos_y: 1976641.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599754.25
      sim_grid_pos_y: 1976634.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1599734.75
      sim_grid_pos_y: 1976380.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1599844.62
      sim_grid_pos_y: 1976382.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1599844.75
      sim_grid_pos_y: 1976381.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1599782.88
      sim_grid_pos_y: 1976282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1599931.38
      sim_grid_pos_y: 1976150.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1600037.88
      sim_grid_pos_y: 1976090.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1600097.25
      sim_grid_pos_y: 1976001.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1600115.38
      sim_grid_pos_y: 1975881.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1600316.25
      sim_grid_pos_y: 1975863
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1600541.75
      sim_grid_pos_y: 1975936.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1600977.88
      sim_grid_pos_y: 1976688.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1600925
      sim_grid_pos_y: 1976850.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1600752.5
      sim_grid_pos_y: 1976979.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1600693.75
      sim_grid_pos_y: 1976980.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1600657.25
      sim_grid_pos_y: 1977275.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1600461.25
      sim_grid_pos_y: 1977268.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1599931.12
      sim_grid_pos_y: 1976933.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1599844.88
      sim_grid_pos_y: 1976883.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.5997e+06
      sim_grid_pos_y: 1976824
    }
    terrain_level_point {
      sim_grid_pos_x: 1599766.88
      sim_grid_pos_y: 1976694.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1599764.38
      sim_grid_pos_y: 1976658
    }
    terrain_level_point {
      sim_grid_pos_x: 1599734.88
      sim_grid_pos_y: 1976650.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1599712.5
      sim_grid_pos_y: 1976359.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1599808.25
      sim_grid_pos_y: 1976361.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1599756.25
      sim_grid_pos_y: 1976278.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1599919.38
      sim_grid_pos_y: 1976133.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1600023.5
      sim_grid_pos_y: 1976075
    }
    terrain_level_point {
      sim_grid_pos_x: 1600077.62
      sim_grid_pos_y: 1975993.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1600097.5
      sim_grid_pos_y: 1975862.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1600319.62
      sim_grid_pos_y: 1975842.12
    }
  }
}
