terrain_level_data {
  terrain_level: 6
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2371812.25
      sim_grid_pos_y: 2061311.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2375532
      sim_grid_pos_y: 2056215.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2375109.75
      sim_grid_pos_y: 2055969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2374928
      sim_grid_pos_y: 2056203.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2374402.5
      sim_grid_pos_y: 2056094.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2374071
      sim_grid_pos_y: 2056192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2373473.5
      sim_grid_pos_y: 2057132.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2373177.75
      sim_grid_pos_y: 2058075.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2373079.75
      sim_grid_pos_y: 2058703.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2373013.75
      sim_grid_pos_y: 2058915.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2372877
      sim_grid_pos_y: 2059151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2372764.75
      sim_grid_pos_y: 2059274.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2372448
      sim_grid_pos_y: 2059462.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2371993
      sim_grid_pos_y: 2059727.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2371750.25
      sim_grid_pos_y: 2059925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2371602.25
      sim_grid_pos_y: 2060034.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2371347.25
      sim_grid_pos_y: 2060188.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2375081.25
      sim_grid_pos_y: 2055822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2374882
      sim_grid_pos_y: 2056078.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2374397.75
      sim_grid_pos_y: 2055978
    }
    terrain_level_point {
      sim_grid_pos_x: 2373998.5
      sim_grid_pos_y: 2056096.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2373370.25
      sim_grid_pos_y: 2057085
    }
    terrain_level_point {
      sim_grid_pos_x: 2373067.75
      sim_grid_pos_y: 2058049.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2372969.75
      sim_grid_pos_y: 2058677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2372909.75
      sim_grid_pos_y: 2058870.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2372785.5
      sim_grid_pos_y: 2059084.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2372692.75
      sim_grid_pos_y: 2059186.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2372391.25
      sim_grid_pos_y: 2059365.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2371928.75
      sim_grid_pos_y: 2059634.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2371681
      sim_grid_pos_y: 2059836.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2371539.75
      sim_grid_pos_y: 2059940.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2371205.75
      sim_grid_pos_y: 2060141.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2371733.5
      sim_grid_pos_y: 2061415.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2371864.5
      sim_grid_pos_y: 2061431.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2375696.75
      sim_grid_pos_y: 2056181.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2375052.75
      sim_grid_pos_y: 2055675.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2374836.25
      sim_grid_pos_y: 2055954.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2374393
      sim_grid_pos_y: 2055861.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2373926
      sim_grid_pos_y: 2.056e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2373267
      sim_grid_pos_y: 2057037
    }
    terrain_level_point {
      sim_grid_pos_x: 2372957.5
      sim_grid_pos_y: 2058024
    }
    terrain_level_point {
      sim_grid_pos_x: 2372859.5
      sim_grid_pos_y: 2058652.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2372805.75
      sim_grid_pos_y: 2058824.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2372693.75
      sim_grid_pos_y: 2059017.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2372620.75
      sim_grid_pos_y: 2059098.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2372334.5
      sim_grid_pos_y: 2059267.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2371864.25
      sim_grid_pos_y: 2059541.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2371612
      sim_grid_pos_y: 2059747.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2371476.75
      sim_grid_pos_y: 2059846.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2371064.5
      sim_grid_pos_y: 2060094.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2371654.5
      sim_grid_pos_y: 2061519.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2371916.75
      sim_grid_pos_y: 2061551.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2375861.5
      sim_grid_pos_y: 2056146.88
    }
  }
}
