terrain_level_data {
  terrain_level: 3767
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 451177.281
      sim_grid_pos_y: 1533571.12
    }
    terrain_level_point {
      sim_grid_pos_x: 452234.75
      sim_grid_pos_y: 1533317.38
    }
    terrain_level_point {
      sim_grid_pos_x: 451909.25
      sim_grid_pos_y: 1532689.12
    }
    terrain_level_point {
      sim_grid_pos_x: 451685.875
      sim_grid_pos_y: 1532585
    }
    terrain_level_point {
      sim_grid_pos_x: 451531.875
      sim_grid_pos_y: 1532131.38
    }
    terrain_level_point {
      sim_grid_pos_x: 451219.875
      sim_grid_pos_y: 1531926.88
    }
    terrain_level_point {
      sim_grid_pos_x: 451138.75
      sim_grid_pos_y: 1532179.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451095.156
      sim_grid_pos_y: 1532813.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 451191.656
      sim_grid_pos_y: 1531847.12
    }
    terrain_level_point {
      sim_grid_pos_x: 451088.031
      sim_grid_pos_y: 1.53217e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 451043.719
      sim_grid_pos_y: 1532814.25
    }
    terrain_level_point {
      sim_grid_pos_x: 451132.594
      sim_grid_pos_y: 1533634.62
    }
    terrain_level_point {
      sim_grid_pos_x: 452310.406
      sim_grid_pos_y: 1533351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 451946.719
      sim_grid_pos_y: 1.53265e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 451727.344
      sim_grid_pos_y: 1532547.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451574.719
      sim_grid_pos_y: 1532098.25
    }
  }
}
