terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2385125.25
      sim_grid_pos_y: 926718.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2383774.75
      sim_grid_pos_y: 927346.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2385261.75
      sim_grid_pos_y: 929402.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2386372.5
      sim_grid_pos_y: 931424.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2387271
      sim_grid_pos_y: 932973.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2387891.75
      sim_grid_pos_y: 934141.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2389555
      sim_grid_pos_y: 934374.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2389936.75
      sim_grid_pos_y: 933960.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2389209.5
      sim_grid_pos_y: 933264.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2387167.25
      sim_grid_pos_y: 929991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2386572
      sim_grid_pos_y: 929237.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2385992.25
      sim_grid_pos_y: 928264
    }
    terrain_level_point {
      sim_grid_pos_x: 2385607.5
      sim_grid_pos_y: 927501.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2385293
      sim_grid_pos_y: 927094.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2385140.5
      sim_grid_pos_y: 926677.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2383728
      sim_grid_pos_y: 927334.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2385235.75
      sim_grid_pos_y: 929419.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2386345.75
      sim_grid_pos_y: 931439.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2387244
      sim_grid_pos_y: 932987.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2387872
      sim_grid_pos_y: 934169.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2389566.5
      sim_grid_pos_y: 934407.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2.38998e+06
      sim_grid_pos_y: 933959.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2389233.5
      sim_grid_pos_y: 933245.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2387192.5
      sim_grid_pos_y: 929973.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2386597.5
      sim_grid_pos_y: 929220.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2386019.25
      sim_grid_pos_y: 928249.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2385633.75
      sim_grid_pos_y: 927485
    }
    terrain_level_point {
      sim_grid_pos_x: 2385319.5
      sim_grid_pos_y: 927078.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2385155.75
      sim_grid_pos_y: 926636
    }
    terrain_level_point {
      sim_grid_pos_x: 2383681.25
      sim_grid_pos_y: 927321.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2385209.75
      sim_grid_pos_y: 929435.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2386319
      sim_grid_pos_y: 931454.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2387217
      sim_grid_pos_y: 933003
    }
    terrain_level_point {
      sim_grid_pos_x: 2387852.25
      sim_grid_pos_y: 934198.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2389578.25
      sim_grid_pos_y: 934439.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2390023
      sim_grid_pos_y: 933958.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2389257.5
      sim_grid_pos_y: 933225.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2387217.75
      sim_grid_pos_y: 929956.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2386622.75
      sim_grid_pos_y: 929202.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2386046.25
      sim_grid_pos_y: 928234.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2385659.75
      sim_grid_pos_y: 927468.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2385346.25
      sim_grid_pos_y: 927062.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2385171.25
      sim_grid_pos_y: 926594.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2383634.5
      sim_grid_pos_y: 927309.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2385183.75
      sim_grid_pos_y: 929452.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2386292.25
      sim_grid_pos_y: 931470
    }
    terrain_level_point {
      sim_grid_pos_x: 2387190.25
      sim_grid_pos_y: 933017.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2387832.5
      sim_grid_pos_y: 934226.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.38959e+06
      sim_grid_pos_y: 934472.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2390066.25
      sim_grid_pos_y: 933956.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2389281.5
      sim_grid_pos_y: 933206.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2387243
      sim_grid_pos_y: 929938.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2386648.25
      sim_grid_pos_y: 929185.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2386073.25
      sim_grid_pos_y: 928219.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2385686
      sim_grid_pos_y: 927452
    }
    terrain_level_point {
      sim_grid_pos_x: 2385372.75
      sim_grid_pos_y: 927046.5
    }
  }
}
