terrain_level_data {
  terrain_level: 880
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1825117.12
      sim_grid_pos_y: 1309622.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825261.88
      sim_grid_pos_y: 1309837.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1825456
      sim_grid_pos_y: 1309900.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1825458.88
      sim_grid_pos_y: 1310225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1825714.5
      sim_grid_pos_y: 1310264.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1825774.88
      sim_grid_pos_y: 1310085.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826083.25
      sim_grid_pos_y: 1309961.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1826121.5
      sim_grid_pos_y: 1309742.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826001.62
      sim_grid_pos_y: 1309558.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1825831.62
      sim_grid_pos_y: 1309413.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825613.38
      sim_grid_pos_y: 1309474.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825197.25
      sim_grid_pos_y: 1309499.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1825856.5
      sim_grid_pos_y: 1309300.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1825596.38
      sim_grid_pos_y: 1309373
    }
    terrain_level_point {
      sim_grid_pos_x: 1825139.5
      sim_grid_pos_y: 1309400.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1824994.12
      sim_grid_pos_y: 1309623.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825196.5
      sim_grid_pos_y: 1309923.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825354.12
      sim_grid_pos_y: 1309975.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1825357.12
      sim_grid_pos_y: 1310313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825784.12
      sim_grid_pos_y: 1310378.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1825856.88
      sim_grid_pos_y: 1310162.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1826174.38
      sim_grid_pos_y: 1310034.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1826229.5
      sim_grid_pos_y: 1309720.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826079.5
      sim_grid_pos_y: 1309489.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1825881.38
      sim_grid_pos_y: 1309186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825579.25
      sim_grid_pos_y: 1309271.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1825081.75
      sim_grid_pos_y: 1309300.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1824871.25
      sim_grid_pos_y: 1309624.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825131.25
      sim_grid_pos_y: 1310010.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1825252.25
      sim_grid_pos_y: 1310049.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1825255.38
      sim_grid_pos_y: 1310402
    }
    terrain_level_point {
      sim_grid_pos_x: 1825853.75
      sim_grid_pos_y: 1310492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825939
      sim_grid_pos_y: 1310240.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826265.62
      sim_grid_pos_y: 1310108.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1826337.38
      sim_grid_pos_y: 1309698.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1826157.25
      sim_grid_pos_y: 1309421.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1825906.25
      sim_grid_pos_y: 1309073.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1825562.25
      sim_grid_pos_y: 1309169.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825024
      sim_grid_pos_y: 1309201.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1824748.25
      sim_grid_pos_y: 1309625.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825065.88
      sim_grid_pos_y: 1310096.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825150.38
      sim_grid_pos_y: 1310124.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1825153.62
      sim_grid_pos_y: 1310490.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1825923.38
      sim_grid_pos_y: 1310607
    }
    terrain_level_point {
      sim_grid_pos_x: 1826021
      sim_grid_pos_y: 1310317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1826356.75
      sim_grid_pos_y: 1310182.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1826445.38
      sim_grid_pos_y: 1309676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1826235.12
      sim_grid_pos_y: 1309352.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1825931
      sim_grid_pos_y: 1308959.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1825545.12
      sim_grid_pos_y: 1309068
    }
    terrain_level_point {
      sim_grid_pos_x: 1824966.25
      sim_grid_pos_y: 1309102.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1824625.25
      sim_grid_pos_y: 1309626.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825000.5
      sim_grid_pos_y: 1310183.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1825048.5
      sim_grid_pos_y: 1310198.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1825051.88
      sim_grid_pos_y: 1310578.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825993.12
      sim_grid_pos_y: 1310721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1826103.12
      sim_grid_pos_y: 1310395.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1826447.88
      sim_grid_pos_y: 1310256.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826553.25
      sim_grid_pos_y: 1309654.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1826312.88
      sim_grid_pos_y: 1309284.5
    }
  }
}
terrain_level_data {
  terrain_level: 935
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1824428
      sim_grid_pos_y: 1308731.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1824435.62
      sim_grid_pos_y: 1309063.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1824695.75
      sim_grid_pos_y: 1309065.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1824693.75
      sim_grid_pos_y: 1308736.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1824375.5
      sim_grid_pos_y: 1308679.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1824385.5
      sim_grid_pos_y: 1309113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1824747.25
      sim_grid_pos_y: 1309117.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1824744.75
      sim_grid_pos_y: 1308685.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1824323.12
      sim_grid_pos_y: 1308627.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1824335.5
      sim_grid_pos_y: 1309164.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1824798.88
      sim_grid_pos_y: 1309169.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1824795.75
      sim_grid_pos_y: 1308635.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1824270.62
      sim_grid_pos_y: 1308575.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1824285.38
      sim_grid_pos_y: 1309215.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1824850.38
      sim_grid_pos_y: 1309221.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1824846.75
      sim_grid_pos_y: 1308585
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1824218.12
      sim_grid_pos_y: 1308523.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1824235.25
      sim_grid_pos_y: 1309266.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1824902
      sim_grid_pos_y: 1309272.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1824897.62
      sim_grid_pos_y: 1308534.62
    }
  }
}
terrain_level_data {
  terrain_level: 650
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1826014.38
      sim_grid_pos_y: 1308304.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1825726.25
      sim_grid_pos_y: 1308293.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825651.5
      sim_grid_pos_y: 1308676.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1825710.12
      sim_grid_pos_y: 1308775.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1825995.5
      sim_grid_pos_y: 1308793.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826087.5
      sim_grid_pos_y: 1308905.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826224.62
      sim_grid_pos_y: 1308874.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826229
      sim_grid_pos_y: 1308752.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1826052.12
      sim_grid_pos_y: 1308561.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1825684.38
      sim_grid_pos_y: 1308240.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1825597.5
      sim_grid_pos_y: 1308685.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1825679.75
      sim_grid_pos_y: 1308824.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.82597e+06
      sim_grid_pos_y: 1308843.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1826067.88
      sim_grid_pos_y: 1308962.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826274.5
      sim_grid_pos_y: 1308915.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826281
      sim_grid_pos_y: 1308733.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826100.5
      sim_grid_pos_y: 1308538.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826058.88
      sim_grid_pos_y: 1308255
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1825642.5
      sim_grid_pos_y: 1308188
    }
    terrain_level_point {
      sim_grid_pos_x: 1825543.38
      sim_grid_pos_y: 1308694.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1825649.38
      sim_grid_pos_y: 1308874.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1825944.5
      sim_grid_pos_y: 1308892.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1826048.38
      sim_grid_pos_y: 1309019.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826324.25
      sim_grid_pos_y: 1308956.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1826332.88
      sim_grid_pos_y: 1308714.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1826148.88
      sim_grid_pos_y: 1308515.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1826103.38
      sim_grid_pos_y: 1308205.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1825600.62
      sim_grid_pos_y: 1308135.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1825489.38
      sim_grid_pos_y: 1308704
    }
    terrain_level_point {
      sim_grid_pos_x: 1825619.12
      sim_grid_pos_y: 1308923.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1825919
      sim_grid_pos_y: 1308942.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826028.75
      sim_grid_pos_y: 1309076.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826374.12
      sim_grid_pos_y: 1308998.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1826384.88
      sim_grid_pos_y: 1308695
    }
    terrain_level_point {
      sim_grid_pos_x: 1826197.38
      sim_grid_pos_y: 1308492.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826147.88
      sim_grid_pos_y: 1308155.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1825558.75
      sim_grid_pos_y: 1308082.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1825435.25
      sim_grid_pos_y: 1308713.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1825588.75
      sim_grid_pos_y: 1308973
    }
    terrain_level_point {
      sim_grid_pos_x: 1825893.5
      sim_grid_pos_y: 1308992.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826009.25
      sim_grid_pos_y: 1309133.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1826424
      sim_grid_pos_y: 1309039.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1826436.88
      sim_grid_pos_y: 1308675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1826245.75
      sim_grid_pos_y: 1308469.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1826192.5
      sim_grid_pos_y: 1308106.12
    }
  }
}
