terrain_level_data {
  terrain_level: 3725
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1785670.12
      sim_grid_pos_y: 1637596.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1785973.75
      sim_grid_pos_y: 1637603.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1786168
      sim_grid_pos_y: 1637297.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1785994.88
      sim_grid_pos_y: 1636985.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1785671.88
      sim_grid_pos_y: 1636996
    }
    terrain_level_point {
      sim_grid_pos_x: 1785543.25
      sim_grid_pos_y: 1637183.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1785545.5
      sim_grid_pos_y: 1637403.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1786054.12
      sim_grid_pos_y: 1636881.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1785616.62
      sim_grid_pos_y: 1636895.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1785440.38
      sim_grid_pos_y: 1637152.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1785443.25
      sim_grid_pos_y: 1637433.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1785613.38
      sim_grid_pos_y: 1637697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1786029.38
      sim_grid_pos_y: 1637707.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1786287.25
      sim_grid_pos_y: 1637300.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1786113.38
      sim_grid_pos_y: 1636776.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1785561.5
      sim_grid_pos_y: 1636794.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1785337.62
      sim_grid_pos_y: 1637121.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1785341.12
      sim_grid_pos_y: 1637464.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1785556.62
      sim_grid_pos_y: 1637799
    }
    terrain_level_point {
      sim_grid_pos_x: 1786084.88
      sim_grid_pos_y: 1637811.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1786406.38
      sim_grid_pos_y: 1637303.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1786172.5
      sim_grid_pos_y: 1636672.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1785506.25
      sim_grid_pos_y: 1636693.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1785234.75
      sim_grid_pos_y: 1.63709e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1785238.88
      sim_grid_pos_y: 1637495.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.7855e+06
      sim_grid_pos_y: 1637900.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1786140.5
      sim_grid_pos_y: 1637915.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1786525.62
      sim_grid_pos_y: 1637307.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1786231.75
      sim_grid_pos_y: 1636567.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1785451
      sim_grid_pos_y: 1636592.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1785131.88
      sim_grid_pos_y: 1637058.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1785136.62
      sim_grid_pos_y: 1637525.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1785443.25
      sim_grid_pos_y: 1638001.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1786196
      sim_grid_pos_y: 1638019.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1786644.88
      sim_grid_pos_y: 1637310.75
    }
  }
}
terrain_level_data {
  terrain_level: 3750
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1784751.75
      sim_grid_pos_y: 1635708.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784748.5
      sim_grid_pos_y: 1635882.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1784855
      sim_grid_pos_y: 1636003.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784959.75
      sim_grid_pos_y: 1635969.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1785008.38
      sim_grid_pos_y: 1635870.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1785007
      sim_grid_pos_y: 1635715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784888.75
      sim_grid_pos_y: 1635648.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1784891.62
      sim_grid_pos_y: 1635591.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1784701.12
      sim_grid_pos_y: 1635675.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784696.88
      sim_grid_pos_y: 1635901.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784838.88
      sim_grid_pos_y: 1636063.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784996.12
      sim_grid_pos_y: 1636011
    }
    terrain_level_point {
      sim_grid_pos_x: 1785059.75
      sim_grid_pos_y: 1635882.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1785058
      sim_grid_pos_y: 1635685.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1784894.5
      sim_grid_pos_y: 1635533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784650.5
      sim_grid_pos_y: 1635641.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1784645.25
      sim_grid_pos_y: 1635920.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1784822.88
      sim_grid_pos_y: 1636122.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1785032.62
      sim_grid_pos_y: 1636052.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1785111.12
      sim_grid_pos_y: 1635894.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1785109
      sim_grid_pos_y: 1635655.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1784897.25
      sim_grid_pos_y: 1635476.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1784599.88
      sim_grid_pos_y: 1635607.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784593.62
      sim_grid_pos_y: 1635939.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1784806.75
      sim_grid_pos_y: 1636182
    }
    terrain_level_point {
      sim_grid_pos_x: 1785069.12
      sim_grid_pos_y: 1636094.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1785162.5
      sim_grid_pos_y: 1635906.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.78516e+06
      sim_grid_pos_y: 1635625
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1784900.12
      sim_grid_pos_y: 1635419.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784549.12
      sim_grid_pos_y: 1635574.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1784542
      sim_grid_pos_y: 1635958
    }
    terrain_level_point {
      sim_grid_pos_x: 1784790.62
      sim_grid_pos_y: 1636241.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1785105.5
      sim_grid_pos_y: 1636136.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1785213.88
      sim_grid_pos_y: 1635918
    }
    terrain_level_point {
      sim_grid_pos_x: 1785211
      sim_grid_pos_y: 1635595
    }
  }
}
terrain_level_data {
  terrain_level: 3655
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1784400.25
      sim_grid_pos_y: 1635675.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784433.5
      sim_grid_pos_y: 1636002.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784146.62
      sim_grid_pos_y: 1636028.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784119.38
      sim_grid_pos_y: 1635698.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1784489.62
      sim_grid_pos_y: 1636049.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1784099.75
      sim_grid_pos_y: 1636084.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1784064.12
      sim_grid_pos_y: 1635651.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1784446.25
      sim_grid_pos_y: 1.63562e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1784545.88
      sim_grid_pos_y: 1636095.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1784052.88
      sim_grid_pos_y: 1636140.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1784008.88
      sim_grid_pos_y: 1635605.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1784492.12
      sim_grid_pos_y: 1635564.75
    }
  }
}
