terrain_level_data {
  terrain_level: 65
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1352956.25
      sim_grid_pos_y: 2115592
    }
    terrain_level_point {
      sim_grid_pos_x: 1353300.12
      sim_grid_pos_y: 2115899.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1353278
      sim_grid_pos_y: 2116442.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1353483.5
      sim_grid_pos_y: 2116490.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353920.25
      sim_grid_pos_y: 2116867
    }
    terrain_level_point {
      sim_grid_pos_x: 1354342.12
      sim_grid_pos_y: 2116577
    }
    terrain_level_point {
      sim_grid_pos_x: 1354765.25
      sim_grid_pos_y: 2116467.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354931.12
      sim_grid_pos_y: 2116516.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355101.75
      sim_grid_pos_y: 2116681.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354933.62
      sim_grid_pos_y: 2116814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354388.75
      sim_grid_pos_y: 2116996
    }
    terrain_level_point {
      sim_grid_pos_x: 1354427.62
      sim_grid_pos_y: 2117187.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354679.88
      sim_grid_pos_y: 2117544.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354963
      sim_grid_pos_y: 2117443.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355248.88
      sim_grid_pos_y: 2117518.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355274.25
      sim_grid_pos_y: 2117796.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354999.25
      sim_grid_pos_y: 2117801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354966.25
      sim_grid_pos_y: 2117931.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.35503e+06
      sim_grid_pos_y: 2118075
    }
    terrain_level_point {
      sim_grid_pos_x: 1354942.38
      sim_grid_pos_y: 2118147.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355138.62
      sim_grid_pos_y: 2118341.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355182
      sim_grid_pos_y: 2118566
    }
    terrain_level_point {
      sim_grid_pos_x: 1355901.88
      sim_grid_pos_y: 2119421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355848.5
      sim_grid_pos_y: 2119832
    }
    terrain_level_point {
      sim_grid_pos_x: 1355709.12
      sim_grid_pos_y: 2119948.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355663
      sim_grid_pos_y: 2120112.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356061.25
      sim_grid_pos_y: 2121617.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356404.38
      sim_grid_pos_y: 2122797.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356068.25
      sim_grid_pos_y: 2123217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353874.25
      sim_grid_pos_y: 2123377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353867.5
      sim_grid_pos_y: 2123210.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354270.75
      sim_grid_pos_y: 2122863.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354527.88
      sim_grid_pos_y: 2122458
    }
    terrain_level_point {
      sim_grid_pos_x: 1354817.75
      sim_grid_pos_y: 2122367.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355038.5
      sim_grid_pos_y: 2122176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355179.25
      sim_grid_pos_y: 2121851
    }
    terrain_level_point {
      sim_grid_pos_x: 1355147.62
      sim_grid_pos_y: 2121533
    }
    terrain_level_point {
      sim_grid_pos_x: 1354774.25
      sim_grid_pos_y: 2120609.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354306.12
      sim_grid_pos_y: 2119818.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353778.62
      sim_grid_pos_y: 2119246.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353025.75
      sim_grid_pos_y: 2118712.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1352720.12
      sim_grid_pos_y: 2118388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352293.5
      sim_grid_pos_y: 2118120.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1352199.25
      sim_grid_pos_y: 2117489
    }
    terrain_level_point {
      sim_grid_pos_x: 1352385.5
      sim_grid_pos_y: 2116590.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1353331.38
      sim_grid_pos_y: 2115886.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353309.88
      sim_grid_pos_y: 2116418.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353497.75
      sim_grid_pos_y: 2116462.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353922.38
      sim_grid_pos_y: 2116828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354329.25
      sim_grid_pos_y: 2116548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354765.88
      sim_grid_pos_y: 2116435.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354947.12
      sim_grid_pos_y: 2116489.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355148.38
      sim_grid_pos_y: 2116683.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354948.5
      sim_grid_pos_y: 2116842
    }
    terrain_level_point {
      sim_grid_pos_x: 1354424.38
      sim_grid_pos_y: 2117016.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354456.5
      sim_grid_pos_y: 2117175.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354691.5
      sim_grid_pos_y: 2117507.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354961.62
      sim_grid_pos_y: 2117411
    }
    terrain_level_point {
      sim_grid_pos_x: 1355277.62
      sim_grid_pos_y: 2117494.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355307.88
      sim_grid_pos_y: 2117826.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355023.38
      sim_grid_pos_y: 2117832.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354998.75
      sim_grid_pos_y: 2117928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355067.5
      sim_grid_pos_y: 2118083.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354988.25
      sim_grid_pos_y: 2118149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355167.12
      sim_grid_pos_y: 2118326.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355210.75
      sim_grid_pos_y: 2118552.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355934.12
      sim_grid_pos_y: 2119412
    }
    terrain_level_point {
      sim_grid_pos_x: 1355877.5
      sim_grid_pos_y: 2119848
    }
    terrain_level_point {
      sim_grid_pos_x: 1355736.12
      sim_grid_pos_y: 2119966
    }
    terrain_level_point {
      sim_grid_pos_x: 1355694.88
      sim_grid_pos_y: 2120112.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356090.88
      sim_grid_pos_y: 2121609
    }
    terrain_level_point {
      sim_grid_pos_x: 1356438.38
      sim_grid_pos_y: 2122804.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356083.88
      sim_grid_pos_y: 2123247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353844.88
      sim_grid_pos_y: 2123410.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353836.25
      sim_grid_pos_y: 2123196.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354247.25
      sim_grid_pos_y: 2122843.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354507.88
      sim_grid_pos_y: 2122432
    }
    terrain_level_point {
      sim_grid_pos_x: 1354802.5
      sim_grid_pos_y: 2.12234e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1355013
      sim_grid_pos_y: 2122158
    }
    terrain_level_point {
      sim_grid_pos_x: 1355147.88
      sim_grid_pos_y: 2121846.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355117.38
      sim_grid_pos_y: 2121540.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354746.62
      sim_grid_pos_y: 2120622.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354281.25
      sim_grid_pos_y: 2119836.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1353758.25
      sim_grid_pos_y: 2119269.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353005.5
      sim_grid_pos_y: 2118735.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352700.5
      sim_grid_pos_y: 2118412.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352265.12
      sim_grid_pos_y: 2118138.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352168.12
      sim_grid_pos_y: 2117488
    }
    terrain_level_point {
      sim_grid_pos_x: 1352356.38
      sim_grid_pos_y: 2116579
    }
    terrain_level_point {
      sim_grid_pos_x: 1352948.38
      sim_grid_pos_y: 2115543.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1353362.75
      sim_grid_pos_y: 2115873.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353341.62
      sim_grid_pos_y: 2116394.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353512.12
      sim_grid_pos_y: 2116434
    }
    terrain_level_point {
      sim_grid_pos_x: 1353924.5
      sim_grid_pos_y: 2116789.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354316.25
      sim_grid_pos_y: 2116520.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354766.5
      sim_grid_pos_y: 2116403.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354963.12
      sim_grid_pos_y: 2116462
    }
    terrain_level_point {
      sim_grid_pos_x: 1355195
      sim_grid_pos_y: 2116686
    }
    terrain_level_point {
      sim_grid_pos_x: 1354963.38
      sim_grid_pos_y: 2116869.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354459.88
      sim_grid_pos_y: 2117037
    }
    terrain_level_point {
      sim_grid_pos_x: 1354485.25
      sim_grid_pos_y: 2117162.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354703.12
      sim_grid_pos_y: 2117471
    }
    terrain_level_point {
      sim_grid_pos_x: 1354960.25
      sim_grid_pos_y: 2117378.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355306.25
      sim_grid_pos_y: 2117470.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355341.5
      sim_grid_pos_y: 2117856.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355047.38
      sim_grid_pos_y: 2117862.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355031.12
      sim_grid_pos_y: 2117925.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355105.12
      sim_grid_pos_y: 2118092.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355034
      sim_grid_pos_y: 2118151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355195.5
      sim_grid_pos_y: 2118311
    }
    terrain_level_point {
      sim_grid_pos_x: 1355239.38
      sim_grid_pos_y: 2118538.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355966.38
      sim_grid_pos_y: 2119402.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355906.5
      sim_grid_pos_y: 2119863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355763.25
      sim_grid_pos_y: 2119983.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355726.75
      sim_grid_pos_y: 2120113
    }
    terrain_level_point {
      sim_grid_pos_x: 1356120.62
      sim_grid_pos_y: 2121601.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356472.38
      sim_grid_pos_y: 2122811.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356099.5
      sim_grid_pos_y: 2123277
    }
    terrain_level_point {
      sim_grid_pos_x: 1353815.38
      sim_grid_pos_y: 2123443.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353804.88
      sim_grid_pos_y: 2123183
    }
    terrain_level_point {
      sim_grid_pos_x: 1354223.75
      sim_grid_pos_y: 2122823
    }
    terrain_level_point {
      sim_grid_pos_x: 1354488
      sim_grid_pos_y: 2122406
    }
    terrain_level_point {
      sim_grid_pos_x: 1354787.25
      sim_grid_pos_y: 2122312.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354987.62
      sim_grid_pos_y: 2122139.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355116.5
      sim_grid_pos_y: 2121841.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355087.25
      sim_grid_pos_y: 2121547.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354719
      sim_grid_pos_y: 2120636.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354256.5
      sim_grid_pos_y: 2119855
    }
    terrain_level_point {
      sim_grid_pos_x: 1353737.75
      sim_grid_pos_y: 2119292.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352985.12
      sim_grid_pos_y: 2118759
    }
    terrain_level_point {
      sim_grid_pos_x: 1352680.75
      sim_grid_pos_y: 2118436.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352236.75
      sim_grid_pos_y: 2118157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1352136.88
      sim_grid_pos_y: 2117487.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1352327.25
      sim_grid_pos_y: 2116568
    }
    terrain_level_point {
      sim_grid_pos_x: 1352940.62
      sim_grid_pos_y: 2115495.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1353394
      sim_grid_pos_y: 2.11586e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1353373.38
      sim_grid_pos_y: 2116370.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353526.5
      sim_grid_pos_y: 2116405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1353926.62
      sim_grid_pos_y: 2116750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354303.25
      sim_grid_pos_y: 2116491.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354767
      sim_grid_pos_y: 2116371.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354979.12
      sim_grid_pos_y: 2116434.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355241.75
      sim_grid_pos_y: 2116688.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354978.25
      sim_grid_pos_y: 2116897
    }
    terrain_level_point {
      sim_grid_pos_x: 1354495.38
      sim_grid_pos_y: 2117057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354514.12
      sim_grid_pos_y: 2117150.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354714.75
      sim_grid_pos_y: 2117434
    }
    terrain_level_point {
      sim_grid_pos_x: 1354958.88
      sim_grid_pos_y: 2117346.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355334.88
      sim_grid_pos_y: 2117446
    }
    terrain_level_point {
      sim_grid_pos_x: 1355375.12
      sim_grid_pos_y: 2117886.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355071.38
      sim_grid_pos_y: 2117892.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355063.62
      sim_grid_pos_y: 2117923
    }
    terrain_level_point {
      sim_grid_pos_x: 1355142.62
      sim_grid_pos_y: 2118101.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355079.75
      sim_grid_pos_y: 2118153.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355223.88
      sim_grid_pos_y: 2118295.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355268.12
      sim_grid_pos_y: 2118525
    }
    terrain_level_point {
      sim_grid_pos_x: 1355998.62
      sim_grid_pos_y: 2119393
    }
    terrain_level_point {
      sim_grid_pos_x: 1355935.38
      sim_grid_pos_y: 2119879.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355790.25
      sim_grid_pos_y: 2120001
    }
    terrain_level_point {
      sim_grid_pos_x: 1355758.62
      sim_grid_pos_y: 2120113.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356150.12
      sim_grid_pos_y: 2121592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356506.38
      sim_grid_pos_y: 2122818
    }
    terrain_level_point {
      sim_grid_pos_x: 1356115.12
      sim_grid_pos_y: 2123306.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1353786
      sim_grid_pos_y: 2123476.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353773.5
      sim_grid_pos_y: 2123169.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354200.25
      sim_grid_pos_y: 2122802.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354468
      sim_grid_pos_y: 2.12238e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1354772
      sim_grid_pos_y: 2122285
    }
    terrain_level_point {
      sim_grid_pos_x: 1354962.12
      sim_grid_pos_y: 2122120.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355085
      sim_grid_pos_y: 2121836.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1355057.12
      sim_grid_pos_y: 2121555.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354691.25
      sim_grid_pos_y: 2120650.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354231.62
      sim_grid_pos_y: 2119873.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353717.38
      sim_grid_pos_y: 2119315.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352964.88
      sim_grid_pos_y: 2118782.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1352661.12
      sim_grid_pos_y: 2118460.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352208.38
      sim_grid_pos_y: 2118176
    }
    terrain_level_point {
      sim_grid_pos_x: 1352105.62
      sim_grid_pos_y: 2117486.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1352298.12
      sim_grid_pos_y: 2116557
    }
    terrain_level_point {
      sim_grid_pos_x: 1352932.75
      sim_grid_pos_y: 2115447
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1353425.38
      sim_grid_pos_y: 2115846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1353405.12
      sim_grid_pos_y: 2116346
    }
    terrain_level_point {
      sim_grid_pos_x: 1353540.88
      sim_grid_pos_y: 2116377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353928.75
      sim_grid_pos_y: 2116712
    }
    terrain_level_point {
      sim_grid_pos_x: 1354290.38
      sim_grid_pos_y: 2116463.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354767.62
      sim_grid_pos_y: 2116339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354995
      sim_grid_pos_y: 2116407.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355288.38
      sim_grid_pos_y: 2116690.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354993
      sim_grid_pos_y: 2116924.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354531
      sim_grid_pos_y: 2117078.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354543
      sim_grid_pos_y: 2117138
    }
    terrain_level_point {
      sim_grid_pos_x: 1354726.38
      sim_grid_pos_y: 2117397.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354957.5
      sim_grid_pos_y: 2117314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355363.62
      sim_grid_pos_y: 2117421.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355408.75
      sim_grid_pos_y: 2117916.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355097.12
      sim_grid_pos_y: 2117923
    }
    terrain_level_point {
      sim_grid_pos_x: 1355180.12
      sim_grid_pos_y: 2.11811e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1355125.5
      sim_grid_pos_y: 2118155.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355252.25
      sim_grid_pos_y: 2118280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355296.75
      sim_grid_pos_y: 2118511.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1356030.88
      sim_grid_pos_y: 2119383.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355964.38
      sim_grid_pos_y: 2119895.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1355817.25
      sim_grid_pos_y: 2120018.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355790.5
      sim_grid_pos_y: 2120113.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1356179.88
      sim_grid_pos_y: 2121584.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356540.38
      sim_grid_pos_y: 2122824.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1356130.75
      sim_grid_pos_y: 2123336.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1353756.5
      sim_grid_pos_y: 2123509.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1353742.25
      sim_grid_pos_y: 2123155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354176.62
      sim_grid_pos_y: 2122782.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1354448.12
      sim_grid_pos_y: 2122354
    }
    terrain_level_point {
      sim_grid_pos_x: 1354756.75
      sim_grid_pos_y: 2122257.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1354936.75
      sim_grid_pos_y: 2122102
    }
    terrain_level_point {
      sim_grid_pos_x: 1355053.62
      sim_grid_pos_y: 2121831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1355026.88
      sim_grid_pos_y: 2121562.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1354663.62
      sim_grid_pos_y: 2120664
    }
    terrain_level_point {
      sim_grid_pos_x: 1354206.88
      sim_grid_pos_y: 2119892
    }
    terrain_level_point {
      sim_grid_pos_x: 1353697
      sim_grid_pos_y: 2119339
    }
    terrain_level_point {
      sim_grid_pos_x: 1352944.62
      sim_grid_pos_y: 2118805.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1352641.38
      sim_grid_pos_y: 2118484.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1352180.12
      sim_grid_pos_y: 2118194.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1352074.38
      sim_grid_pos_y: 2117485.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1352269
      sim_grid_pos_y: 2116546
    }
    terrain_level_point {
      sim_grid_pos_x: 1352924.88
      sim_grid_pos_y: 2115398.75
    }
  }
}
