terrain_level_data {
  terrain_level: 485
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1626262.62
      sim_grid_pos_y: 1486246
    }
    terrain_level_point {
      sim_grid_pos_x: 1626413
      sim_grid_pos_y: 1486242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1626401
      sim_grid_pos_y: 1486671.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1626509.5
      sim_grid_pos_y: 1486689.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1626497.12
      sim_grid_pos_y: 1486867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1626289.38
      sim_grid_pos_y: 1486823.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1626118.75
      sim_grid_pos_y: 1486994.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1626033.5
      sim_grid_pos_y: 1486907.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1626236.88
      sim_grid_pos_y: 1486768
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1626506
      sim_grid_pos_y: 1486585
    }
    terrain_level_point {
      sim_grid_pos_x: 1626618.25
      sim_grid_pos_y: 1486603.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1626591.25
      sim_grid_pos_y: 1486992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1626322.62
      sim_grid_pos_y: 1486935.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1626118
      sim_grid_pos_y: 1.48714e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1625874.75
      sim_grid_pos_y: 1486891.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1626137
      sim_grid_pos_y: 1486712.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1626164.88
      sim_grid_pos_y: 1486145.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1626518.5
      sim_grid_pos_y: 1486137.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1626611
      sim_grid_pos_y: 1486498.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1626727
      sim_grid_pos_y: 1486517.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1626685.38
      sim_grid_pos_y: 1487117.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1626355.75
      sim_grid_pos_y: 1487047.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1626117.38
      sim_grid_pos_y: 1487285.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1625716
      sim_grid_pos_y: 1486876.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1626037.12
      sim_grid_pos_y: 1486656.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1626067.25
      sim_grid_pos_y: 1486045.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1626624
      sim_grid_pos_y: 1486033.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1626716
      sim_grid_pos_y: 1486412
    }
    terrain_level_point {
      sim_grid_pos_x: 1626835.75
      sim_grid_pos_y: 1486431.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1626779.38
      sim_grid_pos_y: 1487241.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1626389
      sim_grid_pos_y: 1487159
    }
    terrain_level_point {
      sim_grid_pos_x: 1626116.62
      sim_grid_pos_y: 1487431.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1625557.12
      sim_grid_pos_y: 1486860.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1625937.12
      sim_grid_pos_y: 1486600.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1625969.5
      sim_grid_pos_y: 1485944.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1626729.5
      sim_grid_pos_y: 1485928.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1626821
      sim_grid_pos_y: 1486325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1626944.5
      sim_grid_pos_y: 1486346
    }
    terrain_level_point {
      sim_grid_pos_x: 1626873.5
      sim_grid_pos_y: 1487366.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1626422.12
      sim_grid_pos_y: 1487270.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1626116
      sim_grid_pos_y: 1487577.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1625398.38
      sim_grid_pos_y: 1486845.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1625837.25
      sim_grid_pos_y: 1486544.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1625871.88
      sim_grid_pos_y: 1485844.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1626835
      sim_grid_pos_y: 1485823.38
    }
  }
}
terrain_level_data {
  terrain_level: 460
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1627596.88
      sim_grid_pos_y: 1485502.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1627598
      sim_grid_pos_y: 1485813.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1627920.38
      sim_grid_pos_y: 1485814.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1627915.88
      sim_grid_pos_y: 1485496.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1627966.5
      sim_grid_pos_y: 1485444.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1627545.5
      sim_grid_pos_y: 1485452
    }
    terrain_level_point {
      sim_grid_pos_x: 1627547
      sim_grid_pos_y: 1485864.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1627972.38
      sim_grid_pos_y: 1485866.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1628017
      sim_grid_pos_y: 1485392
    }
    terrain_level_point {
      sim_grid_pos_x: 1627494
      sim_grid_pos_y: 1485401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1627495.88
      sim_grid_pos_y: 1485915.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1628024.38
      sim_grid_pos_y: 1485917.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1628067.5
      sim_grid_pos_y: 1485339.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1627442.62
      sim_grid_pos_y: 1485351.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1627444.75
      sim_grid_pos_y: 1485966.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1628076.38
      sim_grid_pos_y: 1485969.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1628118
      sim_grid_pos_y: 1485287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1627391.12
      sim_grid_pos_y: 1485301
    }
    terrain_level_point {
      sim_grid_pos_x: 1627393.75
      sim_grid_pos_y: 1486017.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1628128.38
      sim_grid_pos_y: 1486020.62
    }
  }
}
