terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2225364
      sim_grid_pos_y: 821922.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2225228.25
      sim_grid_pos_y: 822145.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2224770.75
      sim_grid_pos_y: 822272.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2224570.25
      sim_grid_pos_y: 822141.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2224561
      sim_grid_pos_y: 822448.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2223712
      sim_grid_pos_y: 823728.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2228110.75
      sim_grid_pos_y: 826034.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2228280.5
      sim_grid_pos_y: 826141.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2228509.5
      sim_grid_pos_y: 826064.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2.22932e+06
      sim_grid_pos_y: 825876.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2228740.25
      sim_grid_pos_y: 824528.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2225355.75
      sim_grid_pos_y: 821877.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2225208.25
      sim_grid_pos_y: 822118.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2224776
      sim_grid_pos_y: 822239.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2224572
      sim_grid_pos_y: 822106.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2.22454e+06
      sim_grid_pos_y: 822122.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2224530.5
      sim_grid_pos_y: 822439.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2223667.5
      sim_grid_pos_y: 823740.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2228095.25
      sim_grid_pos_y: 826060.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2228276.25
      sim_grid_pos_y: 826175.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2228517.75
      sim_grid_pos_y: 826094.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2229362.75
      sim_grid_pos_y: 825898.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2228765.5
      sim_grid_pos_y: 824509.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2225347.25
      sim_grid_pos_y: 821832.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2225188.25
      sim_grid_pos_y: 822092.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2224781
      sim_grid_pos_y: 822206.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2224573.75
      sim_grid_pos_y: 822070.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2.22451e+06
      sim_grid_pos_y: 822104
    }
    terrain_level_point {
      sim_grid_pos_x: 2.2245e+06
      sim_grid_pos_y: 822429.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2223623
      sim_grid_pos_y: 823751.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2.22808e+06
      sim_grid_pos_y: 826087.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2228272.25
      sim_grid_pos_y: 826208.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2228526.25
      sim_grid_pos_y: 826124.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2229405.75
      sim_grid_pos_y: 825920
    }
    terrain_level_point {
      sim_grid_pos_x: 2228790.5
      sim_grid_pos_y: 824489.938
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2225339
      sim_grid_pos_y: 821786.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2225168.25
      sim_grid_pos_y: 822066.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2224786.25
      sim_grid_pos_y: 822172.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2224575.5
      sim_grid_pos_y: 822035.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2224479.75
      sim_grid_pos_y: 822085.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2224469.5
      sim_grid_pos_y: 822419.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2223578.5
      sim_grid_pos_y: 823763.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2228064.5
      sim_grid_pos_y: 826114.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2228268.25
      sim_grid_pos_y: 826242.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2228534.5
      sim_grid_pos_y: 826153.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2229448.5
      sim_grid_pos_y: 825941.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2228815.5
      sim_grid_pos_y: 824470.438
    }
  }
}
