terrain_level_data {
  terrain_level: 50
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 916716.25
      sim_grid_pos_y: 1382072.75
    }
    terrain_level_point {
      sim_grid_pos_x: 916839.125
      sim_grid_pos_y: 1382437
    }
    terrain_level_point {
      sim_grid_pos_x: 916896.625
      sim_grid_pos_y: 1383773.62
    }
    terrain_level_point {
      sim_grid_pos_x: 916243.688
      sim_grid_pos_y: 1384670.75
    }
    terrain_level_point {
      sim_grid_pos_x: 917025
      sim_grid_pos_y: 1384943.75
    }
    terrain_level_point {
      sim_grid_pos_x: 918162.688
      sim_grid_pos_y: 1385241.5
    }
    terrain_level_point {
      sim_grid_pos_x: 918500.562
      sim_grid_pos_y: 1385248.38
    }
    terrain_level_point {
      sim_grid_pos_x: 918530.062
      sim_grid_pos_y: 1384806
    }
    terrain_level_point {
      sim_grid_pos_x: 918779.875
      sim_grid_pos_y: 1384807.38
    }
    terrain_level_point {
      sim_grid_pos_x: 918773.5
      sim_grid_pos_y: 1382068
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 918804.188
      sim_grid_pos_y: 1382037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 916673.438
      sim_grid_pos_y: 1382042
    }
    terrain_level_point {
      sim_grid_pos_x: 916808.625
      sim_grid_pos_y: 1382442.75
    }
    terrain_level_point {
      sim_grid_pos_x: 916865.438
      sim_grid_pos_y: 1383764.25
    }
    terrain_level_point {
      sim_grid_pos_x: 916194.438
      sim_grid_pos_y: 1384686.12
    }
    terrain_level_point {
      sim_grid_pos_x: 917016.062
      sim_grid_pos_y: 1384973.12
    }
    terrain_level_point {
      sim_grid_pos_x: 918158.438
      sim_grid_pos_y: 1385272.12
    }
    terrain_level_point {
      sim_grid_pos_x: 918529.25
      sim_grid_pos_y: 1385279.75
    }
    terrain_level_point {
      sim_grid_pos_x: 918558.875
      sim_grid_pos_y: 1384836.88
    }
    terrain_level_point {
      sim_grid_pos_x: 918810.75
      sim_grid_pos_y: 1384838.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 918834.875
      sim_grid_pos_y: 1382006.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916630.625
      sim_grid_pos_y: 1382011.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916778.062
      sim_grid_pos_y: 1382448.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916834.25
      sim_grid_pos_y: 1383754.88
    }
    terrain_level_point {
      sim_grid_pos_x: 916145.188
      sim_grid_pos_y: 1384701.5
    }
    terrain_level_point {
      sim_grid_pos_x: 917007.062
      sim_grid_pos_y: 1385002.62
    }
    terrain_level_point {
      sim_grid_pos_x: 918154.125
      sim_grid_pos_y: 1385302.75
    }
    terrain_level_point {
      sim_grid_pos_x: 918558
      sim_grid_pos_y: 1385311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 918587.625
      sim_grid_pos_y: 1384867.88
    }
    terrain_level_point {
      sim_grid_pos_x: 918841.562
      sim_grid_pos_y: 1384869.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 918865.562
      sim_grid_pos_y: 1381975.5
    }
    terrain_level_point {
      sim_grid_pos_x: 916587.812
      sim_grid_pos_y: 1381980.75
    }
    terrain_level_point {
      sim_grid_pos_x: 916747.562
      sim_grid_pos_y: 1382454.12
    }
    terrain_level_point {
      sim_grid_pos_x: 916803.062
      sim_grid_pos_y: 1383745.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916095.938
      sim_grid_pos_y: 1384716.88
    }
    terrain_level_point {
      sim_grid_pos_x: 916998.062
      sim_grid_pos_y: 1385032
    }
    terrain_level_point {
      sim_grid_pos_x: 918149.875
      sim_grid_pos_y: 1385333.5
    }
    terrain_level_point {
      sim_grid_pos_x: 918586.75
      sim_grid_pos_y: 1385342.38
    }
    terrain_level_point {
      sim_grid_pos_x: 918616.375
      sim_grid_pos_y: 1384898.75
    }
    terrain_level_point {
      sim_grid_pos_x: 918872.375
      sim_grid_pos_y: 1384900.25
    }
  }
}
terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 914542.688
      sim_grid_pos_y: 1381943.38
    }
    terrain_level_point {
      sim_grid_pos_x: 914549.625
      sim_grid_pos_y: 1381009.75
    }
    terrain_level_point {
      sim_grid_pos_x: 916000.312
      sim_grid_pos_y: 1381038.88
    }
    terrain_level_point {
      sim_grid_pos_x: 916362
      sim_grid_pos_y: 1381470.12
    }
    terrain_level_point {
      sim_grid_pos_x: 916197.188
      sim_grid_pos_y: 1381872.12
    }
    terrain_level_point {
      sim_grid_pos_x: 916270.75
      sim_grid_pos_y: 1382746.62
    }
    terrain_level_point {
      sim_grid_pos_x: 916018.438
      sim_grid_pos_y: 1382900.25
    }
    terrain_level_point {
      sim_grid_pos_x: 915804.188
      sim_grid_pos_y: 1382901.88
    }
    terrain_level_point {
      sim_grid_pos_x: 915225
      sim_grid_pos_y: 1382614.38
    }
    terrain_level_point {
      sim_grid_pos_x: 914930.5
      sim_grid_pos_y: 1382048.38
    }
    terrain_level_point {
      sim_grid_pos_x: 914650.5
      sim_grid_pos_y: 1382023.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 916014.875
      sim_grid_pos_y: 1381008.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916397.5
      sim_grid_pos_y: 1381464.62
    }
    terrain_level_point {
      sim_grid_pos_x: 916228.438
      sim_grid_pos_y: 1381877
    }
    terrain_level_point {
      sim_grid_pos_x: 916303
      sim_grid_pos_y: 1382763
    }
    terrain_level_point {
      sim_grid_pos_x: 916027.188
      sim_grid_pos_y: 1382930.88
    }
    terrain_level_point {
      sim_grid_pos_x: 915797.062
      sim_grid_pos_y: 1382932.62
    }
    terrain_level_point {
      sim_grid_pos_x: 915202.375
      sim_grid_pos_y: 1382637.38
    }
    terrain_level_point {
      sim_grid_pos_x: 914911
      sim_grid_pos_y: 1382077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 914639.125
      sim_grid_pos_y: 1382053.25
    }
    terrain_level_point {
      sim_grid_pos_x: 914511.812
      sim_grid_pos_y: 1381958.88
    }
    terrain_level_point {
      sim_grid_pos_x: 914519.062
      sim_grid_pos_y: 1380978.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 916029.438
      sim_grid_pos_y: 1380977.88
    }
    terrain_level_point {
      sim_grid_pos_x: 916433
      sim_grid_pos_y: 1381459
    }
    terrain_level_point {
      sim_grid_pos_x: 916259.75
      sim_grid_pos_y: 1381881.75
    }
    terrain_level_point {
      sim_grid_pos_x: 916335.25
      sim_grid_pos_y: 1382779.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916035.938
      sim_grid_pos_y: 1382961.62
    }
    terrain_level_point {
      sim_grid_pos_x: 915790
      sim_grid_pos_y: 1382963.5
    }
    terrain_level_point {
      sim_grid_pos_x: 915179.75
      sim_grid_pos_y: 1382660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 914891.5
      sim_grid_pos_y: 1382106.62
    }
    terrain_level_point {
      sim_grid_pos_x: 914627.75
      sim_grid_pos_y: 1382083.12
    }
    terrain_level_point {
      sim_grid_pos_x: 914480.938
      sim_grid_pos_y: 1381974.25
    }
    terrain_level_point {
      sim_grid_pos_x: 914488.562
      sim_grid_pos_y: 1380947
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 916044.062
      sim_grid_pos_y: 1380947.38
    }
    terrain_level_point {
      sim_grid_pos_x: 916468.5
      sim_grid_pos_y: 1381453.5
    }
    terrain_level_point {
      sim_grid_pos_x: 916291
      sim_grid_pos_y: 1381886.62
    }
    terrain_level_point {
      sim_grid_pos_x: 916367.5
      sim_grid_pos_y: 1382795.75
    }
    terrain_level_point {
      sim_grid_pos_x: 916044.688
      sim_grid_pos_y: 1382992.38
    }
    terrain_level_point {
      sim_grid_pos_x: 915782.875
      sim_grid_pos_y: 1382994.25
    }
    terrain_level_point {
      sim_grid_pos_x: 915157.062
      sim_grid_pos_y: 1382683.62
    }
    terrain_level_point {
      sim_grid_pos_x: 914872
      sim_grid_pos_y: 1382135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 914616.375
      sim_grid_pos_y: 1382113
    }
    terrain_level_point {
      sim_grid_pos_x: 914450.062
      sim_grid_pos_y: 1381989.62
    }
    terrain_level_point {
      sim_grid_pos_x: 914458.062
      sim_grid_pos_y: 1380915.62
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 917872.438
      sim_grid_pos_y: 1381634.75
    }
    terrain_level_point {
      sim_grid_pos_x: 917681.938
      sim_grid_pos_y: 1381661.88
    }
    terrain_level_point {
      sim_grid_pos_x: 918147.562
      sim_grid_pos_y: 1380982.62
    }
    terrain_level_point {
      sim_grid_pos_x: 919003.125
      sim_grid_pos_y: 1380992.62
    }
    terrain_level_point {
      sim_grid_pos_x: 919301.25
      sim_grid_pos_y: 1381136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 919420.75
      sim_grid_pos_y: 1.38113e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 919521
      sim_grid_pos_y: 1380985
    }
    terrain_level_point {
      sim_grid_pos_x: 919928.812
      sim_grid_pos_y: 1380989.5
    }
    terrain_level_point {
      sim_grid_pos_x: 919967.375
      sim_grid_pos_y: 1381229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 920011.5
      sim_grid_pos_y: 1381267.62
    }
    terrain_level_point {
      sim_grid_pos_x: 920084.938
      sim_grid_pos_y: 1381168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 920389.625
      sim_grid_pos_y: 1.38118e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 920772.75
      sim_grid_pos_y: 1381496.75
    }
    terrain_level_point {
      sim_grid_pos_x: 920970.812
      sim_grid_pos_y: 1382122.38
    }
    terrain_level_point {
      sim_grid_pos_x: 919546.75
      sim_grid_pos_y: 1381816.75
    }
    terrain_level_point {
      sim_grid_pos_x: 918329.5
      sim_grid_pos_y: 1381629.25
    }
    terrain_level_point {
      sim_grid_pos_x: 918249.062
      sim_grid_pos_y: 1381805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 918063.938
      sim_grid_pos_y: 1381860.12
    }
    terrain_level_point {
      sim_grid_pos_x: 917937.75
      sim_grid_pos_y: 1381832.5
    }
    terrain_level_point {
      sim_grid_pos_x: 917936.875
      sim_grid_pos_y: 1381618.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 919010.312
      sim_grid_pos_y: 1380962
    }
    terrain_level_point {
      sim_grid_pos_x: 919307.5
      sim_grid_pos_y: 1381105.12
    }
    terrain_level_point {
      sim_grid_pos_x: 919404.062
      sim_grid_pos_y: 1.3811e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 919505
      sim_grid_pos_y: 1380954.12
    }
    terrain_level_point {
      sim_grid_pos_x: 919955.062
      sim_grid_pos_y: 1380959
    }
    terrain_level_point {
      sim_grid_pos_x: 919995.938
      sim_grid_pos_y: 1381213.62
    }
    terrain_level_point {
      sim_grid_pos_x: 920006.5
      sim_grid_pos_y: 1381222.75
    }
    terrain_level_point {
      sim_grid_pos_x: 920069.875
      sim_grid_pos_y: 1381137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 920401.188
      sim_grid_pos_y: 1381149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 920799.312
      sim_grid_pos_y: 1381478.75
    }
    terrain_level_point {
      sim_grid_pos_x: 921016.062
      sim_grid_pos_y: 1382163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 919541.25
      sim_grid_pos_y: 1381847
    }
    terrain_level_point {
      sim_grid_pos_x: 918347.812
      sim_grid_pos_y: 1381663.12
    }
    terrain_level_point {
      sim_grid_pos_x: 918271.25
      sim_grid_pos_y: 1381831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 918065.062
      sim_grid_pos_y: 1381891.88
    }
    terrain_level_point {
      sim_grid_pos_x: 917907.062
      sim_grid_pos_y: 1381857.25
    }
    terrain_level_point {
      sim_grid_pos_x: 917906.25
      sim_grid_pos_y: 1381657.88
    }
    terrain_level_point {
      sim_grid_pos_x: 917878.438
      sim_grid_pos_y: 1381665
    }
    terrain_level_point {
      sim_grid_pos_x: 917666.438
      sim_grid_pos_y: 1381695.25
    }
    terrain_level_point {
      sim_grid_pos_x: 917645.25
      sim_grid_pos_y: 1381661.12
    }
    terrain_level_point {
      sim_grid_pos_x: 918131.5
      sim_grid_pos_y: 1380951.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 919017.562
      sim_grid_pos_y: 1380931.25
    }
    terrain_level_point {
      sim_grid_pos_x: 919313.75
      sim_grid_pos_y: 1381074
    }
    terrain_level_point {
      sim_grid_pos_x: 919387.312
      sim_grid_pos_y: 1381070.12
    }
    terrain_level_point {
      sim_grid_pos_x: 919489
      sim_grid_pos_y: 1380923.25
    }
    terrain_level_point {
      sim_grid_pos_x: 919981.375
      sim_grid_pos_y: 1380928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 920017.812
      sim_grid_pos_y: 1381155.88
    }
    terrain_level_point {
      sim_grid_pos_x: 920054.812
      sim_grid_pos_y: 1381106
    }
    terrain_level_point {
      sim_grid_pos_x: 920412.75
      sim_grid_pos_y: 1381119.38
    }
    terrain_level_point {
      sim_grid_pos_x: 920825.938
      sim_grid_pos_y: 1381460.88
    }
    terrain_level_point {
      sim_grid_pos_x: 921061.375
      sim_grid_pos_y: 1382204.75
    }
    terrain_level_point {
      sim_grid_pos_x: 919535.562
      sim_grid_pos_y: 1381877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 918366.188
      sim_grid_pos_y: 1381697.12
    }
    terrain_level_point {
      sim_grid_pos_x: 918293.375
      sim_grid_pos_y: 1381857
    }
    terrain_level_point {
      sim_grid_pos_x: 918066.188
      sim_grid_pos_y: 1381923.62
    }
    terrain_level_point {
      sim_grid_pos_x: 917876.438
      sim_grid_pos_y: 1381882.12
    }
    terrain_level_point {
      sim_grid_pos_x: 917875.625
      sim_grid_pos_y: 1381696.38
    }
    terrain_level_point {
      sim_grid_pos_x: 917650.875
      sim_grid_pos_y: 1381728.5
    }
    terrain_level_point {
      sim_grid_pos_x: 917608.5
      sim_grid_pos_y: 1381660.25
    }
    terrain_level_point {
      sim_grid_pos_x: 918115.438
      sim_grid_pos_y: 1380920.75
    }
  }
}
