terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 485844.375
      sim_grid_pos_y: 1474177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485452.719
      sim_grid_pos_y: 1473066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485323.125
      sim_grid_pos_y: 1472026.12
    }
    terrain_level_point {
      sim_grid_pos_x: 485416.594
      sim_grid_pos_y: 1471108.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485650.406
      sim_grid_pos_y: 1470267.75
    }
    terrain_level_point {
      sim_grid_pos_x: 484281.688
      sim_grid_pos_y: 1469409.62
    }
    terrain_level_point {
      sim_grid_pos_x: 482600.562
      sim_grid_pos_y: 1469387.5
    }
    terrain_level_point {
      sim_grid_pos_x: 481672.344
      sim_grid_pos_y: 1469161.62
    }
    terrain_level_point {
      sim_grid_pos_x: 479851.281
      sim_grid_pos_y: 1469174.62
    }
    terrain_level_point {
      sim_grid_pos_x: 474267.875
      sim_grid_pos_y: 1469132.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474145.938
      sim_grid_pos_y: 1473610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 475073.531
      sim_grid_pos_y: 1473495.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476140.094
      sim_grid_pos_y: 1473664.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479611.594
      sim_grid_pos_y: 1473658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 480304
      sim_grid_pos_y: 1473873.25
    }
    terrain_level_point {
      sim_grid_pos_x: 481567.594
      sim_grid_pos_y: 1474492
    }
    terrain_level_point {
      sim_grid_pos_x: 484272.5
      sim_grid_pos_y: 1474616
    }
    terrain_level_point {
      sim_grid_pos_x: 485078.031
      sim_grid_pos_y: 1474604.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 474237.969
      sim_grid_pos_y: 1469101.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474114.219
      sim_grid_pos_y: 1473645.38
    }
    terrain_level_point {
      sim_grid_pos_x: 475073
      sim_grid_pos_y: 1473526.12
    }
    terrain_level_point {
      sim_grid_pos_x: 476137.688
      sim_grid_pos_y: 1473694.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479606.969
      sim_grid_pos_y: 1473689.25
    }
    terrain_level_point {
      sim_grid_pos_x: 480292.656
      sim_grid_pos_y: 1473902
    }
    terrain_level_point {
      sim_grid_pos_x: 481559.781
      sim_grid_pos_y: 1474522.5
    }
    terrain_level_point {
      sim_grid_pos_x: 484272.031
      sim_grid_pos_y: 1474646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485086.219
      sim_grid_pos_y: 1474635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 485882
      sim_grid_pos_y: 1474192
    }
    terrain_level_point {
      sim_grid_pos_x: 485482.812
      sim_grid_pos_y: 1473059.62
    }
    terrain_level_point {
      sim_grid_pos_x: 485354.062
      sim_grid_pos_y: 1472025.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485446.938
      sim_grid_pos_y: 1471114.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485686.188
      sim_grid_pos_y: 1470253.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484290.719
      sim_grid_pos_y: 1469379
    }
    terrain_level_point {
      sim_grid_pos_x: 482604.438
      sim_grid_pos_y: 1469356.75
    }
    terrain_level_point {
      sim_grid_pos_x: 481675.906
      sim_grid_pos_y: 1469130.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479851.281
      sim_grid_pos_y: 1469143.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 474208.031
      sim_grid_pos_y: 1469070.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474082.5
      sim_grid_pos_y: 1473680.38
    }
    terrain_level_point {
      sim_grid_pos_x: 475072.5
      sim_grid_pos_y: 1473557.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476135.312
      sim_grid_pos_y: 1473725.62
    }
    terrain_level_point {
      sim_grid_pos_x: 479602.375
      sim_grid_pos_y: 1.47372e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 480281.219
      sim_grid_pos_y: 1473930.62
    }
    terrain_level_point {
      sim_grid_pos_x: 481552
      sim_grid_pos_y: 1474552.88
    }
    terrain_level_point {
      sim_grid_pos_x: 484271.531
      sim_grid_pos_y: 1474677.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485094.438
      sim_grid_pos_y: 1474665.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485919.625
      sim_grid_pos_y: 1474206.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485512.906
      sim_grid_pos_y: 1473052.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485385
      sim_grid_pos_y: 1472025.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485477.25
      sim_grid_pos_y: 1471120.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485721.969
      sim_grid_pos_y: 1.47024e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 484299.75
      sim_grid_pos_y: 1469348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 482608.344
      sim_grid_pos_y: 1469326.12
    }
    terrain_level_point {
      sim_grid_pos_x: 481679.5
      sim_grid_pos_y: 1.4691e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 479851.312
      sim_grid_pos_y: 1469113
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 474178.125
      sim_grid_pos_y: 1469039.75
    }
    terrain_level_point {
      sim_grid_pos_x: 474050.781
      sim_grid_pos_y: 1473715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 475071.969
      sim_grid_pos_y: 1473588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 476132.906
      sim_grid_pos_y: 1473756.38
    }
    terrain_level_point {
      sim_grid_pos_x: 479597.688
      sim_grid_pos_y: 1473750.88
    }
    terrain_level_point {
      sim_grid_pos_x: 480269.875
      sim_grid_pos_y: 1473959.25
    }
    terrain_level_point {
      sim_grid_pos_x: 481544.219
      sim_grid_pos_y: 1474583.38
    }
    terrain_level_point {
      sim_grid_pos_x: 484271.062
      sim_grid_pos_y: 1474708.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485102.625
      sim_grid_pos_y: 1474696.38
    }
    terrain_level_point {
      sim_grid_pos_x: 485957.281
      sim_grid_pos_y: 1474220.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485543.031
      sim_grid_pos_y: 1473045.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485415.969
      sim_grid_pos_y: 1472025.12
    }
    terrain_level_point {
      sim_grid_pos_x: 485507.594
      sim_grid_pos_y: 1471125.88
    }
    terrain_level_point {
      sim_grid_pos_x: 485757.75
      sim_grid_pos_y: 1470226.12
    }
    terrain_level_point {
      sim_grid_pos_x: 484308.781
      sim_grid_pos_y: 1469317.62
    }
    terrain_level_point {
      sim_grid_pos_x: 482612.219
      sim_grid_pos_y: 1469295.38
    }
    terrain_level_point {
      sim_grid_pos_x: 481683.062
      sim_grid_pos_y: 1469069.25
    }
    terrain_level_point {
      sim_grid_pos_x: 479851.312
      sim_grid_pos_y: 1469082.25
    }
  }
}
