terrain_level_data {
  terrain_level: 975
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1748835.38
      sim_grid_pos_y: 1424968.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1749100.62
      sim_grid_pos_y: 1425673.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1749433.75
      sim_grid_pos_y: 1425864.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1749585.38
      sim_grid_pos_y: 1425643.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1749469.88
      sim_grid_pos_y: 1425534.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1749149.75
      sim_grid_pos_y: 1425277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1748929.38
      sim_grid_pos_y: 1424891
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1748958
      sim_grid_pos_y: 1424734.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1748713.62
      sim_grid_pos_y: 1424936.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1749017.62
      sim_grid_pos_y: 1425743.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1749464.62
      sim_grid_pos_y: 1.426e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1749719.62
      sim_grid_pos_y: 1425629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1749537.38
      sim_grid_pos_y: 1425457.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1749229.12
      sim_grid_pos_y: 1425209.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1748986.62
      sim_grid_pos_y: 1424577.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1748591.88
      sim_grid_pos_y: 1424904
    }
    terrain_level_point {
      sim_grid_pos_x: 1748934.75
      sim_grid_pos_y: 1425814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1749495.62
      sim_grid_pos_y: 1426135.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1749853.88
      sim_grid_pos_y: 1425615.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1749604.75
      sim_grid_pos_y: 1.42538e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1749308.62
      sim_grid_pos_y: 1425142
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1749015.25
      sim_grid_pos_y: 1424420.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1748470.12
      sim_grid_pos_y: 1424871.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1748851.75
      sim_grid_pos_y: 1425885.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1749526.5
      sim_grid_pos_y: 1426271.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1749988
      sim_grid_pos_y: 1425601.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1749672.25
      sim_grid_pos_y: 1425302.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1749388
      sim_grid_pos_y: 1425074.25
    }
  }
}
terrain_level_data {
  terrain_level: 800
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1748605.25
      sim_grid_pos_y: 1419185.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1749036.5
      sim_grid_pos_y: 1419801.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1748213.25
      sim_grid_pos_y: 1420453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1752538.12
      sim_grid_pos_y: 1427509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1753024.75
      sim_grid_pos_y: 1427273.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1753182.75
      sim_grid_pos_y: 1427698.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1752659.38
      sim_grid_pos_y: 1427993.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1752960.38
      sim_grid_pos_y: 1428492
    }
    terrain_level_point {
      sim_grid_pos_x: 1752624.62
      sim_grid_pos_y: 1428669.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1752230.5
      sim_grid_pos_y: 1428082.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1751776.38
      sim_grid_pos_y: 1428292.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.75126e+06
      sim_grid_pos_y: 1427385.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1750575.88
      sim_grid_pos_y: 1425988.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1747573.75
      sim_grid_pos_y: 1421374.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1746726.88
      sim_grid_pos_y: 1421864.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.74479e+06
      sim_grid_pos_y: 1421454.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1744845.5
      sim_grid_pos_y: 1420558.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1745201.62
      sim_grid_pos_y: 1420453.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1747173.12
      sim_grid_pos_y: 1420576.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1747097.38
      sim_grid_pos_y: 1419610.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1749175.88
      sim_grid_pos_y: 1419821.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1748348.12
      sim_grid_pos_y: 1420477.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1752577
      sim_grid_pos_y: 1427376.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1753081.5
      sim_grid_pos_y: 1427131.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1753309.38
      sim_grid_pos_y: 1427744.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752801.75
      sim_grid_pos_y: 1428030.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1753104.25
      sim_grid_pos_y: 1428532
    }
    terrain_level_point {
      sim_grid_pos_x: 1752590.88
      sim_grid_pos_y: 1428803
    }
    terrain_level_point {
      sim_grid_pos_x: 1752194.12
      sim_grid_pos_y: 1428211.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1751733.88
      sim_grid_pos_y: 1428425
    }
    terrain_level_point {
      sim_grid_pos_x: 1751169.38
      sim_grid_pos_y: 1427433.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1750486.5
      sim_grid_pos_y: 1426039.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1747540.88
      sim_grid_pos_y: 1421511.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1746744.12
      sim_grid_pos_y: 1421972.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1744682.12
      sim_grid_pos_y: 1421536.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1744747.62
      sim_grid_pos_y: 1420480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.74519e+06
      sim_grid_pos_y: 1420349.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1747061.75
      sim_grid_pos_y: 1420466.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1746988.62
      sim_grid_pos_y: 1419534.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1748647.5
      sim_grid_pos_y: 1419067.12
    }
  }
}
