terrain_level_data {
  terrain_level: 110
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1936132.5
      sim_grid_pos_y: 63007.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 1935970.38
      sim_grid_pos_y: 66344.7188
    }
    terrain_level_point {
      sim_grid_pos_x: 1933867.75
      sim_grid_pos_y: 66280.8281
    }
    terrain_level_point {
      sim_grid_pos_x: 1934070.38
      sim_grid_pos_y: 62880.2148
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1936164.62
      sim_grid_pos_y: 62978.4805
    }
    terrain_level_point {
      sim_grid_pos_x: 1935999.62
      sim_grid_pos_y: 66376.3828
    }
    terrain_level_point {
      sim_grid_pos_x: 1933835.25
      sim_grid_pos_y: 66310.6094
    }
    terrain_level_point {
      sim_grid_pos_x: 1934041.5
      sim_grid_pos_y: 62847.6133
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1936196.88
      sim_grid_pos_y: 62949.6523
    }
    terrain_level_point {
      sim_grid_pos_x: 1936028.88
      sim_grid_pos_y: 66408.0391
    }
    terrain_level_point {
      sim_grid_pos_x: 1933802.62
      sim_grid_pos_y: 66340.3906
    }
    terrain_level_point {
      sim_grid_pos_x: 1934012.62
      sim_grid_pos_y: 62815.0234
    }
  }
}
