terrain_level_data {
  terrain_level: 1200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1905485.25
      sim_grid_pos_y: 446356.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1905361.62
      sim_grid_pos_y: 446504.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.90539e+06
      sim_grid_pos_y: 446724.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1905608.25
      sim_grid_pos_y: 446797.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1905809
      sim_grid_pos_y: 446637.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1905902.5
      sim_grid_pos_y: 446500.031
    }
    terrain_level_point {
      sim_grid_pos_x: 1905796.5
      sim_grid_pos_y: 446415.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1905622.5
      sim_grid_pos_y: 446330.094
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1905626.75
      sim_grid_pos_y: 446297.969
    }
    terrain_level_point {
      sim_grid_pos_x: 1905468.62
      sim_grid_pos_y: 446327.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1905329.5
      sim_grid_pos_y: 446495.406
    }
    terrain_level_point {
      sim_grid_pos_x: 1905362
      sim_grid_pos_y: 446747.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1905614.25
      sim_grid_pos_y: 446831.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1905831.88
      sim_grid_pos_y: 446658.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1905943.88
      sim_grid_pos_y: 446493.781
    }
    terrain_level_point {
      sim_grid_pos_x: 1905813.12
      sim_grid_pos_y: 446389.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1905631.12
      sim_grid_pos_y: 446265.844
    }
    terrain_level_point {
      sim_grid_pos_x: 1905452
      sim_grid_pos_y: 446299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1905297.25
      sim_grid_pos_y: 446486.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1905333.88
      sim_grid_pos_y: 446770.281
    }
    terrain_level_point {
      sim_grid_pos_x: 1905620.38
      sim_grid_pos_y: 446866.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1905854.62
      sim_grid_pos_y: 446679.469
    }
    terrain_level_point {
      sim_grid_pos_x: 1905985.38
      sim_grid_pos_y: 446487.531
    }
    terrain_level_point {
      sim_grid_pos_x: 1905829.62
      sim_grid_pos_y: 446363.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1905635.5
      sim_grid_pos_y: 446233.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1905435.5
      sim_grid_pos_y: 446271.594
    }
    terrain_level_point {
      sim_grid_pos_x: 1905265
      sim_grid_pos_y: 446476.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1905305.88
      sim_grid_pos_y: 446793.344
    }
    terrain_level_point {
      sim_grid_pos_x: 1905626.5
      sim_grid_pos_y: 446900.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1905877.5
      sim_grid_pos_y: 446700.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1906026.88
      sim_grid_pos_y: 446481.281
    }
    terrain_level_point {
      sim_grid_pos_x: 1905846.25
      sim_grid_pos_y: 446337.031
    }
  }
}
terrain_level_data {
  terrain_level: 995
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1905557.38
      sim_grid_pos_y: 447152.406
    }
    terrain_level_point {
      sim_grid_pos_x: 1905459.62
      sim_grid_pos_y: 447228.406
    }
    terrain_level_point {
      sim_grid_pos_x: 1905632
      sim_grid_pos_y: 447441.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1905717.25
      sim_grid_pos_y: 447351.531
    }
    terrain_level_point {
      sim_grid_pos_x: 1905765.5
      sim_grid_pos_y: 447352.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1905739.75
      sim_grid_pos_y: 447323.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1905678.38
      sim_grid_pos_y: 447292.344
    }
    terrain_level_point {
      sim_grid_pos_x: 1905620.88
      sim_grid_pos_y: 447152.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1905546.88
      sim_grid_pos_y: 447121.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1905416
      sim_grid_pos_y: 447223.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1905630.25
      sim_grid_pos_y: 447488.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1905730.38
      sim_grid_pos_y: 447382.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1905785.25
      sim_grid_pos_y: 447383.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1905801.75
      sim_grid_pos_y: 447346.344
    }
    terrain_level_point {
      sim_grid_pos_x: 1905758.75
      sim_grid_pos_y: 447298.906
    }
    terrain_level_point {
      sim_grid_pos_x: 1905702.5
      sim_grid_pos_y: 447270.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1905641.5
      sim_grid_pos_y: 447121.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1905536.25
      sim_grid_pos_y: 447090.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1905372.38
      sim_grid_pos_y: 447218.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1905628.38
      sim_grid_pos_y: 447535.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1905743.5
      sim_grid_pos_y: 447413.344
    }
    terrain_level_point {
      sim_grid_pos_x: 1905805
      sim_grid_pos_y: 447414.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1905838.12
      sim_grid_pos_y: 447340.594
    }
    terrain_level_point {
      sim_grid_pos_x: 1905777.75
      sim_grid_pos_y: 447274.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1905726.62
      sim_grid_pos_y: 447247.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1905662.12
      sim_grid_pos_y: 447091.031
    }
  }
}
terrain_level_data {
  terrain_level: 770
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1903832
      sim_grid_pos_y: 445409.531
    }
    terrain_level_point {
      sim_grid_pos_x: 1903603.5
      sim_grid_pos_y: 445555.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1903537.62
      sim_grid_pos_y: 445404.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1903784.5
      sim_grid_pos_y: 445262.344
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1903868.62
      sim_grid_pos_y: 445422.656
    }
    terrain_level_point {
      sim_grid_pos_x: 1903589.62
      sim_grid_pos_y: 445601.094
    }
    terrain_level_point {
      sim_grid_pos_x: 1903498.5
      sim_grid_pos_y: 445391.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1903802.12
      sim_grid_pos_y: 445216.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1903905.12
      sim_grid_pos_y: 445435.781
    }
    terrain_level_point {
      sim_grid_pos_x: 1903575.88
      sim_grid_pos_y: 445646.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1903459.25
      sim_grid_pos_y: 445378.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1903819.75
      sim_grid_pos_y: 445171.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1903941.75
      sim_grid_pos_y: 445448.906
    }
    terrain_level_point {
      sim_grid_pos_x: 1903562
      sim_grid_pos_y: 445691.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1903420.12
      sim_grid_pos_y: 445365.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1903837.38
      sim_grid_pos_y: 445125.594
    }
  }
}
