terrain_level_data {
  terrain_level: 45
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2261884.75
      sim_grid_pos_y: 781224.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2263637.75
      sim_grid_pos_y: 783523.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2264899.5
      sim_grid_pos_y: 782589.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2266738.75
      sim_grid_pos_y: 781748
    }
    terrain_level_point {
      sim_grid_pos_x: 2267066.5
      sim_grid_pos_y: 781431.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2268017
      sim_grid_pos_y: 779626.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2268123.5
      sim_grid_pos_y: 779076.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2267581.25
      sim_grid_pos_y: 777255.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2266914.5
      sim_grid_pos_y: 777562.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2266503.25
      sim_grid_pos_y: 778089.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2266320.25
      sim_grid_pos_y: 778277.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2265417.5
      sim_grid_pos_y: 778657.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2267600.5
      sim_grid_pos_y: 777212.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2266894.75
      sim_grid_pos_y: 777538.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2.26648e+06
      sim_grid_pos_y: 778069.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2266302.5
      sim_grid_pos_y: 778251.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2265402.25
      sim_grid_pos_y: 778630.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2261841.25
      sim_grid_pos_y: 781218.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2263631.75
      sim_grid_pos_y: 783566.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2264915.25
      sim_grid_pos_y: 782616.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2266756.25
      sim_grid_pos_y: 781773.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2267091.5
      sim_grid_pos_y: 781450.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2268046.5
      sim_grid_pos_y: 779637.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2268155.25
      sim_grid_pos_y: 779075
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2267619.75
      sim_grid_pos_y: 777169.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2266875
      sim_grid_pos_y: 777513.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2266456.75
      sim_grid_pos_y: 778049.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2266284.75
      sim_grid_pos_y: 778225.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2265387
      sim_grid_pos_y: 778603.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2261797.75
      sim_grid_pos_y: 781212.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2263625.5
      sim_grid_pos_y: 783609.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2264931
      sim_grid_pos_y: 782642.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2266774
      sim_grid_pos_y: 781799.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2267116.25
      sim_grid_pos_y: 781468.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2268075.75
      sim_grid_pos_y: 779647.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2268187
      sim_grid_pos_y: 779073.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2267639.25
      sim_grid_pos_y: 777126.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2266855.5
      sim_grid_pos_y: 777488.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2266433.75
      sim_grid_pos_y: 778028.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2266267
      sim_grid_pos_y: 778199.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2265372
      sim_grid_pos_y: 778576.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2261754.25
      sim_grid_pos_y: 781205.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2263619.5
      sim_grid_pos_y: 783652
    }
    terrain_level_point {
      sim_grid_pos_x: 2264946.5
      sim_grid_pos_y: 782669.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2266791.5
      sim_grid_pos_y: 781825.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2267141.25
      sim_grid_pos_y: 781487.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2268105
      sim_grid_pos_y: 779657.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2268218.5
      sim_grid_pos_y: 779071.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2267658.5
      sim_grid_pos_y: 777083.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2266835.75
      sim_grid_pos_y: 777463.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2266410.5
      sim_grid_pos_y: 778008.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2266249.5
      sim_grid_pos_y: 778173.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2265356.75
      sim_grid_pos_y: 778549.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2261710.75
      sim_grid_pos_y: 781199.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2263613.5
      sim_grid_pos_y: 783694.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2264962.25
      sim_grid_pos_y: 782696.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2266809
      sim_grid_pos_y: 781851.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2267166.25
      sim_grid_pos_y: 781506.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2268134.5
      sim_grid_pos_y: 779668
    }
    terrain_level_point {
      sim_grid_pos_x: 2268250.25
      sim_grid_pos_y: 779070.375
    }
  }
}
