terrain_level_data {
  terrain_level: 388
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1887993.88
      sim_grid_pos_y: 1216049
    }
    terrain_level_point {
      sim_grid_pos_x: 1887899.88
      sim_grid_pos_y: 1216176.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1887929.75
      sim_grid_pos_y: 1216341.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1888030.38
      sim_grid_pos_y: 1216392.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1888155.38
      sim_grid_pos_y: 1216400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1888264.5
      sim_grid_pos_y: 1216275.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1888265.12
      sim_grid_pos_y: 1216062.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1888144.25
      sim_grid_pos_y: 1215994.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1888148.88
      sim_grid_pos_y: 1215938.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1887961.88
      sim_grid_pos_y: 1216006
    }
    terrain_level_point {
      sim_grid_pos_x: 1887845.5
      sim_grid_pos_y: 1216163.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1887883.88
      sim_grid_pos_y: 1216375.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1888016.62
      sim_grid_pos_y: 1216443
    }
    terrain_level_point {
      sim_grid_pos_x: 1888177.5
      sim_grid_pos_y: 1216453.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1888315.62
      sim_grid_pos_y: 1216294.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1888316.5
      sim_grid_pos_y: 1216032.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1888153.62
      sim_grid_pos_y: 1215882.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1887929.88
      sim_grid_pos_y: 1215963.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1887791.12
      sim_grid_pos_y: 1216151
    }
    terrain_level_point {
      sim_grid_pos_x: 1887837.88
      sim_grid_pos_y: 1216410.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1888002.75
      sim_grid_pos_y: 1216493.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1888199.5
      sim_grid_pos_y: 1216506.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1888366.88
      sim_grid_pos_y: 1216313.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1888367.88
      sim_grid_pos_y: 1216003
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1888158.25
      sim_grid_pos_y: 1215826
    }
    terrain_level_point {
      sim_grid_pos_x: 1887897.88
      sim_grid_pos_y: 1215920.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1887736.75
      sim_grid_pos_y: 1216138.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1887792
      sim_grid_pos_y: 1216444.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1887989
      sim_grid_pos_y: 1216543.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1888221.5
      sim_grid_pos_y: 1216559.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1888418.12
      sim_grid_pos_y: 1216332.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1888419.12
      sim_grid_pos_y: 1215973.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1888163
      sim_grid_pos_y: 1215769.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1887865.88
      sim_grid_pos_y: 1215877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1887682.38
      sim_grid_pos_y: 1216125.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1887746.12
      sim_grid_pos_y: 1216478.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1887975.25
      sim_grid_pos_y: 1216594.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1888243.5
      sim_grid_pos_y: 1216612
    }
    terrain_level_point {
      sim_grid_pos_x: 1888469.25
      sim_grid_pos_y: 1216351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1888470.5
      sim_grid_pos_y: 1215943.25
    }
  }
}
terrain_level_data {
  terrain_level: 325
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1890563.5
      sim_grid_pos_y: 1217049.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1890583.5
      sim_grid_pos_y: 1217194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1890736
      sim_grid_pos_y: 1217262.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1890836.25
      sim_grid_pos_y: 1217211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1890925.25
      sim_grid_pos_y: 1217033.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1890834.12
      sim_grid_pos_y: 1216899.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1890733.75
      sim_grid_pos_y: 1216857.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1890589.75
      sim_grid_pos_y: 1216924.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1890732.5
      sim_grid_pos_y: 1216801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1890544.88
      sim_grid_pos_y: 1216889
    }
    terrain_level_point {
      sim_grid_pos_x: 1890511.5
      sim_grid_pos_y: 1217047.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1890536.5
      sim_grid_pos_y: 1217229.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1890737.38
      sim_grid_pos_y: 1217319.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1890874.5
      sim_grid_pos_y: 1217249.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1890984.5
      sim_grid_pos_y: 1.21703e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1890867.88
      sim_grid_pos_y: 1216857.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1890731.25
      sim_grid_pos_y: 1216745.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.8905e+06
      sim_grid_pos_y: 1216853.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1890459.5
      sim_grid_pos_y: 1217045.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1890489.62
      sim_grid_pos_y: 1217264.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1890738.62
      sim_grid_pos_y: 1217376
    }
    terrain_level_point {
      sim_grid_pos_x: 1890912.75
      sim_grid_pos_y: 1217288
    }
    terrain_level_point {
      sim_grid_pos_x: 1891043.75
      sim_grid_pos_y: 1217026.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1890901.75
      sim_grid_pos_y: 1216816.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1.89073e+06
      sim_grid_pos_y: 1216689.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1890455.12
      sim_grid_pos_y: 1216817.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1890407.5
      sim_grid_pos_y: 1217044
    }
    terrain_level_point {
      sim_grid_pos_x: 1890442.75
      sim_grid_pos_y: 1217299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.89074e+06
      sim_grid_pos_y: 1217432.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1890951
      sim_grid_pos_y: 1217326.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1891103
      sim_grid_pos_y: 1217022.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1890935.62
      sim_grid_pos_y: 1216774.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1890728.75
      sim_grid_pos_y: 1216633.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1890410.25
      sim_grid_pos_y: 1216782
    }
    terrain_level_point {
      sim_grid_pos_x: 1890355.5
      sim_grid_pos_y: 1217042.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1890395.88
      sim_grid_pos_y: 1217335
    }
    terrain_level_point {
      sim_grid_pos_x: 1890741.38
      sim_grid_pos_y: 1217489.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1890989.25
      sim_grid_pos_y: 1217364.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1891162.25
      sim_grid_pos_y: 1217018.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1890969.38
      sim_grid_pos_y: 1216733.12
    }
  }
}
terrain_level_data {
  terrain_level: 360
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1886652
      sim_grid_pos_y: 1214707
    }
    terrain_level_point {
      sim_grid_pos_x: 1886654.62
      sim_grid_pos_y: 1214835.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1886753.5
      sim_grid_pos_y: 1214850.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1886924.25
      sim_grid_pos_y: 1214831.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1887000.38
      sim_grid_pos_y: 1214779.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1887012.12
      sim_grid_pos_y: 1.21463e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1886930.88
      sim_grid_pos_y: 1214610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1886691.25
      sim_grid_pos_y: 1214616.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1886936.38
      sim_grid_pos_y: 1214559.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1886657.25
      sim_grid_pos_y: 1214566.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1886600.5
      sim_grid_pos_y: 1214696.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1886604.25
      sim_grid_pos_y: 1214879.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1886752.5
      sim_grid_pos_y: 1214902
    }
    terrain_level_point {
      sim_grid_pos_x: 1886942.5
      sim_grid_pos_y: 1214881
    }
    terrain_level_point {
      sim_grid_pos_x: 1887049.62
      sim_grid_pos_y: 1214808.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1887066.62
      sim_grid_pos_y: 1214590.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1886941.75
      sim_grid_pos_y: 1214507.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1886623.25
      sim_grid_pos_y: 1214515.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1886549
      sim_grid_pos_y: 1214686.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1886553.88
      sim_grid_pos_y: 1214923.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1886751.5
      sim_grid_pos_y: 1214953.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1886960.75
      sim_grid_pos_y: 1214930.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1887098.75
      sim_grid_pos_y: 1214837
    }
    terrain_level_point {
      sim_grid_pos_x: 1887121.12
      sim_grid_pos_y: 1214550.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1886947.25
      sim_grid_pos_y: 1214456.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1886589.25
      sim_grid_pos_y: 1214465.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1886497.5
      sim_grid_pos_y: 1214676.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1886503.5
      sim_grid_pos_y: 1214968.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1886750.38
      sim_grid_pos_y: 1215005.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1886979
      sim_grid_pos_y: 1214980.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1887148
      sim_grid_pos_y: 1214865.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1887175.62
      sim_grid_pos_y: 1214511.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1886952.62
      sim_grid_pos_y: 1214404.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1886555.25
      sim_grid_pos_y: 1214414.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1886446
      sim_grid_pos_y: 1214666.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1886453.12
      sim_grid_pos_y: 1215012.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1886749.38
      sim_grid_pos_y: 1215057.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1886997.38
      sim_grid_pos_y: 1215029.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1887197.12
      sim_grid_pos_y: 1214894.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1887230.12
      sim_grid_pos_y: 1214471.5
    }
  }
}
