terrain_level_data {
  terrain_level: 180
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1216323.62
      sim_grid_pos_y: 1558649.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217453
      sim_grid_pos_y: 1558645.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217691.88
      sim_grid_pos_y: 1558351.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1217864.12
      sim_grid_pos_y: 1558109.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218089.62
      sim_grid_pos_y: 1557991.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1218099.38
      sim_grid_pos_y: 1557802.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218236.12
      sim_grid_pos_y: 1557786.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218279.88
      sim_grid_pos_y: 1557210.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218296.88
      sim_grid_pos_y: 1556828.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1218642.88
      sim_grid_pos_y: 1556815
    }
    terrain_level_point {
      sim_grid_pos_x: 1219360.5
      sim_grid_pos_y: 1556789.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219592
      sim_grid_pos_y: 1556741.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1219732.62
      sim_grid_pos_y: 1556989.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219555.12
      sim_grid_pos_y: 1557142
    }
    terrain_level_point {
      sim_grid_pos_x: 1219613.25
      sim_grid_pos_y: 1557693.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1219380.62
      sim_grid_pos_y: 1557801.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1219436
      sim_grid_pos_y: 1558395.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1219268.5
      sim_grid_pos_y: 1558561
    }
    terrain_level_point {
      sim_grid_pos_x: 1219781.5
      sim_grid_pos_y: 1559113
    }
    terrain_level_point {
      sim_grid_pos_x: 1219953.5
      sim_grid_pos_y: 1.55918e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1220268
      sim_grid_pos_y: 1559569.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1220250.88
      sim_grid_pos_y: 1559721
    }
    terrain_level_point {
      sim_grid_pos_x: 1219761.88
      sim_grid_pos_y: 1.5597e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1219784.5
      sim_grid_pos_y: 1559894.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1219438.75
      sim_grid_pos_y: 1560159.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219012.5
      sim_grid_pos_y: 1560283.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218881
      sim_grid_pos_y: 1560226.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218744.62
      sim_grid_pos_y: 1560185.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218617
      sim_grid_pos_y: 1560227.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1218249.88
      sim_grid_pos_y: 1560522.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218077.5
      sim_grid_pos_y: 1560538.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1217992.62
      sim_grid_pos_y: 1560607.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1217832.5
      sim_grid_pos_y: 1560620.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217702.62
      sim_grid_pos_y: 1560703.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217449.38
      sim_grid_pos_y: 1560712.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1217435
      sim_grid_pos_y: 1560906
    }
    terrain_level_point {
      sim_grid_pos_x: 1217083
      sim_grid_pos_y: 1560893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1216979
      sim_grid_pos_y: 1560754.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1216961.5
      sim_grid_pos_y: 1560557.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1216699.5
      sim_grid_pos_y: 1560450.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216472.88
      sim_grid_pos_y: 1560319.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1215952.5
      sim_grid_pos_y: 1560085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1215877.88
      sim_grid_pos_y: 1559673.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1219771.88
      sim_grid_pos_y: 1556995.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219587.38
      sim_grid_pos_y: 1557154.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219646.12
      sim_grid_pos_y: 1557712
    }
    terrain_level_point {
      sim_grid_pos_x: 1219413.25
      sim_grid_pos_y: 1557820.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1219468
      sim_grid_pos_y: 1558407.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219311.38
      sim_grid_pos_y: 1558561.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219799.25
      sim_grid_pos_y: 1559086.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219972.38
      sim_grid_pos_y: 1559154.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1220300.12
      sim_grid_pos_y: 1559559.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1220278.25
      sim_grid_pos_y: 1559753
    }
    terrain_level_point {
      sim_grid_pos_x: 1219796.5
      sim_grid_pos_y: 1559732.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1219817.12
      sim_grid_pos_y: 1559908.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219452.88
      sim_grid_pos_y: 1560187.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219010.38
      sim_grid_pos_y: 1560315.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1218870.38
      sim_grid_pos_y: 1560255.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1218745
      sim_grid_pos_y: 1560217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218631.88
      sim_grid_pos_y: 1560254.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1218262
      sim_grid_pos_y: 1560552
    }
    terrain_level_point {
      sim_grid_pos_x: 1218089.62
      sim_grid_pos_y: 1560568
    }
    terrain_level_point {
      sim_grid_pos_x: 1218004.75
      sim_grid_pos_y: 1560637
    }
    terrain_level_point {
      sim_grid_pos_x: 1217842.75
      sim_grid_pos_y: 1560650.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217712.12
      sim_grid_pos_y: 1560734.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217478
      sim_grid_pos_y: 1560742
    }
    terrain_level_point {
      sim_grid_pos_x: 1217463.5
      sim_grid_pos_y: 1560937.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1217067.12
      sim_grid_pos_y: 1560923.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216949.12
      sim_grid_pos_y: 1560765.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1216932.62
      sim_grid_pos_y: 1560578.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1216685.88
      sim_grid_pos_y: 1560478.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1216458.88
      sim_grid_pos_y: 1560347.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1215925.12
      sim_grid_pos_y: 1560107
    }
    terrain_level_point {
      sim_grid_pos_x: 1215845.88
      sim_grid_pos_y: 1559669.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216303.5
      sim_grid_pos_y: 1558618.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1217438.38
      sim_grid_pos_y: 1558614.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1217667.38
      sim_grid_pos_y: 1558332.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1217843.38
      sim_grid_pos_y: 1558085.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1218059.88
      sim_grid_pos_y: 1557972.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.21807e+06
      sim_grid_pos_y: 1557774.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1218207.38
      sim_grid_pos_y: 1557758.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1218249.12
      sim_grid_pos_y: 1557208.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218267.38
      sim_grid_pos_y: 1556799.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218641.75
      sim_grid_pos_y: 1556784.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1219356.88
      sim_grid_pos_y: 1556758.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1219607.62
      sim_grid_pos_y: 1556706.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1219811.12
      sim_grid_pos_y: 1557002.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1219619.75
      sim_grid_pos_y: 1557167.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1219679
      sim_grid_pos_y: 1557730.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1219445.88
      sim_grid_pos_y: 1557839
    }
    terrain_level_point {
      sim_grid_pos_x: 1.2195e+06
      sim_grid_pos_y: 1558418.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1219354.12
      sim_grid_pos_y: 1558562.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219817
      sim_grid_pos_y: 1559060.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219991.12
      sim_grid_pos_y: 1559128.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1220332.12
      sim_grid_pos_y: 1559550.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1220305.5
      sim_grid_pos_y: 1559784.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219831.25
      sim_grid_pos_y: 1559764.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1219849.75
      sim_grid_pos_y: 1559922
    }
    terrain_level_point {
      sim_grid_pos_x: 1219467
      sim_grid_pos_y: 1560215
    }
    terrain_level_point {
      sim_grid_pos_x: 1219008.38
      sim_grid_pos_y: 1560348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218859.88
      sim_grid_pos_y: 1560284.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1218745.5
      sim_grid_pos_y: 1560249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1218646.75
      sim_grid_pos_y: 1560282.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1218274
      sim_grid_pos_y: 1560581.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1218101.75
      sim_grid_pos_y: 1560597.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1218016.75
      sim_grid_pos_y: 1560666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217852.88
      sim_grid_pos_y: 1560680.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217721.5
      sim_grid_pos_y: 1560764.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1217506.62
      sim_grid_pos_y: 1560771.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217491.88
      sim_grid_pos_y: 1560969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1217051.38
      sim_grid_pos_y: 1560954
    }
    terrain_level_point {
      sim_grid_pos_x: 1216919.25
      sim_grid_pos_y: 1560777.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1216903.62
      sim_grid_pos_y: 1560600.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1216672.38
      sim_grid_pos_y: 1560506.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1216444.75
      sim_grid_pos_y: 1560374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1215897.75
      sim_grid_pos_y: 1560128.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1215814
      sim_grid_pos_y: 1559666
    }
    terrain_level_point {
      sim_grid_pos_x: 1216283.25
      sim_grid_pos_y: 1558588
    }
    terrain_level_point {
      sim_grid_pos_x: 1217423.75
      sim_grid_pos_y: 1558584
    }
    terrain_level_point {
      sim_grid_pos_x: 1217642.88
      sim_grid_pos_y: 1558314.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217822.62
      sim_grid_pos_y: 1558061.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.21803e+06
      sim_grid_pos_y: 1557953.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218040.62
      sim_grid_pos_y: 1557747.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1218178.62
      sim_grid_pos_y: 1557731.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1218218.5
      sim_grid_pos_y: 1557206.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1218237.88
      sim_grid_pos_y: 1556769.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1218640.5
      sim_grid_pos_y: 1556753.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1219353.12
      sim_grid_pos_y: 1556727.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219623.38
      sim_grid_pos_y: 1556672.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1219850.38
      sim_grid_pos_y: 1557009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1219652
      sim_grid_pos_y: 1557180.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1219711.88
      sim_grid_pos_y: 1557749.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1219478.5
      sim_grid_pos_y: 1557857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1219532
      sim_grid_pos_y: 1558430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1219397
      sim_grid_pos_y: 1558563.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1219834.75
      sim_grid_pos_y: 1559034.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1220009.88
      sim_grid_pos_y: 1559102.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1220364.12
      sim_grid_pos_y: 1559541.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1220332.88
      sim_grid_pos_y: 1559816.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219866
      sim_grid_pos_y: 1559796.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219882.25
      sim_grid_pos_y: 1559935.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1219481.12
      sim_grid_pos_y: 1560242.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219006.25
      sim_grid_pos_y: 1560381.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1218849.25
      sim_grid_pos_y: 1560313
    }
    terrain_level_point {
      sim_grid_pos_x: 1218745.88
      sim_grid_pos_y: 1560282
    }
    terrain_level_point {
      sim_grid_pos_x: 1218661.62
      sim_grid_pos_y: 1560309.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1218286.12
      sim_grid_pos_y: 1560611.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218113.88
      sim_grid_pos_y: 1560627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1218028.75
      sim_grid_pos_y: 1560696.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1217863
      sim_grid_pos_y: 1560710.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1217731
      sim_grid_pos_y: 1560795.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1217535.25
      sim_grid_pos_y: 1560801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1217520.38
      sim_grid_pos_y: 1561001.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217035.5
      sim_grid_pos_y: 1560984.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1216889.38
      sim_grid_pos_y: 1560788.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1216874.62
      sim_grid_pos_y: 1560621.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216658.88
      sim_grid_pos_y: 1560533.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1216430.75
      sim_grid_pos_y: 1560402.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1215870.38
      sim_grid_pos_y: 1560149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1215782.12
      sim_grid_pos_y: 1559662.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1216263.12
      sim_grid_pos_y: 1558557.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217409
      sim_grid_pos_y: 1558553.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1217618.5
      sim_grid_pos_y: 1558295.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1217801.75
      sim_grid_pos_y: 1558037.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1218000.25
      sim_grid_pos_y: 1557934.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1218011.25
      sim_grid_pos_y: 1557719.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1218149.88
      sim_grid_pos_y: 1557703.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1218187.75
      sim_grid_pos_y: 1557204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1218208.5
      sim_grid_pos_y: 1556740.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1218639.38
      sim_grid_pos_y: 1556722.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1219349.5
      sim_grid_pos_y: 1556697.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1219639
      sim_grid_pos_y: 1556637.62
    }
  }
}
