terrain_level_data {
  terrain_level: 370
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1685410.25
      sim_grid_pos_y: 1389230.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685492.5
      sim_grid_pos_y: 1389143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685622.12
      sim_grid_pos_y: 1389042.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685732.75
      sim_grid_pos_y: 1389092.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685791.5
      sim_grid_pos_y: 1389198.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685844.12
      sim_grid_pos_y: 1389250.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685955.5
      sim_grid_pos_y: 1389342.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686030.5
      sim_grid_pos_y: 1389475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.68605e+06
      sim_grid_pos_y: 1389576
    }
    terrain_level_point {
      sim_grid_pos_x: 1686051.62
      sim_grid_pos_y: 1389645.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685981.12
      sim_grid_pos_y: 1389759.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685794.38
      sim_grid_pos_y: 1389755.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685673.25
      sim_grid_pos_y: 1389731.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685540.5
      sim_grid_pos_y: 1389683.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685435.62
      sim_grid_pos_y: 1389613
    }
    terrain_level_point {
      sim_grid_pos_x: 1685388.75
      sim_grid_pos_y: 1389471.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685383.38
      sim_grid_pos_y: 1389367
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1685747.38
      sim_grid_pos_y: 1389077
    }
    terrain_level_point {
      sim_grid_pos_x: 1685808
      sim_grid_pos_y: 1389186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685857.88
      sim_grid_pos_y: 1389234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685971.5
      sim_grid_pos_y: 1389328.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.68605e+06
      sim_grid_pos_y: 1389468.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686070.5
      sim_grid_pos_y: 1389573.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686072.25
      sim_grid_pos_y: 1389651.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685992.38
      sim_grid_pos_y: 1.38978e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1685792.12
      sim_grid_pos_y: 1389776.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685667.62
      sim_grid_pos_y: 1389750.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685531.12
      sim_grid_pos_y: 1389701.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685418.38
      sim_grid_pos_y: 1389626.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685368.38
      sim_grid_pos_y: 1389475.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685362.75
      sim_grid_pos_y: 1389365.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685391.25
      sim_grid_pos_y: 1389221.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685478.62
      sim_grid_pos_y: 1389128
    }
    terrain_level_point {
      sim_grid_pos_x: 1685619.25
      sim_grid_pos_y: 1389018.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1685762
      sim_grid_pos_y: 1389061.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685824.5
      sim_grid_pos_y: 1389173.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685871.5
      sim_grid_pos_y: 1389219.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685987.5
      sim_grid_pos_y: 1389315.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686069.5
      sim_grid_pos_y: 1389461.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1686090.88
      sim_grid_pos_y: 1389571.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1686092.88
      sim_grid_pos_y: 1389656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1686003.62
      sim_grid_pos_y: 1389800.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1685789.88
      sim_grid_pos_y: 1389796.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685662.12
      sim_grid_pos_y: 1389770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1685521.88
      sim_grid_pos_y: 1389720.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685401.12
      sim_grid_pos_y: 1389639.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685348
      sim_grid_pos_y: 1389479.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685342.12
      sim_grid_pos_y: 1389364
    }
    terrain_level_point {
      sim_grid_pos_x: 1685372.25
      sim_grid_pos_y: 1389211.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685464.75
      sim_grid_pos_y: 1389112.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1685616.5
      sim_grid_pos_y: 1388994.75
    }
  }
}
terrain_level_data {
  terrain_level: 370
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1686700.5
      sim_grid_pos_y: 1389973
    }
    terrain_level_point {
      sim_grid_pos_x: 1686798.62
      sim_grid_pos_y: 1390136
    }
    terrain_level_point {
      sim_grid_pos_x: 1686775.25
      sim_grid_pos_y: 1390217.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1686743.12
      sim_grid_pos_y: 1390342.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686613.5
      sim_grid_pos_y: 1390332.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686526.38
      sim_grid_pos_y: 1390261.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686481.25
      sim_grid_pos_y: 1390196.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1686369.25
      sim_grid_pos_y: 1390176.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686259.88
      sim_grid_pos_y: 1390198.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686228.75
      sim_grid_pos_y: 1390116
    }
    terrain_level_point {
      sim_grid_pos_x: 1686246.38
      sim_grid_pos_y: 1390035.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686359.38
      sim_grid_pos_y: 1389946.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1686502.38
      sim_grid_pos_y: 1389909.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686618.38
      sim_grid_pos_y: 1389909.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1686632.38
      sim_grid_pos_y: 1389868.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1686731.62
      sim_grid_pos_y: 1389945.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1686843
      sim_grid_pos_y: 1390130.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686814.88
      sim_grid_pos_y: 1390228.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1686774.38
      sim_grid_pos_y: 1390385.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1686597.5
      sim_grid_pos_y: 1390372.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686496
      sim_grid_pos_y: 1390289.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1686457.25
      sim_grid_pos_y: 1390234
    }
    terrain_level_point {
      sim_grid_pos_x: 1686369.75
      sim_grid_pos_y: 1390218.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686233.88
      sim_grid_pos_y: 1390246.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686186.12
      sim_grid_pos_y: 1390119.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686209.38
      sim_grid_pos_y: 1390012.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1686340.75
      sim_grid_pos_y: 1389909
    }
    terrain_level_point {
      sim_grid_pos_x: 1686497.12
      sim_grid_pos_y: 1389868.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1686646.5
      sim_grid_pos_y: 1389827.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1686762.88
      sim_grid_pos_y: 1389917.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1686887.38
      sim_grid_pos_y: 1390124.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1686854.38
      sim_grid_pos_y: 1390239.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686805.5
      sim_grid_pos_y: 1390429.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686581.5
      sim_grid_pos_y: 1390412.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686465.62
      sim_grid_pos_y: 1390317.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1686433.38
      sim_grid_pos_y: 1390271.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686370.25
      sim_grid_pos_y: 1390259.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686207.88
      sim_grid_pos_y: 1390293.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686143.38
      sim_grid_pos_y: 1390122.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1686172.5
      sim_grid_pos_y: 1389989.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686322
      sim_grid_pos_y: 1389871.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1686492
      sim_grid_pos_y: 1389827.12
    }
  }
}
terrain_level_data {
  terrain_level: 336
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1685282.75
      sim_grid_pos_y: 1389576
    }
    terrain_level_point {
      sim_grid_pos_x: 1685222.12
      sim_grid_pos_y: 1389515.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685237.75
      sim_grid_pos_y: 1389447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685148.25
      sim_grid_pos_y: 1389374
    }
    terrain_level_point {
      sim_grid_pos_x: 1685064.12
      sim_grid_pos_y: 1389470.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685052
      sim_grid_pos_y: 1389539.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685072.12
      sim_grid_pos_y: 1389612.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685195.75
      sim_grid_pos_y: 1389690.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1685145.88
      sim_grid_pos_y: 1389345.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685044.88
      sim_grid_pos_y: 1389460.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685031
      sim_grid_pos_y: 1389540.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685054.38
      sim_grid_pos_y: 1389625.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685200.75
      sim_grid_pos_y: 1389718.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685309.88
      sim_grid_pos_y: 1389574
    }
    terrain_level_point {
      sim_grid_pos_x: 1685244.62
      sim_grid_pos_y: 1389509.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685260.5
      sim_grid_pos_y: 1389439.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1685143.5
      sim_grid_pos_y: 1389317
    }
    terrain_level_point {
      sim_grid_pos_x: 1685025.62
      sim_grid_pos_y: 1389451.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.68501e+06
      sim_grid_pos_y: 1389541.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685036.75
      sim_grid_pos_y: 1389638.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685205.75
      sim_grid_pos_y: 1389745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685337
      sim_grid_pos_y: 1389572.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685267.12
      sim_grid_pos_y: 1389502.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685283.38
      sim_grid_pos_y: 1389431.88
    }
  }
}
terrain_level_data {
  terrain_level: 295
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1685268.62
      sim_grid_pos_y: 1389821.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685339.25
      sim_grid_pos_y: 1389853.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685534.5
      sim_grid_pos_y: 1390044.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685716.12
      sim_grid_pos_y: 1390134.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685885.88
      sim_grid_pos_y: 1390222.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685960.25
      sim_grid_pos_y: 1390295.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685833.62
      sim_grid_pos_y: 1390462.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685705.38
      sim_grid_pos_y: 1390463.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685504.25
      sim_grid_pos_y: 1390429.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685364.25
      sim_grid_pos_y: 1390276.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685231.38
      sim_grid_pos_y: 1390237.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685084.25
      sim_grid_pos_y: 1390083.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685137.38
      sim_grid_pos_y: 1389871.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1685356.88
      sim_grid_pos_y: 1389828
    }
    terrain_level_point {
      sim_grid_pos_x: 1685552.5
      sim_grid_pos_y: 1390019.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.68573e+06
      sim_grid_pos_y: 1390107.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685904.12
      sim_grid_pos_y: 1390197.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1686001.12
      sim_grid_pos_y: 1390292.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685849
      sim_grid_pos_y: 1390492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1685703
      sim_grid_pos_y: 1390494.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685488.75
      sim_grid_pos_y: 1390458
    }
    terrain_level_point {
      sim_grid_pos_x: 1685347.38
      sim_grid_pos_y: 1390303.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685214.75
      sim_grid_pos_y: 1390264.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685050.25
      sim_grid_pos_y: 1390092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685111.5
      sim_grid_pos_y: 1389848.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1685269.62
      sim_grid_pos_y: 1389788.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1685374.38
      sim_grid_pos_y: 1389802.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685570.5
      sim_grid_pos_y: 1389993.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1685743.88
      sim_grid_pos_y: 1390079.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1685922.38
      sim_grid_pos_y: 1390171.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1686041.88
      sim_grid_pos_y: 1390289.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685864.38
      sim_grid_pos_y: 1390523.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685700.5
      sim_grid_pos_y: 1390525.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1685473.12
      sim_grid_pos_y: 1390486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1685330.5
      sim_grid_pos_y: 1390330.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685198.25
      sim_grid_pos_y: 1390291.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685016.25
      sim_grid_pos_y: 1390101.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1685085.5
      sim_grid_pos_y: 1389825.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1685270.75
      sim_grid_pos_y: 1389755.38
    }
  }
}
