terrain_level_data {
  terrain_level: 1225
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2388407.5
      sim_grid_pos_y: 971893.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2388405.5
      sim_grid_pos_y: 972086.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2388696.5
      sim_grid_pos_y: 972133.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2389069.5
      sim_grid_pos_y: 972345.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389138
      sim_grid_pos_y: 972147.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2389098.75
      sim_grid_pos_y: 971947.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2389060.5
      sim_grid_pos_y: 971837.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2388985.25
      sim_grid_pos_y: 971713.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2388884.75
      sim_grid_pos_y: 971705.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2388730.25
      sim_grid_pos_y: 971710.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2388887.25
      sim_grid_pos_y: 971602.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2388701.5
      sim_grid_pos_y: 971609.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2388305.5
      sim_grid_pos_y: 971833.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2388302
      sim_grid_pos_y: 972173.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2388662
      sim_grid_pos_y: 972231.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2389126
      sim_grid_pos_y: 972495.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389244
      sim_grid_pos_y: 972154.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2389198
      sim_grid_pos_y: 971920.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2389153.75
      sim_grid_pos_y: 971793.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389045.75
      sim_grid_pos_y: 971615.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2388889.75
      sim_grid_pos_y: 971500.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2388673
      sim_grid_pos_y: 971507.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2388203.75
      sim_grid_pos_y: 971773.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2388198.75
      sim_grid_pos_y: 972260.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2388627.25
      sim_grid_pos_y: 972330.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2389182.75
      sim_grid_pos_y: 972645.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389349.75
      sim_grid_pos_y: 972162
    }
    terrain_level_point {
      sim_grid_pos_x: 2389297.25
      sim_grid_pos_y: 971894.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2389247
      sim_grid_pos_y: 971749.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389106
      sim_grid_pos_y: 971518
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2388892.25
      sim_grid_pos_y: 971397.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2388644.25
      sim_grid_pos_y: 971405.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2388101.75
      sim_grid_pos_y: 971713.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2388095.25
      sim_grid_pos_y: 972347.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2388592.75
      sim_grid_pos_y: 972428.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2389239.25
      sim_grid_pos_y: 972795.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2389455.75
      sim_grid_pos_y: 972169.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2389396.5
      sim_grid_pos_y: 971867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2389340.25
      sim_grid_pos_y: 971705.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2389166.5
      sim_grid_pos_y: 971420.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2388894.75
      sim_grid_pos_y: 971294.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2388615.75
      sim_grid_pos_y: 971304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2387999.75
      sim_grid_pos_y: 971653.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2387991.75
      sim_grid_pos_y: 972434.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2388558
      sim_grid_pos_y: 972526.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2389296
      sim_grid_pos_y: 972945.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2389561.75
      sim_grid_pos_y: 972176.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2389495.5
      sim_grid_pos_y: 971840.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2389433.5
      sim_grid_pos_y: 971661.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2389226.75
      sim_grid_pos_y: 971322.188
    }
  }
}
terrain_level_data {
  terrain_level: 1032
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2389442.75
      sim_grid_pos_y: 970508.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2389623.75
      sim_grid_pos_y: 970487.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2389633.25
      sim_grid_pos_y: 970805.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2389460.75
      sim_grid_pos_y: 970767.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2389686.5
      sim_grid_pos_y: 970869.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2389412.25
      sim_grid_pos_y: 970809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2389388.25
      sim_grid_pos_y: 970463.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2389673.25
      sim_grid_pos_y: 970429.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2389739.75
      sim_grid_pos_y: 970933.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2389363.75
      sim_grid_pos_y: 970851.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389333.75
      sim_grid_pos_y: 970418.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2389723
      sim_grid_pos_y: 970371.938
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2389792.75
      sim_grid_pos_y: 970998
    }
    terrain_level_point {
      sim_grid_pos_x: 2389315.25
      sim_grid_pos_y: 970893.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2389279.25
      sim_grid_pos_y: 970373.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2389772.5
      sim_grid_pos_y: 970314.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2389846
      sim_grid_pos_y: 971062.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2389266.75
      sim_grid_pos_y: 970935.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2389224.75
      sim_grid_pos_y: 970328.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2389822
      sim_grid_pos_y: 970256.875
    }
  }
}
terrain_level_data {
  terrain_level: 1280
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2.38793e+06
      sim_grid_pos_y: 971886.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2387983
      sim_grid_pos_y: 972235
    }
    terrain_level_point {
      sim_grid_pos_x: 2388336.25
      sim_grid_pos_y: 972136.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2388257.75
      sim_grid_pos_y: 971778.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2388295.75
      sim_grid_pos_y: 971711.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2387872.75
      sim_grid_pos_y: 971851.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2387941
      sim_grid_pos_y: 972299.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2388396.75
      sim_grid_pos_y: 972173.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2388333.75
      sim_grid_pos_y: 971645.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2387815.5
      sim_grid_pos_y: 971816.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2387899
      sim_grid_pos_y: 972364.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2388457
      sim_grid_pos_y: 972209.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2388371.75
      sim_grid_pos_y: 971578.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2387758.25
      sim_grid_pos_y: 971781
    }
    terrain_level_point {
      sim_grid_pos_x: 2387857
      sim_grid_pos_y: 972429.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2388517.5
      sim_grid_pos_y: 972245.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2388409.5
      sim_grid_pos_y: 971512.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2387701.25
      sim_grid_pos_y: 971745.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2387815
      sim_grid_pos_y: 972494.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2388578
      sim_grid_pos_y: 972282.188
    }
  }
}
terrain_level_data {
  terrain_level: 600
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2386927
      sim_grid_pos_y: 977886.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2386821.5
      sim_grid_pos_y: 977929.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2386654.5
      sim_grid_pos_y: 977938.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2386553.75
      sim_grid_pos_y: 977940.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2386454
      sim_grid_pos_y: 977914.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2386449.5
      sim_grid_pos_y: 977711.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2386719.5
      sim_grid_pos_y: 977649
    }
    terrain_level_point {
      sim_grid_pos_x: 2386947.75
      sim_grid_pos_y: 977720.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2.38706e+06
      sim_grid_pos_y: 977647.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2387021.25
      sim_grid_pos_y: 977959.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2386844
      sim_grid_pos_y: 978030.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2386658.25
      sim_grid_pos_y: 978041.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2386541.75
      sim_grid_pos_y: 978043
    }
    terrain_level_point {
      sim_grid_pos_x: 2386353.25
      sim_grid_pos_y: 977994.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2386345
      sim_grid_pos_y: 977630.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2386723.5
      sim_grid_pos_y: 977542.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2387172.25
      sim_grid_pos_y: 977575.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2387115.75
      sim_grid_pos_y: 978031.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2386866.5
      sim_grid_pos_y: 978132.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2386661.75
      sim_grid_pos_y: 978143.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2386529.5
      sim_grid_pos_y: 978145.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2386252.5
      sim_grid_pos_y: 978074.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2386240.75
      sim_grid_pos_y: 977549.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2386727.5
      sim_grid_pos_y: 977436.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2387284.75
      sim_grid_pos_y: 977503.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2.38721e+06
      sim_grid_pos_y: 978104.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2386889.25
      sim_grid_pos_y: 978233.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2386665.5
      sim_grid_pos_y: 978246.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2386517.5
      sim_grid_pos_y: 978248.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2386152
      sim_grid_pos_y: 978154.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2386136.25
      sim_grid_pos_y: 977468.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2386731.25
      sim_grid_pos_y: 977330.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2387397
      sim_grid_pos_y: 977430.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2387304.25
      sim_grid_pos_y: 978176.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2386911.75
      sim_grid_pos_y: 978335.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2386669
      sim_grid_pos_y: 978348.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2386505.25
      sim_grid_pos_y: 978351.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2386051.25
      sim_grid_pos_y: 978234.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2386032
      sim_grid_pos_y: 977387.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2386735.25
      sim_grid_pos_y: 977224.312
    }
  }
}
