terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 579890.812
      sim_grid_pos_y: 2229416.25
    }
    terrain_level_point {
      sim_grid_pos_x: 582476.188
      sim_grid_pos_y: 2227161.5
    }
    terrain_level_point {
      sim_grid_pos_x: 580583.875
      sim_grid_pos_y: 2225063.25
    }
    terrain_level_point {
      sim_grid_pos_x: 580092.5
      sim_grid_pos_y: 2225388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 579025
      sim_grid_pos_y: 2225631.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573472.312
      sim_grid_pos_y: 2225770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573207.188
      sim_grid_pos_y: 2226333.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572745.5
      sim_grid_pos_y: 2226546.75
    }
    terrain_level_point {
      sim_grid_pos_x: 572201.375
      sim_grid_pos_y: 2226377.75
    }
    terrain_level_point {
      sim_grid_pos_x: 569186.5
      sim_grid_pos_y: 2223809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 564475.188
      sim_grid_pos_y: 2223798.25
    }
    terrain_level_point {
      sim_grid_pos_x: 559357.875
      sim_grid_pos_y: 2229420.5
    }
    terrain_level_point {
      sim_grid_pos_x: 558084.312
      sim_grid_pos_y: 2229665.5
    }
    terrain_level_point {
      sim_grid_pos_x: 556401.625
      sim_grid_pos_y: 2231395
    }
    terrain_level_point {
      sim_grid_pos_x: 556384.188
      sim_grid_pos_y: 2.23345e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 557470.375
      sim_grid_pos_y: 2234580.75
    }
    terrain_level_point {
      sim_grid_pos_x: 562224.75
      sim_grid_pos_y: 2234464
    }
    terrain_level_point {
      sim_grid_pos_x: 562317.375
      sim_grid_pos_y: 2234865
    }
    terrain_level_point {
      sim_grid_pos_x: 565555.438
      sim_grid_pos_y: 2234822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 566347.625
      sim_grid_pos_y: 2231470.5
    }
    terrain_level_point {
      sim_grid_pos_x: 566670.5
      sim_grid_pos_y: 2231491.25
    }
    terrain_level_point {
      sim_grid_pos_x: 566373.5
      sim_grid_pos_y: 2234538.75
    }
    terrain_level_point {
      sim_grid_pos_x: 567240.188
      sim_grid_pos_y: 2234482.75
    }
    terrain_level_point {
      sim_grid_pos_x: 567746.062
      sim_grid_pos_y: 2235614
    }
    terrain_level_point {
      sim_grid_pos_x: 568134
      sim_grid_pos_y: 2235882.5
    }
    terrain_level_point {
      sim_grid_pos_x: 568138.812
      sim_grid_pos_y: 2237013
    }
    terrain_level_point {
      sim_grid_pos_x: 569518.5
      sim_grid_pos_y: 2236951
    }
    terrain_level_point {
      sim_grid_pos_x: 570181.5
      sim_grid_pos_y: 2235424.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572706.812
      sim_grid_pos_y: 2236512.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573313.75
      sim_grid_pos_y: 2237184.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573991.5
      sim_grid_pos_y: 2237472.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574458.5
      sim_grid_pos_y: 2236370.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571702.438
      sim_grid_pos_y: 2235221.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571426
      sim_grid_pos_y: 2234375.75
    }
    terrain_level_point {
      sim_grid_pos_x: 571155.75
      sim_grid_pos_y: 2233693.25
    }
    terrain_level_point {
      sim_grid_pos_x: 570464.438
      sim_grid_pos_y: 2232183
    }
    terrain_level_point {
      sim_grid_pos_x: 571592.375
      sim_grid_pos_y: 2231647
    }
    terrain_level_point {
      sim_grid_pos_x: 572359.312
      sim_grid_pos_y: 2233164.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573556.562
      sim_grid_pos_y: 2233531.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574060.125
      sim_grid_pos_y: 2233441.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574289.312
      sim_grid_pos_y: 2232338.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574447.562
      sim_grid_pos_y: 2231966
    }
    terrain_level_point {
      sim_grid_pos_x: 573791.5
      sim_grid_pos_y: 2231255.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574133.5
      sim_grid_pos_y: 2230461.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 564466.125
      sim_grid_pos_y: 2223777.75
    }
    terrain_level_point {
      sim_grid_pos_x: 559347.312
      sim_grid_pos_y: 2229401.75
    }
    terrain_level_point {
      sim_grid_pos_x: 558074.125
      sim_grid_pos_y: 2229646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 556381.188
      sim_grid_pos_y: 2231386.5
    }
    terrain_level_point {
      sim_grid_pos_x: 556363.562
      sim_grid_pos_y: 2233458.25
    }
    terrain_level_point {
      sim_grid_pos_x: 557461.875
      sim_grid_pos_y: 2234601.5
    }
    terrain_level_point {
      sim_grid_pos_x: 562208.562
      sim_grid_pos_y: 2234485
    }
    terrain_level_point {
      sim_grid_pos_x: 562301.125
      sim_grid_pos_y: 2234885.75
    }
    terrain_level_point {
      sim_grid_pos_x: 565571.75
      sim_grid_pos_y: 2234842.5
    }
    terrain_level_point {
      sim_grid_pos_x: 566363.625
      sim_grid_pos_y: 2231492
    }
    terrain_level_point {
      sim_grid_pos_x: 566648
      sim_grid_pos_y: 2231510.25
    }
    terrain_level_point {
      sim_grid_pos_x: 566350.75
      sim_grid_pos_y: 2234560.75
    }
    terrain_level_point {
      sim_grid_pos_x: 567227.25
      sim_grid_pos_y: 2234504.25
    }
    terrain_level_point {
      sim_grid_pos_x: 567729.688
      sim_grid_pos_y: 2235627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 568113.562
      sim_grid_pos_y: 2235893.25
    }
    terrain_level_point {
      sim_grid_pos_x: 568118.438
      sim_grid_pos_y: 2237034.5
    }
    terrain_level_point {
      sim_grid_pos_x: 569532.25
      sim_grid_pos_y: 2236970.75
    }
    terrain_level_point {
      sim_grid_pos_x: 570192.125
      sim_grid_pos_y: 2235451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572694.562
      sim_grid_pos_y: 2236529.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573301.562
      sim_grid_pos_y: 2237201.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574002.375
      sim_grid_pos_y: 2237499.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574485.438
      sim_grid_pos_y: 2236359.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571719
      sim_grid_pos_y: 2235206.25
    }
    terrain_level_point {
      sim_grid_pos_x: 571445.312
      sim_grid_pos_y: 2234368.75
    }
    terrain_level_point {
      sim_grid_pos_x: 571174.562
      sim_grid_pos_y: 2233685.25
    }
    terrain_level_point {
      sim_grid_pos_x: 570491.5
      sim_grid_pos_y: 2232192.75
    }
    terrain_level_point {
      sim_grid_pos_x: 571583.125
      sim_grid_pos_y: 2231674.25
    }
    terrain_level_point {
      sim_grid_pos_x: 572344.938
      sim_grid_pos_y: 2233181.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573555.312
      sim_grid_pos_y: 2233552.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574077.375
      sim_grid_pos_y: 2233459
    }
    terrain_level_point {
      sim_grid_pos_x: 574309
      sim_grid_pos_y: 2232344.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574471.625
      sim_grid_pos_y: 2231962
    }
    terrain_level_point {
      sim_grid_pos_x: 573815.562
      sim_grid_pos_y: 2231251.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574148
      sim_grid_pos_y: 2230479.5
    }
    terrain_level_point {
      sim_grid_pos_x: 579900.062
      sim_grid_pos_y: 2229435.5
    }
    terrain_level_point {
      sim_grid_pos_x: 582505.375
      sim_grid_pos_y: 2227163.25
    }
    terrain_level_point {
      sim_grid_pos_x: 580587.312
      sim_grid_pos_y: 2225036.5
    }
    terrain_level_point {
      sim_grid_pos_x: 580084.25
      sim_grid_pos_y: 2225369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 579022.438
      sim_grid_pos_y: 2225611.25
    }
    terrain_level_point {
      sim_grid_pos_x: 573459.125
      sim_grid_pos_y: 2225750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573191.75
      sim_grid_pos_y: 2226318
    }
    terrain_level_point {
      sim_grid_pos_x: 572744.062
      sim_grid_pos_y: 2226525
    }
    terrain_level_point {
      sim_grid_pos_x: 572211.5
      sim_grid_pos_y: 2226359.5
    }
    terrain_level_point {
      sim_grid_pos_x: 569194.062
      sim_grid_pos_y: 2223789
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 564457.062
      sim_grid_pos_y: 2223757
    }
    terrain_level_point {
      sim_grid_pos_x: 559336.75
      sim_grid_pos_y: 2229382.75
    }
    terrain_level_point {
      sim_grid_pos_x: 558063.875
      sim_grid_pos_y: 2229627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 556360.75
      sim_grid_pos_y: 2231378.25
    }
    terrain_level_point {
      sim_grid_pos_x: 556343
      sim_grid_pos_y: 2233466.25
    }
    terrain_level_point {
      sim_grid_pos_x: 557453.312
      sim_grid_pos_y: 2234622
    }
    terrain_level_point {
      sim_grid_pos_x: 562192.312
      sim_grid_pos_y: 2234505.75
    }
    terrain_level_point {
      sim_grid_pos_x: 562284.875
      sim_grid_pos_y: 2234906.5
    }
    terrain_level_point {
      sim_grid_pos_x: 565588
      sim_grid_pos_y: 2234862.75
    }
    terrain_level_point {
      sim_grid_pos_x: 566379.562
      sim_grid_pos_y: 2231513.5
    }
    terrain_level_point {
      sim_grid_pos_x: 566625.562
      sim_grid_pos_y: 2231529.25
    }
    terrain_level_point {
      sim_grid_pos_x: 566328
      sim_grid_pos_y: 2234582.75
    }
    terrain_level_point {
      sim_grid_pos_x: 567214.375
      sim_grid_pos_y: 2234525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 567713.312
      sim_grid_pos_y: 2235641.25
    }
    terrain_level_point {
      sim_grid_pos_x: 568093.125
      sim_grid_pos_y: 2235904
    }
    terrain_level_point {
      sim_grid_pos_x: 568098
      sim_grid_pos_y: 2237056
    }
    terrain_level_point {
      sim_grid_pos_x: 569545.938
      sim_grid_pos_y: 2236990.75
    }
    terrain_level_point {
      sim_grid_pos_x: 570202.812
      sim_grid_pos_y: 2235478.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572682.375
      sim_grid_pos_y: 2236546.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573289.375
      sim_grid_pos_y: 2237219
    }
    terrain_level_point {
      sim_grid_pos_x: 574013.25
      sim_grid_pos_y: 2237526.5
    }
    terrain_level_point {
      sim_grid_pos_x: 574512.375
      sim_grid_pos_y: 2236348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571735.562
      sim_grid_pos_y: 2235190.75
    }
    terrain_level_point {
      sim_grid_pos_x: 571464.625
      sim_grid_pos_y: 2234361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 571193.438
      sim_grid_pos_y: 2233677.25
    }
    terrain_level_point {
      sim_grid_pos_x: 570518.562
      sim_grid_pos_y: 2232202.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571573.812
      sim_grid_pos_y: 2231701.25
    }
    terrain_level_point {
      sim_grid_pos_x: 572330.562
      sim_grid_pos_y: 2233198.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573554
      sim_grid_pos_y: 2233573.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574094.625
      sim_grid_pos_y: 2233476.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574328.625
      sim_grid_pos_y: 2232351
    }
    terrain_level_point {
      sim_grid_pos_x: 574495.688
      sim_grid_pos_y: 2231957.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573839.688
      sim_grid_pos_y: 2231247
    }
    terrain_level_point {
      sim_grid_pos_x: 574162.5
      sim_grid_pos_y: 2230497.75
    }
    terrain_level_point {
      sim_grid_pos_x: 579909.25
      sim_grid_pos_y: 2229454.5
    }
    terrain_level_point {
      sim_grid_pos_x: 582534.562
      sim_grid_pos_y: 2227165
    }
    terrain_level_point {
      sim_grid_pos_x: 580590.688
      sim_grid_pos_y: 2225009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 580076.062
      sim_grid_pos_y: 2225350.25
    }
    terrain_level_point {
      sim_grid_pos_x: 579019.875
      sim_grid_pos_y: 2225591
    }
    terrain_level_point {
      sim_grid_pos_x: 573446
      sim_grid_pos_y: 2225730.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573176.438
      sim_grid_pos_y: 2226302.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572742.625
      sim_grid_pos_y: 2226503
    }
    terrain_level_point {
      sim_grid_pos_x: 572221.562
      sim_grid_pos_y: 2226341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 569201.688
      sim_grid_pos_y: 2223768.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 564448.062
      sim_grid_pos_y: 2223736.5
    }
    terrain_level_point {
      sim_grid_pos_x: 559326.188
      sim_grid_pos_y: 2229364
    }
    terrain_level_point {
      sim_grid_pos_x: 558053.688
      sim_grid_pos_y: 2229608.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556340.312
      sim_grid_pos_y: 2231369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556322.438
      sim_grid_pos_y: 2233474.5
    }
    terrain_level_point {
      sim_grid_pos_x: 557444.812
      sim_grid_pos_y: 2234642.75
    }
    terrain_level_point {
      sim_grid_pos_x: 562176.125
      sim_grid_pos_y: 2234526.75
    }
    terrain_level_point {
      sim_grid_pos_x: 562268.562
      sim_grid_pos_y: 2234927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 565604.312
      sim_grid_pos_y: 2234883.25
    }
    terrain_level_point {
      sim_grid_pos_x: 566395.562
      sim_grid_pos_y: 2231535
    }
    terrain_level_point {
      sim_grid_pos_x: 566603.125
      sim_grid_pos_y: 2231548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 566305.25
      sim_grid_pos_y: 2234604.75
    }
    terrain_level_point {
      sim_grid_pos_x: 567201.5
      sim_grid_pos_y: 2234547
    }
    terrain_level_point {
      sim_grid_pos_x: 567696.938
      sim_grid_pos_y: 2235654.75
    }
    terrain_level_point {
      sim_grid_pos_x: 568072.625
      sim_grid_pos_y: 2235914.75
    }
    terrain_level_point {
      sim_grid_pos_x: 568077.562
      sim_grid_pos_y: 2237077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 569559.625
      sim_grid_pos_y: 2237010.75
    }
    terrain_level_point {
      sim_grid_pos_x: 570213.438
      sim_grid_pos_y: 2235505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 572670.188
      sim_grid_pos_y: 2236563.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573277.188
      sim_grid_pos_y: 2237236
    }
    terrain_level_point {
      sim_grid_pos_x: 574024.125
      sim_grid_pos_y: 2237553.5
    }
    terrain_level_point {
      sim_grid_pos_x: 574539.25
      sim_grid_pos_y: 2236337.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571752.125
      sim_grid_pos_y: 2235175.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571483.938
      sim_grid_pos_y: 2234355
    }
    terrain_level_point {
      sim_grid_pos_x: 571212.312
      sim_grid_pos_y: 2233669.25
    }
    terrain_level_point {
      sim_grid_pos_x: 570545.625
      sim_grid_pos_y: 2232212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571564.562
      sim_grid_pos_y: 2231728.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572316.25
      sim_grid_pos_y: 2233215.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573552.75
      sim_grid_pos_y: 2233594.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574111.875
      sim_grid_pos_y: 2233494.5
    }
    terrain_level_point {
      sim_grid_pos_x: 574348.312
      sim_grid_pos_y: 2232357
    }
    terrain_level_point {
      sim_grid_pos_x: 574519.75
      sim_grid_pos_y: 2231953.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573863.812
      sim_grid_pos_y: 2231243
    }
    terrain_level_point {
      sim_grid_pos_x: 574176.938
      sim_grid_pos_y: 2230516
    }
    terrain_level_point {
      sim_grid_pos_x: 579918.5
      sim_grid_pos_y: 2229473.75
    }
    terrain_level_point {
      sim_grid_pos_x: 582563.75
      sim_grid_pos_y: 2227166.75
    }
    terrain_level_point {
      sim_grid_pos_x: 580594.125
      sim_grid_pos_y: 2224982.75
    }
    terrain_level_point {
      sim_grid_pos_x: 580067.875
      sim_grid_pos_y: 2225331
    }
    terrain_level_point {
      sim_grid_pos_x: 579017.312
      sim_grid_pos_y: 2225570.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573432.812
      sim_grid_pos_y: 2225710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 573161.062
      sim_grid_pos_y: 2226287
    }
    terrain_level_point {
      sim_grid_pos_x: 572741.188
      sim_grid_pos_y: 2226481
    }
    terrain_level_point {
      sim_grid_pos_x: 572231.625
      sim_grid_pos_y: 2226322.75
    }
    terrain_level_point {
      sim_grid_pos_x: 569209.25
      sim_grid_pos_y: 2223748
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 564439
      sim_grid_pos_y: 2223716
    }
    terrain_level_point {
      sim_grid_pos_x: 559315.562
      sim_grid_pos_y: 2229345
    }
    terrain_level_point {
      sim_grid_pos_x: 558043.5
      sim_grid_pos_y: 2229589.75
    }
    terrain_level_point {
      sim_grid_pos_x: 556319.875
      sim_grid_pos_y: 2231361.25
    }
    terrain_level_point {
      sim_grid_pos_x: 556301.875
      sim_grid_pos_y: 2233482.75
    }
    terrain_level_point {
      sim_grid_pos_x: 557436.25
      sim_grid_pos_y: 2234663.5
    }
    terrain_level_point {
      sim_grid_pos_x: 562159.875
      sim_grid_pos_y: 2234547.75
    }
    terrain_level_point {
      sim_grid_pos_x: 562252.312
      sim_grid_pos_y: 2234948
    }
    terrain_level_point {
      sim_grid_pos_x: 565620.562
      sim_grid_pos_y: 2234903.5
    }
    terrain_level_point {
      sim_grid_pos_x: 566411.562
      sim_grid_pos_y: 2231556.75
    }
    terrain_level_point {
      sim_grid_pos_x: 566580.625
      sim_grid_pos_y: 2231567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 566282.5
      sim_grid_pos_y: 2234626.75
    }
    terrain_level_point {
      sim_grid_pos_x: 567188.562
      sim_grid_pos_y: 2234568.25
    }
    terrain_level_point {
      sim_grid_pos_x: 567680.562
      sim_grid_pos_y: 2235668.25
    }
    terrain_level_point {
      sim_grid_pos_x: 568052.188
      sim_grid_pos_y: 2235925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 568057.188
      sim_grid_pos_y: 2237098.75
    }
    terrain_level_point {
      sim_grid_pos_x: 569573.375
      sim_grid_pos_y: 2237030.5
    }
    terrain_level_point {
      sim_grid_pos_x: 570224.125
      sim_grid_pos_y: 2235532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 572657.938
      sim_grid_pos_y: 2236580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 573265
      sim_grid_pos_y: 2237253.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574035
      sim_grid_pos_y: 2237580.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574566.188
      sim_grid_pos_y: 2236326.5
    }
    terrain_level_point {
      sim_grid_pos_x: 571768.75
      sim_grid_pos_y: 2235160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 571503.188
      sim_grid_pos_y: 2234348
    }
    terrain_level_point {
      sim_grid_pos_x: 571231.188
      sim_grid_pos_y: 2233661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 570572.688
      sim_grid_pos_y: 2232222.25
    }
    terrain_level_point {
      sim_grid_pos_x: 571555.312
      sim_grid_pos_y: 2231755.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572301.875
      sim_grid_pos_y: 2233232.75
    }
    terrain_level_point {
      sim_grid_pos_x: 573551.5
      sim_grid_pos_y: 2233615.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574129.125
      sim_grid_pos_y: 2233512.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574367.938
      sim_grid_pos_y: 2232363.25
    }
    terrain_level_point {
      sim_grid_pos_x: 574543.812
      sim_grid_pos_y: 2231949.25
    }
    terrain_level_point {
      sim_grid_pos_x: 573887.875
      sim_grid_pos_y: 2231238.75
    }
    terrain_level_point {
      sim_grid_pos_x: 574191.438
      sim_grid_pos_y: 2230534.25
    }
    terrain_level_point {
      sim_grid_pos_x: 579927.688
      sim_grid_pos_y: 2229493
    }
    terrain_level_point {
      sim_grid_pos_x: 582592.938
      sim_grid_pos_y: 2227168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 580597.5
      sim_grid_pos_y: 2224956
    }
    terrain_level_point {
      sim_grid_pos_x: 580059.688
      sim_grid_pos_y: 2225311.75
    }
    terrain_level_point {
      sim_grid_pos_x: 579014.75
      sim_grid_pos_y: 2.22555e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 573419.688
      sim_grid_pos_y: 2.22569e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 573145.688
      sim_grid_pos_y: 2226271.5
    }
    terrain_level_point {
      sim_grid_pos_x: 572739.75
      sim_grid_pos_y: 2226459.25
    }
    terrain_level_point {
      sim_grid_pos_x: 572241.75
      sim_grid_pos_y: 2226304.5
    }
    terrain_level_point {
      sim_grid_pos_x: 569216.812
      sim_grid_pos_y: 2223727.5
    }
  }
}
