terrain_level_data {
  terrain_level: 160
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2354855.5
      sim_grid_pos_y: 2000252
    }
    terrain_level_point {
      sim_grid_pos_x: 2354996.5
      sim_grid_pos_y: 2000368.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354866.25
      sim_grid_pos_y: 2000477.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2354895.25
      sim_grid_pos_y: 2000567.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2355116
      sim_grid_pos_y: 2000633.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355055
      sim_grid_pos_y: 2000757.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35515e+06
      sim_grid_pos_y: 2000840.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355309
      sim_grid_pos_y: 2000839.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2355522.75
      sim_grid_pos_y: 2001043.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2355603
      sim_grid_pos_y: 2000864.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2355594.5
      sim_grid_pos_y: 2000745.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2355318.5
      sim_grid_pos_y: 2000490.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355181.75
      sim_grid_pos_y: 2000292
    }
    terrain_level_point {
      sim_grid_pos_x: 2354966.5
      sim_grid_pos_y: 2000110.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2354951.5
      sim_grid_pos_y: 1999963.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354713
      sim_grid_pos_y: 2000267.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2354836.25
      sim_grid_pos_y: 2000368.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354747.5
      sim_grid_pos_y: 2000443.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354814.25
      sim_grid_pos_y: 2000650.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2354970.5
      sim_grid_pos_y: 2000697.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354928
      sim_grid_pos_y: 2000782.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2355111.75
      sim_grid_pos_y: 2000942.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355268
      sim_grid_pos_y: 2000942.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2355557
      sim_grid_pos_y: 2001217.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355707
      sim_grid_pos_y: 2000882.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2355693.75
      sim_grid_pos_y: 2000698.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355396.5
      sim_grid_pos_y: 2000422.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2355258.25
      sim_grid_pos_y: 2000222.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2354936.25
      sim_grid_pos_y: 1999817
    }
    terrain_level_point {
      sim_grid_pos_x: 2354570.5
      sim_grid_pos_y: 2000282.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354675.75
      sim_grid_pos_y: 2000369.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354628.75
      sim_grid_pos_y: 2000409
    }
    terrain_level_point {
      sim_grid_pos_x: 2354733
      sim_grid_pos_y: 2000733.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354824.75
      sim_grid_pos_y: 2000760.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354801.25
      sim_grid_pos_y: 2000808.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2355073.25
      sim_grid_pos_y: 2001045.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2355227
      sim_grid_pos_y: 2001045
    }
    terrain_level_point {
      sim_grid_pos_x: 2355591.25
      sim_grid_pos_y: 2001392.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355811.25
      sim_grid_pos_y: 2000901
    }
    terrain_level_point {
      sim_grid_pos_x: 2355793.25
      sim_grid_pos_y: 2000650.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2355474.5
      sim_grid_pos_y: 2000355.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355335
      sim_grid_pos_y: 2000152.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2354921.25
      sim_grid_pos_y: 1999670.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354428
      sim_grid_pos_y: 2000298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354515.5
      sim_grid_pos_y: 2000370.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35451e+06
      sim_grid_pos_y: 2000374.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2354652
      sim_grid_pos_y: 2000815.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354679.25
      sim_grid_pos_y: 2000824
    }
    terrain_level_point {
      sim_grid_pos_x: 2354674.25
      sim_grid_pos_y: 2000833.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355035
      sim_grid_pos_y: 2001147.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2355186.25
      sim_grid_pos_y: 2001147.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2355625.75
      sim_grid_pos_y: 2001566.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2355915.25
      sim_grid_pos_y: 2000919.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2355892.5
      sim_grid_pos_y: 2000602.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355552.5
      sim_grid_pos_y: 2000287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2355411.5
      sim_grid_pos_y: 2000083.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2354906
      sim_grid_pos_y: 1999523.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2354285.75
      sim_grid_pos_y: 2000313.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354417.75
      sim_grid_pos_y: 2000422.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354554
      sim_grid_pos_y: 2000845.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354547.5
      sim_grid_pos_y: 2000859.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354562.5
      sim_grid_pos_y: 2000872.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354571
      sim_grid_pos_y: 2000898.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354604.25
      sim_grid_pos_y: 2000908.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2354996.75
      sim_grid_pos_y: 2001250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2355145.25
      sim_grid_pos_y: 2001250.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35566e+06
      sim_grid_pos_y: 2001740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2356019.5
      sim_grid_pos_y: 2000937.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2355992
      sim_grid_pos_y: 2000555.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355630.5
      sim_grid_pos_y: 2.00022e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2355488
      sim_grid_pos_y: 2000013.75
    }
  }
}
terrain_level_data {
  terrain_level: 88
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2354821.5
      sim_grid_pos_y: 2001794
    }
    terrain_level_point {
      sim_grid_pos_x: 2354782.5
      sim_grid_pos_y: 2002044.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355397.75
      sim_grid_pos_y: 2002056.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2355417.75
      sim_grid_pos_y: 2001793.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2355473.25
      sim_grid_pos_y: 2001742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2354777.5
      sim_grid_pos_y: 2001742.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2354722.75
      sim_grid_pos_y: 2002094.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355445.25
      sim_grid_pos_y: 2002109.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2355528.5
      sim_grid_pos_y: 2001691.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354733.75
      sim_grid_pos_y: 2001691.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354663
      sim_grid_pos_y: 2002144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2355492.5
      sim_grid_pos_y: 2002161.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2355583.75
      sim_grid_pos_y: 2.00164e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2354689.75
      sim_grid_pos_y: 2001640.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2354603.25
      sim_grid_pos_y: 2002194.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35554e+06
      sim_grid_pos_y: 2002213.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2355639.25
      sim_grid_pos_y: 2001588.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354646
      sim_grid_pos_y: 2001589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354543.5
      sim_grid_pos_y: 2002244.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2355587.5
      sim_grid_pos_y: 2002265.88
    }
  }
}
terrain_level_data {
  terrain_level: 140
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2353986
      sim_grid_pos_y: 2000480.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2353875.75
      sim_grid_pos_y: 2000599.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2353977
      sim_grid_pos_y: 2000713.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354151.25
      sim_grid_pos_y: 2000708.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354251.25
      sim_grid_pos_y: 2000629
    }
    terrain_level_point {
      sim_grid_pos_x: 2354228
      sim_grid_pos_y: 2000485
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2353964
      sim_grid_pos_y: 2000428.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2353806.5
      sim_grid_pos_y: 2000598.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2353954.75
      sim_grid_pos_y: 2000765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2354169.75
      sim_grid_pos_y: 2000758.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35427e+06
      sim_grid_pos_y: 2000647.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354271.75
      sim_grid_pos_y: 2000434.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2353942
      sim_grid_pos_y: 2000376.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2353737.25
      sim_grid_pos_y: 2000597.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2353932.25
      sim_grid_pos_y: 2000817.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354188
      sim_grid_pos_y: 2000809.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2354296.25
      sim_grid_pos_y: 2000674.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2354315.75
      sim_grid_pos_y: 2000384.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2.35392e+06
      sim_grid_pos_y: 2000324.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2353668
      sim_grid_pos_y: 2000597.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35391e+06
      sim_grid_pos_y: 2000869.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354206.5
      sim_grid_pos_y: 2000860.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2354316.5
      sim_grid_pos_y: 2000697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2354359.5
      sim_grid_pos_y: 2000333.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2353898
      sim_grid_pos_y: 2000273.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2353599
      sim_grid_pos_y: 2000596.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2353887.5
      sim_grid_pos_y: 2000921
    }
    terrain_level_point {
      sim_grid_pos_x: 2354225
      sim_grid_pos_y: 2000911.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2354338.25
      sim_grid_pos_y: 2000708
    }
    terrain_level_point {
      sim_grid_pos_x: 2354403.25
      sim_grid_pos_y: 2000283.5
    }
  }
}
