terrain_level_data {
  terrain_level: 579
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1208613.5
      sim_grid_pos_y: 1489645.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208611.25
      sim_grid_pos_y: 1490318.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.20888e+06
      sim_grid_pos_y: 1490357.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209145
      sim_grid_pos_y: 1490046
    }
    terrain_level_point {
      sim_grid_pos_x: 1209482.5
      sim_grid_pos_y: 1489877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209798.12
      sim_grid_pos_y: 1489851.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1210027.12
      sim_grid_pos_y: 1490214.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1210366.12
      sim_grid_pos_y: 1490180.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1210165.75
      sim_grid_pos_y: 1489927.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209918.88
      sim_grid_pos_y: 1489717.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1209920.25
      sim_grid_pos_y: 1489422.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1209756.12
      sim_grid_pos_y: 1489469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209714
      sim_grid_pos_y: 1489671.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209326.5
      sim_grid_pos_y: 1489712.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1208934.25
      sim_grid_pos_y: 1489696.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208796.88
      sim_grid_pos_y: 1489549.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1209971.75
      sim_grid_pos_y: 1489354.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209712.38
      sim_grid_pos_y: 1489428.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209671.5
      sim_grid_pos_y: 1489624.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209324.88
      sim_grid_pos_y: 1489661.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208957.38
      sim_grid_pos_y: 1489646.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208807.62
      sim_grid_pos_y: 1489485.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1208562.38
      sim_grid_pos_y: 1489614.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208559.88
      sim_grid_pos_y: 1490363.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1208900.75
      sim_grid_pos_y: 1490412.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1209177.38
      sim_grid_pos_y: 1490087.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209496.62
      sim_grid_pos_y: 1489927.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209771.38
      sim_grid_pos_y: 1489905.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1210000.75
      sim_grid_pos_y: 1490268.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1210401.5
      sim_grid_pos_y: 1490228.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1210425.25
      sim_grid_pos_y: 1490172.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1210202.75
      sim_grid_pos_y: 1489892.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209970.25
      sim_grid_pos_y: 1489693.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1210023.25
      sim_grid_pos_y: 1489286.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209668.38
      sim_grid_pos_y: 1489387.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209628.88
      sim_grid_pos_y: 1489577.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209323.25
      sim_grid_pos_y: 1489610.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1208980.5
      sim_grid_pos_y: 1489595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208818.38
      sim_grid_pos_y: 1489422
    }
    terrain_level_point {
      sim_grid_pos_x: 1208511.25
      sim_grid_pos_y: 1489583.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1208508.5
      sim_grid_pos_y: 1490407.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1208921.38
      sim_grid_pos_y: 1490467.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209209.62
      sim_grid_pos_y: 1490128.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209510.62
      sim_grid_pos_y: 1489977.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209744.5
      sim_grid_pos_y: 1489959
    }
    terrain_level_point {
      sim_grid_pos_x: 1209974.25
      sim_grid_pos_y: 1490322.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1210436.88
      sim_grid_pos_y: 1490276.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1210484.25
      sim_grid_pos_y: 1490164.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1210239.88
      sim_grid_pos_y: 1489856.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1210021.62
      sim_grid_pos_y: 1489670.38
    }
  }
}
terrain_level_data {
  terrain_level: 410
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1209524.25
      sim_grid_pos_y: 1489294.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1209332.38
      sim_grid_pos_y: 1489259.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.20935e+06
      sim_grid_pos_y: 1489061.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1209553.12
      sim_grid_pos_y: 1489127.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1209611.25
      sim_grid_pos_y: 1489092.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1209565.88
      sim_grid_pos_y: 1489353.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209277.25
      sim_grid_pos_y: 1489301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1209304.62
      sim_grid_pos_y: 1488993.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1209669.38
      sim_grid_pos_y: 1489057
    }
    terrain_level_point {
      sim_grid_pos_x: 1209607.62
      sim_grid_pos_y: 1489413.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1209222
      sim_grid_pos_y: 1489343.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1209259.12
      sim_grid_pos_y: 1488924.5
    }
  }
}
