terrain_level_data {
  terrain_level: 104
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 724917.75
      sim_grid_pos_y: 1564237.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725196.25
      sim_grid_pos_y: 1564938
    }
    terrain_level_point {
      sim_grid_pos_x: 725344.688
      sim_grid_pos_y: 1564913.5
    }
    terrain_level_point {
      sim_grid_pos_x: 725500.062
      sim_grid_pos_y: 1565280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 726120.062
      sim_grid_pos_y: 1567106.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725996.438
      sim_grid_pos_y: 1567187.62
    }
    terrain_level_point {
      sim_grid_pos_x: 726444.125
      sim_grid_pos_y: 1568447.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726570.875
      sim_grid_pos_y: 1568476.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726836.938
      sim_grid_pos_y: 1569158.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726753.562
      sim_grid_pos_y: 1569386.12
    }
    terrain_level_point {
      sim_grid_pos_x: 726561.75
      sim_grid_pos_y: 1569517.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726073.562
      sim_grid_pos_y: 1569472.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725369.188
      sim_grid_pos_y: 1569406.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724970.188
      sim_grid_pos_y: 1569202.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724200.688
      sim_grid_pos_y: 1568499.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724585.312
      sim_grid_pos_y: 1568156.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724881.625
      sim_grid_pos_y: 1568012.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725060.75
      sim_grid_pos_y: 1568157.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725165.812
      sim_grid_pos_y: 1568092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 725261.688
      sim_grid_pos_y: 1567815.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725041.125
      sim_grid_pos_y: 1567078.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724974.688
      sim_grid_pos_y: 1566982
    }
    terrain_level_point {
      sim_grid_pos_x: 724648.938
      sim_grid_pos_y: 1566882
    }
    terrain_level_point {
      sim_grid_pos_x: 724681
      sim_grid_pos_y: 1566651.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724634.75
      sim_grid_pos_y: 1566267.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724807.688
      sim_grid_pos_y: 1566207
    }
    terrain_level_point {
      sim_grid_pos_x: 724529.625
      sim_grid_pos_y: 1565415.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724423.875
      sim_grid_pos_y: 1565290.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724382.75
      sim_grid_pos_y: 1564654.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724670.875
      sim_grid_pos_y: 1564574.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724608.375
      sim_grid_pos_y: 1564398.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 725209.25
      sim_grid_pos_y: 1564915.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725357.25
      sim_grid_pos_y: 1564890.62
    }
    terrain_level_point {
      sim_grid_pos_x: 725519.25
      sim_grid_pos_y: 1565273.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726144.562
      sim_grid_pos_y: 1567115.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726021.188
      sim_grid_pos_y: 1567196
    }
    terrain_level_point {
      sim_grid_pos_x: 726459.688
      sim_grid_pos_y: 1568429.88
    }
    terrain_level_point {
      sim_grid_pos_x: 726586.062
      sim_grid_pos_y: 1568459.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726858.875
      sim_grid_pos_y: 1569158
    }
    terrain_level_point {
      sim_grid_pos_x: 726770.562
      sim_grid_pos_y: 1569399.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726567.25
      sim_grid_pos_y: 1569538.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726071.688
      sim_grid_pos_y: 1569492.5
    }
    terrain_level_point {
      sim_grid_pos_x: 725363.375
      sim_grid_pos_y: 1569426.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724958.375
      sim_grid_pos_y: 1569219.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724170.062
      sim_grid_pos_y: 1568499.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724573.812
      sim_grid_pos_y: 1568138.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724884.375
      sim_grid_pos_y: 1567988.75
    }
    terrain_level_point {
      sim_grid_pos_x: 725062.312
      sim_grid_pos_y: 1568132.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725148.812
      sim_grid_pos_y: 1568079
    }
    terrain_level_point {
      sim_grid_pos_x: 725240.125
      sim_grid_pos_y: 1567815.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725022.438
      sim_grid_pos_y: 1567087.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724961.875
      sim_grid_pos_y: 1566999.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724626.188
      sim_grid_pos_y: 1566896.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724660.312
      sim_grid_pos_y: 1566651.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724612.438
      sim_grid_pos_y: 1566253.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724781.562
      sim_grid_pos_y: 1566194.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724511.5
      sim_grid_pos_y: 1565425.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724403.812
      sim_grid_pos_y: 1565298.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724361.188
      sim_grid_pos_y: 1564639.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724644.188
      sim_grid_pos_y: 1564560.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724583.062
      sim_grid_pos_y: 1564388.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724928.438
      sim_grid_pos_y: 1564208.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 725222.188
      sim_grid_pos_y: 1564892.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725369.875
      sim_grid_pos_y: 1564867.75
    }
    terrain_level_point {
      sim_grid_pos_x: 725538.438
      sim_grid_pos_y: 1565266
    }
    terrain_level_point {
      sim_grid_pos_x: 726169.125
      sim_grid_pos_y: 1567123.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726045.875
      sim_grid_pos_y: 1567204.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726475.25
      sim_grid_pos_y: 1568412.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726601.188
      sim_grid_pos_y: 1568441.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726880.812
      sim_grid_pos_y: 1569157.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726787.562
      sim_grid_pos_y: 1569412.62
    }
    terrain_level_point {
      sim_grid_pos_x: 726572.688
      sim_grid_pos_y: 1569559.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726069.75
      sim_grid_pos_y: 1569513
    }
    terrain_level_point {
      sim_grid_pos_x: 725357.562
      sim_grid_pos_y: 1569446.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724946.625
      sim_grid_pos_y: 1569236.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724139.5
      sim_grid_pos_y: 1568498.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724562.312
      sim_grid_pos_y: 1568121.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724887.125
      sim_grid_pos_y: 1567964.62
    }
    terrain_level_point {
      sim_grid_pos_x: 725063.938
      sim_grid_pos_y: 1568107.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725131.875
      sim_grid_pos_y: 1568065.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725218.625
      sim_grid_pos_y: 1567815
    }
    terrain_level_point {
      sim_grid_pos_x: 725003.688
      sim_grid_pos_y: 1567096.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724949.062
      sim_grid_pos_y: 1567017
    }
    terrain_level_point {
      sim_grid_pos_x: 724603.5
      sim_grid_pos_y: 1566911
    }
    terrain_level_point {
      sim_grid_pos_x: 724639.625
      sim_grid_pos_y: 1566651.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724590.062
      sim_grid_pos_y: 1566239.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724755.375
      sim_grid_pos_y: 1566181.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724493.438
      sim_grid_pos_y: 1565436.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724383.812
      sim_grid_pos_y: 1565306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724339.688
      sim_grid_pos_y: 1564624.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724617.562
      sim_grid_pos_y: 1564546.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724557.812
      sim_grid_pos_y: 1564378.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724939.062
      sim_grid_pos_y: 1564179.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 725235.125
      sim_grid_pos_y: 1564869.25
    }
    terrain_level_point {
      sim_grid_pos_x: 725382.438
      sim_grid_pos_y: 1564844.88
    }
    terrain_level_point {
      sim_grid_pos_x: 725557.562
      sim_grid_pos_y: 1565258.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726193.625
      sim_grid_pos_y: 1567132.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726070.625
      sim_grid_pos_y: 1567212.62
    }
    terrain_level_point {
      sim_grid_pos_x: 726490.812
      sim_grid_pos_y: 1568395
    }
    terrain_level_point {
      sim_grid_pos_x: 726616.375
      sim_grid_pos_y: 1568424.12
    }
    terrain_level_point {
      sim_grid_pos_x: 726902.688
      sim_grid_pos_y: 1569157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726804.562
      sim_grid_pos_y: 1569425.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726578.188
      sim_grid_pos_y: 1569580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726067.875
      sim_grid_pos_y: 1569533.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725351.688
      sim_grid_pos_y: 1569466.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724934.812
      sim_grid_pos_y: 1569253.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724108.875
      sim_grid_pos_y: 1568498.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724550.812
      sim_grid_pos_y: 1568104.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724889.938
      sim_grid_pos_y: 1567940.5
    }
    terrain_level_point {
      sim_grid_pos_x: 725065.5
      sim_grid_pos_y: 1568082.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725114.875
      sim_grid_pos_y: 1568051.75
    }
    terrain_level_point {
      sim_grid_pos_x: 725197.062
      sim_grid_pos_y: 1567814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724985
      sim_grid_pos_y: 1567105.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724936.25
      sim_grid_pos_y: 1567034.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724580.75
      sim_grid_pos_y: 1566925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724619
      sim_grid_pos_y: 1566651.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724567.75
      sim_grid_pos_y: 1566225.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724729.25
      sim_grid_pos_y: 1566169.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724475.312
      sim_grid_pos_y: 1565446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724363.812
      sim_grid_pos_y: 1565314.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724318.125
      sim_grid_pos_y: 1564609
    }
    terrain_level_point {
      sim_grid_pos_x: 724590.875
      sim_grid_pos_y: 1564533
    }
    terrain_level_point {
      sim_grid_pos_x: 724532.5
      sim_grid_pos_y: 1564368.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724949.75
      sim_grid_pos_y: 1564151.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 725248.062
      sim_grid_pos_y: 1564846.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725395.062
      sim_grid_pos_y: 1564822
    }
    terrain_level_point {
      sim_grid_pos_x: 725576.75
      sim_grid_pos_y: 1565251.38
    }
    terrain_level_point {
      sim_grid_pos_x: 726218.188
      sim_grid_pos_y: 1567140.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726095.375
      sim_grid_pos_y: 1567221
    }
    terrain_level_point {
      sim_grid_pos_x: 726506.375
      sim_grid_pos_y: 1568377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726631.562
      sim_grid_pos_y: 1568406.62
    }
    terrain_level_point {
      sim_grid_pos_x: 726924.625
      sim_grid_pos_y: 1569157.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726821.562
      sim_grid_pos_y: 1569439
    }
    terrain_level_point {
      sim_grid_pos_x: 726583.625
      sim_grid_pos_y: 1569601.62
    }
    terrain_level_point {
      sim_grid_pos_x: 726066
      sim_grid_pos_y: 1569553.75
    }
    terrain_level_point {
      sim_grid_pos_x: 725345.875
      sim_grid_pos_y: 1569486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724923
      sim_grid_pos_y: 1569270.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724078.312
      sim_grid_pos_y: 1568498.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724539.312
      sim_grid_pos_y: 1568087.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724892.688
      sim_grid_pos_y: 1567916.38
    }
    terrain_level_point {
      sim_grid_pos_x: 725067.125
      sim_grid_pos_y: 1568057.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725097.875
      sim_grid_pos_y: 1568038.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725175.562
      sim_grid_pos_y: 1567814
    }
    terrain_level_point {
      sim_grid_pos_x: 724966.25
      sim_grid_pos_y: 1567114.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724923.375
      sim_grid_pos_y: 1567052
    }
    terrain_level_point {
      sim_grid_pos_x: 724558.062
      sim_grid_pos_y: 1566939.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724598.312
      sim_grid_pos_y: 1566651
    }
    terrain_level_point {
      sim_grid_pos_x: 724545.438
      sim_grid_pos_y: 1566211.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724703.062
      sim_grid_pos_y: 1566156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724457.25
      sim_grid_pos_y: 1565456.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724343.75
      sim_grid_pos_y: 1565322.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724296.625
      sim_grid_pos_y: 1564593.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724564.188
      sim_grid_pos_y: 1564519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724507.25
      sim_grid_pos_y: 1564358.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724960.438
      sim_grid_pos_y: 1564122.38
    }
  }
}
