terrain_level_data {
  terrain_level: 73
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1919689.62
      sim_grid_pos_y: 1265389.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1919866.75
      sim_grid_pos_y: 1264019.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1922572.5
      sim_grid_pos_y: 1265325.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1923089.5
      sim_grid_pos_y: 1265549.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1925365.38
      sim_grid_pos_y: 1266761.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1925191.75
      sim_grid_pos_y: 1268017.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1924358
      sim_grid_pos_y: 1267841
    }
    terrain_level_point {
      sim_grid_pos_x: 1922569.38
      sim_grid_pos_y: 1267255.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1922325.62
      sim_grid_pos_y: 1266730.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1922114.12
      sim_grid_pos_y: 1266519.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1922628
      sim_grid_pos_y: 1265204.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1923147.38
      sim_grid_pos_y: 1265429.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1925510.12
      sim_grid_pos_y: 1266687.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1925304.12
      sim_grid_pos_y: 1268177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1924323.38
      sim_grid_pos_y: 1.26797e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1922472.88
      sim_grid_pos_y: 1267364.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1922214.75
      sim_grid_pos_y: 1266808.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1922036.5
      sim_grid_pos_y: 1266630.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1919545
      sim_grid_pos_y: 1265469.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1919758.25
      sim_grid_pos_y: 1263819.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1922683.5
      sim_grid_pos_y: 1265083.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1923205.25
      sim_grid_pos_y: 1265309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1925655
      sim_grid_pos_y: 1266613.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1925416.5
      sim_grid_pos_y: 1268337.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1924288.75
      sim_grid_pos_y: 1268098.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1922376.38
      sim_grid_pos_y: 1267472.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1922103.75
      sim_grid_pos_y: 1266886
    }
    terrain_level_point {
      sim_grid_pos_x: 1921959
      sim_grid_pos_y: 1266741.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1919400.25
      sim_grid_pos_y: 1265548.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1919649.75
      sim_grid_pos_y: 1263618.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1922739
      sim_grid_pos_y: 1264962.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1923263.25
      sim_grid_pos_y: 1265189.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1925799.75
      sim_grid_pos_y: 1266539.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1925529
      sim_grid_pos_y: 1268497.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1924254.12
      sim_grid_pos_y: 1268227.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1922279.88
      sim_grid_pos_y: 1267581.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1921992.88
      sim_grid_pos_y: 1266963.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1921881.38
      sim_grid_pos_y: 1266852.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1919255.62
      sim_grid_pos_y: 1265628.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1919541.25
      sim_grid_pos_y: 1263418.38
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1922822
      sim_grid_pos_y: 1265526.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1922822
      sim_grid_pos_y: 1265926.12
    }
  }
}
