terrain_level_data {
  terrain_level: 2890
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2985752
      sim_grid_pos_y: 1707231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2973855.5
      sim_grid_pos_y: 1706223.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2973231.75
      sim_grid_pos_y: 1706130.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2971889.5
      sim_grid_pos_y: 1706107.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2971847
      sim_grid_pos_y: 1707789.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2973927.25
      sim_grid_pos_y: 1707915.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2976224
      sim_grid_pos_y: 1708298.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2977401.25
      sim_grid_pos_y: 1708364.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2977391.5
      sim_grid_pos_y: 1710038.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2979624.25
      sim_grid_pos_y: 1710315.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2979642
      sim_grid_pos_y: 1709981.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2980136.75
      sim_grid_pos_y: 1709991.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2980208
      sim_grid_pos_y: 1708573
    }
    terrain_level_point {
      sim_grid_pos_x: 2982675
      sim_grid_pos_y: 1708699.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2983504.5
      sim_grid_pos_y: 1708658.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2985325.75
      sim_grid_pos_y: 1708918.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2971789.5
      sim_grid_pos_y: 1706003.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2971742
      sim_grid_pos_y: 1707886
    }
    terrain_level_point {
      sim_grid_pos_x: 2973915.75
      sim_grid_pos_y: 1708017.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2976212.75
      sim_grid_pos_y: 1708400.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2977298.25
      sim_grid_pos_y: 1708461.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2977288.5
      sim_grid_pos_y: 1710128.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2979720.75
      sim_grid_pos_y: 1710431.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2979739
      sim_grid_pos_y: 1710085.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2980234.25
      sim_grid_pos_y: 1710096.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2980305.25
      sim_grid_pos_y: 1708680.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2982675
      sim_grid_pos_y: 1708802
    }
    terrain_level_point {
      sim_grid_pos_x: 2983499.75
      sim_grid_pos_y: 1708761.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2985402.5
      sim_grid_pos_y: 1709033.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2985881
      sim_grid_pos_y: 1707139.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2973867.5
      sim_grid_pos_y: 1706121.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2973240.25
      sim_grid_pos_y: 1706028.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2971689.75
      sim_grid_pos_y: 1705899.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2971637
      sim_grid_pos_y: 1707982.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2973904.25
      sim_grid_pos_y: 1708119.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2976201.25
      sim_grid_pos_y: 1708502.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2977195
      sim_grid_pos_y: 1708558.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2977185.5
      sim_grid_pos_y: 1710219.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2979817.25
      sim_grid_pos_y: 1710546.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2979836.25
      sim_grid_pos_y: 1710190.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2980331.5
      sim_grid_pos_y: 1710201.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2980402.5
      sim_grid_pos_y: 1708788.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2982674.75
      sim_grid_pos_y: 1708904.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2983495
      sim_grid_pos_y: 1708864
    }
    terrain_level_point {
      sim_grid_pos_x: 2985479.25
      sim_grid_pos_y: 1709147.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.98601e+06
      sim_grid_pos_y: 1707047.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2973879.25
      sim_grid_pos_y: 1706019.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2973248.75
      sim_grid_pos_y: 1705925.88
    }
  }
}
