terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1770382.5
      sim_grid_pos_y: 1092533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1772349.25
      sim_grid_pos_y: 1093688
    }
    terrain_level_point {
      sim_grid_pos_x: 1772838
      sim_grid_pos_y: 1092614.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1771402.5
      sim_grid_pos_y: 1091673.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1770201.75
      sim_grid_pos_y: 1091580.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1770164.25
      sim_grid_pos_y: 1091547.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1770354.75
      sim_grid_pos_y: 1092553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1772363
      sim_grid_pos_y: 1093731.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1772877
      sim_grid_pos_y: 1092603
    }
    terrain_level_point {
      sim_grid_pos_x: 1771412.75
      sim_grid_pos_y: 1091643.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1770126.5
      sim_grid_pos_y: 1091513.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1770327.25
      sim_grid_pos_y: 1092572.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1772377
      sim_grid_pos_y: 1093775.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1772916
      sim_grid_pos_y: 1092591.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1771423
      sim_grid_pos_y: 1091613.12
    }
  }
}
terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1772614.25
      sim_grid_pos_y: 1092098.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1773118.5
      sim_grid_pos_y: 1091320.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1773438
      sim_grid_pos_y: 1091521.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1773470.5
      sim_grid_pos_y: 1091657.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1773329.75
      sim_grid_pos_y: 1091921.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1773471.25
      sim_grid_pos_y: 1091958
    }
    terrain_level_point {
      sim_grid_pos_x: 1773435.75
      sim_grid_pos_y: 1092112.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1773196.75
      sim_grid_pos_y: 1092552
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1773465
      sim_grid_pos_y: 1091502.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1773503
      sim_grid_pos_y: 1091661.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1773375.25
      sim_grid_pos_y: 1091901.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1773508
      sim_grid_pos_y: 1091935.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1773464.75
      sim_grid_pos_y: 1092123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1773206.5
      sim_grid_pos_y: 1092598.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1772573
      sim_grid_pos_y: 1092105.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1773109.25
      sim_grid_pos_y: 1091278
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1773492.25
      sim_grid_pos_y: 1091482.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1773535.75
      sim_grid_pos_y: 1091666
    }
    terrain_level_point {
      sim_grid_pos_x: 1773420.75
      sim_grid_pos_y: 1091881.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1773544.75
      sim_grid_pos_y: 1091913.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1773493.75
      sim_grid_pos_y: 1092134.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1773216.25
      sim_grid_pos_y: 1092645
    }
    terrain_level_point {
      sim_grid_pos_x: 1772532
      sim_grid_pos_y: 1092112.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.7731e+06
      sim_grid_pos_y: 1091235.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1773519.25
      sim_grid_pos_y: 1091463.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1773568.25
      sim_grid_pos_y: 1091670.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1773466.25
      sim_grid_pos_y: 1091861.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1773581.5
      sim_grid_pos_y: 1091891.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1773522.75
      sim_grid_pos_y: 1092145.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1773226
      sim_grid_pos_y: 1092691.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1772490.75
      sim_grid_pos_y: 1092119.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1773090.5
      sim_grid_pos_y: 1091193.62
    }
  }
}
