terrain_level_data {
  terrain_level: 42
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2154950.25
      sim_grid_pos_y: 60904.0391
    }
    terrain_level_point {
      sim_grid_pos_x: 2161524.5
      sim_grid_pos_y: 69676.3906
    }
    terrain_level_point {
      sim_grid_pos_x: 2161255
      sim_grid_pos_y: 70919.4375
    }
    terrain_level_point {
      sim_grid_pos_x: 2159078.5
      sim_grid_pos_y: 71788.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 2154429.25
      sim_grid_pos_y: 70420.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 2152380.25
      sim_grid_pos_y: 69142.7422
    }
    terrain_level_point {
      sim_grid_pos_x: 2154307.75
      sim_grid_pos_y: 65803.4141
    }
    terrain_level_point {
      sim_grid_pos_x: 2152931.75
      sim_grid_pos_y: 64252.4336
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2161579.5
      sim_grid_pos_y: 69664.3828
    }
    terrain_level_point {
      sim_grid_pos_x: 2161299.25
      sim_grid_pos_y: 70956.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 2159081.25
      sim_grid_pos_y: 71842.6641
    }
    terrain_level_point {
      sim_grid_pos_x: 2154408
      sim_grid_pos_y: 70467.5156
    }
    terrain_level_point {
      sim_grid_pos_x: 2152311.25
      sim_grid_pos_y: 69160.0312
    }
    terrain_level_point {
      sim_grid_pos_x: 2154244.75
      sim_grid_pos_y: 65809.7891
    }
    terrain_level_point {
      sim_grid_pos_x: 2152868.5
      sim_grid_pos_y: 64258.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2154945.75
      sim_grid_pos_y: 60812.4023
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2161634.5
      sim_grid_pos_y: 69652.3594
    }
    terrain_level_point {
      sim_grid_pos_x: 2161343.5
      sim_grid_pos_y: 70994.4375
    }
    terrain_level_point {
      sim_grid_pos_x: 2159083.75
      sim_grid_pos_y: 71896.8516
    }
    terrain_level_point {
      sim_grid_pos_x: 2154386.75
      sim_grid_pos_y: 70514.7109
    }
    terrain_level_point {
      sim_grid_pos_x: 2152242
      sim_grid_pos_y: 69177.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 2154182
      sim_grid_pos_y: 65816.1719
    }
    terrain_level_point {
      sim_grid_pos_x: 2152805
      sim_grid_pos_y: 64264.0703
    }
    terrain_level_point {
      sim_grid_pos_x: 2154941
      sim_grid_pos_y: 60720.7617
    }
  }
}
