terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2478810.75
      sim_grid_pos_y: 255915.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2467521.25
      sim_grid_pos_y: 262582.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2464739.25
      sim_grid_pos_y: 260790.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2454782.5
      sim_grid_pos_y: 254359.891
    }
    terrain_level_point {
      sim_grid_pos_x: 2454888.25
      sim_grid_pos_y: 241260.641
    }
    terrain_level_point {
      sim_grid_pos_x: 2461307.75
      sim_grid_pos_y: 241278.516
    }
    terrain_level_point {
      sim_grid_pos_x: 2463321.25
      sim_grid_pos_y: 241616.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2463943.75
      sim_grid_pos_y: 243800.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2466283
      sim_grid_pos_y: 246097.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2473055.5
      sim_grid_pos_y: 250131.953
    }
    terrain_level_point {
      sim_grid_pos_x: 2475709
      sim_grid_pos_y: 246134.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2479345.25
      sim_grid_pos_y: 248535.422
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2461312.25
      sim_grid_pos_y: 241227.266
    }
    terrain_level_point {
      sim_grid_pos_x: 2463361.75
      sim_grid_pos_y: 241571.797
    }
    terrain_level_point {
      sim_grid_pos_x: 2463989.25
      sim_grid_pos_y: 243772.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2466314.5
      sim_grid_pos_y: 246056.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2473039.75
      sim_grid_pos_y: 250062.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2475694.75
      sim_grid_pos_y: 246063.984
    }
    terrain_level_point {
      sim_grid_pos_x: 2479398.5
      sim_grid_pos_y: 248509.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2478859.75
      sim_grid_pos_y: 255946.297
    }
    terrain_level_point {
      sim_grid_pos_x: 2.46752e+06
      sim_grid_pos_y: 262642.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2464711.5
      sim_grid_pos_y: 260833.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2454731
      sim_grid_pos_y: 254387.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2454837.25
      sim_grid_pos_y: 241209.234
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2461316.5
      sim_grid_pos_y: 241176.016
    }
    terrain_level_point {
      sim_grid_pos_x: 2463402
      sim_grid_pos_y: 241526.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2464035
      sim_grid_pos_y: 243745.922
    }
    terrain_level_point {
      sim_grid_pos_x: 2466346
      sim_grid_pos_y: 246015.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2473024.25
      sim_grid_pos_y: 249993.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2475680.25
      sim_grid_pos_y: 245993.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2479451.75
      sim_grid_pos_y: 248482.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2478909
      sim_grid_pos_y: 255976.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2467518.75
      sim_grid_pos_y: 262702.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2464683.75
      sim_grid_pos_y: 260876.328
    }
    terrain_level_point {
      sim_grid_pos_x: 2454679.5
      sim_grid_pos_y: 254415.422
    }
    terrain_level_point {
      sim_grid_pos_x: 2454786.5
      sim_grid_pos_y: 241157.828
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2461320.75
      sim_grid_pos_y: 241124.766
    }
    terrain_level_point {
      sim_grid_pos_x: 2463442.5
      sim_grid_pos_y: 241481.422
    }
    terrain_level_point {
      sim_grid_pos_x: 2464080.5
      sim_grid_pos_y: 243718.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2466377.75
      sim_grid_pos_y: 245974.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2473008.5
      sim_grid_pos_y: 249924.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2475665.75
      sim_grid_pos_y: 245922.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2479505.25
      sim_grid_pos_y: 248456.703
    }
    terrain_level_point {
      sim_grid_pos_x: 2478958.25
      sim_grid_pos_y: 256007.266
    }
    terrain_level_point {
      sim_grid_pos_x: 2467517.75
      sim_grid_pos_y: 262763.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2464656
      sim_grid_pos_y: 260919.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2454628
      sim_grid_pos_y: 254443.203
    }
    terrain_level_point {
      sim_grid_pos_x: 2454735.5
      sim_grid_pos_y: 241106.422
    }
  }
}
