terrain_level_data {
  terrain_level: 275
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1240411
      sim_grid_pos_y: 1564666.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1240448.88
      sim_grid_pos_y: 1564192.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1241163.5
      sim_grid_pos_y: 1563580.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1242391
      sim_grid_pos_y: 1563595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1242907
      sim_grid_pos_y: 1563775.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1243474.5
      sim_grid_pos_y: 1563486.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1243436.62
      sim_grid_pos_y: 1563122.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243676.75
      sim_grid_pos_y: 1562936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1245370.38
      sim_grid_pos_y: 1563146.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1245846.38
      sim_grid_pos_y: 1562666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1247015.62
      sim_grid_pos_y: 1563073.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1247507.62
      sim_grid_pos_y: 1563636.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1248548.75
      sim_grid_pos_y: 1563847.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.24978e+06
      sim_grid_pos_y: 1563629.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1251256.88
      sim_grid_pos_y: 1563932.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1251970.62
      sim_grid_pos_y: 1565871.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1250903.75
      sim_grid_pos_y: 1566098.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1248395.88
      sim_grid_pos_y: 1565908.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1247068.62
      sim_grid_pos_y: 1566051
    }
    terrain_level_point {
      sim_grid_pos_x: 1246555.12
      sim_grid_pos_y: 1565905.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1246181.88
      sim_grid_pos_y: 1565725.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1245717.12
      sim_grid_pos_y: 1565421.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1245697
      sim_grid_pos_y: 1565223.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1244062.5
      sim_grid_pos_y: 1565143.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243374
      sim_grid_pos_y: 1565471.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1242444.75
      sim_grid_pos_y: 1566290.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1240559.38
      sim_grid_pos_y: 1566554.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1240446.88
      sim_grid_pos_y: 1565541.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1247092.75
      sim_grid_pos_y: 1562959.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1247578.25
      sim_grid_pos_y: 1563514.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1248550.38
      sim_grid_pos_y: 1563712.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1249781.88
      sim_grid_pos_y: 1563493.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1251356.25
      sim_grid_pos_y: 1563817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1252148.88
      sim_grid_pos_y: 1565969.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1250912.75
      sim_grid_pos_y: 1566232.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1248398
      sim_grid_pos_y: 1566042.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1247057.12
      sim_grid_pos_y: 1566186.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1246507.62
      sim_grid_pos_y: 1566030.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1246116.12
      sim_grid_pos_y: 1565841.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1245590.88
      sim_grid_pos_y: 1565498.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1245576
      sim_grid_pos_y: 1565351
    }
    terrain_level_point {
      sim_grid_pos_x: 1244089.5
      sim_grid_pos_y: 1565278.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1243448.25
      sim_grid_pos_y: 1565583.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1242502.88
      sim_grid_pos_y: 1566417.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1240442
      sim_grid_pos_y: 1566705.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1240313.88
      sim_grid_pos_y: 1565551.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1240277.5
      sim_grid_pos_y: 1564663.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1240320.38
      sim_grid_pos_y: 1564127.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1241115
      sim_grid_pos_y: 1563446.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1242414.38
      sim_grid_pos_y: 1563462.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1242897.25
      sim_grid_pos_y: 1563631.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1243332.38
      sim_grid_pos_y: 1563409.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1243296.38
      sim_grid_pos_y: 1563062.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243638.5
      sim_grid_pos_y: 1562797.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1245321.88
      sim_grid_pos_y: 1563006
    }
    terrain_level_point {
      sim_grid_pos_x: 1245811
      sim_grid_pos_y: 1562513.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1247169.88
      sim_grid_pos_y: 1562844.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1247649
      sim_grid_pos_y: 1563393.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1248552.12
      sim_grid_pos_y: 1563576.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1249783.62
      sim_grid_pos_y: 1563358
    }
    terrain_level_point {
      sim_grid_pos_x: 1251455.75
      sim_grid_pos_y: 1563701.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1252327.12
      sim_grid_pos_y: 1566068.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1250921.75
      sim_grid_pos_y: 1566367.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1248400.12
      sim_grid_pos_y: 1566176
    }
    terrain_level_point {
      sim_grid_pos_x: 1247045.75
      sim_grid_pos_y: 1566321.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1246460.12
      sim_grid_pos_y: 1566155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1246050.5
      sim_grid_pos_y: 1565957.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1245464.75
      sim_grid_pos_y: 1565575.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1245454.88
      sim_grid_pos_y: 1565478.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1244116.38
      sim_grid_pos_y: 1565412.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1243522.38
      sim_grid_pos_y: 1565695.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1242561.12
      sim_grid_pos_y: 1566543.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1240324.75
      sim_grid_pos_y: 1566856.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1240180.88
      sim_grid_pos_y: 1565561.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1240144
      sim_grid_pos_y: 1564661
    }
    terrain_level_point {
      sim_grid_pos_x: 1240191.88
      sim_grid_pos_y: 1564061.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1241066.38
      sim_grid_pos_y: 1563312.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1242437.75
      sim_grid_pos_y: 1563329.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1242887.38
      sim_grid_pos_y: 1563486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1243190.38
      sim_grid_pos_y: 1563332.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243156.25
      sim_grid_pos_y: 1563002.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243600.38
      sim_grid_pos_y: 1562658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1245273.38
      sim_grid_pos_y: 1562865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1245775.5
      sim_grid_pos_y: 1562359.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1247247
      sim_grid_pos_y: 1562730.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1247719.62
      sim_grid_pos_y: 1563271.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1248553.75
      sim_grid_pos_y: 1563440.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1249785.5
      sim_grid_pos_y: 1563222.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1251555.25
      sim_grid_pos_y: 1563586
    }
    terrain_level_point {
      sim_grid_pos_x: 1252505.38
      sim_grid_pos_y: 1566166.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1250930.75
      sim_grid_pos_y: 1566501.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1248402.12
      sim_grid_pos_y: 1566309.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1247034.25
      sim_grid_pos_y: 1566456.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1246412.62
      sim_grid_pos_y: 1566280.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1245984.75
      sim_grid_pos_y: 1566074.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1245338.5
      sim_grid_pos_y: 1565652.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1245333.88
      sim_grid_pos_y: 1565606.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1244143.38
      sim_grid_pos_y: 1565547.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1243596.5
      sim_grid_pos_y: 1565808
    }
    terrain_level_point {
      sim_grid_pos_x: 1242619.25
      sim_grid_pos_y: 1.56667e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1240207.38
      sim_grid_pos_y: 1567007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1240047.88
      sim_grid_pos_y: 1565571.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1240010.5
      sim_grid_pos_y: 1564658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1240063.5
      sim_grid_pos_y: 1563996.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1241017.88
      sim_grid_pos_y: 1563178.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1242461.12
      sim_grid_pos_y: 1563196.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1242877.62
      sim_grid_pos_y: 1563342
    }
    terrain_level_point {
      sim_grid_pos_x: 1243048.38
      sim_grid_pos_y: 1563255.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1243016
      sim_grid_pos_y: 1562942.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243562.25
      sim_grid_pos_y: 1562519.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1245224.75
      sim_grid_pos_y: 1562725.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.24574e+06
      sim_grid_pos_y: 1562206.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1247324.12
      sim_grid_pos_y: 1562616.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1247790.38
      sim_grid_pos_y: 1563149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1248555.5
      sim_grid_pos_y: 1563305.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1249787.38
      sim_grid_pos_y: 1563086.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1251654.62
      sim_grid_pos_y: 1563470.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1252683.62
      sim_grid_pos_y: 1566264.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1250939.75
      sim_grid_pos_y: 1566636
    }
    terrain_level_point {
      sim_grid_pos_x: 1248404.25
      sim_grid_pos_y: 1566443.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1247022.88
      sim_grid_pos_y: 1566592.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1246365.25
      sim_grid_pos_y: 1566405.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1245919.12
      sim_grid_pos_y: 1566190.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1245219.88
      sim_grid_pos_y: 1565733.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1244170.38
      sim_grid_pos_y: 1565682.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243670.62
      sim_grid_pos_y: 1565920.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1242677.38
      sim_grid_pos_y: 1566796.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.24009e+06
      sim_grid_pos_y: 1567158.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1239914.88
      sim_grid_pos_y: 1565581.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1239877
      sim_grid_pos_y: 1564655.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1239935
      sim_grid_pos_y: 1563931
    }
    terrain_level_point {
      sim_grid_pos_x: 1240969.25
      sim_grid_pos_y: 1563044.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1242484.62
      sim_grid_pos_y: 1563063.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1242867.88
      sim_grid_pos_y: 1563197.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1242906.38
      sim_grid_pos_y: 1563177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1242875.75
      sim_grid_pos_y: 1562882.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1243524.12
      sim_grid_pos_y: 1562380.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1245176.25
      sim_grid_pos_y: 1562585.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1245704.5
      sim_grid_pos_y: 1562053
    }
  }
}
