terrain_level_data {
  terrain_level: 275
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3169978.25
      sim_grid_pos_y: 734706.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3160947
      sim_grid_pos_y: 731110.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3161852
      sim_grid_pos_y: 729257.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3162818
      sim_grid_pos_y: 728657.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3164379.75
      sim_grid_pos_y: 728951.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3164528.75
      sim_grid_pos_y: 728667.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3166374.5
      sim_grid_pos_y: 729983.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3166908.75
      sim_grid_pos_y: 730340.312
    }
    terrain_level_point {
      sim_grid_pos_x: 3168033.75
      sim_grid_pos_y: 730801.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3169075.25
      sim_grid_pos_y: 731887.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 3166403.5
      sim_grid_pos_y: 729940.812
    }
    terrain_level_point {
      sim_grid_pos_x: 3166933
      sim_grid_pos_y: 730294.812
    }
    terrain_level_point {
      sim_grid_pos_x: 3168063.25
      sim_grid_pos_y: 730758.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3169120.5
      sim_grid_pos_y: 731860.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3170037
      sim_grid_pos_y: 734722.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3169989.5
      sim_grid_pos_y: 734766.438
    }
    terrain_level_point {
      sim_grid_pos_x: 3160876.5
      sim_grid_pos_y: 731137.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3161812.5
      sim_grid_pos_y: 729221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3162807.75
      sim_grid_pos_y: 728603.625
    }
    terrain_level_point {
      sim_grid_pos_x: 3164351.75
      sim_grid_pos_y: 728894.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3164510.5
      sim_grid_pos_y: 728591.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 3166432.5
      sim_grid_pos_y: 729898.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3166957.25
      sim_grid_pos_y: 730249.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3168092.75
      sim_grid_pos_y: 730714.938
    }
    terrain_level_point {
      sim_grid_pos_x: 3169165.75
      sim_grid_pos_y: 731833.438
    }
    terrain_level_point {
      sim_grid_pos_x: 3170095.75
      sim_grid_pos_y: 734737.375
    }
    terrain_level_point {
      sim_grid_pos_x: 3170000.75
      sim_grid_pos_y: 734826.062
    }
    terrain_level_point {
      sim_grid_pos_x: 3160806.25
      sim_grid_pos_y: 731164.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3161773
      sim_grid_pos_y: 729186
    }
    terrain_level_point {
      sim_grid_pos_x: 3162797.75
      sim_grid_pos_y: 728549.562
    }
    terrain_level_point {
      sim_grid_pos_x: 3164324
      sim_grid_pos_y: 728836.688
    }
    terrain_level_point {
      sim_grid_pos_x: 3164492.5
      sim_grid_pos_y: 728515.5
    }
  }
}
