terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1130727.88
      sim_grid_pos_y: 1339825.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1130674.75
      sim_grid_pos_y: 1340933.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1131031.12
      sim_grid_pos_y: 1341155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131328.25
      sim_grid_pos_y: 1342221
    }
    terrain_level_point {
      sim_grid_pos_x: 1131302.75
      sim_grid_pos_y: 1342417.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1131517.38
      sim_grid_pos_y: 1343364.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132855.75
      sim_grid_pos_y: 1344287.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133025.62
      sim_grid_pos_y: 1344775.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133263.12
      sim_grid_pos_y: 1345186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133449.75
      sim_grid_pos_y: 1345528.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133925.5
      sim_grid_pos_y: 1345545
    }
    terrain_level_point {
      sim_grid_pos_x: 1134097.12
      sim_grid_pos_y: 1345632.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134429.12
      sim_grid_pos_y: 1345929.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134405.75
      sim_grid_pos_y: 1346370.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134175.12
      sim_grid_pos_y: 1346842.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134773
      sim_grid_pos_y: 1347209.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136250.12
      sim_grid_pos_y: 1347186
    }
    terrain_level_point {
      sim_grid_pos_x: 1136602.88
      sim_grid_pos_y: 1346898.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136887.75
      sim_grid_pos_y: 1346521
    }
    terrain_level_point {
      sim_grid_pos_x: 1136570.75
      sim_grid_pos_y: 1346295.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136697.12
      sim_grid_pos_y: 1346192
    }
    terrain_level_point {
      sim_grid_pos_x: 1136863.25
      sim_grid_pos_y: 1346281.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136955.5
      sim_grid_pos_y: 1346041.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1137143.12
      sim_grid_pos_y: 1346159
    }
    terrain_level_point {
      sim_grid_pos_x: 1137420.88
      sim_grid_pos_y: 1345960.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1137440.38
      sim_grid_pos_y: 1345484.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1137473.62
      sim_grid_pos_y: 1344981.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134282.5
      sim_grid_pos_y: 1338685.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133450.38
      sim_grid_pos_y: 1339035.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133108
      sim_grid_pos_y: 1339403.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132169.88
      sim_grid_pos_y: 1339712.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132019.25
      sim_grid_pos_y: 1339690.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131802.62
      sim_grid_pos_y: 1339869.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1134292.12
      sim_grid_pos_y: 1338658.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133438.38
      sim_grid_pos_y: 1339018.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133096.62
      sim_grid_pos_y: 1339386
    }
    terrain_level_point {
      sim_grid_pos_x: 1132168.12
      sim_grid_pos_y: 1339691.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132013.25
      sim_grid_pos_y: 1339668.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1131795.62
      sim_grid_pos_y: 1339848.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1130708.38
      sim_grid_pos_y: 1339803.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1130653.75
      sim_grid_pos_y: 1340944.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1131013.62
      sim_grid_pos_y: 1341168.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1131307.5
      sim_grid_pos_y: 1342222.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1131282
      sim_grid_pos_y: 1342418.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131499.25
      sim_grid_pos_y: 1343376.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132838.5
      sim_grid_pos_y: 1344300.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133007
      sim_grid_pos_y: 1344784
    }
    terrain_level_point {
      sim_grid_pos_x: 1133245.38
      sim_grid_pos_y: 1345197
    }
    terrain_level_point {
      sim_grid_pos_x: 1133437.38
      sim_grid_pos_y: 1345548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133920.25
      sim_grid_pos_y: 1345565.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134085.5
      sim_grid_pos_y: 1345649.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134408.12
      sim_grid_pos_y: 1345938.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134385.5
      sim_grid_pos_y: 1346365.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134148.5
      sim_grid_pos_y: 1346850.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134767.25
      sim_grid_pos_y: 1347230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136257.62
      sim_grid_pos_y: 1347206.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136617.75
      sim_grid_pos_y: 1346912.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136916.88
      sim_grid_pos_y: 1346516.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1136604.5
      sim_grid_pos_y: 1346294.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136699.5
      sim_grid_pos_y: 1346216.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1136874
      sim_grid_pos_y: 1346311
    }
    terrain_level_point {
      sim_grid_pos_x: 1136965.75
      sim_grid_pos_y: 1346072.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1137143.88
      sim_grid_pos_y: 1346183.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1137441
      sim_grid_pos_y: 1345971.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1137460.88
      sim_grid_pos_y: 1345485
    }
    terrain_level_point {
      sim_grid_pos_x: 1137494.5
      sim_grid_pos_y: 1344977.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1134301.75
      sim_grid_pos_y: 1338632.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133426.25
      sim_grid_pos_y: 1339001.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133085.25
      sim_grid_pos_y: 1339368.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132166.38
      sim_grid_pos_y: 1339670.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132007.25
      sim_grid_pos_y: 1339646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131788.62
      sim_grid_pos_y: 1339827.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1130688.88
      sim_grid_pos_y: 1339782.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1130632.62
      sim_grid_pos_y: 1340956
    }
    terrain_level_point {
      sim_grid_pos_x: 1130996
      sim_grid_pos_y: 1341182.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131286.62
      sim_grid_pos_y: 1342224
    }
    terrain_level_point {
      sim_grid_pos_x: 1131261.12
      sim_grid_pos_y: 1342419.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131481
      sim_grid_pos_y: 1343388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132821.38
      sim_grid_pos_y: 1344313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132988.25
      sim_grid_pos_y: 1344792.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133227.5
      sim_grid_pos_y: 1345207
    }
    terrain_level_point {
      sim_grid_pos_x: 1133425
      sim_grid_pos_y: 1345568.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133915
      sim_grid_pos_y: 1345585.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134073.75
      sim_grid_pos_y: 1345666.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134387.12
      sim_grid_pos_y: 1345947.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134365.25
      sim_grid_pos_y: 1346360.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134122
      sim_grid_pos_y: 1346858.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134761.62
      sim_grid_pos_y: 1347250.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136265
      sim_grid_pos_y: 1347226.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136632.62
      sim_grid_pos_y: 1346927
    }
    terrain_level_point {
      sim_grid_pos_x: 1136946
      sim_grid_pos_y: 1346512.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136638.25
      sim_grid_pos_y: 1346293.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136701.88
      sim_grid_pos_y: 1346241.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136884.75
      sim_grid_pos_y: 1346340.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136976
      sim_grid_pos_y: 1346103
    }
    terrain_level_point {
      sim_grid_pos_x: 1137144.62
      sim_grid_pos_y: 1346208.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1137461
      sim_grid_pos_y: 1345982.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1137481.38
      sim_grid_pos_y: 1345486.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1137515.25
      sim_grid_pos_y: 1344972.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1134311.38
      sim_grid_pos_y: 1338606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133414.25
      sim_grid_pos_y: 1338984.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133073.75
      sim_grid_pos_y: 1339350.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1132164.62
      sim_grid_pos_y: 1339649.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132001.25
      sim_grid_pos_y: 1339625.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1131781.62
      sim_grid_pos_y: 1339806.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1130669.38
      sim_grid_pos_y: 1339761.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1130611.62
      sim_grid_pos_y: 1340967
    }
    terrain_level_point {
      sim_grid_pos_x: 1130978.38
      sim_grid_pos_y: 1341195.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1131265.75
      sim_grid_pos_y: 1342225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1131240.38
      sim_grid_pos_y: 1342420.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1131462.75
      sim_grid_pos_y: 1343401.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132804.25
      sim_grid_pos_y: 1344326.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1132969.5
      sim_grid_pos_y: 1344801.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133209.5
      sim_grid_pos_y: 1345217
    }
    terrain_level_point {
      sim_grid_pos_x: 1133412.62
      sim_grid_pos_y: 1345588.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133909.75
      sim_grid_pos_y: 1345606
    }
    terrain_level_point {
      sim_grid_pos_x: 1134062.12
      sim_grid_pos_y: 1345683.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134366.12
      sim_grid_pos_y: 1345955.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134345
      sim_grid_pos_y: 1346354.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134095.38
      sim_grid_pos_y: 1346866
    }
    terrain_level_point {
      sim_grid_pos_x: 1134756
      sim_grid_pos_y: 1347271.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1136272.5
      sim_grid_pos_y: 1347247.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136647.5
      sim_grid_pos_y: 1346941.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136975
      sim_grid_pos_y: 1346507.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136672
      sim_grid_pos_y: 1346292
    }
    terrain_level_point {
      sim_grid_pos_x: 1136704.12
      sim_grid_pos_y: 1346265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136895.5
      sim_grid_pos_y: 1346369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136986.12
      sim_grid_pos_y: 1346133.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1137145.5
      sim_grid_pos_y: 1346233
    }
    terrain_level_point {
      sim_grid_pos_x: 1137481.12
      sim_grid_pos_y: 1345992.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1137501.88
      sim_grid_pos_y: 1345487.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1137536.12
      sim_grid_pos_y: 1344968.62
    }
  }
}
terrain_level_data {
  terrain_level: 3
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1136730.12
      sim_grid_pos_y: 1341993.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1138203.75
      sim_grid_pos_y: 1341307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1138257.75
      sim_grid_pos_y: 1341408.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136767.62
      sim_grid_pos_y: 1342130.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1138285.88
      sim_grid_pos_y: 1341417.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136754.38
      sim_grid_pos_y: 1342159.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136705.88
      sim_grid_pos_y: 1341982
    }
    terrain_level_point {
      sim_grid_pos_x: 1138212.62
      sim_grid_pos_y: 1341281
    }
  }
}
