terrain_level_data {
  terrain_level: 36
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 485288.594
      sim_grid_pos_y: 2166176.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485317.531
      sim_grid_pos_y: 2166037
    }
    terrain_level_point {
      sim_grid_pos_x: 485486.531
      sim_grid_pos_y: 2165726
    }
    terrain_level_point {
      sim_grid_pos_x: 485805.281
      sim_grid_pos_y: 2165501.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486230.875
      sim_grid_pos_y: 2164945.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486911.156
      sim_grid_pos_y: 2165362.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487295.562
      sim_grid_pos_y: 2165504
    }
    terrain_level_point {
      sim_grid_pos_x: 486968.219
      sim_grid_pos_y: 2166887.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486661.844
      sim_grid_pos_y: 2166955.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486584.656
      sim_grid_pos_y: 2166823.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486271.5
      sim_grid_pos_y: 2166877.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 486924.594
      sim_grid_pos_y: 2165335
    }
    terrain_level_point {
      sim_grid_pos_x: 487331.781
      sim_grid_pos_y: 2165484.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486993.688
      sim_grid_pos_y: 2166913
    }
    terrain_level_point {
      sim_grid_pos_x: 486646.625
      sim_grid_pos_y: 2166990.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486568.875
      sim_grid_pos_y: 2166857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486264.062
      sim_grid_pos_y: 2166910.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485254.375
      sim_grid_pos_y: 2166189.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485288.344
      sim_grid_pos_y: 2166026.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485462.938
      sim_grid_pos_y: 2165705
    }
    terrain_level_point {
      sim_grid_pos_x: 485783.719
      sim_grid_pos_y: 2165479.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486223.312
      sim_grid_pos_y: 2164905
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 486938.094
      sim_grid_pos_y: 2165307.25
    }
    terrain_level_point {
      sim_grid_pos_x: 487368
      sim_grid_pos_y: 2165465
    }
    terrain_level_point {
      sim_grid_pos_x: 487019.188
      sim_grid_pos_y: 2166939
    }
    terrain_level_point {
      sim_grid_pos_x: 486631.438
      sim_grid_pos_y: 2167025.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486553.094
      sim_grid_pos_y: 2166891.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486256.656
      sim_grid_pos_y: 2166942.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485220.188
      sim_grid_pos_y: 2166203
    }
    terrain_level_point {
      sim_grid_pos_x: 485259.156
      sim_grid_pos_y: 2166015.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485439.344
      sim_grid_pos_y: 2165684
    }
    terrain_level_point {
      sim_grid_pos_x: 485762.188
      sim_grid_pos_y: 2165456.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486215.75
      sim_grid_pos_y: 2164864.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 486951.562
      sim_grid_pos_y: 2165279.25
    }
    terrain_level_point {
      sim_grid_pos_x: 487404.188
      sim_grid_pos_y: 2165445.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487044.688
      sim_grid_pos_y: 2166964.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486616.219
      sim_grid_pos_y: 2167060.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486537.344
      sim_grid_pos_y: 2166925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486249.219
      sim_grid_pos_y: 2166975.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485186
      sim_grid_pos_y: 2166216.5
    }
    terrain_level_point {
      sim_grid_pos_x: 485229.969
      sim_grid_pos_y: 2166005
    }
    terrain_level_point {
      sim_grid_pos_x: 485415.75
      sim_grid_pos_y: 2165662.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485740.625
      sim_grid_pos_y: 2165434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486208.188
      sim_grid_pos_y: 2164823.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 486965.031
      sim_grid_pos_y: 2165251.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487440.406
      sim_grid_pos_y: 2165426
    }
    terrain_level_point {
      sim_grid_pos_x: 487070.188
      sim_grid_pos_y: 2166990.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486601.031
      sim_grid_pos_y: 2167095.25
    }
    terrain_level_point {
      sim_grid_pos_x: 486521.562
      sim_grid_pos_y: 2166959.5
    }
    terrain_level_point {
      sim_grid_pos_x: 486241.812
      sim_grid_pos_y: 2167007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485151.812
      sim_grid_pos_y: 2166229.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485200.781
      sim_grid_pos_y: 2165994.25
    }
    terrain_level_point {
      sim_grid_pos_x: 485392.156
      sim_grid_pos_y: 2165641.75
    }
    terrain_level_point {
      sim_grid_pos_x: 485719.094
      sim_grid_pos_y: 2165411.75
    }
    terrain_level_point {
      sim_grid_pos_x: 486200.625
      sim_grid_pos_y: 2164783
    }
  }
}
