terrain_level_data {
  terrain_level: 640
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1669753.12
      sim_grid_pos_y: 1565449.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1670260.12
      sim_grid_pos_y: 1565775.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1671370.75
      sim_grid_pos_y: 1565958
    }
    terrain_level_point {
      sim_grid_pos_x: 1672017.25
      sim_grid_pos_y: 1566167.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1672354.12
      sim_grid_pos_y: 1.5659e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1672915.75
      sim_grid_pos_y: 1565831.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1673309
      sim_grid_pos_y: 1565966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673472.62
      sim_grid_pos_y: 1565795.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673241.5
      sim_grid_pos_y: 1565563.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1673364.12
      sim_grid_pos_y: 1565240.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1673678.62
      sim_grid_pos_y: 1564835.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1673044.5
      sim_grid_pos_y: 1564752.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1672896
      sim_grid_pos_y: 1564579.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1672433.75
      sim_grid_pos_y: 1565008.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1672373.62
      sim_grid_pos_y: 1565242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1672125.5
      sim_grid_pos_y: 1565319.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1671934
      sim_grid_pos_y: 1565509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1671684.62
      sim_grid_pos_y: 1565581.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1671438.75
      sim_grid_pos_y: 1565448.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1670921.62
      sim_grid_pos_y: 1565349.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1670603.5
      sim_grid_pos_y: 1565316.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1670292.12
      sim_grid_pos_y: 1565261
    }
    terrain_level_point {
      sim_grid_pos_x: 1670069.62
      sim_grid_pos_y: 1564753.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1669793.12
      sim_grid_pos_y: 1564887.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1672898.5
      sim_grid_pos_y: 1564535.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1672406.12
      sim_grid_pos_y: 1564991.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1672348.12
      sim_grid_pos_y: 1565218.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1672109.12
      sim_grid_pos_y: 1565292.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1671918
      sim_grid_pos_y: 1565482.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1671688.12
      sim_grid_pos_y: 1565548.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1671449.25
      sim_grid_pos_y: 1565419.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1670926.12
      sim_grid_pos_y: 1565318.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1670607.88
      sim_grid_pos_y: 1565286.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1670313.75
      sim_grid_pos_y: 1565233.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1670084.88
      sim_grid_pos_y: 1564711.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1669763.75
      sim_grid_pos_y: 1564867.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1669721.25
      sim_grid_pos_y: 1565465.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1670248.88
      sim_grid_pos_y: 1565805.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1671363.5
      sim_grid_pos_y: 1565987.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1672023.5
      sim_grid_pos_y: 1566201.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1672366.38
      sim_grid_pos_y: 1565929.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1672912.5
      sim_grid_pos_y: 1565862.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1673317.62
      sim_grid_pos_y: 1566001.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1673515.62
      sim_grid_pos_y: 1565794.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1673277.25
      sim_grid_pos_y: 1565555.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1673391.25
      sim_grid_pos_y: 1565255.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1673713.88
      sim_grid_pos_y: 1564840.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1673700.25
      sim_grid_pos_y: 1564807.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1673060.12
      sim_grid_pos_y: 1564723.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1672901
      sim_grid_pos_y: 1564491
    }
    terrain_level_point {
      sim_grid_pos_x: 1672378.62
      sim_grid_pos_y: 1564975.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1672322.62
      sim_grid_pos_y: 1565194.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1672092.88
      sim_grid_pos_y: 1565265.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1671901.88
      sim_grid_pos_y: 1565454.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1671691.75
      sim_grid_pos_y: 1565515.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1671459.75
      sim_grid_pos_y: 1565390.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1670930.62
      sim_grid_pos_y: 1565288.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1670612
      sim_grid_pos_y: 1565255.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1670335.25
      sim_grid_pos_y: 1565206.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1670100.25
      sim_grid_pos_y: 1564670.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1669734.25
      sim_grid_pos_y: 1564847.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1669689.25
      sim_grid_pos_y: 1565481.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1670237.5
      sim_grid_pos_y: 1565834.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1671356.25
      sim_grid_pos_y: 1566017.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1672029.62
      sim_grid_pos_y: 1566236
    }
    terrain_level_point {
      sim_grid_pos_x: 1672378.75
      sim_grid_pos_y: 1565959
    }
    terrain_level_point {
      sim_grid_pos_x: 1672909.12
      sim_grid_pos_y: 1565894
    }
    terrain_level_point {
      sim_grid_pos_x: 1673326.25
      sim_grid_pos_y: 1566037.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1673558.62
      sim_grid_pos_y: 1565794.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1673313.12
      sim_grid_pos_y: 1565548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673418.38
      sim_grid_pos_y: 1565271.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1673749
      sim_grid_pos_y: 1564845.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1673722
      sim_grid_pos_y: 1564779.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1673075.75
      sim_grid_pos_y: 1564694.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1672903.5
      sim_grid_pos_y: 1564446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1672351
      sim_grid_pos_y: 1564959
    }
    terrain_level_point {
      sim_grid_pos_x: 1672297
      sim_grid_pos_y: 1565169.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1672076.5
      sim_grid_pos_y: 1565238.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1671885.88
      sim_grid_pos_y: 1565427.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1671695.25
      sim_grid_pos_y: 1565482.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1671470.25
      sim_grid_pos_y: 1565360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1670935.12
      sim_grid_pos_y: 1565257.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1670616.5
      sim_grid_pos_y: 1565225.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1670356.88
      sim_grid_pos_y: 1565178.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1670115.62
      sim_grid_pos_y: 1564628.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1669704.88
      sim_grid_pos_y: 1564827.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1669657.25
      sim_grid_pos_y: 1565497.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1670226.25
      sim_grid_pos_y: 1565863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1671349
      sim_grid_pos_y: 1566047.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1672035.88
      sim_grid_pos_y: 1566270.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1672391.12
      sim_grid_pos_y: 1565988.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1672905.88
      sim_grid_pos_y: 1565925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1673334.88
      sim_grid_pos_y: 1566072.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1673601.62
      sim_grid_pos_y: 1565793.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1673348.88
      sim_grid_pos_y: 1565540.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1673445.5
      sim_grid_pos_y: 1565286.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673784.25
      sim_grid_pos_y: 1564850.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673743.62
      sim_grid_pos_y: 1564751.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1673091.5
      sim_grid_pos_y: 1564665.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1672906
      sim_grid_pos_y: 1564402.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1672323.5
      sim_grid_pos_y: 1564942.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1672271.5
      sim_grid_pos_y: 1565145.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1672060.25
      sim_grid_pos_y: 1565211.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1671869.75
      sim_grid_pos_y: 1.5654e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1671698.88
      sim_grid_pos_y: 1565449.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1671480.62
      sim_grid_pos_y: 1565331.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1670939.62
      sim_grid_pos_y: 1565227.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1670620.62
      sim_grid_pos_y: 1565194.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1670378.5
      sim_grid_pos_y: 1565151.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1670130.88
      sim_grid_pos_y: 1564587
    }
    terrain_level_point {
      sim_grid_pos_x: 1669675.38
      sim_grid_pos_y: 1564808
    }
    terrain_level_point {
      sim_grid_pos_x: 1669625.25
      sim_grid_pos_y: 1565513.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1670215
      sim_grid_pos_y: 1565893
    }
    terrain_level_point {
      sim_grid_pos_x: 1671341.62
      sim_grid_pos_y: 1566077.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1672042.12
      sim_grid_pos_y: 1566304.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1672403.38
      sim_grid_pos_y: 1566017.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1672902.62
      sim_grid_pos_y: 1565956.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1673343.5
      sim_grid_pos_y: 1566108.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1673644.62
      sim_grid_pos_y: 1565793.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1673384.62
      sim_grid_pos_y: 1565533
    }
    terrain_level_point {
      sim_grid_pos_x: 1673472.62
      sim_grid_pos_y: 1565301.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1673819.5
      sim_grid_pos_y: 1564855
    }
    terrain_level_point {
      sim_grid_pos_x: 1673765.38
      sim_grid_pos_y: 1564723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673107.12
      sim_grid_pos_y: 1564636.25
    }
  }
}
