terrain_level_data {
  terrain_level: 122
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2889413.25
      sim_grid_pos_y: 586347.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2889163
      sim_grid_pos_y: 585210.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2888839
      sim_grid_pos_y: 582919.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2888847.75
      sim_grid_pos_y: 579939.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2888989.5
      sim_grid_pos_y: 576721.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2889148.25
      sim_grid_pos_y: 575757.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2888650.25
      sim_grid_pos_y: 574054.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2887538.25
      sim_grid_pos_y: 572196.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2888727.25
      sim_grid_pos_y: 571182.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2890152.5
      sim_grid_pos_y: 572734.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2890698.5
      sim_grid_pos_y: 573515.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2890949
      sim_grid_pos_y: 574836.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2890083.25
      sim_grid_pos_y: 579189.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2890106.25
      sim_grid_pos_y: 581479
    }
    terrain_level_point {
      sim_grid_pos_x: 2890979
      sim_grid_pos_y: 586616.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2891671.75
      sim_grid_pos_y: 588561.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2893079.75
      sim_grid_pos_y: 590408.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2897450.25
      sim_grid_pos_y: 592344.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2896514.25
      sim_grid_pos_y: 594180.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2893479.75
      sim_grid_pos_y: 592670.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2892460.75
      sim_grid_pos_y: 592319.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2892257.5
      sim_grid_pos_y: 592462
    }
    terrain_level_point {
      sim_grid_pos_x: 2890836.25
      sim_grid_pos_y: 591513.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2890683.25
      sim_grid_pos_y: 590290.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2890135
      sim_grid_pos_y: 589364.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2889739.5
      sim_grid_pos_y: 588175.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2890176.75
      sim_grid_pos_y: 572714.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2890727.5
      sim_grid_pos_y: 573502.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2890980.25
      sim_grid_pos_y: 574836.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2890114
      sim_grid_pos_y: 579192.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2890137
      sim_grid_pos_y: 581476.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2891008.75
      sim_grid_pos_y: 586608.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2891699.25
      sim_grid_pos_y: 588546.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2893099.5
      sim_grid_pos_y: 590383.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2897492.25
      sim_grid_pos_y: 592330
    }
    terrain_level_point {
      sim_grid_pos_x: 2896528
      sim_grid_pos_y: 594222.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2893467.75
      sim_grid_pos_y: 592699.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2892465.5
      sim_grid_pos_y: 592353.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2892257.75
      sim_grid_pos_y: 592499.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2890807.5
      sim_grid_pos_y: 591531.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2890653.5
      sim_grid_pos_y: 590301.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2890106.75
      sim_grid_pos_y: 589377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2889709.75
      sim_grid_pos_y: 588183
    }
    terrain_level_point {
      sim_grid_pos_x: 2889383
      sim_grid_pos_y: 586353.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2889132.75
      sim_grid_pos_y: 585215.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2888808.25
      sim_grid_pos_y: 582921.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2888817
      sim_grid_pos_y: 579938.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2888958.75
      sim_grid_pos_y: 576718.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2889116.75
      sim_grid_pos_y: 575759.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2888622
      sim_grid_pos_y: 574067
    }
    terrain_level_point {
      sim_grid_pos_x: 2887498.5
      sim_grid_pos_y: 572190.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2888729.75
      sim_grid_pos_y: 571140.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2890200.75
      sim_grid_pos_y: 572695.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2890756.5
      sim_grid_pos_y: 573490.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2891011.5
      sim_grid_pos_y: 574836.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2890144.75
      sim_grid_pos_y: 579195.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2890167.75
      sim_grid_pos_y: 581473.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2891038.75
      sim_grid_pos_y: 586600.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2891726.5
      sim_grid_pos_y: 588532
    }
    terrain_level_point {
      sim_grid_pos_x: 2893119.25
      sim_grid_pos_y: 590358.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2897534.5
      sim_grid_pos_y: 592315
    }
    terrain_level_point {
      sim_grid_pos_x: 2896541.5
      sim_grid_pos_y: 594263.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2893455.75
      sim_grid_pos_y: 592727.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2892470.25
      sim_grid_pos_y: 592387.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2892258.25
      sim_grid_pos_y: 592536.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2890778.75
      sim_grid_pos_y: 591549.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2890623.75
      sim_grid_pos_y: 590311.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2890078.75
      sim_grid_pos_y: 589390.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2889679.75
      sim_grid_pos_y: 588190.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2889353
      sim_grid_pos_y: 586359.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2889102.5
      sim_grid_pos_y: 585221.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2888777.5
      sim_grid_pos_y: 582924
    }
    terrain_level_point {
      sim_grid_pos_x: 2888786.25
      sim_grid_pos_y: 579937.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2888928
      sim_grid_pos_y: 576715
    }
    terrain_level_point {
      sim_grid_pos_x: 2889085.25
      sim_grid_pos_y: 575761.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2888593.5
      sim_grid_pos_y: 574079.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2887458.75
      sim_grid_pos_y: 572183.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2888732.5
      sim_grid_pos_y: 571097.562
    }
  }
}
