terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 452728.125
      sim_grid_pos_y: 2149046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452493.25
      sim_grid_pos_y: 2149419.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452998.312
      sim_grid_pos_y: 2149772.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452684.406
      sim_grid_pos_y: 2150211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452224.844
      sim_grid_pos_y: 2150342.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452050.125
      sim_grid_pos_y: 2150461.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451956.531
      sim_grid_pos_y: 2150697.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452214.969
      sim_grid_pos_y: 2151121.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452658.844
      sim_grid_pos_y: 2151375.75
    }
    terrain_level_point {
      sim_grid_pos_x: 452956.094
      sim_grid_pos_y: 2151497.75
    }
    terrain_level_point {
      sim_grid_pos_x: 453466.719
      sim_grid_pos_y: 2151361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 454055.281
      sim_grid_pos_y: 2150448
    }
    terrain_level_point {
      sim_grid_pos_x: 454119.812
      sim_grid_pos_y: 2150039.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 452719.438
      sim_grid_pos_y: 2149002.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452451.625
      sim_grid_pos_y: 2149428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452955.219
      sim_grid_pos_y: 2149780.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452665.656
      sim_grid_pos_y: 2150185
    }
    terrain_level_point {
      sim_grid_pos_x: 452211.625
      sim_grid_pos_y: 2150314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452025.031
      sim_grid_pos_y: 2150441.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451922.281
      sim_grid_pos_y: 2150700.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452192.844
      sim_grid_pos_y: 2151144.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452645.281
      sim_grid_pos_y: 2151403.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452953.969
      sim_grid_pos_y: 2151530.25
    }
    terrain_level_point {
      sim_grid_pos_x: 453486.156
      sim_grid_pos_y: 2151388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 454084.656
      sim_grid_pos_y: 2150459.25
    }
    terrain_level_point {
      sim_grid_pos_x: 454153.156
      sim_grid_pos_y: 2150026
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 452710.781
      sim_grid_pos_y: 2148958.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452410
      sim_grid_pos_y: 2149436.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452912.125
      sim_grid_pos_y: 2149787.5
    }
    terrain_level_point {
      sim_grid_pos_x: 452646.906
      sim_grid_pos_y: 2150158.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452198.406
      sim_grid_pos_y: 2150286
    }
    terrain_level_point {
      sim_grid_pos_x: 451999.906
      sim_grid_pos_y: 2150421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451888.031
      sim_grid_pos_y: 2150703.25
    }
    terrain_level_point {
      sim_grid_pos_x: 452170.688
      sim_grid_pos_y: 2151167
    }
    terrain_level_point {
      sim_grid_pos_x: 452631.75
      sim_grid_pos_y: 2151431
    }
    terrain_level_point {
      sim_grid_pos_x: 452951.875
      sim_grid_pos_y: 2151562.5
    }
    terrain_level_point {
      sim_grid_pos_x: 453505.562
      sim_grid_pos_y: 2151415.25
    }
    terrain_level_point {
      sim_grid_pos_x: 454114.031
      sim_grid_pos_y: 2150470.25
    }
    terrain_level_point {
      sim_grid_pos_x: 454186.5
      sim_grid_pos_y: 2150012
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 451829.094
      sim_grid_pos_y: 2149680.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451696.031
      sim_grid_pos_y: 2149935.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451476.562
      sim_grid_pos_y: 2149825.25
    }
    terrain_level_point {
      sim_grid_pos_x: 451027.406
      sim_grid_pos_y: 2150570.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450015.875
      sim_grid_pos_y: 2151779.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449307.531
      sim_grid_pos_y: 2151798
    }
    terrain_level_point {
      sim_grid_pos_x: 449332.656
      sim_grid_pos_y: 2151033.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449384.031
      sim_grid_pos_y: 2150739.75
    }
    terrain_level_point {
      sim_grid_pos_x: 449871.562
      sim_grid_pos_y: 2149919.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449871.281
      sim_grid_pos_y: 2149428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450051.125
      sim_grid_pos_y: 2149152.75
    }
    terrain_level_point {
      sim_grid_pos_x: 450196.25
      sim_grid_pos_y: 2149217.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450434.781
      sim_grid_pos_y: 2148747
    }
    terrain_level_point {
      sim_grid_pos_x: 451050.438
      sim_grid_pos_y: 2149051.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450988.656
      sim_grid_pos_y: 2149182.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 451091.125
      sim_grid_pos_y: 2149037
    }
    terrain_level_point {
      sim_grid_pos_x: 451028.406
      sim_grid_pos_y: 2149170.25
    }
    terrain_level_point {
      sim_grid_pos_x: 451869.844
      sim_grid_pos_y: 2149669
    }
    terrain_level_point {
      sim_grid_pos_x: 451709.281
      sim_grid_pos_y: 2149976.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451488.219
      sim_grid_pos_y: 2149865.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451052.5
      sim_grid_pos_y: 2150588
    }
    terrain_level_point {
      sim_grid_pos_x: 450030.562
      sim_grid_pos_y: 2151809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449275.719
      sim_grid_pos_y: 2151829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449302
      sim_grid_pos_y: 2151030.25
    }
    terrain_level_point {
      sim_grid_pos_x: 449354.688
      sim_grid_pos_y: 2150729
    }
    terrain_level_point {
      sim_grid_pos_x: 449840.812
      sim_grid_pos_y: 2149911
    }
    terrain_level_point {
      sim_grid_pos_x: 449840.531
      sim_grid_pos_y: 2149419
    }
    terrain_level_point {
      sim_grid_pos_x: 450039.719
      sim_grid_pos_y: 2149114
    }
    terrain_level_point {
      sim_grid_pos_x: 450182.062
      sim_grid_pos_y: 2149177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450421.125
      sim_grid_pos_y: 2148706
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 451131.781
      sim_grid_pos_y: 2149022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451068.125
      sim_grid_pos_y: 2149158
    }
    terrain_level_point {
      sim_grid_pos_x: 451910.625
      sim_grid_pos_y: 2149657.5
    }
    terrain_level_point {
      sim_grid_pos_x: 451722.531
      sim_grid_pos_y: 2150017.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451499.844
      sim_grid_pos_y: 2149905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 451077.625
      sim_grid_pos_y: 2150606
    }
    terrain_level_point {
      sim_grid_pos_x: 450045.25
      sim_grid_pos_y: 2.15184e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 449243.906
      sim_grid_pos_y: 2151861
    }
    terrain_level_point {
      sim_grid_pos_x: 449271.344
      sim_grid_pos_y: 2151027
    }
    terrain_level_point {
      sim_grid_pos_x: 449325.375
      sim_grid_pos_y: 2150718
    }
    terrain_level_point {
      sim_grid_pos_x: 449810.062
      sim_grid_pos_y: 2149902.5
    }
    terrain_level_point {
      sim_grid_pos_x: 449809.75
      sim_grid_pos_y: 2.14941e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 450028.281
      sim_grid_pos_y: 2149075.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450167.875
      sim_grid_pos_y: 2149137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 450407.438
      sim_grid_pos_y: 2148664.75
    }
  }
}
