terrain_level_data {
  terrain_level: 315
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2568773.5
      sim_grid_pos_y: 2181477.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2563960.25
      sim_grid_pos_y: 2180186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2561087
      sim_grid_pos_y: 2179270.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2561321.5
      sim_grid_pos_y: 2178020.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2565426
      sim_grid_pos_y: 2178616
    }
    terrain_level_point {
      sim_grid_pos_x: 2567771.75
      sim_grid_pos_y: 2179230.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2565452.75
      sim_grid_pos_y: 2178485.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2567867.5
      sim_grid_pos_y: 2179118
    }
    terrain_level_point {
      sim_grid_pos_x: 2568929.5
      sim_grid_pos_y: 2181499.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2568820.25
      sim_grid_pos_y: 2181627.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2563922.75
      sim_grid_pos_y: 2180314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2560934.25
      sim_grid_pos_y: 2179362
    }
    terrain_level_point {
      sim_grid_pos_x: 2561214.25
      sim_grid_pos_y: 2177870.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2565479.25
      sim_grid_pos_y: 2178354.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2567963
      sim_grid_pos_y: 2179005.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2569085.5
      sim_grid_pos_y: 2181522.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2568867
      sim_grid_pos_y: 2181778.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2563885.25
      sim_grid_pos_y: 2180442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2560781.75
      sim_grid_pos_y: 2179453.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2561106.75
      sim_grid_pos_y: 2177720.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2565505.75
      sim_grid_pos_y: 2178223.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2568058.75
      sim_grid_pos_y: 2178892.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2569241.5
      sim_grid_pos_y: 2181545
    }
    terrain_level_point {
      sim_grid_pos_x: 2568913.75
      sim_grid_pos_y: 2181928.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2563847.75
      sim_grid_pos_y: 2180570.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2560629
      sim_grid_pos_y: 2179544.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2560999.25
      sim_grid_pos_y: 2.17757e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2565532.25
      sim_grid_pos_y: 2178092.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2568154.5
      sim_grid_pos_y: 2178779.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2569397.5
      sim_grid_pos_y: 2181567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2568960.5
      sim_grid_pos_y: 2182079.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2563810.25
      sim_grid_pos_y: 2180698.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2560476.25
      sim_grid_pos_y: 2179635.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2560892
      sim_grid_pos_y: 2177419.75
    }
  }
}
