terrain_level_data {
  terrain_level: 7
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 33806.3
      sim_grid_pos_y: 2671059.25
    }
    terrain_level_point {
      sim_grid_pos_x: 32183.6875
      sim_grid_pos_y: 2671084
    }
    terrain_level_point {
      sim_grid_pos_x: 30581.3633
      sim_grid_pos_y: 2667869.25
    }
    terrain_level_point {
      sim_grid_pos_x: 30847.3184
      sim_grid_pos_y: 2667785
    }
    terrain_level_point {
      sim_grid_pos_x: 30557.9082
      sim_grid_pos_y: 2667186.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30956.7656
      sim_grid_pos_y: 2666236.25
    }
    terrain_level_point {
      sim_grid_pos_x: 29580.6191
      sim_grid_pos_y: 2665609.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30625.5566
      sim_grid_pos_y: 2663823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30773.1152
      sim_grid_pos_y: 2663811.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30933.3145
      sim_grid_pos_y: 2661909.75
    }
    terrain_level_point {
      sim_grid_pos_x: 32843.0156
      sim_grid_pos_y: 2662156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 32986.6328
      sim_grid_pos_y: 2666223.25
    }
    terrain_level_point {
      sim_grid_pos_x: 37830.0117
      sim_grid_pos_y: 2666083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 38755.7266
      sim_grid_pos_y: 2670890.5
    }
    terrain_level_point {
      sim_grid_pos_x: 36424.5625
      sim_grid_pos_y: 2670946.5
    }
    terrain_level_point {
      sim_grid_pos_x: 35910.3828
      sim_grid_pos_y: 2668274.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33776.0781
      sim_grid_pos_y: 2668361.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 32862.8945
      sim_grid_pos_y: 2662138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33006.4062
      sim_grid_pos_y: 2666202.25
    }
    terrain_level_point {
      sim_grid_pos_x: 37846.8555
      sim_grid_pos_y: 2666062.25
    }
    terrain_level_point {
      sim_grid_pos_x: 38780.4453
      sim_grid_pos_y: 2670910.5
    }
    terrain_level_point {
      sim_grid_pos_x: 36407.707
      sim_grid_pos_y: 2670967.5
    }
    terrain_level_point {
      sim_grid_pos_x: 35893.5742
      sim_grid_pos_y: 2668295.75
    }
    terrain_level_point {
      sim_grid_pos_x: 33796.7969
      sim_grid_pos_y: 2668381
    }
    terrain_level_point {
      sim_grid_pos_x: 33827.0352
      sim_grid_pos_y: 2671079.25
    }
    terrain_level_point {
      sim_grid_pos_x: 32171.0957
      sim_grid_pos_y: 2671104.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30552.3164
      sim_grid_pos_y: 2667857
    }
    terrain_level_point {
      sim_grid_pos_x: 30818.5449
      sim_grid_pos_y: 2667772.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30535.416
      sim_grid_pos_y: 2667187.25
    }
    terrain_level_point {
      sim_grid_pos_x: 30930.166
      sim_grid_pos_y: 2666246.5
    }
    terrain_level_point {
      sim_grid_pos_x: 29551.4453
      sim_grid_pos_y: 2665619
    }
    terrain_level_point {
      sim_grid_pos_x: 30613.2559
      sim_grid_pos_y: 2663803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30754.1465
      sim_grid_pos_y: 2663792.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30914.6855
      sim_grid_pos_y: 2661886.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 32882.7773
      sim_grid_pos_y: 2662120.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33026.1758
      sim_grid_pos_y: 2666181
    }
    terrain_level_point {
      sim_grid_pos_x: 37863.6953
      sim_grid_pos_y: 2666041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 38805.1562
      sim_grid_pos_y: 2670930.25
    }
    terrain_level_point {
      sim_grid_pos_x: 36390.8555
      sim_grid_pos_y: 2670988.5
    }
    terrain_level_point {
      sim_grid_pos_x: 35876.7852
      sim_grid_pos_y: 2668317
    }
    terrain_level_point {
      sim_grid_pos_x: 33817.5273
      sim_grid_pos_y: 2668400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 33847.7773
      sim_grid_pos_y: 2671099.5
    }
    terrain_level_point {
      sim_grid_pos_x: 32158.4961
      sim_grid_pos_y: 2671125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30523.2754
      sim_grid_pos_y: 2667844.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30789.7656
      sim_grid_pos_y: 2667760.25
    }
    terrain_level_point {
      sim_grid_pos_x: 30512.9258
      sim_grid_pos_y: 2667187.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30903.5547
      sim_grid_pos_y: 2666257
    }
    terrain_level_point {
      sim_grid_pos_x: 29522.2754
      sim_grid_pos_y: 2665628.25
    }
    terrain_level_point {
      sim_grid_pos_x: 30600.9453
      sim_grid_pos_y: 2663784.25
    }
    terrain_level_point {
      sim_grid_pos_x: 30735.166
      sim_grid_pos_y: 2663773.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30896.0449
      sim_grid_pos_y: 2661863.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 32902.6562
      sim_grid_pos_y: 2662102.25
    }
    terrain_level_point {
      sim_grid_pos_x: 33045.957
      sim_grid_pos_y: 2.66616e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 37880.5273
      sim_grid_pos_y: 2666020.25
    }
    terrain_level_point {
      sim_grid_pos_x: 38829.875
      sim_grid_pos_y: 2670950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 36373.9961
      sim_grid_pos_y: 2671009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 35859.9766
      sim_grid_pos_y: 2668338
    }
    terrain_level_point {
      sim_grid_pos_x: 33838.2461
      sim_grid_pos_y: 2668420.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33868.5039
      sim_grid_pos_y: 2671119.75
    }
    terrain_level_point {
      sim_grid_pos_x: 32145.9062
      sim_grid_pos_y: 2671146
    }
    terrain_level_point {
      sim_grid_pos_x: 30494.2266
      sim_grid_pos_y: 2667832.25
    }
    terrain_level_point {
      sim_grid_pos_x: 30760.9961
      sim_grid_pos_y: 2667747.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30490.4355
      sim_grid_pos_y: 2667188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30876.9453
      sim_grid_pos_y: 2666267.5
    }
    terrain_level_point {
      sim_grid_pos_x: 29493.1152
      sim_grid_pos_y: 2665637.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30588.6465
      sim_grid_pos_y: 2663764.75
    }
    terrain_level_point {
      sim_grid_pos_x: 30716.1953
      sim_grid_pos_y: 2663754.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30877.416
      sim_grid_pos_y: 2661840.5
    }
  }
}
terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 28823.5078
      sim_grid_pos_y: 2667817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 31515.4219
      sim_grid_pos_y: 2673235.75
    }
    terrain_level_point {
      sim_grid_pos_x: 34067.6523
      sim_grid_pos_y: 2673748.75
    }
    terrain_level_point {
      sim_grid_pos_x: 33363.957
      sim_grid_pos_y: 2682730.5
    }
    terrain_level_point {
      sim_grid_pos_x: 32706.9297
      sim_grid_pos_y: 2682479
    }
    terrain_level_point {
      sim_grid_pos_x: 31503.0977
      sim_grid_pos_y: 2684431.25
    }
    terrain_level_point {
      sim_grid_pos_x: 31732.9648
      sim_grid_pos_y: 2685234.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31566.0469
      sim_grid_pos_y: 2.68546e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 30397.2363
      sim_grid_pos_y: 2686254.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28372.459
      sim_grid_pos_y: 2685971.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28642.2812
      sim_grid_pos_y: 2683522.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28052.9902
      sim_grid_pos_y: 2682846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26485.2031
      sim_grid_pos_y: 2682641.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26374.9297
      sim_grid_pos_y: 2683342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26810.3398
      sim_grid_pos_y: 2683458.75
    }
    terrain_level_point {
      sim_grid_pos_x: 27158.8184
      sim_grid_pos_y: 2683936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 26956.0938
      sim_grid_pos_y: 2685748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 23686.0293
      sim_grid_pos_y: 2685285
    }
    terrain_level_point {
      sim_grid_pos_x: 23452.1445
      sim_grid_pos_y: 2682785.5
    }
    terrain_level_point {
      sim_grid_pos_x: 24066.3555
      sim_grid_pos_y: 2681617
    }
    terrain_level_point {
      sim_grid_pos_x: 25248.5527
      sim_grid_pos_y: 2681434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 26678.4648
      sim_grid_pos_y: 2679482
    }
    terrain_level_point {
      sim_grid_pos_x: 28935.9961
      sim_grid_pos_y: 2676940.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28667.3086
      sim_grid_pos_y: 2675925
    }
    terrain_level_point {
      sim_grid_pos_x: 28757.7578
      sim_grid_pos_y: 2675653.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28800.3047
      sim_grid_pos_y: 2675027.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28979.541
      sim_grid_pos_y: 2674654.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28778.2754
      sim_grid_pos_y: 2673951
    }
    terrain_level_point {
      sim_grid_pos_x: 28728.4688
      sim_grid_pos_y: 2673134.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28679.8359
      sim_grid_pos_y: 2672370.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28510.7812
      sim_grid_pos_y: 2671688.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28230.2852
      sim_grid_pos_y: 2671605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28221.0508
      sim_grid_pos_y: 2670949.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28529.1914
      sim_grid_pos_y: 2670738.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28307.0488
      sim_grid_pos_y: 2670250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28110.8516
      sim_grid_pos_y: 2669551.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28064.8984
      sim_grid_pos_y: 2669094.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28124.6133
      sim_grid_pos_y: 2668528
    }
    terrain_level_point {
      sim_grid_pos_x: 28144.9336
      sim_grid_pos_y: 2667333.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28230.1953
      sim_grid_pos_y: 2666958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28591.9746
      sim_grid_pos_y: 2666797.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28790.5176
      sim_grid_pos_y: 2667037
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 28820.8047
      sim_grid_pos_y: 2667025.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28853.9648
      sim_grid_pos_y: 2667809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31536.2754
      sim_grid_pos_y: 2673208.5
    }
    terrain_level_point {
      sim_grid_pos_x: 34100.4453
      sim_grid_pos_y: 2673724
    }
    terrain_level_point {
      sim_grid_pos_x: 33391.4062
      sim_grid_pos_y: 2682773.75
    }
    terrain_level_point {
      sim_grid_pos_x: 32719.7266
      sim_grid_pos_y: 2682516.75
    }
    terrain_level_point {
      sim_grid_pos_x: 31536.4062
      sim_grid_pos_y: 2684435.75
    }
    terrain_level_point {
      sim_grid_pos_x: 31766.7051
      sim_grid_pos_y: 2685240.75
    }
    terrain_level_point {
      sim_grid_pos_x: 31587.6562
      sim_grid_pos_y: 2685482.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30404.7266
      sim_grid_pos_y: 2686286.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28338.6152
      sim_grid_pos_y: 2685998.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28610.2363
      sim_grid_pos_y: 2683532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28037.4766
      sim_grid_pos_y: 2682875.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26510.9355
      sim_grid_pos_y: 2682676.25
    }
    terrain_level_point {
      sim_grid_pos_x: 26409.6152
      sim_grid_pos_y: 2683320.25
    }
    terrain_level_point {
      sim_grid_pos_x: 26828.7754
      sim_grid_pos_y: 2683431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 27190.7148
      sim_grid_pos_y: 2683928
    }
    terrain_level_point {
      sim_grid_pos_x: 26983.1445
      sim_grid_pos_y: 2685783.5
    }
    terrain_level_point {
      sim_grid_pos_x: 23657.666
      sim_grid_pos_y: 2685312
    }
    terrain_level_point {
      sim_grid_pos_x: 23420.6758
      sim_grid_pos_y: 2682779.25
    }
    terrain_level_point {
      sim_grid_pos_x: 24046.3359
      sim_grid_pos_y: 2681589
    }
    terrain_level_point {
      sim_grid_pos_x: 25231.2852
      sim_grid_pos_y: 2681405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26654.5059
      sim_grid_pos_y: 2679462.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28902.0449
      sim_grid_pos_y: 2676932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28635.2266
      sim_grid_pos_y: 2675924
    }
    terrain_level_point {
      sim_grid_pos_x: 28727.3359
      sim_grid_pos_y: 2675647.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28770.0156
      sim_grid_pos_y: 2675019.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28946.7656
      sim_grid_pos_y: 2674652
    }
    terrain_level_point {
      sim_grid_pos_x: 28747.7754
      sim_grid_pos_y: 2673956
    }
    terrain_level_point {
      sim_grid_pos_x: 28697.7656
      sim_grid_pos_y: 2673136.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28649.3164
      sim_grid_pos_y: 2672375.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28485.1758
      sim_grid_pos_y: 2671713
    }
    terrain_level_point {
      sim_grid_pos_x: 28199.8457
      sim_grid_pos_y: 2671628.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28190.0664
      sim_grid_pos_y: 2670933.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28490.4863
      sim_grid_pos_y: 2670728
    }
    terrain_level_point {
      sim_grid_pos_x: 28278.0664
      sim_grid_pos_y: 2670261.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28080.5156
      sim_grid_pos_y: 2669557.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28033.9766
      sim_grid_pos_y: 2669094.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28093.8945
      sim_grid_pos_y: 2668526
    }
    terrain_level_point {
      sim_grid_pos_x: 28114.2363
      sim_grid_pos_y: 2667330.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28203.6152
      sim_grid_pos_y: 2666937
    }
    terrain_level_point {
      sim_grid_pos_x: 28600.7656
      sim_grid_pos_y: 2666759.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 28851.1055
      sim_grid_pos_y: 2667013.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28884.416
      sim_grid_pos_y: 2667801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 31557.1055
      sim_grid_pos_y: 2673181.25
    }
    terrain_level_point {
      sim_grid_pos_x: 34133.2461
      sim_grid_pos_y: 2673699.25
    }
    terrain_level_point {
      sim_grid_pos_x: 33418.8555
      sim_grid_pos_y: 2682817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 32732.5352
      sim_grid_pos_y: 2682554.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31569.7051
      sim_grid_pos_y: 2684440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31800.4551
      sim_grid_pos_y: 2685246.75
    }
    terrain_level_point {
      sim_grid_pos_x: 31609.2656
      sim_grid_pos_y: 2685505
    }
    terrain_level_point {
      sim_grid_pos_x: 30412.2148
      sim_grid_pos_y: 2686319
    }
    terrain_level_point {
      sim_grid_pos_x: 28304.7656
      sim_grid_pos_y: 2686024.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28578.1758
      sim_grid_pos_y: 2683542.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28021.9551
      sim_grid_pos_y: 2682904.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26536.666
      sim_grid_pos_y: 2682710.5
    }
    terrain_level_point {
      sim_grid_pos_x: 26444.3164
      sim_grid_pos_y: 2683297.5
    }
    terrain_level_point {
      sim_grid_pos_x: 26847.2148
      sim_grid_pos_y: 2683404.75
    }
    terrain_level_point {
      sim_grid_pos_x: 27222.6055
      sim_grid_pos_y: 2683919.5
    }
    terrain_level_point {
      sim_grid_pos_x: 27010.1855
      sim_grid_pos_y: 2685818.25
    }
    terrain_level_point {
      sim_grid_pos_x: 23629.3047
      sim_grid_pos_y: 2685339
    }
    terrain_level_point {
      sim_grid_pos_x: 23389.1953
      sim_grid_pos_y: 2682773
    }
    terrain_level_point {
      sim_grid_pos_x: 24026.3262
      sim_grid_pos_y: 2681561
    }
    terrain_level_point {
      sim_grid_pos_x: 25213.9766
      sim_grid_pos_y: 2681377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 26630.5469
      sim_grid_pos_y: 2679443.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28868.0859
      sim_grid_pos_y: 2676924
    }
    terrain_level_point {
      sim_grid_pos_x: 28603.1367
      sim_grid_pos_y: 2675923
    }
    terrain_level_point {
      sim_grid_pos_x: 28696.9258
      sim_grid_pos_y: 2675641.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28739.7363
      sim_grid_pos_y: 2675011.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28913.9648
      sim_grid_pos_y: 2674649.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28717.2852
      sim_grid_pos_y: 2673961.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28667.0762
      sim_grid_pos_y: 2673138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28618.8047
      sim_grid_pos_y: 2.67238e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 28459.5547
      sim_grid_pos_y: 2671737.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28169.416
      sim_grid_pos_y: 2671651.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28159.0859
      sim_grid_pos_y: 2670917.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28451.7852
      sim_grid_pos_y: 2670717.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28249.0957
      sim_grid_pos_y: 2670271.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28050.1855
      sim_grid_pos_y: 2669563
    }
    terrain_level_point {
      sim_grid_pos_x: 28003.0547
      sim_grid_pos_y: 2669094
    }
    terrain_level_point {
      sim_grid_pos_x: 28063.1562
      sim_grid_pos_y: 2668524.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28083.5352
      sim_grid_pos_y: 2667326.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28177.0254
      sim_grid_pos_y: 2666915.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28609.5547
      sim_grid_pos_y: 2666722
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 28881.3965
      sim_grid_pos_y: 2667002
    }
    terrain_level_point {
      sim_grid_pos_x: 28914.875
      sim_grid_pos_y: 2667793.75
    }
    terrain_level_point {
      sim_grid_pos_x: 31577.9453
      sim_grid_pos_y: 2673154.25
    }
    terrain_level_point {
      sim_grid_pos_x: 34166.0352
      sim_grid_pos_y: 2673674.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33446.3047
      sim_grid_pos_y: 2682860.75
    }
    terrain_level_point {
      sim_grid_pos_x: 32745.3359
      sim_grid_pos_y: 2682592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31603.0156
      sim_grid_pos_y: 2684445
    }
    terrain_level_point {
      sim_grid_pos_x: 31834.1953
      sim_grid_pos_y: 2685253
    }
    terrain_level_point {
      sim_grid_pos_x: 31630.8652
      sim_grid_pos_y: 2685527.5
    }
    terrain_level_point {
      sim_grid_pos_x: 30419.7051
      sim_grid_pos_y: 2686351
    }
    terrain_level_point {
      sim_grid_pos_x: 28270.9258
      sim_grid_pos_y: 2686050.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28546.125
      sim_grid_pos_y: 2683552.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28006.416
      sim_grid_pos_y: 2682933.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26562.3867
      sim_grid_pos_y: 2682745
    }
    terrain_level_point {
      sim_grid_pos_x: 26478.9961
      sim_grid_pos_y: 2683275
    }
    terrain_level_point {
      sim_grid_pos_x: 26865.6445
      sim_grid_pos_y: 2683378
    }
    terrain_level_point {
      sim_grid_pos_x: 27254.5059
      sim_grid_pos_y: 2683911
    }
    terrain_level_point {
      sim_grid_pos_x: 27037.2363
      sim_grid_pos_y: 2685853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 23600.9453
      sim_grid_pos_y: 2685366.25
    }
    terrain_level_point {
      sim_grid_pos_x: 23357.7266
      sim_grid_pos_y: 2682766.75
    }
    terrain_level_point {
      sim_grid_pos_x: 24006.3047
      sim_grid_pos_y: 2681533
    }
    terrain_level_point {
      sim_grid_pos_x: 25196.7051
      sim_grid_pos_y: 2681349
    }
    terrain_level_point {
      sim_grid_pos_x: 26606.5957
      sim_grid_pos_y: 2679424
    }
    terrain_level_point {
      sim_grid_pos_x: 28834.1367
      sim_grid_pos_y: 2676916
    }
    terrain_level_point {
      sim_grid_pos_x: 28571.0547
      sim_grid_pos_y: 2675922
    }
    terrain_level_point {
      sim_grid_pos_x: 28666.4961
      sim_grid_pos_y: 2675635.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28709.4453
      sim_grid_pos_y: 2675003.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28881.1855
      sim_grid_pos_y: 2674646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28686.7852
      sim_grid_pos_y: 2673966.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28636.375
      sim_grid_pos_y: 2673140.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28588.2754
      sim_grid_pos_y: 2672384.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28433.9355
      sim_grid_pos_y: 2671762
    }
    terrain_level_point {
      sim_grid_pos_x: 28138.9766
      sim_grid_pos_y: 2671674.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28128.0957
      sim_grid_pos_y: 2670901
    }
    terrain_level_point {
      sim_grid_pos_x: 28413.0762
      sim_grid_pos_y: 2670706.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28220.1152
      sim_grid_pos_y: 2670282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28019.8457
      sim_grid_pos_y: 2669568.75
    }
    terrain_level_point {
      sim_grid_pos_x: 27972.1367
      sim_grid_pos_y: 2669094
    }
    terrain_level_point {
      sim_grid_pos_x: 28032.4258
      sim_grid_pos_y: 2668522.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28052.8359
      sim_grid_pos_y: 2667322.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28150.4453
      sim_grid_pos_y: 2666893.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28618.3457
      sim_grid_pos_y: 2666684.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 28911.6855
      sim_grid_pos_y: 2666990.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28945.3262
      sim_grid_pos_y: 2667786
    }
    terrain_level_point {
      sim_grid_pos_x: 31598.7852
      sim_grid_pos_y: 2673127
    }
    terrain_level_point {
      sim_grid_pos_x: 34198.8242
      sim_grid_pos_y: 2673649.75
    }
    terrain_level_point {
      sim_grid_pos_x: 33473.7539
      sim_grid_pos_y: 2682904.25
    }
    terrain_level_point {
      sim_grid_pos_x: 32758.1348
      sim_grid_pos_y: 2682630.25
    }
    terrain_level_point {
      sim_grid_pos_x: 31636.3164
      sim_grid_pos_y: 2684449.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31867.9453
      sim_grid_pos_y: 2685259
    }
    terrain_level_point {
      sim_grid_pos_x: 31652.4766
      sim_grid_pos_y: 2.68555e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 30427.1953
      sim_grid_pos_y: 2686383
    }
    terrain_level_point {
      sim_grid_pos_x: 28237.0762
      sim_grid_pos_y: 2686077
    }
    terrain_level_point {
      sim_grid_pos_x: 28514.0762
      sim_grid_pos_y: 2683562.25
    }
    terrain_level_point {
      sim_grid_pos_x: 27990.8945
      sim_grid_pos_y: 2682962.75
    }
    terrain_level_point {
      sim_grid_pos_x: 26588.125
      sim_grid_pos_y: 2682779.25
    }
    terrain_level_point {
      sim_grid_pos_x: 26513.6953
      sim_grid_pos_y: 2683252.5
    }
    terrain_level_point {
      sim_grid_pos_x: 26884.0859
      sim_grid_pos_y: 2683351
    }
    terrain_level_point {
      sim_grid_pos_x: 27286.4062
      sim_grid_pos_y: 2683902.5
    }
    terrain_level_point {
      sim_grid_pos_x: 27064.2754
      sim_grid_pos_y: 2685888.25
    }
    terrain_level_point {
      sim_grid_pos_x: 23572.5762
      sim_grid_pos_y: 2685393.25
    }
    terrain_level_point {
      sim_grid_pos_x: 23326.2461
      sim_grid_pos_y: 2682760.5
    }
    terrain_level_point {
      sim_grid_pos_x: 23986.2969
      sim_grid_pos_y: 2681505
    }
    terrain_level_point {
      sim_grid_pos_x: 25179.4062
      sim_grid_pos_y: 2681320.5
    }
    terrain_level_point {
      sim_grid_pos_x: 26582.6367
      sim_grid_pos_y: 2679404.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28800.1758
      sim_grid_pos_y: 2676908
    }
    terrain_level_point {
      sim_grid_pos_x: 28538.9766
      sim_grid_pos_y: 2675921
    }
    terrain_level_point {
      sim_grid_pos_x: 28636.0762
      sim_grid_pos_y: 2675629.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28679.166
      sim_grid_pos_y: 2674995.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28848.3965
      sim_grid_pos_y: 2674643.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28656.2949
      sim_grid_pos_y: 2673971.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28605.6855
      sim_grid_pos_y: 2673142.25
    }
    terrain_level_point {
      sim_grid_pos_x: 28557.7656
      sim_grid_pos_y: 2672389.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28408.3164
      sim_grid_pos_y: 2671786.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28108.5352
      sim_grid_pos_y: 2671697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 28097.1055
      sim_grid_pos_y: 2670885
    }
    terrain_level_point {
      sim_grid_pos_x: 28374.3652
      sim_grid_pos_y: 2670695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28191.1445
      sim_grid_pos_y: 2670293
    }
    terrain_level_point {
      sim_grid_pos_x: 27989.5059
      sim_grid_pos_y: 2669574.5
    }
    terrain_level_point {
      sim_grid_pos_x: 27941.2148
      sim_grid_pos_y: 2669094
    }
    terrain_level_point {
      sim_grid_pos_x: 28001.7051
      sim_grid_pos_y: 2668520.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28022.1367
      sim_grid_pos_y: 2667319
    }
    terrain_level_point {
      sim_grid_pos_x: 28123.8652
      sim_grid_pos_y: 2666871.5
    }
    terrain_level_point {
      sim_grid_pos_x: 28627.125
      sim_grid_pos_y: 2666646.75
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 36430.6641
      sim_grid_pos_y: 2673693.75
    }
    terrain_level_point {
      sim_grid_pos_x: 38362.2539
      sim_grid_pos_y: 2673617.25
    }
    terrain_level_point {
      sim_grid_pos_x: 38584.7305
      sim_grid_pos_y: 2680416
    }
    terrain_level_point {
      sim_grid_pos_x: 39776.0156
      sim_grid_pos_y: 2682914
    }
    terrain_level_point {
      sim_grid_pos_x: 38975.6719
      sim_grid_pos_y: 2683297.25
    }
    terrain_level_point {
      sim_grid_pos_x: 39287.8086
      sim_grid_pos_y: 2684008.5
    }
    terrain_level_point {
      sim_grid_pos_x: 37708.9609
      sim_grid_pos_y: 2684792
    }
    terrain_level_point {
      sim_grid_pos_x: 40220.8438
      sim_grid_pos_y: 2690163
    }
    terrain_level_point {
      sim_grid_pos_x: 36569.8594
      sim_grid_pos_y: 2694011.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33345.0781
      sim_grid_pos_y: 2687441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31880.6289
      sim_grid_pos_y: 2686780.75
    }
    terrain_level_point {
      sim_grid_pos_x: 33859.7109
      sim_grid_pos_y: 2683588.5
    }
    terrain_level_point {
      sim_grid_pos_x: 34499.3438
      sim_grid_pos_y: 2.67582e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 36493.7109
      sim_grid_pos_y: 2675779
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 38615.2461
      sim_grid_pos_y: 2680408.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39816.9961
      sim_grid_pos_y: 2682928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39015.7852
      sim_grid_pos_y: 2683312.25
    }
    terrain_level_point {
      sim_grid_pos_x: 39327.7656
      sim_grid_pos_y: 2684023
    }
    terrain_level_point {
      sim_grid_pos_x: 37749.5469
      sim_grid_pos_y: 2684806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 40257.5859
      sim_grid_pos_y: 2690169
    }
    terrain_level_point {
      sim_grid_pos_x: 36561.7344
      sim_grid_pos_y: 2694064.75
    }
    terrain_level_point {
      sim_grid_pos_x: 33322.3359
      sim_grid_pos_y: 2687465
    }
    terrain_level_point {
      sim_grid_pos_x: 31836.0059
      sim_grid_pos_y: 2686794.25
    }
    terrain_level_point {
      sim_grid_pos_x: 33829.6562
      sim_grid_pos_y: 2683578.5
    }
    terrain_level_point {
      sim_grid_pos_x: 34470.9648
      sim_grid_pos_y: 2.67579e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 36462.0352
      sim_grid_pos_y: 2675749
    }
    terrain_level_point {
      sim_grid_pos_x: 36399.0039
      sim_grid_pos_y: 2673664
    }
    terrain_level_point {
      sim_grid_pos_x: 38391.9844
      sim_grid_pos_y: 2673585.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 38645.7773
      sim_grid_pos_y: 2680401
    }
    terrain_level_point {
      sim_grid_pos_x: 39857.9766
      sim_grid_pos_y: 2682943
    }
    terrain_level_point {
      sim_grid_pos_x: 39055.9141
      sim_grid_pos_y: 2683327
    }
    terrain_level_point {
      sim_grid_pos_x: 39367.7148
      sim_grid_pos_y: 2684037.5
    }
    terrain_level_point {
      sim_grid_pos_x: 37790.1445
      sim_grid_pos_y: 2684820.5
    }
    terrain_level_point {
      sim_grid_pos_x: 40294.3359
      sim_grid_pos_y: 2690175
    }
    terrain_level_point {
      sim_grid_pos_x: 36553.6055
      sim_grid_pos_y: 2694118
    }
    terrain_level_point {
      sim_grid_pos_x: 33299.5938
      sim_grid_pos_y: 2687488.5
    }
    terrain_level_point {
      sim_grid_pos_x: 31791.375
      sim_grid_pos_y: 2686808
    }
    terrain_level_point {
      sim_grid_pos_x: 33799.6055
      sim_grid_pos_y: 2683568.75
    }
    terrain_level_point {
      sim_grid_pos_x: 34442.5938
      sim_grid_pos_y: 2675759.75
    }
    terrain_level_point {
      sim_grid_pos_x: 36430.3438
      sim_grid_pos_y: 2675718.75
    }
    terrain_level_point {
      sim_grid_pos_x: 36367.3359
      sim_grid_pos_y: 2673634.5
    }
    terrain_level_point {
      sim_grid_pos_x: 38421.7148
      sim_grid_pos_y: 2673553.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 38676.3047
      sim_grid_pos_y: 2680393.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39898.957
      sim_grid_pos_y: 2682957.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39096.0352
      sim_grid_pos_y: 2683342
    }
    terrain_level_point {
      sim_grid_pos_x: 39407.6758
      sim_grid_pos_y: 2684052
    }
    terrain_level_point {
      sim_grid_pos_x: 37830.7344
      sim_grid_pos_y: 2684834.75
    }
    terrain_level_point {
      sim_grid_pos_x: 40331.0742
      sim_grid_pos_y: 2690181
    }
    terrain_level_point {
      sim_grid_pos_x: 36545.4844
      sim_grid_pos_y: 2694171.25
    }
    terrain_level_point {
      sim_grid_pos_x: 33276.8672
      sim_grid_pos_y: 2687512
    }
    terrain_level_point {
      sim_grid_pos_x: 31746.7559
      sim_grid_pos_y: 2686821.5
    }
    terrain_level_point {
      sim_grid_pos_x: 33769.5664
      sim_grid_pos_y: 2683558.75
    }
    terrain_level_point {
      sim_grid_pos_x: 34414.2148
      sim_grid_pos_y: 2675729.5
    }
    terrain_level_point {
      sim_grid_pos_x: 36398.6641
      sim_grid_pos_y: 2675688.75
    }
    terrain_level_point {
      sim_grid_pos_x: 36335.6758
      sim_grid_pos_y: 2673605
    }
    terrain_level_point {
      sim_grid_pos_x: 38451.4453
      sim_grid_pos_y: 2673521.5
    }
  }
}
