terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1334167.88
      sim_grid_pos_y: 1446505.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1334701.5
      sim_grid_pos_y: 1446507.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1334729.88
      sim_grid_pos_y: 1446688.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1335340.88
      sim_grid_pos_y: 1446690.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.33548e+06
      sim_grid_pos_y: 1444979.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1334985.38
      sim_grid_pos_y: 1445497.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1334561.75
      sim_grid_pos_y: 1445589.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1334149.12
      sim_grid_pos_y: 1445558.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1335472.75
      sim_grid_pos_y: 1444942.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1334969.75
      sim_grid_pos_y: 1445469.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1334559.62
      sim_grid_pos_y: 1445558.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1334117.75
      sim_grid_pos_y: 1445525.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1334137.62
      sim_grid_pos_y: 1446536.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1334675.12
      sim_grid_pos_y: 1446538.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1334703.5
      sim_grid_pos_y: 1446719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1335369.25
      sim_grid_pos_y: 1446721.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1335512.5
      sim_grid_pos_y: 1444960.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1335465.5
      sim_grid_pos_y: 1444905.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1334953.88
      sim_grid_pos_y: 1445441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1334557.5
      sim_grid_pos_y: 1445527.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1334086.25
      sim_grid_pos_y: 1445492.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1334107.5
      sim_grid_pos_y: 1446566.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1334648.88
      sim_grid_pos_y: 1446568.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1334677.25
      sim_grid_pos_y: 1446750.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1335397.62
      sim_grid_pos_y: 1446752.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1335544.88
      sim_grid_pos_y: 1444940.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1335458.25
      sim_grid_pos_y: 1444868.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1334938.25
      sim_grid_pos_y: 1445413.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1334555.25
      sim_grid_pos_y: 1445496.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1334054.88
      sim_grid_pos_y: 1445459
    }
    terrain_level_point {
      sim_grid_pos_x: 1334077.38
      sim_grid_pos_y: 1446597.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1334622.5
      sim_grid_pos_y: 1446599.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1334650.88
      sim_grid_pos_y: 1446780.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1335426
      sim_grid_pos_y: 1446783.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1335577.25
      sim_grid_pos_y: 1444921.75
    }
  }
}
