terrain_level_data {
  terrain_level: 184
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2844953.5
      sim_grid_pos_y: 576676.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2852715
      sim_grid_pos_y: 586391.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2852772.25
      sim_grid_pos_y: 588781.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2850415
      sim_grid_pos_y: 590604.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2846993
      sim_grid_pos_y: 586419
    }
    terrain_level_point {
      sim_grid_pos_x: 2844356
      sim_grid_pos_y: 584663.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2843217.5
      sim_grid_pos_y: 584459
    }
    terrain_level_point {
      sim_grid_pos_x: 2842267.25
      sim_grid_pos_y: 583247.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2843961.5
      sim_grid_pos_y: 581755.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2843456
      sim_grid_pos_y: 581100.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2843479.25
      sim_grid_pos_y: 577958.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2852765.75
      sim_grid_pos_y: 586373.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2852824
      sim_grid_pos_y: 588806.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2850407
      sim_grid_pos_y: 590675.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2846958.25
      sim_grid_pos_y: 586457.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2844336.5
      sim_grid_pos_y: 584712.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2843189.25
      sim_grid_pos_y: 584506
    }
    terrain_level_point {
      sim_grid_pos_x: 2842197
      sim_grid_pos_y: 583241.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2843891.5
      sim_grid_pos_y: 581749.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2843404.5
      sim_grid_pos_y: 581118.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2843428.25
      sim_grid_pos_y: 577935.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2844960.25
      sim_grid_pos_y: 576602.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2852816.5
      sim_grid_pos_y: 586354.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2852876
      sim_grid_pos_y: 588831.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2850399
      sim_grid_pos_y: 590746.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2846923.25
      sim_grid_pos_y: 586495.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2844316.75
      sim_grid_pos_y: 584760.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2843161
      sim_grid_pos_y: 584553
    }
    terrain_level_point {
      sim_grid_pos_x: 2842126.75
      sim_grid_pos_y: 583234.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2843821.5
      sim_grid_pos_y: 581742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2843353
      sim_grid_pos_y: 581135.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2843377
      sim_grid_pos_y: 577911.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2844967
      sim_grid_pos_y: 576529.125
    }
  }
}
