terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 120664.586
      sim_grid_pos_y: 3104104.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120839.578
      sim_grid_pos_y: 3105695.25
    }
    terrain_level_point {
      sim_grid_pos_x: 123270.609
      sim_grid_pos_y: 3104877.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122916.07
      sim_grid_pos_y: 3104081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122828.516
      sim_grid_pos_y: 3103823.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122766.625
      sim_grid_pos_y: 3103696.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122553.18
      sim_grid_pos_y: 3103134.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122300.672
      sim_grid_pos_y: 3102980.5
    }
    terrain_level_point {
      sim_grid_pos_x: 121081.312
      sim_grid_pos_y: 3102867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120920.539
      sim_grid_pos_y: 3103016.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120766.547
      sim_grid_pos_y: 3103139.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120587.203
      sim_grid_pos_y: 3103242
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 121070.461
      sim_grid_pos_y: 3102835.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120900.414
      sim_grid_pos_y: 3102993.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120749.273
      sim_grid_pos_y: 3103114
    }
    terrain_level_point {
      sim_grid_pos_x: 120554.805
      sim_grid_pos_y: 3103225
    }
    terrain_level_point {
      sim_grid_pos_x: 120633.984
      sim_grid_pos_y: 3104107.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120813.18
      sim_grid_pos_y: 3105736.75
    }
    terrain_level_point {
      sim_grid_pos_x: 123312.445
      sim_grid_pos_y: 3104896.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122944.742
      sim_grid_pos_y: 3.10407e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 122857.008
      sim_grid_pos_y: 3103812
    }
    terrain_level_point {
      sim_grid_pos_x: 122794.875
      sim_grid_pos_y: 3103684.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122578.195
      sim_grid_pos_y: 3103114
    }
    terrain_level_point {
      sim_grid_pos_x: 122310.609
      sim_grid_pos_y: 3102950.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 121059.609
      sim_grid_pos_y: 3102803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120880.484
      sim_grid_pos_y: 3.10297e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 120731.891
      sim_grid_pos_y: 3103088.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120522.398
      sim_grid_pos_y: 3103208
    }
    terrain_level_point {
      sim_grid_pos_x: 120603.383
      sim_grid_pos_y: 3104110.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120786.789
      sim_grid_pos_y: 3105778
    }
    terrain_level_point {
      sim_grid_pos_x: 123354.289
      sim_grid_pos_y: 3104914.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122973.422
      sim_grid_pos_y: 3104058.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122885.508
      sim_grid_pos_y: 3103800.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122823.164
      sim_grid_pos_y: 3103672.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122603.211
      sim_grid_pos_y: 3103093.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122320.555
      sim_grid_pos_y: 3102920.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 121048.758
      sim_grid_pos_y: 3102771.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120860.273
      sim_grid_pos_y: 3102946.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120714.609
      sim_grid_pos_y: 3103063
    }
    terrain_level_point {
      sim_grid_pos_x: 120490
      sim_grid_pos_y: 3103191
    }
    terrain_level_point {
      sim_grid_pos_x: 120572.773
      sim_grid_pos_y: 3104113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120760.391
      sim_grid_pos_y: 3105819.25
    }
    terrain_level_point {
      sim_grid_pos_x: 123396.133
      sim_grid_pos_y: 3104933
    }
    terrain_level_point {
      sim_grid_pos_x: 123002.094
      sim_grid_pos_y: 3104047.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122914
      sim_grid_pos_y: 3103788.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122851.391
      sim_grid_pos_y: 3.10366e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 122628.219
      sim_grid_pos_y: 3103072.5
    }
    terrain_level_point {
      sim_grid_pos_x: 122330.492
      sim_grid_pos_y: 3102890.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 121037.914
      sim_grid_pos_y: 3.10274e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 120840.211
      sim_grid_pos_y: 3102923.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120697.328
      sim_grid_pos_y: 3103037.5
    }
    terrain_level_point {
      sim_grid_pos_x: 120457.602
      sim_grid_pos_y: 3103174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 120542.164
      sim_grid_pos_y: 3104116.75
    }
    terrain_level_point {
      sim_grid_pos_x: 120733.992
      sim_grid_pos_y: 3105860.5
    }
    terrain_level_point {
      sim_grid_pos_x: 123437.984
      sim_grid_pos_y: 3104951.25
    }
    terrain_level_point {
      sim_grid_pos_x: 123030.773
      sim_grid_pos_y: 3104036.25
    }
    terrain_level_point {
      sim_grid_pos_x: 122942.5
      sim_grid_pos_y: 3103776.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122879.641
      sim_grid_pos_y: 3103647.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122653.234
      sim_grid_pos_y: 3103051.75
    }
    terrain_level_point {
      sim_grid_pos_x: 122340.43
      sim_grid_pos_y: 3102860.75
    }
  }
}
