terrain_level_data {
  terrain_level: 220
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1559553.5
      sim_grid_pos_y: 1043895.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1.55934e+06
      sim_grid_pos_y: 1044184.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1559033.75
      sim_grid_pos_y: 1044187.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558843.12
      sim_grid_pos_y: 1044102.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558629.12
      sim_grid_pos_y: 1044118.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1558480.25
      sim_grid_pos_y: 1044249.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1558228.12
      sim_grid_pos_y: 1044323.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1558115.5
      sim_grid_pos_y: 1044093.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1558264.88
      sim_grid_pos_y: 1043939.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1558434.5
      sim_grid_pos_y: 1043838.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1558645.88
      sim_grid_pos_y: 1043922.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558843
      sim_grid_pos_y: 1043768.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1559002.75
      sim_grid_pos_y: 1043758.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1559100.88
      sim_grid_pos_y: 1043552.19
    }
    terrain_level_point {
      sim_grid_pos_x: 1559345.5
      sim_grid_pos_y: 1043638.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1559376.25
      sim_grid_pos_y: 1043594.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1559618.25
      sim_grid_pos_y: 1043894.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1559366
      sim_grid_pos_y: 1044235.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1559023
      sim_grid_pos_y: 1044238.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1558834.12
      sim_grid_pos_y: 1044154.56
    }
    terrain_level_point {
      sim_grid_pos_x: 1.55865e+06
      sim_grid_pos_y: 1044168.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1558505.5
      sim_grid_pos_y: 1044295.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1558201.12
      sim_grid_pos_y: 1044385.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1558053.62
      sim_grid_pos_y: 1044084.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1558232.75
      sim_grid_pos_y: 1043898.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1.55843e+06
      sim_grid_pos_y: 1043781.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558637.5
      sim_grid_pos_y: 1043863.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1558824
      sim_grid_pos_y: 1043718.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1558969.38
      sim_grid_pos_y: 1043709.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1559074.38
      sim_grid_pos_y: 1043488.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1559407
      sim_grid_pos_y: 1043551.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1559683
      sim_grid_pos_y: 1043892.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1559392.12
      sim_grid_pos_y: 1044286.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1559012.25
      sim_grid_pos_y: 1044290.19
    }
    terrain_level_point {
      sim_grid_pos_x: 1558825
      sim_grid_pos_y: 1044206.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1558671
      sim_grid_pos_y: 1044218
    }
    terrain_level_point {
      sim_grid_pos_x: 1558530.88
      sim_grid_pos_y: 1044341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1558174.12
      sim_grid_pos_y: 1044446.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1557991.75
      sim_grid_pos_y: 1044074.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1558200.75
      sim_grid_pos_y: 1043858.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1558425.5
      sim_grid_pos_y: 1043724.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1558629.12
      sim_grid_pos_y: 1043805.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558805
      sim_grid_pos_y: 1043668.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1558936.12
      sim_grid_pos_y: 1043660.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1559047.88
      sim_grid_pos_y: 1043424.81
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1559437.75
      sim_grid_pos_y: 1043507.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1559747.88
      sim_grid_pos_y: 1043891.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1559418.12
      sim_grid_pos_y: 1044337.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1559001.62
      sim_grid_pos_y: 1044341.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1558815.88
      sim_grid_pos_y: 1044258.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1558691.88
      sim_grid_pos_y: 1044267.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1558556.25
      sim_grid_pos_y: 1044387.19
    }
    terrain_level_point {
      sim_grid_pos_x: 1558147.25
      sim_grid_pos_y: 1044507.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1557929.88
      sim_grid_pos_y: 1044064.56
    }
    terrain_level_point {
      sim_grid_pos_x: 1558168.62
      sim_grid_pos_y: 1043817.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1558421
      sim_grid_pos_y: 1043667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1558620.75
      sim_grid_pos_y: 1043746.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1558786
      sim_grid_pos_y: 1043617.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1558902.75
      sim_grid_pos_y: 1043610.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1559021.38
      sim_grid_pos_y: 1043361.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1559468.5
      sim_grid_pos_y: 1043464.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1559812.62
      sim_grid_pos_y: 1.04389e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1559456.5
      sim_grid_pos_y: 1044372.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1559060.88
      sim_grid_pos_y: 1044443.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1558819
      sim_grid_pos_y: 1044338.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1558699.5
      sim_grid_pos_y: 1044329.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558581.62
      sim_grid_pos_y: 1044433.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1558120.25
      sim_grid_pos_y: 1044569.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1557868
      sim_grid_pos_y: 1044054.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1558136.5
      sim_grid_pos_y: 1043777.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1558416.38
      sim_grid_pos_y: 1043610.56
    }
    terrain_level_point {
      sim_grid_pos_x: 1558612.38
      sim_grid_pos_y: 1043688.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558767
      sim_grid_pos_y: 1043567.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1558869.5
      sim_grid_pos_y: 1043561.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1558994.88
      sim_grid_pos_y: 1043297.44
    }
  }
}
