terrain_level_data {
  terrain_level: 230
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1674215
      sim_grid_pos_y: 964733.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1674213.5
      sim_grid_pos_y: 964917.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1674394.75
      sim_grid_pos_y: 964916.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1674415.62
      sim_grid_pos_y: 964724.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1674496
      sim_grid_pos_y: 964649.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1674143.75
      sim_grid_pos_y: 964665.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1674141.12
      sim_grid_pos_y: 964990
    }
    terrain_level_point {
      sim_grid_pos_x: 1674459.12
      sim_grid_pos_y: 964988.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1674576.38
      sim_grid_pos_y: 964573.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1674072.62
      sim_grid_pos_y: 964596.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1674068.75
      sim_grid_pos_y: 965062.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1674523.62
      sim_grid_pos_y: 965059.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1674656.75
      sim_grid_pos_y: 964498.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1674001.38
      sim_grid_pos_y: 964527.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1673996.38
      sim_grid_pos_y: 965134.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1674588
      sim_grid_pos_y: 965131.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1674737.12
      sim_grid_pos_y: 964422.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1673930.25
      sim_grid_pos_y: 964459.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1673924
      sim_grid_pos_y: 965206.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1674652.38
      sim_grid_pos_y: 965202.562
    }
  }
}
terrain_level_data {
  terrain_level: 180
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1675184.38
      sim_grid_pos_y: 964849.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1675183.75
      sim_grid_pos_y: 964719.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1675028
      sim_grid_pos_y: 964634.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1674938.62
      sim_grid_pos_y: 964654.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1674844.62
      sim_grid_pos_y: 964733.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1674855.75
      sim_grid_pos_y: 964818.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1674978.12
      sim_grid_pos_y: 964921.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1675035.62
      sim_grid_pos_y: 964580.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1674915.38
      sim_grid_pos_y: 964607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1674790.12
      sim_grid_pos_y: 964712
    }
    terrain_level_point {
      sim_grid_pos_x: 1674807.5
      sim_grid_pos_y: 964845.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1674967.5
      sim_grid_pos_y: 964979.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1675235.75
      sim_grid_pos_y: 964886
    }
    terrain_level_point {
      sim_grid_pos_x: 1675234.88
      sim_grid_pos_y: 964688.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1675043.12
      sim_grid_pos_y: 964526.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1674892
      sim_grid_pos_y: 964560.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1674735.62
      sim_grid_pos_y: 964690.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1674759.25
      sim_grid_pos_y: 964871.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1674956.88
      sim_grid_pos_y: 965037.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1675287.25
      sim_grid_pos_y: 964922.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1675286
      sim_grid_pos_y: 964658.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1675050.75
      sim_grid_pos_y: 964472.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1674868.75
      sim_grid_pos_y: 964512.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1674681.12
      sim_grid_pos_y: 964669.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1674711
      sim_grid_pos_y: 964898.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1674946.25
      sim_grid_pos_y: 965095.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1675338.62
      sim_grid_pos_y: 964958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1675337.12
      sim_grid_pos_y: 964627.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1675058.25
      sim_grid_pos_y: 964417.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1674845.38
      sim_grid_pos_y: 964465.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1674626.75
      sim_grid_pos_y: 964648.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1674662.75
      sim_grid_pos_y: 964924.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1674935.62
      sim_grid_pos_y: 965153.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1.67539e+06
      sim_grid_pos_y: 964995.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1675388.25
      sim_grid_pos_y: 964597
    }
  }
}
terrain_level_data {
  terrain_level: 85
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1675205.62
      sim_grid_pos_y: 965531.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1674993.75
      sim_grid_pos_y: 965845.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1674523.75
      sim_grid_pos_y: 965460.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1674719
      sim_grid_pos_y: 965204.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1675276.88
      sim_grid_pos_y: 965518
    }
    terrain_level_point {
      sim_grid_pos_x: 1675004.75
      sim_grid_pos_y: 965921.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1674452.88
      sim_grid_pos_y: 965468.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1674707.5
      sim_grid_pos_y: 965135.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1675348
      sim_grid_pos_y: 965504.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1675015.75
      sim_grid_pos_y: 965996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1674382.12
      sim_grid_pos_y: 965476.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1674696.12
      sim_grid_pos_y: 965066
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1675419.25
      sim_grid_pos_y: 965490.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1675026.75
      sim_grid_pos_y: 966071.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1674311.25
      sim_grid_pos_y: 965485.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1674684.62
      sim_grid_pos_y: 964996.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1675490.5
      sim_grid_pos_y: 965476.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1675037.75
      sim_grid_pos_y: 966147.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1674240.5
      sim_grid_pos_y: 965493.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1674673.25
      sim_grid_pos_y: 964927.062
    }
  }
}
