terrain_level_data {
  terrain_level: 130
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1361633.75
      sim_grid_pos_y: 1431569.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1361542.38
      sim_grid_pos_y: 1431777.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1361937
      sim_grid_pos_y: 1432085.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1362063.88
      sim_grid_pos_y: 1431907.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1361621.5
      sim_grid_pos_y: 1431520.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1361504.62
      sim_grid_pos_y: 1431786.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1361943.38
      sim_grid_pos_y: 1432129.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1362106
      sim_grid_pos_y: 1431901.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1361609.25
      sim_grid_pos_y: 1431472.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1361466.88
      sim_grid_pos_y: 1431796.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1361949.75
      sim_grid_pos_y: 1432173.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1362148.12
      sim_grid_pos_y: 1431895
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1361597.12
      sim_grid_pos_y: 1431423.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1361429
      sim_grid_pos_y: 1431805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1361956.25
      sim_grid_pos_y: 1432217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1362190.12
      sim_grid_pos_y: 1431889
    }
  }
}
