terrain_level_data {
  terrain_level: 86
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1808950.62
      sim_grid_pos_y: 1792177
    }
    terrain_level_point {
      sim_grid_pos_x: 1808417.5
      sim_grid_pos_y: 1792619.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1810209.62
      sim_grid_pos_y: 1793252.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1811406
      sim_grid_pos_y: 1794731.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1816223.38
      sim_grid_pos_y: 1798991.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1816814.12
      sim_grid_pos_y: 1798429
    }
    terrain_level_point {
      sim_grid_pos_x: 1809389.38
      sim_grid_pos_y: 1790177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1809324.12
      sim_grid_pos_y: 1790922.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1809069.62
      sim_grid_pos_y: 1791751.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1809420.62
      sim_grid_pos_y: 1790058.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1809293.12
      sim_grid_pos_y: 1790101.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1809222.88
      sim_grid_pos_y: 1790902.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1808971.25
      sim_grid_pos_y: 1791722.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1808860.5
      sim_grid_pos_y: 1792118.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1808306
      sim_grid_pos_y: 1792579
    }
    terrain_level_point {
      sim_grid_pos_x: 1808327
      sim_grid_pos_y: 1792696.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1810148.25
      sim_grid_pos_y: 1793339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1811331.62
      sim_grid_pos_y: 1794802.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1816225.88
      sim_grid_pos_y: 1799130.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1816957
      sim_grid_pos_y: 1798434.5
    }
  }
}
