terrain_level_data {
  terrain_level: 48
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2660526.75
      sim_grid_pos_y: 394450.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2664088.5
      sim_grid_pos_y: 398008.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2667282.25
      sim_grid_pos_y: 400453
    }
    terrain_level_point {
      sim_grid_pos_x: 2668511.25
      sim_grid_pos_y: 400890.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2668253
      sim_grid_pos_y: 401669.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2665625.5
      sim_grid_pos_y: 402618.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2658129.75
      sim_grid_pos_y: 402700.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2656973.5
      sim_grid_pos_y: 397655.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2657049.5
      sim_grid_pos_y: 397006.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2658201.75
      sim_grid_pos_y: 395354.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2658590.25
      sim_grid_pos_y: 393611.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2660562
      sim_grid_pos_y: 394398.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2664129.25
      sim_grid_pos_y: 397962.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2667312
      sim_grid_pos_y: 400398.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2668588.75
      sim_grid_pos_y: 400852.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2668302
      sim_grid_pos_y: 401717.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2665636.5
      sim_grid_pos_y: 402679.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2658081
      sim_grid_pos_y: 402763.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2656911
      sim_grid_pos_y: 397659.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2656990.25
      sim_grid_pos_y: 396983.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2658144.5
      sim_grid_pos_y: 395329.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2658546.5
      sim_grid_pos_y: 393525.094
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2660597.25
      sim_grid_pos_y: 394346.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2664169.75
      sim_grid_pos_y: 397916.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2667341.75
      sim_grid_pos_y: 400343.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2668666
      sim_grid_pos_y: 400814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2668351
      sim_grid_pos_y: 401765.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2665647.5
      sim_grid_pos_y: 402741.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2658032
      sim_grid_pos_y: 402825.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2656848.75
      sim_grid_pos_y: 397662.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2656930.75
      sim_grid_pos_y: 396961.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2658087
      sim_grid_pos_y: 395304.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2658502.5
      sim_grid_pos_y: 393439.031
    }
  }
}
