terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2007509.88
      sim_grid_pos_y: 143716.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2007668.38
      sim_grid_pos_y: 145772.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2001021.88
      sim_grid_pos_y: 146656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2000890.5
      sim_grid_pos_y: 144974.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2004021
      sim_grid_pos_y: 142754.969
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2007558.25
      sim_grid_pos_y: 143676.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2007723.25
      sim_grid_pos_y: 145817.328
    }
    terrain_level_point {
      sim_grid_pos_x: 2000975
      sim_grid_pos_y: 146714.703
    }
    terrain_level_point {
      sim_grid_pos_x: 2000837.12
      sim_grid_pos_y: 144949.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2004011.12
      sim_grid_pos_y: 142699.078
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2007606.62
      sim_grid_pos_y: 143637.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2007778.12
      sim_grid_pos_y: 145861.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2000928.12
      sim_grid_pos_y: 146772.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2000783.88
      sim_grid_pos_y: 144924.172
    }
    terrain_level_point {
      sim_grid_pos_x: 2004001.38
      sim_grid_pos_y: 142643.203
    }
  }
}
