terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1100896.88
      sim_grid_pos_y: 1306573.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1100456
      sim_grid_pos_y: 1306655
    }
    terrain_level_point {
      sim_grid_pos_x: 1099791.38
      sim_grid_pos_y: 1306937.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1099778.38
      sim_grid_pos_y: 1307185.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1099495.38
      sim_grid_pos_y: 1307353
    }
    terrain_level_point {
      sim_grid_pos_x: 1099192.25
      sim_grid_pos_y: 1307378.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1101439.12
      sim_grid_pos_y: 1313613.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1102905.5
      sim_grid_pos_y: 1312970.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1103117.88
      sim_grid_pos_y: 1312638.12
    }
  }
}
