terrain_level_data {
  terrain_level: 280
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1471300.88
      sim_grid_pos_y: 1753438
    }
    terrain_level_point {
      sim_grid_pos_x: 1472254.62
      sim_grid_pos_y: 1755290.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1472413
      sim_grid_pos_y: 1755668.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1472581.88
      sim_grid_pos_y: 1755648.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1473172.62
      sim_grid_pos_y: 1754973.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1473231.62
      sim_grid_pos_y: 1753735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1472693.75
      sim_grid_pos_y: 1752249.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1470712.75
      sim_grid_pos_y: 1752272
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1472794
      sim_grid_pos_y: 1752104.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1470480.88
      sim_grid_pos_y: 1752131.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1471173
      sim_grid_pos_y: 1753503.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1472124.5
      sim_grid_pos_y: 1755351.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1472322.5
      sim_grid_pos_y: 1755823.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1472653.62
      sim_grid_pos_y: 1755784.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1473313.62
      sim_grid_pos_y: 1755030.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1473376.38
      sim_grid_pos_y: 1753713.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1472894.25
      sim_grid_pos_y: 1751960.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1470249
      sim_grid_pos_y: 1751990.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471045.12
      sim_grid_pos_y: 1753568.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471994.25
      sim_grid_pos_y: 1755411.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1472231.88
      sim_grid_pos_y: 1755979.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1472725.25
      sim_grid_pos_y: 1755920.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1473454.62
      sim_grid_pos_y: 1755087.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1473521.12
      sim_grid_pos_y: 1753691.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1472994.5
      sim_grid_pos_y: 1751815.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1470017.12
      sim_grid_pos_y: 1751849.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470917.25
      sim_grid_pos_y: 1753633.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1471864
      sim_grid_pos_y: 1755472.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1472141.25
      sim_grid_pos_y: 1756134.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1472796.88
      sim_grid_pos_y: 1756056.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1473595.62
      sim_grid_pos_y: 1755144.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1473665.88
      sim_grid_pos_y: 1753669.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1473094.75
      sim_grid_pos_y: 1751670.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1469785.38
      sim_grid_pos_y: 1751708.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470789.38
      sim_grid_pos_y: 1753698.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1471733.75
      sim_grid_pos_y: 1755533.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1472050.62
      sim_grid_pos_y: 1756289.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1472868.5
      sim_grid_pos_y: 1756193
    }
    terrain_level_point {
      sim_grid_pos_x: 1473736.62
      sim_grid_pos_y: 1755201.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1473810.62
      sim_grid_pos_y: 1753648
    }
  }
}
