terrain_level_data {
  terrain_level: 118
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2219478.5
      sim_grid_pos_y: 1708731
    }
    terrain_level_point {
      sim_grid_pos_x: 2221322.5
      sim_grid_pos_y: 1707476.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2229167
      sim_grid_pos_y: 1714234
    }
    terrain_level_point {
      sim_grid_pos_x: 2228724.25
      sim_grid_pos_y: 1715251.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2228437.5
      sim_grid_pos_y: 1716253.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2227776.25
      sim_grid_pos_y: 1716267.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2225291.5
      sim_grid_pos_y: 1714827.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2223211.25
      sim_grid_pos_y: 1713797.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2222288.25
      sim_grid_pos_y: 1711843.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2221841.5
      sim_grid_pos_y: 1711061.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2221484
      sim_grid_pos_y: 1710320.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2229204.25
      sim_grid_pos_y: 1714225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2228753.25
      sim_grid_pos_y: 1715261.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2228460.75
      sim_grid_pos_y: 1716283.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2227768.25
      sim_grid_pos_y: 1716298
    }
    terrain_level_point {
      sim_grid_pos_x: 2225277
      sim_grid_pos_y: 1714854.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2223188
      sim_grid_pos_y: 1713820.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2222261
      sim_grid_pos_y: 1711857.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2221814.25
      sim_grid_pos_y: 1711075.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2221459.5
      sim_grid_pos_y: 1710340.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2219426.5
      sim_grid_pos_y: 1708729.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2221324.5
      sim_grid_pos_y: 1707437.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2229241.5
      sim_grid_pos_y: 1714217
    }
    terrain_level_point {
      sim_grid_pos_x: 2228782.25
      sim_grid_pos_y: 1715272
    }
    terrain_level_point {
      sim_grid_pos_x: 2228484
      sim_grid_pos_y: 1716314.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2227760.25
      sim_grid_pos_y: 1716329
    }
    terrain_level_point {
      sim_grid_pos_x: 2225262.5
      sim_grid_pos_y: 1714881.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2223164.75
      sim_grid_pos_y: 1713843.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2222233.75
      sim_grid_pos_y: 1711872.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2221787
      sim_grid_pos_y: 1711089.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2221434.75
      sim_grid_pos_y: 1710360.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2219374.75
      sim_grid_pos_y: 1708727.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2221326.75
      sim_grid_pos_y: 1707399
    }
  }
}
