terrain_level_data {
  terrain_level: 60
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1473453.75
      sim_grid_pos_y: 1431300.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470972
      sim_grid_pos_y: 1430887.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1470537.25
      sim_grid_pos_y: 1429936.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1470598.5
      sim_grid_pos_y: 1428601.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1470878
      sim_grid_pos_y: 1427830.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1471256.62
      sim_grid_pos_y: 1427299.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1471800.88
      sim_grid_pos_y: 1426702.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1472434.62
      sim_grid_pos_y: 1426149.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1474891.25
      sim_grid_pos_y: 1423482.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1475031.38
      sim_grid_pos_y: 1422650.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1475884.5
      sim_grid_pos_y: 1422871.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1476244.62
      sim_grid_pos_y: 1423087.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1476351.88
      sim_grid_pos_y: 1423962.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1478465.88
      sim_grid_pos_y: 1424469.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1479075
      sim_grid_pos_y: 1425144
    }
    terrain_level_point {
      sim_grid_pos_x: 1478974.88
      sim_grid_pos_y: 1426778.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1478476.88
      sim_grid_pos_y: 1427426.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1477564.38
      sim_grid_pos_y: 1427631.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1477483.12
      sim_grid_pos_y: 1429260.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1476274.5
      sim_grid_pos_y: 1429049.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1475603.88
      sim_grid_pos_y: 1.42905e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1475039.62
      sim_grid_pos_y: 1429239.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1474412.5
      sim_grid_pos_y: 1429709.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1475896.5
      sim_grid_pos_y: 1422842.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1476273.38
      sim_grid_pos_y: 1423069
    }
    terrain_level_point {
      sim_grid_pos_x: 1476379.75
      sim_grid_pos_y: 1423937.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1478482.25
      sim_grid_pos_y: 1424441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1479106.38
      sim_grid_pos_y: 1425133
    }
    terrain_level_point {
      sim_grid_pos_x: 1479005
      sim_grid_pos_y: 1426789.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1478494.5
      sim_grid_pos_y: 1427454.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1477593.88
      sim_grid_pos_y: 1427656.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1477512.12
      sim_grid_pos_y: 1429296.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1476271.88
      sim_grid_pos_y: 1.42908e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1475609
      sim_grid_pos_y: 1429080.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1475054.12
      sim_grid_pos_y: 1429267.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1474435.75
      sim_grid_pos_y: 1429730.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1473469.25
      sim_grid_pos_y: 1431334.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1470950.75
      sim_grid_pos_y: 1430915.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470506.25
      sim_grid_pos_y: 1429942.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470568
      sim_grid_pos_y: 1428595.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1470850.5
      sim_grid_pos_y: 1427816.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1471232.62
      sim_grid_pos_y: 1427280.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471779.25
      sim_grid_pos_y: 1426680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1472413.12
      sim_grid_pos_y: 1426127.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1474862.38
      sim_grid_pos_y: 1423468.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1475006.62
      sim_grid_pos_y: 1422612.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1475908.5
      sim_grid_pos_y: 1422813.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1476302.12
      sim_grid_pos_y: 1423050.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1476407.75
      sim_grid_pos_y: 1423912.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1478498.75
      sim_grid_pos_y: 1424413.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1479137.88
      sim_grid_pos_y: 1425121.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1479035.12
      sim_grid_pos_y: 1426801.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1478512.12
      sim_grid_pos_y: 1427482
    }
    terrain_level_point {
      sim_grid_pos_x: 1477623.38
      sim_grid_pos_y: 1427681.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1477541.12
      sim_grid_pos_y: 1429332.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1476269.25
      sim_grid_pos_y: 1429110.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1475614
      sim_grid_pos_y: 1429111.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1475068.62
      sim_grid_pos_y: 1429294.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1474459
      sim_grid_pos_y: 1429751.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1473484.88
      sim_grid_pos_y: 1431367.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1470929.62
      sim_grid_pos_y: 1430943
    }
    terrain_level_point {
      sim_grid_pos_x: 1470475.12
      sim_grid_pos_y: 1429948.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470537.5
      sim_grid_pos_y: 1428589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1470823
      sim_grid_pos_y: 1427802
    }
    terrain_level_point {
      sim_grid_pos_x: 1471208.62
      sim_grid_pos_y: 1427260.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1471757.75
      sim_grid_pos_y: 1426658.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1472391.62
      sim_grid_pos_y: 1426105.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1474833.62
      sim_grid_pos_y: 1423454.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1474981.88
      sim_grid_pos_y: 1422574
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1475920.5
      sim_grid_pos_y: 1422785.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1476330.75
      sim_grid_pos_y: 1423031.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1476435.62
      sim_grid_pos_y: 1423887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1478515.12
      sim_grid_pos_y: 1424386.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1479169.38
      sim_grid_pos_y: 1425110.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1479065.25
      sim_grid_pos_y: 1426812.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1478529.75
      sim_grid_pos_y: 1427509.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1477653
      sim_grid_pos_y: 1427706.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1477570.12
      sim_grid_pos_y: 1429368.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1476266.62
      sim_grid_pos_y: 1429141.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1475619
      sim_grid_pos_y: 1429142.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1475083.12
      sim_grid_pos_y: 1429322.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1474482.25
      sim_grid_pos_y: 1429772.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1473500.5
      sim_grid_pos_y: 1431401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1470908.38
      sim_grid_pos_y: 1430970.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1470444
      sim_grid_pos_y: 1429954.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470507
      sim_grid_pos_y: 1428583
    }
    terrain_level_point {
      sim_grid_pos_x: 1470795.5
      sim_grid_pos_y: 1427787.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1471184.62
      sim_grid_pos_y: 1427241.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1471736.25
      sim_grid_pos_y: 1426636.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1472370.12
      sim_grid_pos_y: 1426083.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1474804.75
      sim_grid_pos_y: 1423440.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1474957
      sim_grid_pos_y: 1422535.75
    }
  }
}
terrain_level_data {
  terrain_level: 100
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1471311
      sim_grid_pos_y: 1427291
    }
    terrain_level_point {
      sim_grid_pos_x: 1470985.38
      sim_grid_pos_y: 1426423.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470966.25
      sim_grid_pos_y: 1426278.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1471274
      sim_grid_pos_y: 1426115.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1471505.25
      sim_grid_pos_y: 1425756.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471809.62
      sim_grid_pos_y: 1425669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1471944.75
      sim_grid_pos_y: 1425204.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471442.25
      sim_grid_pos_y: 1424865.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1471556.62
      sim_grid_pos_y: 1424424.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1472032.12
      sim_grid_pos_y: 1423579
    }
    terrain_level_point {
      sim_grid_pos_x: 1472639.38
      sim_grid_pos_y: 1423970.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1473178.25
      sim_grid_pos_y: 1424259.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1473402.25
      sim_grid_pos_y: 1424532.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1473624.12
      sim_grid_pos_y: 1424886.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1473575.25
      sim_grid_pos_y: 1425054.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1473315.5
      sim_grid_pos_y: 1425046.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1473195.75
      sim_grid_pos_y: 1425091.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1472400.12
      sim_grid_pos_y: 1426116.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1472655
      sim_grid_pos_y: 1423944
    }
    terrain_level_point {
      sim_grid_pos_x: 1473198.25
      sim_grid_pos_y: 1424234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1473427.25
      sim_grid_pos_y: 1424514.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1473657.5
      sim_grid_pos_y: 1424881.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1473598.12
      sim_grid_pos_y: 1425086.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1473320.75
      sim_grid_pos_y: 1425077
    }
    terrain_level_point {
      sim_grid_pos_x: 1473214.75
      sim_grid_pos_y: 1425117.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1472423.62
      sim_grid_pos_y: 1426136.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1471299.75
      sim_grid_pos_y: 1427348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470955.25
      sim_grid_pos_y: 1426430.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1470933
      sim_grid_pos_y: 1426261.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1471252.5
      sim_grid_pos_y: 1426092.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1471485.62
      sim_grid_pos_y: 1425729.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1471784.75
      sim_grid_pos_y: 1425644.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1471909
      sim_grid_pos_y: 1425217.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471407
      sim_grid_pos_y: 1424878.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1471527.88
      sim_grid_pos_y: 1424413
    }
    terrain_level_point {
      sim_grid_pos_x: 1472021.38
      sim_grid_pos_y: 1423535.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1472670.62
      sim_grid_pos_y: 1423917.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1473218.12
      sim_grid_pos_y: 1424210.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1473452.25
      sim_grid_pos_y: 1424496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1473690.88
      sim_grid_pos_y: 1424877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1473621
      sim_grid_pos_y: 1425118
    }
    terrain_level_point {
      sim_grid_pos_x: 1473325.88
      sim_grid_pos_y: 1425108
    }
    terrain_level_point {
      sim_grid_pos_x: 1473233.88
      sim_grid_pos_y: 1425143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1472447.12
      sim_grid_pos_y: 1426156
    }
    terrain_level_point {
      sim_grid_pos_x: 1471288.38
      sim_grid_pos_y: 1427405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1470925.25
      sim_grid_pos_y: 1426438.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1470899.75
      sim_grid_pos_y: 1426244
    }
    terrain_level_point {
      sim_grid_pos_x: 1471231
      sim_grid_pos_y: 1426068.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1471466.12
      sim_grid_pos_y: 1425703.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.47176e+06
      sim_grid_pos_y: 1425619.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1471873.25
      sim_grid_pos_y: 1425230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1471371.75
      sim_grid_pos_y: 1424892
    }
    terrain_level_point {
      sim_grid_pos_x: 1471499.12
      sim_grid_pos_y: 1424401.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1472010.5
      sim_grid_pos_y: 1423492
    }
  }
}
