terrain_level_data {
  terrain_level: 270
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2199645.75
      sim_grid_pos_y: 1039125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2199725.5
      sim_grid_pos_y: 1038980.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199749.25
      sim_grid_pos_y: 1038876.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2199806.5
      sim_grid_pos_y: 1038799.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2199917
      sim_grid_pos_y: 1038760.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2200028.5
      sim_grid_pos_y: 1038626.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2200094.75
      sim_grid_pos_y: 1038639.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2200153.25
      sim_grid_pos_y: 1038537.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2200220.25
      sim_grid_pos_y: 1038511.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2200342.25
      sim_grid_pos_y: 1038485.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2200536.75
      sim_grid_pos_y: 1038469.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200634.25
      sim_grid_pos_y: 1038409.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200742
      sim_grid_pos_y: 1038099.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2200488.25
      sim_grid_pos_y: 1038005.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2200175
      sim_grid_pos_y: 1037290.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200080.25
      sim_grid_pos_y: 1037172.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199791.5
      sim_grid_pos_y: 1037512.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199569.5
      sim_grid_pos_y: 1038116.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2199332.75
      sim_grid_pos_y: 1038981.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199423.25
      sim_grid_pos_y: 1039155.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199470.75
      sim_grid_pos_y: 1039299.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2199614.25
      sim_grid_pos_y: 1039302.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2199636.5
      sim_grid_pos_y: 1039335.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199677.5
      sim_grid_pos_y: 1039258.44
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2200080.75
      sim_grid_pos_y: 1037124.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2199764.5
      sim_grid_pos_y: 1037497.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2199540.25
      sim_grid_pos_y: 1038107.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2.1993e+06
      sim_grid_pos_y: 1038985.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2199394.75
      sim_grid_pos_y: 1039167.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199448.25
      sim_grid_pos_y: 1039329.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199597.75
      sim_grid_pos_y: 1039332.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2199639.75
      sim_grid_pos_y: 1039396
    }
    terrain_level_point {
      sim_grid_pos_x: 2.19971e+06
      sim_grid_pos_y: 1039262.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2199678.5
      sim_grid_pos_y: 1039129.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2199754.5
      sim_grid_pos_y: 1038991.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199777.75
      sim_grid_pos_y: 1038889.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199825.5
      sim_grid_pos_y: 1038825.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2199935.25
      sim_grid_pos_y: 1038786.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2200040.5
      sim_grid_pos_y: 1038659.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2200110.5
      sim_grid_pos_y: 1038674.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2200174.5
      sim_grid_pos_y: 1038561.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2200228.75
      sim_grid_pos_y: 1038541.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200346.75
      sim_grid_pos_y: 1038516.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2200546.5
      sim_grid_pos_y: 1038499.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2200659.75
      sim_grid_pos_y: 1038430.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2200781
      sim_grid_pos_y: 1038081.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2200511.25
      sim_grid_pos_y: 1037981.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2200201.5
      sim_grid_pos_y: 1037274.44
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2200081.25
      sim_grid_pos_y: 1037076.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199737.5
      sim_grid_pos_y: 1037481.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2199510.75
      sim_grid_pos_y: 1038097.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199267
      sim_grid_pos_y: 1038988.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2199366.25
      sim_grid_pos_y: 1039179.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199425.75
      sim_grid_pos_y: 1039359.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199581
      sim_grid_pos_y: 1039363.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199642.75
      sim_grid_pos_y: 1039456.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199742.5
      sim_grid_pos_y: 1039266.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2199711.25
      sim_grid_pos_y: 1039134.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2199783.5
      sim_grid_pos_y: 1039002.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2199806.5
      sim_grid_pos_y: 1038903.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199844.75
      sim_grid_pos_y: 1038851.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2199953.5
      sim_grid_pos_y: 1038812.44
    }
    terrain_level_point {
      sim_grid_pos_x: 2200052.25
      sim_grid_pos_y: 1038693.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200126.25
      sim_grid_pos_y: 1038708.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200195.75
      sim_grid_pos_y: 1038586.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2200237.5
      sim_grid_pos_y: 1038571.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2200351.5
      sim_grid_pos_y: 1038546.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2200556.25
      sim_grid_pos_y: 1038529.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2200685.25
      sim_grid_pos_y: 1038450.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2.20082e+06
      sim_grid_pos_y: 1038063
    }
    terrain_level_point {
      sim_grid_pos_x: 2200534.25
      sim_grid_pos_y: 1037957
    }
    terrain_level_point {
      sim_grid_pos_x: 2200228.25
      sim_grid_pos_y: 1037258.31
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2200082
      sim_grid_pos_y: 1037027.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199710.5
      sim_grid_pos_y: 1037465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2199481.5
      sim_grid_pos_y: 1038088.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2199234.25
      sim_grid_pos_y: 1038992.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2199338
      sim_grid_pos_y: 1039191.06
    }
    terrain_level_point {
      sim_grid_pos_x: 2199403.25
      sim_grid_pos_y: 1039390.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2199564.25
      sim_grid_pos_y: 1039393.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2199646
      sim_grid_pos_y: 1039516.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199775.25
      sim_grid_pos_y: 1039270.81
    }
    terrain_level_point {
      sim_grid_pos_x: 2199743.75
      sim_grid_pos_y: 1039138.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2199812.5
      sim_grid_pos_y: 1039013.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2199835
      sim_grid_pos_y: 1038916.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2199864
      sim_grid_pos_y: 1038876.94
    }
    terrain_level_point {
      sim_grid_pos_x: 2199971.75
      sim_grid_pos_y: 1038838.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200064.25
      sim_grid_pos_y: 1038727.56
    }
    terrain_level_point {
      sim_grid_pos_x: 2200142
      sim_grid_pos_y: 1038743.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2200216.75
      sim_grid_pos_y: 1038611.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200246.25
      sim_grid_pos_y: 1038600.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200355.75
      sim_grid_pos_y: 1038577.31
    }
    terrain_level_point {
      sim_grid_pos_x: 2200566.25
      sim_grid_pos_y: 1038559.69
    }
    terrain_level_point {
      sim_grid_pos_x: 2200710.75
      sim_grid_pos_y: 1038471.19
    }
    terrain_level_point {
      sim_grid_pos_x: 2200858.75
      sim_grid_pos_y: 1038044.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2200557.25
      sim_grid_pos_y: 1037932.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2200254.75
      sim_grid_pos_y: 1037242.25
    }
  }
}
