terrain_level_data {
  terrain_level: 1400
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1678221.62
      sim_grid_pos_y: 1609260.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678075.62
      sim_grid_pos_y: 1608873
    }
    terrain_level_point {
      sim_grid_pos_x: 1678401.88
      sim_grid_pos_y: 1608697.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1678508.25
      sim_grid_pos_y: 1608573.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678641.88
      sim_grid_pos_y: 1608455.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1678854.62
      sim_grid_pos_y: 1608655.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1679050.75
      sim_grid_pos_y: 1608593.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1679463.62
      sim_grid_pos_y: 1608845.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1679294.12
      sim_grid_pos_y: 1609031.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1678815.25
      sim_grid_pos_y: 1608966.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1678867.75
      sim_grid_pos_y: 1608597.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1679057.62
      sim_grid_pos_y: 1608537.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1679543.5
      sim_grid_pos_y: 1608834.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1679313.75
      sim_grid_pos_y: 1609085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1678823.88
      sim_grid_pos_y: 1609019
    }
    terrain_level_point {
      sim_grid_pos_x: 1678193.62
      sim_grid_pos_y: 1609331.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1678011.88
      sim_grid_pos_y: 1608849.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1678369.12
      sim_grid_pos_y: 1608657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1678471.62
      sim_grid_pos_y: 1608537.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678643
      sim_grid_pos_y: 1608386
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1678881
      sim_grid_pos_y: 1608539.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1679064.38
      sim_grid_pos_y: 1608481.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1679623.25
      sim_grid_pos_y: 1608823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1679333.5
      sim_grid_pos_y: 1.60914e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1678832.62
      sim_grid_pos_y: 1609072
    }
    terrain_level_point {
      sim_grid_pos_x: 1678165.62
      sim_grid_pos_y: 1609402.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1677948
      sim_grid_pos_y: 1608825.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1678336.5
      sim_grid_pos_y: 1608616.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678435.12
      sim_grid_pos_y: 1608501.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678644
      sim_grid_pos_y: 1608316.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1678894.12
      sim_grid_pos_y: 1608481.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1679071.12
      sim_grid_pos_y: 1608425.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1679703.12
      sim_grid_pos_y: 1608812.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1679353.12
      sim_grid_pos_y: 1609194.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1678841.25
      sim_grid_pos_y: 1609124.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1678137.62
      sim_grid_pos_y: 1609473.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1677884.25
      sim_grid_pos_y: 1608801.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1678303.75
      sim_grid_pos_y: 1608576
    }
    terrain_level_point {
      sim_grid_pos_x: 1678398.38
      sim_grid_pos_y: 1608465.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1678645.12
      sim_grid_pos_y: 1608247.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1678907.38
      sim_grid_pos_y: 1608423.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1679077.88
      sim_grid_pos_y: 1608369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1679782.88
      sim_grid_pos_y: 1608801
    }
    terrain_level_point {
      sim_grid_pos_x: 1679372.88
      sim_grid_pos_y: 1609248.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.67885e+06
      sim_grid_pos_y: 1609177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1678109.62
      sim_grid_pos_y: 1609545
    }
    terrain_level_point {
      sim_grid_pos_x: 1677820.5
      sim_grid_pos_y: 1608777.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1678271.12
      sim_grid_pos_y: 1608535.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1678361.88
      sim_grid_pos_y: 1608429.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1678646.12
      sim_grid_pos_y: 1608177.75
    }
  }
}
terrain_level_data {
  terrain_level: 1456
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1678207.12
      sim_grid_pos_y: 1609602.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1678213.62
      sim_grid_pos_y: 1609810.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678402.12
      sim_grid_pos_y: 1609802.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1678405
      sim_grid_pos_y: 1609610.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1678154.25
      sim_grid_pos_y: 1609549
    }
    terrain_level_point {
      sim_grid_pos_x: 1678164
      sim_grid_pos_y: 1609864
    }
    terrain_level_point {
      sim_grid_pos_x: 1678452.62
      sim_grid_pos_y: 1609851.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678457
      sim_grid_pos_y: 1609561
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1678101.25
      sim_grid_pos_y: 1609495.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1678114.38
      sim_grid_pos_y: 1609917.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1678503.12
      sim_grid_pos_y: 1609900.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1678509
      sim_grid_pos_y: 1609511.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1678048.25
      sim_grid_pos_y: 1609442.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1678064.88
      sim_grid_pos_y: 1609970.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1678553.62
      sim_grid_pos_y: 1.60995e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1678561
      sim_grid_pos_y: 1609462.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1677995.38
      sim_grid_pos_y: 1609388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1678015.25
      sim_grid_pos_y: 1610024.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1678604.12
      sim_grid_pos_y: 1609999.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1678613
      sim_grid_pos_y: 1609413.25
    }
  }
}
