terrain_level_data {
  terrain_level: 176
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1034016.31
      sim_grid_pos_y: 1684151.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1033652.06
      sim_grid_pos_y: 1684466.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1032195.31
      sim_grid_pos_y: 1684812.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1031326.56
      sim_grid_pos_y: 1683770.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1030692.44
      sim_grid_pos_y: 1683263.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1030477.38
      sim_grid_pos_y: 1682926.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1029895.12
      sim_grid_pos_y: 1682615.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.02838e+06
      sim_grid_pos_y: 1680792
    }
    terrain_level_point {
      sim_grid_pos_x: 1028270.69
      sim_grid_pos_y: 1679925.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1025358.31
      sim_grid_pos_y: 1676171.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1027843.56
      sim_grid_pos_y: 1674626.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1029753.44
      sim_grid_pos_y: 1674939.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1031492.25
      sim_grid_pos_y: 1676402.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1033930.75
      sim_grid_pos_y: 1676960.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1035039.81
      sim_grid_pos_y: 1678953.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1029766.75
      sim_grid_pos_y: 1674910.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1031506.38
      sim_grid_pos_y: 1676373.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1033951
      sim_grid_pos_y: 1676933.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1035072.12
      sim_grid_pos_y: 1678948.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1034044.44
      sim_grid_pos_y: 1684167.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1033666.5
      sim_grid_pos_y: 1684494.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1032183.88
      sim_grid_pos_y: 1684847.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1031304.88
      sim_grid_pos_y: 1683792.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1030669.25
      sim_grid_pos_y: 1683283.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1030455.75
      sim_grid_pos_y: 1682950.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1029875.31
      sim_grid_pos_y: 1682639.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1028350.56
      sim_grid_pos_y: 1680804.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1028241.25
      sim_grid_pos_y: 1679937.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1025313.12
      sim_grid_pos_y: 1676163
    }
    terrain_level_point {
      sim_grid_pos_x: 1027837.12
      sim_grid_pos_y: 1674594.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1029780.06
      sim_grid_pos_y: 1674881.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1031520.44
      sim_grid_pos_y: 1676345.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1033971.19
      sim_grid_pos_y: 1676906.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1035104.5
      sim_grid_pos_y: 1678943.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1034072.56
      sim_grid_pos_y: 1684184
    }
    terrain_level_point {
      sim_grid_pos_x: 1033680.94
      sim_grid_pos_y: 1684522.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1032172.5
      sim_grid_pos_y: 1684881.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1031283.25
      sim_grid_pos_y: 1683814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1030646.06
      sim_grid_pos_y: 1683304.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1030434.19
      sim_grid_pos_y: 1682973.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1029855.5
      sim_grid_pos_y: 1682664.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1028321.19
      sim_grid_pos_y: 1680817.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1028211.81
      sim_grid_pos_y: 1679949.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1025267.88
      sim_grid_pos_y: 1676154.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1027830.69
      sim_grid_pos_y: 1674562.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1029793.44
      sim_grid_pos_y: 1674852.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1031534.56
      sim_grid_pos_y: 1676317.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1033991.38
      sim_grid_pos_y: 1676879.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1035136.88
      sim_grid_pos_y: 1678938.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1034100.69
      sim_grid_pos_y: 1684200.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1033695.38
      sim_grid_pos_y: 1684550.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1032161.06
      sim_grid_pos_y: 1684915.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1031261.56
      sim_grid_pos_y: 1683836.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1030622.94
      sim_grid_pos_y: 1683325.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1030412.56
      sim_grid_pos_y: 1682996.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1029835.69
      sim_grid_pos_y: 1682688.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1028291.81
      sim_grid_pos_y: 1680830.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1028182.31
      sim_grid_pos_y: 1679961.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1025222.69
      sim_grid_pos_y: 1676146.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1027824.25
      sim_grid_pos_y: 1.67453e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1029806.75
      sim_grid_pos_y: 1674823.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1031548.69
      sim_grid_pos_y: 1676288.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1034011.62
      sim_grid_pos_y: 1676852.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1035169.25
      sim_grid_pos_y: 1678933.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1034128.81
      sim_grid_pos_y: 1684216.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1033709.81
      sim_grid_pos_y: 1684579.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1032149.62
      sim_grid_pos_y: 1684950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.03124e+06
      sim_grid_pos_y: 1683858.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1030599.75
      sim_grid_pos_y: 1683346.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1030391
      sim_grid_pos_y: 1683020.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1029815.88
      sim_grid_pos_y: 1682712.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1028262.38
      sim_grid_pos_y: 1680843
    }
    terrain_level_point {
      sim_grid_pos_x: 1028152.88
      sim_grid_pos_y: 1679973.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1025177.44
      sim_grid_pos_y: 1676138.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1027817.81
      sim_grid_pos_y: 1674497.88
    }
  }
}
