terrain_level_data {
  terrain_level: 164
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2899611.75
      sim_grid_pos_y: 588096.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2898032.5
      sim_grid_pos_y: 586058.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2897716.75
      sim_grid_pos_y: 584807.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2897809.5
      sim_grid_pos_y: 584095.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2.89912e+06
      sim_grid_pos_y: 584264.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2899166.75
      sim_grid_pos_y: 584495.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2900514.25
      sim_grid_pos_y: 585548.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2902422
      sim_grid_pos_y: 587755.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2903768
      sim_grid_pos_y: 589879.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2904101.5
      sim_grid_pos_y: 591432.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2903703.75
      sim_grid_pos_y: 592026.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2902171.25
      sim_grid_pos_y: 591093.125
    }
  }
}
