terrain_level_data {
  terrain_level: 120
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 734921.375
      sim_grid_pos_y: 2023315.62
    }
    terrain_level_point {
      sim_grid_pos_x: 734020
      sim_grid_pos_y: 2024687.38
    }
    terrain_level_point {
      sim_grid_pos_x: 733170.25
      sim_grid_pos_y: 2025993.12
    }
    terrain_level_point {
      sim_grid_pos_x: 733773.438
      sim_grid_pos_y: 2026374.5
    }
    terrain_level_point {
      sim_grid_pos_x: 733316.312
      sim_grid_pos_y: 2027047.25
    }
    terrain_level_point {
      sim_grid_pos_x: 732525
      sim_grid_pos_y: 2028222
    }
    terrain_level_point {
      sim_grid_pos_x: 731989.5
      sim_grid_pos_y: 2028279.62
    }
    terrain_level_point {
      sim_grid_pos_x: 731431.062
      sim_grid_pos_y: 2028916
    }
    terrain_level_point {
      sim_grid_pos_x: 730993.062
      sim_grid_pos_y: 2028765
    }
    terrain_level_point {
      sim_grid_pos_x: 730412
      sim_grid_pos_y: 2028083.12
    }
    terrain_level_point {
      sim_grid_pos_x: 729528.312
      sim_grid_pos_y: 2026557.62
    }
    terrain_level_point {
      sim_grid_pos_x: 731546.875
      sim_grid_pos_y: 2023492.25
    }
    terrain_level_point {
      sim_grid_pos_x: 731045.25
      sim_grid_pos_y: 2022849.62
    }
    terrain_level_point {
      sim_grid_pos_x: 730919.188
      sim_grid_pos_y: 2022194.75
    }
    terrain_level_point {
      sim_grid_pos_x: 731471.562
      sim_grid_pos_y: 2021454.88
    }
    terrain_level_point {
      sim_grid_pos_x: 731895
      sim_grid_pos_y: 2020891.5
    }
    terrain_level_point {
      sim_grid_pos_x: 732798.562
      sim_grid_pos_y: 2020547.62
    }
    terrain_level_point {
      sim_grid_pos_x: 733669.438
      sim_grid_pos_y: 2018860.5
    }
    terrain_level_point {
      sim_grid_pos_x: 734575.5
      sim_grid_pos_y: 2018593.75
    }
    terrain_level_point {
      sim_grid_pos_x: 735122.688
      sim_grid_pos_y: 2017792.88
    }
    terrain_level_point {
      sim_grid_pos_x: 734391.688
      sim_grid_pos_y: 2017241.88
    }
    terrain_level_point {
      sim_grid_pos_x: 735459
      sim_grid_pos_y: 2015622
    }
    terrain_level_point {
      sim_grid_pos_x: 737785.75
      sim_grid_pos_y: 2017351.12
    }
    terrain_level_point {
      sim_grid_pos_x: 737685.938
      sim_grid_pos_y: 2019295.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 737890.938
      sim_grid_pos_y: 2017301.5
    }
    terrain_level_point {
      sim_grid_pos_x: 737786.875
      sim_grid_pos_y: 2019329.88
    }
    terrain_level_point {
      sim_grid_pos_x: 735006.25
      sim_grid_pos_y: 2023373.12
    }
    terrain_level_point {
      sim_grid_pos_x: 734105.938
      sim_grid_pos_y: 2024743.25
    }
    terrain_level_point {
      sim_grid_pos_x: 734105.938
      sim_grid_pos_y: 2024743.25
    }
    terrain_level_point {
      sim_grid_pos_x: 733312.812
      sim_grid_pos_y: 2025961.88
    }
    terrain_level_point {
      sim_grid_pos_x: 733917.75
      sim_grid_pos_y: 2026344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 733401.125
      sim_grid_pos_y: 2027104.88
    }
    terrain_level_point {
      sim_grid_pos_x: 732583.375
      sim_grid_pos_y: 2028318.88
    }
    terrain_level_point {
      sim_grid_pos_x: 732040.188
      sim_grid_pos_y: 2028377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 731462.75
      sim_grid_pos_y: 2029035.38
    }
    terrain_level_point {
      sim_grid_pos_x: 730933.188
      sim_grid_pos_y: 2028852.75
    }
    terrain_level_point {
      sim_grid_pos_x: 730327.938
      sim_grid_pos_y: 2028142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 729407.875
      sim_grid_pos_y: 2026554.12
    }
    terrain_level_point {
      sim_grid_pos_x: 731420.812
      sim_grid_pos_y: 2023497.38
    }
    terrain_level_point {
      sim_grid_pos_x: 730949.25
      sim_grid_pos_y: 2022893.25
    }
    terrain_level_point {
      sim_grid_pos_x: 730809.938
      sim_grid_pos_y: 2022169.75
    }
    terrain_level_point {
      sim_grid_pos_x: 731389.5
      sim_grid_pos_y: 2021393.38
    }
    terrain_level_point {
      sim_grid_pos_x: 731830.875
      sim_grid_pos_y: 2020806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 732725.5
      sim_grid_pos_y: 2020465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 733598.438
      sim_grid_pos_y: 2018774.62
    }
    terrain_level_point {
      sim_grid_pos_x: 734511.438
      sim_grid_pos_y: 2018505.75
    }
    terrain_level_point {
      sim_grid_pos_x: 734982.812
      sim_grid_pos_y: 2017815.88
    }
    terrain_level_point {
      sim_grid_pos_x: 734253.125
      sim_grid_pos_y: 2017265.88
    }
    terrain_level_point {
      sim_grid_pos_x: 735433.062
      sim_grid_pos_y: 2015475
    }
  }
}
