terrain_level_data {
  terrain_level: 16
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 35868.6602
      sim_grid_pos_y: 2.82362e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 39522.8555
      sim_grid_pos_y: 2829984.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39949.7578
      sim_grid_pos_y: 2830288.25
    }
    terrain_level_point {
      sim_grid_pos_x: 40492.207
      sim_grid_pos_y: 2829992
    }
    terrain_level_point {
      sim_grid_pos_x: 40406.4336
      sim_grid_pos_y: 2829501
    }
    terrain_level_point {
      sim_grid_pos_x: 40279.5469
      sim_grid_pos_y: 2829269.5
    }
    terrain_level_point {
      sim_grid_pos_x: 40055.1
      sim_grid_pos_y: 2828271.75
    }
    terrain_level_point {
      sim_grid_pos_x: 38647.8789
      sim_grid_pos_y: 2825791.75
    }
    terrain_level_point {
      sim_grid_pos_x: 39393.2695
      sim_grid_pos_y: 2825406
    }
    terrain_level_point {
      sim_grid_pos_x: 39744.9648
      sim_grid_pos_y: 2825472
    }
    terrain_level_point {
      sim_grid_pos_x: 39871.8125
      sim_grid_pos_y: 2.82568e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 39935.2344
      sim_grid_pos_y: 2825161
    }
    terrain_level_point {
      sim_grid_pos_x: 39469.9453
      sim_grid_pos_y: 2824369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 38908.3
      sim_grid_pos_y: 2823987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 37892.4805
      sim_grid_pos_y: 2823299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 37678.5703
      sim_grid_pos_y: 2823418
    }
    terrain_level_point {
      sim_grid_pos_x: 37480.6133
      sim_grid_pos_y: 2.82319e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 36940.6367
      sim_grid_pos_y: 2822803
    }
    terrain_level_point {
      sim_grid_pos_x: 36824.6484
      sim_grid_pos_y: 2822609.5
    }
    terrain_level_point {
      sim_grid_pos_x: 36052.6523
      sim_grid_pos_y: 2821840.75
    }
    terrain_level_point {
      sim_grid_pos_x: 35904.6562
      sim_grid_pos_y: 2821764.25
    }
    terrain_level_point {
      sim_grid_pos_x: 35088.6562
      sim_grid_pos_y: 2822272.25
    }
    terrain_level_point {
      sim_grid_pos_x: 35107.6562
      sim_grid_pos_y: 2822834
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 35902.3047
      sim_grid_pos_y: 2821705.25
    }
    terrain_level_point {
      sim_grid_pos_x: 35036.4258
      sim_grid_pos_y: 2822244.5
    }
    terrain_level_point {
      sim_grid_pos_x: 35057.0859
      sim_grid_pos_y: 2822855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 35827.3867
      sim_grid_pos_y: 2823651
    }
    terrain_level_point {
      sim_grid_pos_x: 39483.9844
      sim_grid_pos_y: 2830019.75
    }
    terrain_level_point {
      sim_grid_pos_x: 39946.1758
      sim_grid_pos_y: 2830348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 40549.0273
      sim_grid_pos_y: 2830019.5
    }
    terrain_level_point {
      sim_grid_pos_x: 40455.4766
      sim_grid_pos_y: 2829483.75
    }
    terrain_level_point {
      sim_grid_pos_x: 40327.9648
      sim_grid_pos_y: 2829251.25
    }
    terrain_level_point {
      sim_grid_pos_x: 40103.4453
      sim_grid_pos_y: 2828253
    }
    terrain_level_point {
      sim_grid_pos_x: 38718.7578
      sim_grid_pos_y: 2825812.75
    }
    terrain_level_point {
      sim_grid_pos_x: 39401.1562
      sim_grid_pos_y: 2825459.75
    }
    terrain_level_point {
      sim_grid_pos_x: 39713.0664
      sim_grid_pos_y: 2825518.25
    }
    terrain_level_point {
      sim_grid_pos_x: 39847.0273
      sim_grid_pos_y: 2825737.75
    }
    terrain_level_point {
      sim_grid_pos_x: 39918.2773
      sim_grid_pos_y: 2825722.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39988.2266
      sim_grid_pos_y: 2.82515e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 39508.2969
      sim_grid_pos_y: 2824333.5
    }
    terrain_level_point {
      sim_grid_pos_x: 38937.0781
      sim_grid_pos_y: 2823945.25
    }
    terrain_level_point {
      sim_grid_pos_x: 37895.1953
      sim_grid_pos_y: 2823239.75
    }
    terrain_level_point {
      sim_grid_pos_x: 37690.0859
      sim_grid_pos_y: 2823353
    }
    terrain_level_point {
      sim_grid_pos_x: 37515.375
      sim_grid_pos_y: 2823151.75
    }
    terrain_level_point {
      sim_grid_pos_x: 36979.1445
      sim_grid_pos_y: 2822767.5
    }
    terrain_level_point {
      sim_grid_pos_x: 36865.3359
      sim_grid_pos_y: 2822577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 36083.2266
      sim_grid_pos_y: 2821798.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 35899.957
      sim_grid_pos_y: 2821646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 34984.1875
      sim_grid_pos_y: 2822216.5
    }
    terrain_level_point {
      sim_grid_pos_x: 35006.5273
      sim_grid_pos_y: 2822877
    }
    terrain_level_point {
      sim_grid_pos_x: 35786.125
      sim_grid_pos_y: 2823682.25
    }
    terrain_level_point {
      sim_grid_pos_x: 39445.125
      sim_grid_pos_y: 2830055
    }
    terrain_level_point {
      sim_grid_pos_x: 39942.5977
      sim_grid_pos_y: 2830409
    }
    terrain_level_point {
      sim_grid_pos_x: 40605.8477
      sim_grid_pos_y: 2830046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 40504.5078
      sim_grid_pos_y: 2829466.5
    }
    terrain_level_point {
      sim_grid_pos_x: 40376.3945
      sim_grid_pos_y: 2829233
    }
    terrain_level_point {
      sim_grid_pos_x: 40151.7969
      sim_grid_pos_y: 2828234.5
    }
    terrain_level_point {
      sim_grid_pos_x: 38789.6367
      sim_grid_pos_y: 2825833.75
    }
    terrain_level_point {
      sim_grid_pos_x: 39409.0352
      sim_grid_pos_y: 2825513.25
    }
    terrain_level_point {
      sim_grid_pos_x: 39681.1953
      sim_grid_pos_y: 2825564.25
    }
    terrain_level_point {
      sim_grid_pos_x: 39822.2344
      sim_grid_pos_y: 2825795.5
    }
    terrain_level_point {
      sim_grid_pos_x: 39964.7461
      sim_grid_pos_y: 2825764.75
    }
    terrain_level_point {
      sim_grid_pos_x: 40041.2148
      sim_grid_pos_y: 2825139
    }
    terrain_level_point {
      sim_grid_pos_x: 39546.6445
      sim_grid_pos_y: 2824297.75
    }
    terrain_level_point {
      sim_grid_pos_x: 38965.8555
      sim_grid_pos_y: 2823903
    }
    terrain_level_point {
      sim_grid_pos_x: 37897.9062
      sim_grid_pos_y: 2823179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 37701.5977
      sim_grid_pos_y: 2823288.25
    }
    terrain_level_point {
      sim_grid_pos_x: 37550.1367
      sim_grid_pos_y: 2823113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 37017.6562
      sim_grid_pos_y: 2822732
    }
    terrain_level_point {
      sim_grid_pos_x: 36906.0273
      sim_grid_pos_y: 2822545.75
    }
    terrain_level_point {
      sim_grid_pos_x: 36113.7852
      sim_grid_pos_y: 2821757
    }
  }
}
