terrain_level_data {
  terrain_level: 292
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1140833.25
      sim_grid_pos_y: 1789463.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1142078.38
      sim_grid_pos_y: 1789354.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1144436.25
      sim_grid_pos_y: 1790202.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1145540.12
      sim_grid_pos_y: 1789773.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1146174.75
      sim_grid_pos_y: 1790232.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1147751.62
      sim_grid_pos_y: 1790069.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1149050.75
      sim_grid_pos_y: 1789063.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1150592
      sim_grid_pos_y: 1789045.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1151528.5
      sim_grid_pos_y: 1790145.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1151777
      sim_grid_pos_y: 1790841.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1151541
      sim_grid_pos_y: 1791887.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1151769.88
      sim_grid_pos_y: 1792813.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1151225.12
      sim_grid_pos_y: 1793476.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1150293.25
      sim_grid_pos_y: 1794245.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1150264.88
      sim_grid_pos_y: 1796136.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1144166.12
      sim_grid_pos_y: 1796061.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1143126.38
      sim_grid_pos_y: 1795687.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1142178
      sim_grid_pos_y: 1795642.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1140289.12
      sim_grid_pos_y: 1794990.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1139392
      sim_grid_pos_y: 1794808
    }
    terrain_level_point {
      sim_grid_pos_x: 1138814
      sim_grid_pos_y: 1793662.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1138688.88
      sim_grid_pos_y: 1791761.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1139923.88
      sim_grid_pos_y: 1789760.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1151618.75
      sim_grid_pos_y: 1790093.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1151883.62
      sim_grid_pos_y: 1790834.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1151646.38
      sim_grid_pos_y: 1791886.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1151881.75
      sim_grid_pos_y: 1792839
    }
    terrain_level_point {
      sim_grid_pos_x: 1151298
      sim_grid_pos_y: 1793549.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1150395
      sim_grid_pos_y: 1794294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1150365.88
      sim_grid_pos_y: 1796240.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1144147.62
      sim_grid_pos_y: 1796163.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1143106.12
      sim_grid_pos_y: 1795789
    }
    terrain_level_point {
      sim_grid_pos_x: 1142158.5
      sim_grid_pos_y: 1795744
    }
    terrain_level_point {
      sim_grid_pos_x: 1140262.12
      sim_grid_pos_y: 1.79509e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1139322.88
      sim_grid_pos_y: 1794898.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1138713.12
      sim_grid_pos_y: 1.79369e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1138584.38
      sim_grid_pos_y: 1791735.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1139856.38
      sim_grid_pos_y: 1789674.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1140812.62
      sim_grid_pos_y: 1789362.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1142091.88
      sim_grid_pos_y: 1.78925e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1144434.88
      sim_grid_pos_y: 1790092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1145555
      sim_grid_pos_y: 1789657.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1146203.12
      sim_grid_pos_y: 1790126.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1147712
      sim_grid_pos_y: 1789970.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1149015.12
      sim_grid_pos_y: 1788961.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1150638.88
      sim_grid_pos_y: 1788942.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1151709
      sim_grid_pos_y: 1790041
    }
    terrain_level_point {
      sim_grid_pos_x: 1151990.12
      sim_grid_pos_y: 1790828.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1151751.75
      sim_grid_pos_y: 1791885.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1151993.62
      sim_grid_pos_y: 1792864.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1151371
      sim_grid_pos_y: 1793622
    }
    terrain_level_point {
      sim_grid_pos_x: 1150496.88
      sim_grid_pos_y: 1794343.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1150466.88
      sim_grid_pos_y: 1796344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1144129.12
      sim_grid_pos_y: 1796265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1143086
      sim_grid_pos_y: 1795890.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1142138.88
      sim_grid_pos_y: 1795845.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140235
      sim_grid_pos_y: 1795189.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1139253.62
      sim_grid_pos_y: 1794989.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1138612.12
      sim_grid_pos_y: 1793717.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.13848e+06
      sim_grid_pos_y: 1.79171e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1139788.88
      sim_grid_pos_y: 1789589
    }
    terrain_level_point {
      sim_grid_pos_x: 1140791.88
      sim_grid_pos_y: 1789261.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1142105.38
      sim_grid_pos_y: 1789145.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1144433.5
      sim_grid_pos_y: 1789983.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1145569.88
      sim_grid_pos_y: 1789541.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1146231.5
      sim_grid_pos_y: 1790020.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1147672.38
      sim_grid_pos_y: 1789871.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1148979.62
      sim_grid_pos_y: 1788859.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1150685.75
      sim_grid_pos_y: 1788839.25
    }
  }
}
