terrain_level_data {
  terrain_level: 85
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1413638.12
      sim_grid_pos_y: 1475701.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1413040.5
      sim_grid_pos_y: 1475857.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411669.75
      sim_grid_pos_y: 1476278.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411327.12
      sim_grid_pos_y: 1476323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1410890.75
      sim_grid_pos_y: 1476328.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1410777.5
      sim_grid_pos_y: 1476115.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1410782
      sim_grid_pos_y: 1475959.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1411166
      sim_grid_pos_y: 1475606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1411260.5
      sim_grid_pos_y: 1475296.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411419
      sim_grid_pos_y: 1474876.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1411643.88
      sim_grid_pos_y: 1474856.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1411701
      sim_grid_pos_y: 1474972.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1411789.5
      sim_grid_pos_y: 1475007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1411794.5
      sim_grid_pos_y: 1475083.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1411734.88
      sim_grid_pos_y: 1475123.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411633.12
      sim_grid_pos_y: 1475140.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411576.5
      sim_grid_pos_y: 1475385.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411744.75
      sim_grid_pos_y: 1475408
    }
    terrain_level_point {
      sim_grid_pos_x: 1411876.62
      sim_grid_pos_y: 1475278.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411916.62
      sim_grid_pos_y: 1475197.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1412079.12
      sim_grid_pos_y: 1475122.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1412121.5
      sim_grid_pos_y: 1475172.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1412124.38
      sim_grid_pos_y: 1475232.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1412182.38
      sim_grid_pos_y: 1475256.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1412296.25
      sim_grid_pos_y: 1475199.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1412302.25
      sim_grid_pos_y: 1475155.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1412256.25
      sim_grid_pos_y: 1475117.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1412193.75
      sim_grid_pos_y: 1475136.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1412179.38
      sim_grid_pos_y: 1475086.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1412210.62
      sim_grid_pos_y: 1475059.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1412161.38
      sim_grid_pos_y: 1474821.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1412007.75
      sim_grid_pos_y: 1474864.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411865.75
      sim_grid_pos_y: 1474913.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1411846.25
      sim_grid_pos_y: 1474932.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1411777.62
      sim_grid_pos_y: 1474901.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411703.38
      sim_grid_pos_y: 1474908.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1411741.38
      sim_grid_pos_y: 1474676.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411882.38
      sim_grid_pos_y: 1474504.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1412191.12
      sim_grid_pos_y: 1474536
    }
    terrain_level_point {
      sim_grid_pos_x: 1412701.5
      sim_grid_pos_y: 1474204.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1413218.12
      sim_grid_pos_y: 1474248.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1413399.25
      sim_grid_pos_y: 1474240.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1413981.62
      sim_grid_pos_y: 1473983.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1414587.12
      sim_grid_pos_y: 1473604
    }
    terrain_level_point {
      sim_grid_pos_x: 1414792.75
      sim_grid_pos_y: 1473691.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1415249.5
      sim_grid_pos_y: 1474722.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1413856.75
      sim_grid_pos_y: 1475621.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1414870.12
      sim_grid_pos_y: 1473612.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1415378.75
      sim_grid_pos_y: 1474761.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1413902.62
      sim_grid_pos_y: 1475713.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1413668.75
      sim_grid_pos_y: 1475799.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1413068.38
      sim_grid_pos_y: 1475955.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1411691.62
      sim_grid_pos_y: 1476379
    }
    terrain_level_point {
      sim_grid_pos_x: 1411334.38
      sim_grid_pos_y: 1476425.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1410829.62
      sim_grid_pos_y: 1476431.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1410674.25
      sim_grid_pos_y: 1476139.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1410680.75
      sim_grid_pos_y: 1475913.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1411076
      sim_grid_pos_y: 1475549.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411163.38
      sim_grid_pos_y: 1475263.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411345.75
      sim_grid_pos_y: 1474780.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1411624.5
      sim_grid_pos_y: 1474755.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411644.75
      sim_grid_pos_y: 1474632.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1411838
      sim_grid_pos_y: 1474397.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1412165.5
      sim_grid_pos_y: 1474430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1412675.12
      sim_grid_pos_y: 1474099.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1413220.12
      sim_grid_pos_y: 1474145.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1413375.5
      sim_grid_pos_y: 1474138.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1413933.38
      sim_grid_pos_y: 1473892.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1414577.88
      sim_grid_pos_y: 1473488.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1414947.38
      sim_grid_pos_y: 1473533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1415508
      sim_grid_pos_y: 1.4748e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1413948.62
      sim_grid_pos_y: 1475806
    }
    terrain_level_point {
      sim_grid_pos_x: 1413699.38
      sim_grid_pos_y: 1475897.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1413096.5
      sim_grid_pos_y: 1476054.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411713.5
      sim_grid_pos_y: 1476479.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411341.62
      sim_grid_pos_y: 1476528.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1410768.38
      sim_grid_pos_y: 1476534.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1410571
      sim_grid_pos_y: 1476164
    }
    terrain_level_point {
      sim_grid_pos_x: 1410579.5
      sim_grid_pos_y: 1475867.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1410986.12
      sim_grid_pos_y: 1475493.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411066.38
      sim_grid_pos_y: 1475230.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1411272.5
      sim_grid_pos_y: 1474683.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1411536.25
      sim_grid_pos_y: 1474660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411548
      sim_grid_pos_y: 1474589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411793.62
      sim_grid_pos_y: 1474289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.41214e+06
      sim_grid_pos_y: 1474324.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1412648.75
      sim_grid_pos_y: 1473994.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1413222.12
      sim_grid_pos_y: 1474042.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1413351.75
      sim_grid_pos_y: 1474037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1413885.25
      sim_grid_pos_y: 1473802.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1414568.62
      sim_grid_pos_y: 1473373.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1415024.75
      sim_grid_pos_y: 1473455.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1415637.25
      sim_grid_pos_y: 1474838.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1413994.62
      sim_grid_pos_y: 1475898.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.41373e+06
      sim_grid_pos_y: 1475995.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1413124.5
      sim_grid_pos_y: 1476153.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411735.38
      sim_grid_pos_y: 1476580.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411348.88
      sim_grid_pos_y: 1476630.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1410707.25
      sim_grid_pos_y: 1476638
    }
    terrain_level_point {
      sim_grid_pos_x: 1410467.75
      sim_grid_pos_y: 1476188.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1410478.25
      sim_grid_pos_y: 1475821.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1410896.12
      sim_grid_pos_y: 1475436.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1410969.25
      sim_grid_pos_y: 1475197.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1411199.38
      sim_grid_pos_y: 1474587.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1411448
      sim_grid_pos_y: 1474565.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1411451.25
      sim_grid_pos_y: 1474545.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1411749.25
      sim_grid_pos_y: 1474182.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1412114.38
      sim_grid_pos_y: 1474219.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1412622.38
      sim_grid_pos_y: 1473889.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1413224.38
      sim_grid_pos_y: 1473940.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1413328
      sim_grid_pos_y: 1473935.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1413837.12
      sim_grid_pos_y: 1473711.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1414559.5
      sim_grid_pos_y: 1473258.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1415102.12
      sim_grid_pos_y: 1473376.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1415766.5
      sim_grid_pos_y: 1474877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1414040.62
      sim_grid_pos_y: 1475990.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1413760.62
      sim_grid_pos_y: 1476093.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1413152.62
      sim_grid_pos_y: 1476251.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1411757.25
      sim_grid_pos_y: 1476680.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1411356.12
      sim_grid_pos_y: 1476733.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1410646
      sim_grid_pos_y: 1476741.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1410364.5
      sim_grid_pos_y: 1476212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1410377
      sim_grid_pos_y: 1475775.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1410806.25
      sim_grid_pos_y: 1.47538e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1410872.12
      sim_grid_pos_y: 1475164.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411126.12
      sim_grid_pos_y: 1474491.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1411381.88
      sim_grid_pos_y: 1474468.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1411704.88
      sim_grid_pos_y: 1474074.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1412088.88
      sim_grid_pos_y: 1474113.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1412596
      sim_grid_pos_y: 1473784.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1413226.38
      sim_grid_pos_y: 1473837.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1413304.38
      sim_grid_pos_y: 1473834
    }
    terrain_level_point {
      sim_grid_pos_x: 1413789
      sim_grid_pos_y: 1473620.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1414550.25
      sim_grid_pos_y: 1473143.12
    }
  }
}
