terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2883241
      sim_grid_pos_y: 2307054.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2883560.75
      sim_grid_pos_y: 2307436.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2883174.75
      sim_grid_pos_y: 2308434.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2882289.25
      sim_grid_pos_y: 2309135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2881888.25
      sim_grid_pos_y: 2308206
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2883596
      sim_grid_pos_y: 2307431
    }
    terrain_level_point {
      sim_grid_pos_x: 2883200.25
      sim_grid_pos_y: 2308453.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2882276.75
      sim_grid_pos_y: 2309184.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2881851
      sim_grid_pos_y: 2308197.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2883244.75
      sim_grid_pos_y: 2307010.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2883631.25
      sim_grid_pos_y: 2307425
    }
    terrain_level_point {
      sim_grid_pos_x: 2883226
      sim_grid_pos_y: 2308472.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2882264.5
      sim_grid_pos_y: 2309233.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2881813.75
      sim_grid_pos_y: 2308188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2883248.5
      sim_grid_pos_y: 2306967
    }
  }
}
