terrain_level_data {
  terrain_level: 190
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1661888.5
      sim_grid_pos_y: 1149870.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1661886.5
      sim_grid_pos_y: 1150065.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1661946.25
      sim_grid_pos_y: 1150102.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1661910.88
      sim_grid_pos_y: 1150183.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1661945.38
      sim_grid_pos_y: 1150258
    }
    terrain_level_point {
      sim_grid_pos_x: 1662136
      sim_grid_pos_y: 1150282.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1662183.12
      sim_grid_pos_y: 1150213.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1662171.5
      sim_grid_pos_y: 1149942.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1662101.75
      sim_grid_pos_y: 1149866.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1662003
      sim_grid_pos_y: 1149787.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1662004.38
      sim_grid_pos_y: 1149723.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1661837.62
      sim_grid_pos_y: 1149844.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1661834.88
      sim_grid_pos_y: 1150094.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1661881.38
      sim_grid_pos_y: 1150122.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1661854.62
      sim_grid_pos_y: 1150184.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1661910.75
      sim_grid_pos_y: 1150305.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1662160.62
      sim_grid_pos_y: 1150336.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1662235.12
      sim_grid_pos_y: 1150228.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1662221.88
      sim_grid_pos_y: 1149922.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1662136.88
      sim_grid_pos_y: 1149828.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1662005.88
      sim_grid_pos_y: 1149658.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1661786.62
      sim_grid_pos_y: 1149818
    }
    terrain_level_point {
      sim_grid_pos_x: 1661783.38
      sim_grid_pos_y: 1150122.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1661816.62
      sim_grid_pos_y: 1150143.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1661798.38
      sim_grid_pos_y: 1150184.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1661876.25
      sim_grid_pos_y: 1150352.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1662185.25
      sim_grid_pos_y: 1150391.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1662287
      sim_grid_pos_y: 1150243
    }
    terrain_level_point {
      sim_grid_pos_x: 1662272.25
      sim_grid_pos_y: 1149901.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1662172
      sim_grid_pos_y: 1149791.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1662007.38
      sim_grid_pos_y: 1149594.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1661735.62
      sim_grid_pos_y: 1149791.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1661731.75
      sim_grid_pos_y: 1150151.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1661751.88
      sim_grid_pos_y: 1150163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1661742.25
      sim_grid_pos_y: 1150185.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1661841.62
      sim_grid_pos_y: 1150399.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1662209.88
      sim_grid_pos_y: 1150446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1662339
      sim_grid_pos_y: 1150257.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1662322.75
      sim_grid_pos_y: 1149880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1662207.12
      sim_grid_pos_y: 1149753.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1662008.75
      sim_grid_pos_y: 1149530.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1661684.62
      sim_grid_pos_y: 1149765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1661680.12
      sim_grid_pos_y: 1150179.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1661687
      sim_grid_pos_y: 1150183.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1661686
      sim_grid_pos_y: 1150186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1661807
      sim_grid_pos_y: 1150447.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1662234.5
      sim_grid_pos_y: 1150501.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1662391
      sim_grid_pos_y: 1150272.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1662373.12
      sim_grid_pos_y: 1149859.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1662242.25
      sim_grid_pos_y: 1149716.12
    }
  }
}
terrain_level_data {
  terrain_level: 80
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1660482.75
      sim_grid_pos_y: 1149880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1660487.88
      sim_grid_pos_y: 1150088.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1660457.62
      sim_grid_pos_y: 1150214.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1660639.25
      sim_grid_pos_y: 1150271.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1660770.38
      sim_grid_pos_y: 1150139.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1660765.38
      sim_grid_pos_y: 1149893.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1660430.25
      sim_grid_pos_y: 1149826.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1660436.5
      sim_grid_pos_y: 1150083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1660396.5
      sim_grid_pos_y: 1150248.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1660653.62
      sim_grid_pos_y: 1150330.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1660822.12
      sim_grid_pos_y: 1150159.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1660815.62
      sim_grid_pos_y: 1149844.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1660377.62
      sim_grid_pos_y: 1149772.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1660385
      sim_grid_pos_y: 1150077.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1660335.5
      sim_grid_pos_y: 1150283
    }
    terrain_level_point {
      sim_grid_pos_x: 1660668
      sim_grid_pos_y: 1150388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1660873.75
      sim_grid_pos_y: 1150180.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1660865.88
      sim_grid_pos_y: 1149795.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1660325
      sim_grid_pos_y: 1149719.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1660333.62
      sim_grid_pos_y: 1150072.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1660274.5
      sim_grid_pos_y: 1150317.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1660682.38
      sim_grid_pos_y: 1150446.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1660925.5
      sim_grid_pos_y: 1150201.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1660916.12
      sim_grid_pos_y: 1149747
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1660272.5
      sim_grid_pos_y: 1149665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1660282.25
      sim_grid_pos_y: 1150066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1660213.38
      sim_grid_pos_y: 1150351.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1660696.75
      sim_grid_pos_y: 1150505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1660977.12
      sim_grid_pos_y: 1150221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1660966.38
      sim_grid_pos_y: 1149698
    }
  }
}
