terrain_level_data {
  terrain_level: 136
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1327291.5
      sim_grid_pos_y: 1586499.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1327312
      sim_grid_pos_y: 1586539.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328258.25
      sim_grid_pos_y: 1586939.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328531.38
      sim_grid_pos_y: 1587055.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329186.88
      sim_grid_pos_y: 1587301.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329375.38
      sim_grid_pos_y: 1587396
    }
    terrain_level_point {
      sim_grid_pos_x: 1329302.38
      sim_grid_pos_y: 1587647.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329598.88
      sim_grid_pos_y: 1587744.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329915.25
      sim_grid_pos_y: 1587581.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1330033.88
      sim_grid_pos_y: 1587419
    }
    terrain_level_point {
      sim_grid_pos_x: 1329474
      sim_grid_pos_y: 1587155.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329464.62
      sim_grid_pos_y: 1587075.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329542.88
      sim_grid_pos_y: 1586948.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1330107.12
      sim_grid_pos_y: 1586510.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1330987
      sim_grid_pos_y: 1586142
    }
    terrain_level_point {
      sim_grid_pos_x: 1331418.88
      sim_grid_pos_y: 1585679.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1330860.25
      sim_grid_pos_y: 1585639.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329748.12
      sim_grid_pos_y: 1585914.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329549.12
      sim_grid_pos_y: 1585936.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1329404.88
      sim_grid_pos_y: 1585918.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329261.12
      sim_grid_pos_y: 1585894.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328917.62
      sim_grid_pos_y: 1585733.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328311.75
      sim_grid_pos_y: 1585357.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1327747.88
      sim_grid_pos_y: 1585020.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1327544.25
      sim_grid_pos_y: 1584943.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1327272.38
      sim_grid_pos_y: 1584922.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326923.25
      sim_grid_pos_y: 1585038.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326672.75
      sim_grid_pos_y: 1585129.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326621.38
      sim_grid_pos_y: 1585383.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326461.62
      sim_grid_pos_y: 1585599.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1326399.5
      sim_grid_pos_y: 1585800.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1326534.25
      sim_grid_pos_y: 1585836.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1326539.12
      sim_grid_pos_y: 1586001.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1326684.5
      sim_grid_pos_y: 1586222.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1326767.12
      sim_grid_pos_y: 1586333.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326874.25
      sim_grid_pos_y: 1586297.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326897.5
      sim_grid_pos_y: 1586247.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1327006
      sim_grid_pos_y: 1586304.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1327305.12
      sim_grid_pos_y: 1586427.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1327271.12
      sim_grid_pos_y: 1584912.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1326919.88
      sim_grid_pos_y: 1585029.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1326663.88
      sim_grid_pos_y: 1585122
    }
    terrain_level_point {
      sim_grid_pos_x: 1326611.75
      sim_grid_pos_y: 1585379.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1326452.38
      sim_grid_pos_y: 1585595.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1326386.5
      sim_grid_pos_y: 1585807.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1326524.25
      sim_grid_pos_y: 1585844.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326529
      sim_grid_pos_y: 1586004.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326676.12
      sim_grid_pos_y: 1586228.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326763.38
      sim_grid_pos_y: 1586345.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326881.75
      sim_grid_pos_y: 1586306
    }
    terrain_level_point {
      sim_grid_pos_x: 1326902.38
      sim_grid_pos_y: 1586261.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1327001.62
      sim_grid_pos_y: 1586313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1327293.5
      sim_grid_pos_y: 1586434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1327280.75
      sim_grid_pos_y: 1586501
    }
    terrain_level_point {
      sim_grid_pos_x: 1327304.5
      sim_grid_pos_y: 1586547.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328254.25
      sim_grid_pos_y: 1586949.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328527.5
      sim_grid_pos_y: 1587064.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329182.75
      sim_grid_pos_y: 1587310.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329363.25
      sim_grid_pos_y: 1587401.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329289.75
      sim_grid_pos_y: 1587654.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329599.75
      sim_grid_pos_y: 1587756
    }
    terrain_level_point {
      sim_grid_pos_x: 1329922
      sim_grid_pos_y: 1587589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1330049.5
      sim_grid_pos_y: 1587415
    }
    terrain_level_point {
      sim_grid_pos_x: 1329483.62
      sim_grid_pos_y: 1587148.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329475.25
      sim_grid_pos_y: 1587077.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329550.62
      sim_grid_pos_y: 1586955.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1330112.25
      sim_grid_pos_y: 1586519.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1330993
      sim_grid_pos_y: 1586150.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331430.75
      sim_grid_pos_y: 1585681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1331426
      sim_grid_pos_y: 1585669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1330859.38
      sim_grid_pos_y: 1585628.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1329746.38
      sim_grid_pos_y: 1585904.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329549.12
      sim_grid_pos_y: 1585926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329406.38
      sim_grid_pos_y: 1585908.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329264.12
      sim_grid_pos_y: 1585884.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328922.62
      sim_grid_pos_y: 1585724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328317.12
      sim_grid_pos_y: 1585348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1327752.25
      sim_grid_pos_y: 1585011.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1327546.5
      sim_grid_pos_y: 1584933.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1327269.88
      sim_grid_pos_y: 1584901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326916.5
      sim_grid_pos_y: 1585019.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326655
      sim_grid_pos_y: 1585114.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326602.12
      sim_grid_pos_y: 1585375
    }
    terrain_level_point {
      sim_grid_pos_x: 1326443
      sim_grid_pos_y: 1585590.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326373.62
      sim_grid_pos_y: 1585815
    }
    terrain_level_point {
      sim_grid_pos_x: 1326514.25
      sim_grid_pos_y: 1585852.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326518.75
      sim_grid_pos_y: 1586007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326667.75
      sim_grid_pos_y: 1586234.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1326759.5
      sim_grid_pos_y: 1586357.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326889.25
      sim_grid_pos_y: 1586314.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326907.12
      sim_grid_pos_y: 1586275.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326997.25
      sim_grid_pos_y: 1586323.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1327281.88
      sim_grid_pos_y: 1586440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1327270.12
      sim_grid_pos_y: 1586502.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1327297.12
      sim_grid_pos_y: 1586555.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328250.25
      sim_grid_pos_y: 1586958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328250.25
      sim_grid_pos_y: 1586958.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328523.75
      sim_grid_pos_y: 1587074.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329178.62
      sim_grid_pos_y: 1.58732e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1329351
      sim_grid_pos_y: 1587406.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329277.12
      sim_grid_pos_y: 1587660.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1329600.62
      sim_grid_pos_y: 1587767
    }
    terrain_level_point {
      sim_grid_pos_x: 1329928.88
      sim_grid_pos_y: 1587597.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1330065.12
      sim_grid_pos_y: 1587411.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329493.12
      sim_grid_pos_y: 1587141.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329485.75
      sim_grid_pos_y: 1587079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329558.38
      sim_grid_pos_y: 1586962.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1330117.5
      sim_grid_pos_y: 1586528.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1330999
      sim_grid_pos_y: 1586159.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1331442.75
      sim_grid_pos_y: 1585684
    }
    terrain_level_point {
      sim_grid_pos_x: 1331433.25
      sim_grid_pos_y: 1585659.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1330858.5
      sim_grid_pos_y: 1585618.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329744.62
      sim_grid_pos_y: 1585894.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329549.25
      sim_grid_pos_y: 1585916.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329408
      sim_grid_pos_y: 1585898.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329267.25
      sim_grid_pos_y: 1585874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328927.5
      sim_grid_pos_y: 1585715.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328322.5
      sim_grid_pos_y: 1585339.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1327756.75
      sim_grid_pos_y: 1585002.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1327548.75
      sim_grid_pos_y: 1584923.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1327264.75
      sim_grid_pos_y: 1584860.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1326903
      sim_grid_pos_y: 1584980.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1326619.25
      sim_grid_pos_y: 1585083.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1326563.75
      sim_grid_pos_y: 1585358
    }
    terrain_level_point {
      sim_grid_pos_x: 1326406
      sim_grid_pos_y: 1585571.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326321.88
      sim_grid_pos_y: 1585843.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1326474.12
      sim_grid_pos_y: 1585884.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326478.12
      sim_grid_pos_y: 1586020.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1326634.12
      sim_grid_pos_y: 1586258.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1326744.38
      sim_grid_pos_y: 1586405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1326919
      sim_grid_pos_y: 1586347.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1326926.25
      sim_grid_pos_y: 1586331.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1326979.88
      sim_grid_pos_y: 1586360.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1327235.38
      sim_grid_pos_y: 1586465.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1327227.12
      sim_grid_pos_y: 1586508.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1327267.38
      sim_grid_pos_y: 1586587.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328234.25
      sim_grid_pos_y: 1586996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328234.25
      sim_grid_pos_y: 1586996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328508.62
      sim_grid_pos_y: 1587112.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329162.12
      sim_grid_pos_y: 1587357.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329302.12
      sim_grid_pos_y: 1587427.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329226.75
      sim_grid_pos_y: 1587687.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329604.25
      sim_grid_pos_y: 1587811.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329956.25
      sim_grid_pos_y: 1587629.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1330127.62
      sim_grid_pos_y: 1587395.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329531.12
      sim_grid_pos_y: 1587114.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329528.25
      sim_grid_pos_y: 1587089.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329589.38
      sim_grid_pos_y: 1586990.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1330138.38
      sim_grid_pos_y: 1586564.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1331023
      sim_grid_pos_y: 1586193.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331490.25
      sim_grid_pos_y: 1585693.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1331462
      sim_grid_pos_y: 1585620.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1330854.88
      sim_grid_pos_y: 1585577.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329737.25
      sim_grid_pos_y: 1585853.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1329549.5
      sim_grid_pos_y: 1585874.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329413.88
      sim_grid_pos_y: 1585857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1329279.62
      sim_grid_pos_y: 1585835
    }
    terrain_level_point {
      sim_grid_pos_x: 1328947.12
      sim_grid_pos_y: 1585679.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328343.75
      sim_grid_pos_y: 1585304.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1327774.75
      sim_grid_pos_y: 1584965
    }
    terrain_level_point {
      sim_grid_pos_x: 1327557.75
      sim_grid_pos_y: 1584883
    }
  }
}
terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1329384.5
      sim_grid_pos_y: 1587378.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329302.62
      sim_grid_pos_y: 1587492.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329159.12
      sim_grid_pos_y: 1587528.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329067.88
      sim_grid_pos_y: 1587534.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328952.62
      sim_grid_pos_y: 1587614.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.3288e+06
      sim_grid_pos_y: 1.58759e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1328738.75
      sim_grid_pos_y: 1587533.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328633.25
      sim_grid_pos_y: 1587488.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328566.75
      sim_grid_pos_y: 1587354.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328500.88
      sim_grid_pos_y: 1587324.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328433.12
      sim_grid_pos_y: 1587315.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328355.38
      sim_grid_pos_y: 1587348.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328181.12
      sim_grid_pos_y: 1587356.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328130.62
      sim_grid_pos_y: 1587317.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328090.12
      sim_grid_pos_y: 1587384.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1327922.5
      sim_grid_pos_y: 1587262.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1327916.12
      sim_grid_pos_y: 1587232
    }
    terrain_level_point {
      sim_grid_pos_x: 1327968.38
      sim_grid_pos_y: 1587174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328080.62
      sim_grid_pos_y: 1587229
    }
    terrain_level_point {
      sim_grid_pos_x: 1328131.5
      sim_grid_pos_y: 1587252.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328185.75
      sim_grid_pos_y: 1587253.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328221.25
      sim_grid_pos_y: 1587232.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328253
      sim_grid_pos_y: 1.58722e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1328288
      sim_grid_pos_y: 1587199
    }
    terrain_level_point {
      sim_grid_pos_x: 1328344.62
      sim_grid_pos_y: 1587085.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328408.38
      sim_grid_pos_y: 1587101.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328496.38
      sim_grid_pos_y: 1587141.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328645.5
      sim_grid_pos_y: 1587153.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1328411.75
      sim_grid_pos_y: 1587092
    }
    terrain_level_point {
      sim_grid_pos_x: 1328498.88
      sim_grid_pos_y: 1587131.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328647.38
      sim_grid_pos_y: 1587143
    }
    terrain_level_point {
      sim_grid_pos_x: 1329401.12
      sim_grid_pos_y: 1587372.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329308.75
      sim_grid_pos_y: 1587502
    }
    terrain_level_point {
      sim_grid_pos_x: 1329160.62
      sim_grid_pos_y: 1587538.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329071.38
      sim_grid_pos_y: 1587544.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328955.12
      sim_grid_pos_y: 1587625.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328795.25
      sim_grid_pos_y: 1587599.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328733
      sim_grid_pos_y: 1587542
    }
    terrain_level_point {
      sim_grid_pos_x: 1328625.75
      sim_grid_pos_y: 1587496.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328559.25
      sim_grid_pos_y: 1587362.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328498
      sim_grid_pos_y: 1587334.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328434.5
      sim_grid_pos_y: 1587325.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328357.75
      sim_grid_pos_y: 1587358.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328177.88
      sim_grid_pos_y: 1587366.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328133.5
      sim_grid_pos_y: 1587332.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328093.12
      sim_grid_pos_y: 1587399.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1327913.25
      sim_grid_pos_y: 1587268.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1327905.12
      sim_grid_pos_y: 1587229
    }
    terrain_level_point {
      sim_grid_pos_x: 1327965.88
      sim_grid_pos_y: 1587161.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328085.12
      sim_grid_pos_y: 1587219.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328133.75
      sim_grid_pos_y: 1587242
    }
    terrain_level_point {
      sim_grid_pos_x: 1328183
      sim_grid_pos_y: 1587242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328216.75
      sim_grid_pos_y: 1587223.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328248.5
      sim_grid_pos_y: 1587210.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328280.25
      sim_grid_pos_y: 1587191.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328339.12
      sim_grid_pos_y: 1587074
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1328415.12
      sim_grid_pos_y: 1587082.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328501.5
      sim_grid_pos_y: 1587121.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328649.38
      sim_grid_pos_y: 1587132.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1329417.75
      sim_grid_pos_y: 1587366.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1329314.88
      sim_grid_pos_y: 1587511
    }
    terrain_level_point {
      sim_grid_pos_x: 1329162.25
      sim_grid_pos_y: 1587549
    }
    terrain_level_point {
      sim_grid_pos_x: 1329075
      sim_grid_pos_y: 1587554.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328957.5
      sim_grid_pos_y: 1587636.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328790.5
      sim_grid_pos_y: 1587609.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328727.38
      sim_grid_pos_y: 1587550.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328618.25
      sim_grid_pos_y: 1587504.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328551.62
      sim_grid_pos_y: 1587370.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328495.12
      sim_grid_pos_y: 1587344.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328436
      sim_grid_pos_y: 1587336.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.32836e+06
      sim_grid_pos_y: 1587369
    }
    terrain_level_point {
      sim_grid_pos_x: 1328174.62
      sim_grid_pos_y: 1587377.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328136.38
      sim_grid_pos_y: 1587348
    }
    terrain_level_point {
      sim_grid_pos_x: 1328096.12
      sim_grid_pos_y: 1587414.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1327904
      sim_grid_pos_y: 1587274.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1327894
      sim_grid_pos_y: 1587226
    }
    terrain_level_point {
      sim_grid_pos_x: 1327963.5
      sim_grid_pos_y: 1587149.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328089.5
      sim_grid_pos_y: 1587210.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328136.12
      sim_grid_pos_y: 1587231.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328180.38
      sim_grid_pos_y: 1587232.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328212.38
      sim_grid_pos_y: 1587213.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328244
      sim_grid_pos_y: 1587201.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328272.38
      sim_grid_pos_y: 1587184.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328333.62
      sim_grid_pos_y: 1587062.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1328418.5
      sim_grid_pos_y: 1587072.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328504.12
      sim_grid_pos_y: 1587111.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328651.25
      sim_grid_pos_y: 1587122.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329434.38
      sim_grid_pos_y: 1587361.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329321
      sim_grid_pos_y: 1.58752e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1329163.88
      sim_grid_pos_y: 1587559.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329078.5
      sim_grid_pos_y: 1587564.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.32896e+06
      sim_grid_pos_y: 1587647.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328785.88
      sim_grid_pos_y: 1587618.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328721.75
      sim_grid_pos_y: 1587559.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1328610.75
      sim_grid_pos_y: 1587512.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328544.12
      sim_grid_pos_y: 1587377.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328492.25
      sim_grid_pos_y: 1587354.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328437.38
      sim_grid_pos_y: 1587346.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1328362.38
      sim_grid_pos_y: 1587379.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328171.38
      sim_grid_pos_y: 1587387.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1328139.12
      sim_grid_pos_y: 1587363.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328099.12
      sim_grid_pos_y: 1587429.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1327894.75
      sim_grid_pos_y: 1587280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1327882.88
      sim_grid_pos_y: 1587223
    }
    terrain_level_point {
      sim_grid_pos_x: 1327961
      sim_grid_pos_y: 1587136.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328093.75
      sim_grid_pos_y: 1587201.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328138.38
      sim_grid_pos_y: 1587221.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1328177.62
      sim_grid_pos_y: 1587222.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328207.88
      sim_grid_pos_y: 1587204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1328239.5
      sim_grid_pos_y: 1587192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328264.5
      sim_grid_pos_y: 1587177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328328.12
      sim_grid_pos_y: 1587050.12
    }
  }
}
