terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 207752.125
      sim_grid_pos_y: 3191745
    }
    terrain_level_point {
      sim_grid_pos_x: 205234.266
      sim_grid_pos_y: 3193474.75
    }
    terrain_level_point {
      sim_grid_pos_x: 205075.609
      sim_grid_pos_y: 3194393
    }
    terrain_level_point {
      sim_grid_pos_x: 206380.359
      sim_grid_pos_y: 3194806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 206943.531
      sim_grid_pos_y: 3195325
    }
    terrain_level_point {
      sim_grid_pos_x: 207041.781
      sim_grid_pos_y: 3196766.5
    }
    terrain_level_point {
      sim_grid_pos_x: 207694.797
      sim_grid_pos_y: 3197843.75
    }
    terrain_level_point {
      sim_grid_pos_x: 208042.469
      sim_grid_pos_y: 3197659
    }
    terrain_level_point {
      sim_grid_pos_x: 210206.172
      sim_grid_pos_y: 3196216
    }
    terrain_level_point {
      sim_grid_pos_x: 210287.266
      sim_grid_pos_y: 3195527.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 207760.344
      sim_grid_pos_y: 3191702.25
    }
    terrain_level_point {
      sim_grid_pos_x: 205206.156
      sim_grid_pos_y: 3193456.75
    }
    terrain_level_point {
      sim_grid_pos_x: 205040.734
      sim_grid_pos_y: 3194414.25
    }
    terrain_level_point {
      sim_grid_pos_x: 206364.547
      sim_grid_pos_y: 3194833.5
    }
    terrain_level_point {
      sim_grid_pos_x: 206913.688
      sim_grid_pos_y: 3195339.25
    }
    terrain_level_point {
      sim_grid_pos_x: 207011.594
      sim_grid_pos_y: 3196776
    }
    terrain_level_point {
      sim_grid_pos_x: 207683.562
      sim_grid_pos_y: 3197884.75
    }
    terrain_level_point {
      sim_grid_pos_x: 208058.266
      sim_grid_pos_y: 3197685.25
    }
    terrain_level_point {
      sim_grid_pos_x: 210235.047
      sim_grid_pos_y: 3196233.75
    }
    terrain_level_point {
      sim_grid_pos_x: 210319.156
      sim_grid_pos_y: 3195520.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 207768.578
      sim_grid_pos_y: 3191659.25
    }
    terrain_level_point {
      sim_grid_pos_x: 205178.062
      sim_grid_pos_y: 3193438.75
    }
    terrain_level_point {
      sim_grid_pos_x: 205005.844
      sim_grid_pos_y: 3194435.5
    }
    terrain_level_point {
      sim_grid_pos_x: 206348.734
      sim_grid_pos_y: 3194860.75
    }
    terrain_level_point {
      sim_grid_pos_x: 206883.844
      sim_grid_pos_y: 3195353.5
    }
    terrain_level_point {
      sim_grid_pos_x: 206981.422
      sim_grid_pos_y: 3196785.5
    }
    terrain_level_point {
      sim_grid_pos_x: 207672.344
      sim_grid_pos_y: 3197925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 208074.062
      sim_grid_pos_y: 3197711.75
    }
    terrain_level_point {
      sim_grid_pos_x: 210263.938
      sim_grid_pos_y: 3196251.5
    }
    terrain_level_point {
      sim_grid_pos_x: 210351.016
      sim_grid_pos_y: 3195512.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 207776.812
      sim_grid_pos_y: 3191616.25
    }
    terrain_level_point {
      sim_grid_pos_x: 205149.953
      sim_grid_pos_y: 3193420.75
    }
    terrain_level_point {
      sim_grid_pos_x: 204970.969
      sim_grid_pos_y: 3194456.75
    }
    terrain_level_point {
      sim_grid_pos_x: 206332.938
      sim_grid_pos_y: 3194888
    }
    terrain_level_point {
      sim_grid_pos_x: 206853.984
      sim_grid_pos_y: 3195367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 206951.234
      sim_grid_pos_y: 3196795.25
    }
    terrain_level_point {
      sim_grid_pos_x: 207661.109
      sim_grid_pos_y: 3197966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 208089.844
      sim_grid_pos_y: 3197738.25
    }
    terrain_level_point {
      sim_grid_pos_x: 210292.812
      sim_grid_pos_y: 3196269.25
    }
    terrain_level_point {
      sim_grid_pos_x: 210382.906
      sim_grid_pos_y: 3195504.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 207785.031
      sim_grid_pos_y: 3191573.25
    }
    terrain_level_point {
      sim_grid_pos_x: 205121.844
      sim_grid_pos_y: 3193402.75
    }
    terrain_level_point {
      sim_grid_pos_x: 204936.094
      sim_grid_pos_y: 3194478
    }
    terrain_level_point {
      sim_grid_pos_x: 206317.156
      sim_grid_pos_y: 3194915.25
    }
    terrain_level_point {
      sim_grid_pos_x: 206824.125
      sim_grid_pos_y: 3195382.25
    }
    terrain_level_point {
      sim_grid_pos_x: 206921.062
      sim_grid_pos_y: 3196804.75
    }
    terrain_level_point {
      sim_grid_pos_x: 207649.875
      sim_grid_pos_y: 3198007
    }
    terrain_level_point {
      sim_grid_pos_x: 208105.641
      sim_grid_pos_y: 3197764.75
    }
    terrain_level_point {
      sim_grid_pos_x: 210321.703
      sim_grid_pos_y: 3196287
    }
    terrain_level_point {
      sim_grid_pos_x: 210414.766
      sim_grid_pos_y: 3195497
    }
  }
}
