terrain_level_data {
  terrain_level: 1335
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3060387
      sim_grid_pos_y: 1564103.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3060518.75
      sim_grid_pos_y: 1564530.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3061129.25
      sim_grid_pos_y: 1564984.62
    }
    terrain_level_point {
      sim_grid_pos_x: 3061713.75
      sim_grid_pos_y: 1565213.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3062146.5
      sim_grid_pos_y: 1565404.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3062871.25
      sim_grid_pos_y: 1565359.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3063437.75
      sim_grid_pos_y: 1565630.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3063987.5
      sim_grid_pos_y: 1565694.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3064298.75
      sim_grid_pos_y: 1565643.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3064431
      sim_grid_pos_y: 1565342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3064028
      sim_grid_pos_y: 1565122.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3063266.25
      sim_grid_pos_y: 1564857.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3062547.75
      sim_grid_pos_y: 1564683.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3062045.25
      sim_grid_pos_y: 1564646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3061216
      sim_grid_pos_y: 1564375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 3060381.5
      sim_grid_pos_y: 1564079.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3060363.75
      sim_grid_pos_y: 1564097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3060501.25
      sim_grid_pos_y: 1564543.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3061119
      sim_grid_pos_y: 1565002.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3061706
      sim_grid_pos_y: 1565232
    }
    terrain_level_point {
      sim_grid_pos_x: 3062143
      sim_grid_pos_y: 1565424.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3062867.25
      sim_grid_pos_y: 1.56538e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 3063432
      sim_grid_pos_y: 1565650.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3063988
      sim_grid_pos_y: 1565714.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3064313
      sim_grid_pos_y: 1565661.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3064457.5
      sim_grid_pos_y: 1565333.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3064036.5
      sim_grid_pos_y: 1565104.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3063272
      sim_grid_pos_y: 1564838.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3062551
      sim_grid_pos_y: 1564663
    }
    terrain_level_point {
      sim_grid_pos_x: 3062049.25
      sim_grid_pos_y: 1564626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3061222.5
      sim_grid_pos_y: 1564355.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 3060376
      sim_grid_pos_y: 1564056.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3060340.5
      sim_grid_pos_y: 1564091.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3060483.5
      sim_grid_pos_y: 1564555.62
    }
    terrain_level_point {
      sim_grid_pos_x: 3061109
      sim_grid_pos_y: 1565020.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3061698
      sim_grid_pos_y: 1565251
    }
    terrain_level_point {
      sim_grid_pos_x: 3062139.25
      sim_grid_pos_y: 1565445.62
    }
    terrain_level_point {
      sim_grid_pos_x: 3062863.25
      sim_grid_pos_y: 1565400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3063426.25
      sim_grid_pos_y: 1565670.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3063988.5
      sim_grid_pos_y: 1565735.62
    }
    terrain_level_point {
      sim_grid_pos_x: 3064327.25
      sim_grid_pos_y: 1565680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3064483.75
      sim_grid_pos_y: 1565324.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3064044.75
      sim_grid_pos_y: 1565085.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3063277.75
      sim_grid_pos_y: 1564818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 3062554.25
      sim_grid_pos_y: 1564642.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3062053.25
      sim_grid_pos_y: 1564606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3061229
      sim_grid_pos_y: 1564336
    }
  }
}
