terrain_level_data {
  terrain_level: 50
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1835599.12
      sim_grid_pos_y: 1117800.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1836858.5
      sim_grid_pos_y: 1118049.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1837177.25
      sim_grid_pos_y: 1118383.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1837290.62
      sim_grid_pos_y: 1118593.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1836972.75
      sim_grid_pos_y: 1120551.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1836831.75
      sim_grid_pos_y: 1120952.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1836788.25
      sim_grid_pos_y: 1121302.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1836794.38
      sim_grid_pos_y: 1121946.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1836570.62
      sim_grid_pos_y: 1122565.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1835461.75
      sim_grid_pos_y: 1.123e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1835186.75
      sim_grid_pos_y: 1122976.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1834763.75
      sim_grid_pos_y: 1122951
    }
    terrain_level_point {
      sim_grid_pos_x: 1834183.12
      sim_grid_pos_y: 1123299.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1834566.38
      sim_grid_pos_y: 1122117.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1836874
      sim_grid_pos_y: 1118021.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1837202.38
      sim_grid_pos_y: 1118364.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1837322.75
      sim_grid_pos_y: 1118588
    }
    terrain_level_point {
      sim_grid_pos_x: 1837002.62
      sim_grid_pos_y: 1120558.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1836861.75
      sim_grid_pos_y: 1120959.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1836819
      sim_grid_pos_y: 1121304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1836825.25
      sim_grid_pos_y: 1121951.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1836594.75
      sim_grid_pos_y: 1122588.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1835466.38
      sim_grid_pos_y: 1123031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1835184.5
      sim_grid_pos_y: 1123007.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1834771.5
      sim_grid_pos_y: 1122982.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1834180.62
      sim_grid_pos_y: 1123336.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1834147.25
      sim_grid_pos_y: 1123309.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1834536.75
      sim_grid_pos_y: 1122109.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1835576.12
      sim_grid_pos_y: 1117764.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1836889.5
      sim_grid_pos_y: 1117993.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1837227.5
      sim_grid_pos_y: 1118346.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1837354.75
      sim_grid_pos_y: 1118582.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1837032.62
      sim_grid_pos_y: 1120566.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1836891.88
      sim_grid_pos_y: 1120966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1836849.75
      sim_grid_pos_y: 1121306
    }
    terrain_level_point {
      sim_grid_pos_x: 1836856
      sim_grid_pos_y: 1121956.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1836619
      sim_grid_pos_y: 1122612.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1835470.88
      sim_grid_pos_y: 1123062.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1835182.25
      sim_grid_pos_y: 1123038.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1834779.12
      sim_grid_pos_y: 1123013.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1834178.12
      sim_grid_pos_y: 1123373.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1834111.5
      sim_grid_pos_y: 1123320.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1834507.12
      sim_grid_pos_y: 1122100.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1835553
      sim_grid_pos_y: 1117728.38
    }
  }
}
