terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 810895.5
      sim_grid_pos_y: 2249772
    }
    terrain_level_point {
      sim_grid_pos_x: 810523.312
      sim_grid_pos_y: 2249793.5
    }
    terrain_level_point {
      sim_grid_pos_x: 810415.625
      sim_grid_pos_y: 2249542.25
    }
    terrain_level_point {
      sim_grid_pos_x: 809320.812
      sim_grid_pos_y: 2249535.75
    }
    terrain_level_point {
      sim_grid_pos_x: 809322.938
      sim_grid_pos_y: 2251627.75
    }
    terrain_level_point {
      sim_grid_pos_x: 811005.312
      sim_grid_pos_y: 2251616.25
    }
    terrain_level_point {
      sim_grid_pos_x: 810991.375
      sim_grid_pos_y: 2252589
    }
    terrain_level_point {
      sim_grid_pos_x: 815728.375
      sim_grid_pos_y: 2252492.75
    }
    terrain_level_point {
      sim_grid_pos_x: 815682.312
      sim_grid_pos_y: 2250464.75
    }
    terrain_level_point {
      sim_grid_pos_x: 810919.375
      sim_grid_pos_y: 2250553
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 809290.062
      sim_grid_pos_y: 2249504.75
    }
    terrain_level_point {
      sim_grid_pos_x: 809292.188
      sim_grid_pos_y: 2251658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 810974.125
      sim_grid_pos_y: 2251647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 810960.188
      sim_grid_pos_y: 2252620.5
    }
    terrain_level_point {
      sim_grid_pos_x: 815759.812
      sim_grid_pos_y: 2252523
    }
    terrain_level_point {
      sim_grid_pos_x: 815712.375
      sim_grid_pos_y: 2250433.5
    }
    terrain_level_point {
      sim_grid_pos_x: 810949.188
      sim_grid_pos_y: 2250521.5
    }
    terrain_level_point {
      sim_grid_pos_x: 810925.312
      sim_grid_pos_y: 2249739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 810543.062
      sim_grid_pos_y: 2249761.5
    }
    terrain_level_point {
      sim_grid_pos_x: 810435.938
      sim_grid_pos_y: 2249511.5
    }
  }
}
