terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1138338
      sim_grid_pos_y: 1369248.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1139192.25
      sim_grid_pos_y: 1369561.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1139963
      sim_grid_pos_y: 1367405.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1140388.38
      sim_grid_pos_y: 1367636.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1140913.62
      sim_grid_pos_y: 1366231.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1140805.88
      sim_grid_pos_y: 1362338.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1140706.12
      sim_grid_pos_y: 1362179.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140694.88
      sim_grid_pos_y: 1361277.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1141638.12
      sim_grid_pos_y: 1361695.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1142124.38
      sim_grid_pos_y: 1360242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1141739.75
      sim_grid_pos_y: 1358294.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1139839.5
      sim_grid_pos_y: 1358292.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1139702.75
      sim_grid_pos_y: 1355564.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1138968.75
      sim_grid_pos_y: 1355133
    }
    terrain_level_point {
      sim_grid_pos_x: 1136070.38
      sim_grid_pos_y: 1355052.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135507.25
      sim_grid_pos_y: 1355865.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135617.62
      sim_grid_pos_y: 1356303.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135603.38
      sim_grid_pos_y: 1358270.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135463.5
      sim_grid_pos_y: 1359919.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135714.5
      sim_grid_pos_y: 1360125.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135526.62
      sim_grid_pos_y: 1360416.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135181.75
      sim_grid_pos_y: 1360499.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134609.75
      sim_grid_pos_y: 1360674.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134551.75
      sim_grid_pos_y: 1361850.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135102.62
      sim_grid_pos_y: 1362250.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135316.12
      sim_grid_pos_y: 1363767.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1136065.12
      sim_grid_pos_y: 1.36382e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1136628.25
      sim_grid_pos_y: 1364692.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136572.88
      sim_grid_pos_y: 1365278
    }
    terrain_level_point {
      sim_grid_pos_x: 1136215.88
      sim_grid_pos_y: 1365288.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136178.75
      sim_grid_pos_y: 1365795.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136653.88
      sim_grid_pos_y: 1365805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136649.25
      sim_grid_pos_y: 1367182.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136537
      sim_grid_pos_y: 1367510.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136684.88
      sim_grid_pos_y: 1367925.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1138459.25
      sim_grid_pos_y: 1367857.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1138531.62
      sim_grid_pos_y: 1368152.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138372
      sim_grid_pos_y: 1368418.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1138425.38
      sim_grid_pos_y: 1368684.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1136054.5
      sim_grid_pos_y: 1355021.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135474
      sim_grid_pos_y: 1355859.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135586.88
      sim_grid_pos_y: 1356307.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135572.62
      sim_grid_pos_y: 1358268.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135431.5
      sim_grid_pos_y: 1359933.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135673.75
      sim_grid_pos_y: 1360131.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135507.38
      sim_grid_pos_y: 1360389.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135173.75
      sim_grid_pos_y: 1360469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134580.12
      sim_grid_pos_y: 1360651
    }
    terrain_level_point {
      sim_grid_pos_x: 1134520.25
      sim_grid_pos_y: 1361866
    }
    terrain_level_point {
      sim_grid_pos_x: 1135073.88
      sim_grid_pos_y: 1362268
    }
    terrain_level_point {
      sim_grid_pos_x: 1135289.12
      sim_grid_pos_y: 1363796.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136047.62
      sim_grid_pos_y: 1363849.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1136596.62
      sim_grid_pos_y: 1364700.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136544.88
      sim_grid_pos_y: 1365248.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136187.25
      sim_grid_pos_y: 1365258.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136145.75
      sim_grid_pos_y: 1365825.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136623
      sim_grid_pos_y: 1365836
    }
    terrain_level_point {
      sim_grid_pos_x: 1136618.5
      sim_grid_pos_y: 1367177.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1136504.38
      sim_grid_pos_y: 1367510.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136663.38
      sim_grid_pos_y: 1367956.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138435.38
      sim_grid_pos_y: 1367888.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138498.75
      sim_grid_pos_y: 1368147.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138339.38
      sim_grid_pos_y: 1368412.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1138394.25
      sim_grid_pos_y: 1368685
    }
    terrain_level_point {
      sim_grid_pos_x: 1138303.75
      sim_grid_pos_y: 1369268.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1139210.75
      sim_grid_pos_y: 1369600.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1139979.88
      sim_grid_pos_y: 1367449.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140404.75
      sim_grid_pos_y: 1367680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1140944.5
      sim_grid_pos_y: 1366236.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1140836.38
      sim_grid_pos_y: 1362329.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140736.75
      sim_grid_pos_y: 1362170.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140726.25
      sim_grid_pos_y: 1361324.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1141656.62
      sim_grid_pos_y: 1361737.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1142156.12
      sim_grid_pos_y: 1360244.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1141765
      sim_grid_pos_y: 1358263.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1139868.75
      sim_grid_pos_y: 1358262.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1139732.62
      sim_grid_pos_y: 1355546.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1138977.5
      sim_grid_pos_y: 1355102.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1136038.75
      sim_grid_pos_y: 1354989.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135440.75
      sim_grid_pos_y: 1355853.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135556.12
      sim_grid_pos_y: 1356310.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135542
      sim_grid_pos_y: 1358267.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135399.5
      sim_grid_pos_y: 1359946.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135633
      sim_grid_pos_y: 1360137.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135488.25
      sim_grid_pos_y: 1360362.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135165.62
      sim_grid_pos_y: 1360439.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134550.5
      sim_grid_pos_y: 1360627.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134488.62
      sim_grid_pos_y: 1361881.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135045.25
      sim_grid_pos_y: 1362285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135262.12
      sim_grid_pos_y: 1363825.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136030.12
      sim_grid_pos_y: 1363879.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136565
      sim_grid_pos_y: 1364708.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136516.75
      sim_grid_pos_y: 1365218.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136158.62
      sim_grid_pos_y: 1365229
    }
    terrain_level_point {
      sim_grid_pos_x: 1136112.75
      sim_grid_pos_y: 1365855.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136592.12
      sim_grid_pos_y: 1365866.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136587.75
      sim_grid_pos_y: 1367172.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136471.88
      sim_grid_pos_y: 1367511.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136642
      sim_grid_pos_y: 1367988.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1138411.5
      sim_grid_pos_y: 1367920.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1138465.88
      sim_grid_pos_y: 1368142.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138306.88
      sim_grid_pos_y: 1368407.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1138363
      sim_grid_pos_y: 1368685.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1138269.5
      sim_grid_pos_y: 1369288.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1139229.25
      sim_grid_pos_y: 1369640.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1139996.75
      sim_grid_pos_y: 1367493.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1140421.25
      sim_grid_pos_y: 1367724.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1140975.5
      sim_grid_pos_y: 1366241.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1140866.88
      sim_grid_pos_y: 1362320.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1140767.38
      sim_grid_pos_y: 1362161.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140757.5
      sim_grid_pos_y: 1361372.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1141675
      sim_grid_pos_y: 1361778.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1142187.88
      sim_grid_pos_y: 1360246.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1141790.38
      sim_grid_pos_y: 1358232.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1139898
      sim_grid_pos_y: 1358231.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1139762.5
      sim_grid_pos_y: 1355528
    }
    terrain_level_point {
      sim_grid_pos_x: 1138986.25
      sim_grid_pos_y: 1355072
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1136022.88
      sim_grid_pos_y: 1354958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135407.62
      sim_grid_pos_y: 1355847.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135525.38
      sim_grid_pos_y: 1356314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135511.25
      sim_grid_pos_y: 1358265.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135367.5
      sim_grid_pos_y: 1359960.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135592.25
      sim_grid_pos_y: 1360144.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135469.12
      sim_grid_pos_y: 1360335.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135157.5
      sim_grid_pos_y: 1360410.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134520.75
      sim_grid_pos_y: 1360604.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134457.12
      sim_grid_pos_y: 1361896.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135016.62
      sim_grid_pos_y: 1362302.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135235.12
      sim_grid_pos_y: 1363854.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136012.62
      sim_grid_pos_y: 1363908.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136533.38
      sim_grid_pos_y: 1364715.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1136488.75
      sim_grid_pos_y: 1365188.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.13613e+06
      sim_grid_pos_y: 1365199.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136079.62
      sim_grid_pos_y: 1365885.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1136561.25
      sim_grid_pos_y: 1365896.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136557
      sim_grid_pos_y: 1367167.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136439.25
      sim_grid_pos_y: 1367511.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136620.62
      sim_grid_pos_y: 1368020.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1138387.5
      sim_grid_pos_y: 1367952.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1138433
      sim_grid_pos_y: 1368137.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1138274.38
      sim_grid_pos_y: 1368401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1138331.75
      sim_grid_pos_y: 1368686.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1138235.25
      sim_grid_pos_y: 1369308.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1139247.75
      sim_grid_pos_y: 1.36968e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1140013.62
      sim_grid_pos_y: 1367537.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1140437.62
      sim_grid_pos_y: 1367768
    }
    terrain_level_point {
      sim_grid_pos_x: 1141006.38
      sim_grid_pos_y: 1366246.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1140897.38
      sim_grid_pos_y: 1362311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1140798
      sim_grid_pos_y: 1362152.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1140788.88
      sim_grid_pos_y: 1361419.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1141693.5
      sim_grid_pos_y: 1361820.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1142219.62
      sim_grid_pos_y: 1360248.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1141815.62
      sim_grid_pos_y: 1358202
    }
    terrain_level_point {
      sim_grid_pos_x: 1139927.25
      sim_grid_pos_y: 1358200.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1139792.38
      sim_grid_pos_y: 1.35551e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1138995
      sim_grid_pos_y: 1355041.5
    }
  }
}
terrain_level_data {
  terrain_level: 40
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1135392.5
      sim_grid_pos_y: 1358243.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135368.62
      sim_grid_pos_y: 1358071.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132281.12
      sim_grid_pos_y: 1358037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1132715.5
      sim_grid_pos_y: 1359254.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133987.75
      sim_grid_pos_y: 1359248
    }
    terrain_level_point {
      sim_grid_pos_x: 1134253.88
      sim_grid_pos_y: 1359495.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134228
      sim_grid_pos_y: 1359678.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135371.12
      sim_grid_pos_y: 1359637.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1132237.25
      sim_grid_pos_y: 1358006
    }
    terrain_level_point {
      sim_grid_pos_x: 1132693.88
      sim_grid_pos_y: 1359285.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133975.75
      sim_grid_pos_y: 1359278.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134221.25
      sim_grid_pos_y: 1359507.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134192.5
      sim_grid_pos_y: 1359710.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135401.38
      sim_grid_pos_y: 1359667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135423.25
      sim_grid_pos_y: 1358241.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135395.5
      sim_grid_pos_y: 1358040.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1132193.5
      sim_grid_pos_y: 1357974.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1132672.12
      sim_grid_pos_y: 1359316.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133963.75
      sim_grid_pos_y: 1359309.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134188.5
      sim_grid_pos_y: 1359518.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134156.88
      sim_grid_pos_y: 1359742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135431.75
      sim_grid_pos_y: 1359697.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135454.12
      sim_grid_pos_y: 1358239.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135422.25
      sim_grid_pos_y: 1358010.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1132149.75
      sim_grid_pos_y: 1357943.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1132650.5
      sim_grid_pos_y: 1359347.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133951.62
      sim_grid_pos_y: 1359340.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134155.75
      sim_grid_pos_y: 1359530.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134121.25
      sim_grid_pos_y: 1359774.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135462
      sim_grid_pos_y: 1359726.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135484.88
      sim_grid_pos_y: 1358237.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135449.12
      sim_grid_pos_y: 1357979.75
    }
  }
}
terrain_level_data {
  terrain_level: 90
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1133939.38
      sim_grid_pos_y: 1359422
    }
    terrain_level_point {
      sim_grid_pos_x: 1132861
      sim_grid_pos_y: 1359413.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132742
      sim_grid_pos_y: 1360011
    }
    terrain_level_point {
      sim_grid_pos_x: 1133055.62
      sim_grid_pos_y: 1361058.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133608.38
      sim_grid_pos_y: 1361077.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133873.88
      sim_grid_pos_y: 1360995.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133984.25
      sim_grid_pos_y: 1360793
    }
    terrain_level_point {
      sim_grid_pos_x: 1134073.75
      sim_grid_pos_y: 1360510.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134067.62
      sim_grid_pos_y: 1360024.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134039
      sim_grid_pos_y: 1359507.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1132835.75
      sim_grid_pos_y: 1359382.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1132710.38
      sim_grid_pos_y: 1360012.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133032.5
      sim_grid_pos_y: 1361088.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133612.5
      sim_grid_pos_y: 1361108.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133894.88
      sim_grid_pos_y: 1361021.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134012.75
      sim_grid_pos_y: 1360805
    }
    terrain_level_point {
      sim_grid_pos_x: 1134104.62
      sim_grid_pos_y: 1360515.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134098.38
      sim_grid_pos_y: 1360023.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134069
      sim_grid_pos_y: 1359492.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133950.88
      sim_grid_pos_y: 1359391.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1132810.5
      sim_grid_pos_y: 1359351.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1132678.75
      sim_grid_pos_y: 1360014
    }
    terrain_level_point {
      sim_grid_pos_x: 1133009.38
      sim_grid_pos_y: 1361118.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133616.62
      sim_grid_pos_y: 1361139.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133915.88
      sim_grid_pos_y: 1361047.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134041.12
      sim_grid_pos_y: 1360817.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134135.5
      sim_grid_pos_y: 1360519.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134129.12
      sim_grid_pos_y: 1360022.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134099
      sim_grid_pos_y: 1359477.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133962.25
      sim_grid_pos_y: 1359360.62
    }
  }
}
