terrain_level_data {
  terrain_level: 45
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2680082.25
      sim_grid_pos_y: 415172.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2682200.75
      sim_grid_pos_y: 416406.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2678793.25
      sim_grid_pos_y: 421570.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2676653.5
      sim_grid_pos_y: 423330.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2675783.5
      sim_grid_pos_y: 422476.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2674315
      sim_grid_pos_y: 421656.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2676644.25
      sim_grid_pos_y: 419375.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2678966.75
      sim_grid_pos_y: 417034.656
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2682229.75
      sim_grid_pos_y: 416399.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2678808.75
      sim_grid_pos_y: 421584.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2676652.25
      sim_grid_pos_y: 423357.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2675771
      sim_grid_pos_y: 422492.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2674281.25
      sim_grid_pos_y: 421660.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2676629.75
      sim_grid_pos_y: 419360.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2678950.5
      sim_grid_pos_y: 417021.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2680075
      sim_grid_pos_y: 415145.031
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2682258.75
      sim_grid_pos_y: 416392.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2678824.25
      sim_grid_pos_y: 421598.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2676651
      sim_grid_pos_y: 423385.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2675758.5
      sim_grid_pos_y: 422509.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2674247.25
      sim_grid_pos_y: 421665.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2676615.5
      sim_grid_pos_y: 419346.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2678934.25
      sim_grid_pos_y: 417009.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2680067.75
      sim_grid_pos_y: 415117.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2682287.75
      sim_grid_pos_y: 416385.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2678839.5
      sim_grid_pos_y: 421612.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2.67665e+06
      sim_grid_pos_y: 423413.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2675746.25
      sim_grid_pos_y: 422525.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2674213.25
      sim_grid_pos_y: 421669.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2676600.5
      sim_grid_pos_y: 419332.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2678917.75
      sim_grid_pos_y: 416996.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2680060.75
      sim_grid_pos_y: 415089.219
    }
  }
}
