terrain_level_data {
  terrain_level: 320
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1227347.88
      sim_grid_pos_y: 107218.766
    }
    terrain_level_point {
      sim_grid_pos_x: 1228058.25
      sim_grid_pos_y: 107934.961
    }
    terrain_level_point {
      sim_grid_pos_x: 1228157.12
      sim_grid_pos_y: 108037.172
    }
    terrain_level_point {
      sim_grid_pos_x: 1228369
      sim_grid_pos_y: 108189.031
    }
    terrain_level_point {
      sim_grid_pos_x: 1228642.5
      sim_grid_pos_y: 108783.414
    }
    terrain_level_point {
      sim_grid_pos_x: 1229024.88
      sim_grid_pos_y: 109783.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1229710.12
      sim_grid_pos_y: 110926.578
    }
    terrain_level_point {
      sim_grid_pos_x: 1229868.75
      sim_grid_pos_y: 110670.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1229688.38
      sim_grid_pos_y: 110192.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1229792
      sim_grid_pos_y: 109714.133
    }
    terrain_level_point {
      sim_grid_pos_x: 1229473.88
      sim_grid_pos_y: 109189.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1229201.88
      sim_grid_pos_y: 109236.977
    }
    terrain_level_point {
      sim_grid_pos_x: 1229053.75
      sim_grid_pos_y: 109148.469
    }
    terrain_level_point {
      sim_grid_pos_x: 1228715
      sim_grid_pos_y: 107818.969
    }
    terrain_level_point {
      sim_grid_pos_x: 1228390.25
      sim_grid_pos_y: 106618.398
    }
    terrain_level_point {
      sim_grid_pos_x: 1228578.62
      sim_grid_pos_y: 106367.258
    }
    terrain_level_point {
      sim_grid_pos_x: 1228773.5
      sim_grid_pos_y: 106467.477
    }
    terrain_level_point {
      sim_grid_pos_x: 1229029
      sim_grid_pos_y: 106680
    }
    terrain_level_point {
      sim_grid_pos_x: 1229115.12
      sim_grid_pos_y: 106550.055
    }
    terrain_level_point {
      sim_grid_pos_x: 1229007
      sim_grid_pos_y: 106275.781
    }
    terrain_level_point {
      sim_grid_pos_x: 1228687.38
      sim_grid_pos_y: 105667.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1228475.62
      sim_grid_pos_y: 105662.133
    }
    terrain_level_point {
      sim_grid_pos_x: 1228371.75
      sim_grid_pos_y: 104989.594
    }
    terrain_level_point {
      sim_grid_pos_x: 1228350.12
      sim_grid_pos_y: 104691.547
    }
    terrain_level_point {
      sim_grid_pos_x: 1227842.38
      sim_grid_pos_y: 104708.289
    }
    terrain_level_point {
      sim_grid_pos_x: 1227866.62
      sim_grid_pos_y: 105359.398
    }
    terrain_level_point {
      sim_grid_pos_x: 1227024.75
      sim_grid_pos_y: 105747.641
    }
    terrain_level_point {
      sim_grid_pos_x: 1227066
      sim_grid_pos_y: 106188.094
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1228378.75
      sim_grid_pos_y: 104659.828
    }
    terrain_level_point {
      sim_grid_pos_x: 1227810.5
      sim_grid_pos_y: 104678.57
    }
    terrain_level_point {
      sim_grid_pos_x: 1227835.12
      sim_grid_pos_y: 105340.055
    }
    terrain_level_point {
      sim_grid_pos_x: 1226992.12
      sim_grid_pos_y: 105728.828
    }
    terrain_level_point {
      sim_grid_pos_x: 1227035.62
      sim_grid_pos_y: 106193.617
    }
    terrain_level_point {
      sim_grid_pos_x: 1227320.38
      sim_grid_pos_y: 107234.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1228036.38
      sim_grid_pos_y: 107956.617
    }
    terrain_level_point {
      sim_grid_pos_x: 1228137
      sim_grid_pos_y: 108060.547
    }
    terrain_level_point {
      sim_grid_pos_x: 1228344.5
      sim_grid_pos_y: 108209.281
    }
    terrain_level_point {
      sim_grid_pos_x: 1228614.12
      sim_grid_pos_y: 108795.297
    }
    terrain_level_point {
      sim_grid_pos_x: 1228997.12
      sim_grid_pos_y: 109796.656
    }
    terrain_level_point {
      sim_grid_pos_x: 1229709.62
      sim_grid_pos_y: 110985.68
    }
    terrain_level_point {
      sim_grid_pos_x: 1229902.88
      sim_grid_pos_y: 110674.008
    }
    terrain_level_point {
      sim_grid_pos_x: 1229720.38
      sim_grid_pos_y: 110190.367
    }
    terrain_level_point {
      sim_grid_pos_x: 1229824.62
      sim_grid_pos_y: 109708.648
    }
    terrain_level_point {
      sim_grid_pos_x: 1229489.25
      sim_grid_pos_y: 109156.055
    }
    terrain_level_point {
      sim_grid_pos_x: 1229207.88
      sim_grid_pos_y: 109204.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1229080.38
      sim_grid_pos_y: 109128.578
    }
    terrain_level_point {
      sim_grid_pos_x: 1228744.75
      sim_grid_pos_y: 107811.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1228423.75
      sim_grid_pos_y: 106624.859
    }
    terrain_level_point {
      sim_grid_pos_x: 1228587.62
      sim_grid_pos_y: 106406.484
    }
    terrain_level_point {
      sim_grid_pos_x: 1228756.38
      sim_grid_pos_y: 106493.266
    }
    terrain_level_point {
      sim_grid_pos_x: 1229035.75
      sim_grid_pos_y: 106725.578
    }
    terrain_level_point {
      sim_grid_pos_x: 1229149.62
      sim_grid_pos_y: 106553.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1229035.12
      sim_grid_pos_y: 106262.945
    }
    terrain_level_point {
      sim_grid_pos_x: 1228706.25
      sim_grid_pos_y: 105637.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1228502.12
      sim_grid_pos_y: 105632.102
    }
    terrain_level_point {
      sim_grid_pos_x: 1228402.25
      sim_grid_pos_y: 104986.109
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1228407.25
      sim_grid_pos_y: 104628.117
    }
    terrain_level_point {
      sim_grid_pos_x: 1227778.62
      sim_grid_pos_y: 104648.836
    }
    terrain_level_point {
      sim_grid_pos_x: 1227803.62
      sim_grid_pos_y: 105320.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1226959.5
      sim_grid_pos_y: 105710.016
    }
    terrain_level_point {
      sim_grid_pos_x: 1227005.25
      sim_grid_pos_y: 106199.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1227292.88
      sim_grid_pos_y: 107250.602
    }
    terrain_level_point {
      sim_grid_pos_x: 1228014.25
      sim_grid_pos_y: 107977.977
    }
    terrain_level_point {
      sim_grid_pos_x: 1228116.88
      sim_grid_pos_y: 108083.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1.22832e+06
      sim_grid_pos_y: 108229.531
    }
    terrain_level_point {
      sim_grid_pos_x: 1228585.75
      sim_grid_pos_y: 108807.266
    }
    terrain_level_point {
      sim_grid_pos_x: 1228969.38
      sim_grid_pos_y: 109810.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1229709.12
      sim_grid_pos_y: 111044.766
    }
    terrain_level_point {
      sim_grid_pos_x: 1229937
      sim_grid_pos_y: 110677.336
    }
    terrain_level_point {
      sim_grid_pos_x: 1229752.38
      sim_grid_pos_y: 110188
    }
    terrain_level_point {
      sim_grid_pos_x: 1229857.25
      sim_grid_pos_y: 109703.164
    }
    terrain_level_point {
      sim_grid_pos_x: 1229504.62
      sim_grid_pos_y: 109122.18
    }
    terrain_level_point {
      sim_grid_pos_x: 1229213.75
      sim_grid_pos_y: 109172.469
    }
    terrain_level_point {
      sim_grid_pos_x: 1229107
      sim_grid_pos_y: 109108.68
    }
    terrain_level_point {
      sim_grid_pos_x: 1228774.5
      sim_grid_pos_y: 107803.336
    }
    terrain_level_point {
      sim_grid_pos_x: 1228457.38
      sim_grid_pos_y: 106631.32
    }
    terrain_level_point {
      sim_grid_pos_x: 1228596.62
      sim_grid_pos_y: 106445.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1228739.38
      sim_grid_pos_y: 106519.109
    }
    terrain_level_point {
      sim_grid_pos_x: 1229042.38
      sim_grid_pos_y: 106771.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1229184.12
      sim_grid_pos_y: 106557.328
    }
    terrain_level_point {
      sim_grid_pos_x: 1229063.12
      sim_grid_pos_y: 106250.117
    }
    terrain_level_point {
      sim_grid_pos_x: 1228725.12
      sim_grid_pos_y: 105607.43
    }
    terrain_level_point {
      sim_grid_pos_x: 1228528.5
      sim_grid_pos_y: 105602.055
    }
    terrain_level_point {
      sim_grid_pos_x: 1228432.88
      sim_grid_pos_y: 104982.781
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1228435.88
      sim_grid_pos_y: 104596.398
    }
    terrain_level_point {
      sim_grid_pos_x: 1227746.75
      sim_grid_pos_y: 104619.117
    }
    terrain_level_point {
      sim_grid_pos_x: 1227772.12
      sim_grid_pos_y: 105301.367
    }
    terrain_level_point {
      sim_grid_pos_x: 1226926.75
      sim_grid_pos_y: 105691.195
    }
    terrain_level_point {
      sim_grid_pos_x: 1226974.88
      sim_grid_pos_y: 106204.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1227265.38
      sim_grid_pos_y: 107266.516
    }
    terrain_level_point {
      sim_grid_pos_x: 1227992.5
      sim_grid_pos_y: 107999.695
    }
    terrain_level_point {
      sim_grid_pos_x: 1228096.62
      sim_grid_pos_y: 108107.32
    }
    terrain_level_point {
      sim_grid_pos_x: 1228295.38
      sim_grid_pos_y: 108249.789
    }
    terrain_level_point {
      sim_grid_pos_x: 1228557.38
      sim_grid_pos_y: 108819.336
    }
    terrain_level_point {
      sim_grid_pos_x: 1228941.62
      sim_grid_pos_y: 109823.664
    }
    terrain_level_point {
      sim_grid_pos_x: 1229708.75
      sim_grid_pos_y: 111103.867
    }
    terrain_level_point {
      sim_grid_pos_x: 1229971.12
      sim_grid_pos_y: 110680.656
    }
    terrain_level_point {
      sim_grid_pos_x: 1229784.38
      sim_grid_pos_y: 110185.641
    }
    terrain_level_point {
      sim_grid_pos_x: 1229889.88
      sim_grid_pos_y: 109697.695
    }
    terrain_level_point {
      sim_grid_pos_x: 1229520.12
      sim_grid_pos_y: 109088.297
    }
    terrain_level_point {
      sim_grid_pos_x: 1229219.75
      sim_grid_pos_y: 109140.227
    }
    terrain_level_point {
      sim_grid_pos_x: 1229133.75
      sim_grid_pos_y: 109088.789
    }
    terrain_level_point {
      sim_grid_pos_x: 1228804.25
      sim_grid_pos_y: 107795.531
    }
    terrain_level_point {
      sim_grid_pos_x: 1228491
      sim_grid_pos_y: 106637.766
    }
    terrain_level_point {
      sim_grid_pos_x: 1228605.62
      sim_grid_pos_y: 106484.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1228722.25
      sim_grid_pos_y: 106544.898
    }
    terrain_level_point {
      sim_grid_pos_x: 1229049.12
      sim_grid_pos_y: 106816.734
    }
    terrain_level_point {
      sim_grid_pos_x: 1229218.5
      sim_grid_pos_y: 106560.961
    }
    terrain_level_point {
      sim_grid_pos_x: 1229091.12
      sim_grid_pos_y: 106237.281
    }
    terrain_level_point {
      sim_grid_pos_x: 1228743.88
      sim_grid_pos_y: 105577.18
    }
    terrain_level_point {
      sim_grid_pos_x: 1228555
      sim_grid_pos_y: 105572.008
    }
    terrain_level_point {
      sim_grid_pos_x: 1228463.5
      sim_grid_pos_y: 104979.18
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1228464.38
      sim_grid_pos_y: 104564.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1227714.88
      sim_grid_pos_y: 104589.398
    }
    terrain_level_point {
      sim_grid_pos_x: 1227740.62
      sim_grid_pos_y: 105282.031
    }
    terrain_level_point {
      sim_grid_pos_x: 1226894.12
      sim_grid_pos_y: 105672.391
    }
    terrain_level_point {
      sim_grid_pos_x: 1226944.5
      sim_grid_pos_y: 106210.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1227237.75
      sim_grid_pos_y: 107282.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1227970.88
      sim_grid_pos_y: 108021.602
    }
    terrain_level_point {
      sim_grid_pos_x: 1228076.5
      sim_grid_pos_y: 108130.711
    }
    terrain_level_point {
      sim_grid_pos_x: 1228270.88
      sim_grid_pos_y: 108270.047
    }
    terrain_level_point {
      sim_grid_pos_x: 1228529
      sim_grid_pos_y: 108831.18
    }
    terrain_level_point {
      sim_grid_pos_x: 1228913.75
      sim_grid_pos_y: 109837.164
    }
    terrain_level_point {
      sim_grid_pos_x: 1229708.25
      sim_grid_pos_y: 111162.961
    }
    terrain_level_point {
      sim_grid_pos_x: 1230005.25
      sim_grid_pos_y: 110683.984
    }
    terrain_level_point {
      sim_grid_pos_x: 1229816.38
      sim_grid_pos_y: 110183.289
    }
    terrain_level_point {
      sim_grid_pos_x: 1229922.62
      sim_grid_pos_y: 109692.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1229535.5
      sim_grid_pos_y: 109054.414
    }
    terrain_level_point {
      sim_grid_pos_x: 1229225.75
      sim_grid_pos_y: 109107.969
    }
    terrain_level_point {
      sim_grid_pos_x: 1229160.38
      sim_grid_pos_y: 109068.891
    }
    terrain_level_point {
      sim_grid_pos_x: 1228834
      sim_grid_pos_y: 107787.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1228524.62
      sim_grid_pos_y: 106644.219
    }
    terrain_level_point {
      sim_grid_pos_x: 1228614.75
      sim_grid_pos_y: 106524.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1228705.25
      sim_grid_pos_y: 106570.711
    }
    terrain_level_point {
      sim_grid_pos_x: 1229055.75
      sim_grid_pos_y: 106862.32
    }
    terrain_level_point {
      sim_grid_pos_x: 1229253
      sim_grid_pos_y: 106564.602
    }
    terrain_level_point {
      sim_grid_pos_x: 1229119.12
      sim_grid_pos_y: 106224.445
    }
    terrain_level_point {
      sim_grid_pos_x: 1228762.75
      sim_grid_pos_y: 105546.93
    }
    terrain_level_point {
      sim_grid_pos_x: 1228581.5
      sim_grid_pos_y: 105541.969
    }
    terrain_level_point {
      sim_grid_pos_x: 1228494
      sim_grid_pos_y: 104975.719
    }
  }
}
