terrain_level_data {
  terrain_level: 430
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1389797.5
      sim_grid_pos_y: 1798230.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1389639.5
      sim_grid_pos_y: 1797819.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1389122.88
      sim_grid_pos_y: 1795362
    }
    terrain_level_point {
      sim_grid_pos_x: 1389027.88
      sim_grid_pos_y: 1795134.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1389091
      sim_grid_pos_y: 1794905.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.38923e+06
      sim_grid_pos_y: 1795011.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1389497
      sim_grid_pos_y: 1795090.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1389792.38
      sim_grid_pos_y: 1795209.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1390490.75
      sim_grid_pos_y: 1796020.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1391023.25
      sim_grid_pos_y: 1796476.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1391298.25
      sim_grid_pos_y: 1796524.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391486
      sim_grid_pos_y: 1796369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391665.62
      sim_grid_pos_y: 1796376.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1391898.75
      sim_grid_pos_y: 1796462.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392050.25
      sim_grid_pos_y: 1796634.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392081.5
      sim_grid_pos_y: 1796913.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1391935
      sim_grid_pos_y: 1797088
    }
    terrain_level_point {
      sim_grid_pos_x: 1392020.38
      sim_grid_pos_y: 1797155.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392837.5
      sim_grid_pos_y: 1797205.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392935.88
      sim_grid_pos_y: 1797661.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1392192.12
      sim_grid_pos_y: 1798023
    }
    terrain_level_point {
      sim_grid_pos_x: 1392317.62
      sim_grid_pos_y: 1798577.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392326.5
      sim_grid_pos_y: 1798842.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392279.38
      sim_grid_pos_y: 1799093.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392492.88
      sim_grid_pos_y: 1799465
    }
    terrain_level_point {
      sim_grid_pos_x: 1392488.88
      sim_grid_pos_y: 1799693.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1392230.75
      sim_grid_pos_y: 1799840.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392076.75
      sim_grid_pos_y: 1799972.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391983.25
      sim_grid_pos_y: 1800239.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391388.88
      sim_grid_pos_y: 1799903.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1390479.12
      sim_grid_pos_y: 1799264.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1389941.88
      sim_grid_pos_y: 1798773.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1389277.12
      sim_grid_pos_y: 1794918.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1389530.88
      sim_grid_pos_y: 1794993.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1389853.75
      sim_grid_pos_y: 1795123.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1390563.38
      sim_grid_pos_y: 1795947.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1391068.62
      sim_grid_pos_y: 1796380.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1391269.38
      sim_grid_pos_y: 1796415.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1391450.88
      sim_grid_pos_y: 1796265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391685.75
      sim_grid_pos_y: 1796275.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1391958.5
      sim_grid_pos_y: 1796374.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392148.5
      sim_grid_pos_y: 1796591
    }
    terrain_level_point {
      sim_grid_pos_x: 1392188.38
      sim_grid_pos_y: 1796945.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1392094.62
      sim_grid_pos_y: 1797057.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1392921.38
      sim_grid_pos_y: 1797108
    }
    terrain_level_point {
      sim_grid_pos_x: 1393053
      sim_grid_pos_y: 1797718.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.39231e+06
      sim_grid_pos_y: 1798079.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392419.75
      sim_grid_pos_y: 1798564.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1392429.25
      sim_grid_pos_y: 1798850.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1392387.12
      sim_grid_pos_y: 1799075
    }
    terrain_level_point {
      sim_grid_pos_x: 1392595.88
      sim_grid_pos_y: 1799438.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392590.38
      sim_grid_pos_y: 1799753.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1392290.12
      sim_grid_pos_y: 1799924.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1392164.38
      sim_grid_pos_y: 1800032.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392039.38
      sim_grid_pos_y: 1800389.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1391334
      sim_grid_pos_y: 1799990.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1390414.75
      sim_grid_pos_y: 1799344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1389850.5
      sim_grid_pos_y: 1798828.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1389699.88
      sim_grid_pos_y: 1798261.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1389540.88
      sim_grid_pos_y: 1797848.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1389024.62
      sim_grid_pos_y: 1795392.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1388919.62
      sim_grid_pos_y: 1795141.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1389032.5
      sim_grid_pos_y: 1794732.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1389324.25
      sim_grid_pos_y: 1794825.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1389564.75
      sim_grid_pos_y: 1794896.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1389915.12
      sim_grid_pos_y: 1795038.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1390636
      sim_grid_pos_y: 1795874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1391114
      sim_grid_pos_y: 1796284.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1391240.5
      sim_grid_pos_y: 1796306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1391415.75
      sim_grid_pos_y: 1796161.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391705.88
      sim_grid_pos_y: 1796173.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392018.25
      sim_grid_pos_y: 1796287.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392246.75
      sim_grid_pos_y: 1796547.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392293.88
      sim_grid_pos_y: 1796966.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1393005.25
      sim_grid_pos_y: 1797010.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1393170.12
      sim_grid_pos_y: 1797775.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392428
      sim_grid_pos_y: 1798136.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1392521.88
      sim_grid_pos_y: 1798551.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392532.12
      sim_grid_pos_y: 1798858.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392494.88
      sim_grid_pos_y: 1799056.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1392698.88
      sim_grid_pos_y: 1799412
    }
    terrain_level_point {
      sim_grid_pos_x: 1392691.88
      sim_grid_pos_y: 1799813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392349.5
      sim_grid_pos_y: 1800008.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392252
      sim_grid_pos_y: 1800092.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392095.62
      sim_grid_pos_y: 1800538.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391279.25
      sim_grid_pos_y: 1800077.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1390350.38
      sim_grid_pos_y: 1799424.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1389759.12
      sim_grid_pos_y: 1798883.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1389602.25
      sim_grid_pos_y: 1798293.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1389442.12
      sim_grid_pos_y: 1797877.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1388926.25
      sim_grid_pos_y: 1795423.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1388811.38
      sim_grid_pos_y: 1795148.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1388973.88
      sim_grid_pos_y: 1794559.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1389371.38
      sim_grid_pos_y: 1794732.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1389598.62
      sim_grid_pos_y: 1794799.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1389976.62
      sim_grid_pos_y: 1794952.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1390708.62
      sim_grid_pos_y: 1795801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391159.38
      sim_grid_pos_y: 1796188.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1391211.62
      sim_grid_pos_y: 1796197.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1391380.62
      sim_grid_pos_y: 1796057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391726
      sim_grid_pos_y: 1796071.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392078
      sim_grid_pos_y: 1796200.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392345.12
      sim_grid_pos_y: 1796504.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1392386.12
      sim_grid_pos_y: 1796869.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1393089.12
      sim_grid_pos_y: 1796912.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1393287.38
      sim_grid_pos_y: 1797832.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392545.88
      sim_grid_pos_y: 1798193
    }
    terrain_level_point {
      sim_grid_pos_x: 1392624
      sim_grid_pos_y: 1798538.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392635
      sim_grid_pos_y: 1798866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392602.62
      sim_grid_pos_y: 1799038.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392801.88
      sim_grid_pos_y: 1799385.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392793.38
      sim_grid_pos_y: 1799873.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1392408.88
      sim_grid_pos_y: 1800093
    }
    terrain_level_point {
      sim_grid_pos_x: 1392339.75
      sim_grid_pos_y: 1800152.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1392151.88
      sim_grid_pos_y: 1800688.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1391224.38
      sim_grid_pos_y: 1800164.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1390286.12
      sim_grid_pos_y: 1799504.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1389667.75
      sim_grid_pos_y: 1798939.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1389504.5
      sim_grid_pos_y: 1798325.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1389343.5
      sim_grid_pos_y: 1797906.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1388827.88
      sim_grid_pos_y: 1795453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1388703.12
      sim_grid_pos_y: 1795155.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1388915.25
      sim_grid_pos_y: 1794385.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1389418.5
      sim_grid_pos_y: 1794639.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1389632.5
      sim_grid_pos_y: 1794703
    }
    terrain_level_point {
      sim_grid_pos_x: 1390038
      sim_grid_pos_y: 1794866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1390781.25
      sim_grid_pos_y: 1795728.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1391191.75
      sim_grid_pos_y: 1796080.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1391345.62
      sim_grid_pos_y: 1795953.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1391746.12
      sim_grid_pos_y: 1795969.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392137.75
      sim_grid_pos_y: 1796113
    }
    terrain_level_point {
      sim_grid_pos_x: 1392443.38
      sim_grid_pos_y: 1796460.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1392478.38
      sim_grid_pos_y: 1796772.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1393173
      sim_grid_pos_y: 1796815.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1393404.5
      sim_grid_pos_y: 1.79789e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1392663.88
      sim_grid_pos_y: 1798249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1392726.12
      sim_grid_pos_y: 1798525.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1392737.88
      sim_grid_pos_y: 1798874.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392710.38
      sim_grid_pos_y: 1799020.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392904.88
      sim_grid_pos_y: 1799358.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1392894.88
      sim_grid_pos_y: 1799933.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1392468.25
      sim_grid_pos_y: 1800177.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1392427.38
      sim_grid_pos_y: 1800212.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1392208.12
      sim_grid_pos_y: 1800837.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1391169.5
      sim_grid_pos_y: 1800251
    }
    terrain_level_point {
      sim_grid_pos_x: 1390221.75
      sim_grid_pos_y: 1799584.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1389576.38
      sim_grid_pos_y: 1798994.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1389406.88
      sim_grid_pos_y: 1798356.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1389244.88
      sim_grid_pos_y: 1797936
    }
    terrain_level_point {
      sim_grid_pos_x: 1388729.62
      sim_grid_pos_y: 1795484.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1388594.88
      sim_grid_pos_y: 1795162.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1388856.75
      sim_grid_pos_y: 1794212.5
    }
  }
}
