terrain_level_data {
  terrain_level: 2793
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1437327.12
      sim_grid_pos_y: 1769553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436812.25
      sim_grid_pos_y: 1769772.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436499.5
      sim_grid_pos_y: 1770013
    }
    terrain_level_point {
      sim_grid_pos_x: 1436404.38
      sim_grid_pos_y: 1770476.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436105.88
      sim_grid_pos_y: 1770588.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435748
      sim_grid_pos_y: 1770869.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1435358.12
      sim_grid_pos_y: 1771325.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1436016.38
      sim_grid_pos_y: 1771563.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436771.75
      sim_grid_pos_y: 1771288.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436975.75
      sim_grid_pos_y: 1770981
    }
    terrain_level_point {
      sim_grid_pos_x: 1437329.38
      sim_grid_pos_y: 1770649.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1437607.25
      sim_grid_pos_y: 1770182.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1437353.5
      sim_grid_pos_y: 1769486.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436786.12
      sim_grid_pos_y: 1769728.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436453.12
      sim_grid_pos_y: 1769984
    }
    terrain_level_point {
      sim_grid_pos_x: 1436359.88
      sim_grid_pos_y: 1770438.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436080.38
      sim_grid_pos_y: 1770543.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1435712.38
      sim_grid_pos_y: 1770832.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1435271
      sim_grid_pos_y: 1771348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1436016.5
      sim_grid_pos_y: 1771618.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436805.12
      sim_grid_pos_y: 1771330.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437015.12
      sim_grid_pos_y: 1771014.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1437369.75
      sim_grid_pos_y: 1770681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1437664.88
      sim_grid_pos_y: 1770186.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1437379.75
      sim_grid_pos_y: 1769419.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436760.12
      sim_grid_pos_y: 1769683.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436406.75
      sim_grid_pos_y: 1769955
    }
    terrain_level_point {
      sim_grid_pos_x: 1436315.38
      sim_grid_pos_y: 1770400.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436055
      sim_grid_pos_y: 1770498
    }
    terrain_level_point {
      sim_grid_pos_x: 1435676.62
      sim_grid_pos_y: 1770795.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1435183.88
      sim_grid_pos_y: 1771371.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1436016.5
      sim_grid_pos_y: 1771673
    }
    terrain_level_point {
      sim_grid_pos_x: 1436838.5
      sim_grid_pos_y: 1771373
    }
    terrain_level_point {
      sim_grid_pos_x: 1437054.5
      sim_grid_pos_y: 1771047.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437410.12
      sim_grid_pos_y: 1770714.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1437722.5
      sim_grid_pos_y: 1770189.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1437406.12
      sim_grid_pos_y: 1769352.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436734
      sim_grid_pos_y: 1769639
    }
    terrain_level_point {
      sim_grid_pos_x: 1436360.38
      sim_grid_pos_y: 1769925.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436270.88
      sim_grid_pos_y: 1770362
    }
    terrain_level_point {
      sim_grid_pos_x: 1436029.5
      sim_grid_pos_y: 1770452.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1435641
      sim_grid_pos_y: 1770758.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1435096.75
      sim_grid_pos_y: 1771394.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436016.62
      sim_grid_pos_y: 1771727.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1436871.88
      sim_grid_pos_y: 1771415.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1437094
      sim_grid_pos_y: 1771080.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1437450.38
      sim_grid_pos_y: 1770746.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437780.12
      sim_grid_pos_y: 1770193
    }
  }
}
