terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2865152.75
      sim_grid_pos_y: 2292116.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2867011
      sim_grid_pos_y: 2287302.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2871998.5
      sim_grid_pos_y: 2289340.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2871336.75
      sim_grid_pos_y: 2291175
    }
    terrain_level_point {
      sim_grid_pos_x: 2871964.5
      sim_grid_pos_y: 2292576
    }
    terrain_level_point {
      sim_grid_pos_x: 2870685.5
      sim_grid_pos_y: 2293045.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2870538
      sim_grid_pos_y: 2293523
    }
    terrain_level_point {
      sim_grid_pos_x: 2868260.75
      sim_grid_pos_y: 2294535
    }
    terrain_level_point {
      sim_grid_pos_x: 2867732.25
      sim_grid_pos_y: 2294762.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2867003
      sim_grid_pos_y: 2294584.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865678.75
      sim_grid_pos_y: 2294036.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2865289.75
      sim_grid_pos_y: 2293822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865145.25
      sim_grid_pos_y: 2293717.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2865064.25
      sim_grid_pos_y: 2293914.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2864756.75
      sim_grid_pos_y: 2293778.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2872037.25
      sim_grid_pos_y: 2289323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2871369.75
      sim_grid_pos_y: 2291173.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2872006.25
      sim_grid_pos_y: 2292593.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2870710.5
      sim_grid_pos_y: 2293069.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2870563.25
      sim_grid_pos_y: 2293545.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2868273
      sim_grid_pos_y: 2294563.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2867735
      sim_grid_pos_y: 2294794.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2866993.5
      sim_grid_pos_y: 2294613.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2865665.25
      sim_grid_pos_y: 2294064.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865273.25
      sim_grid_pos_y: 2293848.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865158.75
      sim_grid_pos_y: 2293765
    }
    terrain_level_point {
      sim_grid_pos_x: 2865080.5
      sim_grid_pos_y: 2293955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2864720.75
      sim_grid_pos_y: 2293796.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2865123.5
      sim_grid_pos_y: 2292107
    }
    terrain_level_point {
      sim_grid_pos_x: 2866993.5
      sim_grid_pos_y: 2287262.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2872076.25
      sim_grid_pos_y: 2289306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2871403
      sim_grid_pos_y: 2291172.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2872047.75
      sim_grid_pos_y: 2292611
    }
    terrain_level_point {
      sim_grid_pos_x: 2870735.5
      sim_grid_pos_y: 2293093
    }
    terrain_level_point {
      sim_grid_pos_x: 2870588.5
      sim_grid_pos_y: 2293567.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2868285.5
      sim_grid_pos_y: 2294591.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2867737.75
      sim_grid_pos_y: 2294827
    }
    terrain_level_point {
      sim_grid_pos_x: 2866983.75
      sim_grid_pos_y: 2294643.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2865652
      sim_grid_pos_y: 2294092.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2865256.5
      sim_grid_pos_y: 2293874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865172.25
      sim_grid_pos_y: 2293813
    }
    terrain_level_point {
      sim_grid_pos_x: 2865097
      sim_grid_pos_y: 2293996
    }
    terrain_level_point {
      sim_grid_pos_x: 2864685
      sim_grid_pos_y: 2293814
    }
    terrain_level_point {
      sim_grid_pos_x: 2865094
      sim_grid_pos_y: 2292097.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2866976.25
      sim_grid_pos_y: 2287222.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2872115.25
      sim_grid_pos_y: 2289288.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2871436.25
      sim_grid_pos_y: 2291171.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2872089.25
      sim_grid_pos_y: 2292628.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2870760.25
      sim_grid_pos_y: 2293116.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2870613.75
      sim_grid_pos_y: 2293590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2868297.75
      sim_grid_pos_y: 2294619.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2867740.5
      sim_grid_pos_y: 2294859.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2866974.25
      sim_grid_pos_y: 2294672.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865638.75
      sim_grid_pos_y: 2.29412e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2.86524e+06
      sim_grid_pos_y: 2293900.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865185.75
      sim_grid_pos_y: 2293861
    }
    terrain_level_point {
      sim_grid_pos_x: 2865113.5
      sim_grid_pos_y: 2294037
    }
    terrain_level_point {
      sim_grid_pos_x: 2864649
      sim_grid_pos_y: 2293831.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2865064.5
      sim_grid_pos_y: 2292088.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2866958.75
      sim_grid_pos_y: 2287181.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2872154.25
      sim_grid_pos_y: 2289271.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2871469.25
      sim_grid_pos_y: 2.29117e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2872130.75
      sim_grid_pos_y: 2292646
    }
    terrain_level_point {
      sim_grid_pos_x: 2870785.25
      sim_grid_pos_y: 2293140.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2870639
      sim_grid_pos_y: 2293612.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.86831e+06
      sim_grid_pos_y: 2294647.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2867743.25
      sim_grid_pos_y: 2294891.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2866964.75
      sim_grid_pos_y: 2294701.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2865625.25
      sim_grid_pos_y: 2294148
    }
    terrain_level_point {
      sim_grid_pos_x: 2865223.5
      sim_grid_pos_y: 2293926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865199.25
      sim_grid_pos_y: 2293909
    }
    terrain_level_point {
      sim_grid_pos_x: 2.86513e+06
      sim_grid_pos_y: 2294078
    }
    terrain_level_point {
      sim_grid_pos_x: 2864613.25
      sim_grid_pos_y: 2293849.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2865035
      sim_grid_pos_y: 2292079.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2866941.25
      sim_grid_pos_y: 2287141.5
    }
  }
}
