terrain_level_data {
  terrain_level: 3620
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1726428.88
      sim_grid_pos_y: 1654867.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726479.88
      sim_grid_pos_y: 1654982.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1726598
      sim_grid_pos_y: 1655049.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1726712.88
      sim_grid_pos_y: 1654975.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1726764.38
      sim_grid_pos_y: 1654876.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1726705.88
      sim_grid_pos_y: 1654747.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1726599.5
      sim_grid_pos_y: 1654709
    }
    terrain_level_point {
      sim_grid_pos_x: 1726469
      sim_grid_pos_y: 1654773
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1726593.5
      sim_grid_pos_y: 1654597.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726389.5
      sim_grid_pos_y: 1654697.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726317.12
      sim_grid_pos_y: 1654868.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726399.88
      sim_grid_pos_y: 1655055
    }
    terrain_level_point {
      sim_grid_pos_x: 1726601.5
      sim_grid_pos_y: 1655169.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1726791.38
      sim_grid_pos_y: 1655046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726878.38
      sim_grid_pos_y: 1654879.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1726781.38
      sim_grid_pos_y: 1654665.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1726587.38
      sim_grid_pos_y: 1654486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.72631e+06
      sim_grid_pos_y: 1654622.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1726205.38
      sim_grid_pos_y: 1654869.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1726319.88
      sim_grid_pos_y: 1655127.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1726605
      sim_grid_pos_y: 1655289.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726869.75
      sim_grid_pos_y: 1655118
    }
    terrain_level_point {
      sim_grid_pos_x: 1726992.38
      sim_grid_pos_y: 1654882.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726856.88
      sim_grid_pos_y: 1654584.12
    }
  }
}
terrain_level_data {
  terrain_level: 3555
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1725922.5
      sim_grid_pos_y: 1654513.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1725790.5
      sim_grid_pos_y: 1654686.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1725829.25
      sim_grid_pos_y: 1654836.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1726237.75
      sim_grid_pos_y: 1654948.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1726348.75
      sim_grid_pos_y: 1654781.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1726276.75
      sim_grid_pos_y: 1654677.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1726248.5
      sim_grid_pos_y: 1654552.88
    }
  }
}
