terrain_level_data {
  terrain_level: 30
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 526866.125
      sim_grid_pos_y: 2213671
    }
    terrain_level_point {
      sim_grid_pos_x: 526810.875
      sim_grid_pos_y: 2214557.5
    }
    terrain_level_point {
      sim_grid_pos_x: 526752.25
      sim_grid_pos_y: 2215416.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526690.75
      sim_grid_pos_y: 2215907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 526704.812
      sim_grid_pos_y: 2216251
    }
    terrain_level_point {
      sim_grid_pos_x: 527242
      sim_grid_pos_y: 2216537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527616.375
      sim_grid_pos_y: 2216537.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527838.125
      sim_grid_pos_y: 2216243.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527798.312
      sim_grid_pos_y: 2214626.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528266
      sim_grid_pos_y: 2213609.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527659.188
      sim_grid_pos_y: 2213044.5
    }
    terrain_level_point {
      sim_grid_pos_x: 527335.125
      sim_grid_pos_y: 2213057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526830.375
      sim_grid_pos_y: 2213233.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526819.5
      sim_grid_pos_y: 2213501.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 527666.938
      sim_grid_pos_y: 2213023.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527331.25
      sim_grid_pos_y: 2213037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526810.438
      sim_grid_pos_y: 2213218.5
    }
    terrain_level_point {
      sim_grid_pos_x: 526798.875
      sim_grid_pos_y: 2213504
    }
    terrain_level_point {
      sim_grid_pos_x: 526845.438
      sim_grid_pos_y: 2213673.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526790.438
      sim_grid_pos_y: 2214556.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526731.812
      sim_grid_pos_y: 2215414.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526670.188
      sim_grid_pos_y: 2215906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526684.812
      sim_grid_pos_y: 2216263.5
    }
    terrain_level_point {
      sim_grid_pos_x: 527236.875
      sim_grid_pos_y: 2216558.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527626.625
      sim_grid_pos_y: 2216557.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527858.75
      sim_grid_pos_y: 2216250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 527818.938
      sim_grid_pos_y: 2214630.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528290.812
      sim_grid_pos_y: 2213604.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 527674.625
      sim_grid_pos_y: 2213002.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527327.375
      sim_grid_pos_y: 2213017
    }
    terrain_level_point {
      sim_grid_pos_x: 526790.5
      sim_grid_pos_y: 2213203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526778.25
      sim_grid_pos_y: 2213506.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526824.75
      sim_grid_pos_y: 2213675.5
    }
    terrain_level_point {
      sim_grid_pos_x: 526770
      sim_grid_pos_y: 2214554.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526711.438
      sim_grid_pos_y: 2215412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526649.625
      sim_grid_pos_y: 2215905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526664.812
      sim_grid_pos_y: 2216276
    }
    terrain_level_point {
      sim_grid_pos_x: 527231.75
      sim_grid_pos_y: 2216578.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527636.812
      sim_grid_pos_y: 2216578.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527879.438
      sim_grid_pos_y: 2216257.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527839.5
      sim_grid_pos_y: 2214634.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528315.625
      sim_grid_pos_y: 2213599.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 527682.312
      sim_grid_pos_y: 2212982
    }
    terrain_level_point {
      sim_grid_pos_x: 527323.5
      sim_grid_pos_y: 2212996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 526770.562
      sim_grid_pos_y: 2213189
    }
    terrain_level_point {
      sim_grid_pos_x: 526757.625
      sim_grid_pos_y: 2213508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526804.062
      sim_grid_pos_y: 2213677.5
    }
    terrain_level_point {
      sim_grid_pos_x: 526749.5
      sim_grid_pos_y: 2214553.75
    }
    terrain_level_point {
      sim_grid_pos_x: 526691
      sim_grid_pos_y: 2215410.25
    }
    terrain_level_point {
      sim_grid_pos_x: 526629.062
      sim_grid_pos_y: 2215905
    }
    terrain_level_point {
      sim_grid_pos_x: 526644.812
      sim_grid_pos_y: 2216288.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527226.625
      sim_grid_pos_y: 2216599.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527647.062
      sim_grid_pos_y: 2216598.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527900.125
      sim_grid_pos_y: 2216263.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527860.125
      sim_grid_pos_y: 2214639
    }
    terrain_level_point {
      sim_grid_pos_x: 528340.5
      sim_grid_pos_y: 2213594.5
    }
  }
}
terrain_level_data {
  terrain_level: 125
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 527842.25
      sim_grid_pos_y: 2214687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 527839.125
      sim_grid_pos_y: 2215261.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528698.25
      sim_grid_pos_y: 2215273.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528682.25
      sim_grid_pos_y: 2214683
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 528702.188
      sim_grid_pos_y: 2214662.5
    }
    terrain_level_point {
      sim_grid_pos_x: 527821.875
      sim_grid_pos_y: 2214667.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527818.5
      sim_grid_pos_y: 2215281.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528719.312
      sim_grid_pos_y: 2215294.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 528722.125
      sim_grid_pos_y: 2214641.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527801.5
      sim_grid_pos_y: 2214646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527797.875
      sim_grid_pos_y: 2215301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528740.375
      sim_grid_pos_y: 2215315
    }
  }
}
terrain_level_data {
  terrain_level: 25
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 528141.688
      sim_grid_pos_y: 2216435
    }
    terrain_level_point {
      sim_grid_pos_x: 528121.938
      sim_grid_pos_y: 2216675.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528379.062
      sim_grid_pos_y: 2217083
    }
    terrain_level_point {
      sim_grid_pos_x: 528480
      sim_grid_pos_y: 2217134.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528591.312
      sim_grid_pos_y: 2216974.25
    }
    terrain_level_point {
      sim_grid_pos_x: 529033.25
      sim_grid_pos_y: 2217272.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528976.125
      sim_grid_pos_y: 2217371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 530837.25
      sim_grid_pos_y: 2217367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 531389.438
      sim_grid_pos_y: 2218266.5
    }
    terrain_level_point {
      sim_grid_pos_x: 531597.562
      sim_grid_pos_y: 2218291.75
    }
    terrain_level_point {
      sim_grid_pos_x: 532582.5
      sim_grid_pos_y: 2217571
    }
    terrain_level_point {
      sim_grid_pos_x: 532501.438
      sim_grid_pos_y: 2217195.75
    }
    terrain_level_point {
      sim_grid_pos_x: 532512.25
      sim_grid_pos_y: 2216075.25
    }
    terrain_level_point {
      sim_grid_pos_x: 530491.25
      sim_grid_pos_y: 2216160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 530381.375
      sim_grid_pos_y: 2216276.25
    }
    terrain_level_point {
      sim_grid_pos_x: 529110.625
      sim_grid_pos_y: 2216267.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528907.375
      sim_grid_pos_y: 2216136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527806.438
      sim_grid_pos_y: 2216115
    }
    terrain_level_point {
      sim_grid_pos_x: 527810.5
      sim_grid_pos_y: 2216253.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 532532.938
      sim_grid_pos_y: 2216053.75
    }
    terrain_level_point {
      sim_grid_pos_x: 530482.125
      sim_grid_pos_y: 2216140.25
    }
    terrain_level_point {
      sim_grid_pos_x: 530372.625
      sim_grid_pos_y: 2216255.75
    }
    terrain_level_point {
      sim_grid_pos_x: 529116.75
      sim_grid_pos_y: 2216246.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528913.625
      sim_grid_pos_y: 2216115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 527785.312
      sim_grid_pos_y: 2216094
    }
    terrain_level_point {
      sim_grid_pos_x: 527790.375
      sim_grid_pos_y: 2216266
    }
    terrain_level_point {
      sim_grid_pos_x: 528120.125
      sim_grid_pos_y: 2216446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528100.938
      sim_grid_pos_y: 2216680.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528364.75
      sim_grid_pos_y: 2217098.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528486.625
      sim_grid_pos_y: 2217160.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528596.562
      sim_grid_pos_y: 2217002.5
    }
    terrain_level_point {
      sim_grid_pos_x: 529005.938
      sim_grid_pos_y: 2217279
    }
    terrain_level_point {
      sim_grid_pos_x: 528952.438
      sim_grid_pos_y: 2217371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528964.312
      sim_grid_pos_y: 2217391.75
    }
    terrain_level_point {
      sim_grid_pos_x: 530825.812
      sim_grid_pos_y: 2217388.25
    }
    terrain_level_point {
      sim_grid_pos_x: 531377.125
      sim_grid_pos_y: 2218285.75
    }
    terrain_level_point {
      sim_grid_pos_x: 531603.125
      sim_grid_pos_y: 2218313
    }
    terrain_level_point {
      sim_grid_pos_x: 532605.375
      sim_grid_pos_y: 2217579.75
    }
    terrain_level_point {
      sim_grid_pos_x: 532521.938
      sim_grid_pos_y: 2217193.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 532553.625
      sim_grid_pos_y: 2216032.5
    }
    terrain_level_point {
      sim_grid_pos_x: 530472.938
      sim_grid_pos_y: 2.21612e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 530363.875
      sim_grid_pos_y: 2216235.25
    }
    terrain_level_point {
      sim_grid_pos_x: 529122.812
      sim_grid_pos_y: 2216226.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528919.812
      sim_grid_pos_y: 2216095.5
    }
    terrain_level_point {
      sim_grid_pos_x: 527764.188
      sim_grid_pos_y: 2216073.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527770.25
      sim_grid_pos_y: 2216278.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528098.625
      sim_grid_pos_y: 2216458.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528079.938
      sim_grid_pos_y: 2216685.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528350.438
      sim_grid_pos_y: 2217114.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528493.25
      sim_grid_pos_y: 2217187
    }
    terrain_level_point {
      sim_grid_pos_x: 528601.875
      sim_grid_pos_y: 2217030.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528978.562
      sim_grid_pos_y: 2217285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528928.75
      sim_grid_pos_y: 2217371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528952.5
      sim_grid_pos_y: 2217412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 530814.375
      sim_grid_pos_y: 2217408.75
    }
    terrain_level_point {
      sim_grid_pos_x: 531364.875
      sim_grid_pos_y: 2218304.75
    }
    terrain_level_point {
      sim_grid_pos_x: 531608.75
      sim_grid_pos_y: 2218334.25
    }
    terrain_level_point {
      sim_grid_pos_x: 532628.188
      sim_grid_pos_y: 2217588.5
    }
    terrain_level_point {
      sim_grid_pos_x: 532542.438
      sim_grid_pos_y: 2217191.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 532574.375
      sim_grid_pos_y: 2216011
    }
    terrain_level_point {
      sim_grid_pos_x: 530463.75
      sim_grid_pos_y: 2.2161e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 530355.062
      sim_grid_pos_y: 2216214.5
    }
    terrain_level_point {
      sim_grid_pos_x: 529128.938
      sim_grid_pos_y: 2216205.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528926.062
      sim_grid_pos_y: 2216075
    }
    terrain_level_point {
      sim_grid_pos_x: 527743
      sim_grid_pos_y: 2216052.25
    }
    terrain_level_point {
      sim_grid_pos_x: 527750.062
      sim_grid_pos_y: 2216290.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528077.125
      sim_grid_pos_y: 2216469.75
    }
    terrain_level_point {
      sim_grid_pos_x: 528058.938
      sim_grid_pos_y: 2216691
    }
    terrain_level_point {
      sim_grid_pos_x: 528336.125
      sim_grid_pos_y: 2.21713e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 528499.875
      sim_grid_pos_y: 2217213.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528607.125
      sim_grid_pos_y: 2217059.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528951.25
      sim_grid_pos_y: 2217291.5
    }
    terrain_level_point {
      sim_grid_pos_x: 528905.062
      sim_grid_pos_y: 2217371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 528940.688
      sim_grid_pos_y: 2217432.75
    }
    terrain_level_point {
      sim_grid_pos_x: 530802.938
      sim_grid_pos_y: 2217429.25
    }
    terrain_level_point {
      sim_grid_pos_x: 531352.562
      sim_grid_pos_y: 2218324
    }
    terrain_level_point {
      sim_grid_pos_x: 531614.312
      sim_grid_pos_y: 2218355.5
    }
    terrain_level_point {
      sim_grid_pos_x: 532651.062
      sim_grid_pos_y: 2217597.25
    }
    terrain_level_point {
      sim_grid_pos_x: 532563
      sim_grid_pos_y: 2217189.5
    }
  }
}
