terrain_level_data {
  terrain_level: 110
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 502264.094
      sim_grid_pos_y: 1935504.38
    }
    terrain_level_point {
      sim_grid_pos_x: 502204.781
      sim_grid_pos_y: 1935472.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502121.719
      sim_grid_pos_y: 1935472
    }
    terrain_level_point {
      sim_grid_pos_x: 501965.938
      sim_grid_pos_y: 1935498.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501751.125
      sim_grid_pos_y: 1935510.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501719.969
      sim_grid_pos_y: 1935367.38
    }
    terrain_level_point {
      sim_grid_pos_x: 501724.781
      sim_grid_pos_y: 1935243.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501776.969
      sim_grid_pos_y: 1935112.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501851.344
      sim_grid_pos_y: 1935020.38
    }
    terrain_level_point {
      sim_grid_pos_x: 502018.938
      sim_grid_pos_y: 1934968.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502097.188
      sim_grid_pos_y: 1934908.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502155.188
      sim_grid_pos_y: 1934821.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502099.656
      sim_grid_pos_y: 1934584.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502070.031
      sim_grid_pos_y: 1934421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502017.375
      sim_grid_pos_y: 1934116.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504082.969
      sim_grid_pos_y: 1933767.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504096.812
      sim_grid_pos_y: 1933813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 503990.656
      sim_grid_pos_y: 1934120.62
    }
    terrain_level_point {
      sim_grid_pos_x: 503635.531
      sim_grid_pos_y: 1934255.25
    }
    terrain_level_point {
      sim_grid_pos_x: 503566.969
      sim_grid_pos_y: 1934397.5
    }
    terrain_level_point {
      sim_grid_pos_x: 503781.156
      sim_grid_pos_y: 1934617.62
    }
    terrain_level_point {
      sim_grid_pos_x: 503958.5
      sim_grid_pos_y: 1934701.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504045.594
      sim_grid_pos_y: 1934981.62
    }
    terrain_level_point {
      sim_grid_pos_x: 504274.156
      sim_grid_pos_y: 1935150.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504543.656
      sim_grid_pos_y: 1935148.62
    }
    terrain_level_point {
      sim_grid_pos_x: 504661.156
      sim_grid_pos_y: 1935253.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504577.125
      sim_grid_pos_y: 1935375.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504596.531
      sim_grid_pos_y: 1935518.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504661.5
      sim_grid_pos_y: 1935701.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504595.656
      sim_grid_pos_y: 1935752.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504126.844
      sim_grid_pos_y: 1935475.12
    }
    terrain_level_point {
      sim_grid_pos_x: 503513.719
      sim_grid_pos_y: 1935577
    }
    terrain_level_point {
      sim_grid_pos_x: 503561.75
      sim_grid_pos_y: 1935885.5
    }
    terrain_level_point {
      sim_grid_pos_x: 503147.969
      sim_grid_pos_y: 1935985.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502717.094
      sim_grid_pos_y: 1936058.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502522.5
      sim_grid_pos_y: 1936611
    }
    terrain_level_point {
      sim_grid_pos_x: 501980.656
      sim_grid_pos_y: 1937560.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501779.531
      sim_grid_pos_y: 1937440.25
    }
    terrain_level_point {
      sim_grid_pos_x: 501976
      sim_grid_pos_y: 1936961.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502117.094
      sim_grid_pos_y: 1936559
    }
    terrain_level_point {
      sim_grid_pos_x: 502059.406
      sim_grid_pos_y: 1936495.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502236.719
      sim_grid_pos_y: 1936129.38
    }
    terrain_level_point {
      sim_grid_pos_x: 502345.156
      sim_grid_pos_y: 1935960.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 504129.125
      sim_grid_pos_y: 1933813.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504015.031
      sim_grid_pos_y: 1934144.25
    }
    terrain_level_point {
      sim_grid_pos_x: 503657.938
      sim_grid_pos_y: 1934279.75
    }
    terrain_level_point {
      sim_grid_pos_x: 503604.031
      sim_grid_pos_y: 1934391.5
    }
    terrain_level_point {
      sim_grid_pos_x: 503799.312
      sim_grid_pos_y: 1934592.12
    }
    terrain_level_point {
      sim_grid_pos_x: 503983.844
      sim_grid_pos_y: 1934679.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504071.969
      sim_grid_pos_y: 1934962.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504284.188
      sim_grid_pos_y: 1935119.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504555.312
      sim_grid_pos_y: 1935117.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504701.844
      sim_grid_pos_y: 1935248.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504609.219
      sim_grid_pos_y: 1935383.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504626.594
      sim_grid_pos_y: 1935511
    }
    terrain_level_point {
      sim_grid_pos_x: 504697.938
      sim_grid_pos_y: 1935712.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504597.969
      sim_grid_pos_y: 1935789.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504120.812
      sim_grid_pos_y: 1935507.38
    }
    terrain_level_point {
      sim_grid_pos_x: 503548.781
      sim_grid_pos_y: 1935602.38
    }
    terrain_level_point {
      sim_grid_pos_x: 503596.5
      sim_grid_pos_y: 1935908.75
    }
    terrain_level_point {
      sim_grid_pos_x: 503154.156
      sim_grid_pos_y: 1936015.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502740.062
      sim_grid_pos_y: 1936085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502550.594
      sim_grid_pos_y: 1936623.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501991.812
      sim_grid_pos_y: 1937602.62
    }
    terrain_level_point {
      sim_grid_pos_x: 501741
      sim_grid_pos_y: 1937453.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501947.25
      sim_grid_pos_y: 1936950.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502082
      sim_grid_pos_y: 1936566.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502022.688
      sim_grid_pos_y: 1936500.88
    }
    terrain_level_point {
      sim_grid_pos_x: 502209.844
      sim_grid_pos_y: 1936114.38
    }
    terrain_level_point {
      sim_grid_pos_x: 502312.781
      sim_grid_pos_y: 1935954.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502236.438
      sim_grid_pos_y: 1935524.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502196.969
      sim_grid_pos_y: 1935503.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502124.188
      sim_grid_pos_y: 1935502.75
    }
    terrain_level_point {
      sim_grid_pos_x: 501969.438
      sim_grid_pos_y: 1935529.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501726.625
      sim_grid_pos_y: 1935543.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501689.062
      sim_grid_pos_y: 1935370.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501694.25
      sim_grid_pos_y: 1935237.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501750.094
      sim_grid_pos_y: 1935097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 501833.281
      sim_grid_pos_y: 1934993.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502004.625
      sim_grid_pos_y: 1934940.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502074.438
      sim_grid_pos_y: 1934887.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502122.188
      sim_grid_pos_y: 1934815.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502069.531
      sim_grid_pos_y: 1934590.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502039.75
      sim_grid_pos_y: 1934426.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501981.812
      sim_grid_pos_y: 1934091.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504104.594
      sim_grid_pos_y: 1933732.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 504161.438
      sim_grid_pos_y: 1933814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504039.406
      sim_grid_pos_y: 1934167.88
    }
    terrain_level_point {
      sim_grid_pos_x: 503680.281
      sim_grid_pos_y: 1934304.12
    }
    terrain_level_point {
      sim_grid_pos_x: 503641.094
      sim_grid_pos_y: 1934385.38
    }
    terrain_level_point {
      sim_grid_pos_x: 503817.5
      sim_grid_pos_y: 1934566.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504009.219
      sim_grid_pos_y: 1934657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504098.344
      sim_grid_pos_y: 1934944.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504294.25
      sim_grid_pos_y: 1935088.62
    }
    terrain_level_point {
      sim_grid_pos_x: 504567
      sim_grid_pos_y: 1935086.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504742.531
      sim_grid_pos_y: 1935244
    }
    terrain_level_point {
      sim_grid_pos_x: 504641.281
      sim_grid_pos_y: 1935391
    }
    terrain_level_point {
      sim_grid_pos_x: 504656.625
      sim_grid_pos_y: 1935503.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504734.375
      sim_grid_pos_y: 1935722.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504600.25
      sim_grid_pos_y: 1935826.62
    }
    terrain_level_point {
      sim_grid_pos_x: 504114.812
      sim_grid_pos_y: 1935539.5
    }
    terrain_level_point {
      sim_grid_pos_x: 503583.875
      sim_grid_pos_y: 1935627.75
    }
    terrain_level_point {
      sim_grid_pos_x: 503631.25
      sim_grid_pos_y: 1935932
    }
    terrain_level_point {
      sim_grid_pos_x: 503160.344
      sim_grid_pos_y: 1936045.88
    }
    terrain_level_point {
      sim_grid_pos_x: 502763.062
      sim_grid_pos_y: 1936112.88
    }
    terrain_level_point {
      sim_grid_pos_x: 502578.688
      sim_grid_pos_y: 1936636.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502003
      sim_grid_pos_y: 1937645.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501702.5
      sim_grid_pos_y: 1937465.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501918.469
      sim_grid_pos_y: 1936939.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502046.906
      sim_grid_pos_y: 1936573.25
    }
    terrain_level_point {
      sim_grid_pos_x: 501985.938
      sim_grid_pos_y: 1936506.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502182.969
      sim_grid_pos_y: 1936099.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502280.375
      sim_grid_pos_y: 1935947.62
    }
    terrain_level_point {
      sim_grid_pos_x: 502208.781
      sim_grid_pos_y: 1935544.62
    }
    terrain_level_point {
      sim_grid_pos_x: 502189.125
      sim_grid_pos_y: 1935534.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502126.719
      sim_grid_pos_y: 1935533.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501972.906
      sim_grid_pos_y: 1935560.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501702.156
      sim_grid_pos_y: 1935575.25
    }
    terrain_level_point {
      sim_grid_pos_x: 501658.188
      sim_grid_pos_y: 1935372.75
    }
    terrain_level_point {
      sim_grid_pos_x: 501663.719
      sim_grid_pos_y: 1935231
    }
    terrain_level_point {
      sim_grid_pos_x: 501723.25
      sim_grid_pos_y: 1935081.62
    }
    terrain_level_point {
      sim_grid_pos_x: 501815.188
      sim_grid_pos_y: 1934967.12
    }
    terrain_level_point {
      sim_grid_pos_x: 501990.25
      sim_grid_pos_y: 1934913
    }
    terrain_level_point {
      sim_grid_pos_x: 502051.688
      sim_grid_pos_y: 1934865.88
    }
    terrain_level_point {
      sim_grid_pos_x: 502089.219
      sim_grid_pos_y: 1934809.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502039.406
      sim_grid_pos_y: 1934596.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502009.469
      sim_grid_pos_y: 1934432.25
    }
    terrain_level_point {
      sim_grid_pos_x: 501946.25
      sim_grid_pos_y: 1934066.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504126.219
      sim_grid_pos_y: 1933697.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 504193.75
      sim_grid_pos_y: 1933815.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504063.781
      sim_grid_pos_y: 1934191.62
    }
    terrain_level_point {
      sim_grid_pos_x: 503702.688
      sim_grid_pos_y: 1934328.5
    }
    terrain_level_point {
      sim_grid_pos_x: 503678.156
      sim_grid_pos_y: 1934379.38
    }
    terrain_level_point {
      sim_grid_pos_x: 503835.656
      sim_grid_pos_y: 1934541.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504034.562
      sim_grid_pos_y: 1934635.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504124.719
      sim_grid_pos_y: 1934925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504304.25
      sim_grid_pos_y: 1935057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504578.656
      sim_grid_pos_y: 1935056.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504783.25
      sim_grid_pos_y: 1935239.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504673.375
      sim_grid_pos_y: 1935398.62
    }
    terrain_level_point {
      sim_grid_pos_x: 504686.688
      sim_grid_pos_y: 1935496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504770.812
      sim_grid_pos_y: 1935733.62
    }
    terrain_level_point {
      sim_grid_pos_x: 504602.562
      sim_grid_pos_y: 1935863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504108.812
      sim_grid_pos_y: 1935571.75
    }
    terrain_level_point {
      sim_grid_pos_x: 503618.938
      sim_grid_pos_y: 1935653.12
    }
    terrain_level_point {
      sim_grid_pos_x: 503666
      sim_grid_pos_y: 1935955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 503166.5
      sim_grid_pos_y: 1936076
    }
    terrain_level_point {
      sim_grid_pos_x: 502786.062
      sim_grid_pos_y: 1936140.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502606.75
      sim_grid_pos_y: 1936649.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502014.156
      sim_grid_pos_y: 1937687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501663.969
      sim_grid_pos_y: 1937478.75
    }
    terrain_level_point {
      sim_grid_pos_x: 501889.688
      sim_grid_pos_y: 1936928.38
    }
    terrain_level_point {
      sim_grid_pos_x: 502011.812
      sim_grid_pos_y: 1936580.38
    }
    terrain_level_point {
      sim_grid_pos_x: 501949.188
      sim_grid_pos_y: 1936511.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502156.094
      sim_grid_pos_y: 1936084.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502248
      sim_grid_pos_y: 1935941.12
    }
    terrain_level_point {
      sim_grid_pos_x: 502181.125
      sim_grid_pos_y: 1935564.88
    }
    terrain_level_point {
      sim_grid_pos_x: 502129.188
      sim_grid_pos_y: 1935564.38
    }
    terrain_level_point {
      sim_grid_pos_x: 501976.406
      sim_grid_pos_y: 1935590.75
    }
    terrain_level_point {
      sim_grid_pos_x: 501677.656
      sim_grid_pos_y: 1935607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501627.312
      sim_grid_pos_y: 1935375.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501633.188
      sim_grid_pos_y: 1935224.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501696.375
      sim_grid_pos_y: 1935065.88
    }
    terrain_level_point {
      sim_grid_pos_x: 501797.094
      sim_grid_pos_y: 1934940.5
    }
    terrain_level_point {
      sim_grid_pos_x: 501975.938
      sim_grid_pos_y: 1934885.25
    }
    terrain_level_point {
      sim_grid_pos_x: 502028.938
      sim_grid_pos_y: 1934844.5
    }
    terrain_level_point {
      sim_grid_pos_x: 502056.219
      sim_grid_pos_y: 1934803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 502009.281
      sim_grid_pos_y: 1934603
    }
    terrain_level_point {
      sim_grid_pos_x: 501979.188
      sim_grid_pos_y: 1934437.62
    }
    terrain_level_point {
      sim_grid_pos_x: 501910.688
      sim_grid_pos_y: 1934040.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504147.844
      sim_grid_pos_y: 1933662.75
    }
  }
}
terrain_level_data {
  terrain_level: 70
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 503990.219
      sim_grid_pos_y: 1933726.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504240.438
      sim_grid_pos_y: 1933683
    }
    terrain_level_point {
      sim_grid_pos_x: 504599.469
      sim_grid_pos_y: 1933620.88
    }
    terrain_level_point {
      sim_grid_pos_x: 504908.656
      sim_grid_pos_y: 1933581.5
    }
    terrain_level_point {
      sim_grid_pos_x: 505919.438
      sim_grid_pos_y: 1933401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 506011.688
      sim_grid_pos_y: 1933288.62
    }
    terrain_level_point {
      sim_grid_pos_x: 505994.219
      sim_grid_pos_y: 1932853.62
    }
    terrain_level_point {
      sim_grid_pos_x: 505188.344
      sim_grid_pos_y: 1932919.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504575.156
      sim_grid_pos_y: 1933032
    }
    terrain_level_point {
      sim_grid_pos_x: 503944.688
      sim_grid_pos_y: 1933178.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 506013.844
      sim_grid_pos_y: 1932831.5
    }
    terrain_level_point {
      sim_grid_pos_x: 505185.625
      sim_grid_pos_y: 1932899.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504571
      sim_grid_pos_y: 1933011.88
    }
    terrain_level_point {
      sim_grid_pos_x: 503922.781
      sim_grid_pos_y: 1933162.25
    }
    terrain_level_point {
      sim_grid_pos_x: 503971.625
      sim_grid_pos_y: 1933750.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504243.938
      sim_grid_pos_y: 1933703.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504602.594
      sim_grid_pos_y: 1933641.25
    }
    terrain_level_point {
      sim_grid_pos_x: 504911.75
      sim_grid_pos_y: 1933601.75
    }
    terrain_level_point {
      sim_grid_pos_x: 505930.5
      sim_grid_pos_y: 1933420.38
    }
    terrain_level_point {
      sim_grid_pos_x: 506032.5
      sim_grid_pos_y: 1933295.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 506033.5
      sim_grid_pos_y: 1932809.38
    }
    terrain_level_point {
      sim_grid_pos_x: 505182.938
      sim_grid_pos_y: 1932878.75
    }
    terrain_level_point {
      sim_grid_pos_x: 504566.812
      sim_grid_pos_y: 1932991.88
    }
    terrain_level_point {
      sim_grid_pos_x: 503900.875
      sim_grid_pos_y: 1933146.38
    }
    terrain_level_point {
      sim_grid_pos_x: 503953.062
      sim_grid_pos_y: 1933774.12
    }
    terrain_level_point {
      sim_grid_pos_x: 504247.406
      sim_grid_pos_y: 1933723.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504247.406
      sim_grid_pos_y: 1933723.38
    }
    terrain_level_point {
      sim_grid_pos_x: 504605.531
      sim_grid_pos_y: 1933661.5
    }
    terrain_level_point {
      sim_grid_pos_x: 504914.844
      sim_grid_pos_y: 1933622
    }
    terrain_level_point {
      sim_grid_pos_x: 505941.562
      sim_grid_pos_y: 1933439.25
    }
    terrain_level_point {
      sim_grid_pos_x: 506053.281
      sim_grid_pos_y: 1933302.62
    }
  }
}
terrain_level_data {
  terrain_level: 110
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 505494.906
      sim_grid_pos_y: 1934923.62
    }
    terrain_level_point {
      sim_grid_pos_x: 505297
      sim_grid_pos_y: 1935049
    }
    terrain_level_point {
      sim_grid_pos_x: 505260.344
      sim_grid_pos_y: 1934892.75
    }
    terrain_level_point {
      sim_grid_pos_x: 505420.188
      sim_grid_pos_y: 1934625
    }
    terrain_level_point {
      sim_grid_pos_x: 505986.094
      sim_grid_pos_y: 1933987.38
    }
    terrain_level_point {
      sim_grid_pos_x: 506123.781
      sim_grid_pos_y: 1934032.88
    }
    terrain_level_point {
      sim_grid_pos_x: 506224.594
      sim_grid_pos_y: 1934217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 506309.844
      sim_grid_pos_y: 1934430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 506403.875
      sim_grid_pos_y: 1934735
    }
    terrain_level_point {
      sim_grid_pos_x: 506326.344
      sim_grid_pos_y: 1934897
    }
    terrain_level_point {
      sim_grid_pos_x: 506125.906
      sim_grid_pos_y: 1934923.38
    }
    terrain_level_point {
      sim_grid_pos_x: 506072.375
      sim_grid_pos_y: 1934810.25
    }
    terrain_level_point {
      sim_grid_pos_x: 505905.688
      sim_grid_pos_y: 1934883.75
    }
    terrain_level_point {
      sim_grid_pos_x: 505811.844
      sim_grid_pos_y: 1934954
    }
    terrain_level_point {
      sim_grid_pos_x: 505622.125
      sim_grid_pos_y: 1934825.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 506137.906
      sim_grid_pos_y: 1934016
    }
    terrain_level_point {
      sim_grid_pos_x: 506243.188
      sim_grid_pos_y: 1934208.75
    }
    terrain_level_point {
      sim_grid_pos_x: 506329.188
      sim_grid_pos_y: 1934423.5
    }
    terrain_level_point {
      sim_grid_pos_x: 506425.812
      sim_grid_pos_y: 1934736.62
    }
    terrain_level_point {
      sim_grid_pos_x: 506340.031
      sim_grid_pos_y: 1934915.88
    }
    terrain_level_point {
      sim_grid_pos_x: 506113.781
      sim_grid_pos_y: 1934945.62
    }
    terrain_level_point {
      sim_grid_pos_x: 506062.375
      sim_grid_pos_y: 1934837
    }
    terrain_level_point {
      sim_grid_pos_x: 505916.125
      sim_grid_pos_y: 1934901.5
    }
    terrain_level_point {
      sim_grid_pos_x: 505812.438
      sim_grid_pos_y: 1934979.25
    }
    terrain_level_point {
      sim_grid_pos_x: 505622.875
      sim_grid_pos_y: 1934851.25
    }
    terrain_level_point {
      sim_grid_pos_x: 505506.656
      sim_grid_pos_y: 1934940.38
    }
    terrain_level_point {
      sim_grid_pos_x: 505283.594
      sim_grid_pos_y: 1935081.75
    }
    terrain_level_point {
      sim_grid_pos_x: 505238.469
      sim_grid_pos_y: 1934889.38
    }
    terrain_level_point {
      sim_grid_pos_x: 505403.594
      sim_grid_pos_y: 1934612.75
    }
    terrain_level_point {
      sim_grid_pos_x: 505979.75
      sim_grid_pos_y: 1933963.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 506152
      sim_grid_pos_y: 1933999.12
    }
    terrain_level_point {
      sim_grid_pos_x: 506261.75
      sim_grid_pos_y: 1.9342e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 506348.531
      sim_grid_pos_y: 1934416.62
    }
    terrain_level_point {
      sim_grid_pos_x: 506447.781
      sim_grid_pos_y: 1934738.25
    }
    terrain_level_point {
      sim_grid_pos_x: 506353.75
      sim_grid_pos_y: 1934934.75
    }
    terrain_level_point {
      sim_grid_pos_x: 506101.625
      sim_grid_pos_y: 1934968
    }
    terrain_level_point {
      sim_grid_pos_x: 506052.375
      sim_grid_pos_y: 1934863.88
    }
    terrain_level_point {
      sim_grid_pos_x: 505926.531
      sim_grid_pos_y: 1934919.38
    }
    terrain_level_point {
      sim_grid_pos_x: 505813.062
      sim_grid_pos_y: 1935004.38
    }
    terrain_level_point {
      sim_grid_pos_x: 505623.656
      sim_grid_pos_y: 1934876.5
    }
    terrain_level_point {
      sim_grid_pos_x: 505518.406
      sim_grid_pos_y: 1934957.25
    }
    terrain_level_point {
      sim_grid_pos_x: 505270.25
      sim_grid_pos_y: 1935114.5
    }
    terrain_level_point {
      sim_grid_pos_x: 505216.625
      sim_grid_pos_y: 1934886
    }
    terrain_level_point {
      sim_grid_pos_x: 505386.969
      sim_grid_pos_y: 1934600.62
    }
    terrain_level_point {
      sim_grid_pos_x: 505973.344
      sim_grid_pos_y: 1.93394e+06
    }
  }
}
