terrain_level_data {
  terrain_level: 50
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2725851.25
      sim_grid_pos_y: 457186.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2725459.75
      sim_grid_pos_y: 457420.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2725898.25
      sim_grid_pos_y: 458048.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2726257.25
      sim_grid_pos_y: 458610.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2725991.25
      sim_grid_pos_y: 458841.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2726432.5
      sim_grid_pos_y: 459401.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2726887
      sim_grid_pos_y: 458866.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2726272.5
      sim_grid_pos_y: 458068.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2726565.25
      sim_grid_pos_y: 457505.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2725847.75
      sim_grid_pos_y: 457128.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2725386.25
      sim_grid_pos_y: 457404.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2725855.5
      sim_grid_pos_y: 458077.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2726190.25
      sim_grid_pos_y: 458601
    }
    terrain_level_point {
      sim_grid_pos_x: 2725920.75
      sim_grid_pos_y: 458835
    }
    terrain_level_point {
      sim_grid_pos_x: 2726431.25
      sim_grid_pos_y: 459482.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2726953
      sim_grid_pos_y: 458868.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2726333
      sim_grid_pos_y: 458063.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2726635.75
      sim_grid_pos_y: 457480.781
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2725844.25
      sim_grid_pos_y: 457070.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2725312.75
      sim_grid_pos_y: 457389.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2725813
      sim_grid_pos_y: 458105.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2726123.25
      sim_grid_pos_y: 458591.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2725850.25
      sim_grid_pos_y: 458828.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2726429.75
      sim_grid_pos_y: 459563.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2727018.75
      sim_grid_pos_y: 458870
    }
    terrain_level_point {
      sim_grid_pos_x: 2726393.5
      sim_grid_pos_y: 458058.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2726706.25
      sim_grid_pos_y: 457456.156
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2725841
      sim_grid_pos_y: 457012.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2725239.25
      sim_grid_pos_y: 457373.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2725770.25
      sim_grid_pos_y: 458133.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2726056.25
      sim_grid_pos_y: 458581.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2725779.75
      sim_grid_pos_y: 458821.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2726428.25
      sim_grid_pos_y: 459644.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2727084.75
      sim_grid_pos_y: 458871.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2726454
      sim_grid_pos_y: 458052.656
    }
    terrain_level_point {
      sim_grid_pos_x: 2726777
      sim_grid_pos_y: 457431.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2725837.5
      sim_grid_pos_y: 456955.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2725165.75
      sim_grid_pos_y: 457357.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2725727.75
      sim_grid_pos_y: 458162.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2725989.25
      sim_grid_pos_y: 458571.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2725709.25
      sim_grid_pos_y: 458815.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2726426.75
      sim_grid_pos_y: 459725.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2727150.5
      sim_grid_pos_y: 458873.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2726514.75
      sim_grid_pos_y: 458047.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2726847.5
      sim_grid_pos_y: 457406.969
    }
  }
}
