terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2058898.88
      sim_grid_pos_y: 1621954.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2058303.62
      sim_grid_pos_y: 1622434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2057405.12
      sim_grid_pos_y: 1623420.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2057097
      sim_grid_pos_y: 1623290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058056.62
      sim_grid_pos_y: 1619102.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058589.12
      sim_grid_pos_y: 1616812.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058458.75
      sim_grid_pos_y: 1616724.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2058790.25
      sim_grid_pos_y: 1616070.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058799.88
      sim_grid_pos_y: 1615751.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2058957.5
      sim_grid_pos_y: 1615178.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2059246
      sim_grid_pos_y: 1615367.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2059022.62
      sim_grid_pos_y: 1616579
    }
    terrain_level_point {
      sim_grid_pos_x: 2058872.38
      sim_grid_pos_y: 1617304.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2058774.75
      sim_grid_pos_y: 1617451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058772.5
      sim_grid_pos_y: 1617567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058817.75
      sim_grid_pos_y: 1617799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058924.38
      sim_grid_pos_y: 1618014.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2059806.12
      sim_grid_pos_y: 1619943.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2059875.5
      sim_grid_pos_y: 1620175.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2059932
      sim_grid_pos_y: 1620437.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2059953.62
      sim_grid_pos_y: 1620564.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2059985.5
      sim_grid_pos_y: 1620714.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2059968.62
      sim_grid_pos_y: 1621445.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2059929.12
      sim_grid_pos_y: 1621945.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2059313.88
      sim_grid_pos_y: 1615338.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2059083
      sim_grid_pos_y: 1616590.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2058930.25
      sim_grid_pos_y: 1617328.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2058836
      sim_grid_pos_y: 1617470.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2058834.12
      sim_grid_pos_y: 1617562.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2058876.5
      sim_grid_pos_y: 1617779.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2058979.88
      sim_grid_pos_y: 1617988.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2059863.88
      sim_grid_pos_y: 1619921.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2059935.12
      sim_grid_pos_y: 1620160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2059992.38
      sim_grid_pos_y: 1620425.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2060014
      sim_grid_pos_y: 1620552.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2060047.12
      sim_grid_pos_y: 1620708.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.06003e+06
      sim_grid_pos_y: 1621448.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2059986
      sim_grid_pos_y: 1622006.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058920.88
      sim_grid_pos_y: 1622016
    }
    terrain_level_point {
      sim_grid_pos_x: 2058346
      sim_grid_pos_y: 1622479.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2057421.25
      sim_grid_pos_y: 1623494.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2057025.5
      sim_grid_pos_y: 1623327
    }
    terrain_level_point {
      sim_grid_pos_x: 2057996.62
      sim_grid_pos_y: 1619089.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2058519.75
      sim_grid_pos_y: 1.61684e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2058379.5
      sim_grid_pos_y: 1616744.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058729.25
      sim_grid_pos_y: 1616054.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058738.62
      sim_grid_pos_y: 1615742.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2058920.62
      sim_grid_pos_y: 1615080.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2059381.75
      sim_grid_pos_y: 1615309.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2059143.38
      sim_grid_pos_y: 1616602.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2058988
      sim_grid_pos_y: 1617352.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2058897.12
      sim_grid_pos_y: 1617489.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2058895.75
      sim_grid_pos_y: 1617556.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058935.25
      sim_grid_pos_y: 1617759.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2059035.5
      sim_grid_pos_y: 1617961.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2059921.62
      sim_grid_pos_y: 1619900.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2059994.75
      sim_grid_pos_y: 1620144.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2060052.75
      sim_grid_pos_y: 1620413.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2060074.5
      sim_grid_pos_y: 1620541.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2060108.75
      sim_grid_pos_y: 1620703.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2060091.5
      sim_grid_pos_y: 1621451.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2060042.88
      sim_grid_pos_y: 1622068
    }
    terrain_level_point {
      sim_grid_pos_x: 2058942.75
      sim_grid_pos_y: 1622077.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2058388.25
      sim_grid_pos_y: 1622524.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2057437.38
      sim_grid_pos_y: 1623568.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2056954
      sim_grid_pos_y: 1623363.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2057936.75
      sim_grid_pos_y: 1619075.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2058450.25
      sim_grid_pos_y: 1616867.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2058300.12
      sim_grid_pos_y: 1616764.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058668.12
      sim_grid_pos_y: 1616039.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2058677.38
      sim_grid_pos_y: 1615732.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2058883.62
      sim_grid_pos_y: 1614983
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2059449.62
      sim_grid_pos_y: 1615280.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2059203.75
      sim_grid_pos_y: 1616614.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2059045.88
      sim_grid_pos_y: 1617376.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2058958.25
      sim_grid_pos_y: 1617508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2058957.38
      sim_grid_pos_y: 1617551.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2058994.12
      sim_grid_pos_y: 1617739.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2059091
      sim_grid_pos_y: 1617935.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2059979.25
      sim_grid_pos_y: 1619878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2060054.38
      sim_grid_pos_y: 1620129.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2060113.25
      sim_grid_pos_y: 1620402.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2060134.88
      sim_grid_pos_y: 1620529.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2060170.38
      sim_grid_pos_y: 1620697.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2060153
      sim_grid_pos_y: 1621454.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2060099.75
      sim_grid_pos_y: 1622129
    }
    terrain_level_point {
      sim_grid_pos_x: 2058964.62
      sim_grid_pos_y: 1622138.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2058430.5
      sim_grid_pos_y: 1622569
    }
    terrain_level_point {
      sim_grid_pos_x: 2057453.5
      sim_grid_pos_y: 1623641.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2056882.5
      sim_grid_pos_y: 1623400.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2057876.75
      sim_grid_pos_y: 1619061.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2058380.75
      sim_grid_pos_y: 1616894.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2058220.88
      sim_grid_pos_y: 1616785.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2058607.12
      sim_grid_pos_y: 1616023.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2058616.12
      sim_grid_pos_y: 1615723.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2058846.75
      sim_grid_pos_y: 1614885.25
    }
  }
}
