terrain_level_data {
  terrain_level: 554
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3031717.75
      sim_grid_pos_y: 115274.875
    }
    terrain_level_point {
      sim_grid_pos_x: 3030647.75
      sim_grid_pos_y: 112770.086
    }
    terrain_level_point {
      sim_grid_pos_x: 3.02836e+06
      sim_grid_pos_y: 111986.602
    }
    terrain_level_point {
      sim_grid_pos_x: 3028242.5
      sim_grid_pos_y: 111289.047
    }
    terrain_level_point {
      sim_grid_pos_x: 3028907.75
      sim_grid_pos_y: 106252.945
    }
    terrain_level_point {
      sim_grid_pos_x: 3029508.75
      sim_grid_pos_y: 106155.492
    }
    terrain_level_point {
      sim_grid_pos_x: 3032102.5
      sim_grid_pos_y: 106819.984
    }
    terrain_level_point {
      sim_grid_pos_x: 3036414.25
      sim_grid_pos_y: 107908.047
    }
    terrain_level_point {
      sim_grid_pos_x: 3036897.75
      sim_grid_pos_y: 108484
    }
    terrain_level_point {
      sim_grid_pos_x: 3034999.5
      sim_grid_pos_y: 114373.719
    }
    terrain_level_point {
      sim_grid_pos_x: 3033192.5
      sim_grid_pos_y: 115729.242
    }
  }
}
