terrain_level_data {
  terrain_level: 860
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1581241
      sim_grid_pos_y: 1719278.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1581710.75
      sim_grid_pos_y: 1719538.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1581366.5
      sim_grid_pos_y: 1720187.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1580908.25
      sim_grid_pos_y: 1720330.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1580371.25
      sim_grid_pos_y: 1720563.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1579610.38
      sim_grid_pos_y: 1720794.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1579571.88
      sim_grid_pos_y: 1720937.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1579281.62
      sim_grid_pos_y: 1721192.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1579207.62
      sim_grid_pos_y: 1721477.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578925.62
      sim_grid_pos_y: 1721835.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1578715.5
      sim_grid_pos_y: 1721631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1578597.12
      sim_grid_pos_y: 1721956.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578384.25
      sim_grid_pos_y: 1722315.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1578088.12
      sim_grid_pos_y: 1722592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1577953.62
      sim_grid_pos_y: 1722923
    }
    terrain_level_point {
      sim_grid_pos_x: 1577964.38
      sim_grid_pos_y: 1723186.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1577876
      sim_grid_pos_y: 1723563.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578222.25
      sim_grid_pos_y: 1723780.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1578083.75
      sim_grid_pos_y: 1724033.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577912.12
      sim_grid_pos_y: 1724222.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1578161.88
      sim_grid_pos_y: 1724379.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1578040.62
      sim_grid_pos_y: 1724587.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577905.25
      sim_grid_pos_y: 1724369.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577783.75
      sim_grid_pos_y: 1724436.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577771.5
      sim_grid_pos_y: 1724557.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577535.25
      sim_grid_pos_y: 1724891.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577241.25
      sim_grid_pos_y: 1724854.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1576928.12
      sim_grid_pos_y: 1725145.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576879.38
      sim_grid_pos_y: 1725273.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1576875.62
      sim_grid_pos_y: 1725386.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1576512.25
      sim_grid_pos_y: 1725539.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576180.5
      sim_grid_pos_y: 1725837.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576020.88
      sim_grid_pos_y: 1726170.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575843.75
      sim_grid_pos_y: 1726378
    }
    terrain_level_point {
      sim_grid_pos_x: 1575696.12
      sim_grid_pos_y: 1726478.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575525.38
      sim_grid_pos_y: 1726469
    }
    terrain_level_point {
      sim_grid_pos_x: 1575394.25
      sim_grid_pos_y: 1726627.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575231.62
      sim_grid_pos_y: 1726647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1574712.12
      sim_grid_pos_y: 1726843.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1574678.12
      sim_grid_pos_y: 1726931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1574903.88
      sim_grid_pos_y: 1727073.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1575106
      sim_grid_pos_y: 1727155.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575175
      sim_grid_pos_y: 1727172.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575800.12
      sim_grid_pos_y: 1727378.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576573.12
      sim_grid_pos_y: 1727442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576896.12
      sim_grid_pos_y: 1727529.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577219.12
      sim_grid_pos_y: 1727557
    }
    terrain_level_point {
      sim_grid_pos_x: 1577572.38
      sim_grid_pos_y: 1727834.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577650.5
      sim_grid_pos_y: 1728164.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577539.62
      sim_grid_pos_y: 1728638.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577141.88
      sim_grid_pos_y: 1728475.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576668.12
      sim_grid_pos_y: 1728524.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576330.62
      sim_grid_pos_y: 1728548.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576110.5
      sim_grid_pos_y: 1728338.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576167.5
      sim_grid_pos_y: 1728119.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576080.12
      sim_grid_pos_y: 1728014.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575836.75
      sim_grid_pos_y: 1727935.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575733.25
      sim_grid_pos_y: 1728045
    }
    terrain_level_point {
      sim_grid_pos_x: 1575246.12
      sim_grid_pos_y: 1727900.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575048
      sim_grid_pos_y: 1727854.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1574817.25
      sim_grid_pos_y: 1727923
    }
    terrain_level_point {
      sim_grid_pos_x: 1574697.5
      sim_grid_pos_y: 1727861.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1574619.5
      sim_grid_pos_y: 1727604.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1574199.25
      sim_grid_pos_y: 1727250.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1573667.88
      sim_grid_pos_y: 1727194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1573179.75
      sim_grid_pos_y: 1727187.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1573009.88
      sim_grid_pos_y: 1727289
    }
    terrain_level_point {
      sim_grid_pos_x: 1572461.12
      sim_grid_pos_y: 1727008.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1572688.75
      sim_grid_pos_y: 1726673.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1572698.62
      sim_grid_pos_y: 1726526.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1572233
      sim_grid_pos_y: 1726198.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1572391.5
      sim_grid_pos_y: 1725937.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1572756
      sim_grid_pos_y: 1726107.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1573104.5
      sim_grid_pos_y: 1726214
    }
    terrain_level_point {
      sim_grid_pos_x: 1573318.62
      sim_grid_pos_y: 1726194.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1573662.12
      sim_grid_pos_y: 1726290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1574215.38
      sim_grid_pos_y: 1726134.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1574807.12
      sim_grid_pos_y: 1725663.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575274.38
      sim_grid_pos_y: 1725151.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575827.88
      sim_grid_pos_y: 1724689.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575799
      sim_grid_pos_y: 1724562.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576083.38
      sim_grid_pos_y: 1724188
    }
    terrain_level_point {
      sim_grid_pos_x: 1576321.38
      sim_grid_pos_y: 1724281.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1576806.25
      sim_grid_pos_y: 1723860.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576949.75
      sim_grid_pos_y: 1723687.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577243.38
      sim_grid_pos_y: 1722980.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577447.12
      sim_grid_pos_y: 1.72239e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1577750.25
      sim_grid_pos_y: 1721854.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578235.5
      sim_grid_pos_y: 1721307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1578239.25
      sim_grid_pos_y: 1721021
    }
    terrain_level_point {
      sim_grid_pos_x: 1578258.62
      sim_grid_pos_y: 1720893.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578363
      sim_grid_pos_y: 1720768.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1579092.5
      sim_grid_pos_y: 1720536.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1581752.12
      sim_grid_pos_y: 1719526.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1581387.75
      sim_grid_pos_y: 1720212.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1580919
      sim_grid_pos_y: 1720359.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1580381.88
      sim_grid_pos_y: 1720592.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579635.62
      sim_grid_pos_y: 1720818.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579599.12
      sim_grid_pos_y: 1720954.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1579309
      sim_grid_pos_y: 1721209.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579235.75
      sim_grid_pos_y: 1721491.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578928.75
      sim_grid_pos_y: 1721881.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578728.12
      sim_grid_pos_y: 1721686.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578625
      sim_grid_pos_y: 1721969.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1578408.5
      sim_grid_pos_y: 1722335.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578114.12
      sim_grid_pos_y: 1722610.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577984.62
      sim_grid_pos_y: 1722928.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577995.25
      sim_grid_pos_y: 1723189.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577911
      sim_grid_pos_y: 1723549
    }
    terrain_level_point {
      sim_grid_pos_x: 1578263.12
      sim_grid_pos_y: 1723769.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578109
      sim_grid_pos_y: 1724051.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577959.62
      sim_grid_pos_y: 1724216.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578203.5
      sim_grid_pos_y: 1724369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1578041.38
      sim_grid_pos_y: 1724647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577894.5
      sim_grid_pos_y: 1724410.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577812.75
      sim_grid_pos_y: 1724455.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577801.25
      sim_grid_pos_y: 1724568.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577549.75
      sim_grid_pos_y: 1724924.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577251.62
      sim_grid_pos_y: 1724886.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1576954.38
      sim_grid_pos_y: 1725162.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.57691e+06
      sim_grid_pos_y: 1725279.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576905.75
      sim_grid_pos_y: 1725407.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576528.88
      sim_grid_pos_y: 1725565.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576205.62
      sim_grid_pos_y: 1725855.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576046.88
      sim_grid_pos_y: 1726187
    }
    terrain_level_point {
      sim_grid_pos_x: 1575864.5
      sim_grid_pos_y: 1726401.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575704.88
      sim_grid_pos_y: 1726509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575539.25
      sim_grid_pos_y: 1726500.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575410.12
      sim_grid_pos_y: 1726656.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575239
      sim_grid_pos_y: 1726677.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1574735.88
      sim_grid_pos_y: 1726867
    }
    terrain_level_point {
      sim_grid_pos_x: 1574715.88
      sim_grid_pos_y: 1726919
    }
    terrain_level_point {
      sim_grid_pos_x: 1574918
      sim_grid_pos_y: 1727046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575115.62
      sim_grid_pos_y: 1727126.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575183.5
      sim_grid_pos_y: 1727143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575806.25
      sim_grid_pos_y: 1727348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576578.5
      sim_grid_pos_y: 1727412.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576901.5
      sim_grid_pos_y: 1727499.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577230.88
      sim_grid_pos_y: 1727527.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577599.88
      sim_grid_pos_y: 1727816.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577682.12
      sim_grid_pos_y: 1728164.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577561.38
      sim_grid_pos_y: 1728680.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1577137.38
      sim_grid_pos_y: 1728506.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576670.88
      sim_grid_pos_y: 1728555.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576319.25
      sim_grid_pos_y: 1728580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576076.12
      sim_grid_pos_y: 1728348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1576133.75
      sim_grid_pos_y: 1728127.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576062.12
      sim_grid_pos_y: 1728041.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575845.75
      sim_grid_pos_y: 1727970.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575742.62
      sim_grid_pos_y: 1728079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575238.38
      sim_grid_pos_y: 1727929.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575049
      sim_grid_pos_y: 1727886.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574814.12
      sim_grid_pos_y: 1727956
    }
    terrain_level_point {
      sim_grid_pos_x: 1574671.88
      sim_grid_pos_y: 1727883.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1574592.75
      sim_grid_pos_y: 1727622
    }
    terrain_level_point {
      sim_grid_pos_x: 1574186.62
      sim_grid_pos_y: 1727279.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1573666.12
      sim_grid_pos_y: 1727225
    }
    terrain_level_point {
      sim_grid_pos_x: 1573188
      sim_grid_pos_y: 1727218.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1573011
      sim_grid_pos_y: 1727324.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1572416.12
      sim_grid_pos_y: 1727020.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1572658.62
      sim_grid_pos_y: 1726663.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1572666.75
      sim_grid_pos_y: 1726541.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1572191.75
      sim_grid_pos_y: 1726207.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1572379.5
      sim_grid_pos_y: 1725897.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1572767
      sim_grid_pos_y: 1726078.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1573107.75
      sim_grid_pos_y: 1726182.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1573321.5
      sim_grid_pos_y: 1726163.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1573662.12
      sim_grid_pos_y: 1726258.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1574201
      sim_grid_pos_y: 1726106.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574786
      sim_grid_pos_y: 1725640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1575253
      sim_grid_pos_y: 1725129.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575793.75
      sim_grid_pos_y: 1724677.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575765.88
      sim_grid_pos_y: 1724555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576073
      sim_grid_pos_y: 1724150.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576315.25
      sim_grid_pos_y: 1724246.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576784.12
      sim_grid_pos_y: 1723838.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576923.12
      sim_grid_pos_y: 1723671
    }
    terrain_level_point {
      sim_grid_pos_x: 1577214.62
      sim_grid_pos_y: 1722969.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577419
      sim_grid_pos_y: 1722377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577725.12
      sim_grid_pos_y: 1721836.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578204.88
      sim_grid_pos_y: 1721295.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1578208.5
      sim_grid_pos_y: 1721018.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1578229.5
      sim_grid_pos_y: 1720880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1578345.12
      sim_grid_pos_y: 1720742.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1579079.88
      sim_grid_pos_y: 1720508.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1581240.62
      sim_grid_pos_y: 1719242.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1581793.38
      sim_grid_pos_y: 1719513.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1581409
      sim_grid_pos_y: 1720238.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1580929.75
      sim_grid_pos_y: 1720388
    }
    terrain_level_point {
      sim_grid_pos_x: 1580392.5
      sim_grid_pos_y: 1720621.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579661
      sim_grid_pos_y: 1720843.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1579626.5
      sim_grid_pos_y: 1720971.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579336.38
      sim_grid_pos_y: 1721226.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1579263.88
      sim_grid_pos_y: 1721505.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578931.75
      sim_grid_pos_y: 1721927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1578740.75
      sim_grid_pos_y: 1721741.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1578653
      sim_grid_pos_y: 1721983
    }
    terrain_level_point {
      sim_grid_pos_x: 1578432.62
      sim_grid_pos_y: 1722354.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.57814e+06
      sim_grid_pos_y: 1722628.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578015.62
      sim_grid_pos_y: 1722933.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1578026.25
      sim_grid_pos_y: 1723192.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577945.88
      sim_grid_pos_y: 1723534.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578304
      sim_grid_pos_y: 1723758.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1578134.25
      sim_grid_pos_y: 1724069.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578007
      sim_grid_pos_y: 1724209.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1578245
      sim_grid_pos_y: 1724359.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578042.25
      sim_grid_pos_y: 1724707
    }
    terrain_level_point {
      sim_grid_pos_x: 1577883.75
      sim_grid_pos_y: 1724451.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577841.75
      sim_grid_pos_y: 1724474.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577831.12
      sim_grid_pos_y: 1.72458e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1577564.12
      sim_grid_pos_y: 1724957.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577262
      sim_grid_pos_y: 1724919
    }
    terrain_level_point {
      sim_grid_pos_x: 1576980.5
      sim_grid_pos_y: 1725180.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576940.5
      sim_grid_pos_y: 1725286
    }
    terrain_level_point {
      sim_grid_pos_x: 1576935.75
      sim_grid_pos_y: 1725428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576545.62
      sim_grid_pos_y: 1725591.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576230.75
      sim_grid_pos_y: 1725874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1576072.88
      sim_grid_pos_y: 1726203.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575885.12
      sim_grid_pos_y: 1726424.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575713.5
      sim_grid_pos_y: 1726540.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1575553
      sim_grid_pos_y: 1726532.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575426
      sim_grid_pos_y: 1726685.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575246.38
      sim_grid_pos_y: 1726707.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1574759.62
      sim_grid_pos_y: 1726891
    }
    terrain_level_point {
      sim_grid_pos_x: 1574753.75
      sim_grid_pos_y: 1726906.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1574932.12
      sim_grid_pos_y: 1727018.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575125
      sim_grid_pos_y: 1727097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575192
      sim_grid_pos_y: 1727113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1575812.5
      sim_grid_pos_y: 1727318.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576583.75
      sim_grid_pos_y: 1727381.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576906.88
      sim_grid_pos_y: 1727468.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577242.62
      sim_grid_pos_y: 1727497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577627.25
      sim_grid_pos_y: 1727799.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577713.75
      sim_grid_pos_y: 1728164.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577583.12
      sim_grid_pos_y: 1728723
    }
    terrain_level_point {
      sim_grid_pos_x: 1577132.88
      sim_grid_pos_y: 1728538
    }
    terrain_level_point {
      sim_grid_pos_x: 1576673.5
      sim_grid_pos_y: 1728585.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576307.88
      sim_grid_pos_y: 1728612.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576041.88
      sim_grid_pos_y: 1728358.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.5761e+06
      sim_grid_pos_y: 1728134.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576044.25
      sim_grid_pos_y: 1728067.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575854.75
      sim_grid_pos_y: 1728005.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575752
      sim_grid_pos_y: 1728114.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1575230.5
      sim_grid_pos_y: 1727959.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.57505e+06
      sim_grid_pos_y: 1727918.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1574811.12
      sim_grid_pos_y: 1727989
    }
    terrain_level_point {
      sim_grid_pos_x: 1574646.25
      sim_grid_pos_y: 1727904.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574565.88
      sim_grid_pos_y: 1727639.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574174
      sim_grid_pos_y: 1727309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1573664.25
      sim_grid_pos_y: 1727255.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1573196.25
      sim_grid_pos_y: 1727249.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1573012.12
      sim_grid_pos_y: 1727359.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1572371.12
      sim_grid_pos_y: 1727031.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1572628.5
      sim_grid_pos_y: 1726652.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1572634.88
      sim_grid_pos_y: 1726556.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1572150.62
      sim_grid_pos_y: 1726215.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1572367.5
      sim_grid_pos_y: 1725858
    }
    terrain_level_point {
      sim_grid_pos_x: 1572778.12
      sim_grid_pos_y: 1726049.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1573111
      sim_grid_pos_y: 1726151.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1573324.38
      sim_grid_pos_y: 1726132.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1573662
      sim_grid_pos_y: 1726226.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574186.75
      sim_grid_pos_y: 1726078.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574765
      sim_grid_pos_y: 1725618.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575231.75
      sim_grid_pos_y: 1725106.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575759.5
      sim_grid_pos_y: 1724666.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1575732.62
      sim_grid_pos_y: 1724548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576062.5
      sim_grid_pos_y: 1724113.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1576309.12
      sim_grid_pos_y: 1724210.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576762.12
      sim_grid_pos_y: 1723817
    }
    terrain_level_point {
      sim_grid_pos_x: 1576896.5
      sim_grid_pos_y: 1723655
    }
    terrain_level_point {
      sim_grid_pos_x: 1577185.88
      sim_grid_pos_y: 1722958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577390.75
      sim_grid_pos_y: 1722364.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577699.88
      sim_grid_pos_y: 1721818.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578174.25
      sim_grid_pos_y: 1721284
    }
    terrain_level_point {
      sim_grid_pos_x: 1578177.75
      sim_grid_pos_y: 1721016
    }
    terrain_level_point {
      sim_grid_pos_x: 1578200.38
      sim_grid_pos_y: 1720867.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578327.25
      sim_grid_pos_y: 1720715.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1579067.25
      sim_grid_pos_y: 1720480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1581240.12
      sim_grid_pos_y: 1719207.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1581834.75
      sim_grid_pos_y: 1719501.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1581430.25
      sim_grid_pos_y: 1720263.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1580940.5
      sim_grid_pos_y: 1720416.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1580403.12
      sim_grid_pos_y: 1720650.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1579686.25
      sim_grid_pos_y: 1720867.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579653.75
      sim_grid_pos_y: 1720988.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1579363.75
      sim_grid_pos_y: 1721243.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1579292.12
      sim_grid_pos_y: 1721519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578934.75
      sim_grid_pos_y: 1721973
    }
    terrain_level_point {
      sim_grid_pos_x: 1578753.5
      sim_grid_pos_y: 1721797
    }
    terrain_level_point {
      sim_grid_pos_x: 1578680.88
      sim_grid_pos_y: 1721996.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578456.88
      sim_grid_pos_y: 1722374.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1578166
      sim_grid_pos_y: 1722646.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1578046.62
      sim_grid_pos_y: 1722939.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578057.12
      sim_grid_pos_y: 1723195.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577980.88
      sim_grid_pos_y: 1723520.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578344.88
      sim_grid_pos_y: 1723748
    }
    terrain_level_point {
      sim_grid_pos_x: 1578159.5
      sim_grid_pos_y: 1724087.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578054.5
      sim_grid_pos_y: 1724203.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578286.62
      sim_grid_pos_y: 1724349.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1578043
      sim_grid_pos_y: 1724766.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577873
      sim_grid_pos_y: 1724492.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1577870.75
      sim_grid_pos_y: 1724493.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1577860.88
      sim_grid_pos_y: 1724591.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577578.62
      sim_grid_pos_y: 1724990.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577272.38
      sim_grid_pos_y: 1724951.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577006.75
      sim_grid_pos_y: 1725198.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576971.12
      sim_grid_pos_y: 1725292.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576965.88
      sim_grid_pos_y: 1725449
    }
    terrain_level_point {
      sim_grid_pos_x: 1576562.25
      sim_grid_pos_y: 1725618.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576255.75
      sim_grid_pos_y: 1725893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576098.88
      sim_grid_pos_y: 1726220.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575905.88
      sim_grid_pos_y: 1726447.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575722.25
      sim_grid_pos_y: 1726572.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575566.75
      sim_grid_pos_y: 1726563.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1575441.88
      sim_grid_pos_y: 1726714.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575253.75
      sim_grid_pos_y: 1726737.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1574809.25
      sim_grid_pos_y: 1726905.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1574946.12
      sim_grid_pos_y: 1726991.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575134.62
      sim_grid_pos_y: 1727067.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1575200.5
      sim_grid_pos_y: 1727084.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575818.62
      sim_grid_pos_y: 1727287.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1576589.12
      sim_grid_pos_y: 1727351.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576912.12
      sim_grid_pos_y: 1727438.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1577254.38
      sim_grid_pos_y: 1727467.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1577654.75
      sim_grid_pos_y: 1727781.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1577745.25
      sim_grid_pos_y: 1728164.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577604.88
      sim_grid_pos_y: 1728765.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1577128.38
      sim_grid_pos_y: 1728569.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1576676.25
      sim_grid_pos_y: 1728616.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576296.5
      sim_grid_pos_y: 1728643.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576007.5
      sim_grid_pos_y: 1728367.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1576066.25
      sim_grid_pos_y: 1728142.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1576026.25
      sim_grid_pos_y: 1728094.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1575863.75
      sim_grid_pos_y: 1728041.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1575761.38
      sim_grid_pos_y: 1728149.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1575222.88
      sim_grid_pos_y: 1727989.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575051
      sim_grid_pos_y: 1727950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1574808
      sim_grid_pos_y: 1728021.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1574620.62
      sim_grid_pos_y: 1727926
    }
    terrain_level_point {
      sim_grid_pos_x: 1574539.12
      sim_grid_pos_y: 1727657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1574161.5
      sim_grid_pos_y: 1727339
    }
    terrain_level_point {
      sim_grid_pos_x: 1573662.38
      sim_grid_pos_y: 1727286.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1573204.62
      sim_grid_pos_y: 1727280.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1573013.25
      sim_grid_pos_y: 1727394.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1572326
      sim_grid_pos_y: 1727043.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1572598.38
      sim_grid_pos_y: 1726642.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1572603.12
      sim_grid_pos_y: 1726572
    }
    terrain_level_point {
      sim_grid_pos_x: 1572109.38
      sim_grid_pos_y: 1726224.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1572355.5
      sim_grid_pos_y: 1725818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1572789.12
      sim_grid_pos_y: 1726020.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1573114.25
      sim_grid_pos_y: 1726120.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1573327.12
      sim_grid_pos_y: 1726101.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1573662
      sim_grid_pos_y: 1726194.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1574172.5
      sim_grid_pos_y: 1726050.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1574743.88
      sim_grid_pos_y: 1725595.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1575210.5
      sim_grid_pos_y: 1725084.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1575725.38
      sim_grid_pos_y: 1724654.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1575699.5
      sim_grid_pos_y: 1724541.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1576052.12
      sim_grid_pos_y: 1724076.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1576303.12
      sim_grid_pos_y: 1724175.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.57674e+06
      sim_grid_pos_y: 1723795.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1576869.88
      sim_grid_pos_y: 1723638.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577157.12
      sim_grid_pos_y: 1722947.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577362.62
      sim_grid_pos_y: 1722351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1577674.75
      sim_grid_pos_y: 1721800.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1578143.62
      sim_grid_pos_y: 1721272.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578147.12
      sim_grid_pos_y: 1721013.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1578171.25
      sim_grid_pos_y: 1720854.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1578309.5
      sim_grid_pos_y: 1720689.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1579054.75
      sim_grid_pos_y: 1720451.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1581239.75
      sim_grid_pos_y: 1719171.88
    }
  }
}
