terrain_level_data {
  terrain_level: 675
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2853504
      sim_grid_pos_y: 2281991.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853359.5
      sim_grid_pos_y: 2281729
    }
    terrain_level_point {
      sim_grid_pos_x: 2853495.25
      sim_grid_pos_y: 2281438.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853266.5
      sim_grid_pos_y: 2281361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853128
      sim_grid_pos_y: 2281507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852981.75
      sim_grid_pos_y: 2281548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852948
      sim_grid_pos_y: 2281398.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852681
      sim_grid_pos_y: 2281596.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852437.75
      sim_grid_pos_y: 2281510.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852306.25
      sim_grid_pos_y: 2281235.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852143.5
      sim_grid_pos_y: 2281070.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2851900.25
      sim_grid_pos_y: 2281084.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852042.5
      sim_grid_pos_y: 2281272.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852064
      sim_grid_pos_y: 2281505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852175.75
      sim_grid_pos_y: 2281669.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852455.25
      sim_grid_pos_y: 2281672.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.85274e+06
      sim_grid_pos_y: 2281734.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852775
      sim_grid_pos_y: 2.28184e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2853105.5
      sim_grid_pos_y: 2281872.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853300.25
      sim_grid_pos_y: 2282028.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2852184
      sim_grid_pos_y: 2280965.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2851833
      sim_grid_pos_y: 2280985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2851781.5
      sim_grid_pos_y: 2281097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2851943
      sim_grid_pos_y: 2281311
    }
    terrain_level_point {
      sim_grid_pos_x: 2851964.25
      sim_grid_pos_y: 2281541
    }
    terrain_level_point {
      sim_grid_pos_x: 2852121
      sim_grid_pos_y: 2281771.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852443.75
      sim_grid_pos_y: 2281775
    }
    terrain_level_point {
      sim_grid_pos_x: 2852661
      sim_grid_pos_y: 2281822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852698.75
      sim_grid_pos_y: 2281935.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853065
      sim_grid_pos_y: 2281971.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853272.5
      sim_grid_pos_y: 2282138
    }
    terrain_level_point {
      sim_grid_pos_x: 2853662.5
      sim_grid_pos_y: 2282067.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2853474.5
      sim_grid_pos_y: 2281725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2853547
      sim_grid_pos_y: 2281431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853237.25
      sim_grid_pos_y: 2281243.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853073
      sim_grid_pos_y: 2281416.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2853058
      sim_grid_pos_y: 2281420.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853013.5
      sim_grid_pos_y: 2281222.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852663.75
      sim_grid_pos_y: 2281481.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852512
      sim_grid_pos_y: 2281428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852391.25
      sim_grid_pos_y: 2281175.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2852224.25
      sim_grid_pos_y: 2.28086e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2851765.5
      sim_grid_pos_y: 2280887
    }
    terrain_level_point {
      sim_grid_pos_x: 2851662.5
      sim_grid_pos_y: 2281110.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2851843.75
      sim_grid_pos_y: 2281349.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2851864.75
      sim_grid_pos_y: 2281576.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852066.5
      sim_grid_pos_y: 2281873.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852432
      sim_grid_pos_y: 2281877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852582.25
      sim_grid_pos_y: 2281910.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852622.5
      sim_grid_pos_y: 2282031
    }
    terrain_level_point {
      sim_grid_pos_x: 2853024.75
      sim_grid_pos_y: 2282070.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853244.75
      sim_grid_pos_y: 2282247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2853821
      sim_grid_pos_y: 2282142.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853589.5
      sim_grid_pos_y: 2281721.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853607.75
      sim_grid_pos_y: 2281416.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853208
      sim_grid_pos_y: 2281125.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853118
      sim_grid_pos_y: 2281220.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2853079
      sim_grid_pos_y: 2281047
    }
    terrain_level_point {
      sim_grid_pos_x: 2852646.5
      sim_grid_pos_y: 2281366.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852586
      sim_grid_pos_y: 2281345.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852476.5
      sim_grid_pos_y: 2281116
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2852264.75
      sim_grid_pos_y: 2280755
    }
    terrain_level_point {
      sim_grid_pos_x: 2851698.25
      sim_grid_pos_y: 2280788.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2851543.75
      sim_grid_pos_y: 2281123
    }
    terrain_level_point {
      sim_grid_pos_x: 2851744.25
      sim_grid_pos_y: 2281388.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2851765
      sim_grid_pos_y: 2281612.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852011.75
      sim_grid_pos_y: 2281975.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852420.5
      sim_grid_pos_y: 2281979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852503.25
      sim_grid_pos_y: 2281997.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2852546.25
      sim_grid_pos_y: 2282126.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852984.25
      sim_grid_pos_y: 2282169.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853217.25
      sim_grid_pos_y: 2282356.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853979.5
      sim_grid_pos_y: 2282218
    }
    terrain_level_point {
      sim_grid_pos_x: 2853704.25
      sim_grid_pos_y: 2281717.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853691.5
      sim_grid_pos_y: 2281377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853178.75
      sim_grid_pos_y: 2281007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853175.75
      sim_grid_pos_y: 2281010.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853144.25
      sim_grid_pos_y: 2280871
    }
    terrain_level_point {
      sim_grid_pos_x: 2852648.25
      sim_grid_pos_y: 2281238
    }
    terrain_level_point {
      sim_grid_pos_x: 2852561.5
      sim_grid_pos_y: 2281056.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2852305.25
      sim_grid_pos_y: 2.28065e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2851630.75
      sim_grid_pos_y: 2280689.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2851425
      sim_grid_pos_y: 2281136
    }
    terrain_level_point {
      sim_grid_pos_x: 2851645
      sim_grid_pos_y: 2281426.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2851665.25
      sim_grid_pos_y: 2281648.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2851957.25
      sim_grid_pos_y: 2282077.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2852408.75
      sim_grid_pos_y: 2282082
    }
    terrain_level_point {
      sim_grid_pos_x: 2852424.5
      sim_grid_pos_y: 2282085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852469.75
      sim_grid_pos_y: 2282222
    }
    terrain_level_point {
      sim_grid_pos_x: 2852944
      sim_grid_pos_y: 2282268.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853189.5
      sim_grid_pos_y: 2282465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2854138
      sim_grid_pos_y: 2282293.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853819.25
      sim_grid_pos_y: 2281714
    }
    terrain_level_point {
      sim_grid_pos_x: 2853791.75
      sim_grid_pos_y: 2281323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853262.25
      sim_grid_pos_y: 2280927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853209.75
      sim_grid_pos_y: 2280695
    }
    terrain_level_point {
      sim_grid_pos_x: 2852687.25
      sim_grid_pos_y: 2281081.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2852646.75
      sim_grid_pos_y: 2280996.75
    }
  }
}
terrain_level_data {
  terrain_level: 425
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2854199.75
      sim_grid_pos_y: 2280709
    }
    terrain_level_point {
      sim_grid_pos_x: 2853941.5
      sim_grid_pos_y: 2280856.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2854023.5
      sim_grid_pos_y: 2281447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2854295.75
      sim_grid_pos_y: 2281319.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2854231
      sim_grid_pos_y: 2280644
    }
    terrain_level_point {
      sim_grid_pos_x: 2.85392e+06
      sim_grid_pos_y: 2280834.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2854006.25
      sim_grid_pos_y: 2281462.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2854341
      sim_grid_pos_y: 2281343.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2854262.25
      sim_grid_pos_y: 2280578.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853898.5
      sim_grid_pos_y: 2280821
    }
    terrain_level_point {
      sim_grid_pos_x: 2853991.75
      sim_grid_pos_y: 2281506.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2854386.5
      sim_grid_pos_y: 2281367.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2854293.5
      sim_grid_pos_y: 2280513.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853874
      sim_grid_pos_y: 2280808.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2853960.5
      sim_grid_pos_y: 2281555.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2854431.75
      sim_grid_pos_y: 2281391.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2854324.75
      sim_grid_pos_y: 2280448.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853849.25
      sim_grid_pos_y: 2280803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2853944.75
      sim_grid_pos_y: 2281588.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2854477
      sim_grid_pos_y: 2281415.5
    }
  }
}
