terrain_level_data {
  terrain_level: 480
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1536878.62
      sim_grid_pos_y: 1089583.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1537140.88
      sim_grid_pos_y: 1090141.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1537343.38
      sim_grid_pos_y: 1090497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1537560.5
      sim_grid_pos_y: 1090240.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1537970.75
      sim_grid_pos_y: 1090389
    }
    terrain_level_point {
      sim_grid_pos_x: 1538014.62
      sim_grid_pos_y: 1090798.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1538180.38
      sim_grid_pos_y: 1090801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1538198.5
      sim_grid_pos_y: 1090463
    }
    terrain_level_point {
      sim_grid_pos_x: 1538353.88
      sim_grid_pos_y: 1090332.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538408.5
      sim_grid_pos_y: 1089971.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.53822e+06
      sim_grid_pos_y: 1089698.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1536828.38
      sim_grid_pos_y: 1089476.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1536760.62
      sim_grid_pos_y: 1089573.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1537049.75
      sim_grid_pos_y: 1090188.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537326.88
      sim_grid_pos_y: 1090675.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1537592.75
      sim_grid_pos_y: 1090361.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1537875.62
      sim_grid_pos_y: 1090463.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1537922.38
      sim_grid_pos_y: 1090899.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1538277.5
      sim_grid_pos_y: 1090905.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1538298.5
      sim_grid_pos_y: 1090512.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1538449.5
      sim_grid_pos_y: 1090386
    }
    terrain_level_point {
      sim_grid_pos_x: 1538516
      sim_grid_pos_y: 1089946.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538276.88
      sim_grid_pos_y: 1089600.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1536778.12
      sim_grid_pos_y: 1089369.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1536642.62
      sim_grid_pos_y: 1089563.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1536958.75
      sim_grid_pos_y: 1090236.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1537310.38
      sim_grid_pos_y: 1090853.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1537624.88
      sim_grid_pos_y: 1090481.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1537780.5
      sim_grid_pos_y: 1090538.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.53783e+06
      sim_grid_pos_y: 1091000.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1538374.5
      sim_grid_pos_y: 1091010.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1538398.5
      sim_grid_pos_y: 1090562.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1538545
      sim_grid_pos_y: 1090439.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1538623.38
      sim_grid_pos_y: 1089921.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1538333.75
      sim_grid_pos_y: 1089502.62
    }
  }
}
