terrain_level_data {
  terrain_level: 42
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1030382.38
      sim_grid_pos_y: 1387525.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1027070.56
      sim_grid_pos_y: 1387512
    }
    terrain_level_point {
      sim_grid_pos_x: 1027141.12
      sim_grid_pos_y: 1388810.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1026363.25
      sim_grid_pos_y: 1388662.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1025119.94
      sim_grid_pos_y: 1387370.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1023615.94
      sim_grid_pos_y: 1386447.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1021599.75
      sim_grid_pos_y: 1385044.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1020855
      sim_grid_pos_y: 1384060.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1020521.25
      sim_grid_pos_y: 1382807.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1021001.06
      sim_grid_pos_y: 1381097.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1020983.12
      sim_grid_pos_y: 1380437.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1021688.62
      sim_grid_pos_y: 1378782.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1022838.06
      sim_grid_pos_y: 1378127.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1025529.88
      sim_grid_pos_y: 1376922.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1027871.5
      sim_grid_pos_y: 1376961.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1030877.5
      sim_grid_pos_y: 1378798
    }
    terrain_level_point {
      sim_grid_pos_x: 1029892.88
      sim_grid_pos_y: 1380623.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1031654.94
      sim_grid_pos_y: 1381132.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1034216.62
      sim_grid_pos_y: 1383144.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1032933.25
      sim_grid_pos_y: 1385900.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1027886.31
      sim_grid_pos_y: 1376910.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1030945.69
      sim_grid_pos_y: 1378779.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1029968.19
      sim_grid_pos_y: 1380591.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1031678.75
      sim_grid_pos_y: 1381085.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1034280.25
      sim_grid_pos_y: 1383129.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1032973.44
      sim_grid_pos_y: 1385935.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1030397.25
      sim_grid_pos_y: 1387576.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1027124.69
      sim_grid_pos_y: 1387563.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1027195.88
      sim_grid_pos_y: 1388872.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1026337.62
      sim_grid_pos_y: 1388709.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1025087.56
      sim_grid_pos_y: 1387410.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1023587.88
      sim_grid_pos_y: 1386490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1021563.75
      sim_grid_pos_y: 1385081.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1020808.06
      sim_grid_pos_y: 1384083
    }
    terrain_level_point {
      sim_grid_pos_x: 1020468.12
      sim_grid_pos_y: 1382806.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1020949.62
      sim_grid_pos_y: 1381091.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1020931.56
      sim_grid_pos_y: 1380427.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1021648.25
      sim_grid_pos_y: 1378746.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1022814.88
      sim_grid_pos_y: 1378081.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1025519.31
      sim_grid_pos_y: 1376871.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1027901.12
      sim_grid_pos_y: 1376859.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1031013.88
      sim_grid_pos_y: 1378761.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1030043.44
      sim_grid_pos_y: 1.38056e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1031702.56
      sim_grid_pos_y: 1381039.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1034343.88
      sim_grid_pos_y: 1383114.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1033013.56
      sim_grid_pos_y: 1385970.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1030412.06
      sim_grid_pos_y: 1387627.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1027178.81
      sim_grid_pos_y: 1387615
    }
    terrain_level_point {
      sim_grid_pos_x: 1027250.62
      sim_grid_pos_y: 1388935.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1026312
      sim_grid_pos_y: 1388756.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1025055.19
      sim_grid_pos_y: 1387450.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1023559.81
      sim_grid_pos_y: 1386533.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1021527.81
      sim_grid_pos_y: 1385119
    }
    terrain_level_point {
      sim_grid_pos_x: 1020761.12
      sim_grid_pos_y: 1384106
    }
    terrain_level_point {
      sim_grid_pos_x: 1020414.94
      sim_grid_pos_y: 1382806.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1020898.12
      sim_grid_pos_y: 1381084.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.02088e+06
      sim_grid_pos_y: 1380417.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1021607.88
      sim_grid_pos_y: 1378710.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1022791.62
      sim_grid_pos_y: 1378036.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1025508.81
      sim_grid_pos_y: 1376819.88
    }
  }
}
