terrain_level_data {
  terrain_level: 560
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1446444.25
      sim_grid_pos_y: 1541303.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1446455.5
      sim_grid_pos_y: 1541636.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1446798.5
      sim_grid_pos_y: 1541590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1447049.12
      sim_grid_pos_y: 1541783.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1447320.88
      sim_grid_pos_y: 1541711.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1447540.38
      sim_grid_pos_y: 1541885.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1447692.75
      sim_grid_pos_y: 1541878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1447827.62
      sim_grid_pos_y: 1541669
    }
    terrain_level_point {
      sim_grid_pos_x: 1447945
      sim_grid_pos_y: 1541599.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1447858.25
      sim_grid_pos_y: 1541494.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1447269.38
      sim_grid_pos_y: 1541329.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1446799.88
      sim_grid_pos_y: 1541153.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1446798.75
      sim_grid_pos_y: 1541098.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1446391.88
      sim_grid_pos_y: 1541270.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1446406.25
      sim_grid_pos_y: 1541695.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1446784.12
      sim_grid_pos_y: 1541644
    }
    terrain_level_point {
      sim_grid_pos_x: 1447037.75
      sim_grid_pos_y: 1541839.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1447309.25
      sim_grid_pos_y: 1541767.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1447523.62
      sim_grid_pos_y: 1541937.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1447721.5
      sim_grid_pos_y: 1541928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1447864.25
      sim_grid_pos_y: 1541706.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1448022.62
      sim_grid_pos_y: 1541612.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1447887.5
      sim_grid_pos_y: 1541449.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1447285.38
      sim_grid_pos_y: 1541280.5
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1447597.62
      sim_grid_pos_y: 1542262.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1447402.62
      sim_grid_pos_y: 1542094.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1447617
      sim_grid_pos_y: 1541980.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1447748.88
      sim_grid_pos_y: 1542157.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1447807.12
      sim_grid_pos_y: 1542167.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1447594.75
      sim_grid_pos_y: 1542314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1447330.38
      sim_grid_pos_y: 1542086.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1447628.88
      sim_grid_pos_y: 1541928.12
    }
  }
}
