terrain_level_data {
  terrain_level: 333
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2038054.88
      sim_grid_pos_y: 1258089.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2037781.88
      sim_grid_pos_y: 1258365.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2037883
      sim_grid_pos_y: 1258971
    }
    terrain_level_point {
      sim_grid_pos_x: 2038271.25
      sim_grid_pos_y: 1260152.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2038409.12
      sim_grid_pos_y: 1260448.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039423.88
      sim_grid_pos_y: 1261662.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039652.88
      sim_grid_pos_y: 1261803
    }
    terrain_level_point {
      sim_grid_pos_x: 2039989.38
      sim_grid_pos_y: 1261798.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2040105.62
      sim_grid_pos_y: 1261767.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2040156.12
      sim_grid_pos_y: 1261580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040327.62
      sim_grid_pos_y: 1261303.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2041143.38
      sim_grid_pos_y: 1260686.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2040741
      sim_grid_pos_y: 1260234.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039557.12
      sim_grid_pos_y: 1259228.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2038801.62
      sim_grid_pos_y: 1258468
    }
    terrain_level_point {
      sim_grid_pos_x: 2038250.5
      sim_grid_pos_y: 1257886.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2038250.75
      sim_grid_pos_y: 1257842.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2038033
      sim_grid_pos_y: 1258067.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2037749
      sim_grid_pos_y: 1258354.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2037853
      sim_grid_pos_y: 1258978.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2038242.62
      sim_grid_pos_y: 1260163.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2038382.88
      sim_grid_pos_y: 1260465
    }
    terrain_level_point {
      sim_grid_pos_x: 2039403.5
      sim_grid_pos_y: 1261686.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2039644.38
      sim_grid_pos_y: 1261833.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039993.5
      sim_grid_pos_y: 1261829.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2040130.62
      sim_grid_pos_y: 1261793.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2040184.62
      sim_grid_pos_y: 1261592.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2040350.75
      sim_grid_pos_y: 1261324.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2041188.5
      sim_grid_pos_y: 1260690.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2040762.5
      sim_grid_pos_y: 1260212.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039578
      sim_grid_pos_y: 1259205.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2038823.88
      sim_grid_pos_y: 1258446.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2038251
      sim_grid_pos_y: 1257797.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2038010.75
      sim_grid_pos_y: 1258046.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2037716
      sim_grid_pos_y: 1258344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2037823.12
      sim_grid_pos_y: 1258985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2038214
      sim_grid_pos_y: 1260175
    }
    terrain_level_point {
      sim_grid_pos_x: 2038356.75
      sim_grid_pos_y: 1260481.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039383.12
      sim_grid_pos_y: 1261709.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039635.88
      sim_grid_pos_y: 1261864.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039997.62
      sim_grid_pos_y: 1261859.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2040155.75
      sim_grid_pos_y: 1261818.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2040213.25
      sim_grid_pos_y: 1261605.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2040373.88
      sim_grid_pos_y: 1261345.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2041233.62
      sim_grid_pos_y: 1260695.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2040784.12
      sim_grid_pos_y: 1260190.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039599
      sim_grid_pos_y: 1259183
    }
    terrain_level_point {
      sim_grid_pos_x: 2038845.75
      sim_grid_pos_y: 1258425.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2038251.12
      sim_grid_pos_y: 1257753.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2037988.88
      sim_grid_pos_y: 1258024.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2037683.12
      sim_grid_pos_y: 1258334
    }
    terrain_level_point {
      sim_grid_pos_x: 2037793.12
      sim_grid_pos_y: 1258993.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2038185.25
      sim_grid_pos_y: 1260186.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2038330.5
      sim_grid_pos_y: 1260498.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2039362.75
      sim_grid_pos_y: 1261733.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039627.38
      sim_grid_pos_y: 1261895.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2040001.88
      sim_grid_pos_y: 1261890.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040180.75
      sim_grid_pos_y: 1261843.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2040241.75
      sim_grid_pos_y: 1261617.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040397
      sim_grid_pos_y: 1261366.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2041278.75
      sim_grid_pos_y: 1260699.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040805.62
      sim_grid_pos_y: 1260168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039619.88
      sim_grid_pos_y: 1259160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2038867.75
      sim_grid_pos_y: 1258403.75
    }
  }
}
