terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 381036.875
      sim_grid_pos_y: 1758752.62
    }
    terrain_level_point {
      sim_grid_pos_x: 375193.562
      sim_grid_pos_y: 1764806.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365021.844
      sim_grid_pos_y: 1764863.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365017.938
      sim_grid_pos_y: 1762535.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367152
      sim_grid_pos_y: 1759399.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367155.188
      sim_grid_pos_y: 1758314.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 381057.844
      sim_grid_pos_y: 1758722.5
    }
    terrain_level_point {
      sim_grid_pos_x: 381072.906
      sim_grid_pos_y: 1758759.5
    }
    terrain_level_point {
      sim_grid_pos_x: 375206.688
      sim_grid_pos_y: 1764837.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364991.125
      sim_grid_pos_y: 1764894.38
    }
    terrain_level_point {
      sim_grid_pos_x: 364987.188
      sim_grid_pos_y: 1762526.12
    }
    terrain_level_point {
      sim_grid_pos_x: 367121.281
      sim_grid_pos_y: 1759390.12
    }
    terrain_level_point {
      sim_grid_pos_x: 367124.5
      sim_grid_pos_y: 1758282.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 381078.812
      sim_grid_pos_y: 1758692.38
    }
    terrain_level_point {
      sim_grid_pos_x: 381108.938
      sim_grid_pos_y: 1758766.5
    }
    terrain_level_point {
      sim_grid_pos_x: 375219.812
      sim_grid_pos_y: 1764868
    }
    terrain_level_point {
      sim_grid_pos_x: 364960.438
      sim_grid_pos_y: 1764925.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364956.406
      sim_grid_pos_y: 1762516.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367090.562
      sim_grid_pos_y: 1759380.62
    }
    terrain_level_point {
      sim_grid_pos_x: 367093.844
      sim_grid_pos_y: 1758251
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 381099.781
      sim_grid_pos_y: 1758662.25
    }
    terrain_level_point {
      sim_grid_pos_x: 381144.969
      sim_grid_pos_y: 1758773.5
    }
    terrain_level_point {
      sim_grid_pos_x: 375232.938
      sim_grid_pos_y: 1764898.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364929.719
      sim_grid_pos_y: 1764956.25
    }
    terrain_level_point {
      sim_grid_pos_x: 364925.625
      sim_grid_pos_y: 1762507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 367059.844
      sim_grid_pos_y: 1759371.12
    }
    terrain_level_point {
      sim_grid_pos_x: 367063.188
      sim_grid_pos_y: 1758219.25
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 384855.688
      sim_grid_pos_y: 1767243.12
    }
    terrain_level_point {
      sim_grid_pos_x: 380586.812
      sim_grid_pos_y: 1768120.38
    }
    terrain_level_point {
      sim_grid_pos_x: 380406.75
      sim_grid_pos_y: 1768366.75
    }
    terrain_level_point {
      sim_grid_pos_x: 378433.125
      sim_grid_pos_y: 1768883
    }
    terrain_level_point {
      sim_grid_pos_x: 378345.25
      sim_grid_pos_y: 1769141
    }
    terrain_level_point {
      sim_grid_pos_x: 378002.562
      sim_grid_pos_y: 1769217.38
    }
    terrain_level_point {
      sim_grid_pos_x: 378536.188
      sim_grid_pos_y: 1771333.88
    }
    terrain_level_point {
      sim_grid_pos_x: 382227.125
      sim_grid_pos_y: 1770480.62
    }
    terrain_level_point {
      sim_grid_pos_x: 382442.969
      sim_grid_pos_y: 1771255.62
    }
    terrain_level_point {
      sim_grid_pos_x: 382767.219
      sim_grid_pos_y: 1771899.25
    }
    terrain_level_point {
      sim_grid_pos_x: 383108
      sim_grid_pos_y: 1771924.5
    }
    terrain_level_point {
      sim_grid_pos_x: 384152.312
      sim_grid_pos_y: 1772635.5
    }
    terrain_level_point {
      sim_grid_pos_x: 386043.031
      sim_grid_pos_y: 1771979.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 384878.344
      sim_grid_pos_y: 1767207
    }
    terrain_level_point {
      sim_grid_pos_x: 380569
      sim_grid_pos_y: 1768092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 380388.375
      sim_grid_pos_y: 1768339.75
    }
    terrain_level_point {
      sim_grid_pos_x: 378409.344
      sim_grid_pos_y: 1768857.38
    }
    terrain_level_point {
      sim_grid_pos_x: 378321.688
      sim_grid_pos_y: 1769114.62
    }
    terrain_level_point {
      sim_grid_pos_x: 377965.031
      sim_grid_pos_y: 1769194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 378513.75
      sim_grid_pos_y: 1771370.62
    }
    terrain_level_point {
      sim_grid_pos_x: 382205.375
      sim_grid_pos_y: 1770517.12
    }
    terrain_level_point {
      sim_grid_pos_x: 382414.156
      sim_grid_pos_y: 1771266.75
    }
    terrain_level_point {
      sim_grid_pos_x: 382747.562
      sim_grid_pos_y: 1771928.62
    }
    terrain_level_point {
      sim_grid_pos_x: 383097.469
      sim_grid_pos_y: 1771954.5
    }
    terrain_level_point {
      sim_grid_pos_x: 384147.812
      sim_grid_pos_y: 1772669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 386079.719
      sim_grid_pos_y: 1771998.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 384901.031
      sim_grid_pos_y: 1767171
    }
    terrain_level_point {
      sim_grid_pos_x: 380551.156
      sim_grid_pos_y: 1768064.88
    }
    terrain_level_point {
      sim_grid_pos_x: 380370
      sim_grid_pos_y: 1768312.88
    }
    terrain_level_point {
      sim_grid_pos_x: 378385.562
      sim_grid_pos_y: 1768831.75
    }
    terrain_level_point {
      sim_grid_pos_x: 378298.125
      sim_grid_pos_y: 1769088.38
    }
    terrain_level_point {
      sim_grid_pos_x: 377927.469
      sim_grid_pos_y: 1769171.12
    }
    terrain_level_point {
      sim_grid_pos_x: 378491.312
      sim_grid_pos_y: 1771407.5
    }
    terrain_level_point {
      sim_grid_pos_x: 382183.625
      sim_grid_pos_y: 1770553.75
    }
    terrain_level_point {
      sim_grid_pos_x: 382385.312
      sim_grid_pos_y: 1771277.88
    }
    terrain_level_point {
      sim_grid_pos_x: 382727.938
      sim_grid_pos_y: 1771958
    }
    terrain_level_point {
      sim_grid_pos_x: 383087
      sim_grid_pos_y: 1771984.62
    }
    terrain_level_point {
      sim_grid_pos_x: 384143.281
      sim_grid_pos_y: 1772703.75
    }
    terrain_level_point {
      sim_grid_pos_x: 386116.375
      sim_grid_pos_y: 1772018.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 384923.688
      sim_grid_pos_y: 1767134.88
    }
    terrain_level_point {
      sim_grid_pos_x: 380533.344
      sim_grid_pos_y: 1768037.12
    }
    terrain_level_point {
      sim_grid_pos_x: 380351.625
      sim_grid_pos_y: 1768285.88
    }
    terrain_level_point {
      sim_grid_pos_x: 378361.781
      sim_grid_pos_y: 1768806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 378274.594
      sim_grid_pos_y: 1769062.12
    }
    terrain_level_point {
      sim_grid_pos_x: 377889.906
      sim_grid_pos_y: 1769148
    }
    terrain_level_point {
      sim_grid_pos_x: 378468.844
      sim_grid_pos_y: 1771444.25
    }
    terrain_level_point {
      sim_grid_pos_x: 382161.906
      sim_grid_pos_y: 1770590.38
    }
    terrain_level_point {
      sim_grid_pos_x: 382356.5
      sim_grid_pos_y: 1771289.12
    }
    terrain_level_point {
      sim_grid_pos_x: 382708.312
      sim_grid_pos_y: 1771987.38
    }
    terrain_level_point {
      sim_grid_pos_x: 383076.5
      sim_grid_pos_y: 1772014.62
    }
    terrain_level_point {
      sim_grid_pos_x: 384138.75
      sim_grid_pos_y: 1772737.88
    }
    terrain_level_point {
      sim_grid_pos_x: 386153.062
      sim_grid_pos_y: 1772038.62
    }
  }
}
terrain_level_data {
  terrain_level: 13
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 373001.281
      sim_grid_pos_y: 1758306.62
    }
    terrain_level_point {
      sim_grid_pos_x: 380938
      sim_grid_pos_y: 1758400.62
    }
    terrain_level_point {
      sim_grid_pos_x: 381227.188
      sim_grid_pos_y: 1744226.12
    }
    terrain_level_point {
      sim_grid_pos_x: 379655.281
      sim_grid_pos_y: 1741349.38
    }
    terrain_level_point {
      sim_grid_pos_x: 374604.156
      sim_grid_pos_y: 1741394
    }
    terrain_level_point {
      sim_grid_pos_x: 372967.344
      sim_grid_pos_y: 1750067.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 379673.438
      sim_grid_pos_y: 1741318.38
    }
    terrain_level_point {
      sim_grid_pos_x: 374578.594
      sim_grid_pos_y: 1741363.5
    }
    terrain_level_point {
      sim_grid_pos_x: 372936.562
      sim_grid_pos_y: 1750064.5
    }
    terrain_level_point {
      sim_grid_pos_x: 372970.656
      sim_grid_pos_y: 1758337
    }
    terrain_level_point {
      sim_grid_pos_x: 380968.125
      sim_grid_pos_y: 1758431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 381258.094
      sim_grid_pos_y: 1744218.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 379691.594
      sim_grid_pos_y: 1741287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 374553.062
      sim_grid_pos_y: 1741332.88
    }
    terrain_level_point {
      sim_grid_pos_x: 372905.812
      sim_grid_pos_y: 1750061.75
    }
    terrain_level_point {
      sim_grid_pos_x: 372940.031
      sim_grid_pos_y: 1758367.38
    }
    terrain_level_point {
      sim_grid_pos_x: 380998.25
      sim_grid_pos_y: 1758462.88
    }
    terrain_level_point {
      sim_grid_pos_x: 381289.031
      sim_grid_pos_y: 1744211
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 379709.75
      sim_grid_pos_y: 1741256.62
    }
    terrain_level_point {
      sim_grid_pos_x: 374527.531
      sim_grid_pos_y: 1741302.38
    }
    terrain_level_point {
      sim_grid_pos_x: 372875.031
      sim_grid_pos_y: 1750058.88
    }
    terrain_level_point {
      sim_grid_pos_x: 372909.375
      sim_grid_pos_y: 1758397.75
    }
    terrain_level_point {
      sim_grid_pos_x: 381028.375
      sim_grid_pos_y: 1758494
    }
    terrain_level_point {
      sim_grid_pos_x: 381319.938
      sim_grid_pos_y: 1744203.38
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 360250.625
      sim_grid_pos_y: 1748038.25
    }
    terrain_level_point {
      sim_grid_pos_x: 359931.188
      sim_grid_pos_y: 1753564.88
    }
    terrain_level_point {
      sim_grid_pos_x: 361641.781
      sim_grid_pos_y: 1754931.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365222.719
      sim_grid_pos_y: 1753615.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365221.438
      sim_grid_pos_y: 1752469.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364838
      sim_grid_pos_y: 1751789.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365145
      sim_grid_pos_y: 1751035.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365203.125
      sim_grid_pos_y: 1749957.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365069.344
      sim_grid_pos_y: 1749352.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365149.656
      sim_grid_pos_y: 1.74892e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 363912.375
      sim_grid_pos_y: 1747998.25
    }
    terrain_level_point {
      sim_grid_pos_x: 363093.938
      sim_grid_pos_y: 1748735.12
    }
    terrain_level_point {
      sim_grid_pos_x: 360938.594
      sim_grid_pos_y: 1747214.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360575.469
      sim_grid_pos_y: 1747263.5
    }
    terrain_level_point {
      sim_grid_pos_x: 360303.062
      sim_grid_pos_y: 1747630.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 360946.438
      sim_grid_pos_y: 1747182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360558.531
      sim_grid_pos_y: 1747234.75
    }
    terrain_level_point {
      sim_grid_pos_x: 360273.594
      sim_grid_pos_y: 1747618.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360219.969
      sim_grid_pos_y: 1748035.38
    }
    terrain_level_point {
      sim_grid_pos_x: 359899.594
      sim_grid_pos_y: 1753578.88
    }
    terrain_level_point {
      sim_grid_pos_x: 361636.125
      sim_grid_pos_y: 1754966.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365253.5
      sim_grid_pos_y: 1753636.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365252.156
      sim_grid_pos_y: 1752461.88
    }
    terrain_level_point {
      sim_grid_pos_x: 364872.094
      sim_grid_pos_y: 1751787.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365175.438
      sim_grid_pos_y: 1751042.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365234.062
      sim_grid_pos_y: 1749954.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365100.75
      sim_grid_pos_y: 1749351.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365183.406
      sim_grid_pos_y: 1748906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 363910.562
      sim_grid_pos_y: 1747958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363091.625
      sim_grid_pos_y: 1748695.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 360954.281
      sim_grid_pos_y: 1747150.12
    }
    terrain_level_point {
      sim_grid_pos_x: 360541.562
      sim_grid_pos_y: 1747206
    }
    terrain_level_point {
      sim_grid_pos_x: 360244.094
      sim_grid_pos_y: 1747606.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360189.312
      sim_grid_pos_y: 1748032.62
    }
    terrain_level_point {
      sim_grid_pos_x: 359867.938
      sim_grid_pos_y: 1753593
    }
    terrain_level_point {
      sim_grid_pos_x: 361630.469
      sim_grid_pos_y: 1755001.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365284.281
      sim_grid_pos_y: 1753658.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365282.906
      sim_grid_pos_y: 1752453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 364906.188
      sim_grid_pos_y: 1751785.62
    }
    terrain_level_point {
      sim_grid_pos_x: 365205.875
      sim_grid_pos_y: 1751049.5
    }
    terrain_level_point {
      sim_grid_pos_x: 365265
      sim_grid_pos_y: 1749952.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365132.125
      sim_grid_pos_y: 1749351.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365217.125
      sim_grid_pos_y: 1748893.62
    }
    terrain_level_point {
      sim_grid_pos_x: 363908.719
      sim_grid_pos_y: 1747918.88
    }
    terrain_level_point {
      sim_grid_pos_x: 363089.281
      sim_grid_pos_y: 1748656.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 360962.125
      sim_grid_pos_y: 1747118
    }
    terrain_level_point {
      sim_grid_pos_x: 360524.594
      sim_grid_pos_y: 1747177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 360214.594
      sim_grid_pos_y: 1747594.38
    }
    terrain_level_point {
      sim_grid_pos_x: 360158.688
      sim_grid_pos_y: 1748029.75
    }
    terrain_level_point {
      sim_grid_pos_x: 359836.344
      sim_grid_pos_y: 1753607.12
    }
    terrain_level_point {
      sim_grid_pos_x: 361624.812
      sim_grid_pos_y: 1755036.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365315.062
      sim_grid_pos_y: 1753679.75
    }
    terrain_level_point {
      sim_grid_pos_x: 365313.656
      sim_grid_pos_y: 1752445.62
    }
    terrain_level_point {
      sim_grid_pos_x: 364940.281
      sim_grid_pos_y: 1751783.38
    }
    terrain_level_point {
      sim_grid_pos_x: 365236.312
      sim_grid_pos_y: 1751056.25
    }
    terrain_level_point {
      sim_grid_pos_x: 365295.938
      sim_grid_pos_y: 1749949.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365163.5
      sim_grid_pos_y: 1749350.88
    }
    terrain_level_point {
      sim_grid_pos_x: 365250.875
      sim_grid_pos_y: 1748880.38
    }
    terrain_level_point {
      sim_grid_pos_x: 363906.844
      sim_grid_pos_y: 1747879.12
    }
    terrain_level_point {
      sim_grid_pos_x: 363086.969
      sim_grid_pos_y: 1748617.25
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 358877.812
      sim_grid_pos_y: 1719854
    }
    terrain_level_point {
      sim_grid_pos_x: 349492.281
      sim_grid_pos_y: 1727348.88
    }
    terrain_level_point {
      sim_grid_pos_x: 345844.031
      sim_grid_pos_y: 1723301
    }
    terrain_level_point {
      sim_grid_pos_x: 345476.75
      sim_grid_pos_y: 1722440.62
    }
    terrain_level_point {
      sim_grid_pos_x: 344106.125
      sim_grid_pos_y: 1720938.12
    }
    terrain_level_point {
      sim_grid_pos_x: 344077.625
      sim_grid_pos_y: 1720501.62
    }
    terrain_level_point {
      sim_grid_pos_x: 344163.438
      sim_grid_pos_y: 1720353.5
    }
    terrain_level_point {
      sim_grid_pos_x: 344350.031
      sim_grid_pos_y: 1720123
    }
    terrain_level_point {
      sim_grid_pos_x: 345945.688
      sim_grid_pos_y: 1718214.88
    }
    terrain_level_point {
      sim_grid_pos_x: 346117.094
      sim_grid_pos_y: 1718157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 346844.125
      sim_grid_pos_y: 1.71819e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 346937.406
      sim_grid_pos_y: 1718243.5
    }
    terrain_level_point {
      sim_grid_pos_x: 346974.844
      sim_grid_pos_y: 1718355.38
    }
    terrain_level_point {
      sim_grid_pos_x: 346668.844
      sim_grid_pos_y: 1720089.75
    }
    terrain_level_point {
      sim_grid_pos_x: 346708.406
      sim_grid_pos_y: 1720405.12
    }
    terrain_level_point {
      sim_grid_pos_x: 346841.094
      sim_grid_pos_y: 1720622
    }
    terrain_level_point {
      sim_grid_pos_x: 347063.156
      sim_grid_pos_y: 1720786.5
    }
    terrain_level_point {
      sim_grid_pos_x: 347364.219
      sim_grid_pos_y: 1720885
    }
    terrain_level_point {
      sim_grid_pos_x: 349745.375
      sim_grid_pos_y: 1721516.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350333.188
      sim_grid_pos_y: 1721367.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350626.25
      sim_grid_pos_y: 1721099.25
    }
    terrain_level_point {
      sim_grid_pos_x: 350751.219
      sim_grid_pos_y: 1720755.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350771.438
      sim_grid_pos_y: 1720406.38
    }
    terrain_level_point {
      sim_grid_pos_x: 350662.031
      sim_grid_pos_y: 1720087.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350442.562
      sim_grid_pos_y: 1719734
    }
    terrain_level_point {
      sim_grid_pos_x: 350425.844
      sim_grid_pos_y: 1719423.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350877.281
      sim_grid_pos_y: 1718417.12
    }
    terrain_level_point {
      sim_grid_pos_x: 350857.031
      sim_grid_pos_y: 1718068.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350756.5
      sim_grid_pos_y: 1717830.12
    }
    terrain_level_point {
      sim_grid_pos_x: 350569.75
      sim_grid_pos_y: 1717546.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350501.188
      sim_grid_pos_y: 1717184.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350534.625
      sim_grid_pos_y: 1716830.5
    }
    terrain_level_point {
      sim_grid_pos_x: 350661.406
      sim_grid_pos_y: 1716493.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350856.375
      sim_grid_pos_y: 1716257.38
    }
    terrain_level_point {
      sim_grid_pos_x: 353128.094
      sim_grid_pos_y: 1714426.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354274.375
      sim_grid_pos_y: 1713986.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 358920.812
      sim_grid_pos_y: 1719859
    }
    terrain_level_point {
      sim_grid_pos_x: 349488.812
      sim_grid_pos_y: 1727391
    }
    terrain_level_point {
      sim_grid_pos_x: 345817.781
      sim_grid_pos_y: 1723317.88
    }
    terrain_level_point {
      sim_grid_pos_x: 345450.5
      sim_grid_pos_y: 1722457.5
    }
    terrain_level_point {
      sim_grid_pos_x: 344076.125
      sim_grid_pos_y: 1720951
    }
    terrain_level_point {
      sim_grid_pos_x: 344046.312
      sim_grid_pos_y: 1720494.38
    }
    terrain_level_point {
      sim_grid_pos_x: 344138.031
      sim_grid_pos_y: 1720336
    }
    terrain_level_point {
      sim_grid_pos_x: 344326.281
      sim_grid_pos_y: 1720103.5
    }
    terrain_level_point {
      sim_grid_pos_x: 345927.625
      sim_grid_pos_y: 1718188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 346112.719
      sim_grid_pos_y: 1718126.12
    }
    terrain_level_point {
      sim_grid_pos_x: 346852.938
      sim_grid_pos_y: 1718159.62
    }
    terrain_level_point {
      sim_grid_pos_x: 346962.844
      sim_grid_pos_y: 1718222.62
    }
    terrain_level_point {
      sim_grid_pos_x: 347006.5
      sim_grid_pos_y: 1718353
    }
    terrain_level_point {
      sim_grid_pos_x: 346699.938
      sim_grid_pos_y: 1720090.62
    }
    terrain_level_point {
      sim_grid_pos_x: 346738.125
      sim_grid_pos_y: 1720394.75
    }
    terrain_level_point {
      sim_grid_pos_x: 346864.219
      sim_grid_pos_y: 1720600.75
    }
    terrain_level_point {
      sim_grid_pos_x: 347077.5
      sim_grid_pos_y: 1720758.75
    }
    terrain_level_point {
      sim_grid_pos_x: 347372.906
      sim_grid_pos_y: 1720855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 349745.562
      sim_grid_pos_y: 1721484.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350318.125
      sim_grid_pos_y: 1721339.88
    }
    terrain_level_point {
      sim_grid_pos_x: 350599.906
      sim_grid_pos_y: 1721081.62
    }
    terrain_level_point {
      sim_grid_pos_x: 350720.781
      sim_grid_pos_y: 1720749.62
    }
    terrain_level_point {
      sim_grid_pos_x: 350740.375
      sim_grid_pos_y: 1720410.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350634.062
      sim_grid_pos_y: 1720101
    }
    terrain_level_point {
      sim_grid_pos_x: 350412.281
      sim_grid_pos_y: 1719743.5
    }
    terrain_level_point {
      sim_grid_pos_x: 350394.719
      sim_grid_pos_y: 1719418
    }
    terrain_level_point {
      sim_grid_pos_x: 350846.156
      sim_grid_pos_y: 1718411.38
    }
    terrain_level_point {
      sim_grid_pos_x: 350826.625
      sim_grid_pos_y: 1718076
    }
    terrain_level_point {
      sim_grid_pos_x: 350729.25
      sim_grid_pos_y: 1717844.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350540.656
      sim_grid_pos_y: 1717558.62
    }
    terrain_level_point {
      sim_grid_pos_x: 350470.156
      sim_grid_pos_y: 1717186.25
    }
    terrain_level_point {
      sim_grid_pos_x: 350504.375
      sim_grid_pos_y: 1716823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 350634.438
      sim_grid_pos_y: 1716478.25
    }
    terrain_level_point {
      sim_grid_pos_x: 350834.656
      sim_grid_pos_y: 1716235.38
    }
    terrain_level_point {
      sim_grid_pos_x: 353112.562
      sim_grid_pos_y: 1714399.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354284.562
      sim_grid_pos_y: 1713949.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 358963.844
      sim_grid_pos_y: 1719864
    }
    terrain_level_point {
      sim_grid_pos_x: 349485.375
      sim_grid_pos_y: 1727433.12
    }
    terrain_level_point {
      sim_grid_pos_x: 345791.5
      sim_grid_pos_y: 1723334.62
    }
    terrain_level_point {
      sim_grid_pos_x: 345424.281
      sim_grid_pos_y: 1722474.5
    }
    terrain_level_point {
      sim_grid_pos_x: 344046.125
      sim_grid_pos_y: 1720963.75
    }
    terrain_level_point {
      sim_grid_pos_x: 344015.031
      sim_grid_pos_y: 1720487
    }
    terrain_level_point {
      sim_grid_pos_x: 344112.594
      sim_grid_pos_y: 1720318.5
    }
    terrain_level_point {
      sim_grid_pos_x: 344302.5
      sim_grid_pos_y: 1720083.88
    }
    terrain_level_point {
      sim_grid_pos_x: 345909.594
      sim_grid_pos_y: 1718162.12
    }
    terrain_level_point {
      sim_grid_pos_x: 346108.344
      sim_grid_pos_y: 1718095.12
    }
    terrain_level_point {
      sim_grid_pos_x: 346861.781
      sim_grid_pos_y: 1718129.25
    }
    terrain_level_point {
      sim_grid_pos_x: 346988.312
      sim_grid_pos_y: 1718201.75
    }
    terrain_level_point {
      sim_grid_pos_x: 347038.156
      sim_grid_pos_y: 1718350.62
    }
    terrain_level_point {
      sim_grid_pos_x: 346731.031
      sim_grid_pos_y: 1720091.38
    }
    terrain_level_point {
      sim_grid_pos_x: 346767.812
      sim_grid_pos_y: 1720384.38
    }
    terrain_level_point {
      sim_grid_pos_x: 346887.312
      sim_grid_pos_y: 1720579.62
    }
    terrain_level_point {
      sim_grid_pos_x: 347091.781
      sim_grid_pos_y: 1720731.12
    }
    terrain_level_point {
      sim_grid_pos_x: 347381.656
      sim_grid_pos_y: 1720826
    }
    terrain_level_point {
      sim_grid_pos_x: 349745.75
      sim_grid_pos_y: 1721453.12
    }
    terrain_level_point {
      sim_grid_pos_x: 350303.062
      sim_grid_pos_y: 1721312
    }
    terrain_level_point {
      sim_grid_pos_x: 350573.594
      sim_grid_pos_y: 1721064
    }
    terrain_level_point {
      sim_grid_pos_x: 350690.344
      sim_grid_pos_y: 1720743.38
    }
    terrain_level_point {
      sim_grid_pos_x: 350709.344
      sim_grid_pos_y: 1720415
    }
    terrain_level_point {
      sim_grid_pos_x: 350606.125
      sim_grid_pos_y: 1720114.25
    }
    terrain_level_point {
      sim_grid_pos_x: 350381.969
      sim_grid_pos_y: 1719753.12
    }
    terrain_level_point {
      sim_grid_pos_x: 350363.625
      sim_grid_pos_y: 1719412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 350815
      sim_grid_pos_y: 1718405.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350796.25
      sim_grid_pos_y: 1718083
    }
    terrain_level_point {
      sim_grid_pos_x: 350702.031
      sim_grid_pos_y: 1717859.38
    }
    terrain_level_point {
      sim_grid_pos_x: 350511.594
      sim_grid_pos_y: 1717570.38
    }
    terrain_level_point {
      sim_grid_pos_x: 350439.125
      sim_grid_pos_y: 1717187.75
    }
    terrain_level_point {
      sim_grid_pos_x: 350474.156
      sim_grid_pos_y: 1716816.5
    }
    terrain_level_point {
      sim_grid_pos_x: 350607.438
      sim_grid_pos_y: 1716462.62
    }
    terrain_level_point {
      sim_grid_pos_x: 350812.906
      sim_grid_pos_y: 1716213.38
    }
    terrain_level_point {
      sim_grid_pos_x: 353097.031
      sim_grid_pos_y: 1714372.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354294.719
      sim_grid_pos_y: 1713913
    }
  }
}
