terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 604002.312
      sim_grid_pos_y: 2256435.25
    }
    terrain_level_point {
      sim_grid_pos_x: 604080.438
      sim_grid_pos_y: 2257715.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604163.438
      sim_grid_pos_y: 2258749.25
    }
    terrain_level_point {
      sim_grid_pos_x: 604291.75
      sim_grid_pos_y: 2258828
    }
    terrain_level_point {
      sim_grid_pos_x: 603990.188
      sim_grid_pos_y: 2259570.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603762.812
      sim_grid_pos_y: 2259606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603718.812
      sim_grid_pos_y: 2259771.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603846
      sim_grid_pos_y: 2.2599e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 603797.938
      sim_grid_pos_y: 2260183.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603006.75
      sim_grid_pos_y: 2261073.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605764.438
      sim_grid_pos_y: 2260227.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606148.562
      sim_grid_pos_y: 2260209.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606625.5
      sim_grid_pos_y: 2260075.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606982.062
      sim_grid_pos_y: 2260042
    }
    terrain_level_point {
      sim_grid_pos_x: 607403.75
      sim_grid_pos_y: 2260150.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607772
      sim_grid_pos_y: 2260248.75
    }
    terrain_level_point {
      sim_grid_pos_x: 609001.375
      sim_grid_pos_y: 2260757.25
    }
    terrain_level_point {
      sim_grid_pos_x: 609354.75
      sim_grid_pos_y: 2260362.5
    }
    terrain_level_point {
      sim_grid_pos_x: 609433.75
      sim_grid_pos_y: 2260055
    }
    terrain_level_point {
      sim_grid_pos_x: 608183.125
      sim_grid_pos_y: 2259451
    }
    terrain_level_point {
      sim_grid_pos_x: 608021.062
      sim_grid_pos_y: 2259347.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607786.5
      sim_grid_pos_y: 2259203.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607483.625
      sim_grid_pos_y: 2259238
    }
    terrain_level_point {
      sim_grid_pos_x: 606950.875
      sim_grid_pos_y: 2259590.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606513.188
      sim_grid_pos_y: 2259521
    }
    terrain_level_point {
      sim_grid_pos_x: 606442.938
      sim_grid_pos_y: 2259091
    }
    terrain_level_point {
      sim_grid_pos_x: 606470.375
      sim_grid_pos_y: 2258910.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606530.125
      sim_grid_pos_y: 2258834.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606535.75
      sim_grid_pos_y: 2258499
    }
    terrain_level_point {
      sim_grid_pos_x: 606407.438
      sim_grid_pos_y: 2258351.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606389.5
      sim_grid_pos_y: 2258244.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606016.438
      sim_grid_pos_y: 2258221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605627.062
      sim_grid_pos_y: 2257372
    }
    terrain_level_point {
      sim_grid_pos_x: 605509.375
      sim_grid_pos_y: 2257254
    }
    terrain_level_point {
      sim_grid_pos_x: 605380.75
      sim_grid_pos_y: 2256884
    }
    terrain_level_point {
      sim_grid_pos_x: 605017.375
      sim_grid_pos_y: 2256711.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605020.938
      sim_grid_pos_y: 2.25658e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 605169.25
      sim_grid_pos_y: 2256448
    }
    terrain_level_point {
      sim_grid_pos_x: 605379.25
      sim_grid_pos_y: 2256431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605499.625
      sim_grid_pos_y: 2256521
    }
    terrain_level_point {
      sim_grid_pos_x: 605792.938
      sim_grid_pos_y: 2256580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605997.25
      sim_grid_pos_y: 2256480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606019.75
      sim_grid_pos_y: 2256363.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605899.75
      sim_grid_pos_y: 2256323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605908.5
      sim_grid_pos_y: 2256192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605547.5
      sim_grid_pos_y: 2255745.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605193.562
      sim_grid_pos_y: 2254733.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601646.75
      sim_grid_pos_y: 2254787
    }
    terrain_level_point {
      sim_grid_pos_x: 600623.25
      sim_grid_pos_y: 2254298.5
    }
    terrain_level_point {
      sim_grid_pos_x: 599390.312
      sim_grid_pos_y: 2254723
    }
    terrain_level_point {
      sim_grid_pos_x: 598762.625
      sim_grid_pos_y: 2254695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 598302
      sim_grid_pos_y: 2254301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597942.562
      sim_grid_pos_y: 2254192
    }
    terrain_level_point {
      sim_grid_pos_x: 595068.375
      sim_grid_pos_y: 2253878.75
    }
    terrain_level_point {
      sim_grid_pos_x: 594957.938
      sim_grid_pos_y: 2254076.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594354.062
      sim_grid_pos_y: 2254005.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594097.875
      sim_grid_pos_y: 2.25526e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 593474.312
      sim_grid_pos_y: 2255748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593527.812
      sim_grid_pos_y: 2256072.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593683.438
      sim_grid_pos_y: 2256302
    }
    terrain_level_point {
      sim_grid_pos_x: 593701.75
      sim_grid_pos_y: 2256852.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593848
      sim_grid_pos_y: 2256853
    }
    terrain_level_point {
      sim_grid_pos_x: 593960.188
      sim_grid_pos_y: 2256967.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593994.188
      sim_grid_pos_y: 2257726.75
    }
    terrain_level_point {
      sim_grid_pos_x: 594048.75
      sim_grid_pos_y: 2257848.25
    }
    terrain_level_point {
      sim_grid_pos_x: 594439.375
      sim_grid_pos_y: 2258036.25
    }
    terrain_level_point {
      sim_grid_pos_x: 595616.75
      sim_grid_pos_y: 2258002.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595947.125
      sim_grid_pos_y: 2257687
    }
    terrain_level_point {
      sim_grid_pos_x: 596334.125
      sim_grid_pos_y: 2257462.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596054
      sim_grid_pos_y: 2257305.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596074.625
      sim_grid_pos_y: 2256566.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595946.25
      sim_grid_pos_y: 2256564.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595955.438
      sim_grid_pos_y: 2256167.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595027.688
      sim_grid_pos_y: 2255134.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595472.562
      sim_grid_pos_y: 2254592.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597501.75
      sim_grid_pos_y: 2254788
    }
    terrain_level_point {
      sim_grid_pos_x: 597670.25
      sim_grid_pos_y: 2254927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597654.125
      sim_grid_pos_y: 2255444.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597504.125
      sim_grid_pos_y: 2255450.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597557.25
      sim_grid_pos_y: 2257395.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596907.062
      sim_grid_pos_y: 2257419
    }
    terrain_level_point {
      sim_grid_pos_x: 596859.312
      sim_grid_pos_y: 2257486.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596779.75
      sim_grid_pos_y: 2257505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596978.125
      sim_grid_pos_y: 2257692.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597019.5
      sim_grid_pos_y: 2257843.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596862.75
      sim_grid_pos_y: 2259277
    }
    terrain_level_point {
      sim_grid_pos_x: 597613.062
      sim_grid_pos_y: 2258519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 598987.875
      sim_grid_pos_y: 2258793.5
    }
    terrain_level_point {
      sim_grid_pos_x: 599230.688
      sim_grid_pos_y: 2258985.5
    }
    terrain_level_point {
      sim_grid_pos_x: 599361.312
      sim_grid_pos_y: 2259007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 600054.125
      sim_grid_pos_y: 2258984.75
    }
    terrain_level_point {
      sim_grid_pos_x: 600550.625
      sim_grid_pos_y: 2259112.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602469.625
      sim_grid_pos_y: 2259863.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602588.562
      sim_grid_pos_y: 2259836.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602546.562
      sim_grid_pos_y: 2259537
    }
    terrain_level_point {
      sim_grid_pos_x: 602658.125
      sim_grid_pos_y: 2259354.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602817.938
      sim_grid_pos_y: 2259251.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603028.438
      sim_grid_pos_y: 2259274.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603036.438
      sim_grid_pos_y: 2259118.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601664
      sim_grid_pos_y: 2258679.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601574.5
      sim_grid_pos_y: 2256995.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600571.688
      sim_grid_pos_y: 2256969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600555.125
      sim_grid_pos_y: 2256500.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 595051.438
      sim_grid_pos_y: 2253846
    }
    terrain_level_point {
      sim_grid_pos_x: 594941.125
      sim_grid_pos_y: 2254043.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594329.562
      sim_grid_pos_y: 2253971.75
    }
    terrain_level_point {
      sim_grid_pos_x: 594070
      sim_grid_pos_y: 2255242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593441
      sim_grid_pos_y: 2255735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593498.562
      sim_grid_pos_y: 2256084.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593653
      sim_grid_pos_y: 2256312
    }
    terrain_level_point {
      sim_grid_pos_x: 593672
      sim_grid_pos_y: 2256883.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593835.062
      sim_grid_pos_y: 2256883.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593929.938
      sim_grid_pos_y: 2256980.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593963.688
      sim_grid_pos_y: 2257734
    }
    terrain_level_point {
      sim_grid_pos_x: 594025.312
      sim_grid_pos_y: 2257871.25
    }
    terrain_level_point {
      sim_grid_pos_x: 594432.812
      sim_grid_pos_y: 2258067
    }
    terrain_level_point {
      sim_grid_pos_x: 595629.438
      sim_grid_pos_y: 2258033
    }
    terrain_level_point {
      sim_grid_pos_x: 595965.75
      sim_grid_pos_y: 2257711.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596365.062
      sim_grid_pos_y: 2.25748e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 596364.812
      sim_grid_pos_y: 2257444.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596085.25
      sim_grid_pos_y: 2257287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596106.25
      sim_grid_pos_y: 2256536.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595977.75
      sim_grid_pos_y: 2256534.25
    }
    terrain_level_point {
      sim_grid_pos_x: 595986.438
      sim_grid_pos_y: 2256156
    }
    terrain_level_point {
      sim_grid_pos_x: 595068.25
      sim_grid_pos_y: 2255133.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595485.938
      sim_grid_pos_y: 2254624.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597489.438
      sim_grid_pos_y: 2254817.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597639.062
      sim_grid_pos_y: 2254941.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597624.312
      sim_grid_pos_y: 2255414.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597472.562
      sim_grid_pos_y: 2255421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597525.688
      sim_grid_pos_y: 2257365.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596890.75
      sim_grid_pos_y: 2257388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596840.938
      sim_grid_pos_y: 2257459
    }
    terrain_level_point {
      sim_grid_pos_x: 596754.75
      sim_grid_pos_y: 2257479.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596745.25
      sim_grid_pos_y: 2257515
    }
    terrain_level_point {
      sim_grid_pos_x: 596950.75
      sim_grid_pos_y: 2257708.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596988.312
      sim_grid_pos_y: 2257846
    }
    terrain_level_point {
      sim_grid_pos_x: 596829.812
      sim_grid_pos_y: 2259295.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596869.188
      sim_grid_pos_y: 2259314.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597623.312
      sim_grid_pos_y: 2258552.75
    }
    terrain_level_point {
      sim_grid_pos_x: 598974.625
      sim_grid_pos_y: 2258822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 599217.75
      sim_grid_pos_y: 2259014.5
    }
    terrain_level_point {
      sim_grid_pos_x: 599359.188
      sim_grid_pos_y: 2259038.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600050.75
      sim_grid_pos_y: 2259015.75
    }
    terrain_level_point {
      sim_grid_pos_x: 600541.188
      sim_grid_pos_y: 2259141.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602467.25
      sim_grid_pos_y: 2259895.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602622.938
      sim_grid_pos_y: 2.25986e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 602578.562
      sim_grid_pos_y: 2259543.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602680.75
      sim_grid_pos_y: 2259376.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602825.438
      sim_grid_pos_y: 2259283
    }
    terrain_level_point {
      sim_grid_pos_x: 603057.438
      sim_grid_pos_y: 2259308.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603068.375
      sim_grid_pos_y: 2259096.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601693.562
      sim_grid_pos_y: 2258656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601603.688
      sim_grid_pos_y: 2256965.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600601.438
      sim_grid_pos_y: 2256939.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600587
      sim_grid_pos_y: 2256530.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603973.438
      sim_grid_pos_y: 2256466.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604049.75
      sim_grid_pos_y: 2257717.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604134.062
      sim_grid_pos_y: 2258767.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604253.438
      sim_grid_pos_y: 2258840.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603968.25
      sim_grid_pos_y: 2259542.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603738.25
      sim_grid_pos_y: 2259579
    }
    terrain_level_point {
      sim_grid_pos_x: 603684.562
      sim_grid_pos_y: 2259781
    }
    terrain_level_point {
      sim_grid_pos_x: 603813
      sim_grid_pos_y: 2259910.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603769.062
      sim_grid_pos_y: 2260169.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602968.312
      sim_grid_pos_y: 2261070.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602993.5
      sim_grid_pos_y: 2.26111e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 605769.75
      sim_grid_pos_y: 2260258
    }
    terrain_level_point {
      sim_grid_pos_x: 606153.5
      sim_grid_pos_y: 2260240.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606631.125
      sim_grid_pos_y: 2260106
    }
    terrain_level_point {
      sim_grid_pos_x: 606979.562
      sim_grid_pos_y: 2260073
    }
    terrain_level_point {
      sim_grid_pos_x: 607395.812
      sim_grid_pos_y: 2.26018e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 607395.812
      sim_grid_pos_y: 2.26018e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 607762.125
      sim_grid_pos_y: 2260278
    }
    terrain_level_point {
      sim_grid_pos_x: 609009.812
      sim_grid_pos_y: 2260794
    }
    terrain_level_point {
      sim_grid_pos_x: 609382.688
      sim_grid_pos_y: 2260377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 609469.812
      sim_grid_pos_y: 2260038.25
    }
    terrain_level_point {
      sim_grid_pos_x: 608198.125
      sim_grid_pos_y: 2259424
    }
    terrain_level_point {
      sim_grid_pos_x: 608037.375
      sim_grid_pos_y: 2259321.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607793.562
      sim_grid_pos_y: 2259171.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607472.812
      sim_grid_pos_y: 2259208.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606943.812
      sim_grid_pos_y: 2259558.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606539.938
      sim_grid_pos_y: 2259494.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606474.062
      sim_grid_pos_y: 2259090.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606499.562
      sim_grid_pos_y: 2258923
    }
    terrain_level_point {
      sim_grid_pos_x: 606560.688
      sim_grid_pos_y: 2258845.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606566.688
      sim_grid_pos_y: 2258487.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606436.312
      sim_grid_pos_y: 2258337.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606415.75
      sim_grid_pos_y: 2258215
    }
    terrain_level_point {
      sim_grid_pos_x: 606036.75
      sim_grid_pos_y: 2258192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605652.75
      sim_grid_pos_y: 2257354.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605536.125
      sim_grid_pos_y: 2257237.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605405.625
      sim_grid_pos_y: 2256861.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605048.625
      sim_grid_pos_y: 2256692.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605051.312
      sim_grid_pos_y: 2256594
    }
    terrain_level_point {
      sim_grid_pos_x: 605181.938
      sim_grid_pos_y: 2256477.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605370.125
      sim_grid_pos_y: 2256463.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605486.812
      sim_grid_pos_y: 2256549.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605797.062
      sim_grid_pos_y: 2256612.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606024.562
      sim_grid_pos_y: 2256501
    }
    terrain_level_point {
      sim_grid_pos_x: 606055.062
      sim_grid_pos_y: 2256342.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605932.062
      sim_grid_pos_y: 2256301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605940
      sim_grid_pos_y: 2256182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605574.812
      sim_grid_pos_y: 2.25573e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 605215.312
      sim_grid_pos_y: 2254702.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601653.5
      sim_grid_pos_y: 2254756
    }
    terrain_level_point {
      sim_grid_pos_x: 600625.125
      sim_grid_pos_y: 2254265.25
    }
    terrain_level_point {
      sim_grid_pos_x: 599385.875
      sim_grid_pos_y: 2254692
    }
    terrain_level_point {
      sim_grid_pos_x: 598774.562
      sim_grid_pos_y: 2254665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 598317.062
      sim_grid_pos_y: 2254274.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597948.75
      sim_grid_pos_y: 2254161.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 595034.5
      sim_grid_pos_y: 2253813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 594924.312
      sim_grid_pos_y: 2254010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594305.062
      sim_grid_pos_y: 2253937.75
    }
    terrain_level_point {
      sim_grid_pos_x: 594042.125
      sim_grid_pos_y: 2255225.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593407.688
      sim_grid_pos_y: 2255722.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593469.312
      sim_grid_pos_y: 2256096
    }
    terrain_level_point {
      sim_grid_pos_x: 593622.562
      sim_grid_pos_y: 2256321.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593642.25
      sim_grid_pos_y: 2256914
    }
    terrain_level_point {
      sim_grid_pos_x: 593822.062
      sim_grid_pos_y: 2256914.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593899.75
      sim_grid_pos_y: 2256993.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593933.25
      sim_grid_pos_y: 2257741.25
    }
    terrain_level_point {
      sim_grid_pos_x: 594001.812
      sim_grid_pos_y: 2257894
    }
    terrain_level_point {
      sim_grid_pos_x: 594426.188
      sim_grid_pos_y: 2258098
    }
    terrain_level_point {
      sim_grid_pos_x: 595642.125
      sim_grid_pos_y: 2258063.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595984.375
      sim_grid_pos_y: 2257736.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596395.938
      sim_grid_pos_y: 2257497.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596395.438
      sim_grid_pos_y: 2257426.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596116.562
      sim_grid_pos_y: 2257269.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596137.812
      sim_grid_pos_y: 2256506.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596009.188
      sim_grid_pos_y: 2256504
    }
    terrain_level_point {
      sim_grid_pos_x: 596017.5
      sim_grid_pos_y: 2256144.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595108.75
      sim_grid_pos_y: 2255132.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595499.312
      sim_grid_pos_y: 2254656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597477.062
      sim_grid_pos_y: 2254847.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597607.875
      sim_grid_pos_y: 2254955.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597594.438
      sim_grid_pos_y: 2255385.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597441
      sim_grid_pos_y: 2255392
    }
    terrain_level_point {
      sim_grid_pos_x: 597494.125
      sim_grid_pos_y: 2257336
    }
    terrain_level_point {
      sim_grid_pos_x: 596874.438
      sim_grid_pos_y: 2257358.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596822.562
      sim_grid_pos_y: 2257431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596729.812
      sim_grid_pos_y: 2257453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596710.812
      sim_grid_pos_y: 2257524.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596923.375
      sim_grid_pos_y: 2257725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596957.125
      sim_grid_pos_y: 2257848.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596796.812
      sim_grid_pos_y: 2259313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596875.688
      sim_grid_pos_y: 2259351.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597633.5
      sim_grid_pos_y: 2258586.25
    }
    terrain_level_point {
      sim_grid_pos_x: 598961.375
      sim_grid_pos_y: 2258851
    }
    terrain_level_point {
      sim_grid_pos_x: 599204.812
      sim_grid_pos_y: 2259043.25
    }
    terrain_level_point {
      sim_grid_pos_x: 599357.062
      sim_grid_pos_y: 2259069.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600047.375
      sim_grid_pos_y: 2259046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 600531.75
      sim_grid_pos_y: 2259170.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602464.875
      sim_grid_pos_y: 2259927.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602657.312
      sim_grid_pos_y: 2259883.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602610.562
      sim_grid_pos_y: 2259550.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602703.312
      sim_grid_pos_y: 2259398.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602832.938
      sim_grid_pos_y: 2259314.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603086.5
      sim_grid_pos_y: 2259342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603100.312
      sim_grid_pos_y: 2259074.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601723.125
      sim_grid_pos_y: 2258634
    }
    terrain_level_point {
      sim_grid_pos_x: 601632.938
      sim_grid_pos_y: 2256935.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600631.125
      sim_grid_pos_y: 2256909.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600618.812
      sim_grid_pos_y: 2256561
    }
    terrain_level_point {
      sim_grid_pos_x: 603944.5
      sim_grid_pos_y: 2256498
    }
    terrain_level_point {
      sim_grid_pos_x: 604019.062
      sim_grid_pos_y: 2257719.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604104.625
      sim_grid_pos_y: 2258785.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604215.125
      sim_grid_pos_y: 2258853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603946.25
      sim_grid_pos_y: 2259514.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603713.688
      sim_grid_pos_y: 2259551.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603650.312
      sim_grid_pos_y: 2.25979e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 603780.062
      sim_grid_pos_y: 2259921
    }
    terrain_level_point {
      sim_grid_pos_x: 603740.25
      sim_grid_pos_y: 2260155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602929.812
      sim_grid_pos_y: 2261067.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602980.188
      sim_grid_pos_y: 2261146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605775.062
      sim_grid_pos_y: 2260288.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606158.438
      sim_grid_pos_y: 2260270.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606636.75
      sim_grid_pos_y: 2260136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606977.125
      sim_grid_pos_y: 2260104.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607388.25
      sim_grid_pos_y: 2.26021e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 607752.188
      sim_grid_pos_y: 2260307
    }
    terrain_level_point {
      sim_grid_pos_x: 609018.188
      sim_grid_pos_y: 2260830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 609410.625
      sim_grid_pos_y: 2260392.5
    }
    terrain_level_point {
      sim_grid_pos_x: 609505.812
      sim_grid_pos_y: 2260021.5
    }
    terrain_level_point {
      sim_grid_pos_x: 608213.188
      sim_grid_pos_y: 2259397.25
    }
    terrain_level_point {
      sim_grid_pos_x: 608053.75
      sim_grid_pos_y: 2259295.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607800.625
      sim_grid_pos_y: 2.25914e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 607462
      sim_grid_pos_y: 2259178.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606936.812
      sim_grid_pos_y: 2259526
    }
    terrain_level_point {
      sim_grid_pos_x: 606566.688
      sim_grid_pos_y: 2259467.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606505.25
      sim_grid_pos_y: 2259090.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606528.75
      sim_grid_pos_y: 2258935.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606591.25
      sim_grid_pos_y: 2258856.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606597.625
      sim_grid_pos_y: 2258476.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606465.25
      sim_grid_pos_y: 2258324
    }
    terrain_level_point {
      sim_grid_pos_x: 606442.062
      sim_grid_pos_y: 2258185.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606057
      sim_grid_pos_y: 2258162.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605678.438
      sim_grid_pos_y: 2257336.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605562.875
      sim_grid_pos_y: 2257220.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605430.438
      sim_grid_pos_y: 2256839.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605079.938
      sim_grid_pos_y: 2256673.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605081.688
      sim_grid_pos_y: 2256608.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605194.625
      sim_grid_pos_y: 2256507.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605361.062
      sim_grid_pos_y: 2256495
    }
    terrain_level_point {
      sim_grid_pos_x: 605474
      sim_grid_pos_y: 2256578.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605801.25
      sim_grid_pos_y: 2256645
    }
    terrain_level_point {
      sim_grid_pos_x: 606051.875
      sim_grid_pos_y: 2256521.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606090.375
      sim_grid_pos_y: 2256321.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605964.312
      sim_grid_pos_y: 2256280.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605971.5
      sim_grid_pos_y: 2256172.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605602.062
      sim_grid_pos_y: 2255714.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605237
      sim_grid_pos_y: 2254671.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601660.25
      sim_grid_pos_y: 2254725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 600627.062
      sim_grid_pos_y: 2254232
    }
    terrain_level_point {
      sim_grid_pos_x: 599381.375
      sim_grid_pos_y: 2254661
    }
    terrain_level_point {
      sim_grid_pos_x: 598786.5
      sim_grid_pos_y: 2254635
    }
    terrain_level_point {
      sim_grid_pos_x: 598332.188
      sim_grid_pos_y: 2254246.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597955
      sim_grid_pos_y: 2254131.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 595017.562
      sim_grid_pos_y: 2253780.25
    }
    terrain_level_point {
      sim_grid_pos_x: 594907.438
      sim_grid_pos_y: 2253977.5
    }
    terrain_level_point {
      sim_grid_pos_x: 594280.625
      sim_grid_pos_y: 2253904
    }
    terrain_level_point {
      sim_grid_pos_x: 594014.25
      sim_grid_pos_y: 2255208.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593374.375
      sim_grid_pos_y: 2255709.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593440.062
      sim_grid_pos_y: 2256107.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593592.125
      sim_grid_pos_y: 2256331.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593612.438
      sim_grid_pos_y: 2256944.75
    }
    terrain_level_point {
      sim_grid_pos_x: 593809.125
      sim_grid_pos_y: 2256945.25
    }
    terrain_level_point {
      sim_grid_pos_x: 593869.562
      sim_grid_pos_y: 2257007
    }
    terrain_level_point {
      sim_grid_pos_x: 593902.812
      sim_grid_pos_y: 2257748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 593978.375
      sim_grid_pos_y: 2257917
    }
    terrain_level_point {
      sim_grid_pos_x: 594419.625
      sim_grid_pos_y: 2258129
    }
    terrain_level_point {
      sim_grid_pos_x: 595654.812
      sim_grid_pos_y: 2258094
    }
    terrain_level_point {
      sim_grid_pos_x: 596002.938
      sim_grid_pos_y: 2257761.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596426.812
      sim_grid_pos_y: 2257515.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596426.062
      sim_grid_pos_y: 2257408.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596147.812
      sim_grid_pos_y: 2257252
    }
    terrain_level_point {
      sim_grid_pos_x: 596169.438
      sim_grid_pos_y: 2256476
    }
    terrain_level_point {
      sim_grid_pos_x: 596040.625
      sim_grid_pos_y: 2256473.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596048.5
      sim_grid_pos_y: 2256133
    }
    terrain_level_point {
      sim_grid_pos_x: 595149.312
      sim_grid_pos_y: 2255132
    }
    terrain_level_point {
      sim_grid_pos_x: 595512.688
      sim_grid_pos_y: 2254689
    }
    terrain_level_point {
      sim_grid_pos_x: 597464.75
      sim_grid_pos_y: 2254877.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597576.625
      sim_grid_pos_y: 2254969.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597564.562
      sim_grid_pos_y: 2255355.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597409.438
      sim_grid_pos_y: 2255362.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597462.5
      sim_grid_pos_y: 2257306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596858.062
      sim_grid_pos_y: 2257328.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596804.125
      sim_grid_pos_y: 2257404.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596704.812
      sim_grid_pos_y: 2257428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596676.312
      sim_grid_pos_y: 2257534.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596895.938
      sim_grid_pos_y: 2257741.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596925.875
      sim_grid_pos_y: 2257851
    }
    terrain_level_point {
      sim_grid_pos_x: 596763.875
      sim_grid_pos_y: 2259332
    }
    terrain_level_point {
      sim_grid_pos_x: 596882.188
      sim_grid_pos_y: 2259388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597643.75
      sim_grid_pos_y: 2258619.5
    }
    terrain_level_point {
      sim_grid_pos_x: 598948.062
      sim_grid_pos_y: 2258879.75
    }
    terrain_level_point {
      sim_grid_pos_x: 599191.875
      sim_grid_pos_y: 2259072.25
    }
    terrain_level_point {
      sim_grid_pos_x: 599354.938
      sim_grid_pos_y: 2259100.25
    }
    terrain_level_point {
      sim_grid_pos_x: 600044
      sim_grid_pos_y: 2259077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600522.25
      sim_grid_pos_y: 2259200.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602462.438
      sim_grid_pos_y: 2259959.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602691.688
      sim_grid_pos_y: 2259907.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602642.562
      sim_grid_pos_y: 2259557
    }
    terrain_level_point {
      sim_grid_pos_x: 602725.875
      sim_grid_pos_y: 2259420.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602840.438
      sim_grid_pos_y: 2259346.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603115.562
      sim_grid_pos_y: 2259377
    }
    terrain_level_point {
      sim_grid_pos_x: 603132.25
      sim_grid_pos_y: 2259052.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601752.75
      sim_grid_pos_y: 2258611.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601662.125
      sim_grid_pos_y: 2256905.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600660.875
      sim_grid_pos_y: 2256879.5
    }
    terrain_level_point {
      sim_grid_pos_x: 600650.688
      sim_grid_pos_y: 2256591
    }
    terrain_level_point {
      sim_grid_pos_x: 603915.625
      sim_grid_pos_y: 2256529.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603988.375
      sim_grid_pos_y: 2257722
    }
    terrain_level_point {
      sim_grid_pos_x: 604075.25
      sim_grid_pos_y: 2258803.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604176.812
      sim_grid_pos_y: 2258865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603924.312
      sim_grid_pos_y: 2259487.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603689.062
      sim_grid_pos_y: 2259524.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603616.062
      sim_grid_pos_y: 2259799.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603747.062
      sim_grid_pos_y: 2259931.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603711.375
      sim_grid_pos_y: 2260142
    }
    terrain_level_point {
      sim_grid_pos_x: 602891.312
      sim_grid_pos_y: 2261064.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602966.938
      sim_grid_pos_y: 2261182.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605780.375
      sim_grid_pos_y: 2260319
    }
    terrain_level_point {
      sim_grid_pos_x: 606163.375
      sim_grid_pos_y: 2260301.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606642.375
      sim_grid_pos_y: 2260166.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606974.688
      sim_grid_pos_y: 2260135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607380.062
      sim_grid_pos_y: 2260239.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607742.312
      sim_grid_pos_y: 2260336.25
    }
    terrain_level_point {
      sim_grid_pos_x: 609026.562
      sim_grid_pos_y: 2260867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 609438.562
      sim_grid_pos_y: 2260407.25
    }
    terrain_level_point {
      sim_grid_pos_x: 609541.875
      sim_grid_pos_y: 2260004.75
    }
    terrain_level_point {
      sim_grid_pos_x: 608228.188
      sim_grid_pos_y: 2259370.25
    }
    terrain_level_point {
      sim_grid_pos_x: 608070.062
      sim_grid_pos_y: 2259269.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607807.688
      sim_grid_pos_y: 2259108.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607451.188
      sim_grid_pos_y: 2259148.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606929.812
      sim_grid_pos_y: 2259493.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606593.5
      sim_grid_pos_y: 2259440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606536.375
      sim_grid_pos_y: 2259090.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606557.938
      sim_grid_pos_y: 2258948.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606621.812
      sim_grid_pos_y: 2258867
    }
    terrain_level_point {
      sim_grid_pos_x: 606628.625
      sim_grid_pos_y: 2258465.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606494.125
      sim_grid_pos_y: 2258310.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606468.312
      sim_grid_pos_y: 2258156.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606077.25
      sim_grid_pos_y: 2258133
    }
    terrain_level_point {
      sim_grid_pos_x: 605704.062
      sim_grid_pos_y: 2257318.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605589.625
      sim_grid_pos_y: 2257203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605455.25
      sim_grid_pos_y: 2256817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605111.25
      sim_grid_pos_y: 2256654
    }
    terrain_level_point {
      sim_grid_pos_x: 605112.062
      sim_grid_pos_y: 2256622.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605207.312
      sim_grid_pos_y: 2256537.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605351.938
      sim_grid_pos_y: 2256526.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605461.188
      sim_grid_pos_y: 2256607.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605805.375
      sim_grid_pos_y: 2256677.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606079.188
      sim_grid_pos_y: 2256542.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606125.688
      sim_grid_pos_y: 2256301
    }
    terrain_level_point {
      sim_grid_pos_x: 605996.562
      sim_grid_pos_y: 2256258.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606003
      sim_grid_pos_y: 2256162.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605629.312
      sim_grid_pos_y: 2255699.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605258.688
      sim_grid_pos_y: 2254640.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601667
      sim_grid_pos_y: 2254694.25
    }
    terrain_level_point {
      sim_grid_pos_x: 600628.938
      sim_grid_pos_y: 2254198.75
    }
    terrain_level_point {
      sim_grid_pos_x: 599376.875
      sim_grid_pos_y: 2.25463e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 598798.438
      sim_grid_pos_y: 2254604.75
    }
    terrain_level_point {
      sim_grid_pos_x: 598347.312
      sim_grid_pos_y: 2254219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597961.188
      sim_grid_pos_y: 2254101.25
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 605778.125
      sim_grid_pos_y: 2256749.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605897.688
      sim_grid_pos_y: 2257227.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605914.188
      sim_grid_pos_y: 2257637.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606095.875
      sim_grid_pos_y: 2257954.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606246.375
      sim_grid_pos_y: 2258043.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606426.438
      sim_grid_pos_y: 2258070.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606450.125
      sim_grid_pos_y: 2257913.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606410.188
      sim_grid_pos_y: 2257029.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606281.5
      sim_grid_pos_y: 2257029.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606261.375
      sim_grid_pos_y: 2256927
    }
    terrain_level_point {
      sim_grid_pos_x: 606128.688
      sim_grid_pos_y: 2256760.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606000.438
      sim_grid_pos_y: 2256820.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605891
      sim_grid_pos_y: 2256804.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605859.625
      sim_grid_pos_y: 2256722.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 605877.812
      sim_grid_pos_y: 2256684.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605741.312
      sim_grid_pos_y: 2256729.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605867.062
      sim_grid_pos_y: 2257232.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605883.75
      sim_grid_pos_y: 2257646.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606073.188
      sim_grid_pos_y: 2257976.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606235.875
      sim_grid_pos_y: 2258073.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606452.25
      sim_grid_pos_y: 2258105.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606480.938
      sim_grid_pos_y: 2257914.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606439.562
      sim_grid_pos_y: 2256998.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606306.812
      sim_grid_pos_y: 2256998.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606290.125
      sim_grid_pos_y: 2256913.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606137.562
      sim_grid_pos_y: 2256722
    }
    terrain_level_point {
      sim_grid_pos_x: 605995.75
      sim_grid_pos_y: 2256789
    }
    terrain_level_point {
      sim_grid_pos_x: 605913.312
      sim_grid_pos_y: 2256776.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 605896.062
      sim_grid_pos_y: 2256645.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605704.562
      sim_grid_pos_y: 2256709.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605836.438
      sim_grid_pos_y: 2257236.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605853.312
      sim_grid_pos_y: 2257655
    }
    terrain_level_point {
      sim_grid_pos_x: 606050.562
      sim_grid_pos_y: 2257998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606225.375
      sim_grid_pos_y: 2258102.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606478.125
      sim_grid_pos_y: 2258140.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606511.812
      sim_grid_pos_y: 2257916.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606469
      sim_grid_pos_y: 2256968
    }
    terrain_level_point {
      sim_grid_pos_x: 606332.062
      sim_grid_pos_y: 2256967.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606318.875
      sim_grid_pos_y: 2256900.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606146.5
      sim_grid_pos_y: 2256683.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605991.062
      sim_grid_pos_y: 2256757.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605935.562
      sim_grid_pos_y: 2256748.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 605914.25
      sim_grid_pos_y: 2256607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605667.812
      sim_grid_pos_y: 2256689
    }
    terrain_level_point {
      sim_grid_pos_x: 605805.875
      sim_grid_pos_y: 2257241
    }
    terrain_level_point {
      sim_grid_pos_x: 605822.875
      sim_grid_pos_y: 2257663.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606027.875
      sim_grid_pos_y: 2258021.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606214.812
      sim_grid_pos_y: 2258132.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606503.938
      sim_grid_pos_y: 2258175.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606542.688
      sim_grid_pos_y: 2257918
    }
    terrain_level_point {
      sim_grid_pos_x: 606498.375
      sim_grid_pos_y: 2256937.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606357.375
      sim_grid_pos_y: 2256937
    }
    terrain_level_point {
      sim_grid_pos_x: 606347.625
      sim_grid_pos_y: 2256887.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606155.375
      sim_grid_pos_y: 2256645.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605986.375
      sim_grid_pos_y: 2256725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605957.875
      sim_grid_pos_y: 2256721
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 600672.5
      sim_grid_pos_y: 2256590.75
    }
    terrain_level_point {
      sim_grid_pos_x: 600670
      sim_grid_pos_y: 2256786.25
    }
    terrain_level_point {
      sim_grid_pos_x: 601391.25
      sim_grid_pos_y: 2256798.75
    }
    terrain_level_point {
      sim_grid_pos_x: 601674.062
      sim_grid_pos_y: 2256914
    }
    terrain_level_point {
      sim_grid_pos_x: 601751.188
      sim_grid_pos_y: 2258599.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603134.75
      sim_grid_pos_y: 2259077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603063.062
      sim_grid_pos_y: 2258503.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603099.062
      sim_grid_pos_y: 2257931.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602488.5
      sim_grid_pos_y: 2257719
    }
    terrain_level_point {
      sim_grid_pos_x: 602290.5
      sim_grid_pos_y: 2257778.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602090.25
      sim_grid_pos_y: 2257350.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602065.875
      sim_grid_pos_y: 2256971.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602392.625
      sim_grid_pos_y: 2256931.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603256.812
      sim_grid_pos_y: 2256967.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603389.875
      sim_grid_pos_y: 2257214
    }
    terrain_level_point {
      sim_grid_pos_x: 603400.188
      sim_grid_pos_y: 2257565.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603877.062
      sim_grid_pos_y: 2258199.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603918.125
      sim_grid_pos_y: 2258878.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603852.938
      sim_grid_pos_y: 2259268.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603972.625
      sim_grid_pos_y: 2259544
    }
    terrain_level_point {
      sim_grid_pos_x: 604139.75
      sim_grid_pos_y: 2258684.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603962.812
      sim_grid_pos_y: 2256472.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 603981.688
      sim_grid_pos_y: 2256451.25
    }
    terrain_level_point {
      sim_grid_pos_x: 600652.25
      sim_grid_pos_y: 2256571
    }
    terrain_level_point {
      sim_grid_pos_x: 600649.25
      sim_grid_pos_y: 2256806.5
    }
    terrain_level_point {
      sim_grid_pos_x: 601387.062
      sim_grid_pos_y: 2256819
    }
    terrain_level_point {
      sim_grid_pos_x: 601654.188
      sim_grid_pos_y: 2256928
    }
    terrain_level_point {
      sim_grid_pos_x: 601731.375
      sim_grid_pos_y: 2258614
    }
    terrain_level_point {
      sim_grid_pos_x: 603159.188
      sim_grid_pos_y: 2259107.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603083.688
      sim_grid_pos_y: 2258502.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603120.562
      sim_grid_pos_y: 2257917.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602488.938
      sim_grid_pos_y: 2257697.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602301.562
      sim_grid_pos_y: 2257753.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602110.438
      sim_grid_pos_y: 2257345.25
    }
    terrain_level_point {
      sim_grid_pos_x: 602087.562
      sim_grid_pos_y: 2256989.5
    }
    terrain_level_point {
      sim_grid_pos_x: 602393.438
      sim_grid_pos_y: 2256952.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603244.312
      sim_grid_pos_y: 2256987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603369.5
      sim_grid_pos_y: 2257219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603379.875
      sim_grid_pos_y: 2257572.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603857
      sim_grid_pos_y: 2258206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603897.5
      sim_grid_pos_y: 2258877
    }
    terrain_level_point {
      sim_grid_pos_x: 603831.688
      sim_grid_pos_y: 2259271
    }
    terrain_level_point {
      sim_grid_pos_x: 603959.812
      sim_grid_pos_y: 2259566
    }
    terrain_level_point {
      sim_grid_pos_x: 603989.875
      sim_grid_pos_y: 2259562.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604160.438
      sim_grid_pos_y: 2258686
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 596012.875
      sim_grid_pos_y: 2256184
    }
    terrain_level_point {
      sim_grid_pos_x: 595819.25
      sim_grid_pos_y: 2256040.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595067.625
      sim_grid_pos_y: 2255149.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595486.125
      sim_grid_pos_y: 2254644.25
    }
    terrain_level_point {
      sim_grid_pos_x: 597381.812
      sim_grid_pos_y: 2254821.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597614.5
      sim_grid_pos_y: 2254985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597611.938
      sim_grid_pos_y: 2255425.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597456.125
      sim_grid_pos_y: 2255409.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597318.812
      sim_grid_pos_y: 2255363.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597157.562
      sim_grid_pos_y: 2255171
    }
    terrain_level_point {
      sim_grid_pos_x: 596779.562
      sim_grid_pos_y: 2255193.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596410.938
      sim_grid_pos_y: 2255044.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596228.5
      sim_grid_pos_y: 2254987.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595851.125
      sim_grid_pos_y: 2255111.25
    }
    terrain_level_point {
      sim_grid_pos_x: 595802.188
      sim_grid_pos_y: 2255231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595982.688
      sim_grid_pos_y: 2255520.75
    }
    terrain_level_point {
      sim_grid_pos_x: 596177.438
      sim_grid_pos_y: 2255772.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 597389.188
      sim_grid_pos_y: 2254801.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597635.062
      sim_grid_pos_y: 2254975
    }
    terrain_level_point {
      sim_grid_pos_x: 597632.312
      sim_grid_pos_y: 2255448.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597451.812
      sim_grid_pos_y: 2255429.75
    }
    terrain_level_point {
      sim_grid_pos_x: 597306.812
      sim_grid_pos_y: 2255381.5
    }
    terrain_level_point {
      sim_grid_pos_x: 597148.438
      sim_grid_pos_y: 2255192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596776.125
      sim_grid_pos_y: 2255214
    }
    terrain_level_point {
      sim_grid_pos_x: 596404.062
      sim_grid_pos_y: 2255064.25
    }
    terrain_level_point {
      sim_grid_pos_x: 596228.625
      sim_grid_pos_y: 2255009
    }
    terrain_level_point {
      sim_grid_pos_x: 595866.562
      sim_grid_pos_y: 2255127.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595825.125
      sim_grid_pos_y: 2255229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595999.562
      sim_grid_pos_y: 2255509
    }
    terrain_level_point {
      sim_grid_pos_x: 596200.812
      sim_grid_pos_y: 2255769.5
    }
    terrain_level_point {
      sim_grid_pos_x: 596022.062
      sim_grid_pos_y: 2256216.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595805.125
      sim_grid_pos_y: 2256055.75
    }
    terrain_level_point {
      sim_grid_pos_x: 595040.938
      sim_grid_pos_y: 2255149.5
    }
    terrain_level_point {
      sim_grid_pos_x: 595477.25
      sim_grid_pos_y: 2254622.75
    }
  }
}
