terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 444010.656
      sim_grid_pos_y: 2143267.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444105.062
      sim_grid_pos_y: 2143709.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444291.5
      sim_grid_pos_y: 2144148.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444646.719
      sim_grid_pos_y: 2144576.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445042.375
      sim_grid_pos_y: 2144855.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445253.156
      sim_grid_pos_y: 2145007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 445889
      sim_grid_pos_y: 2145642.75
    }
    terrain_level_point {
      sim_grid_pos_x: 446145.344
      sim_grid_pos_y: 2145326.5
    }
    terrain_level_point {
      sim_grid_pos_x: 446154.562
      sim_grid_pos_y: 2145228
    }
    terrain_level_point {
      sim_grid_pos_x: 446273.156
      sim_grid_pos_y: 2145168
    }
    terrain_level_point {
      sim_grid_pos_x: 446245.281
      sim_grid_pos_y: 2144812
    }
    terrain_level_point {
      sim_grid_pos_x: 445764.812
      sim_grid_pos_y: 2143635.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444737.5
      sim_grid_pos_y: 2143997.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444674.031
      sim_grid_pos_y: 2143774
    }
    terrain_level_point {
      sim_grid_pos_x: 445018.5
      sim_grid_pos_y: 2143639.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444897.812
      sim_grid_pos_y: 2143334.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445407.406
      sim_grid_pos_y: 2143150.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445359.438
      sim_grid_pos_y: 2143006.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445284.594
      sim_grid_pos_y: 2143044
    }
    terrain_level_point {
      sim_grid_pos_x: 445124.844
      sim_grid_pos_y: 2142636.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444900.219
      sim_grid_pos_y: 2142600.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444701.969
      sim_grid_pos_y: 2142679.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444569.344
      sim_grid_pos_y: 2143054.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 444896.688
      sim_grid_pos_y: 2142568.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444677.625
      sim_grid_pos_y: 2142656.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444545.094
      sim_grid_pos_y: 2143031
    }
    terrain_level_point {
      sim_grid_pos_x: 443975.062
      sim_grid_pos_y: 2143247.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444075.594
      sim_grid_pos_y: 2143719
    }
    terrain_level_point {
      sim_grid_pos_x: 444264.938
      sim_grid_pos_y: 2144165
    }
    terrain_level_point {
      sim_grid_pos_x: 444625.656
      sim_grid_pos_y: 2144599.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445024.625
      sim_grid_pos_y: 2144880.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445024.625
      sim_grid_pos_y: 2144880.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445233.156
      sim_grid_pos_y: 2145031
    }
    terrain_level_point {
      sim_grid_pos_x: 445891.406
      sim_grid_pos_y: 2145688.5
    }
    terrain_level_point {
      sim_grid_pos_x: 446175.094
      sim_grid_pos_y: 2145338.75
    }
    terrain_level_point {
      sim_grid_pos_x: 446183.594
      sim_grid_pos_y: 2145247.75
    }
    terrain_level_point {
      sim_grid_pos_x: 446305.438
      sim_grid_pos_y: 2145186.25
    }
    terrain_level_point {
      sim_grid_pos_x: 446275.594
      sim_grid_pos_y: 2144804.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445782.219
      sim_grid_pos_y: 2143597
    }
    terrain_level_point {
      sim_grid_pos_x: 444758.156
      sim_grid_pos_y: 2143957.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444711.25
      sim_grid_pos_y: 2143792.5
    }
    terrain_level_point {
      sim_grid_pos_x: 445058.469
      sim_grid_pos_y: 2143657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444938.062
      sim_grid_pos_y: 2143352.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445446.094
      sim_grid_pos_y: 2143169.5
    }
    terrain_level_point {
      sim_grid_pos_x: 445377.375
      sim_grid_pos_y: 2142963.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445300.938
      sim_grid_pos_y: 2143001.5
    }
    terrain_level_point {
      sim_grid_pos_x: 445147.062
      sim_grid_pos_y: 2142608.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 444893.125
      sim_grid_pos_y: 2142536.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444653.25
      sim_grid_pos_y: 2142632.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444520.844
      sim_grid_pos_y: 2143007.25
    }
    terrain_level_point {
      sim_grid_pos_x: 443939.469
      sim_grid_pos_y: 2143228.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444046.125
      sim_grid_pos_y: 2143728.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444238.406
      sim_grid_pos_y: 2144181.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444604.594
      sim_grid_pos_y: 2144622
    }
    terrain_level_point {
      sim_grid_pos_x: 445006.906
      sim_grid_pos_y: 2144906
    }
    terrain_level_point {
      sim_grid_pos_x: 445006.906
      sim_grid_pos_y: 2144906
    }
    terrain_level_point {
      sim_grid_pos_x: 445213.156
      sim_grid_pos_y: 2145054.5
    }
    terrain_level_point {
      sim_grid_pos_x: 445893.812
      sim_grid_pos_y: 2145734.5
    }
    terrain_level_point {
      sim_grid_pos_x: 446204.844
      sim_grid_pos_y: 2145350.75
    }
    terrain_level_point {
      sim_grid_pos_x: 446212.625
      sim_grid_pos_y: 2145267.5
    }
    terrain_level_point {
      sim_grid_pos_x: 446337.719
      sim_grid_pos_y: 2145204.25
    }
    terrain_level_point {
      sim_grid_pos_x: 446305.875
      sim_grid_pos_y: 2144797.75
    }
    terrain_level_point {
      sim_grid_pos_x: 445799.625
      sim_grid_pos_y: 2143558.25
    }
    terrain_level_point {
      sim_grid_pos_x: 444778.781
      sim_grid_pos_y: 2143917.5
    }
    terrain_level_point {
      sim_grid_pos_x: 444748.5
      sim_grid_pos_y: 2143811
    }
    terrain_level_point {
      sim_grid_pos_x: 445098.438
      sim_grid_pos_y: 2143674.75
    }
    terrain_level_point {
      sim_grid_pos_x: 444978.312
      sim_grid_pos_y: 2143370.5
    }
    terrain_level_point {
      sim_grid_pos_x: 445484.75
      sim_grid_pos_y: 2143188.25
    }
    terrain_level_point {
      sim_grid_pos_x: 445395.344
      sim_grid_pos_y: 2.14292e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 445317.312
      sim_grid_pos_y: 2142959
    }
    terrain_level_point {
      sim_grid_pos_x: 445169.281
      sim_grid_pos_y: 2142581
    }
  }
}
