terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 461533.781
      sim_grid_pos_y: 2036602
    }
    terrain_level_point {
      sim_grid_pos_x: 461726.156
      sim_grid_pos_y: 2037594.12
    }
    terrain_level_point {
      sim_grid_pos_x: 461692.219
      sim_grid_pos_y: 2038102
    }
    terrain_level_point {
      sim_grid_pos_x: 461323.375
      sim_grid_pos_y: 2037857.88
    }
    terrain_level_point {
      sim_grid_pos_x: 460770.594
      sim_grid_pos_y: 2037739.38
    }
    terrain_level_point {
      sim_grid_pos_x: 460869.656
      sim_grid_pos_y: 2037162.25
    }
    terrain_level_point {
      sim_grid_pos_x: 461243.969
      sim_grid_pos_y: 2037174.62
    }
    terrain_level_point {
      sim_grid_pos_x: 461185.219
      sim_grid_pos_y: 2036943.88
    }
    terrain_level_point {
      sim_grid_pos_x: 459704.844
      sim_grid_pos_y: 2037236.75
    }
    terrain_level_point {
      sim_grid_pos_x: 460033.812
      sim_grid_pos_y: 2038756.62
    }
    terrain_level_point {
      sim_grid_pos_x: 457635.531
      sim_grid_pos_y: 2039135.12
    }
    terrain_level_point {
      sim_grid_pos_x: 457270.812
      sim_grid_pos_y: 2039000.5
    }
    terrain_level_point {
      sim_grid_pos_x: 456981.969
      sim_grid_pos_y: 2038735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 456818.219
      sim_grid_pos_y: 2038641
    }
    terrain_level_point {
      sim_grid_pos_x: 456571.625
      sim_grid_pos_y: 2038541.62
    }
    terrain_level_point {
      sim_grid_pos_x: 456403.906
      sim_grid_pos_y: 2038485.25
    }
    terrain_level_point {
      sim_grid_pos_x: 456392.406
      sim_grid_pos_y: 2038127.38
    }
    terrain_level_point {
      sim_grid_pos_x: 456957.969
      sim_grid_pos_y: 2037984.62
    }
    terrain_level_point {
      sim_grid_pos_x: 457012.969
      sim_grid_pos_y: 2037797.12
    }
    terrain_level_point {
      sim_grid_pos_x: 457085.156
      sim_grid_pos_y: 2037678.38
    }
    terrain_level_point {
      sim_grid_pos_x: 457045.312
      sim_grid_pos_y: 2037580.25
    }
    terrain_level_point {
      sim_grid_pos_x: 458615.125
      sim_grid_pos_y: 2037257.5
    }
    terrain_level_point {
      sim_grid_pos_x: 458945.031
      sim_grid_pos_y: 2036800.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459064.125
      sim_grid_pos_y: 2036755.88
    }
    terrain_level_point {
      sim_grid_pos_x: 459232.312
      sim_grid_pos_y: 2036645.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459321.875
      sim_grid_pos_y: 2036704.62
    }
    terrain_level_point {
      sim_grid_pos_x: 459676.531
      sim_grid_pos_y: 2036908
    }
    terrain_level_point {
      sim_grid_pos_x: 459956.281
      sim_grid_pos_y: 2036902.5
    }
    terrain_level_point {
      sim_grid_pos_x: 460202.406
      sim_grid_pos_y: 2036868.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 461746.781
      sim_grid_pos_y: 2037592.88
    }
    terrain_level_point {
      sim_grid_pos_x: 461710.344
      sim_grid_pos_y: 2038138.62
    }
    terrain_level_point {
      sim_grid_pos_x: 461315.281
      sim_grid_pos_y: 2037877.12
    }
    terrain_level_point {
      sim_grid_pos_x: 460747.062
      sim_grid_pos_y: 2037755.25
    }
    terrain_level_point {
      sim_grid_pos_x: 460852.469
      sim_grid_pos_y: 2037141.12
    }
    terrain_level_point {
      sim_grid_pos_x: 461217.375
      sim_grid_pos_y: 2037153.25
    }
    terrain_level_point {
      sim_grid_pos_x: 461170.156
      sim_grid_pos_y: 2036967.75
    }
    terrain_level_point {
      sim_grid_pos_x: 459729.281
      sim_grid_pos_y: 2037252.75
    }
    terrain_level_point {
      sim_grid_pos_x: 460058.438
      sim_grid_pos_y: 2038773.5
    }
    terrain_level_point {
      sim_grid_pos_x: 457633.438
      sim_grid_pos_y: 2039156.25
    }
    terrain_level_point {
      sim_grid_pos_x: 457259.938
      sim_grid_pos_y: 2039018.38
    }
    terrain_level_point {
      sim_grid_pos_x: 456969.781
      sim_grid_pos_y: 2038752.12
    }
    terrain_level_point {
      sim_grid_pos_x: 456809.219
      sim_grid_pos_y: 2038659.5
    }
    terrain_level_point {
      sim_grid_pos_x: 456564.562
      sim_grid_pos_y: 2038560.88
    }
    terrain_level_point {
      sim_grid_pos_x: 456383.875
      sim_grid_pos_y: 2038500.12
    }
    terrain_level_point {
      sim_grid_pos_x: 456371.375
      sim_grid_pos_y: 2038111.5
    }
    terrain_level_point {
      sim_grid_pos_x: 456941.594
      sim_grid_pos_y: 2037967.62
    }
    terrain_level_point {
      sim_grid_pos_x: 456994.062
      sim_grid_pos_y: 2037788.75
    }
    terrain_level_point {
      sim_grid_pos_x: 457062.281
      sim_grid_pos_y: 2037676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 457017.031
      sim_grid_pos_y: 2037565.12
    }
    terrain_level_point {
      sim_grid_pos_x: 458603.188
      sim_grid_pos_y: 2037239
    }
    terrain_level_point {
      sim_grid_pos_x: 458932.031
      sim_grid_pos_y: 2036783.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459054.812
      sim_grid_pos_y: 2036737.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459232.344
      sim_grid_pos_y: 2036621
    }
    terrain_level_point {
      sim_grid_pos_x: 459332.594
      sim_grid_pos_y: 2036687.12
    }
    terrain_level_point {
      sim_grid_pos_x: 459681.812
      sim_grid_pos_y: 2036887.38
    }
    terrain_level_point {
      sim_grid_pos_x: 459954.625
      sim_grid_pos_y: 2036882
    }
    terrain_level_point {
      sim_grid_pos_x: 460199
      sim_grid_pos_y: 2036848.5
    }
    terrain_level_point {
      sim_grid_pos_x: 461549.969
      sim_grid_pos_y: 2036577.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 461767.438
      sim_grid_pos_y: 2037591.5
    }
    terrain_level_point {
      sim_grid_pos_x: 461728.438
      sim_grid_pos_y: 2038175.12
    }
    terrain_level_point {
      sim_grid_pos_x: 461307.188
      sim_grid_pos_y: 2037896.38
    }
    terrain_level_point {
      sim_grid_pos_x: 460723.5
      sim_grid_pos_y: 2037771.25
    }
    terrain_level_point {
      sim_grid_pos_x: 460835.281
      sim_grid_pos_y: 2037120.12
    }
    terrain_level_point {
      sim_grid_pos_x: 461190.75
      sim_grid_pos_y: 2037131.88
    }
    terrain_level_point {
      sim_grid_pos_x: 461155.062
      sim_grid_pos_y: 2036991.62
    }
    terrain_level_point {
      sim_grid_pos_x: 459753.75
      sim_grid_pos_y: 2037268.88
    }
    terrain_level_point {
      sim_grid_pos_x: 460083.062
      sim_grid_pos_y: 2038790.38
    }
    terrain_level_point {
      sim_grid_pos_x: 457631.375
      sim_grid_pos_y: 2039177.25
    }
    terrain_level_point {
      sim_grid_pos_x: 457249.031
      sim_grid_pos_y: 2039036.12
    }
    terrain_level_point {
      sim_grid_pos_x: 456957.594
      sim_grid_pos_y: 2038768.75
    }
    terrain_level_point {
      sim_grid_pos_x: 456800.219
      sim_grid_pos_y: 2038678
    }
    terrain_level_point {
      sim_grid_pos_x: 456557.344
      sim_grid_pos_y: 2038580.12
    }
    terrain_level_point {
      sim_grid_pos_x: 456363.844
      sim_grid_pos_y: 2038515
    }
    terrain_level_point {
      sim_grid_pos_x: 456350.344
      sim_grid_pos_y: 2038095.75
    }
    terrain_level_point {
      sim_grid_pos_x: 456925.219
      sim_grid_pos_y: 2037950.62
    }
    terrain_level_point {
      sim_grid_pos_x: 456975.125
      sim_grid_pos_y: 2037780.38
    }
    terrain_level_point {
      sim_grid_pos_x: 457039.406
      sim_grid_pos_y: 2037674.75
    }
    terrain_level_point {
      sim_grid_pos_x: 456988.781
      sim_grid_pos_y: 2.03755e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 458591.219
      sim_grid_pos_y: 2037220.5
    }
    terrain_level_point {
      sim_grid_pos_x: 458919.031
      sim_grid_pos_y: 2036766.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459045.438
      sim_grid_pos_y: 2036719.12
    }
    terrain_level_point {
      sim_grid_pos_x: 459232.375
      sim_grid_pos_y: 2036596.38
    }
    terrain_level_point {
      sim_grid_pos_x: 459343.375
      sim_grid_pos_y: 2036669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 459687.094
      sim_grid_pos_y: 2036866.75
    }
    terrain_level_point {
      sim_grid_pos_x: 459953.062
      sim_grid_pos_y: 2036861.5
    }
    terrain_level_point {
      sim_grid_pos_x: 460195.594
      sim_grid_pos_y: 2036828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 461566.188
      sim_grid_pos_y: 2036553.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 461788.062
      sim_grid_pos_y: 2037590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 461746.531
      sim_grid_pos_y: 2038211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 461299.094
      sim_grid_pos_y: 2037915.62
    }
    terrain_level_point {
      sim_grid_pos_x: 460699.969
      sim_grid_pos_y: 2037787.12
    }
    terrain_level_point {
      sim_grid_pos_x: 460818.094
      sim_grid_pos_y: 2037099
    }
    terrain_level_point {
      sim_grid_pos_x: 461164.156
      sim_grid_pos_y: 2037110.5
    }
    terrain_level_point {
      sim_grid_pos_x: 461140
      sim_grid_pos_y: 2037015.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459778.188
      sim_grid_pos_y: 2037285
    }
    terrain_level_point {
      sim_grid_pos_x: 460107.719
      sim_grid_pos_y: 2038807.25
    }
    terrain_level_point {
      sim_grid_pos_x: 457629.281
      sim_grid_pos_y: 2039198.38
    }
    terrain_level_point {
      sim_grid_pos_x: 457238.156
      sim_grid_pos_y: 2039054
    }
    terrain_level_point {
      sim_grid_pos_x: 456945.375
      sim_grid_pos_y: 2038785.38
    }
    terrain_level_point {
      sim_grid_pos_x: 456791.219
      sim_grid_pos_y: 2038696.5
    }
    terrain_level_point {
      sim_grid_pos_x: 456550.281
      sim_grid_pos_y: 2038599.38
    }
    terrain_level_point {
      sim_grid_pos_x: 456343.781
      sim_grid_pos_y: 2.03853e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 456329.344
      sim_grid_pos_y: 2038079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 456908.844
      sim_grid_pos_y: 2037933.62
    }
    terrain_level_point {
      sim_grid_pos_x: 456956.219
      sim_grid_pos_y: 2037772.12
    }
    terrain_level_point {
      sim_grid_pos_x: 457016.531
      sim_grid_pos_y: 2037672.88
    }
    terrain_level_point {
      sim_grid_pos_x: 456960.5
      sim_grid_pos_y: 2037534.88
    }
    terrain_level_point {
      sim_grid_pos_x: 458579.281
      sim_grid_pos_y: 2037202
    }
    terrain_level_point {
      sim_grid_pos_x: 458906.031
      sim_grid_pos_y: 2036749.38
    }
    terrain_level_point {
      sim_grid_pos_x: 459036.125
      sim_grid_pos_y: 2036700.62
    }
    terrain_level_point {
      sim_grid_pos_x: 459232.406
      sim_grid_pos_y: 2036571.88
    }
    terrain_level_point {
      sim_grid_pos_x: 459354.219
      sim_grid_pos_y: 2036652.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459692.344
      sim_grid_pos_y: 2036846.12
    }
    terrain_level_point {
      sim_grid_pos_x: 459951.406
      sim_grid_pos_y: 2036841.12
    }
    terrain_level_point {
      sim_grid_pos_x: 460192.219
      sim_grid_pos_y: 2036808
    }
    terrain_level_point {
      sim_grid_pos_x: 461582.406
      sim_grid_pos_y: 2036529.5
    }
  }
}
