terrain_level_data {
  terrain_level: 145
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1240405.38
      sim_grid_pos_y: 1532895.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1239165.62
      sim_grid_pos_y: 1533459.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1238171.88
      sim_grid_pos_y: 1531290.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1239277.5
      sim_grid_pos_y: 1530627.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1240447.12
      sim_grid_pos_y: 1532910.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1239150.5
      sim_grid_pos_y: 1533500.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1238132.38
      sim_grid_pos_y: 1531278.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1239290.25
      sim_grid_pos_y: 1530583.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1240488.88
      sim_grid_pos_y: 1532924.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1239135.25
      sim_grid_pos_y: 1533541.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1238093
      sim_grid_pos_y: 1531266
    }
    terrain_level_point {
      sim_grid_pos_x: 1239302.88
      sim_grid_pos_y: 1530540.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1240530.5
      sim_grid_pos_y: 1532939.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1239120.12
      sim_grid_pos_y: 1533581.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1238053.5
      sim_grid_pos_y: 1531253.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1239315.62
      sim_grid_pos_y: 1530496.62
    }
  }
}
