terrain_level_data {
  terrain_level: 130
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2927478.5
      sim_grid_pos_y: 540725.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2927838.5
      sim_grid_pos_y: 541302.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2928504.5
      sim_grid_pos_y: 542057
    }
    terrain_level_point {
      sim_grid_pos_x: 2931783.5
      sim_grid_pos_y: 545619.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2931605.25
      sim_grid_pos_y: 545685.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2927242.5
      sim_grid_pos_y: 540825.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2927855
      sim_grid_pos_y: 541290.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2928519.5
      sim_grid_pos_y: 542043.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2931819.25
      sim_grid_pos_y: 545628.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2931599.25
      sim_grid_pos_y: 545709.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2927208
      sim_grid_pos_y: 540818.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2927486.5
      sim_grid_pos_y: 540700
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2927871.5
      sim_grid_pos_y: 541278
    }
    terrain_level_point {
      sim_grid_pos_x: 2928535
      sim_grid_pos_y: 542029.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2931855.25
      sim_grid_pos_y: 545637
    }
    terrain_level_point {
      sim_grid_pos_x: 2931593.25
      sim_grid_pos_y: 545734.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2927173.75
      sim_grid_pos_y: 540810.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2927494.75
      sim_grid_pos_y: 540674.25
    }
  }
}
terrain_level_data {
  terrain_level: 130
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2927423.25
      sim_grid_pos_y: 540730.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2928879.5
      sim_grid_pos_y: 540333
    }
    terrain_level_point {
      sim_grid_pos_x: 2928929.25
      sim_grid_pos_y: 540402.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2927467.5
      sim_grid_pos_y: 540802.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2928946.25
      sim_grid_pos_y: 540408.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2927462.75
      sim_grid_pos_y: 540814.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2927407.25
      sim_grid_pos_y: 540724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2928883.75
      sim_grid_pos_y: 540321.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2928963.25
      sim_grid_pos_y: 540414.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2927458
      sim_grid_pos_y: 540826.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2927391.5
      sim_grid_pos_y: 540718
    }
    terrain_level_point {
      sim_grid_pos_x: 2928887.75
      sim_grid_pos_y: 540309.438
    }
  }
}
