terrain_level_data {
  terrain_level: 35
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1308372.5
      sim_grid_pos_y: 1440450.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307620.5
      sim_grid_pos_y: 1442281.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307371
      sim_grid_pos_y: 1442813.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1306127.62
      sim_grid_pos_y: 1444285.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1306104.38
      sim_grid_pos_y: 1444979.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308500.38
      sim_grid_pos_y: 1445709.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1312061.25
      sim_grid_pos_y: 1441874.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1311049.12
      sim_grid_pos_y: 1440878.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1311155.5
      sim_grid_pos_y: 1440538.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1308352.25
      sim_grid_pos_y: 1440419.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1307592.38
      sim_grid_pos_y: 1442269.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1307344.88
      sim_grid_pos_y: 1442796.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1306097.25
      sim_grid_pos_y: 1444273.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1306072.88
      sim_grid_pos_y: 1445002
    }
    terrain_level_point {
      sim_grid_pos_x: 1308509.88
      sim_grid_pos_y: 1445744.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1312104.12
      sim_grid_pos_y: 1441873.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1311084.12
      sim_grid_pos_y: 1440870.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1311197
      sim_grid_pos_y: 1440509.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1308331.88
      sim_grid_pos_y: 1440388
    }
    terrain_level_point {
      sim_grid_pos_x: 1307564.25
      sim_grid_pos_y: 1442256.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307318.75
      sim_grid_pos_y: 1.44278e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1306066.75
      sim_grid_pos_y: 1444262
    }
    terrain_level_point {
      sim_grid_pos_x: 1306041.38
      sim_grid_pos_y: 1445024.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1308519.38
      sim_grid_pos_y: 1445779.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1312147
      sim_grid_pos_y: 1441872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1311119
      sim_grid_pos_y: 1440861.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1311238.5
      sim_grid_pos_y: 1440479.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1308311.5
      sim_grid_pos_y: 1440356.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1307536.12
      sim_grid_pos_y: 1442244.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1307292.62
      sim_grid_pos_y: 1442763.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1306036.38
      sim_grid_pos_y: 1444250.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1306009.88
      sim_grid_pos_y: 1445047
    }
    terrain_level_point {
      sim_grid_pos_x: 1308528.75
      sim_grid_pos_y: 1445814.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1312189.88
      sim_grid_pos_y: 1441871.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1311154
      sim_grid_pos_y: 1440852.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1311279.88
      sim_grid_pos_y: 1440450.38
    }
  }
}
