terrain_level_data {
  terrain_level: 1360
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2972223.5
      sim_grid_pos_y: 1197832.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2974582.5
      sim_grid_pos_y: 1199786.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2974414.5
      sim_grid_pos_y: 1200351.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2977109.25
      sim_grid_pos_y: 1202582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2977322
      sim_grid_pos_y: 1203678.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2978899
      sim_grid_pos_y: 1204667.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2979839
      sim_grid_pos_y: 1204371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2981197.5
      sim_grid_pos_y: 1203599.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2982197.25
      sim_grid_pos_y: 1202641.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2980176
      sim_grid_pos_y: 1200411.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2978905.5
      sim_grid_pos_y: 1199641.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2978083.75
      sim_grid_pos_y: 1199532.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2977287
      sim_grid_pos_y: 1198881
    }
    terrain_level_point {
      sim_grid_pos_x: 2976593
      sim_grid_pos_y: 1197395.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2973041.75
      sim_grid_pos_y: 1196222
    }
    terrain_level_point {
      sim_grid_pos_x: 2971971
      sim_grid_pos_y: 1196721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2971549
      sim_grid_pos_y: 1197275.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2973038.5
      sim_grid_pos_y: 1196166.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2971938
      sim_grid_pos_y: 1196680.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2971478.25
      sim_grid_pos_y: 1197283.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2972190.75
      sim_grid_pos_y: 1197872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2972190.75
      sim_grid_pos_y: 1197872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2974523.75
      sim_grid_pos_y: 1199804.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2974355.75
      sim_grid_pos_y: 1200369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2977062.25
      sim_grid_pos_y: 1202610.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2977276
      sim_grid_pos_y: 1203710.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2978892
      sim_grid_pos_y: 1204723.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2979859.5
      sim_grid_pos_y: 1204418.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2981228.25
      sim_grid_pos_y: 1203641.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2982268.75
      sim_grid_pos_y: 1202643.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2980209
      sim_grid_pos_y: 1200371.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2978923
      sim_grid_pos_y: 1199591.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2978105
      sim_grid_pos_y: 1199483.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2977328.5
      sim_grid_pos_y: 1198848.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.97663e+06
      sim_grid_pos_y: 1197353.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2973035.25
      sim_grid_pos_y: 1196111.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2971904.75
      sim_grid_pos_y: 1196639.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2971407.75
      sim_grid_pos_y: 1197291.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2972158
      sim_grid_pos_y: 1197911.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2972158
      sim_grid_pos_y: 1197911.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2974465
      sim_grid_pos_y: 1199822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2974297
      sim_grid_pos_y: 1200387.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2977015.5
      sim_grid_pos_y: 1202637.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.97723e+06
      sim_grid_pos_y: 1203742
    }
    terrain_level_point {
      sim_grid_pos_x: 2978884.75
      sim_grid_pos_y: 1204779.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2979880.25
      sim_grid_pos_y: 1204465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2981259.25
      sim_grid_pos_y: 1203682.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2982340.25
      sim_grid_pos_y: 1202646.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2980241.75
      sim_grid_pos_y: 1200331.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2978940.25
      sim_grid_pos_y: 1199542.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2978126.25
      sim_grid_pos_y: 1199434.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.97737e+06
      sim_grid_pos_y: 1198816.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2976667.25
      sim_grid_pos_y: 1197311.75
    }
  }
}
