terrain_level_data {
  terrain_level: 56
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1319447.38
      sim_grid_pos_y: 1453752.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1322682.75
      sim_grid_pos_y: 1453982.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1322863.75
      sim_grid_pos_y: 1450653.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1319710.62
      sim_grid_pos_y: 1450395.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1319682.38
      sim_grid_pos_y: 1450362.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1319414.25
      sim_grid_pos_y: 1453781.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1322711.75
      sim_grid_pos_y: 1454015.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1322896.12
      sim_grid_pos_y: 1450625.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1319654.12
      sim_grid_pos_y: 1450329
    }
    terrain_level_point {
      sim_grid_pos_x: 1319381.25
      sim_grid_pos_y: 1453809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1322740.75
      sim_grid_pos_y: 1454048.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1322928.38
      sim_grid_pos_y: 1450597
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1319625.88
      sim_grid_pos_y: 1450295.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1319348.12
      sim_grid_pos_y: 1453838
    }
    terrain_level_point {
      sim_grid_pos_x: 1322769.75
      sim_grid_pos_y: 1454081.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1322960.75
      sim_grid_pos_y: 1450568.88
    }
  }
}
