terrain_level_data {
  terrain_level: 1235
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1440539.62
      sim_grid_pos_y: 1516731.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1440413.12
      sim_grid_pos_y: 1516899.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1440246.5
      sim_grid_pos_y: 1517070.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1440260.25
      sim_grid_pos_y: 1517229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1440516
      sim_grid_pos_y: 1517207.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1440786.62
      sim_grid_pos_y: 1517190.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1441041.75
      sim_grid_pos_y: 1517038.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1441202.88
      sim_grid_pos_y: 1516817.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1441013.88
      sim_grid_pos_y: 1516715.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1441026
      sim_grid_pos_y: 1516664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1440513.38
      sim_grid_pos_y: 1516681.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1440374.25
      sim_grid_pos_y: 1516865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1440193.38
      sim_grid_pos_y: 1517051.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1440213.62
      sim_grid_pos_y: 1517285
    }
    terrain_level_point {
      sim_grid_pos_x: 1440519.62
      sim_grid_pos_y: 1517258.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1440802.25
      sim_grid_pos_y: 1517240.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1441077
      sim_grid_pos_y: 1517077.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1441279
      sim_grid_pos_y: 1516800.12
    }
  }
}
terrain_level_data {
  terrain_level: 1207
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1440014.5
      sim_grid_pos_y: 1518056.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1440121.25
      sim_grid_pos_y: 1518149
    }
    terrain_level_point {
      sim_grid_pos_x: 1440563.12
      sim_grid_pos_y: 1517395.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1440370.25
      sim_grid_pos_y: 1517360.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1440341.88
      sim_grid_pos_y: 1517303.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1439950.62
      sim_grid_pos_y: 1518068.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1440134.25
      sim_grid_pos_y: 1518228.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1440644.5
      sim_grid_pos_y: 1517358
    }
  }
}
terrain_level_data {
  terrain_level: 978
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1439472
      sim_grid_pos_y: 1516162.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1439589.62
      sim_grid_pos_y: 1516492.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1439753
      sim_grid_pos_y: 1516394.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1439611.88
      sim_grid_pos_y: 1516086.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1439635.5
      sim_grid_pos_y: 1516015.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1439409
      sim_grid_pos_y: 1516138.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1439562.38
      sim_grid_pos_y: 1516568.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1439818.75
      sim_grid_pos_y: 1516414.62
    }
  }
}
