terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1963387.88
      sim_grid_pos_y: 1628086.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1963952.88
      sim_grid_pos_y: 1627004.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1963547.38
      sim_grid_pos_y: 1627106.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1963028.88
      sim_grid_pos_y: 1627193.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1962650.75
      sim_grid_pos_y: 1627227.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1962460.38
      sim_grid_pos_y: 1627294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1962277.25
      sim_grid_pos_y: 1627426
    }
    terrain_level_point {
      sim_grid_pos_x: 1961300.5
      sim_grid_pos_y: 1627794.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1960891.5
      sim_grid_pos_y: 1627834.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1959613.75
      sim_grid_pos_y: 1628664.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958571.38
      sim_grid_pos_y: 1629180.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1958194.12
      sim_grid_pos_y: 1629954
    }
    terrain_level_point {
      sim_grid_pos_x: 1958172.25
      sim_grid_pos_y: 1630437.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1958013.75
      sim_grid_pos_y: 1630825.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958104.5
      sim_grid_pos_y: 1630874.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958156.88
      sim_grid_pos_y: 1630790.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1958564.62
      sim_grid_pos_y: 1630412.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1958761.5
      sim_grid_pos_y: 1630454.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1958855.75
      sim_grid_pos_y: 1630231.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1959005.25
      sim_grid_pos_y: 1630165.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1962748
      sim_grid_pos_y: 1628006.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1964004.25
      sim_grid_pos_y: 1626854.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1963520.12
      sim_grid_pos_y: 1626975.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1963011.75
      sim_grid_pos_y: 1627061.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1962622.25
      sim_grid_pos_y: 1627096.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1962398.12
      sim_grid_pos_y: 1627175.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1962213.75
      sim_grid_pos_y: 1627307.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.96127e+06
      sim_grid_pos_y: 1627663.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1960846.12
      sim_grid_pos_y: 1627704.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1959547.62
      sim_grid_pos_y: 1628548.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958471.5
      sim_grid_pos_y: 1629081
    }
    terrain_level_point {
      sim_grid_pos_x: 1958062.25
      sim_grid_pos_y: 1629920.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1958040.25
      sim_grid_pos_y: 1630408.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1957845
      sim_grid_pos_y: 1630885.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1958151.12
      sim_grid_pos_y: 1631050.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1958260.38
      sim_grid_pos_y: 1630876.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1958604.5
      sim_grid_pos_y: 1630557.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1958841.38
      sim_grid_pos_y: 1630607.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1958958
      sim_grid_pos_y: 1630332.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1959065.75
      sim_grid_pos_y: 1630284.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1962775.88
      sim_grid_pos_y: 1628144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1963463.12
      sim_grid_pos_y: 1628230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1964111
      sim_grid_pos_y: 1626990.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1964055.5
      sim_grid_pos_y: 1626704.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1963492.75
      sim_grid_pos_y: 1626845.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1962994.88
      sim_grid_pos_y: 1626929.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1962593.75
      sim_grid_pos_y: 1626964.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1962335.88
      sim_grid_pos_y: 1627055.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1962150.38
      sim_grid_pos_y: 1627189
    }
    terrain_level_point {
      sim_grid_pos_x: 1961239.5
      sim_grid_pos_y: 1627532.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1960800.88
      sim_grid_pos_y: 1627575.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1959481.5
      sim_grid_pos_y: 1628432.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958371.62
      sim_grid_pos_y: 1628981.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1957930.38
      sim_grid_pos_y: 1629886.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1957908.12
      sim_grid_pos_y: 1630379
    }
    terrain_level_point {
      sim_grid_pos_x: 1957676.38
      sim_grid_pos_y: 1630946.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958197.75
      sim_grid_pos_y: 1631227.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1958364
      sim_grid_pos_y: 1630962.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958644.5
      sim_grid_pos_y: 1630702.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1958921.25
      sim_grid_pos_y: 1630761
    }
    terrain_level_point {
      sim_grid_pos_x: 1959060.25
      sim_grid_pos_y: 1630432.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1959126.25
      sim_grid_pos_y: 1630403.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1962803.75
      sim_grid_pos_y: 1628282
    }
    terrain_level_point {
      sim_grid_pos_x: 1963538.5
      sim_grid_pos_y: 1628374
    }
    terrain_level_point {
      sim_grid_pos_x: 1964269
      sim_grid_pos_y: 1626975.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1964106.88
      sim_grid_pos_y: 1626554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1963465.5
      sim_grid_pos_y: 1626714.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1962977.75
      sim_grid_pos_y: 1626797
    }
    terrain_level_point {
      sim_grid_pos_x: 1962565.25
      sim_grid_pos_y: 1626833.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1962273.62
      sim_grid_pos_y: 1626936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1962086.88
      sim_grid_pos_y: 1627070.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1961209
      sim_grid_pos_y: 1627401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1960755.62
      sim_grid_pos_y: 1627445.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1959415.38
      sim_grid_pos_y: 1628316.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1958271.62
      sim_grid_pos_y: 1628882.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1957798.5
      sim_grid_pos_y: 1629853.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1957776
      sim_grid_pos_y: 1.63035e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1957507.62
      sim_grid_pos_y: 1631006.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1958244.38
      sim_grid_pos_y: 1631403.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1958467.5
      sim_grid_pos_y: 1631047.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1958684.38
      sim_grid_pos_y: 1630847
    }
    terrain_level_point {
      sim_grid_pos_x: 1959001.12
      sim_grid_pos_y: 1630914.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1959162.38
      sim_grid_pos_y: 1630533.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1959186.75
      sim_grid_pos_y: 1630522.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1962831.5
      sim_grid_pos_y: 1628419.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1963613.75
      sim_grid_pos_y: 1628517.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1964427.12
      sim_grid_pos_y: 1626960.62
    }
  }
}
