terrain_level_data {
  terrain_level: 26
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 435693.375
      sim_grid_pos_y: 1848732
    }
    terrain_level_point {
      sim_grid_pos_x: 434522.5
      sim_grid_pos_y: 1849582.88
    }
    terrain_level_point {
      sim_grid_pos_x: 432845.844
      sim_grid_pos_y: 1849062.62
    }
    terrain_level_point {
      sim_grid_pos_x: 432130.812
      sim_grid_pos_y: 1849309.25
    }
    terrain_level_point {
      sim_grid_pos_x: 431644.875
      sim_grid_pos_y: 1849291.62
    }
    terrain_level_point {
      sim_grid_pos_x: 432884.656
      sim_grid_pos_y: 1845146.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434084.094
      sim_grid_pos_y: 1846489
    }
    terrain_level_point {
      sim_grid_pos_x: 434945.875
      sim_grid_pos_y: 1847718.12
    }
    terrain_level_point {
      sim_grid_pos_x: 435253.344
      sim_grid_pos_y: 1847522.75
    }
    terrain_level_point {
      sim_grid_pos_x: 435090.062
      sim_grid_pos_y: 1846439.25
    }
    terrain_level_point {
      sim_grid_pos_x: 435667.781
      sim_grid_pos_y: 1846042.25
    }
    terrain_level_point {
      sim_grid_pos_x: 436162.812
      sim_grid_pos_y: 1845474.88
    }
    terrain_level_point {
      sim_grid_pos_x: 437728.219
      sim_grid_pos_y: 1846030.12
    }
    terrain_level_point {
      sim_grid_pos_x: 438700.969
      sim_grid_pos_y: 1846513.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440189.031
      sim_grid_pos_y: 1847357.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440443.188
      sim_grid_pos_y: 1847664.88
    }
    terrain_level_point {
      sim_grid_pos_x: 440553.625
      sim_grid_pos_y: 1848086
    }
    terrain_level_point {
      sim_grid_pos_x: 440638.562
      sim_grid_pos_y: 1848795.88
    }
    terrain_level_point {
      sim_grid_pos_x: 442298.312
      sim_grid_pos_y: 1852234.75
    }
    terrain_level_point {
      sim_grid_pos_x: 442255.531
      sim_grid_pos_y: 1852551.75
    }
    terrain_level_point {
      sim_grid_pos_x: 441987.031
      sim_grid_pos_y: 1854542.25
    }
    terrain_level_point {
      sim_grid_pos_x: 441666.438
      sim_grid_pos_y: 1855965.5
    }
    terrain_level_point {
      sim_grid_pos_x: 440905.781
      sim_grid_pos_y: 1855682.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440264.125
      sim_grid_pos_y: 1855643.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439529.875
      sim_grid_pos_y: 1855007.12
    }
    terrain_level_point {
      sim_grid_pos_x: 435783.094
      sim_grid_pos_y: 1854135.75
    }
    terrain_level_point {
      sim_grid_pos_x: 435902.812
      sim_grid_pos_y: 1853104
    }
    terrain_level_point {
      sim_grid_pos_x: 436553.094
      sim_grid_pos_y: 1852332.75
    }
    terrain_level_point {
      sim_grid_pos_x: 436877.406
      sim_grid_pos_y: 1851427.75
    }
    terrain_level_point {
      sim_grid_pos_x: 436970.75
      sim_grid_pos_y: 1850677.25
    }
    terrain_level_point {
      sim_grid_pos_x: 436945.281
      sim_grid_pos_y: 1850519.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436646.062
      sim_grid_pos_y: 1850878.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436512.219
      sim_grid_pos_y: 1851972.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436309.094
      sim_grid_pos_y: 1852313.12
    }
    terrain_level_point {
      sim_grid_pos_x: 435854.531
      sim_grid_pos_y: 1.85254e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 435378.812
      sim_grid_pos_y: 1851469.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436601.5
      sim_grid_pos_y: 1850395.25
    }
    terrain_level_point {
      sim_grid_pos_x: 436826.531
      sim_grid_pos_y: 1850141.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436675.312
      sim_grid_pos_y: 1849846.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436187.188
      sim_grid_pos_y: 1849066
    }
    terrain_level_point {
      sim_grid_pos_x: 435359.281
      sim_grid_pos_y: 1847844
    }
    terrain_level_point {
      sim_grid_pos_x: 435161.344
      sim_grid_pos_y: 1848017.75
    }
    terrain_level_point {
      sim_grid_pos_x: 435226.594
      sim_grid_pos_y: 1848115.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 434100.188
      sim_grid_pos_y: 1846476.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434951.406
      sim_grid_pos_y: 1847690.38
    }
    terrain_level_point {
      sim_grid_pos_x: 435231.062
      sim_grid_pos_y: 1847512.62
    }
    terrain_level_point {
      sim_grid_pos_x: 435067.875
      sim_grid_pos_y: 1846429.62
    }
    terrain_level_point {
      sim_grid_pos_x: 435654.031
      sim_grid_pos_y: 1846026.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436156.531
      sim_grid_pos_y: 1845450.88
    }
    terrain_level_point {
      sim_grid_pos_x: 437736.25
      sim_grid_pos_y: 1846011.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438710.594
      sim_grid_pos_y: 1846495.12
    }
    terrain_level_point {
      sim_grid_pos_x: 440202.438
      sim_grid_pos_y: 1847341.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440461.875
      sim_grid_pos_y: 1847655.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440573.812
      sim_grid_pos_y: 1848082.12
    }
    terrain_level_point {
      sim_grid_pos_x: 440658.5
      sim_grid_pos_y: 1.84879e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 442319.469
      sim_grid_pos_y: 1852231.38
    }
    terrain_level_point {
      sim_grid_pos_x: 442275.844
      sim_grid_pos_y: 1852554.5
    }
    terrain_level_point {
      sim_grid_pos_x: 442007.219
      sim_grid_pos_y: 1854545.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441681.281
      sim_grid_pos_y: 1855992.88
    }
    terrain_level_point {
      sim_grid_pos_x: 440901.469
      sim_grid_pos_y: 1855702.5
    }
    terrain_level_point {
      sim_grid_pos_x: 440255.938
      sim_grid_pos_y: 1855663.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439520.281
      sim_grid_pos_y: 1855025.88
    }
    terrain_level_point {
      sim_grid_pos_x: 435760.625
      sim_grid_pos_y: 1854151.62
    }
    terrain_level_point {
      sim_grid_pos_x: 435883.156
      sim_grid_pos_y: 1853095.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436535.062
      sim_grid_pos_y: 1852322.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436857.344
      sim_grid_pos_y: 1851423
    }
    terrain_level_point {
      sim_grid_pos_x: 436950.031
      sim_grid_pos_y: 1850677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 436932.219
      sim_grid_pos_y: 1850567.25
    }
    terrain_level_point {
      sim_grid_pos_x: 436665.656
      sim_grid_pos_y: 1850886.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436532.062
      sim_grid_pos_y: 1851979.62
    }
    terrain_level_point {
      sim_grid_pos_x: 436323.625
      sim_grid_pos_y: 1852328.75
    }
    terrain_level_point {
      sim_grid_pos_x: 435844.5
      sim_grid_pos_y: 1852567.88
    }
    terrain_level_point {
      sim_grid_pos_x: 435353.938
      sim_grid_pos_y: 1851464.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436587
      sim_grid_pos_y: 1850380.75
    }
    terrain_level_point {
      sim_grid_pos_x: 436801.875
      sim_grid_pos_y: 1850138.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436657.469
      sim_grid_pos_y: 1849856.62
    }
    terrain_level_point {
      sim_grid_pos_x: 436170
      sim_grid_pos_y: 1849077.25
    }
    terrain_level_point {
      sim_grid_pos_x: 435355.344
      sim_grid_pos_y: 1847874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 435188.375
      sim_grid_pos_y: 1848021.25
    }
    terrain_level_point {
      sim_grid_pos_x: 435243.312
      sim_grid_pos_y: 1848103.62
    }
    terrain_level_point {
      sim_grid_pos_x: 435722.344
      sim_grid_pos_y: 1848736.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434526.25
      sim_grid_pos_y: 1849605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432846.188
      sim_grid_pos_y: 1849084.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432133.875
      sim_grid_pos_y: 1849329.88
    }
    terrain_level_point {
      sim_grid_pos_x: 431617.625
      sim_grid_pos_y: 1849311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 432868.438
      sim_grid_pos_y: 1845129.38
    }
    terrain_level_point {
      sim_grid_pos_x: 432891.938
      sim_grid_pos_y: 1845124.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 434116.281
      sim_grid_pos_y: 1846463.5
    }
    terrain_level_point {
      sim_grid_pos_x: 434956.969
      sim_grid_pos_y: 1847662.5
    }
    terrain_level_point {
      sim_grid_pos_x: 435208.812
      sim_grid_pos_y: 1847502.5
    }
    terrain_level_point {
      sim_grid_pos_x: 435045.688
      sim_grid_pos_y: 1.84642e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 435640.312
      sim_grid_pos_y: 1846011.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436150.25
      sim_grid_pos_y: 1845426.88
    }
    terrain_level_point {
      sim_grid_pos_x: 437744.25
      sim_grid_pos_y: 1845992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438720.219
      sim_grid_pos_y: 1846477
    }
    terrain_level_point {
      sim_grid_pos_x: 440215.844
      sim_grid_pos_y: 1847325.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440480.562
      sim_grid_pos_y: 1847645.75
    }
    terrain_level_point {
      sim_grid_pos_x: 440594
      sim_grid_pos_y: 1848078.38
    }
    terrain_level_point {
      sim_grid_pos_x: 440678.469
      sim_grid_pos_y: 1848784.25
    }
    terrain_level_point {
      sim_grid_pos_x: 442340.594
      sim_grid_pos_y: 1852228
    }
    terrain_level_point {
      sim_grid_pos_x: 442296.156
      sim_grid_pos_y: 1852557.25
    }
    terrain_level_point {
      sim_grid_pos_x: 442027.438
      sim_grid_pos_y: 1854549.5
    }
    terrain_level_point {
      sim_grid_pos_x: 441696.125
      sim_grid_pos_y: 1856020.38
    }
    terrain_level_point {
      sim_grid_pos_x: 440897.219
      sim_grid_pos_y: 1855722.88
    }
    terrain_level_point {
      sim_grid_pos_x: 440247.781
      sim_grid_pos_y: 1855683.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439510.656
      sim_grid_pos_y: 1855044.75
    }
    terrain_level_point {
      sim_grid_pos_x: 435738.125
      sim_grid_pos_y: 1854167.38
    }
    terrain_level_point {
      sim_grid_pos_x: 435863.5
      sim_grid_pos_y: 1853087
    }
    terrain_level_point {
      sim_grid_pos_x: 436516.969
      sim_grid_pos_y: 1852312
    }
    terrain_level_point {
      sim_grid_pos_x: 436837.281
      sim_grid_pos_y: 1851418.12
    }
    terrain_level_point {
      sim_grid_pos_x: 436929.312
      sim_grid_pos_y: 1850678
    }
    terrain_level_point {
      sim_grid_pos_x: 436919.125
      sim_grid_pos_y: 1850614.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436685.312
      sim_grid_pos_y: 1850895.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436551.875
      sim_grid_pos_y: 1851986.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436338.156
      sim_grid_pos_y: 1852344.5
    }
    terrain_level_point {
      sim_grid_pos_x: 435834.469
      sim_grid_pos_y: 1852595.88
    }
    terrain_level_point {
      sim_grid_pos_x: 435329.094
      sim_grid_pos_y: 1851459
    }
    terrain_level_point {
      sim_grid_pos_x: 436572.5
      sim_grid_pos_y: 1850366.12
    }
    terrain_level_point {
      sim_grid_pos_x: 436777.25
      sim_grid_pos_y: 1850135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 436639.656
      sim_grid_pos_y: 1849866.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436152.75
      sim_grid_pos_y: 1849088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 435351.406
      sim_grid_pos_y: 1847905.5
    }
    terrain_level_point {
      sim_grid_pos_x: 435215.406
      sim_grid_pos_y: 1848024.88
    }
    terrain_level_point {
      sim_grid_pos_x: 435259.938
      sim_grid_pos_y: 1848091.62
    }
    terrain_level_point {
      sim_grid_pos_x: 435751.312
      sim_grid_pos_y: 1848740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 434529.969
      sim_grid_pos_y: 1849628.12
    }
    terrain_level_point {
      sim_grid_pos_x: 432846.531
      sim_grid_pos_y: 1849105.75
    }
    terrain_level_point {
      sim_grid_pos_x: 432136.969
      sim_grid_pos_y: 1849350.5
    }
    terrain_level_point {
      sim_grid_pos_x: 431590.375
      sim_grid_pos_y: 1849330.62
    }
    terrain_level_point {
      sim_grid_pos_x: 432852.25
      sim_grid_pos_y: 1845112
    }
    terrain_level_point {
      sim_grid_pos_x: 432899.188
      sim_grid_pos_y: 1845101.5
    }
  }
}
