terrain_level_data {
  terrain_level: 60
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1378504.62
      sim_grid_pos_y: 1.15751e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1378718.88
      sim_grid_pos_y: 1157660.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1378857.62
      sim_grid_pos_y: 1157829
    }
    terrain_level_point {
      sim_grid_pos_x: 1379075
      sim_grid_pos_y: 1157337.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1379503.12
      sim_grid_pos_y: 1156858.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1379677.75
      sim_grid_pos_y: 1156793
    }
    terrain_level_point {
      sim_grid_pos_x: 1379511.38
      sim_grid_pos_y: 1156165.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1379349.88
      sim_grid_pos_y: 1156440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1379159.12
      sim_grid_pos_y: 1156569.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1379489.75
      sim_grid_pos_y: 1156120.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1379319.12
      sim_grid_pos_y: 1156411.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1379129.75
      sim_grid_pos_y: 1.15654e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1378447.75
      sim_grid_pos_y: 1.15752e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1378690.75
      sim_grid_pos_y: 1157691.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1378868.25
      sim_grid_pos_y: 1157906.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1379109.88
      sim_grid_pos_y: 1157360.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1379526.88
      sim_grid_pos_y: 1156893.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1379726.88
      sim_grid_pos_y: 1156818.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1379544
      sim_grid_pos_y: 1156128.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1379468.25
      sim_grid_pos_y: 1156076.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1379288.5
      sim_grid_pos_y: 1156383
    }
    terrain_level_point {
      sim_grid_pos_x: 1379100.5
      sim_grid_pos_y: 1156510.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1378390.75
      sim_grid_pos_y: 1157530.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1378662.62
      sim_grid_pos_y: 1157721.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1378878.88
      sim_grid_pos_y: 1157983.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1379144.75
      sim_grid_pos_y: 1157382.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1379550.75
      sim_grid_pos_y: 1156928.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1379776
      sim_grid_pos_y: 1156843.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1379576.62
      sim_grid_pos_y: 1156091.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1379446.75
      sim_grid_pos_y: 1156032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1379257.75
      sim_grid_pos_y: 1156354.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1379071.12
      sim_grid_pos_y: 1156480.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1378333.75
      sim_grid_pos_y: 1157540.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1378634.5
      sim_grid_pos_y: 1157752
    }
    terrain_level_point {
      sim_grid_pos_x: 1378889.5
      sim_grid_pos_y: 1158061
    }
    terrain_level_point {
      sim_grid_pos_x: 1379179.62
      sim_grid_pos_y: 1157405.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1379574.62
      sim_grid_pos_y: 1156963.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1379825.12
      sim_grid_pos_y: 1156869
    }
    terrain_level_point {
      sim_grid_pos_x: 1379609.25
      sim_grid_pos_y: 1156054.5
    }
  }
}
