terrain_level_data {
  terrain_level: 290
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2499886
      sim_grid_pos_y: 2151443.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499982.25
      sim_grid_pos_y: 2151629.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499883.75
      sim_grid_pos_y: 2151874
    }
    terrain_level_point {
      sim_grid_pos_x: 2500015.75
      sim_grid_pos_y: 2152081.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500337
      sim_grid_pos_y: 2152078.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500386
      sim_grid_pos_y: 2151891
    }
    terrain_level_point {
      sim_grid_pos_x: 2500304
      sim_grid_pos_y: 2151717.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2500353.5
      sim_grid_pos_y: 2151539.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500250.5
      sim_grid_pos_y: 2151403.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2500092.5
      sim_grid_pos_y: 2151271
    }
    terrain_level_point {
      sim_grid_pos_x: 2499979.25
      sim_grid_pos_y: 2151279.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2500109.5
      sim_grid_pos_y: 2151218.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499948.25
      sim_grid_pos_y: 2151230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499827.75
      sim_grid_pos_y: 2151442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499926
      sim_grid_pos_y: 2151632
    }
    terrain_level_point {
      sim_grid_pos_x: 2499826.5
      sim_grid_pos_y: 2151879.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499987.5
      sim_grid_pos_y: 2152133
    }
    terrain_level_point {
      sim_grid_pos_x: 2500376.75
      sim_grid_pos_y: 2152129.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500440.25
      sim_grid_pos_y: 2151886
    }
    terrain_level_point {
      sim_grid_pos_x: 2500358.5
      sim_grid_pos_y: 2151712.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500409.75
      sim_grid_pos_y: 2151529.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2500287.75
      sim_grid_pos_y: 2151367.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2500126.25
      sim_grid_pos_y: 2151165.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499917.25
      sim_grid_pos_y: 2151181.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499769.5
      sim_grid_pos_y: 2151441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499869.75
      sim_grid_pos_y: 2151634.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499769
      sim_grid_pos_y: 2151884.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499959.5
      sim_grid_pos_y: 2152184.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500416.5
      sim_grid_pos_y: 2152180.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500494.5
      sim_grid_pos_y: 2151880.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500413
      sim_grid_pos_y: 2151708
    }
    terrain_level_point {
      sim_grid_pos_x: 2500465.75
      sim_grid_pos_y: 2151518.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500325.25
      sim_grid_pos_y: 2151332.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2500143.25
      sim_grid_pos_y: 2151113.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499886
      sim_grid_pos_y: 2151132
    }
    terrain_level_point {
      sim_grid_pos_x: 2499711.25
      sim_grid_pos_y: 2151440.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499813.25
      sim_grid_pos_y: 2151637.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499711.75
      sim_grid_pos_y: 2151889.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499931.5
      sim_grid_pos_y: 2152236
    }
    terrain_level_point {
      sim_grid_pos_x: 2500456.25
      sim_grid_pos_y: 2152231.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500548.75
      sim_grid_pos_y: 2151875.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500467.5
      sim_grid_pos_y: 2151703.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500522
      sim_grid_pos_y: 2151508
    }
    terrain_level_point {
      sim_grid_pos_x: 2500362.5
      sim_grid_pos_y: 2151296.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2500160.25
      sim_grid_pos_y: 2151060.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499855
      sim_grid_pos_y: 2151083
    }
    terrain_level_point {
      sim_grid_pos_x: 2499652.75
      sim_grid_pos_y: 2151439.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499757
      sim_grid_pos_y: 2151640.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499654.25
      sim_grid_pos_y: 2151895
    }
    terrain_level_point {
      sim_grid_pos_x: 2499903.5
      sim_grid_pos_y: 2152287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2500495.75
      sim_grid_pos_y: 2152282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2500603.25
      sim_grid_pos_y: 2151870.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500522
      sim_grid_pos_y: 2151698.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2500578.25
      sim_grid_pos_y: 2151497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.5004e+06
      sim_grid_pos_y: 2151261
    }
  }
}
terrain_level_data {
  terrain_level: 160
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2499008.5
      sim_grid_pos_y: 2151086.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499233.75
      sim_grid_pos_y: 2151367
    }
    terrain_level_point {
      sim_grid_pos_x: 2498796
      sim_grid_pos_y: 2151662.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498587
      sim_grid_pos_y: 2151329.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498505.75
      sim_grid_pos_y: 2151142.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2498624.25
      sim_grid_pos_y: 2151061
    }
    terrain_level_point {
      sim_grid_pos_x: 2498777.5
      sim_grid_pos_y: 2151194.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2498786.25
      sim_grid_pos_y: 2151134
    }
    terrain_level_point {
      sim_grid_pos_x: 2499023.25
      sim_grid_pos_y: 2151023.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499308.5
      sim_grid_pos_y: 2151378.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498780.75
      sim_grid_pos_y: 2151734.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498541.5
      sim_grid_pos_y: 2151353.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498442
      sim_grid_pos_y: 2151124.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498628
      sim_grid_pos_y: 2150996.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2498794.75
      sim_grid_pos_y: 2151073.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2499038
      sim_grid_pos_y: 2150959.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499383.5
      sim_grid_pos_y: 2151389.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2498765.5
      sim_grid_pos_y: 2151806.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498496
      sim_grid_pos_y: 2151377.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498378.25
      sim_grid_pos_y: 2151106.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498631.5
      sim_grid_pos_y: 2150931.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2498803.25
      sim_grid_pos_y: 2151013
    }
    terrain_level_point {
      sim_grid_pos_x: 2499053
      sim_grid_pos_y: 2150896.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499458.25
      sim_grid_pos_y: 2151401
    }
    terrain_level_point {
      sim_grid_pos_x: 2498750.25
      sim_grid_pos_y: 2151878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498450.5
      sim_grid_pos_y: 2151401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498314.25
      sim_grid_pos_y: 2151088.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498635.25
      sim_grid_pos_y: 2150866.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2498811.75
      sim_grid_pos_y: 2150952.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2499067.75
      sim_grid_pos_y: 2150832.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2499533.25
      sim_grid_pos_y: 2151412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498735.25
      sim_grid_pos_y: 2151950.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2498405.25
      sim_grid_pos_y: 2151425.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498250.5
      sim_grid_pos_y: 2.15107e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2498638.75
      sim_grid_pos_y: 2150801.75
    }
  }
}
terrain_level_data {
  terrain_level: 210
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2497913.25
      sim_grid_pos_y: 2152265.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497749.5
      sim_grid_pos_y: 2152382.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2497727.5
      sim_grid_pos_y: 2152543.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497722.25
      sim_grid_pos_y: 2152774.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497881.25
      sim_grid_pos_y: 2152871.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498003
      sim_grid_pos_y: 2152734.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498016.25
      sim_grid_pos_y: 2152386.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2497921.75
      sim_grid_pos_y: 2152196
    }
    terrain_level_point {
      sim_grid_pos_x: 2497701.75
      sim_grid_pos_y: 2152354
    }
    terrain_level_point {
      sim_grid_pos_x: 2497676.5
      sim_grid_pos_y: 2152539.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497670.25
      sim_grid_pos_y: 2152802.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2497891
      sim_grid_pos_y: 2152937.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498053.75
      sim_grid_pos_y: 2152755
    }
    terrain_level_point {
      sim_grid_pos_x: 2498068.25
      sim_grid_pos_y: 2152369
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2497930.5
      sim_grid_pos_y: 2152126.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2497653.75
      sim_grid_pos_y: 2152325.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497625.25
      sim_grid_pos_y: 2152535.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497618.25
      sim_grid_pos_y: 2152830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2497900.75
      sim_grid_pos_y: 2153003.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498104.25
      sim_grid_pos_y: 2152775.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2498120.25
      sim_grid_pos_y: 2152351
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2497939
      sim_grid_pos_y: 2152057.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2497606
      sim_grid_pos_y: 2152296.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2497574
      sim_grid_pos_y: 2152531
    }
    terrain_level_point {
      sim_grid_pos_x: 2497566.25
      sim_grid_pos_y: 2152859.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497910.5
      sim_grid_pos_y: 2153069.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498154.75
      sim_grid_pos_y: 2152795.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498172.25
      sim_grid_pos_y: 2152333
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2497947.5
      sim_grid_pos_y: 2151988.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2497558.25
      sim_grid_pos_y: 2152267.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2497523
      sim_grid_pos_y: 2152527
    }
    terrain_level_point {
      sim_grid_pos_x: 2497514.5
      sim_grid_pos_y: 2152887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2497920.25
      sim_grid_pos_y: 2153135.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2498205.25
      sim_grid_pos_y: 2152816
    }
    terrain_level_point {
      sim_grid_pos_x: 2498224
      sim_grid_pos_y: 2152315
    }
  }
}
