terrain_level_data {
  terrain_level: 800
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3037271
      sim_grid_pos_y: 99596.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 3036509.5
      sim_grid_pos_y: 97531.6094
    }
    terrain_level_point {
      sim_grid_pos_x: 3037068.75
      sim_grid_pos_y: 96954.9219
    }
    terrain_level_point {
      sim_grid_pos_x: 3036404.25
      sim_grid_pos_y: 95316.7812
    }
    terrain_level_point {
      sim_grid_pos_x: 3035626
      sim_grid_pos_y: 94353.125
    }
    terrain_level_point {
      sim_grid_pos_x: 3035570.25
      sim_grid_pos_y: 92336.5859
    }
    terrain_level_point {
      sim_grid_pos_x: 3034885.5
      sim_grid_pos_y: 91342.4375
    }
    terrain_level_point {
      sim_grid_pos_x: 3035802.5
      sim_grid_pos_y: 90224.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 3036253
      sim_grid_pos_y: 90107.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 3036771.75
      sim_grid_pos_y: 90008.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 3038361.5
      sim_grid_pos_y: 99416.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 3038420.75
      sim_grid_pos_y: 99458.7109
    }
    terrain_level_point {
      sim_grid_pos_x: 3037237.5
      sim_grid_pos_y: 99653.7422
    }
    terrain_level_point {
      sim_grid_pos_x: 3036450.25
      sim_grid_pos_y: 97519.0781
    }
    terrain_level_point {
      sim_grid_pos_x: 3037008.75
      sim_grid_pos_y: 96943.2109
    }
    terrain_level_point {
      sim_grid_pos_x: 3036359.75
      sim_grid_pos_y: 95343.0938
    }
    terrain_level_point {
      sim_grid_pos_x: 3035575.25
      sim_grid_pos_y: 94371.8594
    }
    terrain_level_point {
      sim_grid_pos_x: 3035519.5
      sim_grid_pos_y: 92353.1875
    }
    terrain_level_point {
      sim_grid_pos_x: 3034821.5
      sim_grid_pos_y: 91339.75
    }
    terrain_level_point {
      sim_grid_pos_x: 3035773.5
      sim_grid_pos_y: 90179.1328
    }
    terrain_level_point {
      sim_grid_pos_x: 3036241.75
      sim_grid_pos_y: 90057.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 3036813.5
      sim_grid_pos_y: 89948.6562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 3038479.75
      sim_grid_pos_y: 99500.9219
    }
    terrain_level_point {
      sim_grid_pos_x: 3037204
      sim_grid_pos_y: 99711.2
    }
    terrain_level_point {
      sim_grid_pos_x: 3036391
      sim_grid_pos_y: 97506.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 3036948.75
      sim_grid_pos_y: 96931.5078
    }
    terrain_level_point {
      sim_grid_pos_x: 3036315
      sim_grid_pos_y: 95369.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 3035524.5
      sim_grid_pos_y: 94390.5938
    }
    terrain_level_point {
      sim_grid_pos_x: 3035468.75
      sim_grid_pos_y: 92369.7734
    }
    terrain_level_point {
      sim_grid_pos_x: 3034757.25
      sim_grid_pos_y: 91337.0625
    }
    terrain_level_point {
      sim_grid_pos_x: 3035744.5
      sim_grid_pos_y: 90133.7109
    }
    terrain_level_point {
      sim_grid_pos_x: 3036230.5
      sim_grid_pos_y: 90007.4375
    }
    terrain_level_point {
      sim_grid_pos_x: 3036855.25
      sim_grid_pos_y: 89888.5234
    }
  }
}
