terrain_level_data {
  terrain_level: 382
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1689688
      sim_grid_pos_y: 1501592.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689738
      sim_grid_pos_y: 1502010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1690870.62
      sim_grid_pos_y: 1501994.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1690843.5
      sim_grid_pos_y: 1501525.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1690882.12
      sim_grid_pos_y: 1501482.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1689642.12
      sim_grid_pos_y: 1501554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1689701.62
      sim_grid_pos_y: 1502052
    }
    terrain_level_point {
      sim_grid_pos_x: 1690914.12
      sim_grid_pos_y: 1502034.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1690920.62
      sim_grid_pos_y: 1501439
    }
    terrain_level_point {
      sim_grid_pos_x: 1689596.25
      sim_grid_pos_y: 1501515.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1689665.25
      sim_grid_pos_y: 1502093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1690957.5
      sim_grid_pos_y: 1502075.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1690959.25
      sim_grid_pos_y: 1501395.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689550.38
      sim_grid_pos_y: 1501477.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1689629
      sim_grid_pos_y: 1502135.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1691001
      sim_grid_pos_y: 1502115.62
    }
  }
}
