terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 387265.219
      sim_grid_pos_y: 1778104.88
    }
    terrain_level_point {
      sim_grid_pos_x: 387781.312
      sim_grid_pos_y: 1777902.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388031.281
      sim_grid_pos_y: 1777642.5
    }
    terrain_level_point {
      sim_grid_pos_x: 387974.312
      sim_grid_pos_y: 1776901.25
    }
    terrain_level_point {
      sim_grid_pos_x: 389923.719
      sim_grid_pos_y: 1776163.38
    }
    terrain_level_point {
      sim_grid_pos_x: 390019.969
      sim_grid_pos_y: 1776362.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389023.156
      sim_grid_pos_y: 1776860.12
    }
    terrain_level_point {
      sim_grid_pos_x: 389089.5
      sim_grid_pos_y: 1777016.38
    }
    terrain_level_point {
      sim_grid_pos_x: 389196.969
      sim_grid_pos_y: 1777292.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388572.219
      sim_grid_pos_y: 1777839.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388382.094
      sim_grid_pos_y: 1778279.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388440.719
      sim_grid_pos_y: 1778483.62
    }
    terrain_level_point {
      sim_grid_pos_x: 388440.625
      sim_grid_pos_y: 1778738.62
    }
    terrain_level_point {
      sim_grid_pos_x: 388582.719
      sim_grid_pos_y: 1778729.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388612.188
      sim_grid_pos_y: 1778465
    }
    terrain_level_point {
      sim_grid_pos_x: 388801.438
      sim_grid_pos_y: 1778143
    }
    terrain_level_point {
      sim_grid_pos_x: 389429.062
      sim_grid_pos_y: 1777576.75
    }
    terrain_level_point {
      sim_grid_pos_x: 389290.812
      sim_grid_pos_y: 1777395.12
    }
    terrain_level_point {
      sim_grid_pos_x: 389703.906
      sim_grid_pos_y: 1776956
    }
    terrain_level_point {
      sim_grid_pos_x: 389881.062
      sim_grid_pos_y: 1776882.38
    }
    terrain_level_point {
      sim_grid_pos_x: 390537.062
      sim_grid_pos_y: 1777112.5
    }
    terrain_level_point {
      sim_grid_pos_x: 390568.156
      sim_grid_pos_y: 1776986.25
    }
    terrain_level_point {
      sim_grid_pos_x: 390700.938
      sim_grid_pos_y: 1776921
    }
    terrain_level_point {
      sim_grid_pos_x: 391323.469
      sim_grid_pos_y: 1776788.5
    }
    terrain_level_point {
      sim_grid_pos_x: 392075.5
      sim_grid_pos_y: 1776295.62
    }
    terrain_level_point {
      sim_grid_pos_x: 392032.969
      sim_grid_pos_y: 1775953.5
    }
    terrain_level_point {
      sim_grid_pos_x: 391207.375
      sim_grid_pos_y: 1775543.62
    }
    terrain_level_point {
      sim_grid_pos_x: 391049.531
      sim_grid_pos_y: 1775384.88
    }
    terrain_level_point {
      sim_grid_pos_x: 390999.156
      sim_grid_pos_y: 1775072.25
    }
    terrain_level_point {
      sim_grid_pos_x: 390879.719
      sim_grid_pos_y: 1774916.75
    }
    terrain_level_point {
      sim_grid_pos_x: 390876.875
      sim_grid_pos_y: 1774729.62
    }
    terrain_level_point {
      sim_grid_pos_x: 390956.938
      sim_grid_pos_y: 1774497.75
    }
    terrain_level_point {
      sim_grid_pos_x: 389849.562
      sim_grid_pos_y: 1774778.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389164.875
      sim_grid_pos_y: 1773893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388329.25
      sim_grid_pos_y: 1774479.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388120.406
      sim_grid_pos_y: 1774632.75
    }
    terrain_level_point {
      sim_grid_pos_x: 387983.062
      sim_grid_pos_y: 1775162.75
    }
    terrain_level_point {
      sim_grid_pos_x: 387620.5
      sim_grid_pos_y: 1775405
    }
    terrain_level_point {
      sim_grid_pos_x: 386371.312
      sim_grid_pos_y: 1775925.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 389171.25
      sim_grid_pos_y: 1773851.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388311.344
      sim_grid_pos_y: 1774454.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388093.375
      sim_grid_pos_y: 1774614.38
    }
    terrain_level_point {
      sim_grid_pos_x: 387956.25
      sim_grid_pos_y: 1775143.75
    }
    terrain_level_point {
      sim_grid_pos_x: 387605.906
      sim_grid_pos_y: 1775377.75
    }
    terrain_level_point {
      sim_grid_pos_x: 386331.25
      sim_grid_pos_y: 1775908.62
    }
    terrain_level_point {
      sim_grid_pos_x: 387248.25
      sim_grid_pos_y: 1778144.62
    }
    terrain_level_point {
      sim_grid_pos_x: 387798.812
      sim_grid_pos_y: 1777928.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388063
      sim_grid_pos_y: 1777653.88
    }
    terrain_level_point {
      sim_grid_pos_x: 388006.75
      sim_grid_pos_y: 1776921.88
    }
    terrain_level_point {
      sim_grid_pos_x: 389908.25
      sim_grid_pos_y: 1776202.12
    }
    terrain_level_point {
      sim_grid_pos_x: 389979.062
      sim_grid_pos_y: 1776348.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388983.531
      sim_grid_pos_y: 1776845.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389061.031
      sim_grid_pos_y: 1777028
    }
    terrain_level_point {
      sim_grid_pos_x: 389160.5
      sim_grid_pos_y: 1777283.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388546.75
      sim_grid_pos_y: 1777820.88
    }
    terrain_level_point {
      sim_grid_pos_x: 388349.469
      sim_grid_pos_y: 1778277.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388409.969
      sim_grid_pos_y: 1778487.88
    }
    terrain_level_point {
      sim_grid_pos_x: 388409.844
      sim_grid_pos_y: 1778771.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388610.406
      sim_grid_pos_y: 1778758.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388642.031
      sim_grid_pos_y: 1778474.88
    }
    terrain_level_point {
      sim_grid_pos_x: 388825.562
      sim_grid_pos_y: 1778162.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389470.656
      sim_grid_pos_y: 1777580.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389331.062
      sim_grid_pos_y: 1777397.12
    }
    terrain_level_point {
      sim_grid_pos_x: 389721.812
      sim_grid_pos_y: 1776981.88
    }
    terrain_level_point {
      sim_grid_pos_x: 389881.969
      sim_grid_pos_y: 1776915.25
    }
    terrain_level_point {
      sim_grid_pos_x: 390558.844
      sim_grid_pos_y: 1777152.62
    }
    terrain_level_point {
      sim_grid_pos_x: 390594.594
      sim_grid_pos_y: 1777007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 390711.094
      sim_grid_pos_y: 1776950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 391335.531
      sim_grid_pos_y: 1776817.38
    }
    terrain_level_point {
      sim_grid_pos_x: 392108.406
      sim_grid_pos_y: 1776310.88
    }
    terrain_level_point {
      sim_grid_pos_x: 392061.469
      sim_grid_pos_y: 1775933.38
    }
    terrain_level_point {
      sim_grid_pos_x: 391225.594
      sim_grid_pos_y: 1775518.38
    }
    terrain_level_point {
      sim_grid_pos_x: 391078.344
      sim_grid_pos_y: 1775370.25
    }
    terrain_level_point {
      sim_grid_pos_x: 391028.312
      sim_grid_pos_y: 1775059.62
    }
    terrain_level_point {
      sim_grid_pos_x: 390910.312
      sim_grid_pos_y: 1774906.12
    }
    terrain_level_point {
      sim_grid_pos_x: 390907.719
      sim_grid_pos_y: 1774734.5
    }
    terrain_level_point {
      sim_grid_pos_x: 390992
      sim_grid_pos_y: 1774490.5
    }
    terrain_level_point {
      sim_grid_pos_x: 390967.188
      sim_grid_pos_y: 1774463.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389861.562
      sim_grid_pos_y: 1774743.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 389177.625
      sim_grid_pos_y: 1773809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388293.375
      sim_grid_pos_y: 1774429.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388066.344
      sim_grid_pos_y: 1774596.12
    }
    terrain_level_point {
      sim_grid_pos_x: 387929.406
      sim_grid_pos_y: 1775124.62
    }
    terrain_level_point {
      sim_grid_pos_x: 387591.312
      sim_grid_pos_y: 1775350.5
    }
    terrain_level_point {
      sim_grid_pos_x: 386291.188
      sim_grid_pos_y: 1775892
    }
    terrain_level_point {
      sim_grid_pos_x: 387231.312
      sim_grid_pos_y: 1778184.38
    }
    terrain_level_point {
      sim_grid_pos_x: 387816.312
      sim_grid_pos_y: 1777954.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388094.75
      sim_grid_pos_y: 1777665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388039.188
      sim_grid_pos_y: 1776942.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389892.812
      sim_grid_pos_y: 1776240.88
    }
    terrain_level_point {
      sim_grid_pos_x: 389938.156
      sim_grid_pos_y: 1776334.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388943.875
      sim_grid_pos_y: 1776831
    }
    terrain_level_point {
      sim_grid_pos_x: 389032.594
      sim_grid_pos_y: 1777039.75
    }
    terrain_level_point {
      sim_grid_pos_x: 389124
      sim_grid_pos_y: 1777274.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388521.25
      sim_grid_pos_y: 1777802.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388316.875
      sim_grid_pos_y: 1778275.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388379.188
      sim_grid_pos_y: 1778492.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388379.094
      sim_grid_pos_y: 1778804.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388638.125
      sim_grid_pos_y: 1778787.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388671.875
      sim_grid_pos_y: 1778484.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388849.656
      sim_grid_pos_y: 1778182.38
    }
    terrain_level_point {
      sim_grid_pos_x: 389512.281
      sim_grid_pos_y: 1777584.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389371.312
      sim_grid_pos_y: 1777399.25
    }
    terrain_level_point {
      sim_grid_pos_x: 389739.688
      sim_grid_pos_y: 1777007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 389882.906
      sim_grid_pos_y: 1776948.25
    }
    terrain_level_point {
      sim_grid_pos_x: 390580.594
      sim_grid_pos_y: 1777192.88
    }
    terrain_level_point {
      sim_grid_pos_x: 390621.031
      sim_grid_pos_y: 1777028.75
    }
    terrain_level_point {
      sim_grid_pos_x: 390721.188
      sim_grid_pos_y: 1776979.62
    }
    terrain_level_point {
      sim_grid_pos_x: 391347.562
      sim_grid_pos_y: 1776846.25
    }
    terrain_level_point {
      sim_grid_pos_x: 392141.281
      sim_grid_pos_y: 1776326.12
    }
    terrain_level_point {
      sim_grid_pos_x: 392089.938
      sim_grid_pos_y: 1775913.12
    }
    terrain_level_point {
      sim_grid_pos_x: 391243.812
      sim_grid_pos_y: 1775493.12
    }
    terrain_level_point {
      sim_grid_pos_x: 391107.125
      sim_grid_pos_y: 1775355.5
    }
    terrain_level_point {
      sim_grid_pos_x: 391057.438
      sim_grid_pos_y: 1775047.12
    }
    terrain_level_point {
      sim_grid_pos_x: 390940.906
      sim_grid_pos_y: 1774895.5
    }
    terrain_level_point {
      sim_grid_pos_x: 390938.562
      sim_grid_pos_y: 1774739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 391027.094
      sim_grid_pos_y: 1774483.25
    }
    terrain_level_point {
      sim_grid_pos_x: 390977.406
      sim_grid_pos_y: 1774429.12
    }
    terrain_level_point {
      sim_grid_pos_x: 389873.531
      sim_grid_pos_y: 1774709
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 389184
      sim_grid_pos_y: 1773767.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388275.469
      sim_grid_pos_y: 1774404.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388039.312
      sim_grid_pos_y: 1774577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 387902.594
      sim_grid_pos_y: 1775105.62
    }
    terrain_level_point {
      sim_grid_pos_x: 387576.719
      sim_grid_pos_y: 1775323.25
    }
    terrain_level_point {
      sim_grid_pos_x: 386251.125
      sim_grid_pos_y: 1775875.38
    }
    terrain_level_point {
      sim_grid_pos_x: 387214.344
      sim_grid_pos_y: 1778224.12
    }
    terrain_level_point {
      sim_grid_pos_x: 387833.812
      sim_grid_pos_y: 1777980.62
    }
    terrain_level_point {
      sim_grid_pos_x: 388126.469
      sim_grid_pos_y: 1777676.62
    }
    terrain_level_point {
      sim_grid_pos_x: 388071.625
      sim_grid_pos_y: 1776963.12
    }
    terrain_level_point {
      sim_grid_pos_x: 389877.375
      sim_grid_pos_y: 1776279.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389897.25
      sim_grid_pos_y: 1776320.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388904.281
      sim_grid_pos_y: 1776816.38
    }
    terrain_level_point {
      sim_grid_pos_x: 389004.062
      sim_grid_pos_y: 1777051.25
    }
    terrain_level_point {
      sim_grid_pos_x: 389087.531
      sim_grid_pos_y: 1777265.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388495.781
      sim_grid_pos_y: 1777783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388284.281
      sim_grid_pos_y: 1778273
    }
    terrain_level_point {
      sim_grid_pos_x: 388348.438
      sim_grid_pos_y: 1778496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 388348.312
      sim_grid_pos_y: 1778837.25
    }
    terrain_level_point {
      sim_grid_pos_x: 388665.844
      sim_grid_pos_y: 1778816.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388701.688
      sim_grid_pos_y: 1778494.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388873.781
      sim_grid_pos_y: 1778202
    }
    terrain_level_point {
      sim_grid_pos_x: 389553.875
      sim_grid_pos_y: 1777588.38
    }
    terrain_level_point {
      sim_grid_pos_x: 389411.594
      sim_grid_pos_y: 1777401.38
    }
    terrain_level_point {
      sim_grid_pos_x: 389757.594
      sim_grid_pos_y: 1777033.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389883.844
      sim_grid_pos_y: 1776981.12
    }
    terrain_level_point {
      sim_grid_pos_x: 390602.375
      sim_grid_pos_y: 1777233.12
    }
    terrain_level_point {
      sim_grid_pos_x: 390647.438
      sim_grid_pos_y: 1777050.12
    }
    terrain_level_point {
      sim_grid_pos_x: 390731.344
      sim_grid_pos_y: 1777008.88
    }
    terrain_level_point {
      sim_grid_pos_x: 391359.594
      sim_grid_pos_y: 1776875.12
    }
    terrain_level_point {
      sim_grid_pos_x: 392174.156
      sim_grid_pos_y: 1776341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 392118.438
      sim_grid_pos_y: 1775893
    }
    terrain_level_point {
      sim_grid_pos_x: 391262.062
      sim_grid_pos_y: 1775467.75
    }
    terrain_level_point {
      sim_grid_pos_x: 391135.906
      sim_grid_pos_y: 1775340.88
    }
    terrain_level_point {
      sim_grid_pos_x: 391086.562
      sim_grid_pos_y: 1775034.5
    }
    terrain_level_point {
      sim_grid_pos_x: 390971.5
      sim_grid_pos_y: 1774884.88
    }
    terrain_level_point {
      sim_grid_pos_x: 390969.375
      sim_grid_pos_y: 1774744.38
    }
    terrain_level_point {
      sim_grid_pos_x: 391062.125
      sim_grid_pos_y: 1774475.88
    }
    terrain_level_point {
      sim_grid_pos_x: 390987.625
      sim_grid_pos_y: 1774394.88
    }
    terrain_level_point {
      sim_grid_pos_x: 389885.531
      sim_grid_pos_y: 1774674.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 389190.375
      sim_grid_pos_y: 1773725.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388257.531
      sim_grid_pos_y: 1774379.38
    }
    terrain_level_point {
      sim_grid_pos_x: 388012.281
      sim_grid_pos_y: 1774559.5
    }
    terrain_level_point {
      sim_grid_pos_x: 387875.75
      sim_grid_pos_y: 1775086.5
    }
    terrain_level_point {
      sim_grid_pos_x: 387562.125
      sim_grid_pos_y: 1775296
    }
    terrain_level_point {
      sim_grid_pos_x: 386211.062
      sim_grid_pos_y: 1775858.75
    }
    terrain_level_point {
      sim_grid_pos_x: 387197.375
      sim_grid_pos_y: 1778263.75
    }
    terrain_level_point {
      sim_grid_pos_x: 387851.312
      sim_grid_pos_y: 1778006.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388158.188
      sim_grid_pos_y: 1777688.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388104.062
      sim_grid_pos_y: 1776983.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389743.656
      sim_grid_pos_y: 1776363
    }
    terrain_level_point {
      sim_grid_pos_x: 388864.656
      sim_grid_pos_y: 1776801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388975.5
      sim_grid_pos_y: 1777062.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389051.031
      sim_grid_pos_y: 1777256.62
    }
    terrain_level_point {
      sim_grid_pos_x: 388470.312
      sim_grid_pos_y: 1777765.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388251.656
      sim_grid_pos_y: 1778270.88
    }
    terrain_level_point {
      sim_grid_pos_x: 388317.688
      sim_grid_pos_y: 1778500.88
    }
    terrain_level_point {
      sim_grid_pos_x: 388317.531
      sim_grid_pos_y: 1778870.12
    }
    terrain_level_point {
      sim_grid_pos_x: 388693.562
      sim_grid_pos_y: 1778845
    }
    terrain_level_point {
      sim_grid_pos_x: 388731.531
      sim_grid_pos_y: 1778504.75
    }
    terrain_level_point {
      sim_grid_pos_x: 388897.906
      sim_grid_pos_y: 1778221.62
    }
    terrain_level_point {
      sim_grid_pos_x: 389595.5
      sim_grid_pos_y: 1777592.25
    }
    terrain_level_point {
      sim_grid_pos_x: 389451.812
      sim_grid_pos_y: 1777403.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389775.469
      sim_grid_pos_y: 1777059.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389884.781
      sim_grid_pos_y: 1777014
    }
    terrain_level_point {
      sim_grid_pos_x: 390624.125
      sim_grid_pos_y: 1777273.38
    }
    terrain_level_point {
      sim_grid_pos_x: 390673.875
      sim_grid_pos_y: 1777071.38
    }
    terrain_level_point {
      sim_grid_pos_x: 390741.5
      sim_grid_pos_y: 1777038.12
    }
    terrain_level_point {
      sim_grid_pos_x: 391371.625
      sim_grid_pos_y: 1776904
    }
    terrain_level_point {
      sim_grid_pos_x: 392207.062
      sim_grid_pos_y: 1776356.5
    }
    terrain_level_point {
      sim_grid_pos_x: 392146.906
      sim_grid_pos_y: 1775872.75
    }
    terrain_level_point {
      sim_grid_pos_x: 391280.281
      sim_grid_pos_y: 1775442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 391164.719
      sim_grid_pos_y: 1775326.25
    }
    terrain_level_point {
      sim_grid_pos_x: 391115.688
      sim_grid_pos_y: 1775021.88
    }
    terrain_level_point {
      sim_grid_pos_x: 391002.125
      sim_grid_pos_y: 1774874.12
    }
    terrain_level_point {
      sim_grid_pos_x: 391000.219
      sim_grid_pos_y: 1774749.38
    }
    terrain_level_point {
      sim_grid_pos_x: 391097.219
      sim_grid_pos_y: 1774468.62
    }
    terrain_level_point {
      sim_grid_pos_x: 390997.875
      sim_grid_pos_y: 1774360.5
    }
    terrain_level_point {
      sim_grid_pos_x: 389897.5
      sim_grid_pos_y: 1774639.5
    }
  }
}
