terrain_level_data {
  terrain_level: 1352
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1406036.25
      sim_grid_pos_y: 1532733.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1406152.5
      sim_grid_pos_y: 1532864.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1406413.75
      sim_grid_pos_y: 1532890.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1406568.25
      sim_grid_pos_y: 1532762.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1406579.88
      sim_grid_pos_y: 1532539.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1406305.12
      sim_grid_pos_y: 1532502.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1406111.38
      sim_grid_pos_y: 1532590.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1406297.25
      sim_grid_pos_y: 1532449.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1406074.12
      sim_grid_pos_y: 1532551.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1405974.38
      sim_grid_pos_y: 1532740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1406127.5
      sim_grid_pos_y: 1532914
    }
    terrain_level_point {
      sim_grid_pos_x: 1406430.12
      sim_grid_pos_y: 1532943.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1406618.25
      sim_grid_pos_y: 1532787.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1406633.62
      sim_grid_pos_y: 1532494.75
    }
  }
}
