terrain_level_data {
  terrain_level: 174
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1657275.5
      sim_grid_pos_y: 975579.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1657276
      sim_grid_pos_y: 975392
    }
    terrain_level_point {
      sim_grid_pos_x: 1657487.12
      sim_grid_pos_y: 975251.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1657702.25
      sim_grid_pos_y: 975382.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1657700.5
      sim_grid_pos_y: 975605.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1657485.38
      sim_grid_pos_y: 975721.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1657805.25
      sim_grid_pos_y: 975325.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1657802.5
      sim_grid_pos_y: 975666.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1657479.38
      sim_grid_pos_y: 975841.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1657172.88
      sim_grid_pos_y: 975633.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1657173.62
      sim_grid_pos_y: 975337
    }
    terrain_level_point {
      sim_grid_pos_x: 1657484.75
      sim_grid_pos_y: 975129.688
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1657908.25
      sim_grid_pos_y: 975268.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1657904.62
      sim_grid_pos_y: 975728.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1657473.38
      sim_grid_pos_y: 975961.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1657070.12
      sim_grid_pos_y: 975687.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1657071.25
      sim_grid_pos_y: 975282.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1657482.38
      sim_grid_pos_y: 975008.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1658011.25
      sim_grid_pos_y: 975211.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1658006.62
      sim_grid_pos_y: 975789.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1657467.25
      sim_grid_pos_y: 976081.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1656967.5
      sim_grid_pos_y: 975741.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1656968.88
      sim_grid_pos_y: 975227.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1.65748e+06
      sim_grid_pos_y: 974886.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1658114.12
      sim_grid_pos_y: 975154.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1658108.75
      sim_grid_pos_y: 975850.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1657461.25
      sim_grid_pos_y: 976201.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1656864.75
      sim_grid_pos_y: 975796.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1656866.5
      sim_grid_pos_y: 975172.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1657477.75
      sim_grid_pos_y: 974764.75
    }
  }
}
terrain_level_data {
  terrain_level: 74
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1666854
      sim_grid_pos_y: 965719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1666659.88
      sim_grid_pos_y: 967463.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1664344.12
      sim_grid_pos_y: 969804.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1663099.75
      sim_grid_pos_y: 969998
    }
    terrain_level_point {
      sim_grid_pos_x: 1658122.88
      sim_grid_pos_y: 972537.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1655821.88
      sim_grid_pos_y: 970734.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1654592.12
      sim_grid_pos_y: 969932.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1653092.88
      sim_grid_pos_y: 969508.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652095.12
      sim_grid_pos_y: 969907.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1652023.75
      sim_grid_pos_y: 969718.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1653009
      sim_grid_pos_y: 969115.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1653969.25
      sim_grid_pos_y: 969437.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1654058
      sim_grid_pos_y: 969269
    }
    terrain_level_point {
      sim_grid_pos_x: 1655222.75
      sim_grid_pos_y: 969391.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1655771.25
      sim_grid_pos_y: 969336.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1657269.62
      sim_grid_pos_y: 970828.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1660048.25
      sim_grid_pos_y: 968429.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1664083.38
      sim_grid_pos_y: 965021.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1665637.75
      sim_grid_pos_y: 965852.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1665658.12
      sim_grid_pos_y: 965747.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1.66697e+06
      sim_grid_pos_y: 965603.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1666757.88
      sim_grid_pos_y: 967510.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1664393.25
      sim_grid_pos_y: 969901
    }
    terrain_level_point {
      sim_grid_pos_x: 1663131.75
      sim_grid_pos_y: 970096.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1658111.12
      sim_grid_pos_y: 972658.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1655762.12
      sim_grid_pos_y: 970818.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1654549.25
      sim_grid_pos_y: 970026.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1653098.62
      sim_grid_pos_y: 969616.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1652036
      sim_grid_pos_y: 970041.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1651897.88
      sim_grid_pos_y: 969675.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1652996.25
      sim_grid_pos_y: 969002.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1653919.25
      sim_grid_pos_y: 969312.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1653999.75
      sim_grid_pos_y: 969159.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1655223
      sim_grid_pos_y: 969288.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1655809.25
      sim_grid_pos_y: 969229.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1657274.62
      sim_grid_pos_y: 970688.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1659981.62
      sim_grid_pos_y: 968351.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1664070.38
      sim_grid_pos_y: 964898.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1665678.5
      sim_grid_pos_y: 965642
    }
    terrain_level_point {
      sim_grid_pos_x: 1667086.12
      sim_grid_pos_y: 965487.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1666855.75
      sim_grid_pos_y: 967557.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1664442.38
      sim_grid_pos_y: 969997.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1663163.62
      sim_grid_pos_y: 970195.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1658099.5
      sim_grid_pos_y: 972779.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1655702.38
      sim_grid_pos_y: 970901.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654506.25
      sim_grid_pos_y: 970120.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1653104.25
      sim_grid_pos_y: 969724.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1651977
      sim_grid_pos_y: 970175.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1651772.12
      sim_grid_pos_y: 969632.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1652983.5
      sim_grid_pos_y: 968890.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1653869.25
      sim_grid_pos_y: 969187.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1653941.5
      sim_grid_pos_y: 969050.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1655223.25
      sim_grid_pos_y: 969185.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1655847.25
      sim_grid_pos_y: 969122.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1657279.5
      sim_grid_pos_y: 970548.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1659915.12
      sim_grid_pos_y: 968273.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1664057.38
      sim_grid_pos_y: 964775.5
    }
  }
}
