terrain_level_data {
  terrain_level: 150
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2754063
      sim_grid_pos_y: 2279388.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754062.5
      sim_grid_pos_y: 2279570.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753880.5
      sim_grid_pos_y: 2279634.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753694.5
      sim_grid_pos_y: 2279620.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753731.75
      sim_grid_pos_y: 2279853.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753683.25
      sim_grid_pos_y: 2280049.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753411.25
      sim_grid_pos_y: 2280222
    }
    terrain_level_point {
      sim_grid_pos_x: 2753481
      sim_grid_pos_y: 2280432.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753220.75
      sim_grid_pos_y: 2280569.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753106.5
      sim_grid_pos_y: 2280372.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752663.75
      sim_grid_pos_y: 2280567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2752578.25
      sim_grid_pos_y: 2280374.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753058.25
      sim_grid_pos_y: 2280088.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752876.5
      sim_grid_pos_y: 2279854
    }
    terrain_level_point {
      sim_grid_pos_x: 2753338.25
      sim_grid_pos_y: 2279487
    }
    terrain_level_point {
      sim_grid_pos_x: 2753645.5
      sim_grid_pos_y: 2279378.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753964.25
      sim_grid_pos_y: 2279283.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2754114.5
      sim_grid_pos_y: 2279368.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754113.75
      sim_grid_pos_y: 2279606.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753887.5
      sim_grid_pos_y: 2279686.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753755.25
      sim_grid_pos_y: 2279676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753784
      sim_grid_pos_y: 2279856
    }
    terrain_level_point {
      sim_grid_pos_x: 2753728
      sim_grid_pos_y: 2280081.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753472.5
      sim_grid_pos_y: 2280244
    }
    terrain_level_point {
      sim_grid_pos_x: 2753543.5
      sim_grid_pos_y: 2280457.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753201
      sim_grid_pos_y: 2280637.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753085.25
      sim_grid_pos_y: 2280437.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752637.75
      sim_grid_pos_y: 2280635.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752513
      sim_grid_pos_y: 2280353.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2752982.25
      sim_grid_pos_y: 2280074.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752805
      sim_grid_pos_y: 2279845.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753313
      sim_grid_pos_y: 2279441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753629.5
      sim_grid_pos_y: 2.27933e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2753979.75
      sim_grid_pos_y: 2279225.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2754165.75
      sim_grid_pos_y: 2279347.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2754165
      sim_grid_pos_y: 2279643.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753894.25
      sim_grid_pos_y: 2279738.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753816.25
      sim_grid_pos_y: 2279732.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753836.25
      sim_grid_pos_y: 2279858.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753773
      sim_grid_pos_y: 2280114
    }
    terrain_level_point {
      sim_grid_pos_x: 2753533.75
      sim_grid_pos_y: 2280265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753605.75
      sim_grid_pos_y: 2280482.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753181.5
      sim_grid_pos_y: 2280706
    }
    terrain_level_point {
      sim_grid_pos_x: 2753064
      sim_grid_pos_y: 2280503.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752611.5
      sim_grid_pos_y: 2280702.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752447.75
      sim_grid_pos_y: 2280332.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2752906.25
      sim_grid_pos_y: 2280059.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752733.5
      sim_grid_pos_y: 2279836.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753288
      sim_grid_pos_y: 2279396
    }
    terrain_level_point {
      sim_grid_pos_x: 2753613.75
      sim_grid_pos_y: 2279281.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753995.5
      sim_grid_pos_y: 2279167.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2754217
      sim_grid_pos_y: 2279327.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754216
      sim_grid_pos_y: 2279679.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753901.25
      sim_grid_pos_y: 2279790.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753877
      sim_grid_pos_y: 2279788.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753888.5
      sim_grid_pos_y: 2279860.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753817.75
      sim_grid_pos_y: 2280146.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753595
      sim_grid_pos_y: 2280287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753668.25
      sim_grid_pos_y: 2280508
    }
    terrain_level_point {
      sim_grid_pos_x: 2753161.75
      sim_grid_pos_y: 2280774.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753042.5
      sim_grid_pos_y: 2280568.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752585.5
      sim_grid_pos_y: 2280770.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752382.5
      sim_grid_pos_y: 2280311.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752830.25
      sim_grid_pos_y: 2280045.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2752662
      sim_grid_pos_y: 2279828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753262.75
      sim_grid_pos_y: 2279350.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753598
      sim_grid_pos_y: 2279232.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2754011
      sim_grid_pos_y: 2279109.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2754268.5
      sim_grid_pos_y: 2279307.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2754267.25
      sim_grid_pos_y: 2279716
    }
    terrain_level_point {
      sim_grid_pos_x: 2753936
      sim_grid_pos_y: 2279832.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753941
      sim_grid_pos_y: 2279862.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753862.5
      sim_grid_pos_y: 2280178.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753656.25
      sim_grid_pos_y: 2280309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753730.5
      sim_grid_pos_y: 2280533
    }
    terrain_level_point {
      sim_grid_pos_x: 2753142
      sim_grid_pos_y: 2280842.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753021.25
      sim_grid_pos_y: 2280634
    }
    terrain_level_point {
      sim_grid_pos_x: 2752559.25
      sim_grid_pos_y: 2280837.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752317
      sim_grid_pos_y: 2280291
    }
    terrain_level_point {
      sim_grid_pos_x: 2752754.25
      sim_grid_pos_y: 2280031
    }
    terrain_level_point {
      sim_grid_pos_x: 2752590.5
      sim_grid_pos_y: 2279819.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753237.5
      sim_grid_pos_y: 2279305.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753582
      sim_grid_pos_y: 2279183.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2754026.75
      sim_grid_pos_y: 2279051
    }
  }
}
terrain_level_data {
  terrain_level: 185
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2753003
      sim_grid_pos_y: 2279020.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753006.5
      sim_grid_pos_y: 2279192
    }
    terrain_level_point {
      sim_grid_pos_x: 2753173.25
      sim_grid_pos_y: 2279194
    }
    terrain_level_point {
      sim_grid_pos_x: 2753169.5
      sim_grid_pos_y: 2279015.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2753199.5
      sim_grid_pos_y: 2278984
    }
    terrain_level_point {
      sim_grid_pos_x: 2752971.5
      sim_grid_pos_y: 2278991
    }
    terrain_level_point {
      sim_grid_pos_x: 2752976.5
      sim_grid_pos_y: 2279222.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2753204.5
      sim_grid_pos_y: 2279225.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2753229.5
      sim_grid_pos_y: 2278952.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752940.25
      sim_grid_pos_y: 2278961.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752946.25
      sim_grid_pos_y: 2279252.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753236
      sim_grid_pos_y: 2279256.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2753259.75
      sim_grid_pos_y: 2278920.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2752908.75
      sim_grid_pos_y: 2278931.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2752916.25
      sim_grid_pos_y: 2279283.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2753267.5
      sim_grid_pos_y: 2279287.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2753289.75
      sim_grid_pos_y: 2278888.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2752877.25
      sim_grid_pos_y: 2278901.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2752886
      sim_grid_pos_y: 2279313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2753299
      sim_grid_pos_y: 2279318.75
    }
  }
}
