terrain_level_data {
  terrain_level: 285
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1688251.5
      sim_grid_pos_y: 1392927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1688407.25
      sim_grid_pos_y: 1393326.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1688574.88
      sim_grid_pos_y: 1393525.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1688824.88
      sim_grid_pos_y: 1393604.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689055.12
      sim_grid_pos_y: 1393494.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1689235.25
      sim_grid_pos_y: 1393376.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1689268.62
      sim_grid_pos_y: 1393143.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1688968.62
      sim_grid_pos_y: 1392873.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1688603.25
      sim_grid_pos_y: 1392527.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1688320.25
      sim_grid_pos_y: 1392507.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1688294.5
      sim_grid_pos_y: 1392474.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1688219.75
      sim_grid_pos_y: 1392930.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1688380.5
      sim_grid_pos_y: 1393342.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1688557
      sim_grid_pos_y: 1393551.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1688827.25
      sim_grid_pos_y: 1393637.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689070.25
      sim_grid_pos_y: 1393521.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1689263.75
      sim_grid_pos_y: 1393394.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1689301.38
      sim_grid_pos_y: 1393131.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1688989.62
      sim_grid_pos_y: 1392850.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1688616.38
      sim_grid_pos_y: 1392497.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1688268.62
      sim_grid_pos_y: 1392441.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1688188
      sim_grid_pos_y: 1392934.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1688353.62
      sim_grid_pos_y: 1393358.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1688539.25
      sim_grid_pos_y: 1393578.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1688829.5
      sim_grid_pos_y: 1393670.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689085.38
      sim_grid_pos_y: 1393548.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1689292.25
      sim_grid_pos_y: 1393412.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1689334.12
      sim_grid_pos_y: 1393119.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1689010.5
      sim_grid_pos_y: 1392828.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1688629.5
      sim_grid_pos_y: 1392468
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1688242.88
      sim_grid_pos_y: 1392409
    }
    terrain_level_point {
      sim_grid_pos_x: 1688156.25
      sim_grid_pos_y: 1392937.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1688326.88
      sim_grid_pos_y: 1393374.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1688521.5
      sim_grid_pos_y: 1393605
    }
    terrain_level_point {
      sim_grid_pos_x: 1688831.75
      sim_grid_pos_y: 1393703.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689100.5
      sim_grid_pos_y: 1393575.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1689320.75
      sim_grid_pos_y: 1393430.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1689366.88
      sim_grid_pos_y: 1393107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1689031.5
      sim_grid_pos_y: 1392805.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1688642.75
      sim_grid_pos_y: 1392438.12
    }
  }
}
