terrain_level_data {
  terrain_level: 290
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1438901.88
      sim_grid_pos_y: 1532938.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436732.75
      sim_grid_pos_y: 1532770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1435502.75
      sim_grid_pos_y: 1532937.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434056.38
      sim_grid_pos_y: 1532968.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1433713.12
      sim_grid_pos_y: 1532861.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433290.75
      sim_grid_pos_y: 1532270.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1433110.75
      sim_grid_pos_y: 1532132.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.43307e+06
      sim_grid_pos_y: 1531994
    }
    terrain_level_point {
      sim_grid_pos_x: 1433234.12
      sim_grid_pos_y: 1531941
    }
    terrain_level_point {
      sim_grid_pos_x: 1433407.5
      sim_grid_pos_y: 1531846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433574.38
      sim_grid_pos_y: 1531596.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433833.5
      sim_grid_pos_y: 1531795
    }
    terrain_level_point {
      sim_grid_pos_x: 1434152.62
      sim_grid_pos_y: 1531493.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434286.88
      sim_grid_pos_y: 1531641.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434275.5
      sim_grid_pos_y: 1531681.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434366.62
      sim_grid_pos_y: 1531702.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434419.5
      sim_grid_pos_y: 1531737.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434405.75
      sim_grid_pos_y: 1531808.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434497.5
      sim_grid_pos_y: 1531802.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434565.25
      sim_grid_pos_y: 1531681.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434650.38
      sim_grid_pos_y: 1531800.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434817.12
      sim_grid_pos_y: 1531810.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434979.12
      sim_grid_pos_y: 1531848.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1435471.38
      sim_grid_pos_y: 1532095.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435757.62
      sim_grid_pos_y: 1532068.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1435732.62
      sim_grid_pos_y: 1532048.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436469
      sim_grid_pos_y: 1531948.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436491.75
      sim_grid_pos_y: 1531706.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1436472.12
      sim_grid_pos_y: 1531622.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436539
      sim_grid_pos_y: 1531558
    }
    terrain_level_point {
      sim_grid_pos_x: 1436604.88
      sim_grid_pos_y: 1531497
    }
    terrain_level_point {
      sim_grid_pos_x: 1436636.75
      sim_grid_pos_y: 1531385.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436715.62
      sim_grid_pos_y: 1531205.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436809.38
      sim_grid_pos_y: 1531159.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1436864.62
      sim_grid_pos_y: 1531286.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1437162.12
      sim_grid_pos_y: 1531361.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437307.38
      sim_grid_pos_y: 1531760.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1437305.25
      sim_grid_pos_y: 1531863.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437256.62
      sim_grid_pos_y: 1531984.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437450.62
      sim_grid_pos_y: 1532010.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1438076
      sim_grid_pos_y: 1532009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1438356.75
      sim_grid_pos_y: 1532087.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438424.62
      sim_grid_pos_y: 1532093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1438699.88
      sim_grid_pos_y: 1532083.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438765.5
      sim_grid_pos_y: 1532108.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438828.75
      sim_grid_pos_y: 1532185.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1438904.38
      sim_grid_pos_y: 1532516.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1436886.75
      sim_grid_pos_y: 1531260.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1437185.5
      sim_grid_pos_y: 1531335.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1437338.25
      sim_grid_pos_y: 1531755.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1437335.88
      sim_grid_pos_y: 1531869.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1437299.88
      sim_grid_pos_y: 1531959.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1437452.62
      sim_grid_pos_y: 1531979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438080.25
      sim_grid_pos_y: 1531978.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1438362.25
      sim_grid_pos_y: 1532057.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1438425.38
      sim_grid_pos_y: 1532062.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438705
      sim_grid_pos_y: 1532052.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438784.12
      sim_grid_pos_y: 1532082.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1438857.12
      sim_grid_pos_y: 1532172
    }
    terrain_level_point {
      sim_grid_pos_x: 1438935.12
      sim_grid_pos_y: 1532513
    }
    terrain_level_point {
      sim_grid_pos_x: 1438932.5
      sim_grid_pos_y: 1532971.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436733.62
      sim_grid_pos_y: 1532801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1435505.12
      sim_grid_pos_y: 1532968
    }
    terrain_level_point {
      sim_grid_pos_x: 1434052
      sim_grid_pos_y: 1532999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433694.12
      sim_grid_pos_y: 1532887.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1433268.38
      sim_grid_pos_y: 1532292.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433084.12
      sim_grid_pos_y: 1532150.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433032
      sim_grid_pos_y: 1531974
    }
    terrain_level_point {
      sim_grid_pos_x: 1433222
      sim_grid_pos_y: 1531912.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1433386.12
      sim_grid_pos_y: 1531823.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1433567
      sim_grid_pos_y: 1531552.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1433831.38
      sim_grid_pos_y: 1531754.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434154.25
      sim_grid_pos_y: 1.53145e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1434321.12
      sim_grid_pos_y: 1531633
    }
    terrain_level_point {
      sim_grid_pos_x: 1434313.88
      sim_grid_pos_y: 1531658.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434379
      sim_grid_pos_y: 1531673.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434453.62
      sim_grid_pos_y: 1531723.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434443.62
      sim_grid_pos_y: 1531775.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434478.75
      sim_grid_pos_y: 1531772.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434562.12
      sim_grid_pos_y: 1531624.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434666.88
      sim_grid_pos_y: 1531770.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434821.5
      sim_grid_pos_y: 1531780.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434989.62
      sim_grid_pos_y: 1531819.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435477.25
      sim_grid_pos_y: 1532063.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1435702.25
      sim_grid_pos_y: 1532043.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1435708.5
      sim_grid_pos_y: 1532020.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436440.62
      sim_grid_pos_y: 1531921
    }
    terrain_level_point {
      sim_grid_pos_x: 1436460.62
      sim_grid_pos_y: 1531708.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436438.25
      sim_grid_pos_y: 1531612.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436517.88
      sim_grid_pos_y: 1531535.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436577.62
      sim_grid_pos_y: 1531480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436607.75
      sim_grid_pos_y: 1531374.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1436692
      sim_grid_pos_y: 1531182.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436824.75
      sim_grid_pos_y: 1531118.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1436909
      sim_grid_pos_y: 1531234
    }
    terrain_level_point {
      sim_grid_pos_x: 1437208.75
      sim_grid_pos_y: 1.53131e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1437369.12
      sim_grid_pos_y: 1531750.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1437366.5
      sim_grid_pos_y: 1531876.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1437343.25
      sim_grid_pos_y: 1531934.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1437454.62
      sim_grid_pos_y: 1531949
    }
    terrain_level_point {
      sim_grid_pos_x: 1438084.38
      sim_grid_pos_y: 1531947.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1438367.75
      sim_grid_pos_y: 1532027
    }
    terrain_level_point {
      sim_grid_pos_x: 1438426.12
      sim_grid_pos_y: 1532031.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1438710.12
      sim_grid_pos_y: 1532021.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1438802.75
      sim_grid_pos_y: 1532057.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1438885.5
      sim_grid_pos_y: 1532158
    }
    terrain_level_point {
      sim_grid_pos_x: 1438966
      sim_grid_pos_y: 1532509.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1438963
      sim_grid_pos_y: 1533005
    }
    terrain_level_point {
      sim_grid_pos_x: 1436734.5
      sim_grid_pos_y: 1532832.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1435507.5
      sim_grid_pos_y: 1532998.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434047.62
      sim_grid_pos_y: 1533030.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433675.12
      sim_grid_pos_y: 1532913.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433246
      sim_grid_pos_y: 1532313.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433057.38
      sim_grid_pos_y: 1532169.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1432994.12
      sim_grid_pos_y: 1531953.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433209.75
      sim_grid_pos_y: 1531884.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433364.75
      sim_grid_pos_y: 1.5318e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1433559.62
      sim_grid_pos_y: 1531508
    }
    terrain_level_point {
      sim_grid_pos_x: 1433829.38
      sim_grid_pos_y: 1531714.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434155.88
      sim_grid_pos_y: 1531406.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434355.25
      sim_grid_pos_y: 1531624.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434352.12
      sim_grid_pos_y: 1531636
    }
    terrain_level_point {
      sim_grid_pos_x: 1434391.38
      sim_grid_pos_y: 1531644.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434481.38
      sim_grid_pos_y: 1531705.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434559
      sim_grid_pos_y: 1531567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434683.25
      sim_grid_pos_y: 1531741.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434826
      sim_grid_pos_y: 1531749.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1435000.25
      sim_grid_pos_y: 1531790.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1435483.25
      sim_grid_pos_y: 1532032.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1435678.25
      sim_grid_pos_y: 1532014.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1435684.25
      sim_grid_pos_y: 1531993.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436412.38
      sim_grid_pos_y: 1531893.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1436429.62
      sim_grid_pos_y: 1531710.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1436404.25
      sim_grid_pos_y: 1531602.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436496.75
      sim_grid_pos_y: 1531513.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436550.5
      sim_grid_pos_y: 1531463.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436578.75
      sim_grid_pos_y: 1531364.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436668.38
      sim_grid_pos_y: 1.53116e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1436840.12
      sim_grid_pos_y: 1531076.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1436931.12
      sim_grid_pos_y: 1531207.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1437232.12
      sim_grid_pos_y: 1531284.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.4374e+06
      sim_grid_pos_y: 1531745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1437397.12
      sim_grid_pos_y: 1531882.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1437386.5
      sim_grid_pos_y: 1531908.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1437456.62
      sim_grid_pos_y: 1531918.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1438088.62
      sim_grid_pos_y: 1531917
    }
    terrain_level_point {
      sim_grid_pos_x: 1438373.25
      sim_grid_pos_y: 1531996.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1438426.88
      sim_grid_pos_y: 1532001.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1438715.25
      sim_grid_pos_y: 1531990.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1438821.25
      sim_grid_pos_y: 1532031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1438913.88
      sim_grid_pos_y: 1532144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1438996.75
      sim_grid_pos_y: 1532506.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1438993.62
      sim_grid_pos_y: 1533038.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436735.38
      sim_grid_pos_y: 1532863.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.43551e+06
      sim_grid_pos_y: 1533029.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434043.25
      sim_grid_pos_y: 1533061
    }
    terrain_level_point {
      sim_grid_pos_x: 1433656.12
      sim_grid_pos_y: 1.53294e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1433223.75
      sim_grid_pos_y: 1532335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433030.75
      sim_grid_pos_y: 1532187.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432956.12
      sim_grid_pos_y: 1531933.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433197.62
      sim_grid_pos_y: 1531855.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433343.38
      sim_grid_pos_y: 1531776.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1433552.25
      sim_grid_pos_y: 1531463.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1433827.25
      sim_grid_pos_y: 1531674
    }
    terrain_level_point {
      sim_grid_pos_x: 1434157.5
      sim_grid_pos_y: 1531362.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434385
      sim_grid_pos_y: 1531611.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434403.75
      sim_grid_pos_y: 1531616
    }
    terrain_level_point {
      sim_grid_pos_x: 1434471
      sim_grid_pos_y: 1531661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434556
      sim_grid_pos_y: 1531510.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434699.75
      sim_grid_pos_y: 1531711.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434830.5
      sim_grid_pos_y: 1531719
    }
    terrain_level_point {
      sim_grid_pos_x: 1435010.75
      sim_grid_pos_y: 1531761.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1435489.12
      sim_grid_pos_y: 1532001
    }
    terrain_level_point {
      sim_grid_pos_x: 1435654.38
      sim_grid_pos_y: 1531985.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1435660.12
      sim_grid_pos_y: 1531965.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1436384
      sim_grid_pos_y: 1531866.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1436398.5
      sim_grid_pos_y: 1531712.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436370.38
      sim_grid_pos_y: 1531592.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1436475.62
      sim_grid_pos_y: 1531490.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436523.25
      sim_grid_pos_y: 1531446.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436549.75
      sim_grid_pos_y: 1531353.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1436644.75
      sim_grid_pos_y: 1531137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1436855.5
      sim_grid_pos_y: 1531034.75
    }
  }
}
