terrain_level_data {
  terrain_level: 450
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2136259.75
      sim_grid_pos_y: 1342123.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2138884.75
      sim_grid_pos_y: 1343748.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2140772.25
      sim_grid_pos_y: 1340736.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2140816
      sim_grid_pos_y: 1339754.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2140438
      sim_grid_pos_y: 1339714.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2140148.75
      sim_grid_pos_y: 1340119
    }
    terrain_level_point {
      sim_grid_pos_x: 2138829.25
      sim_grid_pos_y: 1341146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2138169.5
      sim_grid_pos_y: 1341535
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2140423.25
      sim_grid_pos_y: 1339681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2140126.5
      sim_grid_pos_y: 1340097.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2138812
      sim_grid_pos_y: 1341120.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2138157
      sim_grid_pos_y: 1341506.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2136231.75
      sim_grid_pos_y: 1342100.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2136226.75
      sim_grid_pos_y: 1342139.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2138894.5
      sim_grid_pos_y: 1343790.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2140802.5
      sim_grid_pos_y: 1340745.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2140848
      sim_grid_pos_y: 1339727.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2140408.75
      sim_grid_pos_y: 1339649.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2140104
      sim_grid_pos_y: 1340075.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2138794.5
      sim_grid_pos_y: 1341095.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2138144.5
      sim_grid_pos_y: 1341478.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2136203.75
      sim_grid_pos_y: 1342076.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2136193.75
      sim_grid_pos_y: 1342155.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2138904.5
      sim_grid_pos_y: 1343833.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2140833
      sim_grid_pos_y: 1340755
    }
    terrain_level_point {
      sim_grid_pos_x: 2.14088e+06
      sim_grid_pos_y: 1339699.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2140394.25
      sim_grid_pos_y: 1339616.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2140081.5
      sim_grid_pos_y: 1340054.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2138777.25
      sim_grid_pos_y: 1341069.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2138132
      sim_grid_pos_y: 1.34145e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2136175.75
      sim_grid_pos_y: 1342053
    }
    terrain_level_point {
      sim_grid_pos_x: 2136160.75
      sim_grid_pos_y: 1342170.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2138914.25
      sim_grid_pos_y: 1343875.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2140863.25
      sim_grid_pos_y: 1340764.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2140912
      sim_grid_pos_y: 1339672.38
    }
  }
}
