terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 371039.375
      sim_grid_pos_y: 1863091.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371089.156
      sim_grid_pos_y: 1863317.38
    }
    terrain_level_point {
      sim_grid_pos_x: 372351.75
      sim_grid_pos_y: 1863599.38
    }
    terrain_level_point {
      sim_grid_pos_x: 372966.344
      sim_grid_pos_y: 1863567.62
    }
    terrain_level_point {
      sim_grid_pos_x: 373131.875
      sim_grid_pos_y: 1863471.88
    }
    terrain_level_point {
      sim_grid_pos_x: 373518.688
      sim_grid_pos_y: 1863988.25
    }
    terrain_level_point {
      sim_grid_pos_x: 373747.406
      sim_grid_pos_y: 1.86392e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 375969.031
      sim_grid_pos_y: 1862435.25
    }
    terrain_level_point {
      sim_grid_pos_x: 375655.969
      sim_grid_pos_y: 1861967.25
    }
    terrain_level_point {
      sim_grid_pos_x: 375879.875
      sim_grid_pos_y: 1861856.38
    }
    terrain_level_point {
      sim_grid_pos_x: 375830.156
      sim_grid_pos_y: 1861719.75
    }
    terrain_level_point {
      sim_grid_pos_x: 375631.125
      sim_grid_pos_y: 1861391.88
    }
    terrain_level_point {
      sim_grid_pos_x: 375683.625
      sim_grid_pos_y: 1861221.25
    }
    terrain_level_point {
      sim_grid_pos_x: 375492.031
      sim_grid_pos_y: 1860968.38
    }
    terrain_level_point {
      sim_grid_pos_x: 375551.125
      sim_grid_pos_y: 1860726.75
    }
    terrain_level_point {
      sim_grid_pos_x: 375488.125
      sim_grid_pos_y: 1860479
    }
    terrain_level_point {
      sim_grid_pos_x: 375482.469
      sim_grid_pos_y: 1860163
    }
    terrain_level_point {
      sim_grid_pos_x: 375417.062
      sim_grid_pos_y: 1860204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 374597.781
      sim_grid_pos_y: 1860718.62
    }
    terrain_level_point {
      sim_grid_pos_x: 374554.594
      sim_grid_pos_y: 1860673.75
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 371142.031
      sim_grid_pos_y: 1863440.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371331.938
      sim_grid_pos_y: 1864094.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371302.219
      sim_grid_pos_y: 1864712.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371521.406
      sim_grid_pos_y: 1864864.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371549.219
      sim_grid_pos_y: 1864765
    }
    terrain_level_point {
      sim_grid_pos_x: 371667.531
      sim_grid_pos_y: 1864765.38
    }
    terrain_level_point {
      sim_grid_pos_x: 372170.344
      sim_grid_pos_y: 1864034.38
    }
    terrain_level_point {
      sim_grid_pos_x: 372103.344
      sim_grid_pos_y: 1864010.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372127.406
      sim_grid_pos_y: 1863861
    }
    terrain_level_point {
      sim_grid_pos_x: 373236.656
      sim_grid_pos_y: 1863825.75
    }
    terrain_level_point {
      sim_grid_pos_x: 373241.438
      sim_grid_pos_y: 1863755.75
    }
    terrain_level_point {
      sim_grid_pos_x: 373253.688
      sim_grid_pos_y: 1863726.12
    }
    terrain_level_point {
      sim_grid_pos_x: 373130.531
      sim_grid_pos_y: 1863554.75
    }
    terrain_level_point {
      sim_grid_pos_x: 372941.406
      sim_grid_pos_y: 1863666.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372334.594
      sim_grid_pos_y: 1863701.25
    }
    terrain_level_point {
      sim_grid_pos_x: 372130.281
      sim_grid_pos_y: 1863625.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371789.125
      sim_grid_pos_y: 1863555
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 371098.719
      sim_grid_pos_y: 1863401.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371300.969
      sim_grid_pos_y: 1864098.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371270.688
      sim_grid_pos_y: 1864727.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371539.406
      sim_grid_pos_y: 1864914.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371572.562
      sim_grid_pos_y: 1864795.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371683.656
      sim_grid_pos_y: 1864796.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372218.25
      sim_grid_pos_y: 1864019
    }
    terrain_level_point {
      sim_grid_pos_x: 372137.781
      sim_grid_pos_y: 1863989.88
    }
    terrain_level_point {
      sim_grid_pos_x: 372153.75
      sim_grid_pos_y: 1863890.88
    }
    terrain_level_point {
      sim_grid_pos_x: 373265.438
      sim_grid_pos_y: 1863855.62
    }
    terrain_level_point {
      sim_grid_pos_x: 373271.781
      sim_grid_pos_y: 1863762.75
    }
    terrain_level_point {
      sim_grid_pos_x: 373288.656
      sim_grid_pos_y: 1863722.12
    }
    terrain_level_point {
      sim_grid_pos_x: 373139.125
      sim_grid_pos_y: 1863514
    }
    terrain_level_point {
      sim_grid_pos_x: 372932.219
      sim_grid_pos_y: 1863635.75
    }
    terrain_level_point {
      sim_grid_pos_x: 372339.219
      sim_grid_pos_y: 1863670.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372138.781
      sim_grid_pos_y: 1863595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371794.906
      sim_grid_pos_y: 1863524.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 371055.406
      sim_grid_pos_y: 1863362.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371270
      sim_grid_pos_y: 1864101.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371239.125
      sim_grid_pos_y: 1864743.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371557.406
      sim_grid_pos_y: 1864964.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371595.906
      sim_grid_pos_y: 1864826.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371699.812
      sim_grid_pos_y: 1864827
    }
    terrain_level_point {
      sim_grid_pos_x: 372266.125
      sim_grid_pos_y: 1864003.75
    }
    terrain_level_point {
      sim_grid_pos_x: 372172.188
      sim_grid_pos_y: 1863969.62
    }
    terrain_level_point {
      sim_grid_pos_x: 372180.062
      sim_grid_pos_y: 1863920.88
    }
    terrain_level_point {
      sim_grid_pos_x: 373294.25
      sim_grid_pos_y: 1863885.5
    }
    terrain_level_point {
      sim_grid_pos_x: 373302.125
      sim_grid_pos_y: 1.86377e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 373323.656
      sim_grid_pos_y: 1863718.12
    }
    terrain_level_point {
      sim_grid_pos_x: 373147.688
      sim_grid_pos_y: 1863473.25
    }
    terrain_level_point {
      sim_grid_pos_x: 372923
      sim_grid_pos_y: 1863605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 372343.906
      sim_grid_pos_y: 1863639.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372147.312
      sim_grid_pos_y: 1863566.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371800.719
      sim_grid_pos_y: 1863494.62
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 370978.625
      sim_grid_pos_y: 1862851.5
    }
    terrain_level_point {
      sim_grid_pos_x: 370944.969
      sim_grid_pos_y: 1862713.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371322.562
      sim_grid_pos_y: 1862438.75
    }
    terrain_level_point {
      sim_grid_pos_x: 371525.844
      sim_grid_pos_y: 1862125.62
    }
    terrain_level_point {
      sim_grid_pos_x: 372473.531
      sim_grid_pos_y: 1861415.62
    }
    terrain_level_point {
      sim_grid_pos_x: 373032.938
      sim_grid_pos_y: 1861053.88
    }
    terrain_level_point {
      sim_grid_pos_x: 373652.156
      sim_grid_pos_y: 1860855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 374360.219
      sim_grid_pos_y: 1860335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 375156.719
      sim_grid_pos_y: 1860080.62
    }
    terrain_level_point {
      sim_grid_pos_x: 375345.5
      sim_grid_pos_y: 1860186.88
    }
    terrain_level_point {
      sim_grid_pos_x: 374652
      sim_grid_pos_y: 1860600.12
    }
    terrain_level_point {
      sim_grid_pos_x: 374576.969
      sim_grid_pos_y: 1860513.88
    }
    terrain_level_point {
      sim_grid_pos_x: 374212.031
      sim_grid_pos_y: 1860769.62
    }
    terrain_level_point {
      sim_grid_pos_x: 374177.625
      sim_grid_pos_y: 1860850.38
    }
    terrain_level_point {
      sim_grid_pos_x: 373255.25
      sim_grid_pos_y: 1861514.38
    }
    terrain_level_point {
      sim_grid_pos_x: 372925.125
      sim_grid_pos_y: 1861526.75
    }
    terrain_level_point {
      sim_grid_pos_x: 372430.469
      sim_grid_pos_y: 1861924
    }
    terrain_level_point {
      sim_grid_pos_x: 372418.469
      sim_grid_pos_y: 1862026.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371662.969
      sim_grid_pos_y: 1862586.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371401.688
      sim_grid_pos_y: 1862768.88
    }
    terrain_level_point {
      sim_grid_pos_x: 371278.938
      sim_grid_pos_y: 1862773.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371153.406
      sim_grid_pos_y: 1862867
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 375406.844
      sim_grid_pos_y: 1860186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 374645.656
      sim_grid_pos_y: 1860639.62
    }
    terrain_level_point {
      sim_grid_pos_x: 374571.938
      sim_grid_pos_y: 1860555
    }
    terrain_level_point {
      sim_grid_pos_x: 374236.875
      sim_grid_pos_y: 1860789.75
    }
    terrain_level_point {
      sim_grid_pos_x: 374202.562
      sim_grid_pos_y: 1860870.25
    }
    terrain_level_point {
      sim_grid_pos_x: 373265.688
      sim_grid_pos_y: 1861544.75
    }
    terrain_level_point {
      sim_grid_pos_x: 372936.438
      sim_grid_pos_y: 1861557.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372459.562
      sim_grid_pos_y: 1861940.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372447.469
      sim_grid_pos_y: 1862043.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371680.938
      sim_grid_pos_y: 1862611.5
    }
    terrain_level_point {
      sim_grid_pos_x: 371411.875
      sim_grid_pos_y: 1862799.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371289.656
      sim_grid_pos_y: 1862804
    }
    terrain_level_point {
      sim_grid_pos_x: 371162.375
      sim_grid_pos_y: 1862898.62
    }
    terrain_level_point {
      sim_grid_pos_x: 370953.969
      sim_grid_pos_y: 1862880.12
    }
    terrain_level_point {
      sim_grid_pos_x: 370910.188
      sim_grid_pos_y: 1862701.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371299.844
      sim_grid_pos_y: 1862417.25
    }
    terrain_level_point {
      sim_grid_pos_x: 371503.031
      sim_grid_pos_y: 1862104.25
    }
    terrain_level_point {
      sim_grid_pos_x: 372455.938
      sim_grid_pos_y: 1861390.38
    }
    terrain_level_point {
      sim_grid_pos_x: 373019.656
      sim_grid_pos_y: 1861025.88
    }
    terrain_level_point {
      sim_grid_pos_x: 373638
      sim_grid_pos_y: 1860827.75
    }
    terrain_level_point {
      sim_grid_pos_x: 374346.062
      sim_grid_pos_y: 1860307.62
    }
    terrain_level_point {
      sim_grid_pos_x: 375160.125
      sim_grid_pos_y: 1860047.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 375468.188
      sim_grid_pos_y: 1860185.38
    }
    terrain_level_point {
      sim_grid_pos_x: 374639.344
      sim_grid_pos_y: 1860679.25
    }
    terrain_level_point {
      sim_grid_pos_x: 374566.938
      sim_grid_pos_y: 1860596.12
    }
    terrain_level_point {
      sim_grid_pos_x: 374261.719
      sim_grid_pos_y: 1860809.88
    }
    terrain_level_point {
      sim_grid_pos_x: 374227.5
      sim_grid_pos_y: 1860890.25
    }
    terrain_level_point {
      sim_grid_pos_x: 373276.125
      sim_grid_pos_y: 1861575.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372947.781
      sim_grid_pos_y: 1861587.5
    }
    terrain_level_point {
      sim_grid_pos_x: 372488.625
      sim_grid_pos_y: 1861956.12
    }
    terrain_level_point {
      sim_grid_pos_x: 372476.469
      sim_grid_pos_y: 1862060.12
    }
    terrain_level_point {
      sim_grid_pos_x: 371698.906
      sim_grid_pos_y: 1862636.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371422.094
      sim_grid_pos_y: 1862829.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371300.375
      sim_grid_pos_y: 1862834.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371171.312
      sim_grid_pos_y: 1862930.38
    }
    terrain_level_point {
      sim_grid_pos_x: 370929.312
      sim_grid_pos_y: 1862908.88
    }
    terrain_level_point {
      sim_grid_pos_x: 370875.406
      sim_grid_pos_y: 1862688.38
    }
    terrain_level_point {
      sim_grid_pos_x: 371277.156
      sim_grid_pos_y: 1862395.62
    }
    terrain_level_point {
      sim_grid_pos_x: 371480.188
      sim_grid_pos_y: 1862083
    }
    terrain_level_point {
      sim_grid_pos_x: 372438.344
      sim_grid_pos_y: 1861365.12
    }
    terrain_level_point {
      sim_grid_pos_x: 373006.375
      sim_grid_pos_y: 1860997.88
    }
    terrain_level_point {
      sim_grid_pos_x: 373623.844
      sim_grid_pos_y: 1.8608e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 374331.906
      sim_grid_pos_y: 1860279.88
    }
    terrain_level_point {
      sim_grid_pos_x: 375163.531
      sim_grid_pos_y: 1860013.88
    }
  }
}
