terrain_level_data {
  terrain_level: 460
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2298299.5
      sim_grid_pos_y: 1329053.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2297527.75
      sim_grid_pos_y: 1326416.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296881
      sim_grid_pos_y: 1322555.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2297006.75
      sim_grid_pos_y: 1321792.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2296138.75
      sim_grid_pos_y: 1321700.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2295736.25
      sim_grid_pos_y: 1322369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2295383
      sim_grid_pos_y: 1324044.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296047.5
      sim_grid_pos_y: 1325363.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296092.75
      sim_grid_pos_y: 1326688.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2296273
      sim_grid_pos_y: 1327592.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296223
      sim_grid_pos_y: 1327868.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2295943.25
      sim_grid_pos_y: 1327953.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296135.5
      sim_grid_pos_y: 1328233.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296331
      sim_grid_pos_y: 1328305.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296367
      sim_grid_pos_y: 1328459.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296350.25
      sim_grid_pos_y: 1329295.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296471
      sim_grid_pos_y: 1330079.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296858.5
      sim_grid_pos_y: 1329584.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2296122.5
      sim_grid_pos_y: 1321667.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2295707.25
      sim_grid_pos_y: 1322358.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2295350.75
      sim_grid_pos_y: 1324048.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296017
      sim_grid_pos_y: 1325371.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2296062.25
      sim_grid_pos_y: 1326691.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296241.75
      sim_grid_pos_y: 1327592.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296196.25
      sim_grid_pos_y: 1327844.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2295894
      sim_grid_pos_y: 1327936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296115.75
      sim_grid_pos_y: 1328259.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2296305
      sim_grid_pos_y: 1328328.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296336.25
      sim_grid_pos_y: 1328462.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296319.5
      sim_grid_pos_y: 1329297.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296443.75
      sim_grid_pos_y: 1330104.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2296482.75
      sim_grid_pos_y: 1330114.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296877.5
      sim_grid_pos_y: 1329610.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2298337
      sim_grid_pos_y: 1329072
    }
    terrain_level_point {
      sim_grid_pos_x: 2297557.75
      sim_grid_pos_y: 1326409.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296912.25
      sim_grid_pos_y: 1322555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297042.25
      sim_grid_pos_y: 1321765
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2296106.25
      sim_grid_pos_y: 1321635
    }
    terrain_level_point {
      sim_grid_pos_x: 2295678
      sim_grid_pos_y: 1322346.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2295318.5
      sim_grid_pos_y: 1324053
    }
    terrain_level_point {
      sim_grid_pos_x: 2295986.5
      sim_grid_pos_y: 1325379.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2296031.5
      sim_grid_pos_y: 1326695.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296210.5
      sim_grid_pos_y: 1327593.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2296169.25
      sim_grid_pos_y: 1327820.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2295844.75
      sim_grid_pos_y: 1327919.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296096
      sim_grid_pos_y: 1328284.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296278.75
      sim_grid_pos_y: 1328351.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296305.5
      sim_grid_pos_y: 1328466.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296288.75
      sim_grid_pos_y: 1329299.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296416.5
      sim_grid_pos_y: 1330129
    }
    terrain_level_point {
      sim_grid_pos_x: 2296494.5
      sim_grid_pos_y: 1330149.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296896.25
      sim_grid_pos_y: 1329636.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2298374.75
      sim_grid_pos_y: 1329091
    }
    terrain_level_point {
      sim_grid_pos_x: 2297587.75
      sim_grid_pos_y: 1326402.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296943.5
      sim_grid_pos_y: 1322555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297078
      sim_grid_pos_y: 1321737.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2.29609e+06
      sim_grid_pos_y: 1321602.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2295649
      sim_grid_pos_y: 1322335.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2295286
      sim_grid_pos_y: 1324057.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2295956
      sim_grid_pos_y: 1325387
    }
    terrain_level_point {
      sim_grid_pos_x: 2296001
      sim_grid_pos_y: 1326698.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296179.25
      sim_grid_pos_y: 1327593.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2296142.25
      sim_grid_pos_y: 1327796.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2295795.75
      sim_grid_pos_y: 1327902
    }
    terrain_level_point {
      sim_grid_pos_x: 2296076
      sim_grid_pos_y: 1328310.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2296252.5
      sim_grid_pos_y: 1328374.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2296274.75
      sim_grid_pos_y: 1328469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2296258
      sim_grid_pos_y: 1329301.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296389
      sim_grid_pos_y: 1330153.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296506.25
      sim_grid_pos_y: 1330184.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296915
      sim_grid_pos_y: 1329662.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2298412.25
      sim_grid_pos_y: 1329109.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2297617.75
      sim_grid_pos_y: 1326396
    }
    terrain_level_point {
      sim_grid_pos_x: 2296974.5
      sim_grid_pos_y: 1322555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297113.5
      sim_grid_pos_y: 1321710.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2296073.75
      sim_grid_pos_y: 1321569.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29562e+06
      sim_grid_pos_y: 1322323.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2295253.75
      sim_grid_pos_y: 1324061.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2295925.5
      sim_grid_pos_y: 1325394.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2295970.25
      sim_grid_pos_y: 1326702.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2296147.75
      sim_grid_pos_y: 1327593.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296115.5
      sim_grid_pos_y: 1327772.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2295746.5
      sim_grid_pos_y: 1327884.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296056.25
      sim_grid_pos_y: 1328336
    }
    terrain_level_point {
      sim_grid_pos_x: 2296226.5
      sim_grid_pos_y: 1328398
    }
    terrain_level_point {
      sim_grid_pos_x: 2296243.75
      sim_grid_pos_y: 1328472.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2296227
      sim_grid_pos_y: 1329303.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2296361.75
      sim_grid_pos_y: 1330178.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2296518
      sim_grid_pos_y: 1330219.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2296934
      sim_grid_pos_y: 1329688
    }
    terrain_level_point {
      sim_grid_pos_x: 2298449.75
      sim_grid_pos_y: 1329128.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2297647.75
      sim_grid_pos_y: 1326389
    }
    terrain_level_point {
      sim_grid_pos_x: 2297005.75
      sim_grid_pos_y: 1322555.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297149.25
      sim_grid_pos_y: 1321683.5
    }
  }
}
