terrain_level_data {
  terrain_level: 35
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1311436
      sim_grid_pos_y: 1436247.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1311216.5
      sim_grid_pos_y: 1440475.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1307820.38
      sim_grid_pos_y: 1440320.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1308064.12
      sim_grid_pos_y: 1439622.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1308337.38
      sim_grid_pos_y: 1438986
    }
    terrain_level_point {
      sim_grid_pos_x: 1310494.38
      sim_grid_pos_y: 1435709.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1311467.62
      sim_grid_pos_y: 1436230.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1311245.62
      sim_grid_pos_y: 1440507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1307777.75
      sim_grid_pos_y: 1440349.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1308035.5
      sim_grid_pos_y: 1439611.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1308310.25
      sim_grid_pos_y: 1438971.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1310484.62
      sim_grid_pos_y: 1435668.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1311499.38
      sim_grid_pos_y: 1436213
    }
    terrain_level_point {
      sim_grid_pos_x: 1311274.88
      sim_grid_pos_y: 1440539.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1307735.12
      sim_grid_pos_y: 1440378.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308006.75
      sim_grid_pos_y: 1439600.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308283
      sim_grid_pos_y: 1438956.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1310474.75
      sim_grid_pos_y: 1435627.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1311531
      sim_grid_pos_y: 1436195.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1311304
      sim_grid_pos_y: 1440571.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1307692.5
      sim_grid_pos_y: 1440407.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1307978.12
      sim_grid_pos_y: 1439589.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1308255.88
      sim_grid_pos_y: 1438942
    }
    terrain_level_point {
      sim_grid_pos_x: 1310465
      sim_grid_pos_y: 1435586.5
    }
  }
}
