terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1831180.12
      sim_grid_pos_y: 1174969.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831182.75
      sim_grid_pos_y: 1175079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831230.38
      sim_grid_pos_y: 1175157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831312.62
      sim_grid_pos_y: 1175185.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1831387
      sim_grid_pos_y: 1175157.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831445
      sim_grid_pos_y: 1175085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831449.12
      sim_grid_pos_y: 1174968.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1831393.75
      sim_grid_pos_y: 1174925.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1831322.38
      sim_grid_pos_y: 1174885
    }
    terrain_level_point {
      sim_grid_pos_x: 1831246.12
      sim_grid_pos_y: 1174918
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1831328.38
      sim_grid_pos_y: 1174770.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831193.38
      sim_grid_pos_y: 1174829.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831076.38
      sim_grid_pos_y: 1174920.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831080.88
      sim_grid_pos_y: 1.17511e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1831162.38
      sim_grid_pos_y: 1175242.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1831314
      sim_grid_pos_y: 1175294.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831449.25
      sim_grid_pos_y: 1175243.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831546.25
      sim_grid_pos_y: 1175123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831553.38
      sim_grid_pos_y: 1174919.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831450.62
      sim_grid_pos_y: 1174839.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1831334.38
      sim_grid_pos_y: 1174656.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831140.5
      sim_grid_pos_y: 1174740.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1830972.62
      sim_grid_pos_y: 1174871.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1830979.12
      sim_grid_pos_y: 1175140.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1831094.38
      sim_grid_pos_y: 1175327.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831315.5
      sim_grid_pos_y: 1175402.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831511.38
      sim_grid_pos_y: 1175330.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831647.5
      sim_grid_pos_y: 1175160.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831657.75
      sim_grid_pos_y: 1174870.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831507.62
      sim_grid_pos_y: 1174754
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1831340.38
      sim_grid_pos_y: 1174542
    }
    terrain_level_point {
      sim_grid_pos_x: 1831087.75
      sim_grid_pos_y: 1174651.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1830869
      sim_grid_pos_y: 1174822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1830877.25
      sim_grid_pos_y: 1175170.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831026.5
      sim_grid_pos_y: 1175412.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831316.88
      sim_grid_pos_y: 1175511.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1831573.5
      sim_grid_pos_y: 1175416.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831748.75
      sim_grid_pos_y: 1175198.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831762
      sim_grid_pos_y: 1174821.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831564.5
      sim_grid_pos_y: 1174668.5
    }
  }
}
terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1831481.25
      sim_grid_pos_y: 1175337.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831637.12
      sim_grid_pos_y: 1175481.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831862.62
      sim_grid_pos_y: 1175287.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1831726.12
      sim_grid_pos_y: 1175116.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1831732.25
      sim_grid_pos_y: 1175041.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831405.25
      sim_grid_pos_y: 1175336.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831635.75
      sim_grid_pos_y: 1.17555e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1831933.5
      sim_grid_pos_y: 1175294.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1831738.38
      sim_grid_pos_y: 1174967.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831329.25
      sim_grid_pos_y: 1175336.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1831634.5
      sim_grid_pos_y: 1175618.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1832004.38
      sim_grid_pos_y: 1175301.25
    }
  }
}
terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1831866.88
      sim_grid_pos_y: 1174888.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1832115.88
      sim_grid_pos_y: 1175080.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1831992.12
      sim_grid_pos_y: 1175207.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831763
      sim_grid_pos_y: 1175052.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1832192.75
      sim_grid_pos_y: 1175075.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831998.88
      sim_grid_pos_y: 1175273.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831693
      sim_grid_pos_y: 1175066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1831853.62
      sim_grid_pos_y: 1174813.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1832269.75
      sim_grid_pos_y: 1.17507e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1832005.62
      sim_grid_pos_y: 1175340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831623
      sim_grid_pos_y: 1175081.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1831840.5
      sim_grid_pos_y: 1174739
    }
  }
}
terrain_level_data {
  terrain_level: 155
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1829320.62
      sim_grid_pos_y: 1175406.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1829169.25
      sim_grid_pos_y: 1175198.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1828887.25
      sim_grid_pos_y: 1175319.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1828799.25
      sim_grid_pos_y: 1175464.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1828792.88
      sim_grid_pos_y: 1175668.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1829072.88
      sim_grid_pos_y: 1175777
    }
    terrain_level_point {
      sim_grid_pos_x: 1829256.88
      sim_grid_pos_y: 1175660.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1829186.75
      sim_grid_pos_y: 1175135.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1828852
      sim_grid_pos_y: 1175279.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1828748.38
      sim_grid_pos_y: 1175449.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1828740.62
      sim_grid_pos_y: 1175703.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1829078.5
      sim_grid_pos_y: 1175834.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1829301.62
      sim_grid_pos_y: 1175692.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1829376.25
      sim_grid_pos_y: 1175396.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1829204.12
      sim_grid_pos_y: 1175072.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1828816.75
      sim_grid_pos_y: 1175238.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1828697.5
      sim_grid_pos_y: 1175434.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1828688.25
      sim_grid_pos_y: 1175738
    }
    terrain_level_point {
      sim_grid_pos_x: 1829084.12
      sim_grid_pos_y: 1175891.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1829346.38
      sim_grid_pos_y: 1175725
    }
    terrain_level_point {
      sim_grid_pos_x: 1829431.75
      sim_grid_pos_y: 1175385.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1829221.5
      sim_grid_pos_y: 1175009.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1828781.38
      sim_grid_pos_y: 1175197.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1828646.75
      sim_grid_pos_y: 1175419.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1828635.88
      sim_grid_pos_y: 1175772.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1829089.62
      sim_grid_pos_y: 1175948.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1829391
      sim_grid_pos_y: 1175757.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1829487.38
      sim_grid_pos_y: 1175374.62
    }
  }
}
terrain_level_data {
  terrain_level: 65
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1831010.5
      sim_grid_pos_y: 1167219.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1831016.38
      sim_grid_pos_y: 1167631.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831282.62
      sim_grid_pos_y: 1167635.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831283.62
      sim_grid_pos_y: 1167233.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1830958.5
      sim_grid_pos_y: 1167165.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1830965.88
      sim_grid_pos_y: 1167682.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1831333.75
      sim_grid_pos_y: 1167687.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831335
      sim_grid_pos_y: 1167185.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1830906.5
      sim_grid_pos_y: 1167111.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1830915.38
      sim_grid_pos_y: 1167732.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1831384.88
      sim_grid_pos_y: 1167739.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831386.38
      sim_grid_pos_y: 1167136.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1830854.38
      sim_grid_pos_y: 1167057.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1830864.75
      sim_grid_pos_y: 1167783.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1831436
      sim_grid_pos_y: 1167791.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1831437.75
      sim_grid_pos_y: 1167087.88
    }
  }
}
terrain_level_data {
  terrain_level: 118
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1828663.12
      sim_grid_pos_y: 1176876.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1828492.88
      sim_grid_pos_y: 1177031.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1828597.25
      sim_grid_pos_y: 1177153.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1828802
      sim_grid_pos_y: 1177013
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1828664.38
      sim_grid_pos_y: 1176806.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1828421.62
      sim_grid_pos_y: 1177026.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1828588.25
      sim_grid_pos_y: 1177221.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1828882.5
      sim_grid_pos_y: 1177020.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1828665.75
      sim_grid_pos_y: 1176735.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1828350.25
      sim_grid_pos_y: 1177022.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1828579.25
      sim_grid_pos_y: 1.17729e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1828962.88
      sim_grid_pos_y: 1177027.12
    }
  }
}
