terrain_level_data {
  terrain_level: 185
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2939348
      sim_grid_pos_y: 575978
    }
    terrain_level_point {
      sim_grid_pos_x: 2927332.25
      sim_grid_pos_y: 573331.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2927735.25
      sim_grid_pos_y: 571298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2929723.25
      sim_grid_pos_y: 570793.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2935828.5
      sim_grid_pos_y: 573265.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2939712
      sim_grid_pos_y: 574064.625
    }
  }
}
