terrain_level_data {
  terrain_level: 341
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1486449.88
      sim_grid_pos_y: 1728645.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1486650.38
      sim_grid_pos_y: 1727824
    }
    terrain_level_point {
      sim_grid_pos_x: 1486923.12
      sim_grid_pos_y: 1727841.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487098.38
      sim_grid_pos_y: 1728012.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487375.75
      sim_grid_pos_y: 1727994.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487476.25
      sim_grid_pos_y: 1727963.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487579.5
      sim_grid_pos_y: 1728005
    }
    terrain_level_point {
      sim_grid_pos_x: 1487636
      sim_grid_pos_y: 1728081.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487685.12
      sim_grid_pos_y: 1728179.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487726.12
      sim_grid_pos_y: 1728301
    }
    terrain_level_point {
      sim_grid_pos_x: 1487762.5
      sim_grid_pos_y: 1728356.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487869.12
      sim_grid_pos_y: 1728433.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488120.12
      sim_grid_pos_y: 1728488.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488110.12
      sim_grid_pos_y: 1728448.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488194.75
      sim_grid_pos_y: 1728433
    }
    terrain_level_point {
      sim_grid_pos_x: 1488221.25
      sim_grid_pos_y: 1728399.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488249.38
      sim_grid_pos_y: 1728436.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488283.62
      sim_grid_pos_y: 1728411
    }
    terrain_level_point {
      sim_grid_pos_x: 1488352
      sim_grid_pos_y: 1728541.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488378.5
      sim_grid_pos_y: 1728671.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488414.75
      sim_grid_pos_y: 1728705.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488504
      sim_grid_pos_y: 1728727.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488586.88
      sim_grid_pos_y: 1728699.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488647
      sim_grid_pos_y: 1728690.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1488707.75
      sim_grid_pos_y: 1728718.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488737.5
      sim_grid_pos_y: 1.72876e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1488591.62
      sim_grid_pos_y: 1729064.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488575
      sim_grid_pos_y: 1729153.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488539.25
      sim_grid_pos_y: 1729219.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488407.12
      sim_grid_pos_y: 1729235
    }
    terrain_level_point {
      sim_grid_pos_x: 1488300.25
      sim_grid_pos_y: 1.72928e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1488223
      sim_grid_pos_y: 1729363.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488191.75
      sim_grid_pos_y: 1.72949e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1488334.25
      sim_grid_pos_y: 1729664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1488474.75
      sim_grid_pos_y: 1729710.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487109.38
      sim_grid_pos_y: 1729966.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487128.12
      sim_grid_pos_y: 1729679.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487148.88
      sim_grid_pos_y: 1729517.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1487126.62
      sim_grid_pos_y: 1729421.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1486934.25
      sim_grid_pos_y: 1729149.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.48685e+06
      sim_grid_pos_y: 1729024.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1486677.5
      sim_grid_pos_y: 1728921.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1486936.38
      sim_grid_pos_y: 1727811.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.48711e+06
      sim_grid_pos_y: 1727981.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1487370.12
      sim_grid_pos_y: 1727963.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487477.62
      sim_grid_pos_y: 1727931
    }
    terrain_level_point {
      sim_grid_pos_x: 1487599
      sim_grid_pos_y: 1727979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1487662.25
      sim_grid_pos_y: 1728065.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1487713.62
      sim_grid_pos_y: 1728167.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487754
      sim_grid_pos_y: 1728287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487785.12
      sim_grid_pos_y: 1728334.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487881.88
      sim_grid_pos_y: 1728405
    }
    terrain_level_point {
      sim_grid_pos_x: 1488078.25
      sim_grid_pos_y: 1728448
    }
    terrain_level_point {
      sim_grid_pos_x: 1488072.38
      sim_grid_pos_y: 1728424.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488177.75
      sim_grid_pos_y: 1728404.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488221.75
      sim_grid_pos_y: 1728349.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488255.5
      sim_grid_pos_y: 1728393.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488294.25
      sim_grid_pos_y: 1728365
    }
    terrain_level_point {
      sim_grid_pos_x: 1488381.25
      sim_grid_pos_y: 1728530.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488406.75
      sim_grid_pos_y: 1728655.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.48843e+06
      sim_grid_pos_y: 1728677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488502.62
      sim_grid_pos_y: 1728695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488579.5
      sim_grid_pos_y: 1728669.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488651.5
      sim_grid_pos_y: 1728658.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488728.12
      sim_grid_pos_y: 1728694
    }
    terrain_level_point {
      sim_grid_pos_x: 1488773.12
      sim_grid_pos_y: 1728757
    }
    terrain_level_point {
      sim_grid_pos_x: 1488621.12
      sim_grid_pos_y: 1729073.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488604.25
      sim_grid_pos_y: 1729164.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1488558.62
      sim_grid_pos_y: 1729248
    }
    terrain_level_point {
      sim_grid_pos_x: 1488415
      sim_grid_pos_y: 1729265
    }
    terrain_level_point {
      sim_grid_pos_x: 1488318.38
      sim_grid_pos_y: 1729305.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488251
      sim_grid_pos_y: 1729378.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488225.38
      sim_grid_pos_y: 1729482.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488352.38
      sim_grid_pos_y: 1729637.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488507
      sim_grid_pos_y: 1729688.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488503.88
      sim_grid_pos_y: 1729736.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1487076
      sim_grid_pos_y: 1730004.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487097.5
      sim_grid_pos_y: 1729676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487117.62
      sim_grid_pos_y: 1729519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1487098
      sim_grid_pos_y: 1729434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1486908.88
      sim_grid_pos_y: 1729166.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1486828.38
      sim_grid_pos_y: 1729047.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1486657.12
      sim_grid_pos_y: 1728945.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1486416.38
      sim_grid_pos_y: 1728653.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1486626.5
      sim_grid_pos_y: 1727791.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1486949.75
      sim_grid_pos_y: 1727781.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487121.75
      sim_grid_pos_y: 1727949.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1487364.5
      sim_grid_pos_y: 1727933.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487479
      sim_grid_pos_y: 1727898.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487618.62
      sim_grid_pos_y: 1727954.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487688.62
      sim_grid_pos_y: 1728049
    }
    terrain_level_point {
      sim_grid_pos_x: 1487742
      sim_grid_pos_y: 1728155.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1487782
      sim_grid_pos_y: 1728273.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487807.75
      sim_grid_pos_y: 1728313.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487894.75
      sim_grid_pos_y: 1728376.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488036.38
      sim_grid_pos_y: 1728407.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488034.62
      sim_grid_pos_y: 1728400.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488160.75
      sim_grid_pos_y: 1728376.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488222.25
      sim_grid_pos_y: 1728299.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1488261.62
      sim_grid_pos_y: 1728350.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488304.75
      sim_grid_pos_y: 1728318.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488410.62
      sim_grid_pos_y: 1728520.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488434.88
      sim_grid_pos_y: 1728639.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488445.25
      sim_grid_pos_y: 1728649.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488501.38
      sim_grid_pos_y: 1728663.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488572.25
      sim_grid_pos_y: 1728639.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488655.88
      sim_grid_pos_y: 1728626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488748.38
      sim_grid_pos_y: 1728669.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488808.62
      sim_grid_pos_y: 1728753.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488650.62
      sim_grid_pos_y: 1729083.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488633.62
      sim_grid_pos_y: 1729174.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488578
      sim_grid_pos_y: 1729276.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488422.88
      sim_grid_pos_y: 1729295
    }
    terrain_level_point {
      sim_grid_pos_x: 1488336.5
      sim_grid_pos_y: 1729331.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488279
      sim_grid_pos_y: 1729393.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488258.88
      sim_grid_pos_y: 1729474.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488370.5
      sim_grid_pos_y: 1729611.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488539.25
      sim_grid_pos_y: 1729666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488533
      sim_grid_pos_y: 1729762.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1487042.75
      sim_grid_pos_y: 1730042
    }
    terrain_level_point {
      sim_grid_pos_x: 1487066.88
      sim_grid_pos_y: 1729673.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487086.5
      sim_grid_pos_y: 1729520.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1487069.38
      sim_grid_pos_y: 1729447.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1486883.62
      sim_grid_pos_y: 1729184.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1486806.75
      sim_grid_pos_y: 1729070.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1486636.75
      sim_grid_pos_y: 1728968.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1486382.88
      sim_grid_pos_y: 1728660.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1486602.75
      sim_grid_pos_y: 1727759.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1486963.12
      sim_grid_pos_y: 1727751.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487133.38
      sim_grid_pos_y: 1727918
    }
    terrain_level_point {
      sim_grid_pos_x: 1487358.88
      sim_grid_pos_y: 1727903
    }
    terrain_level_point {
      sim_grid_pos_x: 1487480.38
      sim_grid_pos_y: 1727865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1487638.12
      sim_grid_pos_y: 1727929.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1487714.88
      sim_grid_pos_y: 1728032.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487770.5
      sim_grid_pos_y: 1728143.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1487809.88
      sim_grid_pos_y: 1728260.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487830.38
      sim_grid_pos_y: 1728291.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1487907.62
      sim_grid_pos_y: 1728347.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488019.38
      sim_grid_pos_y: 1728372.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488143.75
      sim_grid_pos_y: 1728348.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1488222.75
      sim_grid_pos_y: 1728249.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488267.62
      sim_grid_pos_y: 1728308.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488315.38
      sim_grid_pos_y: 1728272.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488439.88
      sim_grid_pos_y: 1.72851e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1488462.75
      sim_grid_pos_y: 1728622.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.4885e+06
      sim_grid_pos_y: 1728631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1488564.88
      sim_grid_pos_y: 1728609.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1488660.38
      sim_grid_pos_y: 1728594.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488768.75
      sim_grid_pos_y: 1728645.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488844.25
      sim_grid_pos_y: 1728750.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488680.12
      sim_grid_pos_y: 1729093
    }
    terrain_level_point {
      sim_grid_pos_x: 1488663
      sim_grid_pos_y: 1729185.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488597.5
      sim_grid_pos_y: 1729305.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488430.88
      sim_grid_pos_y: 1729325.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488354.5
      sim_grid_pos_y: 1729357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1488307
      sim_grid_pos_y: 1729408.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1488292.5
      sim_grid_pos_y: 1729467.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1488388.62
      sim_grid_pos_y: 1729585
    }
    terrain_level_point {
      sim_grid_pos_x: 1488571.5
      sim_grid_pos_y: 1729645.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1488562.12
      sim_grid_pos_y: 1729787.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1487009.5
      sim_grid_pos_y: 1730079.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1487036.25
      sim_grid_pos_y: 1729670.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1487055.25
      sim_grid_pos_y: 1729522.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1487040.75
      sim_grid_pos_y: 1729459.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1486858.38
      sim_grid_pos_y: 1729201.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1486785
      sim_grid_pos_y: 1729093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1486616.5
      sim_grid_pos_y: 1728992.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1486349.25
      sim_grid_pos_y: 1728668.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1486579
      sim_grid_pos_y: 1727727
    }
  }
}
