terrain_level_data {
  terrain_level: 325
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2019028.12
      sim_grid_pos_y: 1224999.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2018761.38
      sim_grid_pos_y: 1225099.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2018611.38
      sim_grid_pos_y: 1225274.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2018454
      sim_grid_pos_y: 1225513.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2018263.25
      sim_grid_pos_y: 1225436.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2017918.38
      sim_grid_pos_y: 1225921.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2018249.12
      sim_grid_pos_y: 1226150.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2018389
      sim_grid_pos_y: 1225920.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2019116.25
      sim_grid_pos_y: 1225871
    }
    terrain_level_point {
      sim_grid_pos_x: 2019120.62
      sim_grid_pos_y: 1225334.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2019133
      sim_grid_pos_y: 1225059.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2019032.62
      sim_grid_pos_y: 1224943.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2018731.12
      sim_grid_pos_y: 1225055.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2018570.38
      sim_grid_pos_y: 1225243.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2018434.25
      sim_grid_pos_y: 1225450.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2018245
      sim_grid_pos_y: 1225373.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2017846.5
      sim_grid_pos_y: 1225934.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2018264.75
      sim_grid_pos_y: 1226223.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2018419
      sim_grid_pos_y: 1225969.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2019167.12
      sim_grid_pos_y: 1225919
    }
    terrain_level_point {
      sim_grid_pos_x: 2019171.88
      sim_grid_pos_y: 1225335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2019185.62
      sim_grid_pos_y: 1225030.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2019037.12
      sim_grid_pos_y: 1224887.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2018700.75
      sim_grid_pos_y: 1225012.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2018529.25
      sim_grid_pos_y: 1225212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2018414.5
      sim_grid_pos_y: 1225387.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2018226.62
      sim_grid_pos_y: 1225311.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2017774.62
      sim_grid_pos_y: 1225946.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2018280.25
      sim_grid_pos_y: 1226296.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2018449
      sim_grid_pos_y: 1226019
    }
    terrain_level_point {
      sim_grid_pos_x: 2019218
      sim_grid_pos_y: 1225966.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2019223.12
      sim_grid_pos_y: 1225336.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2019238.25
      sim_grid_pos_y: 1225001.25
    }
  }
}
terrain_level_data {
  terrain_level: 310
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2015578.88
      sim_grid_pos_y: 1228212.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2015415.5
      sim_grid_pos_y: 1228365.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2015409.62
      sim_grid_pos_y: 1228486.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2015322
      sim_grid_pos_y: 1228552.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015315.5
      sim_grid_pos_y: 1228684.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2015288.12
      sim_grid_pos_y: 1228800.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2015335.75
      sim_grid_pos_y: 1228924.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2015415.12
      sim_grid_pos_y: 1229129.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.01573e+06
      sim_grid_pos_y: 1228334.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2015576.38
      sim_grid_pos_y: 1228144.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015365.25
      sim_grid_pos_y: 1228342
    }
    terrain_level_point {
      sim_grid_pos_x: 2015359.62
      sim_grid_pos_y: 1228460.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2015272
      sim_grid_pos_y: 1228526.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015264.5
      sim_grid_pos_y: 1228677
    }
    terrain_level_point {
      sim_grid_pos_x: 2015234.62
      sim_grid_pos_y: 1228803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2015287.88
      sim_grid_pos_y: 1228942.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015379.88
      sim_grid_pos_y: 1229180.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015449.88
      sim_grid_pos_y: 1229181.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2015791.5
      sim_grid_pos_y: 1228318.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2015574
      sim_grid_pos_y: 1228076.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015315.12
      sim_grid_pos_y: 1228318.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015309.5
      sim_grid_pos_y: 1228433.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015222
      sim_grid_pos_y: 1228499.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015213.62
      sim_grid_pos_y: 1228669.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2015181.12
      sim_grid_pos_y: 1228807.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.01524e+06
      sim_grid_pos_y: 1228961.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015344.75
      sim_grid_pos_y: 1229232
    }
    terrain_level_point {
      sim_grid_pos_x: 2015484.62
      sim_grid_pos_y: 1229232.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2015853
      sim_grid_pos_y: 1228302.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2015571.5
      sim_grid_pos_y: 1228008.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015264.88
      sim_grid_pos_y: 1228295.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2015259.5
      sim_grid_pos_y: 1228407.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015172
      sim_grid_pos_y: 1228473.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2015162.62
      sim_grid_pos_y: 1228662.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2015127.5
      sim_grid_pos_y: 1228810.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2015192.25
      sim_grid_pos_y: 1228979.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2015309.5
      sim_grid_pos_y: 1229283.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2015519.5
      sim_grid_pos_y: 1229284
    }
    terrain_level_point {
      sim_grid_pos_x: 2015914.62
      sim_grid_pos_y: 1228286.25
    }
  }
}
terrain_level_data {
  terrain_level: 130
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2020002.5
      sim_grid_pos_y: 1222193.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2020150.75
      sim_grid_pos_y: 1222410.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2019174.5
      sim_grid_pos_y: 1224204.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2018071.62
      sim_grid_pos_y: 1225290.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2016924.12
      sim_grid_pos_y: 1227000.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2017148.5
      sim_grid_pos_y: 1227186.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2015946.12
      sim_grid_pos_y: 1227858.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2015185.62
      sim_grid_pos_y: 1228186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2013306.38
      sim_grid_pos_y: 1229878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2011647.75
      sim_grid_pos_y: 1228716.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2011261.75
      sim_grid_pos_y: 1228328.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2011517.12
      sim_grid_pos_y: 1227756.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2020270.75
      sim_grid_pos_y: 1222404.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2019257.25
      sim_grid_pos_y: 1224266.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2018150.88
      sim_grid_pos_y: 1225356.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2017060.88
      sim_grid_pos_y: 1226981
    }
    terrain_level_point {
      sim_grid_pos_x: 2017329.25
      sim_grid_pos_y: 1227203
    }
    terrain_level_point {
      sim_grid_pos_x: 2015991.5
      sim_grid_pos_y: 1227950.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2015241.75
      sim_grid_pos_y: 1228273.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2013314.38
      sim_grid_pos_y: 1230009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2011581.5
      sim_grid_pos_y: 1228795.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2011139.5
      sim_grid_pos_y: 1228350.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2011435.75
      sim_grid_pos_y: 1227687.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2020030.38
      sim_grid_pos_y: 1222053
    }
  }
}
