terrain_level_data {
  terrain_level: 3778
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2359863.25
      sim_grid_pos_y: 1602077
    }
    terrain_level_point {
      sim_grid_pos_x: 2.35988e+06
      sim_grid_pos_y: 1602717.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2359594.75
      sim_grid_pos_y: 1602852.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2359694.75
      sim_grid_pos_y: 1602216
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2359913.5
      sim_grid_pos_y: 1602043.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2359932.25
      sim_grid_pos_y: 1.60275e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2359588.5
      sim_grid_pos_y: 1602912.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2359539.25
      sim_grid_pos_y: 1602875.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2359647
      sim_grid_pos_y: 1602188.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2359855.25
      sim_grid_pos_y: 1602017
    }
  }
}
