terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1.91412e+06
      sim_grid_pos_y: 1706667.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914614.75
      sim_grid_pos_y: 1707061
    }
    terrain_level_point {
      sim_grid_pos_x: 1914944.88
      sim_grid_pos_y: 1707381.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1915500.88
      sim_grid_pos_y: 1707706.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915755.5
      sim_grid_pos_y: 1707997.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915907.12
      sim_grid_pos_y: 1708360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1916190.75
      sim_grid_pos_y: 1708412.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1916825.88
      sim_grid_pos_y: 1708638.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916879.12
      sim_grid_pos_y: 1708224.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1916706.25
      sim_grid_pos_y: 1707906.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915938
      sim_grid_pos_y: 1706950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915473
      sim_grid_pos_y: 1706077.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1914494.62
      sim_grid_pos_y: 1.70621e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1914041.12
      sim_grid_pos_y: 1706179.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1915490.12
      sim_grid_pos_y: 1706044.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1914493.5
      sim_grid_pos_y: 1706179.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914004.62
      sim_grid_pos_y: 1706146.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914091.5
      sim_grid_pos_y: 1706684.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914594.5
      sim_grid_pos_y: 1707084.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914926.12
      sim_grid_pos_y: 1707406.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915481
      sim_grid_pos_y: 1707730.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915729
      sim_grid_pos_y: 1708014.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1915885.12
      sim_grid_pos_y: 1708388.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1916182.88
      sim_grid_pos_y: 1708442
    }
    terrain_level_point {
      sim_grid_pos_x: 1916851.5
      sim_grid_pos_y: 1708680.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1916910.88
      sim_grid_pos_y: 1708218.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1916732
      sim_grid_pos_y: 1707889.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915963.75
      sim_grid_pos_y: 1706933.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1915507.12
      sim_grid_pos_y: 1706011.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1914492.5
      sim_grid_pos_y: 1706148.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1913968.12
      sim_grid_pos_y: 1706113.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1914063.12
      sim_grid_pos_y: 1706700.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1914574.12
      sim_grid_pos_y: 1707107.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1914907.38
      sim_grid_pos_y: 1707430.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915461.12
      sim_grid_pos_y: 1707754.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915702.5
      sim_grid_pos_y: 1708030.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915863.25
      sim_grid_pos_y: 1708415.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916174.88
      sim_grid_pos_y: 1708471.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1916877.25
      sim_grid_pos_y: 1708722.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1916942.62
      sim_grid_pos_y: 1708212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916757.62
      sim_grid_pos_y: 1707872.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915989.5
      sim_grid_pos_y: 1706916.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1915524.25
      sim_grid_pos_y: 1705977.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1914491.5
      sim_grid_pos_y: 1706117.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1913931.5
      sim_grid_pos_y: 1.70608e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1914034.62
      sim_grid_pos_y: 1706717.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914553.75
      sim_grid_pos_y: 1707130.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1914888.62
      sim_grid_pos_y: 1707455.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1915441.25
      sim_grid_pos_y: 1707778.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915676.12
      sim_grid_pos_y: 1708047.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915841.25
      sim_grid_pos_y: 1708442.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1916166.88
      sim_grid_pos_y: 1708501.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1916902.88
      sim_grid_pos_y: 1708763.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1916974.5
      sim_grid_pos_y: 1708206.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916783.38
      sim_grid_pos_y: 1707855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916015.38
      sim_grid_pos_y: 1706899.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1915541.38
      sim_grid_pos_y: 1705944.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914490.38
      sim_grid_pos_y: 1706086.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1913895
      sim_grid_pos_y: 1706046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1914006.12
      sim_grid_pos_y: 1706734.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1914533.5
      sim_grid_pos_y: 1707153.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1914869.88
      sim_grid_pos_y: 1707480.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915421.38
      sim_grid_pos_y: 1707802.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915649.62
      sim_grid_pos_y: 1708063.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915819.38
      sim_grid_pos_y: 1.70847e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1916159
      sim_grid_pos_y: 1708531.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1916928.5
      sim_grid_pos_y: 1708805.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1917006.25
      sim_grid_pos_y: 1708200.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1916809
      sim_grid_pos_y: 1707838.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1916041.12
      sim_grid_pos_y: 1706882.25
    }
  }
}
