terrain_level_data {
  terrain_level: 430
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 749250.188
      sim_grid_pos_y: 1610948
    }
    terrain_level_point {
      sim_grid_pos_x: 749239
      sim_grid_pos_y: 1610841.12
    }
    terrain_level_point {
      sim_grid_pos_x: 748891.062
      sim_grid_pos_y: 1610842.5
    }
    terrain_level_point {
      sim_grid_pos_x: 748887
      sim_grid_pos_y: 1610941.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 749257.438
      sim_grid_pos_y: 1610820.5
    }
    terrain_level_point {
      sim_grid_pos_x: 748871.375
      sim_grid_pos_y: 1610822.12
    }
    terrain_level_point {
      sim_grid_pos_x: 748865.625
      sim_grid_pos_y: 1610962
    }
    terrain_level_point {
      sim_grid_pos_x: 749273
      sim_grid_pos_y: 1610968.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 749275.938
      sim_grid_pos_y: 1.6108e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 748851.688
      sim_grid_pos_y: 1610801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 748844.312
      sim_grid_pos_y: 1610982.12
    }
    terrain_level_point {
      sim_grid_pos_x: 749295.812
      sim_grid_pos_y: 1610989.75
    }
  }
}
