terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 51266.0703
      sim_grid_pos_y: 2791359.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50383.6367
      sim_grid_pos_y: 2791350.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50374.5156
      sim_grid_pos_y: 2791227.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49771.4531
      sim_grid_pos_y: 2791273
    }
    terrain_level_point {
      sim_grid_pos_x: 49800.0586
      sim_grid_pos_y: 2790634.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49280.5625
      sim_grid_pos_y: 2790652.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49213.7
      sim_grid_pos_y: 2790630.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49218.9336
      sim_grid_pos_y: 2789817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49225.3789
      sim_grid_pos_y: 2789766
    }
    terrain_level_point {
      sim_grid_pos_x: 49266.8867
      sim_grid_pos_y: 2789654.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49999.8
      sim_grid_pos_y: 2789652.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50002.3828
      sim_grid_pos_y: 2789724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50559.9492
      sim_grid_pos_y: 2789726.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50992.2188
      sim_grid_pos_y: 2789977.75
    }
    terrain_level_point {
      sim_grid_pos_x: 51240.7461
      sim_grid_pos_y: 2790178.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 50032.0703
      sim_grid_pos_y: 2789693.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50568.2891
      sim_grid_pos_y: 2789695.75
    }
    terrain_level_point {
      sim_grid_pos_x: 51009.7188
      sim_grid_pos_y: 2789952.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51271.1875
      sim_grid_pos_y: 2790163.75
    }
    terrain_level_point {
      sim_grid_pos_x: 51297.5
      sim_grid_pos_y: 2791390.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50355.0703
      sim_grid_pos_y: 2791380.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50346.1289
      sim_grid_pos_y: 2791260.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49739.168
      sim_grid_pos_y: 2791306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49767.8398
      sim_grid_pos_y: 2790666.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49276.1289
      sim_grid_pos_y: 2790683.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49182.8
      sim_grid_pos_y: 2790652.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49188.1875
      sim_grid_pos_y: 2789815.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49195.3086
      sim_grid_pos_y: 2789758.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49245.4883
      sim_grid_pos_y: 2789623.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50029.4688
      sim_grid_pos_y: 2789621.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 50061.7383
      sim_grid_pos_y: 2789663
    }
    terrain_level_point {
      sim_grid_pos_x: 50576.6406
      sim_grid_pos_y: 2789665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51027.2188
      sim_grid_pos_y: 2789927
    }
    terrain_level_point {
      sim_grid_pos_x: 51301.6406
      sim_grid_pos_y: 2790149
    }
    terrain_level_point {
      sim_grid_pos_x: 51328.9297
      sim_grid_pos_y: 2791421.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50326.4883
      sim_grid_pos_y: 2791411
    }
    terrain_level_point {
      sim_grid_pos_x: 50317.7383
      sim_grid_pos_y: 2791293.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49706.8906
      sim_grid_pos_y: 2791339.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49735.6289
      sim_grid_pos_y: 2790698.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49271.7109
      sim_grid_pos_y: 2790714.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49151.9
      sim_grid_pos_y: 2790675
    }
    terrain_level_point {
      sim_grid_pos_x: 49157.4492
      sim_grid_pos_y: 2789813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49165.2383
      sim_grid_pos_y: 2789751.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49224.0781
      sim_grid_pos_y: 2789593
    }
    terrain_level_point {
      sim_grid_pos_x: 50059.1406
      sim_grid_pos_y: 2789590.5
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 49701.1328
      sim_grid_pos_y: 2791341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49327.6484
      sim_grid_pos_y: 2791352.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49032.5664
      sim_grid_pos_y: 2.79136e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 48936.4766
      sim_grid_pos_y: 2791764
    }
    terrain_level_point {
      sim_grid_pos_x: 48711.7812
      sim_grid_pos_y: 2791640.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48733.4375
      sim_grid_pos_y: 2791545.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48622.8086
      sim_grid_pos_y: 2791508.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48563.1094
      sim_grid_pos_y: 2791285
    }
    terrain_level_point {
      sim_grid_pos_x: 48242.6758
      sim_grid_pos_y: 2790792.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48497.9805
      sim_grid_pos_y: 2790476.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48279.1953
      sim_grid_pos_y: 2790417.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48092.7148
      sim_grid_pos_y: 2790144.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48286.3398
      sim_grid_pos_y: 2789601.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47888.9336
      sim_grid_pos_y: 2789499.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47898.4102
      sim_grid_pos_y: 2789176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47923.8438
      sim_grid_pos_y: 2789148.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47923.2461
      sim_grid_pos_y: 2788914.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49031.7188
      sim_grid_pos_y: 2789299.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50423.6719
      sim_grid_pos_y: 2789273.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51513.0078
      sim_grid_pos_y: 2790133.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51333.4
      sim_grid_pos_y: 2790163.75
    }
    terrain_level_point {
      sim_grid_pos_x: 51187.5352
      sim_grid_pos_y: 2.79007e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 51013.6367
      sim_grid_pos_y: 2789888.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50620.9883
      sim_grid_pos_y: 2789652
    }
    terrain_level_point {
      sim_grid_pos_x: 50067.9727
      sim_grid_pos_y: 2789642.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50047.0664
      sim_grid_pos_y: 2789602
    }
    terrain_level_point {
      sim_grid_pos_x: 49630.1602
      sim_grid_pos_y: 2789598.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49625.0156
      sim_grid_pos_y: 2789689.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49370.1094
      sim_grid_pos_y: 2789687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49340.7266
      sim_grid_pos_y: 2.7896e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 49158.0391
      sim_grid_pos_y: 2789605
    }
    terrain_level_point {
      sim_grid_pos_x: 49123.3047
      sim_grid_pos_y: 2790649.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49234.3828
      sim_grid_pos_y: 2790742.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49703.2695
      sim_grid_pos_y: 2790728.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 49036.6484
      sim_grid_pos_y: 2789268.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50434.0898
      sim_grid_pos_y: 2789242.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51547.7578
      sim_grid_pos_y: 2790121.5
    }
    terrain_level_point {
      sim_grid_pos_x: 51537.8711
      sim_grid_pos_y: 2790160.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51326.8
      sim_grid_pos_y: 2790196.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51167.8398
      sim_grid_pos_y: 2790094
    }
    terrain_level_point {
      sim_grid_pos_x: 50994.2383
      sim_grid_pos_y: 2789912.5
    }
    terrain_level_point {
      sim_grid_pos_x: 50612.2
      sim_grid_pos_y: 2789682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50049.0703
      sim_grid_pos_y: 2789672.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50028.2578
      sim_grid_pos_y: 2789632.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49659.2188
      sim_grid_pos_y: 2789629.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49654.0781
      sim_grid_pos_y: 2789720.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49347.9492
      sim_grid_pos_y: 2789718
    }
    terrain_level_point {
      sim_grid_pos_x: 49318.8398
      sim_grid_pos_y: 2789631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49187.8203
      sim_grid_pos_y: 2789635
    }
    terrain_level_point {
      sim_grid_pos_x: 49154.5508
      sim_grid_pos_y: 2790635.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49245.1875
      sim_grid_pos_y: 2790711.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49734.1406
      sim_grid_pos_y: 2790697.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49731.7812
      sim_grid_pos_y: 2791371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49328.5
      sim_grid_pos_y: 2791383.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49057.0195
      sim_grid_pos_y: 2791390.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48957.0508
      sim_grid_pos_y: 2791810.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48676.6289
      sim_grid_pos_y: 2791656
    }
    terrain_level_point {
      sim_grid_pos_x: 48697.2383
      sim_grid_pos_y: 2791566
    }
    terrain_level_point {
      sim_grid_pos_x: 48597.3594
      sim_grid_pos_y: 2791532.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48534.6602
      sim_grid_pos_y: 2791297.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48204.7109
      sim_grid_pos_y: 2790790.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48444.3789
      sim_grid_pos_y: 2790494.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48260.2
      sim_grid_pos_y: 2790444.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48058.4883
      sim_grid_pos_y: 2790149.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48246.0586
      sim_grid_pos_y: 2789623
    }
    terrain_level_point {
      sim_grid_pos_x: 47857.4609
      sim_grid_pos_y: 2789523.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47868
      sim_grid_pos_y: 2789164.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47893.0586
      sim_grid_pos_y: 2789136.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47892.3789
      sim_grid_pos_y: 2788871.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 49041.5391
      sim_grid_pos_y: 2789237.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50444.5195
      sim_grid_pos_y: 2789211.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51582.5
      sim_grid_pos_y: 2790109.75
    }
    terrain_level_point {
      sim_grid_pos_x: 51562.7305
      sim_grid_pos_y: 2790187.25
    }
    terrain_level_point {
      sim_grid_pos_x: 51320.1875
      sim_grid_pos_y: 2790228.5
    }
    terrain_level_point {
      sim_grid_pos_x: 51148.1406
      sim_grid_pos_y: 2790117.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50974.8789
      sim_grid_pos_y: 2789936.75
    }
    terrain_level_point {
      sim_grid_pos_x: 50603.418
      sim_grid_pos_y: 2789713.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50030.1797
      sim_grid_pos_y: 2789703.25
    }
    terrain_level_point {
      sim_grid_pos_x: 50009.4609
      sim_grid_pos_y: 2789663.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49688.2695
      sim_grid_pos_y: 2789660.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49683.1289
      sim_grid_pos_y: 2789751.25
    }
    terrain_level_point {
      sim_grid_pos_x: 49325.7812
      sim_grid_pos_y: 2789748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49296.9297
      sim_grid_pos_y: 2789662.75
    }
    terrain_level_point {
      sim_grid_pos_x: 49217.5977
      sim_grid_pos_y: 2789665
    }
    terrain_level_point {
      sim_grid_pos_x: 49185.7891
      sim_grid_pos_y: 2790621.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49256
      sim_grid_pos_y: 2790680.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49765.0078
      sim_grid_pos_y: 2790665.5
    }
    terrain_level_point {
      sim_grid_pos_x: 49762.4375
      sim_grid_pos_y: 2791401
    }
    terrain_level_point {
      sim_grid_pos_x: 49329.3477
      sim_grid_pos_y: 2791414
    }
    terrain_level_point {
      sim_grid_pos_x: 49081.4688
      sim_grid_pos_y: 2791420.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48977.6211
      sim_grid_pos_y: 2791857
    }
    terrain_level_point {
      sim_grid_pos_x: 48641.4688
      sim_grid_pos_y: 2791671.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48661.0312
      sim_grid_pos_y: 2791586.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48571.918
      sim_grid_pos_y: 2791556.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48506.2
      sim_grid_pos_y: 2791310.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48166.7383
      sim_grid_pos_y: 2790788.25
    }
    terrain_level_point {
      sim_grid_pos_x: 48390.7891
      sim_grid_pos_y: 2790511.5
    }
    terrain_level_point {
      sim_grid_pos_x: 48241.2109
      sim_grid_pos_y: 2790471
    }
    terrain_level_point {
      sim_grid_pos_x: 48024.25
      sim_grid_pos_y: 2790153.75
    }
    terrain_level_point {
      sim_grid_pos_x: 48205.7695
      sim_grid_pos_y: 2789644.5
    }
    terrain_level_point {
      sim_grid_pos_x: 47826
      sim_grid_pos_y: 2789547
    }
    terrain_level_point {
      sim_grid_pos_x: 47837.5781
      sim_grid_pos_y: 2789152.25
    }
    terrain_level_point {
      sim_grid_pos_x: 47862.2695
      sim_grid_pos_y: 2789124.75
    }
    terrain_level_point {
      sim_grid_pos_x: 47861.5195
      sim_grid_pos_y: 2788828
    }
  }
}
