terrain_level_data {
  terrain_level: 3960
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1857446.62
      sim_grid_pos_y: 1715947.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1857456.5
      sim_grid_pos_y: 1716517.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1857827.25
      sim_grid_pos_y: 1716622.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1858220.25
      sim_grid_pos_y: 1716447
    }
    terrain_level_point {
      sim_grid_pos_x: 1858261.75
      sim_grid_pos_y: 1716164.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857938.75
      sim_grid_pos_y: 1715700.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1857972.12
      sim_grid_pos_y: 1715568.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1857343
      sim_grid_pos_y: 1715884.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857355.25
      sim_grid_pos_y: 1716595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857835.12
      sim_grid_pos_y: 1716731.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1858313.5
      sim_grid_pos_y: 1716517.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1858369.12
      sim_grid_pos_y: 1716139.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1858005.5
      sim_grid_pos_y: 1715437.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1857239.38
      sim_grid_pos_y: 1715822.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1857254
      sim_grid_pos_y: 1716673.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857843
      sim_grid_pos_y: 1716840.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1858406.75
      sim_grid_pos_y: 1716588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1858476.38
      sim_grid_pos_y: 1716114.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1858039
      sim_grid_pos_y: 1715305.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1857135.75
      sim_grid_pos_y: 1715759.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1857152.88
      sim_grid_pos_y: 1716751.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1857850.88
      sim_grid_pos_y: 1716949.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.8585e+06
      sim_grid_pos_y: 1716658.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1858583.75
      sim_grid_pos_y: 1716089
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1858072.38
      sim_grid_pos_y: 1715174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1857032.12
      sim_grid_pos_y: 1715696.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1857051.62
      sim_grid_pos_y: 1716829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1857858.75
      sim_grid_pos_y: 1717057.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1858593.25
      sim_grid_pos_y: 1716729.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1858691.12
      sim_grid_pos_y: 1716063.75
    }
  }
}
terrain_level_data {
  terrain_level: 4075
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1859060.25
      sim_grid_pos_y: 1713647.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859060.25
      sim_grid_pos_y: 1714032.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859254.38
      sim_grid_pos_y: 1714071.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859370.12
      sim_grid_pos_y: 1713904.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1859372
      sim_grid_pos_y: 1713607.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1859298.25
      sim_grid_pos_y: 1713478.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1859108.38
      sim_grid_pos_y: 1713491.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1859355.38
      sim_grid_pos_y: 1713371.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1859031.12
      sim_grid_pos_y: 1713394.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1858957.75
      sim_grid_pos_y: 1713631.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1858957.75
      sim_grid_pos_y: 1714116.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859300.38
      sim_grid_pos_y: 1714185.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1859472.5
      sim_grid_pos_y: 1713936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1859474.75
      sim_grid_pos_y: 1713580.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1859412.5
      sim_grid_pos_y: 1713264.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1858953.88
      sim_grid_pos_y: 1713297.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1858855.25
      sim_grid_pos_y: 1713616.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1858855.25
      sim_grid_pos_y: 1714200.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859346.25
      sim_grid_pos_y: 1714299
    }
    terrain_level_point {
      sim_grid_pos_x: 1859574.88
      sim_grid_pos_y: 1713968.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1859577.38
      sim_grid_pos_y: 1713554
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1859469.62
      sim_grid_pos_y: 1713157.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1858876.62
      sim_grid_pos_y: 1713200.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1858752.62
      sim_grid_pos_y: 1713600.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1858752.62
      sim_grid_pos_y: 1714284.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859392.25
      sim_grid_pos_y: 1714412.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1859677.12
      sim_grid_pos_y: 1714001.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1859680.12
      sim_grid_pos_y: 1713527.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1859526.75
      sim_grid_pos_y: 1713050.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1858799.38
      sim_grid_pos_y: 1713102.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1858650.12
      sim_grid_pos_y: 1713585.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1858650.12
      sim_grid_pos_y: 1714368.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859438.12
      sim_grid_pos_y: 1714526.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1859779.5
      sim_grid_pos_y: 1714033.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1859782.88
      sim_grid_pos_y: 1713500.38
    }
  }
}
