terrain_level_data {
  terrain_level: 4
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1018508.38
      sim_grid_pos_y: 1336157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1018636
      sim_grid_pos_y: 1336047.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1019022.5
      sim_grid_pos_y: 1336434.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1019010.31
      sim_grid_pos_y: 1336540.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1018893.62
      sim_grid_pos_y: 1336538.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1019033.25
      sim_grid_pos_y: 1336430.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1019019.44
      sim_grid_pos_y: 1336551
    }
    terrain_level_point {
      sim_grid_pos_x: 1018889.38
      sim_grid_pos_y: 1336548.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1018493.25
      sim_grid_pos_y: 1336156.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1018636.5
      sim_grid_pos_y: 1336034
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1019044
      sim_grid_pos_y: 1336426.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1019028.56
      sim_grid_pos_y: 1336561.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1018885.06
      sim_grid_pos_y: 1336558.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1018478.12
      sim_grid_pos_y: 1336156
    }
    terrain_level_point {
      sim_grid_pos_x: 1018637.06
      sim_grid_pos_y: 1.33602e+06
    }
  }
}
terrain_level_data {
  terrain_level: 4
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1019432.5
      sim_grid_pos_y: 1337106.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1019551
      sim_grid_pos_y: 1336992.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1019266.56
      sim_grid_pos_y: 1336702
    }
    terrain_level_point {
      sim_grid_pos_x: 1019156
      sim_grid_pos_y: 1336698.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1019163.88
      sim_grid_pos_y: 1336831.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1019145.06
      sim_grid_pos_y: 1336688.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1019153.88
      sim_grid_pos_y: 1336835.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1019432.25
      sim_grid_pos_y: 1337120.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1019565.56
      sim_grid_pos_y: 1336993.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1019271
      sim_grid_pos_y: 1336691.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1019134.19
      sim_grid_pos_y: 1336677.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1019143.88
      sim_grid_pos_y: 1336840.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1019432
      sim_grid_pos_y: 1337135.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1019580.12
      sim_grid_pos_y: 1336993.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1019275.44
      sim_grid_pos_y: 1336681.75
    }
  }
}
