terrain_level_data {
  terrain_level: 920
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1651544.25
      sim_grid_pos_y: 1764293.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1651619.38
      sim_grid_pos_y: 1764677.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1651860.62
      sim_grid_pos_y: 1764988.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1652163.25
      sim_grid_pos_y: 1765214.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1652436
      sim_grid_pos_y: 1765288.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1652604.25
      sim_grid_pos_y: 1765022
    }
    terrain_level_point {
      sim_grid_pos_x: 1652681.25
      sim_grid_pos_y: 1764721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652668.88
      sim_grid_pos_y: 1764427.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1652971.25
      sim_grid_pos_y: 1764166.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653143.5
      sim_grid_pos_y: 1764796.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653404.88
      sim_grid_pos_y: 1764757.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1653431.38
      sim_grid_pos_y: 1764394.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653515
      sim_grid_pos_y: 1764289.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1653428.25
      sim_grid_pos_y: 1764107.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654206
      sim_grid_pos_y: 1.76359e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1654174.25
      sim_grid_pos_y: 1763919.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654227.12
      sim_grid_pos_y: 1764246.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1654382
      sim_grid_pos_y: 1764333.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1654497.88
      sim_grid_pos_y: 1764003.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1654774.5
      sim_grid_pos_y: 1763911.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1654886.88
      sim_grid_pos_y: 1763531
    }
    terrain_level_point {
      sim_grid_pos_x: 1655037.62
      sim_grid_pos_y: 1763692.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1655130.25
      sim_grid_pos_y: 1.76385e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1655240.62
      sim_grid_pos_y: 1763744.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1655016.88
      sim_grid_pos_y: 1763130.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1655342.38
      sim_grid_pos_y: 1762968.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1655517.5
      sim_grid_pos_y: 1762999
    }
    terrain_level_point {
      sim_grid_pos_x: 1655590.5
      sim_grid_pos_y: 1763186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1655877.5
      sim_grid_pos_y: 1763244.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1655976.38
      sim_grid_pos_y: 1763125.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1655965.88
      sim_grid_pos_y: 1762918.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1655902.75
      sim_grid_pos_y: 1762711
    }
    terrain_level_point {
      sim_grid_pos_x: 1656006.38
      sim_grid_pos_y: 1762609.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1656354.62
      sim_grid_pos_y: 1762619
    }
    terrain_level_point {
      sim_grid_pos_x: 1656385.38
      sim_grid_pos_y: 1762561.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1656295.75
      sim_grid_pos_y: 1762384.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1656224.88
      sim_grid_pos_y: 1762274.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1656419.75
      sim_grid_pos_y: 1762330.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656535.5
      sim_grid_pos_y: 1762312.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1656574.5
      sim_grid_pos_y: 1762214.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1656615.88
      sim_grid_pos_y: 1762168.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1656690.88
      sim_grid_pos_y: 1762170.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1656772.38
      sim_grid_pos_y: 1762078.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656812
      sim_grid_pos_y: 1761976
    }
    terrain_level_point {
      sim_grid_pos_x: 1656980.25
      sim_grid_pos_y: 1761896.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1657095.62
      sim_grid_pos_y: 1761740.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1657143.12
      sim_grid_pos_y: 1761918.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1657325
      sim_grid_pos_y: 1762088.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1657435.5
      sim_grid_pos_y: 1762076.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1657516.38
      sim_grid_pos_y: 1761893.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1657475.38
      sim_grid_pos_y: 1759755.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1655497.88
      sim_grid_pos_y: 1759654.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1655352.62
      sim_grid_pos_y: 1759516.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1655226
      sim_grid_pos_y: 1759496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.65502e+06
      sim_grid_pos_y: 1759567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654891.75
      sim_grid_pos_y: 1759775.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1654980.38
      sim_grid_pos_y: 1759811.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654649.75
      sim_grid_pos_y: 1759856.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1654411.88
      sim_grid_pos_y: 1759989.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654288.88
      sim_grid_pos_y: 1759998.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1654255.12
      sim_grid_pos_y: 1760108
    }
    terrain_level_point {
      sim_grid_pos_x: 1654060.12
      sim_grid_pos_y: 1760177.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1653784.12
      sim_grid_pos_y: 1760867.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1653603.62
      sim_grid_pos_y: 1761121
    }
    terrain_level_point {
      sim_grid_pos_x: 1653534.75
      sim_grid_pos_y: 1761234.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1653404.62
      sim_grid_pos_y: 1761260.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653349.25
      sim_grid_pos_y: 1761533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653179.75
      sim_grid_pos_y: 1761571.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1653180.25
      sim_grid_pos_y: 1761720.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653071.25
      sim_grid_pos_y: 1761691.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1652963.75
      sim_grid_pos_y: 1761653
    }
    terrain_level_point {
      sim_grid_pos_x: 1652886
      sim_grid_pos_y: 1761582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652795.88
      sim_grid_pos_y: 1761537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1652651.12
      sim_grid_pos_y: 1761600.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652448
      sim_grid_pos_y: 1762056.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1652251.12
      sim_grid_pos_y: 1762284.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1652079.12
      sim_grid_pos_y: 1762390.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1655221.25
      sim_grid_pos_y: 1759443.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1654986
      sim_grid_pos_y: 1759525
    }
    terrain_level_point {
      sim_grid_pos_x: 1654828.88
      sim_grid_pos_y: 1759780.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1654633.25
      sim_grid_pos_y: 1759807.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654396.75
      sim_grid_pos_y: 1759939
    }
    terrain_level_point {
      sim_grid_pos_x: 1654250.25
      sim_grid_pos_y: 1759950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654213.75
      sim_grid_pos_y: 1760068.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654021.12
      sim_grid_pos_y: 1760136.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653738.88
      sim_grid_pos_y: 1760842.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653560.75
      sim_grid_pos_y: 1761092.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653502.62
      sim_grid_pos_y: 1761188.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1653361.12
      sim_grid_pos_y: 1761217.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1653305.62
      sim_grid_pos_y: 1761491
    }
    terrain_level_point {
      sim_grid_pos_x: 1653128.38
      sim_grid_pos_y: 1761530.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1653128.75
      sim_grid_pos_y: 1761653.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653086.5
      sim_grid_pos_y: 1761642.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1652990.75
      sim_grid_pos_y: 1761608.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652915.25
      sim_grid_pos_y: 1761539.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1652797.38
      sim_grid_pos_y: 1761481.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652612.5
      sim_grid_pos_y: 1761561
    }
    terrain_level_point {
      sim_grid_pos_x: 1652404.25
      sim_grid_pos_y: 1762028.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1652217.5
      sim_grid_pos_y: 1762245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1652035.12
      sim_grid_pos_y: 1762357.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1651491.62
      sim_grid_pos_y: 1764291
    }
    terrain_level_point {
      sim_grid_pos_x: 1651571.5
      sim_grid_pos_y: 1764699.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1651824.38
      sim_grid_pos_y: 1765025.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1652140.38
      sim_grid_pos_y: 1765261
    }
    terrain_level_point {
      sim_grid_pos_x: 1652459.12
      sim_grid_pos_y: 1765347.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1652652
      sim_grid_pos_y: 1765042.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1652732.88
      sim_grid_pos_y: 1764726.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1652721.25
      sim_grid_pos_y: 1764450.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652943.25
      sim_grid_pos_y: 1764258.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653106.12
      sim_grid_pos_y: 1764854.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1653453
      sim_grid_pos_y: 1764801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653481.38
      sim_grid_pos_y: 1764414.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1653575.12
      sim_grid_pos_y: 1764295.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653493.75
      sim_grid_pos_y: 1764125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654144.62
      sim_grid_pos_y: 1763692.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1654122.62
      sim_grid_pos_y: 1763921
    }
    terrain_level_point {
      sim_grid_pos_x: 1654180.38
      sim_grid_pos_y: 1764279.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654410.25
      sim_grid_pos_y: 1764407.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1654538
      sim_grid_pos_y: 1764044.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654816.12
      sim_grid_pos_y: 1763951.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1654910.62
      sim_grid_pos_y: 1763631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654996.25
      sim_grid_pos_y: 1763723
    }
    terrain_level_point {
      sim_grid_pos_x: 1655118.75
      sim_grid_pos_y: 1763931.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1655300.38
      sim_grid_pos_y: 1763758.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1655080.75
      sim_grid_pos_y: 1763155.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1655350.12
      sim_grid_pos_y: 1763022
    }
    terrain_level_point {
      sim_grid_pos_x: 1655480.25
      sim_grid_pos_y: 1763044.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1655552.88
      sim_grid_pos_y: 1763230.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1655897.5
      sim_grid_pos_y: 1763300.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656028.5
      sim_grid_pos_y: 1763142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1656016.75
      sim_grid_pos_y: 1762909.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1655960.75
      sim_grid_pos_y: 1762725.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656026.75
      sim_grid_pos_y: 1762661
    }
    terrain_level_point {
      sim_grid_pos_x: 1656385
      sim_grid_pos_y: 1762671.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1656443.12
      sim_grid_pos_y: 1762561.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656341.5
      sim_grid_pos_y: 1762361.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1656416.5
      sim_grid_pos_y: 1762383.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1656572.25
      sim_grid_pos_y: 1762358.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1656618.75
      sim_grid_pos_y: 1762242
    }
    terrain_level_point {
      sim_grid_pos_x: 1656638.25
      sim_grid_pos_y: 1762220.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1656713.38
      sim_grid_pos_y: 1762222
    }
    terrain_level_point {
      sim_grid_pos_x: 1656816.88
      sim_grid_pos_y: 1762106
    }
    terrain_level_point {
      sim_grid_pos_x: 1656852.38
      sim_grid_pos_y: 1762013.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1657013.88
      sim_grid_pos_y: 1761937.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1657073.62
      sim_grid_pos_y: 1761856.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1657097.5
      sim_grid_pos_y: 1761945.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1657307.12
      sim_grid_pos_y: 1762142
    }
    terrain_level_point {
      sim_grid_pos_x: 1657470.38
      sim_grid_pos_y: 1762124.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1657567.88
      sim_grid_pos_y: 1761903.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1657525.62
      sim_grid_pos_y: 1759707.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1655519.38
      sim_grid_pos_y: 1759604.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1655376.38
      sim_grid_pos_y: 1759468.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1655216.62
      sim_grid_pos_y: 1759391.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654951.88
      sim_grid_pos_y: 1759482.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654797.88
      sim_grid_pos_y: 1759732.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1654616.75
      sim_grid_pos_y: 1759757.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1654381.62
      sim_grid_pos_y: 1759888.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1654211.62
      sim_grid_pos_y: 1759901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1654172.38
      sim_grid_pos_y: 1760028.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653982.12
      sim_grid_pos_y: 1760096.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1653693.5
      sim_grid_pos_y: 1760818
    }
    terrain_level_point {
      sim_grid_pos_x: 1653517.88
      sim_grid_pos_y: 1761064.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1653470.38
      sim_grid_pos_y: 1761142.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653317.62
      sim_grid_pos_y: 1761173.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653262
      sim_grid_pos_y: 1761448.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1653076.88
      sim_grid_pos_y: 1761489
    }
    terrain_level_point {
      sim_grid_pos_x: 1653077.25
      sim_grid_pos_y: 1761584.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1653017.62
      sim_grid_pos_y: 1761563.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1652944.38
      sim_grid_pos_y: 1761496.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1652798.75
      sim_grid_pos_y: 1761424.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1652573.88
      sim_grid_pos_y: 1761521.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1652360.5
      sim_grid_pos_y: 1762000.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1652183.88
      sim_grid_pos_y: 1762206
    }
    terrain_level_point {
      sim_grid_pos_x: 1651991.25
      sim_grid_pos_y: 1762324.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1651439
      sim_grid_pos_y: 1764288.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1651523.5
      sim_grid_pos_y: 1764721
    }
    terrain_level_point {
      sim_grid_pos_x: 1651788.12
      sim_grid_pos_y: 1765062
    }
    terrain_level_point {
      sim_grid_pos_x: 1652117.5
      sim_grid_pos_y: 1765308
    }
    terrain_level_point {
      sim_grid_pos_x: 1652482.25
      sim_grid_pos_y: 1765407.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1652699.62
      sim_grid_pos_y: 1765063.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1652784.38
      sim_grid_pos_y: 1764732.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1652773.5
      sim_grid_pos_y: 1764472.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1652915.25
      sim_grid_pos_y: 1764350.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653068.75
      sim_grid_pos_y: 1764911.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653501.12
      sim_grid_pos_y: 1764846.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1653531.38
      sim_grid_pos_y: 1764433.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1653635.12
      sim_grid_pos_y: 1764302.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1653559.12
      sim_grid_pos_y: 1764143.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1654083.25
      sim_grid_pos_y: 1763794.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1654071
      sim_grid_pos_y: 1763922.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1654133.75
      sim_grid_pos_y: 1764312.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1654438.38
      sim_grid_pos_y: 1764482.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1654578
      sim_grid_pos_y: 1764085
    }
    terrain_level_point {
      sim_grid_pos_x: 1654857.75
      sim_grid_pos_y: 1763991.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1654934.38
      sim_grid_pos_y: 1763732
    }
    terrain_level_point {
      sim_grid_pos_x: 1654955
      sim_grid_pos_y: 1763753.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1655107.25
      sim_grid_pos_y: 1764013.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.65536e+06
      sim_grid_pos_y: 1763772.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1655144.62
      sim_grid_pos_y: 1763181.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1655357.88
      sim_grid_pos_y: 1763075.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1655443
      sim_grid_pos_y: 1763090.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1655515.25
      sim_grid_pos_y: 1763275.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1655917.38
      sim_grid_pos_y: 1763357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1656080.75
      sim_grid_pos_y: 1.76316e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1656067.62
      sim_grid_pos_y: 1762900.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656018.88
      sim_grid_pos_y: 1762740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1656047.12
      sim_grid_pos_y: 1762712.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656415.38
      sim_grid_pos_y: 1762723.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1656500.88
      sim_grid_pos_y: 1762562.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1656434.88
      sim_grid_pos_y: 1762432.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1656609.12
      sim_grid_pos_y: 1762404.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1656662
      sim_grid_pos_y: 1762272
    }
    terrain_level_point {
      sim_grid_pos_x: 1656735.88
      sim_grid_pos_y: 1762273.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1656861.25
      sim_grid_pos_y: 1762133.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1656892.88
      sim_grid_pos_y: 1762051.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1657047.38
      sim_grid_pos_y: 1761978.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1657051.62
      sim_grid_pos_y: 1761972.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1657051.75
      sim_grid_pos_y: 1761973.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1657289.25
      sim_grid_pos_y: 1762195.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1657505.38
      sim_grid_pos_y: 1762171.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1657619.38
      sim_grid_pos_y: 1761914.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1657576
      sim_grid_pos_y: 1759658.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1655541
      sim_grid_pos_y: 1759553.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.6554e+06
      sim_grid_pos_y: 1759419.88
    }
  }
}
