terrain_level_data {
  terrain_level: 35
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1918848.88
      sim_grid_pos_y: 1063230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1919588.38
      sim_grid_pos_y: 1063533.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1920179.75
      sim_grid_pos_y: 1064700.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1920211.75
      sim_grid_pos_y: 1065223.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1919567
      sim_grid_pos_y: 1065752.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1915385.38
      sim_grid_pos_y: 1066253.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1916747.62
      sim_grid_pos_y: 1064267.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1918081
      sim_grid_pos_y: 1063613.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1918235.25
      sim_grid_pos_y: 1063242.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1919610.62
      sim_grid_pos_y: 1063509.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1920210.12
      sim_grid_pos_y: 1064691.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1920243.38
      sim_grid_pos_y: 1065237.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1919579.5
      sim_grid_pos_y: 1065782.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915369.38
      sim_grid_pos_y: 1066286.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1915348.88
      sim_grid_pos_y: 1066252.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1916726.88
      sim_grid_pos_y: 1064243.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1918057.12
      sim_grid_pos_y: 1063591.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1918214.62
      sim_grid_pos_y: 1063211.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1918854.62
      sim_grid_pos_y: 1063199.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1919632.88
      sim_grid_pos_y: 1063485.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1920240.5
      sim_grid_pos_y: 1064683.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1920275
      sim_grid_pos_y: 1065251.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1919592.12
      sim_grid_pos_y: 1065811.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915353.38
      sim_grid_pos_y: 1066319.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915312.25
      sim_grid_pos_y: 1066251.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1916706.12
      sim_grid_pos_y: 1064219.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1918033.12
      sim_grid_pos_y: 1063568.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1918193.88
      sim_grid_pos_y: 1063181.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1918860.38
      sim_grid_pos_y: 1063168.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1919655.12
      sim_grid_pos_y: 1063461.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1920270.75
      sim_grid_pos_y: 1064675.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1920306.62
      sim_grid_pos_y: 1065265.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1919604.62
      sim_grid_pos_y: 1065841.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1915337.25
      sim_grid_pos_y: 1066352
    }
    terrain_level_point {
      sim_grid_pos_x: 1915275.62
      sim_grid_pos_y: 1066250.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1916685.25
      sim_grid_pos_y: 1064195.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1918009.12
      sim_grid_pos_y: 1063546.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1918173.25
      sim_grid_pos_y: 1063151.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1918866.12
      sim_grid_pos_y: 1063137.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1919677.38
      sim_grid_pos_y: 1063437.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1920301
      sim_grid_pos_y: 1064667.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1920338.38
      sim_grid_pos_y: 1065279.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1919617.25
      sim_grid_pos_y: 1065870.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1915321.25
      sim_grid_pos_y: 1066384.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1915239.12
      sim_grid_pos_y: 1066249.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1916664.5
      sim_grid_pos_y: 1064171.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1917985.25
      sim_grid_pos_y: 1063523.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1918152.5
      sim_grid_pos_y: 1063120.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1918871.88
      sim_grid_pos_y: 1063106.75
    }
  }
}
