terrain_level_data {
  terrain_level: 1929
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1727806.5
      sim_grid_pos_y: 1667415.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1725481.75
      sim_grid_pos_y: 1666969
    }
    terrain_level_point {
      sim_grid_pos_x: 1725356.62
      sim_grid_pos_y: 1667645.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1721093.62
      sim_grid_pos_y: 1667383.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.7203e+06
      sim_grid_pos_y: 1666988.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1719501.75
      sim_grid_pos_y: 1666491.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1718301.75
      sim_grid_pos_y: 1666459
    }
    terrain_level_point {
      sim_grid_pos_x: 1716482
      sim_grid_pos_y: 1667002.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1716173.75
      sim_grid_pos_y: 1665554.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1716435
      sim_grid_pos_y: 1664737.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1724352.38
      sim_grid_pos_y: 1666404.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.72789e+06
      sim_grid_pos_y: 1667034.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1724372
      sim_grid_pos_y: 1666303.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1728012.88
      sim_grid_pos_y: 1666952
    }
    terrain_level_point {
      sim_grid_pos_x: 1727885.25
      sim_grid_pos_y: 1667535.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1725563.75
      sim_grid_pos_y: 1667089.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1725440.88
      sim_grid_pos_y: 1667753.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1721066.5
      sim_grid_pos_y: 1667484.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.72025e+06
      sim_grid_pos_y: 1667077.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1719471.25
      sim_grid_pos_y: 1666593.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1718315.38
      sim_grid_pos_y: 1666562
    }
    terrain_level_point {
      sim_grid_pos_x: 1716404.88
      sim_grid_pos_y: 1667132.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1716067.75
      sim_grid_pos_y: 1665549.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1716365.62
      sim_grid_pos_y: 1664618.12
    }
  }
}
