terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 438616.969
      sim_grid_pos_y: 2067319.38
    }
    terrain_level_point {
      sim_grid_pos_x: 437888.625
      sim_grid_pos_y: 2067169.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437047.75
      sim_grid_pos_y: 2066590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437002.094
      sim_grid_pos_y: 2065821.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437071.844
      sim_grid_pos_y: 2065118.62
    }
    terrain_level_point {
      sim_grid_pos_x: 437192.438
      sim_grid_pos_y: 2064618
    }
    terrain_level_point {
      sim_grid_pos_x: 437513.5
      sim_grid_pos_y: 2064270.12
    }
    terrain_level_point {
      sim_grid_pos_x: 438099.5
      sim_grid_pos_y: 2063868.62
    }
    terrain_level_point {
      sim_grid_pos_x: 438554.906
      sim_grid_pos_y: 2063629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439154.062
      sim_grid_pos_y: 2063549.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439574.906
      sim_grid_pos_y: 2063721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440130.625
      sim_grid_pos_y: 2064094
    }
    terrain_level_point {
      sim_grid_pos_x: 439439.656
      sim_grid_pos_y: 2065029
    }
    terrain_level_point {
      sim_grid_pos_x: 439237.469
      sim_grid_pos_y: 2065172.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439333.656
      sim_grid_pos_y: 2065651.5
    }
    terrain_level_point {
      sim_grid_pos_x: 439577.031
      sim_grid_pos_y: 2065953.5
    }
    terrain_level_point {
      sim_grid_pos_x: 439830.219
      sim_grid_pos_y: 2066112
    }
    terrain_level_point {
      sim_grid_pos_x: 440568.281
      sim_grid_pos_y: 2066191.75
    }
    terrain_level_point {
      sim_grid_pos_x: 441031.031
      sim_grid_pos_y: 2065123.38
    }
    terrain_level_point {
      sim_grid_pos_x: 441796.438
      sim_grid_pos_y: 2065586.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441214.25
      sim_grid_pos_y: 2066600.75
    }
    terrain_level_point {
      sim_grid_pos_x: 440877.438
      sim_grid_pos_y: 2067483.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441157.188
      sim_grid_pos_y: 2.06791e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 441211.25
      sim_grid_pos_y: 2068578.25
    }
    terrain_level_point {
      sim_grid_pos_x: 439802.344
      sim_grid_pos_y: 2068121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 438777.062
      sim_grid_pos_y: 2067773
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 439637.844
      sim_grid_pos_y: 2063603
    }
    terrain_level_point {
      sim_grid_pos_x: 440320.719
      sim_grid_pos_y: 2064061
    }
    terrain_level_point {
      sim_grid_pos_x: 439534.125
      sim_grid_pos_y: 2065125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 439385.188
      sim_grid_pos_y: 2065230.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439457.906
      sim_grid_pos_y: 2065593.38
    }
    terrain_level_point {
      sim_grid_pos_x: 439666.75
      sim_grid_pos_y: 2065852.38
    }
    terrain_level_point {
      sim_grid_pos_x: 439875
      sim_grid_pos_y: 2065982.88
    }
    terrain_level_point {
      sim_grid_pos_x: 440484.969
      sim_grid_pos_y: 2066048.75
    }
    terrain_level_point {
      sim_grid_pos_x: 440969.438
      sim_grid_pos_y: 2064930.25
    }
    terrain_level_point {
      sim_grid_pos_x: 441976.875
      sim_grid_pos_y: 2065540.38
    }
    terrain_level_point {
      sim_grid_pos_x: 441335.062
      sim_grid_pos_y: 2066658
    }
    terrain_level_point {
      sim_grid_pos_x: 441026.25
      sim_grid_pos_y: 2067467.75
    }
    terrain_level_point {
      sim_grid_pos_x: 441287.312
      sim_grid_pos_y: 2067865.38
    }
    terrain_level_point {
      sim_grid_pos_x: 441360.219
      sim_grid_pos_y: 2068766.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439760.344
      sim_grid_pos_y: 2068247.62
    }
    terrain_level_point {
      sim_grid_pos_x: 438672.906
      sim_grid_pos_y: 2067878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 438516.344
      sim_grid_pos_y: 2067434.62
    }
    terrain_level_point {
      sim_grid_pos_x: 437835.281
      sim_grid_pos_y: 2067294.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436918.562
      sim_grid_pos_y: 2066663.12
    }
    terrain_level_point {
      sim_grid_pos_x: 436868.438
      sim_grid_pos_y: 2065818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436940.094
      sim_grid_pos_y: 2065096.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437071
      sim_grid_pos_y: 2064553.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437425.75
      sim_grid_pos_y: 2064168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 438030.656
      sim_grid_pos_y: 2063754.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438513.875
      sim_grid_pos_y: 2063500.75
    }
    terrain_level_point {
      sim_grid_pos_x: 439171.562
      sim_grid_pos_y: 2063412.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 439700.781
      sim_grid_pos_y: 2063484.75
    }
    terrain_level_point {
      sim_grid_pos_x: 440510.812
      sim_grid_pos_y: 2064028.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439628.594
      sim_grid_pos_y: 2065221.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439532.906
      sim_grid_pos_y: 2065289.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439582.156
      sim_grid_pos_y: 2065535.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439756.469
      sim_grid_pos_y: 2065751.38
    }
    terrain_level_point {
      sim_grid_pos_x: 439919.781
      sim_grid_pos_y: 2065853.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440401.688
      sim_grid_pos_y: 2065905.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440907.844
      sim_grid_pos_y: 2064737.12
    }
    terrain_level_point {
      sim_grid_pos_x: 442157.312
      sim_grid_pos_y: 2065493.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441455.844
      sim_grid_pos_y: 2066715.38
    }
    terrain_level_point {
      sim_grid_pos_x: 441175.062
      sim_grid_pos_y: 2067451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 441417.406
      sim_grid_pos_y: 2067820.62
    }
    terrain_level_point {
      sim_grid_pos_x: 441509.188
      sim_grid_pos_y: 2068955.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439718.344
      sim_grid_pos_y: 2068374.12
    }
    terrain_level_point {
      sim_grid_pos_x: 438568.75
      sim_grid_pos_y: 2067983.88
    }
    terrain_level_point {
      sim_grid_pos_x: 438415.688
      sim_grid_pos_y: 2.06755e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 437781.938
      sim_grid_pos_y: 2067419.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436789.344
      sim_grid_pos_y: 2066736
    }
    terrain_level_point {
      sim_grid_pos_x: 436734.75
      sim_grid_pos_y: 2065815.75
    }
    terrain_level_point {
      sim_grid_pos_x: 436808.375
      sim_grid_pos_y: 2065074
    }
    terrain_level_point {
      sim_grid_pos_x: 436949.531
      sim_grid_pos_y: 2064488.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437338.031
      sim_grid_pos_y: 2064067.12
    }
    terrain_level_point {
      sim_grid_pos_x: 437961.812
      sim_grid_pos_y: 2063639.88
    }
    terrain_level_point {
      sim_grid_pos_x: 438472.844
      sim_grid_pos_y: 2063371.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439189.062
      sim_grid_pos_y: 2063276
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 439763.719
      sim_grid_pos_y: 2063366.5
    }
    terrain_level_point {
      sim_grid_pos_x: 440700.906
      sim_grid_pos_y: 2063995.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439723.062
      sim_grid_pos_y: 2065318.25
    }
    terrain_level_point {
      sim_grid_pos_x: 439680.625
      sim_grid_pos_y: 2065348.25
    }
    terrain_level_point {
      sim_grid_pos_x: 439706.438
      sim_grid_pos_y: 2065476.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439846.188
      sim_grid_pos_y: 2065650.25
    }
    terrain_level_point {
      sim_grid_pos_x: 439964.531
      sim_grid_pos_y: 2065724.38
    }
    terrain_level_point {
      sim_grid_pos_x: 440318.406
      sim_grid_pos_y: 2065762.62
    }
    terrain_level_point {
      sim_grid_pos_x: 440846.219
      sim_grid_pos_y: 2064544
    }
    terrain_level_point {
      sim_grid_pos_x: 442337.719
      sim_grid_pos_y: 2065447.25
    }
    terrain_level_point {
      sim_grid_pos_x: 441576.625
      sim_grid_pos_y: 2066772.62
    }
    terrain_level_point {
      sim_grid_pos_x: 441323.875
      sim_grid_pos_y: 2067435.38
    }
    terrain_level_point {
      sim_grid_pos_x: 441547.5
      sim_grid_pos_y: 2067776
    }
    terrain_level_point {
      sim_grid_pos_x: 441658.125
      sim_grid_pos_y: 2069143.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439676.344
      sim_grid_pos_y: 2068500.62
    }
    terrain_level_point {
      sim_grid_pos_x: 438464.594
      sim_grid_pos_y: 2068089.25
    }
    terrain_level_point {
      sim_grid_pos_x: 438315.062
      sim_grid_pos_y: 2067665.38
    }
    terrain_level_point {
      sim_grid_pos_x: 437728.594
      sim_grid_pos_y: 2067544.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436660.156
      sim_grid_pos_y: 2066808.88
    }
    terrain_level_point {
      sim_grid_pos_x: 436601.094
      sim_grid_pos_y: 2065813.12
    }
    terrain_level_point {
      sim_grid_pos_x: 436676.656
      sim_grid_pos_y: 2065051.62
    }
    terrain_level_point {
      sim_grid_pos_x: 436828.094
      sim_grid_pos_y: 2064423.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437250.281
      sim_grid_pos_y: 2063965.75
    }
    terrain_level_point {
      sim_grid_pos_x: 437892.969
      sim_grid_pos_y: 2063525.38
    }
    terrain_level_point {
      sim_grid_pos_x: 438431.812
      sim_grid_pos_y: 2063242.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439206.562
      sim_grid_pos_y: 2063139.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 439826.656
      sim_grid_pos_y: 2063248.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440891.031
      sim_grid_pos_y: 2063962.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439827.25
      sim_grid_pos_y: 2065401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 439830.688
      sim_grid_pos_y: 2065418.62
    }
    terrain_level_point {
      sim_grid_pos_x: 439935.906
      sim_grid_pos_y: 2065549.25
    }
    terrain_level_point {
      sim_grid_pos_x: 440009.312
      sim_grid_pos_y: 2065595.12
    }
    terrain_level_point {
      sim_grid_pos_x: 440235.094
      sim_grid_pos_y: 2065619.5
    }
    terrain_level_point {
      sim_grid_pos_x: 440784.625
      sim_grid_pos_y: 2064350.88
    }
    terrain_level_point {
      sim_grid_pos_x: 442518.156
      sim_grid_pos_y: 2065400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 441697.438
      sim_grid_pos_y: 2066829.88
    }
    terrain_level_point {
      sim_grid_pos_x: 441472.688
      sim_grid_pos_y: 2067419.25
    }
    terrain_level_point {
      sim_grid_pos_x: 441677.625
      sim_grid_pos_y: 2067731.25
    }
    terrain_level_point {
      sim_grid_pos_x: 441807.094
      sim_grid_pos_y: 2069332.12
    }
    terrain_level_point {
      sim_grid_pos_x: 439634.375
      sim_grid_pos_y: 2068627.12
    }
    terrain_level_point {
      sim_grid_pos_x: 438360.469
      sim_grid_pos_y: 2068194.62
    }
    terrain_level_point {
      sim_grid_pos_x: 438214.438
      sim_grid_pos_y: 2067780.75
    }
    terrain_level_point {
      sim_grid_pos_x: 437675.25
      sim_grid_pos_y: 2067669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 436530.969
      sim_grid_pos_y: 2066881.75
    }
    terrain_level_point {
      sim_grid_pos_x: 436467.406
      sim_grid_pos_y: 2065810.5
    }
    terrain_level_point {
      sim_grid_pos_x: 436544.938
      sim_grid_pos_y: 2065029.38
    }
    terrain_level_point {
      sim_grid_pos_x: 436706.625
      sim_grid_pos_y: 2064358.38
    }
    terrain_level_point {
      sim_grid_pos_x: 437162.531
      sim_grid_pos_y: 2063864.25
    }
    terrain_level_point {
      sim_grid_pos_x: 437824.094
      sim_grid_pos_y: 2063411
    }
    terrain_level_point {
      sim_grid_pos_x: 438390.781
      sim_grid_pos_y: 2063113.88
    }
    terrain_level_point {
      sim_grid_pos_x: 439224.031
      sim_grid_pos_y: 2063002.38
    }
  }
}
