terrain_level_data {
  terrain_level: 350
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1461663
      sim_grid_pos_y: 1558928.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1462023
      sim_grid_pos_y: 1558923.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464199.75
      sim_grid_pos_y: 1558899.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464592.75
      sim_grid_pos_y: 1.5588e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1465106.25
      sim_grid_pos_y: 1558720.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1465599.62
      sim_grid_pos_y: 1559027.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465322.62
      sim_grid_pos_y: 1559723.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465088
      sim_grid_pos_y: 1561066.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464798.88
      sim_grid_pos_y: 1561108.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464575.62
      sim_grid_pos_y: 1561019.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464068.38
      sim_grid_pos_y: 1560895
    }
    terrain_level_point {
      sim_grid_pos_x: 1463582.12
      sim_grid_pos_y: 1561140.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1463114.88
      sim_grid_pos_y: 1561271
    }
    terrain_level_point {
      sim_grid_pos_x: 1463150.38
      sim_grid_pos_y: 1561008.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1463439.38
      sim_grid_pos_y: 1560606.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464484.88
      sim_grid_pos_y: 1560485.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464391.88
      sim_grid_pos_y: 1559941.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464022.5
      sim_grid_pos_y: 1559531.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1463549.88
      sim_grid_pos_y: 1559654.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1462789
      sim_grid_pos_y: 1559696.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1462467.88
      sim_grid_pos_y: 1559809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1462197.75
      sim_grid_pos_y: 1559944.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1462021.5
      sim_grid_pos_y: 1559901.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1461768.38
      sim_grid_pos_y: 1559978.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461603.12
      sim_grid_pos_y: 1559981.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461345.12
      sim_grid_pos_y: 1559783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460834.12
      sim_grid_pos_y: 1559996.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1460704.88
      sim_grid_pos_y: 1559968.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460954.38
      sim_grid_pos_y: 1559306.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1460973.62
      sim_grid_pos_y: 1559166.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461111.38
      sim_grid_pos_y: 1559017.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461310.5
      sim_grid_pos_y: 1558919.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1465637.75
      sim_grid_pos_y: 1559015.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465352.38
      sim_grid_pos_y: 1559732.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1465114.38
      sim_grid_pos_y: 1561094
    }
    terrain_level_point {
      sim_grid_pos_x: 1464795.12
      sim_grid_pos_y: 1561139.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464566.25
      sim_grid_pos_y: 1561048.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464072.12
      sim_grid_pos_y: 1560927.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1463593.38
      sim_grid_pos_y: 1561169.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1463078.12
      sim_grid_pos_y: 1561313.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1463121
      sim_grid_pos_y: 1560997.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1463422.38
      sim_grid_pos_y: 1560577.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464449
      sim_grid_pos_y: 1560458.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464363.12
      sim_grid_pos_y: 1559955.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464012.12
      sim_grid_pos_y: 1559565.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463554.62
      sim_grid_pos_y: 1559685
    }
    terrain_level_point {
      sim_grid_pos_x: 1462795
      sim_grid_pos_y: 1559727.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1462479.88
      sim_grid_pos_y: 1559837.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1462201.38
      sim_grid_pos_y: 1559977
    }
    terrain_level_point {
      sim_grid_pos_x: 1462022.38
      sim_grid_pos_y: 1559933
    }
    terrain_level_point {
      sim_grid_pos_x: 1461773.25
      sim_grid_pos_y: 1560009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461592.88
      sim_grid_pos_y: 1560012.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461340.5
      sim_grid_pos_y: 1559818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460837
      sim_grid_pos_y: 1560028.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460663.5
      sim_grid_pos_y: 1559990.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460924.5
      sim_grid_pos_y: 1559299.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460944.5
      sim_grid_pos_y: 1559153
    }
    terrain_level_point {
      sim_grid_pos_x: 1461092.75
      sim_grid_pos_y: 1558992.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461303.75
      sim_grid_pos_y: 1558888.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1461663.25
      sim_grid_pos_y: 1558897.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1462022.62
      sim_grid_pos_y: 1558892.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464195.75
      sim_grid_pos_y: 1558869
    }
    terrain_level_point {
      sim_grid_pos_x: 1464586.5
      sim_grid_pos_y: 1558769.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1465112.75
      sim_grid_pos_y: 1558688.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1465675.88
      sim_grid_pos_y: 1559002.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465382.12
      sim_grid_pos_y: 1559740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1465140.88
      sim_grid_pos_y: 1561121.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464791.38
      sim_grid_pos_y: 1561171.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464556.88
      sim_grid_pos_y: 1561078
    }
    terrain_level_point {
      sim_grid_pos_x: 1464075.75
      sim_grid_pos_y: 1560960.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1463604.5
      sim_grid_pos_y: 1561198.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1463041.25
      sim_grid_pos_y: 1561355.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1463091.5
      sim_grid_pos_y: 1560985.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1463405.25
      sim_grid_pos_y: 1560548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464413.25
      sim_grid_pos_y: 1560432.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464334.25
      sim_grid_pos_y: 1559969.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1464001.75
      sim_grid_pos_y: 1559600.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1463559.38
      sim_grid_pos_y: 1559715.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1462801.12
      sim_grid_pos_y: 1559757.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1462491.88
      sim_grid_pos_y: 1559866.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1462205.12
      sim_grid_pos_y: 1560009.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1462023.25
      sim_grid_pos_y: 1559964.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461778.12
      sim_grid_pos_y: 1560040.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1461582.62
      sim_grid_pos_y: 1560043.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461335.88
      sim_grid_pos_y: 1559853.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1460839.88
      sim_grid_pos_y: 1560061.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460622.25
      sim_grid_pos_y: 1560012.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460894.5
      sim_grid_pos_y: 1559291.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460915.25
      sim_grid_pos_y: 1559139.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461074
      sim_grid_pos_y: 1558967.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461296.88
      sim_grid_pos_y: 1558857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461663.38
      sim_grid_pos_y: 1558867.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1462022.25
      sim_grid_pos_y: 1558861.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464191.75
      sim_grid_pos_y: 1558838.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464580.38
      sim_grid_pos_y: 1558739.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1465119.38
      sim_grid_pos_y: 1558656.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1465713.88
      sim_grid_pos_y: 1558990.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465411.88
      sim_grid_pos_y: 1559749
    }
    terrain_level_point {
      sim_grid_pos_x: 1465167.25
      sim_grid_pos_y: 1561148.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464787.62
      sim_grid_pos_y: 1561202.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464547.5
      sim_grid_pos_y: 1561107.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464079.5
      sim_grid_pos_y: 1560992.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1463615.75
      sim_grid_pos_y: 1561226.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463004.5
      sim_grid_pos_y: 1561397.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1463062
      sim_grid_pos_y: 1560973.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1463388.25
      sim_grid_pos_y: 1560519.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464377.5
      sim_grid_pos_y: 1560405.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464305.38
      sim_grid_pos_y: 1559983.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1463991.5
      sim_grid_pos_y: 1559634.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463564.25
      sim_grid_pos_y: 1559746
    }
    terrain_level_point {
      sim_grid_pos_x: 1462807.25
      sim_grid_pos_y: 1559788.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1462504
      sim_grid_pos_y: 1559894.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1462208.75
      sim_grid_pos_y: 1560042.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1462024.25
      sim_grid_pos_y: 1559996.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461783
      sim_grid_pos_y: 1560070.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461572.38
      sim_grid_pos_y: 1560074.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461331.38
      sim_grid_pos_y: 1559889
    }
    terrain_level_point {
      sim_grid_pos_x: 1460842.75
      sim_grid_pos_y: 1560093.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460580.88
      sim_grid_pos_y: 1560035.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460864.5
      sim_grid_pos_y: 1559283.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460886.12
      sim_grid_pos_y: 1559125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461055.25
      sim_grid_pos_y: 1558942.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461290.12
      sim_grid_pos_y: 1558826.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461663.5
      sim_grid_pos_y: 1558836.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1462021.88
      sim_grid_pos_y: 1558830.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464187.75
      sim_grid_pos_y: 1558807.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1464574.25
      sim_grid_pos_y: 1558709.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1465126
      sim_grid_pos_y: 1558624
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1465752
      sim_grid_pos_y: 1558977.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1465441.62
      sim_grid_pos_y: 1559757.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1465193.75
      sim_grid_pos_y: 1561175.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464783.88
      sim_grid_pos_y: 1561234.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1464538
      sim_grid_pos_y: 1561136.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1464083.25
      sim_grid_pos_y: 1561025.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1463626.88
      sim_grid_pos_y: 1561255.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1462967.75
      sim_grid_pos_y: 1561439.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463032.62
      sim_grid_pos_y: 1560961.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463371.12
      sim_grid_pos_y: 1560490.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1464341.62
      sim_grid_pos_y: 1560378.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1464276.62
      sim_grid_pos_y: 1559997.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1463981.12
      sim_grid_pos_y: 1559669.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1463569
      sim_grid_pos_y: 1559776.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1462813.25
      sim_grid_pos_y: 1559818.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1462516
      sim_grid_pos_y: 1559923
    }
    terrain_level_point {
      sim_grid_pos_x: 1462212.38
      sim_grid_pos_y: 1560074.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1462025.12
      sim_grid_pos_y: 1560028.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461787.75
      sim_grid_pos_y: 1560101.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461562.25
      sim_grid_pos_y: 1560105.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461326.75
      sim_grid_pos_y: 1559924.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460845.62
      sim_grid_pos_y: 1560125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1460539.62
      sim_grid_pos_y: 1560057.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460834.5
      sim_grid_pos_y: 1559276.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1460857
      sim_grid_pos_y: 1559111.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461036.5
      sim_grid_pos_y: 1558917.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461283.38
      sim_grid_pos_y: 1558795.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461663.5
      sim_grid_pos_y: 1558805.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1462021.5
      sim_grid_pos_y: 1558800.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1464183.75
      sim_grid_pos_y: 1558776.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1464568.12
      sim_grid_pos_y: 1558679.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1465132.5
      sim_grid_pos_y: 1558591.75
    }
  }
}
terrain_level_data {
  terrain_level: 450
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1462288.88
      sim_grid_pos_y: 1561120.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1462744.75
      sim_grid_pos_y: 1561149.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1463044.88
      sim_grid_pos_y: 1561201.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1462782.75
      sim_grid_pos_y: 1562037.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1462674.12
      sim_grid_pos_y: 1562284.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1461817.62
      sim_grid_pos_y: 1562222.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461387.5
      sim_grid_pos_y: 1562135.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461119
      sim_grid_pos_y: 1562192.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1460805.62
      sim_grid_pos_y: 1561972
    }
    terrain_level_point {
      sim_grid_pos_x: 1460925.75
      sim_grid_pos_y: 1561653.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460833.25
      sim_grid_pos_y: 1561598.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1460981.25
      sim_grid_pos_y: 1561436.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1460983.75
      sim_grid_pos_y: 1561343.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1461117.5
      sim_grid_pos_y: 1561022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461472.62
      sim_grid_pos_y: 1.56098e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1461892.5
      sim_grid_pos_y: 1560978.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1462295.12
      sim_grid_pos_y: 1561089.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1462748.38
      sim_grid_pos_y: 1561118.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1463084.75
      sim_grid_pos_y: 1561177.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1462811.62
      sim_grid_pos_y: 1562048.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1462693.5
      sim_grid_pos_y: 1562316.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461813.5
      sim_grid_pos_y: 1562253.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461387.62
      sim_grid_pos_y: 1562166.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1461112.38
      sim_grid_pos_y: 1562225.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460768.5
      sim_grid_pos_y: 1561983.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460887.88
      sim_grid_pos_y: 1561666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1460785
      sim_grid_pos_y: 1561605.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460950.75
      sim_grid_pos_y: 1561424.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460953.12
      sim_grid_pos_y: 1561337.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1461096
      sim_grid_pos_y: 1560994.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1461470.75
      sim_grid_pos_y: 1560949.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461897.75
      sim_grid_pos_y: 1560947.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1462301.38
      sim_grid_pos_y: 1561059.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1462752
      sim_grid_pos_y: 1561087.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1463124.62
      sim_grid_pos_y: 1561152.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1462840.38
      sim_grid_pos_y: 1562059.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1462713
      sim_grid_pos_y: 1562349
    }
    terrain_level_point {
      sim_grid_pos_x: 1461809.25
      sim_grid_pos_y: 1562284
    }
    terrain_level_point {
      sim_grid_pos_x: 1461387.75
      sim_grid_pos_y: 1562198.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1461105.62
      sim_grid_pos_y: 1562258.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1460731.25
      sim_grid_pos_y: 1561994.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.46085e+06
      sim_grid_pos_y: 1561679.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1460736.75
      sim_grid_pos_y: 1561612.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460920.38
      sim_grid_pos_y: 1561411.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1460922.5
      sim_grid_pos_y: 1561330.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1461074.5
      sim_grid_pos_y: 1560965.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1461468.88
      sim_grid_pos_y: 1560918.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461903
      sim_grid_pos_y: 1560917.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1462307.62
      sim_grid_pos_y: 1561029
    }
    terrain_level_point {
      sim_grid_pos_x: 1462755.62
      sim_grid_pos_y: 1561057.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1463164.38
      sim_grid_pos_y: 1561128.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1462869.25
      sim_grid_pos_y: 1562070.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1462732.38
      sim_grid_pos_y: 1562381.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1461805.12
      sim_grid_pos_y: 1562314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461387.88
      sim_grid_pos_y: 1562229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461098.88
      sim_grid_pos_y: 1562291.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460694.12
      sim_grid_pos_y: 1562006.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1460812.12
      sim_grid_pos_y: 1561693.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1460688.5
      sim_grid_pos_y: 1.56162e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1460889.88
      sim_grid_pos_y: 1561399.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1460892
      sim_grid_pos_y: 1561324
    }
    terrain_level_point {
      sim_grid_pos_x: 1461053
      sim_grid_pos_y: 1560937.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1461467
      sim_grid_pos_y: 1560887.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1461908.25
      sim_grid_pos_y: 1560886.38
    }
  }
}
