terrain_level_data {
  terrain_level: 960
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1193622.62
      sim_grid_pos_y: 1886989.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1193583
      sim_grid_pos_y: 1889528.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1193546.62
      sim_grid_pos_y: 1889862.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1193307.12
      sim_grid_pos_y: 1890183
    }
    terrain_level_point {
      sim_grid_pos_x: 1193089.88
      sim_grid_pos_y: 1890438.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1192391.12
      sim_grid_pos_y: 1892297.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1193283.5
      sim_grid_pos_y: 1893448.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1194012
      sim_grid_pos_y: 1892443.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1194438.75
      sim_grid_pos_y: 1891641.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1194876.75
      sim_grid_pos_y: 1891567.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.19535e+06
      sim_grid_pos_y: 1891213.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1195312.12
      sim_grid_pos_y: 1891044
    }
    terrain_level_point {
      sim_grid_pos_x: 1195075
      sim_grid_pos_y: 1890867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1194927.88
      sim_grid_pos_y: 1890881.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1195009.12
      sim_grid_pos_y: 1887942.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1194739.75
      sim_grid_pos_y: 1887615.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1194601.88
      sim_grid_pos_y: 1887479
    }
    terrain_level_point {
      sim_grid_pos_x: 1194451.38
      sim_grid_pos_y: 1887585.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194293.5
      sim_grid_pos_y: 1887629.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.19417e+06
      sim_grid_pos_y: 1887601.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194127.25
      sim_grid_pos_y: 1887277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1194137.62
      sim_grid_pos_y: 1886984.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1194265.12
      sim_grid_pos_y: 1886860.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1193501.5
      sim_grid_pos_y: 1886867.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1193460.12
      sim_grid_pos_y: 1889520.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1193428
      sim_grid_pos_y: 1889815.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1193211
      sim_grid_pos_y: 1890106.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1192982.25
      sim_grid_pos_y: 1890374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1192251.75
      sim_grid_pos_y: 1892319
    }
    terrain_level_point {
      sim_grid_pos_x: 1193286.75
      sim_grid_pos_y: 1893654
    }
    terrain_level_point {
      sim_grid_pos_x: 1194116.62
      sim_grid_pos_y: 1892508.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1194518.88
      sim_grid_pos_y: 1891752.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1194926.62
      sim_grid_pos_y: 1891683.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1195487.38
      sim_grid_pos_y: 1891264.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1195422.25
      sim_grid_pos_y: 1890972.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1195110.38
      sim_grid_pos_y: 1890740.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1195054.62
      sim_grid_pos_y: 1890745.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1195133.38
      sim_grid_pos_y: 1887899.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1194830.62
      sim_grid_pos_y: 1887532
    }
    terrain_level_point {
      sim_grid_pos_x: 1194614.88
      sim_grid_pos_y: 1887318.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1194397.62
      sim_grid_pos_y: 1887473
    }
    terrain_level_point {
      sim_grid_pos_x: 1194290.38
      sim_grid_pos_y: 1887502.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194280.75
      sim_grid_pos_y: 1887500.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1194250.62
      sim_grid_pos_y: 1887271.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1194392.62
      sim_grid_pos_y: 1886736.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1193380.38
      sim_grid_pos_y: 1886745.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1193337.12
      sim_grid_pos_y: 1889512.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1193309.25
      sim_grid_pos_y: 1889769.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1193114.62
      sim_grid_pos_y: 1890029.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1192874.62
      sim_grid_pos_y: 1890311.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1192112.5
      sim_grid_pos_y: 1.89234e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1193290.12
      sim_grid_pos_y: 1893859
    }
    terrain_level_point {
      sim_grid_pos_x: 1194221.25
      sim_grid_pos_y: 1892574.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1194599.12
      sim_grid_pos_y: 1891863.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1194976.38
      sim_grid_pos_y: 1.8918e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1195624.75
      sim_grid_pos_y: 1891315.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1195532.38
      sim_grid_pos_y: 1890901.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1195180.75
      sim_grid_pos_y: 1890639.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1195257.62
      sim_grid_pos_y: 1887857.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1194921.62
      sim_grid_pos_y: 1887449
    }
    terrain_level_point {
      sim_grid_pos_x: 1194627.88
      sim_grid_pos_y: 1887158.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1194382.75
      sim_grid_pos_y: 1887332.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194373.88
      sim_grid_pos_y: 1887265.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1194520.25
      sim_grid_pos_y: 1886612.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1193259.25
      sim_grid_pos_y: 1886623.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1193214.25
      sim_grid_pos_y: 1889505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1193190.62
      sim_grid_pos_y: 1889722.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1193018.62
      sim_grid_pos_y: 1889952.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1192767
      sim_grid_pos_y: 1890247.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1191973.12
      sim_grid_pos_y: 1892361.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1193293.38
      sim_grid_pos_y: 1894064.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1194325.88
      sim_grid_pos_y: 1892639.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1194679.25
      sim_grid_pos_y: 1891974.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1195026.25
      sim_grid_pos_y: 1891916.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1195762.12
      sim_grid_pos_y: 1891366.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1195642.62
      sim_grid_pos_y: 1.89083e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1195305.5
      sim_grid_pos_y: 1890578.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1195381.88
      sim_grid_pos_y: 1887814.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1195012.62
      sim_grid_pos_y: 1887365.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1194640.88
      sim_grid_pos_y: 1886998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194503
      sim_grid_pos_y: 1887096.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1194647.75
      sim_grid_pos_y: 1886488.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1193138.12
      sim_grid_pos_y: 1886501.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1193091.38
      sim_grid_pos_y: 1889497.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1193072
      sim_grid_pos_y: 1889675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1192922.38
      sim_grid_pos_y: 1889875.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1192659.38
      sim_grid_pos_y: 1890184.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1191833.75
      sim_grid_pos_y: 1892382.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1193296.75
      sim_grid_pos_y: 1894269.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1194430.5
      sim_grid_pos_y: 1892704.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194759.5
      sim_grid_pos_y: 1892086.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1195076.12
      sim_grid_pos_y: 1892032.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1195899.62
      sim_grid_pos_y: 1891417
    }
    terrain_level_point {
      sim_grid_pos_x: 1195752.75
      sim_grid_pos_y: 1890758.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1195430.25
      sim_grid_pos_y: 1890518.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1195506.12
      sim_grid_pos_y: 1887772
    }
    terrain_level_point {
      sim_grid_pos_x: 1195103.5
      sim_grid_pos_y: 1887282.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194653.88
      sim_grid_pos_y: 1886838.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1194634.75
      sim_grid_pos_y: 1886852.25
    }
  }
}
