terrain_level_data {
  terrain_level: 1000
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1698006
      sim_grid_pos_y: 923454.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1697937.25
      sim_grid_pos_y: 923579.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1698008.25
      sim_grid_pos_y: 923701.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1698166.25
      sim_grid_pos_y: 923789
    }
    terrain_level_point {
      sim_grid_pos_x: 1698284
      sim_grid_pos_y: 923789.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1698546.62
      sim_grid_pos_y: 923755.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1698850.62
      sim_grid_pos_y: 923644.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1.69888e+06
      sim_grid_pos_y: 923397.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1698888.75
      sim_grid_pos_y: 923234.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1698783.88
      sim_grid_pos_y: 923029.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698649.38
      sim_grid_pos_y: 922996.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698587
      sim_grid_pos_y: 923199.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1698589.62
      sim_grid_pos_y: 923403.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698346.5
      sim_grid_pos_y: 923590.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1698194.5
      sim_grid_pos_y: 923452.625
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1698579.75
      sim_grid_pos_y: 922874
    }
    terrain_level_point {
      sim_grid_pos_x: 1698484.38
      sim_grid_pos_y: 923185.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1698486.5
      sim_grid_pos_y: 923353.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698351.88
      sim_grid_pos_y: 923457
    }
    terrain_level_point {
      sim_grid_pos_x: 1698233.62
      sim_grid_pos_y: 923349.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1697945.12
      sim_grid_pos_y: 923352.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1697819.5
      sim_grid_pos_y: 923580.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1697933.88
      sim_grid_pos_y: 923778
    }
    terrain_level_point {
      sim_grid_pos_x: 1698139.62
      sim_grid_pos_y: 923891.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1698290.5
      sim_grid_pos_y: 923892.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1698571.12
      sim_grid_pos_y: 923855.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1698944.88
      sim_grid_pos_y: 923719.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1698982.25
      sim_grid_pos_y: 923406.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1698992.62
      sim_grid_pos_y: 923212.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1698853.75
      sim_grid_pos_y: 922941.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1698510.12
      sim_grid_pos_y: 922751.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1698381.62
      sim_grid_pos_y: 923170.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1698383.25
      sim_grid_pos_y: 923303.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698357.38
      sim_grid_pos_y: 923323.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1698272.75
      sim_grid_pos_y: 923246.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1697884.12
      sim_grid_pos_y: 923250.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1697701.75
      sim_grid_pos_y: 923582
    }
    terrain_level_point {
      sim_grid_pos_x: 1697859.38
      sim_grid_pos_y: 923854.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1698113.12
      sim_grid_pos_y: 923993.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1698297
      sim_grid_pos_y: 923994.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698595.62
      sim_grid_pos_y: 923955.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1699039.25
      sim_grid_pos_y: 923793.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1699084.5
      sim_grid_pos_y: 923414.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1699096.5
      sim_grid_pos_y: 923190.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1698923.75
      sim_grid_pos_y: 922852.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1698440.5
      sim_grid_pos_y: 922628.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1698282.5
      sim_grid_pos_y: 923144.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1697823.25
      sim_grid_pos_y: 923149
    }
    terrain_level_point {
      sim_grid_pos_x: 1697584
      sim_grid_pos_y: 923583.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1697785
      sim_grid_pos_y: 923930.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1698086.5
      sim_grid_pos_y: 924096.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1698303.38
      sim_grid_pos_y: 924097.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1698620.12
      sim_grid_pos_y: 924055.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1699133.62
      sim_grid_pos_y: 923868.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1699186.62
      sim_grid_pos_y: 923423.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1699200.38
      sim_grid_pos_y: 923168.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1698993.62
      sim_grid_pos_y: 922764.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1698370.88
      sim_grid_pos_y: 922506.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1698206.38
      sim_grid_pos_y: 923042.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1697762.25
      sim_grid_pos_y: 923047.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1697466.25
      sim_grid_pos_y: 923584.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1697710.5
      sim_grid_pos_y: 924006.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1698059.88
      sim_grid_pos_y: 924198.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1698309.88
      sim_grid_pos_y: 924199.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1698644.62
      sim_grid_pos_y: 924155.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1699227.88
      sim_grid_pos_y: 923943.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1699288.88
      sim_grid_pos_y: 923432.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1699304.12
      sim_grid_pos_y: 923146.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1699063.62
      sim_grid_pos_y: 922675.938
    }
  }
}
terrain_level_data {
  terrain_level: 80
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1696185.62
      sim_grid_pos_y: 925905.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1695766.38
      sim_grid_pos_y: 926271.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1695781.88
      sim_grid_pos_y: 926665
    }
    terrain_level_point {
      sim_grid_pos_x: 1696078.75
      sim_grid_pos_y: 926629.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1696098.75
      sim_grid_pos_y: 926250.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1696269
      sim_grid_pos_y: 925967.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1696183.12
      sim_grid_pos_y: 925839.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1695714.25
      sim_grid_pos_y: 926248.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1695732.88
      sim_grid_pos_y: 926722.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1696127.75
      sim_grid_pos_y: 926674.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1696149.25
      sim_grid_pos_y: 926265.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1696336.88
      sim_grid_pos_y: 925954.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1696180.62
      sim_grid_pos_y: 925773.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1695662
      sim_grid_pos_y: 926226.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1695683.88
      sim_grid_pos_y: 926780.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1696176.62
      sim_grid_pos_y: 926720.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1696199.75
      sim_grid_pos_y: 926281
    }
    terrain_level_point {
      sim_grid_pos_x: 1696404.75
      sim_grid_pos_y: 925940.875
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1696178.12
      sim_grid_pos_y: 925707.875
    }
    terrain_level_point {
      sim_grid_pos_x: 1695609.88
      sim_grid_pos_y: 926203.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1695634.75
      sim_grid_pos_y: 926837.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1696225.62
      sim_grid_pos_y: 926766.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1696250.25
      sim_grid_pos_y: 926296.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1696472.62
      sim_grid_pos_y: 925927.562
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1696175.62
      sim_grid_pos_y: 925642.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1695557.62
      sim_grid_pos_y: 926181.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1695585.75
      sim_grid_pos_y: 926895.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1696274.5
      sim_grid_pos_y: 926812.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1696300.75
      sim_grid_pos_y: 926312
    }
    terrain_level_point {
      sim_grid_pos_x: 1696540.5
      sim_grid_pos_y: 925914.25
    }
  }
}
terrain_level_data {
  terrain_level: 220
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1700102.38
      sim_grid_pos_y: 925260.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1699710.62
      sim_grid_pos_y: 925466.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1699452.5
      sim_grid_pos_y: 925347.125
    }
    terrain_level_point {
      sim_grid_pos_x: 1699635.88
      sim_grid_pos_y: 925126.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1700022.75
      sim_grid_pos_y: 925045.375
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1700166
      sim_grid_pos_y: 925285.062
    }
    terrain_level_point {
      sim_grid_pos_x: 1699712.12
      sim_grid_pos_y: 925523.375
    }
    terrain_level_point {
      sim_grid_pos_x: 1699370.25
      sim_grid_pos_y: 925365.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1699608
      sim_grid_pos_y: 925080.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1700055.5
      sim_grid_pos_y: 924986.125
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1700229.75
      sim_grid_pos_y: 925309.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1699713.5
      sim_grid_pos_y: 925580.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1699288.12
      sim_grid_pos_y: 925384.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1.69958e+06
      sim_grid_pos_y: 925033.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1700088.25
      sim_grid_pos_y: 924926.812
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1700293.38
      sim_grid_pos_y: 925334
    }
    terrain_level_point {
      sim_grid_pos_x: 1699715
      sim_grid_pos_y: 925637.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1699206
      sim_grid_pos_y: 925402.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1699552
      sim_grid_pos_y: 924987.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1700121
      sim_grid_pos_y: 924867.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1700357.12
      sim_grid_pos_y: 925358.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1699716.5
      sim_grid_pos_y: 925694.812
    }
    terrain_level_point {
      sim_grid_pos_x: 1699123.75
      sim_grid_pos_y: 925421.188
    }
    terrain_level_point {
      sim_grid_pos_x: 1699524
      sim_grid_pos_y: 924941
    }
    terrain_level_point {
      sim_grid_pos_x: 1700153.75
      sim_grid_pos_y: 924808.25
    }
  }
}
