terrain_level_data {
  terrain_level: 48
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1332128
      sim_grid_pos_y: 1473369.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1335679.75
      sim_grid_pos_y: 1471048.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1336769.88
      sim_grid_pos_y: 1471018.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1338247.25
      sim_grid_pos_y: 1471628.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1338833.88
      sim_grid_pos_y: 1471432.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1342205.12
      sim_grid_pos_y: 1468183.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1344066.38
      sim_grid_pos_y: 1470176.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1340309.12
      sim_grid_pos_y: 1473826.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1340734.5
      sim_grid_pos_y: 1474217.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1340419.5
      sim_grid_pos_y: 1474623.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1343067.38
      sim_grid_pos_y: 1477358.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1342409.62
      sim_grid_pos_y: 1477999
    }
    terrain_level_point {
      sim_grid_pos_x: 1340022.25
      sim_grid_pos_y: 1478688.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1337652.88
      sim_grid_pos_y: 1479273.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1335276.5
      sim_grid_pos_y: 1481667.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1331765.5
      sim_grid_pos_y: 1481581
    }
    terrain_level_point {
      sim_grid_pos_x: 1331597.12
      sim_grid_pos_y: 1481117
    }
    terrain_level_point {
      sim_grid_pos_x: 1332447.62
      sim_grid_pos_y: 1480285.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1331913.75
      sim_grid_pos_y: 1479460.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331805
      sim_grid_pos_y: 1479230.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1331767.5
      sim_grid_pos_y: 1477786.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1331196.62
      sim_grid_pos_y: 1477083
    }
    terrain_level_point {
      sim_grid_pos_x: 1331167.12
      sim_grid_pos_y: 1476331.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1331278.12
      sim_grid_pos_y: 1476059.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1331157.75
      sim_grid_pos_y: 1475720.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1331641
      sim_grid_pos_y: 1474571.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1331703
      sim_grid_pos_y: 1473533.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1344209.88
      sim_grid_pos_y: 1470179.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1340458.38
      sim_grid_pos_y: 1473824.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1340873.38
      sim_grid_pos_y: 1474206.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1340555
      sim_grid_pos_y: 1474615.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1343212.12
      sim_grid_pos_y: 1477360.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1342462.75
      sim_grid_pos_y: 1478090.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1340048.75
      sim_grid_pos_y: 1478787.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1337705.38
      sim_grid_pos_y: 1479366
    }
    terrain_level_point {
      sim_grid_pos_x: 1335318.12
      sim_grid_pos_y: 1481771
    }
    terrain_level_point {
      sim_grid_pos_x: 1331693
      sim_grid_pos_y: 1481681.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1331478.25
      sim_grid_pos_y: 1481089.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1332316
      sim_grid_pos_y: 1480270.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1331824
      sim_grid_pos_y: 1479510.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331703.12
      sim_grid_pos_y: 1479254.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1331665.88
      sim_grid_pos_y: 1477824
    }
    terrain_level_point {
      sim_grid_pos_x: 1331095.5
      sim_grid_pos_y: 1477121.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1331063.75
      sim_grid_pos_y: 1476313.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1331168.38
      sim_grid_pos_y: 1476056.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331047.88
      sim_grid_pos_y: 1475717.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331539.75
      sim_grid_pos_y: 1474547.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1331604.62
      sim_grid_pos_y: 1473461.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1332081
      sim_grid_pos_y: 1473277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1335648
      sim_grid_pos_y: 1470946.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1336788.88
      sim_grid_pos_y: 1470915.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1338251
      sim_grid_pos_y: 1471519.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1338779.38
      sim_grid_pos_y: 1471342.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1342209
      sim_grid_pos_y: 1468037.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1344353.5
      sim_grid_pos_y: 1470183.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1340607.62
      sim_grid_pos_y: 1473822.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1341012.25
      sim_grid_pos_y: 1474194.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1340690.62
      sim_grid_pos_y: 1474608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1343356.88
      sim_grid_pos_y: 1477363.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1342515.88
      sim_grid_pos_y: 1478181.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1340075.25
      sim_grid_pos_y: 1478886.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1337757.88
      sim_grid_pos_y: 1479458.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1335359.75
      sim_grid_pos_y: 1481874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1331620.5
      sim_grid_pos_y: 1481782.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1331359.25
      sim_grid_pos_y: 1481062.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1332184.38
      sim_grid_pos_y: 1480256.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1331734.12
      sim_grid_pos_y: 1479560.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1331601.12
      sim_grid_pos_y: 1479278.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1331564.38
      sim_grid_pos_y: 1477861.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1330994.38
      sim_grid_pos_y: 1477159.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1330960.5
      sim_grid_pos_y: 1476294.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1331058.75
      sim_grid_pos_y: 1476054.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1330937.88
      sim_grid_pos_y: 1475714.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1331438.38
      sim_grid_pos_y: 1474524.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1331506.12
      sim_grid_pos_y: 1473389.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1332034
      sim_grid_pos_y: 1473185.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1335616.12
      sim_grid_pos_y: 1470845
    }
    terrain_level_point {
      sim_grid_pos_x: 1336807.88
      sim_grid_pos_y: 1470812.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1338254.88
      sim_grid_pos_y: 1.47141e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1338725
      sim_grid_pos_y: 1471253
    }
    terrain_level_point {
      sim_grid_pos_x: 1342212.75
      sim_grid_pos_y: 1467891.62
    }
  }
}
