terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 316092.188
      sim_grid_pos_y: 1338755.62
    }
    terrain_level_point {
      sim_grid_pos_x: 314078.5
      sim_grid_pos_y: 1337597.88
    }
    terrain_level_point {
      sim_grid_pos_x: 313004.531
      sim_grid_pos_y: 1339654.25
    }
    terrain_level_point {
      sim_grid_pos_x: 312954.781
      sim_grid_pos_y: 1339928.5
    }
    terrain_level_point {
      sim_grid_pos_x: 312874.344
      sim_grid_pos_y: 1340072
    }
    terrain_level_point {
      sim_grid_pos_x: 312977.25
      sim_grid_pos_y: 1340116.12
    }
    terrain_level_point {
      sim_grid_pos_x: 312748.781
      sim_grid_pos_y: 1340541.75
    }
    terrain_level_point {
      sim_grid_pos_x: 312587.656
      sim_grid_pos_y: 1340444.75
    }
    terrain_level_point {
      sim_grid_pos_x: 310547.281
      sim_grid_pos_y: 1344392
    }
    terrain_level_point {
      sim_grid_pos_x: 312205.844
      sim_grid_pos_y: 1345292.12
    }
    terrain_level_point {
      sim_grid_pos_x: 312548.094
      sim_grid_pos_y: 1345910.75
    }
    terrain_level_point {
      sim_grid_pos_x: 314505.062
      sim_grid_pos_y: 1345406.75
    }
    terrain_level_point {
      sim_grid_pos_x: 314494.781
      sim_grid_pos_y: 1344582.12
    }
    terrain_level_point {
      sim_grid_pos_x: 314183.312
      sim_grid_pos_y: 1344326.25
    }
    terrain_level_point {
      sim_grid_pos_x: 313426.156
      sim_grid_pos_y: 1343906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 313826.188
      sim_grid_pos_y: 1343258.38
    }
    terrain_level_point {
      sim_grid_pos_x: 314175.031
      sim_grid_pos_y: 1343157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 314499.375
      sim_grid_pos_y: 1342384.88
    }
    terrain_level_point {
      sim_grid_pos_x: 314619.844
      sim_grid_pos_y: 1341950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 314457.75
      sim_grid_pos_y: 1341822.75
    }
    terrain_level_point {
      sim_grid_pos_x: 314892.188
      sim_grid_pos_y: 1340990.62
    }
    terrain_level_point {
      sim_grid_pos_x: 315074.719
      sim_grid_pos_y: 1341032
    }
    terrain_level_point {
      sim_grid_pos_x: 315281.094
      sim_grid_pos_y: 1340809.62
    }
    terrain_level_point {
      sim_grid_pos_x: 315428.25
      sim_grid_pos_y: 1340511.12
    }
    terrain_level_point {
      sim_grid_pos_x: 315197.781
      sim_grid_pos_y: 1340397.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 314066.062
      sim_grid_pos_y: 1337555.25
    }
    terrain_level_point {
      sim_grid_pos_x: 312975.094
      sim_grid_pos_y: 1339644.12
    }
    terrain_level_point {
      sim_grid_pos_x: 312925.406
      sim_grid_pos_y: 1339918
    }
    terrain_level_point {
      sim_grid_pos_x: 312830.781
      sim_grid_pos_y: 1340086.88
    }
    terrain_level_point {
      sim_grid_pos_x: 312934.25
      sim_grid_pos_y: 1340131.12
    }
    terrain_level_point {
      sim_grid_pos_x: 312736.969
      sim_grid_pos_y: 1340498.75
    }
    terrain_level_point {
      sim_grid_pos_x: 312575.375
      sim_grid_pos_y: 1340401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 310506.125
      sim_grid_pos_y: 1344404.62
    }
    terrain_level_point {
      sim_grid_pos_x: 312183.281
      sim_grid_pos_y: 1345314.88
    }
    terrain_level_point {
      sim_grid_pos_x: 312532.688
      sim_grid_pos_y: 1345946.38
    }
    terrain_level_point {
      sim_grid_pos_x: 314536.094
      sim_grid_pos_y: 1345430.5
    }
    terrain_level_point {
      sim_grid_pos_x: 314525.344
      sim_grid_pos_y: 1344567.38
    }
    terrain_level_point {
      sim_grid_pos_x: 314200.688
      sim_grid_pos_y: 1344300.75
    }
    terrain_level_point {
      sim_grid_pos_x: 313469.25
      sim_grid_pos_y: 1343895.5
    }
    terrain_level_point {
      sim_grid_pos_x: 313846.156
      sim_grid_pos_y: 1343284.62
    }
    terrain_level_point {
      sim_grid_pos_x: 314197.719
      sim_grid_pos_y: 1343182.62
    }
    terrain_level_point {
      sim_grid_pos_x: 314528.5
      sim_grid_pos_y: 1342395
    }
    terrain_level_point {
      sim_grid_pos_x: 314654.938
      sim_grid_pos_y: 1341938.75
    }
    terrain_level_point {
      sim_grid_pos_x: 314496.844
      sim_grid_pos_y: 1341814.38
    }
    terrain_level_point {
      sim_grid_pos_x: 314908.5
      sim_grid_pos_y: 1341025.88
    }
    terrain_level_point {
      sim_grid_pos_x: 315085.188
      sim_grid_pos_y: 1341065.88
    }
    terrain_level_point {
      sim_grid_pos_x: 315306.688
      sim_grid_pos_y: 1340827.25
    }
    terrain_level_point {
      sim_grid_pos_x: 315469.438
      sim_grid_pos_y: 1340497.12
    }
    terrain_level_point {
      sim_grid_pos_x: 315240.125
      sim_grid_pos_y: 1340384.12
    }
    terrain_level_point {
      sim_grid_pos_x: 316133.562
      sim_grid_pos_y: 1338743.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 314053.625
      sim_grid_pos_y: 1337512.62
    }
    terrain_level_point {
      sim_grid_pos_x: 312945.688
      sim_grid_pos_y: 1339634
    }
    terrain_level_point {
      sim_grid_pos_x: 312896.062
      sim_grid_pos_y: 1339907.38
    }
    terrain_level_point {
      sim_grid_pos_x: 312787.25
      sim_grid_pos_y: 1340101.62
    }
    terrain_level_point {
      sim_grid_pos_x: 312891.281
      sim_grid_pos_y: 1340146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 312725.125
      sim_grid_pos_y: 1340455.75
    }
    terrain_level_point {
      sim_grid_pos_x: 312563.125
      sim_grid_pos_y: 1340358.25
    }
    terrain_level_point {
      sim_grid_pos_x: 310464.969
      sim_grid_pos_y: 1344417.38
    }
    terrain_level_point {
      sim_grid_pos_x: 312160.719
      sim_grid_pos_y: 1345337.62
    }
    terrain_level_point {
      sim_grid_pos_x: 312517.312
      sim_grid_pos_y: 1345982.12
    }
    terrain_level_point {
      sim_grid_pos_x: 314567.156
      sim_grid_pos_y: 1345454.25
    }
    terrain_level_point {
      sim_grid_pos_x: 314555.938
      sim_grid_pos_y: 1344552.62
    }
    terrain_level_point {
      sim_grid_pos_x: 314218.031
      sim_grid_pos_y: 1344275.25
    }
    terrain_level_point {
      sim_grid_pos_x: 313512.344
      sim_grid_pos_y: 1343884.12
    }
    terrain_level_point {
      sim_grid_pos_x: 313866.094
      sim_grid_pos_y: 1343310.88
    }
    terrain_level_point {
      sim_grid_pos_x: 314220.375
      sim_grid_pos_y: 1343208
    }
    terrain_level_point {
      sim_grid_pos_x: 314557.594
      sim_grid_pos_y: 1342405.12
    }
    terrain_level_point {
      sim_grid_pos_x: 314690.062
      sim_grid_pos_y: 1341927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 314535.906
      sim_grid_pos_y: 1341806
    }
    terrain_level_point {
      sim_grid_pos_x: 314924.781
      sim_grid_pos_y: 1341061.12
    }
    terrain_level_point {
      sim_grid_pos_x: 315095.688
      sim_grid_pos_y: 1341099.88
    }
    terrain_level_point {
      sim_grid_pos_x: 315332.281
      sim_grid_pos_y: 1340844.88
    }
    terrain_level_point {
      sim_grid_pos_x: 315510.625
      sim_grid_pos_y: 1340483.12
    }
    terrain_level_point {
      sim_grid_pos_x: 315282.469
      sim_grid_pos_y: 1340370.62
    }
    terrain_level_point {
      sim_grid_pos_x: 316174.969
      sim_grid_pos_y: 1338732.25
    }
  }
}
terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 317186
      sim_grid_pos_y: 1339242.62
    }
    terrain_level_point {
      sim_grid_pos_x: 314037.406
      sim_grid_pos_y: 1337530.62
    }
    terrain_level_point {
      sim_grid_pos_x: 310124.719
      sim_grid_pos_y: 1345095.38
    }
    terrain_level_point {
      sim_grid_pos_x: 309973.531
      sim_grid_pos_y: 1345041
    }
    terrain_level_point {
      sim_grid_pos_x: 313984.875
      sim_grid_pos_y: 1337367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 317256.156
      sim_grid_pos_y: 1339040.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 317294
      sim_grid_pos_y: 1339025
    }
    terrain_level_point {
      sim_grid_pos_x: 317203.188
      sim_grid_pos_y: 1339287
    }
    terrain_level_point {
      sim_grid_pos_x: 314050.281
      sim_grid_pos_y: 1337572.62
    }
    terrain_level_point {
      sim_grid_pos_x: 310139.688
      sim_grid_pos_y: 1345133.5
    }
    terrain_level_point {
      sim_grid_pos_x: 309929.906
      sim_grid_pos_y: 1345058
    }
    terrain_level_point {
      sim_grid_pos_x: 313971.75
      sim_grid_pos_y: 1337326.5
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 318366.469
      sim_grid_pos_y: 1341002.5
    }
    terrain_level_point {
      sim_grid_pos_x: 317990.188
      sim_grid_pos_y: 1341302.5
    }
    terrain_level_point {
      sim_grid_pos_x: 319786.781
      sim_grid_pos_y: 1343508.62
    }
    terrain_level_point {
      sim_grid_pos_x: 319122.781
      sim_grid_pos_y: 1343545
    }
    terrain_level_point {
      sim_grid_pos_x: 319170.156
      sim_grid_pos_y: 1343625.62
    }
    terrain_level_point {
      sim_grid_pos_x: 319180.5
      sim_grid_pos_y: 1344326.25
    }
    terrain_level_point {
      sim_grid_pos_x: 319853.562
      sim_grid_pos_y: 1344378.62
    }
    terrain_level_point {
      sim_grid_pos_x: 320207.094
      sim_grid_pos_y: 1344345.5
    }
    terrain_level_point {
      sim_grid_pos_x: 320410.406
      sim_grid_pos_y: 1344391.62
    }
    terrain_level_point {
      sim_grid_pos_x: 321216.812
      sim_grid_pos_y: 1345366.62
    }
    terrain_level_point {
      sim_grid_pos_x: 321489.688
      sim_grid_pos_y: 1346151.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322381.906
      sim_grid_pos_y: 1347582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322996.688
      sim_grid_pos_y: 1347282.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322488
      sim_grid_pos_y: 1346548.62
    }
    terrain_level_point {
      sim_grid_pos_x: 323060.375
      sim_grid_pos_y: 1346023.5
    }
    terrain_level_point {
      sim_grid_pos_x: 323531.062
      sim_grid_pos_y: 1345510.12
    }
    terrain_level_point {
      sim_grid_pos_x: 323503.375
      sim_grid_pos_y: 1345314.12
    }
    terrain_level_point {
      sim_grid_pos_x: 323421.094
      sim_grid_pos_y: 1345169.62
    }
    terrain_level_point {
      sim_grid_pos_x: 323186.969
      sim_grid_pos_y: 1345321
    }
    terrain_level_point {
      sim_grid_pos_x: 323111.719
      sim_grid_pos_y: 1345281.75
    }
    terrain_level_point {
      sim_grid_pos_x: 323079.594
      sim_grid_pos_y: 1345309.12
    }
    terrain_level_point {
      sim_grid_pos_x: 323014.031
      sim_grid_pos_y: 1345208
    }
    terrain_level_point {
      sim_grid_pos_x: 322964.688
      sim_grid_pos_y: 1345197.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322891.781
      sim_grid_pos_y: 1345261.75
    }
    terrain_level_point {
      sim_grid_pos_x: 322861.531
      sim_grid_pos_y: 1345217.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322752.344
      sim_grid_pos_y: 1345312.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322717.062
      sim_grid_pos_y: 1345305.38
    }
    terrain_level_point {
      sim_grid_pos_x: 322342.438
      sim_grid_pos_y: 1345020.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322424.719
      sim_grid_pos_y: 1344972.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322380.531
      sim_grid_pos_y: 1344788.75
    }
    terrain_level_point {
      sim_grid_pos_x: 322237.812
      sim_grid_pos_y: 1344740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322133.469
      sim_grid_pos_y: 1344231.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322049.625
      sim_grid_pos_y: 1344236.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322013.562
      sim_grid_pos_y: 1344151.75
    }
    terrain_level_point {
      sim_grid_pos_x: 322183.625
      sim_grid_pos_y: 1343786.88
    }
    terrain_level_point {
      sim_grid_pos_x: 322162.469
      sim_grid_pos_y: 1343371.12
    }
    terrain_level_point {
      sim_grid_pos_x: 321995.938
      sim_grid_pos_y: 1343349.5
    }
    terrain_level_point {
      sim_grid_pos_x: 321958.156
      sim_grid_pos_y: 1343386.12
    }
    terrain_level_point {
      sim_grid_pos_x: 321969.219
      sim_grid_pos_y: 1343472.75
    }
    terrain_level_point {
      sim_grid_pos_x: 321960.906
      sim_grid_pos_y: 1344128.75
    }
    terrain_level_point {
      sim_grid_pos_x: 320465.594
      sim_grid_pos_y: 1343538.12
    }
    terrain_level_point {
      sim_grid_pos_x: 320512.969
      sim_grid_pos_y: 1343382.62
    }
    terrain_level_point {
      sim_grid_pos_x: 320431.5
      sim_grid_pos_y: 1343076.38
    }
    terrain_level_point {
      sim_grid_pos_x: 320277.125
      sim_grid_pos_y: 1343036.12
    }
    terrain_level_point {
      sim_grid_pos_x: 320089.062
      sim_grid_pos_y: 1342927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 319923.312
      sim_grid_pos_y: 1342940.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 318371.25
      sim_grid_pos_y: 1340959.38
    }
    terrain_level_point {
      sim_grid_pos_x: 317946.719
      sim_grid_pos_y: 1341297.88
    }
    terrain_level_point {
      sim_grid_pos_x: 319724.781
      sim_grid_pos_y: 1343481.12
    }
    terrain_level_point {
      sim_grid_pos_x: 319070.656
      sim_grid_pos_y: 1343517.12
    }
    terrain_level_point {
      sim_grid_pos_x: 319139.531
      sim_grid_pos_y: 1343634.12
    }
    terrain_level_point {
      sim_grid_pos_x: 319150.156
      sim_grid_pos_y: 1344354.75
    }
    terrain_level_point {
      sim_grid_pos_x: 319853.812
      sim_grid_pos_y: 1344409.5
    }
    terrain_level_point {
      sim_grid_pos_x: 320205.062
      sim_grid_pos_y: 1344376.62
    }
    terrain_level_point {
      sim_grid_pos_x: 320393.406
      sim_grid_pos_y: 1344419.25
    }
    terrain_level_point {
      sim_grid_pos_x: 321189.562
      sim_grid_pos_y: 1345382
    }
    terrain_level_point {
      sim_grid_pos_x: 321461.75
      sim_grid_pos_y: 1346164.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322370.469
      sim_grid_pos_y: 1347622
    }
    terrain_level_point {
      sim_grid_pos_x: 323042.406
      sim_grid_pos_y: 1347294.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322528.562
      sim_grid_pos_y: 1346553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 323082.156
      sim_grid_pos_y: 1346045.25
    }
    terrain_level_point {
      sim_grid_pos_x: 323563.562
      sim_grid_pos_y: 1345520.25
    }
    terrain_level_point {
      sim_grid_pos_x: 323533
      sim_grid_pos_y: 1345304.12
    }
    terrain_level_point {
      sim_grid_pos_x: 323431.719
      sim_grid_pos_y: 1345126.12
    }
    terrain_level_point {
      sim_grid_pos_x: 323185.312
      sim_grid_pos_y: 1345285.5
    }
    terrain_level_point {
      sim_grid_pos_x: 323107.562
      sim_grid_pos_y: 1345244.88
    }
    terrain_level_point {
      sim_grid_pos_x: 323086.312
      sim_grid_pos_y: 1345263
    }
    terrain_level_point {
      sim_grid_pos_x: 323032.875
      sim_grid_pos_y: 1345180.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322955.969
      sim_grid_pos_y: 1345164.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322897.594
      sim_grid_pos_y: 1345215.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322867.5
      sim_grid_pos_y: 1345171.38
    }
    terrain_level_point {
      sim_grid_pos_x: 322743.469
      sim_grid_pos_y: 1345279.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322729.969
      sim_grid_pos_y: 1345276.5
    }
    terrain_level_point {
      sim_grid_pos_x: 322397.625
      sim_grid_pos_y: 1345023.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322460
      sim_grid_pos_y: 1344987.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322406.469
      sim_grid_pos_y: 1344765
    }
    terrain_level_point {
      sim_grid_pos_x: 322264.375
      sim_grid_pos_y: 1344717.12
    }
    terrain_level_point {
      sim_grid_pos_x: 322158.25
      sim_grid_pos_y: 1344199.38
    }
    terrain_level_point {
      sim_grid_pos_x: 322069.469
      sim_grid_pos_y: 1344204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 322047.219
      sim_grid_pos_y: 1344152.25
    }
    terrain_level_point {
      sim_grid_pos_x: 322214.75
      sim_grid_pos_y: 1343793
    }
    terrain_level_point {
      sim_grid_pos_x: 322191.875
      sim_grid_pos_y: 1343344
    }
    terrain_level_point {
      sim_grid_pos_x: 321985.156
      sim_grid_pos_y: 1343317
    }
    terrain_level_point {
      sim_grid_pos_x: 321925.719
      sim_grid_pos_y: 1343374.88
    }
    terrain_level_point {
      sim_grid_pos_x: 321938.438
      sim_grid_pos_y: 1343474.5
    }
    terrain_level_point {
      sim_grid_pos_x: 321930.719
      sim_grid_pos_y: 1344083.75
    }
    terrain_level_point {
      sim_grid_pos_x: 320503.281
      sim_grid_pos_y: 1.34352e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 320544.938
      sim_grid_pos_y: 1343383.25
    }
    terrain_level_point {
      sim_grid_pos_x: 320456.594
      sim_grid_pos_y: 1343051.12
    }
    terrain_level_point {
      sim_grid_pos_x: 320288.969
      sim_grid_pos_y: 1343007.5
    }
    terrain_level_point {
      sim_grid_pos_x: 320096.156
      sim_grid_pos_y: 1342895.62
    }
    terrain_level_point {
      sim_grid_pos_x: 319937.062
      sim_grid_pos_y: 1342908.5
    }
  }
}
