terrain_level_data {
  terrain_level: 393
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1113724.12
      sim_grid_pos_y: 1407532.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1113645.12
      sim_grid_pos_y: 1407885.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1113558.25
      sim_grid_pos_y: 1408254.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1113775.5
      sim_grid_pos_y: 1408359.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1113868.25
      sim_grid_pos_y: 1408191.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1113922.62
      sim_grid_pos_y: 1407925.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1114542.25
      sim_grid_pos_y: 1407744.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1114354.38
      sim_grid_pos_y: 1.40722e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1114412.12
      sim_grid_pos_y: 1407077
    }
    terrain_level_point {
      sim_grid_pos_x: 1113634.75
      sim_grid_pos_y: 1407462.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1113545.12
      sim_grid_pos_y: 1407863
    }
    terrain_level_point {
      sim_grid_pos_x: 1113439.62
      sim_grid_pos_y: 1408310.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1113818.25
      sim_grid_pos_y: 1408494.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1113965.62
      sim_grid_pos_y: 1408226.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1114010.62
      sim_grid_pos_y: 1408006.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1114675.5
      sim_grid_pos_y: 1407812.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1114469.75
      sim_grid_pos_y: 1406933.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1113545.38
      sim_grid_pos_y: 1407392.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1113445.38
      sim_grid_pos_y: 1407839
    }
    terrain_level_point {
      sim_grid_pos_x: 1113321
      sim_grid_pos_y: 1408367
    }
    terrain_level_point {
      sim_grid_pos_x: 1113861.12
      sim_grid_pos_y: 1408629
    }
    terrain_level_point {
      sim_grid_pos_x: 1114063
      sim_grid_pos_y: 1408262.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1114098.75
      sim_grid_pos_y: 1408087.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1114808.75
      sim_grid_pos_y: 1407880.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1114527.38
      sim_grid_pos_y: 1406790.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1113456
      sim_grid_pos_y: 1407322.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1113345.25
      sim_grid_pos_y: 1407816.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1113202.38
      sim_grid_pos_y: 1408423.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1113904
      sim_grid_pos_y: 1408763.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1114160.25
      sim_grid_pos_y: 1408298.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1114186.88
      sim_grid_pos_y: 1408168.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1114942
      sim_grid_pos_y: 1407948.75
    }
  }
}
