terrain_level_data {
  terrain_level: 1080
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1528384.38
      sim_grid_pos_y: 1886682
    }
    terrain_level_point {
      sim_grid_pos_x: 1528175.12
      sim_grid_pos_y: 1886593
    }
    terrain_level_point {
      sim_grid_pos_x: 1527733.88
      sim_grid_pos_y: 1886592.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1527744
      sim_grid_pos_y: 1887240.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1527238.12
      sim_grid_pos_y: 1888062.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1527319.25
      sim_grid_pos_y: 1888414.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1527269
      sim_grid_pos_y: 1888737.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1527788
      sim_grid_pos_y: 1888895.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527939.38
      sim_grid_pos_y: 1888626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528142.88
      sim_grid_pos_y: 1888487.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528342.38
      sim_grid_pos_y: 1888462.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528388.5
      sim_grid_pos_y: 1888291.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528126
      sim_grid_pos_y: 1888280.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528008.5
      sim_grid_pos_y: 1888210.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1528130.38
      sim_grid_pos_y: 1887848.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528354.62
      sim_grid_pos_y: 1887758.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1527702.62
      sim_grid_pos_y: 1886561.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527713.12
      sim_grid_pos_y: 1887232.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1527205.25
      sim_grid_pos_y: 1888057.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1527288
      sim_grid_pos_y: 1888415.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1527234.5
      sim_grid_pos_y: 1888758.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1527802.75
      sim_grid_pos_y: 1888932.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1527962.62
      sim_grid_pos_y: 1888647.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528154.12
      sim_grid_pos_y: 1888517
    }
    terrain_level_point {
      sim_grid_pos_x: 1528366.62
      sim_grid_pos_y: 1888490.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528428.25
      sim_grid_pos_y: 1888262.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528135
      sim_grid_pos_y: 1888250.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1528045.5
      sim_grid_pos_y: 1888196.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528155
      sim_grid_pos_y: 1887872
    }
    terrain_level_point {
      sim_grid_pos_x: 1528384.88
      sim_grid_pos_y: 1887779.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528415.75
      sim_grid_pos_y: 1886662
    }
    terrain_level_point {
      sim_grid_pos_x: 1528181.5
      sim_grid_pos_y: 1886562.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1527671.38
      sim_grid_pos_y: 1886531
    }
    terrain_level_point {
      sim_grid_pos_x: 1527682.25
      sim_grid_pos_y: 1887223.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527172.5
      sim_grid_pos_y: 1888052.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1527256.75
      sim_grid_pos_y: 1888416.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.5272e+06
      sim_grid_pos_y: 1888780.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1527817.38
      sim_grid_pos_y: 1888969
    }
    terrain_level_point {
      sim_grid_pos_x: 1527985.88
      sim_grid_pos_y: 1888669.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528165.38
      sim_grid_pos_y: 1888546.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528391
      sim_grid_pos_y: 1888518.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528467.88
      sim_grid_pos_y: 1888233.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528144.12
      sim_grid_pos_y: 1888219.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528082.62
      sim_grid_pos_y: 1888183
    }
    terrain_level_point {
      sim_grid_pos_x: 1528179.62
      sim_grid_pos_y: 1887895.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528415
      sim_grid_pos_y: 1887800.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528447
      sim_grid_pos_y: 1886641.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528187.75
      sim_grid_pos_y: 1886531.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1527640.12
      sim_grid_pos_y: 1886500.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1527651.25
      sim_grid_pos_y: 1887215.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1527139.62
      sim_grid_pos_y: 1888046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527225.38
      sim_grid_pos_y: 1888417.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1527165.5
      sim_grid_pos_y: 1888802.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1527832.12
      sim_grid_pos_y: 1889005.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528009.25
      sim_grid_pos_y: 1888690.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528176.5
      sim_grid_pos_y: 1888576.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528415.25
      sim_grid_pos_y: 1888546.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1528507.62
      sim_grid_pos_y: 1888204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528153.25
      sim_grid_pos_y: 1888189.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1528119.62
      sim_grid_pos_y: 1888169.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528204.25
      sim_grid_pos_y: 1887918.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528445.25
      sim_grid_pos_y: 1887821.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528478.38
      sim_grid_pos_y: 1886621.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528194
      sim_grid_pos_y: 1886500.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1527608.88
      sim_grid_pos_y: 1886469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1527620.38
      sim_grid_pos_y: 1887206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527106.88
      sim_grid_pos_y: 1888041.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1527194.12
      sim_grid_pos_y: 1888418.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527131
      sim_grid_pos_y: 1888823.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1527846.75
      sim_grid_pos_y: 1889042.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528032.5
      sim_grid_pos_y: 1888711.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528187.75
      sim_grid_pos_y: 1888605.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528439.5
      sim_grid_pos_y: 1888574.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1528547.38
      sim_grid_pos_y: 1888175.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528162.38
      sim_grid_pos_y: 1888159
    }
    terrain_level_point {
      sim_grid_pos_x: 1528156.75
      sim_grid_pos_y: 1888155.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528228.88
      sim_grid_pos_y: 1887941.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528475.38
      sim_grid_pos_y: 1887842.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528509.62
      sim_grid_pos_y: 1886601.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528200.25
      sim_grid_pos_y: 1886470.12
    }
  }
}
terrain_level_data {
  terrain_level: 1120
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1528580.38
      sim_grid_pos_y: 1886725
    }
    terrain_level_point {
      sim_grid_pos_x: 1528823.75
      sim_grid_pos_y: 1886728.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1529032.62
      sim_grid_pos_y: 1886803.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1529249.12
      sim_grid_pos_y: 1887028
    }
    terrain_level_point {
      sim_grid_pos_x: 1529074
      sim_grid_pos_y: 1887259.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528854
      sim_grid_pos_y: 1887235.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528691.5
      sim_grid_pos_y: 1887090.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528608.75
      sim_grid_pos_y: 1887033.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1528542.62
      sim_grid_pos_y: 1886923
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1528829.38
      sim_grid_pos_y: 1886698
    }
    terrain_level_point {
      sim_grid_pos_x: 1529049.75
      sim_grid_pos_y: 1886777.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1529289.62
      sim_grid_pos_y: 1887025.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1529088
      sim_grid_pos_y: 1887292.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528840.88
      sim_grid_pos_y: 1887265.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1528672.38
      sim_grid_pos_y: 1887114.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528585.88
      sim_grid_pos_y: 1887055.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1528510.12
      sim_grid_pos_y: 1886928.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528555
      sim_grid_pos_y: 1886693.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1528835
      sim_grid_pos_y: 1886667.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1529066.88
      sim_grid_pos_y: 1886750.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1.52933e+06
      sim_grid_pos_y: 1887023.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1529102
      sim_grid_pos_y: 1887324.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1528827.75
      sim_grid_pos_y: 1887294.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1528653.5
      sim_grid_pos_y: 1887139
    }
    terrain_level_point {
      sim_grid_pos_x: 1528562.88
      sim_grid_pos_y: 1887077
    }
    terrain_level_point {
      sim_grid_pos_x: 1528477.75
      sim_grid_pos_y: 1886934.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528529.62
      sim_grid_pos_y: 1886662.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1528840.62
      sim_grid_pos_y: 1886636.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1529084
      sim_grid_pos_y: 1886724.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1529370.38
      sim_grid_pos_y: 1887020.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1529116
      sim_grid_pos_y: 1887357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528814.62
      sim_grid_pos_y: 1887324.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1528634.5
      sim_grid_pos_y: 1887163.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.52854e+06
      sim_grid_pos_y: 1887098.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1528445.38
      sim_grid_pos_y: 1886940.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1528504.25
      sim_grid_pos_y: 1886631.5
    }
  }
}
