terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 761964.625
      sim_grid_pos_y: 1415702.25
    }
    terrain_level_point {
      sim_grid_pos_x: 761354.625
      sim_grid_pos_y: 1404817.25
    }
    terrain_level_point {
      sim_grid_pos_x: 760927.625
      sim_grid_pos_y: 1403488.75
    }
    terrain_level_point {
      sim_grid_pos_x: 760897.125
      sim_grid_pos_y: 1401787.5
    }
    terrain_level_point {
      sim_grid_pos_x: 756855.875
      sim_grid_pos_y: 1402034.88
    }
    terrain_level_point {
      sim_grid_pos_x: 757458.25
      sim_grid_pos_y: 1413321.5
    }
    terrain_level_point {
      sim_grid_pos_x: 756539.438
      sim_grid_pos_y: 1413901.88
    }
    terrain_level_point {
      sim_grid_pos_x: 757788
      sim_grid_pos_y: 1415717.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 760927.312
      sim_grid_pos_y: 1401754.88
    }
    terrain_level_point {
      sim_grid_pos_x: 756823.562
      sim_grid_pos_y: 1402006
    }
    terrain_level_point {
      sim_grid_pos_x: 757426.562
      sim_grid_pos_y: 1413305.12
    }
    terrain_level_point {
      sim_grid_pos_x: 756495.938
      sim_grid_pos_y: 1413893
    }
    terrain_level_point {
      sim_grid_pos_x: 757771.875
      sim_grid_pos_y: 1415747.88
    }
    terrain_level_point {
      sim_grid_pos_x: 761997.125
      sim_grid_pos_y: 1415732.88
    }
    terrain_level_point {
      sim_grid_pos_x: 761385.125
      sim_grid_pos_y: 1404811.62
    }
    terrain_level_point {
      sim_grid_pos_x: 760958.312
      sim_grid_pos_y: 1403483.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 760957.5
      sim_grid_pos_y: 1401722.12
    }
    terrain_level_point {
      sim_grid_pos_x: 756791.188
      sim_grid_pos_y: 1401977.25
    }
    terrain_level_point {
      sim_grid_pos_x: 757394.875
      sim_grid_pos_y: 1413288.75
    }
    terrain_level_point {
      sim_grid_pos_x: 756452.5
      sim_grid_pos_y: 1413884
    }
    terrain_level_point {
      sim_grid_pos_x: 757755.75
      sim_grid_pos_y: 1415778.75
    }
    terrain_level_point {
      sim_grid_pos_x: 762029.688
      sim_grid_pos_y: 1415763.5
    }
    terrain_level_point {
      sim_grid_pos_x: 761415.625
      sim_grid_pos_y: 1404805.88
    }
    terrain_level_point {
      sim_grid_pos_x: 760988.938
      sim_grid_pos_y: 1403478.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 760987.625
      sim_grid_pos_y: 1401689.5
    }
    terrain_level_point {
      sim_grid_pos_x: 756758.875
      sim_grid_pos_y: 1401948.38
    }
    terrain_level_point {
      sim_grid_pos_x: 757363.25
      sim_grid_pos_y: 1413272.5
    }
    terrain_level_point {
      sim_grid_pos_x: 756409
      sim_grid_pos_y: 1413875.12
    }
    terrain_level_point {
      sim_grid_pos_x: 757739.625
      sim_grid_pos_y: 1415809.5
    }
    terrain_level_point {
      sim_grid_pos_x: 762062.188
      sim_grid_pos_y: 1415794.12
    }
    terrain_level_point {
      sim_grid_pos_x: 761446.125
      sim_grid_pos_y: 1404800.25
    }
    terrain_level_point {
      sim_grid_pos_x: 761019.625
      sim_grid_pos_y: 1403473.5
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 748530.438
      sim_grid_pos_y: 1409783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 748197.688
      sim_grid_pos_y: 1402605.62
    }
    terrain_level_point {
      sim_grid_pos_x: 744931.938
      sim_grid_pos_y: 1402787.88
    }
    terrain_level_point {
      sim_grid_pos_x: 744420.562
      sim_grid_pos_y: 1403180.88
    }
    terrain_level_point {
      sim_grid_pos_x: 742982.25
      sim_grid_pos_y: 1403256.12
    }
    terrain_level_point {
      sim_grid_pos_x: 741340.688
      sim_grid_pos_y: 1404143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 740628.438
      sim_grid_pos_y: 1404174.5
    }
    terrain_level_point {
      sim_grid_pos_x: 739770.375
      sim_grid_pos_y: 1403338.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738527.438
      sim_grid_pos_y: 1403358
    }
    terrain_level_point {
      sim_grid_pos_x: 737509.938
      sim_grid_pos_y: 1402707
    }
    terrain_level_point {
      sim_grid_pos_x: 737055.938
      sim_grid_pos_y: 1402586
    }
    terrain_level_point {
      sim_grid_pos_x: 736628.188
      sim_grid_pos_y: 1402798.25
    }
    terrain_level_point {
      sim_grid_pos_x: 736199.938
      sim_grid_pos_y: 1403126.12
    }
    terrain_level_point {
      sim_grid_pos_x: 735868.188
      sim_grid_pos_y: 1404690.75
    }
    terrain_level_point {
      sim_grid_pos_x: 735726.062
      sim_grid_pos_y: 1405357.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735700.688
      sim_grid_pos_y: 1406883
    }
    terrain_level_point {
      sim_grid_pos_x: 735619.562
      sim_grid_pos_y: 1407390.38
    }
    terrain_level_point {
      sim_grid_pos_x: 735499.812
      sim_grid_pos_y: 1409801.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735755.562
      sim_grid_pos_y: 1409936.25
    }
    terrain_level_point {
      sim_grid_pos_x: 736343.312
      sim_grid_pos_y: 1409880.62
    }
    terrain_level_point {
      sim_grid_pos_x: 738334.375
      sim_grid_pos_y: 1410055.12
    }
    terrain_level_point {
      sim_grid_pos_x: 739660.25
      sim_grid_pos_y: 1409944.38
    }
    terrain_level_point {
      sim_grid_pos_x: 742132.625
      sim_grid_pos_y: 1409897.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 737052.625
      sim_grid_pos_y: 1402553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 736611.875
      sim_grid_pos_y: 1402772
    }
    terrain_level_point {
      sim_grid_pos_x: 736172.188
      sim_grid_pos_y: 1403108.62
    }
    terrain_level_point {
      sim_grid_pos_x: 735838.125
      sim_grid_pos_y: 1404684.38
    }
    terrain_level_point {
      sim_grid_pos_x: 735695.375
      sim_grid_pos_y: 1405353.75
    }
    terrain_level_point {
      sim_grid_pos_x: 735670
      sim_grid_pos_y: 1406880.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735588.938
      sim_grid_pos_y: 1407387.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735468.125
      sim_grid_pos_y: 1409819.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735749.312
      sim_grid_pos_y: 1409967.75
    }
    terrain_level_point {
      sim_grid_pos_x: 736343.375
      sim_grid_pos_y: 1409911.5
    }
    terrain_level_point {
      sim_grid_pos_x: 738334.312
      sim_grid_pos_y: 1410086
    }
    terrain_level_point {
      sim_grid_pos_x: 739661.812
      sim_grid_pos_y: 1409975.12
    }
    terrain_level_point {
      sim_grid_pos_x: 742133.188
      sim_grid_pos_y: 1409927.88
    }
    terrain_level_point {
      sim_grid_pos_x: 742133.188
      sim_grid_pos_y: 1409927.88
    }
    terrain_level_point {
      sim_grid_pos_x: 748562.625
      sim_grid_pos_y: 1409813.88
    }
    terrain_level_point {
      sim_grid_pos_x: 748226.938
      sim_grid_pos_y: 1402573.25
    }
    terrain_level_point {
      sim_grid_pos_x: 744920.75
      sim_grid_pos_y: 1402757.62
    }
    terrain_level_point {
      sim_grid_pos_x: 744409.375
      sim_grid_pos_y: 1403150.62
    }
    terrain_level_point {
      sim_grid_pos_x: 742973.75
      sim_grid_pos_y: 1403225.75
    }
    terrain_level_point {
      sim_grid_pos_x: 741332.25
      sim_grid_pos_y: 1404112.88
    }
    terrain_level_point {
      sim_grid_pos_x: 740640.375
      sim_grid_pos_y: 1404143.12
    }
    terrain_level_point {
      sim_grid_pos_x: 739782.688
      sim_grid_pos_y: 1403307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 738536.25
      sim_grid_pos_y: 1403327.12
    }
    terrain_level_point {
      sim_grid_pos_x: 737522.5
      sim_grid_pos_y: 1402678.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 737049.375
      sim_grid_pos_y: 1402520.5
    }
    terrain_level_point {
      sim_grid_pos_x: 736595.5
      sim_grid_pos_y: 1402745.75
    }
    terrain_level_point {
      sim_grid_pos_x: 736144.438
      sim_grid_pos_y: 1403091.12
    }
    terrain_level_point {
      sim_grid_pos_x: 735808
      sim_grid_pos_y: 1404678
    }
    terrain_level_point {
      sim_grid_pos_x: 735808
      sim_grid_pos_y: 1404678
    }
    terrain_level_point {
      sim_grid_pos_x: 735664.625
      sim_grid_pos_y: 1405350.25
    }
    terrain_level_point {
      sim_grid_pos_x: 735639.25
      sim_grid_pos_y: 1406877.62
    }
    terrain_level_point {
      sim_grid_pos_x: 735558.312
      sim_grid_pos_y: 1407384
    }
    terrain_level_point {
      sim_grid_pos_x: 735436.438
      sim_grid_pos_y: 1409837.38
    }
    terrain_level_point {
      sim_grid_pos_x: 735743.062
      sim_grid_pos_y: 1409999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 736343.5
      sim_grid_pos_y: 1409942.38
    }
    terrain_level_point {
      sim_grid_pos_x: 738334.25
      sim_grid_pos_y: 1410116.88
    }
    terrain_level_point {
      sim_grid_pos_x: 739663.438
      sim_grid_pos_y: 1410005.88
    }
    terrain_level_point {
      sim_grid_pos_x: 742133.688
      sim_grid_pos_y: 1409958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 742133.688
      sim_grid_pos_y: 1409958.62
    }
    terrain_level_point {
      sim_grid_pos_x: 748594.812
      sim_grid_pos_y: 1409844.12
    }
    terrain_level_point {
      sim_grid_pos_x: 748256.25
      sim_grid_pos_y: 1402540.75
    }
    terrain_level_point {
      sim_grid_pos_x: 744909.562
      sim_grid_pos_y: 1402727.5
    }
    terrain_level_point {
      sim_grid_pos_x: 744398.25
      sim_grid_pos_y: 1403120.38
    }
    terrain_level_point {
      sim_grid_pos_x: 742965.188
      sim_grid_pos_y: 1403195.38
    }
    terrain_level_point {
      sim_grid_pos_x: 741323.875
      sim_grid_pos_y: 1404082.5
    }
    terrain_level_point {
      sim_grid_pos_x: 740652.312
      sim_grid_pos_y: 1404111.88
    }
    terrain_level_point {
      sim_grid_pos_x: 739795
      sim_grid_pos_y: 1403276.88
    }
    terrain_level_point {
      sim_grid_pos_x: 738545
      sim_grid_pos_y: 1403296.25
    }
    terrain_level_point {
      sim_grid_pos_x: 737535
      sim_grid_pos_y: 1402650.12
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 756644.75
      sim_grid_pos_y: 1398125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 756304.375
      sim_grid_pos_y: 1398160.38
    }
    terrain_level_point {
      sim_grid_pos_x: 755889.25
      sim_grid_pos_y: 1393191
    }
    terrain_level_point {
      sim_grid_pos_x: 755661.375
      sim_grid_pos_y: 1392542.5
    }
    terrain_level_point {
      sim_grid_pos_x: 754102.062
      sim_grid_pos_y: 1392822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 753094.562
      sim_grid_pos_y: 1392899.12
    }
    terrain_level_point {
      sim_grid_pos_x: 752882.25
      sim_grid_pos_y: 1390832.88
    }
    terrain_level_point {
      sim_grid_pos_x: 756278.312
      sim_grid_pos_y: 1390627.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 756676.875
      sim_grid_pos_y: 1398153
    }
    terrain_level_point {
      sim_grid_pos_x: 756276.312
      sim_grid_pos_y: 1398194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 755858.938
      sim_grid_pos_y: 1393197.5
    }
    terrain_level_point {
      sim_grid_pos_x: 755641
      sim_grid_pos_y: 1392577.38
    }
    terrain_level_point {
      sim_grid_pos_x: 754106
      sim_grid_pos_y: 1392853.12
    }
    terrain_level_point {
      sim_grid_pos_x: 753067
      sim_grid_pos_y: 1392932
    }
    terrain_level_point {
      sim_grid_pos_x: 752848.375
      sim_grid_pos_y: 1390804.12
    }
    terrain_level_point {
      sim_grid_pos_x: 756307.5
      sim_grid_pos_y: 1390595.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 756709.062
      sim_grid_pos_y: 1398180.62
    }
    terrain_level_point {
      sim_grid_pos_x: 756248.25
      sim_grid_pos_y: 1398228
    }
    terrain_level_point {
      sim_grid_pos_x: 755828.625
      sim_grid_pos_y: 1393204
    }
    terrain_level_point {
      sim_grid_pos_x: 755620.688
      sim_grid_pos_y: 1392612.38
    }
    terrain_level_point {
      sim_grid_pos_x: 754109.875
      sim_grid_pos_y: 1392883.62
    }
    terrain_level_point {
      sim_grid_pos_x: 753039.438
      sim_grid_pos_y: 1392965
    }
    terrain_level_point {
      sim_grid_pos_x: 752814.5
      sim_grid_pos_y: 1390775.38
    }
    terrain_level_point {
      sim_grid_pos_x: 756336.688
      sim_grid_pos_y: 1390562.75
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 729028.625
      sim_grid_pos_y: 1422369.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724988.625
      sim_grid_pos_y: 1422282.12
    }
    terrain_level_point {
      sim_grid_pos_x: 725040.875
      sim_grid_pos_y: 1429242.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724703.562
      sim_grid_pos_y: 1430282
    }
    terrain_level_point {
      sim_grid_pos_x: 724149.25
      sim_grid_pos_y: 1430792.12
    }
    terrain_level_point {
      sim_grid_pos_x: 723334.062
      sim_grid_pos_y: 1430956.5
    }
    terrain_level_point {
      sim_grid_pos_x: 722370.688
      sim_grid_pos_y: 1430889.75
    }
    terrain_level_point {
      sim_grid_pos_x: 721692
      sim_grid_pos_y: 1435636.75
    }
    terrain_level_point {
      sim_grid_pos_x: 721761
      sim_grid_pos_y: 1437885.5
    }
    terrain_level_point {
      sim_grid_pos_x: 721669.188
      sim_grid_pos_y: 1439431.25
    }
    terrain_level_point {
      sim_grid_pos_x: 721801.625
      sim_grid_pos_y: 1440787.38
    }
    terrain_level_point {
      sim_grid_pos_x: 722346.062
      sim_grid_pos_y: 1442403.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724343
      sim_grid_pos_y: 1446766.88
    }
    terrain_level_point {
      sim_grid_pos_x: 724809.812
      sim_grid_pos_y: 1447835.25
    }
    terrain_level_point {
      sim_grid_pos_x: 726849
      sim_grid_pos_y: 1451772.25
    }
    terrain_level_point {
      sim_grid_pos_x: 729109.562
      sim_grid_pos_y: 1451958
    }
    terrain_level_point {
      sim_grid_pos_x: 728945.75
      sim_grid_pos_y: 1435925.62
    }
    terrain_level_point {
      sim_grid_pos_x: 727536.25
      sim_grid_pos_y: 1435459.5
    }
    terrain_level_point {
      sim_grid_pos_x: 729009.188
      sim_grid_pos_y: 1433795.12
    }
    terrain_level_point {
      sim_grid_pos_x: 728543.312
      sim_grid_pos_y: 1433203
    }
    terrain_level_point {
      sim_grid_pos_x: 728572.688
      sim_grid_pos_y: 1431678.62
    }
    terrain_level_point {
      sim_grid_pos_x: 729071.875
      sim_grid_pos_y: 1430832
    }
    terrain_level_point {
      sim_grid_pos_x: 729023.125
      sim_grid_pos_y: 1429224.25
    }
    terrain_level_point {
      sim_grid_pos_x: 728864.25
      sim_grid_pos_y: 1428397.62
    }
    terrain_level_point {
      sim_grid_pos_x: 728860.625
      sim_grid_pos_y: 1425728.62
    }
    terrain_level_point {
      sim_grid_pos_x: 729046.812
      sim_grid_pos_y: 1424591.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 724957.625
      sim_grid_pos_y: 1422250.75
    }
    terrain_level_point {
      sim_grid_pos_x: 725010.062
      sim_grid_pos_y: 1429237.5
    }
    terrain_level_point {
      sim_grid_pos_x: 724676.812
      sim_grid_pos_y: 1430264.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724134.75
      sim_grid_pos_y: 1430763.62
    }
    terrain_level_point {
      sim_grid_pos_x: 723332.062
      sim_grid_pos_y: 1430925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 722344.25
      sim_grid_pos_y: 1430857.12
    }
    terrain_level_point {
      sim_grid_pos_x: 721661.188
      sim_grid_pos_y: 1435635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 721730.25
      sim_grid_pos_y: 1437885
    }
    terrain_level_point {
      sim_grid_pos_x: 721638.375
      sim_grid_pos_y: 1439431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 721771.375
      sim_grid_pos_y: 1440793.88
    }
    terrain_level_point {
      sim_grid_pos_x: 722317.438
      sim_grid_pos_y: 1442415
    }
    terrain_level_point {
      sim_grid_pos_x: 724314.812
      sim_grid_pos_y: 1446779.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724782.062
      sim_grid_pos_y: 1447848.5
    }
    terrain_level_point {
      sim_grid_pos_x: 726829.5
      sim_grid_pos_y: 1451801.5
    }
    terrain_level_point {
      sim_grid_pos_x: 729140.625
      sim_grid_pos_y: 1451991.38
    }
    terrain_level_point {
      sim_grid_pos_x: 728976.25
      sim_grid_pos_y: 1435903.25
    }
    terrain_level_point {
      sim_grid_pos_x: 727590.188
      sim_grid_pos_y: 1435444.88
    }
    terrain_level_point {
      sim_grid_pos_x: 729049.25
      sim_grid_pos_y: 1433796.38
    }
    terrain_level_point {
      sim_grid_pos_x: 728574.25
      sim_grid_pos_y: 1433192.62
    }
    terrain_level_point {
      sim_grid_pos_x: 728603.25
      sim_grid_pos_y: 1431687.25
    }
    terrain_level_point {
      sim_grid_pos_x: 729102.875
      sim_grid_pos_y: 1.43084e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 729053.812
      sim_grid_pos_y: 1429220.88
    }
    terrain_level_point {
      sim_grid_pos_x: 728895
      sim_grid_pos_y: 1428394.75
    }
    terrain_level_point {
      sim_grid_pos_x: 728891.375
      sim_grid_pos_y: 1425731.12
    }
    terrain_level_point {
      sim_grid_pos_x: 729077.562
      sim_grid_pos_y: 1424594.25
    }
    terrain_level_point {
      sim_grid_pos_x: 729059.125
      sim_grid_pos_y: 1422339.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 724926.625
      sim_grid_pos_y: 1422219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 724979.25
      sim_grid_pos_y: 1429232.75
    }
    terrain_level_point {
      sim_grid_pos_x: 724650.062
      sim_grid_pos_y: 1430247.62
    }
    terrain_level_point {
      sim_grid_pos_x: 724120.25
      sim_grid_pos_y: 1430735.25
    }
    terrain_level_point {
      sim_grid_pos_x: 723330.062
      sim_grid_pos_y: 1430894.62
    }
    terrain_level_point {
      sim_grid_pos_x: 722317.875
      sim_grid_pos_y: 1430824.38
    }
    terrain_level_point {
      sim_grid_pos_x: 721630.375
      sim_grid_pos_y: 1435633.38
    }
    terrain_level_point {
      sim_grid_pos_x: 721699.438
      sim_grid_pos_y: 1437884.62
    }
    terrain_level_point {
      sim_grid_pos_x: 721607.5
      sim_grid_pos_y: 1439432.38
    }
    terrain_level_point {
      sim_grid_pos_x: 721741.062
      sim_grid_pos_y: 1440800.38
    }
    terrain_level_point {
      sim_grid_pos_x: 722288.812
      sim_grid_pos_y: 1442426.38
    }
    terrain_level_point {
      sim_grid_pos_x: 724286.938
      sim_grid_pos_y: 1446792.12
    }
    terrain_level_point {
      sim_grid_pos_x: 724754.25
      sim_grid_pos_y: 1447861.75
    }
    terrain_level_point {
      sim_grid_pos_x: 726810
      sim_grid_pos_y: 1451830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 729171.75
      sim_grid_pos_y: 1452024.75
    }
    terrain_level_point {
      sim_grid_pos_x: 729006.812
      sim_grid_pos_y: 1435881
    }
    terrain_level_point {
      sim_grid_pos_x: 727644.125
      sim_grid_pos_y: 1435430.38
    }
    terrain_level_point {
      sim_grid_pos_x: 729089.312
      sim_grid_pos_y: 1433797.5
    }
    terrain_level_point {
      sim_grid_pos_x: 728605.25
      sim_grid_pos_y: 1433182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 728633.875
      sim_grid_pos_y: 1431696
    }
    terrain_level_point {
      sim_grid_pos_x: 729133.938
      sim_grid_pos_y: 1430848
    }
    terrain_level_point {
      sim_grid_pos_x: 729084.438
      sim_grid_pos_y: 1429217.5
    }
    terrain_level_point {
      sim_grid_pos_x: 728925.75
      sim_grid_pos_y: 1428391.75
    }
    terrain_level_point {
      sim_grid_pos_x: 728922.125
      sim_grid_pos_y: 1425733.62
    }
    terrain_level_point {
      sim_grid_pos_x: 729108.375
      sim_grid_pos_y: 1424596.62
    }
    terrain_level_point {
      sim_grid_pos_x: 729089.625
      sim_grid_pos_y: 1422309.12
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 719627.188
      sim_grid_pos_y: 1412049.5
    }
    terrain_level_point {
      sim_grid_pos_x: 715700.062
      sim_grid_pos_y: 1413111.5
    }
    terrain_level_point {
      sim_grid_pos_x: 714735.25
      sim_grid_pos_y: 1412398.5
    }
    terrain_level_point {
      sim_grid_pos_x: 714389.875
      sim_grid_pos_y: 1413077.38
    }
    terrain_level_point {
      sim_grid_pos_x: 712903.625
      sim_grid_pos_y: 1413818.5
    }
    terrain_level_point {
      sim_grid_pos_x: 715335.625
      sim_grid_pos_y: 1417527.25
    }
    terrain_level_point {
      sim_grid_pos_x: 717604.812
      sim_grid_pos_y: 1416366.62
    }
    terrain_level_point {
      sim_grid_pos_x: 720367.812
      sim_grid_pos_y: 1415827
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 719651.062
      sim_grid_pos_y: 1412011.12
    }
    terrain_level_point {
      sim_grid_pos_x: 715706.375
      sim_grid_pos_y: 1413077.88
    }
    terrain_level_point {
      sim_grid_pos_x: 714724.312
      sim_grid_pos_y: 1412352.12
    }
    terrain_level_point {
      sim_grid_pos_x: 714367.062
      sim_grid_pos_y: 1413054.38
    }
    terrain_level_point {
      sim_grid_pos_x: 712858.875
      sim_grid_pos_y: 1413806.38
    }
    terrain_level_point {
      sim_grid_pos_x: 715325.062
      sim_grid_pos_y: 1417567.25
    }
    terrain_level_point {
      sim_grid_pos_x: 717614.938
      sim_grid_pos_y: 1416395.88
    }
    terrain_level_point {
      sim_grid_pos_x: 720403.875
      sim_grid_pos_y: 1415851.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 719674.875
      sim_grid_pos_y: 1411972.88
    }
    terrain_level_point {
      sim_grid_pos_x: 715712.688
      sim_grid_pos_y: 1413044.38
    }
    terrain_level_point {
      sim_grid_pos_x: 714713.375
      sim_grid_pos_y: 1412305.88
    }
    terrain_level_point {
      sim_grid_pos_x: 714344.25
      sim_grid_pos_y: 1413031.38
    }
    terrain_level_point {
      sim_grid_pos_x: 712814.188
      sim_grid_pos_y: 1413794.25
    }
    terrain_level_point {
      sim_grid_pos_x: 715314.438
      sim_grid_pos_y: 1417607.25
    }
    terrain_level_point {
      sim_grid_pos_x: 717625.125
      sim_grid_pos_y: 1416425.25
    }
    terrain_level_point {
      sim_grid_pos_x: 720440
      sim_grid_pos_y: 1415875.62
    }
  }
}
terrain_level_data {
  terrain_level: 5
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 696972.875
      sim_grid_pos_y: 1440253
    }
    terrain_level_point {
      sim_grid_pos_x: 696066.562
      sim_grid_pos_y: 1437921.12
    }
    terrain_level_point {
      sim_grid_pos_x: 694782.875
      sim_grid_pos_y: 1428126.88
    }
    terrain_level_point {
      sim_grid_pos_x: 695559.375
      sim_grid_pos_y: 1425780.88
    }
    terrain_level_point {
      sim_grid_pos_x: 696293.938
      sim_grid_pos_y: 1424773.62
    }
    terrain_level_point {
      sim_grid_pos_x: 697522.625
      sim_grid_pos_y: 1424426.62
    }
    terrain_level_point {
      sim_grid_pos_x: 698296.625
      sim_grid_pos_y: 1423563.5
    }
    terrain_level_point {
      sim_grid_pos_x: 698482
      sim_grid_pos_y: 1421418.12
    }
    terrain_level_point {
      sim_grid_pos_x: 698189.375
      sim_grid_pos_y: 1417948
    }
    terrain_level_point {
      sim_grid_pos_x: 696027.938
      sim_grid_pos_y: 1418824
    }
    terrain_level_point {
      sim_grid_pos_x: 687927.438
      sim_grid_pos_y: 1410626.5
    }
    terrain_level_point {
      sim_grid_pos_x: 691439.75
      sim_grid_pos_y: 1406911
    }
    terrain_level_point {
      sim_grid_pos_x: 695864
      sim_grid_pos_y: 1410330.12
    }
    terrain_level_point {
      sim_grid_pos_x: 699464.5
      sim_grid_pos_y: 1412874.12
    }
    terrain_level_point {
      sim_grid_pos_x: 700752.688
      sim_grid_pos_y: 1414326.75
    }
    terrain_level_point {
      sim_grid_pos_x: 702101.438
      sim_grid_pos_y: 1416071.12
    }
    terrain_level_point {
      sim_grid_pos_x: 703158.188
      sim_grid_pos_y: 1419169
    }
    terrain_level_point {
      sim_grid_pos_x: 703334.188
      sim_grid_pos_y: 1420209
    }
    terrain_level_point {
      sim_grid_pos_x: 704509.188
      sim_grid_pos_y: 1423972.75
    }
    terrain_level_point {
      sim_grid_pos_x: 704581.625
      sim_grid_pos_y: 1425863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 704452.188
      sim_grid_pos_y: 1427155.5
    }
    terrain_level_point {
      sim_grid_pos_x: 704053.125
      sim_grid_pos_y: 1428322.38
    }
    terrain_level_point {
      sim_grid_pos_x: 701022
      sim_grid_pos_y: 1433935.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 695882.375
      sim_grid_pos_y: 1410305.38
    }
    terrain_level_point {
      sim_grid_pos_x: 699485.125
      sim_grid_pos_y: 1412851
    }
    terrain_level_point {
      sim_grid_pos_x: 700776.375
      sim_grid_pos_y: 1414307.12
    }
    terrain_level_point {
      sim_grid_pos_x: 702128.938
      sim_grid_pos_y: 1416056.38
    }
    terrain_level_point {
      sim_grid_pos_x: 703188.062
      sim_grid_pos_y: 1419161.5
    }
    terrain_level_point {
      sim_grid_pos_x: 703364.188
      sim_grid_pos_y: 1420201.88
    }
    terrain_level_point {
      sim_grid_pos_x: 704539.75
      sim_grid_pos_y: 1423967.5
    }
    terrain_level_point {
      sim_grid_pos_x: 704612.5
      sim_grid_pos_y: 1425864.62
    }
    terrain_level_point {
      sim_grid_pos_x: 704482.438
      sim_grid_pos_y: 1427162.12
    }
    terrain_level_point {
      sim_grid_pos_x: 704081.375
      sim_grid_pos_y: 1428334.75
    }
    terrain_level_point {
      sim_grid_pos_x: 701048.562
      sim_grid_pos_y: 1433951
    }
    terrain_level_point {
      sim_grid_pos_x: 696988.562
      sim_grid_pos_y: 1440285.38
    }
    terrain_level_point {
      sim_grid_pos_x: 696951
      sim_grid_pos_y: 1440281.62
    }
    terrain_level_point {
      sim_grid_pos_x: 696036.562
      sim_grid_pos_y: 1437928.75
    }
    terrain_level_point {
      sim_grid_pos_x: 694751.438
      sim_grid_pos_y: 1428123.88
    }
    terrain_level_point {
      sim_grid_pos_x: 695531.688
      sim_grid_pos_y: 1425766.62
    }
    terrain_level_point {
      sim_grid_pos_x: 696275.375
      sim_grid_pos_y: 1424746.88
    }
    terrain_level_point {
      sim_grid_pos_x: 697505.688
      sim_grid_pos_y: 1424399.38
    }
    terrain_level_point {
      sim_grid_pos_x: 698266.875
      sim_grid_pos_y: 1423550.5
    }
    terrain_level_point {
      sim_grid_pos_x: 698451.125
      sim_grid_pos_y: 1421418.12
    }
    terrain_level_point {
      sim_grid_pos_x: 698162.25
      sim_grid_pos_y: 1417992.25
    }
    terrain_level_point {
      sim_grid_pos_x: 696020.5
      sim_grid_pos_y: 1418860.25
    }
    terrain_level_point {
      sim_grid_pos_x: 687884.625
      sim_grid_pos_y: 1410627
    }
    terrain_level_point {
      sim_grid_pos_x: 691436.562
      sim_grid_pos_y: 1406869.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 695900.562
      sim_grid_pos_y: 1410280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 699505.812
      sim_grid_pos_y: 1412827.88
    }
    terrain_level_point {
      sim_grid_pos_x: 700800.062
      sim_grid_pos_y: 1414287.5
    }
    terrain_level_point {
      sim_grid_pos_x: 702156.375
      sim_grid_pos_y: 1416041.5
    }
    terrain_level_point {
      sim_grid_pos_x: 703218
      sim_grid_pos_y: 1419153.88
    }
    terrain_level_point {
      sim_grid_pos_x: 703394.125
      sim_grid_pos_y: 1420194.62
    }
    terrain_level_point {
      sim_grid_pos_x: 704570.312
      sim_grid_pos_y: 1423962.25
    }
    terrain_level_point {
      sim_grid_pos_x: 704643.312
      sim_grid_pos_y: 1425865.62
    }
    terrain_level_point {
      sim_grid_pos_x: 704512.688
      sim_grid_pos_y: 1427168.62
    }
    terrain_level_point {
      sim_grid_pos_x: 704109.688
      sim_grid_pos_y: 1428347.12
    }
    terrain_level_point {
      sim_grid_pos_x: 701075.062
      sim_grid_pos_y: 1433966.62
    }
    terrain_level_point {
      sim_grid_pos_x: 697004.312
      sim_grid_pos_y: 1440317.88
    }
    terrain_level_point {
      sim_grid_pos_x: 696929.188
      sim_grid_pos_y: 1440310.38
    }
    terrain_level_point {
      sim_grid_pos_x: 696006.562
      sim_grid_pos_y: 1437936.5
    }
    terrain_level_point {
      sim_grid_pos_x: 694720
      sim_grid_pos_y: 1428120.88
    }
    terrain_level_point {
      sim_grid_pos_x: 695504
      sim_grid_pos_y: 1425752.38
    }
    terrain_level_point {
      sim_grid_pos_x: 696256.75
      sim_grid_pos_y: 1424720.12
    }
    terrain_level_point {
      sim_grid_pos_x: 697488.688
      sim_grid_pos_y: 1424372.25
    }
    terrain_level_point {
      sim_grid_pos_x: 698237.125
      sim_grid_pos_y: 1423537.62
    }
    terrain_level_point {
      sim_grid_pos_x: 698420.25
      sim_grid_pos_y: 1421418
    }
    terrain_level_point {
      sim_grid_pos_x: 698135.125
      sim_grid_pos_y: 1418036.38
    }
    terrain_level_point {
      sim_grid_pos_x: 696013.062
      sim_grid_pos_y: 1418896.38
    }
    terrain_level_point {
      sim_grid_pos_x: 687841.875
      sim_grid_pos_y: 1410627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 691433.312
      sim_grid_pos_y: 1406828.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 695918.875
      sim_grid_pos_y: 1410255.88
    }
    terrain_level_point {
      sim_grid_pos_x: 699526.438
      sim_grid_pos_y: 1412804.88
    }
    terrain_level_point {
      sim_grid_pos_x: 700823.75
      sim_grid_pos_y: 1414267.75
    }
    terrain_level_point {
      sim_grid_pos_x: 702183.875
      sim_grid_pos_y: 1416026.75
    }
    terrain_level_point {
      sim_grid_pos_x: 703247.875
      sim_grid_pos_y: 1419146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 703424.125
      sim_grid_pos_y: 1420187.5
    }
    terrain_level_point {
      sim_grid_pos_x: 704600.875
      sim_grid_pos_y: 1423957
    }
    terrain_level_point {
      sim_grid_pos_x: 704674.125
      sim_grid_pos_y: 1425866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 704542.938
      sim_grid_pos_y: 1427175.25
    }
    terrain_level_point {
      sim_grid_pos_x: 704137.938
      sim_grid_pos_y: 1428359.5
    }
    terrain_level_point {
      sim_grid_pos_x: 701101.562
      sim_grid_pos_y: 1433982.25
    }
    terrain_level_point {
      sim_grid_pos_x: 697020
      sim_grid_pos_y: 1440350.38
    }
    terrain_level_point {
      sim_grid_pos_x: 696907.375
      sim_grid_pos_y: 1440339.12
    }
    terrain_level_point {
      sim_grid_pos_x: 695976.5
      sim_grid_pos_y: 1437944.12
    }
    terrain_level_point {
      sim_grid_pos_x: 694688.625
      sim_grid_pos_y: 1428117.88
    }
    terrain_level_point {
      sim_grid_pos_x: 695476.312
      sim_grid_pos_y: 1425738.12
    }
    terrain_level_point {
      sim_grid_pos_x: 696238.188
      sim_grid_pos_y: 1424693.5
    }
    terrain_level_point {
      sim_grid_pos_x: 697471.812
      sim_grid_pos_y: 1424345.12
    }
    terrain_level_point {
      sim_grid_pos_x: 698207.375
      sim_grid_pos_y: 1423524.75
    }
    terrain_level_point {
      sim_grid_pos_x: 698389.375
      sim_grid_pos_y: 1421418
    }
    terrain_level_point {
      sim_grid_pos_x: 698108
      sim_grid_pos_y: 1418080.5
    }
    terrain_level_point {
      sim_grid_pos_x: 696005.562
      sim_grid_pos_y: 1418932.62
    }
    terrain_level_point {
      sim_grid_pos_x: 687799.125
      sim_grid_pos_y: 1410628
    }
    terrain_level_point {
      sim_grid_pos_x: 691430.125
      sim_grid_pos_y: 1406786.88
    }
  }
}
