terrain_level_data {
  terrain_level: 204
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 153352.969
      sim_grid_pos_y: 2230551.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152925.875
      sim_grid_pos_y: 2231007.25
    }
    terrain_level_point {
      sim_grid_pos_x: 152742.719
      sim_grid_pos_y: 2231083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 152812.156
      sim_grid_pos_y: 2230891.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149442.859
      sim_grid_pos_y: 2234245.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149575.219
      sim_grid_pos_y: 2234392.75
    }
    terrain_level_point {
      sim_grid_pos_x: 149710.391
      sim_grid_pos_y: 2234386
    }
    terrain_level_point {
      sim_grid_pos_x: 149685.984
      sim_grid_pos_y: 2234555.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149294.281
      sim_grid_pos_y: 2234570.75
    }
    terrain_level_point {
      sim_grid_pos_x: 149190.422
      sim_grid_pos_y: 2234647.5
    }
    terrain_level_point {
      sim_grid_pos_x: 149184.5
      sim_grid_pos_y: 2234893
    }
    terrain_level_point {
      sim_grid_pos_x: 148974.531
      sim_grid_pos_y: 2234705
    }
    terrain_level_point {
      sim_grid_pos_x: 148501.562
      sim_grid_pos_y: 2235174.75
    }
    terrain_level_point {
      sim_grid_pos_x: 148115.562
      sim_grid_pos_y: 2234823
    }
    terrain_level_point {
      sim_grid_pos_x: 151142.578
      sim_grid_pos_y: 2231783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150661.078
      sim_grid_pos_y: 2231324.5
    }
    terrain_level_point {
      sim_grid_pos_x: 150600.922
      sim_grid_pos_y: 2.23137e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 150493.453
      sim_grid_pos_y: 2231276.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150512.812
      sim_grid_pos_y: 2231079.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150694.5
      sim_grid_pos_y: 2231148.75
    }
    terrain_level_point {
      sim_grid_pos_x: 151202.438
      sim_grid_pos_y: 2230903.75
    }
    terrain_level_point {
      sim_grid_pos_x: 151434.906
      sim_grid_pos_y: 2230897.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151546.844
      sim_grid_pos_y: 2230782.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151800.609
      sim_grid_pos_y: 2230716.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151858.688
      sim_grid_pos_y: 2230657.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152016.734
      sim_grid_pos_y: 2230813
    }
    terrain_level_point {
      sim_grid_pos_x: 152272.047
      sim_grid_pos_y: 2230658.5
    }
    terrain_level_point {
      sim_grid_pos_x: 153246.812
      sim_grid_pos_y: 2229639.75
    }
    terrain_level_point {
      sim_grid_pos_x: 153407.391
      sim_grid_pos_y: 2229801
    }
    terrain_level_point {
      sim_grid_pos_x: 153397.391
      sim_grid_pos_y: 2230053.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 153459.5
      sim_grid_pos_y: 2229780.75
    }
    terrain_level_point {
      sim_grid_pos_x: 153448.562
      sim_grid_pos_y: 2230057
    }
    terrain_level_point {
      sim_grid_pos_x: 153402.453
      sim_grid_pos_y: 2230573.75
    }
    terrain_level_point {
      sim_grid_pos_x: 152955.734
      sim_grid_pos_y: 2231050.25
    }
    terrain_level_point {
      sim_grid_pos_x: 152731.484
      sim_grid_pos_y: 2231143.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152683.141
      sim_grid_pos_y: 2231097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 152686.109
      sim_grid_pos_y: 2231089
    }
    terrain_level_point {
      sim_grid_pos_x: 149513.531
      sim_grid_pos_y: 2234247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149597.062
      sim_grid_pos_y: 2234340.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149770.016
      sim_grid_pos_y: 2234331.75
    }
    terrain_level_point {
      sim_grid_pos_x: 149730.641
      sim_grid_pos_y: 2234604.75
    }
    terrain_level_point {
      sim_grid_pos_x: 149312.078
      sim_grid_pos_y: 2234621.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149241.062
      sim_grid_pos_y: 2234673.75
    }
    terrain_level_point {
      sim_grid_pos_x: 149234.953
      sim_grid_pos_y: 2234927
    }
    terrain_level_point {
      sim_grid_pos_x: 149174.734
      sim_grid_pos_y: 2234953
    }
    terrain_level_point {
      sim_grid_pos_x: 148976.344
      sim_grid_pos_y: 2234775.5
    }
    terrain_level_point {
      sim_grid_pos_x: 148503.078
      sim_grid_pos_y: 2235245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 148041.422
      sim_grid_pos_y: 2234824.75
    }
    terrain_level_point {
      sim_grid_pos_x: 151069.281
      sim_grid_pos_y: 2231784.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150657.234
      sim_grid_pos_y: 2231391.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150598.703
      sim_grid_pos_y: 2231436
    }
    terrain_level_point {
      sim_grid_pos_x: 150439.844
      sim_grid_pos_y: 2231298
    }
    terrain_level_point {
      sim_grid_pos_x: 150468.344
      sim_grid_pos_y: 2231008
    }
    terrain_level_point {
      sim_grid_pos_x: 150692.094
      sim_grid_pos_y: 2231093
    }
    terrain_level_point {
      sim_grid_pos_x: 151190.062
      sim_grid_pos_y: 2230852.75
    }
    terrain_level_point {
      sim_grid_pos_x: 151412.703
      sim_grid_pos_y: 2230846.75
    }
    terrain_level_point {
      sim_grid_pos_x: 151520.094
      sim_grid_pos_y: 2230736.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151774
      sim_grid_pos_y: 2230670.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151858.109
      sim_grid_pos_y: 2230585
    }
    terrain_level_point {
      sim_grid_pos_x: 152024.281
      sim_grid_pos_y: 2230748.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152239.703
      sim_grid_pos_y: 2230618.25
    }
    terrain_level_point {
      sim_grid_pos_x: 153246.078
      sim_grid_pos_y: 2229566.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 153511.594
      sim_grid_pos_y: 2229760.25
    }
    terrain_level_point {
      sim_grid_pos_x: 153499.734
      sim_grid_pos_y: 2230060.25
    }
    terrain_level_point {
      sim_grid_pos_x: 153451.953
      sim_grid_pos_y: 2230595.75
    }
    terrain_level_point {
      sim_grid_pos_x: 152985.578
      sim_grid_pos_y: 2231093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152720.266
      sim_grid_pos_y: 2231203.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152681.203
      sim_grid_pos_y: 2231166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149584.188
      sim_grid_pos_y: 2234249.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149618.891
      sim_grid_pos_y: 2234288
    }
    terrain_level_point {
      sim_grid_pos_x: 149829.625
      sim_grid_pos_y: 2234277.5
    }
    terrain_level_point {
      sim_grid_pos_x: 149775.281
      sim_grid_pos_y: 2234654.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149329.844
      sim_grid_pos_y: 2234672
    }
    terrain_level_point {
      sim_grid_pos_x: 149291.703
      sim_grid_pos_y: 2234700.25
    }
    terrain_level_point {
      sim_grid_pos_x: 149285.406
      sim_grid_pos_y: 2234961
    }
    terrain_level_point {
      sim_grid_pos_x: 149164.984
      sim_grid_pos_y: 2235013.25
    }
    terrain_level_point {
      sim_grid_pos_x: 148978.172
      sim_grid_pos_y: 2234845.75
    }
    terrain_level_point {
      sim_grid_pos_x: 148504.594
      sim_grid_pos_y: 2235316.25
    }
    terrain_level_point {
      sim_grid_pos_x: 147967.281
      sim_grid_pos_y: 2234826.5
    }
    terrain_level_point {
      sim_grid_pos_x: 150996
      sim_grid_pos_y: 2231785.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150653.406
      sim_grid_pos_y: 2231458.75
    }
    terrain_level_point {
      sim_grid_pos_x: 150596.484
      sim_grid_pos_y: 2231502
    }
    terrain_level_point {
      sim_grid_pos_x: 150386.234
      sim_grid_pos_y: 2231319.5
    }
    terrain_level_point {
      sim_grid_pos_x: 150423.891
      sim_grid_pos_y: 2230936.25
    }
    terrain_level_point {
      sim_grid_pos_x: 150689.672
      sim_grid_pos_y: 2231037.25
    }
    terrain_level_point {
      sim_grid_pos_x: 151177.703
      sim_grid_pos_y: 2230801.75
    }
    terrain_level_point {
      sim_grid_pos_x: 151390.5
      sim_grid_pos_y: 2230796.25
    }
    terrain_level_point {
      sim_grid_pos_x: 151493.344
      sim_grid_pos_y: 2230690.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151747.406
      sim_grid_pos_y: 2230624.5
    }
    terrain_level_point {
      sim_grid_pos_x: 151857.531
      sim_grid_pos_y: 2230512.5
    }
    terrain_level_point {
      sim_grid_pos_x: 152031.828
      sim_grid_pos_y: 2230684
    }
    terrain_level_point {
      sim_grid_pos_x: 152207.359
      sim_grid_pos_y: 2230577.75
    }
    terrain_level_point {
      sim_grid_pos_x: 153245.344
      sim_grid_pos_y: 2229493
    }
  }
}
