terrain_level_data {
  terrain_level: 50
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 647243.25
      sim_grid_pos_y: 3315965
    }
    terrain_level_point {
      sim_grid_pos_x: 647253.25
      sim_grid_pos_y: 3316206.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647529.25
      sim_grid_pos_y: 3316903.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647742.25
      sim_grid_pos_y: 3316994.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647864.938
      sim_grid_pos_y: 3316964
    }
    terrain_level_point {
      sim_grid_pos_x: 647919.875
      sim_grid_pos_y: 3316902.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648101.312
      sim_grid_pos_y: 3316840.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648209.938
      sim_grid_pos_y: 3316920.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648446.25
      sim_grid_pos_y: 3316920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648404.875
      sim_grid_pos_y: 3316783.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648257.438
      sim_grid_pos_y: 3316763.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647937.562
      sim_grid_pos_y: 3316537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647941.688
      sim_grid_pos_y: 3315639
    }
    terrain_level_point {
      sim_grid_pos_x: 649365.312
      sim_grid_pos_y: 3315561.25
    }
    terrain_level_point {
      sim_grid_pos_x: 649357.312
      sim_grid_pos_y: 3314115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 649419.25
      sim_grid_pos_y: 3.31393e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 648843.062
      sim_grid_pos_y: 3313769.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648276.062
      sim_grid_pos_y: 3313782
    }
    terrain_level_point {
      sim_grid_pos_x: 648141.625
      sim_grid_pos_y: 3314026.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648248.75
      sim_grid_pos_y: 3314420.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648172.25
      sim_grid_pos_y: 3314911.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647934.75
      sim_grid_pos_y: 3.31524e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 647295.375
      sim_grid_pos_y: 3315203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647175.812
      sim_grid_pos_y: 3314754
    }
    terrain_level_point {
      sim_grid_pos_x: 646652.5
      sim_grid_pos_y: 3314510.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646269.062
      sim_grid_pos_y: 3314980.5
    }
    terrain_level_point {
      sim_grid_pos_x: 646134.5
      sim_grid_pos_y: 3315793.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646555.125
      sim_grid_pos_y: 3316059.75
    }
    terrain_level_point {
      sim_grid_pos_x: 646912.188
      sim_grid_pos_y: 3316057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 646982.812
      sim_grid_pos_y: 3315912.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647181.562
      sim_grid_pos_y: 3315919.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 648846.938
      sim_grid_pos_y: 3313738.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648257.625
      sim_grid_pos_y: 3313751.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648108.688
      sim_grid_pos_y: 3314022.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648217.375
      sim_grid_pos_y: 3314422
    }
    terrain_level_point {
      sim_grid_pos_x: 648143
      sim_grid_pos_y: 3314899.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647919.688
      sim_grid_pos_y: 3315208.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647319.375
      sim_grid_pos_y: 3315174.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647201.875
      sim_grid_pos_y: 3314732.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646643.812
      sim_grid_pos_y: 3314472.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646240.062
      sim_grid_pos_y: 3314967.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646100.812
      sim_grid_pos_y: 3315808.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646546.25
      sim_grid_pos_y: 3316090.5
    }
    terrain_level_point {
      sim_grid_pos_x: 646931.5
      sim_grid_pos_y: 3316088.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647001.688
      sim_grid_pos_y: 3315944.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647171
      sim_grid_pos_y: 3315950.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647213.125
      sim_grid_pos_y: 3315981
    }
    terrain_level_point {
      sim_grid_pos_x: 647222.75
      sim_grid_pos_y: 3316212.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647505.375
      sim_grid_pos_y: 3316926.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647739.625
      sim_grid_pos_y: 3317027.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647881.562
      sim_grid_pos_y: 3316991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647937.438
      sim_grid_pos_y: 3316929.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648096.062
      sim_grid_pos_y: 3316874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648199.812
      sim_grid_pos_y: 3316951.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648487.625
      sim_grid_pos_y: 3316951.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648428.625
      sim_grid_pos_y: 3316755.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648269
      sim_grid_pos_y: 3316734
    }
    terrain_level_point {
      sim_grid_pos_x: 647968.438
      sim_grid_pos_y: 3316521.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647972.312
      sim_grid_pos_y: 3315668
    }
    terrain_level_point {
      sim_grid_pos_x: 649396.188
      sim_grid_pos_y: 3315590.5
    }
    terrain_level_point {
      sim_grid_pos_x: 649388.125
      sim_grid_pos_y: 3314120.75
    }
    terrain_level_point {
      sim_grid_pos_x: 649458.625
      sim_grid_pos_y: 3313909
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 648850.812
      sim_grid_pos_y: 3313707.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648239.188
      sim_grid_pos_y: 3313721.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648075.75
      sim_grid_pos_y: 3314019
    }
    terrain_level_point {
      sim_grid_pos_x: 648185.938
      sim_grid_pos_y: 3314423.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648113.75
      sim_grid_pos_y: 3314887.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647904.625
      sim_grid_pos_y: 3315176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647343.375
      sim_grid_pos_y: 3315144.75
    }
    terrain_level_point {
      sim_grid_pos_x: 647227.875
      sim_grid_pos_y: 3314710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646635.062
      sim_grid_pos_y: 3314434.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646211
      sim_grid_pos_y: 3314954.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646067.125
      sim_grid_pos_y: 3315823.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646537.438
      sim_grid_pos_y: 3316121.25
    }
    terrain_level_point {
      sim_grid_pos_x: 646950.75
      sim_grid_pos_y: 3316119.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647020.625
      sim_grid_pos_y: 3315975.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647160.5
      sim_grid_pos_y: 3315980.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647183
      sim_grid_pos_y: 3315997
    }
    terrain_level_point {
      sim_grid_pos_x: 647192.25
      sim_grid_pos_y: 3316219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 647481.5
      sim_grid_pos_y: 3.31695e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 647737.062
      sim_grid_pos_y: 3317059.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647898.25
      sim_grid_pos_y: 3317019
    }
    terrain_level_point {
      sim_grid_pos_x: 647955
      sim_grid_pos_y: 3316955.75
    }
    terrain_level_point {
      sim_grid_pos_x: 648090.75
      sim_grid_pos_y: 3316909
    }
    terrain_level_point {
      sim_grid_pos_x: 648189.688
      sim_grid_pos_y: 3316982
    }
    terrain_level_point {
      sim_grid_pos_x: 648529
      sim_grid_pos_y: 3316982.25
    }
    terrain_level_point {
      sim_grid_pos_x: 648452.375
      sim_grid_pos_y: 3316727.5
    }
    terrain_level_point {
      sim_grid_pos_x: 648280.562
      sim_grid_pos_y: 3316704.5
    }
    terrain_level_point {
      sim_grid_pos_x: 647999.25
      sim_grid_pos_y: 3316506
    }
    terrain_level_point {
      sim_grid_pos_x: 648002.938
      sim_grid_pos_y: 3315697.25
    }
    terrain_level_point {
      sim_grid_pos_x: 649427.125
      sim_grid_pos_y: 3315619.5
    }
    terrain_level_point {
      sim_grid_pos_x: 649418.875
      sim_grid_pos_y: 3314125.5
    }
    terrain_level_point {
      sim_grid_pos_x: 649498
      sim_grid_pos_y: 3313888
    }
  }
}
