terrain_level_data {
  terrain_level: 20
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 787107.875
      sim_grid_pos_y: 1435786.38
    }
    terrain_level_point {
      sim_grid_pos_x: 785085.062
      sim_grid_pos_y: 1437041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 783030.938
      sim_grid_pos_y: 1435098.88
    }
    terrain_level_point {
      sim_grid_pos_x: 783041.312
      sim_grid_pos_y: 1434829.38
    }
    terrain_level_point {
      sim_grid_pos_x: 783667.562
      sim_grid_pos_y: 1434579.12
    }
    terrain_level_point {
      sim_grid_pos_x: 784178.75
      sim_grid_pos_y: 1434352
    }
    terrain_level_point {
      sim_grid_pos_x: 784516.438
      sim_grid_pos_y: 1434610.38
    }
    terrain_level_point {
      sim_grid_pos_x: 785015.812
      sim_grid_pos_y: 1434012
    }
    terrain_level_point {
      sim_grid_pos_x: 785371.688
      sim_grid_pos_y: 1434035.38
    }
    terrain_level_point {
      sim_grid_pos_x: 786296.875
      sim_grid_pos_y: 1434761.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 785383.188
      sim_grid_pos_y: 1434005.25
    }
    terrain_level_point {
      sim_grid_pos_x: 786318.688
      sim_grid_pos_y: 1434739.5
    }
    terrain_level_point {
      sim_grid_pos_x: 787153.438
      sim_grid_pos_y: 1435794.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785081.188
      sim_grid_pos_y: 1437079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782999.688
      sim_grid_pos_y: 1435111.62
    }
    terrain_level_point {
      sim_grid_pos_x: 783011.312
      sim_grid_pos_y: 1434808.25
    }
    terrain_level_point {
      sim_grid_pos_x: 783655.5
      sim_grid_pos_y: 1434550.88
    }
    terrain_level_point {
      sim_grid_pos_x: 784182.938
      sim_grid_pos_y: 1434316.5
    }
    terrain_level_point {
      sim_grid_pos_x: 784511.75
      sim_grid_pos_y: 1434568
    }
    terrain_level_point {
      sim_grid_pos_x: 785002.25
      sim_grid_pos_y: 1433980.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 785394.688
      sim_grid_pos_y: 1433975.25
    }
    terrain_level_point {
      sim_grid_pos_x: 786340.562
      sim_grid_pos_y: 1434717.62
    }
    terrain_level_point {
      sim_grid_pos_x: 787198.938
      sim_grid_pos_y: 1435802.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785077.25
      sim_grid_pos_y: 1437118.5
    }
    terrain_level_point {
      sim_grid_pos_x: 782968.375
      sim_grid_pos_y: 1435124.38
    }
    terrain_level_point {
      sim_grid_pos_x: 782981.375
      sim_grid_pos_y: 1434787.12
    }
    terrain_level_point {
      sim_grid_pos_x: 783643.5
      sim_grid_pos_y: 1434522.5
    }
    terrain_level_point {
      sim_grid_pos_x: 784187.125
      sim_grid_pos_y: 1434281
    }
    terrain_level_point {
      sim_grid_pos_x: 784507
      sim_grid_pos_y: 1434525.62
    }
    terrain_level_point {
      sim_grid_pos_x: 784988.625
      sim_grid_pos_y: 1433948.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 785406.188
      sim_grid_pos_y: 1433945.12
    }
    terrain_level_point {
      sim_grid_pos_x: 786362.438
      sim_grid_pos_y: 1434695.62
    }
    terrain_level_point {
      sim_grid_pos_x: 787244.438
      sim_grid_pos_y: 1435810.25
    }
    terrain_level_point {
      sim_grid_pos_x: 785073.312
      sim_grid_pos_y: 1437157.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782937.125
      sim_grid_pos_y: 1435137.12
    }
    terrain_level_point {
      sim_grid_pos_x: 782951.375
      sim_grid_pos_y: 1434766
    }
    terrain_level_point {
      sim_grid_pos_x: 783631.875
      sim_grid_pos_y: 1434494
    }
    terrain_level_point {
      sim_grid_pos_x: 784191.312
      sim_grid_pos_y: 1434245.5
    }
    terrain_level_point {
      sim_grid_pos_x: 784502.312
      sim_grid_pos_y: 1434483.38
    }
    terrain_level_point {
      sim_grid_pos_x: 784975.062
      sim_grid_pos_y: 1433916.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 785417.688
      sim_grid_pos_y: 1433915.12
    }
    terrain_level_point {
      sim_grid_pos_x: 786384.312
      sim_grid_pos_y: 1434673.62
    }
    terrain_level_point {
      sim_grid_pos_x: 787290
      sim_grid_pos_y: 1435818.12
    }
    terrain_level_point {
      sim_grid_pos_x: 785069.438
      sim_grid_pos_y: 1437195.75
    }
    terrain_level_point {
      sim_grid_pos_x: 782905.875
      sim_grid_pos_y: 1435149.88
    }
    terrain_level_point {
      sim_grid_pos_x: 782921.438
      sim_grid_pos_y: 1434744.88
    }
    terrain_level_point {
      sim_grid_pos_x: 783619.812
      sim_grid_pos_y: 1434465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 784195.5
      sim_grid_pos_y: 1434209.88
    }
    terrain_level_point {
      sim_grid_pos_x: 784497.562
      sim_grid_pos_y: 1434441
    }
    terrain_level_point {
      sim_grid_pos_x: 784961.438
      sim_grid_pos_y: 1433885.12
    }
  }
}
