terrain_level_data {
  terrain_level: 95
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1501407.38
      sim_grid_pos_y: 1200104.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1501754
      sim_grid_pos_y: 1200147.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1502532
      sim_grid_pos_y: 1200380.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1502561.25
      sim_grid_pos_y: 1200040.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1503013.38
      sim_grid_pos_y: 1199993.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503013.88
      sim_grid_pos_y: 1199199.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1502256.25
      sim_grid_pos_y: 1199438.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1501773.62
      sim_grid_pos_y: 1199446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1501332.25
      sim_grid_pos_y: 1199744.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1503065.25
      sim_grid_pos_y: 1199129.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1502248
      sim_grid_pos_y: 1199387.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1501757.5
      sim_grid_pos_y: 1199395.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1501275
      sim_grid_pos_y: 1199721.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1501364.75
      sim_grid_pos_y: 1200151.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1501743.5
      sim_grid_pos_y: 1200197.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1502577.62
      sim_grid_pos_y: 1200447.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502608.62
      sim_grid_pos_y: 1200087.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1503064.62
      sim_grid_pos_y: 1.20004e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1503116.5
      sim_grid_pos_y: 1199059.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1502239.62
      sim_grid_pos_y: 1199336.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1501741.5
      sim_grid_pos_y: 1199344.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1501217.88
      sim_grid_pos_y: 1199698.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1501322
      sim_grid_pos_y: 1200197.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1501732.88
      sim_grid_pos_y: 1200248
    }
    terrain_level_point {
      sim_grid_pos_x: 1502623.38
      sim_grid_pos_y: 1200514.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502656.12
      sim_grid_pos_y: 1200133.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503115.88
      sim_grid_pos_y: 1200086.25
    }
  }
}
terrain_level_data {
  terrain_level: 25
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1503697
      sim_grid_pos_y: 1197440.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1503722.25
      sim_grid_pos_y: 1197628
    }
    terrain_level_point {
      sim_grid_pos_x: 1503587.12
      sim_grid_pos_y: 1197658
    }
    terrain_level_point {
      sim_grid_pos_x: 1503277
      sim_grid_pos_y: 1197646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503299.75
      sim_grid_pos_y: 1197282.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1503790.62
      sim_grid_pos_y: 1197366.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503836.5
      sim_grid_pos_y: 1197707.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503596.5
      sim_grid_pos_y: 1197760.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503168.12
      sim_grid_pos_y: 1197745.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1503206.25
      sim_grid_pos_y: 1197135.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1503884.12
      sim_grid_pos_y: 1197293.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1503950.62
      sim_grid_pos_y: 1197787.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1503605.88
      sim_grid_pos_y: 1197863.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1503059.12
      sim_grid_pos_y: 1197844.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1503112.75
      sim_grid_pos_y: 1196988.38
    }
  }
}
terrain_level_data {
  terrain_level: 160
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1501866
      sim_grid_pos_y: 1200541
    }
    terrain_level_point {
      sim_grid_pos_x: 1501858.62
      sim_grid_pos_y: 1200716
    }
    terrain_level_point {
      sim_grid_pos_x: 1502031.75
      sim_grid_pos_y: 1200811.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1502173.12
      sim_grid_pos_y: 1200635.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1502029
      sim_grid_pos_y: 1200451.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1502042.5
      sim_grid_pos_y: 1200385.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1501816
      sim_grid_pos_y: 1200509.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1501806.12
      sim_grid_pos_y: 1200745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1502044.75
      sim_grid_pos_y: 1200876.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1502238.62
      sim_grid_pos_y: 1200635.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1502056
      sim_grid_pos_y: 1.20032e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1501766
      sim_grid_pos_y: 1200478.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1501753.5
      sim_grid_pos_y: 1200775.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1502057.75
      sim_grid_pos_y: 1200942.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1502304.12
      sim_grid_pos_y: 1200636
    }
  }
}
