terrain_level_data {
  terrain_level: 260
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1093765.25
      sim_grid_pos_y: 1675545.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1093370.75
      sim_grid_pos_y: 1675321.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1094491.62
      sim_grid_pos_y: 1673589.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1095834.5
      sim_grid_pos_y: 1673520.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098190.88
      sim_grid_pos_y: 1673568.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1098314
      sim_grid_pos_y: 1672839.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1101541.75
      sim_grid_pos_y: 1672955.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1101577.62
      sim_grid_pos_y: 1674101.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1100869.5
      sim_grid_pos_y: 1675401.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1100746.38
      sim_grid_pos_y: 1676486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098933.75
      sim_grid_pos_y: 1675998.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1095116.5
      sim_grid_pos_y: 1676058.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1094223.88
      sim_grid_pos_y: 1675566.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1101571.5
      sim_grid_pos_y: 1672926
    }
    terrain_level_point {
      sim_grid_pos_x: 1101608.62
      sim_grid_pos_y: 1674108.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1100899.38
      sim_grid_pos_y: 1675410.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1100772.88
      sim_grid_pos_y: 1676525.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098929.88
      sim_grid_pos_y: 1676029.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1095108.75
      sim_grid_pos_y: 1676089.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1094215.25
      sim_grid_pos_y: 1675596.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1093756.38
      sim_grid_pos_y: 1675575.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1093327.12
      sim_grid_pos_y: 1675331.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1094474.25
      sim_grid_pos_y: 1673559.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1095834.12
      sim_grid_pos_y: 1673489.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1098165
      sim_grid_pos_y: 1673537.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1098288.12
      sim_grid_pos_y: 1672808.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1101601.38
      sim_grid_pos_y: 1672896.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1101639.62
      sim_grid_pos_y: 1674116
    }
    terrain_level_point {
      sim_grid_pos_x: 1100929.25
      sim_grid_pos_y: 1675420.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1100799.5
      sim_grid_pos_y: 1676564.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098926
      sim_grid_pos_y: 1676060.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1095101
      sim_grid_pos_y: 1676120.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1094206.75
      sim_grid_pos_y: 1675627.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1093747.62
      sim_grid_pos_y: 1675605.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1093283.62
      sim_grid_pos_y: 1675342.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1094457
      sim_grid_pos_y: 1673529.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1095833.62
      sim_grid_pos_y: 1673459
    }
    terrain_level_point {
      sim_grid_pos_x: 1098139
      sim_grid_pos_y: 1673506.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1098262.25
      sim_grid_pos_y: 1672776.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1101631.25
      sim_grid_pos_y: 1672866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1101670.62
      sim_grid_pos_y: 1674123.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1100959.25
      sim_grid_pos_y: 1675429.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1100826
      sim_grid_pos_y: 1676603.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1098922.25
      sim_grid_pos_y: 1676091.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1095093.38
      sim_grid_pos_y: 1676151.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1094198.12
      sim_grid_pos_y: 1675657.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1093738.88
      sim_grid_pos_y: 1675636.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1093240.12
      sim_grid_pos_y: 1675353
    }
    terrain_level_point {
      sim_grid_pos_x: 1094439.75
      sim_grid_pos_y: 1673499.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1095833.12
      sim_grid_pos_y: 1673428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1098113.12
      sim_grid_pos_y: 1673475
    }
    terrain_level_point {
      sim_grid_pos_x: 1098236.5
      sim_grid_pos_y: 1672744.75
    }
  }
}
