terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1129772.25
      sim_grid_pos_y: 1460420.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1129666.25
      sim_grid_pos_y: 1460753.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1129814.88
      sim_grid_pos_y: 1460865.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1126747.12
      sim_grid_pos_y: 1467890.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1126558.12
      sim_grid_pos_y: 1467862.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1126114.12
      sim_grid_pos_y: 1468920.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1124282.12
      sim_grid_pos_y: 1468285.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1124566.5
      sim_grid_pos_y: 1465042.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1124675
      sim_grid_pos_y: 1464481
    }
    terrain_level_point {
      sim_grid_pos_x: 1125187.38
      sim_grid_pos_y: 1463236.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1124507.75
      sim_grid_pos_y: 1462965.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1124747.88
      sim_grid_pos_y: 1462723.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1125508.88
      sim_grid_pos_y: 1461123.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1125758.5
      sim_grid_pos_y: 1460469.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1127339.75
      sim_grid_pos_y: 1457889.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1129807.12
      sim_grid_pos_y: 1460412.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1129702.12
      sim_grid_pos_y: 1460742.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1129852.88
      sim_grid_pos_y: 1460855.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1126765.88
      sim_grid_pos_y: 1467923.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1126577.25
      sim_grid_pos_y: 1467896.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1126131.25
      sim_grid_pos_y: 1468958.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1124249.38
      sim_grid_pos_y: 1468306.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1124536
      sim_grid_pos_y: 1465038.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1124645.38
      sim_grid_pos_y: 1464472.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1125147.12
      sim_grid_pos_y: 1463253.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1124453.25
      sim_grid_pos_y: 1462977
    }
    terrain_level_point {
      sim_grid_pos_x: 1124722.38
      sim_grid_pos_y: 1462705.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1125480.62
      sim_grid_pos_y: 1461111.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1125730.88
      sim_grid_pos_y: 1460456.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1127334.25
      sim_grid_pos_y: 1457839.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1129842
      sim_grid_pos_y: 1460404.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1129738.12
      sim_grid_pos_y: 1460730.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1129890.75
      sim_grid_pos_y: 1460845.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1126784.75
      sim_grid_pos_y: 1467957.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1126596.38
      sim_grid_pos_y: 1467930.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1126148.5
      sim_grid_pos_y: 1468997.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1124216.75
      sim_grid_pos_y: 1468327.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1124505.5
      sim_grid_pos_y: 1465034.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1124615.75
      sim_grid_pos_y: 1464463.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1125106.88
      sim_grid_pos_y: 1463270.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1124398.62
      sim_grid_pos_y: 1462988.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1124696.88
      sim_grid_pos_y: 1462687.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1125452.25
      sim_grid_pos_y: 1461099.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1125703.12
      sim_grid_pos_y: 1460442.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1127328.88
      sim_grid_pos_y: 1457789.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1129876.88
      sim_grid_pos_y: 1460396.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1129774
      sim_grid_pos_y: 1460719.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1129928.75
      sim_grid_pos_y: 1460835.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1126803.5
      sim_grid_pos_y: 1467991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1126615.5
      sim_grid_pos_y: 1467964.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1126165.62
      sim_grid_pos_y: 1469036
    }
    terrain_level_point {
      sim_grid_pos_x: 1124184
      sim_grid_pos_y: 1468348.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1124475
      sim_grid_pos_y: 1.46503e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1124586.12
      sim_grid_pos_y: 1464454.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1125066.5
      sim_grid_pos_y: 1463287.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1124344.12
      sim_grid_pos_y: 1462999.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1124671.38
      sim_grid_pos_y: 1462669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1125424
      sim_grid_pos_y: 1461087.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1125675.38
      sim_grid_pos_y: 1460429
    }
    terrain_level_point {
      sim_grid_pos_x: 1127323.5
      sim_grid_pos_y: 1457739.62
    }
  }
}
