terrain_level_data {
  terrain_level: 460
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1133574.75
      sim_grid_pos_y: 1697919.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133557.5
      sim_grid_pos_y: 1697806.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133519.75
      sim_grid_pos_y: 1697730.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133490.38
      sim_grid_pos_y: 1697630.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133503.12
      sim_grid_pos_y: 1697442.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133532.88
      sim_grid_pos_y: 1697311.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133615.75
      sim_grid_pos_y: 1697136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133741.62
      sim_grid_pos_y: 1697006.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133936.62
      sim_grid_pos_y: 1696980.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133983.25
      sim_grid_pos_y: 1696930.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134606.5
      sim_grid_pos_y: 1696794.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134699.75
      sim_grid_pos_y: 1696536.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134895.88
      sim_grid_pos_y: 1696370.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135106.75
      sim_grid_pos_y: 1696573
    }
    terrain_level_point {
      sim_grid_pos_x: 1135461.62
      sim_grid_pos_y: 1696774.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135692.38
      sim_grid_pos_y: 1697075.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135715.12
      sim_grid_pos_y: 1697279.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135819.12
      sim_grid_pos_y: 1697446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135870.25
      sim_grid_pos_y: 1697524.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135981.25
      sim_grid_pos_y: 1697589
    }
    terrain_level_point {
      sim_grid_pos_x: 1135899.38
      sim_grid_pos_y: 1697927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135984.5
      sim_grid_pos_y: 1698282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136082.62
      sim_grid_pos_y: 1698617.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135880.88
      sim_grid_pos_y: 1698991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135824.5
      sim_grid_pos_y: 1699242.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135672.75
      sim_grid_pos_y: 1699234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135643.38
      sim_grid_pos_y: 1699155.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135474.12
      sim_grid_pos_y: 1699191.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135275.25
      sim_grid_pos_y: 1699230.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134885.5
      sim_grid_pos_y: 1699242
    }
    terrain_level_point {
      sim_grid_pos_x: 1134743.5
      sim_grid_pos_y: 1699209.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134652.12
      sim_grid_pos_y: 1699160.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134534.62
      sim_grid_pos_y: 1699096.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134412.25
      sim_grid_pos_y: 1699056.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134342.75
      sim_grid_pos_y: 1699026.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134227.12
      sim_grid_pos_y: 1698892.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133992.75
      sim_grid_pos_y: 1698833.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133895.62
      sim_grid_pos_y: 1698800.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133843.88
      sim_grid_pos_y: 1698744.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133817.75
      sim_grid_pos_y: 1698692.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133819.25
      sim_grid_pos_y: 1698532.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133784.12
      sim_grid_pos_y: 1698302.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133660.5
      sim_grid_pos_y: 1698155.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133591.62
      sim_grid_pos_y: 1698072.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1135125.25
      sim_grid_pos_y: 1696548.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135482.25
      sim_grid_pos_y: 1696750.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135722
      sim_grid_pos_y: 1697063.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135745
      sim_grid_pos_y: 1697268.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135845
      sim_grid_pos_y: 1697430.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135891.88
      sim_grid_pos_y: 1697501.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136016.5
      sim_grid_pos_y: 1697573.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135931
      sim_grid_pos_y: 1697927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1136014.12
      sim_grid_pos_y: 1698274.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136115.62
      sim_grid_pos_y: 1698621
    }
    terrain_level_point {
      sim_grid_pos_x: 1.13591e+06
      sim_grid_pos_y: 1699002.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135848.75
      sim_grid_pos_y: 1699274.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135650.88
      sim_grid_pos_y: 1699264.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135623.75
      sim_grid_pos_y: 1699191.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135480.25
      sim_grid_pos_y: 1699222
    }
    terrain_level_point {
      sim_grid_pos_x: 1135278.75
      sim_grid_pos_y: 1699261.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134882.5
      sim_grid_pos_y: 1699272.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134732.62
      sim_grid_pos_y: 1699238.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134637.5
      sim_grid_pos_y: 1699188
    }
    terrain_level_point {
      sim_grid_pos_x: 1134522.25
      sim_grid_pos_y: 1699125
    }
    terrain_level_point {
      sim_grid_pos_x: 1134401.38
      sim_grid_pos_y: 1699084.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134324.12
      sim_grid_pos_y: 1699052.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134210.12
      sim_grid_pos_y: 1698919.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133984
      sim_grid_pos_y: 1698862.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133878.38
      sim_grid_pos_y: 1698827.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133818.38
      sim_grid_pos_y: 1698762.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133787
      sim_grid_pos_y: 1698699.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133788.38
      sim_grid_pos_y: 1698534.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133755
      sim_grid_pos_y: 1698315.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133637
      sim_grid_pos_y: 1698175.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133562
      sim_grid_pos_y: 1698085.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133544.25
      sim_grid_pos_y: 1697923
    }
    terrain_level_point {
      sim_grid_pos_x: 1133527.88
      sim_grid_pos_y: 1697816.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133491
      sim_grid_pos_y: 1697741.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133459.38
      sim_grid_pos_y: 1697634
    }
    terrain_level_point {
      sim_grid_pos_x: 1133472.62
      sim_grid_pos_y: 1697438.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133503.62
      sim_grid_pos_y: 1697301.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133590.12
      sim_grid_pos_y: 1697118.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133726.88
      sim_grid_pos_y: 1696977.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133921.62
      sim_grid_pos_y: 1696951.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133967.38
      sim_grid_pos_y: 1696902.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134583.38
      sim_grid_pos_y: 1696768.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134673.62
      sim_grid_pos_y: 1696518.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134897.12
      sim_grid_pos_y: 1696329
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1135143.75
      sim_grid_pos_y: 1696523.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135502.88
      sim_grid_pos_y: 1696727
    }
    terrain_level_point {
      sim_grid_pos_x: 1135751.62
      sim_grid_pos_y: 1697051.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1135774.75
      sim_grid_pos_y: 1697258.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135871.12
      sim_grid_pos_y: 1697413.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135913.62
      sim_grid_pos_y: 1697478.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136051.75
      sim_grid_pos_y: 1697558.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135962.62
      sim_grid_pos_y: 1697927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136043.88
      sim_grid_pos_y: 1698266.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136148.75
      sim_grid_pos_y: 1698624.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1135939.12
      sim_grid_pos_y: 1699013.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135873.12
      sim_grid_pos_y: 1699306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135629.12
      sim_grid_pos_y: 1699294.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135604.12
      sim_grid_pos_y: 1699227
    }
    terrain_level_point {
      sim_grid_pos_x: 1135486.38
      sim_grid_pos_y: 1699252.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135282.12
      sim_grid_pos_y: 1699292
    }
    terrain_level_point {
      sim_grid_pos_x: 1134879.5
      sim_grid_pos_y: 1699303.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134721.88
      sim_grid_pos_y: 1699267.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134622.88
      sim_grid_pos_y: 1699215
    }
    terrain_level_point {
      sim_grid_pos_x: 1.13451e+06
      sim_grid_pos_y: 1699153.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134390.62
      sim_grid_pos_y: 1699113.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134305.5
      sim_grid_pos_y: 1699077.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134193.12
      sim_grid_pos_y: 1698947.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133975.38
      sim_grid_pos_y: 1698892.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133861
      sim_grid_pos_y: 1698853.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133792.88
      sim_grid_pos_y: 1698779.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133756.12
      sim_grid_pos_y: 1698707.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133757.62
      sim_grid_pos_y: 1698537
    }
    terrain_level_point {
      sim_grid_pos_x: 1133725.88
      sim_grid_pos_y: 1698329
    }
    terrain_level_point {
      sim_grid_pos_x: 1133613.38
      sim_grid_pos_y: 1698195.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133532.5
      sim_grid_pos_y: 1698097.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133513.75
      sim_grid_pos_y: 1697927.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1133498.12
      sim_grid_pos_y: 1697825.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133462.25
      sim_grid_pos_y: 1697752.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133428.25
      sim_grid_pos_y: 1697637.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133442.12
      sim_grid_pos_y: 1697433.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133474.38
      sim_grid_pos_y: 1697291.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133564.5
      sim_grid_pos_y: 1697100.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133712.25
      sim_grid_pos_y: 1696948.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133906.75
      sim_grid_pos_y: 1696922.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133951.5
      sim_grid_pos_y: 1696874.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134560.12
      sim_grid_pos_y: 1696741.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134647.5
      sim_grid_pos_y: 1.6965e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1134898.5
      sim_grid_pos_y: 1696287.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1135162.38
      sim_grid_pos_y: 1696498.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135523.5
      sim_grid_pos_y: 1696703.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1135781.25
      sim_grid_pos_y: 1697039.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135804.5
      sim_grid_pos_y: 1697248.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135896.75
      sim_grid_pos_y: 1697396.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135935.38
      sim_grid_pos_y: 1697455.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1136087.12
      sim_grid_pos_y: 1697543.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135994.25
      sim_grid_pos_y: 1697927.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1136073.62
      sim_grid_pos_y: 1698258.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1136181.88
      sim_grid_pos_y: 1698627.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1135968.12
      sim_grid_pos_y: 1699024.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1135897.5
      sim_grid_pos_y: 1699338.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135607.38
      sim_grid_pos_y: 1699324
    }
    terrain_level_point {
      sim_grid_pos_x: 1135584.62
      sim_grid_pos_y: 1699262.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1135492.62
      sim_grid_pos_y: 1699282.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1135285.5
      sim_grid_pos_y: 1699322.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1134876.5
      sim_grid_pos_y: 1699334.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134711
      sim_grid_pos_y: 1699296.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134608.25
      sim_grid_pos_y: 1699242.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1134497.62
      sim_grid_pos_y: 1699181.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1134379.75
      sim_grid_pos_y: 1699142.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1134286.88
      sim_grid_pos_y: 1699103.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1134176.12
      sim_grid_pos_y: 1698974.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133966.75
      sim_grid_pos_y: 1698921.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1133843.75
      sim_grid_pos_y: 1698880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133767.25
      sim_grid_pos_y: 1698797.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133725.25
      sim_grid_pos_y: 1698714.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133726.88
      sim_grid_pos_y: 1698539.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133696.75
      sim_grid_pos_y: 1698342.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133589.75
      sim_grid_pos_y: 1698214.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133502.88
      sim_grid_pos_y: 1698110.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133483.25
      sim_grid_pos_y: 1697931
    }
    terrain_level_point {
      sim_grid_pos_x: 1133468.5
      sim_grid_pos_y: 1697834.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133433.5
      sim_grid_pos_y: 1697763.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1133397.25
      sim_grid_pos_y: 1697640.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1133411.62
      sim_grid_pos_y: 1697429.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1133445.12
      sim_grid_pos_y: 1697281.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133538.88
      sim_grid_pos_y: 1697083
    }
    terrain_level_point {
      sim_grid_pos_x: 1133697.62
      sim_grid_pos_y: 1696919.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1133891.88
      sim_grid_pos_y: 1696893.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1133935.62
      sim_grid_pos_y: 1696846.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134537
      sim_grid_pos_y: 1696715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1134621.38
      sim_grid_pos_y: 1696481.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1134899.75
      sim_grid_pos_y: 1696246.12
    }
  }
}
