terrain_level_data {
  terrain_level: 72
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2039691.5
      sim_grid_pos_y: 1614047
    }
    terrain_level_point {
      sim_grid_pos_x: 2.03981e+06
      sim_grid_pos_y: 1613889.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2040022.38
      sim_grid_pos_y: 1614094.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039928.5
      sim_grid_pos_y: 1614238
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2040088.5
      sim_grid_pos_y: 1614087.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039940.38
      sim_grid_pos_y: 1614313.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039620.75
      sim_grid_pos_y: 1614055.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039803.88
      sim_grid_pos_y: 1613812.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2040154.62
      sim_grid_pos_y: 1614080.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039952.25
      sim_grid_pos_y: 1614388.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.03955e+06
      sim_grid_pos_y: 1614064.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039797.88
      sim_grid_pos_y: 1613735
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2040220.75
      sim_grid_pos_y: 1614072.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039964.12
      sim_grid_pos_y: 1614464.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039479.25
      sim_grid_pos_y: 1614073.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039791.75
      sim_grid_pos_y: 1613657.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2040286.88
      sim_grid_pos_y: 1614065.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039975.88
      sim_grid_pos_y: 1614539.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039408.5
      sim_grid_pos_y: 1614082.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2039785.62
      sim_grid_pos_y: 1613580.5
    }
  }
}
terrain_level_data {
  terrain_level: 105
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2039249.62
      sim_grid_pos_y: 1612992.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039313.88
      sim_grid_pos_y: 1613280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039605.75
      sim_grid_pos_y: 1613543.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039767.12
      sim_grid_pos_y: 1613380.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040027.5
      sim_grid_pos_y: 1613358.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2040002.38
      sim_grid_pos_y: 1613181.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039726.62
      sim_grid_pos_y: 1613058.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039732.25
      sim_grid_pos_y: 1612725.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039549.88
      sim_grid_pos_y: 1612729.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039498.25
      sim_grid_pos_y: 1612859.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039274.88
      sim_grid_pos_y: 1612917.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2039784.38
      sim_grid_pos_y: 1612673.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039514.75
      sim_grid_pos_y: 1612679.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039460.25
      sim_grid_pos_y: 1612816.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039235.12
      sim_grid_pos_y: 1612874.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039196.5
      sim_grid_pos_y: 1612989.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039267.5
      sim_grid_pos_y: 1613307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039607.75
      sim_grid_pos_y: 1613614.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039790.25
      sim_grid_pos_y: 1.61343e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2040085.88
      sim_grid_pos_y: 1613405.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2040049.12
      sim_grid_pos_y: 1613146.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039778.5
      sim_grid_pos_y: 1613025.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2039836.5
      sim_grid_pos_y: 1612621.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039479.62
      sim_grid_pos_y: 1612628.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039422.25
      sim_grid_pos_y: 1612773.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039195.5
      sim_grid_pos_y: 1612831.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039143.38
      sim_grid_pos_y: 1612986.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039221
      sim_grid_pos_y: 1613334.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039609.75
      sim_grid_pos_y: 1613684.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039813.38
      sim_grid_pos_y: 1613479.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040144.38
      sim_grid_pos_y: 1613451.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2040095.88
      sim_grid_pos_y: 1613111.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039830.38
      sim_grid_pos_y: 1612992.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2039888.62
      sim_grid_pos_y: 1612568.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039444.62
      sim_grid_pos_y: 1612578.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039384.12
      sim_grid_pos_y: 1612730.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2039155.75
      sim_grid_pos_y: 1612789.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039090.25
      sim_grid_pos_y: 1612984
    }
    terrain_level_point {
      sim_grid_pos_x: 2039174.5
      sim_grid_pos_y: 1613362
    }
    terrain_level_point {
      sim_grid_pos_x: 2039611.75
      sim_grid_pos_y: 1613755.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2039836.5
      sim_grid_pos_y: 1613529
    }
    terrain_level_point {
      sim_grid_pos_x: 2040202.75
      sim_grid_pos_y: 1613498.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2040142.75
      sim_grid_pos_y: 1613075.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2039882.12
      sim_grid_pos_y: 1612959.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2039940.88
      sim_grid_pos_y: 1612516.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2039409.5
      sim_grid_pos_y: 1612527.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039346.12
      sim_grid_pos_y: 1612687.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2039116
      sim_grid_pos_y: 1612746.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039037
      sim_grid_pos_y: 1612981.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2039128
      sim_grid_pos_y: 1613389.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2039613.62
      sim_grid_pos_y: 1613826.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2039859.62
      sim_grid_pos_y: 1613578.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2040261.12
      sim_grid_pos_y: 1613544.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2040189.5
      sim_grid_pos_y: 1613040.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2039934
      sim_grid_pos_y: 1612926.62
    }
  }
}
