terrain_level_data {
  terrain_level: 500
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2189953.25
      sim_grid_pos_y: 1762316.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189966
      sim_grid_pos_y: 1762746.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2190119.25
      sim_grid_pos_y: 1762850.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2190323.5
      sim_grid_pos_y: 1762822
    }
    terrain_level_point {
      sim_grid_pos_x: 2190344.75
      sim_grid_pos_y: 1762497
    }
    terrain_level_point {
      sim_grid_pos_x: 2190202.25
      sim_grid_pos_y: 1762309
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2190227.25
      sim_grid_pos_y: 1762257
    }
    terrain_level_point {
      sim_grid_pos_x: 2189900.5
      sim_grid_pos_y: 1762267.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189915.75
      sim_grid_pos_y: 1762774.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2190106.75
      sim_grid_pos_y: 1762904.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2190372
      sim_grid_pos_y: 1762867
    }
    terrain_level_point {
      sim_grid_pos_x: 2190397.25
      sim_grid_pos_y: 1762481.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2190252
      sim_grid_pos_y: 1762204.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2189847.75
      sim_grid_pos_y: 1762217.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2189865.25
      sim_grid_pos_y: 1762801.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2190094.25
      sim_grid_pos_y: 1762957.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2190420.5
      sim_grid_pos_y: 1762912
    }
    terrain_level_point {
      sim_grid_pos_x: 2190449.75
      sim_grid_pos_y: 1762465.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2190277
      sim_grid_pos_y: 1762152.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2189795
      sim_grid_pos_y: 1762167.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189814.75
      sim_grid_pos_y: 1762829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2190082
      sim_grid_pos_y: 1763011.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2190468.75
      sim_grid_pos_y: 1762956.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2190502
      sim_grid_pos_y: 1762449.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2190301.75
      sim_grid_pos_y: 1762100.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189742.25
      sim_grid_pos_y: 1762118.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189764.25
      sim_grid_pos_y: 1762857.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2190069.5
      sim_grid_pos_y: 1763064.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2190517.25
      sim_grid_pos_y: 1763001.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2190554.5
      sim_grid_pos_y: 1762434.12
    }
  }
}
terrain_level_data {
  terrain_level: 490
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2190836
      sim_grid_pos_y: 1762895.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2190837
      sim_grid_pos_y: 1763088.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2191032.25
      sim_grid_pos_y: 1763083.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2191024.25
      sim_grid_pos_y: 1762899.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2190784.25
      sim_grid_pos_y: 1762842.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2190786
      sim_grid_pos_y: 1763140.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2191085.5
      sim_grid_pos_y: 1763133.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2191073.25
      sim_grid_pos_y: 1762849.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2190732.75
      sim_grid_pos_y: 1762790.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2190735
      sim_grid_pos_y: 1763193.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2191139
      sim_grid_pos_y: 1763183.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2191122.5
      sim_grid_pos_y: 1762799.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2190681.25
      sim_grid_pos_y: 1762738.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2190684
      sim_grid_pos_y: 1763245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2191192.5
      sim_grid_pos_y: 1763233.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2191171.5
      sim_grid_pos_y: 1762748.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2190629.75
      sim_grid_pos_y: 1762685.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2190633
      sim_grid_pos_y: 1763298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2191246
      sim_grid_pos_y: 1763283.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2191220.75
      sim_grid_pos_y: 1762698.75
    }
  }
}
terrain_level_data {
  terrain_level: 375
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2189645.75
      sim_grid_pos_y: 1761685.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189613
      sim_grid_pos_y: 1761807.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2189679.5
      sim_grid_pos_y: 1761905.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2189806.5
      sim_grid_pos_y: 1761920.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2189884
      sim_grid_pos_y: 1761839.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2189856
      sim_grid_pos_y: 1761697.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189760.25
      sim_grid_pos_y: 1761593.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2189765.25
      sim_grid_pos_y: 1761523.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189600.5
      sim_grid_pos_y: 1761656.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2189557.25
      sim_grid_pos_y: 1761816.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189650.25
      sim_grid_pos_y: 1761953.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189826
      sim_grid_pos_y: 1761974.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189939.25
      sim_grid_pos_y: 1761855.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189903.5
      sim_grid_pos_y: 1761673.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2189770.5
      sim_grid_pos_y: 1761453.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189555.25
      sim_grid_pos_y: 1761627
    }
    terrain_level_point {
      sim_grid_pos_x: 2189501.75
      sim_grid_pos_y: 1761826.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189621
      sim_grid_pos_y: 1762001.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2189845.25
      sim_grid_pos_y: 1762028.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2189994.75
      sim_grid_pos_y: 1761871.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2189951
      sim_grid_pos_y: 1761649
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2189775.75
      sim_grid_pos_y: 1761383.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189510.25
      sim_grid_pos_y: 1761597.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2189446
      sim_grid_pos_y: 1761835.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2189591.75
      sim_grid_pos_y: 1.76205e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2189864.75
      sim_grid_pos_y: 1762082.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2190050.25
      sim_grid_pos_y: 1761888
    }
    terrain_level_point {
      sim_grid_pos_x: 2189998.5
      sim_grid_pos_y: 1761624.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2189780.75
      sim_grid_pos_y: 1761313
    }
    terrain_level_point {
      sim_grid_pos_x: 2189465
      sim_grid_pos_y: 1761568.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189390.5
      sim_grid_pos_y: 1761844.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2189562.5
      sim_grid_pos_y: 1762098.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2189884
      sim_grid_pos_y: 1762136.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2190105.5
      sim_grid_pos_y: 1761904.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2190046
      sim_grid_pos_y: 1761600.88
    }
  }
}
