terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 16003.0312
      sim_grid_pos_y: 3262542.25
    }
    terrain_level_point {
      sim_grid_pos_x: 19729.2148
      sim_grid_pos_y: 3257677
    }
    terrain_level_point {
      sim_grid_pos_x: 20098.6758
      sim_grid_pos_y: 3256850.75
    }
    terrain_level_point {
      sim_grid_pos_x: 20610.4785
      sim_grid_pos_y: 3256609.75
    }
    terrain_level_point {
      sim_grid_pos_x: 21130.375
      sim_grid_pos_y: 3255538.5
    }
    terrain_level_point {
      sim_grid_pos_x: 21562.8789
      sim_grid_pos_y: 3255333.75
    }
    terrain_level_point {
      sim_grid_pos_x: 22549.0859
      sim_grid_pos_y: 3256094
    }
    terrain_level_point {
      sim_grid_pos_x: 20717.916
      sim_grid_pos_y: 3258438.75
    }
    terrain_level_point {
      sim_grid_pos_x: 20859.5137
      sim_grid_pos_y: 3259567.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20552.6094
      sim_grid_pos_y: 3259696.25
    }
    terrain_level_point {
      sim_grid_pos_x: 20785.0781
      sim_grid_pos_y: 3261263.75
    }
    terrain_level_point {
      sim_grid_pos_x: 19784.75
      sim_grid_pos_y: 3261382.5
    }
    terrain_level_point {
      sim_grid_pos_x: 19116.8203
      sim_grid_pos_y: 3260857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 16998.3457
      sim_grid_pos_y: 3263511
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 22592.3789
      sim_grid_pos_y: 3256088.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20750.0391
      sim_grid_pos_y: 3258447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20892.9297
      sim_grid_pos_y: 3259586.75
    }
    terrain_level_point {
      sim_grid_pos_x: 20586.5508
      sim_grid_pos_y: 3259715.25
    }
    terrain_level_point {
      sim_grid_pos_x: 20820.1484
      sim_grid_pos_y: 3261290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 19775.75
      sim_grid_pos_y: 3261414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 19121.8203
      sim_grid_pos_y: 3260900.75
    }
    terrain_level_point {
      sim_grid_pos_x: 17001.2109
      sim_grid_pos_y: 3263556.75
    }
    terrain_level_point {
      sim_grid_pos_x: 15962
      sim_grid_pos_y: 3262545.25
    }
    terrain_level_point {
      sim_grid_pos_x: 19702.6
      sim_grid_pos_y: 3257661.25
    }
    terrain_level_point {
      sim_grid_pos_x: 20075.2598
      sim_grid_pos_y: 3256828
    }
    terrain_level_point {
      sim_grid_pos_x: 20587.5508
      sim_grid_pos_y: 3256586.5
    }
    terrain_level_point {
      sim_grid_pos_x: 21107.4199
      sim_grid_pos_y: 3255515.5
    }
    terrain_level_point {
      sim_grid_pos_x: 21566.7402
      sim_grid_pos_y: 3255297.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 22635.6797
      sim_grid_pos_y: 3256083
    }
    terrain_level_point {
      sim_grid_pos_x: 20782.1484
      sim_grid_pos_y: 3258456.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20926.3594
      sim_grid_pos_y: 3259606
    }
    terrain_level_point {
      sim_grid_pos_x: 20620.4688
      sim_grid_pos_y: 3259734.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20855.2188
      sim_grid_pos_y: 3261317.25
    }
    terrain_level_point {
      sim_grid_pos_x: 19766.75
      sim_grid_pos_y: 3261446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 19126.8203
      sim_grid_pos_y: 3260943.75
    }
    terrain_level_point {
      sim_grid_pos_x: 17004.0801
      sim_grid_pos_y: 3263602.5
    }
    terrain_level_point {
      sim_grid_pos_x: 15920.9697
      sim_grid_pos_y: 3262548.25
    }
    terrain_level_point {
      sim_grid_pos_x: 19675.9902
      sim_grid_pos_y: 3257645.25
    }
    terrain_level_point {
      sim_grid_pos_x: 20051.8301
      sim_grid_pos_y: 3256805
    }
    terrain_level_point {
      sim_grid_pos_x: 20564.6289
      sim_grid_pos_y: 3256563.25
    }
    terrain_level_point {
      sim_grid_pos_x: 21084.4805
      sim_grid_pos_y: 3255492.25
    }
    terrain_level_point {
      sim_grid_pos_x: 21570.5898
      sim_grid_pos_y: 3255262
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 22678.9688
      sim_grid_pos_y: 3256077.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20814.2598
      sim_grid_pos_y: 3258465.25
    }
    terrain_level_point {
      sim_grid_pos_x: 20959.7793
      sim_grid_pos_y: 3259625.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20654.4102
      sim_grid_pos_y: 3259753.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20890.2891
      sim_grid_pos_y: 3261344.25
    }
    terrain_level_point {
      sim_grid_pos_x: 19757.7402
      sim_grid_pos_y: 3261478.5
    }
    terrain_level_point {
      sim_grid_pos_x: 19131.8086
      sim_grid_pos_y: 3260986.75
    }
    terrain_level_point {
      sim_grid_pos_x: 17006.9395
      sim_grid_pos_y: 3263648
    }
    terrain_level_point {
      sim_grid_pos_x: 15879.9395
      sim_grid_pos_y: 3262551.25
    }
    terrain_level_point {
      sim_grid_pos_x: 19649.3984
      sim_grid_pos_y: 3257629.5
    }
    terrain_level_point {
      sim_grid_pos_x: 20028.4102
      sim_grid_pos_y: 3256782
    }
    terrain_level_point {
      sim_grid_pos_x: 20541.7
      sim_grid_pos_y: 3.25654e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 21061.5293
      sim_grid_pos_y: 3255469
    }
    terrain_level_point {
      sim_grid_pos_x: 21574.4492
      sim_grid_pos_y: 3255226
    }
  }
}
