terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2643672.5
      sim_grid_pos_y: 412596.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2643904
      sim_grid_pos_y: 412634.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2643991
      sim_grid_pos_y: 413085.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2644293
      sim_grid_pos_y: 413651.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2643826
      sim_grid_pos_y: 413949.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2643507
      sim_grid_pos_y: 413314.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2643222.75
      sim_grid_pos_y: 413510.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2643103.25
      sim_grid_pos_y: 413288.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2643301.75
      sim_grid_pos_y: 412878.312
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2643947.5
      sim_grid_pos_y: 412590.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2644039.75
      sim_grid_pos_y: 413068.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2644360.5
      sim_grid_pos_y: 413669.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2643805.75
      sim_grid_pos_y: 414023.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2643487.5
      sim_grid_pos_y: 413390.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2643204.75
      sim_grid_pos_y: 413585.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2643045.75
      sim_grid_pos_y: 413289.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2643261
      sim_grid_pos_y: 412844.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2643659
      sim_grid_pos_y: 412542.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2643991
      sim_grid_pos_y: 412545.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2644088.75
      sim_grid_pos_y: 413051.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2644428
      sim_grid_pos_y: 413687.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2643785.5
      sim_grid_pos_y: 414097.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2643468.25
      sim_grid_pos_y: 413465.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2643186.75
      sim_grid_pos_y: 413660.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2642988.25
      sim_grid_pos_y: 413291.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2.64322e+06
      sim_grid_pos_y: 412811.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2643645.5
      sim_grid_pos_y: 412488.062
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2644034.75
      sim_grid_pos_y: 412500.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2644137.5
      sim_grid_pos_y: 413033.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2644495.5
      sim_grid_pos_y: 413704.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2643765
      sim_grid_pos_y: 414171.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2643449
      sim_grid_pos_y: 413541.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2643168.75
      sim_grid_pos_y: 413734.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2642930.75
      sim_grid_pos_y: 413292.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2643179.25
      sim_grid_pos_y: 412778.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2643632.25
      sim_grid_pos_y: 412433.844
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2644078.25
      sim_grid_pos_y: 412456.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2644186.25
      sim_grid_pos_y: 413016.438
    }
    terrain_level_point {
      sim_grid_pos_x: 2644563.25
      sim_grid_pos_y: 413722.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2643744.75
      sim_grid_pos_y: 414245
    }
    terrain_level_point {
      sim_grid_pos_x: 2643429.5
      sim_grid_pos_y: 413617.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2643150.75
      sim_grid_pos_y: 413809.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2642873
      sim_grid_pos_y: 413293.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2643138.5
      sim_grid_pos_y: 412744.812
    }
    terrain_level_point {
      sim_grid_pos_x: 2643618.75
      sim_grid_pos_y: 412379.656
    }
  }
}
