terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 355913.562
      sim_grid_pos_y: 3008593
    }
    terrain_level_point {
      sim_grid_pos_x: 358268.188
      sim_grid_pos_y: 3007682.5
    }
    terrain_level_point {
      sim_grid_pos_x: 356367.406
      sim_grid_pos_y: 3006038.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354659.469
      sim_grid_pos_y: 3005926.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353898.5
      sim_grid_pos_y: 3005959
    }
    terrain_level_point {
      sim_grid_pos_x: 353769.969
      sim_grid_pos_y: 3005745.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353161.312
      sim_grid_pos_y: 3005628.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353158.562
      sim_grid_pos_y: 3005717
    }
    terrain_level_point {
      sim_grid_pos_x: 353326.344
      sim_grid_pos_y: 3005822.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353148.594
      sim_grid_pos_y: 3006227.25
    }
    terrain_level_point {
      sim_grid_pos_x: 352986.031
      sim_grid_pos_y: 3006497.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353370.094
      sim_grid_pos_y: 3007239.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353335.031
      sim_grid_pos_y: 3007423.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353755.062
      sim_grid_pos_y: 3007955.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353975.344
      sim_grid_pos_y: 3007784
    }
    terrain_level_point {
      sim_grid_pos_x: 354474
      sim_grid_pos_y: 3008065.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354607.469
      sim_grid_pos_y: 3008208
    }
    terrain_level_point {
      sim_grid_pos_x: 354717.156
      sim_grid_pos_y: 3008207.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354899.781
      sim_grid_pos_y: 3008259.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355046.75
      sim_grid_pos_y: 3008273.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355124.375
      sim_grid_pos_y: 3008228
    }
    terrain_level_point {
      sim_grid_pos_x: 355205.938
      sim_grid_pos_y: 3008397.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355304.969
      sim_grid_pos_y: 3008467.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355401.781
      sim_grid_pos_y: 3008380.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355538.938
      sim_grid_pos_y: 3008417.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355584.094
      sim_grid_pos_y: 3008503.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355635.125
      sim_grid_pos_y: 3008474
    }
    terrain_level_point {
      sim_grid_pos_x: 355712.781
      sim_grid_pos_y: 3008503.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355616
      sim_grid_pos_y: 3008706.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355811.719
      sim_grid_pos_y: 3008677.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 353131.688
      sim_grid_pos_y: 3005591.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353127.281
      sim_grid_pos_y: 3005733.75
    }
    terrain_level_point {
      sim_grid_pos_x: 353287.531
      sim_grid_pos_y: 3005834.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353121.219
      sim_grid_pos_y: 3006213
    }
    terrain_level_point {
      sim_grid_pos_x: 352950.812
      sim_grid_pos_y: 3006496.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353337.906
      sim_grid_pos_y: 3007244.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353302.188
      sim_grid_pos_y: 3007431.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353749.844
      sim_grid_pos_y: 3007998.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353978.062
      sim_grid_pos_y: 3007821
    }
    terrain_level_point {
      sim_grid_pos_x: 354454.781
      sim_grid_pos_y: 3.00809e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 354594.219
      sim_grid_pos_y: 3008239
    }
    terrain_level_point {
      sim_grid_pos_x: 354712.969
      sim_grid_pos_y: 3008238.25
    }
    terrain_level_point {
      sim_grid_pos_x: 354894.094
      sim_grid_pos_y: 3008289.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355053.719
      sim_grid_pos_y: 3008304.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355111.125
      sim_grid_pos_y: 3008271.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355181.656
      sim_grid_pos_y: 3008417.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355307.219
      sim_grid_pos_y: 3008507.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355409.938
      sim_grid_pos_y: 3008414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355517.938
      sim_grid_pos_y: 3008443.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355571.719
      sim_grid_pos_y: 3008546.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355637.906
      sim_grid_pos_y: 3008508
    }
    terrain_level_point {
      sim_grid_pos_x: 355670.656
      sim_grid_pos_y: 3008520.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355580.312
      sim_grid_pos_y: 3.00871e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 355602.25
      sim_grid_pos_y: 3008739.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355824.719
      sim_grid_pos_y: 3008706.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355929.344
      sim_grid_pos_y: 3.00862e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 358327.031
      sim_grid_pos_y: 3007692.75
    }
    terrain_level_point {
      sim_grid_pos_x: 356379.719
      sim_grid_pos_y: 3006008.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354659.812
      sim_grid_pos_y: 3005895.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353915.438
      sim_grid_pos_y: 3005927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353789.25
      sim_grid_pos_y: 3005717.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 353102.062
      sim_grid_pos_y: 3005554.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353096
      sim_grid_pos_y: 3005750.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353248.688
      sim_grid_pos_y: 3005846.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353093.812
      sim_grid_pos_y: 3006199
    }
    terrain_level_point {
      sim_grid_pos_x: 352915.625
      sim_grid_pos_y: 3006495
    }
    terrain_level_point {
      sim_grid_pos_x: 353305.688
      sim_grid_pos_y: 3007249
    }
    terrain_level_point {
      sim_grid_pos_x: 353269.344
      sim_grid_pos_y: 3007439.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353744.625
      sim_grid_pos_y: 3008041.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353980.781
      sim_grid_pos_y: 3007857.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354435.562
      sim_grid_pos_y: 3008114.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354580.938
      sim_grid_pos_y: 3008269.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354708.75
      sim_grid_pos_y: 3008269
    }
    terrain_level_point {
      sim_grid_pos_x: 354888.375
      sim_grid_pos_y: 3.00832e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 355060.656
      sim_grid_pos_y: 3008336.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355097.875
      sim_grid_pos_y: 3008314.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355157.375
      sim_grid_pos_y: 3008438
    }
    terrain_level_point {
      sim_grid_pos_x: 355309.5
      sim_grid_pos_y: 3008546.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355418.125
      sim_grid_pos_y: 3008448.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355496.906
      sim_grid_pos_y: 3008469.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355559.375
      sim_grid_pos_y: 3008589.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355620.781
      sim_grid_pos_y: 3008553.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355544.594
      sim_grid_pos_y: 3008713.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355588.469
      sim_grid_pos_y: 3008772.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355837.75
      sim_grid_pos_y: 3008736
    }
    terrain_level_point {
      sim_grid_pos_x: 355945.156
      sim_grid_pos_y: 3008646.75
    }
    terrain_level_point {
      sim_grid_pos_x: 358385.875
      sim_grid_pos_y: 3007703
    }
    terrain_level_point {
      sim_grid_pos_x: 356392.031
      sim_grid_pos_y: 3005978.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354660.156
      sim_grid_pos_y: 3005864.75
    }
    terrain_level_point {
      sim_grid_pos_x: 353932.375
      sim_grid_pos_y: 3005896
    }
    terrain_level_point {
      sim_grid_pos_x: 353808.531
      sim_grid_pos_y: 3005690.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 353072.438
      sim_grid_pos_y: 3005517.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353064.719
      sim_grid_pos_y: 3005767.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353209.844
      sim_grid_pos_y: 3005858.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353066.469
      sim_grid_pos_y: 3006184.75
    }
    terrain_level_point {
      sim_grid_pos_x: 352880.406
      sim_grid_pos_y: 3006494
    }
    terrain_level_point {
      sim_grid_pos_x: 353273.469
      sim_grid_pos_y: 3007253.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353236.469
      sim_grid_pos_y: 3007447.25
    }
    terrain_level_point {
      sim_grid_pos_x: 353739.406
      sim_grid_pos_y: 3008084.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353983.469
      sim_grid_pos_y: 3007894.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354416.312
      sim_grid_pos_y: 3008138.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354567.688
      sim_grid_pos_y: 3008300.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354704.562
      sim_grid_pos_y: 3008299.75
    }
    terrain_level_point {
      sim_grid_pos_x: 354882.688
      sim_grid_pos_y: 3008350.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355067.625
      sim_grid_pos_y: 3008367.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355084.594
      sim_grid_pos_y: 3008358
    }
    terrain_level_point {
      sim_grid_pos_x: 355133.062
      sim_grid_pos_y: 3008458.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355311.75
      sim_grid_pos_y: 3008586
    }
    terrain_level_point {
      sim_grid_pos_x: 355426.281
      sim_grid_pos_y: 3008482.5
    }
    terrain_level_point {
      sim_grid_pos_x: 355475.906
      sim_grid_pos_y: 3008496
    }
    terrain_level_point {
      sim_grid_pos_x: 355547.031
      sim_grid_pos_y: 3008632
    }
    terrain_level_point {
      sim_grid_pos_x: 355550.188
      sim_grid_pos_y: 3008630.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355508.906
      sim_grid_pos_y: 3008716.75
    }
    terrain_level_point {
      sim_grid_pos_x: 355574.719
      sim_grid_pos_y: 3008806
    }
    terrain_level_point {
      sim_grid_pos_x: 355850.75
      sim_grid_pos_y: 3008765.25
    }
    terrain_level_point {
      sim_grid_pos_x: 355960.906
      sim_grid_pos_y: 3008673.75
    }
    terrain_level_point {
      sim_grid_pos_x: 358444.719
      sim_grid_pos_y: 3007713
    }
    terrain_level_point {
      sim_grid_pos_x: 356404.344
      sim_grid_pos_y: 3005948.5
    }
    terrain_level_point {
      sim_grid_pos_x: 354660.5
      sim_grid_pos_y: 3005834
    }
    terrain_level_point {
      sim_grid_pos_x: 353949.312
      sim_grid_pos_y: 3005864.5
    }
    terrain_level_point {
      sim_grid_pos_x: 353827.812
      sim_grid_pos_y: 3005662.5
    }
  }
}
