terrain_level_data {
  terrain_level: 56
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2725507.75
      sim_grid_pos_y: 464946.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2719593.5
      sim_grid_pos_y: 462392.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2718213
      sim_grid_pos_y: 462481.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2717617.25
      sim_grid_pos_y: 464629
    }
    terrain_level_point {
      sim_grid_pos_x: 2719022.5
      sim_grid_pos_y: 465987.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2719067
      sim_grid_pos_y: 467718.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2720349.25
      sim_grid_pos_y: 467757.219
    }
    terrain_level_point {
      sim_grid_pos_x: 2720478.75
      sim_grid_pos_y: 469073.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2.72338e+06
      sim_grid_pos_y: 469400.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2725045.5
      sim_grid_pos_y: 468632.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2725681.25
      sim_grid_pos_y: 467393.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2727153.75
      sim_grid_pos_y: 467419.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2727587.25
      sim_grid_pos_y: 467192.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2727621.25
      sim_grid_pos_y: 466409.094
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2719602.5
      sim_grid_pos_y: 462340.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2718173.25
      sim_grid_pos_y: 462433.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2717559.75
      sim_grid_pos_y: 464644.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718971.75
      sim_grid_pos_y: 466009.469
    }
    terrain_level_point {
      sim_grid_pos_x: 2719017
      sim_grid_pos_y: 467768.719
    }
    terrain_level_point {
      sim_grid_pos_x: 2720302.75
      sim_grid_pos_y: 467807.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2720431.75
      sim_grid_pos_y: 469119.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2723388.25
      sim_grid_pos_y: 469452.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2725083
      sim_grid_pos_y: 468671.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2725712.25
      sim_grid_pos_y: 467445.188
    }
    terrain_level_point {
      sim_grid_pos_x: 2727166
      sim_grid_pos_y: 467470.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2727637.25
      sim_grid_pos_y: 467224.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2727673.75
      sim_grid_pos_y: 466383.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2725532.75
      sim_grid_pos_y: 464901.594
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2719611.5
      sim_grid_pos_y: 462288.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2718133.75
      sim_grid_pos_y: 462384.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2717502.25
      sim_grid_pos_y: 464660.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2718921
      sim_grid_pos_y: 466031.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2718967
      sim_grid_pos_y: 467818.531
    }
    terrain_level_point {
      sim_grid_pos_x: 2720256
      sim_grid_pos_y: 467857
    }
    terrain_level_point {
      sim_grid_pos_x: 2720384.75
      sim_grid_pos_y: 469166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2723396.75
      sim_grid_pos_y: 469505.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2725120.5
      sim_grid_pos_y: 468710.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2725743.25
      sim_grid_pos_y: 467497
    }
    terrain_level_point {
      sim_grid_pos_x: 2727178.25
      sim_grid_pos_y: 467522.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2727687.25
      sim_grid_pos_y: 467256.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2727726.25
      sim_grid_pos_y: 466356.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2725557.75
      sim_grid_pos_y: 464856.531
    }
  }
}
