terrain_level_data {
  terrain_level: 165
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1270786.75
      sim_grid_pos_y: 235215.734
    }
    terrain_level_point {
      sim_grid_pos_x: 1269532.12
      sim_grid_pos_y: 235724.578
    }
    terrain_level_point {
      sim_grid_pos_x: 1269072.88
      sim_grid_pos_y: 235710.953
    }
    terrain_level_point {
      sim_grid_pos_x: 1269038.38
      sim_grid_pos_y: 235303.844
    }
    terrain_level_point {
      sim_grid_pos_x: 1269377.38
      sim_grid_pos_y: 235293.016
    }
    terrain_level_point {
      sim_grid_pos_x: 1269367.25
      sim_grid_pos_y: 234717.203
    }
    terrain_level_point {
      sim_grid_pos_x: 1270073.62
      sim_grid_pos_y: 234713.562
    }
    terrain_level_point {
      sim_grid_pos_x: 1270089.75
      sim_grid_pos_y: 234026.766
    }
    terrain_level_point {
      sim_grid_pos_x: 1270774.62
      sim_grid_pos_y: 234010.438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1270879.62
      sim_grid_pos_y: 235277.641
    }
    terrain_level_point {
      sim_grid_pos_x: 1269548.75
      sim_grid_pos_y: 235817.391
    }
    terrain_level_point {
      sim_grid_pos_x: 1268987.88
      sim_grid_pos_y: 235800.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1268938.12
      sim_grid_pos_y: 235214.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1269283.5
      sim_grid_pos_y: 235203.688
    }
    terrain_level_point {
      sim_grid_pos_x: 1269273.38
      sim_grid_pos_y: 234625.406
    }
    terrain_level_point {
      sim_grid_pos_x: 1269983.5
      sim_grid_pos_y: 234621.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1269999.62
      sim_grid_pos_y: 233936.609
    }
    terrain_level_point {
      sim_grid_pos_x: 1270865.88
      sim_grid_pos_y: 233915.953
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1270972.5
      sim_grid_pos_y: 235339.531
    }
    terrain_level_point {
      sim_grid_pos_x: 1269565.5
      sim_grid_pos_y: 235910.203
    }
    terrain_level_point {
      sim_grid_pos_x: 1268903
      sim_grid_pos_y: 235890.547
    }
    terrain_level_point {
      sim_grid_pos_x: 1268838
      sim_grid_pos_y: 235125.609
    }
    terrain_level_point {
      sim_grid_pos_x: 1269189.62
      sim_grid_pos_y: 235114.359
    }
    terrain_level_point {
      sim_grid_pos_x: 1269179.38
      sim_grid_pos_y: 234533.625
    }
    terrain_level_point {
      sim_grid_pos_x: 1269893.38
      sim_grid_pos_y: 234529.938
    }
    terrain_level_point {
      sim_grid_pos_x: 1269909.38
      sim_grid_pos_y: 233846.469
    }
    terrain_level_point {
      sim_grid_pos_x: 1270957.25
      sim_grid_pos_y: 233821.469
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1271065.38
      sim_grid_pos_y: 235401.438
    }
    terrain_level_point {
      sim_grid_pos_x: 1269582.12
      sim_grid_pos_y: 236003.016
    }
    terrain_level_point {
      sim_grid_pos_x: 1268818
      sim_grid_pos_y: 235980.344
    }
    terrain_level_point {
      sim_grid_pos_x: 1268737.75
      sim_grid_pos_y: 235036.484
    }
    terrain_level_point {
      sim_grid_pos_x: 1269095.75
      sim_grid_pos_y: 235025.047
    }
    terrain_level_point {
      sim_grid_pos_x: 1269085.5
      sim_grid_pos_y: 234441.828
    }
    terrain_level_point {
      sim_grid_pos_x: 1269803.25
      sim_grid_pos_y: 234438.141
    }
    terrain_level_point {
      sim_grid_pos_x: 1269819.25
      sim_grid_pos_y: 233756.312
    }
    terrain_level_point {
      sim_grid_pos_x: 1271048.5
      sim_grid_pos_y: 233727
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1271158.25
      sim_grid_pos_y: 235463.328
    }
    terrain_level_point {
      sim_grid_pos_x: 1269598.88
      sim_grid_pos_y: 236095.828
    }
    terrain_level_point {
      sim_grid_pos_x: 1268733
      sim_grid_pos_y: 236070.141
    }
    terrain_level_point {
      sim_grid_pos_x: 1268637.62
      sim_grid_pos_y: 234947.359
    }
    terrain_level_point {
      sim_grid_pos_x: 1269001.88
      sim_grid_pos_y: 234935.719
    }
    terrain_level_point {
      sim_grid_pos_x: 1268991.62
      sim_grid_pos_y: 234350.047
    }
    terrain_level_point {
      sim_grid_pos_x: 1269713.12
      sim_grid_pos_y: 234346.328
    }
    terrain_level_point {
      sim_grid_pos_x: 1269729
      sim_grid_pos_y: 233666.156
    }
    terrain_level_point {
      sim_grid_pos_x: 1271139.88
      sim_grid_pos_y: 233632.531
    }
  }
}
