terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1828826.62
      sim_grid_pos_y: 1023892.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1828617.88
      sim_grid_pos_y: 1024035.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1828686.88
      sim_grid_pos_y: 1024274.44
    }
    terrain_level_point {
      sim_grid_pos_x: 1829140.62
      sim_grid_pos_y: 1024343.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1829337
      sim_grid_pos_y: 1024357.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1829398.25
      sim_grid_pos_y: 1024221.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1829228.12
      sim_grid_pos_y: 1024081.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1829159
      sim_grid_pos_y: 1024075.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1829090.88
      sim_grid_pos_y: 1023931.19
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1828814.25
      sim_grid_pos_y: 1023839.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1828558.38
      sim_grid_pos_y: 1024014.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1828646.75
      sim_grid_pos_y: 1024320.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1829135
      sim_grid_pos_y: 1024394.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1829369
      sim_grid_pos_y: 1024411.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1829461
      sim_grid_pos_y: 1024207
    }
    terrain_level_point {
      sim_grid_pos_x: 1829248.38
      sim_grid_pos_y: 1024031.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1829192.75
      sim_grid_pos_y: 1024026.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1829125.38
      sim_grid_pos_y: 1023884.44
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1828801.75
      sim_grid_pos_y: 1023785.69
    }
    terrain_level_point {
      sim_grid_pos_x: 1828498.75
      sim_grid_pos_y: 1023993.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1828606.62
      sim_grid_pos_y: 1024365.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1829129.25
      sim_grid_pos_y: 1024445.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1829401.12
      sim_grid_pos_y: 1024465
    }
    terrain_level_point {
      sim_grid_pos_x: 1829523.88
      sim_grid_pos_y: 1024192.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1829268.62
      sim_grid_pos_y: 1023981.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1829226.5
      sim_grid_pos_y: 1023978.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1.82916e+06
      sim_grid_pos_y: 1023837.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1828789.25
      sim_grid_pos_y: 1023732.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1828439.25
      sim_grid_pos_y: 1023971.94
    }
    terrain_level_point {
      sim_grid_pos_x: 1828566.5
      sim_grid_pos_y: 1024411.56
    }
    terrain_level_point {
      sim_grid_pos_x: 1829123.62
      sim_grid_pos_y: 1024496.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1829433.12
      sim_grid_pos_y: 1024518.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1829586.62
      sim_grid_pos_y: 1024177.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1829288.88
      sim_grid_pos_y: 1023932.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1829260.25
      sim_grid_pos_y: 1023929.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1829194.62
      sim_grid_pos_y: 1023790.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1828776.88
      sim_grid_pos_y: 1023678.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1828379.62
      sim_grid_pos_y: 1023950.56
    }
    terrain_level_point {
      sim_grid_pos_x: 1828526.38
      sim_grid_pos_y: 1024457.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1829117.88
      sim_grid_pos_y: 1024547.81
    }
    terrain_level_point {
      sim_grid_pos_x: 1829465.25
      sim_grid_pos_y: 1024572.31
    }
    terrain_level_point {
      sim_grid_pos_x: 1829649.5
      sim_grid_pos_y: 1024163.06
    }
    terrain_level_point {
      sim_grid_pos_x: 1829309.25
      sim_grid_pos_y: 1023882.56
    }
    terrain_level_point {
      sim_grid_pos_x: 1829294
      sim_grid_pos_y: 1023881.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1829229.12
      sim_grid_pos_y: 1023744.06
    }
  }
}
