terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 762629.188
      sim_grid_pos_y: 1415502.38
    }
    terrain_level_point {
      sim_grid_pos_x: 758475.312
      sim_grid_pos_y: 1415725
    }
    terrain_level_point {
      sim_grid_pos_x: 757842.438
      sim_grid_pos_y: 1415764.5
    }
    terrain_level_point {
      sim_grid_pos_x: 757537.812
      sim_grid_pos_y: 1415858.25
    }
    terrain_level_point {
      sim_grid_pos_x: 758224.188
      sim_grid_pos_y: 1416886
    }
    terrain_level_point {
      sim_grid_pos_x: 758304.312
      sim_grid_pos_y: 1418935
    }
    terrain_level_point {
      sim_grid_pos_x: 762332.562
      sim_grid_pos_y: 1418770.88
    }
    terrain_level_point {
      sim_grid_pos_x: 762456.875
      sim_grid_pos_y: 1418583.25
    }
    terrain_level_point {
      sim_grid_pos_x: 762741.562
      sim_grid_pos_y: 1418596.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 762658.812
      sim_grid_pos_y: 1.41547e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 758473.5
      sim_grid_pos_y: 1415694.25
    }
    terrain_level_point {
      sim_grid_pos_x: 757836.938
      sim_grid_pos_y: 1415734
    }
    terrain_level_point {
      sim_grid_pos_x: 757489.25
      sim_grid_pos_y: 1415841
    }
    terrain_level_point {
      sim_grid_pos_x: 758193.812
      sim_grid_pos_y: 1416895.88
    }
    terrain_level_point {
      sim_grid_pos_x: 758274.812
      sim_grid_pos_y: 1418967
    }
    terrain_level_point {
      sim_grid_pos_x: 762349.5
      sim_grid_pos_y: 1418801
    }
    terrain_level_point {
      sim_grid_pos_x: 762472.875
      sim_grid_pos_y: 1418614.75
    }
    terrain_level_point {
      sim_grid_pos_x: 762773.562
      sim_grid_pos_y: 1418629.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 762688.375
      sim_grid_pos_y: 1415437.62
    }
    terrain_level_point {
      sim_grid_pos_x: 758471.75
      sim_grid_pos_y: 1415663.62
    }
    terrain_level_point {
      sim_grid_pos_x: 757831.375
      sim_grid_pos_y: 1415703.5
    }
    terrain_level_point {
      sim_grid_pos_x: 757440.75
      sim_grid_pos_y: 1415823.75
    }
    terrain_level_point {
      sim_grid_pos_x: 758163.438
      sim_grid_pos_y: 1416905.75
    }
    terrain_level_point {
      sim_grid_pos_x: 758245.25
      sim_grid_pos_y: 1418998.88
    }
    terrain_level_point {
      sim_grid_pos_x: 762366.438
      sim_grid_pos_y: 1418831.12
    }
    terrain_level_point {
      sim_grid_pos_x: 762488.812
      sim_grid_pos_y: 1418646.38
    }
    terrain_level_point {
      sim_grid_pos_x: 762805.5
      sim_grid_pos_y: 1418661.5
    }
  }
}
