terrain_level_data {
  terrain_level: 550
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2878629.75
      sim_grid_pos_y: 2.31841e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2878619
      sim_grid_pos_y: 2318514.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878628.25
      sim_grid_pos_y: 2318636.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878720.5
      sim_grid_pos_y: 2318666.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878772
      sim_grid_pos_y: 2318668.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878851
      sim_grid_pos_y: 2318629.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878880.25
      sim_grid_pos_y: 2318495
    }
    terrain_level_point {
      sim_grid_pos_x: 2878870.75
      sim_grid_pos_y: 2318369.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878806.5
      sim_grid_pos_y: 2318325
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2878811.25
      sim_grid_pos_y: 2318265.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878581.75
      sim_grid_pos_y: 2318376.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878567.5
      sim_grid_pos_y: 2318514
    }
    terrain_level_point {
      sim_grid_pos_x: 2878579.75
      sim_grid_pos_y: 2318675
    }
    terrain_level_point {
      sim_grid_pos_x: 2878711.5
      sim_grid_pos_y: 2318717.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878783
      sim_grid_pos_y: 2318719.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878895.75
      sim_grid_pos_y: 2318665
    }
    terrain_level_point {
      sim_grid_pos_x: 2878932
      sim_grid_pos_y: 2318498.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.87892e+06
      sim_grid_pos_y: 2318341.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2878816
      sim_grid_pos_y: 2318206.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878533.75
      sim_grid_pos_y: 2318342.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878516
      sim_grid_pos_y: 2318513.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878531.25
      sim_grid_pos_y: 2318713.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878702.75
      sim_grid_pos_y: 2318768.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878794
      sim_grid_pos_y: 2318771.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878940.5
      sim_grid_pos_y: 2318700.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878983.75
      sim_grid_pos_y: 2318502
    }
    terrain_level_point {
      sim_grid_pos_x: 2878969.25
      sim_grid_pos_y: 2318313.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2878820.75
      sim_grid_pos_y: 2318147.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878485.75
      sim_grid_pos_y: 2318308.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878464.5
      sim_grid_pos_y: 2318512.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878482.75
      sim_grid_pos_y: 2318751.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878694
      sim_grid_pos_y: 2318819.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878805.25
      sim_grid_pos_y: 2318823
    }
    terrain_level_point {
      sim_grid_pos_x: 2878985.5
      sim_grid_pos_y: 2318735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2879035.5
      sim_grid_pos_y: 2318505.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879018.5
      sim_grid_pos_y: 2318285
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2878825
      sim_grid_pos_y: 2318088
    }
    terrain_level_point {
      sim_grid_pos_x: 2878434.25
      sim_grid_pos_y: 2318278
    }
    terrain_level_point {
      sim_grid_pos_x: 2878413.25
      sim_grid_pos_y: 2318513.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878434.25
      sim_grid_pos_y: 2318789.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878685.25
      sim_grid_pos_y: 2318870.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878816.25
      sim_grid_pos_y: 2318874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879030.25
      sim_grid_pos_y: 2318770.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879087
      sim_grid_pos_y: 2318509.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2879067.75
      sim_grid_pos_y: 2318257
    }
  }
}
terrain_level_data {
  terrain_level: 558
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2879951
      sim_grid_pos_y: 2318317.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2879897.5
      sim_grid_pos_y: 2.31842e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2879926
      sim_grid_pos_y: 2318522.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2880005.25
      sim_grid_pos_y: 2318548.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2880109.75
      sim_grid_pos_y: 2318522
    }
    terrain_level_point {
      sim_grid_pos_x: 2880127.25
      sim_grid_pos_y: 2318408.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2880094.25
      sim_grid_pos_y: 2318318.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2879926.25
      sim_grid_pos_y: 2318276.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2879853.75
      sim_grid_pos_y: 2318415.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2879892.25
      sim_grid_pos_y: 2318555
    }
    terrain_level_point {
      sim_grid_pos_x: 2880003.75
      sim_grid_pos_y: 2318591
    }
    terrain_level_point {
      sim_grid_pos_x: 2880146
      sim_grid_pos_y: 2318555
    }
    terrain_level_point {
      sim_grid_pos_x: 2880169.5
      sim_grid_pos_y: 2318404.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2880122.75
      sim_grid_pos_y: 2318277.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2879901.5
      sim_grid_pos_y: 2318235
    }
    terrain_level_point {
      sim_grid_pos_x: 2.87981e+06
      sim_grid_pos_y: 2318410.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879858.5
      sim_grid_pos_y: 2318587.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880002.25
      sim_grid_pos_y: 2318633.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2880182.25
      sim_grid_pos_y: 2318588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880211.75
      sim_grid_pos_y: 2318400.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880151.5
      sim_grid_pos_y: 2318237
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2879876.75
      sim_grid_pos_y: 2318193.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879766
      sim_grid_pos_y: 2318406
    }
    terrain_level_point {
      sim_grid_pos_x: 2879825
      sim_grid_pos_y: 2318619.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880001
      sim_grid_pos_y: 2318676.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2880218.75
      sim_grid_pos_y: 2318621.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880253.75
      sim_grid_pos_y: 2318396.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880180.25
      sim_grid_pos_y: 2318196.25
    }
  }
}
terrain_level_data {
  terrain_level: 200
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2876830.75
      sim_grid_pos_y: 2318537.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2876730.25
      sim_grid_pos_y: 2318585.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2876747
      sim_grid_pos_y: 2318881.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2877035.5
      sim_grid_pos_y: 2319019
    }
    terrain_level_point {
      sim_grid_pos_x: 2877040.5
      sim_grid_pos_y: 2318754
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 2876841.75
      sim_grid_pos_y: 2318475
    }
    terrain_level_point {
      sim_grid_pos_x: 2876677
      sim_grid_pos_y: 2318554.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2876697.5
      sim_grid_pos_y: 2318914.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2877085.25
      sim_grid_pos_y: 2319099.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2877092
      sim_grid_pos_y: 2318733.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 2876853
      sim_grid_pos_y: 2318412.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2876624
      sim_grid_pos_y: 2318523
    }
    terrain_level_point {
      sim_grid_pos_x: 2876648
      sim_grid_pos_y: 2318947.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2877135
      sim_grid_pos_y: 2319180.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2877143.75
      sim_grid_pos_y: 2318713.25
    }
  }
}
