terrain_level_data {
  terrain_level: 66
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 432034.812
      sim_grid_pos_y: 2152677.75
    }
    terrain_level_point {
      sim_grid_pos_x: 431912.531
      sim_grid_pos_y: 2152396
    }
    terrain_level_point {
      sim_grid_pos_x: 432190.375
      sim_grid_pos_y: 2151526.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432852.031
      sim_grid_pos_y: 2151881.75
    }
    terrain_level_point {
      sim_grid_pos_x: 433133.781
      sim_grid_pos_y: 2.15206e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 433874.188
      sim_grid_pos_y: 2152234
    }
    terrain_level_point {
      sim_grid_pos_x: 434216.281
      sim_grid_pos_y: 2152389.5
    }
    terrain_level_point {
      sim_grid_pos_x: 434213.156
      sim_grid_pos_y: 2152675
    }
    terrain_level_point {
      sim_grid_pos_x: 434254.125
      sim_grid_pos_y: 2153097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434289.719
      sim_grid_pos_y: 2153565.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434169.438
      sim_grid_pos_y: 2153334
    }
    terrain_level_point {
      sim_grid_pos_x: 433746.969
      sim_grid_pos_y: 2152919.25
    }
    terrain_level_point {
      sim_grid_pos_x: 433215.844
      sim_grid_pos_y: 2152728.75
    }
    terrain_level_point {
      sim_grid_pos_x: 432813.312
      sim_grid_pos_y: 2152794.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432609.875
      sim_grid_pos_y: 2153020.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432281.469
      sim_grid_pos_y: 2152974.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 432867.562
      sim_grid_pos_y: 2151855.25
    }
    terrain_level_point {
      sim_grid_pos_x: 433145.844
      sim_grid_pos_y: 2152031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 433884.156
      sim_grid_pos_y: 2152204.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434247.25
      sim_grid_pos_y: 2152369.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434243.938
      sim_grid_pos_y: 2152673.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434284.781
      sim_grid_pos_y: 2153094.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434322.281
      sim_grid_pos_y: 2153588.5
    }
    terrain_level_point {
      sim_grid_pos_x: 434274
      sim_grid_pos_y: 2153602.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434144.375
      sim_grid_pos_y: 2153352.5
    }
    terrain_level_point {
      sim_grid_pos_x: 433730.25
      sim_grid_pos_y: 2152945.75
    }
    terrain_level_point {
      sim_grid_pos_x: 433212.938
      sim_grid_pos_y: 2152760.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432828.938
      sim_grid_pos_y: 2152823
    }
    terrain_level_point {
      sim_grid_pos_x: 432621.812
      sim_grid_pos_y: 2153052.75
    }
    terrain_level_point {
      sim_grid_pos_x: 432265.438
      sim_grid_pos_y: 2153003.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432008.344
      sim_grid_pos_y: 2152694
    }
    terrain_level_point {
      sim_grid_pos_x: 431879.719
      sim_grid_pos_y: 2152397.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432172.344
      sim_grid_pos_y: 2151482
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 432883.062
      sim_grid_pos_y: 2151828.75
    }
    terrain_level_point {
      sim_grid_pos_x: 433157.938
      sim_grid_pos_y: 2152002.5
    }
    terrain_level_point {
      sim_grid_pos_x: 433894.125
      sim_grid_pos_y: 2152175.5
    }
    terrain_level_point {
      sim_grid_pos_x: 434278.219
      sim_grid_pos_y: 2.15235e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 434274.688
      sim_grid_pos_y: 2152672.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434315.438
      sim_grid_pos_y: 2153092
    }
    terrain_level_point {
      sim_grid_pos_x: 434354.844
      sim_grid_pos_y: 2153611.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434258.281
      sim_grid_pos_y: 2153638.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434119.312
      sim_grid_pos_y: 2153371
    }
    terrain_level_point {
      sim_grid_pos_x: 433713.469
      sim_grid_pos_y: 2152972.5
    }
    terrain_level_point {
      sim_grid_pos_x: 433210.062
      sim_grid_pos_y: 2152792
    }
    terrain_level_point {
      sim_grid_pos_x: 432844.531
      sim_grid_pos_y: 2152851.75
    }
    terrain_level_point {
      sim_grid_pos_x: 432633.719
      sim_grid_pos_y: 2153085.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432249.375
      sim_grid_pos_y: 2153032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 431981.875
      sim_grid_pos_y: 2152710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 431846.906
      sim_grid_pos_y: 2152399.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432154.312
      sim_grid_pos_y: 2151437.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 432898.562
      sim_grid_pos_y: 2151802
    }
    terrain_level_point {
      sim_grid_pos_x: 433170
      sim_grid_pos_y: 2151973.75
    }
    terrain_level_point {
      sim_grid_pos_x: 433904.125
      sim_grid_pos_y: 2152146.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434309.188
      sim_grid_pos_y: 2152330.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434305.469
      sim_grid_pos_y: 2152671
    }
    terrain_level_point {
      sim_grid_pos_x: 434346.062
      sim_grid_pos_y: 2153089.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434387.438
      sim_grid_pos_y: 2153634
    }
    terrain_level_point {
      sim_grid_pos_x: 434242.531
      sim_grid_pos_y: 2153675.25
    }
    terrain_level_point {
      sim_grid_pos_x: 434094.312
      sim_grid_pos_y: 2153389.75
    }
    terrain_level_point {
      sim_grid_pos_x: 433696.781
      sim_grid_pos_y: 2152999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 433207.156
      sim_grid_pos_y: 2152823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432860.156
      sim_grid_pos_y: 2152880.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432645.656
      sim_grid_pos_y: 2153118.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432233.344
      sim_grid_pos_y: 2153061.25
    }
    terrain_level_point {
      sim_grid_pos_x: 431955.406
      sim_grid_pos_y: 2152726.5
    }
    terrain_level_point {
      sim_grid_pos_x: 431814.062
      sim_grid_pos_y: 2152400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 432136.281
      sim_grid_pos_y: 2151392.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 432914.094
      sim_grid_pos_y: 2151775.5
    }
    terrain_level_point {
      sim_grid_pos_x: 433182.094
      sim_grid_pos_y: 2151945
    }
    terrain_level_point {
      sim_grid_pos_x: 433914.094
      sim_grid_pos_y: 2152117
    }
    terrain_level_point {
      sim_grid_pos_x: 434340.156
      sim_grid_pos_y: 2152310.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434336.25
      sim_grid_pos_y: 2152669.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434376.719
      sim_grid_pos_y: 2153086.75
    }
    terrain_level_point {
      sim_grid_pos_x: 434420
      sim_grid_pos_y: 2153656.5
    }
    terrain_level_point {
      sim_grid_pos_x: 434226.812
      sim_grid_pos_y: 2153711.5
    }
    terrain_level_point {
      sim_grid_pos_x: 434069.25
      sim_grid_pos_y: 2153408.25
    }
    terrain_level_point {
      sim_grid_pos_x: 433680.031
      sim_grid_pos_y: 2153025.75
    }
    terrain_level_point {
      sim_grid_pos_x: 433204.281
      sim_grid_pos_y: 2152855.25
    }
    terrain_level_point {
      sim_grid_pos_x: 432875.781
      sim_grid_pos_y: 2152909
    }
    terrain_level_point {
      sim_grid_pos_x: 432657.594
      sim_grid_pos_y: 2153151
    }
    terrain_level_point {
      sim_grid_pos_x: 432217.312
      sim_grid_pos_y: 2.15309e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 431928.938
      sim_grid_pos_y: 2152742.75
    }
    terrain_level_point {
      sim_grid_pos_x: 431781.281
      sim_grid_pos_y: 2152402.5
    }
    terrain_level_point {
      sim_grid_pos_x: 432118.219
      sim_grid_pos_y: 2151348.25
    }
  }
}
