terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1639971.25
      sim_grid_pos_y: 1153943.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639889.38
      sim_grid_pos_y: 1154115.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639818.88
      sim_grid_pos_y: 1154406.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639796
      sim_grid_pos_y: 1154610.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639883
      sim_grid_pos_y: 1154767.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640073.88
      sim_grid_pos_y: 1154822
    }
    terrain_level_point {
      sim_grid_pos_x: 1640180.12
      sim_grid_pos_y: 1154907.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640284.12
      sim_grid_pos_y: 1155052.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640454.62
      sim_grid_pos_y: 1155156.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640636.38
      sim_grid_pos_y: 1155247.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640761
      sim_grid_pos_y: 1155352.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640891.25
      sim_grid_pos_y: 1155469.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641026.25
      sim_grid_pos_y: 1155499.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641168.5
      sim_grid_pos_y: 1155335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641257.25
      sim_grid_pos_y: 1155071.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641204.12
      sim_grid_pos_y: 1154737.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641176.25
      sim_grid_pos_y: 1154431.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641180.25
      sim_grid_pos_y: 1154207.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641114.25
      sim_grid_pos_y: 1153855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641043.38
      sim_grid_pos_y: 1153675.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640871.12
      sim_grid_pos_y: 1153583.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640762.88
      sim_grid_pos_y: 1153543.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640627.38
      sim_grid_pos_y: 1153364.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640571.12
      sim_grid_pos_y: 1153239.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640552.5
      sim_grid_pos_y: 1153123.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640406.25
      sim_grid_pos_y: 1153136.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640285.38
      sim_grid_pos_y: 1153195.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640149.5
      sim_grid_pos_y: 1153194
    }
    terrain_level_point {
      sim_grid_pos_x: 1639959.5
      sim_grid_pos_y: 1153166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639783.5
      sim_grid_pos_y: 1153277.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639731.5
      sim_grid_pos_y: 1153419.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639784.25
      sim_grid_pos_y: 1153525.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639816.38
      sim_grid_pos_y: 1153686.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639903.88
      sim_grid_pos_y: 1153824.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1640595.62
      sim_grid_pos_y: 1153067.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640392.12
      sim_grid_pos_y: 1153086
    }
    terrain_level_point {
      sim_grid_pos_x: 1640273.75
      sim_grid_pos_y: 1153144.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640153.62
      sim_grid_pos_y: 1153142.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639948.25
      sim_grid_pos_y: 1153112.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639741.38
      sim_grid_pos_y: 1153243.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639675.88
      sim_grid_pos_y: 1153422.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639735.25
      sim_grid_pos_y: 1153542
    }
    terrain_level_point {
      sim_grid_pos_x: 1639768
      sim_grid_pos_y: 1153706
    }
    terrain_level_point {
      sim_grid_pos_x: 1639859.88
      sim_grid_pos_y: 1153850.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639913.5
      sim_grid_pos_y: 1153945.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639840.75
      sim_grid_pos_y: 1154097.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639768.38
      sim_grid_pos_y: 1154398
    }
    terrain_level_point {
      sim_grid_pos_x: 1639743.12
      sim_grid_pos_y: 1154621
    }
    terrain_level_point {
      sim_grid_pos_x: 1639848.5
      sim_grid_pos_y: 1154811
    }
    terrain_level_point {
      sim_grid_pos_x: 1640049.88
      sim_grid_pos_y: 1154868.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640142.5
      sim_grid_pos_y: 1154943.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640248.5
      sim_grid_pos_y: 1155090.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640429.62
      sim_grid_pos_y: 1155201.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640608
      sim_grid_pos_y: 1155291
    }
    terrain_level_point {
      sim_grid_pos_x: 1640727.38
      sim_grid_pos_y: 1155391.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640867
      sim_grid_pos_y: 1155516.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641045
      sim_grid_pos_y: 1155556.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641213.88
      sim_grid_pos_y: 1155361.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641309.88
      sim_grid_pos_y: 1155075.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641255.12
      sim_grid_pos_y: 1154731.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641227.5
      sim_grid_pos_y: 1154429.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641231.62
      sim_grid_pos_y: 1154202.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641163.75
      sim_grid_pos_y: 1153841.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641084.25
      sim_grid_pos_y: 1153638.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640892.25
      sim_grid_pos_y: 1153536.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640794.62
      sim_grid_pos_y: 1153500.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640671.75
      sim_grid_pos_y: 1153338.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640620.62
      sim_grid_pos_y: 1153224.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1640638.62
      sim_grid_pos_y: 1153012.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640378.12
      sim_grid_pos_y: 1153035.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640262.12
      sim_grid_pos_y: 1153092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640157.5
      sim_grid_pos_y: 1153091.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639936.88
      sim_grid_pos_y: 1153059.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639699.25
      sim_grid_pos_y: 1153209.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639620.12
      sim_grid_pos_y: 1153425.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639686.38
      sim_grid_pos_y: 1153558.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639719.62
      sim_grid_pos_y: 1153725.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639815.88
      sim_grid_pos_y: 1153877.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639855.75
      sim_grid_pos_y: 1153947.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639792.25
      sim_grid_pos_y: 1154080.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639717.75
      sim_grid_pos_y: 1154389
    }
    terrain_level_point {
      sim_grid_pos_x: 1639690.38
      sim_grid_pos_y: 1154631.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639814
      sim_grid_pos_y: 1154854.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640025.75
      sim_grid_pos_y: 1154914.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640104.88
      sim_grid_pos_y: 1154978.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640212.88
      sim_grid_pos_y: 1155129.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640404.75
      sim_grid_pos_y: 1155246.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640579.75
      sim_grid_pos_y: 1155334.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640693.5
      sim_grid_pos_y: 1155429.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640842.62
      sim_grid_pos_y: 1155563.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641063.75
      sim_grid_pos_y: 1155613.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641259.25
      sim_grid_pos_y: 1155387.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641362.5
      sim_grid_pos_y: 1155079.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641306
      sim_grid_pos_y: 1154724.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641278.88
      sim_grid_pos_y: 1154428
    }
    terrain_level_point {
      sim_grid_pos_x: 1641283
      sim_grid_pos_y: 1154198.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641213.25
      sim_grid_pos_y: 1153827.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641125
      sim_grid_pos_y: 1153602.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640913.25
      sim_grid_pos_y: 1153489.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640826.38
      sim_grid_pos_y: 1153457.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640716.12
      sim_grid_pos_y: 1153311.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640670.25
      sim_grid_pos_y: 1153210.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1640681.75
      sim_grid_pos_y: 1152957.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640364.12
      sim_grid_pos_y: 1152985.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640250.5
      sim_grid_pos_y: 1153041.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640161.62
      sim_grid_pos_y: 1153040.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639925.5
      sim_grid_pos_y: 1153005.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639657.12
      sim_grid_pos_y: 1153175.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639564.38
      sim_grid_pos_y: 1153428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639637.38
      sim_grid_pos_y: 1153575.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639671.25
      sim_grid_pos_y: 1153744.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639771.88
      sim_grid_pos_y: 1153903.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639798
      sim_grid_pos_y: 1153949.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639743.62
      sim_grid_pos_y: 1154063.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639667.25
      sim_grid_pos_y: 1154380.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639637.62
      sim_grid_pos_y: 1154642
    }
    terrain_level_point {
      sim_grid_pos_x: 1639779.5
      sim_grid_pos_y: 1154897.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640001.62
      sim_grid_pos_y: 1154961.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640067.25
      sim_grid_pos_y: 1155014.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640177.38
      sim_grid_pos_y: 1155167.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640379.88
      sim_grid_pos_y: 1155291.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640551.38
      sim_grid_pos_y: 1155377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640660.12
      sim_grid_pos_y: 1155468.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640818.38
      sim_grid_pos_y: 1155611
    }
    terrain_level_point {
      sim_grid_pos_x: 1641082.38
      sim_grid_pos_y: 1155669.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641304.62
      sim_grid_pos_y: 1155413.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1641415
      sim_grid_pos_y: 1155084.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1641356.88
      sim_grid_pos_y: 1154718.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641330.12
      sim_grid_pos_y: 1154426.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641334.38
      sim_grid_pos_y: 1154194.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641262.75
      sim_grid_pos_y: 1153812.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641165.88
      sim_grid_pos_y: 1153566.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640934.25
      sim_grid_pos_y: 1153442.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640858.25
      sim_grid_pos_y: 1153414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640760.38
      sim_grid_pos_y: 1153285.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640719.75
      sim_grid_pos_y: 1153195.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1640724.88
      sim_grid_pos_y: 1152901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.64035e+06
      sim_grid_pos_y: 1152935.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640238.88
      sim_grid_pos_y: 1152989.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640165.5
      sim_grid_pos_y: 1152989.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639914.12
      sim_grid_pos_y: 1152952.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639614.88
      sim_grid_pos_y: 1153141.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639508.75
      sim_grid_pos_y: 1153431.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639588.5
      sim_grid_pos_y: 1153592.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639622.75
      sim_grid_pos_y: 1153764.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639727.88
      sim_grid_pos_y: 1153929.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639740.25
      sim_grid_pos_y: 1153951.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639695.12
      sim_grid_pos_y: 1154046
    }
    terrain_level_point {
      sim_grid_pos_x: 1639616.62
      sim_grid_pos_y: 1154371.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639584.88
      sim_grid_pos_y: 1154652.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639745
      sim_grid_pos_y: 1154941.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639977.5
      sim_grid_pos_y: 1155007.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640029.62
      sim_grid_pos_y: 1155049.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1640141.75
      sim_grid_pos_y: 1155206
    }
    terrain_level_point {
      sim_grid_pos_x: 1640355
      sim_grid_pos_y: 1155336.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640523
      sim_grid_pos_y: 1155420.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640626.38
      sim_grid_pos_y: 1155507.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640794.12
      sim_grid_pos_y: 1155658.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641101.12
      sim_grid_pos_y: 1155726.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.64135e+06
      sim_grid_pos_y: 1155439.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641467.62
      sim_grid_pos_y: 1155088.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1641407.75
      sim_grid_pos_y: 1154712
    }
    terrain_level_point {
      sim_grid_pos_x: 1641381.38
      sim_grid_pos_y: 1154424.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1641385.75
      sim_grid_pos_y: 1154189.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641312.25
      sim_grid_pos_y: 1153798.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1641206.62
      sim_grid_pos_y: 1153529.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640955.25
      sim_grid_pos_y: 1153395.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.64089e+06
      sim_grid_pos_y: 1153371.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640804.75
      sim_grid_pos_y: 1153259.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640769.25
      sim_grid_pos_y: 1153180.38
    }
  }
}
