terrain_level_data {
  terrain_level: 735
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1424213.38
      sim_grid_pos_y: 1463564
    }
    terrain_level_point {
      sim_grid_pos_x: 1424301.5
      sim_grid_pos_y: 1463726
    }
    terrain_level_point {
      sim_grid_pos_x: 1424652.12
      sim_grid_pos_y: 1463619.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1424997.5
      sim_grid_pos_y: 1463605.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1424918.12
      sim_grid_pos_y: 1463358.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1424586.88
      sim_grid_pos_y: 1463342.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1424334.38
      sim_grid_pos_y: 1463453.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1424577.25
      sim_grid_pos_y: 1463290.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1424306
      sim_grid_pos_y: 1463410.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1424149.12
      sim_grid_pos_y: 1463553.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1424276.38
      sim_grid_pos_y: 1463787.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1424660.75
      sim_grid_pos_y: 1463670.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1425067
      sim_grid_pos_y: 1463654.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1424956
      sim_grid_pos_y: 1463309.5
    }
  }
}
terrain_level_data {
  terrain_level: 648
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1425665.5
      sim_grid_pos_y: 1463361.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1425767
      sim_grid_pos_y: 1463529.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1426003
      sim_grid_pos_y: 1463502.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1426240.62
      sim_grid_pos_y: 1463363.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1426137.88
      sim_grid_pos_y: 1463194.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1426049.62
      sim_grid_pos_y: 1462954.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1425863.12
      sim_grid_pos_y: 1462966.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1425805.75
      sim_grid_pos_y: 1.46325e+06
    }
  }
}
terrain_level_data {
  terrain_level: 502
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1422419.75
      sim_grid_pos_y: 1463007.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1422568.88
      sim_grid_pos_y: 1463326.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1422834.38
      sim_grid_pos_y: 1463278.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1423040.25
      sim_grid_pos_y: 1463034.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1423119.25
      sim_grid_pos_y: 1462789.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1422805.62
      sim_grid_pos_y: 1462748.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1422566.12
      sim_grid_pos_y: 1462848.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1422798.62
      sim_grid_pos_y: 1462695.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1422536
      sim_grid_pos_y: 1462805.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1422358.75
      sim_grid_pos_y: 1462997.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1422539.12
      sim_grid_pos_y: 1463384.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1422861.75
      sim_grid_pos_y: 1463326
    }
    terrain_level_point {
      sim_grid_pos_x: 1423086
      sim_grid_pos_y: 1463059.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1423186.88
      sim_grid_pos_y: 1462746.38
    }
  }
}
