terrain_level_data {
  terrain_level: 397
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1113083.5
      sim_grid_pos_y: 1522524.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1113217.5
      sim_grid_pos_y: 1523115.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1113736.5
      sim_grid_pos_y: 1522920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1113814
      sim_grid_pos_y: 1522410.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1113369.88
      sim_grid_pos_y: 1522332
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1113347
      sim_grid_pos_y: 1522223.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1112968
      sim_grid_pos_y: 1522478.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1113143.5
      sim_grid_pos_y: 1523252.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1113828.88
      sim_grid_pos_y: 1522995.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1113930.38
      sim_grid_pos_y: 1522326.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1113324.12
      sim_grid_pos_y: 1522115.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1112852.5
      sim_grid_pos_y: 1522432.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1113069.5
      sim_grid_pos_y: 1523389.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1113921.12
      sim_grid_pos_y: 1523070.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1114046.75
      sim_grid_pos_y: 1522243.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1113301.25
      sim_grid_pos_y: 1522007.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1112737
      sim_grid_pos_y: 1522386.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1112995.5
      sim_grid_pos_y: 1523527.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1114013.5
      sim_grid_pos_y: 1523145.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1114163.12
      sim_grid_pos_y: 1522159.75
    }
  }
}
