terrain_level_data {
  terrain_level: 554
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 606904
      sim_grid_pos_y: 1769669.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606926.25
      sim_grid_pos_y: 1770047.38
    }
    terrain_level_point {
      sim_grid_pos_x: 606995.812
      sim_grid_pos_y: 1770440.62
    }
    terrain_level_point {
      sim_grid_pos_x: 607261.5
      sim_grid_pos_y: 1770805
    }
    terrain_level_point {
      sim_grid_pos_x: 607308.062
      sim_grid_pos_y: 1770920.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607078.5
      sim_grid_pos_y: 1771339.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606486.25
      sim_grid_pos_y: 1771652.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606580.562
      sim_grid_pos_y: 1771214.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606615.812
      sim_grid_pos_y: 1770948.88
    }
    terrain_level_point {
      sim_grid_pos_x: 606273.312
      sim_grid_pos_y: 1770760.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606103.5
      sim_grid_pos_y: 1770211.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605440
      sim_grid_pos_y: 1770184.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605241.688
      sim_grid_pos_y: 1769998.62
    }
    terrain_level_point {
      sim_grid_pos_x: 604514.125
      sim_grid_pos_y: 1769998.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603933.562
      sim_grid_pos_y: 1769194
    }
    terrain_level_point {
      sim_grid_pos_x: 603684
      sim_grid_pos_y: 1768643
    }
    terrain_level_point {
      sim_grid_pos_x: 603814.75
      sim_grid_pos_y: 1768400.62
    }
    terrain_level_point {
      sim_grid_pos_x: 604031.125
      sim_grid_pos_y: 1768289.88
    }
    terrain_level_point {
      sim_grid_pos_x: 604097.188
      sim_grid_pos_y: 1768186.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603835.375
      sim_grid_pos_y: 1767795.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603854.062
      sim_grid_pos_y: 1767412.88
    }
    terrain_level_point {
      sim_grid_pos_x: 604129.5
      sim_grid_pos_y: 1767103.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604250.438
      sim_grid_pos_y: 1766538.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603274
      sim_grid_pos_y: 1765682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603124.812
      sim_grid_pos_y: 1765612.38
    }
    terrain_level_point {
      sim_grid_pos_x: 603209.625
      sim_grid_pos_y: 1765467
    }
    terrain_level_point {
      sim_grid_pos_x: 603382.625
      sim_grid_pos_y: 1765479.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603550.625
      sim_grid_pos_y: 1765187.62
    }
    terrain_level_point {
      sim_grid_pos_x: 603963.938
      sim_grid_pos_y: 1764670.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604512.5
      sim_grid_pos_y: 1764511.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605104.125
      sim_grid_pos_y: 1764666.88
    }
    terrain_level_point {
      sim_grid_pos_x: 604977.875
      sim_grid_pos_y: 1765139.62
    }
    terrain_level_point {
      sim_grid_pos_x: 605060.125
      sim_grid_pos_y: 1765249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604995.938
      sim_grid_pos_y: 1765509.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605160.375
      sim_grid_pos_y: 1765865.88
    }
    terrain_level_point {
      sim_grid_pos_x: 605336.625
      sim_grid_pos_y: 1766217.38
    }
    terrain_level_point {
      sim_grid_pos_x: 605659.25
      sim_grid_pos_y: 1766728
    }
    terrain_level_point {
      sim_grid_pos_x: 605573.375
      sim_grid_pos_y: 1766829.62
    }
    terrain_level_point {
      sim_grid_pos_x: 605642.812
      sim_grid_pos_y: 1767009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605777.875
      sim_grid_pos_y: 1767182.38
    }
    terrain_level_point {
      sim_grid_pos_x: 605931.812
      sim_grid_pos_y: 1767335.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606024.875
      sim_grid_pos_y: 1767398.12
    }
    terrain_level_point {
      sim_grid_pos_x: 606094.562
      sim_grid_pos_y: 1767749.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607273.75
      sim_grid_pos_y: 1767882.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607021.375
      sim_grid_pos_y: 1768428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607090.25
      sim_grid_pos_y: 1768824
    }
    terrain_level_point {
      sim_grid_pos_x: 606942.062
      sim_grid_pos_y: 1769207.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607166.938
      sim_grid_pos_y: 1769446.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 605141.812
      sim_grid_pos_y: 1764645
    }
    terrain_level_point {
      sim_grid_pos_x: 605011.438
      sim_grid_pos_y: 1765133.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605093.5
      sim_grid_pos_y: 1765243
    }
    terrain_level_point {
      sim_grid_pos_x: 605028.375
      sim_grid_pos_y: 1765506.62
    }
    terrain_level_point {
      sim_grid_pos_x: 605188.062
      sim_grid_pos_y: 1765852.38
    }
    terrain_level_point {
      sim_grid_pos_x: 605363.438
      sim_grid_pos_y: 1766202.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605697.25
      sim_grid_pos_y: 1766730.62
    }
    terrain_level_point {
      sim_grid_pos_x: 605608.625
      sim_grid_pos_y: 1766835.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605669.875
      sim_grid_pos_y: 1766994.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605800.938
      sim_grid_pos_y: 1767161.88
    }
    terrain_level_point {
      sim_grid_pos_x: 605951.375
      sim_grid_pos_y: 1767311.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606052.625
      sim_grid_pos_y: 1767379.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606120.375
      sim_grid_pos_y: 1767721.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607319.562
      sim_grid_pos_y: 1767856.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607053.375
      sim_grid_pos_y: 1768432.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607122
      sim_grid_pos_y: 1768827.12
    }
    terrain_level_point {
      sim_grid_pos_x: 606977.75
      sim_grid_pos_y: 1769200.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607211.5
      sim_grid_pos_y: 1769449
    }
    terrain_level_point {
      sim_grid_pos_x: 606935.625
      sim_grid_pos_y: 1769683.12
    }
    terrain_level_point {
      sim_grid_pos_x: 606956.875
      sim_grid_pos_y: 1770043.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607024.812
      sim_grid_pos_y: 1770428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607288.625
      sim_grid_pos_y: 1.77079e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 607342
      sim_grid_pos_y: 1770922.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607101
      sim_grid_pos_y: 1771362.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606483.312
      sim_grid_pos_y: 1771688.88
    }
    terrain_level_point {
      sim_grid_pos_x: 606452.062
      sim_grid_pos_y: 1771665.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606550.25
      sim_grid_pos_y: 1771209
    }
    terrain_level_point {
      sim_grid_pos_x: 606582.562
      sim_grid_pos_y: 1770965.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606247.562
      sim_grid_pos_y: 1770781.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606080.562
      sim_grid_pos_y: 1770241.38
    }
    terrain_level_point {
      sim_grid_pos_x: 605427.312
      sim_grid_pos_y: 1770215
    }
    terrain_level_point {
      sim_grid_pos_x: 605229.5
      sim_grid_pos_y: 1770029.38
    }
    terrain_level_point {
      sim_grid_pos_x: 604498.375
      sim_grid_pos_y: 1770028.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603906.812
      sim_grid_pos_y: 1769209.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603649.688
      sim_grid_pos_y: 1768641.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603792.25
      sim_grid_pos_y: 1768377.62
    }
    terrain_level_point {
      sim_grid_pos_x: 604009.688
      sim_grid_pos_y: 1768266.38
    }
    terrain_level_point {
      sim_grid_pos_x: 604060.438
      sim_grid_pos_y: 1768186.62
    }
    terrain_level_point {
      sim_grid_pos_x: 603804.125
      sim_grid_pos_y: 1767803.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603823.875
      sim_grid_pos_y: 1767400.5
    }
    terrain_level_point {
      sim_grid_pos_x: 604101.125
      sim_grid_pos_y: 1767089.38
    }
    terrain_level_point {
      sim_grid_pos_x: 604216.562
      sim_grid_pos_y: 1766549.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603256.938
      sim_grid_pos_y: 1765708.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603081.375
      sim_grid_pos_y: 1765625.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603192.688
      sim_grid_pos_y: 1765434.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603365.562
      sim_grid_pos_y: 1765447.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603525.125
      sim_grid_pos_y: 1765170.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603946
      sim_grid_pos_y: 1764643.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604512.125
      sim_grid_pos_y: 1764479.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 605179.5
      sim_grid_pos_y: 1764623
    }
    terrain_level_point {
      sim_grid_pos_x: 605045
      sim_grid_pos_y: 1765126.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605126.875
      sim_grid_pos_y: 1765236.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605060.812
      sim_grid_pos_y: 1765503.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605215.75
      sim_grid_pos_y: 1765839.12
    }
    terrain_level_point {
      sim_grid_pos_x: 605390.25
      sim_grid_pos_y: 1766187.12
    }
    terrain_level_point {
      sim_grid_pos_x: 605735.312
      sim_grid_pos_y: 1766733.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605643.938
      sim_grid_pos_y: 1766841.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605696.938
      sim_grid_pos_y: 1766978.88
    }
    terrain_level_point {
      sim_grid_pos_x: 605824.062
      sim_grid_pos_y: 1767141.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605970.938
      sim_grid_pos_y: 1767287.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606080.312
      sim_grid_pos_y: 1767361.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606146.125
      sim_grid_pos_y: 1767693.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607365.375
      sim_grid_pos_y: 1767830.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607085.312
      sim_grid_pos_y: 1768436.62
    }
    terrain_level_point {
      sim_grid_pos_x: 607153.812
      sim_grid_pos_y: 1768830.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607013.438
      sim_grid_pos_y: 1769193.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607256.062
      sim_grid_pos_y: 1769451.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606967.188
      sim_grid_pos_y: 1769696.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606987.438
      sim_grid_pos_y: 1770040.25
    }
    terrain_level_point {
      sim_grid_pos_x: 607053.875
      sim_grid_pos_y: 1770415.88
    }
    terrain_level_point {
      sim_grid_pos_x: 607315.75
      sim_grid_pos_y: 1770774.88
    }
    terrain_level_point {
      sim_grid_pos_x: 607376
      sim_grid_pos_y: 1770924.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607123.562
      sim_grid_pos_y: 1771385.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606480.312
      sim_grid_pos_y: 1771725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606417.875
      sim_grid_pos_y: 1771677.88
    }
    terrain_level_point {
      sim_grid_pos_x: 606519.938
      sim_grid_pos_y: 1771203.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606549.312
      sim_grid_pos_y: 1770982.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606221.875
      sim_grid_pos_y: 1770802.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606057.562
      sim_grid_pos_y: 1770271.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605414.625
      sim_grid_pos_y: 1770245.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605217.312
      sim_grid_pos_y: 1770060.12
    }
    terrain_level_point {
      sim_grid_pos_x: 604482.688
      sim_grid_pos_y: 1770059.62
    }
    terrain_level_point {
      sim_grid_pos_x: 603880.062
      sim_grid_pos_y: 1769225
    }
    terrain_level_point {
      sim_grid_pos_x: 603615.375
      sim_grid_pos_y: 1768640.62
    }
    terrain_level_point {
      sim_grid_pos_x: 603769.688
      sim_grid_pos_y: 1768354.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603988.188
      sim_grid_pos_y: 1768242.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604023.688
      sim_grid_pos_y: 1768187
    }
    terrain_level_point {
      sim_grid_pos_x: 603772.938
      sim_grid_pos_y: 1767812.38
    }
    terrain_level_point {
      sim_grid_pos_x: 603793.625
      sim_grid_pos_y: 1767388.12
    }
    terrain_level_point {
      sim_grid_pos_x: 604072.75
      sim_grid_pos_y: 1767075
    }
    terrain_level_point {
      sim_grid_pos_x: 604182.75
      sim_grid_pos_y: 1766561
    }
    terrain_level_point {
      sim_grid_pos_x: 603239.938
      sim_grid_pos_y: 1765734.75
    }
    terrain_level_point {
      sim_grid_pos_x: 603037.875
      sim_grid_pos_y: 1765639.38
    }
    terrain_level_point {
      sim_grid_pos_x: 603175.75
      sim_grid_pos_y: 1765402.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603348.562
      sim_grid_pos_y: 1765415.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603499.625
      sim_grid_pos_y: 1765152.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603928.062
      sim_grid_pos_y: 1764616.88
    }
    terrain_level_point {
      sim_grid_pos_x: 604511.688
      sim_grid_pos_y: 1764447.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 605217.188
      sim_grid_pos_y: 1764601.12
    }
    terrain_level_point {
      sim_grid_pos_x: 605078.562
      sim_grid_pos_y: 1765120.25
    }
    terrain_level_point {
      sim_grid_pos_x: 605160.188
      sim_grid_pos_y: 1765229.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605093.25
      sim_grid_pos_y: 1765500.38
    }
    terrain_level_point {
      sim_grid_pos_x: 605243.5
      sim_grid_pos_y: 1765825.75
    }
    terrain_level_point {
      sim_grid_pos_x: 605417.062
      sim_grid_pos_y: 1766171.88
    }
    terrain_level_point {
      sim_grid_pos_x: 605773.375
      sim_grid_pos_y: 1766735.88
    }
    terrain_level_point {
      sim_grid_pos_x: 605679.188
      sim_grid_pos_y: 1766847.38
    }
    terrain_level_point {
      sim_grid_pos_x: 605723.938
      sim_grid_pos_y: 1766963.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605847
      sim_grid_pos_y: 1767121
    }
    terrain_level_point {
      sim_grid_pos_x: 605990.625
      sim_grid_pos_y: 1767263.88
    }
    terrain_level_point {
      sim_grid_pos_x: 606108
      sim_grid_pos_y: 1767342.75
    }
    terrain_level_point {
      sim_grid_pos_x: 606171.938
      sim_grid_pos_y: 1767665.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607411.188
      sim_grid_pos_y: 1767805
    }
    terrain_level_point {
      sim_grid_pos_x: 607117.25
      sim_grid_pos_y: 1768440.75
    }
    terrain_level_point {
      sim_grid_pos_x: 607185.562
      sim_grid_pos_y: 1768833.38
    }
    terrain_level_point {
      sim_grid_pos_x: 607049.062
      sim_grid_pos_y: 1769186.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607300.688
      sim_grid_pos_y: 1769454
    }
    terrain_level_point {
      sim_grid_pos_x: 606998.812
      sim_grid_pos_y: 1769710.12
    }
    terrain_level_point {
      sim_grid_pos_x: 607018.062
      sim_grid_pos_y: 1770036.62
    }
    terrain_level_point {
      sim_grid_pos_x: 607082.938
      sim_grid_pos_y: 1770403.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607342.812
      sim_grid_pos_y: 1770759.88
    }
    terrain_level_point {
      sim_grid_pos_x: 607409.938
      sim_grid_pos_y: 1770926.5
    }
    terrain_level_point {
      sim_grid_pos_x: 607146.125
      sim_grid_pos_y: 1771408.38
    }
    terrain_level_point {
      sim_grid_pos_x: 606477.375
      sim_grid_pos_y: 1771761.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606383.688
      sim_grid_pos_y: 1771690.62
    }
    terrain_level_point {
      sim_grid_pos_x: 606489.625
      sim_grid_pos_y: 1771198.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606516.062
      sim_grid_pos_y: 1770999.25
    }
    terrain_level_point {
      sim_grid_pos_x: 606196.188
      sim_grid_pos_y: 1770823.5
    }
    terrain_level_point {
      sim_grid_pos_x: 606034.625
      sim_grid_pos_y: 1770301
    }
    terrain_level_point {
      sim_grid_pos_x: 605401.938
      sim_grid_pos_y: 1770275.5
    }
    terrain_level_point {
      sim_grid_pos_x: 605205.125
      sim_grid_pos_y: 1770090.88
    }
    terrain_level_point {
      sim_grid_pos_x: 604466.938
      sim_grid_pos_y: 1770090.38
    }
    terrain_level_point {
      sim_grid_pos_x: 603853.312
      sim_grid_pos_y: 1769240.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603581.062
      sim_grid_pos_y: 1768639.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603747.188
      sim_grid_pos_y: 1768331.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603966.75
      sim_grid_pos_y: 1768219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603987
      sim_grid_pos_y: 1768187.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603741.688
      sim_grid_pos_y: 1767821.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603763.438
      sim_grid_pos_y: 1767375.75
    }
    terrain_level_point {
      sim_grid_pos_x: 604044.375
      sim_grid_pos_y: 1767060.62
    }
    terrain_level_point {
      sim_grid_pos_x: 604148.875
      sim_grid_pos_y: 1766572.25
    }
    terrain_level_point {
      sim_grid_pos_x: 603222.875
      sim_grid_pos_y: 1765760.75
    }
    terrain_level_point {
      sim_grid_pos_x: 602994.375
      sim_grid_pos_y: 1765652.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603158.875
      sim_grid_pos_y: 1765370.88
    }
    terrain_level_point {
      sim_grid_pos_x: 603331.5
      sim_grid_pos_y: 1765383.12
    }
    terrain_level_point {
      sim_grid_pos_x: 603474.125
      sim_grid_pos_y: 1765135.5
    }
    terrain_level_point {
      sim_grid_pos_x: 603910.125
      sim_grid_pos_y: 1.76459e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 604511.312
      sim_grid_pos_y: 1764416
    }
  }
}
