terrain_level_data {
  terrain_level: 1300
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2879882.75
      sim_grid_pos_y: 1273719.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2879203
      sim_grid_pos_y: 1273191.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879095.25
      sim_grid_pos_y: 1273229.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2878668.5
      sim_grid_pos_y: 1272935.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2878433.5
      sim_grid_pos_y: 1273186.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2878143.75
      sim_grid_pos_y: 1272990.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2877349.25
      sim_grid_pos_y: 1272688.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2876175
      sim_grid_pos_y: 1274552.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2876939
      sim_grid_pos_y: 1275148.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2877518.5
      sim_grid_pos_y: 1275477.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2879009.5
      sim_grid_pos_y: 1276561
    }
    terrain_level_point {
      sim_grid_pos_x: 2.87994e+06
      sim_grid_pos_y: 1277279.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2879965.25
      sim_grid_pos_y: 1276865.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2880674.75
      sim_grid_pos_y: 1275411.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2881023.25
      sim_grid_pos_y: 1275057.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2881041.75
      sim_grid_pos_y: 1274680.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2880341.75
      sim_grid_pos_y: 1274509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2880560.25
      sim_grid_pos_y: 1274180.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2877336.75
      sim_grid_pos_y: 1272650.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2876134.25
      sim_grid_pos_y: 1274559.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2876921.75
      sim_grid_pos_y: 1275174
    }
    terrain_level_point {
      sim_grid_pos_x: 2877501.75
      sim_grid_pos_y: 1275503
    }
    terrain_level_point {
      sim_grid_pos_x: 2878991
      sim_grid_pos_y: 1276585.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2879935.75
      sim_grid_pos_y: 1277315
    }
    terrain_level_point {
      sim_grid_pos_x: 2879969.5
      sim_grid_pos_y: 1277299.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2879995.75
      sim_grid_pos_y: 1276873.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.8807e+06
      sim_grid_pos_y: 1275429.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2881053.5
      sim_grid_pos_y: 1275070.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2881073.5
      sim_grid_pos_y: 1274656.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880391.5
      sim_grid_pos_y: 1.27449e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2880602.75
      sim_grid_pos_y: 1274171.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2879900.75
      sim_grid_pos_y: 1273694.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2879208.5
      sim_grid_pos_y: 1273157.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.8791e+06
      sim_grid_pos_y: 1273195.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878664
      sim_grid_pos_y: 1272894.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2878429
      sim_grid_pos_y: 1273146.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2878158.25
      sim_grid_pos_y: 1272962.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2877324.25
      sim_grid_pos_y: 1272613
    }
    terrain_level_point {
      sim_grid_pos_x: 2876093.25
      sim_grid_pos_y: 1274566.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2876904.75
      sim_grid_pos_y: 1275199.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2877485.25
      sim_grid_pos_y: 1275529
    }
    terrain_level_point {
      sim_grid_pos_x: 2878972.75
      sim_grid_pos_y: 1276610.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2879931.5
      sim_grid_pos_y: 1277350.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2879999
      sim_grid_pos_y: 1.27732e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2880026
      sim_grid_pos_y: 1276881.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2880725.5
      sim_grid_pos_y: 1275447.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2881083.5
      sim_grid_pos_y: 1275084.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2881105.5
      sim_grid_pos_y: 1274632.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2880441.5
      sim_grid_pos_y: 1274470.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2880645.25
      sim_grid_pos_y: 1274163.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2879919
      sim_grid_pos_y: 1273669.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2879214.25
      sim_grid_pos_y: 1273122.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2879104.5
      sim_grid_pos_y: 1273161
    }
    terrain_level_point {
      sim_grid_pos_x: 2878659.75
      sim_grid_pos_y: 1272854.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2878424.5
      sim_grid_pos_y: 1273106.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2878172.5
      sim_grid_pos_y: 1272935.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2877311.5
      sim_grid_pos_y: 1272575.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2876052.5
      sim_grid_pos_y: 1274573.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2876887.5
      sim_grid_pos_y: 1275225.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2877468.5
      sim_grid_pos_y: 1275554.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2878954.25
      sim_grid_pos_y: 1276634.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2879927.5
      sim_grid_pos_y: 1277386.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2880028.5
      sim_grid_pos_y: 1277340.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2880056.25
      sim_grid_pos_y: 1276889.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2880751
      sim_grid_pos_y: 1275465.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2881113.75
      sim_grid_pos_y: 1275097.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2881137.5
      sim_grid_pos_y: 1274608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2880491.25
      sim_grid_pos_y: 1274451
    }
    terrain_level_point {
      sim_grid_pos_x: 2880687.75
      sim_grid_pos_y: 1274155.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2879937
      sim_grid_pos_y: 1273644.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2879219.75
      sim_grid_pos_y: 1273088.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2879109
      sim_grid_pos_y: 1273126.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2878655.25
      sim_grid_pos_y: 1272814
    }
    terrain_level_point {
      sim_grid_pos_x: 2.87842e+06
      sim_grid_pos_y: 1273066
    }
    terrain_level_point {
      sim_grid_pos_x: 2878186.75
      sim_grid_pos_y: 1272907.88
    }
  }
}
