terrain_level_data {
  terrain_level: 1330
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2454811.5
      sim_grid_pos_y: 1390046
    }
    terrain_level_point {
      sim_grid_pos_x: 2455396
      sim_grid_pos_y: 1390043.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2458409.75
      sim_grid_pos_y: 1388844.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2459115
      sim_grid_pos_y: 1388440.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2459856.5
      sim_grid_pos_y: 1387657.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2459414
      sim_grid_pos_y: 1386912.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2458994.75
      sim_grid_pos_y: 1386483
    }
    terrain_level_point {
      sim_grid_pos_x: 2.45793e+06
      sim_grid_pos_y: 1387405.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2457713.25
      sim_grid_pos_y: 1388172.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2457654.5
      sim_grid_pos_y: 1388340.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2457077.75
      sim_grid_pos_y: 1388645.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2456717.75
      sim_grid_pos_y: 1388732.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2456249.25
      sim_grid_pos_y: 1389098.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2455328.75
      sim_grid_pos_y: 1389598.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2458996.5
      sim_grid_pos_y: 1386440.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2457903
      sim_grid_pos_y: 1387388.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2457683.75
      sim_grid_pos_y: 1388163.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2457629.5
      sim_grid_pos_y: 1388318.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2457066.75
      sim_grid_pos_y: 1388616.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2456704
      sim_grid_pos_y: 1388704.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2456232.25
      sim_grid_pos_y: 1389072.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2455311.25
      sim_grid_pos_y: 1389572.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2454775.25
      sim_grid_pos_y: 1390036.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2454790.25
      sim_grid_pos_y: 1390076.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2455401.75
      sim_grid_pos_y: 1390074.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2458423.25
      sim_grid_pos_y: 1388872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2459134.25
      sim_grid_pos_y: 1388464.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2459894.75
      sim_grid_pos_y: 1387661.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2459438.5
      sim_grid_pos_y: 1386893.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2458998.25
      sim_grid_pos_y: 1386398.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2457876
      sim_grid_pos_y: 1387371.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2457654.5
      sim_grid_pos_y: 1388154.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2457604.5
      sim_grid_pos_y: 1388297.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2457055.75
      sim_grid_pos_y: 1388587.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2456690.25
      sim_grid_pos_y: 1388676.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2456215.5
      sim_grid_pos_y: 1389046.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2455293.5
      sim_grid_pos_y: 1389547.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2454738.75
      sim_grid_pos_y: 1390027.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2454769
      sim_grid_pos_y: 1390107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2455407.75
      sim_grid_pos_y: 1390105.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2458436.5
      sim_grid_pos_y: 1388900.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2459153.5
      sim_grid_pos_y: 1388489.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2459933
      sim_grid_pos_y: 1387665.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2459463
      sim_grid_pos_y: 1386874.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2.459e+06
      sim_grid_pos_y: 1386356.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2457848.75
      sim_grid_pos_y: 1387353.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2457625.25
      sim_grid_pos_y: 1388145
    }
    terrain_level_point {
      sim_grid_pos_x: 2457579.5
      sim_grid_pos_y: 1388275.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2457044.75
      sim_grid_pos_y: 1388558.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2456676.5
      sim_grid_pos_y: 1388647.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2456198.5
      sim_grid_pos_y: 1389020.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2455276
      sim_grid_pos_y: 1389521.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2454702.5
      sim_grid_pos_y: 1390018.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2454747.5
      sim_grid_pos_y: 1390138.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2455413.75
      sim_grid_pos_y: 1390136
    }
    terrain_level_point {
      sim_grid_pos_x: 2.45845e+06
      sim_grid_pos_y: 1388927.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2459172.5
      sim_grid_pos_y: 1388513.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2459971.5
      sim_grid_pos_y: 1387670.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2459487.5
      sim_grid_pos_y: 1386855.62
    }
  }
}
