terrain_level_data {
  terrain_level: 170
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 475021.156
      sim_grid_pos_y: 2039118.38
    }
    terrain_level_point {
      sim_grid_pos_x: 475544.688
      sim_grid_pos_y: 2037863.75
    }
    terrain_level_point {
      sim_grid_pos_x: 479359.594
      sim_grid_pos_y: 2040553.62
    }
    terrain_level_point {
      sim_grid_pos_x: 478964.156
      sim_grid_pos_y: 2041652.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 479421.062
      sim_grid_pos_y: 2040534.25
    }
    terrain_level_point {
      sim_grid_pos_x: 478990.562
      sim_grid_pos_y: 2041730.12
    }
    terrain_level_point {
      sim_grid_pos_x: 474957.281
      sim_grid_pos_y: 2039138.25
    }
    terrain_level_point {
      sim_grid_pos_x: 475522
      sim_grid_pos_y: 2037785
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 479482.5
      sim_grid_pos_y: 2040514.88
    }
    terrain_level_point {
      sim_grid_pos_x: 479017
      sim_grid_pos_y: 2041808.12
    }
    terrain_level_point {
      sim_grid_pos_x: 474893.438
      sim_grid_pos_y: 2039158.12
    }
    terrain_level_point {
      sim_grid_pos_x: 475499.281
      sim_grid_pos_y: 2037706.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 479543.969
      sim_grid_pos_y: 2040495.5
    }
    terrain_level_point {
      sim_grid_pos_x: 479043.438
      sim_grid_pos_y: 2041886
    }
    terrain_level_point {
      sim_grid_pos_x: 474829.594
      sim_grid_pos_y: 2039178
    }
    terrain_level_point {
      sim_grid_pos_x: 475476.594
      sim_grid_pos_y: 2037627.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 479605.438
      sim_grid_pos_y: 2040476.12
    }
    terrain_level_point {
      sim_grid_pos_x: 479069.875
      sim_grid_pos_y: 2041964
    }
    terrain_level_point {
      sim_grid_pos_x: 474765.719
      sim_grid_pos_y: 2039197.88
    }
    terrain_level_point {
      sim_grid_pos_x: 475453.906
      sim_grid_pos_y: 2037548.88
    }
  }
}
