terrain_level_data {
  terrain_level: 400
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1433081
      sim_grid_pos_y: 1740074.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433233.12
      sim_grid_pos_y: 1740195
    }
    terrain_level_point {
      sim_grid_pos_x: 1433581.38
      sim_grid_pos_y: 1740185.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1433874.12
      sim_grid_pos_y: 1740263.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434170.75
      sim_grid_pos_y: 1740310.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434559.88
      sim_grid_pos_y: 1740481
    }
    terrain_level_point {
      sim_grid_pos_x: 1434757.25
      sim_grid_pos_y: 1740540.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435728
      sim_grid_pos_y: 1740633.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435627.25
      sim_grid_pos_y: 1.74113e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1435380.25
      sim_grid_pos_y: 1741080.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434535.25
      sim_grid_pos_y: 1740929
    }
    terrain_level_point {
      sim_grid_pos_x: 1434433.75
      sim_grid_pos_y: 1741138.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434535.38
      sim_grid_pos_y: 1741244
    }
    terrain_level_point {
      sim_grid_pos_x: 1434805.62
      sim_grid_pos_y: 1741241.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434814.88
      sim_grid_pos_y: 1741630.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434650.75
      sim_grid_pos_y: 1741704.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434065.38
      sim_grid_pos_y: 1741583.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433775.62
      sim_grid_pos_y: 1741458.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433625.5
      sim_grid_pos_y: 1741316
    }
    terrain_level_point {
      sim_grid_pos_x: 1433308
      sim_grid_pos_y: 1741298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433247.12
      sim_grid_pos_y: 1741154.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432944.25
      sim_grid_pos_y: 1741099.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1433243.5
      sim_grid_pos_y: 1740164
    }
    terrain_level_point {
      sim_grid_pos_x: 1433585
      sim_grid_pos_y: 1740154.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433880.5
      sim_grid_pos_y: 1740233.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434179.38
      sim_grid_pos_y: 1740280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434570.62
      sim_grid_pos_y: 1740452
    }
    terrain_level_point {
      sim_grid_pos_x: 1434763.12
      sim_grid_pos_y: 1.74051e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1435764.88
      sim_grid_pos_y: 1740606
    }
    terrain_level_point {
      sim_grid_pos_x: 1435651.25
      sim_grid_pos_y: 1741166.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1435374.12
      sim_grid_pos_y: 1741110.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1435374.12
      sim_grid_pos_y: 1741110.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434552.75
      sim_grid_pos_y: 1740963.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434470.75
      sim_grid_pos_y: 1741132.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434548.38
      sim_grid_pos_y: 1741213.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434835.62
      sim_grid_pos_y: 1741210.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434846.12
      sim_grid_pos_y: 1741649.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434654.38
      sim_grid_pos_y: 1741736.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434056
      sim_grid_pos_y: 1741613
    }
    terrain_level_point {
      sim_grid_pos_x: 1433758.38
      sim_grid_pos_y: 1741485
    }
    terrain_level_point {
      sim_grid_pos_x: 1433612.5
      sim_grid_pos_y: 1741346.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433287.12
      sim_grid_pos_y: 1741327.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433225.38
      sim_grid_pos_y: 1741181.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1432909.88
      sim_grid_pos_y: 1741124.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1433052.88
      sim_grid_pos_y: 1740053
    }
    terrain_level_point {
      sim_grid_pos_x: 1433086.12
      sim_grid_pos_y: 1740039.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1433253.75
      sim_grid_pos_y: 1740132.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433588.62
      sim_grid_pos_y: 1740123.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1433886.88
      sim_grid_pos_y: 1740203.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434188.12
      sim_grid_pos_y: 1740250.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434581.12
      sim_grid_pos_y: 1740423.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434769.12
      sim_grid_pos_y: 1740479.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1435801.88
      sim_grid_pos_y: 1740578.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1435675.38
      sim_grid_pos_y: 1741202.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435368.62
      sim_grid_pos_y: 1741140.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434570.25
      sim_grid_pos_y: 1740997.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434507.75
      sim_grid_pos_y: 1741126.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434561.38
      sim_grid_pos_y: 1741182.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434865.62
      sim_grid_pos_y: 1741179.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434877.38
      sim_grid_pos_y: 1741669.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434657.88
      sim_grid_pos_y: 1741768.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434046.75
      sim_grid_pos_y: 1741642.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433741.25
      sim_grid_pos_y: 1741511
    }
    terrain_level_point {
      sim_grid_pos_x: 1433599.5
      sim_grid_pos_y: 1741376.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433266.25
      sim_grid_pos_y: 1741357.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433203.5
      sim_grid_pos_y: 1741209
    }
    terrain_level_point {
      sim_grid_pos_x: 1432875.5
      sim_grid_pos_y: 1741149.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433024.75
      sim_grid_pos_y: 1740031.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433091.12
      sim_grid_pos_y: 1740004.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1433264.12
      sim_grid_pos_y: 1740101.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433592.25
      sim_grid_pos_y: 1740092.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1433893.25
      sim_grid_pos_y: 1740173.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434196.88
      sim_grid_pos_y: 1740221.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434591.88
      sim_grid_pos_y: 1740394.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1434775.12
      sim_grid_pos_y: 1740449.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1435838.75
      sim_grid_pos_y: 1740551.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1435699.38
      sim_grid_pos_y: 1741238.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1435363
      sim_grid_pos_y: 1741171.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434587.75
      sim_grid_pos_y: 1741032.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434544.88
      sim_grid_pos_y: 1741120.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434574.38
      sim_grid_pos_y: 1741151.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434895.62
      sim_grid_pos_y: 1741148.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1434908.5
      sim_grid_pos_y: 1741689.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1434661.5
      sim_grid_pos_y: 1741800.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434037.5
      sim_grid_pos_y: 1741672
    }
    terrain_level_point {
      sim_grid_pos_x: 1433724
      sim_grid_pos_y: 1741537.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433586.5
      sim_grid_pos_y: 1741406.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433245.38
      sim_grid_pos_y: 1741387.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433181.62
      sim_grid_pos_y: 1741236.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1432841.12
      sim_grid_pos_y: 1741174.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1432996.62
      sim_grid_pos_y: 1740009.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433096.12
      sim_grid_pos_y: 1739969.25
    }
  }
}
terrain_level_data {
  terrain_level: 390
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1434315
      sim_grid_pos_y: 1741881.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434380.12
      sim_grid_pos_y: 1742126
    }
    terrain_level_point {
      sim_grid_pos_x: 1434099.88
      sim_grid_pos_y: 1742232.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433732
      sim_grid_pos_y: 1742293
    }
    terrain_level_point {
      sim_grid_pos_x: 1433253.12
      sim_grid_pos_y: 1742419.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1432914.25
      sim_grid_pos_y: 1742491.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1432710.12
      sim_grid_pos_y: 1742513.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1432765.12
      sim_grid_pos_y: 1742068
    }
    terrain_level_point {
      sim_grid_pos_x: 1433245
      sim_grid_pos_y: 1741965.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1433316.62
      sim_grid_pos_y: 1741891.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1434417
      sim_grid_pos_y: 1742144.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1434108
      sim_grid_pos_y: 1742262.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433738.38
      sim_grid_pos_y: 1742323.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433260.25
      sim_grid_pos_y: 1742449.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1432919
      sim_grid_pos_y: 1742522
    }
    terrain_level_point {
      sim_grid_pos_x: 1432674.88
      sim_grid_pos_y: 1742548
    }
    terrain_level_point {
      sim_grid_pos_x: 1432737.25
      sim_grid_pos_y: 1742042.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433229.38
      sim_grid_pos_y: 1741937.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433303.38
      sim_grid_pos_y: 1741860.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434338.5
      sim_grid_pos_y: 1741850.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1434454
      sim_grid_pos_y: 1742163.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1434116
      sim_grid_pos_y: 1742292
    }
    terrain_level_point {
      sim_grid_pos_x: 1433744.88
      sim_grid_pos_y: 1742353.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433267.38
      sim_grid_pos_y: 1742479.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1432923.88
      sim_grid_pos_y: 1742552.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432639.62
      sim_grid_pos_y: 1742582.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1432709.38
      sim_grid_pos_y: 1742017
    }
    terrain_level_point {
      sim_grid_pos_x: 1433213.75
      sim_grid_pos_y: 1741909.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1433290.25
      sim_grid_pos_y: 1.74183e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1434362.12
      sim_grid_pos_y: 1741819.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1434490.88
      sim_grid_pos_y: 1742182.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1434124
      sim_grid_pos_y: 1742321.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1433751.38
      sim_grid_pos_y: 1742383.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1433274.5
      sim_grid_pos_y: 1742509
    }
    terrain_level_point {
      sim_grid_pos_x: 1432928.75
      sim_grid_pos_y: 1742582.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1432604.25
      sim_grid_pos_y: 1742617.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1432681.5
      sim_grid_pos_y: 1741991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1433198.25
      sim_grid_pos_y: 1741881
    }
    terrain_level_point {
      sim_grid_pos_x: 1433277
      sim_grid_pos_y: 1741799.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1434385.62
      sim_grid_pos_y: 1741788.75
    }
  }
}
