terrain_level_data {
  terrain_level: 210
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2720009.75
      sim_grid_pos_y: 522809.781
    }
    terrain_level_point {
      sim_grid_pos_x: 2718188.75
      sim_grid_pos_y: 522769.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2718139.5
      sim_grid_pos_y: 522645.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2718095.5
      sim_grid_pos_y: 522354.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2718212.25
      sim_grid_pos_y: 521018.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2718696
      sim_grid_pos_y: 520986.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2719101.75
      sim_grid_pos_y: 520920.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2720388.5
      sim_grid_pos_y: 520933.375
    }
    terrain_level_point {
      sim_grid_pos_x: 2720290.75
      sim_grid_pos_y: 522781.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2720420.75
      sim_grid_pos_y: 520902.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2720320.25
      sim_grid_pos_y: 522809.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2720011
      sim_grid_pos_y: 522840.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2718167.5
      sim_grid_pos_y: 522799.688
    }
    terrain_level_point {
      sim_grid_pos_x: 2718109.5
      sim_grid_pos_y: 522653.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2718064.5
      sim_grid_pos_y: 522355.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2718183.75
      sim_grid_pos_y: 520990
    }
    terrain_level_point {
      sim_grid_pos_x: 2718692.5
      sim_grid_pos_y: 520955.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2719099.25
      sim_grid_pos_y: 520889.969
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2720453.25
      sim_grid_pos_y: 520872.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2720349.5
      sim_grid_pos_y: 522837.031
    }
    terrain_level_point {
      sim_grid_pos_x: 2720012.25
      sim_grid_pos_y: 522871.344
    }
    terrain_level_point {
      sim_grid_pos_x: 2718146.5
      sim_grid_pos_y: 522830
    }
    terrain_level_point {
      sim_grid_pos_x: 2718079.75
      sim_grid_pos_y: 522661.312
    }
    terrain_level_point {
      sim_grid_pos_x: 2718033.5
      sim_grid_pos_y: 522356.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2718155.5
      sim_grid_pos_y: 520961.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2718689
      sim_grid_pos_y: 520925.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2719097
      sim_grid_pos_y: 520859.188
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2720485.5
      sim_grid_pos_y: 520842.062
    }
    terrain_level_point {
      sim_grid_pos_x: 2720378.75
      sim_grid_pos_y: 522864.969
    }
    terrain_level_point {
      sim_grid_pos_x: 2720013.5
      sim_grid_pos_y: 522902.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2718125.5
      sim_grid_pos_y: 522860.281
    }
    terrain_level_point {
      sim_grid_pos_x: 2718049.75
      sim_grid_pos_y: 522669.406
    }
    terrain_level_point {
      sim_grid_pos_x: 2718002.5
      sim_grid_pos_y: 522357.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2718127.25
      sim_grid_pos_y: 520932.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2718685.5
      sim_grid_pos_y: 520894.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2719094.75
      sim_grid_pos_y: 520828.406
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2720518
      sim_grid_pos_y: 520811.594
    }
    terrain_level_point {
      sim_grid_pos_x: 2720408.25
      sim_grid_pos_y: 522892.906
    }
    terrain_level_point {
      sim_grid_pos_x: 2720014.75
      sim_grid_pos_y: 522932.938
    }
    terrain_level_point {
      sim_grid_pos_x: 2718104.25
      sim_grid_pos_y: 522890.562
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71802e+06
      sim_grid_pos_y: 522677.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2717971.5
      sim_grid_pos_y: 522358.844
    }
    terrain_level_point {
      sim_grid_pos_x: 2718098.75
      sim_grid_pos_y: 520903.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2718682
      sim_grid_pos_y: 520864
    }
    terrain_level_point {
      sim_grid_pos_x: 2719092.25
      sim_grid_pos_y: 520797.625
    }
  }
}
