terrain_level_data {
  terrain_level: 275
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1477985.38
      sim_grid_pos_y: 1229485.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1477966.5
      sim_grid_pos_y: 1229574.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1477789.88
      sim_grid_pos_y: 1229582.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1477800.25
      sim_grid_pos_y: 1229722
    }
    terrain_level_point {
      sim_grid_pos_x: 1478059.38
      sim_grid_pos_y: 1229723
    }
    terrain_level_point {
      sim_grid_pos_x: 1478101.5
      sim_grid_pos_y: 1229816
    }
    terrain_level_point {
      sim_grid_pos_x: 1478253.12
      sim_grid_pos_y: 1229754.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1478238.5
      sim_grid_pos_y: 1229574.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.47815e+06
      sim_grid_pos_y: 1229486
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1477943.88
      sim_grid_pos_y: 1229434.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1477924.62
      sim_grid_pos_y: 1229524.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1477734.75
      sim_grid_pos_y: 1229533.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1477752.62
      sim_grid_pos_y: 1229773.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1478026.25
      sim_grid_pos_y: 1229774.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1478075.12
      sim_grid_pos_y: 1229882
    }
    terrain_level_point {
      sim_grid_pos_x: 1478307.25
      sim_grid_pos_y: 1229788
    }
    terrain_level_point {
      sim_grid_pos_x: 1478288.12
      sim_grid_pos_y: 1229551.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1478171.25
      sim_grid_pos_y: 1229434.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1477902.38
      sim_grid_pos_y: 1229382.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1477882.62
      sim_grid_pos_y: 1229475.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1477679.75
      sim_grid_pos_y: 1229484.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1477705
      sim_grid_pos_y: 1229824.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1477993.12
      sim_grid_pos_y: 1229825.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1478048.75
      sim_grid_pos_y: 1229948
    }
    terrain_level_point {
      sim_grid_pos_x: 1478361.38
      sim_grid_pos_y: 1229821.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1478337.62
      sim_grid_pos_y: 1229529
    }
    terrain_level_point {
      sim_grid_pos_x: 1478192.62
      sim_grid_pos_y: 1229383.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1477861
      sim_grid_pos_y: 1229331.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1477840.75
      sim_grid_pos_y: 1229426
    }
    terrain_level_point {
      sim_grid_pos_x: 1477624.75
      sim_grid_pos_y: 1229435.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1477657.38
      sim_grid_pos_y: 1229875.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.47796e+06
      sim_grid_pos_y: 1229876.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1478022.38
      sim_grid_pos_y: 1230014
    }
    terrain_level_point {
      sim_grid_pos_x: 1478415.62
      sim_grid_pos_y: 1229854.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1478387.25
      sim_grid_pos_y: 1229506.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1478214
      sim_grid_pos_y: 1229332.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1477819.5
      sim_grid_pos_y: 1.22928e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1477798.88
      sim_grid_pos_y: 1229376.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1477569.75
      sim_grid_pos_y: 1229387.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1477609.75
      sim_grid_pos_y: 1229926.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1477926.88
      sim_grid_pos_y: 1229927.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1477996
      sim_grid_pos_y: 1.23008e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1478469.75
      sim_grid_pos_y: 1229888.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1478436.75
      sim_grid_pos_y: 1229483.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1478235.38
      sim_grid_pos_y: 1229281.12
    }
  }
}
terrain_level_data {
  terrain_level: 144
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1479893.5
      sim_grid_pos_y: 1228268
    }
    terrain_level_point {
      sim_grid_pos_x: 1479628
      sim_grid_pos_y: 1228480.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1479856.25
      sim_grid_pos_y: 1228774.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1480144.38
      sim_grid_pos_y: 1228543.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1479899.12
      sim_grid_pos_y: 1228197.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1479556.5
      sim_grid_pos_y: 1228471.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1479847.75
      sim_grid_pos_y: 1228847.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1480219
      sim_grid_pos_y: 1228549
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1479904.62
      sim_grid_pos_y: 1228127.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1479485
      sim_grid_pos_y: 1228463.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1479839.25
      sim_grid_pos_y: 1228920.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1480293.62
      sim_grid_pos_y: 1228554.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1479910.12
      sim_grid_pos_y: 1228057.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1479413.62
      sim_grid_pos_y: 1228454.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1479830.62
      sim_grid_pos_y: 1228992.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1480368.25
      sim_grid_pos_y: 1228560.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1479915.62
      sim_grid_pos_y: 1227987.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1479342.12
      sim_grid_pos_y: 1228446.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1479822.12
      sim_grid_pos_y: 1229065.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1480442.88
      sim_grid_pos_y: 1228566.25
    }
  }
}
terrain_level_data {
  terrain_level: 290
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1478605.88
      sim_grid_pos_y: 1229673
    }
    terrain_level_point {
      sim_grid_pos_x: 1478607.75
      sim_grid_pos_y: 1229936.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1478949.62
      sim_grid_pos_y: 1229932.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1478940.5
      sim_grid_pos_y: 1229669.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1478989.88
      sim_grid_pos_y: 1229617.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1478554.25
      sim_grid_pos_y: 1229622.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1478556.88
      sim_grid_pos_y: 1229988.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1479002.75
      sim_grid_pos_y: 1229982.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1479039.38
      sim_grid_pos_y: 1229566
    }
    terrain_level_point {
      sim_grid_pos_x: 1478502.62
      sim_grid_pos_y: 1229571.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1478506
      sim_grid_pos_y: 1230040.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1479055.88
      sim_grid_pos_y: 1230033.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1479088.88
      sim_grid_pos_y: 1229514.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1478451
      sim_grid_pos_y: 1229520.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1478455.12
      sim_grid_pos_y: 1230092.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1479108.88
      sim_grid_pos_y: 1230084
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1479138.38
      sim_grid_pos_y: 1229462.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1478399.38
      sim_grid_pos_y: 1.22947e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1478404.25
      sim_grid_pos_y: 1230144.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1479162
      sim_grid_pos_y: 1230134.62
    }
  }
}
