terrain_level_data {
  terrain_level: 4045
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1735742.25
      sim_grid_pos_y: 1805356.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1735743.25
      sim_grid_pos_y: 1805495.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735843
      sim_grid_pos_y: 1805565.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735977.75
      sim_grid_pos_y: 1805529.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1736005.12
      sim_grid_pos_y: 1805426.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735931.75
      sim_grid_pos_y: 1805318.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1735955.12
      sim_grid_pos_y: 1805261.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735690.62
      sim_grid_pos_y: 1805314.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1735692.12
      sim_grid_pos_y: 1805521.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735833.12
      sim_grid_pos_y: 1805621.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1736019.62
      sim_grid_pos_y: 1805571.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1736060.62
      sim_grid_pos_y: 1805416.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1735978.38
      sim_grid_pos_y: 1805204.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735639.12
      sim_grid_pos_y: 1805272.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735641.12
      sim_grid_pos_y: 1805548.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1735823.25
      sim_grid_pos_y: 1805676.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1736061.5
      sim_grid_pos_y: 1805613
    }
    terrain_level_point {
      sim_grid_pos_x: 1736116.12
      sim_grid_pos_y: 1805407.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1736001.62
      sim_grid_pos_y: 1805147.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735587.5
      sim_grid_pos_y: 1805231
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73559e+06
      sim_grid_pos_y: 1805575.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735813.25
      sim_grid_pos_y: 1805732.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1736103.5
      sim_grid_pos_y: 1805654.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1736171.75
      sim_grid_pos_y: 1805397.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1736024.88
      sim_grid_pos_y: 1805090.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735536
      sim_grid_pos_y: 1805189.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735539
      sim_grid_pos_y: 1805602.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735803.38
      sim_grid_pos_y: 1805788.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1736145.38
      sim_grid_pos_y: 1805696.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1736227.25
      sim_grid_pos_y: 1805388.5
    }
  }
}
terrain_level_data {
  terrain_level: 4125
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1735514.25
      sim_grid_pos_y: 1804531.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735516.38
      sim_grid_pos_y: 1804647.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735604
      sim_grid_pos_y: 1804725.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735682
      sim_grid_pos_y: 1804673.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735680.38
      sim_grid_pos_y: 1804534
    }
    terrain_level_point {
      sim_grid_pos_x: 1735608
      sim_grid_pos_y: 1804465.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1735612.75
      sim_grid_pos_y: 1804399.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735462.5
      sim_grid_pos_y: 1804505.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735465.5
      sim_grid_pos_y: 1804670.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1735599.5
      sim_grid_pos_y: 1804789.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1735733.62
      sim_grid_pos_y: 1804700.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735731.38
      sim_grid_pos_y: 1804511.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1735617.5
      sim_grid_pos_y: 1804333.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735410.75
      sim_grid_pos_y: 1804479.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735414.75
      sim_grid_pos_y: 1804694.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735595
      sim_grid_pos_y: 1804854.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735785.12
      sim_grid_pos_y: 1804727.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1735782.38
      sim_grid_pos_y: 1804489.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1735622.38
      sim_grid_pos_y: 1804267.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735359
      sim_grid_pos_y: 1804452.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735363.88
      sim_grid_pos_y: 1804717.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735590.5
      sim_grid_pos_y: 1804918.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735836.75
      sim_grid_pos_y: 1804755
    }
    terrain_level_point {
      sim_grid_pos_x: 1735833.5
      sim_grid_pos_y: 1804467.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1735627.12
      sim_grid_pos_y: 1804201.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1735307.25
      sim_grid_pos_y: 1804426.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1735313
      sim_grid_pos_y: 1804740.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1735586
      sim_grid_pos_y: 1804983.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1735888.38
      sim_grid_pos_y: 1804782.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1735884.5
      sim_grid_pos_y: 1804444.75
    }
  }
}
terrain_level_data {
  terrain_level: 3925
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1734870.25
      sim_grid_pos_y: 1803490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1734874.88
      sim_grid_pos_y: 1803810.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735303.88
      sim_grid_pos_y: 1803788
    }
    terrain_level_point {
      sim_grid_pos_x: 1735292.75
      sim_grid_pos_y: 1803464
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1735342.12
      sim_grid_pos_y: 1803409.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734818.25
      sim_grid_pos_y: 1803442.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734824.5
      sim_grid_pos_y: 1803864.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735356.75
      sim_grid_pos_y: 1803836.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1735391.62
      sim_grid_pos_y: 1803355
    }
    terrain_level_point {
      sim_grid_pos_x: 1734766.25
      sim_grid_pos_y: 1803394.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734774
      sim_grid_pos_y: 1803918.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735409.75
      sim_grid_pos_y: 1803885.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1735441
      sim_grid_pos_y: 1803300.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734714.25
      sim_grid_pos_y: 1803346.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734723.5
      sim_grid_pos_y: 1803972.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735462.75
      sim_grid_pos_y: 1803933.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1735490.5
      sim_grid_pos_y: 1803246
    }
    terrain_level_point {
      sim_grid_pos_x: 1734662.25
      sim_grid_pos_y: 1803298.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734673
      sim_grid_pos_y: 1804026.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1735515.62
      sim_grid_pos_y: 1803982.25
    }
  }
}
terrain_level_data {
  terrain_level: 3750
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1734683.88
      sim_grid_pos_y: 1803038.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734454.88
      sim_grid_pos_y: 1803251
    }
    terrain_level_point {
      sim_grid_pos_x: 1734277.62
      sim_grid_pos_y: 1803120.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734150.12
      sim_grid_pos_y: 1803137.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734125.25
      sim_grid_pos_y: 1803302.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1733723.75
      sim_grid_pos_y: 1803102.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73363e+06
      sim_grid_pos_y: 1802778.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734186.12
      sim_grid_pos_y: 1802801.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734328
      sim_grid_pos_y: 1802676.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1734757.5
      sim_grid_pos_y: 1803040.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1734458.62
      sim_grid_pos_y: 1803317.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734263.88
      sim_grid_pos_y: 1803174
    }
    terrain_level_point {
      sim_grid_pos_x: 1734195
      sim_grid_pos_y: 1803183.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734165.38
      sim_grid_pos_y: 1803379.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1733680.75
      sim_grid_pos_y: 1803138.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1733561
      sim_grid_pos_y: 1802724.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734167.75
      sim_grid_pos_y: 1802749.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734330.62
      sim_grid_pos_y: 1802606.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1734831
      sim_grid_pos_y: 1803041.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734462.38
      sim_grid_pos_y: 1803383.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734250.25
      sim_grid_pos_y: 1803227.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.73424e+06
      sim_grid_pos_y: 1803229
    }
    terrain_level_point {
      sim_grid_pos_x: 1734205.5
      sim_grid_pos_y: 1803456.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1733637.88
      sim_grid_pos_y: 1803174
    }
    terrain_level_point {
      sim_grid_pos_x: 1733491.88
      sim_grid_pos_y: 1802670.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1734149.38
      sim_grid_pos_y: 1802697.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734333.12
      sim_grid_pos_y: 1802535.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1734904.62
      sim_grid_pos_y: 1803043.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1734466.12
      sim_grid_pos_y: 1803450.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1734279.12
      sim_grid_pos_y: 1803312.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1734245.75
      sim_grid_pos_y: 1803533.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1733594.88
      sim_grid_pos_y: 1803209.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1733422.88
      sim_grid_pos_y: 1802616.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1734130.88
      sim_grid_pos_y: 1802645.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1734335.75
      sim_grid_pos_y: 1802465.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1734978.12
      sim_grid_pos_y: 1803045.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1734469.88
      sim_grid_pos_y: 1803516.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1734317.12
      sim_grid_pos_y: 1803404.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1734285.88
      sim_grid_pos_y: 1803611.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1733551.88
      sim_grid_pos_y: 1803245.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1733353.75
      sim_grid_pos_y: 1802562
    }
    terrain_level_point {
      sim_grid_pos_x: 1734112.5
      sim_grid_pos_y: 1802593.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1734338.25
      sim_grid_pos_y: 1802395
    }
  }
}
