terrain_level_data {
  terrain_level: 180
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1315491
      sim_grid_pos_y: 2133823.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314410.12
      sim_grid_pos_y: 2132701.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1313801.75
      sim_grid_pos_y: 2132317.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1313074
      sim_grid_pos_y: 2131388
    }
    terrain_level_point {
      sim_grid_pos_x: 1313018.25
      sim_grid_pos_y: 2131118.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1314112.38
      sim_grid_pos_y: 2130173
    }
    terrain_level_point {
      sim_grid_pos_x: 1314649.75
      sim_grid_pos_y: 2130630.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315380.12
      sim_grid_pos_y: 2131401.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315328.12
      sim_grid_pos_y: 2131534.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315579.75
      sim_grid_pos_y: 2132080.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315628.75
      sim_grid_pos_y: 2132223.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315476
      sim_grid_pos_y: 2132822.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315408.62
      sim_grid_pos_y: 2133145.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1314671
      sim_grid_pos_y: 2130608
    }
    terrain_level_point {
      sim_grid_pos_x: 1315415.88
      sim_grid_pos_y: 2131394.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315361.62
      sim_grid_pos_y: 2131533.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315608.38
      sim_grid_pos_y: 2132069
    }
    terrain_level_point {
      sim_grid_pos_x: 1315660.88
      sim_grid_pos_y: 2132221.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315506
      sim_grid_pos_y: 2132829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315439.75
      sim_grid_pos_y: 2133146.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315524.25
      sim_grid_pos_y: 2133842.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315484.25
      sim_grid_pos_y: 2133861.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1314390.62
      sim_grid_pos_y: 2132725.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1313780.88
      sim_grid_pos_y: 2132340.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1313045.38
      sim_grid_pos_y: 2131401.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1312984.5
      sim_grid_pos_y: 2131106.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314112.12
      sim_grid_pos_y: 2130132.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1314692.12
      sim_grid_pos_y: 2130585.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315451.62
      sim_grid_pos_y: 2131387.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315395
      sim_grid_pos_y: 2131532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315636.88
      sim_grid_pos_y: 2132057.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315692.88
      sim_grid_pos_y: 2132220.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315536
      sim_grid_pos_y: 2132836.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315470.88
      sim_grid_pos_y: 2133148
    }
    terrain_level_point {
      sim_grid_pos_x: 1315557.38
      sim_grid_pos_y: 2133860.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315477.38
      sim_grid_pos_y: 2133898.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314371
      sim_grid_pos_y: 2132749.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1313759.88
      sim_grid_pos_y: 2132363.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1313016.75
      sim_grid_pos_y: 2131414.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1312950.75
      sim_grid_pos_y: 2131095.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1314112
      sim_grid_pos_y: 2130091.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1314713.38
      sim_grid_pos_y: 2130563.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315487.38
      sim_grid_pos_y: 2131380.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315428.38
      sim_grid_pos_y: 2131531.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315665.5
      sim_grid_pos_y: 2132046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315725
      sim_grid_pos_y: 2132219.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315565.88
      sim_grid_pos_y: 2132843.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315502
      sim_grid_pos_y: 2133149.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315590.62
      sim_grid_pos_y: 2133878.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1315470.62
      sim_grid_pos_y: 2133935.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314351.5
      sim_grid_pos_y: 2132773.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1313739
      sim_grid_pos_y: 2132386.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1312988
      sim_grid_pos_y: 2131427.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1312917
      sim_grid_pos_y: 2131084
    }
    terrain_level_point {
      sim_grid_pos_x: 1314111.88
      sim_grid_pos_y: 2130051.25
    }
  }
}
terrain_level_data {
  terrain_level: 0
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1314683.88
      sim_grid_pos_y: 2132859.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1314683.88
      sim_grid_pos_y: 2133259.75
    }
  }
}
