terrain_level_data {
  terrain_level: 15
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 492022.156
      sim_grid_pos_y: 2021149.12
    }
    terrain_level_point {
      sim_grid_pos_x: 488091.875
      sim_grid_pos_y: 2018353.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487886.938
      sim_grid_pos_y: 2018294.38
    }
    terrain_level_point {
      sim_grid_pos_x: 487710.5
      sim_grid_pos_y: 2018352.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487630.969
      sim_grid_pos_y: 2018516.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487678
      sim_grid_pos_y: 2018841.38
    }
    terrain_level_point {
      sim_grid_pos_x: 488129.812
      sim_grid_pos_y: 2020509.75
    }
    terrain_level_point {
      sim_grid_pos_x: 488471.625
      sim_grid_pos_y: 2020147.75
    }
    terrain_level_point {
      sim_grid_pos_x: 488813.656
      sim_grid_pos_y: 2020247.25
    }
    terrain_level_point {
      sim_grid_pos_x: 489216.188
      sim_grid_pos_y: 2020548.38
    }
    terrain_level_point {
      sim_grid_pos_x: 489273.531
      sim_grid_pos_y: 2020696.88
    }
    terrain_level_point {
      sim_grid_pos_x: 489542.75
      sim_grid_pos_y: 2020967.38
    }
    terrain_level_point {
      sim_grid_pos_x: 489322.656
      sim_grid_pos_y: 2021329
    }
    terrain_level_point {
      sim_grid_pos_x: 488918.656
      sim_grid_pos_y: 2021829.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488627.375
      sim_grid_pos_y: 2021640.75
    }
    terrain_level_point {
      sim_grid_pos_x: 488391.219
      sim_grid_pos_y: 2021633.75
    }
    terrain_level_point {
      sim_grid_pos_x: 488408.156
      sim_grid_pos_y: 2022083.25
    }
    terrain_level_point {
      sim_grid_pos_x: 488940.438
      sim_grid_pos_y: 2022386.25
    }
    terrain_level_point {
      sim_grid_pos_x: 489474.469
      sim_grid_pos_y: 2022757.12
    }
    terrain_level_point {
      sim_grid_pos_x: 489890.188
      sim_grid_pos_y: 2022917
    }
    terrain_level_point {
      sim_grid_pos_x: 490311.312
      sim_grid_pos_y: 2022921.62
    }
    terrain_level_point {
      sim_grid_pos_x: 490624.188
      sim_grid_pos_y: 2022854.12
    }
    terrain_level_point {
      sim_grid_pos_x: 490949.719
      sim_grid_pos_y: 2022646.5
    }
    terrain_level_point {
      sim_grid_pos_x: 491086.812
      sim_grid_pos_y: 2022541.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 487886.125
      sim_grid_pos_y: 2018251.38
    }
    terrain_level_point {
      sim_grid_pos_x: 487681.156
      sim_grid_pos_y: 2018319.25
    }
    terrain_level_point {
      sim_grid_pos_x: 487588.594
      sim_grid_pos_y: 2018510.25
    }
    terrain_level_point {
      sim_grid_pos_x: 487637.781
      sim_grid_pos_y: 2018849.75
    }
    terrain_level_point {
      sim_grid_pos_x: 488096.531
      sim_grid_pos_y: 2020543.62
    }
    terrain_level_point {
      sim_grid_pos_x: 488143.156
      sim_grid_pos_y: 2020555.38
    }
    terrain_level_point {
      sim_grid_pos_x: 488484.25
      sim_grid_pos_y: 2020194.12
    }
    terrain_level_point {
      sim_grid_pos_x: 488795.031
      sim_grid_pos_y: 2020284.5
    }
    terrain_level_point {
      sim_grid_pos_x: 489182.188
      sim_grid_pos_y: 2020574.25
    }
    terrain_level_point {
      sim_grid_pos_x: 489238.375
      sim_grid_pos_y: 2020719.75
    }
    terrain_level_point {
      sim_grid_pos_x: 489491
      sim_grid_pos_y: 2020973.5
    }
    terrain_level_point {
      sim_grid_pos_x: 489289.031
      sim_grid_pos_y: 2021305.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488909.938
      sim_grid_pos_y: 2021775
    }
    terrain_level_point {
      sim_grid_pos_x: 488640.062
      sim_grid_pos_y: 2021600.12
    }
    terrain_level_point {
      sim_grid_pos_x: 488348.594
      sim_grid_pos_y: 2021591.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488368.031
      sim_grid_pos_y: 2022107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 488918.531
      sim_grid_pos_y: 2022421
    }
    terrain_level_point {
      sim_grid_pos_x: 489455.125
      sim_grid_pos_y: 2022793.62
    }
    terrain_level_point {
      sim_grid_pos_x: 489882.344
      sim_grid_pos_y: 2022958
    }
    terrain_level_point {
      sim_grid_pos_x: 490315.469
      sim_grid_pos_y: 2022962.62
    }
    terrain_level_point {
      sim_grid_pos_x: 490640.031
      sim_grid_pos_y: 2022892.62
    }
    terrain_level_point {
      sim_grid_pos_x: 490973.281
      sim_grid_pos_y: 2022680.12
    }
    terrain_level_point {
      sim_grid_pos_x: 491117.125
      sim_grid_pos_y: 2022569.5
    }
    terrain_level_point {
      sim_grid_pos_x: 492078.469
      sim_grid_pos_y: 2021138.88
    }
    terrain_level_point {
      sim_grid_pos_x: 488109.938
      sim_grid_pos_y: 2018316.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 487885.312
      sim_grid_pos_y: 2018208.5
    }
    terrain_level_point {
      sim_grid_pos_x: 487651.812
      sim_grid_pos_y: 2018285.75
    }
    terrain_level_point {
      sim_grid_pos_x: 487546.188
      sim_grid_pos_y: 2018503.62
    }
    terrain_level_point {
      sim_grid_pos_x: 487597.531
      sim_grid_pos_y: 2018858
    }
    terrain_level_point {
      sim_grid_pos_x: 488063.219
      sim_grid_pos_y: 2020577.62
    }
    terrain_level_point {
      sim_grid_pos_x: 488156.469
      sim_grid_pos_y: 2020601
    }
    terrain_level_point {
      sim_grid_pos_x: 488496.844
      sim_grid_pos_y: 2020240.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488776.469
      sim_grid_pos_y: 2020321.88
    }
    terrain_level_point {
      sim_grid_pos_x: 489148.156
      sim_grid_pos_y: 2.0206e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 489203.219
      sim_grid_pos_y: 2020742.5
    }
    terrain_level_point {
      sim_grid_pos_x: 489439.25
      sim_grid_pos_y: 2020979.62
    }
    terrain_level_point {
      sim_grid_pos_x: 489255.438
      sim_grid_pos_y: 2021281.75
    }
    terrain_level_point {
      sim_grid_pos_x: 488901.25
      sim_grid_pos_y: 2021720.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488652.719
      sim_grid_pos_y: 2021559.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488305.969
      sim_grid_pos_y: 2021549.25
    }
    terrain_level_point {
      sim_grid_pos_x: 488327.906
      sim_grid_pos_y: 2022132
    }
    terrain_level_point {
      sim_grid_pos_x: 488896.719
      sim_grid_pos_y: 2022455.75
    }
    terrain_level_point {
      sim_grid_pos_x: 489435.781
      sim_grid_pos_y: 2022830.12
    }
    terrain_level_point {
      sim_grid_pos_x: 489874.531
      sim_grid_pos_y: 2022998.88
    }
    terrain_level_point {
      sim_grid_pos_x: 490319.625
      sim_grid_pos_y: 2023003.75
    }
    terrain_level_point {
      sim_grid_pos_x: 490655.875
      sim_grid_pos_y: 2022931.12
    }
    terrain_level_point {
      sim_grid_pos_x: 490996.844
      sim_grid_pos_y: 2022713.75
    }
    terrain_level_point {
      sim_grid_pos_x: 491147.438
      sim_grid_pos_y: 2022598
    }
    terrain_level_point {
      sim_grid_pos_x: 492134.781
      sim_grid_pos_y: 2021128.5
    }
    terrain_level_point {
      sim_grid_pos_x: 488128.031
      sim_grid_pos_y: 2018278.62
    }
  }
}
