terrain_level_data {
  terrain_level: 10
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 675715.688
      sim_grid_pos_y: 1388473.62
    }
    terrain_level_point {
      sim_grid_pos_x: 675902.812
      sim_grid_pos_y: 1388850.5
    }
    terrain_level_point {
      sim_grid_pos_x: 702621.375
      sim_grid_pos_y: 1378912.88
    }
    terrain_level_point {
      sim_grid_pos_x: 703679.938
      sim_grid_pos_y: 1378307.25
    }
    terrain_level_point {
      sim_grid_pos_x: 703321.938
      sim_grid_pos_y: 1377902.75
    }
    terrain_level_point {
      sim_grid_pos_x: 702760.125
      sim_grid_pos_y: 1378256.88
    }
    terrain_level_point {
      sim_grid_pos_x: 689386
      sim_grid_pos_y: 1383316.5
    }
    terrain_level_point {
      sim_grid_pos_x: 679787.438
      sim_grid_pos_y: 1386941.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 703325.75
      sim_grid_pos_y: 1377876.12
    }
    terrain_level_point {
      sim_grid_pos_x: 702751
      sim_grid_pos_y: 1378238.5
    }
    terrain_level_point {
      sim_grid_pos_x: 689378.75
      sim_grid_pos_y: 1383297.25
    }
    terrain_level_point {
      sim_grid_pos_x: 689378.75
      sim_grid_pos_y: 1383297.25
    }
    terrain_level_point {
      sim_grid_pos_x: 679780.188
      sim_grid_pos_y: 1386922.25
    }
    terrain_level_point {
      sim_grid_pos_x: 679780.188
      sim_grid_pos_y: 1386922.25
    }
    terrain_level_point {
      sim_grid_pos_x: 675687.188
      sim_grid_pos_y: 1388462.38
    }
    terrain_level_point {
      sim_grid_pos_x: 675892.625
      sim_grid_pos_y: 1388876.12
    }
    terrain_level_point {
      sim_grid_pos_x: 702630.125
      sim_grid_pos_y: 1378931.5
    }
    terrain_level_point {
      sim_grid_pos_x: 703712
      sim_grid_pos_y: 1378312.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 703329.562
      sim_grid_pos_y: 1377849.5
    }
    terrain_level_point {
      sim_grid_pos_x: 702741.812
      sim_grid_pos_y: 1.37822e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 689371.5
      sim_grid_pos_y: 1383278.12
    }
    terrain_level_point {
      sim_grid_pos_x: 689371.5
      sim_grid_pos_y: 1383278.12
    }
    terrain_level_point {
      sim_grid_pos_x: 679772.938
      sim_grid_pos_y: 1386903.12
    }
    terrain_level_point {
      sim_grid_pos_x: 679772.938
      sim_grid_pos_y: 1386903.12
    }
    terrain_level_point {
      sim_grid_pos_x: 675658.75
      sim_grid_pos_y: 1388451.25
    }
    terrain_level_point {
      sim_grid_pos_x: 675882.5
      sim_grid_pos_y: 1388901.75
    }
    terrain_level_point {
      sim_grid_pos_x: 702638.875
      sim_grid_pos_y: 1378950.12
    }
    terrain_level_point {
      sim_grid_pos_x: 703744.062
      sim_grid_pos_y: 1378317.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 703333.375
      sim_grid_pos_y: 1377822.88
    }
    terrain_level_point {
      sim_grid_pos_x: 702732.625
      sim_grid_pos_y: 1378201.62
    }
    terrain_level_point {
      sim_grid_pos_x: 689364.25
      sim_grid_pos_y: 1383258.88
    }
    terrain_level_point {
      sim_grid_pos_x: 689364.312
      sim_grid_pos_y: 1383258.88
    }
    terrain_level_point {
      sim_grid_pos_x: 679765.688
      sim_grid_pos_y: 1386883.88
    }
    terrain_level_point {
      sim_grid_pos_x: 679765.688
      sim_grid_pos_y: 1386883.88
    }
    terrain_level_point {
      sim_grid_pos_x: 675630.312
      sim_grid_pos_y: 1.38844e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 675872.375
      sim_grid_pos_y: 1388927.38
    }
    terrain_level_point {
      sim_grid_pos_x: 702647.562
      sim_grid_pos_y: 1378968.75
    }
    terrain_level_point {
      sim_grid_pos_x: 703776.125
      sim_grid_pos_y: 1378323.12
    }
  }
}
