terrain_level_data {
  terrain_level: 92
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1329537.38
      sim_grid_pos_y: 1394809.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328095.75
      sim_grid_pos_y: 1394996
    }
    terrain_level_point {
      sim_grid_pos_x: 1327705.38
      sim_grid_pos_y: 1393725.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1327807.75
      sim_grid_pos_y: 1392872
    }
    terrain_level_point {
      sim_grid_pos_x: 1329038.25
      sim_grid_pos_y: 1392705.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1329593.75
      sim_grid_pos_y: 1393249.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1329678.25
      sim_grid_pos_y: 1394044.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1329642.88
      sim_grid_pos_y: 1393226
    }
    terrain_level_point {
      sim_grid_pos_x: 1.32973e+06
      sim_grid_pos_y: 1394046.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1329581
      sim_grid_pos_y: 1394855.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1328059.5
      sim_grid_pos_y: 1395052.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1327653.25
      sim_grid_pos_y: 1393730.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1327761.62
      sim_grid_pos_y: 1392826.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329056.25
      sim_grid_pos_y: 1392650.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1329691.88
      sim_grid_pos_y: 1393202.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329781.75
      sim_grid_pos_y: 1394048.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329624.62
      sim_grid_pos_y: 1394901.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1328023.25
      sim_grid_pos_y: 1395108.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1327601
      sim_grid_pos_y: 1393735.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1327715.38
      sim_grid_pos_y: 1392781
    }
    terrain_level_point {
      sim_grid_pos_x: 1329074.25
      sim_grid_pos_y: 1392596.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1329740.88
      sim_grid_pos_y: 1393178.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329833.5
      sim_grid_pos_y: 1394050.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1329668.25
      sim_grid_pos_y: 1394947.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1327986.88
      sim_grid_pos_y: 1395165.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1327548.88
      sim_grid_pos_y: 1393739.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1327669.25
      sim_grid_pos_y: 1392735.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1329092.25
      sim_grid_pos_y: 1392542.5
    }
  }
}
