terrain_level_data {
  terrain_level: 1180
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 3048759.5
      sim_grid_pos_y: 1189613.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3050229.25
      sim_grid_pos_y: 1190328.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3051449.75
      sim_grid_pos_y: 1191559.62
    }
    terrain_level_point {
      sim_grid_pos_x: 3051997
      sim_grid_pos_y: 1191962.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3053453.75
      sim_grid_pos_y: 1193601.88
    }
    terrain_level_point {
      sim_grid_pos_x: 3053954.75
      sim_grid_pos_y: 1193773.62
    }
    terrain_level_point {
      sim_grid_pos_x: 3055452
      sim_grid_pos_y: 1195312.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3057361.25
      sim_grid_pos_y: 1196791.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3055220.25
      sim_grid_pos_y: 1198030.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3054053.25
      sim_grid_pos_y: 1197315.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3052796.25
      sim_grid_pos_y: 1196262.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3051187.75
      sim_grid_pos_y: 1196368.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3048440.25
      sim_grid_pos_y: 1194827.25
    }
    terrain_level_point {
      sim_grid_pos_x: 3048398
      sim_grid_pos_y: 1194634.38
    }
    terrain_level_point {
      sim_grid_pos_x: 3047352.75
      sim_grid_pos_y: 1194600.12
    }
    terrain_level_point {
      sim_grid_pos_x: 3046950.75
      sim_grid_pos_y: 1192889.75
    }
  }
}
