terrain_level_data {
  terrain_level: 375
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1778559.38
      sim_grid_pos_y: 1273058.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1775831.25
      sim_grid_pos_y: 1275645.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1775970.62
      sim_grid_pos_y: 1276439
    }
    terrain_level_point {
      sim_grid_pos_x: 1778071.62
      sim_grid_pos_y: 1275621.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1779486.62
      sim_grid_pos_y: 1274537.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1778569.5
      sim_grid_pos_y: 1272978.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1775775.88
      sim_grid_pos_y: 1275627.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1775930.88
      sim_grid_pos_y: 1276509.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1778097
      sim_grid_pos_y: 1275666.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1779554.88
      sim_grid_pos_y: 1274549.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1778579.75
      sim_grid_pos_y: 1272898
    }
    terrain_level_point {
      sim_grid_pos_x: 1775720.62
      sim_grid_pos_y: 1275609.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1775891.25
      sim_grid_pos_y: 1276579.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1778122.38
      sim_grid_pos_y: 1275711.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1779623.12
      sim_grid_pos_y: 1274562.25
    }
  }
}
