terrain_level_data {
  terrain_level: 18
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1316129
      sim_grid_pos_y: 1372949.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1315118.75
      sim_grid_pos_y: 1376673.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1302255.75
      sim_grid_pos_y: 1385499.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1294239.25
      sim_grid_pos_y: 1373505.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308819.75
      sim_grid_pos_y: 1.36317e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1311222.62
      sim_grid_pos_y: 1366637
    }
    terrain_level_point {
      sim_grid_pos_x: 1312915.12
      sim_grid_pos_y: 1365527.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1314486.25
      sim_grid_pos_y: 1365588.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1315711.88
      sim_grid_pos_y: 1366928.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1311236.25
      sim_grid_pos_y: 1366566.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1312900.75
      sim_grid_pos_y: 1365475.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1314509.62
      sim_grid_pos_y: 1365537.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1315761.75
      sim_grid_pos_y: 1366907
    }
    terrain_level_point {
      sim_grid_pos_x: 1316180.75
      sim_grid_pos_y: 1372955
    }
    terrain_level_point {
      sim_grid_pos_x: 1315163.25
      sim_grid_pos_y: 1376705
    }
    terrain_level_point {
      sim_grid_pos_x: 1302242
      sim_grid_pos_y: 1385571.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1294168.88
      sim_grid_pos_y: 1373492.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308832.38
      sim_grid_pos_y: 1363098.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1.31125e+06
      sim_grid_pos_y: 1366496.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1312886.38
      sim_grid_pos_y: 1365423.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1314533
      sim_grid_pos_y: 1365487.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1315811.75
      sim_grid_pos_y: 1366885.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1316232.5
      sim_grid_pos_y: 1.37296e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1315207.88
      sim_grid_pos_y: 1376736.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1302228.12
      sim_grid_pos_y: 1385643
    }
    terrain_level_point {
      sim_grid_pos_x: 1294098.62
      sim_grid_pos_y: 1373479.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1308845
      sim_grid_pos_y: 1363026.38
    }
  }
}
