terrain_level_data {
  terrain_level: 700
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2300417
      sim_grid_pos_y: 1707509.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.30078e+06
      sim_grid_pos_y: 1707706.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300567
      sim_grid_pos_y: 1708412.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300547.5
      sim_grid_pos_y: 1708868.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300377.75
      sim_grid_pos_y: 1709237.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300360.5
      sim_grid_pos_y: 1709390.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2300628.5
      sim_grid_pos_y: 1709554.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300593.75
      sim_grid_pos_y: 1709678.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300289
      sim_grid_pos_y: 1709644.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300105
      sim_grid_pos_y: 1709796.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299803.5
      sim_grid_pos_y: 1710060.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299808.75
      sim_grid_pos_y: 1710262.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2299478.75
      sim_grid_pos_y: 1710624.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299203.5
      sim_grid_pos_y: 1710626.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2299242.5
      sim_grid_pos_y: 1710931.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299580.75
      sim_grid_pos_y: 1711111.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299689
      sim_grid_pos_y: 1711347.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300090.5
      sim_grid_pos_y: 1711439.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300329.5
      sim_grid_pos_y: 1711554
    }
    terrain_level_point {
      sim_grid_pos_x: 2.30081e+06
      sim_grid_pos_y: 1711974.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300533.25
      sim_grid_pos_y: 1712424
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29995e+06
      sim_grid_pos_y: 1712164
    }
    terrain_level_point {
      sim_grid_pos_x: 2299792.5
      sim_grid_pos_y: 1711913.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2299034.75
      sim_grid_pos_y: 1711508.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29894e+06
      sim_grid_pos_y: 1711231.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2298823
      sim_grid_pos_y: 1711289
    }
    terrain_level_point {
      sim_grid_pos_x: 2297983.5
      sim_grid_pos_y: 1712176.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297868.75
      sim_grid_pos_y: 1712397.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2297474
      sim_grid_pos_y: 1712386.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2297553
      sim_grid_pos_y: 1712130.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2297971.25
      sim_grid_pos_y: 1711793.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2298203
      sim_grid_pos_y: 1711467.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2298696
      sim_grid_pos_y: 1710930.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2298795.75
      sim_grid_pos_y: 1710441.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2298970.25
      sim_grid_pos_y: 1709946.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299298.25
      sim_grid_pos_y: 1709571.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299526.75
      sim_grid_pos_y: 1709342.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299702.25
      sim_grid_pos_y: 1709125.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299806.5
      sim_grid_pos_y: 1708718.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300061
      sim_grid_pos_y: 1708486.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2300816.5
      sim_grid_pos_y: 1707691.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300597.5
      sim_grid_pos_y: 1708417.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300578
      sim_grid_pos_y: 1708875.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300407.75
      sim_grid_pos_y: 1709246.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300393.25
      sim_grid_pos_y: 1709374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2300664.25
      sim_grid_pos_y: 1709540.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300616.5
      sim_grid_pos_y: 1709712.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300298.5
      sim_grid_pos_y: 1709676.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300124.75
      sim_grid_pos_y: 1.70982e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2299834.5
      sim_grid_pos_y: 1710074
    }
    terrain_level_point {
      sim_grid_pos_x: 2299839.75
      sim_grid_pos_y: 1710273.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299492.25
      sim_grid_pos_y: 1710655
    }
    terrain_level_point {
      sim_grid_pos_x: 2299238.5
      sim_grid_pos_y: 1710656.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2299271
      sim_grid_pos_y: 1710911.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299604.25
      sim_grid_pos_y: 1711089.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299710.75
      sim_grid_pos_y: 1711320.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300100.75
      sim_grid_pos_y: 1711410.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300346.5
      sim_grid_pos_y: 1711528.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.30085e+06
      sim_grid_pos_y: 1711968.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300545.5
      sim_grid_pos_y: 1712463
    }
    terrain_level_point {
      sim_grid_pos_x: 2299928.75
      sim_grid_pos_y: 1712188.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2299770.75
      sim_grid_pos_y: 1711936.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299009.5
      sim_grid_pos_y: 1711529.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2298922.25
      sim_grid_pos_y: 1711274.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2298841.5
      sim_grid_pos_y: 1711314.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2298009
      sim_grid_pos_y: 1712194.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297887
      sim_grid_pos_y: 1712429
    }
    terrain_level_point {
      sim_grid_pos_x: 2297432.75
      sim_grid_pos_y: 1712415.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2297526.5
      sim_grid_pos_y: 1712112.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2297948.75
      sim_grid_pos_y: 1711772.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2298179
      sim_grid_pos_y: 1711448.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2298667.5
      sim_grid_pos_y: 1710916.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2298766
      sim_grid_pos_y: 1710433.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2298943
      sim_grid_pos_y: 1709931
    }
    terrain_level_point {
      sim_grid_pos_x: 2299275.75
      sim_grid_pos_y: 1709550.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299503.75
      sim_grid_pos_y: 1709321.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2299674
      sim_grid_pos_y: 1709111.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2299778.75
      sim_grid_pos_y: 1708701.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300034.5
      sim_grid_pos_y: 1708468.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300400.25
      sim_grid_pos_y: 1707465.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2300853.25
      sim_grid_pos_y: 1707676.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300628.25
      sim_grid_pos_y: 1708422.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300608.5
      sim_grid_pos_y: 1708883.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300437.75
      sim_grid_pos_y: 1709254.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300426
      sim_grid_pos_y: 1709358.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.3007e+06
      sim_grid_pos_y: 1709526.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300639
      sim_grid_pos_y: 1709745.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300308
      sim_grid_pos_y: 1709708.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300145
      sim_grid_pos_y: 1709843.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2299865.75
      sim_grid_pos_y: 1710087.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299870.75
      sim_grid_pos_y: 1710285.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299506
      sim_grid_pos_y: 1710685.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299273.25
      sim_grid_pos_y: 1710687.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299299.5
      sim_grid_pos_y: 1710892
    }
    terrain_level_point {
      sim_grid_pos_x: 2299627.75
      sim_grid_pos_y: 1711067.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299732.25
      sim_grid_pos_y: 1711293.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2300111
      sim_grid_pos_y: 1711381
    }
    terrain_level_point {
      sim_grid_pos_x: 2300363.75
      sim_grid_pos_y: 1711502.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300889.75
      sim_grid_pos_y: 1711962.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300557.5
      sim_grid_pos_y: 1712502
    }
    terrain_level_point {
      sim_grid_pos_x: 2299907.75
      sim_grid_pos_y: 1712212.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299749
      sim_grid_pos_y: 1711959.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2298984.25
      sim_grid_pos_y: 1711551.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2298904.5
      sim_grid_pos_y: 1711317.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29886e+06
      sim_grid_pos_y: 1711339.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2298034.25
      sim_grid_pos_y: 1712212.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297905.5
      sim_grid_pos_y: 1712460.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2297391.25
      sim_grid_pos_y: 1712445.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2.2975e+06
      sim_grid_pos_y: 1712094.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2297926
      sim_grid_pos_y: 1711751
    }
    terrain_level_point {
      sim_grid_pos_x: 2298155
      sim_grid_pos_y: 1711428.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2298639.25
      sim_grid_pos_y: 1710901.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2298736.5
      sim_grid_pos_y: 1710425.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2298916
      sim_grid_pos_y: 1709915.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2299253.25
      sim_grid_pos_y: 1709529.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299481
      sim_grid_pos_y: 1709301.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2299646
      sim_grid_pos_y: 1709097.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2299751.25
      sim_grid_pos_y: 1708685.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2300008.25
      sim_grid_pos_y: 1708451.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300383.5
      sim_grid_pos_y: 1707421.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2.30089e+06
      sim_grid_pos_y: 1707661
    }
    terrain_level_point {
      sim_grid_pos_x: 2300658.75
      sim_grid_pos_y: 1708428.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300639
      sim_grid_pos_y: 1708890.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300467.75
      sim_grid_pos_y: 1709262.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300458.75
      sim_grid_pos_y: 1709342.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300736
      sim_grid_pos_y: 1709512.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2300661.75
      sim_grid_pos_y: 1709779.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300317.5
      sim_grid_pos_y: 1709740.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300164.75
      sim_grid_pos_y: 1709866.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2299896.75
      sim_grid_pos_y: 1710101.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299902
      sim_grid_pos_y: 1710297
    }
    terrain_level_point {
      sim_grid_pos_x: 2299519.75
      sim_grid_pos_y: 1710716.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299308.25
      sim_grid_pos_y: 1710717.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299328
      sim_grid_pos_y: 1710872.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299651.5
      sim_grid_pos_y: 1711045.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2299753.75
      sim_grid_pos_y: 1711267.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300121.25
      sim_grid_pos_y: 1711351.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300380.75
      sim_grid_pos_y: 1711476.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2300929.5
      sim_grid_pos_y: 1711956.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2300569.5
      sim_grid_pos_y: 1712541.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2299886.75
      sim_grid_pos_y: 1712236.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299727.5
      sim_grid_pos_y: 1711983.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2298959.25
      sim_grid_pos_y: 1711572.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2298886.75
      sim_grid_pos_y: 1711360.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2298878.5
      sim_grid_pos_y: 1711364.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2298059.5
      sim_grid_pos_y: 1712230.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2297923.75
      sim_grid_pos_y: 1712491.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.29735e+06
      sim_grid_pos_y: 1712474.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2297473.25
      sim_grid_pos_y: 1712076.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2297903.5
      sim_grid_pos_y: 1711729.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2298131
      sim_grid_pos_y: 1711409.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2298610.75
      sim_grid_pos_y: 1710887.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2298706.75
      sim_grid_pos_y: 1710416.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2298889
      sim_grid_pos_y: 1709899.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2299230.75
      sim_grid_pos_y: 1709508.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2299458
      sim_grid_pos_y: 1709280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2299617.75
      sim_grid_pos_y: 1709083
    }
    terrain_level_point {
      sim_grid_pos_x: 2299723.75
      sim_grid_pos_y: 1708668.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2299982
      sim_grid_pos_y: 1708433.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2300366.75
      sim_grid_pos_y: 1707377.75
    }
  }
}
