terrain_level_data {
  terrain_level: 920
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2574199.25
      sim_grid_pos_y: 1432444
    }
    terrain_level_point {
      sim_grid_pos_x: 2574015.5
      sim_grid_pos_y: 1432376.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2573916
      sim_grid_pos_y: 1432244.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2573644
      sim_grid_pos_y: 1432244.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2573498.75
      sim_grid_pos_y: 1432231.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2573085.25
      sim_grid_pos_y: 1432276.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2572787.25
      sim_grid_pos_y: 1432208.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2572564.25
      sim_grid_pos_y: 1432232.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2572380.75
      sim_grid_pos_y: 1432280.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2572267.75
      sim_grid_pos_y: 1432276.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2572125.75
      sim_grid_pos_y: 1432142
    }
    terrain_level_point {
      sim_grid_pos_x: 2572018.25
      sim_grid_pos_y: 1432145.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2571892.75
      sim_grid_pos_y: 1432236.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2571833.75
      sim_grid_pos_y: 1432346.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2570845.5
      sim_grid_pos_y: 1432546.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2570824.75
      sim_grid_pos_y: 1432525.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2570769.75
      sim_grid_pos_y: 1432578.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2570576
      sim_grid_pos_y: 1432609.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2570395.75
      sim_grid_pos_y: 1432752.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2569942.5
      sim_grid_pos_y: 1.43287e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2569534.75
      sim_grid_pos_y: 1432244
    }
    terrain_level_point {
      sim_grid_pos_x: 2569311.5
      sim_grid_pos_y: 1432106.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2569797
      sim_grid_pos_y: 1431973.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2569749
      sim_grid_pos_y: 1431717
    }
    terrain_level_point {
      sim_grid_pos_x: 2570401
      sim_grid_pos_y: 1431581.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571672.25
      sim_grid_pos_y: 1431405.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2573182
      sim_grid_pos_y: 1431196.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2573635.5
      sim_grid_pos_y: 1431136.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2573912
      sim_grid_pos_y: 1431074.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2574043.25
      sim_grid_pos_y: 1431013
    }
    terrain_level_point {
      sim_grid_pos_x: 2574074.25
      sim_grid_pos_y: 1431148.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2574357
      sim_grid_pos_y: 1431138.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2574245.75
      sim_grid_pos_y: 1431431.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2574167
      sim_grid_pos_y: 1431939.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2574098.75
      sim_grid_pos_y: 1431116.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2574402.25
      sim_grid_pos_y: 1431106.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2574275.75
      sim_grid_pos_y: 1431439
    }
    terrain_level_point {
      sim_grid_pos_x: 2574197.75
      sim_grid_pos_y: 1431941.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2574233
      sim_grid_pos_y: 1432489.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2573996.5
      sim_grid_pos_y: 1432402.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2573900.75
      sim_grid_pos_y: 1432275.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2573642.75
      sim_grid_pos_y: 1432275.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2573499.25
      sim_grid_pos_y: 1432262.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2573083.5
      sim_grid_pos_y: 1432307.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2572785.5
      sim_grid_pos_y: 1432239.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2572569.75
      sim_grid_pos_y: 1432262.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2572384.25
      sim_grid_pos_y: 1432311
    }
    terrain_level_point {
      sim_grid_pos_x: 2572255.25
      sim_grid_pos_y: 1432307.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2572114
      sim_grid_pos_y: 1432173.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2572028.75
      sim_grid_pos_y: 1432175.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2571916.5
      sim_grid_pos_y: 1432256.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2571854.25
      sim_grid_pos_y: 1432373.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2570835.25
      sim_grid_pos_y: 1432580.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2570824.25
      sim_grid_pos_y: 1432569
    }
    terrain_level_point {
      sim_grid_pos_x: 2570784
      sim_grid_pos_y: 1432607.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2570589
      sim_grid_pos_y: 1432638.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2570409.75
      sim_grid_pos_y: 1432780.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2569928.75
      sim_grid_pos_y: 1432905.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2569512.75
      sim_grid_pos_y: 1432266.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2569278.25
      sim_grid_pos_y: 1432121.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2569284
      sim_grid_pos_y: 1432081.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2569761.5
      sim_grid_pos_y: 1431951.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2569713
      sim_grid_pos_y: 1431693
    }
    terrain_level_point {
      sim_grid_pos_x: 2570396
      sim_grid_pos_y: 1431551.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2571668
      sim_grid_pos_y: 1431374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2571668
      sim_grid_pos_y: 1431374.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2573178
      sim_grid_pos_y: 1431166.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.57363e+06
      sim_grid_pos_y: 1431106.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2573902
      sim_grid_pos_y: 1431045.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2574064.75
      sim_grid_pos_y: 1430969
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2574123
      sim_grid_pos_y: 1431085.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2574447.5
      sim_grid_pos_y: 1431074.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2574305.5
      sim_grid_pos_y: 1431447
    }
    terrain_level_point {
      sim_grid_pos_x: 2574228.75
      sim_grid_pos_y: 1431942.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2574266.75
      sim_grid_pos_y: 1432534.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2573977.25
      sim_grid_pos_y: 1432428
    }
    terrain_level_point {
      sim_grid_pos_x: 2573885.25
      sim_grid_pos_y: 1432306.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2573641.25
      sim_grid_pos_y: 1432306.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2573499.25
      sim_grid_pos_y: 1432293.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2573081.75
      sim_grid_pos_y: 1432338.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2572783.5
      sim_grid_pos_y: 1432271
    }
    terrain_level_point {
      sim_grid_pos_x: 2572575.25
      sim_grid_pos_y: 1432293.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2572387.75
      sim_grid_pos_y: 1432341.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2572242.5
      sim_grid_pos_y: 1432337.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2572102
      sim_grid_pos_y: 1432204.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2572039
      sim_grid_pos_y: 1432206
    }
    terrain_level_point {
      sim_grid_pos_x: 2571940.25
      sim_grid_pos_y: 1432277.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2571874.5
      sim_grid_pos_y: 1432401.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2570825
      sim_grid_pos_y: 1432613.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2570823.75
      sim_grid_pos_y: 1432612.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2570798.5
      sim_grid_pos_y: 1432636.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2570601.75
      sim_grid_pos_y: 1432667.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2570423.75
      sim_grid_pos_y: 1432808.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2569915.25
      sim_grid_pos_y: 1432940.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2569490.75
      sim_grid_pos_y: 1432289.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2569244.75
      sim_grid_pos_y: 1432137.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2569256.25
      sim_grid_pos_y: 1432057.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2569726
      sim_grid_pos_y: 1431929
    }
    terrain_level_point {
      sim_grid_pos_x: 2569677.25
      sim_grid_pos_y: 1431669
    }
    terrain_level_point {
      sim_grid_pos_x: 2570390.75
      sim_grid_pos_y: 1431521.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2571663.75
      sim_grid_pos_y: 1431344.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2571663.75
      sim_grid_pos_y: 1431344.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2573173.75
      sim_grid_pos_y: 1431135.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2573624.5
      sim_grid_pos_y: 1431076
    }
    terrain_level_point {
      sim_grid_pos_x: 2573892
      sim_grid_pos_y: 1431015.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2574086
      sim_grid_pos_y: 1430925
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2574147.25
      sim_grid_pos_y: 1431053.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2574492.75
      sim_grid_pos_y: 1431042
    }
    terrain_level_point {
      sim_grid_pos_x: 2574335.5
      sim_grid_pos_y: 1431454.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2574259.5
      sim_grid_pos_y: 1431944
    }
    terrain_level_point {
      sim_grid_pos_x: 2574300.5
      sim_grid_pos_y: 1432579.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2573958.25
      sim_grid_pos_y: 1432453.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.57387e+06
      sim_grid_pos_y: 1432337.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.57364e+06
      sim_grid_pos_y: 1432337
    }
    terrain_level_point {
      sim_grid_pos_x: 2573499.75
      sim_grid_pos_y: 1432324.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2.57308e+06
      sim_grid_pos_y: 1432369.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2572781.75
      sim_grid_pos_y: 1432302.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2572580.75
      sim_grid_pos_y: 1432323.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2572391.25
      sim_grid_pos_y: 1432372.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2572229.75
      sim_grid_pos_y: 1432367.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2.57209e+06
      sim_grid_pos_y: 1432235.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2572049.5
      sim_grid_pos_y: 1432236.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2571964.25
      sim_grid_pos_y: 1432298.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2571894.75
      sim_grid_pos_y: 1432428.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2570836.5
      sim_grid_pos_y: 1432642.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2570813
      sim_grid_pos_y: 1432665.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2570614.5
      sim_grid_pos_y: 1432696.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2570437.75
      sim_grid_pos_y: 1432836.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2569901.5
      sim_grid_pos_y: 1432976
    }
    terrain_level_point {
      sim_grid_pos_x: 2569468.75
      sim_grid_pos_y: 1432311.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2569211.5
      sim_grid_pos_y: 1432152.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2569228.75
      sim_grid_pos_y: 1432033.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2569690.75
      sim_grid_pos_y: 1431906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2569641.5
      sim_grid_pos_y: 1431645
    }
    terrain_level_point {
      sim_grid_pos_x: 2570385.5
      sim_grid_pos_y: 1431490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571659.5
      sim_grid_pos_y: 1431313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571659.75
      sim_grid_pos_y: 1431313.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2573169.75
      sim_grid_pos_y: 1431105.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2573619.25
      sim_grid_pos_y: 1431045.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2573882
      sim_grid_pos_y: 1430986.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2574107.5
      sim_grid_pos_y: 1430881
    }
  }
}
terrain_level_data {
  terrain_level: 1245
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2571627
      sim_grid_pos_y: 1432854.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2571477.25
      sim_grid_pos_y: 1432799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2571329
      sim_grid_pos_y: 1432839.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2571234.75
      sim_grid_pos_y: 1432921.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2571173
      sim_grid_pos_y: 1433144.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2571370.75
      sim_grid_pos_y: 1433185
    }
    terrain_level_point {
      sim_grid_pos_x: 2571599.25
      sim_grid_pos_y: 1433096.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2571682.75
      sim_grid_pos_y: 1432972.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2571478.75
      sim_grid_pos_y: 1432767.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2571314.25
      sim_grid_pos_y: 1432811.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2571207.75
      sim_grid_pos_y: 1432904.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571134.5
      sim_grid_pos_y: 1433168.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2571373.5
      sim_grid_pos_y: 1433216.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2571619.25
      sim_grid_pos_y: 1433122
    }
    terrain_level_point {
      sim_grid_pos_x: 2571718
      sim_grid_pos_y: 1432974.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571649.25
      sim_grid_pos_y: 1432829.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2571480.25
      sim_grid_pos_y: 1432735
    }
    terrain_level_point {
      sim_grid_pos_x: 2571299.25
      sim_grid_pos_y: 1432783.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571180.5
      sim_grid_pos_y: 1432887.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2571096.25
      sim_grid_pos_y: 1433191.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2571376.25
      sim_grid_pos_y: 1433248.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2571639.5
      sim_grid_pos_y: 1433147.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2571753.25
      sim_grid_pos_y: 1432977.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2571671.75
      sim_grid_pos_y: 1432805
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2571481.5
      sim_grid_pos_y: 1432702.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571284.5
      sim_grid_pos_y: 1432755.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2571153.25
      sim_grid_pos_y: 1432870.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2571057.75
      sim_grid_pos_y: 1433215.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2571378.75
      sim_grid_pos_y: 1433280.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2571659.75
      sim_grid_pos_y: 1433172.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2571788.75
      sim_grid_pos_y: 1.43298e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 2571694
      sim_grid_pos_y: 1432780.38
    }
  }
}
