terrain_level_data {
  terrain_level: 6
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 461317.844
      sim_grid_pos_y: 2101544.75
    }
    terrain_level_point {
      sim_grid_pos_x: 458535.562
      sim_grid_pos_y: 2101477.75
    }
    terrain_level_point {
      sim_grid_pos_x: 458578.406
      sim_grid_pos_y: 2099985.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459259.188
      sim_grid_pos_y: 2099971.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459250.875
      sim_grid_pos_y: 2099735
    }
    terrain_level_point {
      sim_grid_pos_x: 459956.5
      sim_grid_pos_y: 2099710.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459977.438
      sim_grid_pos_y: 2099660.75
    }
    terrain_level_point {
      sim_grid_pos_x: 460791
      sim_grid_pos_y: 2099579.5
    }
    terrain_level_point {
      sim_grid_pos_x: 460821.781
      sim_grid_pos_y: 2099539.5
    }
    terrain_level_point {
      sim_grid_pos_x: 461363.406
      sim_grid_pos_y: 2099631.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 461394.781
      sim_grid_pos_y: 2099605.25
    }
    terrain_level_point {
      sim_grid_pos_x: 461347.844
      sim_grid_pos_y: 2101576
    }
    terrain_level_point {
      sim_grid_pos_x: 458503.938
      sim_grid_pos_y: 2101507.75
    }
    terrain_level_point {
      sim_grid_pos_x: 458548.5
      sim_grid_pos_y: 2099955.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459227.344
      sim_grid_pos_y: 2099941.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459219.062
      sim_grid_pos_y: 2099705.5
    }
    terrain_level_point {
      sim_grid_pos_x: 459935.812
      sim_grid_pos_y: 2099680.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459956.188
      sim_grid_pos_y: 2099632
    }
    terrain_level_point {
      sim_grid_pos_x: 460774.75
      sim_grid_pos_y: 2.09955e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 460808.719
      sim_grid_pos_y: 2099506.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 461426.156
      sim_grid_pos_y: 2099579.5
    }
    terrain_level_point {
      sim_grid_pos_x: 461377.844
      sim_grid_pos_y: 2101607.5
    }
    terrain_level_point {
      sim_grid_pos_x: 458472.312
      sim_grid_pos_y: 2101537.75
    }
    terrain_level_point {
      sim_grid_pos_x: 458518.594
      sim_grid_pos_y: 2099925.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459195.5
      sim_grid_pos_y: 2099911
    }
    terrain_level_point {
      sim_grid_pos_x: 459187.219
      sim_grid_pos_y: 2099675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 459915.094
      sim_grid_pos_y: 2099650.25
    }
    terrain_level_point {
      sim_grid_pos_x: 459934.969
      sim_grid_pos_y: 2099603.25
    }
    terrain_level_point {
      sim_grid_pos_x: 460758.5
      sim_grid_pos_y: 2099520.75
    }
    terrain_level_point {
      sim_grid_pos_x: 460795.656
      sim_grid_pos_y: 2099472.75
    }
  }
}
