terrain_level_data {
  terrain_level: 42
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1167043.88
      sim_grid_pos_y: 1536210.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1167632.12
      sim_grid_pos_y: 1537429.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1168128
      sim_grid_pos_y: 1542190.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.16944e+06
      sim_grid_pos_y: 1544896.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1168467.88
      sim_grid_pos_y: 1548239.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1167197.62
      sim_grid_pos_y: 1548298.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1166797
      sim_grid_pos_y: 1547878.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1.16639e+06
      sim_grid_pos_y: 1546747.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1163096.12
      sim_grid_pos_y: 1546642.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1163560.62
      sim_grid_pos_y: 1544508.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1162328.75
      sim_grid_pos_y: 1542829.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1164043.12
      sim_grid_pos_y: 1540593.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1162532.25
      sim_grid_pos_y: 1539150.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1162480.5
      sim_grid_pos_y: 1537107.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1164390.25
      sim_grid_pos_y: 1536870.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1164304.12
      sim_grid_pos_y: 1536248.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1167732.25
      sim_grid_pos_y: 1537400.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1168228.12
      sim_grid_pos_y: 1542161.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1169549.5
      sim_grid_pos_y: 1544887.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1168545.88
      sim_grid_pos_y: 1548338.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1167155.75
      sim_grid_pos_y: 1548403
    }
    terrain_level_point {
      sim_grid_pos_x: 1166707.88
      sim_grid_pos_y: 1547933.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1166317.12
      sim_grid_pos_y: 1546847.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1162969.75
      sim_grid_pos_y: 1546741.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1163450.62
      sim_grid_pos_y: 1544531.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1162200.62
      sim_grid_pos_y: 1542828.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1163905.75
      sim_grid_pos_y: 1540603.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1162430.88
      sim_grid_pos_y: 1539195.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1162375.62
      sim_grid_pos_y: 1537017.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1164274.5
      sim_grid_pos_y: 1536781.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1164186.62
      sim_grid_pos_y: 1536147.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1167107.75
      sim_grid_pos_y: 1536107.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1167832.38
      sim_grid_pos_y: 1537372.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1168328.25
      sim_grid_pos_y: 1542133.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1169658.88
      sim_grid_pos_y: 1544877.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1168623.88
      sim_grid_pos_y: 1548437.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1167113.75
      sim_grid_pos_y: 1548507.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1166618.75
      sim_grid_pos_y: 1547988.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1166244.25
      sim_grid_pos_y: 1546947.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1162843.38
      sim_grid_pos_y: 1.54684e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1163340.62
      sim_grid_pos_y: 1544555.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1162072.38
      sim_grid_pos_y: 1542827.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1163768.5
      sim_grid_pos_y: 1540614.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1162329.38
      sim_grid_pos_y: 1539240.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1162270.75
      sim_grid_pos_y: 1536927
    }
    terrain_level_point {
      sim_grid_pos_x: 1164158.62
      sim_grid_pos_y: 1536692.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1164069.25
      sim_grid_pos_y: 1536046.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1167171.75
      sim_grid_pos_y: 1536004.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1167932.5
      sim_grid_pos_y: 1537343.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1168428.38
      sim_grid_pos_y: 1542104.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1169768.38
      sim_grid_pos_y: 1544868.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1168701.88
      sim_grid_pos_y: 1548536.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1167071.88
      sim_grid_pos_y: 1548612.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1166529.62
      sim_grid_pos_y: 1548043.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1166171.38
      sim_grid_pos_y: 1547048
    }
    terrain_level_point {
      sim_grid_pos_x: 1162717
      sim_grid_pos_y: 1546938.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1163230.62
      sim_grid_pos_y: 1544578.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1161944.25
      sim_grid_pos_y: 1542825.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1163631.12
      sim_grid_pos_y: 1540625.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1162228
      sim_grid_pos_y: 1539285
    }
    terrain_level_point {
      sim_grid_pos_x: 1162166
      sim_grid_pos_y: 1536836.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1164042.88
      sim_grid_pos_y: 1536603.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1163951.75
      sim_grid_pos_y: 1535945.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1167235.62
      sim_grid_pos_y: 1535900.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1168032.62
      sim_grid_pos_y: 1537315.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1168528.5
      sim_grid_pos_y: 1542076
    }
    terrain_level_point {
      sim_grid_pos_x: 1169877.88
      sim_grid_pos_y: 1544859.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1168779.75
      sim_grid_pos_y: 1548635.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1.16703e+06
      sim_grid_pos_y: 1548716.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1166440.5
      sim_grid_pos_y: 1548098.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1166098.5
      sim_grid_pos_y: 1547148.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1162590.62
      sim_grid_pos_y: 1547037.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1163120.62
      sim_grid_pos_y: 1544601.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1161816.12
      sim_grid_pos_y: 1542824.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1163493.88
      sim_grid_pos_y: 1540635.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1162126.5
      sim_grid_pos_y: 1539329.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1162061.12
      sim_grid_pos_y: 1536746.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1163927
      sim_grid_pos_y: 1536515
    }
    terrain_level_point {
      sim_grid_pos_x: 1163834.25
      sim_grid_pos_y: 1535844.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1167299.62
      sim_grid_pos_y: 1535797.25
    }
  }
}
