terrain_level_data {
  terrain_level: 364
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1288584.25
      sim_grid_pos_y: 1810657.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1290107.88
      sim_grid_pos_y: 1810993.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1292612.12
      sim_grid_pos_y: 1812016.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1294512.12
      sim_grid_pos_y: 1812947.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1296283.38
      sim_grid_pos_y: 1813856.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1298025.12
      sim_grid_pos_y: 1814506.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1298894.25
      sim_grid_pos_y: 1815015.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1301498
      sim_grid_pos_y: 1818341.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1300795.38
      sim_grid_pos_y: 1818524.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1298817.62
      sim_grid_pos_y: 1818712.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1298025
      sim_grid_pos_y: 1818591.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1297127.12
      sim_grid_pos_y: 1818386.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1296201.75
      sim_grid_pos_y: 1818403.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1295244.5
      sim_grid_pos_y: 1818605.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1293641.25
      sim_grid_pos_y: 1818570.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1292055.5
      sim_grid_pos_y: 1817899.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1291390.5
      sim_grid_pos_y: 1817533.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1290832.12
      sim_grid_pos_y: 1816924.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1290496.75
      sim_grid_pos_y: 1816257.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1290227.75
      sim_grid_pos_y: 1815757.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1289903.88
      sim_grid_pos_y: 1815323.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1289319
      sim_grid_pos_y: 1814851.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1288833.75
      sim_grid_pos_y: 1814562.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1287190.12
      sim_grid_pos_y: 1814125.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1287300.88
      sim_grid_pos_y: 1813723.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1287537.75
      sim_grid_pos_y: 1813384.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1287641.38
      sim_grid_pos_y: 1813222
    }
    terrain_level_point {
      sim_grid_pos_x: 1287530.62
      sim_grid_pos_y: 1812834.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1287241.5
      sim_grid_pos_y: 1812308.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1286748.12
      sim_grid_pos_y: 1811764.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1286426.75
      sim_grid_pos_y: 1811343.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1285462.75
      sim_grid_pos_y: 1810591.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1284800.88
      sim_grid_pos_y: 1810177.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1285002.25
      sim_grid_pos_y: 1809646.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1285116.75
      sim_grid_pos_y: 1809465.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1285429.75
      sim_grid_pos_y: 1809291.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1285999.38
      sim_grid_pos_y: 1809463.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1286035.88
      sim_grid_pos_y: 1809367.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1288617.12
      sim_grid_pos_y: 1810559.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1290138.5
      sim_grid_pos_y: 1810895.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1292654.12
      sim_grid_pos_y: 1811922.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1294558.12
      sim_grid_pos_y: 1812855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1296324.88
      sim_grid_pos_y: 1813762.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1298069.25
      sim_grid_pos_y: 1814413.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1298962.88
      sim_grid_pos_y: 1814937.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1301675.12
      sim_grid_pos_y: 1818401.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1300813.25
      sim_grid_pos_y: 1818625.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1298814.75
      sim_grid_pos_y: 1818815.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1298005.75
      sim_grid_pos_y: 1818692
    }
    terrain_level_point {
      sim_grid_pos_x: 1297116.5
      sim_grid_pos_y: 1818489.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1296213.38
      sim_grid_pos_y: 1818506.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1295254.12
      sim_grid_pos_y: 1818708.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1293619.38
      sim_grid_pos_y: 1818673
    }
    terrain_level_point {
      sim_grid_pos_x: 1292010.62
      sim_grid_pos_y: 1817991.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1291326.38
      sim_grid_pos_y: 1817614.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1290746.88
      sim_grid_pos_y: 1816983.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1290405.75
      sim_grid_pos_y: 1816304.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1290141.12
      sim_grid_pos_y: 1815812.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1289829.5
      sim_grid_pos_y: 1815395.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1289260.25
      sim_grid_pos_y: 1814936.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1288793.5
      sim_grid_pos_y: 1814657.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1287063.75
      sim_grid_pos_y: 1814198.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1287206.75
      sim_grid_pos_y: 1813679.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1287452.38
      sim_grid_pos_y: 1813327.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1287530.12
      sim_grid_pos_y: 1813205.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1287435.25
      sim_grid_pos_y: 1812874.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1287157.5
      sim_grid_pos_y: 1812368.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1286669.25
      sim_grid_pos_y: 1.81183e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1286353.25
      sim_grid_pos_y: 1811416
    }
    terrain_level_point {
      sim_grid_pos_x: 1285403.88
      sim_grid_pos_y: 1810675.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1284675.12
      sim_grid_pos_y: 1810219.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.28491e+06
      sim_grid_pos_y: 1809600.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1285044
      sim_grid_pos_y: 1809388.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1285417.88
      sim_grid_pos_y: 1809180.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1286072.38
      sim_grid_pos_y: 1809271.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1288650.12
      sim_grid_pos_y: 1810461.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1290169.25
      sim_grid_pos_y: 1810797
    }
    terrain_level_point {
      sim_grid_pos_x: 1292696.12
      sim_grid_pos_y: 1811829.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1294604
      sim_grid_pos_y: 1812763.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1296366.38
      sim_grid_pos_y: 1813668.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1298113.5
      sim_grid_pos_y: 1814320.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1299031.62
      sim_grid_pos_y: 1814858.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1301852.12
      sim_grid_pos_y: 1818461
    }
    terrain_level_point {
      sim_grid_pos_x: 1300831.12
      sim_grid_pos_y: 1818726.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1298811.75
      sim_grid_pos_y: 1818919.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1297986.62
      sim_grid_pos_y: 1818792.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1297106
      sim_grid_pos_y: 1818591.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1296225
      sim_grid_pos_y: 1818608.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295263.62
      sim_grid_pos_y: 1818811.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1293597.5
      sim_grid_pos_y: 1818775
    }
    terrain_level_point {
      sim_grid_pos_x: 1291965.88
      sim_grid_pos_y: 1818083.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1291262.12
      sim_grid_pos_y: 1817696.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1290661.75
      sim_grid_pos_y: 1817042
    }
    terrain_level_point {
      sim_grid_pos_x: 1290314.88
      sim_grid_pos_y: 1816352.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1290054.38
      sim_grid_pos_y: 1815868
    }
    terrain_level_point {
      sim_grid_pos_x: 1289755
      sim_grid_pos_y: 1815467
    }
    terrain_level_point {
      sim_grid_pos_x: 1289201.5
      sim_grid_pos_y: 1815020.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1288753.38
      sim_grid_pos_y: 1814753
    }
    terrain_level_point {
      sim_grid_pos_x: 1286937.5
      sim_grid_pos_y: 1814270.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1287112.5
      sim_grid_pos_y: 1813635.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1287367.12
      sim_grid_pos_y: 1813270.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1287418.75
      sim_grid_pos_y: 1813189.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1287339.88
      sim_grid_pos_y: 1812913.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1287073.38
      sim_grid_pos_y: 1812428.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1286590.38
      sim_grid_pos_y: 1811895.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1286279.75
      sim_grid_pos_y: 1811488.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1285345
      sim_grid_pos_y: 1810759.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1284549.5
      sim_grid_pos_y: 1810261.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1284817.88
      sim_grid_pos_y: 1809554.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1284971.25
      sim_grid_pos_y: 1809311.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1285405.88
      sim_grid_pos_y: 1.80907e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1286108.88
      sim_grid_pos_y: 1809175.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1288683
      sim_grid_pos_y: 1810364
    }
    terrain_level_point {
      sim_grid_pos_x: 1290199.88
      sim_grid_pos_y: 1810698.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1292738.12
      sim_grid_pos_y: 1811735.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1.29465e+06
      sim_grid_pos_y: 1812672.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1296407.88
      sim_grid_pos_y: 1813574.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1298157.62
      sim_grid_pos_y: 1814227.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1299100.25
      sim_grid_pos_y: 1.81478e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1302029.25
      sim_grid_pos_y: 1818520.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1300849
      sim_grid_pos_y: 1818828
    }
    terrain_level_point {
      sim_grid_pos_x: 1298808.75
      sim_grid_pos_y: 1819022.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1297967.38
      sim_grid_pos_y: 1818893.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1297095.38
      sim_grid_pos_y: 1818694.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1296236.75
      sim_grid_pos_y: 1818710.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1295273.25
      sim_grid_pos_y: 1818914.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1293575.62
      sim_grid_pos_y: 1818877.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1291921
      sim_grid_pos_y: 1818176.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1291198
      sim_grid_pos_y: 1817778.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1290576.5
      sim_grid_pos_y: 1817100.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1290223.88
      sim_grid_pos_y: 1816399.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1289967.62
      sim_grid_pos_y: 1815923.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1289680.62
      sim_grid_pos_y: 1815538.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1289142.75
      sim_grid_pos_y: 1815104.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1288713.12
      sim_grid_pos_y: 1814848.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1286811.12
      sim_grid_pos_y: 1814343.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1287018.38
      sim_grid_pos_y: 1813591.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1287282
      sim_grid_pos_y: 1813213.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1287307.5
      sim_grid_pos_y: 1813173.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1287244.38
      sim_grid_pos_y: 1812952.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1286989.38
      sim_grid_pos_y: 1812488.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1286511.5
      sim_grid_pos_y: 1811961.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1286206.25
      sim_grid_pos_y: 1811561.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1285286.12
      sim_grid_pos_y: 1810844
    }
    terrain_level_point {
      sim_grid_pos_x: 1284423.75
      sim_grid_pos_y: 1810304.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1284725.62
      sim_grid_pos_y: 1809508.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1284898.62
      sim_grid_pos_y: 1809234.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1285394
      sim_grid_pos_y: 1808959.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1286145.38
      sim_grid_pos_y: 1809079
    }
    terrain_level_point {
      sim_grid_pos_x: 1288716
      sim_grid_pos_y: 1810266.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1290230.5
      sim_grid_pos_y: 1810600.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1.29278e+06
      sim_grid_pos_y: 1811642.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1294696
      sim_grid_pos_y: 1812580.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1296449.25
      sim_grid_pos_y: 1813480.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1298201.88
      sim_grid_pos_y: 1814134.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1299169
      sim_grid_pos_y: 1814701.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1302206.25
      sim_grid_pos_y: 1818580.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1300867
      sim_grid_pos_y: 1818929.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1298805.88
      sim_grid_pos_y: 1819125.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1297948.25
      sim_grid_pos_y: 1818994.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1297084.75
      sim_grid_pos_y: 1818797.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1296248.38
      sim_grid_pos_y: 1818813.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1295282.88
      sim_grid_pos_y: 1819016.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1293553.75
      sim_grid_pos_y: 1818979.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1291876.12
      sim_grid_pos_y: 1818268.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1291133.75
      sim_grid_pos_y: 1.81786e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1290491.38
      sim_grid_pos_y: 1817159.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1290132.75
      sim_grid_pos_y: 1816446.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1289881
      sim_grid_pos_y: 1815978.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1289606.12
      sim_grid_pos_y: 1815610.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1289084
      sim_grid_pos_y: 1815189.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1288672.88
      sim_grid_pos_y: 1814943.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1286684.75
      sim_grid_pos_y: 1814415.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1286924.25
      sim_grid_pos_y: 1813547
    }
    terrain_level_point {
      sim_grid_pos_x: 1287196.25
      sim_grid_pos_y: 1813157
    }
    terrain_level_point {
      sim_grid_pos_x: 1287149
      sim_grid_pos_y: 1812991.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1286905.25
      sim_grid_pos_y: 1812548.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1286432.62
      sim_grid_pos_y: 1812027
    }
    terrain_level_point {
      sim_grid_pos_x: 1286132.88
      sim_grid_pos_y: 1811634.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1285227.25
      sim_grid_pos_y: 1810928
    }
    terrain_level_point {
      sim_grid_pos_x: 1284298
      sim_grid_pos_y: 1810346.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1284633.5
      sim_grid_pos_y: 1809462.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1284825.88
      sim_grid_pos_y: 1809158
    }
    terrain_level_point {
      sim_grid_pos_x: 1285382.12
      sim_grid_pos_y: 1808848.62
    }
  }
}
terrain_level_data {
  terrain_level: 400
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1295356.88
      sim_grid_pos_y: 1816513.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295422
      sim_grid_pos_y: 1816799.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295536
      sim_grid_pos_y: 1816998.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295869.88
      sim_grid_pos_y: 1817065.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1296183.38
      sim_grid_pos_y: 1817041.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1296169.12
      sim_grid_pos_y: 1816916.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1296064.25
      sim_grid_pos_y: 1816804.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1296224.12
      sim_grid_pos_y: 1816265.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1295813
      sim_grid_pos_y: 1816063.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1295658
      sim_grid_pos_y: 1816147.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1295511
      sim_grid_pos_y: 1816385.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1295811.25
      sim_grid_pos_y: 1815982.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295607
      sim_grid_pos_y: 1816093.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295456.12
      sim_grid_pos_y: 1816337.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295277.12
      sim_grid_pos_y: 1816486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295354.38
      sim_grid_pos_y: 1816825.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1295489.88
      sim_grid_pos_y: 1817062.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295865.38
      sim_grid_pos_y: 1817137.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1296263.12
      sim_grid_pos_y: 1817107.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1296237.75
      sim_grid_pos_y: 1816884.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1296144.75
      sim_grid_pos_y: 1816785.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1296310.12
      sim_grid_pos_y: 1816227.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1295809.62
      sim_grid_pos_y: 1815901.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1295555.88
      sim_grid_pos_y: 1816039.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295401.25
      sim_grid_pos_y: 1816289.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1295197.38
      sim_grid_pos_y: 1816459.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1295286.75
      sim_grid_pos_y: 1816852.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1295443.88
      sim_grid_pos_y: 1817126.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1295861
      sim_grid_pos_y: 1.81721e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1296342.75
      sim_grid_pos_y: 1817173.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1296306.38
      sim_grid_pos_y: 1816852.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1296225.25
      sim_grid_pos_y: 1816766.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1296396.12
      sim_grid_pos_y: 1.81619e+06
    }
  }
}
terrain_level_data {
  terrain_level: 575
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1293770.88
      sim_grid_pos_y: 1816264.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1293471.62
      sim_grid_pos_y: 1816749.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1293763.75
      sim_grid_pos_y: 1817148.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1294251.75
      sim_grid_pos_y: 1816855.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1294296.38
      sim_grid_pos_y: 1816360.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 66.6666718
    terrain_level_point {
      sim_grid_pos_x: 1293705.25
      sim_grid_pos_y: 1816116.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1293311.12
      sim_grid_pos_y: 1816756.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1293728
      sim_grid_pos_y: 1817325
    }
    terrain_level_point {
      sim_grid_pos_x: 1294378.5
      sim_grid_pos_y: 1816935.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1.29444e+06
      sim_grid_pos_y: 1816251.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 33.3333359
    terrain_level_point {
      sim_grid_pos_x: 1293639.62
      sim_grid_pos_y: 1815969.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1293150.5
      sim_grid_pos_y: 1816762.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1293692.38
      sim_grid_pos_y: 1817501.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1294505.12
      sim_grid_pos_y: 1817014.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1294583.62
      sim_grid_pos_y: 1816142.12
    }
  }
}
terrain_level_data {
  terrain_level: 480
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1307351.62
      sim_grid_pos_y: 1817469.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1307359.75
      sim_grid_pos_y: 1817617.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307206.38
      sim_grid_pos_y: 1817615.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1307203.88
      sim_grid_pos_y: 1817476
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1307392.25
      sim_grid_pos_y: 1817649.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1307176.12
      sim_grid_pos_y: 1817645.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1307172.5
      sim_grid_pos_y: 1817446.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1307380.75
      sim_grid_pos_y: 1817437.25
    }
  }
}
