terrain_level_data {
  terrain_level: 2500
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2710129.25
      sim_grid_pos_y: 1565568.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710063
      sim_grid_pos_y: 1565597.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2.70961e+06
      sim_grid_pos_y: 1565971.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709232.5
      sim_grid_pos_y: 1566113.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2708379.25
      sim_grid_pos_y: 1566063.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2707907.5
      sim_grid_pos_y: 1566159
    }
    terrain_level_point {
      sim_grid_pos_x: 2707716.75
      sim_grid_pos_y: 1565995.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2707274.25
      sim_grid_pos_y: 1566155.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2707158.5
      sim_grid_pos_y: 1566325.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2707629.25
      sim_grid_pos_y: 1566365.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2707623
      sim_grid_pos_y: 1566521.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2708495.75
      sim_grid_pos_y: 1566569.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2708886.75
      sim_grid_pos_y: 1566336.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2709369.25
      sim_grid_pos_y: 1566401.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2709640.5
      sim_grid_pos_y: 1566358.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710123.5
      sim_grid_pos_y: 1565913.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710199
      sim_grid_pos_y: 1565963.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2710131
      sim_grid_pos_y: 1566350.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2710459.25
      sim_grid_pos_y: 1566740.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710699
      sim_grid_pos_y: 1566301.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.711e+06
      sim_grid_pos_y: 1565583.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2710909
      sim_grid_pos_y: 1565345.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711105
      sim_grid_pos_y: 1565196
    }
    terrain_level_point {
      sim_grid_pos_x: 2711520.25
      sim_grid_pos_y: 1564834.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711863.75
      sim_grid_pos_y: 1564366.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2713319
      sim_grid_pos_y: 1563513.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2713034.75
      sim_grid_pos_y: 1563208.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2712711.5
      sim_grid_pos_y: 1563251.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2712580.25
      sim_grid_pos_y: 1562971.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2712318.25
      sim_grid_pos_y: 1562906.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2712066.25
      sim_grid_pos_y: 1563267.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2711532.75
      sim_grid_pos_y: 1563507.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2711326.25
      sim_grid_pos_y: 1563386.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711102.25
      sim_grid_pos_y: 1563280.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711035.75
      sim_grid_pos_y: 1563559.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711259
      sim_grid_pos_y: 1563729.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711567
      sim_grid_pos_y: 1563859.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711721
      sim_grid_pos_y: 1564015.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711420.5
      sim_grid_pos_y: 1564198.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2711345.75
      sim_grid_pos_y: 1564426.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711112
      sim_grid_pos_y: 1564691.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710874.5
      sim_grid_pos_y: 1564808.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710740.5
      sim_grid_pos_y: 1565048.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2710667.5
      sim_grid_pos_y: 1565337.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710573.75
      sim_grid_pos_y: 1565320.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710572.75
      sim_grid_pos_y: 1564921.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710468.75
      sim_grid_pos_y: 1564929
    }
    terrain_level_point {
      sim_grid_pos_x: 2710439.75
      sim_grid_pos_y: 1565024.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710356.25
      sim_grid_pos_y: 1565049.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2710337.5
      sim_grid_pos_y: 1565188.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710247.5
      sim_grid_pos_y: 1565292.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710225.75
      sim_grid_pos_y: 1565505.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710168.75
      sim_grid_pos_y: 1565519.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2712305
      sim_grid_pos_y: 1562871.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2712046
      sim_grid_pos_y: 1563242.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711534.5
      sim_grid_pos_y: 1563473
    }
    terrain_level_point {
      sim_grid_pos_x: 2711340.75
      sim_grid_pos_y: 1563359.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2711081.25
      sim_grid_pos_y: 1563236.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711001
      sim_grid_pos_y: 1563571.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711243.5
      sim_grid_pos_y: 1563756.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2711549.5
      sim_grid_pos_y: 1563885.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711671.75
      sim_grid_pos_y: 1564009.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711394.75
      sim_grid_pos_y: 1564178.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711318.5
      sim_grid_pos_y: 1564410.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711093
      sim_grid_pos_y: 1564666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710852.25
      sim_grid_pos_y: 1564785.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710711.75
      sim_grid_pos_y: 1565037
    }
    terrain_level_point {
      sim_grid_pos_x: 2710644.75
      sim_grid_pos_y: 1565302.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710604.25
      sim_grid_pos_y: 1565295.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710603.5
      sim_grid_pos_y: 1564888.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710445.5
      sim_grid_pos_y: 1564899.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2710415
      sim_grid_pos_y: 1564999.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710328.5
      sim_grid_pos_y: 1565025.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2710308.25
      sim_grid_pos_y: 1565175.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710218
      sim_grid_pos_y: 1565279.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710197.25
      sim_grid_pos_y: 1565480.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710151.25
      sim_grid_pos_y: 1565492.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71011e+06
      sim_grid_pos_y: 1565543.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710046.75
      sim_grid_pos_y: 1565571.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2709594.25
      sim_grid_pos_y: 1565944.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709227.75
      sim_grid_pos_y: 1566082
    }
    terrain_level_point {
      sim_grid_pos_x: 2708377
      sim_grid_pos_y: 1566032.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2707916
      sim_grid_pos_y: 1566125.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2707723.25
      sim_grid_pos_y: 1565960.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2707254.25
      sim_grid_pos_y: 1566129.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2707103.75
      sim_grid_pos_y: 1566352
    }
    terrain_level_point {
      sim_grid_pos_x: 2707597.25
      sim_grid_pos_y: 1566394
    }
    terrain_level_point {
      sim_grid_pos_x: 2707591
      sim_grid_pos_y: 1566550.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2708503.25
      sim_grid_pos_y: 1566600.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2708893.25
      sim_grid_pos_y: 1566368.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709369.5
      sim_grid_pos_y: 1566432.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709654.5
      sim_grid_pos_y: 1566387.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710126.75
      sim_grid_pos_y: 1565952.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2710165.25
      sim_grid_pos_y: 1565978.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710098.25
      sim_grid_pos_y: 1566359.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710464.75
      sim_grid_pos_y: 1566794.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710726.75
      sim_grid_pos_y: 1566314.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2711033.25
      sim_grid_pos_y: 1565584
    }
    terrain_level_point {
      sim_grid_pos_x: 2710946
      sim_grid_pos_y: 1565355.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711124.5
      sim_grid_pos_y: 1565219.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711543
      sim_grid_pos_y: 1564855.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711884.75
      sim_grid_pos_y: 1564390.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2713367.5
      sim_grid_pos_y: 1563521
    }
    terrain_level_point {
      sim_grid_pos_x: 2713046.5
      sim_grid_pos_y: 1563175.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2712729.75
      sim_grid_pos_y: 1563218.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2712601.75
      sim_grid_pos_y: 1562945.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2712292
      sim_grid_pos_y: 1562837
    }
    terrain_level_point {
      sim_grid_pos_x: 2712025.75
      sim_grid_pos_y: 1563218
    }
    terrain_level_point {
      sim_grid_pos_x: 2711536.5
      sim_grid_pos_y: 1563438.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711355.25
      sim_grid_pos_y: 1563331.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711060.25
      sim_grid_pos_y: 1563192.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710966.5
      sim_grid_pos_y: 1563584.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711228
      sim_grid_pos_y: 1563783
    }
    terrain_level_point {
      sim_grid_pos_x: 2711531.75
      sim_grid_pos_y: 1563911.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711622.5
      sim_grid_pos_y: 1564003.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711369
      sim_grid_pos_y: 1564158.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2711291.25
      sim_grid_pos_y: 1564395.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711074
      sim_grid_pos_y: 1564641.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71083e+06
      sim_grid_pos_y: 1564762
    }
    terrain_level_point {
      sim_grid_pos_x: 2710682.75
      sim_grid_pos_y: 1565025.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710635
      sim_grid_pos_y: 1565215.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710634
      sim_grid_pos_y: 1564855.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710422.25
      sim_grid_pos_y: 1564870.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710390.5
      sim_grid_pos_y: 1564975.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710300.5
      sim_grid_pos_y: 1565001.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710279
      sim_grid_pos_y: 1565162
    }
    terrain_level_point {
      sim_grid_pos_x: 2710188.5
      sim_grid_pos_y: 1565266.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2710169
      sim_grid_pos_y: 1565456.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710133.75
      sim_grid_pos_y: 1565465.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710090.75
      sim_grid_pos_y: 1565518.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2710030.5
      sim_grid_pos_y: 1565544.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2709578.75
      sim_grid_pos_y: 1565917.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709223
      sim_grid_pos_y: 1566051
    }
    terrain_level_point {
      sim_grid_pos_x: 2708375
      sim_grid_pos_y: 1566001.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2707924.75
      sim_grid_pos_y: 1566092.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2707729.5
      sim_grid_pos_y: 1565925.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2707234.5
      sim_grid_pos_y: 1566104.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2707048.75
      sim_grid_pos_y: 1566378.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2707565.5
      sim_grid_pos_y: 1566422.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2707559
      sim_grid_pos_y: 1566579.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2708511
      sim_grid_pos_y: 1566631.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2708899.75
      sim_grid_pos_y: 1566400.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.70937e+06
      sim_grid_pos_y: 1566463.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709668.5
      sim_grid_pos_y: 1566416.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710129.75
      sim_grid_pos_y: 1565991.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710131.5
      sim_grid_pos_y: 1565992.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710065.5
      sim_grid_pos_y: 1566368.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710470.25
      sim_grid_pos_y: 1566849.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710754.5
      sim_grid_pos_y: 1566328.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2711066.25
      sim_grid_pos_y: 1565584.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2710983
      sim_grid_pos_y: 1565366.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711144
      sim_grid_pos_y: 1565243.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2711565.75
      sim_grid_pos_y: 1564876.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711905.75
      sim_grid_pos_y: 1564413.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2713416.25
      sim_grid_pos_y: 1563528.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2713058.25
      sim_grid_pos_y: 1563143
    }
    terrain_level_point {
      sim_grid_pos_x: 2712748
      sim_grid_pos_y: 1563184.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2712623.5
      sim_grid_pos_y: 1562918.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2712278.75
      sim_grid_pos_y: 1562802
    }
    terrain_level_point {
      sim_grid_pos_x: 2712005.25
      sim_grid_pos_y: 1563193.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711538.25
      sim_grid_pos_y: 1563403.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711369.5
      sim_grid_pos_y: 1563304.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2711039
      sim_grid_pos_y: 1563148.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710932
      sim_grid_pos_y: 1563596.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2711212.5
      sim_grid_pos_y: 1563809.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2711514.25
      sim_grid_pos_y: 1563937.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711573.5
      sim_grid_pos_y: 1563997.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2711343.5
      sim_grid_pos_y: 1564137.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2711264
      sim_grid_pos_y: 1564379.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2711054.75
      sim_grid_pos_y: 1564616.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710807.75
      sim_grid_pos_y: 1564738.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710665.25
      sim_grid_pos_y: 1564994.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710664.75
      sim_grid_pos_y: 1564822.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2710398.75
      sim_grid_pos_y: 1564841.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710365.75
      sim_grid_pos_y: 1564950.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2710272.75
      sim_grid_pos_y: 1564978.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2710249.75
      sim_grid_pos_y: 1565148.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710158.75
      sim_grid_pos_y: 1565254
    }
    terrain_level_point {
      sim_grid_pos_x: 2710140.5
      sim_grid_pos_y: 1565431.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2710116.25
      sim_grid_pos_y: 1565438
    }
    terrain_level_point {
      sim_grid_pos_x: 2710071.5
      sim_grid_pos_y: 1565493.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710014.25
      sim_grid_pos_y: 1565518.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2709563.25
      sim_grid_pos_y: 1565890.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2709218.25
      sim_grid_pos_y: 1566019.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2708372.75
      sim_grid_pos_y: 1565970.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2707933.25
      sim_grid_pos_y: 1566059.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2707736
      sim_grid_pos_y: 1565890.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2707214.5
      sim_grid_pos_y: 1566078.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2706993.75
      sim_grid_pos_y: 1566404.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2707533.5
      sim_grid_pos_y: 1566450.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2707527.25
      sim_grid_pos_y: 1566608.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2708518.75
      sim_grid_pos_y: 1566663.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2708906.25
      sim_grid_pos_y: 1566432.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2709370.25
      sim_grid_pos_y: 1566494.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2709682.5
      sim_grid_pos_y: 1566445
    }
    terrain_level_point {
      sim_grid_pos_x: 2710086
      sim_grid_pos_y: 1566074
    }
    terrain_level_point {
      sim_grid_pos_x: 2710032.5
      sim_grid_pos_y: 1566377.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710475.75
      sim_grid_pos_y: 1566903.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2710782.25
      sim_grid_pos_y: 1566341.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2711099.5
      sim_grid_pos_y: 1565585
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71102e+06
      sim_grid_pos_y: 1565376.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2711163.5
      sim_grid_pos_y: 1565267.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2711588.5
      sim_grid_pos_y: 1564897.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2711926.75
      sim_grid_pos_y: 1564436.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2713464.75
      sim_grid_pos_y: 1563535.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2.71307e+06
      sim_grid_pos_y: 1563110.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2712766.5
      sim_grid_pos_y: 1563151.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2712645
      sim_grid_pos_y: 1562892.38
    }
  }
}
