terrain_level_data {
  terrain_level: 1220
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1640133.62
      sim_grid_pos_y: 1233975.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640211.75
      sim_grid_pos_y: 1234204.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639988.88
      sim_grid_pos_y: 1234249.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639885.25
      sim_grid_pos_y: 1234315
    }
    terrain_level_point {
      sim_grid_pos_x: 1639765.25
      sim_grid_pos_y: 1234449.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639579.12
      sim_grid_pos_y: 1234660.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639566.12
      sim_grid_pos_y: 1234918
    }
    terrain_level_point {
      sim_grid_pos_x: 1639563.75
      sim_grid_pos_y: 1235102
    }
    terrain_level_point {
      sim_grid_pos_x: 1639353.5
      sim_grid_pos_y: 1235191.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639083.62
      sim_grid_pos_y: 1235089.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638765.62
      sim_grid_pos_y: 1234946.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638725.38
      sim_grid_pos_y: 1234721.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638632
      sim_grid_pos_y: 1234476.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638485.5
      sim_grid_pos_y: 1234245.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1638626.88
      sim_grid_pos_y: 1233979
    }
    terrain_level_point {
      sim_grid_pos_x: 1638888.12
      sim_grid_pos_y: 1233850.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639233.25
      sim_grid_pos_y: 1233776.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639488.5
      sim_grid_pos_y: 1233874.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639847.38
      sim_grid_pos_y: 1233926.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1639504.12
      sim_grid_pos_y: 1233814.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639857
      sim_grid_pos_y: 1233866
    }
    terrain_level_point {
      sim_grid_pos_x: 1.64018e+06
      sim_grid_pos_y: 1233921
    }
    terrain_level_point {
      sim_grid_pos_x: 1640292.62
      sim_grid_pos_y: 1234251
    }
    terrain_level_point {
      sim_grid_pos_x: 1640012.12
      sim_grid_pos_y: 1234307.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639925.38
      sim_grid_pos_y: 1234362.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639811.25
      sim_grid_pos_y: 1234490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639811.25
      sim_grid_pos_y: 1234490.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639639.5
      sim_grid_pos_y: 1234684.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639627.62
      sim_grid_pos_y: 1.23492e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1639624.75
      sim_grid_pos_y: 1235142.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639354.75
      sim_grid_pos_y: 1235257.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639060.12
      sim_grid_pos_y: 1235146.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1638710.88
      sim_grid_pos_y: 1234989.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1638665.75
      sim_grid_pos_y: 1234738
    }
    terrain_level_point {
      sim_grid_pos_x: 1638576.75
      sim_grid_pos_y: 1234504.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638414.38
      sim_grid_pos_y: 1234247.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638581.88
      sim_grid_pos_y: 1233932.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1638867.88
      sim_grid_pos_y: 1233791.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639238.38
      sim_grid_pos_y: 1233712.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1639519.88
      sim_grid_pos_y: 1233755
    }
    terrain_level_point {
      sim_grid_pos_x: 1639866.5
      sim_grid_pos_y: 1233805.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1640226.38
      sim_grid_pos_y: 1233866.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640373.5
      sim_grid_pos_y: 1234297.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640035.25
      sim_grid_pos_y: 1234365.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639965.5
      sim_grid_pos_y: 1234409.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639857.38
      sim_grid_pos_y: 1234531.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639857.38
      sim_grid_pos_y: 1234531.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639699.88
      sim_grid_pos_y: 1234709.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639689.12
      sim_grid_pos_y: 1234922
    }
    terrain_level_point {
      sim_grid_pos_x: 1639685.75
      sim_grid_pos_y: 1235183.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639356.12
      sim_grid_pos_y: 1235323.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639036.62
      sim_grid_pos_y: 1235203
    }
    terrain_level_point {
      sim_grid_pos_x: 1638656
      sim_grid_pos_y: 1235032.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638606.25
      sim_grid_pos_y: 1234754.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638521.5
      sim_grid_pos_y: 1234532.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638343.38
      sim_grid_pos_y: 1234250.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638536.88
      sim_grid_pos_y: 1233886.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638847.5
      sim_grid_pos_y: 1233733
    }
    terrain_level_point {
      sim_grid_pos_x: 1639243.38
      sim_grid_pos_y: 1233648.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1639535.5
      sim_grid_pos_y: 1233695.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639876.12
      sim_grid_pos_y: 1233744.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1640272.88
      sim_grid_pos_y: 1233812
    }
    terrain_level_point {
      sim_grid_pos_x: 1640454.25
      sim_grid_pos_y: 1234343.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640058.5
      sim_grid_pos_y: 1234423.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1640005.75
      sim_grid_pos_y: 1234457.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639903.5
      sim_grid_pos_y: 1234572.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639903.5
      sim_grid_pos_y: 1234572.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1639760.12
      sim_grid_pos_y: 1234734
    }
    terrain_level_point {
      sim_grid_pos_x: 1639750.62
      sim_grid_pos_y: 1234923.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1639746.75
      sim_grid_pos_y: 1235224.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639357.38
      sim_grid_pos_y: 1235389.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639013.25
      sim_grid_pos_y: 1.23526e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1638601.12
      sim_grid_pos_y: 1235075.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1638546.75
      sim_grid_pos_y: 1234771.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1638466.12
      sim_grid_pos_y: 1234559.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638272.25
      sim_grid_pos_y: 1234253.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638491.88
      sim_grid_pos_y: 1233839.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638827.12
      sim_grid_pos_y: 1233674.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639248.5
      sim_grid_pos_y: 1233584.5
    }
  }
}
terrain_level_data {
  terrain_level: 1250
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1638864
      sim_grid_pos_y: 1236470.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638828.38
      sim_grid_pos_y: 1236301.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638930.62
      sim_grid_pos_y: 1236104.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639215.62
      sim_grid_pos_y: 1236015.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639550.62
      sim_grid_pos_y: 1236007.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639726
      sim_grid_pos_y: 1236249
    }
    terrain_level_point {
      sim_grid_pos_x: 1639804.88
      sim_grid_pos_y: 1236458.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639784.38
      sim_grid_pos_y: 1236689.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639852
      sim_grid_pos_y: 1236903.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639828.12
      sim_grid_pos_y: 1237085.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639446.62
      sim_grid_pos_y: 1237267.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639105.12
      sim_grid_pos_y: 1237274
    }
    terrain_level_point {
      sim_grid_pos_x: 1638876.75
      sim_grid_pos_y: 1237143.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1638856.5
      sim_grid_pos_y: 1236846.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638815.88
      sim_grid_pos_y: 1236672.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 1639789.75
      sim_grid_pos_y: 1236214.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1639877.75
      sim_grid_pos_y: 1236448.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639857.12
      sim_grid_pos_y: 1236682
    }
    terrain_level_point {
      sim_grid_pos_x: 1639925.12
      sim_grid_pos_y: 1236897.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639894.12
      sim_grid_pos_y: 1237133.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639463.62
      sim_grid_pos_y: 1237339
    }
    terrain_level_point {
      sim_grid_pos_x: 1639086.75
      sim_grid_pos_y: 1237346.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1638807.88
      sim_grid_pos_y: 1237186.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638785.25
      sim_grid_pos_y: 1236856.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638742.12
      sim_grid_pos_y: 1236671.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638790.5
      sim_grid_pos_y: 1236469.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638752.88
      sim_grid_pos_y: 1236291
    }
    terrain_level_point {
      sim_grid_pos_x: 1638880.75
      sim_grid_pos_y: 1236044.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639203.88
      sim_grid_pos_y: 1235944.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639586.5
      sim_grid_pos_y: 1235934.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 1639853.5
      sim_grid_pos_y: 1236180.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639950.75
      sim_grid_pos_y: 1236438.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639929.88
      sim_grid_pos_y: 1236674
    }
    terrain_level_point {
      sim_grid_pos_x: 1639998.38
      sim_grid_pos_y: 1236891
    }
    terrain_level_point {
      sim_grid_pos_x: 1639960.25
      sim_grid_pos_y: 1237181.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639480.5
      sim_grid_pos_y: 1237410.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639068.38
      sim_grid_pos_y: 1237418.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638738.88
      sim_grid_pos_y: 1237230.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1638714
      sim_grid_pos_y: 1236867.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638668.38
      sim_grid_pos_y: 1236671.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1638716.88
      sim_grid_pos_y: 1236468.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1638677.25
      sim_grid_pos_y: 1236280.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1638830.88
      sim_grid_pos_y: 1235985.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639192.12
      sim_grid_pos_y: 1235872.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639622.38
      sim_grid_pos_y: 1235862.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 1639917.25
      sim_grid_pos_y: 1236146
    }
    terrain_level_point {
      sim_grid_pos_x: 1640023.62
      sim_grid_pos_y: 1236428.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1640002.62
      sim_grid_pos_y: 1236666.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1640071.62
      sim_grid_pos_y: 1236884.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1640026.25
      sim_grid_pos_y: 1237229.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1639497.38
      sim_grid_pos_y: 1237481.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1639049.88
      sim_grid_pos_y: 1237490.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1638669.88
      sim_grid_pos_y: 1237273.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638642.88
      sim_grid_pos_y: 1236878.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638594.62
      sim_grid_pos_y: 1236671.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1638643.38
      sim_grid_pos_y: 1236467.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1638601.75
      sim_grid_pos_y: 1236270.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1638781
      sim_grid_pos_y: 1235925.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1639180.25
      sim_grid_pos_y: 1235801.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1639658.25
      sim_grid_pos_y: 1235789.5
    }
  }
}
terrain_level_data {
  terrain_level: 370
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1641294.5
      sim_grid_pos_y: 1235126.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1641311.88
      sim_grid_pos_y: 1235446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641575.12
      sim_grid_pos_y: 1235682.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641868.75
      sim_grid_pos_y: 1235664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1642123.5
      sim_grid_pos_y: 1235596.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1642499
      sim_grid_pos_y: 1235601.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1642862.5
      sim_grid_pos_y: 1235652.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1643153.75
      sim_grid_pos_y: 1235430.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1643148.12
      sim_grid_pos_y: 1235143.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1643153.62
      sim_grid_pos_y: 1234804.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1642878.5
      sim_grid_pos_y: 1234571.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1642575.25
      sim_grid_pos_y: 1234608.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1642194.25
      sim_grid_pos_y: 1234684.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641706.88
      sim_grid_pos_y: 1234887.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1642897.75
      sim_grid_pos_y: 1234507.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1642565.62
      sim_grid_pos_y: 1234547.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1642176.25
      sim_grid_pos_y: 1234625.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641679.5
      sim_grid_pos_y: 1234832
    }
    terrain_level_point {
      sim_grid_pos_x: 1641231.12
      sim_grid_pos_y: 1235092.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641251.75
      sim_grid_pos_y: 1235475.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641553.25
      sim_grid_pos_y: 1235745.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641878.75
      sim_grid_pos_y: 1235725.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1642131.12
      sim_grid_pos_y: 1235657.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1642494.12
      sim_grid_pos_y: 1235662.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1642879.38
      sim_grid_pos_y: 1235717.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1643215.88
      sim_grid_pos_y: 1235460.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1643209.62
      sim_grid_pos_y: 1235143.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1643215.62
      sim_grid_pos_y: 1234776.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1642917
      sim_grid_pos_y: 1234443.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1642555.88
      sim_grid_pos_y: 1234486.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1642158.12
      sim_grid_pos_y: 1234566.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1641652.12
      sim_grid_pos_y: 1234776.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641167.62
      sim_grid_pos_y: 1235058
    }
    terrain_level_point {
      sim_grid_pos_x: 1641191.75
      sim_grid_pos_y: 1235504.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641531.38
      sim_grid_pos_y: 1235808.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641888.75
      sim_grid_pos_y: 1235786.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1642138.88
      sim_grid_pos_y: 1235719.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1642489.5
      sim_grid_pos_y: 1235724.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1642896.12
      sim_grid_pos_y: 1235781.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1643278
      sim_grid_pos_y: 1235490.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1643271.12
      sim_grid_pos_y: 1235143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1643277.62
      sim_grid_pos_y: 1234748.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1642936.25
      sim_grid_pos_y: 1234378.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1642546.12
      sim_grid_pos_y: 1234425.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1642140.12
      sim_grid_pos_y: 1234507.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641624.75
      sim_grid_pos_y: 1234721.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1641104.12
      sim_grid_pos_y: 1235023.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641131.62
      sim_grid_pos_y: 1235533.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1641509.5
      sim_grid_pos_y: 1235871.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1641898.75
      sim_grid_pos_y: 1235847.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1642146.5
      sim_grid_pos_y: 1235781.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1642484.75
      sim_grid_pos_y: 1235785.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1642913
      sim_grid_pos_y: 1235846.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1643340.12
      sim_grid_pos_y: 1235520.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1643332.62
      sim_grid_pos_y: 1235143.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1643339.62
      sim_grid_pos_y: 1.23472e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1642955.5
      sim_grid_pos_y: 1234314.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1642536.38
      sim_grid_pos_y: 1234364.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1642122.12
      sim_grid_pos_y: 1234448
    }
    terrain_level_point {
      sim_grid_pos_x: 1641597.38
      sim_grid_pos_y: 1234666.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1641040.75
      sim_grid_pos_y: 1234989.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1641071.62
      sim_grid_pos_y: 1235561.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641487.62
      sim_grid_pos_y: 1235934.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1641908.62
      sim_grid_pos_y: 1235908.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1642154.12
      sim_grid_pos_y: 1235842.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1642479.88
      sim_grid_pos_y: 1235847.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1642929.88
      sim_grid_pos_y: 1235911
    }
    terrain_level_point {
      sim_grid_pos_x: 1643402.25
      sim_grid_pos_y: 1235550.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1643394.25
      sim_grid_pos_y: 1235143.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1643401.62
      sim_grid_pos_y: 1234691.88
    }
  }
}
