terrain_level_data {
  terrain_level: 100
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1751337.5
      sim_grid_pos_y: 1915335.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751351.88
      sim_grid_pos_y: 1915433.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1751479.62
      sim_grid_pos_y: 1915451.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751576.38
      sim_grid_pos_y: 1915401.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1751639.88
      sim_grid_pos_y: 1915316.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1751770.88
      sim_grid_pos_y: 1915319.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751805.62
      sim_grid_pos_y: 1915373.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1751880.62
      sim_grid_pos_y: 1915414.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1751973
      sim_grid_pos_y: 1915401
    }
    terrain_level_point {
      sim_grid_pos_x: 1752019.12
      sim_grid_pos_y: 1.9153e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1751981.88
      sim_grid_pos_y: 1915189
    }
    terrain_level_point {
      sim_grid_pos_x: 1751872.25
      sim_grid_pos_y: 1915174.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751742.25
      sim_grid_pos_y: 1915189.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1751559
      sim_grid_pos_y: 1915186
    }
    terrain_level_point {
      sim_grid_pos_x: 1751379.38
      sim_grid_pos_y: 1915186.88
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1751873.25
      sim_grid_pos_y: 1915071.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1751737.38
      sim_grid_pos_y: 1915086.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751559.62
      sim_grid_pos_y: 1915083.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1751301.62
      sim_grid_pos_y: 1915084.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751232.88
      sim_grid_pos_y: 1915329
    }
    terrain_level_point {
      sim_grid_pos_x: 1751261.5
      sim_grid_pos_y: 1915523.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751497.75
      sim_grid_pos_y: 1915558
    }
    terrain_level_point {
      sim_grid_pos_x: 1751644.62
      sim_grid_pos_y: 1915481.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1751690.38
      sim_grid_pos_y: 1.91542e+06
    }
    terrain_level_point {
      sim_grid_pos_x: 1751714
      sim_grid_pos_y: 1915420.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751733.38
      sim_grid_pos_y: 1915450.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751861.38
      sim_grid_pos_y: 1915521.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1752043.12
      sim_grid_pos_y: 1915494.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1752129.25
      sim_grid_pos_y: 1915305.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1752058.62
      sim_grid_pos_y: 1915095.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1751874.12
      sim_grid_pos_y: 1914968.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1751732.62
      sim_grid_pos_y: 1914984
    }
    terrain_level_point {
      sim_grid_pos_x: 1751560.25
      sim_grid_pos_y: 1914980.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1751223.88
      sim_grid_pos_y: 1914982.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751128.25
      sim_grid_pos_y: 1915322.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1751171.12
      sim_grid_pos_y: 1915614.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1751515.75
      sim_grid_pos_y: 1915664.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1751712.88
      sim_grid_pos_y: 1915561.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1751715.5
      sim_grid_pos_y: 1915557.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1751842.25
      sim_grid_pos_y: 1915627.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752113.25
      sim_grid_pos_y: 1915587.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1752239.38
      sim_grid_pos_y: 1915311.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1752135.38
      sim_grid_pos_y: 1915002.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1751875.12
      sim_grid_pos_y: 1914864.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751727.75
      sim_grid_pos_y: 1914881.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1751560.88
      sim_grid_pos_y: 1914878.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1751146.12
      sim_grid_pos_y: 1914880.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1751023.62
      sim_grid_pos_y: 1915315.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1751080.88
      sim_grid_pos_y: 1915704.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1751533.75
      sim_grid_pos_y: 1915770.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1751716.12
      sim_grid_pos_y: 1915675.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1751823.12
      sim_grid_pos_y: 1915734.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1752183.38
      sim_grid_pos_y: 1915680.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1752349.38
      sim_grid_pos_y: 1915317.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1752212.25
      sim_grid_pos_y: 1914909.12
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1751876.12
      sim_grid_pos_y: 1914761.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1751723
      sim_grid_pos_y: 1914778.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751561.5
      sim_grid_pos_y: 1914775.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1751068.38
      sim_grid_pos_y: 1914778.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1750919
      sim_grid_pos_y: 1915308.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1750990.5
      sim_grid_pos_y: 1915795
    }
    terrain_level_point {
      sim_grid_pos_x: 1751551.75
      sim_grid_pos_y: 1915876.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751714.75
      sim_grid_pos_y: 1915791.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751803.88
      sim_grid_pos_y: 1915840.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752253.5
      sim_grid_pos_y: 1915773.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752459.5
      sim_grid_pos_y: 1915322.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752289
      sim_grid_pos_y: 1914815.75
    }
  }
}
terrain_level_data {
  terrain_level: 225
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1752524.5
      sim_grid_pos_y: 1906555.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1752261.38
      sim_grid_pos_y: 1906597.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1752109.75
      sim_grid_pos_y: 1906736.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1752460.62
      sim_grid_pos_y: 1907121.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752824.88
      sim_grid_pos_y: 1907111.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1752902.38
      sim_grid_pos_y: 1906892.25
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1752556.5
      sim_grid_pos_y: 1906446.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1752214.75
      sim_grid_pos_y: 1906501
    }
    terrain_level_point {
      sim_grid_pos_x: 1751965.25
      sim_grid_pos_y: 1906730.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1752416.5
      sim_grid_pos_y: 1907225.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1752898.12
      sim_grid_pos_y: 1907212.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753022
      sim_grid_pos_y: 1906861.5
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1752588.38
      sim_grid_pos_y: 1906337.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1752168.12
      sim_grid_pos_y: 1906404.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1751820.75
      sim_grid_pos_y: 1906724
    }
    terrain_level_point {
      sim_grid_pos_x: 1752372.38
      sim_grid_pos_y: 1907329.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1752971.38
      sim_grid_pos_y: 1907312.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1753141.5
      sim_grid_pos_y: 1906830.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1752620.38
      sim_grid_pos_y: 1906229
    }
    terrain_level_point {
      sim_grid_pos_x: 1752121.5
      sim_grid_pos_y: 1906308.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1751676.25
      sim_grid_pos_y: 1906717.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1752328.25
      sim_grid_pos_y: 1907433.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753044.62
      sim_grid_pos_y: 1907413.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1753261.12
      sim_grid_pos_y: 1.9068e+06
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1752652.25
      sim_grid_pos_y: 1906120.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1752074.88
      sim_grid_pos_y: 1906211.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1751531.62
      sim_grid_pos_y: 1906711.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1752284.12
      sim_grid_pos_y: 1907537
    }
    terrain_level_point {
      sim_grid_pos_x: 1753117.75
      sim_grid_pos_y: 1907513.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1753380.75
      sim_grid_pos_y: 1906769.25
    }
  }
}
terrain_level_data {
  terrain_level: 475
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 1753288.12
      sim_grid_pos_y: 1909126.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753282
      sim_grid_pos_y: 1909267.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753407
      sim_grid_pos_y: 1909348.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1753508.25
      sim_grid_pos_y: 1909262.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1753508.12
      sim_grid_pos_y: 1909128.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1753403.88
      sim_grid_pos_y: 1909037.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 1753406
      sim_grid_pos_y: 1908971.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1753237.88
      sim_grid_pos_y: 1909100.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1753229.5
      sim_grid_pos_y: 1909294.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753411
      sim_grid_pos_y: 1909412.25
    }
    terrain_level_point {
      sim_grid_pos_x: 1753559.5
      sim_grid_pos_y: 1909286.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1753559.38
      sim_grid_pos_y: 1909105.62
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 1753408.12
      sim_grid_pos_y: 1908905.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1753187.75
      sim_grid_pos_y: 1909074
    }
    terrain_level_point {
      sim_grid_pos_x: 1753177
      sim_grid_pos_y: 1909321.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1753415.12
      sim_grid_pos_y: 1909476
    }
    terrain_level_point {
      sim_grid_pos_x: 1753610.75
      sim_grid_pos_y: 1909310.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1753610.62
      sim_grid_pos_y: 1909082.38
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 1753410.25
      sim_grid_pos_y: 1908839.12
    }
    terrain_level_point {
      sim_grid_pos_x: 1753137.62
      sim_grid_pos_y: 1909047.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1753124.5
      sim_grid_pos_y: 1909348.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1753419.12
      sim_grid_pos_y: 1909539.75
    }
    terrain_level_point {
      sim_grid_pos_x: 1753662.12
      sim_grid_pos_y: 1909333.88
    }
    terrain_level_point {
      sim_grid_pos_x: 1753661.88
      sim_grid_pos_y: 1909059
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 1753412.5
      sim_grid_pos_y: 1908773
    }
    terrain_level_point {
      sim_grid_pos_x: 1753087.38
      sim_grid_pos_y: 1909021.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1753072.12
      sim_grid_pos_y: 1909375.38
    }
    terrain_level_point {
      sim_grid_pos_x: 1753423.25
      sim_grid_pos_y: 1909603.5
    }
    terrain_level_point {
      sim_grid_pos_x: 1753713.38
      sim_grid_pos_y: 1909357.62
    }
    terrain_level_point {
      sim_grid_pos_x: 1753713.12
      sim_grid_pos_y: 1909035.75
    }
  }
}
