terrain_level_data {
  terrain_level: 3
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2046349.38
      sim_grid_pos_y: 81962.6719
    }
    terrain_level_point {
      sim_grid_pos_x: 2046362.25
      sim_grid_pos_y: 82898.1094
    }
    terrain_level_point {
      sim_grid_pos_x: 2046704.12
      sim_grid_pos_y: 84124.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 2047448.5
      sim_grid_pos_y: 85113.6094
    }
    terrain_level_point {
      sim_grid_pos_x: 2051089.5
      sim_grid_pos_y: 88392.125
    }
    terrain_level_point {
      sim_grid_pos_x: 2053421.5
      sim_grid_pos_y: 91788
    }
    terrain_level_point {
      sim_grid_pos_x: 2053115.5
      sim_grid_pos_y: 94231.5156
    }
    terrain_level_point {
      sim_grid_pos_x: 2053356.5
      sim_grid_pos_y: 96540.6562
    }
    terrain_level_point {
      sim_grid_pos_x: 2054268.38
      sim_grid_pos_y: 98966.4062
    }
    terrain_level_point {
      sim_grid_pos_x: 2056266.88
      sim_grid_pos_y: 104859.297
    }
    terrain_level_point {
      sim_grid_pos_x: 2056833
      sim_grid_pos_y: 104300.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2057643.62
      sim_grid_pos_y: 98419.4
    }
    terrain_level_point {
      sim_grid_pos_x: 2057557.25
      sim_grid_pos_y: 92044.75
    }
    terrain_level_point {
      sim_grid_pos_x: 2056710.25
      sim_grid_pos_y: 87862.3359
    }
    terrain_level_point {
      sim_grid_pos_x: 2056035.62
      sim_grid_pos_y: 85612.3359
    }
    terrain_level_point {
      sim_grid_pos_x: 2053399.75
      sim_grid_pos_y: 81451.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 2051235.88
      sim_grid_pos_y: 78079.4922
    }
    terrain_level_point {
      sim_grid_pos_x: 2051161
      sim_grid_pos_y: 74501.8516
    }
    terrain_level_point {
      sim_grid_pos_x: 2052055.62
      sim_grid_pos_y: 71666.6172
    }
    terrain_level_point {
      sim_grid_pos_x: 2.05291e+06
      sim_grid_pos_y: 65693.1953
    }
    terrain_level_point {
      sim_grid_pos_x: 2053508.75
      sim_grid_pos_y: 62990.8359
    }
    terrain_level_point {
      sim_grid_pos_x: 2054958
      sim_grid_pos_y: 60676.7617
    }
    terrain_level_point {
      sim_grid_pos_x: 2053908.88
      sim_grid_pos_y: 59587.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 2054708.88
      sim_grid_pos_y: 56649.6641
    }
    terrain_level_point {
      sim_grid_pos_x: 2052448.5
      sim_grid_pos_y: 55282.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2051773.25
      sim_grid_pos_y: 53088.8203
    }
    terrain_level_point {
      sim_grid_pos_x: 2050186.88
      sim_grid_pos_y: 55163.5703
    }
    terrain_level_point {
      sim_grid_pos_x: 2050176.12
      sim_grid_pos_y: 56438.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2049042.62
      sim_grid_pos_y: 59202.3438
    }
    terrain_level_point {
      sim_grid_pos_x: 2047747.88
      sim_grid_pos_y: 60367.0312
    }
    terrain_level_point {
      sim_grid_pos_x: 2046171.88
      sim_grid_pos_y: 67270.8359
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 80
    terrain_level_point {
      sim_grid_pos_x: 2051760.12
      sim_grid_pos_y: 53055.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2050156.25
      sim_grid_pos_y: 55153.0352
    }
    terrain_level_point {
      sim_grid_pos_x: 2050145.38
      sim_grid_pos_y: 56432.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2049016.88
      sim_grid_pos_y: 59184.1758
    }
    terrain_level_point {
      sim_grid_pos_x: 2047720.12
      sim_grid_pos_y: 60350.6758
    }
    terrain_level_point {
      sim_grid_pos_x: 2046141
      sim_grid_pos_y: 67267.5547
    }
    terrain_level_point {
      sim_grid_pos_x: 2046318.62
      sim_grid_pos_y: 81963.0625
    }
    terrain_level_point {
      sim_grid_pos_x: 2046331.62
      sim_grid_pos_y: 82902.5391
    }
    terrain_level_point {
      sim_grid_pos_x: 2046676.12
      sim_grid_pos_y: 84138.2188
    }
    terrain_level_point {
      sim_grid_pos_x: 2047425.62
      sim_grid_pos_y: 85134.4844
    }
    terrain_level_point {
      sim_grid_pos_x: 2051066.25
      sim_grid_pos_y: 88412.5547
    }
    terrain_level_point {
      sim_grid_pos_x: 2053389.62
      sim_grid_pos_y: 91795.7656
    }
    terrain_level_point {
      sim_grid_pos_x: 2053084.62
      sim_grid_pos_y: 94231.1953
    }
    terrain_level_point {
      sim_grid_pos_x: 2053326.38
      sim_grid_pos_y: 96547.7734
    }
    terrain_level_point {
      sim_grid_pos_x: 2054239.38
      sim_grid_pos_y: 98976.6406
    }
    terrain_level_point {
      sim_grid_pos_x: 2056253.5
      sim_grid_pos_y: 104915.695
    }
    terrain_level_point {
      sim_grid_pos_x: 2056862
      sim_grid_pos_y: 104315.055
    }
    terrain_level_point {
      sim_grid_pos_x: 2057674.38
      sim_grid_pos_y: 98421.3047
    }
    terrain_level_point {
      sim_grid_pos_x: 2057588
      sim_grid_pos_y: 92041.4531
    }
    terrain_level_point {
      sim_grid_pos_x: 2056740.12
      sim_grid_pos_y: 87854.8594
    }
    terrain_level_point {
      sim_grid_pos_x: 2056063.88
      sim_grid_pos_y: 85599.4453
    }
    terrain_level_point {
      sim_grid_pos_x: 2053425.62
      sim_grid_pos_y: 81435.2734
    }
    terrain_level_point {
      sim_grid_pos_x: 2051266.5
      sim_grid_pos_y: 78070.1875
    }
    terrain_level_point {
      sim_grid_pos_x: 2051191.75
      sim_grid_pos_y: 74506.2812
    }
    terrain_level_point {
      sim_grid_pos_x: 2052085.75
      sim_grid_pos_y: 71673.4688
    }
    terrain_level_point {
      sim_grid_pos_x: 2052940.25
      sim_grid_pos_y: 65698.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2053537.62
      sim_grid_pos_y: 63002.6875
    }
    terrain_level_point {
      sim_grid_pos_x: 2054996.75
      sim_grid_pos_y: 60672.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2053943.25
      sim_grid_pos_y: 59579.0547
    }
    terrain_level_point {
      sim_grid_pos_x: 2054744.75
      sim_grid_pos_y: 56635.3555
    }
    terrain_level_point {
      sim_grid_pos_x: 2052474.38
      sim_grid_pos_y: 55262.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 2051797.12
      sim_grid_pos_y: 53061.8438
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 60
    terrain_level_point {
      sim_grid_pos_x: 2051747.12
      sim_grid_pos_y: 53021.6562
    }
    terrain_level_point {
      sim_grid_pos_x: 2050125.5
      sim_grid_pos_y: 55142.5156
    }
    terrain_level_point {
      sim_grid_pos_x: 2050114.75
      sim_grid_pos_y: 56426.5156
    }
    terrain_level_point {
      sim_grid_pos_x: 2048991.12
      sim_grid_pos_y: 59166.0078
    }
    terrain_level_point {
      sim_grid_pos_x: 2047692.25
      sim_grid_pos_y: 60334.3281
    }
    terrain_level_point {
      sim_grid_pos_x: 2046110.25
      sim_grid_pos_y: 67264.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 2046287.88
      sim_grid_pos_y: 81963.4688
    }
    terrain_level_point {
      sim_grid_pos_x: 2046300.88
      sim_grid_pos_y: 82906.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 2046648
      sim_grid_pos_y: 84152.0781
    }
    terrain_level_point {
      sim_grid_pos_x: 2047402.88
      sim_grid_pos_y: 85155.3516
    }
    terrain_level_point {
      sim_grid_pos_x: 2051042.88
      sim_grid_pos_y: 88432.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 2053357.62
      sim_grid_pos_y: 91803.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 2053053.62
      sim_grid_pos_y: 94230.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2053296.12
      sim_grid_pos_y: 96554.9062
    }
    terrain_level_point {
      sim_grid_pos_x: 2054210.5
      sim_grid_pos_y: 98986.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 2056240.25
      sim_grid_pos_y: 104972.094
    }
    terrain_level_point {
      sim_grid_pos_x: 2056891
      sim_grid_pos_y: 104329.609
    }
    terrain_level_point {
      sim_grid_pos_x: 2057705.12
      sim_grid_pos_y: 98423.2
    }
    terrain_level_point {
      sim_grid_pos_x: 2057618.62
      sim_grid_pos_y: 92038.1641
    }
    terrain_level_point {
      sim_grid_pos_x: 2.05677e+06
      sim_grid_pos_y: 87847.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 2056092.12
      sim_grid_pos_y: 85586.5625
    }
    terrain_level_point {
      sim_grid_pos_x: 2053451.62
      sim_grid_pos_y: 81418.7422
    }
    terrain_level_point {
      sim_grid_pos_x: 2051297
      sim_grid_pos_y: 78060.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2051222.62
      sim_grid_pos_y: 74510.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2052115.75
      sim_grid_pos_y: 71680.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 2052970.5
      sim_grid_pos_y: 65704.1953
    }
    terrain_level_point {
      sim_grid_pos_x: 2053566.5
      sim_grid_pos_y: 63014.5078
    }
    terrain_level_point {
      sim_grid_pos_x: 2055035.62
      sim_grid_pos_y: 60668.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2053977.5
      sim_grid_pos_y: 59570.2852
    }
    terrain_level_point {
      sim_grid_pos_x: 2054780.5
      sim_grid_pos_y: 56621.0469
    }
    terrain_level_point {
      sim_grid_pos_x: 2052500.38
      sim_grid_pos_y: 55242.2266
    }
    terrain_level_point {
      sim_grid_pos_x: 2051821
      sim_grid_pos_y: 53034.8672
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 40
    terrain_level_point {
      sim_grid_pos_x: 2051734.12
      sim_grid_pos_y: 52988.0781
    }
    terrain_level_point {
      sim_grid_pos_x: 2050094.88
      sim_grid_pos_y: 55131.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 2050084
      sim_grid_pos_y: 56420.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 2048965.25
      sim_grid_pos_y: 59147.8438
    }
    terrain_level_point {
      sim_grid_pos_x: 2047664.5
      sim_grid_pos_y: 60317.9766
    }
    terrain_level_point {
      sim_grid_pos_x: 2046079.38
      sim_grid_pos_y: 67260.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 2046257.12
      sim_grid_pos_y: 81963.8516
    }
    terrain_level_point {
      sim_grid_pos_x: 2046270.25
      sim_grid_pos_y: 82911.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 2.04662e+06
      sim_grid_pos_y: 84165.9219
    }
    terrain_level_point {
      sim_grid_pos_x: 2047380.12
      sim_grid_pos_y: 85176.2188
    }
    terrain_level_point {
      sim_grid_pos_x: 2051019.62
      sim_grid_pos_y: 88453.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 2053325.62
      sim_grid_pos_y: 91811.3281
    }
    terrain_level_point {
      sim_grid_pos_x: 2053022.75
      sim_grid_pos_y: 94230.5547
    }
    terrain_level_point {
      sim_grid_pos_x: 2053266
      sim_grid_pos_y: 96562.0234
    }
    terrain_level_point {
      sim_grid_pos_x: 2054181.5
      sim_grid_pos_y: 98997.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2056226.88
      sim_grid_pos_y: 105028.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2056920.12
      sim_grid_pos_y: 104344.156
    }
    terrain_level_point {
      sim_grid_pos_x: 2057736
      sim_grid_pos_y: 98425.1172
    }
    terrain_level_point {
      sim_grid_pos_x: 2057649.38
      sim_grid_pos_y: 92034.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2056799.75
      sim_grid_pos_y: 87839.8828
    }
    terrain_level_point {
      sim_grid_pos_x: 2056120.38
      sim_grid_pos_y: 85573.6719
    }
    terrain_level_point {
      sim_grid_pos_x: 2053477.5
      sim_grid_pos_y: 81402.2
    }
    terrain_level_point {
      sim_grid_pos_x: 2051327.62
      sim_grid_pos_y: 78051.5547
    }
    terrain_level_point {
      sim_grid_pos_x: 2051253.5
      sim_grid_pos_y: 74515.1562
    }
    terrain_level_point {
      sim_grid_pos_x: 2052145.88
      sim_grid_pos_y: 71687.1641
    }
    terrain_level_point {
      sim_grid_pos_x: 2053000.75
      sim_grid_pos_y: 65709.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 2053595.5
      sim_grid_pos_y: 63026.3281
    }
    terrain_level_point {
      sim_grid_pos_x: 2055074.5
      sim_grid_pos_y: 60664.6562
    }
    terrain_level_point {
      sim_grid_pos_x: 2054011.75
      sim_grid_pos_y: 59561.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 2054816.25
      sim_grid_pos_y: 56606.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 2052526.25
      sim_grid_pos_y: 55221.9648
    }
    terrain_level_point {
      sim_grid_pos_x: 2051844.88
      sim_grid_pos_y: 53007.8945
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 20
    terrain_level_point {
      sim_grid_pos_x: 2051721
      sim_grid_pos_y: 52954.4961
    }
    terrain_level_point {
      sim_grid_pos_x: 2050064.25
      sim_grid_pos_y: 55121.4648
    }
    terrain_level_point {
      sim_grid_pos_x: 2050053.25
      sim_grid_pos_y: 56414.1328
    }
    terrain_level_point {
      sim_grid_pos_x: 2048939.5
      sim_grid_pos_y: 59129.6758
    }
    terrain_level_point {
      sim_grid_pos_x: 2047636.62
      sim_grid_pos_y: 60301.6328
    }
    terrain_level_point {
      sim_grid_pos_x: 2046048.62
      sim_grid_pos_y: 67257.7
    }
    terrain_level_point {
      sim_grid_pos_x: 2046226.38
      sim_grid_pos_y: 81964.2578
    }
    terrain_level_point {
      sim_grid_pos_x: 2046239.5
      sim_grid_pos_y: 82915.7734
    }
    terrain_level_point {
      sim_grid_pos_x: 2046591.88
      sim_grid_pos_y: 84179.7734
    }
    terrain_level_point {
      sim_grid_pos_x: 2047357.25
      sim_grid_pos_y: 85197.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 2050996.38
      sim_grid_pos_y: 88473.8
    }
    terrain_level_point {
      sim_grid_pos_x: 2053293.62
      sim_grid_pos_y: 91819.1094
    }
    terrain_level_point {
      sim_grid_pos_x: 2052991.75
      sim_grid_pos_y: 94230.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2053235.75
      sim_grid_pos_y: 96569.1484
    }
    terrain_level_point {
      sim_grid_pos_x: 2054152.62
      sim_grid_pos_y: 99007.8438
    }
    terrain_level_point {
      sim_grid_pos_x: 2056213.5
      sim_grid_pos_y: 105084.891
    }
    terrain_level_point {
      sim_grid_pos_x: 2056949.12
      sim_grid_pos_y: 104358.703
    }
    terrain_level_point {
      sim_grid_pos_x: 2057766.75
      sim_grid_pos_y: 98427.0156
    }
    terrain_level_point {
      sim_grid_pos_x: 2057680.12
      sim_grid_pos_y: 92031.5859
    }
    terrain_level_point {
      sim_grid_pos_x: 2056829.62
      sim_grid_pos_y: 87832.4
    }
    terrain_level_point {
      sim_grid_pos_x: 2056148.62
      sim_grid_pos_y: 85560.7891
    }
    terrain_level_point {
      sim_grid_pos_x: 2053503.5
      sim_grid_pos_y: 81385.6719
    }
    terrain_level_point {
      sim_grid_pos_x: 2051358.25
      sim_grid_pos_y: 78042.2422
    }
    terrain_level_point {
      sim_grid_pos_x: 2051284.38
      sim_grid_pos_y: 74519.5625
    }
    terrain_level_point {
      sim_grid_pos_x: 2052176
      sim_grid_pos_y: 71694.0156
    }
    terrain_level_point {
      sim_grid_pos_x: 2053031
      sim_grid_pos_y: 65715.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 2053624.38
      sim_grid_pos_y: 63038.1562
    }
    terrain_level_point {
      sim_grid_pos_x: 2055113.25
      sim_grid_pos_y: 60660.6172
    }
    terrain_level_point {
      sim_grid_pos_x: 2054046
      sim_grid_pos_y: 59552.7578
    }
    terrain_level_point {
      sim_grid_pos_x: 2054852
      sim_grid_pos_y: 56592.4258
    }
    terrain_level_point {
      sim_grid_pos_x: 2052552.25
      sim_grid_pos_y: 55201.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2051868.75
      sim_grid_pos_y: 52980.9258
    }
  }
}
terrain_level_data {
  terrain_level: 2
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2052989.75
      sim_grid_pos_y: 55357.9922
    }
    terrain_level_point {
      sim_grid_pos_x: 2055485.5
      sim_grid_pos_y: 53259.0508
    }
    terrain_level_point {
      sim_grid_pos_x: 2055672.5
      sim_grid_pos_y: 51891.8633
    }
    terrain_level_point {
      sim_grid_pos_x: 2056141.62
      sim_grid_pos_y: 51648.7422
    }
    terrain_level_point {
      sim_grid_pos_x: 2057125.75
      sim_grid_pos_y: 49355.8
    }
    terrain_level_point {
      sim_grid_pos_x: 2058906.62
      sim_grid_pos_y: 47212.832
    }
    terrain_level_point {
      sim_grid_pos_x: 2062114.12
      sim_grid_pos_y: 44915.6836
    }
    terrain_level_point {
      sim_grid_pos_x: 2064125.25
      sim_grid_pos_y: 42689.5586
    }
    terrain_level_point {
      sim_grid_pos_x: 2063025.88
      sim_grid_pos_y: 42785.7031
    }
    terrain_level_point {
      sim_grid_pos_x: 2062719.75
      sim_grid_pos_y: 40744.3281
    }
    terrain_level_point {
      sim_grid_pos_x: 2.06118e+06
      sim_grid_pos_y: 40834.457
    }
    terrain_level_point {
      sim_grid_pos_x: 2060997.12
      sim_grid_pos_y: 39916.1133
    }
    terrain_level_point {
      sim_grid_pos_x: 2057919.12
      sim_grid_pos_y: 40307.6094
    }
    terrain_level_point {
      sim_grid_pos_x: 2057980.12
      sim_grid_pos_y: 41040.9922
    }
    terrain_level_point {
      sim_grid_pos_x: 2056704.75
      sim_grid_pos_y: 41359.543
    }
    terrain_level_point {
      sim_grid_pos_x: 2056736.62
      sim_grid_pos_y: 41893.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 2053634.88
      sim_grid_pos_y: 42146.6
    }
    terrain_level_point {
      sim_grid_pos_x: 2053602.12
      sim_grid_pos_y: 42582.1641
    }
    terrain_level_point {
      sim_grid_pos_x: 2051301.25
      sim_grid_pos_y: 43617.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 2050231.88
      sim_grid_pos_y: 43531.2148
    }
    terrain_level_point {
      sim_grid_pos_x: 2049143.25
      sim_grid_pos_y: 44875.832
    }
    terrain_level_point {
      sim_grid_pos_x: 2047880.5
      sim_grid_pos_y: 45369.043
    }
    terrain_level_point {
      sim_grid_pos_x: 2047069.75
      sim_grid_pos_y: 45778.9883
    }
    terrain_level_point {
      sim_grid_pos_x: 2046207.62
      sim_grid_pos_y: 46424.9648
    }
    terrain_level_point {
      sim_grid_pos_x: 2045353
      sim_grid_pos_y: 48168.2852
    }
    terrain_level_point {
      sim_grid_pos_x: 2044827.75
      sim_grid_pos_y: 48876.7773
    }
    terrain_level_point {
      sim_grid_pos_x: 2047046
      sim_grid_pos_y: 49017.2617
    }
    terrain_level_point {
      sim_grid_pos_x: 2047272.75
      sim_grid_pos_y: 47619.0273
    }
    terrain_level_point {
      sim_grid_pos_x: 2049331
      sim_grid_pos_y: 50803.4609
    }
    terrain_level_point {
      sim_grid_pos_x: 2050587.5
      sim_grid_pos_y: 50649.0156
    }
    terrain_level_point {
      sim_grid_pos_x: 2051672.5
      sim_grid_pos_y: 50130.793
    }
    terrain_level_point {
      sim_grid_pos_x: 2052476.38
      sim_grid_pos_y: 50214.2891
    }
    terrain_level_point {
      sim_grid_pos_x: 2053009.12
      sim_grid_pos_y: 50566.0898
    }
    terrain_level_point {
      sim_grid_pos_x: 2053324.88
      sim_grid_pos_y: 51378.5391
    }
    terrain_level_point {
      sim_grid_pos_x: 2053303.5
      sim_grid_pos_y: 52225.5898
    }
    terrain_level_point {
      sim_grid_pos_x: 2053162.12
      sim_grid_pos_y: 52616.5508
    }
    terrain_level_point {
      sim_grid_pos_x: 2052830.5
      sim_grid_pos_y: 53024.3906
    }
    terrain_level_point {
      sim_grid_pos_x: 2052077
      sim_grid_pos_y: 53081.7812
    }
    terrain_level_point {
      sim_grid_pos_x: 2051569.62
      sim_grid_pos_y: 53077.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 2051055.25
      sim_grid_pos_y: 53843.3086
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 75
    terrain_level_point {
      sim_grid_pos_x: 2061021.62
      sim_grid_pos_y: 39881.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 2057886.12
      sim_grid_pos_y: 40280.8047
    }
    terrain_level_point {
      sim_grid_pos_x: 2057947.38
      sim_grid_pos_y: 41017.4961
    }
    terrain_level_point {
      sim_grid_pos_x: 2056672.62
      sim_grid_pos_y: 41335.8867
    }
    terrain_level_point {
      sim_grid_pos_x: 2056704.12
      sim_grid_pos_y: 41865.6055
    }
    terrain_level_point {
      sim_grid_pos_x: 2053606.12
      sim_grid_pos_y: 42118.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 2053572.88
      sim_grid_pos_y: 42561.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2051295.75
      sim_grid_pos_y: 43586.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2050218.25
      sim_grid_pos_y: 43499.2539
    }
    terrain_level_point {
      sim_grid_pos_x: 2049124.38
      sim_grid_pos_y: 44850.1562
    }
    terrain_level_point {
      sim_grid_pos_x: 2047868
      sim_grid_pos_y: 45340.9336
    }
    terrain_level_point {
      sim_grid_pos_x: 2047053.5
      sim_grid_pos_y: 45752.7539
    }
    terrain_level_point {
      sim_grid_pos_x: 2046183.25
      sim_grid_pos_y: 46404.7852
    }
    terrain_level_point {
      sim_grid_pos_x: 2045326.62
      sim_grid_pos_y: 48152.2266
    }
    terrain_level_point {
      sim_grid_pos_x: 2044792.12
      sim_grid_pos_y: 48873.1445
    }
    terrain_level_point {
      sim_grid_pos_x: 2044807.5
      sim_grid_pos_y: 48906.3164
    }
    terrain_level_point {
      sim_grid_pos_x: 2047071.88
      sim_grid_pos_y: 49049.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2047290.25
      sim_grid_pos_y: 47702.8672
    }
    terrain_level_point {
      sim_grid_pos_x: 2049315.62
      sim_grid_pos_y: 50836.3438
    }
    terrain_level_point {
      sim_grid_pos_x: 2050596.25
      sim_grid_pos_y: 50678.9375
    }
    terrain_level_point {
      sim_grid_pos_x: 2051678
      sim_grid_pos_y: 50162.2852
    }
    terrain_level_point {
      sim_grid_pos_x: 2052465.75
      sim_grid_pos_y: 50244.1055
    }
    terrain_level_point {
      sim_grid_pos_x: 2052984
      sim_grid_pos_y: 50586.3672
    }
    terrain_level_point {
      sim_grid_pos_x: 2053294
      sim_grid_pos_y: 51383.9258
    }
    terrain_level_point {
      sim_grid_pos_x: 2053272.88
      sim_grid_pos_y: 52219.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 2053135
      sim_grid_pos_y: 52601.2148
    }
    terrain_level_point {
      sim_grid_pos_x: 2052815
      sim_grid_pos_y: 52994.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 2052075.88
      sim_grid_pos_y: 53051.0234
    }
    terrain_level_point {
      sim_grid_pos_x: 2051553.25
      sim_grid_pos_y: 53047.0352
    }
    terrain_level_point {
      sim_grid_pos_x: 2051013.75
      sim_grid_pos_y: 53849.8828
    }
    terrain_level_point {
      sim_grid_pos_x: 2052990.38
      sim_grid_pos_y: 55397.5938
    }
    terrain_level_point {
      sim_grid_pos_x: 2055514.38
      sim_grid_pos_y: 53274.9648
    }
    terrain_level_point {
      sim_grid_pos_x: 2055700.75
      sim_grid_pos_y: 51911.8438
    }
    terrain_level_point {
      sim_grid_pos_x: 2056165.62
      sim_grid_pos_y: 51670.9961
    }
    terrain_level_point {
      sim_grid_pos_x: 2057152.25
      sim_grid_pos_y: 49372.0625
    }
    terrain_level_point {
      sim_grid_pos_x: 2058927.75
      sim_grid_pos_y: 47235.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 2062134.62
      sim_grid_pos_y: 44938.7656
    }
    terrain_level_point {
      sim_grid_pos_x: 2064162.12
      sim_grid_pos_y: 42694.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2064143.38
      sim_grid_pos_y: 42657.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 2063052
      sim_grid_pos_y: 42752.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 2062746
      sim_grid_pos_y: 40711.9766
    }
    terrain_level_point {
      sim_grid_pos_x: 2061204.88
      sim_grid_pos_y: 40802.1836
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2061046.25
      sim_grid_pos_y: 39847.8555
    }
    terrain_level_point {
      sim_grid_pos_x: 2057853
      sim_grid_pos_y: 40254.0156
    }
    terrain_level_point {
      sim_grid_pos_x: 2057914.5
      sim_grid_pos_y: 40993.9844
    }
    terrain_level_point {
      sim_grid_pos_x: 2056640.38
      sim_grid_pos_y: 41312.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2056671.62
      sim_grid_pos_y: 41837.3945
    }
    terrain_level_point {
      sim_grid_pos_x: 2053577.5
      sim_grid_pos_y: 42089.5664
    }
    terrain_level_point {
      sim_grid_pos_x: 2053543.62
      sim_grid_pos_y: 42541.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 2051290.38
      sim_grid_pos_y: 43554.9336
    }
    terrain_level_point {
      sim_grid_pos_x: 2050204.5
      sim_grid_pos_y: 43467.2852
    }
    terrain_level_point {
      sim_grid_pos_x: 2049105.62
      sim_grid_pos_y: 44824.4648
    }
    terrain_level_point {
      sim_grid_pos_x: 2047855.38
      sim_grid_pos_y: 45312.8164
    }
    terrain_level_point {
      sim_grid_pos_x: 2047037.25
      sim_grid_pos_y: 45726.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 2046158.88
      sim_grid_pos_y: 46384.6055
    }
    terrain_level_point {
      sim_grid_pos_x: 2045300.25
      sim_grid_pos_y: 48136.207
    }
    terrain_level_point {
      sim_grid_pos_x: 2044756.5
      sim_grid_pos_y: 48869.5156
    }
    terrain_level_point {
      sim_grid_pos_x: 2044787.38
      sim_grid_pos_y: 48935.8555
    }
    terrain_level_point {
      sim_grid_pos_x: 2047097.75
      sim_grid_pos_y: 49082.1875
    }
    terrain_level_point {
      sim_grid_pos_x: 2047307.88
      sim_grid_pos_y: 47786.6953
    }
    terrain_level_point {
      sim_grid_pos_x: 2049300.25
      sim_grid_pos_y: 50869.2266
    }
    terrain_level_point {
      sim_grid_pos_x: 2050605
      sim_grid_pos_y: 50708.8438
    }
    terrain_level_point {
      sim_grid_pos_x: 2051683.38
      sim_grid_pos_y: 50193.7734
    }
    terrain_level_point {
      sim_grid_pos_x: 2052455.12
      sim_grid_pos_y: 50273.9258
    }
    terrain_level_point {
      sim_grid_pos_x: 2052958.88
      sim_grid_pos_y: 50606.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2053263
      sim_grid_pos_y: 51389.3125
    }
    terrain_level_point {
      sim_grid_pos_x: 2053242.25
      sim_grid_pos_y: 52214.0859
    }
    terrain_level_point {
      sim_grid_pos_x: 2053107.88
      sim_grid_pos_y: 52585.8281
    }
    terrain_level_point {
      sim_grid_pos_x: 2052799.5
      sim_grid_pos_y: 52965.0625
    }
    terrain_level_point {
      sim_grid_pos_x: 2052074.75
      sim_grid_pos_y: 53020.2578
    }
    terrain_level_point {
      sim_grid_pos_x: 2051537
      sim_grid_pos_y: 53016.1445
    }
    terrain_level_point {
      sim_grid_pos_x: 2050972.25
      sim_grid_pos_y: 53856.4766
    }
    terrain_level_point {
      sim_grid_pos_x: 2052991.12
      sim_grid_pos_y: 55437.1953
    }
    terrain_level_point {
      sim_grid_pos_x: 2055543.25
      sim_grid_pos_y: 53290.875
    }
    terrain_level_point {
      sim_grid_pos_x: 2055729.12
      sim_grid_pos_y: 51931.8125
    }
    terrain_level_point {
      sim_grid_pos_x: 2056189.5
      sim_grid_pos_y: 51693.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2057178.75
      sim_grid_pos_y: 49388.2734
    }
    terrain_level_point {
      sim_grid_pos_x: 2058948.88
      sim_grid_pos_y: 47258.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2062155.25
      sim_grid_pos_y: 44961.8359
    }
    terrain_level_point {
      sim_grid_pos_x: 2064199
      sim_grid_pos_y: 42699.6836
    }
    terrain_level_point {
      sim_grid_pos_x: 2064161.62
      sim_grid_pos_y: 42624.625
    }
    terrain_level_point {
      sim_grid_pos_x: 2063078.12
      sim_grid_pos_y: 42719.3945
    }
    terrain_level_point {
      sim_grid_pos_x: 2062772.25
      sim_grid_pos_y: 40679.6367
    }
    terrain_level_point {
      sim_grid_pos_x: 2061229.88
      sim_grid_pos_y: 40769.9258
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 25
    terrain_level_point {
      sim_grid_pos_x: 2061070.75
      sim_grid_pos_y: 39813.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2057819.88
      sim_grid_pos_y: 40227.2148
    }
    terrain_level_point {
      sim_grid_pos_x: 2057881.75
      sim_grid_pos_y: 40970.4844
    }
    terrain_level_point {
      sim_grid_pos_x: 2056608.12
      sim_grid_pos_y: 41288.5742
    }
    terrain_level_point {
      sim_grid_pos_x: 2056639.12
      sim_grid_pos_y: 41809.1836
    }
    terrain_level_point {
      sim_grid_pos_x: 2053548.75
      sim_grid_pos_y: 42061.0469
    }
    terrain_level_point {
      sim_grid_pos_x: 2053514.25
      sim_grid_pos_y: 42520.5469
    }
    terrain_level_point {
      sim_grid_pos_x: 2051285
      sim_grid_pos_y: 43523.6562
    }
    terrain_level_point {
      sim_grid_pos_x: 2050190.88
      sim_grid_pos_y: 43435.3242
    }
    terrain_level_point {
      sim_grid_pos_x: 2049086.88
      sim_grid_pos_y: 44798.7852
    }
    terrain_level_point {
      sim_grid_pos_x: 2047842.88
      sim_grid_pos_y: 45284.707
    }
    terrain_level_point {
      sim_grid_pos_x: 2047020.88
      sim_grid_pos_y: 45700.2852
    }
    terrain_level_point {
      sim_grid_pos_x: 2046134.5
      sim_grid_pos_y: 46364.4258
    }
    terrain_level_point {
      sim_grid_pos_x: 2045273.88
      sim_grid_pos_y: 48120.0742
    }
    terrain_level_point {
      sim_grid_pos_x: 2044720.88
      sim_grid_pos_y: 48865.8867
    }
    terrain_level_point {
      sim_grid_pos_x: 2044767.12
      sim_grid_pos_y: 48965.3945
    }
    terrain_level_point {
      sim_grid_pos_x: 2047123.62
      sim_grid_pos_y: 49114.6445
    }
    terrain_level_point {
      sim_grid_pos_x: 2047325.38
      sim_grid_pos_y: 47870.5352
    }
    terrain_level_point {
      sim_grid_pos_x: 2049284.88
      sim_grid_pos_y: 50902.1055
    }
    terrain_level_point {
      sim_grid_pos_x: 2050613.75
      sim_grid_pos_y: 50738.7656
    }
    terrain_level_point {
      sim_grid_pos_x: 2051688.88
      sim_grid_pos_y: 50225.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 2052444.38
      sim_grid_pos_y: 50303.7344
    }
    terrain_level_point {
      sim_grid_pos_x: 2052933.75
      sim_grid_pos_y: 50626.9062
    }
    terrain_level_point {
      sim_grid_pos_x: 2053232.12
      sim_grid_pos_y: 51394.7266
    }
    terrain_level_point {
      sim_grid_pos_x: 2053211.62
      sim_grid_pos_y: 52208.2734
    }
    terrain_level_point {
      sim_grid_pos_x: 2053080.75
      sim_grid_pos_y: 52570.4844
    }
    terrain_level_point {
      sim_grid_pos_x: 2052783.88
      sim_grid_pos_y: 52935.4062
    }
    terrain_level_point {
      sim_grid_pos_x: 2052073.75
      sim_grid_pos_y: 52989.4961
    }
    terrain_level_point {
      sim_grid_pos_x: 2051520.62
      sim_grid_pos_y: 52985.2656
    }
    terrain_level_point {
      sim_grid_pos_x: 2050930.75
      sim_grid_pos_y: 53863.0547
    }
    terrain_level_point {
      sim_grid_pos_x: 2052991.75
      sim_grid_pos_y: 55476.8047
    }
    terrain_level_point {
      sim_grid_pos_x: 2055572.12
      sim_grid_pos_y: 53306.7852
    }
    terrain_level_point {
      sim_grid_pos_x: 2055757.38
      sim_grid_pos_y: 51951.7852
    }
    terrain_level_point {
      sim_grid_pos_x: 2056213.38
      sim_grid_pos_y: 51715.4844
    }
    terrain_level_point {
      sim_grid_pos_x: 2057205.25
      sim_grid_pos_y: 49404.5234
    }
    terrain_level_point {
      sim_grid_pos_x: 2.05897e+06
      sim_grid_pos_y: 47280.9453
    }
    terrain_level_point {
      sim_grid_pos_x: 2062175.88
      sim_grid_pos_y: 44984.9141
    }
    terrain_level_point {
      sim_grid_pos_x: 2064235.88
      sim_grid_pos_y: 42704.7539
    }
    terrain_level_point {
      sim_grid_pos_x: 2064179.75
      sim_grid_pos_y: 42592.1562
    }
    terrain_level_point {
      sim_grid_pos_x: 2063104.25
      sim_grid_pos_y: 42686.2344
    }
    terrain_level_point {
      sim_grid_pos_x: 2062798.5
      sim_grid_pos_y: 40647.2852
    }
    terrain_level_point {
      sim_grid_pos_x: 2061254.75
      sim_grid_pos_y: 40737.6445
    }
  }
}
