terrain_level_data {
  terrain_level: 714
  terrain_level_polygon {
    terrain_leveling_percentage: 100
    terrain_level_point {
      sim_grid_pos_x: 2079148.88
      sim_grid_pos_y: 1356091.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2079097.5
      sim_grid_pos_y: 1356514.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2079012.5
      sim_grid_pos_y: 1356771.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2079333.88
      sim_grid_pos_y: 1356819.5
    }
    terrain_level_point {
      sim_grid_pos_x: 2079557.75
      sim_grid_pos_y: 1356463.62
    }
    terrain_level_point {
      sim_grid_pos_x: 2079608.62
      sim_grid_pos_y: 1356043.38
    }
    terrain_level_point {
      sim_grid_pos_x: 2079576.75
      sim_grid_pos_y: 1355685.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2079345.25
      sim_grid_pos_y: 1355694.75
    }
  }
  terrain_level_polygon {
    terrain_leveling_percentage: 50
    terrain_level_point {
      sim_grid_pos_x: 2079623.5
      sim_grid_pos_y: 1355632
    }
    terrain_level_point {
      sim_grid_pos_x: 2079312.75
      sim_grid_pos_y: 1355644.88
    }
    terrain_level_point {
      sim_grid_pos_x: 2079099
      sim_grid_pos_y: 1356077
    }
    terrain_level_point {
      sim_grid_pos_x: 2079047.25
      sim_grid_pos_y: 1356503
    }
    terrain_level_point {
      sim_grid_pos_x: 2078944.75
      sim_grid_pos_y: 1356813.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2079359.5
      sim_grid_pos_y: 1356875.12
    }
    terrain_level_point {
      sim_grid_pos_x: 2079607.25
      sim_grid_pos_y: 1356481.25
    }
    terrain_level_point {
      sim_grid_pos_x: 2079660.12
      sim_grid_pos_y: 1356044.25
    }
  }
}
